import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_151)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // count-4/3 cleanup (問わ 肌 乗る 層 探す おっしゃる)
  C('conv_03001',
    'Mei and Aoi chat about choosing skincare.',
    'Casual register; vocabulary (問わ/肌/乗る/層/探す) in natural home.',
    'cafe_quiet_chatter',
    ['問わ', '肌', '乗る', '層', '探す'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '自分に合う、肌のケアを探してるの。', en: "I'm looking for skincare that suits me.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'aoi_barista', jp: '肌は、人それぞれ違うもんね。', en: "Skin differs from person to person.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '年齢を問わず、合うものがいいな。', en: "I'd like something that suits regardless of age.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '流行に乗って、選ぶのもありだよ。', en: "Going with the trend to choose is an option too.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '肌に、薄い層を作るタイプがいいの。', en: "I like the type that forms a thin layer on the skin.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '店員さんが、何ておっしゃってた?', en: "What did the shop staff say?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '優しいタイプを、勧めるとおっしゃってた。', en: "They said they'd recommend a gentle type.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '一緒に、いいの探そうよ!', en: "Let's look for a good one together!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  // count-2 academic cluster (働い 無視 かける 学会 超える) ×3
  C('conv_03002',
    'Ren interviews a researcher about long hours.',
    'WIDENED SCENARIO: academic interview; vocabulary (働い/無視/かける/学会/超える) in natural home.',
    'office_quiet_low',
    ['働い', '無視', 'かける', '学会', '超える'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '研究に、長く働いていらっしゃいますね。', en: "You've worked long on your research.", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: '気づけば、十年を超えて働いています。', en: "Before I knew it, I've worked over ten years.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '学会では、発表もされますか?', en: "Do you present at conferences too?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '毎年、学会に時間をかけています。', en: "Each year, I devote time to the conference.", style: 'patient researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '批判を、無視することもありますか?', en: "Do you ever ignore criticism?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '批判は、無視せず受け止めます。', en: "I don't ignore criticism; I take it in.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '限界を超える瞬間も、ありますか?', en: "Are there moments you surpass your limits?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '想像を超える発見に、時間をかけます。', en: "I devote time to discoveries beyond imagination.", style: 'warm researcher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_03003',
    'Hiroshi-boss and Yuki discuss overwork.',
    'WIDENED SCENARIO: business HR; vocabulary (働い/無視/かける/学会/超える) in natural home.',
    'office_quiet_low',
    ['働い', '無視', 'かける', '学会', '超える'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '皆、働きすぎていないかね?', en: "Isn't everyone overworking?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '残業が、規定を超えています。', en: "Overtime exceeds the limit.", style: 'concerned office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '健康を、無視するわけにはいかない。', en: "We can't ignore their health.", style: 'firm boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '改善に、力をかけたいですね。', en: "I want to put effort into improving it.", style: 'earnest office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '長く働いてくれる人を、守りたい。', en: "I want to protect those who work long for us.", style: 'warm boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '専門家の学会の話も、参考になります。', en: "Talks from experts' conferences help as reference.", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '時間をかけて、仕組みを変えよう。', en: "Let's take time and change the system.", style: 'composed boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '声を無視せず、進めますね。', en: "I'll proceed without ignoring the voices.", style: 'resolved office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_03004',
    'Ren and Asuka discuss balancing work and study.',
    'WIDENED SCENARIO: academic chat; vocabulary (働い/無視/かける/学会/超える) in natural home.',
    'lecture_hall_quiet',
    ['働い', '無視', 'かける', '学会', '超える'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '働きながら、学べるか不安です。', en: "I'm anxious about studying while working.", style: 'troubled young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '働いて学ぶ人は、たくさんいますよ。', en: "Many people study while working.", style: 'composed teacher voice, soft warm measured encouraging clarity throughout' },
      { speaker: 'ren_uni', jp: '学会に、参加してもいいですか?', en: "May I attend the conference too?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ぜひ、学会に時間をかけて下さい。', en: "Please devote time to the conference.", style: 'patient teacher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '不安を、無視できないんです。', en: "I can't ignore my anxiety.", style: 'honest young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '不安を無視せず、向き合いましょう。', en: "Let's face the anxiety rather than ignore it.", style: 'composed teacher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '自分を、超えられる気がしてきました。', en: "I'm starting to feel I can surpass myself.", style: 'motivated young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '働いた経験が、学びを超えて活きますよ。', en: "Work experience enriches learning beyond measure.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  // count-1 cluster A — manufacturing/business (製造 削減 賃金 取得 マーケティング)
  C('conv_03005',
    'Hiroshi-boss and Ren review the factory budget.',
    'WIDENED SCENARIO: business strategy; vocabulary (製造/削減/賃金/取得/マーケティング) in natural home.',
    'office_quiet_low',
    ['製造', '削減', '賃金', '取得', 'マーケティング'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '製造のコストを、下げたいんだ。', en: "I want to lower manufacturing costs.", style: 'composed boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '無駄を削減すれば、可能です。', en: "If we cut waste, it's possible.", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '賃金は、削減したくないな。', en: "I don't want to cut wages, though.", style: 'firm boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '賃金は守り、別を削減しましょう。', en: "Let's protect wages and cut elsewhere.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '新しい設備の取得は、どうかね?', en: "What about acquiring new equipment?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '取得すれば、製造が速くなります。', en: "Acquiring it speeds up manufacturing.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'マーケティングも、強化したいな。', en: "I want to strengthen marketing too.", style: 'measured boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: 'マーケティングで、製造の良さを伝えます。', en: "Through marketing, we'll convey our manufacturing quality.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_03006',
    'Sakura interviews a factory manager.',
    'WIDENED SCENARIO: business interview; vocabulary (製造/削減/賃金/取得/マーケティング) in natural home.',
    'office_quiet_low',
    ['製造', '削減', '賃金', '取得', 'マーケティング'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '製造の現場は、今どうですか?', en: "How is the manufacturing floor now?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '無駄を削減し、効率を上げています。', en: "We cut waste and raise efficiency.", style: 'measured manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '賃金は、守られていますか?', en: "Are wages protected?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '削減しても、賃金は下げません。', en: "Even cutting costs, we don't lower wages.", style: 'firm manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '新しい資格の取得も、支援しますか?', en: "Do you support acquiring new qualifications too?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '取得を、会社が支援しています。', en: "The company supports acquisition.", style: 'measured manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: 'マーケティングは、どうしていますか?', en: "How do you handle marketing?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'マーケティングで、製品の良さを広げます。', en: "Through marketing, we spread our product's quality.", style: 'warm manager voice, soft warm informative closing clarity throughout' },
    ]),

  C('conv_03007',
    'Ren reports a marketing plan to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (製造/削減/賃金/取得/マーケティング) in natural home.',
    'office_quiet_low',
    ['製造', '削減', '賃金', '取得', 'マーケティング'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'マーケティングの新案を、まとめました。', en: "I compiled a new marketing proposal.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '費用は、削減できているかね?', en: "Are costs reduced?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '広告費を、二割削減しました。', en: "I cut ad costs by twenty percent.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '製造との連携は、取れているかね?', en: "Is coordination with manufacturing in place?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '製造部門と、データを取得しました。', en: "I acquired data with the manufacturing division.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '賃金への影響は、ないかね?', en: "Is there no impact on wages?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '賃金は、影響なく進められます。', en: "Wages can stay unaffected as we proceed.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'マーケティングで、攻めていこう。', en: "Let's go on the offensive with marketing.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_03008',
    'Kenji and Ren build a marketing data tool.',
    'WIDENED SCENARIO: tech/business; vocabulary (製造/削減/賃金/取得/マーケティング) in natural home.',
    'office_quiet_low',
    ['製造', '削減', '賃金', '取得', 'マーケティング'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'マーケティングのデータを、集めたいんです。', en: "I want to gather marketing data.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '製造の記録も、取得できますよ。', en: "We can acquire manufacturing records too.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '取得したデータで、無駄を削減できますか?', en: "Can we cut waste with the acquired data?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、削減すべき箇所が見えます。', en: "Yes, the spots to cut become visible.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '賃金のデータも、扱うんですか?', en: "Do we handle wage data too?", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '賃金は、別に安全に管理します。', en: "Wages are managed separately and securely.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'マーケティングと製造が、つながりますね。', en: "Marketing and manufacturing connect.", style: 'satisfied young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'データ取得で、判断が速くなりますよ。', en: "With data acquisition, decisions get faster.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // count-1 cluster B — Christmas/travel (クリスマス ツアー パリ 牛 そば)
  C('conv_03009',
    'Daichi and Mei plan a Christmas trip to Paris.',
    'WIDENED SCENARIO: travel chat; vocabulary (クリスマス/ツアー/パリ/牛/そば) in natural home.',
    'cafe_quiet_chatter',
    ['クリスマス', 'ツアー', 'パリ', '牛', 'そば'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'クリスマスに、パリへ行きたいなあ。', en: "I'd love to go to Paris at Christmas.", style: 'lively Kansai man voice, warm hearty dreamy delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ツアーなら、安く行けますよね。', en: "On a tour, we could go cheaply, right.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'パリのツアー、調べてみよか。', en: "Let's look into a Paris tour.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'パリの牛料理、おいしいらしいですよ。', en: "Paris's beef dishes are apparently delicious.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '牛のステーキ、食べたいなあ。', en: "I want to eat a beef steak.", style: 'enthusiastic Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ホテルは、駅のそばがいいですね。', en: "A hotel near the station would be nice.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'そや、駅のそばやと便利やな。', en: "Right, near the station is convenient.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'クリスマスのパリ、楽しみですね!', en: "Paris at Christmas — I'm excited!", style: 'bright woman voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03010',
    'Riku and Aoi talk about a Christmas tour.',
    'Casual register; vocabulary (クリスマス/ツアー/パリ/牛/そば) in natural home.',
    'cafe_quiet_chatter',
    ['クリスマス', 'ツアー', 'パリ', '牛', 'そば'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'クリスマスに、家族でツアー行くんだ!', en: "At Christmas, my family's going on a tour!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、どこのツアー?', en: "Nice, a tour of where?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'パリを回るツアーなんだ!', en: "A tour around Paris!", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'パリで、何が食べたい?', en: "What do you want to eat in Paris?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '本場の牛料理、食べてみたい!', en: "I want to try authentic beef dishes!", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '私は、日本のそばが恋しくなりそう。', en: "I'd probably miss Japanese soba.", style: 'giggly barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'ホテルが、観光地のそばらしいよ。', en: "The hotel's apparently near the sights.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'クリスマスのパリ、写真見せてね!', en: "Show me photos of Paris at Christmas!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03011',
    'Mei and Ren reminisce about a Paris tour.',
    'Casual register; vocabulary (クリスマス/ツアー/パリ/牛/そば) in natural home.',
    'cafe_quiet_chatter',
    ['クリスマス', 'ツアー', 'パリ', '牛', 'そば'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '去年のパリ旅行、楽しかったね。', en: "Last year's Paris trip was fun.", style: 'soft warm woman voice, gentle nostalgic delivery throughout' },
      { speaker: 'ren_uni', jp: 'うん、クリスマスの街が綺麗だったね。', en: "Yeah, the Christmas streets were beautiful.", style: 'warm young man voice, soft warm reflective delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ツアーで、たくさん回れたよね。', en: "On the tour, we saw a lot.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'あの牛料理の店、また行きたいな。', en: "I want to revisit that beef restaurant.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '宿が、川のそばで素敵だったね。', en: "The inn was lovely, near the river.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'パリのツアー、また計画しようよ。', en: "Let's plan a Paris tour again.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '次のクリスマスも、一緒にね。', en: "Next Christmas too, together.", style: 'gentle woman voice, soft warm tender delivery throughout' },
      { speaker: 'ren_uni', jp: '牛料理も、そばの宿も、また楽しもう。', en: "Let's enjoy the beef and the riverside inn again.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_03012',
    'Sakura interviews a travel guide about Paris tours.',
    'WIDENED SCENARIO: travel interview; vocabulary (クリスマス/ツアー/パリ/牛/そば) in natural home.',
    'office_quiet_low',
    ['クリスマス', 'ツアー', 'パリ', '牛', 'そば'],
    ['sakura_teen', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '冬のパリツアーは、人気ですか?', en: "Are winter Paris tours popular?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'daichi_kansai', jp: 'クリスマスの時期は、特に人気やで。', en: "The Christmas season is especially popular.", style: 'lively Kansai guide voice, warm hearty delivery throughout' },
      { speaker: 'sakura_teen', jp: 'ツアーでは、何を案内しますか?', en: "What do you show on the tour?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: 'パリの名所を、ぐるっと回るで。', en: "We go all around Paris's landmarks.", style: 'cheerful Kansai guide voice, warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '食事は、どんなものが出ますか?', en: "What kind of meals are served?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '本場の牛料理を、味わってもらうで。', en: "We have guests savor authentic beef dishes.", style: 'enthusiastic Kansai guide voice, warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '宿は、観光地のそばですか?', en: "Is the lodging near the sights?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '名所のそばに、泊まってもらうで。', en: "We have guests stay near the landmarks.", style: 'warm Kansai guide voice, warm hearty closing delivery throughout' },
    ]),

  // count-1 cluster C — academia/medicine (大学院 医学 書籍 経過 筆者)
  C('conv_03013',
    'Sakura interviews a medical author.',
    'WIDENED SCENARIO: academic interview; vocabulary (大学院/医学/書籍/経過/筆者) in natural home.',
    'office_quiet_low',
    ['大学院', '医学', '書籍', '経過', '筆者'],
    ['sakura_teen', 'saito_doctor'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '先生は、大学院で学ばれたんですね。', en: "You studied at graduate school, doctor.", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'saito_doctor', jp: 'ええ、大学院で医学を専攻しました。', en: "Yes, I majored in medicine in grad school.", style: 'calm doctor voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '医学の書籍も、書かれたんですか?', en: "Did you write medical books too?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'saito_doctor', jp: '筆者として、数冊出しました。', en: "As an author, I published several.", style: 'gentle doctor voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '患者さんの経過も、書籍に?', en: "Did patients' progress go into the books too?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'saito_doctor', jp: '経過の記録を、丁寧に載せました。', en: "I carefully included progress records.", style: 'calm doctor voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '筆者として、伝えたいことは?', en: "As an author, what do you want to convey?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'saito_doctor', jp: '医学は、人のためにあると伝えたいです。', en: "I want to convey that medicine exists for people.", style: 'warm doctor voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_03014',
    'Ren asks Asuka about graduate school.',
    'WIDENED SCENARIO: career chat; vocabulary (大学院/医学/書籍/経過/筆者) in natural home.',
    'lecture_hall_quiet',
    ['大学院', '医学', '書籍', '経過', '筆者'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '大学院に、進もうか迷っています。', en: "I'm torn about going to grad school.", style: 'troubled young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '大学院は、深く学べる場ですよ。', en: "Grad school is a place to study deeply.", style: 'composed teacher voice, soft warm measured encouraging clarity throughout' },
      { speaker: 'ren_uni', jp: '専門の書籍は、難しいですか?', en: "Are specialized books difficult?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '難しい書籍も、経過とともに読めます。', en: "Hard books become readable over time.", style: 'patient teacher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '医学とは、別の分野でもいいですか?', en: "Can it be a field other than medicine?", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '医学に限らず、好きな道を選べます。', en: "Not just medicine — you can choose any path you love.", style: 'composed teacher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: 'いつか、書籍の筆者になりたいです。', en: "Someday I want to be a book's author.", style: 'hopeful young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '筆者になる夢、応援しますよ。', en: "I'll support your dream to become an author.", style: 'warm teacher voice, soft warm encouraging closing clarity throughout' },
    ]),

  C('conv_03015',
    'Mei and Asuka discuss a medical book.',
    'Casual register; vocabulary (大学院/医学/書籍/経過/筆者) in natural home.',
    'living_room_quiet',
    ['大学院', '医学', '書籍', '経過', '筆者'],
    ['mei_romantic', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この医学の書籍、分かりやすいですね。', en: "This medical book is easy to understand.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: '筆者が、大学院で長く研究した方です。', en: "The author researched long in grad school.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '病気の経過も、丁寧に書かれていますね。', en: "The course of illness is carefully written too.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '経過を、図で示しているのが良いですね。', en: "It's good that progress is shown in diagrams.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '医学って、奥が深いですね。', en: "Medicine is profound.", style: 'thoughtful woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '筆者の情熱が、書籍に表れています。', en: "The author's passion shows in the book.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '大学院での苦労が、伝わりますね。', en: "Their grad-school struggles come through.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '良い書籍は、経過を越えて残りますね。', en: "A good book endures beyond the passage of time.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_03016',
    'Saito explains a recovery course to a patient.',
    'WIDENED SCENARIO: medical explanation; vocabulary (大学院/医学/書籍/経過/筆者) in natural home.',
    'clinic_room_quiet',
    ['大学院', '医学', '書籍', '経過', '筆者'],
    ['saito_doctor', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '先生、回復の経過は順調ですか?', en: "Doctor, is my recovery progressing well?", style: 'concerned office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: 'ええ、経過はとても良好です。', en: "Yes, your progress is very good.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: '医学では、よくあることですか?', en: "Is this common in medicine?", style: 'curious office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '医学的に、典型的な経過です。', en: "Medically, it's a typical course.", style: 'clear doctor voice, soft warm measured clarity throughout' },
      { speaker: 'kenji_office', jp: '何か、読める書籍はありますか?', en: "Is there a book I can read?", style: 'attentive office man voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: 'やさしい書籍を、お貸ししますよ。', en: "I'll lend you an accessible book.", style: 'gentle doctor voice, soft warm measured clarity throughout' },
      { speaker: 'kenji_office', jp: '筆者は、お医者さんですか?', en: "Is the author a doctor?", style: 'curious office man voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: 'ええ、大学院で学んだ筆者の本です。', en: "Yes, it's by an author who trained in grad school.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),

  // count-1 cluster D — society/abstract (世の中 性格 実感 依存 根本)
  C('conv_03017',
    'Asuka lectures on human dependence and society.',
    'WIDENED SCENARIO: sociology lecture; vocabulary (世の中/性格/実感/依存/根本) in natural home.',
    'lecture_hall_quiet',
    ['世の中', '性格', '実感', '依存', '根本'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '世の中は、互いに依存して成り立ちます。', en: "Society works by mutual dependence.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '依存は、悪いことなんですか?', en: "Is dependence a bad thing?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '根本では、支え合いでもあります。', en: "At its root, it's also mutual support.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '人の性格も、関係しますか?', en: "Does a person's character relate to it?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、性格が、関わり方を左右します。', en: "Yes, character shapes how we relate.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '頭では分かっても、実感が難しいです。', en: "I understand it in my head, but feeling it is hard.", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '日々の中で、実感は深まります。', en: "In daily life, that sense deepens.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '世の中の根本が、見えた気がします。', en: "I feel I glimpsed society's root.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_03018',
    'Ren and Mei reflect on a documentary about society.',
    'Casual register; vocabulary (世の中/性格/実感/依存/根本) in natural home.',
    'cafe_quiet_chatter',
    ['世の中', '性格', '実感', '依存', '根本'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの番組、世の中の仕組みを描いてたね。', en: "That program depicted how society works.", style: 'soft warm woman voice, gentle reflective delivery throughout' },
      { speaker: 'ren_uni', jp: 'うん、技術への依存が、テーマだったね。', en: "Yeah, dependence on technology was the theme.", style: 'warm young man voice, soft warm reflective delivery throughout' },
      { speaker: 'mei_romantic', jp: '便利さに、すっかり依存してるよね。', en: "We're completely dependent on convenience.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '根本から、考え直す必要があるね。', en: "We need to rethink it from the root.", style: 'thoughtful young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '人の性格も、変わってきた気がする。', en: "I feel people's character has changed too.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '見て初めて、実感が湧いたよ。', en: "Only after watching did it feel real.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '世の中を、自分の目で見たいね。', en: "I want to see society with my own eyes.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '根本の問いを、忘れないようにね。', en: "Let's not forget the fundamental question.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_03019',
    'Saito advises Yuki on stress and reliance.',
    'WIDENED SCENARIO: medical advice; vocabulary (世の中/性格/実感/依存/根本) in natural home.',
    'clinic_room_quiet',
    ['世の中', '性格', '実感', '依存', '根本'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '最近、疲れが取れないんです。', en: "Lately I can't shake my fatigue.", style: 'tired office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '根本の原因は、休息不足ですね。', en: "The root cause is lack of rest.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: 'カフェインに、依存してるかもしれません。', en: "I might be dependent on caffeine.", style: 'honest office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '依存を、少しずつ減らしましょう。', en: "Let's reduce the dependence little by little.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: '頑張りすぎる性格なんです。', en: "I have a character that overworks.", style: 'reflective office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '性格は、無理に変えなくていいですよ。', en: "You don't have to force your character to change.", style: 'warm doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: '休む大切さを、実感しました。', en: "I realized the importance of rest.", style: 'understanding office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '世の中、急がば回れ、ですよ。', en: "In this world, slow and steady wins.", style: 'gentle doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_03020',
    'Ren interviews a sociologist.',
    'WIDENED SCENARIO: expert interview; vocabulary (世の中/性格/実感/依存/根本) in natural home.',
    'office_quiet_low',
    ['世の中', '性格', '実感', '依存', '根本'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '世の中の変化を、研究されていますね。', en: "You research changes in society.", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、人の依存の仕方に注目しています。', en: "Yes, I focus on how people depend on things.", style: 'composed sociologist voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '依存は、性格にもよりますか?', en: "Does dependence depend on character too?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '性格も、根本の要因の一つです。', en: "Character is one fundamental factor.", style: 'patient sociologist voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '研究で、実感が変わりましたか?', en: "Did your research change how you feel about it?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '世の中の優しさを、実感しました。', en: "I came to feel society's kindness.", style: 'composed sociologist voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '根本の問題は、解けますか?', en: "Can the fundamental problem be solved?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '根本を見つめ続けることが、答えです。', en: "Keeping our eyes on the root is the answer.", style: 'warm sociologist voice, soft warm measured closing clarity throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_151 wrote', CONVERSATIONS.length, 'files');
