import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_143)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // N4 finish (いれ hiragana, いただく dictionary) + 取る 一言
  C('conv_02841',
    'Mei makes tea and thanks Aoi for help.',
    'Casual register; vocabulary (いれ/いただく/取る/一言) in natural home.',
    'cafe_quiet_chatter',
    ['いれ', 'いただく', '取る', '一言'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '温かいお茶を、いれますね。', en: "I'll make some hot tea.", style: 'soft warm woman voice, gentle caring delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ありがとう。棚からカップ、取ろうか?', en: "Thanks. Shall I take cups from the shelf?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '手伝っていただくと、助かるな。', en: "It helps to have you assist.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '上の棚から、取っておいたよ。', en: "I took them from the top shelf.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'コーヒーも、いれましょうか?', en: "Shall I make coffee too?", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'お願い。手伝っていただけて、嬉しいな。', en: "Please. I'm glad to have your help.", style: 'warm barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '一言、お礼を言わせてね。', en: "Let me say a word of thanks.", style: 'gentle woman voice, soft warm sincere delivery throughout' },
      { speaker: 'aoi_barista', jp: 'こちらこそ。一言で言えば、最高の相棒だよ!', en: "Likewise. In a word, you're the best partner!", style: 'bubbly barista voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-4/3 cleanup (人事 学部 アンケート 載っ 語っ 乗る)
  C('conv_02842',
    'Hiroshi-boss and Ren review a staffing survey.',
    'WIDENED SCENARIO: business HR; vocabulary (人事/学部/アンケート/載っ/語っ) in natural home.',
    'office_quiet_low',
    ['人事', '学部', 'アンケート', '載っ', '語っ'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '人事のアンケートは、まとまったかね?', en: "Is the HR survey compiled?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'はい、結果が資料に載っています。', en: "Yes, the results are in the document.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '若手は、どんな学部の出身かね?', en: "What faculties are the young staff from?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '技術系の学部が、多いです。', en: "Many are from engineering faculties.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'アンケートで、何か語っていたかね?', en: "Did they say anything in the survey?", style: 'engaged boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '多くが、成長したいと語っていました。', en: "Many said they want to grow.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '人事の方針に、載せておこう。', en: "Let's put it in the HR policy.", style: 'decisive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '社員の声を、しっかり載せます。', en: "I'll firmly include the employees' voices.", style: 'resolved young presenter voice, soft warm closing throughout' },
    ]),

  // CLUSTER A — daily/casual (まるで 多分 やや おかしい さっき)
  C('conv_02843',
    'Mei and Aoi laugh about a strange morning.',
    'Casual register; vocabulary (まるで/多分/やや/おかしい/さっき) in natural home.',
    'cafe_quiet_chatter',
    ['まるで', '多分', 'やや', 'おかしい', 'さっき'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'さっき、変な夢の話、聞いてよ。', en: "Listen to my weird dream from earlier.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、どんな夢?おかしいの?', en: "Sure, what dream? Is it funny?", style: 'soft warm woman voice, gentle curious delivery throughout' },
      { speaker: 'aoi_barista', jp: 'まるで、空を飛んでるみたいだったの。', en: "It was just like flying in the sky.", style: 'animated barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'それは、多分疲れてるんだよ。', en: "That's probably because you're tired.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'やや、寝不足かもしれないね。', en: "I might be slightly short on sleep.", style: 'thoughtful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'さっきも、あくびしてたもんね。', en: "You were yawning earlier too.", style: 'amused woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'まるで子供みたいで、おかしいでしょ?', en: "Just like a kid — funny, right?", style: 'giggly barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '多分、今夜は早く寝た方がいいよ。', en: "You should probably sleep early tonight.", style: 'gentle woman voice, soft warm caring closing delivery throughout' },
    ]),

  C('conv_02844',
    'Ren and Mei puzzle over an odd message.',
    'Casual register; vocabulary (まるで/多分/やや/おかしい/さっき) in natural home.',
    'cafe_quiet_chatter',
    ['まるで', '多分', 'やや', 'おかしい', 'さっき'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'さっき、変なメッセージが来たの。', en: "I got a strange message earlier.", style: 'soft warm woman voice, gentle puzzled delivery throughout' },
      { speaker: 'ren_uni', jp: 'おかしいね。誰からだろう?', en: "That's odd. Who's it from?", style: 'curious young man voice, soft warm engaged delivery throughout' },
      { speaker: 'mei_romantic', jp: 'まるで、暗号みたいな文なの。', en: "It's like a coded message.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '多分、間違って送られたんだよ。', en: "It was probably sent by mistake.", style: 'reassuring young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'やや、気味が悪いけどね。', en: "It's slightly creepy, though.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'さっき、僕にも似たのが来たよ。', en: "I got a similar one earlier too.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'おかしいね。多分、迷惑メールだね。', en: "Weird. It's probably spam.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'まるで気にしないで、消しちゃおう。', en: "Let's just ignore it and delete it.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02845',
    'Riku tells Aoi about an odd class moment.',
    'Casual register; vocabulary (まるで/多分/やや/おかしい/さっき) in natural home.',
    'cafe_quiet_chatter',
    ['まるで', '多分', 'やや', 'おかしい', 'さっき'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'さっき、授業で面白いことあったよ。', en: "Something funny happened in class earlier.", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'へえ、おかしいこと?', en: "Oh, something funny?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '先生が、まるで役者みたいに話したんだ。', en: "The teacher spoke just like an actor.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'それは、多分人気者だね。', en: "That teacher is probably popular.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'やや大げさだけど、楽しかったよ。', en: "A bit over the top, but fun.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'さっきの話、おかしくて笑っちゃった。', en: "Your story just now made me laugh.", style: 'giggly barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '多分、明日も面白い授業だよ。', en: "Tomorrow's class will probably be fun too.", style: 'happy teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'まるで毎日が、ドラマみたいだね!', en: "It's like every day is a drama!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  // CLUSTER B — society/care (保障 介護 普及 要望 規則)
  C('conv_02846',
    'Civic news: Sakura and Ren on elderly care policy.',
    'WIDENED SCENARIO: civic news; vocabulary (保障/介護/普及/要望/規則) in natural home.',
    'studio_room_tone',
    ['保障', '介護', '普及', '要望', '規則'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '介護の制度が、見直されています。', en: "The care system is being reviewed.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '生活の保障は、十分なんですか?', en: "Is the security for daily life sufficient?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '保障を、手厚くする要望が出ています。', en: "There are requests to strengthen the security.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '介護のサービスは、普及していますか?', en: "Are care services widespread?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '地方にも、徐々に普及しています。', en: "They're gradually spreading to rural areas too.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '新しい規則も、定められましたか?', en: "Were new rules set too?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、介護の規則が改められました。', en: "Yes, the care rules were revised.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '現場の要望が、保障に届くといいですね。', en: "I hope field requests reach the security policy.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02847',
    'Sakura interviews a care-service manager.',
    'WIDENED SCENARIO: civic interview; vocabulary (保障/介護/普及/要望/規則) in natural home.',
    'office_quiet_low',
    ['保障', '介護', '普及', '要望', '規則'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '介護の現場は、今どうですか?', en: "How are care worksites now?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '人手不足が、深刻な課題です。', en: "Staff shortage is a serious challenge.", style: 'measured manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '待遇の保障は、進んでいますか?', en: "Is security of conditions improving?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '保障を、手厚くする要望を出しています。', en: "We're requesting stronger security.", style: 'professional manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '新しい機器は、普及しましたか?', en: "Have new devices spread?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '介護機器が、少しずつ普及しています。', en: "Care devices are gradually spreading.", style: 'measured manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '安全の規則も、厳しいんですか?', en: "Are safety rules strict too?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '規則を守り、保障を高めたいですね。', en: "We follow the rules and want to raise security.", style: 'warm manager voice, soft warm informative closing throughout' },
    ]),

  C('conv_02848',
    'Asuka lectures on the welfare system.',
    'WIDENED SCENARIO: civics lecture; vocabulary (保障/介護/普及/要望/規則) in natural home.',
    'lecture_hall_quiet',
    ['保障', '介護', '普及', '要望', '規則'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '社会保障は、皆を支える仕組みです。', en: "Social security is a system that supports everyone.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '介護も、保障に含まれますか?', en: "Is care included in the security too?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、介護も大切な保障の一つです。', en: "Yes, care is one important part of the security.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '制度は、どう普及したんですか?', en: "How did the system spread?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '市民の要望で、普及が進みました。', en: "It spread thanks to citizens' requests.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '規則は、誰が決めるんですか?', en: "Who decides the rules?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '議会が、規則を定めます。', en: "The assembly sets the rules.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '要望を伝えるのも、大切なんですね。', en: "Conveying requests matters too.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  // CLUSTER C — youth/school (若者 留学 成績 書店 出身)
  C('conv_02849',
    'Riku asks Asuka about studying abroad.',
    'WIDENED SCENARIO: school guidance; vocabulary (若者/留学/成績/書店/出身) in natural home.',
    'lecture_hall_quiet',
    ['若者', '留学', '成績', '書店', '出身'],
    ['riku_teen', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '先生、留学に興味があるんです。', en: "Teacher, I'm interested in studying abroad.", style: 'eager teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '若者には、良い経験になりますよ。', en: "It's a good experience for young people.", style: 'composed teacher voice, soft warm measured encouraging clarity throughout' },
      { speaker: 'riku_teen', jp: '成績が、足りるか心配です。', en: "I'm worried my grades aren't enough.", style: 'anxious teen boy voice, soft warm earnest throughout' },
      { speaker: 'asuka_teacher', jp: '成績だけでなく、意欲も見られます。', en: "Not just grades — motivation is assessed too.", style: 'patient teacher voice, soft warm measured encouraging clarity throughout' },
      { speaker: 'riku_teen', jp: '準備の本は、どこにありますか?', en: "Where are the prep books?", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '駅前の書店に、揃っていますよ。', en: "The bookstore by the station has them.", style: 'composed teacher voice, soft warm measured clarity throughout' },
      { speaker: 'riku_teen', jp: '先生は、どこの出身ですか?', en: "Where are you from, teacher?", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '私は南の町の出身です。留学もしました。', en: "I'm from a southern town. I studied abroad too.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02850',
    'Aoi and Riku chat about a friend who studied abroad.',
    'Casual register; vocabulary (若者/留学/成績/書店/出身) in natural home.',
    'cafe_quiet_chatter',
    ['若者', '留学', '成績', '書店', '出身'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '友達が、留学から帰ってきたよ。', en: "My friend came back from studying abroad.", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'へえ、どこの出身の子?', en: "Oh, where's that kid from?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '同じ町の出身で、成績も優秀なんだ。', en: "From my town, and great grades too.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '若者が、世界を見るのはいいね。', en: "It's good for youth to see the world.", style: 'warm barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '留学先の本を、書店で探したよ。', en: "I looked for books from where they studied at the bookstore.", style: 'engaged teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '書店で、留学のコーナーあるの?', en: "Does the bookstore have a study-abroad section?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、若者向けの本が多かったよ。', en: "Yeah, lots of books for young people.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '成績を上げて、あなたも留学しなよ!', en: "Raise your grades and study abroad too!", style: 'bubbly barista voice, soft warm encouraging closing delivery throughout' },
    ]),

  C('conv_02851',
    'Sakura interviews a young returnee.',
    'WIDENED SCENARIO: youth interview; vocabulary (若者/留学/成績/書店/出身) in natural home.',
    'office_quiet_low',
    ['若者', '留学', '成績', '書店', '出身'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '留学を決めた理由は、何でしたか?', en: "What made you decide to study abroad?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: '若者のうちに、世界を見たかったんです。', en: "I wanted to see the world while young.", style: 'warm young man voice, soft warm sincere delivery throughout' },
      { speaker: 'sakura_teen', jp: 'ご出身は、どちらですか?', en: "Where are you from?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '北の町の出身です。本が好きでした。', en: "I'm from a northern town. I loved books.", style: 'gentle young man voice, soft warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '成績は、苦労しましたか?', en: "Did you struggle with grades?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '成績より、伝える力に苦労しました。', en: "More than grades, I struggled to express myself.", style: 'honest young man voice, soft warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '若者に、伝えたいことは?', en: "What do you want to tell young people?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '書店で一冊、世界の本を開いてみて、と。', en: "Open one book about the world at a bookstore.", style: 'warm young man voice, soft warm sincere closing delivery throughout' },
    ]),

  // CLUSTER D — lecture (示す 単純 意図 比較的 限界)
  C('conv_02852',
    'Asuka lectures on clear argument.',
    'WIDENED SCENARIO: writing lecture; vocabulary (示す/単純/意図/比較的/限界) in natural home.',
    'lecture_hall_quiet',
    ['示す', '単純', '意図', '比較的', '限界'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '良い文章は、意図を明確に示します。', en: "Good writing clearly shows its intent.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '単純な文の方が、いいんですか?', en: "Are simpler sentences better?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '単純さは、比較的伝わりやすいです。', en: "Simplicity is relatively easy to convey.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '単純すぎると、限界がありますか?', en: "Is there a limit if it's too simple?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、単純さにも限界があります。', en: "Yes, simplicity has its limits too.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '意図は、どう示せばいいですか?', en: "How should I show the intent?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '比較的早く、結論で意図を示します。', en: "Show the intent relatively early, in the conclusion.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '限界を知って、工夫するんですね。', en: "We know the limits and get creative.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_02853',
    'Ren and Asuka discuss data presentation.',
    'WIDENED SCENARIO: research discussion; vocabulary (示す/単純/意図/比較的/限界) in natural home.',
    'lecture_hall_quiet',
    ['示す', '単純', '意図', '比較的', '限界'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'このデータ、どう示せばいいですか?', en: "How should I present this data?", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '単純なグラフで、示すといいですよ。', en: "Show it with a simple graph.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '比較的、分かりやすくなりますか?', en: "Does it become relatively clear?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、比較的、誤解が減ります。', en: "Yes, relatively, misunderstanding decreases.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'グラフの限界も、ありますか?', en: "Do graphs have limits too?", style: 'thoughtful young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '限界があるので、言葉も添えましょう。', en: "There are limits, so add words too.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '意図を、はっきり示したいです。', en: "I want to clearly show my intent.", style: 'resolved young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '単純に、意図を示すのが一番ですね。', en: "Showing intent simply is best.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02854',
    'Kenji and Ren refine a chart\'s message.',
    'WIDENED SCENARIO: tech/work; vocabulary (示す/単純/意図/比較的/限界) in natural home.',
    'office_quiet_low',
    ['示す', '単純', '意図', '比較的', '限界'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この図、意図が伝わりますか?', en: "Does this chart convey the intent?", style: 'engaged young colleague voice, soft warm focused throughout' },
      { speaker: 'kenji_office', jp: 'もう少し単純にすると、伝わりますよ。', en: "A bit simpler, and it'll get across.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '色が多いのが、限界ですかね?', en: "Is having too many colors the limit?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '比較的、少ない色の方が示しやすいです。', en: "Relatively fewer colors are easier to show with.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '単純化の限界も、ありそうですね。', en: "There seems to be a limit to simplification too.", style: 'thoughtful young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '意図を、一目で示すのが理想です。', en: "Showing intent at a glance is ideal.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '比較的、見やすくなりました。', en: "It got relatively easier to read.", style: 'satisfied young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '単純で、意図がはっきり示せましたね。', en: "Simple, and the intent is clearly shown.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // CLUSTER E — objects/place (テーブル ボタン タクシー 城 シーズン)
  C('conv_02855',
    'Daichi and Mei plan a castle visit in season.',
    'WIDENED SCENARIO: travel chat; vocabulary (テーブル/ボタン/タクシー/城/シーズン) in natural home.',
    'cafe_quiet_chatter',
    ['テーブル', 'ボタン', 'タクシー', '城', 'シーズン'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '紅葉のシーズンに、城を見に行こか。', en: "Let's visit the castle in autumn-leaf season.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: 'いいですね。城まで、遠いですか?', en: "Sounds nice. Is the castle far?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: '駅から、タクシーで行けるで。', en: "We can take a taxi from the station.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'タクシーの予約は、できますか?', en: "Can we reserve a taxi?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'アプリのボタンを押すだけや。', en: "Just press a button in the app.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'お城のカフェで、お茶したいです。', en: "I'd like tea at the castle cafe.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '窓際のテーブルを、取っとこか。', en: "Let's grab a window-side table.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'シーズンの城、楽しみですね!', en: "The castle in season — I'm excited!", style: 'bright woman voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02856',
    'Kenji helps Yuki with a kiosk machine.',
    'WIDENED SCENARIO: tech help; vocabulary (テーブル/ボタン/タクシー/城/シーズン) in natural home.',
    'office_quiet_low',
    ['テーブル', 'ボタン', 'タクシー', '城', 'シーズン'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'この機械、使い方が分からなくて。', en: "I can't figure out this machine.", style: 'puzzled office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: 'まず、緑のボタンを押して下さい。', en: "First, press the green button.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'ボタンを押したら、画面が出ました。', en: "I pressed the button and a screen appeared.", style: 'relieved office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: '出張の城下町、観光シーズンですね。', en: "The castle town for the trip — it's tourist season.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'シーズンだと、タクシーは混みますか?', en: "In season, are taxis crowded?", style: 'curious office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'タクシーは、ボタン一つで呼べますよ。', en: "You can call a taxi with one button.", style: 'reassuring office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '会議室のテーブルも、予約しますね。', en: "I'll reserve the meeting-room table too.", style: 'reliable office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'シーズン前に、城を見られるといいですね。', en: "I hope you can see the castle before the season.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02857',
    'Riku tells Aoi about a castle trip.',
    'Casual register; vocabulary (テーブル/ボタン/タクシー/城/シーズン) in natural home.',
    'cafe_quiet_chatter',
    ['テーブル', 'ボタン', 'タクシー', '城', 'シーズン'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '家族で、古いお城に行ったよ!', en: "My family went to an old castle!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、シーズンだから混んでた?', en: "Nice, was it crowded since it's the season?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、観光シーズンで人が多かった。', en: "Yeah, lots of people in tourist season.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'どうやって、お城まで行ったの?', en: "How did you get to the castle?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'タクシーで、坂を上ったんだ。', en: "We took a taxi up the slope.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'お城のカフェ、入った?', en: "Did you go into the castle cafe?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '窓際のテーブルで、ジュース飲んだよ。', en: "I drank juice at a window table.", style: 'happy teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'シーズンのお城、写真見せてね!', en: "Show me photos of the castle in season!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  // CLUSTER F — emotion/casual (涙 笑い 弱い 面倒 気づい)
  C('conv_02858',
    'Mei and Aoi talk about a moving film.',
    'Casual register; vocabulary (涙/笑い/弱い/面倒/気づい) in natural home.',
    'cafe_quiet_chatter',
    ['涙', '笑い', '弱い', '面倒', '気づい'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの映画、涙が止まらなかったの。', en: "I couldn't stop crying at that film.", style: 'soft emotional woman voice, gentle tender delivery throughout' },
      { speaker: 'aoi_barista', jp: '私も、笑いと涙で忙しかったよ。', en: "I was busy with laughter and tears too.", style: 'bright barista voice, soft warm warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '主人公が、弱い自分を認める場面ね。', en: "The scene where the lead admits his weakness.", style: 'gentle woman voice, soft warm reflective delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そこで、私も気づいたことがあるの。', en: "There, I realized something too.", style: 'thoughtful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '弱さを見せるの、面倒だけど大事ね。', en: "Showing weakness is a hassle, but important.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '笑いの後の涙が、心に残ったよ。', en: "The tears after the laughter stayed with me.", style: 'warm barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '面倒がらずに、また見たいな。', en: "Without being lazy about it, I want to watch again.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '大事なことに、気づかせてくれたね。', en: "It made us realize something important.", style: 'tender barista voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02859',
    'Ren comforts Mei after a hard day.',
    'Casual register; vocabulary (涙/笑い/弱い/面倒/気づい) in natural home.',
    'living_room_quiet',
    ['涙', '笑い', '弱い', '面倒', '気づい'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '今日は、ちょっと涙が出ちゃった。', en: "Today I shed a few tears.", style: 'soft vulnerable woman voice, gentle delivery throughout' },
      { speaker: 'ren_uni', jp: '弱いところ、見せてくれてありがとう。', en: "Thank you for showing your soft side.", style: 'warm young man voice, soft warm caring delivery throughout' },
      { speaker: 'mei_romantic', jp: '面倒な一日で、疲れちゃったの。', en: "It was a troublesome day; I'm worn out.", style: 'tired woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '無理して笑い続けなくていいよ。', en: "You don't have to keep forcing a smile.", style: 'gentle young man voice, soft warm caring delivery throughout' },
      { speaker: 'mei_romantic', jp: 'あなたといると、気づいたら笑ってる。', en: "With you, I find myself laughing.", style: 'soft warm woman voice, gentle tender delivery throughout' },
      { speaker: 'ren_uni', jp: '涙も笑いも、全部受け止めるよ。', en: "Tears and laughter, I'll accept all of it.", style: 'warm young man voice, soft warm sincere delivery throughout' },
      { speaker: 'mei_romantic', jp: '弱さを見せられて、ほっとした。', en: "I'm relieved I could show my weakness.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '面倒な日こそ、そばにいるからね。', en: "On troublesome days especially, I'm here.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02860',
    'Sho tells Grandma about a funny, sad day.',
    'Casual home register; vocabulary (涙/笑い/弱い/面倒/気づい) in natural home.',
    'tatami_room_quiet',
    ['涙', '笑い', '弱い', '面倒', '気づい'],
    ['sho_child', 'sachiko_grandma'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おばあちゃん、今日転んで泣いちゃった。', en: "Grandma, I fell and cried today.", style: 'pouty small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'あら、涙が出たのね。痛かった?', en: "Oh, you shed tears. Did it hurt?", style: 'tender grandmother voice, soft warm gentle delivery throughout' },
      { speaker: 'sho_child', jp: 'でも、友達の笑い話で元気出たよ。', en: "But my friend's funny story cheered me up.", style: 'brightening small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '泣くのは、弱いことじゃないのよ。', en: "Crying isn't a weakness.", style: 'tender grandmother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '片付けが、面倒だったんだもん。', en: "Cleaning up was such a hassle.", style: 'whiny small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '面倒でも、やり遂げたのね。えらいわ。', en: "Even if it was a hassle, you finished. Good boy.", style: 'gentle grandmother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '笑ったら、涙が乾いたって気づいた!', en: "When I laughed, I noticed my tears dried!", style: 'happy small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '良いことに、気づいたわね。', en: "You noticed something good.", style: 'tender grandmother voice, soft warm affectionate closing delivery throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_143 wrote', CONVERSATIONS.length, 'files');
