import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_103)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02041',
    context: 'Aoi runs through cafe blog comments; Hina helps review.',
    purpose: 'Two women working through online publication feedback.',
    ambient: 'cafe_morning_low',
    sound_effects: [],
    target_vocab: ['ブログ', 'コメント', '投稿', 'ページ', '使っ', '反応', '一般', '読者'],
    cast: ['aoi_barista', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '昨日の投稿、コメント、ようけ来てる。', en: "Yesterday post — comments, many came.", style: 'soft adult woman voice, warm warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: 'ページ、開いて、見てみますね。', en: "Page — open, look.", style: 'bright teen girl voice, soft warm helpful delivery carefully' },
      { speaker: 'aoi_barista', jp: '使っている言葉、皆、温かい。', en: "Used words — all, warm.", style: 'tender adult woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'hina_child', jp: '一般の読者、反応、ええですね。', en: "General readers — reaction, fine.", style: 'gentle teen girl voice, soft warm observant delivery carefully' },
      { speaker: 'aoi_barista', jp: 'こうやって、続けていきたい。', en: "Like this — want continue.", style: 'soft adult woman voice, warm warm committed delivery carefully' },
      { speaker: 'hina_child', jp: '次の投稿、何にしますか?', en: "Next post — what?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: '今度は、店の物語、書こうかな。', en: "Next time — shop story, write.", style: 'warm adult woman voice, soft warm planning delivery carefully' },
    ],
  },
  {
    id: 'conv_02042',
    context: 'Daichi struggles with paperwork at home; Mei helps sort.',
    purpose: 'Couple managing administrative tasks together.',
    ambient: 'kitchen_table_lamp',
    sound_effects: [],
    target_vocab: ['作業', '数字', '間違い', '設定', '機関', '号', '確認', '提出'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、この作業、数字、合わへん。', en: "Mei — this work, numbers, won't match.", style: 'frustrated Kansai husband voice, soft warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '間違い、どこかな?', en: "Error — where?", style: 'gentle young wife voice, soft warm helpful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '設定、変えたんかな?', en: "Settings — changed?", style: 'soft Kansai man voice, warm warm thinking delivery carefully' },
      { speaker: 'mei_romantic', jp: 'この号、機関に提出するんでしょ?', en: "This issue — body submit?", style: 'composed young wife voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、確認、一緒に頼むわ。', en: "Yeah — verify, together ask.", style: 'soft Kansai husband voice, warm warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '落ち着いて、見直そうね。', en: "Calm — re-look.", style: 'tender young wife voice, soft warm patient delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おまえおって、助かるわ。', en: "With you — saved.", style: 'tender Kansai husband voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02043',
    context: 'Naoko plans a Kyoto sightseeing trip with Hiroshi-elder.',
    purpose: 'Aunt and elder organizing travel logistics.',
    ambient: 'ramen_shop_afternoon',
    sound_effects: [],
    target_vocab: ['京都', '観光', '案内', '費用', '計画', '北', '離れ', '日'],
    cast: ['naoko_aunt', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '兄ちゃん、京都、観光行こか!', en: "Brother — Kyoto, sightseeing go!", style: 'brassy Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ええなぁ、案内、何や?', en: "Yeah — fine, guide, what?", style: 'warm elder Kansai voice, soft fond delivery carefully' },
      { speaker: 'naoko_aunt', jp: '神社、お寺、ようけ回るで!', en: "Shrines, temples — many tour!", style: 'animated Kansai aunt voice, bright loud passionate delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '費用、どれくらい、かかるんやろ?', en: "Cost — how much, take?", style: 'gentle elder Kansai voice, soft warm thoughtful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '日帰りやったら、安いで。', en: "Day trip — cheap.", style: 'warm Kansai aunt voice, soft warm practical delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '家、離れるの、久しぶりや。', en: "Home — leave, long time.", style: 'soft elder Kansai voice, warm warm reminiscent delivery carefully' },
      { speaker: 'naoko_aunt', jp: '計画、来週、立てよか!', en: "Plan — next week, make!", style: 'bright Kansai aunt voice, loud cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02044',
    context: 'Kenji shows Sho-young a sports event; cheering on a young athlete.',
    purpose: 'Mentor and child engaged in sports admiration.',
    ambient: 'living_room_tv_sports',
    sound_effects: [],
    target_vocab: ['撮影', '舞台', '負け', 'うまく', '選手', '応援', '反応', '感動'],
    cast: ['kenji_office', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '健司おじちゃん、この選手、すごい!', en: "Kenji-ojichan — this player, amazing!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、撮影、ええ角度や!', en: "Yeah — filming, fine angle!", style: 'warm Kansai mentor voice, soft warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: '負け、悔しいやろな。', en: "Lose — frustrating.", style: 'soft empathetic child boy voice, warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'うまく、立ち直るで、必ず。', en: "Well — recover, surely.", style: 'soft Kansai man voice, warm warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '舞台、こんな大きいんやな。', en: "Stage — this big.", style: 'awed child boy voice, soft warm impressed delivery carefully' },
      { speaker: 'kenji_office', jp: '反応、客席、すごい!', en: "Reaction — audience, amazing!", style: 'animated Kansai man voice, bright warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: '感動、伝わるね!', en: "Moved — conveys!", style: 'soft moved child boy voice, warm warm delivery carefully' },
    ],
  },
  {
    id: 'conv_02045',
    context: 'Saito explains a treatment plan to Asuka; medical detail.',
    purpose: 'Doctor sharing complex case with peer.',
    ambient: 'clinic_room_low',
    sound_effects: [],
    target_vocab: ['治療', '科学', '改革', '医療', '機関', '体系', '提供', '改善'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '新しい治療、科学的根拠、確かです。', en: "New treatment — scientific basis, certain.", style: 'measured doctor voice, soft professional clear delivery carefully' },
      { speaker: 'asuka_teacher', jp: '医療改革、進めばいいですね。', en: "Medical reform — proceeds well, hope.", style: 'gentle teacher voice, soft warm hopeful delivery carefully' },
      { speaker: 'saito_doctor', jp: '関連機関、協力体系、整えたい。', en: "Related agencies — cooperation framework, arrange.", style: 'professional doctor voice, soft warm strategic delivery carefully' },
      { speaker: 'asuka_teacher', jp: '提供できる支援、増やせますか?', en: "Provided support — can increase?", style: 'engaged teacher voice, soft warm probing delivery carefully' },
      { speaker: 'saito_doctor', jp: '改善、少しずつ、進んでいます。', en: "Improvement — bit by bit, advancing.", style: 'soft doctor voice, warm warm content delivery carefully' },
      { speaker: 'asuka_teacher', jp: '貴重な取り組みですね。', en: "Precious effort.", style: 'tender teacher voice, soft warm appreciative delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ありがとうございます、励みになります。', en: "Thanks — encouragement.", style: 'humble doctor voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02046',
    context: 'Sakura researches; encounters a confusing data set with Ren.',
    purpose: 'Two writers parsing technical material together.',
    ambient: 'study_papers_lamp',
    sound_effects: [],
    target_vocab: ['数字', '調査', '事実', '確認', 'まったく', '違っ', '結局', '結果'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、この数字、調査結果、変ね。', en: "Ren — these numbers, survey result, strange.", style: 'soft puzzled adult writer voice, warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '事実、確認した方がいいですね。', en: "Fact — verify better.", style: 'composed young man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まったく、違っているデータ、もうひとつある。', en: "Wholly — differing data, one more exists.", style: 'gentle adult writer voice, soft warm focused delivery carefully' },
      { speaker: 'ren_uni', jp: '結局、どっちが正しいんですか?', en: "After all — which correct?", style: 'curious young man voice, soft warm probing delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に出す前に、もう一回、確認したい。', en: "Article before — once more, verify.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '結果、出たら、教えてください。', en: "Result — come out, tell.", style: 'humble young man voice, soft warm patient delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、丁寧に進めるね。', en: "Yeah — carefully proceed.", style: 'gentle adult writer voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02047',
    context: 'Tatsuya-country reads news about national politics; reflects with Asuka.',
    purpose: 'Older couple discussing civic matters seriously.',
    ambient: 'porch_evening_quiet',
    sound_effects: [],
    target_vocab: ['政府', '国民', '日本人', '改革', '主張', '自身', '我々', '責任'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '政府の改革、また話題やな。', en: "Government reform — again topic.", style: 'slow Tohoku farmer voice, warm reflective delivery carefully' },
      { speaker: 'asuka_teacher', jp: '国民の主張、ちゃんと届くかしら。', en: "National argument — properly reach?", style: 'gentle teacher voice, soft warm thoughtful delivery carefully' },
      { speaker: 'tatsuya_country', jp: '日本人として、考えなあかんな。', en: "Japanese as — must think.", style: 'firm Tohoku voice, soft warm committed delivery carefully' },
      { speaker: 'asuka_teacher', jp: '自身、できることから、ね。', en: "Self — from possible, yeah.", style: 'soft teacher voice, warm warm earnest delivery carefully' },
      { speaker: 'tatsuya_country', jp: '我々、年取ったけど、声、出せる。', en: "We — aged but, voice, can put.", style: 'firm Tohoku farmer voice, soft warm passionate delivery carefully' },
      { speaker: 'asuka_teacher', jp: '若い世代にも、責任、伝えたいね。', en: "Young gen too — responsibility, want convey.", style: 'tender teacher voice, soft warm earnest delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、皆で、未来作ろうな。', en: "Yeah — all, future build.", style: 'warm Tohoku voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02048',
    context: 'Hina-young struggles with a homework problem; calls Ren for help.',
    purpose: 'Teen seeking academic help from young adult mentor.',
    ambient: 'phone_evening_quiet',
    sound_effects: [],
    target_vocab: ['パソコン', '使っ', '設定', 'うまく', 'まったく', '戻る', '違っ', 'おら'],
    cast: ['hina_child', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '蓮くん、パソコン、うまく動かない!', en: "Ren — PC, won't move well!", style: 'frustrated teen girl voice, soft warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: 'まったく動かないんですか?', en: "Wholly won't move?", style: 'gentle young man voice, soft warm helpful delivery carefully' },
      { speaker: 'hina_child', jp: '設定、変えちゃったかも。', en: "Settings — may have changed.", style: 'soft worried teen girl voice, warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '元の設定に、戻ることできますか?', en: "Original settings — can return?", style: 'composed young man voice, soft warm patient delivery carefully' },
      { speaker: 'hina_child', jp: 'やってみる、けど、画面、違っている。', en: "Try — but, screen, differing.", style: 'gentle teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '今、お部屋に、おらんでも、教えられます。', en: "Now — room don't, can teach.", style: 'soft young man voice, warm warm helpful delivery carefully' },
      { speaker: 'hina_child', jp: '助かる、本当に、ありがとう!', en: "Saved — truly, thanks!", style: 'thrilled teen girl voice, bright warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02049',
    context: 'Yumiko and Mrs. Mori discuss international news at tea.',
    purpose: 'Two older women parsing world events.',
    ambient: 'tatami_tea_quiet',
    sound_effects: [],
    target_vocab: ['平和', '外国', '世界', '事件', '報道', 'けれど', 'なんて', '時代'],
    cast: ['yumiko_mom', 'mrs_mori_neighbor'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '外国の事件、報道、毎日来ますね。', en: "Foreign incident — reports, daily come.", style: 'soft older mother voice, warm reflective delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '平和な世界、なんて、難しい時代。', en: "Peaceful world — \"oh\", hard era.", style: 'gentle older neighbor voice, soft warm wistful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'けれど、希望、捨てたくない。', en: "But — hope, don't want abandon.", style: 'tender older mother voice, soft warm committed delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '私たちの世代、ようけ見てきた。', en: "Our gen — much seen.", style: 'warm older woman voice, soft warm reflective delivery carefully' },
      { speaker: 'yumiko_mom', jp: '若い人にも、伝えたいわね。', en: "Young people too — want convey.", style: 'soft older mother voice, warm warm earnest delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'うん、孫たちの未来、祈るしかない。', en: "Yeah — grandkids future, can only pray.", style: 'tender older neighbor voice, soft warm hopeful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'こうやって、話せるの、嬉しい。', en: "Like this — can talk, happy.", style: 'tender older mother voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02050',
    context: 'Aoi takes Hina-young to a job orientation event; observes the work culture.',
    purpose: 'Adult mentor showing teen workplace event.',
    ambient: 'event_hall_low',
    sound_effects: [],
    target_vocab: ['イベント', '開催', '一般', '参加', '反応', '雰囲気', 'なんて', '感想'],
    cast: ['aoi_barista', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'ひな、イベント、ようけ人来てるね。', en: "Hina — event, many people coming.", style: 'soft adult woman voice, warm observant delivery carefully' },
      { speaker: 'hina_child', jp: '開催、地元の方々、たくさん参加してる。', en: "Held — local folks, many participate.", style: 'engaged teen girl voice, soft warm impressed delivery carefully' },
      { speaker: 'aoi_barista', jp: '一般の反応、温かいわね。', en: "General reaction — warm.", style: 'tender adult woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'hina_child', jp: '雰囲気、なんて、明るいんでしょ。', en: "Atmosphere — \"how\", bright!", style: 'awed teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: '感想、後で、聞かせてね。', en: "Impressions — later, tell.", style: 'gentle adult woman voice, soft warm curious delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、いろいろ感じた、本当に。', en: "Yeah — various felt, truly.", style: 'soft tender teen girl voice, warm reflective delivery carefully' },
      { speaker: 'aoi_barista', jp: '貴重な体験、宝物だね。', en: "Precious experience — treasure.", style: 'tender adult woman voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02051',
    context: 'Sho-young learns about money basics with Mei using small coins.',
    purpose: 'Mother patiently teaching child finance basics.',
    ambient: 'living_room_table_lamp',
    sound_effects: [],
    target_vocab: ['円', '万', '千', '使っ', '数字', '交換', '計算', 'なんて'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '翔、この百円、何に使う?', en: "Sho — this 100 yen, what use?", style: 'gentle young mother voice, soft warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'お菓子、買いたい、なんて思ってた!', en: "Sweets — want buy, \"oh\" thinking!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '十円、百円、千円、計算してみよう。', en: "Ten, hundred, thousand — calculate try.", style: 'warm young mother voice, soft warm helpful delivery carefully' },
      { speaker: 'sho_child', jp: '一万円って、すごい数字だね!', en: "10000 yen — amazing number!", style: 'awed child boy voice, bright warm delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、交換するの、丁寧にね。', en: "Yeah — exchange, carefully.", style: 'tender young mother voice, soft warm caring delivery carefully' },
    ],
  },
  {
    id: 'conv_02052',
    context: 'Riku-teen and Sho-young trade soccer cards; negotiate carefully.',
    purpose: 'Two teens engaged in trade-style interaction.',
    ambient: 'park_bench_afternoon',
    sound_effects: [],
    target_vocab: ['カード', '種類', '交換', '違っ', 'うまく', '納得', '気持ち', '相手'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '陸くん、このカード、交換しよ!', en: "Riku — this card, exchange!", style: 'eager child boy voice, bright warm enthusiastic delivery carefully' },
      { speaker: 'riku_teen', jp: 'どの種類が、欲しい?', en: "Which type — want?", style: 'soft teen boy voice, warm warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: '違ったレアカード、出てきた!', en: "Differing rare card — came out!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'riku_teen', jp: 'うまく、二枚と交換するか。', en: "Well — two cards exchange?", style: 'composed teen boy voice, soft warm calculating delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、気持ち、納得した!', en: "Yeah — feel, agreed!", style: 'soft happy child boy voice, warm warm content delivery carefully' },
      { speaker: 'riku_teen', jp: '相手の希望、聞くの、大事やな。', en: "Other's wish — listen, matters.", style: 'soft teen boy voice, warm warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、お互い、ええ取引やな!', en: "Yeah — both, fine trade!", style: 'cheerful child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02053',
    context: 'Sakura sets up an interview at a town office; meets a clerk.',
    purpose: 'Adult writer in formal civic interaction.',
    ambient: 'office_lobby_low',
    sound_effects: [],
    target_vocab: ['機関', '案内', '登録', '更新', '提出', '確認', 'メール', '担当'],
    cast: ['sakura_teen', 'takeda_officer'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'takeda_officer', jp: 'お問い合わせの機関、こちらで案内します。', en: "Inquiry body — here guide.", style: 'composed officer voice, soft professional formal delivery carefully' },
      { speaker: 'sakura_teen', jp: 'よろしくお願いします、登録、更新したくて。', en: "Thank you — registration, want update.", style: 'gentle adult writer voice, soft warm polite delivery carefully' },
      { speaker: 'takeda_officer', jp: '担当者、すぐ呼びますね。', en: "Person in charge — soon call.", style: 'warm officer voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '書類、これで提出、合っていますか?', en: "Documents — this submit, correct?", style: 'soft adult writer voice, warm careful confirming delivery carefully' },
      { speaker: 'takeda_officer', jp: '確認します、ちょっとお待ちを。', en: "Verify — slightly wait.", style: 'gentle officer voice, soft warm polite delivery carefully' },
      { speaker: 'sakura_teen', jp: 'メール、後で送ってもいいでしょうか?', en: "Email — later send may?", style: 'composed adult writer voice, soft warm polite delivery carefully' },
      { speaker: 'takeda_officer', jp: 'はい、こちらのアドレスへ。', en: "Yes — here address to.", style: 'professional officer voice, soft warm courteous delivery carefully' },
    ],
  },
  {
    id: 'conv_02054',
    context: 'Kenji and Hiroshi-boss discuss a creative agency partnership.',
    purpose: 'Two adults exploring business collaboration.',
    ambient: 'office_quiet_meeting',
    sound_effects: [],
    target_vocab: ['提供', '提案', '共同', '事業', '可能', '良く', '判断', '展開'],
    cast: ['kenji_office', 'hiroshi_boss'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '社長、提供できる事業、提案します。', en: "Boss — providable business, propose.", style: 'composed Kansai man voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '共同で、進める可能、ありそうやな。', en: "Joint — advance possible, seems.", style: 'measured boss voice, soft warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: '展開、どの方向にしますか?', en: "Development — what direction?", style: 'soft Kansai man voice, warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '判断、良く、お互いに相談しよう。', en: "Judgment — well, both consult.", style: 'gentle boss voice, soft warm collaborative delivery carefully' },
      { speaker: 'kenji_office', jp: 'お互いの良さ、活かせるな。', en: "Both goods — leverage.", style: 'warm Kansai man voice, soft warm hopeful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'これからも、ええ関係、続けような。', en: "Going forward — fine relationship, keep.", style: 'tender boss voice, soft warm enduring delivery carefully' },
      { speaker: 'kenji_office', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble Kansai man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02055',
    context: 'Daichi searches for a lost item; Sho-young helps look.',
    purpose: 'Father and son in domestic search.',
    ambient: 'living_room_low_search',
    sound_effects: [],
    target_vocab: ['探し', '置い', '乗っ', '戻る', '間違い', '見つけ', 'だが', '結局'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '翔、お父さんの鍵、探してくれや。', en: "Sho — Dad's key, search.", style: 'soft Kansai father voice, warm friendly delivery carefully' },
      { speaker: 'sho_child', jp: '机に置いてあったかも、見てみる!', en: "Desk on placed maybe — look!", style: 'eager child boy voice, bright warm helpful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '昨日、何に乗って帰った?', en: "Yesterday — on what came back?", style: 'thoughtful Kansai father voice, soft warm thinking delivery carefully' },
      { speaker: 'sho_child', jp: '間違いで、車から戻るの忘れたかも。', en: "Mistake — from car return forgot maybe.", style: 'soft child boy voice, warm warm tentative delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'だが、結局、見つかってよかった!', en: "But — after all, found, good!", style: 'warm Kansai father voice, soft warm relieved delivery carefully' },
    ],
  },
  {
    id: 'conv_02056',
    context: 'Hina-young goes through her diary entries; reads bits to Yumiko.',
    purpose: 'Teen reflecting on personal record with grandmother.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['日記', 'おり', '思い', '振り返る', '記録', '気持ち', '若い', '過ぎ'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、日記、ようけ書いておりました。', en: "Grandma — diary, much wrote.", style: 'soft teen girl voice, warm reflective delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、思い出、振り返ると、楽しいでしょ。', en: "Oh — memories, looking back, fun.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: '若い頃の気持ち、記録、残してて、よかった。', en: "Young feelings — record, leave, good.", style: 'thoughtful teen girl voice, soft warm content delivery carefully' },
      { speaker: 'yumiko_mom', jp: '時間、過ぎるの、早いわね。', en: "Time — passing, fast.", style: 'soft older mother voice, warm reflective delivery carefully' },
      { speaker: 'hina_child', jp: '思いも、書き続けたい。', en: "Thoughts — want write keep.", style: 'gentle teen girl voice, soft warm committed delivery carefully' },
      { speaker: 'yumiko_mom', jp: '大切な習慣、続けてね。', en: "Precious habit — keep.", style: 'tender older mother voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、絶対!', en: "Yeah — definitely!", style: 'bright teen girl voice, soft warm determined delivery carefully' },
    ],
  },
  {
    id: 'conv_02057',
    context: 'Mei plans a small home science experiment with Sho-young.',
    purpose: 'Mother teaching child basic scientific method.',
    ambient: 'kitchen_evening_warm',
    sound_effects: [],
    target_vocab: ['科学', '実験', '結果', '観察', '記録', '面白い', '反応', '驚き'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '翔、今日、科学実験、しよう!', en: "Sho — today, science experiment, do!", style: 'bright young mother voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、何の実験?', en: "Yay — what experiment?", style: 'thrilled child boy voice, bright warm eager delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お酢と、重曹、混ぜたら、面白い反応するの。', en: "Vinegar and — baking soda, mix, interesting reaction.", style: 'gentle young mother voice, soft warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: '結果、どうなるんだろう?', en: "Result — how become?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'よく観察して、記録、つけよう。', en: "Carefully observe — record, keep.", style: 'warm young mother voice, soft warm instructional delivery carefully' },
      { speaker: 'sho_child', jp: 'うわ、泡!驚き!', en: "Whoa — foam! Surprise!", style: 'awed child boy voice, bright warm delight delivered carefully' },
      { speaker: 'mei_romantic', jp: 'これが、化学反応よ。', en: "This — chemical reaction.", style: 'tender young mother voice, soft warm explanatory delivery carefully' },
    ],
  },
  {
    id: 'conv_02058',
    context: 'Naoko shares cooking failures with Aoi; honest professional chat.',
    purpose: 'Two adult women sharing professional vulnerability.',
    ambient: 'ramen_shop_after_close',
    sound_effects: [],
    target_vocab: ['失敗', '間違い', '反省', 'うまく', '改善', '工夫', '次回', '一般'],
    cast: ['naoko_aunt', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '蒼ちゃん、今日、失敗してもうたわ。', en: "Aoi-chan — today, failed.", style: 'soft Kansai aunt voice, warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: 'まあ、どんな間違い?', en: "Oh — what mistake?", style: 'gentle adult woman voice, soft warm empathetic delivery carefully' },
      { speaker: 'naoko_aunt', jp: '塩、間違いで、ようけ入れた。', en: "Salt — mistake by, much put.", style: 'soft Kansai aunt voice, warm warm contrite delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うまくいかない日も、ありますよ。', en: "Won't go well day — exists.", style: 'warm adult woman voice, soft warm reassuring delivery carefully' },
      { speaker: 'naoko_aunt', jp: '反省、しまくり、しとる。', en: "Reflecting — heavily, doing.", style: 'tender Kansai aunt voice, soft warm humble delivery carefully' },
      { speaker: 'aoi_barista', jp: '次回、工夫で改善できるね。', en: "Next time — ingenuity improve.", style: 'soft adult woman voice, warm warm encouraging delivery carefully' },
      { speaker: 'naoko_aunt', jp: '一般客にも、お詫び、しっかりしたで。', en: "General customers — apology, properly did.", style: 'firm Kansai aunt voice, soft warm professional delivery carefully' },
    ],
  },
  {
    id: 'conv_02059',
    context: 'Ren reports on a sightseeing tour he led for a magazine.',
    purpose: 'Young man recounting professional travel writing assignment.',
    ambient: 'editorial_office_low',
    sound_effects: [],
    target_vocab: ['観光', '案内', '案内', '北', '京都', '撮影', '取材', '記事'],
    cast: ['ren_uni', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'さくらさん、北の観光取材、終わりました。', en: "Sakura — northern sightseeing coverage, ended.", style: 'soft young man voice, warm warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お疲れさま、どうだった?', en: "Good work — how was?", style: 'gentle adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '案内、ようけ詳しかったです。', en: "Guide — much detailed.", style: 'warm young man voice, soft warm impressed delivery carefully' },
      { speaker: 'sakura_teen', jp: '京都とは、違う雰囲気?', en: "Kyoto from — different mood?", style: 'curious adult writer voice, soft warm interested delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、撮影、自然がとても綺麗でした。', en: "Yes — filming, nature very beautiful.", style: 'soft young man voice, warm awed delivery carefully' },
      { speaker: 'sakura_teen', jp: '取材記事、楽しみね。', en: "Coverage article — looking forward.", style: 'warm adult writer voice, soft warm fond delivery carefully' },
      { speaker: 'ren_uni', jp: '心、こめて、書き上げます。', en: "Heart — put, finish.", style: 'soft committed young man voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02060',
    context: 'Hiroshi-elder and family observe a moment of silence on a war memorial.',
    purpose: 'Multi-voice solemn cultural observance.',
    ambient: 'memorial_quiet_breeze',
    sound_effects: [],
    target_vocab: ['平和', '戦争', '我々', '日本人', '主義', '時代', '伝える', '責任'],
    cast: ['hiroshi_elder', 'sakura_teen', 'daichi_kansai', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '今日は、戦争を、思い出す日や。', en: "Today — war, recall day.", style: 'slow elder Kansai voice, warm grave delivery carefully' },
      { speaker: 'sakura_teen', jp: '平和、改めて、感謝します。', en: "Peace — anew, grateful.", style: 'soft adult writer voice, warm reverent delivery carefully' },
      { speaker: 'daichi_kansai', jp: '我々の世代、何ができるやろか。', en: "Our gen — what can do?", style: 'soft Kansai husband voice, warm warm reflective delivery carefully' },
      { speaker: 'sho_child', jp: 'お父さん、戦争って、悲しい。', en: "Dad — war, sad.", style: 'tender child boy voice, soft warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '当時、ようけの日本人、苦しんだ。', en: "Then — many Japanese, suffered.", style: 'gentle elder Kansai voice, soft warm grave delivery carefully' },
      { speaker: 'sakura_teen', jp: '平和主義、伝えるの、私たちの責任。', en: "Pacifism — conveying, our responsibility.", style: 'firm adult writer voice, soft warm committed delivery carefully' },
      { speaker: 'daichi_kansai', jp: '時代を、繋いでいかなあかんな。', en: "Era — must connect.", style: 'warm Kansai husband voice, soft warm enduring delivery carefully' },
      { speaker: 'sho_child', jp: '僕も、平和、守りたい。', en: "I — peace, want protect.", style: 'soft determined child boy voice, warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前みたいな子が、未来や。', en: "Kid like you — future.", style: 'tender elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に、必ず、丁寧に伝えます。', en: "Article — surely, carefully convey.", style: 'reverent adult writer voice, soft warm committed delivery carefully' },
      { speaker: 'daichi_kansai', jp: '家族で、こうやって、来れて良かった。', en: "Family — like this, came, good.", style: 'soft Kansai husband voice, warm warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、忘れない、絶対!', en: "Yeah — won't forget, definitely!", style: 'bright child boy voice, soft warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '感謝、ようけある、ほんま。', en: "Gratitude — much, truly.", style: 'tender elder Kansai voice, soft warm humble delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_103 wrote', CONVERSATIONS.length, 'files');
