import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_096)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01906',
    context: 'Daichi grumbles about his commute being delayed; Mei comforts him.',
    purpose: 'Wife listening to husband\'s daily frustration.',
    ambient: 'kitchen_evening_warm',
    sound_effects: [],
    target_vocab: ['通勤', '遅延', '満員', '疲れ'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '今日の通勤、めっちゃ大変やった。', en: "Today's commute — super hard.", style: 'soft tired Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、何があった?', en: "Oh — what happened?", style: 'gentle young wife voice, soft warm caring inquiry delivered carefully' },
      { speaker: 'daichi_kansai', jp: '遅延、ようけあった。', en: "Delay — many.", style: 'soft Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '満員電車、辛いね。', en: "Packed train — hard.", style: 'tender young woman voice, soft warm empathetic delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お疲れの後、家、ええわ。', en: "After tired — home, fine.", style: 'warm Kansai husband voice, soft tender delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ゆっくり、休んで。', en: "Slowly — rest.", style: 'soft young wife voice, warm tender caring delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'tender Kansai husband voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01907',
    context: 'Sho-young loses something at school; calls Yumiko in tears.',
    purpose: 'Child seeking comfort over small loss.',
    ambient: 'phone_low_quiet',
    sound_effects: [],
    target_vocab: ['失くす', '泣く', '大切', '気持ち'],
    cast: ['sho_child', 'yumiko_mom'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おばあちゃん、宝物、失くした!', en: "Grandma — treasure, lost!", style: 'soft tearful child boy voice, warm raw honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、何だった?', en: "Oh — what was?", style: 'gentle older mother voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: 'お父さんに、もらった鉛筆。', en: "Dad — gave pencil.", style: 'soft sad child boy voice, warm vulnerable delivery carefully' },
      { speaker: 'yumiko_mom', jp: '大切なものね。', en: "Precious thing.", style: 'tender older mother voice, soft warm sympathetic delivery carefully' },
      { speaker: 'sho_child', jp: '気持ち、つらい。', en: "Feel — hard.", style: 'soft tearful child boy voice, warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '一緒に、探そう。', en: "Together — search.", style: 'warm older mother voice, soft warm reassuring delivery carefully' },
    ],
  },
  {
    id: 'conv_01908',
    context: 'Hina-young helps Hiroshi-elder write a postcard to a relative.',
    purpose: 'Teen patiently helping grandfather correspond.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['葉書', '宛名', '切手', '書く'],
    cast: ['hina_child', 'hiroshi_elder'],
    frequency_tier: 5,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'ひな、葉書、宛名、書いてくれる?', en: "Hina — postcard, address, write?", style: 'slow elder Kansai voice, warm humble delivery carefully' },
      { speaker: 'hina_child', jp: 'もちろん、おじいちゃん。', en: "Of course — grandpa.", style: 'soft teen girl voice, warm warm helpful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '切手、ちゃんと貼って。', en: "Stamp — paste properly.", style: 'gentle elder Kansai voice, soft warm careful delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、こうですか?', en: "Yes — like this?", style: 'attentive teen girl voice, soft warm careful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、お前、上手やな。', en: "Yeah — you, skilled.", style: 'warm elder Kansai voice, soft fond proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01909',
    context: 'Aoi takes the baby to the doctor on a stroller; meets Saito briefly.',
    purpose: 'New mother running into doctor casually outdoors.',
    ambient: 'street_morning_low',
    sound_effects: [],
    target_vocab: ['赤ちゃん', '散歩', '元気', '成長'],
    cast: ['aoi_barista', 'saito_doctor'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '蒼さん、お散歩?', en: "Aoi — walk?", style: 'warm doctor voice, soft warm friendly delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、毎日、ベビーカーで。', en: "Yes — daily, stroller.", style: 'soft adult woman voice, warm cheerful delivery carefully' },
      { speaker: 'saito_doctor', jp: '赤ちゃん、元気そうですね。', en: "Baby — looks well.", style: 'gentle doctor voice, soft warm observant delivery carefully' },
      { speaker: 'aoi_barista', jp: 'おかげさまで、成長してます。', en: "Thankfully — growing.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'お互い、ご自愛を。', en: "Both — take care.", style: 'warm doctor voice, soft warm caring delivery carefully' },
    ],
  },
  {
    id: 'conv_01910',
    context: 'Naoko receives a delivery and signs for it gruffly; chats with the deliveryman briefly.',
    purpose: 'Brief Kansai-style customer-service moment.',
    ambient: 'ramen_shop_door_low',
    sound_effects: [],
    target_vocab: ['配達', '荷物', '受け取り', '署名'],
    cast: ['naoko_aunt', 'takeda_officer'],
    frequency_tier: 5,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'takeda_officer', jp: 'お届けです、署名お願いします。', en: "Delivery — please sign.", style: 'soft official voice, warm professional friendly delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、おおきに、ご苦労さん。', en: "Yeah — thanks, good work.", style: 'brassy Kansai aunt voice, bright loud warm delivery carefully' },
      { speaker: 'takeda_officer', jp: '荷物、ここに置きます。', en: "Package — place here.", style: 'gentle official voice, soft warm professional delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'はい、受け取りました。', en: "Yes — received.", style: 'warm Kansai aunt voice, soft cheerful delivery carefully' },
      { speaker: 'takeda_officer', jp: 'では、失礼します。', en: "Then — excuse me.", style: 'composed official voice, soft warm polite delivery carefully' },
    ],
  },
  {
    id: 'conv_01911',
    context: 'Mei wraps a thank-you gift for Sakura; thoughtful packaging.',
    purpose: 'Adult mother carefully preparing meaningful gift.',
    ambient: 'kitchen_table_warm',
    sound_effects: [],
    target_vocab: ['贈り物', '包む', '気持ち', '丁寧'],
    cast: ['mei_romantic', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、何、包んでるの?', en: "Mei — wrapping what?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'さくらさんへの、贈り物。', en: "Sakura — gift to.", style: 'tender young woman voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: '丁寧に、包んでるね。', en: "Carefully — wrapping.", style: 'soft teen girl voice, warm appreciative delivery carefully' },
      { speaker: 'mei_romantic', jp: '気持ち、こめてる。', en: "Heart — putting.", style: 'gentle young woman voice, soft warm tender delivery carefully' },
      { speaker: 'hina_child', jp: '私も、手伝う?', en: "I — help?", style: 'eager teen girl voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01912',
    context: 'Ren picks up an old letter from a long-lost friend; reads it with Sakura.',
    purpose: 'Young man sharing nostalgic correspondence with mentor.',
    ambient: 'study_room_lamp_quiet',
    sound_effects: [],
    target_vocab: ['手紙', '友達', '懐かしい', '記憶'],
    cast: ['ren_uni', 'sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'さくらさん、古い手紙、出てきた。', en: "Sakura — old letter, surfaced.", style: 'soft young man voice, warm awed nostalgic delivery carefully' },
      { speaker: 'sakura_teen', jp: '誰から?', en: "From whom?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'ren_uni', jp: '高校時代の親友。', en: "High school close friend.", style: 'tender young man voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '懐かしい記憶ね。', en: "Nostalgic memory.", style: 'soft adult writer voice, warm tender delivery carefully' },
      { speaker: 'ren_uni', jp: '読むと、心が温まる。', en: "Reading — heart warms.", style: 'soft young man voice, warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '連絡、取ってみる?', en: "Contact — try?", style: 'warm adult writer voice, soft warm suggesting delivery carefully' },
      { speaker: 'ren_uni', jp: 'うん、勇気出して。', en: "Yeah — courage out.", style: 'soft determined young man voice, warm resolved delivery carefully' },
    ],
  },
  {
    id: 'conv_01913',
    context: 'Kenji helps Hiroshi-elder use the train station ticket machine.',
    purpose: 'Adult patiently helping elder with tech.',
    ambient: 'station_machine_low',
    sound_effects: [],
    target_vocab: ['切符', '駅', '行き先', '機械'],
    cast: ['kenji_office', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'この機械、わからん。', en: "This machine — can't.", style: 'soft puzzled elder Kansai voice, warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'おとうさん、行き先押して。', en: "Otosan — destination press.", style: 'soft Kansai man voice, warm patient teaching delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、これか?', en: "Oh — this?", style: 'gentle elder Kansai voice, soft warm uncertain delivery carefully' },
      { speaker: 'kenji_office', jp: 'そう、切符出るで。', en: "Yes — ticket out.", style: 'warm Kansai mentor voice, soft helpful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おおきに、助かるわ。', en: "Thanks — saved.", style: 'tender elder Kansai voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01914',
    context: 'Sakura signs a book at a small bookstore; Hina-young gets one.',
    purpose: 'Author meeting teen reader-fan tenderly.',
    ambient: 'bookstore_quiet_low',
    sound_effects: [],
    target_vocab: ['本', '署名', '読者', '嬉しい'],
    cast: ['sakura_teen', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、本、署名してください!', en: "Sakura — book, sign please!", style: 'eager teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、もちろん!', en: "Oh — of course!", style: 'tender adult writer voice, soft warm delighted delivery carefully' },
      { speaker: 'hina_child', jp: '読者になれて、嬉しい!', en: "Reader — happy!", style: 'thrilled teen girl voice, bright warm grateful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こちらこそ、ありがとう。', en: "Likewise — thanks.", style: 'soft adult writer voice, warm humble grateful delivery carefully' },
      { speaker: 'hina_child', jp: '大切に、します。', en: "Cherish.", style: 'soft teen girl voice, warm reverent delivery carefully' },
    ],
  },
  {
    id: 'conv_01915',
    context: 'Asuka prepares a small art exhibit for students; Saito helps hang pieces.',
    purpose: 'Couple working together for school event.',
    ambient: 'school_gallery_low',
    sound_effects: [],
    target_vocab: ['展示', '準備', '飾る', '一緒'],
    cast: ['asuka_teacher', 'saito_doctor'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '展示の準備、ありがとう。', en: "Exhibit prep — thanks.", style: 'warm teacher voice, soft warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'いえいえ、楽しいよ。', en: "No no — fun.", style: 'soft doctor voice, warm warm friendly delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ここに、飾ろうかな。', en: "Here — decorate.", style: 'soft teacher voice, warm thoughtful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'うん、ええ位置や。', en: "Yeah — fine position.", style: 'gentle doctor voice, soft warm agreeing delivery carefully' },
      { speaker: 'asuka_teacher', jp: '生徒、喜んでくれるかな。', en: "Students — please?", style: 'tender teacher voice, soft warm hopeful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'きっと、感動するよ。', en: "Surely — moved.", style: 'warm doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'asuka_teacher', jp: '一緒に、作れて嬉しい。', en: "Together — making, happy.", style: 'tender teacher voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01916',
    context: 'Yuki-office tells Sakura about a small business idea over coffee.',
    purpose: 'Friend brainstorming new venture with another adult.',
    ambient: 'cafe_morning_low',
    sound_effects: [],
    target_vocab: ['計画', '事業', '夢', '相談'],
    cast: ['yuki_office', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: 'さくらさん、相談したい計画、ある。', en: "Sakura — plan to consult, exists.", style: 'soft office woman voice, warm engaged hopeful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、何?', en: "Oh — what?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'yuki_office', jp: '小さい事業、始めたい。', en: "Small business — want to start.", style: 'warm office woman voice, soft warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: '勇気あるね、夢、いいね。', en: "Brave — dream, lovely.", style: 'tender adult writer voice, soft warm encouraging delivery carefully' },
      { speaker: 'yuki_office', jp: '不安、いっぱい。', en: "Anxiety — full.", style: 'soft office woman voice, warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '一緒に、考えよう。', en: "Together — think.", style: 'warm adult writer voice, soft warm supportive delivery carefully' },
      { speaker: 'yuki_office', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'tender office woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01917',
    context: 'Riku-teen wins a small competition; Sho-young congratulates him with admiration.',
    purpose: 'Younger child celebrating older teen achievement.',
    ambient: 'park_outdoor_low',
    sound_effects: [],
    target_vocab: ['優勝', 'すごい', '頑張る', '尊敬'],
    cast: ['sho_child', 'riku_teen'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '陸くん、優勝、すごい!', en: "Riku — win, amazing!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'riku_teen', jp: 'ふふ、ありがとう!', en: "Heh — thanks!", style: 'soft teen boy voice, warm humble cheerful delivery carefully' },
      { speaker: 'sho_child', jp: '尊敬する、本当に!', en: "Respect — truly!", style: 'soft admiring child boy voice, warm earnest delivery carefully' },
      { speaker: 'riku_teen', jp: '頑張ったからな、長く。', en: "Tried — long.", style: 'warm teen boy voice, soft proud delivery carefully' },
      { speaker: 'sho_child', jp: '僕も、頑張る!', en: "I — try too!", style: 'bright child boy voice, soft warm determined delivery carefully' },
    ],
  },
  {
    id: 'conv_01918',
    context: 'Tatsuya-country mails a package of rice to his daughter; chats with Asuka.',
    purpose: 'Older couple coordinating gift mail.',
    ambient: 'kitchen_morning_quiet',
    sound_effects: [],
    target_vocab: ['米', '宅配', '送る', '心'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '今年の米、娘に送る。', en: "This year's rice — daughter send.", style: 'soft Tohoku farmer voice, warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'まあ、喜ぶわよ、絶対。', en: "Oh — pleased, definitely.", style: 'warm teacher voice, soft warm delivery carefully' },
      { speaker: 'tatsuya_country', jp: '心、こめて、梱包する。', en: "Heart — packing in.", style: 'gentle Tohoku voice, soft warm tender delivery carefully' },
      { speaker: 'asuka_teacher', jp: '宅配、明日、来てくれるって。', en: "Delivery — tomorrow come.", style: 'gentle teacher voice, soft warm informative delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ええわ、楽しみやな。', en: "Fine — looking forward.", style: 'warm Tohoku farmer voice, soft fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01919',
    context: 'Hina-young keeps a daily diary; reads a passage to Sakura.',
    purpose: 'Teen sharing personal writing with author mentor.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['日記', '書く', '気持ち', '記録'],
    cast: ['hina_child', 'sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、日記、見て?', en: "Sakura — diary, see?", style: 'soft shy teen girl voice, warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、読ませて。', en: "Oh — let me read.", style: 'gentle adult writer voice, soft warm interested delivery carefully' },
      { speaker: 'hina_child', jp: '気持ち、ちゃんと書けたかな。', en: "Feelings — written properly?", style: 'soft teen girl voice, warm hopeful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、すごく素直で素敵。', en: "Yeah — honest, lovely.", style: 'tender adult writer voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: '記録、続けるね、ずっと。', en: "Record — keep, always.", style: 'bright teen girl voice, soft warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '大切な習慣だよ。', en: "Precious habit.", style: 'warm adult writer voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、励みになる。', en: "Thanks — encouragement.", style: 'tender teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01920',
    context: 'Daichi takes Sho-young to a small post office to mail birthday card.',
    purpose: 'Father teaching child practical postal task.',
    ambient: 'post_office_quiet',
    sound_effects: [],
    target_vocab: ['郵便', '切手', '封筒', '送る'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、切手、貼る?', en: "Dad — stamp, paste?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、ここに、貼ってみ。', en: "Yeah — here, paste.", style: 'warm Kansai father voice, soft warm helpful delivery carefully' },
      { speaker: 'sho_child', jp: '封筒、これでいい?', en: "Envelope — this fine?", style: 'soft attentive child boy voice, warm careful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、ばっちりや!', en: "Yeah — perfect!", style: 'cheerful Kansai father voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: 'おばあちゃんに、届くね!', en: "Grandma — reaches!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01921',
    context: 'Naoko buys Hina-young a small accessory as a gift; mock-grumpy generosity.',
    purpose: 'Aunt giving teen gift with playful gruffness.',
    ambient: 'ramen_shop_evening',
    sound_effects: [],
    target_vocab: ['贈り物', '気持ち', '可愛い', '嬉しい'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、これ、もう一つ。', en: "Hina — this, one more.", style: 'soft Kansai aunt voice, warm gruff fond delivery carefully' },
      { speaker: 'hina_child', jp: 'えっ、また、もらえるの?', en: "Eh — again, can receive?", style: 'soft awed teen girl voice, warm surprise delivered carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、可愛いと思って。', en: "Yeah — thought cute.", style: 'warm Kansai aunt voice, soft tender shy delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、嬉しい!', en: "Thanks — happy!", style: 'thrilled teen girl voice, bright warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、気持ちだけや。', en: "Heh — just feeling.", style: 'soft Kansai aunt voice, warm humble fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01922',
    context: 'Mei sews a small repair on Sho-young\'s favorite shirt.',
    purpose: 'Mother carefully mending child\'s favorite item.',
    ambient: 'living_room_evening_warm',
    sound_effects: [],
    target_vocab: ['服', '直し', '針', '糸'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、服、直せる?', en: "Mom — clothes, fix?", style: 'soft hopeful child boy voice, warm small delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、針と糸あるから。', en: "Yeah — needle, thread.", style: 'gentle young mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、お母さん!', en: "Thanks — Mom!", style: 'bright child boy voice, soft warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '大事な服やもん。', en: "Precious clothes.", style: 'tender young mother voice, soft warm understanding delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、また、着られる!', en: "Yeah — wear again!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01923',
    context: 'Hiroshi-elder takes a small walk; meets Mrs. Mori at the corner.',
    purpose: 'Two elders briefly chatting on the street.',
    ambient: 'street_corner_afternoon',
    sound_effects: [],
    target_vocab: ['散歩', '近所', '天気', '挨拶'],
    cast: ['hiroshi_elder', 'mrs_mori_neighbor'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'お散歩ですか、お元気ね。', en: "Walk — well.", style: 'warm older neighbor voice, soft warm friendly delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ええ天気やからな。', en: "Yeah — fine weather.", style: 'slow elder Kansai voice, warm content delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '近所で、こうやって会えるの嬉しい。', en: "Neighbor — like this meet, happy.", style: 'gentle older woman voice, soft warm fond delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、感謝やわ。', en: "Truly — grateful.", style: 'soft elder Kansai voice, warm humble delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'また、お会いしましょう。', en: "Again — meet.", style: 'warm older neighbor voice, soft warm friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_01924',
    context: 'Aoi orders supplies for the cafe; phone call with supplier briefly.',
    purpose: 'Business owner making business call.',
    ambient: 'cafe_office_quiet',
    sound_effects: [],
    target_vocab: ['注文', '配達', '確認', '量'],
    cast: ['aoi_barista', 'hiroshi_boss'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '社長、注文の確認、お願いします。', en: "Boss — order confirm, please.", style: 'composed adult woman voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'はい、量、いつもと同じで?', en: "Yes — quantity, usual?", style: 'measured boss voice, soft warm professional delivery carefully' },
      { speaker: 'aoi_barista', jp: '今回、少し増やしてください。', en: "This time — slightly more.", style: 'soft adult woman voice, warm warm clear delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'わかりました、配達日も決めましょう。', en: "Understood — delivery day decide.", style: 'professional boss voice, soft warm efficient delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとうございます。', en: "Thank you.", style: 'gracious adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01925',
    context: 'Whole family writes new year postcards together at the dining table.',
    purpose: 'Multi-voice tradition collective writing scene.',
    ambient: 'dining_table_lamp_warm',
    sound_effects: [],
    target_vocab: ['年賀状', '書く', '皆', '伝える', '幸せ'],
    cast: ['mei_romantic', 'daichi_kansai', 'hina_child', 'sho_child', 'yumiko_mom', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '今年も、年賀状の季節ね。', en: "This year too — postcard season.", style: 'soft young mother voice, warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: '皆、ようけ書かなあかんな。', en: "All — must write many.", style: 'warm Kansai husband voice, soft cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'デザイン、考えるの楽しい!', en: "Design — thinking, fun!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: '僕も、書きたい!', en: "I — want write!", style: 'eager child boy voice, bright warm delivery carefully' },
      { speaker: 'yumiko_mom', jp: '丁寧に、書きましょう。', en: "Carefully — write.", style: 'tender older mother voice, soft warm teaching delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '昔の友人、忘れずに。', en: "Old friends — don't forget.", style: 'slow elder Kansai voice, warm warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: '心、こめて伝えましょうね。', en: "Heart — convey put.", style: 'tender young mother voice, soft warm earnest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '幸せな一年、願って書く。', en: "Happy year — wishing write.", style: 'warm Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: 'お友達、たくさん、書く!', en: "Friends — many, write!", style: 'bright teen girl voice, soft warm energetic delivery carefully' },
      { speaker: 'sho_child', jp: 'お父さん、字、上手!', en: "Dad — letters, skilled!", style: 'awed child boy voice, soft warm admiring delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、賑やかでええわね。', en: "Heh — lively, fine.", style: 'warm older mother voice, soft fond delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '家族、こうやって書くのも、伝統や。', en: "Family — writing like this, tradition.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'mei_romantic', jp: '皆で、ええ年、迎えましょう。', en: "All — fine year, welcome.", style: 'tender young mother voice, soft warm hopeful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_096 wrote', CONVERSATIONS.length, 'files');
