import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_085)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01686',
    context: 'Ren confides to Saito about a recent breakup; honest emotional talk.',
    purpose: 'Young man processing relationship loss with elder mentor.',
    ambient: 'cafe_evening_quiet',
    sound_effects: [],
    target_vocab: ['別れる', '恋', '辛い', '時間'],
    cast: ['ren_uni', 'saito_doctor'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '先生、別れたんです。', en: "Doctor — we broke up.", style: 'soft young man voice, warm raw honest delivery carefully' },
      { speaker: 'saito_doctor', jp: 'そう、辛かったね。', en: "I see — that was hard.", style: 'measured doctor voice, soft warm empathetic delivery carefully' },
      { speaker: 'ren_uni', jp: 'まだ、整理つかなくて。', en: "Still — can't sort it out.", style: 'soft young man voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '時間が、必要ですね。', en: "Time — needed.", style: 'gentle doctor voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: '恋って、難しい。', en: "Love — hard.", style: 'soft young man voice, warm wistful delivery carefully' },
      { speaker: 'saito_doctor', jp: '誰もが、通る道ですよ。', en: "Everyone — passes this road.", style: 'warm doctor voice, soft tender philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、聞いてくれて。', en: "Thanks — for listening.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01687',
    context: 'Mei tells Yumiko about preparing for a relative\'s wedding ceremony.',
    purpose: 'Younger woman seeking older woman\'s guidance for family event.',
    ambient: 'kitchen_morning_warm',
    sound_effects: [],
    target_vocab: ['結婚式', '披露', '親戚', '祝う'],
    cast: ['mei_romantic', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '従姉妹の結婚式、来月よ。', en: "Cousin's wedding — next month.", style: 'soft young woman voice, warm cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、嬉しい知らせね。', en: "Oh — happy news.", style: 'gentle older mother voice, soft warm delivery carefully' },
      { speaker: 'mei_romantic', jp: '披露宴、何着ようかな。', en: "Reception — what to wear.", style: 'gentle young woman voice, soft warm thinking delivery carefully' },
      { speaker: 'yumiko_mom', jp: '着物、どう?', en: "Kimono — how about?", style: 'warm older mother voice, soft helpful suggesting delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、親戚にも喜ばれそう。', en: "Yeah — relatives will be pleased.", style: 'soft young woman voice, warm fond delivery carefully' },
      { speaker: 'yumiko_mom', jp: '一緒に、選びましょう。', en: "Let's choose together.", style: 'tender older mother voice, soft warm helpful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'はい、お願いします。', en: "Yes — please.", style: 'humble young woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01688',
    context: 'Daichi takes baby Hikari (use sho_child as toddler stand-in) to kindergarten first day.',
    purpose: 'Father walking child to first school day.',
    ambient: 'kindergarten_entry_low',
    sound_effects: [],
    target_vocab: ['幼稚園', '初めて', '友達', '頑張る'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '今日、幼稚園、初めてやな。', en: "Today — first kindergarten.", style: 'soft Kansai father voice, warm tender delivery carefully' },
      { speaker: 'sho_child', jp: 'お父さん、ちょっと怖い。', en: "Dad — a bit scared.", style: 'soft small child boy voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '友達、できるで、大丈夫。', en: "Friends — you'll make them, fine.", style: 'warm Kansai father voice, soft reassuring delivery carefully' },
      { speaker: 'sho_child', jp: 'お父さんも来る?', en: "Dad — coming too?", style: 'soft hopeful child boy voice, warm small delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お迎え、ちゃんと来るで。', en: "Pick-up — I'll come properly.", style: 'tender Kansai father voice, soft warm promising delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、頑張る!', en: "Yeah — I'll try!", style: 'brave child boy voice, soft warm resolved delivery carefully' },
    ],
  },
  {
    id: 'conv_01689',
    context: 'Aoi and Kenji discuss whether to have children of their own.',
    purpose: 'Couple having a deep personal conversation about future.',
    ambient: 'porch_evening_quiet',
    sound_effects: [],
    target_vocab: ['子供', '将来', '決断', '夫婦'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、子供のこと、どう思う?', en: "Ken-chan — about kids, what do you think?", style: 'soft adult woman voice, warm careful tender delivery carefully' },
      { speaker: 'kenji_office', jp: 'うん、考え続けてるわ。', en: "Yeah — keep thinking.", style: 'gentle Kansai man voice, soft warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '私たちの将来、見えないの。', en: "Our future — can't see.", style: 'soft adult woman voice, warm honest vulnerable delivery carefully' },
      { speaker: 'kenji_office', jp: '俺らで、決めなあかんな。', en: "We have to decide.", style: 'soft Kansai husband voice, warm serious delivery carefully' },
      { speaker: 'aoi_barista', jp: '子供、欲しいけど、不安。', en: "Want — but anxious.", style: 'tender adult woman voice, soft warm raw delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前の気持ち、わかる。', en: "I understand your feelings.", style: 'warm Kansai man voice, soft tender delivery carefully' },
      { speaker: 'aoi_barista', jp: '夫婦で、よく話し合いたい。', en: "As a couple — want to talk through.", style: 'soft adult woman voice, warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'うん、急がんでええ。', en: "Yeah — no need to rush.", style: 'soft Kansai husband voice, warm patient delivery carefully' },
      { speaker: 'aoi_barista', jp: '時間かけて、考えよう。', en: "Take time — think.", style: 'tender adult woman voice, soft warm united delivery carefully' },
      { speaker: 'kenji_office', jp: 'お互いに、納得できる答えを。', en: "An answer both can accept.", style: 'gentle Kansai man voice, soft warm wise delivery carefully' },
      { speaker: 'aoi_barista', jp: 'けんちゃんと一緒なら、何でも大丈夫。', en: "With you — anything's okay.", style: 'soft adult woman voice, warm tender loving delivery carefully' },
      { speaker: 'kenji_office', jp: '俺もや、おまえと一緒なら。', en: "Same — with you.", style: 'tender Kansai husband voice, soft warm loving delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01690',
    context: 'Sakura and Sho-young have a gentle walk talking about being kind.',
    purpose: 'Adult writer teaching young child about empathy.',
    ambient: 'park_path_breeze',
    sound_effects: [],
    target_vocab: ['優しい', '気持ち', '思いやり', '伝える'],
    cast: ['sakura_teen', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'さくらさん、優しいって何?', en: "Sakura — what's being kind?", style: 'curious child boy voice, soft warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '相手の気持ち、考えること。', en: "Thinking of the other's feelings.", style: 'gentle adult writer voice, soft warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: '思いやり、難しい?', en: "Empathy — hard?", style: 'soft child boy voice, warm thinking delivery carefully' },
      { speaker: 'sakura_teen', jp: '練習すれば、できるよ。', en: "With practice — you can.", style: 'warm adult writer voice, soft encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '頑張ってみる!', en: "I'll try!", style: 'bright child boy voice, soft warm determined delivery carefully' },
    ],
  },
  {
    id: 'conv_01691',
    context: 'Hina-young confesses a small crush on a classmate; Mei listens kindly.',
    purpose: 'Teen confiding first romance to older female mentor.',
    ambient: 'bedroom_lamp_quiet',
    sound_effects: [],
    target_vocab: ['好き', '気持ち', '勇気', '伝える'],
    cast: ['hina_child', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、好きな人、できた。', en: "Mei — I have a crush.", style: 'soft shy teen girl voice, warm tender honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、嬉しい話ね。', en: "Oh — happy story.", style: 'warm young woman voice, soft tender delight delivered carefully' },
      { speaker: 'hina_child', jp: 'でも、伝える勇気、ない。', en: "But — no courage to tell.", style: 'soft teen girl voice, warm vulnerable delivery carefully' },
      { speaker: 'mei_romantic', jp: '気持ち、大切にしてね。', en: "Cherish those feelings.", style: 'tender young woman voice, soft warm wise delivery carefully' },
      { speaker: 'hina_child', jp: 'どうしたら、勇気出る?', en: "How — find courage?", style: 'soft teen girl voice, warm hopeful delivery carefully' },
      { speaker: 'mei_romantic', jp: '焦らないで、自分のペースで。', en: "Don't rush — at your pace.", style: 'gentle young woman voice, soft warm patient delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、ありがとう。', en: "Yeah — thanks.", style: 'soft teen girl voice, warm grateful tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01692',
    context: 'Naoko bursts into tears at a grandniece\'s wedding; Hiroshi-elder comforts her.',
    purpose: 'Tough aunt unexpectedly emotional at family milestone.',
    ambient: 'wedding_reception_warm',
    sound_effects: [],
    target_vocab: ['結婚', '泣く', '幸せ', '家族'],
    cast: ['naoko_aunt', 'hiroshi_elder'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'うわ、泣いてもうた…。', en: "Ugh — crying.", style: 'soft Kansai aunt voice, warm raw honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええんやで、嬉し涙や。', en: "It's fine — tears of joy.", style: 'gentle elder Kansai voice, soft warm tender delivery carefully' },
      { speaker: 'naoko_aunt', jp: '結婚式って、こんなに来るんやな。', en: "Weddings — they hit you like this.", style: 'animated Kansai aunt voice, soft warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '家族の絆、ようけ感じるな。', en: "Feel family bonds — much.", style: 'warm elder Kansai voice, soft tender delivery carefully' },
      { speaker: 'naoko_aunt', jp: '幸せそう、本当に。', en: "Happy-looking — truly.", style: 'soft Kansai aunt voice, warm tearful tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01693',
    context: 'Goro-grandpa and Sachiko-grandma celebrate fifty years together quietly.',
    purpose: 'Elder couple acknowledging quiet golden anniversary.',
    ambient: 'tatami_dinner_warm',
    sound_effects: [],
    target_vocab: ['結婚', '年月', '感謝', '一緒'],
    cast: ['goro_grandpa', 'sachiko_grandma'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'goro_grandpa', jp: 'もう、結婚して五十年や。', en: "Married — fifty years already.", style: 'gentle elder voice, soft warm awed delivery carefully' },
      { speaker: 'sachiko_grandma', jp: 'ふふ、信じられないわね。', en: "Heh — unbelievable.", style: 'tender grandmother voice, soft warm fond delivery carefully' },
      { speaker: 'goro_grandpa', jp: 'おまえと一緒で、ええ年月や。', en: "Years with you — good ones.", style: 'soft elder voice, warm loving delivery carefully' },
      { speaker: 'sachiko_grandma', jp: '感謝ばかりよ、私も。', en: "Only gratitude — for me too.", style: 'warm grandmother voice, soft tender delivery carefully' },
      { speaker: 'goro_grandpa', jp: 'これからも、よろしくな。', en: "Going forward — be with me.", style: 'tender elder voice, soft warm enduring delivery carefully' },
    ],
  },
  {
    id: 'conv_01694',
    context: 'Tatsuya-country and Asuka watch their daughter\'s graduation from afar online.',
    purpose: 'Parents far away celebrating big child milestone via video.',
    ambient: 'farmhouse_tv_low',
    sound_effects: [],
    target_vocab: ['卒業', '娘', '映像', '感動'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '見て、娘の卒業式、始まる。', en: "Look — daughter's graduation starting.", style: 'warm teacher voice, soft eager fond delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、ええ顔しとるな。', en: "Yeah — fine face.", style: 'soft Tohoku farmer voice, warm tender proud delivery carefully' },
      { speaker: 'asuka_teacher', jp: '大きくなったね、娘も。', en: "Grown up — our daughter too.", style: 'tender teacher voice, soft warm emotional delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'うん、感動するわ。', en: "Yeah — moved.", style: 'gentle Tohoku voice, soft warm tearful delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'いつか、こうやって直接見たいね。', en: "Someday — want to see directly.", style: 'soft teacher voice, warm wistful delivery carefully' },
      { speaker: 'tatsuya_country', jp: '映像でも、嬉しいわ。', en: "Even on video — happy.", style: 'soft Tohoku voice, warm humble fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: '本当に、いい子に育ったね。', en: "Truly — raised a fine kid.", style: 'tender teacher voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01695',
    context: 'Yumiko helps Sakura sort through old wedding photos for a piece.',
    purpose: 'Elder helping author research while sharing personal memory.',
    ambient: 'living_room_albums',
    sound_effects: [],
    target_vocab: ['写真', '結婚式', '昔', '懐かしい'],
    cast: ['yumiko_mom', 'sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '昔の結婚式写真、見せてください。', en: "Old wedding photos, please show.", style: 'gentle adult writer voice, soft warm respectful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'これ、私の結婚式よ。', en: "This — my wedding.", style: 'warm older mother voice, soft fond delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、若くて綺麗!', en: "Oh — young and lovely!", style: 'soft adult writer voice, warm admiring delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、四十年前ね。', en: "Heh — forty years ago.", style: 'gentle older mother voice, soft warm reminiscent delivery carefully' },
      { speaker: 'sakura_teen', jp: '伝統的な式ね。', en: "Traditional ceremony.", style: 'warm adult writer voice, soft observant delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、家族みんなで祝った。', en: "Yes — celebrated with family.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '懐かしいでしょうね。', en: "Must be nostalgic.", style: 'soft adult writer voice, warm gentle delivery carefully' },
    ],
  },
  {
    id: 'conv_01696',
    context: 'Hiroshi-boss meets Daichi for a quiet talk about retirement someday.',
    purpose: 'Older boss reflecting with valued employee about future.',
    ambient: 'office_evening_quiet',
    sound_effects: [],
    target_vocab: ['退職', '人生', '次', '楽しむ'],
    cast: ['hiroshi_boss', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: 'いつか、退職する日が来る。', en: "Someday — retirement comes.", style: 'measured boss voice, soft warm philosophical delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'まだ、想像できんですわ。', en: "Can't imagine yet.", style: 'soft Kansai man voice, warm honest delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '人生、次の段階や。', en: "Life — next stage.", style: 'gentle boss voice, soft warm wise delivery carefully' },
      { speaker: 'daichi_kansai', jp: '社長は、どう考えてはるんですか?', en: "Boss — what do you think?", style: 'curious Kansai man voice, soft warm respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '趣味、増やしたいんや。', en: "Hobbies — want to add.", style: 'warm boss voice, soft fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええですね、楽しんでください。', en: "Lovely — please enjoy.", style: 'soft Kansai man voice, warm tender delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'うん、お前らも、いつか考えて。', en: "Yeah — you all, think someday too.", style: 'warm boss voice, soft fond paternal delivery carefully' },
    ],
  },
  {
    id: 'conv_01697',
    context: 'Sho-young brings home his first school report card; nervous and proud.',
    purpose: 'Child showing academic milestone to elder grandfather.',
    ambient: 'living_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['成績', '小学校', '誇る', '頑張る'],
    cast: ['sho_child', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、通知表、見て!', en: "Grandpa — report card, look!", style: 'eager child boy voice, bright cheerful nervous delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、見せてみ。', en: "Yeah — show me.", style: 'warm elder Kansai voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: '頑張ったよ、ちゃんと!', en: "I tried — properly!", style: 'soft proud child boy voice, warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'すごいやんか、誇りに思うわ。', en: "Wow — I'm proud.", style: 'gentle elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、嬉しい!', en: "Yay — happy!", style: 'thrilled child boy voice, bright warm delight delivered carefully' },
    ],
  },
  {
    id: 'conv_01698',
    context: 'Aoi quietly tells Sakura she\'s pregnant with the first child.',
    purpose: 'Friend sharing major personal milestone with another.',
    ambient: 'cafe_morning_quiet',
    sound_effects: [],
    target_vocab: ['妊娠', '赤ちゃん', '嬉しい', '驚き'],
    cast: ['aoi_barista', 'sakura_teen'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'さくら、実はね、妊娠したの。', en: "Sakura — actually, I'm pregnant.", style: 'soft adult woman voice, warm tender shy delivery carefully' },
      { speaker: 'sakura_teen', jp: 'えっ、本当?おめでとう!', en: "Eh — really? Congrats!", style: 'thrilled adult writer voice, bright warm delighted delivery carefully' },
      { speaker: 'aoi_barista', jp: 'まだ、信じられないの。', en: "Still — can't believe.", style: 'soft adult woman voice, warm awed delivery carefully' },
      { speaker: 'sakura_teen', jp: '赤ちゃん、楽しみね。', en: "Baby — looking forward.", style: 'tender adult writer voice, soft warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '嬉しいけど、ちょっと怖い。', en: "Happy but a bit scared.", style: 'soft adult woman voice, warm honest vulnerable delivery carefully' },
    ],
  },
  {
    id: 'conv_01699',
    context: 'Riku-teen confesses to Hina-young that he likes someone; embarrassed teen moment.',
    purpose: 'Two teen friends sharing secret crush news.',
    ambient: 'park_bench_afternoon',
    sound_effects: [],
    target_vocab: ['好き', '秘密', '心', '言う'],
    cast: ['riku_teen', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'riku_teen', jp: 'ひな、秘密にしててな。', en: "Hina — keep it secret.", style: 'soft shy teen boy voice, warm tense delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、絶対言わない。', en: "Yeah — never tell.", style: 'soft loyal teen girl voice, warm promising delivery carefully' },
      { speaker: 'riku_teen', jp: '実は、好きな子おる。', en: "Actually — I like someone.", style: 'soft embarrassed teen boy voice, warm honest delivery carefully' },
      { speaker: 'hina_child', jp: 'まじで?教えて!', en: "Really? Tell me!", style: 'eager teen girl voice, bright cheerful delivery carefully' },
      { speaker: 'riku_teen', jp: 'まあ、心の中だけや、まだ。', en: "Eh — still just in my heart.", style: 'soft teen boy voice, warm shy delivery carefully' },
    ],
  },
  {
    id: 'conv_01700',
    context: 'Whole group hosts Aoi\'s baby shower at the cafe.',
    purpose: 'Friends and family celebrating coming new life warmly.',
    ambient: 'cafe_baby_shower_warm',
    sound_effects: [],
    target_vocab: ['赤ちゃん', '祝う', '贈り物', '一緒', '愛'],
    cast: ['aoi_barista', 'kenji_office', 'sakura_teen', 'mei_romantic', 'naoko_aunt', 'yumiko_mom'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蒼さん、本当におめでとう!', en: "Aoi — truly congrats!", style: 'warm adult writer voice, soft delighted delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ええ知らせやな、嬉しいわ!', en: "Fine news — happy!", style: 'brassy Kansai aunt voice, bright loud delighted delivery carefully' },
      { speaker: 'aoi_barista', jp: 'みんな、ありがとう。', en: "Everyone — thanks.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'kenji_office', jp: '俺、父親になるんやな。', en: "I'll be a father.", style: 'soft Kansai man voice, warm awed honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '心強い、たくさん仲間がいて。', en: "Encouraging — many companions.", style: 'gentle young mother voice, soft warm delivery carefully' },
      { speaker: 'yumiko_mom', jp: '私も、応援するわよ。', en: "I'll cheer too.", style: 'tender older mother voice, soft warm supportive delivery carefully' },
      { speaker: 'aoi_barista', jp: 'みんなの愛、感じる。', en: "Feel everyone's love.", style: 'soft adult woman voice, warm emotional delivery carefully' },
      { speaker: 'sakura_teen', jp: '贈り物、たくさん用意したよ。', en: "Lots of gifts prepared.", style: 'warm adult writer voice, soft warm proud delivery carefully' },
      { speaker: 'naoko_aunt', jp: '赤ちゃん用、めっちゃ買うたで!', en: "Bought tons for the baby!", style: 'animated Kansai aunt voice, bright loud generous delivery carefully' },
      { speaker: 'kenji_office', jp: 'みんなのおかげで、心が温い。', en: "Thanks to all — heart warm.", style: 'tender Kansai man voice, soft warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '一緒に、子育てしましょうね。', en: "Let's raise together.", style: 'tender young mother voice, soft warm sisterly delivery carefully' },
      { speaker: 'yumiko_mom', jp: '困ったら、いつでもね。', en: "When troubled — anytime.", style: 'warm older mother voice, soft tender loyal delivery carefully' },
      { speaker: 'aoi_barista', jp: '本当に、感謝の気持ちでいっぱい。', en: "Truly — full of gratitude.", style: 'soft adult woman voice, warm tearful tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01701',
    context: 'Mei tells Daichi she wants a third child; tender husband-wife talk.',
    purpose: 'Couple discussing family expansion plans.',
    ambient: 'bedroom_evening_low',
    sound_effects: [],
    target_vocab: ['子供', '兄弟', '考える', '幸せ'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'もう一人、子供欲しい。', en: "Want one more child.", style: 'soft young wife voice, warm tender honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ほんま?嬉しいで。', en: "Truly? Happy.", style: 'warm Kansai husband voice, soft tender delight delivered carefully' },
      { speaker: 'mei_romantic', jp: '兄弟、たくさんいた方がいいかな。', en: "More siblings — better?", style: 'gentle young woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '楽しい家庭になるな。', en: "Lively home.", style: 'soft Kansai husband voice, warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: '大変だけど、幸せ。', en: "Tough but — happy.", style: 'tender young mother voice, soft warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '一緒に、考えていこう。', en: "Think together.", style: 'warm Kansai husband voice, soft warm united delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、ありがとう。', en: "Yeah — thanks.", style: 'soft young wife voice, warm tender grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01702',
    context: 'Sakura interviews Ryosuke-dad about being a father across decades.',
    purpose: 'Writer gathering generational paternity perspective.',
    ambient: 'cafe_afternoon_quiet',
    sound_effects: [],
    target_vocab: ['父親', '時代', '変化', '愛'],
    cast: ['sakura_teen', 'ryosuke_dad'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '昔と今、父親の役割、違いますか?', en: "Past and now — father's role differs?", style: 'curious adult writer voice, soft warm professional inquiry delivered carefully' },
      { speaker: 'ryosuke_dad', jp: 'うん、すごく変わった。', en: "Yeah — changed a lot.", style: 'warm middle-aged father voice, soft reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どんな変化でしたか?', en: "What kind of change?", style: 'gentle adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'ryosuke_dad', jp: '家事、育児、もっと関わる時代に。', en: "Housework, childcare — more involved era.", style: 'soft father voice, warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '愛の表現も、変わりましたか?', en: "Love expression — changed too?", style: 'thoughtful adult writer voice, soft warm probing delivery carefully' },
      { speaker: 'ryosuke_dad', jp: 'ええ、もっと素直に伝えるように。', en: "Yes — more openly conveyed.", style: 'gentle father voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: 'いい記事になりそうです。', en: "Going to make a good article.", style: 'warm adult writer voice, soft professional delivery carefully' },
    ],
  },
  {
    id: 'conv_01703',
    context: 'Hina-young goes alone for the first time on a train trip to visit Mei.',
    purpose: 'Teen taking independence step; phone call with parent.',
    ambient: 'train_window_low',
    sound_effects: [],
    target_vocab: ['一人', '電車', '到着', '安心'],
    cast: ['hina_child', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、電車、乗れた!', en: "Mei — caught the train!", style: 'bright teen girl voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'すごい、一人で立派ね。', en: "Wow — alone, splendid.", style: 'warm young woman voice, soft tender proud delivery carefully' },
      { speaker: 'hina_child', jp: 'ドキドキしたけど、大丈夫。', en: "Heart pounded but — fine.", style: 'soft teen girl voice, warm honest cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '到着したら、連絡してね。', en: "When arrived — contact me.", style: 'gentle young woman voice, soft warm caring delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、待っててね!', en: "Yeah — wait for me!", style: 'cheerful teen girl voice, bright warm eager delivery carefully' },
    ],
  },
  {
    id: 'conv_01704',
    context: 'Saito asks Ren about his views on death, philosophically.',
    purpose: 'Doctor and young man having deep philosophical conversation.',
    ambient: 'cafe_evening_lamp',
    sound_effects: [],
    target_vocab: ['死', '生', '意味', '考える'],
    cast: ['saito_doctor', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '死について、考えますか?', en: "About death — do you think?", style: 'measured doctor voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: 'たまに、考えます。', en: "Occasionally — yes.", style: 'soft young man voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '生の意味、見出せますか?', en: "Find life's meaning?", style: 'gentle doctor voice, soft warm probing delivery carefully' },
      { speaker: 'ren_uni', jp: '人と、繋がること、かな。', en: "Connecting with people — maybe.", style: 'thoughtful young man voice, soft warm earnest delivery carefully' },
      { speaker: 'saito_doctor', jp: '素敵な答えですね。', en: "Lovely answer.", style: 'warm doctor voice, soft tender appreciative delivery carefully' },
      { speaker: 'ren_uni', jp: '先生は、どうお考え?', en: "Doctor — your thoughts?", style: 'soft young man voice, warm respectful curious delivery carefully' },
      { speaker: 'saito_doctor', jp: '私も、人との関わりや。', en: "Same — human connection.", style: 'gentle doctor voice, soft warm humble delivery carefully' },
    ],
  },
  {
    id: 'conv_01705',
    context: 'Kenji takes baby news quietly to his old mentor Hiroshi-elder.',
    purpose: 'Adult sharing big personal joy with elder figure.',
    ambient: 'tatami_room_quiet',
    sound_effects: [],
    target_vocab: ['赤ちゃん', '父', '心', '伝える'],
    cast: ['kenji_office', 'hiroshi_elder'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: 'おとうさん、報告がありますわ。', en: "Otosan — a report.", style: 'soft Kansai man voice, warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、何や?', en: "Yeah — what?", style: 'gentle elder Kansai voice, soft warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: '蒼が、妊娠したんです。', en: "Aoi — got pregnant.", style: 'soft Kansai man voice, warm tender announcing delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんまか!めでたいで!', en: "Truly? Auspicious!", style: 'animated elder Kansai voice, bright warm delighted delivery carefully' },
      { speaker: 'kenji_office', jp: '心、温い言葉、ありがとうございます。', en: "Heart — warm words, thank you.", style: 'tender Kansai man voice, soft warm grateful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_085 wrote', CONVERSATIONS.length, 'files');
