import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_075)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01486',
    context: 'Sho and Hina go to the train station for a short school trip; they buy tickets together.',
    purpose: 'Teen siblings navigating travel logistics for the first time alone.',
    ambient: 'station_announcements_low',
    sound_effects: [],
    target_vocab: ['駅', '切符', '到着', '出発'],
    cast: ['sho_child', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '切符、ここで買うんやんな?', en: "We buy tickets here, right?", style: 'curious teen boy voice, soft uncertain inquiring warmth delivered carefully' },
      { speaker: 'hina_child', jp: 'うん、自動販売機からね。', en: "Yeah — from the vending machine.", style: 'composed teen girl voice, soft confident helpful warmth delivered carefully' },
      { speaker: 'sho_child', jp: '出発、何時やったっけ?', en: "What time was departure?", style: 'absent-minded teen boy voice, soft scattered honest delivery warmly carefully' },
      { speaker: 'hina_child', jp: '十時半、まだ余裕ある。', en: "Ten thirty — we've got time.", style: 'calm teen girl voice, soft reassuring competent warmth delivered carefully' },
      { speaker: 'sho_child', jp: '到着までどれくらいかかる?', en: "How long until arrival?", style: 'curious teen boy voice, soft eager travel-prep warmth delivered carefully' },
      { speaker: 'hina_child', jp: '一時間ちょっとかな。', en: "An hour and a bit.", style: 'thoughtful teen girl voice, soft careful estimating warmth delivered carefully' },
      { speaker: 'sho_child', jp: 'ちょっと冒険みたいやな。', en: "Feels a bit like an adventure.", style: 'excited teen boy voice, soft bright eager warmth delivered cheerfully carefully' },
      { speaker: 'hina_child', jp: 'うん、楽しもう!', en: "Yeah — let's enjoy it!", style: 'bright teen girl voice, soft warm cheerful encouragement delivered carefully' },
    ],
  },
  {
    id: 'conv_01487',
    context: 'Mei and Yumiko visit a small tourist spot on a weekday morning.',
    purpose: 'Mother and daughter-in-law enjoying gentle sightseeing.',
    ambient: 'shrine_grounds_breeze',
    sound_effects: [],
    target_vocab: ['観光', '名所', '写真', '撮る', '景色'],
    cast: ['mei_romantic', 'yumiko_mom'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'ここ、有名な名所なのよ。', en: "This is a famous spot, you know.", style: 'gentle older mother voice, soft warm informative cultured delivery carefully' },
      { speaker: 'mei_romantic', jp: '写真撮りましょうか?', en: "Shall we take a photo?", style: 'warm young woman voice, soft eager polite suggestion delivered carefully' },
      { speaker: 'yumiko_mom', jp: 'ええ、お願いね。', en: "Yes — please.", style: 'soft older mother voice, warm gracious gentle agreement delivered carefully' },
      { speaker: 'mei_romantic', jp: '景色、本当に綺麗ですね。', en: "The scenery is truly beautiful.", style: 'soft young woman voice, warm awed reverent appreciation delivered carefully' },
      { speaker: 'yumiko_mom', jp: '観光客も多いけど、静かな時間。', en: "Many tourists, but a quiet moment.", style: 'gentle older woman voice, soft reflective wise warmth delivered carefully' },
      { speaker: 'mei_romantic', jp: '撮りますよ、笑ってください。', en: "Taking it now — please smile.", style: 'cheerful young woman voice, soft warm playful direction delivered carefully' },
      { speaker: 'yumiko_mom', jp: 'はい、チーズ。', en: "Yes — cheese.", style: 'warm older mother voice, soft playful gentle smile delivered carefully' },
    ],
  },
  {
    id: 'conv_01488',
    context: 'Kenji and Daichi help an elderly neighbor with a small building repair.',
    purpose: 'Two friends doing neighborly community labor; brief practical exchange.',
    ambient: 'outdoor_hammer_distant',
    sound_effects: [],
    target_vocab: ['建物', '壁', '屋根', '工事'],
    cast: ['kenji_office', 'daichi_kansai'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'この壁、結構傷んどるな。', en: "This wall's pretty damaged.", style: 'thoughtful Kansai man voice, soft observant honest assessment delivered carefully' },
      { speaker: 'kenji_office', jp: '屋根も、見ておこか。', en: "Let's check the roof too.", style: 'soft Kansai artist voice, warm practical careful delivery gently carefully' },
      { speaker: 'daichi_kansai', jp: '本格的な工事、必要やな。', en: "Proper construction is needed.", style: 'resolved Kansai man voice, soft warm honest professional delivery carefully' },
      { speaker: 'kenji_office', jp: 'おじいさん、一人で住んではる。', en: "The old man lives alone.", style: 'soft Kansai artist voice, warm caring community-minded delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'みんなで手伝わなあかんな。', en: "We've all got to help.", style: 'warm Kansai man voice, soft determined neighborly resolve delivered carefully' },
      { speaker: 'kenji_office', jp: '今度の週末、集めよか。', en: "Let's gather this weekend.", style: 'gentle Kansai artist, soft warm organizational planning delivered carefully' },
      { speaker: 'daichi_kansai', jp: 'ええな、声かけとくわ。', en: "Sounds good — I'll spread the word.", style: 'soft Kansai husband voice, warm committed practical follow-through delivered carefully' },
    ],
  },
  {
    id: 'conv_01489',
    context: 'Sakura asks for directions in an unfamiliar neighborhood; Naoko helps.',
    purpose: 'A polite stranger encounter; warm Kansai directness meets reserved writer.',
    ambient: 'street_corner_quiet',
    sound_effects: [],
    target_vocab: ['道順', '案内', '地図', '曲がる'],
    cast: ['sakura_teen', 'naoko_aunt'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'すみません、道順を教えてください。', en: "Excuse me — could you tell me the way?", style: 'polite adult writer voice, soft formal hesitant warmth delivered carefully' },
      { speaker: 'naoko_aunt', jp: 'どこ行きたいん?地図ある?', en: "Where to? Got a map?", style: 'brisk Kansai aunt voice, bright sharp practical warmth delivered carefully' },
      { speaker: 'sakura_teen', jp: 'はい、ここのカフェまで。', en: "Yes — to this cafe here.", style: 'soft adult writer voice, gentle polite earnest warmth delivered carefully' },
      { speaker: 'naoko_aunt', jp: '次の角、右に曲がるねん。', en: "Next corner, turn right.", style: 'animated Kansai aunt voice, bright direct helpful warmth delivered carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとうございます、助かります。', en: "Thank you — that helps.", style: 'grateful adult writer voice, soft sincere warm relief delivered carefully' },
    ],
  },
  {
    id: 'conv_01490',
    context: 'Aoi and Ren discuss a recent piece of art; long deep discussion about meaning.',
    purpose: 'Two thoughtful adults examining a work of art in detail.',
    ambient: 'gallery_quiet_floor',
    sound_effects: [],
    target_vocab: ['作品', '意味', '感じる', '表現', '色'],
    cast: ['aoi_barista', 'ren_uni'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'この作品、何を表現してるのかな。', en: "What is this work expressing?", style: 'thoughtful adult woman voice, soft curious gentle inquiry delivered carefully' },
      { speaker: 'ren_uni', jp: '色の使い方、すごく繊細です。', en: "The use of color is very delicate.", style: 'soft young artist voice, warm analytical reverent observation delivered carefully' },
      { speaker: 'aoi_barista', jp: '青と灰色の組み合わせ、好き。', en: "I love the blue and gray pairing.", style: 'warm adult woman voice, soft fond aesthetic appreciation delivered carefully' },
      { speaker: 'ren_uni', jp: '孤独を感じるけど、優しい。', en: "It feels lonely but kind.", style: 'gentle young man voice, soft contemplative emotional perception delivered carefully' },
      { speaker: 'aoi_barista', jp: '作家の意図、伝わってくるね。', en: "The artist's intent comes through.", style: 'thoughtful adult woman voice, soft warm intellectual agreement delivered carefully' },
      { speaker: 'ren_uni', jp: '光の表現も、独特です。', en: "The light's rendering is unique.", style: 'engaged young artist voice, soft warm professional admiration delivered carefully' },
      { speaker: 'aoi_barista', jp: 'これ、長く眺めていたい。', en: "I want to gaze at this for long.", style: 'soft adult woman voice, warm contemplative drawn-in warmth delivered carefully' },
      { speaker: 'ren_uni', jp: '何度見ても発見がありそう。', en: "Each viewing reveals something new.", style: 'soft young man voice, warm hopeful intellectual delight delivered carefully' },
      { speaker: 'aoi_barista', jp: 'こういう時間、贅沢ね。', en: "Moments like this are a luxury.", style: 'tender adult woman voice, soft reflective grateful warmth delivered carefully' },
      { speaker: 'ren_uni', jp: '蒼さん、感想ありがとうございます。', en: "Aoi-san, thank you for sharing.", style: 'humble young man voice, soft sincere warm gratitude delivered carefully' },
      { speaker: 'aoi_barista', jp: 'こちらこそ、楽しい時間だった。', en: "Likewise — a lovely time.", style: 'warm adult woman voice, soft genuine reflective gratitude delivered carefully' },
      { speaker: 'ren_uni', jp: 'また一緒に観に来ましょう。', en: "Let's come view again together.", style: 'soft young man voice, warm hopeful gentle invitation delivered carefully' },
      { speaker: 'aoi_barista', jp: 'うん、是非。', en: "Yes — by all means.", style: 'tender adult woman voice, soft warm enthusiastic agreement delivered carefully' },
    ],
  },
  {
    id: 'conv_01491',
    context: 'Hiroshi-elder and a curious child Sho talk on the porch about the old days.',
    purpose: 'Grandfather teaching young boy with patient stories.',
    ambient: 'porch_late_afternoon',
    sound_effects: [],
    target_vocab: ['昔', '若い', '子供', '時代'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、昔って何してたん?', en: "Grandpa, what did you do back then?", style: 'curious teen boy voice, soft eager attentive warmth delivered carefully' },
      { speaker: 'hiroshi_elder', jp: '若い頃は、田んぼ手伝うてた。', en: "When young — helped in the paddies.", style: 'slow elder Kansai voice, warm weathered nostalgic recollection delivered carefully' },
      { speaker: 'sho_child', jp: 'えー、子供から働いてたん?', en: "Whoa — worked from childhood?", style: 'surprised teen boy voice, soft awed honest reaction delivered carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、その時代はみんなそうや。', en: "Yeah — in that era everyone did.", style: 'gentle elder Kansai voice, soft warm matter-of-fact wisdom delivered carefully' },
      { speaker: 'sho_child', jp: 'すごいなぁ、大変やったね。', en: "Wow, that must've been tough.", style: 'admiring teen boy voice, soft warm empathetic appreciation delivered carefully' },
      { speaker: 'hiroshi_elder', jp: '当たり前やったんや、ほんま。', en: "It was just normal, really.", style: 'soft elder Kansai voice, warm quiet humble reflection delivered carefully' },
      { speaker: 'sho_child', jp: 'もっと聞きたい!', en: "I want to hear more!", style: 'eager teen boy voice, bright enthusiastic warm curiosity delivered carefully' },
    ],
  },
  {
    id: 'conv_01492',
    context: 'Sakura plays in the park with Sho-young on a warm spring day.',
    purpose: 'Adult writer babysitting a child cousin; gentle play.',
    ambient: 'park_birds_breeze',
    sound_effects: [],
    target_vocab: ['公園', 'ベンチ', '広場', '遊ぶ'],
    cast: ['sakura_teen', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'さくらねえちゃん、ブランコ乗りたい!', en: "Sakura — I want to ride the swing!", style: 'excited child boy voice, bright eager warm energy delivered cheerfully carefully' },
      { speaker: 'sakura_teen', jp: 'うん、広場まで行こう。', en: "Yeah — let's head to the open area.", style: 'soft adult woman voice, warm patient encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'ベンチで休んでてもいいよ!', en: "You can rest on the bench!", style: 'thoughtful child boy voice, bright considerate sweet warmth delivered carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとう、見てるね。', en: "Thanks — I'll watch.", style: 'gentle adult woman voice, soft warm fond agreement delivered carefully' },
      { speaker: 'sho_child', jp: '見てて!高く飛ぶよ!', en: "Watch me — I'll fly high!", style: 'energetic child boy voice, bright bold cheerful warmth delivered carefully' },
    ],
  },
  {
    id: 'conv_01493',
    context: 'Yumiko helps Mei find her way back at a busy department store after they lose each other.',
    purpose: 'Family member helps another navigate; brief reunion relief.',
    ambient: 'department_store_low',
    sound_effects: [],
    target_vocab: ['迷子', '案内', '受付', '見つける'],
    cast: ['yumiko_mom', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'お母さん、迷子になっちゃった。', en: "Mom — I got lost.", style: 'flustered young woman voice, soft worried relieved warmth delivered carefully' },
      { speaker: 'yumiko_mom', jp: '受付で待ってたのよ、よかった。', en: "I waited at the desk — thank goodness.", style: 'relieved older mother voice, soft warm tender release delivered carefully' },
      { speaker: 'mei_romantic', jp: '案内、わかりにくかった。', en: "The signs were hard to follow.", style: 'soft young woman voice, warm tired honest admission delivered carefully' },
      { speaker: 'yumiko_mom', jp: '見つけてもらえて、安心。', en: "Glad you found me — relief.", style: 'tender older mother voice, soft warm grateful warmth delivered carefully' },
      { speaker: 'mei_romantic', jp: '次は離れずにいるね。', en: "Next time I'll stick close.", style: 'soft young woman voice, warm apologetic gentle resolve delivered carefully' },
    ],
  },
  {
    id: 'conv_01494',
    context: 'Saito and Asuka discuss community health education for schoolchildren.',
    purpose: 'Doctor and teacher coordinating outreach professionally.',
    ambient: 'school_office_quiet',
    sound_effects: [],
    target_vocab: ['健康', '教育', '生徒', '計画'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '生徒の健康教育、どう進めますか?', en: "How should we proceed with health education?", style: 'composed teacher voice, soft professional collaborative inquiry delivered carefully' },
      { speaker: 'saito_doctor', jp: 'まず食生活から始めましょう。', en: "Let's start with diet.", style: 'measured doctor voice, soft professional clear planning delivered carefully' },
      { speaker: 'asuka_teacher', jp: '保護者にも知らせたほうがいいですね。', en: "We should inform the guardians too.", style: 'thoughtful teacher voice, soft professional cooperative careful delivery carefully' },
      { speaker: 'saito_doctor', jp: '計画を一緒に立てましょう。', en: "Let's plan it together.", style: 'warm doctor voice, soft collaborative professional warmth delivered carefully' },
      { speaker: 'asuka_teacher', jp: '来月から、試験的に始めますか?', en: "Shall we start a trial next month?", style: 'engaged teacher voice, soft professional forward-leaning warmth delivered carefully' },
      { speaker: 'saito_doctor', jp: 'いいですね、賛成です。', en: "Sounds good — I agree.", style: 'warm doctor voice, soft professional affirmative warmth delivered carefully' },
      { speaker: 'asuka_teacher', jp: 'ご協力、ありがとうございます。', en: "Thank you for your cooperation.", style: 'gracious teacher voice, soft warm professional sincere gratitude delivered carefully' },
    ],
  },
  {
    id: 'conv_01495',
    context: 'Hina and Aoi spot a stray kitten near the cafe and decide what to do.',
    purpose: 'Spontaneous animal-rescue moment between teen and adult.',
    ambient: 'alley_cafe_evening',
    sound_effects: [],
    target_vocab: ['猫', '怪我', '優しい', '助ける'],
    cast: ['hina_child', 'aoi_barista'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'あっ、猫が震えてる。', en: "Oh — a kitten's shivering.", style: 'soft worried teen girl voice, warm gentle concern delivered carefully' },
      { speaker: 'aoi_barista', jp: '怪我してるかも、優しく近づこう。', en: "It may be hurt — approach gently.", style: 'tender adult woman voice, soft careful instructive warmth delivered carefully' },
      { speaker: 'hina_child', jp: '冷たい体、可哀想。', en: "Cold body — poor thing.", style: 'soft teen girl voice, warm compassionate gentle delivery carefully' },
      { speaker: 'aoi_barista', jp: 'タオル持ってくるね、待ってて。', en: "I'll get a towel — wait here.", style: 'practical adult woman voice, soft warm reassuring action delivered carefully' },
      { speaker: 'hina_child', jp: 'うん、助けたい。', en: "Yeah — I want to help.", style: 'soft determined teen girl voice, warm resolved compassionate delivery carefully' },
    ],
  },
  {
    id: 'conv_01496',
    context: 'Sho-child and Ren make a paper airplane together.',
    purpose: 'Adult and child quiet bonding through small craft.',
    ambient: 'living_room_quiet_paper',
    sound_effects: [],
    target_vocab: ['紙', '折る', '飛ぶ', '形'],
    cast: ['sho_child', 'ren_uni'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '蓮にいちゃん、紙ヒコーキ作って!', en: "Ren — make a paper plane!", style: 'eager child boy voice, bright cheerful warm request delivered cheerfully carefully' },
      { speaker: 'ren_uni', jp: 'よし、一緒に折ろう。', en: "Sure — let's fold one together.", style: 'soft young man voice, warm patient encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'この形、難しいなぁ。', en: "This shape's tricky.", style: 'concentrated child boy voice, soft warm focused effort delivered carefully' },
      { speaker: 'ren_uni', jp: 'ゆっくり、丁寧に折ろうね。', en: "Slowly, carefully.", style: 'gentle young man voice, soft warm instructive patience delivered carefully' },
      { speaker: 'sho_child', jp: '飛んだ、見て見て!', en: "It flew — look look!", style: 'thrilled child boy voice, bright cheerful proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01497',
    context: 'Daichi and Mei have a sweet late-evening porch conversation about gratitude.',
    purpose: 'Married couple bonding tenderly; reflecting on small daily joys.',
    ambient: 'porch_night_crickets',
    sound_effects: [],
    target_vocab: ['夜', '星', '感謝', '幸せ'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '星、ようけ見えるな。', en: "So many stars.", style: 'soft Kansai husband voice, warm fond contemplative delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ね、こんな夜は静か。', en: "Yeah — such a quiet night.", style: 'tender young woman voice, soft warm peaceful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前と居ると、幸せやわ。', en: "With you — I'm happy.", style: 'soft Kansai husband voice, warm sincere loving delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ふふ、急にどうしたの?', en: "Heh — what's gotten into you?", style: 'gentle young wife voice, soft warm teasing affectionate delivery carefully' },
      { speaker: 'daichi_kansai', jp: '感謝の気持ち、伝えたかってん。', en: "Wanted to express my gratitude.", style: 'soft Kansai husband voice, warm earnest tender delivery carefully' },
      { speaker: 'mei_romantic', jp: '私も、本当に感謝してる。', en: "I'm grateful too — truly.", style: 'tender young woman voice, soft warm sincere gratitude delivered carefully' },
      { speaker: 'daichi_kansai', jp: 'ずっと一緒におろうな。', en: "Let's stay together always.", style: 'soft Kansai husband voice, warm tender lifelong promise delivered carefully' },
    ],
  },
  {
    id: 'conv_01498',
    context: 'Naoko and Kenji at the ramen shop bantering about cooking philosophy.',
    purpose: 'Two strong personalities sharing food humor with warmth underneath.',
    ambient: 'ramen_shop_steam',
    sound_effects: [],
    target_vocab: ['ラーメン', '麺', 'スープ', '塩'],
    cast: ['naoko_aunt', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'うちのスープ、特別やで?', en: "Our soup's special, you know?", style: 'brassy Kansai aunt voice, bright proud playful warmth delivered carefully' },
      { speaker: 'kenji_office', jp: 'はい、毎回美味しいです。', en: "Yes — delicious every time.", style: 'polite Kansai man voice, soft warm sincere appreciation delivered carefully' },
      { speaker: 'naoko_aunt', jp: '塩加減が命なんよ、塩。', en: "It all hangs on the salt level.", style: 'animated Kansai aunt voice, bright sharp passionate delivery carefully' },
      { speaker: 'kenji_office', jp: '麺もコシがあって、ええなぁ。', en: "The noodles have great chew, too.", style: 'soft Kansai man voice, warm fond food-appreciation delivered carefully' },
      { speaker: 'naoko_aunt', jp: '当たり前や、毎日打ってんねん。', en: "Of course — I make them fresh daily.", style: 'proud Kansai aunt voice, bright loud emphatic warmth delivered carefully' },
      { speaker: 'kenji_office', jp: 'ナオコさん、ほんま尊敬するわ。', en: "Naoko-san, I genuinely admire you.", style: 'soft Kansai man voice, warm sincere respectful admiration delivered carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、もう一杯食べてき!', en: "Heh — eat another bowl!", style: 'warm Kansai aunt voice, brassy generous loving warmth delivered cheerfully carefully' },
    ],
  },
  {
    id: 'conv_01499',
    context: 'Sakura takes Hina-young to a small library; book recommendation moment.',
    purpose: 'Adult writer mentoring young child reader.',
    ambient: 'library_hush_pages',
    sound_effects: [],
    target_vocab: ['図書館', '本', '物語', '主人公'],
    cast: ['sakura_teen', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、どの本がいい?', en: "Sakura — which book is good?", style: 'soft eager teen girl voice, warm gentle curious delivery carefully' },
      { speaker: 'sakura_teen', jp: 'この物語、主人公が優しいよ。', en: "This story — the hero is kind.", style: 'tender adult writer voice, soft warm recommending delivery carefully' },
      { speaker: 'hina_child', jp: '面白そう、長い?', en: "Sounds fun — is it long?", style: 'curious teen girl voice, soft eager warm question delivered carefully' },
      { speaker: 'sakura_teen', jp: 'ちょうど一週間で読めるよ。', en: "Perfectly readable in a week.", style: 'warm adult writer voice, soft helpful encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '主人公の名前、なんていうの?', en: "What's the hero's name?", style: 'attentive teen girl voice, soft warm engaged inquiry delivered carefully' },
      { speaker: 'sakura_teen', jp: '読んでからのお楽しみね。', en: "That's a surprise for after reading.", style: 'playful adult writer voice, soft warm teasing affectionate delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、楽しみ!', en: "Yeah — looking forward to it!", style: 'bright teen girl voice, soft warm cheerful anticipation delivered carefully' },
    ],
  },
  {
    id: 'conv_01500',
    context: 'Kenji marks his 1500th conversation written; the family gathers to celebrate quietly.',
    purpose: 'A milestone family-and-friends moment; gentle round of toasts.',
    ambient: 'dining_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['節目', '集まる', '乾杯', '幸せ', '一緒'],
    cast: ['kenji_office', 'aoi_barista', 'sakura_teen', 'ren_uni', 'mei_romantic', 'daichi_kansai'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: 'みんな、よう集まってくれたな。', en: "Everyone — thanks for gathering.", style: 'warm Kansai man voice, soft fond grateful host delivery carefully' },
      { speaker: 'aoi_barista', jp: '節目だもの、お祝いしないと。', en: "It's a milestone — must celebrate.", style: 'tender adult woman voice, soft warm cheerful encouragement delivered carefully' },
      { speaker: 'sakura_teen', jp: '本当に、長い道のりだったね。', en: "Truly, a long road.", style: 'reflective adult writer voice, soft warm fond recognition delivered carefully' },
      { speaker: 'ren_uni', jp: '健司さん、お疲れさまでした。', en: "Kenji-san, well done.", style: 'humble young man voice, soft warm respectful appreciation delivered carefully' },
      { speaker: 'mei_romantic', jp: 'みんなと一緒、本当に幸せ。', en: "With everyone — truly happy.", style: 'tender young woman voice, soft warm content gentle delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ほな、乾杯やな。', en: "Right then — toast!", style: 'bright Kansai husband voice, soft warm celebratory delivery carefully' },
      { speaker: 'kenji_office', jp: 'はい、みんなに感謝。乾杯!', en: "Yes — gratitude to all. Cheers!", style: 'warm Kansai voice, soft proud tender toast delivered carefully' },
      { speaker: 'aoi_barista', jp: '健ちゃん、これからもね。', en: "Ken-chan, going forward too.", style: 'tender adult woman voice, soft warm loving promise delivered carefully' },
      { speaker: 'sakura_teen', jp: '次の節目も、一緒に祝おう。', en: "Next milestone — celebrate together too.", style: 'warm adult writer voice, soft fond commitment delivered carefully' },
      { speaker: 'ren_uni', jp: '本当に、いい時間です。', en: "Truly, a good moment.", style: 'soft young man voice, warm content quiet appreciation delivered carefully' },
      { speaker: 'mei_romantic', jp: 'こうやって続いていくこと、嬉しい。', en: "Happy this keeps going.", style: 'tender young mother voice, soft warm forward-hope delivered carefully' },
      { speaker: 'daichi_kansai', jp: '家族ってええもんやな。', en: "Family is a good thing.", style: 'soft Kansai husband voice, warm content tender delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほんま、ありがたい夜や。', en: "Truly, a night of gratitude.", style: 'warm Kansai man voice, soft tender humble appreciation delivered carefully' },
    ],
  },
  {
    id: 'conv_01501',
    context: 'Hiroshi-elder gives Ren some quiet advice about how to listen to people.',
    purpose: 'Elder passing on wisdom about communication.',
    ambient: 'tatami_room_quiet',
    sound_effects: [],
    target_vocab: ['聞く', '相手', '言葉', '心'],
    cast: ['hiroshi_elder', 'ren_uni'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'おじいさん、人の話、苦手で。', en: "Grandpa — I struggle to listen.", style: 'soft young man voice, warm honest vulnerable delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '聞くことは、相手を見ることや。', en: "Listening is seeing the other.", style: 'slow elder Kansai voice, warm wise weighted delivery carefully' },
      { speaker: 'ren_uni', jp: '言葉じゃなくて、心ですか。', en: "Not words — the heart?", style: 'thoughtful young man voice, soft warm earnest understanding delivered carefully' },
      { speaker: 'hiroshi_elder', jp: 'そうや、目で聞くんや。', en: "Yes — listen with your eyes.", style: 'gentle elder Kansai voice, slow warm teaching wisdom delivered carefully' },
      { speaker: 'ren_uni', jp: 'なるほど、難しいですね。', en: "I see — that's hard.", style: 'soft young man voice, warm humble honest reflection delivered carefully' },
      { speaker: 'hiroshi_elder', jp: '一生かかるんや、人を聞くのは。', en: "Listening to people — a lifetime.", style: 'soft elder Kansai voice, warm philosophical reflective delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、覚えておきます。', en: "Yes — I'll remember.", style: 'humble young man voice, soft warm respectful commitment delivered carefully' },
    ],
  },
  {
    id: 'conv_01502',
    context: 'Asuka teaches Sho-young how to ride a bicycle in the empty parking lot.',
    purpose: 'Teacher figure patiently teaching a child a new physical skill.',
    ambient: 'parking_lot_breeze',
    sound_effects: [],
    target_vocab: ['自転車', '練習', 'バランス', '進む'],
    cast: ['asuka_teacher', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'バランス取って、ゆっくり進んで。', en: "Balance and go slowly.", style: 'gentle teacher voice, soft warm instructional patient delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、頑張る!', en: "Yeah — I'll try!", style: 'eager child boy voice, bright cheerful determined warmth delivered carefully' },
      { speaker: 'asuka_teacher', jp: 'いいね、その調子。', en: "Good — keep going.", style: 'encouraging teacher voice, soft warm gentle praise delivered carefully' },
      { speaker: 'sho_child', jp: 'あっ、転んじゃった!', en: "Oh — I fell!", style: 'startled child boy voice, soft warm honest exclamation delivered carefully' },
      { speaker: 'asuka_teacher', jp: '大丈夫、もう一回。', en: "It's okay — one more time.", style: 'gentle teacher voice, soft warm patient encouragement delivered carefully' },
      { speaker: 'sho_child', jp: 'やってみる、見ててね!', en: "I'll try — watch me!", style: 'resolved child boy voice, soft warm brave determination delivered carefully' },
      { speaker: 'asuka_teacher', jp: 'うん、ずっと見てるよ。', en: "Yes — I'm watching.", style: 'warm teacher voice, soft tender supportive delivery carefully' },
    ],
  },
  {
    id: 'conv_01503',
    context: 'Yumiko and Sakura have a quiet morning tea about loss and writing.',
    purpose: 'Two thoughtful women sharing deep emotional reflection.',
    ambient: 'kitchen_morning_tea',
    sound_effects: [],
    target_vocab: ['静か', '時間', '思い', '言葉'],
    cast: ['yumiko_mom', 'sakura_teen'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '静かな朝、ええわね。', en: "A quiet morning is lovely.", style: 'gentle older woman voice, soft warm peaceful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こういう時間、書きたくなる。', en: "Moments like this make me want to write.", style: 'soft adult writer voice, warm reflective contemplative delivery carefully' },
      { speaker: 'yumiko_mom', jp: '言葉、どう選んでるの?', en: "How do you choose words?", style: 'curious older mother voice, soft gentle interested inquiry delivered carefully' },
      { speaker: 'sakura_teen', jp: '心に残った思いを、そのまま。', en: "The lingering feelings — just as they are.", style: 'thoughtful adult writer voice, soft warm honest revealing delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'それは、勇気がいるね。', en: "That takes courage.", style: 'wise older mother voice, soft warm understanding admiration delivered carefully' },
      { speaker: 'sakura_teen', jp: 'はい、でも続けたい。', en: "Yes — but I want to keep going.", style: 'soft adult writer voice, warm resolved gentle commitment delivered carefully' },
      { speaker: 'yumiko_mom', jp: '応援してるよ、いつも。', en: "I'm cheering you on, always.", style: 'tender older mother voice, soft warm steadfast support delivered carefully' },
    ],
  },
  {
    id: 'conv_01504',
    context: 'Daichi takes the family dog for a morning walk; meets Mrs. Mori the neighbor.',
    purpose: 'Casual neighborly greeting; small community warmth.',
    ambient: 'street_morning_birds',
    sound_effects: [],
    target_vocab: ['犬', '散歩', '朝', '挨拶'],
    cast: ['daichi_kansai', 'mrs_mori_neighbor'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'おはようございます、お散歩ですか?', en: "Good morning — taking a walk?", style: 'warm older neighbor voice, soft polite friendly greeting delivered carefully' },
      { speaker: 'daichi_kansai', jp: 'おはようございます、毎朝の日課でな。', en: "Morning — daily routine.", style: 'warm Kansai man voice, soft polite friendly delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '犬、可愛いわね。', en: "The dog's cute.", style: 'gentle older woman voice, soft warm fond observation delivered carefully' },
      { speaker: 'daichi_kansai', jp: '元気だけが取り柄でな。', en: "Energy's its only virtue.", style: 'warm Kansai man voice, soft self-deprecating fond delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふふ、いい朝ですね。', en: "Heh — lovely morning.", style: 'soft older neighbor voice, warm gentle cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01505',
    context: 'Ren and Hiroshi-boss meet at a small cafe to discuss a freelance project.',
    purpose: 'Boss and young freelancer professional yet warm exchange.',
    ambient: 'cafe_business_low',
    sound_effects: [],
    target_vocab: ['契約', '仕事', '依頼', '期限'],
    cast: ['hiroshi_boss', 'ren_uni'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '蓮くん、依頼内容、確認しましょう。', en: "Ren — let's confirm the request.", style: 'authoritative boss voice, soft professional measured delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、よろしくお願いします。', en: "Yes — thank you in advance.", style: 'polite young man voice, soft formal respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '期限は来月の二十日です。', en: "Deadline is the 20th of next month.", style: 'measured boss voice, soft clear professional delivery carefully' },
      { speaker: 'ren_uni', jp: '了解です、間に合わせます。', en: "Understood — I'll meet it.", style: 'soft young man voice, warm respectful committed delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '契約書、後でお送りします。', en: "I'll send the contract later.", style: 'professional boss voice, soft warm clear delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble young man voice, soft sincere grateful warmth delivered carefully' },
      { speaker: 'hiroshi_boss', jp: '今回もよろしくな。', en: "Looking forward this time too.", style: 'warm boss voice, soft trusting professional friendliness delivered carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_075 wrote', CONVERSATIONS.length, 'files');
