import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_101)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02001',
    context: 'Sakura and Yuki-office discuss a televised political program; substantive civic talk.',
    purpose: 'Two adult women parsing a political news program critically.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['政治', '政府', '国民', '委員', '制度', '主張', '議論', '関連'],
    cast: ['sakura_teen', 'yuki_office'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: '今夜の番組、政治の議論、本格的ね。', en: "Tonight's show — political debate, serious.", style: 'composed office woman voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '委員の方々、強く主張してる。', en: "Committee folks — strongly arguing.", style: 'thoughtful adult writer voice, soft warm observant delivery carefully' },
      { speaker: 'yuki_office', jp: '政府の制度、関連した話題ね。', en: "Government system — related topic.", style: 'soft office woman voice, warm intellectual delivery carefully' },
      { speaker: 'sakura_teen', jp: '国民の声、ちゃんと届いてるかな。', en: "National voice — properly reaching?", style: 'gentle adult writer voice, soft warm probing delivery carefully' },
      { speaker: 'yuki_office', jp: '若い世代の主張、もっと反映されるべき。', en: "Young gen claims — more reflected should.", style: 'firm office woman voice, soft warm passionate delivery carefully' },
      { speaker: 'sakura_teen', jp: '議論、こうやって、続けるのが大事。', en: "Debate — like this, continuing matters.", style: 'warm adult writer voice, soft committed delivery carefully' },
      { speaker: 'yuki_office', jp: 'うん、私たちも、考え続けないとね。', en: "Yeah — we too, must keep thinking.", style: 'tender office woman voice, soft warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02002',
    context: 'Hiroshi-boss negotiates a small business deal with another company representative.',
    purpose: 'Business meeting; commercial vocabulary in context.',
    ambient: 'office_meeting_low',
    sound_effects: [],
    target_vocab: ['企業', '経営', '投資', '取引', '戦略', '提供', '製品', '可能'],
    cast: ['hiroshi_boss', 'kenji_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '今回の取引、お互いの企業に利点があります。', en: "This deal — both companies, advantages.", style: 'measured boss voice, soft professional clear delivery carefully' },
      { speaker: 'kenji_office', jp: '提供する製品、品質、確実です。', en: "Provided product — quality, certain.", style: 'composed Kansai man voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '長期的な投資、可能ですか?', en: "Long-term investment — possible?", style: 'professional boss voice, soft warm probing delivery carefully' },
      { speaker: 'kenji_office', jp: '戦略次第、経営判断によって変わります。', en: "Strategy depends — by management.", style: 'soft Kansai man voice, warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '今後の展開、検討させてください。', en: "Future development — let me consider.", style: 'gentle boss voice, soft warm thoughtful delivery carefully' },
      { speaker: 'kenji_office', jp: 'はい、お返事、お待ちしております。', en: "Yes — reply, awaiting.", style: 'humble Kansai man voice, soft warm respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '良いお取引になれば、と願っています。', en: "Good deal — hoping.", style: 'warm boss voice, soft hopeful professional delivery carefully' },
    ],
  },
  {
    id: 'conv_02003',
    context: 'Saito at a small medical conference discussing health policy.',
    purpose: 'Doctor in professional academic context with peer.',
    ambient: 'conference_hall_low',
    sound_effects: [],
    target_vocab: ['医療', '制度', '分野', '報告', '改革', '主張', '議論', '結局'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '医療の分野、改革が必要だと考えています。', en: "Medical field — reform needed, I think.", style: 'measured doctor voice, soft professional thoughtful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '具体的に、どの制度が問題なのですか?', en: "Specifically — which system problem?", style: 'engaged teacher voice, soft warm professional inquiry delivered carefully' },
      { speaker: 'saito_doctor', jp: '地方の医療体制、特に。', en: "Rural medical setup — especially.", style: 'soft doctor voice, warm warm focused delivery carefully' },
      { speaker: 'asuka_teacher', jp: '報告書、どこに提出されるの?', en: "Report — where submitted?", style: 'composed teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'saito_doctor', jp: '厚生労働省、それから関係機関へ。', en: "Health Labor Ministry — then related bodies.", style: 'measured doctor voice, soft warm professional delivery carefully' },
      { speaker: 'asuka_teacher', jp: '主張、ちゃんと届くといいですね。', en: "Argument — reaches well, hope.", style: 'tender teacher voice, soft warm hopeful delivery carefully' },
      { speaker: 'saito_doctor', jp: '議論を、社会全体で続けたい。', en: "Debate — society-wide continue.", style: 'firm doctor voice, soft warm committed delivery carefully' },
      { speaker: 'asuka_teacher', jp: '結局、皆で考えることが、大切ですね。', en: "After all — all thinking matters.", style: 'warm teacher voice, soft warm agreeing delivery carefully' },
    ],
  },
  {
    id: 'conv_02004',
    context: 'Kenji and Ren at editorial meeting; reviewing a magazine layout.',
    purpose: 'Editorial professionals reviewing publication details.',
    ambient: 'office_papers_quiet',
    sound_effects: [],
    target_vocab: ['編集', '掲載', '出版', '版', '構造', 'テーマ', '号', '原稿'],
    cast: ['kenji_office', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '今月の号、テーマ、明確やな。', en: "This month's issue — theme, clear.", style: 'soft Kansai mentor voice, warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '編集の構造、シンプルに整えました。', en: "Edit structure — simply arranged.", style: 'composed young man voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: '原稿、どの順番で掲載する?', en: "Manuscript — what order publish?", style: 'gentle Kansai man voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '冒頭、地方の取材記事を。', en: "Opening — rural coverage article.", style: 'soft young man voice, warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ判断や、出版日、間に合いそう?', en: "Fine call — publish day, in time?", style: 'warm Kansai mentor voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '今週末までに、版、固める予定です。', en: "By weekend — version, finalize.", style: 'committed young man voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: '今後の編集方針、来月相談しよか。', en: "Future edit policy — next month consult.", style: 'soft Kansai man voice, warm warm collaborative delivery carefully' },
    ],
  },
  {
    id: 'conv_02005',
    context: 'Asuka gives a science lecture; students Hina and Sho attend.',
    purpose: 'Teacher in academic teaching mode with intellectual vocab.',
    ambient: 'lecture_hall_quiet',
    sound_effects: [],
    target_vocab: ['科学', '分野', '理論', '実験', '研究', '可能', '関連', '例えば'],
    cast: ['asuka_teacher', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '今日の科学の分野、面白い理論を紹介します。', en: "Today science field — interesting theory introduce.", style: 'warm teacher voice, soft warm professional delivery carefully' },
      { speaker: 'hina_child', jp: '先生、研究、誰がしてるんですか?', en: "Teacher — research, who doing?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '関連する分野、世界中で研究中。', en: "Related fields — worldwide researching.", style: 'gentle teacher voice, soft warm informative delivery carefully' },
      { speaker: 'hina_child', jp: '実験、私たちもできますか?', en: "Experiment — we too can?", style: 'eager teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '可能ですよ、例えば、こんな方法で。', en: "Possible — for example, this way.", style: 'warm teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'すごい、やってみたい!', en: "Wow — want try!", style: 'thrilled teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '次回、実験室で一緒にやりましょう。', en: "Next time — lab together do.", style: 'tender teacher voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02006',
    context: 'Ren writes a blog post; reads it aloud to Sakura for feedback.',
    purpose: 'Two writers discussing online publication.',
    ambient: 'study_room_lamp',
    sound_effects: [],
    target_vocab: ['投稿', 'ブログ', 'サイト', '読者', 'コメント', '反応', '掲載', '発信'],
    cast: ['ren_uni', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'さくらさん、ブログ投稿、見てくれませんか?', en: "Sakura — blog post, see?", style: 'soft young man voice, warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: 'もちろん、サイトに掲載するんでしょ?', en: "Of course — site publish, right?", style: 'gentle adult writer voice, soft warm interested delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、読者の反応、気になります。', en: "Yes — reader reaction, concerns.", style: 'tender young man voice, soft warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'コメント欄、温かい人多いよ。', en: "Comment section — warm people many.", style: 'warm adult writer voice, soft fond reassuring delivery carefully' },
      { speaker: 'ren_uni', jp: '発信を、続けていきたいです。', en: "Posting — want continue.", style: 'soft committed young man voice, warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: '読者、必ず増えていくよ。', en: "Readers — surely increase.", style: 'tender adult writer voice, soft warm encouraging delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、励みになります。', en: "Thank you — encouragement.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02007',
    context: 'Sakura researches at a library; consults a librarian about archives.',
    purpose: 'Writer doing academic research in formal setting.',
    ambient: 'library_quiet_pages',
    sound_effects: [],
    target_vocab: ['文献', '引用', '資料', '調査', '出版', '版', '事実', '根拠'],
    cast: ['sakura_teen', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '当時の資料、探しているんです。', en: "Era materials — searching.", style: 'soft adult writer voice, warm focused delivery carefully' },
      { speaker: 'asuka_teacher', jp: '出版年、どの版でしょうか?', en: "Publication year — which version?", style: 'gentle librarian-mode voice, soft warm helpful delivery carefully' },
      { speaker: 'sakura_teen', jp: '昭和初期の文献、引用したいです。', en: "Early Showa documents — want cite.", style: 'composed adult writer voice, soft warm professional delivery carefully' },
      { speaker: 'asuka_teacher', jp: '事実関係、根拠、しっかり確認を。', en: "Facts — basis, properly verify.", style: 'warm teacher voice, soft warm advising delivery carefully' },
      { speaker: 'sakura_teen', jp: '調査、丁寧にします、必ず。', en: "Research — carefully do, surely.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '貴重な文献、大切に扱ってください。', en: "Precious documents — handle carefully.", style: 'gentle librarian voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、感謝、忘れません。', en: "Yes — gratitude, won't forget.", style: 'reverent adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02008',
    context: 'Daichi at union meeting discussing labor reforms.',
    purpose: 'Workers debating workplace policy.',
    ambient: 'union_hall_low',
    sound_effects: [],
    target_vocab: ['労働', '雇用', '制度', '改革', '提案', '改善', '主張', '負担'],
    cast: ['daichi_kansai', 'kenji_office'],
    frequency_tier: 5,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '労働環境、改善が必要や。', en: "Labor environment — improvement needed.", style: 'firm Kansai man voice, soft warm passionate delivery carefully' },
      { speaker: 'kenji_office', jp: '具体的な提案、ありますか?', en: "Specific proposal — exists?", style: 'composed Kansai man voice, soft warm probing delivery carefully' },
      { speaker: 'daichi_kansai', jp: '雇用制度、まず見直しを。', en: "Employment system — first review.", style: 'soft Kansai man voice, warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: '負担、誰がどう分けるか。', en: "Burden — who divides how.", style: 'gentle Kansai man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '若い社員の負担、減らしたい。', en: "Young staff burden — want reduce.", style: 'warm Kansai husband voice, soft warm caring delivery carefully' },
      { speaker: 'kenji_office', jp: '改革、段階的に進めるのがいい。', en: "Reform — gradual proceed, good.", style: 'measured Kansai mentor voice, soft warm wise delivery carefully' },
      { speaker: 'daichi_kansai', jp: '主張、上にちゃんと届けるで。', en: "Argument — to top properly reach.", style: 'firm Kansai man voice, soft warm committed delivery carefully' },
      { speaker: 'kenji_office', jp: '皆で団結すれば、変わるはず。', en: "All united — should change.", style: 'soft Kansai man voice, warm hopeful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '本気で、取り組もうな。', en: "Seriously — tackle.", style: 'warm Kansai husband voice, soft warm united delivery carefully' },
      { speaker: 'kenji_office', jp: 'こうやって、議論を重ねていきたい。', en: "Like this — debate accumulate.", style: 'gentle Kansai man voice, soft warm philosophical delivery carefully' },
      { speaker: 'daichi_kansai', jp: '俺ら世代の責任や、ほんま。', en: "Our generation responsibility — truly.", style: 'firm Kansai husband voice, soft warm committed delivery carefully' },
      { speaker: 'kenji_office', jp: '次の世代に、繋ぐもんやな。', en: "Next generation — pass on.", style: 'soft Kansai man voice, warm tender delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、頑張ろうや。', en: "Yeah — try.", style: 'warm Kansai husband voice, soft determined delivery carefully' },
    ],
  },
  {
    id: 'conv_02009',
    context: 'Hiroshi-elder reads the morning newspaper aloud to Sho-young, explaining.',
    purpose: 'Elder patiently translating news for child.',
    ambient: 'porch_morning_paper',
    sound_effects: [],
    target_vocab: ['新聞', '報道', '事件', '記事', '政治', '当時', 'まったく', '残っ'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '今朝の新聞、ようけ記事あるな。', en: "Morning paper — many articles.", style: 'slow elder Kansai voice, warm content delivery carefully' },
      { speaker: 'sho_child', jp: 'おじいちゃん、政治の話?', en: "Grandpa — political talk?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、報道、毎日、いろんな事件や。', en: "Yeah — reporting, daily, various events.", style: 'gentle elder Kansai voice, soft warm informative delivery carefully' },
      { speaker: 'sho_child', jp: '当時、おじいちゃんの時代、どうやった?', en: "That time — grandpa era, how?", style: 'curious child boy voice, soft warm interested delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'まったく違うで、新聞、ようけ家に届いた。', en: "Wholly different — paper, much home delivered.", style: 'warm elder Kansai voice, soft warm reminiscent delivery carefully' },
      { speaker: 'sho_child', jp: '今、紙、残ってる家、少ない?', en: "Now — paper, remaining home, few?", style: 'thoughtful child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、時代、変わったな、ほんま。', en: "Yeah — times, changed truly.", style: 'soft elder Kansai voice, warm reflective delivery carefully' },
    ],
  },
  {
    id: 'conv_02010',
    context: 'Naoko discusses regional dialect with a customer from Kanto.',
    purpose: 'Aunt explaining Kansai-Kanto linguistic difference.',
    ambient: 'ramen_shop_afternoon',
    sound_effects: [],
    target_vocab: ['地方', '言葉', '違い', '方々', '使っ', 'やはり', 'かなり', 'けれども'],
    cast: ['naoko_aunt', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'おばさん、地方の言葉、違い、面白いですね。', en: "Auntie — regional words, differences, fun.", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、関東の方々、けっこう違うで。', en: "Yeah — Kanto folks, quite differ.", style: 'brassy Kansai aunt voice, bright loud informative delivery carefully' },
      { speaker: 'sakura_teen', jp: 'やはり、使っている表現、変わりますね。', en: "Indeed — used expressions, change.", style: 'soft adult writer voice, warm observant delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'かなり違うで、けれども、心は同じ。', en: "Quite differ — but, heart same.", style: 'warm Kansai aunt voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: 'なるほど、文化の豊かさ、感じます。', en: "I see — culture richness, feel.", style: 'tender adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '日本、ようけ言葉ある国や!', en: "Japan — many words country!", style: 'animated Kansai aunt voice, bright proud delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に、書きたい話題です。', en: "Article — want write topic.", style: 'soft adult writer voice, warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02011',
    context: 'Tatsuya-country shares wartime memories with Sakura researching for an article.',
    purpose: 'Elder farmer sharing painful historical memory.',
    ambient: 'tatami_lamp_evening',
    sound_effects: [],
    target_vocab: ['戦争', '当時', '時代', '記憶', '事実', '主義', '体験', '残っ'],
    cast: ['tatsuya_country', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '戦争の体験、お聞かせください。', en: "War experience — please share.", style: 'soft adult writer voice, warm reverent inquiry delivered carefully' },
      { speaker: 'tatsuya_country', jp: '当時、まだ子供やった。', en: "Then — still child.", style: 'slow Tohoku farmer voice, warm soft honest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どんな時代でしたか?', en: "What era?", style: 'gentle adult writer voice, soft warm careful delivery carefully' },
      { speaker: 'tatsuya_country', jp: '物資、ようけ無くて、皆苦労した。', en: "Supplies — much absent, all suffered.", style: 'gentle Tohoku voice, soft warm grave delivery carefully' },
      { speaker: 'sakura_teen', jp: '今でも、記憶、鮮明ですか?', en: "Even now — memory, vivid?", style: 'soft adult writer voice, warm warm probing delivery carefully' },
      { speaker: 'tatsuya_country', jp: '心に、残っとる、ずっと。', en: "Heart — remains, always.", style: 'soft Tohoku farmer voice, warm tender delivery carefully' },
      { speaker: 'sakura_teen', jp: '事実を、若い人に伝えるべきですね。', en: "Fact — to young convey should.", style: 'gentle adult writer voice, soft warm earnest delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、平和主義、忘れたらあかん。', en: "Yeah — pacifism, mustn't forget.", style: 'firm Tohoku voice, soft warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '時代を、私たちが伝える責任。', en: "Era — we convey responsibility.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お前みたいな、若い作家、頼りや。', en: "You like — young writer, rely.", style: 'tender Tohoku farmer voice, soft warm proud delivery carefully' },
      { speaker: 'sakura_teen', jp: '心、こめて書きます、必ず。', en: "Heart — put write, surely.", style: 'reverent adult writer voice, soft warm committed delivery carefully' },
      { speaker: 'tatsuya_country', jp: '感謝や、ほんま。', en: "Gratitude — truly.", style: 'soft Tohoku farmer voice, warm tender humble delivery carefully' },
      { speaker: 'sakura_teen', jp: '貴重なお話、忘れません。', en: "Precious words — won't forget.", style: 'soft adult writer voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02012',
    context: 'Yumiko starts her own cooking blog; Aoi helps her set up.',
    purpose: 'Elder mother joining modern publishing format.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['ブログ', '投稿', '料理', '写真', 'コメント', 'サイト', '日記', 'ページ'],
    cast: ['yumiko_mom', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '蒼ちゃん、ブログ、私もできるかしら?', en: "Aoi-chan — blog, I too can?", style: 'soft older mother voice, warm uncertain hopeful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'もちろん、お母さん!料理の投稿、素敵ですよ。', en: "Of course — Mom! Cooking post, lovely.", style: 'warm adult woman voice, soft warm encouraging delivery carefully' },
      { speaker: 'yumiko_mom', jp: '写真、どうやって載せるの?', en: "Photo — how put?", style: 'gentle older mother voice, soft warm curious delivery carefully' },
      { speaker: 'aoi_barista', jp: 'このページ、押して、選ぶだけ。', en: "This page — press, choose only.", style: 'soft adult woman voice, warm warm helpful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'コメント、いただけるかしら?', en: "Comment — can get?", style: 'soft older mother voice, warm hopeful delivery carefully' },
      { speaker: 'aoi_barista', jp: '日記みたいに書けば、読者来ますよ。', en: "Diary-like write — readers come.", style: 'tender adult woman voice, soft warm reassuring delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、楽しくなりそう、サイト。', en: "Heh — becomes fun, site.", style: 'warm older mother voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02013',
    context: 'Hina-young prepares a school presentation; Mei coaches her.',
    purpose: 'Mother helping teen prepare academic presentation.',
    ambient: 'living_room_table_lamp',
    sound_effects: [],
    target_vocab: ['発表', '資料', 'テーマ', '調査', '結論', '構造', '主張', '関連'],
    cast: ['hina_child', 'mei_romantic'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、発表の資料、これで大丈夫かな?', en: "Mei — presentation materials, okay?", style: 'soft anxious teen girl voice, warm hopeful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'テーマ、明確に伝わってる。', en: "Theme — clearly conveying.", style: 'warm young woman voice, soft warm reassuring delivery carefully' },
      { speaker: 'hina_child', jp: '調査の結果、結論、こうまとめた。', en: "Research result — conclusion, this summarize.", style: 'composed teen girl voice, soft warm professional delivery carefully' },
      { speaker: 'mei_romantic', jp: '構造、論理的でいい。', en: "Structure — logical, good.", style: 'gentle young woman voice, soft warm approving delivery carefully' },
      { speaker: 'hina_child', jp: '主張、強く出した方がいいかな?', en: "Argument — strongly bring, better?", style: 'curious teen girl voice, soft warm asking delivery carefully' },
      { speaker: 'mei_romantic', jp: '関連する具体例、もう一つ足すと深い。', en: "Related examples — one more add, deeper.", style: 'tender young woman voice, soft warm helpful delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、頑張る!', en: "Thanks — try!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02014',
    context: 'Aoi plans a cafe music event; brainstorms with Kenji.',
    purpose: 'Couple planning small business event.',
    ambient: 'cafe_planning_low',
    sound_effects: [],
    target_vocab: ['開催', 'イベント', '宣伝', '反応', 'コメント', 'サイト', '提供', '可能'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、イベント開催、来月どう?', en: "Ken-chan — event hold, next month how?", style: 'soft adult woman voice, warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええなぁ、宣伝、どう進める?', en: "Lovely — promo, how proceed?", style: 'warm Kansai husband voice, soft warm engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: 'サイトに掲載して、コメント募集。', en: "Site post — comments recruit.", style: 'composed adult woman voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: '反応、楽しみやな。', en: "Reaction — looking forward.", style: 'gentle Kansai man voice, soft warm hopeful delivery carefully' },
      { speaker: 'aoi_barista', jp: '飲み物、特別なメニュー提供しようか。', en: "Drinks — special menu provide?", style: 'thoughtful adult woman voice, soft warm planning delivery carefully' },
      { speaker: 'kenji_office', jp: '可能やで、お前なら、やれる。', en: "Possible — you, can do.", style: 'warm Kansai husband voice, soft warm encouraging delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、心強い、ありがとう。', en: "Yeah — encouraging, thanks.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02015',
    context: 'Saito presents research at a small panel; Asuka asks audience questions.',
    purpose: 'Doctor academic context with research vocabulary.',
    ambient: 'conference_room_low',
    sound_effects: [],
    target_vocab: ['医療', '分野', '研究', '報告', '質問', '結局', '構造', '提供'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '今日の研究報告、医療分野の新しい構造です。', en: "Today's research report — medical field new structure.", style: 'measured doctor voice, soft professional clear delivery carefully' },
      { speaker: 'asuka_teacher', jp: '質問、よろしいでしょうか?', en: "Question — okay?", style: 'composed teacher voice, soft warm respectful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'はい、どうぞ。', en: "Yes — please.", style: 'warm doctor voice, soft warm inviting delivery carefully' },
      { speaker: 'asuka_teacher', jp: '結局、この提供方法、どの患者層に?', en: "After all — this provision method, which patient layer?", style: 'engaged teacher voice, soft warm professional delivery carefully' },
      { speaker: 'saito_doctor', jp: '高齢者中心ですが、若い世代にも。', en: "Elderly-centered — but young gen also.", style: 'gentle doctor voice, soft warm informative delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'なるほど、深い研究ですね。', en: "I see — deep research.", style: 'tender teacher voice, soft warm appreciative delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ご清聴、ありがとうございました。', en: "Listening — thanks.", style: 'humble doctor voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02016',
    context: 'Hiroshi-elder explains abstract Japanese to Sho-young; gentle teaching.',
    purpose: 'Grandfather patiently teaching grammar conjunctions.',
    ambient: 'tatami_lamp_quiet',
    sound_effects: [],
    target_vocab: ['場合', 'において', 'あるいは', '例えば', 'けれども', 'そして', 'さらに', 'やはり'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、「あるいは」って、何?', en: "Grandpa — \"or rather\", what?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '「これ、あるいは、それ」、選ぶ時使う。', en: "\"This, or that\" — choose time use.", style: 'gentle elder Kansai voice, soft warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: '「場合」も、同じような意味?', en: "\"Case\" — same meaning?", style: 'thoughtful child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '「雨の場合、傘」って、状況のことや。', en: "\"In rain case, umbrella\" — situation matter.", style: 'soft elder Kansai voice, warm warm patient delivery carefully' },
      { speaker: 'sho_child', jp: '「において」「さらに」「やはり」も、難しい!', en: "\"In\", \"further\", \"indeed\" — hard!", style: 'animated child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '例えば、本で読むと、覚えるで。', en: "Example — reading in book, remember.", style: 'warm elder Kansai voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'そして、けれども、ちゃんと覚える!', en: "And, but — properly remember!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02017',
    context: 'Ren writes a news article; collaborates with editor Sakura.',
    purpose: 'Two writers editing a piece together.',
    ambient: 'study_lamp_late',
    sound_effects: [],
    target_vocab: ['取材', '記事', '編集', '掲載', '出版', '主張', '事実', '根拠'],
    cast: ['ren_uni', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'さくらさん、取材記事、初稿できました。', en: "Sakura — coverage article, first draft done.", style: 'soft young man voice, warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '主張、事実、ちゃんと分かれてる?', en: "Argument — fact, properly separated?", style: 'gentle adult writer voice, soft warm editing delivery carefully' },
      { speaker: 'ren_uni', jp: '根拠、複数の資料から取りました。', en: "Basis — multiple materials took.", style: 'composed young man voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '編集、どこ直す予定?', en: "Edit — where fix plan?", style: 'engaged adult writer voice, soft warm collaborative delivery carefully' },
      { speaker: 'ren_uni', jp: '結論部分、もう一度、調整します。', en: "Conclusion — once more, adjust.", style: 'soft young man voice, warm warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '掲載、来週には間に合いそうね。', en: "Publish — by next week, in time.", style: 'warm adult writer voice, soft warm content delivery carefully' },
      { speaker: 'ren_uni', jp: '出版社にも、しっかり報告します。', en: "Publisher — properly report.", style: 'humble young man voice, soft warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_02018',
    context: 'Mei explains household finances strategy to Daichi.',
    purpose: 'Wife sharing financial planning with husband.',
    ambient: 'kitchen_evening_lamp',
    sound_effects: [],
    target_vocab: ['家計', '計画', '投資', '貯金', '節約', '戦略', '変更', '将来'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、家計の計画、見直したい。', en: "Daichi — household plan, want review.", style: 'soft young wife voice, warm practical delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、何か変更が必要?', en: "Yeah — anything change needed?", style: 'warm Kansai husband voice, soft warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: '貯金、もう少し、増やしたいの。', en: "Savings — bit more, want increase.", style: 'gentle young woman voice, soft warm earnest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '節約、どこを削るんや?', en: "Save — where cut?", style: 'soft Kansai husband voice, warm warm thoughtful delivery carefully' },
      { speaker: 'mei_romantic', jp: '外食、減らして、将来のため投資にする。', en: "Eating out — reduce, future for invest.", style: 'composed young woman voice, soft warm strategic delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええ戦略や、賛成や。', en: "Fine strategy — agree.", style: 'warm Kansai husband voice, soft warm approving delivery carefully' },
      { speaker: 'mei_romantic', jp: '一緒に、頑張ろうね。', en: "Together — try.", style: 'tender young wife voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02019',
    context: 'Yuki-office discusses women in workplace policy with Aoi.',
    purpose: 'Two adult women discussing gender equality at work.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['制度', '改革', '平等', '主張', '議論', '反応', '社会', '実際'],
    cast: ['yuki_office', 'aoi_barista'],
    frequency_tier: 5,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: '女性の制度、改革、少しずつ進んでる。', en: "Women's system — reform, gradually advancing.", style: 'composed office woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、でも、実際、まだ平等じゃない。', en: "Yeah — but, actually, not equal yet.", style: 'soft adult woman voice, warm honest delivery carefully' },
      { speaker: 'yuki_office', jp: '主張、続けて、声、上げていきたい。', en: "Argument — continue, voice, raise.", style: 'firm office woman voice, soft warm passionate delivery carefully' },
      { speaker: 'aoi_barista', jp: '社会の反応、どう感じる?', en: "Society reaction — feel how?", style: 'gentle adult woman voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: '徐々に変わってる、でも遅い。', en: "Gradually changing — but slow.", style: 'tender office woman voice, soft warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '若い世代、もっと声、出すべきね。', en: "Young gen — more voice, should put.", style: 'warm adult woman voice, soft warm earnest delivery carefully' },
      { speaker: 'yuki_office', jp: '議論を、続けることが、本当に大切。', en: "Debate — continuing, truly matters.", style: 'soft committed office woman voice, warm philosophical delivery carefully' },
      { speaker: 'aoi_barista', jp: '私たちも、行動で示そうね。', en: "We too — action show.", style: 'tender adult woman voice, soft warm committed delivery carefully' },
      { speaker: 'yuki_office', jp: '次世代の女性、応援したい。', en: "Next-gen women — want support.", style: 'warm office woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、変えていきましょう。', en: "Yeah — change.", style: 'soft adult woman voice, warm warm determined delivery carefully' },
      { speaker: 'yuki_office', jp: 'こうやって、話せて、心強い。', en: "Like this — talking, encouraging.", style: 'tender office woman voice, soft warm grateful delivery carefully' },
      { speaker: 'aoi_barista', jp: '本当に、ありがとう、ゆきさん。', en: "Truly — thanks, Yuki-san.", style: 'warm adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'yuki_office', jp: 'こちらこそ、共に進もう。', en: "Likewise — together advance.", style: 'soft office woman voice, warm warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02020',
    context: 'Whole group does year-end reflection on lessons learned.',
    purpose: 'Multi-voice reflection on the year past.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['振り返る', '来年', '計画', '期待', '結局', '今後', 'さらに', '良く'],
    cast: ['sakura_teen', 'kenji_office', 'aoi_barista', 'mei_romantic', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '今年も、振り返れば、いろいろあったね。', en: "This year too — looking back, various.", style: 'soft adult writer voice, warm reflective delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほんま、結局、ええ年やった。', en: "Truly — after all, fine year.", style: 'soft Kansai man voice, warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: '来年、さらに、頑張りたい。', en: "Next year — further, try.", style: 'tender adult woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'mei_romantic', jp: '計画、しっかり立てよう。', en: "Plan — firmly establish.", style: 'gentle young mother voice, soft warm committed delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '今後の家族の絆、期待しとる。', en: "Future family bond — expect.", style: 'slow elder Kansai voice, warm tender enduring delivery carefully' },
      { speaker: 'sakura_teen', jp: '皆との時間、今年も大切でした。', en: "Time with all — this year too precious.", style: 'tender adult writer voice, soft warm grateful delivery carefully' },
      { speaker: 'kenji_office', jp: '良くここまで来たな、皆。', en: "Well came this far — all.", style: 'warm Kansai man voice, soft warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '感謝、いっぱい。', en: "Gratitude — full.", style: 'soft adult woman voice, warm warm tender delivery carefully' },
      { speaker: 'mei_romantic', jp: '来年も、皆で、笑って過ごそう。', en: "Next year too — all, laughing spend.", style: 'tender young mother voice, soft warm united delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、家族の力、ようけある。', en: "Yeah — family strength, much.", style: 'gentle elder Kansai voice, soft warm proud delivery carefully' },
      { speaker: 'sakura_teen', jp: 'これからも、書き続けます。', en: "Going forward — write keep.", style: 'soft committed adult writer voice, warm warm enduring delivery carefully' },
      { speaker: 'kenji_office', jp: '今後も、ええ作品作るで。', en: "Going forward — fine works make.", style: 'warm Kansai man voice, soft warm committed delivery carefully' },
      { speaker: 'aoi_barista', jp: '皆で、来年、迎えましょう!', en: "All — next year, welcome!", style: 'bright adult woman voice, soft warm cheerful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_101 wrote', CONVERSATIONS.length, 'files');
