import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_093)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01846',
    context: 'Sho-young struggles with arithmetic homework; Hina-young helps him.',
    purpose: 'Older teen sister patiently helping younger brother.',
    ambient: 'living_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['算数', '宿題', '問題', '教える'],
    cast: ['hina_child', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'ねえちゃん、算数、難しい!', en: "Sis — math, hard!", style: 'soft frustrated child boy voice, warm honest delivery carefully' },
      { speaker: 'hina_child', jp: 'どの問題?見せて。', en: "Which problem? Show.", style: 'gentle teen girl voice, soft warm helpful delivery carefully' },
      { speaker: 'sho_child', jp: 'この計算、わからん。', en: "This calc — don't get.", style: 'soft child boy voice, warm honest delivery carefully' },
      { speaker: 'hina_child', jp: '順番に、一緒にやろう。', en: "In order — together do.", style: 'soft teen girl voice, warm patient delivery carefully' },
      { speaker: 'sho_child', jp: 'ねえちゃん、優しい!', en: "Sis — kind!", style: 'soft grateful child boy voice, warm appreciative delivery carefully' },
      { speaker: 'hina_child', jp: '宿題、頑張ろう。', en: "Homework — try.", style: 'warm teen girl voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、ありがとう!', en: "Yeah — thanks!", style: 'bright child boy voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01847',
    context: 'Hina-young tells Mei her future university application plans.',
    purpose: 'Teen confiding plans with adult mentor.',
    ambient: 'living_room_evening_warm',
    sound_effects: [],
    target_vocab: ['大学', '受験', '進学', '夢'],
    cast: ['hina_child', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、大学、決めた!', en: "Mei — uni, decided!", style: 'bright teen girl voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、どんなところ?', en: "Oh — what place?", style: 'gentle young woman voice, soft warm curious delivery carefully' },
      { speaker: 'hina_child', jp: '文学部、考えてる。', en: "Literature — thinking.", style: 'soft teen girl voice, warm earnest delivery carefully' },
      { speaker: 'mei_romantic', jp: '受験、頑張ってね。', en: "Exam — try.", style: 'tender young woman voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '夢、本気で叶えたい。', en: "Dream — seriously fulfill.", style: 'soft determined teen girl voice, warm committed delivery carefully' },
      { speaker: 'mei_romantic', jp: '応援してる、ずっと。', en: "Cheering — always.", style: 'warm young woman voice, soft fond steadfast delivery carefully' },
      { speaker: 'hina_child', jp: '心強い、ありがとう!', en: "Encouraging — thanks!", style: 'bright teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01848',
    context: 'Asuka grades student essays; Saito brings tea and quiet support.',
    purpose: 'Husband supporting wife during work.',
    ambient: 'study_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['作文', '採点', '生徒', '評価'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'お茶、入れたよ。', en: "Tea — brewed.", style: 'soft doctor voice, warm tender helpful delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ありがとう、助かるわ。', en: "Thanks — saved.", style: 'tender teacher voice, soft warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: '作文、たくさんあるね。', en: "Essays — many.", style: 'gentle doctor voice, soft warm observant delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'うん、評価、丁寧にしたい。', en: "Yeah — evaluate carefully.", style: 'warm teacher voice, soft warm committed delivery carefully' },
      { speaker: 'saito_doctor', jp: '生徒、喜ぶよ、きっと。', en: "Students — pleased, surely.", style: 'tender doctor voice, soft warm reassuring delivery carefully' },
    ],
  },
  {
    id: 'conv_01849',
    context: 'Ren tutors Sho-young in English; gentle teaching session.',
    purpose: 'Adult kindly teaching child language.',
    ambient: 'kitchen_table_low',
    sound_effects: [],
    target_vocab: ['英語', '単語', '発音', '練習'],
    cast: ['ren_uni', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '翔くん、英語、楽しい?', en: "Sho — English, fun?", style: 'soft young man voice, warm warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、ちょっと難しい。', en: "Yeah — bit hard.", style: 'soft child boy voice, warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '発音、繰り返し、大事。', en: "Pronunciation — repeat, matters.", style: 'gentle young man voice, soft warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'お兄ちゃん、見本見せて。', en: "Brother — show example.", style: 'eager child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: 'OK、聞いてみて。', en: "OK — listen.", style: 'warm young man voice, soft friendly delivery carefully' },
      { speaker: 'sho_child', jp: '言ってみる!', en: "I'll say!", style: 'soft determined child boy voice, warm cheerful delivery carefully' },
      { speaker: 'ren_uni', jp: 'いい発音、続けよう。', en: "Fine pronunc — continue.", style: 'tender young man voice, soft warm encouraging delivery carefully' },
    ],
  },
  {
    id: 'conv_01850',
    context: 'Sakura visits a small university lecture; chats with Hiroshi-boss as alumnus.',
    purpose: 'Writer attending intellectual event with publisher.',
    ambient: 'university_corridor_low',
    sound_effects: [],
    target_vocab: ['講義', '大学', '学問', '深い'],
    cast: ['sakura_teen', 'hiroshi_boss'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '社長、講義、興味深かった。', en: "Boss — lecture, fascinating.", style: 'soft adult writer voice, warm intellectual delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'おう、深い話やったな。', en: "Yeah — deep talk.", style: 'measured boss voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '学問、続けると面白い。', en: "Scholarship — continued, fun.", style: 'gentle adult writer voice, soft warm reflective delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'うん、生涯学習やな。', en: "Yeah — lifelong learning.", style: 'warm boss voice, soft fond philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に、参考にします。', en: "Article — reference.", style: 'soft adult writer voice, warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_01851',
    context: 'Kenji helps Sho-young with art homework; patient hands-on session.',
    purpose: 'Mentor uncle teaching child drawing technique.',
    ambient: 'living_room_table_lamp',
    sound_effects: [],
    target_vocab: ['美術', '描く', '色', '形'],
    cast: ['kenji_office', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '健司おじちゃん、美術、苦手。', en: "Kenji-ojichan — art, weak at.", style: 'soft child boy voice, warm vulnerable honest delivery carefully' },
      { speaker: 'kenji_office', jp: '誰でも、最初は難しいで。', en: "Everyone — first hard.", style: 'warm Kansai mentor voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: '色、何で塗ったらいい?', en: "Color — what to paint?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: '好きな色、選んでみ。', en: "Like color — pick.", style: 'gentle Kansai man voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '形、まる、まる、たくさん。', en: "Shape — circles, lots.", style: 'cheerful child boy voice, bright warm delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええなぁ、ええ感じや!', en: "Lovely — fine feel!", style: 'warm Kansai mentor voice, soft fond praising delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、楽しい!', en: "Thanks — fun!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01852',
    context: 'Yumiko helps Hina-young memorize kanji for a test.',
    purpose: 'Grandmother teaching teen with patience.',
    ambient: 'tatami_room_quiet',
    sound_effects: [],
    target_vocab: ['漢字', '覚える', '練習', '試験'],
    cast: ['yumiko_mom', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、漢字、覚えられない!', en: "Grandma — kanji, can't memorize!", style: 'frustrated teen girl voice, soft warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '繰り返し、書いてみて。', en: "Repeatedly — write.", style: 'gentle older mother voice, soft warm teaching delivery carefully' },
      { speaker: 'hina_child', jp: '試験、来週なの。', en: "Test — next week.", style: 'soft teen girl voice, warm anxious delivery carefully' },
      { speaker: 'yumiko_mom', jp: '焦らず、少しずつね。', en: "Don't rush — bit by bit.", style: 'warm older mother voice, soft tender encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、頑張る!', en: "Yeah — try!", style: 'soft determined teen girl voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01853',
    context: 'Riku-teen tells Sho-young about his university campus visit.',
    purpose: 'Older teen sharing future hopes with younger.',
    ambient: 'park_bench_afternoon',
    sound_effects: [],
    target_vocab: ['大学', '校舎', '進学', '楽しみ'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'riku_teen', jp: '大学、見学行ってきた!', en: "Uni — visited!", style: 'bright teen boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'えっ、どんな感じ?', en: "Eh — how feel?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'riku_teen', jp: '校舎、めっちゃ広かった!', en: "Campus — super wide!", style: 'animated teen boy voice, bright cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'いいなぁ、進学、楽しみ?', en: "Nice — looking forward?", style: 'soft child boy voice, warm fond delivery carefully' },
      { speaker: 'riku_teen', jp: 'うん、めっちゃ楽しみや!', en: "Yeah — super excited!", style: 'bright teen boy voice, soft warm eager delivery carefully' },
    ],
  },
  {
    id: 'conv_01854',
    context: 'Asuka explains hiragana writing to Sho-young after school.',
    purpose: 'Teacher patiently teaching child letters.',
    ambient: 'classroom_after_quiet',
    sound_effects: [],
    target_vocab: ['ひらがな', '書く', '丁寧', '上手'],
    cast: ['asuka_teacher', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '翔くん、ひらがな、丁寧にね。', en: "Sho — hiragana, carefully.", style: 'warm teacher voice, soft warm instructional delivery carefully' },
      { speaker: 'sho_child', jp: 'はい、頑張ります!', en: "Yes — try!", style: 'soft determined child boy voice, warm committed delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'もう、上手に書けるね。', en: "Already — well-written.", style: 'gentle teacher voice, soft warm praising delivery carefully' },
      { speaker: 'sho_child', jp: 'ほんと?嬉しい!', en: "Really? Happy!", style: 'thrilled child boy voice, bright warm proud delivery carefully' },
      { speaker: 'asuka_teacher', jp: '練習続ければ、もっと。', en: "Practice continued — more.", style: 'tender teacher voice, soft warm encouraging delivery carefully' },
    ],
  },
  {
    id: 'conv_01855',
    context: 'Mei discusses helping her child with school choice with Daichi.',
    purpose: 'Married couple deciding on child schooling.',
    ambient: 'bedroom_evening_lamp',
    sound_effects: [],
    target_vocab: ['学校', '選ぶ', '相談', '将来'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '翔の学校、決めなきゃ。', en: "Sho's school — must decide.", style: 'soft young mother voice, warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、選択肢、たくさんあるな。', en: "Yeah — many options.", style: 'soft Kansai husband voice, warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: '公立、私立、迷うね。', en: "Public, private — wavering.", style: 'gentle young woman voice, soft warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '本人の希望、聞かなな。', en: "His wish — must ask.", style: 'warm Kansai husband voice, soft thoughtful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まだ小さいけど、感じはあるね。', en: "Still small — but has sense.", style: 'soft young mother voice, warm tender delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お友達、大事やしな。', en: "Friends — matter.", style: 'gentle Kansai husband voice, soft warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '近くがいいかな。', en: "Nearby — better?", style: 'gentle young woman voice, soft warm thinking delivery carefully' },
      { speaker: 'daichi_kansai', jp: '通学、安全、第一や。', en: "Commute — safety first.", style: 'firm Kansai husband voice, soft warm careful delivery carefully' },
      { speaker: 'mei_romantic', jp: '見学、行ってみよう。', en: "Visit — let's go.", style: 'soft young mother voice, warm warm decisive delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、来週末予約しよか。', en: "Yeah — book next weekend.", style: 'warm Kansai husband voice, soft committed delivery carefully' },
      { speaker: 'mei_romantic', jp: '将来のため、丁寧に決めたい。', en: "For future — decide carefully.", style: 'tender young mother voice, soft warm earnest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お互い、納得できる選択を。', en: "Both — accept choice.", style: 'gentle Kansai husband voice, soft warm united delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、相談、嬉しい。', en: "Thanks — discussion, happy.", style: 'tender young wife voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01856',
    context: 'Sakura visits a high school as guest speaker; Asuka hosts.',
    purpose: 'Author and teacher collaborating on student talk.',
    ambient: 'school_auditorium_low',
    sound_effects: [],
    target_vocab: ['生徒', '話す', '夢', '伝える'],
    cast: ['sakura_teen', 'asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'さくら先生、生徒、楽しみにしてる。', en: "Sakura — students looking forward.", style: 'warm teacher voice, soft warm inviting delivery carefully' },
      { speaker: 'sakura_teen', jp: '緊張するわ、何百人?', en: "Nervous — hundreds?", style: 'soft adult writer voice, warm honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'はい、夢の話、聞きたいって。', en: "Yes — want to hear dream story.", style: 'gentle teacher voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '私の経験、伝えていい?', en: "My experience — can convey?", style: 'curious adult writer voice, soft warm earnest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '是非、心の声を。', en: "By all means — heart's voice.", style: 'warm teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'sakura_teen', jp: '頑張ります、若い人に届くよう。', en: "Try — reach the young.", style: 'soft determined adult writer voice, warm committed delivery carefully' },
      { speaker: 'asuka_teacher', jp: '応援してます。', en: "Cheering.", style: 'tender teacher voice, soft warm supportive delivery carefully' },
    ],
  },
  {
    id: 'conv_01857',
    context: 'Naoko encourages Hina-young to keep studying despite a hard week.',
    purpose: 'Aunt giving teen pep talk during struggle.',
    ambient: 'ramen_shop_evening',
    sound_effects: [],
    target_vocab: ['勉強', '辛い', '休む', '続ける'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばちゃん、勉強、辛い。', en: "Auntie — study, hard.", style: 'soft weary teen girl voice, warm honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: '休みもいるで、無理せん。', en: "Rest too — don't push.", style: 'warm Kansai aunt voice, soft tender wise delivery carefully' },
      { speaker: 'hina_child', jp: '頭、回らない。', en: "Brain — won't turn.", style: 'tired teen girl voice, soft warm honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: '一旦、お茶でも飲も。', en: "Once — tea drink.", style: 'animated Kansai aunt voice, bright warm caring delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、休憩する。', en: "Yeah — rest.", style: 'soft teen girl voice, warm agreement delivered carefully' },
      { speaker: 'naoko_aunt', jp: '続ける根性、お前にある。', en: "Persisting grit — you have.", style: 'firm Kansai aunt voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、頑張る!', en: "Thanks — try!", style: 'soft determined teen girl voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01858',
    context: 'Hiroshi-elder watches educational TV with Sho-young about history.',
    purpose: 'Grandfather and child engaging with history together.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['歴史', '昔', '武士', '面白い'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、武士、強かった?', en: "Grandpa — samurai, strong?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、心、強かったで。', en: "Yeah — heart strong.", style: 'slow elder Kansai voice, warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '歴史、面白い!', en: "History — fun!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '昔の話、ようけ知ってる。', en: "Old stories — know lots.", style: 'gentle elder Kansai voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: 'もっと、教えて!', en: "More — teach!", style: 'eager child boy voice, bright warm delivery carefully' },
    ],
  },
  {
    id: 'conv_01859',
    context: 'Aoi attends a community lecture; brief chat with Saito on philosophical topic.',
    purpose: 'Two adults connecting through intellectual event.',
    ambient: 'community_hall_low',
    sound_effects: [],
    target_vocab: ['講演', '哲学', '深い', '考える'],
    cast: ['aoi_barista', 'saito_doctor'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '先生、今夜の講演、深かったですね。', en: "Doctor — tonight's lecture, deep.", style: 'soft adult woman voice, warm intellectual delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ、考えさせられました。', en: "Yes — made to think.", style: 'measured doctor voice, soft warm thoughtful delivery carefully' },
      { speaker: 'aoi_barista', jp: '哲学、難しいけど面白い。', en: "Philosophy — hard but fun.", style: 'gentle adult woman voice, soft warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '人生、振り返る、いい機会。', en: "Life — reflect, fine chance.", style: 'soft doctor voice, warm philosophical delivery carefully' },
      { speaker: 'aoi_barista', jp: 'こういう時間、必要ですね。', en: "Times like this — needed.", style: 'tender adult woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'saito_doctor', jp: 'また、来ましょう。', en: "Come again.", style: 'warm doctor voice, soft fond delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、是非。', en: "Yes — by all means.", style: 'soft adult woman voice, warm friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_01860',
    context: 'Tatsuya-country reads a long letter from his daughter aloud to Asuka.',
    purpose: 'Couple sharing meaningful family correspondence.',
    ambient: 'tatami_lamp_evening',
    sound_effects: [],
    target_vocab: ['手紙', '娘', '元気', '心'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: 'お、娘から、手紙や!', en: "Oh — from daughter, letter!", style: 'cheerful Tohoku farmer voice, soft warm delighted delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'まあ、嬉しい!読んで?', en: "Oh — happy! Read?", style: 'tender teacher voice, soft warm eager delivery carefully' },
      { speaker: 'tatsuya_country', jp: '東京で、元気にしてる。', en: "Tokyo — well.", style: 'soft Tohoku voice, warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: '安心、よかった。', en: "Relief — good.", style: 'warm teacher voice, soft warm grateful delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お父さん、心配してくれてって。', en: "Dad — caring, she wrote.", style: 'tearful Tohoku farmer voice, soft warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: '優しい子よね、本当に。', en: "Kind kid — truly.", style: 'tender teacher voice, soft warm reverent delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、ええ娘や。', en: "Yeah — fine daughter.", style: 'soft Tohoku voice, warm fatherly delivery carefully' },
    ],
  },
  {
    id: 'conv_01861',
    context: 'Yuki-office mentors Aoi for new staff training at the cafe.',
    purpose: 'Two adult women collaborating professionally.',
    ambient: 'cafe_morning_quiet',
    sound_effects: [],
    target_vocab: ['指導', '研修', '丁寧', '成長'],
    cast: ['yuki_office', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'ゆきさん、新人指導、お願いできる?', en: "Yuki — new staff guide, ask?", style: 'soft adult woman voice, warm professional inviting delivery carefully' },
      { speaker: 'yuki_office', jp: '喜んで、頑張ります。', en: "Gladly — try.", style: 'warm office woman voice, soft eager delivery carefully' },
      { speaker: 'aoi_barista', jp: '丁寧に、教えてあげてね。', en: "Carefully — teach.", style: 'gentle adult woman voice, soft warm instructive delivery carefully' },
      { speaker: 'yuki_office', jp: 'はい、成長を見守ります。', en: "Yes — watch growth.", style: 'soft office woman voice, warm committed delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01862',
    context: 'Sho-young proudly shows Ren a book he finished reading.',
    purpose: 'Child showing reading achievement to mentor.',
    ambient: 'living_room_evening_warm',
    sound_effects: [],
    target_vocab: ['本', '読む', '感想', '面白い'],
    cast: ['sho_child', 'ren_uni'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '蓮にいちゃん、本、読み終えた!', en: "Ren — book finished!", style: 'thrilled child boy voice, bright warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: 'すごいね!感想は?', en: "Wow! Impressions?", style: 'gentle young man voice, soft warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: 'すごく、面白かった!', en: "Super — fun!", style: 'bright child boy voice, soft warm enthusiastic delivery carefully' },
      { speaker: 'ren_uni', jp: '主人公、好きになった?', en: "Hero — liked?", style: 'soft young man voice, warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、大好き!', en: "Yeah — love!", style: 'thrilled child boy voice, bright warm delivery carefully' },
    ],
  },
  {
    id: 'conv_01863',
    context: 'Daichi attends Sho-young\'s school parents\' day; pleasant teacher exchange.',
    purpose: 'Father connecting with school staff.',
    ambient: 'school_classroom_low',
    sound_effects: [],
    target_vocab: ['授業', '見学', '先生', '感謝'],
    cast: ['daichi_kansai', 'asuka_teacher'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '先生、授業、ありがとうございました。', en: "Teacher — class, thanks.", style: 'warm Kansai husband voice, soft warm grateful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '翔くん、ようやってますよ。', en: "Sho — doing well.", style: 'gentle teacher voice, soft warm proud delivery carefully' },
      { speaker: 'daichi_kansai', jp: '家でも、明るく話します。', en: "Home — talks brightly.", style: 'soft Kansai husband voice, warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: '友達も、たくさんできましたね。', en: "Friends — many made.", style: 'warm teacher voice, soft fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ご指導、感謝します。', en: "Guidance — grateful.", style: 'humble Kansai man voice, soft warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_01864',
    context: 'Hina-young helps Sho-young with science homework about plants.',
    purpose: 'Older sister gently teaching younger brother.',
    ambient: 'kitchen_table_low',
    sound_effects: [],
    target_vocab: ['理科', '植物', '観察', '記録'],
    cast: ['hina_child', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'ねえちゃん、理科、わからん!', en: "Sis — science, don't get!", style: 'frustrated child boy voice, soft warm honest delivery carefully' },
      { speaker: 'hina_child', jp: '植物、観察してみて。', en: "Plant — observe.", style: 'gentle teen girl voice, soft warm instructive delivery carefully' },
      { speaker: 'sho_child', jp: '葉っぱ、何枚?', en: "Leaves — how many?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: '数えて、記録するの。', en: "Count — record.", style: 'soft teen girl voice, warm helpful delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、わかった!', en: "Yeah — got!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01865',
    context: 'Whole group celebrates Hina\'s exam success; many warm voices.',
    purpose: 'Big celebration of teen\'s educational milestone.',
    ambient: 'living_room_party_warm',
    sound_effects: [],
    target_vocab: ['合格', '頑張る', '祝う', '家族', '応援'],
    cast: ['hina_child', 'mei_romantic', 'daichi_kansai', 'sho_child', 'naoko_aunt', 'yumiko_mom', 'sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'ひな、合格、本当におめでとう!', en: "Hina — pass, truly congrats!", style: 'tender young woman voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、皆のおかげ!', en: "Thanks — thanks to all!", style: 'thrilled teen girl voice, bright warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前、ようやった!', en: "You — well done!", style: 'warm Kansai husband voice, soft proud delivery carefully' },
      { speaker: 'sho_child', jp: 'ねえちゃん、すごい!', en: "Sis — amazing!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お祝い、盛大にせなな!', en: "Celebrate — grandly!", style: 'brassy Kansai aunt voice, bright loud delighted delivery carefully' },
      { speaker: 'yumiko_mom', jp: '頑張った姿、見てたよ。', en: "Your effort — watched.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '夢、実現したね。', en: "Dream — realized.", style: 'warm adult writer voice, soft tender proud delivery carefully' },
      { speaker: 'hina_child', jp: '皆の応援、心強かった。', en: "Everyone's cheers — encouraging.", style: 'soft teen girl voice, warm tearful grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'これから、ずっと応援するよ。', en: "From now — always cheer.", style: 'tender young woman voice, soft warm steadfast delivery carefully' },
      { speaker: 'daichi_kansai', jp: '家族、宝物やな。', en: "Family — treasure.", style: 'soft Kansai husband voice, warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: 'ねえちゃん、お祝い、僕も!', en: "Sis — congrats, me too!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、可愛いやんか、皆!', en: "Heh — cute, all!", style: 'warm Kansai aunt voice, bright fond delivery carefully' },
      { speaker: 'hina_child', jp: '本当に、ありがとう。', en: "Truly — thanks.", style: 'tender teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_093 wrote', CONVERSATIONS.length, 'files');
