// scripts/batches/batch_003.mjs
// Batch 3: conv_00044 .. conv_00063.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
fs.mkdirSync(OUT_DIR, { recursive: true });
const NOW = new Date().toISOString();
const META = (row) => ({ generated_by: 'claude-opus-4-7 (batch_003)', generated_at: NOW, source_plan_row: row || '' });

const CONVERSATIONS = [
  {
    id: 'conv_00044',
    context: 'A small ramen shop near the hospital. Dr. Saito and her old friend Asuka have a standing every-other-Thursday lunch — short, fast, real.',
    purpose: 'professional women friendship — venting + small advice + warmth',
    ambient: 'busy_restaurant',
    target_vocab: ['本当に','時間','大変','大丈夫','友達','今日'],
    cast: ['saito_doctor','asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '今日も疲れた。本当に、本当に長い一日。', en: 'Today wore me out. Really — really long day.', style: 'Sits down heavily. Doubled 「本当に」 lands genuine, not performative. Tired exhale.', mood: 'spent' },
      { speaker: 'asuka_teacher', jp: '食べな食べな。話して、ぜんぶ。', en: 'Eat, eat. Talk — all of it.', style: 'Already pushing the bowl across the table. Brisk maternal warmth from a peer.', mood: 'pushing_care' },
      { speaker: 'saito_doctor', jp: '朝から手術三件。看護師も足りなくて。', en: 'Three surgeries since morning. Short on nurses too.', style: 'Plain, exhausted recitation. The complaint as report — no drama in the voice.', mood: 'reporting_tired' },
      { speaker: 'asuka_teacher', jp: '大変だね…大丈夫？体は。', en: 'That\'s tough… are you okay? Body-wise.', style: 'A real concerned beat. The 「体は」 carries real worry for her friend.', mood: 'concerned_real' },
      { speaker: 'saito_doctor', jp: '体は…なんとか。心がね。', en: 'Body — managing. The heart, though.', style: 'A small pause before 「心がね」. The honest answer she only gives this friend.', mood: 'honest_quiet' },
      { speaker: 'asuka_teacher', jp: 'そっか。先生も人間やもんね。', en: 'Mm. You\'re human too, doctor-sensei.', style: 'Gentle teasing in the title. Easy warmth.', mood: 'gentle_teasing' },
      { speaker: 'saito_doctor', jp: '…やめてよ、教師にそう言われるの、効くから。', en: '…Stop — when a teacher says that, it actually lands.', style: 'A small laugh. Half-protest, half-thank-you.', mood: 'half_laugh' },
      { speaker: 'asuka_teacher', jp: '(laughs) 効いたなら成功。', en: '(laughs) If it landed — mission accomplished.', style: 'Real laugh. Picks up her chopsticks.', mood: 'laughing' },
      { speaker: 'saito_doctor', jp: '来週、絶対飲みに行こ。', en: 'Next week — we are absolutely going for drinks.', style: 'Firm. Already deciding for both of them.', mood: 'firm_planning' },
      { speaker: 'asuka_teacher', jp: 'もちろん。時間、絶対作って。', en: 'Of course. Make the time. Definitely.', style: 'Bossy but warm. The friendship maintained as agenda.', mood: 'bossy_warm' },
      { speaker: 'saito_doctor', jp: '本当に、友達でよかった。', en: 'Honestly — glad you\'re my friend.', style: 'Quiet, sincere. Eyes on the bowl. Sentence weight unusual for her.', mood: 'sincere_quiet' },
    ],
  },
  {
    id: 'conv_00045',
    context: 'A summer afternoon at Sachiko\'s home. Hina has asked, out of nowhere, what life was like "in the old days." Sachiko sets her tea down and tells her something.',
    purpose: 'oral history — grandmother shares a small story from her childhood',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','一緒','見る','大丈夫','元気','家'],
    cast: ['sachiko_grandma','hina_child'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、昔って、どんなだったの？', en: 'Grandma — what was the old days like?', style: 'Genuine kid curiosity. Pulls a cushion closer in the voice.', mood: 'curious_kid' },
      { speaker: 'sachiko_grandma', jp: '昔ねえ…時間が、ゆっくりだった気がする。', en: 'The old days… time felt slower somehow.', style: 'Slow, melodic. Looks somewhere far in the voice. A small smile.', mood: 'remembering' },
      { speaker: 'hina_child', jp: 'ゆっくり？どういうこと？', en: 'Slower? What does that mean?', style: 'Tilts her head in the voice. Honest puzzlement.', mood: 'puzzled' },
      { speaker: 'sachiko_grandma', jp: 'テレビも、電話も、少なかったから。', en: 'There were so few TVs, telephones, all of it.', style: 'Listing as memory. Slight wobble of older speech. No nostalgia weight.', mood: 'gentle_listing' },
      { speaker: 'hina_child', jp: 'えっ、本当に？何してたの？', en: 'Wait — really? What did you do?', style: 'Eight-year-old amazement. Sits forward in the voice.', mood: 'astonished' },
      { speaker: 'sachiko_grandma', jp: 'お友達と、家の前で、よく遊んでね。', en: 'With friends — in front of the house — we played a lot.', style: 'A small smile audible. The 「ね」 ending is the warm invitation to imagine.', mood: 'inviting_imagine' },
      { speaker: 'hina_child', jp: '何で遊ぶの？', en: 'What\'d you play with?', style: 'Wants the answer urgently. Voice bouncing.', mood: 'eager' },
      { speaker: 'sachiko_grandma', jp: '石とか、棒とか…本当にね、なんでも遊びになった。', en: 'Stones, sticks… really, anything could become a game.', style: 'A tiny laugh inside the voice. The 「本当にね」 carries fond surprise at her own memory.', mood: 'fond_remembering' },
      { speaker: 'hina_child', jp: '…つまんなくなかった？', en: '…Wasn\'t that boring?', style: 'Honest worry, eight-year-old style. Doesn\'t mean to be rude.', mood: 'honestly_worried' },
      { speaker: 'sachiko_grandma', jp: '不思議とね、つまんなかった記憶、ないの。', en: 'Strange to say — I don\'t remember being bored.', style: 'A small wondering pause before the answer. Soft, surprised by her own truth.', mood: 'wondering_truth' },
      { speaker: 'hina_child', jp: 'えー、本当に？', en: 'Whaa — really?', style: 'High lift on 「えー」. Genuine kid disbelief.', mood: 'disbelieving_kid' },
      { speaker: 'sachiko_grandma', jp: 'うん。お友達と、ただ一緒にいるのが、楽しかった。', en: 'Mm. Just being with friends — that itself was fun.', style: 'Slow, certain. The whole story compressed into the second clause.', mood: 'distilled_truth' },
      { speaker: 'hina_child', jp: '…(thinking, quiet)', en: '(quiet, thinking)', style: 'A real beat of consideration. The kid is actually trying to imagine it.', mood: 'thinking_real' },
      { speaker: 'sachiko_grandma', jp: '今度、ひなちゃんも、テレビ消して、ちょっと遊んでみる？', en: 'Want to try it sometime — turn off the TV, just play a little?', style: 'A small invitation in the form of a question. Warm.', mood: 'gentle_invitation' },
      { speaker: 'hina_child', jp: 'うん！おばあちゃんと一緒なら、やる！', en: 'Yeah! With you — I\'ll do it!', style: 'Full kid-volume return. The whole conversation\'s warmth resolved into a yes.', mood: 'bright_yes' },
    ],
  },
  {
    id: 'conv_00046',
    context: 'A bus stop after school. Two teens — one Kansai-flavored, one Tokyo — both checking phones, end up exchanging exactly three sentences.',
    purpose: 'incidental teen encounter — phatic with the smallest possible humor',
    ambient: 'city_street_day',
    target_vocab: ['今','本当に','ない'],
    cast: ['sakura_teen','riku_teen'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'バス、遅すぎひん？', en: 'Bus is way late, right?', style: 'Out of nowhere. Kansai cadence. Doesn\'t look up from her phone.', mood: 'casual_complaint' },
      { speaker: 'riku_teen', jp: '…うん。十分は来てない。', en: '…Yeah. Hasn\'t come in ten minutes.', style: 'Mumbled but real. Caught off-guard by being talked to. Voice cracks half a step.', mood: 'mumbled_response' },
      { speaker: 'sakura_teen', jp: 'マジ、今日に限って、本当に。', en: 'Seriously — of all days, today.', style: 'A real sigh. The shared misery solidarity of strangers.', mood: 'shared_misery' },
      { speaker: 'riku_teen', jp: '(small laugh)', en: '(small laugh)', style: 'A real laugh, surprising himself. A beat of unguarded.', mood: 'unguarded_beat' },
      { speaker: 'sakura_teen', jp: 'あ、来た。やっと。', en: 'Oh — it\'s here. Finally.', style: 'Stands. The conversation closes itself naturally.', mood: 'closing_natural' },
      { speaker: 'riku_teen', jp: '…うん。', en: '…Yeah.', style: 'One syllable goodbye. Stays on his phone but smaller smile in the voice.', mood: 'small_smile' },
    ],
  },
  {
    id: 'conv_00047',
    context: 'A neighborhood koban. Ren has come in to ask about a misplaced bicycle. Officer Takeda is patient, methodical, and warm.',
    purpose: 'small bureaucratic encounter — careful kindness from a uniformed adult',
    ambient: 'police_box',
    target_vocab: ['今日','すみません','本当に','時間','どこ','見る'],
    cast: ['takeda_officer','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'すみません、ちょっといいですか…', en: 'Excuse me, do you have a moment…', style: 'Hesitant opener at the doorway. Bow inside the voice.', mood: 'polite_hesitant' },
      { speaker: 'takeda_officer', jp: 'はい、どうぞ。お入りください。', en: 'Yes, please — come in.', style: 'Calm, professional, already standing.', mood: 'professional_inviting' },
      { speaker: 'ren_uni', jp: '自転車、停めた場所、どこか…忘れちゃって。', en: 'My bicycle — where I parked it — I, um, forgot.', style: 'Half-laughs at his own embarrassment. The 「忘れちゃって」 trails off.', mood: 'embarrassed' },
      { speaker: 'takeda_officer', jp: '大丈夫ですよ。今日、いつごろ停めましたか？', en: 'It\'s alright. Around what time today did you park it?', style: 'No judgment. Pulls out a notepad in the voice.', mood: 'no_judgment' },
      { speaker: 'ren_uni', jp: 'お昼ごろ…たぶん駅の近くで。', en: 'Around noon… probably near the station.', style: 'Trying to reconstruct his own day. Voice slightly uncertain.', mood: 'reconstructing' },
      { speaker: 'takeda_officer', jp: 'では、一緒に駅の駐輪場、見てみましょうか。', en: 'Then — let\'s go look at the station\'s bike-park together.', style: 'Practical kindness. Already reaching for his cap in the voice.', mood: 'practical_kind' },
      { speaker: 'ren_uni', jp: 'えっ、本当に？お時間、大丈夫ですか？', en: 'Wait — really? Is that okay, time-wise?', style: 'Genuinely surprised. The 「本当に？」 is half-disbelief, half-gratitude.', mood: 'grateful_surprise' },
      { speaker: 'takeda_officer', jp: '今、暇です。行きましょう。', en: 'I\'m free right now. Let\'s go.', style: 'A small joke in the voice — koban officers are rarely "暇". Closes the encounter with kindness.', mood: 'gentle_humor' },
    ],
  },
  {
    id: 'conv_00048',
    context: 'A train carriage on a slow afternoon line. Naoko and Sachiko end up on facing seats; Naoko, predictably, opens the conversation first.',
    purpose: 'cross-region elder bonding — Osaka brashness meets Tokyo softness',
    ambient: 'train_carriage',
    target_vocab: ['本当に','今','時間','大変','一人','家族'],
    cast: ['naoko_aunt','sachiko_grandma'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'お一人ですか？お疲れさん。', en: 'Travelling alone? Nice work.', style: 'Loud opener across the aisle. Kansai brightness. No greeting first.', mood: 'loud_friendly' },
      { speaker: 'sachiko_grandma', jp: 'あら、はい…さちこと申します。', en: 'Oh — yes. I\'m Sachiko.', style: 'Soft, formal Tokyo. The slight wobble of older speech.', mood: 'soft_formal' },
      { speaker: 'naoko_aunt', jp: 'なおこです。今、東京戻り？', en: 'Naoko. Heading back to Tokyo?', style: 'Already on first names. Kansai economy.', mood: 'instant_familiar' },
      { speaker: 'sachiko_grandma', jp: 'はい、息子の家へ。家族と少しだけ。', en: 'Yes — to my son\'s. Just a short visit with family.', style: 'Easy answer. Pleased by the directness.', mood: 'pleased_answering' },
      { speaker: 'naoko_aunt', jp: 'ええなあ。うちは、子供おらんけど、姪が三人。', en: 'Nice. No kids of my own, but three nieces.', style: 'Volunteers it. No envy, just the inventory.', mood: 'matter_of_fact' },
      { speaker: 'sachiko_grandma', jp: 'まあ、三人も。にぎやかでしょう。', en: 'My — three! That must be lively.', style: 'Genuine delight. A small clap inside the voice.', mood: 'delighted' },
      { speaker: 'naoko_aunt', jp: '本当にうるさい。でも、それでええ。', en: 'Really noisy. But — that\'s how it should be.', style: 'Big Kansai grin in the voice. The contradiction is the warmth.', mood: 'kansai_grin' },
      { speaker: 'sachiko_grandma', jp: 'わかります。…一人の時間も、大変だから。', en: 'I understand. …Time alone — it can be hard too.', style: 'Half a step quieter. Slight truth-telling.', mood: 'half_truth' },
      { speaker: 'naoko_aunt', jp: 'やんなあ。今度、関西来た時、連絡しいや。', en: 'Right? Next time you\'re in Kansai — give me a shout.', style: 'Pulls out a card in the voice. Practical, immediate Kansai care.', mood: 'practical_warmth' },
      { speaker: 'sachiko_grandma', jp: '本当に？嬉しいです。ありがとうございます。', en: 'Really? I\'m glad. Thank you so much.', style: 'A real bow inside the voice. The 「嬉しい」 unforced.', mood: 'touched_glad' },
    ],
  },
  {
    id: 'conv_00049',
    context: 'A Tuesday evening phone call. Kenji, between meetings, calls his mother. She picks up on the second ring.',
    purpose: 'adult son to aging mother — light maintenance call with a small genuine moment',
    ambient: 'phone_call_silent',
    target_vocab: ['今','本当に','元気','時間','大丈夫','明日','大変'],
    cast: ['kenji_office','sachiko_grandma'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'もしもし、けんちゃん？', en: 'Hello — Ken-chan?', style: 'Pleased recognition. The childhood diminutive still in use.', mood: 'pleased_recognising' },
      { speaker: 'kenji_office', jp: '母さん、元気？今、大丈夫？', en: 'Mom — you good? Got a sec?', style: 'Brisk but warm. Walking somewhere in the voice.', mood: 'warm_brisk' },
      { speaker: 'sachiko_grandma', jp: '元気よ。あなたは？仕事、大変じゃない？', en: 'I\'m well. And you? Work isn\'t too hard?', style: 'The mother\'s first instinct: ask back. Voice gentle.', mood: 'asking_back' },
      { speaker: 'kenji_office', jp: 'まあ、まあ。今日、長かった。', en: 'It\'s — fine. Today was long.', style: 'Half-honest. Doesn\'t want to worry her, can\'t lie either.', mood: 'half_honest' },
      { speaker: 'sachiko_grandma', jp: 'そう。無理しちゃ駄目よ。本当に。', en: 'Mm. Don\'t push yourself. Really.', style: 'Slow, weighted. The 「本当に」 is the whole line.', mood: 'maternal_warning' },
      { speaker: 'kenji_office', jp: 'うん。…明日は早く帰る予定。', en: 'Yeah. …Planning to come home early tomorrow.', style: 'A small offering of reassurance. Voice softer.', mood: 'reassuring' },
      { speaker: 'sachiko_grandma', jp: 'いつ、こっち来れる？', en: 'When can you come over?', style: 'The question she has been holding onto. Light, but real.', mood: 'gentle_ask' },
      { speaker: 'kenji_office', jp: '今月中…たぶん。時間、作る。', en: 'Within this month… probably. I\'ll make time.', style: 'A promise to himself as much as her. Walks faster in the voice.', mood: 'promising_self' },
      { speaker: 'sachiko_grandma', jp: '無理しないで。…声、聞けたから、それでいい。', en: 'Don\'t push yourself. …Just hearing your voice — that\'s enough.', style: 'The line every adult child eventually hears. Slow, real.', mood: 'enough_real' },
      { speaker: 'kenji_office', jp: '…うん。また電話する。', en: '…Yeah. I\'ll call again.', style: 'Smaller. Caught by the line. A beat before he speaks.', mood: 'caught_smaller' },
      { speaker: 'sachiko_grandma', jp: 'お仕事、頑張ってね。', en: 'Work hard, alright.', style: 'Closing line, the universal mom version. Affectionate.', mood: 'closing_warm' },
    ],
  },
  {
    id: 'conv_00050',
    context: 'A small clinic in Fukuoka. Goro has come in (against his preference) for a routine check. Dr. Saito is on a one-day visiting rotation.',
    purpose: 'gruff old man at the doctor — Kyushu drawl meets clinical calm',
    ambient: 'clinic_waiting_room',
    target_vocab: ['本当に','大丈夫','痛い','時間','少し','どこ'],
    cast: ['saito_doctor','goro_grandpa'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'こちら、おかけください。今日はどうされましたか？', en: 'Please, have a seat. What brings you in today?', style: 'Calm, professional, even. Eye-contact in the voice.', mood: 'professional_calm' },
      { speaker: 'goro_grandpa', jp: '別に。娘が、行けっち。', en: 'Nothing, really. Daughter said go.', style: 'Kyushu drawl, half-grumbling. Sits down anyway.', mood: 'grumpy_kyushu' },
      { speaker: 'saito_doctor', jp: '(small smile) なるほど。最近、どこか痛みは？', en: '(small smile) I see. Any pain anywhere lately?', style: 'A real small smile audible. Diagnostic but warm.', mood: 'gently_amused' },
      { speaker: 'goro_grandpa', jp: '膝な、少し。歩いたら、もうな。', en: 'Knee — a little. When I walk, well — you know.', style: 'Pats his own knee in the voice. Reluctant honest admission.', mood: 'reluctant_admission' },
      { speaker: 'saito_doctor', jp: '見せていただいてもいいですか。', en: 'May I take a look?', style: 'Formal, asking permission. Doesn\'t touch first.', mood: 'careful_asking' },
      { speaker: 'goro_grandpa', jp: '…どうぞ。', en: '…Go on.', style: 'Single word. Permission given, not enthusiastically.', mood: 'reluctant_permission' },
      { speaker: 'saito_doctor', jp: 'うん。少し炎症がありますね。本当に、無理せずに。', en: 'Mm. There\'s some inflammation. Please don\'t push yourself.', style: 'Clinical observation paired with real warmth on 「本当に」.', mood: 'clinical_warm' },
      { speaker: 'goro_grandpa', jp: '俺、漁師やったんよ、昔。', en: 'I used to be a fisherman, back then.', style: 'Non sequitur but real. Explaining himself indirectly.', mood: 'indirect_explaining' },
      { speaker: 'saito_doctor', jp: 'だからこそ、今、大切に。お時間、もう少し取れますか？', en: 'Exactly why — be careful now. Can I have a bit more of your time?', style: 'Doesn\'t patronise. Asks like he\'s the boss.', mood: 'respectful_asking' },
    ],
  },
  {
    id: 'conv_00051',
    context: 'A small inn in Iwate. A retired Tokyo professor (Hiroshi Kato) and a local farmer (Tatsuya Endo) end up at adjacent low tables in the dining room. They start a conversation slowly.',
    purpose: 'two retirees meet over dinner — city scholar and country man recognising each other',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','一緒','元気','大変','ない','見る','子供'],
    cast: ['hiroshi_elder','tatsuya_country'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'こんばんは。少し、いいですか。', en: 'Good evening. May I — a moment?', style: 'Slow, polite, asking permission to share a table. A small bow inside the voice.', mood: 'careful_polite' },
      { speaker: 'tatsuya_country', jp: 'ああ、どうぞ。', en: 'Ah — please.', style: 'Two words, unhurried Tohoku softness. Gestures at the cushion.', mood: 'unhurried_welcome' },
      { speaker: 'hiroshi_elder', jp: 'お一人で、ご旅行ですか。', en: 'Travelling alone, are you?', style: 'A small conversational opener. Slow, considered.', mood: 'opener_slow' },
      { speaker: 'tatsuya_country', jp: 'いや、ここに住んどる。', en: 'No — I live here.', style: 'Slight Tohoku smile audible. Slight pride.', mood: 'local_pride' },
      { speaker: 'hiroshi_elder', jp: 'ああ、これは失礼を。…本当にいい場所ですね。', en: 'Ah — my apologies. …Truly a fine place.', style: 'Bows again in the voice. The 「本当に」 unforced.', mood: 'apologetic_admiring' },
      { speaker: 'tatsuya_country', jp: '東京の方ですか。', en: 'You\'re from Tokyo?', style: 'Plain question. Eyes on the bowl, ears fully on.', mood: 'plain_asking' },
      { speaker: 'hiroshi_elder', jp: 'はい。退職してから、こうして時々。', en: 'Yes. Since I retired — I travel like this now and then.', style: 'A small life-story compressed. Slow, complete sentences.', mood: 'autobiographical_slow' },
      { speaker: 'tatsuya_country', jp: 'いいなあ。うちの娘も、東京。', en: 'Nice. My daughter\'s in Tokyo too.', style: 'A small offering. Pride and distance equal.', mood: 'small_offering' },
      { speaker: 'hiroshi_elder', jp: 'そうですか。お元気で？', en: 'Is that so. She\'s well?', style: 'Genuine interest. Sets his chopsticks down half a step.', mood: 'genuine_interest' },
      { speaker: 'tatsuya_country', jp: '元気らしい。会えるか、年に一回。', en: 'Well — apparently. See her about once a year.', style: 'Plain, unembellished. The honest report of a Tohoku father.', mood: 'plain_father' },
      { speaker: 'hiroshi_elder', jp: '…私の息子も、似たような感じです。', en: '…My son\'s much the same.', style: 'Quiet recognition. The small unexpected club of distant-children fathers.', mood: 'quiet_club' },
      { speaker: 'tatsuya_country', jp: '(small nod) 子供は、子供なりに、大変なんやろな。', en: '(small nod) Kids have their own kind of hard, I suppose.', style: 'A philosophy gently offered. Tohoku cadence.', mood: 'philosophical_gentle' },
      { speaker: 'hiroshi_elder', jp: '本当に。…一緒に飲みませんか、少し。', en: 'Truly. …Care to drink a little, together?', style: 'A small bridge offered. The 「少し」 lowers the stakes.', mood: 'small_invitation' },
      { speaker: 'tatsuya_country', jp: 'ええなあ。じゃ、一杯だけ。', en: 'Sounds good. One cup then.', style: 'A real small smile in the voice. Slides a cup across.', mood: 'agreeing_warm' },
    ],
  },
  {
    id: 'conv_00052',
    context: 'Friday night, kitchen of their apartment. Yumiko has had a day. Ryosuke is washing dishes and knows the signs.',
    purpose: 'partner debrief — a hard day, decompressed in real time',
    ambient: 'apartment_indoor',
    target_vocab: ['今日','本当に','大変','大丈夫','時間','ない','一緒'],
    cast: ['yumiko_mom','ryosuke_dad'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '…今日、本当に最悪だった。', en: '…Today was actually awful.', style: 'Sets her bag down hard. The 「本当に」 carries the whole day.', mood: 'dumping_in' },
      { speaker: 'ryosuke_dad', jp: 'おかえり。座って。ワインある。', en: 'Welcome home. Sit. There\'s wine.', style: 'Already pouring. Doesn\'t ask what happened — gives her a runway first.', mood: 'runway_given' },
      { speaker: 'yumiko_mom', jp: 'ありがとう。…本当に、本当に長い一日。', en: 'Thank you. …Really, really long day.', style: 'Sits, drops the bag at her feet. Doubled 「本当に」 — real, not theatrical.', mood: 'real_tired' },
      { speaker: 'ryosuke_dad', jp: 'まあ、話したかったら話して。話したくなかったら、別に。', en: 'If you want to talk — talk. If not — that\'s fine too.', style: 'Spoken to the dishes. Calm, no pressure. Towel over shoulder.', mood: 'no_pressure' },
      { speaker: 'yumiko_mom', jp: 'クライアントが、本当にひどくて。', en: 'The client — was really awful.', style: 'A short complete sentence. The dam breaks evenly.', mood: 'dam_breaking' },
      { speaker: 'ryosuke_dad', jp: 'うん。', en: 'Mm.', style: 'One syllable. All listening. Hands keep moving on the dishes.', mood: 'listening' },
      { speaker: 'yumiko_mom', jp: '私のせいじゃないのに、ずっと文句言ってきて。', en: 'Wasn\'t even my fault and he just kept complaining.', style: 'Frustrated honest. Voice climbs a half-step.', mood: 'frustrated_honest' },
      { speaker: 'ryosuke_dad', jp: 'それは、大変だな。', en: 'That sounds rough.', style: 'No solution-offering. The validation as the only thing needed.', mood: 'validating' },
      { speaker: 'yumiko_mom', jp: 'うん…大丈夫、そのうち。今は、ちょっと一緒にいて。', en: 'Mm… it\'ll be okay, eventually. Just — sit with me a bit now.', style: 'A small softening. The honest ask.', mood: 'honest_ask' },
      { speaker: 'ryosuke_dad', jp: 'いるよ。時間あるから、ずっと。', en: 'I\'m here. I\'ve got time — for as long.', style: 'Sits down across from her, towel discarded. The whole evening offered.', mood: 'fully_present' },
      { speaker: 'yumiko_mom', jp: '…ありがとう。', en: '…Thank you.', style: 'The smallest line of the night. Eyes on the wine glass.', mood: 'small_grateful' },
    ],
  },
  {
    id: 'conv_00053',
    context: 'Closing time at the café where Aoi works. 9:55pm. One last customer — a tired-looking salaryman she\'s never seen before.',
    purpose: 'tiny late-night service encounter — small dignity from both sides',
    ambient: 'cafe_afternoon',
    target_vocab: ['今','本当に','大丈夫','時間','ありがとう'],
    cast: ['aoi_barista','kenji_office'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'いらっしゃいませ。あ、もうすぐ閉店なんですが…', en: 'Welcome. Oh — we\'re closing soon, just so you know.', style: 'Apologetic but warm. Already glancing at the clock in the voice.', mood: 'apologetic_warm' },
      { speaker: 'kenji_office', jp: 'あ、大丈夫です。テイクアウトでも。', en: 'Oh — that\'s fine. Take-away is fine too.', style: 'Half-relieved. Voice tired but kind.', mood: 'tired_kind' },
      { speaker: 'aoi_barista', jp: 'はい、もちろん。本当に、お時間ぎりぎりで…', en: 'Yes, of course. Sorry about the timing being so tight…', style: 'Genuinely apologetic. The 「本当に」 unforced.', mood: 'genuinely_sorry' },
      { speaker: 'kenji_office', jp: 'いえ、こっちこそ。最後の客で、すみません。', en: 'No — my fault. Sorry for being the last one.', style: 'A real polite mutual apology. Half-laughs at the absurdity.', mood: 'mutual_polite' },
      { speaker: 'aoi_barista', jp: 'お疲れさまですね。今日も、大変でしたか？', en: 'Hard day, huh. Was today rough too?', style: 'A small kindness beyond the script. Reads him in two seconds.', mood: 'reading_him' },
      { speaker: 'kenji_office', jp: '…ええ、まあ。よくわかりますね。', en: '…Yeah — a bit. You read it well.', style: 'A surprised small laugh. Caught being seen.', mood: 'caught_seen' },
      { speaker: 'aoi_barista', jp: 'お顔に出ます、ちょっとだけ。', en: 'It shows on the face — just a little.', style: 'A small smile. Sliding the cup across.', mood: 'small_smile' },
      { speaker: 'kenji_office', jp: '本当にありがとう。気持ち、少し軽くなった。', en: 'Really — thank you. Lightened things a bit.', style: 'Sincere. Voice slightly different than when he came in.', mood: 'sincerely_lighter' },
    ],
  },
  {
    id: 'conv_00054',
    context: 'Saturday morning. Yumiko is signing a permission slip. Hina hovers, dramatic, ready to defend her case.',
    purpose: 'tiny domestic logistics — kid lobbying mom',
    ambient: 'apartment_indoor',
    target_vocab: ['今日','本当に','大丈夫','ありがとう'],
    cast: ['yumiko_mom','hina_child'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'お母さん、これ、はやくサインして！', en: 'Mom — sign this, hurry!', style: 'Shoves the paper in front of her, bouncing.', mood: 'urgent_kid' },
      { speaker: 'yumiko_mom', jp: 'はいはい。…遠足、来週？', en: 'Yes, yes. …Field trip next week?', style: 'Pen already in hand. Reading even while signing.', mood: 'efficient_mom' },
      { speaker: 'hina_child', jp: 'うん！本当に行きたい！', en: 'Yeah! I really want to go!', style: 'Adds the lobbying even after she\'s being signed up. Eight-year-old logic.', mood: 'lobbying' },
      { speaker: 'yumiko_mom', jp: '大丈夫、サインしてる。', en: 'It\'s fine — I\'m signing it.', style: 'Half-laugh. The mom-voice of someone who has done this thirty times.', mood: 'amused_mom' },
      { speaker: 'hina_child', jp: 'ありがとうお母さん大好き！', en: 'Thank you mom love you!', style: 'All one breath, full kid-volume. Already running off in the voice.', mood: 'all_one_breath' },
      { speaker: 'yumiko_mom', jp: '今日のうちに、ランドセル準備してね？', en: 'Get your school-bag ready today, okay?', style: 'Calls after her in the voice. Pragmatic afterword.', mood: 'practical_afterword' },
    ],
  },
  {
    id: 'conv_00055',
    context: 'Monday morning, office cafeteria. Daichi is hungover; Kenji is unreasonably cheerful.',
    purpose: 'morning-after banter — friend solidarity through teasing',
    ambient: 'office_open_plan',
    target_vocab: ['今日','本当に','大丈夫','時間','水'],
    cast: ['daichi_kansai','kenji_office'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: 'おはよう。…生きてる？', en: 'Morning. …You alive?', style: 'A small grin in the voice. Sets a cup of water in front of him.', mood: 'grinning' },
      { speaker: 'daichi_kansai', jp: '生きとらん。本当に、生きとらん。', en: 'Not alive. Genuinely — not alive.', style: 'Head down on the table in the voice. Full Kansai protest.', mood: 'mock_dying' },
      { speaker: 'kenji_office', jp: '水、飲み。今日、午後会議やで。', en: 'Drink some water. You\'ve got a meeting this afternoon, you know.', style: 'Half-laughs. Borrows Kansai for one phrase, mockingly.', mood: 'mocking_kansai' },
      { speaker: 'daichi_kansai', jp: 'やめてや、お前。本当に、やめてや。', en: 'Stop, man. Really — stop.', style: 'Mock-injured. Voice cracks in mock-pain.', mood: 'mock_injured' },
      { speaker: 'kenji_office', jp: '大丈夫やって、時間あるから。寝とき、少し。', en: 'You\'ll be fine — got time. Sleep a bit.', style: 'Genuine warm pat-on-shoulder energy. Real friendship under the bit.', mood: 'real_friendship' },
      { speaker: 'daichi_kansai', jp: '…ありがと。本当に。', en: '…Thanks. Really.', style: 'Mumbled, real. The quietest he\'s been all morning.', mood: 'real_thanks' },
    ],
  },
  {
    id: 'conv_00056',
    context: 'A small café in Shibuya. Hiroshi (the boss) and Asuka (the teacher) were classmates in university. They run into each other for the first time in fifteen years.',
    purpose: 'old-friends reunion — accidental, slightly awkward, then real',
    ambient: 'cafe_afternoon',
    target_vocab: ['本当に','時間','今','大変','元気','一緒','友達'],
    cast: ['hiroshi_boss','asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'えっ…ひろし？', en: 'Wait… Hiroshi?', style: 'Half-rises in the voice. Genuine surprise.', mood: 'genuine_surprise' },
      { speaker: 'hiroshi_boss', jp: '…あすか？うわ、本当に久しぶり。', en: '…Asuka? Wow — it\'s really been a while.', style: 'The composed boss-voice cracks half a step. Pleased.', mood: 'composed_cracking' },
      { speaker: 'asuka_teacher', jp: '何年ぶり？十五年？', en: 'How many years? Fifteen?', style: 'Already grabbing the chair across from him. Brisk.', mood: 'brisk_recovering' },
      { speaker: 'hiroshi_boss', jp: 'そのくらい…本当に、時間ってあっという間。', en: 'About that… really — time, it flies.', style: 'The boss-philosophy of a man who suddenly feels old.', mood: 'mortality_brief' },
      { speaker: 'asuka_teacher', jp: '元気そう。仕事、今どこ？', en: 'You look well. Where are you working now?', style: 'Easy, real curiosity. Sits forward in the voice.', mood: 'easy_curious' },
      { speaker: 'hiroshi_boss', jp: '同じ会社で、ずっと。…部長になったよ。', en: 'Same company — the whole time. …Made department head.', style: 'A small admission. Voice slightly proud, slightly embarrassed.', mood: 'modest_admission' },
      { speaker: 'asuka_teacher', jp: 'おお、すごい。一緒に勉強した子が…', en: 'Whoa — impressive. The kid I studied with…', style: 'A real laugh of recognition. Affectionate.', mood: 'affectionate_recognition' },
      { speaker: 'hiroshi_boss', jp: 'やめろよ(laughs)。あすかは？', en: 'Stop it — (laughs). And you?', style: 'The composed-boss laugh, rare in the wild. Genuine.', mood: 'rare_laugh' },
      { speaker: 'asuka_teacher', jp: '日本語教えてる。本当に楽しいよ。', en: 'I teach Japanese. It\'s really fun.', style: 'Direct, unembellished, glad. The 「本当に」 lands genuine.', mood: 'direct_glad' },
      { speaker: 'hiroshi_boss', jp: '…合ってるね、あすかに。本当に。', en: '…It suits you. Really.', style: 'A small thoughtful pause. The real-friend observation.', mood: 'real_observation' },
      { speaker: 'asuka_teacher', jp: 'ね、また飲みに行こ。時間、作って？', en: 'Hey — let\'s go for drinks. Make the time?', style: 'Half-command, half-invite. Old-classmate energy.', mood: 'old_classmate' },
      { speaker: 'hiroshi_boss', jp: '本当に、作る。連絡先、交換しよう。', en: 'Really — I will. Let\'s swap contacts.', style: 'A small decisive line. Phone out in the voice.', mood: 'small_decisive' },
    ],
  },
  {
    id: 'conv_00057',
    context: 'Mei\'s apartment, midweek. Her older "aunt-friend" Naoko has visited from Osaka and is unpacking food in Mei\'s kitchen, uninvited.',
    purpose: 'older-woman-younger-woman intergenerational — Kansai care meets Tokyo gentleness',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','今','元気','時間','一緒','大丈夫'],
    cast: ['naoko_aunt','mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'メイちゃん、これ、冷蔵庫入れとき。', en: 'Mei-chan — put this in the fridge.', style: 'Already shoving containers into said fridge in the voice. Kansai economy.', mood: 'shoving' },
      { speaker: 'mei_romantic', jp: 'なおこさん、本当に多すぎ…', en: 'Naoko-san — really, too much…', style: 'Half-laugh of disbelief. The apartment is too small.', mood: 'amused_overwhelmed' },
      { speaker: 'naoko_aunt', jp: '多い方がええんよ。一人やろ？', en: 'Better too much. You\'re alone, aren\'t you?', style: 'The Kansai logic delivered as fact. Mid-action.', mood: 'kansai_fact' },
      { speaker: 'mei_romantic', jp: '一人やないですよ、レンが…', en: 'I\'m not alone — Ren\'s here…', style: 'A small smile in the voice. Half-protest.', mood: 'small_smile' },
      { speaker: 'naoko_aunt', jp: 'あー、彼ね。元気？ちゃんと食べてる？', en: 'Ah, that one. Well? Eating properly?', style: 'Switches without missing a beat. Still moving in the voice.', mood: 'shifting_interrogation' },
      { speaker: 'mei_romantic', jp: '元気です。本当に、よく食べる。', en: 'He\'s well. Really — he eats a lot.', style: 'A real fond smile audible.', mood: 'fond' },
      { speaker: 'naoko_aunt', jp: 'よろしい。…で、メイちゃんは、最近、大丈夫？', en: 'Good. …And you — are you alright lately?', style: 'Stops moving. Voice drops half a register. The real question.', mood: 'pivot_real' },
      { speaker: 'mei_romantic', jp: '…うん、大丈夫。本当に。', en: '…Mm — fine. Really.', style: 'A small honest pause before the answer. Means it.', mood: 'honest_pause' },
      { speaker: 'naoko_aunt', jp: 'ええわ、それなら。今度、一緒にどっか行こ。', en: 'Good then. Next time — let\'s go somewhere together.', style: 'Already moving again. The plan as the affection.', mood: 'plan_as_love' },
      { speaker: 'mei_romantic', jp: 'はい。時間、ちゃんと作ります。', en: 'Yes — I\'ll make the time, properly.', style: 'Quiet promise. A small bow inside the voice.', mood: 'quiet_promise' },
    ],
  },
  {
    id: 'conv_00058',
    context: 'After-school office at the language/career school. Riku is sitting across from Asuka. He needs help preparing for his first part-time job interview.',
    purpose: 'mentor preparation — gentle teacher, anxious teen',
    ambient: 'school_classroom',
    target_vocab: ['本当に','大丈夫','今','時間','言う','どう','少し'],
    cast: ['asuka_teacher','riku_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'じゃ、リクくん、座って。緊張してる？', en: 'Right — Riku-kun, sit. You nervous?', style: 'Sits across from him at his height. Calm.', mood: 'calm_inviting' },
      { speaker: 'riku_teen', jp: '…めっちゃ。', en: '…Super.', style: 'One word, mumbled. Eyes on the desk.', mood: 'mumbled_one_word' },
      { speaker: 'asuka_teacher', jp: '大丈夫。本当に、誰でも緊張する。', en: 'It\'s fine. Really — everyone gets nervous.', style: 'Normalising warmth. Slides a glass of water across.', mood: 'normalising' },
      { speaker: 'riku_teen', jp: '何、言えばいい？', en: 'What do I even say?', style: 'Half-helpless. Looks up briefly.', mood: 'helpless_looking_up' },
      { speaker: 'asuka_teacher', jp: 'まず、名前と、学校と、なぜ働きたいか。', en: 'First — name, school, and why you want to work.', style: 'Listing on her fingers in the voice. Practical.', mood: 'practical_listing' },
      { speaker: 'riku_teen', jp: 'なぜ…本当のこと言っていい？', en: 'Why… can I say the honest reason?', style: 'A small hopeful question. Voice cracks half a step.', mood: 'hopeful_check' },
      { speaker: 'asuka_teacher', jp: 'うん。むしろ、本当のことの方が伝わるから。', en: 'Yes — actually, honest answers land better.', style: 'Patient, real. The teacher\'s favourite line.', mood: 'patient_real' },
      { speaker: 'riku_teen', jp: 'お金、欲しい。本当に。新しいギター、買いたくて。', en: 'I want money. Really. Want to buy a new guitar.', style: 'A surprised honest rush. The truth comes out fast.', mood: 'honest_rush' },
      { speaker: 'asuka_teacher', jp: 'いいね。それ、すごくいい理由。', en: 'That\'s good. Really solid reason, actually.', style: 'A real teacher-affirmation. Not performative.', mood: 'real_affirming' },
      { speaker: 'riku_teen', jp: 'え、本当に？', en: 'Wait — really?', style: 'Looks fully up for the first time. Voice lifts.', mood: 'lifting_up' },
      { speaker: 'asuka_teacher', jp: 'うん。じゃ、少し練習しよう。時間、まだある。', en: 'Yes. Let\'s practise a little. We\'ve got time.', style: 'Hand-on-table warmth. The mentor settling in.', mood: 'mentor_settling' },
    ],
  },
  {
    id: 'conv_00059',
    context: 'A Saturday morning phone call. Six-year-old Sho calls his grandpa Goro in Fukuoka. He has news.',
    purpose: 'tiny grandkid-grandparent call — small joy delivered with no preamble',
    ambient: 'phone_call_silent',
    target_vocab: ['本当に','元気','今日','ありがとう','大丈夫'],
    cast: ['sho_child','goro_grandpa'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'goro_grandpa', jp: 'もしもし。', en: 'Hello.', style: 'Slow, gravelly Kyushu drawl. Two syllables.', mood: 'unhurried' },
      { speaker: 'sho_child', jp: 'おじいちゃん、しょうです。', en: 'Grandpa — it\'s Sho.', style: 'A small formal kid-introduction. Pleased with himself.', mood: 'formal_proud' },
      { speaker: 'goro_grandpa', jp: 'ああ、しょうか。元気か。', en: 'Ahh, Sho — you well?', style: 'A small smile audible. The pleased-grandpa voice.', mood: 'pleased_grandpa' },
      { speaker: 'sho_child', jp: '元気。今日ね、自転車、乗れた。', en: 'Good. Today — I rode my bike.', style: 'A small breathless announcement. The whole reason for the call.', mood: 'announcing' },
      { speaker: 'goro_grandpa', jp: 'ほう。本当に？', en: 'Oh — really?', style: 'Genuine astonishment, even though he\'s probably been expecting this call.', mood: 'astonished' },
      { speaker: 'sho_child', jp: '本当に！もう、転ばない。', en: 'Really! I don\'t fall anymore.', style: 'Pure six-year-old certainty. Voice bouncing.', mood: 'certain_kid' },
      { speaker: 'goro_grandpa', jp: 'えらいなあ。今度、見せて。', en: 'Good lad. Show me next time.', style: 'A small slow proud line. Real.', mood: 'slow_proud' },
      { speaker: 'sho_child', jp: 'うん！…おじいちゃん、ありがとう。', en: 'Yeah! …Grandpa — thanks.', style: 'A sudden quiet line. Doesn\'t explain why he\'s thanking him.', mood: 'sudden_quiet' },
    ],
  },
  {
    id: 'conv_00060',
    context: 'Hiroshi (elder) and Mrs. Mori have been neighborhood acquaintances for years. Today they end up at the same bench outside a temple in autumn.',
    purpose: 'old neighbours bench-talk — small gossip, mostly companionship',
    ambient: 'shrine_grounds',
    target_vocab: ['本当に','今日','時間','元気','人','見る'],
    cast: ['hiroshi_elder','mrs_mori_neighbor'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'あら、ひろし先生。お元気そうで。', en: 'Oh — Hiroshi-sensei. You look well.', style: 'Loud opener. Kansai brightness, even on a quiet bench.', mood: 'bright_opener' },
      { speaker: 'hiroshi_elder', jp: 'よしえさん、こちらこそ。お久しぶり。', en: 'Yoshie-san — likewise. It\'s been a while.', style: 'Slow polite return. A small bow inside the voice.', mood: 'polite_return' },
      { speaker: 'mrs_mori_neighbor', jp: '本当に、今日いい天気やね。', en: 'Really — fine weather today, eh.', style: 'Casual Kansai. The 「ね」 carries the small-talk DNA.', mood: 'casual_kansai' },
      { speaker: 'hiroshi_elder', jp: '本当に。…秋は、時間の流れが違って感じる。', en: 'Truly. …Autumn — time flows differently somehow.', style: 'Slow, philosophical. The retired-professor voice.', mood: 'philosophical_slow' },
      { speaker: 'mrs_mori_neighbor', jp: '先生、いつもそういうこと言うね。', en: 'Sensei — you always say things like that, you know.', style: 'Affectionate teasing. A real laugh in the voice.', mood: 'affectionate_teasing' },
      { speaker: 'hiroshi_elder', jp: '(small chuckle) 職業病ですね。', en: '(small chuckle) Professional habit, I suppose.', style: 'A real small laugh. Self-aware.', mood: 'self_aware' },
      { speaker: 'mrs_mori_neighbor', jp: 'うちの裏の人、見た？引っ越したらしい。', en: 'You see the folks behind my place? Apparently they moved.', style: 'Switches to gossip without missing a beat. Voice drops half a register.', mood: 'gossip_drop' },
      { speaker: 'hiroshi_elder', jp: '本当に？知らなかった。最近、見かけなかったが。', en: 'Really? Didn\'t know. Hadn\'t seen them lately, true.', style: 'Slow interest. Files the information carefully.', mood: 'cataloguing' },
      { speaker: 'mrs_mori_neighbor', jp: 'やんなあ。…またお茶でもしよ。今度、ぜひ。', en: 'Right? …Let\'s have tea again. Definitely, next time.', style: 'A small invitation, real.', mood: 'inviting_real' },
      { speaker: 'hiroshi_elder', jp: 'ぜひ。お時間、合わせます。', en: 'I\'d like that. I\'ll match your time.', style: 'Polite, genuine. A real friendship maintained on a bench.', mood: 'genuine_polite' },
      { speaker: 'mrs_mori_neighbor', jp: '本当に、ええ人やわ、ひろしさん。', en: 'Truly — you\'re a good person, Hiroshi-san.', style: 'Unguarded Kansai warmth. Said toward the temple, not him.', mood: 'unguarded_warm' },
    ],
  },
  {
    id: 'conv_00061',
    context: 'A Shinkansen carriage. Sakura sits down, putting her bag on the floor. Tatsuya is in the next seat, eating an onigiri. Three brief exchanges.',
    purpose: 'tiny strangers-on-a-train moment — kindness exchanged in six lines',
    ambient: 'train_carriage',
    target_vocab: ['すみません','ありがとう','本当に','大丈夫'],
    cast: ['tatsuya_country','sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'すみません、ここ、空いてますか？', en: 'Sorry — is this seat free?', style: 'Polite Kansai-Tokyo blend. A small bow inside the voice.', mood: 'polite_kansai' },
      { speaker: 'tatsuya_country', jp: 'ああ、どうぞ。', en: 'Ah — please.', style: 'Slow Tohoku warmth. Two unhurried syllables.', mood: 'unhurried_welcome' },
      { speaker: 'sakura_teen', jp: 'ありがとうございます。…おにぎり、おいしそう。', en: 'Thank you. …Onigiri looks good.', style: 'A small commentary, half-honest, half-friendly.', mood: 'small_friendly' },
      { speaker: 'tatsuya_country', jp: 'うん。家で握ったやつ。一個、いる？', en: 'Mm. Made at home. Want one?', style: 'Offers without ceremony. Holds one out in the voice.', mood: 'offering_unceremonious' },
      { speaker: 'sakura_teen', jp: 'えっ、本当に？大丈夫ですか？', en: 'Wait — really? Are you sure?', style: 'Genuine surprise, half-laugh. Kansai cadence under the politeness.', mood: 'genuine_surprise' },
      { speaker: 'tatsuya_country', jp: 'ええよ。長い旅やからな。', en: 'Sure. It\'s a long trip.', style: 'A small Tohoku smile audible. Slow.', mood: 'slow_kind' },
    ],
  },
  {
    id: 'conv_00062',
    context: 'A late-night wine bar after work. Yuki has been carrying something for months. Yumiko — her senior, now her friend — has noticed. Tonight she sits Yuki down.',
    purpose: 'deferred confessional — junior to senior, woman to woman',
    ambient: 'bar_evening',
    target_vocab: ['本当に','時間','大丈夫','今','言う','大変','友達','心配'],
    cast: ['yuki_office','yumiko_mom'],
    frequency_tier: 2,
    length_tier: 'Extended (21-30)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'ねえ、ゆきちゃん。…ちょっと、聞いていい？', en: 'Hey, Yuki-chan. …Can I ask you something?', style: 'Sets her glass down deliberately. Voice softer than usual.', mood: 'deliberate_soft' },
      { speaker: 'yuki_office', jp: 'はい…どうぞ。', en: 'Yes — please.', style: 'Quiet. Already knows what kind of question it will be.', mood: 'already_knowing' },
      { speaker: 'yumiko_mom', jp: '最近、ちょっと元気ない気がして。本当に、大丈夫？', en: 'Lately — you\'ve seemed a bit off. Really — are you okay?', style: 'The line she has been holding for two weeks. Direct but warm.', mood: 'long_held_question' },
      { speaker: 'yuki_office', jp: '…そんなに、わかりやすいですか？', en: '…Is it that obvious?', style: 'Half-laugh, half-tear. Caught being seen.', mood: 'caught_seen' },
      { speaker: 'yumiko_mom', jp: 'うん。先輩、伊達じゃないからね。', en: 'Mm. I\'m a senior for a reason.', style: 'A small joke to soften the moment. Warm.', mood: 'gentle_joke' },
      { speaker: 'yuki_office', jp: '…本当は、ずっと、悩んでて。', en: '…Truthfully — I\'ve been struggling for a while.', style: 'A quiet release. A breath before each clause.', mood: 'quiet_release' },
      { speaker: 'yumiko_mom', jp: 'うん。', en: 'Mm.', style: 'One syllable. All listening. Hands on the glass.', mood: 'listening' },
      { speaker: 'yuki_office', jp: '今の仕事…向いてない気がして。', en: 'This job… I don\'t think I\'m suited for it.', style: 'The sentence she hasn\'t said out loud yet.', mood: 'releasing_truth' },
      { speaker: 'yumiko_mom', jp: 'なるほど。…どのくらい、考えてた？', en: 'I see. …How long have you been thinking about it?', style: 'No reaction yet. Pure listening tone.', mood: 'pure_listening' },
      { speaker: 'yuki_office', jp: '半年くらい…毎日。', en: 'About six months… every day.', style: 'A small relieved exhale. The weight measured out.', mood: 'naming_weight' },
      { speaker: 'yumiko_mom', jp: '半年か…それは、本当に大変だったね。', en: 'Six months… that\'s genuinely been rough.', style: 'Real recognition. Not pity — recognition.', mood: 'recognising' },
      { speaker: 'yuki_office', jp: '…誰にも言えなくて。', en: '…Couldn\'t tell anyone.', style: 'The quietest line so far. Voice catches half a step.', mood: 'quietest_yet' },
      { speaker: 'yumiko_mom', jp: '私には、いつでも言っていいから。本当に。', en: 'You can tell me anytime. Really.', style: 'Firm warmth. The 「本当に」 carries the weight of years of office friendship.', mood: 'firm_warmth' },
      { speaker: 'yuki_office', jp: 'ありがとうございます…でも、心配かけたくなくて。', en: 'Thank you… but I didn\'t want to worry you.', style: 'Classic Yuki self-effacement. Voice small.', mood: 'self_effacing' },
      { speaker: 'yumiko_mom', jp: '心配かけてくれていいの。それが友達。', en: 'Worrying me is allowed. That\'s what friends do.', style: 'A firm sentence said gently. The pivot of the conversation.', mood: 'pivot_firm' },
      { speaker: 'yuki_office', jp: '…(small breath, eyes wet)', en: '(small breath, eyes wet)', style: 'A real beat. Doesn\'t need to speak. The whole weight resettling.', mood: 'resettling' },
      { speaker: 'yumiko_mom', jp: 'で。次、何したい？少しでも、思ってること、ある？', en: 'So — what do you want next? Even a little — anything you\'ve thought about?', style: 'Pivoting toward action without rushing her.', mood: 'pivoting_forward' },
      { speaker: 'yuki_office', jp: '…まだ、わからない。でも、考えてもいいって思えただけで、楽になった。', en: '…I don\'t know yet. But just being allowed to think about it — it\'s easier.', style: 'A real small relief audible. The conversation\'s actual purpose.', mood: 'real_relief' },
      { speaker: 'yumiko_mom', jp: 'それで十分。時間、ちゃんとかけてね。', en: 'That\'s enough. Take the time, properly.', style: 'Closing-but-not-closing. The mentorship offered without taking over.', mood: 'mentor_closing' },
      { speaker: 'yuki_office', jp: '…本当に、ありがとうございます。', en: '…Truly — thank you.', style: 'The night condensed into one line. Voice steady now.', mood: 'condensed_thanks' },
      { speaker: 'yumiko_mom', jp: 'もう一杯飲も。話、変えていいよ。', en: 'Let\'s have another. Change the topic if you want.', style: 'A practical kindness — releasing the weight of the conversation by lifting it.', mood: 'practical_release' },
      { speaker: 'yuki_office', jp: 'はい…ぜひ。', en: 'Yes… please.', style: 'A small grateful exhale. The night softens.', mood: 'grateful_exhale' },
    ],
  },
  {
    id: 'conv_00063',
    context: 'A small neighborhood library, last hour before closing. Hiroshi (elder) is finishing a shift volunteering. Aoi has come in to return a book.',
    purpose: 'tiny incidental kindness — two people in their separate weeks crossing paths',
    ambient: 'school_classroom',
    target_vocab: ['本当に','時間','今日','ありがとう','見る'],
    cast: ['hiroshi_elder','aoi_barista'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'こんばんは。返却ですか？', en: 'Good evening. Returning a book?', style: 'Calm, professional library voice. Eye-contact in the voice.', mood: 'calm_professional' },
      { speaker: 'aoi_barista', jp: 'はい、これ、お願いします。', en: 'Yes — this one, please.', style: 'A small bow inside the voice. Tired from the café shift.', mood: 'tired_polite' },
      { speaker: 'hiroshi_elder', jp: 'はい…おや、これ、面白かったでしょう。', en: 'Right… oh, this one — fun book, isn\'t it.', style: 'A small note of genuine recognition. The librarian-volunteer\'s pleasure.', mood: 'genuine_recognition' },
      { speaker: 'aoi_barista', jp: '本当に面白かったです。一気に読みました。', en: 'Really enjoyed it. Read it in one go.', style: 'Surprised by his interest. A small smile audible.', mood: 'surprised_smile' },
      { speaker: 'hiroshi_elder', jp: 'いいですね。…同じ作者の、別の本も、見ますか？', en: 'Wonderful. …Want to look at another by the same author?', style: 'Already turning toward the shelf in the voice. Gentle offer.', mood: 'gentle_offer' },
      { speaker: 'aoi_barista', jp: 'えっ、本当にいいんですか？お時間…', en: 'Wait — really? Your time…', style: 'Caught. Half-protests, half-grateful.', mood: 'caught_grateful' },
      { speaker: 'hiroshi_elder', jp: '今日は、あと十五分くらい暇です。', en: 'I\'ve got about fifteen more free minutes today.', style: 'A small joke in the voice. Walking toward the shelf.', mood: 'small_joke' },
      { speaker: 'aoi_barista', jp: 'じゃあ、ぜひ。…本当に、ありがとうございます。', en: 'Then, please. …Thank you — really.', style: 'A real thank-you. The exhaustion of the shift lifting a little.', mood: 'real_thanks' },
      { speaker: 'hiroshi_elder', jp: 'こちらこそ、楽しみがあります。', en: 'Honestly — it\'s my pleasure.', style: 'A small warm closing. The librarian-volunteer\'s genuine line.', mood: 'genuine_closing' },
      { speaker: 'aoi_barista', jp: 'また、来ます。今度ゆっくり。', en: 'I\'ll come again. Properly, next time.', style: 'A small promise. Voice slightly brighter than when she walked in.', mood: 'small_promise' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log(`wrote ${CONVERSATIONS.length} conversation(s) to ${OUT_DIR}`);
