import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_130)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // THEME A — Legal (弁護士 裁判 訴訟 犯罪 措置)
  C('conv_02581',
    'Court news: Sakura and Ren report on a ruling.',
    'WIDENED SCENARIO: legal news; court vocabulary (裁判/訴訟/弁護士/犯罪/措置) in natural home.',
    'studio_room_tone',
    ['裁判', '訴訟', '弁護士', '犯罪', '措置'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '今日、注目の裁判で判決が出ました。', en: "A ruling came in a closely watched trial today.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'どんな訴訟だったんですか?', en: "What kind of lawsuit was it?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '企業を相手取った、長い訴訟でした。', en: "It was a long lawsuit against a company.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '弁護士は、何と述べましたか?', en: "What did the lawyer state?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '弁護士は、判決を評価しました。', en: "The lawyer praised the ruling.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '犯罪の防止にも、つながりますか?', en: "Will it help prevent crime too?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、再発を防ぐ措置も示されました。', en: "Yes, measures to prevent recurrence were shown.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'この裁判が、社会を変えるかもしれませんね。', en: "This trial may change society.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02582',
    'Hiroshi-boss and Yuki discuss a company lawsuit.',
    'WIDENED SCENARIO: corporate legal; lawsuit vocabulary (訴訟/弁護士/措置/裁判) in natural home.',
    'office_quiet_low',
    ['訴訟', '弁護士', '措置', '裁判', '犯罪'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '取引先から、訴訟を起こされました。', en: "A client has filed a lawsuit against us.", style: 'serious office woman voice, soft warm concerned clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '弁護士に、すぐ相談しよう。', en: "Let's consult the lawyer right away.", style: 'decisive boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '弁護士は、和解を勧めています。', en: "The lawyer recommends a settlement.", style: 'measured office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '裁判になれば、時間がかかるな。', en: "If it goes to trial, it'll take time.", style: 'thoughtful boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '早めの措置が、必要だと思います。', en: "I think early measures are needed.", style: 'earnest office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '我が社は、犯罪に関わっていない。', en: "Our company isn't involved in any crime.", style: 'firm boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '弁護士と、措置をまとめます。', en: "I'll work out the measures with the lawyer.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '裁判は、できれば避けたいな。', en: "I'd like to avoid a trial if possible.", style: 'measured boss voice, soft warm composed closing clarity throughout' },
    ]),

  C('conv_02583',
    'Asuka lectures on the justice system.',
    'WIDENED SCENARIO: law lecture; legal vocabulary (裁判/弁護士/犯罪/訴訟/措置) in natural home.',
    'lecture_hall_quiet',
    ['裁判', '弁護士', '犯罪', '訴訟', '措置'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '今日は、裁判の仕組みを学びます。', en: "Today we study how trials work.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '弁護士は、どんな役割ですか?', en: "What role does a lawyer play?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '弁護士は、被告の権利を守ります。', en: "The lawyer protects the defendant's rights.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '犯罪の裁判は、特に厳しいんですか?', en: "Are criminal trials especially strict?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '犯罪を裁くには、慎重な手続きが要ります。', en: "Judging crime requires careful procedure.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '訴訟は、誰でも起こせるんですか?', en: "Can anyone file a lawsuit?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、訴訟は権利を守る措置の一つです。', en: "Yes, a lawsuit is one measure to protect rights.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '裁判が、公平さを支えるんですね。', en: "So trials uphold fairness.", style: 'understanding adult student voice, soft warm realization throughout' },
    ]),

  C('conv_02584',
    'Documentary discussion: Asuka and Ren on a historic trial.',
    'WIDENED SCENARIO: documentary discussion; legal vocabulary (裁判/訴訟/犯罪/弁護士/措置) in natural home.',
    'living_room_quiet',
    ['裁判', '訴訟', '犯罪', '弁護士', '措置'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この裁判は、歴史に残ったんですね。', en: "This trial went down in history.", style: 'thoughtful young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、長い訴訟の末の判決でした。', en: "Yes, a ruling after a long lawsuit.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '弁護士は、どう闘ったんですか?', en: "How did the lawyer fight it?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '弁護士は、証拠を一つずつ示しました。', en: "The lawyer presented evidence one by one.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '犯罪の証明は、難しかったんでしょうね。', en: "Proving the crime must have been hard.", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'その後、再発防止の措置が取られました。', en: "Afterward, preventive measures were taken.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'この訴訟が、法律を変えたんですね。', en: "So this lawsuit changed the law.", style: 'understanding young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: '一つの裁判が、社会を動かしたんですよ。', en: "A single trial moved society.", style: 'warm teacher voice, soft warm measured clarity closing throughout' },
    ]),

  C('conv_02585',
    'Crime news: Sakura and Ren on a prevention plan.',
    'WIDENED SCENARIO: crime news; safety vocabulary (犯罪/措置/弁護士/裁判/訴訟) in natural home.',
    'studio_room_tone',
    ['犯罪', '措置', '弁護士', '裁判', '訴訟'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '市は、犯罪を減らす計画を発表しました。', en: "The city announced a plan to reduce crime.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'どんな措置が、取られるんですか?', en: "What measures will be taken?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '見回りを増やす措置が、中心です。', en: "Increased patrols are the central measure.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '弁護士は、この計画をどう見ますか?', en: "How do lawyers view this plan?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ある弁護士は、権利への配慮を求めました。', en: "One lawyer called for regard for rights.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '行き過ぎると、訴訟も起きかねませんね。', en: "If it goes too far, lawsuits could arise.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '裁判で争われた例も、過去にあります。', en: "There are past cases contested in court.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '犯罪の防止と権利、両立が大切ですね。', en: "Balancing crime prevention and rights matters.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  // THEME B — Corporate (株式会社 法人 会長 職員 事務所 + 理事 株式)
  C('conv_02586',
    'Hiroshi-boss introduces the company to a new hire.',
    'WIDENED SCENARIO: company orientation; corporate vocabulary (株式会社/会長/職員/法人/事務所) in natural home.',
    'office_quiet_low',
    ['株式会社', '会長', '職員', '法人', '事務所'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: 'ようこそ、我が株式会社へ。', en: "Welcome to our company.", style: 'warm boss voice, soft warm composed welcoming clarity throughout' },
      { speaker: 'ren_uni', jp: '株式会社の歴史は、長いんですか?', en: "Does the company have a long history?", style: 'curious young hire voice, soft warm earnest engaged throughout' },
      { speaker: 'hiroshi_boss', jp: '会長が、五十年前に立ち上げたんだ。', en: "The chairman founded it fifty years ago.", style: 'measured boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '職員は、何名いるんですか?', en: "How many staff are there?", style: 'attentive young hire voice, soft warm engaged throughout' },
      { speaker: 'hiroshi_boss', jp: '今、職員は二百名ほどだ。', en: "Now there are about two hundred staff.", style: 'clear boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '法人としての強みは、何ですか?', en: "What's the strength as a corporation?", style: 'thoughtful young hire voice, soft warm curious throughout' },
      { speaker: 'hiroshi_boss', jp: '法人としての信用が、我々の財産だ。', en: "Our credibility as a corporation is our asset.", style: 'firm boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: 'この事務所で、頑張ります!', en: "I'll do my best at this office!", style: 'eager young hire voice, soft warm determined closing throughout' },
    ]),

  C('conv_02587',
    'Business news: Sakura and Ren on a corporate merger.',
    'WIDENED SCENARIO: business news; corporate vocabulary (株式会社/法人/株式/会長) in natural home.',
    'studio_room_tone',
    ['株式会社', '法人', '株式', '会長', '職員'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '二つの株式会社が、合併しました。', en: "Two companies merged.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '株式の扱いは、どうなりますか?', en: "What happens to the shares?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '株式は、新会社にまとめられます。', en: "The shares will be consolidated into the new firm.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '新しい会長は、決まりましたか?', en: "Has the new chairman been decided?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '元の会長が、引き続き務めます。', en: "The former chairman will continue.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '法人としての規模は、大きくなりますね。', en: "The corporation's scale will grow.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '職員の雇用は、守られるそうです。', en: "Staff employment will reportedly be protected.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '株式会社の今後に、注目ですね。', en: "We watch the company's future.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02588',
    'Hiroshi-boss and Yuki prepare a board meeting.',
    'WIDENED SCENARIO: corporate governance; org vocabulary (会長/理事/職員/事務所/法人) in natural home.',
    'office_quiet_low',
    ['会長', '理事', '職員', '事務所', '法人'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '来週、理事会を開くことになった。', en: "We'll hold a board meeting next week.", style: 'composed boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '会長も、出席されますか?', en: "Will the chairman attend too?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'ああ、会長と理事が全員集まる。', en: "Yes, the chairman and all directors gather.", style: 'measured boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '会場は、本部の事務所でしょうか?', en: "Is the venue the head office?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'うむ、事務所の大会議室で行う。', en: "Yes, we'll hold it in the office's large room.", style: 'clear boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '職員の出席は、必要ですか?', en: "Is staff attendance required?", style: 'curious office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '担当の職員だけ、同席してもらう。', en: "Only the responsible staff will sit in.", style: 'measured boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '法人としての方針も、決まりますね。', en: "The corporation's policy will be decided too.", style: 'understanding office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02589',
    'Ren and Yuki review a corporation\'s share structure.',
    'WIDENED SCENARIO: finance discussion; corporate vocabulary (株式/法人/株式会社/理事) in natural home.',
    'office_quiet_low',
    ['株式', '法人', '株式会社', '理事', '会長'],
    ['ren_uni', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この株式会社の株式、誰が持っていますか?', en: "Who holds this company's shares?", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '多くは、会長と理事が持っています。', en: "Most are held by the chairman and directors.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '法人も、株式を持てるんですか?', en: "Can a corporation hold shares too?", style: 'curious young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: 'ええ、他の法人も保有しています。', en: "Yes, other corporations hold some too.", style: 'measured office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '理事会が、株式を動かすんですか?', en: "Does the board move the shares?", style: 'engaged young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '会長と理事が、慎重に判断します。', en: "The chairman and directors judge carefully.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '株式会社の構造、よく分かりました。', en: "I understand the company's structure well.", style: 'satisfied young analyst voice, soft warm appreciative throughout' },
      { speaker: 'yuki_office', jp: '法人の仕組みは、奥が深いですね。', en: "The corporate structure is deep.", style: 'warm office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02590',
    'Yuki and Kenji set up a new branch office.',
    'WIDENED SCENARIO: office logistics; corporate vocabulary (事務所/職員/法人/株式会社) in natural home.',
    'office_quiet_low',
    ['事務所', '職員', '法人', '株式会社', '会長'],
    ['yuki_office', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '新しい事務所の準備、進んでいますか?', en: "Are preparations for the new office progressing?", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'ええ、職員の机を運び入れました。', en: "Yes, we moved in the staff desks.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '何名の職員が、移るんですか?', en: "How many staff are moving?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '十名の職員が、この事務所に移ります。', en: "Ten staff will move to this office.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '法人の登録も、済ませましたか?', en: "Did you finish the corporate registration?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'はい、株式会社として登録済みです。', en: "Yes, it's registered as a company.", style: 'reliable office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '会長の視察も、近いそうですね。', en: "The chairman's visit is reportedly near.", style: 'engaged office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '事務所を、きれいに整えておきましょう。', en: "Let's get the office in good shape.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // THEME C — Tech/digital (ネットワーク デジタル ソフト コンピュータ チェック)
  C('conv_02591',
    'Kenji helps Yuki connect to the office network.',
    'WIDENED SCENARIO: IT help; tech vocabulary (ネットワーク/デジタル/ソフト/コンピュータ/チェック) in natural home.',
    'office_quiet_low',
    ['ネットワーク', 'デジタル', 'ソフト', 'コンピュータ', 'チェック'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'コンピュータが、ネットワークに繋がらないの。', en: "My computer won't connect to the network.", style: 'puzzled office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: 'まず、ネットワークの設定をチェックしましょう。', en: "First, let's check the network settings.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'チェックしたら、繋がりました!', en: "After checking, it connected!", style: 'relieved office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'このソフトも、入れておきましょう。', en: "Let's install this software too.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'デジタルの書類は、ここに保存?', en: "Do I save digital documents here?", style: 'attentive office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'ええ、デジタルで保存すれば安心です。', en: "Yes, saving digitally is safe.", style: 'reassuring office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'ソフトの使い方も、覚えなきゃ。', en: "I have to learn how to use the software.", style: 'earnest office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'コンピュータは、慣れれば簡単ですよ。', en: "Computers are easy once you get used to them.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02592',
    'Tech news: Sakura and Ren on a digital service.',
    'WIDENED SCENARIO: tech news; tech vocabulary (デジタル/ネットワーク/ソフト/コンピュータ) in natural home.',
    'studio_room_tone',
    ['デジタル', 'ネットワーク', 'ソフト', 'コンピュータ', 'チェック'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '新しいデジタルサービスが、始まりました。', en: "A new digital service has launched.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'ネットワークの負担は、大丈夫ですか?', en: "Is the network load okay?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '強いネットワークで、支えています。', en: "It's supported by a strong network.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '専用のソフトが、必要なんですか?', en: "Is dedicated software needed?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'いいえ、ソフトなしでも使えます。', en: "No, you can use it without software.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'コンピュータが古くても、動きますか?', en: "Does it work on older computers?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '事前のチェックを、勧めています。', en: "They recommend a prior check.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'デジタル化が、どんどん進みますね。', en: "Digitization keeps advancing.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02593',
    'Ren interviews Kenji about a software project.',
    'WIDENED SCENARIO: tech interview; tech vocabulary (コンピュータ/ソフト/チェック/ネットワーク) in natural home.',
    'office_quiet_low',
    ['コンピュータ', 'ソフト', 'チェック', 'ネットワーク', 'デジタル'],
    ['ren_uni', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'このソフトは、何ができるんですか?', en: "What can this software do?", style: 'engaged young interviewer voice, soft warm curious throughout' },
      { speaker: 'kenji_office', jp: 'コンピュータの作業を、自動化します。', en: "It automates computer tasks.", style: 'clear office man voice, soft warm informative throughout' },
      { speaker: 'ren_uni', jp: 'ネットワーク越しにも、使えますか?', en: "Can it be used over the network?", style: 'curious young interviewer voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、ネットワーク経由で動きます。', en: "Yes, it runs over the network.", style: 'measured office man voice, soft warm informative throughout' },
      { speaker: 'ren_uni', jp: '間違いは、どうチェックするんですか?', en: "How do you check for errors?", style: 'engaged young interviewer voice, soft warm curious throughout' },
      { speaker: 'kenji_office', jp: 'ソフトが、自動でチェックします。', en: "The software checks automatically.", style: 'clear office man voice, soft warm informative throughout' },
      { speaker: 'ren_uni', jp: 'デジタルの力は、すごいですね。', en: "The power of digital is amazing.", style: 'impressed young interviewer voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'コンピュータが、仕事を変えていきますよ。', en: "Computers keep changing work.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02594',
    'Kenji and Yuki run a system check before launch.',
    'WIDENED SCENARIO: IT operations; tech vocabulary (チェック/ネットワーク/デジタル/コンピュータ) in natural home.',
    'office_quiet_low',
    ['チェック', 'ネットワーク', 'デジタル', 'コンピュータ', 'ソフト'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '公開前に、全部チェックしましょう。', en: "Let's check everything before going live.", style: 'focused office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'ネットワークは、安定していますか?', en: "Is the network stable?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'ネットワークは、問題なしです。', en: "The network has no issues.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'デジタルの記録も、残りますか?', en: "Will digital records be kept too?", style: 'curious office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'ええ、デジタルで全部チェックできます。', en: "Yes, you can check everything digitally.", style: 'reassuring office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'コンピュータの動きは、軽いですか?', en: "Is the computer running light?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'ソフトを整理して、軽くしました。', en: "I tidied the software to make it light.", style: 'satisfied office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'チェックが済めば、安心ですね。', en: "Once the check's done, it's reassuring.", style: 'relieved office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02595',
    'Asuka introduces computing to a student.',
    'WIDENED SCENARIO: computing lecture; tech vocabulary (コンピュータ/デジタル/ネットワーク/ソフト) in natural home.',
    'lecture_hall_quiet',
    ['コンピュータ', 'デジタル', 'ネットワーク', 'ソフト', 'チェック'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'コンピュータは、計算の道具から始まりました。', en: "Computers began as calculating tools.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'デジタルって、どういう意味ですか?', en: "What does 'digital' mean?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'デジタルは、数で表す仕組みです。', en: "Digital is a system that represents things in numbers.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'ネットワークは、何をつなぐんですか?', en: "What does a network connect?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ネットワークは、コンピュータ同士をつなぎます。', en: "A network connects computers to each other.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'ソフトは、誰が作るんですか?', en: "Who makes software?", style: 'thoughtful teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '人が書き、間違いをチェックして作ります。', en: "People write it and check for errors.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'デジタルの世界、面白いですね!', en: "The digital world is fascinating!", style: 'delighted teen boy voice, soft warm bright engaged throughout' },
    ]),

  // THEME D — Lecture connectives (たとえば それら 本来 もっとも そもそも)
  C('conv_02596',
    'Asuka lectures on examples in argument.',
    'WIDENED SCENARIO: lecture; connectives (たとえば/それら/本来/もっとも/そもそも) in natural home.',
    'lecture_hall_quiet',
    ['たとえば', 'それら', '本来', 'もっとも', 'そもそも'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '主張には、たとえばの例が役立ちます。', en: "For a claim, 'for example' helps.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'それらの例は、どう選ぶんですか?', en: "How do we choose those examples?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'それらは、本来の主張に沿って選びます。', en: "We choose those in line with the original claim.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'そもそも、例はいくつ要りますか?', en: "To begin with, how many examples are needed?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'もっとも、多すぎても伝わりません。', en: "That said, too many won't get through.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'たとえば、二つか三つでしょうか?', en: "For example, two or three?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'そもそも、質が本来は大切なんです。', en: "Fundamentally, quality is what truly matters.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'それらを、丁寧に選びます。', en: "I'll choose those carefully.", style: 'satisfied adult student voice, soft warm appreciative throughout' },
    ]),

  C('conv_02597',
    'Asuka lectures on the purpose of education.',
    'WIDENED SCENARIO: education lecture; connectives (本来/そもそも/たとえば/もっとも/それら) in natural home.',
    'lecture_hall_quiet',
    ['本来', 'そもそも', 'たとえば', 'もっとも', 'それら'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'そもそも、学びとは何でしょうか。', en: "To begin with, what is learning?", style: 'contemplative teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: '本来は、知識を得ることですか?', en: "Is it fundamentally gaining knowledge?", style: 'thoughtful young student voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: '本来は、考える力を育てることです。', en: "Fundamentally, it's nurturing the power to think.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: 'たとえば、どんな力ですか?', en: "For example, what power?", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'たとえば、疑問を持つ力です。', en: "For example, the power to question.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: 'それらは、教えられるものですか?', en: "Can those be taught?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'もっとも、自ら気づくのが一番です。', en: "That said, realizing it yourself is best.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: 'それらを、大切にしたいと思います。', en: "I want to value those.", style: 'moved young student voice, soft warm realization throughout' },
    ]),

  C('conv_02598',
    'Asuka lectures on language and meaning.',
    'WIDENED SCENARIO: linguistics lecture; connectives (たとえば/もっとも/本来/それら/そもそも) in natural home.',
    'lecture_hall_quiet',
    ['たとえば', 'もっとも', '本来', 'それら', 'そもそも'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '言葉は、たとえば時代で意味が変わります。', en: "Words change meaning with the era, for example.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'mei_romantic', jp: 'それらの変化は、自然なんですか?', en: "Are those changes natural?", style: 'soft thoughtful woman voice, gentle warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、それらは自然に起こります。', en: "Yes, those happen naturally.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'mei_romantic', jp: 'そもそも、意味はどこから来るんですか?', en: "To begin with, where does meaning come from?", style: 'gentle woman voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'そもそも、人の使い方が意味を作ります。', en: "Fundamentally, how people use words makes meaning.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'mei_romantic', jp: '本来の意味は、消えてしまうんですか?', en: "Does the original meaning disappear?", style: 'soft woman voice, gentle warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'もっとも、本来の意味も残ることがあります。', en: "That said, the original meaning can remain too.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'mei_romantic', jp: 'それらを知ると、言葉が愛しいですね。', en: "Knowing those, words feel dear.", style: 'moved woman voice, soft warm tender realization throughout' },
    ]),

  C('conv_02599',
    'Asuka lectures on history and cause.',
    'WIDENED SCENARIO: history lecture; connectives (そもそも/たとえば/それら/本来/もっとも) in natural home.',
    'lecture_hall_quiet',
    ['そもそも', 'たとえば', 'それら', '本来', 'もっとも'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'そもそも、歴史はなぜ動くのでしょう。', en: "To begin with, why does history move?", style: 'contemplative teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'riku_teen', jp: 'たとえば、戦争が原因ですか?', en: "For example, is war a cause?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'たとえば戦争も、それらの一つです。', en: "War, for example, is one of those.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'riku_teen', jp: 'それらは、つながっているんですか?', en: "Are those connected?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、本来、原因は絡み合っています。', en: "Yes, fundamentally, causes intertwine.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'riku_teen', jp: 'もっとも、偶然もあるんですよね?', en: "That said, there's chance too, right?", style: 'thoughtful teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'もっとも、偶然も歴史を動かします。', en: "Indeed, chance moves history too.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'riku_teen', jp: 'それらを学ぶと、面白いですね。', en: "Learning those is fascinating.", style: 'delighted teen boy voice, soft warm bright engaged throughout' },
    ]),

  C('conv_02600',
    'Asuka lectures on art and originality.',
    'WIDENED SCENARIO: art lecture; connectives (本来/たとえば/もっとも/そもそも/それら) in natural home.',
    'lecture_hall_quiet',
    ['本来', 'たとえば', 'もっとも', 'そもそも', 'それら'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'そもそも、芸術とは何でしょうか。', en: "To begin with, what is art?", style: 'contemplative teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '本来は、美を表すものですか?', en: "Is it fundamentally an expression of beauty?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '本来は、心を表すものだと思います。', en: "Fundamentally, I think it expresses the heart.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: 'たとえば、どんな作品がそうですか?', en: "For example, which works are like that?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'たとえば、古い絵にも、その心が宿ります。', en: "For example, even old paintings hold that heart.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: 'それらは、今も人を動かしますね。', en: "Those still move people today.", style: 'thoughtful adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'もっとも、感じ方は人それぞれです。', en: "That said, how one feels differs by person.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: 'それらを、自分の目で見たいです。', en: "I want to see those with my own eyes.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_130 wrote', CONVERSATIONS.length, 'files');
