import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_149)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // count-2 business-meeting cluster (合意 勢い 冒頭 おっしゃる かける) ×3 + 目指す
  C('conv_02961',
    'Hiroshi-boss opens a negotiation meeting with Yuki.',
    'WIDENED SCENARIO: business meeting; vocabulary (合意/勢い/冒頭/おっしゃる/かける) in natural home.',
    'office_quiet_low',
    ['合意', '勢い', '冒頭', 'おっしゃる', 'かける'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '会議の冒頭で、目標を共有しよう。', en: "Let's share the goal at the meeting's opening.", style: 'composed boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '冒頭の挨拶は、社長がなさいますか?', en: "Will you give the opening greeting?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'ああ、勢いをつけて始めたい。', en: "Yes, I want to start with momentum.", style: 'measured boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '先方は、合意に前向きとおっしゃってます。', en: "The other side says they're open to agreement.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '合意に向けて、全力をかけよう。', en: "Let's put our all into reaching agreement.", style: 'firm boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '時間を、たっぷりかけて話しますか?', en: "Shall we spend plenty of time discussing?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '勢いを大事に、目指す合意を取ろう。', en: "Valuing momentum, let's reach the agreement we aim for.", style: 'composed boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '冒頭から、丁寧に進めますね。', en: "I'll proceed carefully from the opening.", style: 'resolved office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02962',
    'Ren reports a negotiation outcome to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (合意/勢い/冒頭/おっしゃる/かける) in natural home.',
    'office_quiet_low',
    ['合意', '勢い', '冒頭', 'おっしゃる', 'かける'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '交渉で、合意に達しました。', en: "We reached an agreement in the negotiation.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '先方は、冒頭から前向きだったかね?', en: "Was the other side positive from the opening?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '冒頭から、勢いがありました。', en: "There was momentum from the opening.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '担当者は、何とおっしゃっていたかね?', en: "What did the person in charge say?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '長く付き合いたいと、おっしゃっていました。', en: "They said they want a long relationship.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '時間をかけた甲斐が、あったな。', en: "The time we spent paid off.", style: 'satisfied boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'この勢いで、合意を広げたいです。', en: "With this momentum, I want to widen the agreement.", style: 'resolved young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '次も、力をかけて取り組もう。', en: "Let's put effort into the next one too.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02963',
    'Sakura interviews a mediator about reaching consensus.',
    'WIDENED SCENARIO: expert interview; vocabulary (合意/勢い/冒頭/おっしゃる/かける) in natural home.',
    'office_quiet_low',
    ['合意', '勢い', '冒頭', 'おっしゃる', 'かける'],
    ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '合意を得るコツは、何ですか?', en: "What's the knack for reaching agreement?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'asuka_teacher', jp: '冒頭で、信頼を築くことです。', en: "It's building trust at the opening.", style: 'composed mediator voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '勢いに任せても、いいんですか?', en: "Is it okay to rely on momentum?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '勢いより、丁寧に時間をかけます。', en: "More than momentum, I carefully spend time.", style: 'patient mediator voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '皆さん、何とおっしゃいますか?', en: "What do people say?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '安心したと、おっしゃる方が多いです。', en: "Many say they feel reassured.", style: 'composed mediator voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '冒頭の印象が、大事なんですね。', en: "The opening impression matters.", style: 'thoughtful adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '心をかけて聞けば、合意は近づきます。', en: "If you listen with heart, agreement comes closer.", style: 'warm mediator voice, soft warm measured closing clarity throughout' },
    ]),

  // count-4/3 cleanup (群 乗る 気に入っ 恋 肌 + 目指す 層 無く ティー)
  C('conv_02964',
    'Mei and Aoi chat about a romantic film.',
    'Casual register; vocabulary (群/乗る/気に入っ/恋/肌) in natural home.',
    'cafe_quiet_chatter',
    ['群', '乗る', '気に入っ', '恋', '肌'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの恋の映画、すごく気に入ったの。', en: "I really liked that romance film.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'aoi_barista', jp: '主役の女優、人気だよね。', en: "The lead actress is popular, right.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '肌がきれいで、見とれちゃった。', en: "Her skin was beautiful; I was captivated.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ファンの群が、劇場に並んでたよ。', en: "Crowds of fans lined up at the theater.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '人気に乗って、続編も出るみたい。', en: "Riding the popularity, a sequel's coming too.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '私も、あの恋の物語、気に入ったよ。', en: "I liked that love story too.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '波に乗って、ヒットしそうだね。', en: "Riding the wave, it looks set to be a hit.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '次は、人の群を避けて見たいなー。', en: "Next time I want to watch avoiding the crowds.", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  // count-1 cluster A — childhood/media (小学校 出演 アニメ バカ 嫌い)
  C('conv_02965',
    'Riku and Aoi reminisce about childhood anime.',
    'Casual register; vocabulary (小学校/出演/アニメ/バカ/嫌い) in natural home.',
    'cafe_quiet_chatter',
    ['小学校', '出演', 'アニメ', 'バカ', '嫌い'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '小学校の頃、アニメが大好きだったよ。', en: "In elementary school, I loved anime.", style: 'cheerful teen boy voice, bright warm nostalgic delivery throughout' },
      { speaker: 'aoi_barista', jp: '私も!好きな声優、出演してた?', en: "Me too! Did your favorite voice actor appear?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、今も色々なアニメに出演してるよ。', en: "Yeah, they still appear in lots of anime.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '小学校で、よく真似したなー。', en: "I used to imitate it in elementary school.", style: 'giggly barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'バカみたいに、何度も見たんだ。', en: "I watched it over and over like a fool.", style: 'playful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '私は、怖いシーンが嫌いだったよ。', en: "I disliked the scary scenes.", style: 'sheepish barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'バカにしないでよ、僕も怖かったし。', en: "Don't tease me, I was scared too.", style: 'laughing teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '小学校の思い出、最高だね!', en: "Elementary-school memories are the best!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02966',
    'Sho tells Yumiko about a school anime club.',
    'Casual home register; vocabulary (小学校/出演/アニメ/バカ/嫌い) in natural home.',
    'kitchen_evening_quiet',
    ['小学校', '出演', 'アニメ', 'バカ', '嫌い'],
    ['sho_child', 'yumiko_mom'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'ママ、小学校で劇に出演するんだ!', en: "Mom, I'm performing in a play at school!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'まあ、すごいわね。どんな役なの?', en: "Oh, wonderful. What role?", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: '好きなアニメの、主役なんだ!', en: "The lead of my favorite anime!", style: 'thrilled small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'セリフを、忘れないでね。', en: "Don't forget your lines.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '忘れたら、バカみたいだもん。', en: "If I forget, I'd look silly.", style: 'worried small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '練習が嫌いにならないようにね。', en: "Try not to come to dislike practice.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'アニメの役だから、嫌いじゃないよ!', en: "It's an anime role, so I don't dislike it!", style: 'cheerful small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '小学校の劇、見に行くわね。', en: "I'll come watch the school play.", style: 'tender mother voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02967',
    'Sakura interviews a voice actor.',
    'WIDENED SCENARIO: media interview; vocabulary (小学校/出演/アニメ/バカ/嫌い) in natural home.',
    'office_quiet_low',
    ['小学校', '出演', 'アニメ', 'バカ', '嫌い'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '声優を、目指したのはいつからですか?', en: "When did you aim to be a voice actor?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: '小学校の頃、アニメに憧れました。', en: "In elementary school, I admired anime.", style: 'warm young actor voice, soft warm sincere delivery throughout' },
      { speaker: 'sakura_teen', jp: '初めての出演は、緊張しましたか?', en: "Were you nervous at your first appearance?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '出演前は、バカみたいに練習しました。', en: "Before performing, I practiced like crazy.", style: 'gentle young actor voice, soft warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '苦手な、嫌いな役もありますか?', en: "Are there roles you dislike?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '嫌いな役こそ、学びが多いんです。', en: "Roles I dislike teach me the most.", style: 'reflective young actor voice, soft warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '今も、アニメに出演されていますね。', en: "You still appear in anime.", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '小学校の夢を、今も続けています。', en: "I'm still living my elementary-school dream.", style: 'warm young actor voice, soft warm sincere closing delivery throughout' },
    ]),

  C('conv_02968',
    'Mei and Riku debate a popular anime.',
    'Casual register; vocabulary (小学校/出演/アニメ/バカ/嫌い) in natural home.',
    'cafe_quiet_chatter',
    ['小学校', '出演', 'アニメ', 'バカ', '嫌い'],
    ['mei_romantic', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'この新しいアニメ、見た?', en: "Did you watch this new anime?", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、好きな俳優が出演してるのよね。', en: "Yeah, a favorite actor appears in it.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'riku_teen', jp: '小学校の友達も、ハマってるよ。', en: "My elementary-school friends are hooked too.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '私、最初は嫌いだったの。', en: "I disliked it at first.", style: 'honest woman voice, gentle warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'えー、もったいない!バカにできないよ。', en: "What, what a waste! You can't dismiss it.", style: 'playful teen boy voice, bright warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '見たら、すっかり気に入っちゃった。', en: "Once I watched it, I completely loved it.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: '出演者の声、最高だよね!', en: "The cast's voices are the best!", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '嫌いから好きに、変わるものね。', en: "Dislike can turn into love, huh.", style: 'warm woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-1 cluster B — society/news (革命 危機 違反 被告 外交)
  C('conv_02969',
    'News: Sakura and Ren on a diplomatic crisis.',
    'WIDENED SCENARIO: world-news analysis; vocabulary (革命/危機/違反/被告/外交) in natural home.',
    'studio_room_tone',
    ['革命', '危機', '違反', '被告', '外交'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '両国の外交が、危機を迎えています。', en: "Diplomacy between the two nations faces a crisis.", style: 'crisp adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '条約の違反が、原因なんですか?', en: "Is a treaty violation the cause?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、違反が、外交を悪化させました。', en: "Yes, the violation worsened diplomacy.", style: 'clear adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '過去には、革命も経験した国ですね。', en: "It's a country that experienced revolution in the past.", style: 'thoughtful young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '革命以来、緊張が続いています。', en: "Tension has continued since the revolution.", style: 'professional adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '裁判では、被告は何と?', en: "In court, what did the defendant say?", style: 'curious young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '被告は、違反を否定しています。', en: "The defendant denies the violation.", style: 'measured adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '外交の危機が、収まるといいですね。', en: "I hope the diplomatic crisis settles.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02970',
    'Asuka lectures on revolutions in history.',
    'WIDENED SCENARIO: history lecture; vocabulary (革命/危機/違反/被告/外交) in natural home.',
    'lecture_hall_quiet',
    ['革命', '危機', '違反', '被告', '外交'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '革命は、社会の危機から生まれます。', en: "Revolutions are born from social crises.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '危機は、どう始まるんですか?', en: "How does a crisis begin?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '権力の違反が、危機を招きます。', en: "Abuses of power invite crisis.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '革命の後、外交は変わりますか?', en: "Does diplomacy change after a revolution?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、革命後、外交が一新されます。', en: "Yes, after a revolution, diplomacy is renewed.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '指導者が、被告になることも?', en: "Do leaders sometimes become defendants?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '違反を問われ、被告になった例もあります。', en: "There are cases of leaders charged and becoming defendants.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '革命と外交、深く関わるんですね。', en: "Revolution and diplomacy are deeply linked.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_02971',
    'Ren interviews a historian on diplomacy.',
    'WIDENED SCENARIO: expert interview; vocabulary (革命/危機/違反/被告/外交) in natural home.',
    'office_quiet_low',
    ['革命', '危機', '違反', '被告', '外交'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '外交の歴史を、研究されていますね。', en: "You research the history of diplomacy.", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、危機の時代に注目しています。', en: "Yes, I focus on eras of crisis.", style: 'composed historian voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '革命は、外交をどう変えましたか?', en: "How did revolutions change diplomacy?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '革命が、新しい外交を生みました。', en: "Revolutions gave rise to new diplomacy.", style: 'patient historian voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '国際法の違反は、多かったですか?', en: "Were violations of international law common?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '違反を巡る危機が、何度もありました。', en: "Crises over violations occurred many times.", style: 'composed historian voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '責任者が、被告になった例も?', en: "Were there cases of officials becoming defendants?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '被告として、裁かれた例もあります。', en: "There are cases of being tried as defendants.", style: 'warm historian voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02972',
    'Sakura and Ren discuss a legal violation case.',
    'WIDENED SCENARIO: legal news; vocabulary (革命/危機/違反/被告/外交) in natural home.',
    'studio_room_tone',
    ['革命', '危機', '違反', '被告', '外交'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '今日、注目の裁判が開かれました。', en: "A closely watched trial opened today.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '被告は、何を問われていますか?', en: "What is the defendant charged with?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '規則の違反を、問われています。', en: "They're charged with violating the rules.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'この件は、外交にも影響しますか?', en: "Will this affect diplomacy too?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '外交の危機に、つながりかねません。', en: "It could lead to a diplomatic crisis.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '技術の革命が、背景にあるんですか?', en: "Is a technological revolution behind it?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、デジタル革命が関わっています。', en: "Yes, the digital revolution is involved.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '違反が繰り返されないと、いいですね。', en: "I hope the violation isn't repeated.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  // count-1 cluster C — work (勤務 バイト 出席 継続 文書)
  C('conv_02973',
    'Hiroshi-boss and Yuki review attendance and records.',
    'WIDENED SCENARIO: business HR; vocabulary (勤務/バイト/出席/継続/文書) in natural home.',
    'office_quiet_low',
    ['勤務', 'バイト', '出席', '継続', '文書'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '社員の勤務状況は、どうかね?', en: "How is the staff's attendance status?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '皆、真面目に勤務しています。', en: "Everyone works diligently.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'バイトの人も、出席は良いかね?', en: "Is the part-timers' attendance good too?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'バイトの出席も、安定しています。', en: "Part-timers' attendance is stable too.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '記録の文書は、残してあるかね?', en: "Are the record documents kept?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'はい、文書で継続的に残しています。', en: "Yes, I keep them continuously in documents.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '良い勤務を、継続してほしいな。', en: "I hope they continue working well.", style: 'warm boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '文書を整え、継続して管理します。', en: "I'll keep the documents in order and manage continuously.", style: 'resolved office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02974',
    'Riku asks Aoi about her part-time job.',
    'Casual register; vocabulary (勤務/バイト/出席/継続/文書) in natural home.',
    'cafe_quiet_chatter',
    ['勤務', 'バイト', '出席', '継続', '文書'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'アオイさん、バイト長いんだよね?', en: "Aoi, you've worked this part-time job a while, right?", style: 'curious teen boy voice, bright warm engaged delivery throughout' },
      { speaker: 'aoi_barista', jp: 'うん、三年も継続してるんだよ。', en: "Yeah, I've kept it up for three years.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '勤務は、週に何回?', en: "How many times a week do you work?", style: 'engaged teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '四日くらい、勤務してるよ。', en: "I work about four days.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: '学校の出席と、両立できてる?', en: "Can you balance it with school attendance?", style: 'curious teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '出席も、ちゃんとしてるよ。', en: "I keep up my attendance too.", style: 'proud barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'バイトの契約、文書であるの?', en: "Is the part-time contract in a document?", style: 'engaged teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'うん、文書をもらって、継続してるよ。', en: "Yeah, I got a document and keep going.", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02975',
    'Sakura interviews a manager about staffing.',
    'WIDENED SCENARIO: business interview; vocabulary (勤務/バイト/出席/継続/文書) in natural home.',
    'office_quiet_low',
    ['勤務', 'バイト', '出席', '継続', '文書'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '人手不足は、解決しましたか?', en: "Has the staff shortage been solved?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'バイトを増やして、勤務を回しています。', en: "We added part-timers to cover shifts.", style: 'measured manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '勤務の記録は、どう管理しますか?', en: "How do you manage work records?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '文書にして、継続的に残します。', en: "We put them in documents and keep them continuously.", style: 'professional manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '会議の出席率は、どうですか?', en: "How is meeting attendance?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '全員の出席を、目指しています。', en: "We aim for everyone's attendance.", style: 'measured manager voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '良い勤務環境を、継続するコツは?', en: "How do you keep a good work environment going?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '文書で、約束を継続することです。', en: "It's keeping promises continuously in writing.", style: 'warm manager voice, soft warm informative closing clarity throughout' },
    ]),

  C('conv_02976',
    'Kenji helps Ren digitize work documents.',
    'WIDENED SCENARIO: tech/office; vocabulary (勤務/バイト/出席/継続/文書) in natural home.',
    'office_quiet_low',
    ['勤務', 'バイト', '出席', '継続', '文書'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '勤務の文書を、電子化したいんです。', en: "I want to digitize the work documents.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '出席の記録も、含めますか?', en: "Do we include the attendance records too?", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'はい、出席も文書にまとめます。', en: "Yes, I'll compile attendance into documents too.", style: 'reliable young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'バイトの分も、継続して残しましょう。', en: "Let's keep the part-timers' records continuously too.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'バイトの勤務も、増えていますね。', en: "Part-timers' shifts are increasing.", style: 'measured young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '文書を継続管理すれば、楽になります。', en: "Continuously managing documents makes it easier.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '勤務の流れが、見やすくなりますね。', en: "The work flow becomes easier to see.", style: 'satisfied young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '出席も文書も、一つにまとめましょう。', en: "Let's unify attendance and documents.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // count-1 cluster D — housing/daily (マンション 自宅 風景 需要 個別)
  C('conv_02977',
    'Daichi and Mei discuss apartment hunting.',
    'WIDENED SCENARIO: housing chat; vocabulary (マンション/自宅/風景/需要/個別) in natural home.',
    'cafe_quiet_chatter',
    ['マンション', '自宅', '風景', '需要', '個別'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '新しいマンションを、探しているんです。', en: "I'm looking for a new apartment.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: '駅近のマンションは、人気やで。', en: "Apartments near the station are popular.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '窓からの風景が、いい所がいいな。', en: "I'd like a place with a good view from the window.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '高い階やと、風景が最高やで。', en: "On a high floor, the view's the best.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '駅近は、需要が高いんですよね。', en: "Near-station places are in high demand, right.", style: 'thoughtful woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '需要が高いと、早う決めなあかんで。', en: "High demand means you must decide fast.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '個別に、内見できますか?', en: "Can I view them individually?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '個別の内見、頼んだらええよ。自宅から近いとええな。', en: "Just ask for individual viewings. Close to your current home is nice.", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_02978',
    'Sakura interviews a real-estate agent.',
    'WIDENED SCENARIO: real-estate interview; vocabulary (マンション/自宅/風景/需要/個別) in natural home.',
    'office_quiet_low',
    ['マンション', '自宅', '風景', '需要', '個別'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'マンションの需要は、高いですか?', en: "Is demand for apartments high?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '都市部のマンションは、需要が高いです。', en: "Urban apartments are in high demand.", style: 'measured agent voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: 'お客様は、何を重視しますか?', en: "What do customers value?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '窓からの風景を、重視する方が多いです。', en: "Many value the view from the window.", style: 'professional agent voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '自宅選びは、難しいですか?', en: "Is choosing a home difficult?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '自宅は、個別の希望に合わせます。', en: "We match homes to individual wishes.", style: 'measured agent voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '個別の相談も、受けますか?', en: "Do you take individual consultations too?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'ええ、個別に丁寧に対応します。', en: "Yes, we respond carefully on an individual basis.", style: 'warm agent voice, soft warm informative closing clarity throughout' },
    ]),

  C('conv_02979',
    'Ren and Mei chat about moving into a new place.',
    'Casual register; vocabulary (マンション/自宅/風景/需要/個別) in natural home.',
    'cafe_quiet_chatter',
    ['マンション', '自宅', '風景', '需要', '個別'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '新しいマンション、決めたの!', en: "I decided on a new apartment!", style: 'soft warm woman voice, gentle excited delivery throughout' },
      { speaker: 'ren_uni', jp: 'おめでとう!風景はどんな感じ?', en: "Congrats! What's the view like?", style: 'warm young man voice, soft warm engaged delivery throughout' },
      { speaker: 'mei_romantic', jp: '窓から、山の風景が見えるの。', en: "From the window, you see mountain scenery.", style: 'gentle woman voice, soft warm delighted delivery throughout' },
      { speaker: 'ren_uni', jp: 'いいね、自宅で癒やされそうだね。', en: "Nice, you'll feel soothed at home.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '需要が高くて、すぐ埋まるところだったの。', en: "Demand was high; it almost filled up fast.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '個別に内見したの?', en: "Did you view it individually?", style: 'curious young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、個別に案内してもらったの。', en: "Yeah, they showed me around individually.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '新しい自宅、遊びに行くね!', en: "I'll come visit your new home!", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02980',
    'Asuka lectures on urban housing demand.',
    'WIDENED SCENARIO: urban-studies lecture; vocabulary (マンション/自宅/風景/需要/個別) in natural home.',
    'lecture_hall_quiet',
    ['マンション', '自宅', '風景', '需要', '個別'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '都市では、マンションの需要が高いです。', en: "In cities, demand for apartments is high.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '需要は、なぜ高いんですか?', en: "Why is demand high?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '自宅を、職場の近くに求めるからです。', en: "Because people seek homes near their workplaces.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '風景は、価格に関係しますか?', en: "Does the view relate to price?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '良い風景のマンションは、高くなります。', en: "Apartments with good views become expensive.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '人の希望は、個別に違いますよね。', en: "People's wishes differ individually, right.", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、個別の需要を理解することが大切です。', en: "Yes, understanding individual demand matters.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '自宅選びは、人生の選択ですね。', en: "Choosing a home is a life decision.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_149 wrote', CONVERSATIONS.length, 'files');
