import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_076)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01506',
    context: 'Hina oversleeps and rushes to school; Sho teases her in the genkan.',
    purpose: 'Sibling teasing morning chaos; light embarrassment.',
    ambient: 'genkan_morning_rush',
    sound_effects: [],
    target_vocab: ['寝坊', '遅刻', '急ぐ', '目覚まし'],
    cast: ['hina_child', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'やばい、寝坊した!', en: "Oh no — I overslept!", style: 'panicked teen girl voice, soft flustered honest warmth delivered carefully' },
      { speaker: 'sho_child', jp: '目覚まし、鳴ってたで。', en: "The alarm went off, you know.", style: 'teasing teen boy voice, soft warm mocking sibling delivery carefully' },
      { speaker: 'hina_child', jp: 'もう、遅刻しちゃう!', en: "Ugh — I'll be late!", style: 'frantic teen girl voice, soft warm honest exasperation delivered carefully' },
      { speaker: 'sho_child', jp: '急いだら、間に合うって。', en: "If you hurry, you'll make it.", style: 'casual teen boy voice, soft warm laidback support delivered carefully' },
      { speaker: 'hina_child', jp: 'ありがと、行ってくる!', en: "Thanks — heading out!", style: 'rushed teen girl voice, soft warm grateful breathless delivery carefully' },
    ],
  },
  {
    id: 'conv_01507',
    context: 'Mei and Yumiko fold laundry on the porch on a sunny afternoon.',
    purpose: 'Domestic quiet bonding through shared household work.',
    ambient: 'porch_breeze_birds',
    sound_effects: [],
    target_vocab: ['洗濯', '畳む', '布団', '太陽'],
    cast: ['mei_romantic', 'yumiko_mom'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '今日は洗濯日和ね。', en: "Today's perfect for laundry.", style: 'gentle older mother voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '太陽、気持ちいい。', en: "The sun feels nice.", style: 'soft young woman voice, warm peaceful sensory delivery carefully' },
      { speaker: 'yumiko_mom', jp: '布団も干したわよ、ほら。', en: "I aired the futon too — look.", style: 'cheerful older mother voice, soft warm satisfied pride delivered carefully' },
      { speaker: 'mei_romantic', jp: 'ふかふか、気持ちよさそう。', en: "Fluffy — looks comfy.", style: 'tender young woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'yumiko_mom', jp: '今夜、よく眠れそうね。', en: "We'll sleep well tonight.", style: 'warm older mother voice, soft fond peaceful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お母さん、いつもありがとう。', en: "Mom — thanks as always.", style: 'tender young woman voice, soft warm grateful sincerity delivered carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、当たり前のことよ。', en: "Heh — just natural.", style: 'soft older mother voice, warm humble loving delivery carefully' },
    ],
  },
  {
    id: 'conv_01508',
    context: 'Saito examines Hiroshi-elder for routine check-up; gentle medical exchange.',
    purpose: 'Doctor checking elderly patient with warmth and respect.',
    ambient: 'clinic_room_quiet',
    sound_effects: [],
    target_vocab: ['心臓', '血液', '検査', '結果'],
    cast: ['saito_doctor', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '心臓の音、安定してますよ。', en: "Your heart sounds steady.", style: 'measured doctor voice, soft warm professional reassurance delivered carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、よかったわ。', en: "Oh — that's good.", style: 'slow elder Kansai voice, warm relieved soft delivery carefully' },
      { speaker: 'saito_doctor', jp: '血液検査の結果、後でお伝えします。', en: "I'll share blood test results later.", style: 'professional doctor voice, soft clear careful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'よろしゅう頼むわ。', en: "Much obliged.", style: 'gentle elder Kansai voice, slow warm respectful delivery carefully' },
      { speaker: 'saito_doctor', jp: '食生活、続けてくださいね。', en: "Keep up the diet, please.", style: 'soft doctor voice, warm encouraging professional advice delivered carefully' },
      { speaker: 'hiroshi_elder', jp: 'はい、家内も気にしてくれて。', en: "Yes — the wife watches it too.", style: 'soft elder Kansai voice, warm fond grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'いい奥様ですね。', en: "What a fine wife.", style: 'warm doctor voice, soft genuine respectful appreciation delivered carefully' },
    ],
  },
  {
    id: 'conv_01509',
    context: 'Hina worries about a recurring bad dream; talks to Sakura about it.',
    purpose: 'Teen confiding emotional content; adult providing gentle perspective.',
    ambient: 'living_room_lamp_low',
    sound_effects: [],
    target_vocab: ['夢', '悪夢', '怖い', '記憶'],
    cast: ['hina_child', 'sakura_teen'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、悪夢、続いてる。', en: "Sakura — bad dreams keep coming.", style: 'soft worried teen girl voice, warm honest vulnerable delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どんな夢、見るの?', en: "What kind of dream?", style: 'gentle adult writer voice, soft warm caring inquiry delivered carefully' },
      { speaker: 'hina_child', jp: '怖い場所で、走ってる夢。', en: "Running in a scary place.", style: 'soft teen girl voice, warm hesitant honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '記憶が整理されてるのかもね。', en: "Maybe memory is sorting itself.", style: 'thoughtful adult writer voice, soft warm explanatory kindness delivered carefully' },
      { speaker: 'hina_child', jp: 'そうなの?ちょっと安心。', en: "Really? A bit of a relief.", style: 'soft teen girl voice, warm gently relieved delivery carefully' },
      { speaker: 'sakura_teen', jp: '寝る前に、温かい飲み物どう?', en: "Warm drink before bed?", style: 'tender adult writer voice, soft warm gentle suggestion delivered carefully' },
      { speaker: 'hina_child', jp: 'うん、やってみる。', en: "Yeah — I'll try.", style: 'soft teen girl voice, warm grateful agreement delivered carefully' },
    ],
  },
  {
    id: 'conv_01510',
    context: 'Daichi and Kenji wash and air futons together in the yard.',
    purpose: 'Two friends doing weekend chores; quiet companionship.',
    ambient: 'yard_breeze_low',
    sound_effects: [],
    target_vocab: ['布団', '畳', '干す', '日差し'],
    cast: ['daichi_kansai', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '今日の日差し、ええなぁ。', en: "Today's sunshine is lovely.", style: 'warm Kansai man voice, soft appreciative content delivery carefully' },
      { speaker: 'kenji_office', jp: '布団、ふっくらするやろな。', en: "Futons'll get fluffy.", style: 'soft Kansai artist voice, warm fond practical delivery carefully' },
      { speaker: 'daichi_kansai', jp: '畳も干したいな。', en: "Want to air the tatami too.", style: 'thoughtful Kansai man voice, soft warm domestic-pride delivery carefully' },
      { speaker: 'kenji_office', jp: '俺、運ぶの手伝うで。', en: "I'll help carry them.", style: 'warm Kansai artist voice, soft helpful brotherly delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おおきに、助かる。', en: "Thanks — that helps.", style: 'soft Kansai man voice, warm grateful brotherly delivery carefully' },
    ],
  },
  {
    id: 'conv_01511',
    context: 'Sho-young presents Naoko with a drawing of her ramen shop.',
    purpose: 'Child gift-giving to gruff aunt; warmth under the bluster.',
    ambient: 'ramen_shop_afternoon',
    sound_effects: [],
    target_vocab: ['絵', '描く', 'プレゼント', '嬉しい'],
    cast: ['sho_child', 'naoko_aunt'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'ナオコおばちゃん、絵描いた!', en: "Naoko-auntie — I drew a picture!", style: 'eager child boy voice, bright cheerful proud delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おっ、店の絵か?嬉しいやん!', en: "Oh — picture of the shop? Lovely!", style: 'animated Kansai aunt voice, bright loud delighted warmth delivered carefully' },
      { speaker: 'sho_child', jp: 'うん、上手?', en: "Yeah — is it good?", style: 'shy child boy voice, soft hopeful nervous warmth delivered carefully' },
      { speaker: 'naoko_aunt', jp: 'めっちゃ上手や、飾るで!', en: "Super good — I'll display it!", style: 'brassy Kansai aunt voice, bright loud affectionate delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、ありがとう!', en: "Yay — thanks!", style: 'thrilled child boy voice, bright cheerful warm delivery carefully' },
    ],
  },
  {
    id: 'conv_01512',
    context: 'Aoi and Ren talk about a recent author tour through small towns.',
    purpose: 'Two adults discussing travel impressions and books.',
    ambient: 'living_room_low_lamp',
    sound_effects: [],
    target_vocab: ['旅行', '本屋', '田舎', '雰囲気'],
    cast: ['aoi_barista', 'ren_uni'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '田舎の本屋、雰囲気いいって?', en: "Country bookstores have a good vibe?", style: 'curious adult woman voice, soft warm interested inquiry delivered carefully' },
      { speaker: 'ren_uni', jp: 'はい、お客さんとの距離が近い。', en: "Yes — closer to the readers.", style: 'soft young man voice, warm reflective fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '旅行、楽しかった?', en: "Was the trip fun?", style: 'gentle adult woman voice, soft warm caring inquiry delivered carefully' },
      { speaker: 'ren_uni', jp: 'うん、とても勉強になりました。', en: "Yes — very educational.", style: 'soft young man voice, warm sincere humble delivery carefully' },
      { speaker: 'aoi_barista', jp: '次は私も一緒に行こう。', en: "Next time I'll come too.", style: 'warm adult woman voice, soft fond friendly invitation delivered carefully' },
      { speaker: 'ren_uni', jp: '是非、楽しみです。', en: "By all means — looking forward.", style: 'soft young man voice, warm sincere eager delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、決めとこ。', en: "Yeah — let's plan it.", style: 'cheerful adult woman voice, soft warm decisive delivery carefully' },
    ],
  },
  {
    id: 'conv_01513',
    context: 'Hiroshi-boss and Sakura discuss a possible book promotion campaign.',
    purpose: 'Business meeting between boss and respected author.',
    ambient: 'office_meeting_quiet',
    sound_effects: [],
    target_vocab: ['宣伝', '計画', '予算', '販売'],
    cast: ['hiroshi_boss', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: 'さくら先生、宣伝の計画を。', en: "Sakura-sensei — the promotion plan.", style: 'authoritative boss voice, soft professional respectful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、予算はどれくらいですか?', en: "Yes — what's the budget?", style: 'professional adult writer voice, soft warm practical delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '今回は、少し多めに取れます。', en: "This time, we can spend a bit more.", style: 'measured boss voice, soft professional reassuring delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとうございます、頑張ります。', en: "Thank you — I'll work hard.", style: 'humble adult writer voice, soft warm respectful gratitude delivered carefully' },
      { speaker: 'hiroshi_boss', jp: '販売目標も、共有しましょう。', en: "Let's share sales targets too.", style: 'professional boss voice, soft collaborative measured delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、よろしくお願いします。', en: "Yes — thank you.", style: 'polite adult writer voice, soft formal sincere delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '良い本を、世に出しましょう。', en: "Let's bring a good book to the world.", style: 'warm boss voice, soft proud collaborative delivery carefully' },
    ],
  },
  {
    id: 'conv_01514',
    context: 'Mrs. Mori brings homemade pickles over to Yumiko\'s; they chat.',
    purpose: 'Neighborly food exchange; warm community tradition.',
    ambient: 'kitchen_afternoon_clock',
    sound_effects: [],
    target_vocab: ['漬物', '野菜', '近所', 'おすそ分け'],
    cast: ['mrs_mori_neighbor', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'これ、おすそ分け、漬物よ。', en: "Here — a share of pickles for you.", style: 'warm older neighbor voice, soft gracious gift delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、いつもありがとう。', en: "Oh — thank you, as always.", style: 'gentle older mother voice, soft warm grateful delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '野菜が余ったから、ね。', en: "Had extra vegetables, you know.", style: 'kindly older woman voice, soft warm modest delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'お夕飯にいただくわね。', en: "I'll have it at dinner.", style: 'warm older mother voice, soft cheerful appreciative delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふふ、また作るね。', en: "Heh — I'll make more.", style: 'soft older neighbor voice, warm friendly promise delivered carefully' },
    ],
  },
  {
    id: 'conv_01515',
    context: 'Asuka brings her class to a small museum; explaining quietly to a student.',
    purpose: 'Teacher patiently explaining cultural concept to curious student.',
    ambient: 'museum_quiet_floor',
    sound_effects: [],
    target_vocab: ['博物館', '歴史', '展示', '解説'],
    cast: ['asuka_teacher', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '先生、この展示、何ですか?', en: "Teacher — what's this exhibit?", style: 'curious teen girl voice, soft warm attentive inquiry delivered carefully' },
      { speaker: 'asuka_teacher', jp: '古い農具よ、明治時代のね。', en: "Old farm tools — from the Meiji era.", style: 'gentle teacher voice, soft warm informative delivery carefully' },
      { speaker: 'hina_child', jp: 'こんなで、農作業できたんですか?', en: "Could they farm with this?", style: 'amazed teen girl voice, soft warm honest awe delivered carefully' },
      { speaker: 'asuka_teacher', jp: 'ええ、解説の通り、工夫が見える。', en: "Yes — as the caption says, ingenuity shows.", style: 'patient teacher voice, soft warm explanatory delivery carefully' },
      { speaker: 'hina_child', jp: '昔の人、すごいですね。', en: "Old folks were amazing.", style: 'admiring teen girl voice, soft warm reverent delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'うん、歴史から学べる。', en: "Yes — we learn from history.", style: 'warm teacher voice, soft wise reflective delivery carefully' },
      { speaker: 'hina_child', jp: 'もっと見たいです!', en: "I want to see more!", style: 'bright teen girl voice, soft warm eager curiosity delivered carefully' },
    ],
  },
  {
    id: 'conv_01516',
    context: 'Goro-grandpa teaches Sho-child how to fish at the small river.',
    purpose: 'Grandfather figure teaching child outdoor skill patiently.',
    ambient: 'river_quiet_water',
    sound_effects: [],
    target_vocab: ['釣り', '魚', '川', '待つ'],
    cast: ['goro_grandpa', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'goro_grandpa', jp: '釣りはな、静かに待つんや。', en: "Fishing — you wait quietly.", style: 'gentle elder voice, soft warm patient teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、頑張る!', en: "Yeah — I'll try!", style: 'eager child boy voice, bright cheerful determined delivery carefully' },
      { speaker: 'goro_grandpa', jp: '魚が来るまで、川を見てな。', en: "Watch the river till one comes.", style: 'slow elder voice, soft warm patient instruction delivered carefully' },
      { speaker: 'sho_child', jp: '魚、来るかな?', en: "Will a fish come?", style: 'hopeful child boy voice, soft warm eager wait delivered carefully' },
      { speaker: 'goro_grandpa', jp: '焦らんでええ、ゆっくりや。', en: "No need to rush — take it slow.", style: 'warm elder voice, soft wise patient delivery carefully' },
      { speaker: 'sho_child', jp: 'おじいちゃん、優しいね。', en: "Grandpa — you're kind.", style: 'soft child boy voice, warm fond honest observation delivered carefully' },
      { speaker: 'goro_grandpa', jp: 'ふふ、おまえも優しなれ。', en: "Heh — you grow up kind too.", style: 'gentle elder voice, soft warm fatherly wisdom delivered carefully' },
    ],
  },
  {
    id: 'conv_01517',
    context: 'Sachiko-grandma teaches Hina-young how to make a paper crane.',
    purpose: 'Grandmother teaching child traditional craft; quiet attention.',
    ambient: 'tatami_room_quiet',
    sound_effects: [],
    target_vocab: ['折り紙', '形', '手', '伝統'],
    cast: ['sachiko_grandma', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'まず、半分に折ってね。', en: "First — fold in half.", style: 'gentle grandmother voice, soft warm careful instructional delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、こうですか?', en: "Yes — like this?", style: 'attentive teen girl voice, soft warm careful learning delivered carefully' },
      { speaker: 'sachiko_grandma', jp: 'うん、上手ね、ゆっくりで。', en: "Yes — well done, slowly.", style: 'warm grandmother voice, soft gentle praising delivery carefully' },
      { speaker: 'hina_child', jp: '形が見えてきた!', en: "The shape's coming through!", style: 'bright teen girl voice, soft warm proud delivery carefully' },
      { speaker: 'sachiko_grandma', jp: 'これが、伝統の鶴よ。', en: "This is the traditional crane.", style: 'soft grandmother voice, warm reverent cultural delivery carefully' },
    ],
  },
  {
    id: 'conv_01518',
    context: 'Riku and Sho hang out after school; teen friendship banter about a new game.',
    purpose: 'Teen-to-teen casual gaming chat with playful energy.',
    ambient: 'bedroom_evening_lamp',
    sound_effects: [],
    target_vocab: ['ゲーム', '面白い', '難しい', '勝つ'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'riku_teen', jp: 'このゲーム、めっちゃ難しい!', en: "This game's super hard!", style: 'animated teen boy voice, bright frustrated energetic delivery carefully' },
      { speaker: 'sho_child', jp: 'マジ?どこで詰まった?', en: "Really? Where'd you get stuck?", style: 'curious teen boy voice, soft warm engaged delivery carefully' },
      { speaker: 'riku_teen', jp: 'ボス戦、勝てないんよ。', en: "The boss fight — can't beat it.", style: 'frustrated teen boy voice, soft warm honest delivery carefully' },
      { speaker: 'sho_child', jp: '俺、コツ教えるわ。', en: "I'll teach you the trick.", style: 'helpful teen boy voice, soft warm proud friendly delivery carefully' },
      { speaker: 'riku_teen', jp: 'マジ?助かる!', en: "Really? Lifesaver!", style: 'thrilled teen boy voice, bright cheerful grateful delivery carefully' },
      { speaker: 'sho_child', jp: 'まあ、簡単やで。', en: "Eh — it's easy.", style: 'casual teen boy voice, soft warm offhand playful delivery carefully' },
      { speaker: 'riku_teen', jp: 'お前、頼りになるなぁ。', en: "You — you're reliable.", style: 'warm teen boy voice, soft fond friendly admiration delivered carefully' },
    ],
  },
  {
    id: 'conv_01519',
    context: 'Tatsuya-country writes a long letter to his daughter; he reads bits to his wife.',
    purpose: 'Long internal warmth; reading a letter aloud with reflection.',
    ambient: 'farmhouse_evening_quiet',
    sound_effects: [],
    target_vocab: ['手紙', '娘', '便り', '元気'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '娘に手紙、書いとってな。', en: "Writing a letter to my daughter.", style: 'slow Tohoku farmer voice, soft warm reflective fatherly delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'まあ、何て書いてるの?', en: "Oh — what are you writing?", style: 'warm teacher voice, soft curious gentle inquiry delivered carefully' },
      { speaker: 'tatsuya_country', jp: 'まずは、元気かどうか。', en: "First — asking how she is.", style: 'gentle Tohoku voice, soft warm fatherly caring delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'いつも気にかけてあげるのね。', en: "You always think of her.", style: 'tender teacher voice, soft warm fond observation delivered carefully' },
      { speaker: 'tatsuya_country', jp: 'うん、便りも欲しいし。', en: "Yeah — and I want word back.", style: 'soft Tohoku voice, warm honest paternal longing delivered carefully' },
      { speaker: 'asuka_teacher', jp: '次は何を書くの?', en: "What's next?", style: 'engaged teacher voice, soft warm curious delivery carefully' },
      { speaker: 'tatsuya_country', jp: '田んぼの様子、書きたい。', en: "Want to describe the paddies.", style: 'gentle Tohoku farmer voice, soft warm reflective delivery carefully' },
      { speaker: 'asuka_teacher', jp: '景色、伝わるといいわね。', en: "Hope the scenery reaches her.", style: 'warm teacher voice, soft tender hopeful delivery carefully' },
      { speaker: 'tatsuya_country', jp: '言葉、難しいわ、たまに。', en: "Words — hard sometimes.", style: 'soft Tohoku voice, warm honest humble delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ゆっくり、思ったまま書いて。', en: "Slowly — write as you feel.", style: 'gentle teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おおきに、お前のおかげや。', en: "Thanks — thanks to you.", style: 'soft Tohoku farmer voice, warm humble grateful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '夫婦やもの、当然よ。', en: "We're husband and wife — natural.", style: 'tender teacher voice, soft warm loving delivery carefully' },
      { speaker: 'tatsuya_country', jp: '今夜、ええ手紙、書けそうや。', en: "Tonight — I can write a good one.", style: 'gentle Tohoku voice, soft warm content peaceful delivery carefully' },
    ],
  },
  {
    id: 'conv_01520',
    context: 'Ryosuke-dad watches old home videos with Mei in the living room.',
    purpose: 'Father and grown daughter sharing nostalgia tenderly.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['映像', '思い出', '昔', '懐かしい'],
    cast: ['ryosuke_dad', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ryosuke_dad', jp: 'この映像、お前が三歳の時や。', en: "This video — you at three.", style: 'warm middle-aged father voice, soft fond nostalgic delivery carefully' },
      { speaker: 'mei_romantic', jp: 'えっ、こんなだったの?', en: "Wow — I was like this?", style: 'soft young woman voice, warm surprised tender delivery carefully' },
      { speaker: 'ryosuke_dad', jp: 'うん、本当に可愛かった。', en: "Yeah — really cute.", style: 'tender father voice, soft warm proud loving delivery carefully' },
      { speaker: 'mei_romantic', jp: '懐かしいなぁ、お父さん。', en: "Nostalgic — Dad.", style: 'soft young woman voice, warm tender wistful delivery carefully' },
      { speaker: 'ryosuke_dad', jp: '昔の思い出、たくさんあるな。', en: "Lots of old memories.", style: 'gentle father voice, soft warm reflective delivery carefully' },
      { speaker: 'mei_romantic', jp: 'もっと見たいな、一緒に。', en: "Want to watch more — together.", style: 'tender young woman voice, soft warm loving delivery carefully' },
      { speaker: 'ryosuke_dad', jp: 'ええよ、夜長いし。', en: "Sure — long night ahead.", style: 'warm father voice, soft fond unhurried delivery carefully' },
    ],
  },
  {
    id: 'conv_01521',
    context: 'Yuki-office and Kenji discuss a stressful project deadline at work.',
    purpose: 'Two coworkers commiserating about deadlines; gentle solidarity.',
    ambient: 'office_evening_keyboards',
    sound_effects: [],
    target_vocab: ['期限', '残業', '疲れる', '頑張る'],
    cast: ['yuki_office', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: '今夜も残業ですか?', en: "Overtime again tonight?", style: 'soft office woman voice, warm weary professional delivery carefully' },
      { speaker: 'kenji_office', jp: 'うん、期限がな、来週やし。', en: "Yeah — deadline's next week.", style: 'tired Kansai man voice, soft warm honest delivery carefully' },
      { speaker: 'yuki_office', jp: 'お疲れさまです、無理しないで。', en: "Take care — don't push too hard.", style: 'caring office woman voice, soft warm professional concern delivered carefully' },
      { speaker: 'kenji_office', jp: 'おおきに、お前も帰り。', en: "Thanks — you head home too.", style: 'soft Kansai man voice, warm caring brotherly delivery carefully' },
      { speaker: 'yuki_office', jp: 'はい、また明日。', en: "Yes — see you tomorrow.", style: 'gentle office woman voice, soft warm friendly farewell delivered carefully' },
    ],
  },
  {
    id: 'conv_01522',
    context: 'Mei finds Sakura with a sprained ankle; helps her with first aid.',
    purpose: 'Adult helping injured adult; tender care moment.',
    ambient: 'living_room_concerned',
    sound_effects: [],
    target_vocab: ['足首', '痛い', '冷やす', '休む'],
    cast: ['mei_romantic', 'sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '足首、ひねっちゃった。', en: "I twisted my ankle.", style: 'pained adult writer voice, soft warm honest weariness delivered carefully' },
      { speaker: 'mei_romantic', jp: 'えっ、痛い?冷やそう。', en: "Oh — does it hurt? Let's ice it.", style: 'worried young woman voice, soft warm caring action delivered carefully' },
      { speaker: 'sakura_teen', jp: 'うん、お願いね。', en: "Yeah — please.", style: 'soft adult writer voice, warm grateful tired delivery carefully' },
      { speaker: 'mei_romantic', jp: '少し休んでて、私やる。', en: "Rest a bit — I'll handle it.", style: 'gentle young woman voice, soft warm capable reassurance delivered carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとう、本当に。', en: "Thank you — truly.", style: 'tender adult writer voice, soft warm grateful sincerity delivered carefully' },
      { speaker: 'mei_romantic', jp: '無理しないで、大事にね。', en: "Don't push — take care.", style: 'soft young woman voice, warm caring gentle delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、明日は休む。', en: "Yeah — I'll rest tomorrow.", style: 'soft adult writer voice, warm resolved obedient delivery carefully' },
    ],
  },
  {
    id: 'conv_01523',
    context: 'Daichi and Hiroshi-elder share quiet sake on a winter evening.',
    purpose: 'Father and son-in-law bonding tenderly over drink and silence.',
    ambient: 'tatami_winter_quiet',
    sound_effects: [],
    target_vocab: ['酒', '冬', '温める', '味わう'],
    cast: ['daichi_kansai', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '冬の夜、温い酒がええな。', en: "Winter night — warm sake's good.", style: 'slow elder Kansai voice, warm weathered content delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ほんま、味わって飲もか。', en: "Truly — let's savor it.", style: 'soft Kansai husband voice, warm fond agreement delivered carefully' },
      { speaker: 'hiroshi_elder', jp: 'こうやって、一杯ええわ。', en: "Like this — one cup is fine.", style: 'gentle elder Kansai voice, soft warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おとうさんと、嬉しいわ。', en: "With you, Dad — happy.", style: 'soft Kansai man voice, warm tender familial delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ふふ、ありがとうな。', en: "Heh — thanks.", style: 'warm elder Kansai voice, soft humble appreciative delivery carefully' },
    ],
  },
  {
    id: 'conv_01524',
    context: 'Aoi helps Sho-young get over a fear of the dark at bedtime.',
    purpose: 'Adult comforting frightened child; gentle reassurance.',
    ambient: 'bedroom_dark_quiet',
    sound_effects: [],
    target_vocab: ['暗い', '怖い', '安心', '一緒'],
    cast: ['aoi_barista', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '蒼さん、暗いの怖い。', en: "Aoi-san — dark scares me.", style: 'soft scared child boy voice, warm small honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '大丈夫、私ここにいるよ。', en: "It's okay — I'm right here.", style: 'tender adult woman voice, soft warm protective delivery carefully' },
      { speaker: 'sho_child', jp: '一緒に寝てくれる?', en: "Will you stay with me?", style: 'soft child boy voice, warm hopeful small delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、寝るまでね。', en: "Yes — until you fall asleep.", style: 'soft adult woman voice, warm tender loving delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、安心した。', en: "Thanks — feel better.", style: 'soft sleepy child boy voice, warm grateful peaceful delivery carefully' },
    ],
  },
  {
    id: 'conv_01525',
    context: 'Big extended family gathering: meal table conversations cross-thread.',
    purpose: 'Many voices at a holiday meal; warm-overlapping family chat.',
    ambient: 'dining_room_busy_warm',
    sound_effects: [],
    target_vocab: ['集まる', '食事', '家族', '笑顔', '幸せ'],
    cast: ['hiroshi_elder', 'naoko_aunt', 'daichi_kansai', 'mei_romantic', 'hina_child', 'kenji_office'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'みんな揃って、嬉しいわ!', en: "Everyone's here — happy!", style: 'brassy Kansai aunt voice, bright loud warm delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ええ集まりやな。', en: "Yeah — fine gathering.", style: 'slow elder Kansai voice, warm content patriarchal delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お父さん、お酒どうぞ。', en: "Dad — have some sake.", style: 'warm Kansai husband voice, soft attentive familial delivery carefully' },
      { speaker: 'mei_romantic', jp: '料理、たくさんありますよ。', en: "Plenty of food.", style: 'gentle young mother voice, soft warm hosting delivery carefully' },
      { speaker: 'hina_child', jp: 'おばあちゃんの料理、最高!', en: "Grandma's cooking — the best!", style: 'bright teen girl voice, soft warm enthusiastic delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うちのも食べてや!', en: "Eat mine too!", style: 'animated Kansai aunt voice, bright loud fond delivery carefully' },
      { speaker: 'kenji_office', jp: 'みんなの笑顔、ええなぁ。', en: "Everyone's smiles — lovely.", style: 'soft Kansai artist voice, warm fond observant delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '家族の食事、何よりや。', en: "Family meals — above all.", style: 'gentle elder Kansai voice, soft warm wise delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'こうやって、続けていきたい。', en: "Want to keep this going.", style: 'soft Kansai husband voice, warm tender hopeful delivery carefully' },
      { speaker: 'mei_romantic', jp: '本当に、幸せです。', en: "Truly — happy.", style: 'tender young mother voice, soft warm content delivery carefully' },
      { speaker: 'hina_child', jp: 'みんな大好き!', en: "Love everyone!", style: 'bright teen girl voice, soft warm cheerful loving delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、ええ娘や、ほんま!', en: "Heh — fine girl, truly!", style: 'warm Kansai aunt voice, bright fond proud delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほな、もう一杯やろか。', en: "Right — another round?", style: 'warm Kansai man voice, soft cheerful inviting delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_076 wrote', CONVERSATIONS.length, 'files');
