import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_119)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02361',
    'Asuka gives an evening lecture on study methods; Hina attends and asks questions.',
    'Teacher in lecture register, naturally using formal connectives.',
    'lecture_hall_quiet',
    ['場合', 'において', 'あるいは', 'つまり', 'すべて', 'そして'],
    ['asuka_teacher', 'hina_child'], 'Long (13-20)',
    [
      { speaker: 'asuka_teacher', jp: '今日は、勉強の仕方について、お話しします。', en: "Today, I'll talk about how to study.", style: 'composed teacher voice, soft warm professional clear delivery carefully' },
      { speaker: 'hina_child', jp: '先生、よろしくお願いします。', en: "Thank you, sensei.", style: 'soft attentive teen girl voice, warm respectful delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'まず、暗記する場合、繰り返しが大切です。', en: "First, when memorizing, repetition matters.", style: 'gentle teacher voice, soft warm instructive delivery carefully' },
      { speaker: 'hina_child', jp: 'なるほど、毎日ですか?', en: "I see — every day?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ええ。読書においても、同じことが言えます。', en: "Yes. The same applies to reading, too.", style: 'warm teacher voice, soft warm explanatory delivery carefully' },
      { speaker: 'hina_child', jp: 'ノートに書く方法も、いいですか?', en: "Is writing it in a notebook good too?", style: 'soft teen girl voice, warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '書くか、あるいは声に出すか、どちらも効果的です。', en: "Writing, or speaking aloud — both are effective.", style: 'gentle teacher voice, soft warm informative delivery carefully' },
      { speaker: 'hina_child', jp: 'つまり、自分に合う方法を選ぶんですね。', en: "So, I choose the method that suits me.", style: 'thoughtful teen girl voice, soft warm understanding delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'その通りです。すべての人に、同じ方法は合いません。', en: "Exactly. The same method doesn't suit everyone.", style: 'warm teacher voice, soft warm affirming delivery carefully' },
      { speaker: 'hina_child', jp: 'すごく、分かりやすいです。', en: "That's really clear.", style: 'bright teen girl voice, soft warm appreciative delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'そして、何より、続けることが大事ですよ。', en: "And above all, continuing is what matters.", style: 'tender teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、頑張ります!', en: "Yes — I'll work hard!", style: 'soft determined teen girl voice, warm earnest delivery carefully' },
    ]),
  C('conv_02362',
    'Sakura and Ren go over a news article about labor reform for their column.',
    'Two writers in editorial register, civic vocabulary in context.',
    'study_room_lamp',
    ['労働', '政策', '委員', 'によって', 'に対して', '議論'],
    ['sakura_teen', 'ren_uni'], 'Long (13-20)',
    [
      { speaker: 'sakura_teen', jp: '蓮くん、この労働政策の記事、読んだ?', en: "Ren, did you read this article on labor policy?", style: 'soft adult writer voice, warm engaged professional delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、委員会の議論、複雑でしたね。', en: "Yes — the committee's debate was complex.", style: 'composed young man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '新しい制度によって、働き方が変わるみたい。', en: "It seems the new system will change how people work.", style: 'gentle adult writer voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: 'それに対して、反対の声もありますね。', en: "There are voices against it, too.", style: 'soft young man voice, warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '両方の意見、丁寧に書きたいね。', en: "I want to write both sides carefully.", style: 'soft adult writer voice, warm committed delivery carefully' },
      { speaker: 'ren_uni', jp: '委員の発言、引用しましょうか?', en: "Shall we quote the committee members' statements?", style: 'gentle young man voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、根拠が、はっきりするから。', en: "Yes — it makes the basis clear.", style: 'composed adult writer voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '読者にとって、分かりやすい記事になりそう。', en: "It'll be an easy-to-follow article for readers.", style: 'warm young man voice, soft warm hopeful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こういう議論こそ、続けるべきね。', en: "This is exactly the kind of debate we should keep up.", style: 'tender adult writer voice, soft warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '一緒に、進めましょう。', en: "Let's move forward together.", style: 'soft young man voice, warm warm collaborative delivery carefully' },
    ]),
  C('conv_02363',
    'Saito explains how a medication works to a curious Ren shadowing him.',
    'Doctor in explanatory register, technical-but-natural.',
    'clinic_office_quiet',
    ['場合', 'によって', '程度', 'ほとんど', '使用', '効果'],
    ['saito_doctor', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'saito_doctor', jp: 'この薬は、症状の程度によって、量を変えます。', en: "We adjust the dose of this medicine by the severity of symptoms.", style: 'measured doctor voice, soft warm professional clear delivery carefully' },
      { speaker: 'ren_uni', jp: '軽い場合は、少なめですか?', en: "For mild cases, is it a smaller amount?", style: 'curious young man voice, soft warm engaged delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ。ほとんどの患者さんは、それで良くなります。', en: "Yes. Most patients improve with that.", style: 'gentle doctor voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: '使用するとき、注意点はありますか?', en: "Are there precautions when using it?", style: 'engaged young man voice, soft warm professional delivery carefully' },
      { speaker: 'saito_doctor', jp: '食後に飲むこと。これが、効果を高めます。', en: "Take it after meals — that boosts the effect.", style: 'measured doctor voice, soft warm careful delivery carefully' },
      { speaker: 'ren_uni', jp: 'なるほど、勉強になります。', en: "I see — that's instructive.", style: 'humble young man voice, soft warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: '患者さんに、丁寧に伝えることが大事ですよ。', en: "It's important to explain it to patients carefully.", style: 'warm doctor voice, soft warm wise delivery carefully' },
    ]),
  C('conv_02364',
    'Hiroshi-boss runs a small company meeting; Yuki presents a decision.',
    'Business meeting register, professional vocabulary naturally.',
    'office_meeting_low',
    ['決定', '目的', '代表', '使用', 'について', '検討'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '今日の会議の目的、確認しましょう。', en: "Let's confirm the purpose of today's meeting.", style: 'measured boss voice, soft warm professional delivery carefully' },
      { speaker: 'yuki_office', jp: '新しいシステムの使用について、ご報告します。', en: "I'll report on the use of the new system.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '導入は、もう決定しましたか?', en: "Has its adoption been decided?", style: 'professional boss voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: 'いえ、まだ検討の段階です。', en: "No — it's still under consideration.", style: 'gentle office woman voice, soft warm clear delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '会社の代表として、慎重に決めたい。', en: "As the company's representative, I want to decide carefully.", style: 'warm boss voice, soft warm thoughtful delivery carefully' },
      { speaker: 'yuki_office', jp: '資料、ご確認いただけますか?', en: "Could you review the materials?", style: 'soft office woman voice, warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ええ。皆で、ようく考えましょう。', en: "Yes. Let's all think it through carefully.", style: 'warm boss voice, soft warm collaborative delivery carefully' },
    ]),
  C('conv_02365',
    'Sakura and Hiroshi-elder discuss an international news segment.',
    'Two adults discussing world affairs naturally.',
    'living_room_tv_low',
    ['国際', '中国', 'アメリカ', '韓国', '代表', '関係'],
    ['sakura_teen', 'hiroshi_elder'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'おとうさん、国際のニュース、見てますか?', en: "Otosan, are you watching the international news?", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、中国とアメリカの話、ようけ出とるな。', en: "Yeah — there's a lot about China and America.", style: 'slow elder Kansai voice, warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '韓国の代表も、会議に出ていましたね。', en: "Korea's representative was at the conference too.", style: 'gentle adult writer voice, soft warm informative delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '世界の関係、複雑になっとるな。', en: "World relations have grown complicated.", style: 'gentle elder Kansai voice, soft warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: '平和が、いちばん大事ですね。', en: "Peace is what matters most.", style: 'soft adult writer voice, warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、その通りや。', en: "Truly — exactly so.", style: 'warm elder Kansai voice, soft warm agreeing delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に、ちゃんと書きたい。', en: "I want to write about it properly.", style: 'tender adult writer voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02366',
    'Kenji explains the purpose of a new art project to Ren.',
    'Mentor in explanatory register, naturally formal.',
    'studio_lamp_evening',
    ['目的', 'そして', 'つまり', 'すべて', 'について', '表現'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '今回の作品の目的、説明するわ。', en: "Let me explain the aim of this work.", style: 'soft Kansai mentor voice, warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、ぜひ聞きたいです。', en: "Yes, I'd love to hear it.", style: 'soft young man voice, warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: '色について、ようけ考えてん。そして、線も。', en: "I thought a lot about color. And about line too.", style: 'gentle Kansai man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'ren_uni', jp: 'つまり、すべてに意味があるんですね。', en: "So everything has meaning.", style: 'thoughtful young man voice, soft warm understanding delivery carefully' },
      { speaker: 'kenji_office', jp: 'そや。表現するもの、すべて、繋がっとる。', en: "That's right. Everything I express is connected.", style: 'warm Kansai man voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '深い考え方ですね。', en: "That's a deep way of thinking.", style: 'soft young man voice, warm admiring delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前も、自分の表現、見つけてや。', en: "You find your own expression too.", style: 'tender Kansai man voice, soft warm encouraging delivery carefully' },
    ]),
  C('conv_02367',
    'Asuka explains a grammar point; Sho-young is the young learner.',
    'Teacher patiently explaining connectives to a child.',
    'classroom_after_quiet',
    ['つまり', 'しかも', 'そこで', '全く', 'あるいは', '例えば'],
    ['asuka_teacher', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '翔くん、「つまり」って言葉、知ってる?', en: "Sho, do you know the word \"in other words\"?", style: 'warm teacher voice, soft warm gentle delivery carefully' },
      { speaker: 'sho_child', jp: 'うーん、ちょっと、難しい。', en: "Hmm, it's a little hard.", style: 'soft child boy voice, warm honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '前の話を、まとめる時に使うのよ。', en: "You use it to sum up what came before.", style: 'gentle teacher voice, soft warm instructive delivery carefully' },
      { speaker: 'sho_child', jp: '「しかも」は?', en: "What about \"moreover\"?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '「しかも」は、付け加える時。例えば、こうよ。', en: "\"Moreover\" is for adding on. Like this, for example.", style: 'warm teacher voice, soft warm explanatory delivery carefully' },
      { speaker: 'sho_child', jp: '全く分からなかったけど、少し分かった!', en: "I didn't get it at all, but now I sort of do!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'そこで、もう一回、練習してみようね。', en: "So then, let's practice once more.", style: 'tender teacher voice, soft warm patient delivery carefully' },
    ]),
  C('conv_02368',
    'Ren reads about manufacturing for an article; discusses with Sakura.',
    'Writers discussing industry in editorial register.',
    'cafe_afternoon_low',
    ['生産', '購入', '及び', 'のみ', 'これら', '製品'],
    ['ren_uni', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'さくらさん、この工場の生産、すごいです。', en: "Sakura, this factory's output is incredible.", style: 'soft young man voice, warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どんな製品を、作ってるの?', en: "What kind of products do they make?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'ren_uni', jp: '部品、及び、完成品、両方です。', en: "Both parts and finished goods.", style: 'composed young man voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: 'これらは、どこで購入できるの?', en: "Where can these be purchased?", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '専門の店のみ、扱っているそうです。', en: "Apparently only specialty shops carry them.", style: 'gentle young man voice, soft warm informative delivery carefully' },
      { speaker: 'sakura_teen', jp: 'なるほど、面白い記事になりそう。', en: "I see — it'll make an interesting article.", style: 'warm adult writer voice, soft warm content delivery carefully' },
      { speaker: 'ren_uni', jp: '丁寧に、まとめます。', en: "I'll write it up carefully.", style: 'humble young man voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02369',
    'Daichi tells Mei about a workplace decision affecting his hours.',
    'Couple discussing work change naturally.',
    'kitchen_evening_warm',
    ['決定', 'わけ', 'その後', '以前', 'しまう', '相談'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'メイ、会社の決定で、勤務時間、変わるねん。', en: "Mei, a company decision is changing my work hours.", style: 'soft Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'えっ、どういうわけ?', en: "What — for what reason?", style: 'soft worried young wife voice, warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '以前より、朝が早くなってしまうんや。', en: "Mornings will get earlier than before.", style: 'gentle Kansai husband voice, soft warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'その後の予定も、変えないとね。', en: "We'll have to change the later schedule too.", style: 'gentle young woman voice, soft warm practical delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おまえと、ようく相談したかってん。', en: "I wanted to talk it over with you properly.", style: 'soft Kansai husband voice, warm warm earnest delivery carefully' },
      { speaker: 'mei_romantic', jp: '二人で、考えていこう。', en: "Let's think it through together.", style: 'tender young wife voice, soft warm united delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ありがとう、心強いわ。', en: "Thanks — that's reassuring.", style: 'tender Kansai husband voice, soft warm grateful delivery carefully' },
    ]),
  C('conv_02370',
    'Yuki explains a new law affecting the cafe to Aoi.',
    'Two women discussing regulation in practical register.',
    'cafe_office_quiet',
    ['法律', 'に関する', '場合', '及び', 'について', '確認'],
    ['yuki_office', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '蒼さん、食品に関する法律、変わったの。', en: "Aoi, the law on food has changed.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'aoi_barista', jp: 'まあ、お店に、影響あるの?', en: "Oh — does it affect the shop?", style: 'soft worried adult woman voice, warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: '表示及び保存方法について、確認が必要。', en: "We need to check the labeling and storage methods.", style: 'gentle office woman voice, soft warm informative delivery carefully' },
      { speaker: 'aoi_barista', jp: 'その場合、どうすればいい?', en: "In that case, what should I do?", style: 'curious adult woman voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: '一緒に、書類を見ましょう。', en: "Let's look at the documents together.", style: 'warm office woman voice, soft warm collaborative delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、助かる。', en: "Thanks — that helps.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'yuki_office', jp: '何でも、相談してね。', en: "Consult me about anything.", style: 'soft office woman voice, warm warm supportive delivery carefully' },
    ]),
  C('conv_02371',
    'Hiroshi-elder reflects on how society used to be; talks with Sakura.',
    'Elder reflecting on social change naturally.',
    'tatami_evening_lamp',
    ['以前', 'かなり', 'ほとんど', 'すべて', '彼ら', '時代'],
    ['hiroshi_elder', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_elder', jp: '以前は、近所付き合いが、かなり濃かったわ。', en: "In the old days, neighborly ties were quite close.", style: 'slow elder Kansai voice, warm reminiscent delivery carefully' },
      { speaker: 'sakura_teen', jp: '今とは、ずいぶん違うんですね。', en: "Quite different from now, then.", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほとんどの家が、互いに助け合うとった。', en: "Almost every household helped one another.", style: 'gentle elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '彼らの絆、すごく強かったんですね。', en: "Their bonds were really strong.", style: 'gentle adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'すべてが、ゆっくり流れとった時代や。', en: "It was a time when everything flowed slowly.", style: 'soft elder Kansai voice, warm warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: '貴重なお話、ありがとうございます。', en: "Thank you for this precious story.", style: 'tender adult writer voice, soft warm grateful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前に伝えられて、嬉しいわ。', en: "I'm glad I can pass it on to you.", style: 'warm elder Kansai voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02372',
    'Ren interviews a young environmental researcher about pollution.',
    'WIDENED SCENARIO: writer interviewing scientist — rare technical word in natural home.',
    'lab_office_low',
    ['汚染', '環境', '影響', 'における', '調査', 'ダイオキシン'],
    ['ren_uni', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '先生、この地域の汚染、深刻ですか?', en: "Doctor, is the pollution in this area serious?", style: 'soft young man voice, warm professional inquiry delivered carefully' },
      { speaker: 'sakura_teen', jp: '川における調査、続けています。', en: "We're continuing the survey in the river.", style: 'composed researcher-mode adult voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '環境への影響、大きいんですね。', en: "The impact on the environment is large, then.", style: 'gentle young man voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ええ。ダイオキシンの値、注意して見ています。', en: "Yes. We watch the dioxin levels carefully.", style: 'soft researcher voice, warm professional clear delivery carefully' },
      { speaker: 'ren_uni', jp: '一般の人に、どう伝えるべきですか?', en: "How should it be conveyed to the public?", style: 'engaged young man voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '丁寧に、事実を、伝えることが大事です。', en: "It's important to convey the facts carefully.", style: 'warm researcher voice, soft warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '記事に、しっかり書きます。', en: "I'll write it up thoroughly.", style: 'humble young man voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02373',
    'Sakura profiles a software engineer; discusses their work.',
    'WIDENED SCENARIO: tech profile interview — technical word in natural home.',
    'office_quiet_low',
    ['アルゴリズム', '開発', '効率', 'について', '改善', '技術'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'お仕事の内容について、教えてください。', en: "Please tell me about your work.", style: 'gentle adult writer voice, soft warm professional inquiry delivered carefully' },
      { speaker: 'ren_uni', jp: 'アルゴリズムの開発を、しています。', en: "I develop algorithms.", style: 'composed engineer-mode young man voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '効率を、高めるためですか?', en: "To improve efficiency?", style: 'curious adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、日々、改善を重ねています。', en: "Yes — I keep refining it day by day.", style: 'soft young man voice, warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '技術の進歩、速いですね。', en: "Technology advances quickly.", style: 'soft adult writer voice, warm appreciative delivery carefully' },
      { speaker: 'ren_uni', jp: '心は、忘れないようにしています。', en: "I try not to forget the human heart in it.", style: 'gentle young man voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '素敵な姿勢ですね。', en: "What a wonderful attitude.", style: 'tender adult writer voice, soft warm admiring delivery carefully' },
    ]),
  C('conv_02374',
    'Saito explains anesthesia to a nervous patient before a procedure.',
    'WIDENED SCENARIO: doctor explaining procedure — medical word in natural home.',
    'clinic_room_quiet',
    ['麻酔', '手術', '心配', 'について', '安心', '丁寧'],
    ['saito_doctor', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '先生、手術、すごく心配です。', en: "Doctor, I'm very anxious about the surgery.", style: 'soft worried young mother voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '麻酔について、丁寧に説明しますね。', en: "Let me explain the anesthesia carefully.", style: 'measured doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: '痛みは、ないんですか?', en: "There won't be any pain?", style: 'gentle young woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ、麻酔が効けば、痛みは感じません。', en: "Yes — once the anesthesia takes, you won't feel pain.", style: 'gentle doctor voice, soft warm clear delivery carefully' },
      { speaker: 'mei_romantic', jp: '少し、安心しました。', en: "I feel a little relieved.", style: 'soft young woman voice, warm warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'チーム全員で、しっかり支えますよ。', en: "The whole team will support you firmly.", style: 'warm doctor voice, soft warm steadfast delivery carefully' },
      { speaker: 'mei_romactic', jp: 'ありがとうございます。', en: "Thank you very much.", style: 'tender young woman voice, soft warm grateful delivery carefully' },
    ]),
  C('conv_02375',
    'Hiroshi-boss and Kenji discuss a representative attending a trade event.',
    'Business register, formal vocabulary naturally.',
    'office_meeting_low',
    ['代表', '国際', '使用', '及び', 'について', '参加'],
    ['hiroshi_boss', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '国際の展示会、代表を送りたい。', en: "I'd like to send a representative to the international expo.", style: 'measured boss voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええですね、誰が行きますか?', en: "Sounds good — who will go?", style: 'soft Kansai man voice, warm engaged delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '若手及びベテラン、両方、参加させたい。', en: "I want both young and veteran staff to attend.", style: 'professional boss voice, soft warm strategic delivery carefully' },
      { speaker: 'kenji_office', jp: '製品の使用例も、見せられますね。', en: "We can show product use cases too.", style: 'gentle Kansai man voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'その点について、準備を進めてくれ。', en: "Please proceed with preparations on that point.", style: 'warm boss voice, soft warm directive delivery carefully' },
      { speaker: 'kenji_office', jp: '了解しました、頑張ります。', en: "Understood — I'll do my best.", style: 'soft Kansai man voice, warm committed delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '頼りにしとるで。', en: "I'm counting on you.", style: 'warm boss voice, soft warm trusting delivery carefully' },
    ]),
  C('conv_02376',
    'Asuka discusses an international exchange program with a student.',
    'Teacher discussing opportunity in formal-natural register.',
    'classroom_after_quiet',
    ['国際', '韓国', 'において', '目的', 'すべて', '経験'],
    ['asuka_teacher', 'hina_child'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'ひな、国際交流のプログラム、知ってる?', en: "Hina, do you know about the international exchange program?", style: 'warm teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: 'いえ、どんなものですか?', en: "No — what's it like?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '韓国の学校において、一週間、過ごすの。', en: "You spend a week at a school in Korea.", style: 'gentle teacher voice, soft warm informative delivery carefully' },
      { speaker: 'hina_child', jp: 'わあ、目的は何ですか?', en: "Wow — what's the aim?", style: 'eager teen girl voice, bright warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '文化を学ぶこと。すべてが、貴重な経験よ。', en: "To learn the culture. Everything is a precious experience.", style: 'warm teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '行ってみたい!', en: "I'd love to go!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '応援するわ、頑張ってね。', en: "I'll support you — do your best.", style: 'tender teacher voice, soft warm supportive delivery carefully' },
    ]),
  C('conv_02377',
    'Ren reads a research paper aloud; discusses methodology with Saito.',
    'Mentor and protege in academic register naturally.',
    'study_lamp_quiet',
    ['調査', 'における', '行わ', '結果', 'について', '根拠'],
    ['ren_uni', 'saito_doctor'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '先生、この調査、どこで行われたんですか?', en: "Doctor, where was this study conducted?", style: 'soft young man voice, warm engaged professional delivery carefully' },
      { speaker: 'saito_doctor', jp: '大学の研究室において、行われました。', en: "It was carried out in a university lab.", style: 'measured doctor voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: '結果について、信頼できますか?', en: "Can the results be trusted?", style: 'engaged young man voice, soft warm probing delivery carefully' },
      { speaker: 'saito_doctor', jp: '根拠が、しっかりしています。', en: "The basis is solid.", style: 'gentle doctor voice, soft warm clear delivery carefully' },
      { speaker: 'ren_uni', jp: 'なるほど、勉強になります。', en: "I see — that's instructive.", style: 'humble young man voice, soft warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: '一つ一つ、確認する習慣、大事ですよ。', en: "The habit of checking each point matters.", style: 'warm doctor voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、心がけます。', en: "Yes — I'll keep that in mind.", style: 'soft young man voice, warm committed delivery carefully' },
    ]),
  C('conv_02378',
    'Naoko complains about a delivery truck blocking her shop; Kenji listens.',
    'Aunt venting about everyday nuisance naturally.',
    'ramen_shop_morning',
    ['トラック', 'バック', 'しまっ', '以外', 'かなり', '困る'],
    ['naoko_aunt', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'naoko_aunt', jp: 'けんちゃん、トラックが、店の前、塞いでしもた!', en: "Ken-chan, a truck blocked the front of the shop!", style: 'animated Kansai aunt voice, bright warm exasperated delivery carefully' },
      { speaker: 'kenji_office', jp: 'えっ、バックして、どけてもらえへんの?', en: "Eh — can't they back up and move?", style: 'soft Kansai man voice, warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'かなり、長い時間、止まってんねん。', en: "It's been parked there a good while.", style: 'frustrated Kansai aunt voice, bright warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'それは、困るな。', en: "That's a real problem.", style: 'gentle Kansai man voice, soft warm sympathetic delivery carefully' },
      { speaker: 'naoko_aunt', jp: '正面以外、入口、ないからな。', en: "There's no entrance besides the front.", style: 'soft Kansai aunt voice, warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: '俺、運転手さんに、声かけてみるわ。', en: "I'll go talk to the driver.", style: 'warm Kansai man voice, soft warm helpful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おおきに、助かるわ!', en: "Thanks — that's a big help!", style: 'warm Kansai aunt voice, bright warm grateful delivery carefully' },
    ]),
  C('conv_02379',
    'Sakura discusses a documentary about Chinese history with Hiroshi-elder.',
    'WIDENED SCENARIO: documentary discussion — proper nouns/history in natural home.',
    'living_room_tv_low',
    ['中国', '歴史', '時代', 'における', 'すべて', '文化'],
    ['sakura_teen', 'hiroshi_elder'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'おとうさん、中国の歴史の番組、深いですね。', en: "Otosan, this program on Chinese history is profound.", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、古い時代の話、興味深いな。', en: "Yeah — the ancient eras are fascinating.", style: 'slow elder Kansai voice, warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'その時代における文化、すごく豊かですね。', en: "The culture of that era was so rich.", style: 'gentle adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'すべて、長い歴史の積み重ねや。', en: "It's all the accumulation of long history.", style: 'gentle elder Kansai voice, soft warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: '学ぶこと、たくさんありますね。', en: "There's so much to learn.", style: 'soft adult writer voice, warm reverent delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、奥が深いわ。', en: "Truly, it runs deep.", style: 'warm elder Kansai voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: 'また、一緒に見ましょう。', en: "Let's watch again together.", style: 'tender adult writer voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02380',
    'Whole group has a relaxed evening; light formal-tinged conversation flows.',
    'Multi-voice gathering, natural with some formal vocabulary.',
    'living_room_evening_warm',
    ['そして', 'つまり', 'すべて', 'ひとつ', 'について', '皆'],
    ['hiroshi_elder', 'naoko_aunt', 'mei_romantic', 'daichi_kansai', 'sho_child', 'hina_child'], 'Long (13-20)',
    [
      { speaker: 'hiroshi_elder', jp: '今日も、皆、集まれて、ありがたいな。', en: "I'm grateful everyone could gather today too.", style: 'slow elder Kansai voice, warm warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ほんま、ええ晩や!', en: "Truly, a fine evening!", style: 'brassy Kansai aunt voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '一年について、振り返ると、いろいろあったね。', en: "Looking back on the year, a lot happened.", style: 'soft young mother voice, warm reflective delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'そして、すべて、ええ思い出になったわ。', en: "And it all became good memories.", style: 'warm Kansai husband voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼく、ひとつ、自慢があるよ!', en: "I've got one thing to brag about!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'なになに、聞かせて!', en: "What is it — tell us!", style: 'bright teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: 'かけっこで、勝ったんだ!', en: "I won the race!", style: 'animated child boy voice, bright warm proud delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'すごいやんか、つまり、一番速いんやな!', en: "Amazing — so you're the fastest!", style: 'warm Kansai aunt voice, bright warm delighted delivery carefully' },
      { speaker: 'mei_romantic', jp: '皆の前で、言えて、よかったね。', en: "I'm glad you could say it in front of everyone.", style: 'tender young mother voice, soft warm proud delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'こうやって、皆おるのが、何よりや。', en: "Having everyone here like this is what matters most.", style: 'gentle elder Kansai voice, soft warm enduring delivery carefully' },
      { speaker: 'daichi_kansai', jp: '来年も、皆で、過ごそうな。', en: "Let's spend next year together too.", style: 'warm Kansai husband voice, soft warm committed delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、絶対!', en: "Yeah — definitely!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: '皆、大好き!', en: "I love everyone!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
    ]),
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_119 wrote', CONVERSATIONS.length, 'files');
