import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_140)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // N4-finish: documentary/society cluster (少年 従来 向かっ 小泉 + 他人 イラク 教会 ものの いれ)
  C('conv_02781',
    'Documentary discussion: Asuka and Ren on a coming-of-age film.',
    'WIDENED SCENARIO: documentary discussion; vocabulary (少年/従来/向かっ/小泉/他人) in natural home.',
    'living_room_quiet',
    ['少年', '従来', '向かっ', '小泉', '他人'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この映画、少年が主人公なんですね。', en: "This film has a boy as the protagonist.", style: 'thoughtful young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、少年が夢に向かって歩みます。', en: "Yes, the boy walks toward his dream.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '従来の生き方とは、違うんですか?', en: "Is it different from conventional ways of living?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '従来の常識を、少年が破ります。', en: "The boy breaks conventional norms.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '時代は、小泉政権の頃ですか?', en: "Is it set in the Koizumi-government era?", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、小泉氏の時代が背景です。', en: "Yes, the Koizumi era is the backdrop.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '少年は、他人にも支えられますね。', en: "The boy is supported by strangers too.", style: 'understanding young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: '他人の優しさに、未来へ向かっていきます。', en: "With strangers' kindness, he heads toward the future.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02782',
    'News retrospective: Sakura and Ren on an era.',
    'WIDENED SCENARIO: news retrospective; vocabulary (少年/従来/向かっ/小泉/イラク) in natural home.',
    'studio_room_tone',
    ['少年', '従来', '向かっ', '小泉', 'イラク'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '小泉政権の時代を、振り返ります。', en: "We look back on the Koizumi-government era.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'イラクの問題も、大きかったですね。', en: "The Iraq issue was big too.", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '小泉氏は、従来の路線を変えました。', en: "Mr. Koizumi changed the conventional line.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '当時の少年は、何を感じたでしょう?', en: "What did boys of the time feel?", style: 'thoughtful young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '少年たちは、未来へ向かって育ちました。', en: "The boys grew up heading toward the future.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'イラクの報道も、毎日流れましたね。', en: "Iraq coverage aired every day.", style: 'measured young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '従来の価値観も、揺らぎました。', en: "Conventional values were shaken too.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '小泉氏の決断は、今も議論されます。', en: "Mr. Koizumi's decisions are still debated.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02783',
    'Asuka and Mei discuss a church scene in the film.',
    'WIDENED SCENARIO: film discussion; vocabulary (少年/従来/向かっ/小泉/教会) in natural home.',
    'living_room_quiet',
    ['少年', '従来', '向かっ', '小泉', '教会'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '少年が教会に行く場面、好きです。', en: "I love the scene where the boy goes to the church.", style: 'soft warm woman voice, gentle moved delivery throughout' },
      { speaker: 'asuka_teacher', jp: '古い教会へ、向かって歩きますね。', en: "He walks toward the old church.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '従来の自分を、捨てる場面ですよね。', en: "It's where he sheds his conventional self.", style: 'thoughtful woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、従来の迷いを、教会で手放します。', en: "Yes, he lets go of old doubts at the church.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '時代は、小泉政権の頃でしたね。', en: "It was set in the Koizumi-government era, right?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、小泉氏の時代の街並みです。', en: "Yes, the streetscape is from the Koizumi era.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '少年が前へ向かって、泣けました。', en: "The boy moving forward made me cry.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '教会の光が、未来を照らしますね。', en: "The church's light illuminates the future.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_02784',
    'Asuka and Ren on the boy meeting strangers.',
    'WIDENED SCENARIO: film discussion; vocabulary (少年/従来/向かっ/小泉/他人/ものの) in natural home.',
    'living_room_quiet',
    ['少年', '従来', '向かっ', '小泉', 'ものの'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '少年は、旅に出るんですね。', en: "The boy sets out on a journey.", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '不安なものの、前へ向かっていきます。', en: "Anxious though he is, he heads forward.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '従来の村を、出るんですか?', en: "Does he leave his conventional village?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、従来の暮らしに別れを告げます。', en: "Yes, he bids farewell to conventional life.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '小泉政権の頃の、地方の話ですね。', en: "It's a rural tale from the Koizumi era.", style: 'thoughtful young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '小泉氏の改革が、村にも届いた頃です。', en: "It's when Mr. Koizumi's reforms reached the village too.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '怖いものの、少年は進みますね。', en: "Scared though he is, the boy presses on.", style: 'moved young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: '夢に向かって、進む姿が美しいですね。', en: "His figure heading toward his dream is beautiful.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02785',
    'Asuka and Riku on the boy\'s resolve.',
    'WIDENED SCENARIO: film discussion; vocabulary (少年/向かっ/教会/他人/いれ) in natural home.',
    'living_room_quiet',
    ['少年', '向かっ', '教会', '他人', 'いれ'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '少年が、最後に決意するんですね。', en: "The boy resolves at the end.", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、心に力を入れて立ち上がります。', en: "Yes, he steels his heart and stands up.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '教会で、祈っていましたね。', en: "He was praying at the church.", style: 'observant teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '教会で、他人の優しさを思い出します。', en: "At the church, he recalls strangers' kindness.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '他人に、助けられてきたんですね。', en: "He's been helped by strangers.", style: 'understanding teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '少年は、未来へ向かって走り出します。', en: "The boy dashes off toward the future.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '力を入れて生きる姿、かっこいいです。', en: "His way of living with all his might is cool.", style: 'admiring teen boy voice, soft warm bright throughout' },
      { speaker: 'asuka_teacher', jp: '教会の鐘が、彼を送り出しますね。', en: "The church bell sends him off.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  // N4-finish: academic/business cluster (相当 ざる いただく 実践 + 受ける 与える 電子 追加 資本 向上)
  C('conv_02786',
    'Asuka lectures on putting ethics into practice.',
    'WIDENED SCENARIO: ethics lecture; vocabulary (相当/ざる/いただく/実践/受ける) in natural home.',
    'lecture_hall_quiet',
    ['相当', 'ざる', 'いただく', '実践', '受ける'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '倫理は、実践してこそ価値があります。', en: "Ethics has value only when practiced.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '実践は、相当難しそうですね。', en: "Practice seems considerably difficult.", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '相当な努力が、要ると認めざるを得ません。', en: "I can't deny it takes considerable effort.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '先生の助言を、いただけますか?', en: "May I receive your advice?", style: 'polite adult student voice, soft warm earnest throughout' },
      { speaker: 'asuka_teacher', jp: '喜んで。まず、小さな実践から受け止めましょう。', en: "Gladly. First, take on small practices.", style: 'warm teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '影響を受ける人を、考えるんですね。', en: "We consider those who are affected.", style: 'thoughtful adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、その視点は欠かせざるものです。', en: "Yes, that viewpoint is indispensable.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '助言をいただけて、相当助かりました。', en: "Receiving your advice helped considerably.", style: 'grateful adult student voice, soft warm appreciative closing throughout' },
    ]),

  C('conv_02787',
    'Asuka guides Ren on applying research.',
    'WIDENED SCENARIO: academic guidance; vocabulary (相当/ざる/いただく/実践/与える) in natural home.',
    'lecture_hall_quiet',
    ['相当', 'ざる', 'いただく', '実践', '与える'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '研究を、実践に活かしたいです。', en: "I want to apply my research in practice.", style: 'earnest young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '実践は、社会に影響を与えますよ。', en: "Practice gives an impact to society.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '相当な準備が、要りますか?', en: "Does it require considerable preparation?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '相当の覚悟は、持たざるを得ませんね。', en: "You can't help but hold considerable resolve.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '助言を、いただけますか?', en: "May I receive your advice?", style: 'polite young student voice, soft warm earnest throughout' },
      { speaker: 'asuka_teacher', jp: 'いただいた疑問に、ヒントを与えましょう。', en: "I'll give hints to the questions you raised.", style: 'warm teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '実践で、人に希望を与えたいです。', en: "Through practice, I want to give people hope.", style: 'resolved young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'その志は、相当に立派ですよ。', en: "That ambition is considerably admirable.", style: 'composed teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02788',
    'Hiroshi-boss and Yuki adopt an electronic system.',
    'WIDENED SCENARIO: business ops; vocabulary (相当/ざる/いただく/実践/電子) in natural home.',
    'office_quiet_low',
    ['相当', 'ざる', 'いただく', '実践', '電子'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '電子の仕組みを、導入したい。', en: "I want to introduce an electronic system.", style: 'decisive boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '電子化で、相当楽になりますね。', en: "Going electronic will make it considerably easier.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '社員の同意を、いただけるかね?', en: "Can we get the employees' consent?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '丁寧に説明し、同意をいただきます。', en: "I'll explain carefully and obtain consent.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '実践には、訓練が要るな。', en: "Practice requires training.", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '相当な訓練を、せざるを得ませんね。', en: "We can't help but do considerable training.", style: 'earnest office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '電子の実践を、段階的に進めよう。', en: "Let's roll out the electronic practice in stages.", style: 'firm boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '皆の協力を、いただいて進めます。', en: "I'll proceed with everyone's cooperation.", style: 'resolved office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02789',
    'Ren reports a funded project to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (相当/いただく/実践/追加/資本) in natural home.',
    'office_quiet_low',
    ['相当', 'いただく', '実践', '追加', '資本'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '新事業に、相当の資本が集まりました。', en: "Considerable capital gathered for the new venture.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '追加の資本も、必要かね?', en: "Is additional capital needed too?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '少し追加すれば、実践に移せます。', en: "With a little addition, we can put it into practice.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '出資者の理解は、いただけたかね?', en: "Did we receive investors' understanding?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'はい、快く了承をいただきました。', en: "Yes, we received their ready consent.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '相当な期待が、寄せられているな。', en: "Considerable expectations are being placed on us.", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '追加資本を活かし、実践します。', en: "Using the added capital, we'll execute.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '相当の覚悟で、進めてくれ。', en: "Proceed with considerable resolve.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02790',
    'Riku and Aoi chat about a baseball season.',
    'Casual register; vocabulary (野球/秒/いれ/向上/ものの) in natural home.',
    'cafe_quiet_chatter',
    ['野球', '秒', 'いれ', '向上', 'ものの'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '今シーズン、野球を頑張ってるんだ。', en: "This season, I'm working hard at baseball.", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '走るのも、速くなったの?', en: "Did you get faster at running too?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、数秒だけど、向上したよ!', en: "Yeah, only a few seconds, but I improved!", style: 'proud teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'すごいね、練習に力を入れたんだね。', en: "Amazing, you put effort into practice.", style: 'admiring barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '大変なものの、毎日が楽しいよ。', en: "It's tough, but every day is fun.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '野球で、技術も向上しそうだね。', en: "Your skills will improve through baseball too.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'もっと力を入れて、向上したい!', en: "I want to put in more effort and improve!", style: 'determined teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '一秒でも速く、応援してるよ!', en: "Even a second faster — I'm cheering you on!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  // N3 count-4 sweep (10 convs)
  C('conv_02791',
    'Mei and Ren chat about a lazy day off.',
    'Casual register; vocabulary (取る/困る/回っ/戻り/暇) in natural home.',
    'cafe_quiet_chatter',
    ['取る', '困る', '回っ', '戻り', '暇'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '今日は、久しぶりに休みを取ったの。', en: "Today I took a day off for the first time in a while.", style: 'soft warm woman voice, gentle relaxed delivery throughout' },
      { speaker: 'ren_uni', jp: 'いいね、暇な一日もたまには必要だよ。', en: "Nice, a free day is needed now and then.", style: 'warm young man voice, soft warm relaxed delivery throughout' },
      { speaker: 'mei_romantic', jp: '街を、ぐるっと回ってきたの。', en: "I went all around town.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '道に、困らなかった?', en: "Didn't you get lost?", style: 'curious young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '少し困ったけど、無事に戻りました。', en: "I was a bit troubled, but returned safely.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '暇な時間、楽しめた?', en: "Did you enjoy the free time?", style: 'gentle young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、休みを取って良かったな。', en: "Yeah, I'm glad I took the day off.", style: 'content woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'また暇を見つけて、回ろうよ。', en: "Let's find free time and wander again.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02792',
    'Aoi and Riku talk about singing and rhythm.',
    'Casual register; vocabulary (歌っ/リズム/選択肢/たっぷり/暇) in natural home.',
    'cafe_quiet_chatter',
    ['歌っ', 'リズム', '選択肢', 'たっぷり', '暇'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '昨日、家でたっぷり歌ったんだ。', en: "Yesterday I sang plenty at home.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '暇な時は、音楽が一番だね。', en: "When you're free, music is best.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'リズムに乗るのが、楽しいんだ。', en: "Riding the rhythm is fun.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '曲の選択肢が、たっぷりあるね。', en: "There are plenty of song choices.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '選択肢が多すぎて、迷っちゃう。', en: "Too many choices — I can't decide.", style: 'playful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '暇な日に、一緒に歌おうよ。', en: "Let's sing together on a free day.", style: 'warm barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'いいね、リズムに合わせて歌おう!', en: "Nice, let's sing to the rhythm!", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'たっぷり歌って、すっきりしようね!', en: "Let's sing plenty and feel refreshed!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02793',
    'Saito guides Yuki through a shoulder stretch.',
    'WIDENED SCENARIO: medical/exercise; vocabulary (肩/まわり/底/組み合わせ/少々) in natural home.',
    'clinic_room_quiet',
    ['肩', 'まわり', '底', '組み合わせ', '少々'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '先生、肩がこって辛いんです。', en: "Doctor, my shoulders are stiff and it's painful.", style: 'tired office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '肩のまわりを、ほぐしましょう。', en: "Let's loosen the area around the shoulders.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: '少々、痛むかもしれませんね。', en: "It might hurt a little.", style: 'cautious office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '少々の痛みなら、心配ありません。', en: "A little pain is nothing to worry about.", style: 'gentle doctor voice, soft warm reassuring clarity throughout' },
      { speaker: 'yuki_office', jp: 'まわりの筋肉も、固いんですか?', en: "Are the surrounding muscles stiff too?", style: 'curious office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '足の底から、肩まで組み合わせて動かします。', en: "We move from the soles up to the shoulders, in combination.", style: 'clear doctor voice, soft warm measured clarity throughout' },
      { speaker: 'yuki_office', jp: 'いろんな動きを、組み合わせるんですね。', en: "So we combine various movements.", style: 'understanding office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '肩のまわりが、少々軽くなりましたね。', en: "The area around your shoulders is a little lighter now.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_02794',
    'Mei and Aoi welcome a returning friend.',
    'Casual register; vocabulary (歓迎/祈り/なくなっ/らしく/戻り) in natural home.',
    'cafe_quiet_chatter',
    ['歓迎', '祈り', 'なくなっ', 'らしく', '戻り'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '彼女が、町に戻ってきたんだって!', en: "She's come back to town, I hear!", style: 'excited barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '本当?盛大に歓迎したいね。', en: "Really? Let's give a grand welcome.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'aoi_barista', jp: '前の店は、なくなっちゃったよね。', en: "The old shop is gone now, right?", style: 'wistful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、お気に入りがなくなって寂しいの。', en: "Yeah, it's sad my favorite is gone.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '彼女らしく、元気に戻ってきたかな?', en: "Did she come back lively, just like her?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '元気でいてと、祈っていたの。', en: "I was praying she'd be well.", style: 'tender woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '彼女らしい笑顔が、見られるね。', en: "We'll get to see her signature smile.", style: 'warm barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '心から、歓迎しようね。', en: "Let's welcome her from the heart.", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02795',
    'Asuka and Riku discuss a documentary on modern science.',
    'WIDENED SCENARIO: science discussion; vocabulary (近代/進化/建て/組み合わせ/中村) in natural home.',
    'living_room_quiet',
    ['近代', '進化', '建て', '組み合わせ', '中村'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '近代の科学は、急に進化したんですか?', en: "Did modern science evolve suddenly?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '近代以降、技術が大きく進化しました。', en: "Since the modern era, technology evolved greatly.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'この研究者、中村さんですか?', en: "Is this researcher Mr. Nakamura?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、中村博士の研究です。', en: "Yes, it's Dr. Nakamura's research.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '新しい装置を、建てたんですか?', en: "Did they build a new facility?", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '大きな施設を建て、実験しました。', en: "They built a large facility and experimented.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '色々な技術を、組み合わせたんですね。', en: "They combined various technologies.", style: 'understanding teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '中村博士の組み合わせは、見事でした。', en: "Dr. Nakamura's combination was splendid.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02796',
    'Asuka and Mei discuss a novel\'s characters.',
    'WIDENED SCENARIO: literature chat; vocabulary (中村/木村/歌っ/祈り/らしく) in natural home.',
    'living_room_quiet',
    ['中村', '木村', '歌っ', '祈り', 'らしく'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この物語、中村が魅力的でした。', en: "In this story, Nakamura was fascinating.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: '中村は、いかにも人間らしく描かれていますね。', en: "Nakamura is drawn so very human.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '友人の木村も、いい人ですね。', en: "His friend Kimura is a good person too.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '木村が、静かに歌う場面が好きです。', en: "I love the scene where Kimura sings quietly.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '木村が歌った歌、心に残りました。', en: "The song Kimura sang stayed with me.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '終わりの祈りも、美しいですね。', en: "The prayer at the end is beautiful too.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '中村の祈りに、泣いてしまいました。', en: "I cried at Nakamura's prayer.", style: 'tender woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '木村らしく、最後まで優しかったですね。', en: "True to Kimura, he was kind to the end.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_02797',
    'Sho tells Grandma about a fun mishap.',
    'Casual home register; vocabulary (取る/困っ/回っ/ちゃい/底) in natural home.',
    'tatami_room_quiet',
    ['取る', '困っ', '回っ', 'ちゃい', '底'],
    ['sho_child', 'sachiko_grandma'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おばあちゃん、コマを回して遊んだよ!', en: "Grandma, I played by spinning a top!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'まあ、上手に回ったの?', en: "Oh my, did it spin well?", style: 'tender grandmother voice, soft warm gentle delivery throughout' },
      { speaker: 'sho_child', jp: 'うん、でも箱の底に落ちちゃい困ったの。', en: "Yeah, but it fell to the bottom of the box, and I was stuck.", style: 'pouty small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '底から、取れなかったの?', en: "Couldn't you get it out from the bottom?", style: 'gentle grandmother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '手が届かなくて、困っちゃった。', en: "My hand couldn't reach, so I was troubled.", style: 'rueful small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '箱を回して、取ってみましょうね。', en: "Let's turn the box and get it out.", style: 'tender grandmother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'あ、底から取れたよ!', en: "Oh, I got it from the bottom!", style: 'delighted small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'よかったね。また回して遊びましょう。', en: "Wonderful. Let's spin it and play again.", style: 'tender grandmother voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02798',
    'Daichi welcomes Mei back from a trip.',
    'Casual register; vocabulary (歓迎/戻り/暇/取る/なくなっ) in natural home.',
    'cafe_quiet_chatter',
    ['歓迎', '戻り', '暇', '取る', 'なくなっ'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'おかえり!旅から戻ったんやな、歓迎するで!', en: "Welcome back! You returned from your trip — welcome!", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ただいま。休みを取って、良かったです。', en: "I'm back. I'm glad I took time off.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'daichi_kansai', jp: '暇な時間、ゆっくりできたか?', en: "Did you relax in your free time?", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'はい、たっぷり暇を楽しみました。', en: "Yes, I enjoyed plenty of free time.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'あの古い宿、なくなったらしいで。', en: "That old inn is gone, apparently.", style: 'wistful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'え、なくなっちゃったんですか?残念。', en: "Huh, it's gone? What a shame.", style: 'surprised woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'また休みを取って、一緒に行こか。', en: "Let's take time off and go together again.", style: 'warm Kansai man voice, warm friendly delivery throughout' },
      { speaker: 'mei_romantic', jp: '戻ってこられて、嬉しいです。', en: "I'm happy to be back.", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02799',
    'Ren and Kenji discuss design choices.',
    'WIDENED SCENARIO: tech design; vocabulary (選択肢/組み合わせ/少々/取る/らしく) in natural home.',
    'office_quiet_low',
    ['選択肢', '組み合わせ', '少々', '取る', 'らしく'],
    ['ren_uni', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この画面、選択肢が多すぎませんか?', en: "Doesn't this screen have too many options?", style: 'curious young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: '少々、減らした方がいいですね。', en: "It's better to reduce them a little.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '色の組み合わせも、迷います。', en: "I'm torn on the color combination too.", style: 'thoughtful young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: '落ち着いた組み合わせを、取りましょう。', en: "Let's go with a calm combination.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'うちのアプリらしく、したいです。', en: "I want it to feel like our app.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'らしさを出すなら、選択肢は絞りましょう。', en: "To bring out that character, let's narrow the options.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '少々シンプルに、組み合わせ直します。', en: "I'll recombine it a little more simply.", style: 'resolved young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '良い選択肢を、取れましたね。', en: "We made good choices.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02800',
    'Riku tells Aoi about a class that got cancelled.',
    'Casual register; vocabulary (困っ/なくなっ/回っ/れれ/暇) in natural home.',
    'cafe_quiet_chatter',
    ['困っ', 'なくなっ', '回っ', '進化', '暇'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '今日の授業、急になくなったんだ。', en: "Today's class was suddenly cancelled.", style: 'surprised teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'え、予定がなくなって困った?', en: "Huh, were you troubled the plan fell through?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '最初は困ったけど、暇ができたよ。', en: "At first I was stuck, but I got free time.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '暇な時間、何して回ったの?', en: "What did you do with your free time?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '街を回って、新しい店を見つけたよ。', en: "I went around town and found a new shop.", style: 'happy teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '街も、どんどん進化してるね。', en: "The town keeps evolving too.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '古い店がなくなって、少し寂しいな。', en: "It's a bit sad the old shops are gone.", style: 'wistful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '暇な日に、また一緒に回ろうよ!', en: "Let's go around together again on a free day!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_140 wrote', CONVERSATIONS.length, 'files');
