// scripts/batches/batch_001.mjs
//
// First in-conversation batch: 20 conversations (conv_00004 .. conv_00023).
// Hand-authored by Claude in the chat; written to data/conversations/.
//
// Run: node scripts/batches/batch_001.mjs

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
fs.mkdirSync(OUT_DIR, { recursive: true });

const NOW = new Date().toISOString();

const CONVERSATIONS = [
  {
    id: 'conv_00004',
    context: 'End of a long workday. Kenji catches Yuki at her desk and floats the idea of dinner.',
    purpose: 'casual workplace invitation — gentle decompression after a hard day',
    ambient: 'quiet_office',
    target_vocab: ['今日','一緒','本当に','ありがとう','時間','大丈夫','明日','うん'],
    cast: ['kenji_office','yuki_office'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'kenji_office', jp: 'お、まだいたんだ。', en: 'Oh, still here?', style: 'Light, surprised opener; warm step-down on the second clause. The tone of someone who didn\'t expect to find her but is glad he did.', mood: 'warm_surprised' },
      { speaker: 'yuki_office', jp: 'うん…ちょっと色々あって。', en: 'Yeah… a few things going on.', style: 'Soft, slightly trailing answer. Faintly apologetic without being dramatic. The 「色々」 carries a small weight.', mood: 'tired_evasive' },
      { speaker: 'kenji_office', jp: '今日、本当にお疲れさま。よかったら、ご飯一緒にどう？', en: 'Long day today, really. If you\'re up for it, want to grab dinner together?', style: 'Casual but careful pacing. The invitation arrives like a sidestep — no pressure in the voice. Slight lift on 「どう？」.', mood: 'inviting' },
      { speaker: 'yuki_office', jp: 'えっ、いいの？', en: 'Wait — really?', style: 'Tiny surprised note. The 「えっ」 is half a breath before the question. Pleasure underneath but kept small.', mood: 'pleased_surprise' },
      { speaker: 'kenji_office', jp: 'もちろん。時間あるなら、すぐそこ。', en: 'Of course. If you\'ve got the time, just around the corner.', style: 'Casual reassurance. Hand gesture in the voice. Quick, easy.', mood: 'easy' },
      { speaker: 'yuki_office', jp: '大丈夫だよ。ありがとう、ほんと助かる。', en: 'Yeah, I\'m good. Thanks — really, this helps.', style: 'The thank-you lands genuine rather than polite. Voice steadier than two lines ago.', mood: 'grateful' },
      { speaker: 'kenji_office', jp: 'じゃ、行こ。明日のことは明日考える。', en: 'Then let\'s go. Tomorrow\'s problems are tomorrow\'s.', style: 'Warm closing. Half-laugh in the second clause. The kind of sentence that ends a workday.', mood: 'closing_warm' },
    ],
  },
  {
    id: 'conv_00005',
    context: 'Late morning at the office. Hiroshi stops by Yuki\'s desk after reviewing the report she submitted yesterday.',
    purpose: 'small unexpected recognition — boss-to-subordinate, register stays formal',
    ambient: 'quiet_office',
    target_vocab: ['本当に','ありがとう','大変','時間','ない'],
    cast: ['hiroshi_boss','yuki_office'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hiroshi_boss', jp: '田中さん、昨日の報告書、読みました。', en: 'Ms. Tanaka. I\'ve read yesterday\'s report.', style: 'Composed, neutral, fully controlled. Every word intentional. No volume change.', mood: 'composed_opener' },
      { speaker: 'yuki_office', jp: 'あっ、お時間取らせてしまって、すみません。', en: 'Oh — sorry to have taken your time.', style: 'Reflexive deference. A small bow inside the voice. The 「あっ」 is half a breath, not a real exclamation.', mood: 'deferential' },
      { speaker: 'hiroshi_boss', jp: 'いや、よく整理されていた。あれは本当に助かりました。', en: 'No — it was well organised. That was genuinely helpful.', style: 'Slight softening on 「本当に」 — for him, this is warmth. Still controlled, still even. JP and EN: no smile in the voice, but the meaning of one.', mood: 'understated_warm' },
      { speaker: 'yuki_office', jp: 'いえ、そんな…ありがとうございます。', en: 'Not at all… thank you.', style: 'Surprised, almost knocked back. The 「いえ、そんな」 is genuine, not perfunctory. The thank-you is quieter than expected.', mood: 'genuinely_surprised' },
      { speaker: 'hiroshi_boss', jp: '大変だったと思います。引き続きお願いします。', en: 'I imagine it was hard work. Please keep it up.', style: 'Closing line, a hint warmer than the opener but still within his register. Each word fully formed. He turns to leave on the final syllable.', mood: 'closing' },
    ],
  },
  {
    id: 'conv_00006',
    context: 'Saturday morning. Daichi calls Kenji from Osaka to figure out plans for the evening.',
    purpose: 'friend logistics with banter — casual Kansai-Tokyo phone call between close mates',
    ambient: 'phone_call_silent',
    target_vocab: ['今日','明日','今','一緒','本当に','どう','時間','ない'],
    cast: ['daichi_kansai','kenji_office'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'daichi_kansai', jp: 'おーい、今どこ？', en: 'Oi — where are you right now?', style: 'Loud opener. The 「おーい」 stretched playfully. Kansai energy. No greeting, just straight in.', mood: 'energetic_opener' },
      { speaker: 'kenji_office', jp: '今うちだよ。なに、もう外おる？', en: 'I\'m at home. What — you out already?', style: 'Half-laugh in the voice. Picks up the Kansai inflection for one word ironically. Warm, used to this.', mood: 'amused' },
      { speaker: 'daichi_kansai', jp: 'まだまだ。今日さ、本当に時間ある？', en: 'Nah, not yet. Listen — do you actually have time today?', style: 'Drops half a register to mock-serious. The 「本当に」 is fishing — checking before he commits to a plan.', mood: 'checking' },
      { speaker: 'kenji_office', jp: 'あるよ。何時から？', en: 'Yeah. From when?', style: 'Calm, ready. The lowest-energy line of the call so far on purpose — letting Daichi drive.', mood: 'available' },
      { speaker: 'daichi_kansai', jp: '七時に駅でどう？飲み行こ。', en: 'Seven at the station — how\'s that? Let\'s go drink.', style: 'Lift on 「どう？」, then a flatter, decided 「飲み行こ」. Plan-making mode.', mood: 'planning' },
      { speaker: 'kenji_office', jp: '七時了解。一緒に行く店、もう決めた？', en: 'Seven, got it. You picked the place yet?', style: 'Brisk acknowledgment, then a small teasing prod. Knows Daichi has not picked the place.', mood: 'teasing' },
      { speaker: 'daichi_kansai', jp: '(笑) おまえなぁ、それは今から決めるねん！', en: '(laughs) Oi, that\'s what we\'re deciding NOW!', style: 'Big laugh. Volume up. The 「ねん」 ending is full Kansai. Mock-outraged. JP and EN: both performed-loud.', mood: 'playfully_outraged' },
      { speaker: 'kenji_office', jp: 'はいはい、じゃあ明日には決まってるってことで。', en: 'Yeah, yeah — so let\'s say it\'s decided by tomorrow then.', style: 'Dry comeback. The 「はいはい」 is the wear-the-shoes-of-a-tired-friend dryness. Affectionate underneath.', mood: 'dry' },
    ],
  },
  {
    id: 'conv_00007',
    context: 'Sunday breakfast. Yumiko and Ryosuke are running through the week ahead. The parent-teacher meeting is on Thursday.',
    purpose: 'partner logistics + small worry surfaced — coordination edged with care',
    ambient: 'apartment_indoor',
    target_vocab: ['今週','どう','大丈夫','時間','一緒','明日'],
    cast: ['yumiko_mom','ryosuke_dad'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'yumiko_mom', jp: '今週木曜、面談ね。覚えてる？', en: 'Thursday this week is the meeting. Remember?', style: 'Practical, hands-still-working tone. A check, not a reminder lecture. The 「ね」 at the end is the warm assumption that he does.', mood: 'practical_check' },
      { speaker: 'ryosuke_dad', jp: 'うん、覚えてる。何時からだっけ？', en: 'Yeah, I remember. What time was it again?', style: 'Coffee-cup voice. Confirms before asking the actual question. Soft, present.', mood: 'confirming' },
      { speaker: 'yumiko_mom', jp: '四時。一緒に行ける？', en: 'Four. Can you come with me?', style: 'A small lift on 「一緒に行ける？」. The ask is gentle but real — she wants him there for this one.', mood: 'asking_softly' },
      { speaker: 'ryosuke_dad', jp: '行く。仕事は何とかなる。', en: 'I\'m going. Work will be fine.', style: 'Quiet decisiveness. He commits before checking if he should. Both clauses spoken flat and warm.', mood: 'committing' },
      { speaker: 'yumiko_mom', jp: 'ありがとう。…ちょっとだけ、心配。', en: 'Thank you. …I\'m a little worried.', style: 'A pause before the second clause. The worry isn\'t performed — it slips out. JP and EN both: keep it small.', mood: 'quiet_worry' },
      { speaker: 'ryosuke_dad', jp: '大丈夫だよ。ひな、今うまくいってる。', en: 'It\'s going to be okay. Hina\'s doing well right now.', style: 'Steady reassurance. Speaks slightly slower than usual to hold the moment. Eye-contact-level voice.', mood: 'reassuring' },
      { speaker: 'yumiko_mom', jp: 'うん。明日また話そう、時間あるとき。', en: 'Yeah. Let\'s talk again tomorrow, when we\'ve got time.', style: 'Soft conclusion. She is parking the worry, not putting it down. Gentle.', mood: 'closing_soft' },
    ],
  },
  {
    id: 'conv_00008',
    context: 'After school. Hina rushes to Yumiko in the kitchen with a folded paper, very pleased with herself.',
    purpose: 'small parent-child celebration — pure warmth',
    ambient: 'apartment_indoor',
    target_vocab: ['見る','本当に','一番','ありがとう','大きい'],
    cast: ['hina_child','yumiko_mom'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hina_child', jp: 'お母さん、お母さん！これ見て見て！', en: 'Mom, mom! Look at this, look look!', style: 'Pure eight-year-old explosion. Bouncing in the voice. Paper waved on the second 「見て」.', mood: 'excited' },
      { speaker: 'yumiko_mom', jp: 'はいはい、なに？……うわ、すごい。', en: 'Okay okay, what is it? …Whoa — that\'s great.', style: 'Mom-tone shifts mid-line. The first half is logistical; the 「うわ」 is genuinely impressed. Genuine, not performed.', mood: 'shifting_impressed' },
      { speaker: 'hina_child', jp: '本当に？うさぎ、大きいでしょ？', en: 'For real? The bunny\'s big, right?', style: 'Lit-up question. Her own pride breaking through. Lift on 「大きい」 as she points.', mood: 'proud_seeking' },
      { speaker: 'yumiko_mom', jp: 'うん、上手。これ、クラスで一番じゃない？', en: 'Yeah, it\'s great. Best in the class, isn\'t it?', style: 'Warm exaggeration but the warmth is honest. Mom-tone returning.', mood: 'praising' },
      { speaker: 'hina_child', jp: 'ありがとう！冷蔵庫に貼っていい？', en: 'Thank you! Can I put it on the fridge?', style: 'Already moving. The question is performative — she\'s already going for the magnets.', mood: 'already_moving' },
      { speaker: 'yumiko_mom', jp: 'いいよ。一番上のとこに貼ってあげる。', en: 'Sure. I\'ll put it right at the top.', style: 'Walking-toward-her warmth. The plan is being shared on the move.', mood: 'participating' },
    ],
  },
  {
    id: 'conv_00009',
    context: 'Bedtime. Sho is six and the light is off. Ryosuke is sitting on the edge of the bed.',
    purpose: 'comfort + reassurance — dad-to-young-child after a small worry',
    ambient: 'apartment_indoor',
    target_vocab: ['大丈夫','怖い','一緒','明日','本当に','時間'],
    cast: ['sho_child','ryosuke_dad'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、ちょっと、まだいて。', en: 'Daddy, stay just a little.', style: 'Small, quiet. Almost-whisper. A child not wanting to be alone but trying not to be a bother.', mood: 'small_request' },
      { speaker: 'ryosuke_dad', jp: 'いるよ。どうした？', en: 'I\'m here. What\'s up?', style: 'Sits-down voice. Calm, present, no rush. The 「どうした？」 is open, not probing.', mood: 'present' },
      { speaker: 'sho_child', jp: 'なんか、怖い感じがする。', en: 'Something… feels scary.', style: 'Pauses inside the line. The 「なんか」 is a child not having the word yet. Soft and honest.', mood: 'naming_the_fear' },
      { speaker: 'ryosuke_dad', jp: 'うん。本当のこと言うと、お父さんも子どもの時、よくそうだったよ。', en: 'Yeah. To tell you the truth, when I was a kid I felt that a lot too.', style: 'Slow, warm. The confession is gentle — making the kid less alone with it. JP and EN: same easy honesty.', mood: 'sharing' },
      { speaker: 'sho_child', jp: '本当に？', en: 'Really?', style: 'Tiny lift of relief. Two syllables that mean a lot.', mood: 'relieved_lift' },
      { speaker: 'ryosuke_dad', jp: '本当に。明日まで、ここにいるから。一緒にいよう。', en: 'Really. I\'ll be here until tomorrow. Let\'s be together a while.', style: 'Steady promise. Slows down for 「一緒にいよう」. The kind of sentence that settles a small body.', mood: 'settling' },
      { speaker: 'sho_child', jp: 'うん。…大丈夫。', en: 'Yeah. …I\'m okay.', style: 'Sleepy already. The 「大丈夫」 is half-spoken, almost a sigh.', mood: 'sleepy_okay' },
    ],
  },
  {
    id: 'conv_00010',
    context: 'Morning rush at the café. Yuki is a near-daily regular. Aoi already knows what she wants.',
    purpose: 'tiny familiar transaction — service warmth that builds over many mornings',
    ambient: 'cafe_morning',
    target_vocab: ['今日','いつも','ありがとう','大丈夫','一緒','本当に'],
    cast: ['aoi_barista','yuki_office'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'aoi_barista', jp: 'おはようございます。今日もいつもので大丈夫ですか？', en: 'Good morning. The usual today, okay?', style: 'Warm, melodic, professional. The 「いつもの」 is gentle inside joke — they both know what it is. Eye contact lifted.', mood: 'familiar_warm' },
      { speaker: 'yuki_office', jp: 'はい、お願いします。…あ、今日はちょっと急ぐかも。', en: 'Yes please. …Oh — I might be in a bit of a hurry today.', style: 'Cheerful first half, then a small apologetic add. The 「あ」 is half a breath.', mood: 'apologetic_add' },
      { speaker: 'aoi_barista', jp: '大丈夫です、すぐ出します。', en: 'No problem — I\'ll have it out fast.', style: 'Quick, kind, no fuss. The reassurance lands as practical, not performed.', mood: 'efficient_kind' },
      { speaker: 'yuki_office', jp: '本当に助かります。', en: 'Really, you\'re a lifesaver.', style: 'Genuine thanks. The 「本当に」 sincere, not polite-filler.', mood: 'genuine_thanks' },
      { speaker: 'aoi_barista', jp: 'いつもありがとうございます。お気をつけて。', en: 'Thank you for coming as always. Take care.', style: 'Soft closing. The 「いつも」 carries the relationship. JP and EN: warm and brief, not lingering.', mood: 'closing_warm' },
    ],
  },
  {
    id: 'conv_00011',
    context: 'Examination room. Mei has come in worried about a recurring symptom. Dr. Saito sits down before speaking.',
    purpose: 'medical reassurance — clinical care delivered with warmth',
    ambient: 'clinic_waiting_room',
    target_vocab: ['大丈夫','心配','本当に','時間','少し','どう'],
    cast: ['saito_doctor','mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'saito_doctor', jp: 'お待たせしました。今日はどうされましたか？', en: 'Thank you for waiting. What brings you in today?', style: 'Sits down on the question — physically lowering the stakes. Even, professional, kind.', mood: 'professional_warm' },
      { speaker: 'mei_romantic', jp: 'あの…最近、ちょっと心配なことがあって。', en: 'Um… recently, there\'s been something I\'ve been a bit worried about.', style: 'Soft, careful opener. The 「あの」 is half a breath. Looks at her hands during the line.', mood: 'careful_open' },
      { speaker: 'saito_doctor', jp: 'ゆっくりで大丈夫ですよ。どんなことですか？', en: 'Take your time. What is it?', style: 'Slower than the previous line. The reassurance is given by pace, not by words alone.', mood: 'patient' },
      { speaker: 'mei_romantic', jp: '少し前から、夜、眠れない日が続いていて…', en: 'Since a little while back, there have been nights I can\'t sleep — it\'s been going on…', style: 'Trails into the second clause. Honest but small. Looks up briefly at the end.', mood: 'admitting' },
      { speaker: 'saito_doctor', jp: 'なるほど。それは本当につらいですね。', en: 'I see. That\'s genuinely difficult.', style: 'The 「なるほど」 is brief, then the warmth lands on 「本当に」. No false pity — recognition.', mood: 'recognising' },
      { speaker: 'mei_romantic', jp: 'はい…どうしたらいいか、わからなくて。', en: 'Yes… and I don\'t know what I should do.', style: 'A small inhale before the second half. The admission is the heaviest line so far.', mood: 'lost' },
      { speaker: 'saito_doctor', jp: '少し時間を取って、一緒に整理しましょう。大丈夫。', en: 'Let\'s take a bit of time and sort through this together. It\'ll be okay.', style: 'Quiet authority. The 「大丈夫」 is offered like a small object placed carefully on the desk. JP and EN: same steady kindness.', mood: 'taking_charge_kind' },
      { speaker: 'mei_romantic', jp: 'はい、お願いします。', en: 'Yes — please.', style: 'A small, real relief. Quieter than the previous lines but stronger.', mood: 'relieved_yielding' },
    ],
  },
  {
    id: 'conv_00012',
    context: 'A small police box near a station. Yuki is at the counter, slightly flustered, having lost her wallet.',
    purpose: 'small bureaucratic encounter — professional courtesy + a citizen mildly in distress',
    ambient: 'police_box',
    target_vocab: ['すみません','大丈夫','どこ','今日','時間','本当に'],
    cast: ['takeda_officer','yuki_office'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'yuki_office', jp: 'すみません、財布、なくしてしまって。', en: 'Excuse me — I\'ve lost my wallet.', style: 'Slightly out of breath. Apologetic before the request — Japanese politeness reflex. Eyes scanning the desk.', mood: 'flustered_polite' },
      { speaker: 'takeda_officer', jp: 'はい、こちらへどうぞ。落ち着いて、大丈夫です。', en: 'Yes — please, this way. Take a breath, it\'s okay.', style: 'Professional, measured. The 「落ち着いて」 is offered, not commanded. Hands gesture to a chair.', mood: 'professional_kind' },
      { speaker: 'yuki_office', jp: 'ありがとうございます。', en: 'Thank you.', style: 'Genuine, deflating a half-step from the previous line\'s tension.', mood: 'small_relief' },
      { speaker: 'takeda_officer', jp: '最後にどこで見たか、覚えていますか？', en: 'Where did you last see it — do you remember?', style: 'Calm investigative tone. Each word distinct. Pen lifted to write.', mood: 'investigating' },
      { speaker: 'yuki_office', jp: '今日のお昼、駅の近くのカフェで…多分。', en: 'Today at lunch, at a café near the station… probably.', style: 'Searching her own memory aloud. The 「多分」 honest, not evasive.', mood: 'searching' },
      { speaker: 'takeda_officer', jp: 'なるほど。少し時間をいただければ、確認します。', en: 'I see. If you give me a moment, I\'ll check.', style: 'Confidence without flourish. Pen down, picks up the phone in the voice.', mood: 'taking_action' },
      { speaker: 'yuki_office', jp: '本当に、すみません、ありがとうございます。', en: 'Really — sorry, and thank you.', style: 'Layered politeness. The two registers tumble out together — apology and gratitude both real.', mood: 'overflowing_polite' },
    ],
  },
  {
    id: 'conv_00013',
    context: 'After-class corridor at a small language school. Ren has stayed behind to ask about a particle that has been confusing him.',
    purpose: 'teacher-student instructional moment — patient explanation between adults',
    ambient: 'school_classroom',
    target_vocab: ['本当に','少し','言う','時間','大丈夫','どう'],
    cast: ['asuka_teacher','ren_uni'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'ren_uni', jp: '先生、少しだけ、いいですか？', en: 'Sensei, do you have a moment?', style: 'Hesitant opener. Stops just inside the doorway. The 「少しだけ」 hedges the imposition.', mood: 'hesitant' },
      { speaker: 'asuka_teacher', jp: 'もちろん。どうしましたか？', en: 'Of course. What\'s up?', style: 'Already turning. Warm and ready. The question opens the door fully.', mood: 'inviting' },
      { speaker: 'ren_uni', jp: '「は」と「が」の使い方が、本当によく分からなくて…', en: 'The difference between "wa" and "ga" — I genuinely can\'t get a handle on it…', style: 'A small embarrassed exhale at the end. Almost-confession of a learner stuck in the same place a long time.', mood: 'admitting_stuck' },
      { speaker: 'asuka_teacher', jp: 'よくある悩みですよ。例文で、少しずつ見ていきましょう。', en: 'That\'s a common one. Let\'s look at it step by step with examples.', style: 'Warm normalisation. The 「よくある」 takes the shame off the shelf. Then a quiet plan.', mood: 'normalising' },
      { speaker: 'ren_uni', jp: 'お時間、本当に大丈夫ですか？', en: 'Is your time really okay with this?', style: 'Checks before accepting. Polite, slightly anxious. JP and EN: don\'t hide the worry.', mood: 'double_checking' },
      { speaker: 'asuka_teacher', jp: '大丈夫です。一緒に整理しましょう。', en: 'It\'s fine. Let\'s work through it together.', style: 'Easy reassurance. The 「一緒に」 carries the message — you\'re not alone in this. Calm authority.', mood: 'settling_in' },
      { speaker: 'ren_uni', jp: 'すみません、ありがとうございます。', en: 'I\'m sorry — and thank you.', style: 'The relief leaks through the polite formula. Bows slightly inside the voice.', mood: 'grateful' },
      { speaker: 'asuka_teacher', jp: 'では、まず、この文から見てみましょうか。', en: 'Right — first, let\'s have a look at this sentence.', style: 'Pen tap on the paper in the voice. Teaching has begun. Calm, focused.', mood: 'beginning_lesson' },
    ],
  },
  {
    id: 'conv_00014',
    context: 'Friday evening. Mei and Ren on their couch, side by side, neither doing anything in particular.',
    purpose: 'quiet intimacy — the relief of doing nothing together',
    ambient: 'apartment_indoor',
    target_vocab: ['今日','大丈夫','一緒','本当に','時間','ない'],
    cast: ['mei_romantic','ren_uni'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'mei_romantic', jp: '今日、ほんと疲れた。', en: 'Today really got me.', style: 'Sinks half a foot deeper into the couch in the voice. Honest, not dramatic.', mood: 'spent' },
      { speaker: 'ren_uni', jp: '何かあった？', en: 'Did something happen?', style: 'Quiet, not interrogating. Eyes already turned toward her. The simplest version of the question.', mood: 'attentive' },
      { speaker: 'mei_romantic', jp: '何もない日だったから、余計に。', en: 'Nothing happened — that\'s the part that gets you.', style: 'A small wry laugh inside the voice. Recognising the contradiction.', mood: 'wry' },
      { speaker: 'ren_uni', jp: 'うん、それわかる。', en: 'Yeah — I get that.', style: 'Quiet agreement. Doesn\'t fix it. Just sits with it.', mood: 'sitting_with_her' },
      { speaker: 'mei_romantic', jp: '本当に何もしたくない。一緒にいてくれるだけでいい。', en: 'I really don\'t want to do anything. You being here is enough.', style: 'Soft, vulnerable, no performance. The 「だけでいい」 lands quietly real.', mood: 'gentle_honest' },
      { speaker: 'ren_uni', jp: 'いるよ。時間あるし、今日はもう何も予定ない。', en: 'I\'m right here. I\'ve got time — no plans tonight.', style: 'Steady, comforting. The plain-spoken kind of love. No flourish.', mood: 'present' },
      { speaker: 'mei_romantic', jp: 'ありがとう。…大丈夫になってきた。', en: 'Thank you. …I\'m starting to feel okay.', style: 'A slow exhale before 「大丈夫」. The recovery arrives quietly.', mood: 'recovering' },
    ],
  },
  {
    id: 'conv_00015',
    context: 'Tutoring room. Sakura has come for a Tuesday after-school lesson with her favourite teacher and is in a mood.',
    purpose: 'mid-teen frustration, teacher steady — the kind of lesson where the lesson isn\'t really the lesson',
    ambient: 'school_classroom',
    target_vocab: ['本当に','大丈夫','ない','時間','言う'],
    cast: ['sakura_teen','asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'sakura_teen', jp: '今日、ほんま無理。何もしたくないねん。', en: 'Today I\'m just — I literally can\'t. I don\'t want to do anything.', style: 'Slumps into the chair in the voice. Kansai ending. Honest in a way she\'d never admit to friends.', mood: 'flat_complaint' },
      { speaker: 'asuka_teacher', jp: 'はい。じゃあ、今日は本当に少しだけで終わりましょう。', en: 'Alright. Then let\'s really do just a little today and stop.', style: 'No fight. The agreement is the move. The 「少しだけで終わりましょう」 is a small contract being offered.', mood: 'negotiating_kind' },
      { speaker: 'sakura_teen', jp: '…マジで？', en: '…For real?', style: 'A tiny break in the slump. Suspicious that the adult capitulated this fast.', mood: 'suspicious' },
      { speaker: 'asuka_teacher', jp: 'マジで。何があったか、言いたかったら言って。言いたくなかったら、それも大丈夫。', en: 'For real. If you want to tell me what\'s up, do. If not, that\'s fine too.', style: 'Even, warm, no pressure. The door is wide open, the room is calm.', mood: 'door_open' },
      { speaker: 'sakura_teen', jp: '…別に、たいしたことちゃう。', en: '…It\'s nothing big.', style: 'Smaller than the opening line. Already cracking. JP and EN: both reduced volume.', mood: 'admitting_a_little' },
      { speaker: 'asuka_teacher', jp: 'うん。じゃあ、ここに座っとくだけでも、いいよ。', en: 'Mm. Then just sitting here is fine, too.', style: 'Quiet permission. Doesn\'t push. The 「だけでも」 is the gift.', mood: 'permission' },
      { speaker: 'sakura_teen', jp: '…ありがと。少しだけ、時間ちょうだい。', en: '…Thanks. Just give me a minute.', style: 'The 「ありがと」 unguarded for a second. The asking is the lesson today.', mood: 'unguarded' },
    ],
  },
  {
    id: 'conv_00016',
    context: 'Sunday evening. Sachiko calls her adult daughter Yumiko from her quiet house in Saitama.',
    purpose: 'maintenance call across generations — small news + the unspoken main reason (just hearing her voice)',
    ambient: 'phone_call_silent',
    target_vocab: ['今日','本当に','大丈夫','元気','時間','ありがとう','一緒'],
    cast: ['sachiko_grandma','yumiko_mom'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'sachiko_grandma', jp: 'もしもし、ゆみちゃん？今、ちょっと大丈夫？', en: 'Hello, Yumi? Got a minute right now?', style: 'Slow, melodic, the slight wobble of older speech. Uses the diminutive — has used it her whole life.', mood: 'warm_opening' },
      { speaker: 'yumiko_mom', jp: 'うん、お母さん、大丈夫だよ。どうしたの？', en: 'Yeah, Mom — I\'ve got time. What\'s up?', style: 'Sits down on the question, even though she\'s in the kitchen. Warm and lightly worried by default.', mood: 'attending' },
      { speaker: 'sachiko_grandma', jp: 'いえ、何でもないの。本当に、ただ声、聞きたかっただけ。', en: 'Oh, nothing — really, I just wanted to hear your voice.', style: 'The truth arrives gently. The 「本当に」 is small and honest. JP and EN: same easy openness.', mood: 'honest_warm' },
      { speaker: 'yumiko_mom', jp: 'お母さん、ほんと、いつでも電話していいからね。', en: 'Mom — really, you can call whenever, okay?', style: 'Voice softens half a step. The reassurance is real, layered with affection she doesn\'t usually show in this much daylight.', mood: 'soft_invitation' },
      { speaker: 'sachiko_grandma', jp: 'ありがとう、ね。ひなちゃんは元気？', en: 'Thank you, dear. Is Hina doing well?', style: 'Easy transition into family check-ins. Affectionate diminutive again.', mood: 'asking_after_family' },
      { speaker: 'yumiko_mom', jp: '元気だよ。今日もうるさいくらい。一緒に話す？', en: 'She\'s great. Loud as anything today. Want to talk to her?', style: 'Affectionate eyeroll in the voice. Already turning toward the next room.', mood: 'offering' },
      { speaker: 'sachiko_grandma', jp: 'うん、少しだけね。本当に、ありがとう。', en: 'Yes — just a little. Really — thank you.', style: 'The thank-you is for the call, the offer, and twenty years of these moments. JP and EN: keep it small.', mood: 'gentle_thanks' },
    ],
  },
  {
    id: 'conv_00017',
    context: 'A rural village in Iwate. A young visitor from Tokyo (Ren) has stopped at Tatsuya\'s small farm shop to ask directions to the local shrine.',
    purpose: 'kind rural encounter — quiet help with a side of unsolicited local pride',
    ambient: 'shrine_grounds',
    target_vocab: ['少し','本当に','時間','大丈夫','ありがとう','一番'],
    cast: ['tatsuya_country','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'ren_uni', jp: 'すみません、ちょっとお尋ねしてもいいですか？', en: 'Excuse me — may I ask you something?', style: 'Polite, slightly out of breath. Tokyo formality landing in a rural shop.', mood: 'polite_inquiry' },
      { speaker: 'tatsuya_country', jp: 'ああ、はい。どうぞ。', en: 'Ah, yes. Go ahead.', style: 'Slow, weathered voice. Three unhurried words. Looks up from what he\'s doing only after the first one.', mood: 'unhurried_open' },
      { speaker: 'ren_uni', jp: 'この近くの神社、少し迷ってしまって…', en: 'The shrine around here — I\'ve gotten a little lost…', style: 'A small embarrassed half-laugh. Holds up the phone with a faded map on it.', mood: 'sheepish' },
      { speaker: 'tatsuya_country', jp: 'ああ、神社な。歩いて、十分くらい。', en: 'Ah, the shrine. About ten minutes on foot.', style: 'Sentences arrive in pieces with comfortable air between them. The pace of someone who never rushes.', mood: 'considered' },
      { speaker: 'tatsuya_country', jp: 'この道、まっすぐ。途中で、大きい木があるから、そこを右。', en: 'This road, straight on. There\'s a big tree along the way — turn right there.', style: 'Hand gestures in the voice. Locally tested directions. Each instruction comes with a small pause.', mood: 'giving_directions' },
      { speaker: 'ren_uni', jp: '大丈夫です、わかりました。本当に、ありがとうございます。', en: 'Got it, thank you. Really, thank you.', style: 'A small bow inside the voice. The second 「ありがとう」 is the genuine one.', mood: 'genuine_thanks' },
      { speaker: 'tatsuya_country', jp: 'いいや。…ここの神社、この辺で一番、静かでいいとこだよ。', en: 'It\'s nothing. …The shrine here — quietest, best spot around.', style: 'A small unbidden gift. Pride that doesn\'t announce itself. JP and EN: same quiet conviction.', mood: 'quietly_proud' },
    ],
  },
  {
    id: 'conv_00018',
    context: 'The gate of a small Kobe apartment building, morning. A new resident (Ren) has just brought down his recycling and Mrs. Mori is, predictably, already there.',
    purpose: 'neighbourhood orientation + gossip + welcome — Kansai community contact',
    ambient: 'apartment_hallway',
    target_vocab: ['今日','本当に','大丈夫','ありがとう','時間','一緒','人'],
    cast: ['mrs_mori_neighbor','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'あ、新しい人やんね？おはようさん。', en: 'Oh — you\'re the new one, aren\'t you? Mornin\'.', style: 'Bright, instantly familiar. Kansai cadence. The 「おはようさん」 is half-greeting, half-claim of jurisdiction.', mood: 'claiming' },
      { speaker: 'ren_uni', jp: 'おはようございます。先週、引っ越してきました。', en: 'Good morning. I moved in last week.', style: 'Polite, slightly startled by the warmth. Tokyo formality meeting Kansai warmth.', mood: 'startled_polite' },
      { speaker: 'mrs_mori_neighbor', jp: 'そうそうそう。ゴミの日、わかってる？火曜と金曜やからね。', en: 'Yeah yeah yeah — you know the garbage days? Tuesdays and Fridays, okay?', style: 'Three quick agreement-syllables, then straight into useful intel. The information has been waiting.', mood: 'transmitting_intel' },
      { speaker: 'ren_uni', jp: 'はい、本当にありがとうございます。', en: 'Yes — really, thank you.', style: 'A small bow inside the voice. Adjusting his pace slightly upward to match hers.', mood: 'grateful' },
      { speaker: 'mrs_mori_neighbor', jp: 'あと、上の階の人、夜ちょっとうるさい時あるけど、いい人やから大丈夫。', en: 'Oh — the upstairs folks can be a bit loud at night sometimes, but they\'re good people, so it\'s fine.', style: 'The intel keeps coming. Pre-empts a worry he hasn\'t had yet. Affectionate about the loud upstairs.', mood: 'forewarning_warm' },
      { speaker: 'ren_uni', jp: 'はい、わかりました。', en: 'Got it.', style: 'Bemused — accepting that this is now his life. Small smile in the voice.', mood: 'bemused' },
      { speaker: 'mrs_mori_neighbor', jp: 'なんかあったら、いつでも来てな。時間あるから、私。', en: 'If anything comes up — come round any time, dear. I\'ve got nothing but time.', style: 'Warm, open. The 「時間あるから、私」 is a brag and a gift at once.', mood: 'inviting' },
      { speaker: 'ren_uni', jp: '本当に、ありがとうございます。', en: 'Really — thank you very much.', style: 'Sincere, lands a tiny bit warmer than the first thank-you. He\'s on her side of the gate now.', mood: 'won_over' },
    ],
  },
  {
    id: 'conv_00019',
    context: 'Daichi has stopped by his aunt Naoko\'s ramen shop in Osaka in the dead hour before lunch service.',
    purpose: 'aunt-nephew teasing — Kansai family roast with sincere affection underneath',
    ambient: 'busy_restaurant',
    target_vocab: ['本当に','どう','今','時間','一緒','言う','ない'],
    cast: ['naoko_aunt','daichi_kansai'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'naoko_aunt', jp: 'あんた、また髪伸びたんちゃう？', en: 'Hey — your hair\'s gotten long again, hasn\'t it?', style: 'Looks up from the counter. Loud, immediate, no greeting. The Kansai roast is the greeting.', mood: 'opening_roast' },
      { speaker: 'daichi_kansai', jp: 'おばちゃん、来た瞬間それかいな。', en: 'Oba-chan, that\'s the first thing you say to me?', style: 'Mock-offended. Sits down anyway. Voice already laughing.', mood: 'mock_offended' },
      { speaker: 'naoko_aunt', jp: '本当のこと言うてるだけや。今、彼女おらんやろ、それで。', en: 'Just telling the truth. You\'ve got no girlfriend right now — that\'s why.', style: 'Brassy comic logic. Wipes the counter without looking at him. The diagnosis is rapid.', mood: 'diagnosing' },
      { speaker: 'daichi_kansai', jp: 'なんでわかんねん。', en: 'How do you even know that?', style: 'Almost laughing. Genuinely surprised at the accuracy. JP and EN: both half-laugh.', mood: 'caught' },
      { speaker: 'naoko_aunt', jp: '見たらわかるわ。…で、どう？元気にしてんの？', en: 'I can just tell. …Anyway. How\'re you doing? Holding up?', style: 'Pivot mid-line. The roast was the door — the real question is the room. Voice drops half a step.', mood: 'pivot_real' },
      { speaker: 'daichi_kansai', jp: 'まあな。仕事は忙しいけど、大丈夫。', en: 'Mm — well. Work\'s busy but I\'m okay.', style: 'Quieter now. Honest under the teasing because she earned it.', mood: 'honest_quiet' },
      { speaker: 'naoko_aunt', jp: 'ほな、ラーメン食べてき。時間あるやろ。', en: 'Then have some ramen before you go. You\'ve got the time, right?', style: 'Already pulling a bowl down. The offer isn\'t a question.', mood: 'feeding_him' },
    ],
  },
  {
    id: 'conv_00020',
    context: 'Coastal Fukuoka, late afternoon. Eight-year-old Hina is visiting grandpa Goro and has asked him to tell her a story about when he was young.',
    purpose: 'oral history — grandfather telling, granddaughter listening',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','一番','時間','一緒','ない','人','言う','見る'],
    cast: ['goro_grandpa','hina_child'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hina_child', jp: 'おじいちゃん、お話して。一番面白いの。', en: 'Grandpa, tell me a story. The most interesting one.', style: 'Sits down very close. The demand is delivered as if she\'s pre-paid for it.', mood: 'demanding_kid' },
      { speaker: 'goro_grandpa', jp: '一番、なあ。…むかし、おじいちゃんが、お前くらいの時にな。', en: 'The most interesting, eh. …Long ago, when grandpa was about your age.', style: 'Slow, gravelly. Each clause arrives separately. Kyushu warmth. Looks somewhere far away during the second sentence.', mood: 'settling_in' },
      { speaker: 'hina_child', jp: 'うん。', en: 'Mm.', style: 'One syllable, all attention. She has folded herself smaller.', mood: 'fully_listening' },
      { speaker: 'goro_grandpa', jp: '一人で、海まで歩いてったんよ。誰にも言わんで。', en: 'I walked all the way to the sea by myself. Didn\'t tell anyone.', style: 'A small forbidden gleam in the voice. The 「言わんで」 is Kyushu confessional charm.', mood: 'sharing_secret' },
      { speaker: 'hina_child', jp: '本当に？一人で？', en: 'Really? All alone?', style: 'Pure eight-year-old astonishment. The 「本当に？」 is half a question, half a request to repeat it.', mood: 'astonished' },
      { speaker: 'goro_grandpa', jp: '本当に、一人でな。お母さんに、後で本当に怒られた。', en: 'Really, all alone. Got told off by my mother good and proper afterward.', style: 'Half-laugh inside the gravel. The memory is amused.', mood: 'amused_remembering' },
      { speaker: 'hina_child', jp: '怖くなかった？', en: 'Weren\'t you scared?', style: 'A small worried lift. She\'s thinking about it as if it could happen to her.', mood: 'worried_curious' },
      { speaker: 'goro_grandpa', jp: '怖かったよ。最初な。でも、海、見たら、なんも怖くなくなった。', en: 'I was. At first. But once I saw the sea — none of it felt scary anymore.', style: 'Slowest line yet. The 「見たら」 is the centre of the story. Eyes still somewhere far away.', mood: 'centre_of_story' },
      { speaker: 'hina_child', jp: 'すごい。…ひなも、いつか一緒に見たい。', en: 'Wow. …I want to see it together someday too.', style: 'Small, warm. The 「一緒に」 is the gift she\'s giving back to him.', mood: 'gentle_offering' },
      { speaker: 'goro_grandpa', jp: 'よし。じゃあ、時間ある時、二人で行こう。', en: 'Alright. When there\'s time, we\'ll go — the two of us.', style: 'Quiet promise. Both clauses spoken at the same patient pace as the rest of the story. JP and EN: same settled warmth.', mood: 'making_promise' },
    ],
  },
  {
    id: 'conv_00021',
    context: 'A weekday evening. Hiroshi calls Yuki\'s mobile from the office — late, unusual. She answers from her apartment.',
    purpose: 'unusual after-hours boss call — professional + a small wrinkle of real concern',
    ambient: 'phone_call_silent',
    target_vocab: ['本当に','時間','大丈夫','明日','すみません','少し'],
    cast: ['hiroshi_boss','yuki_office'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hiroshi_boss', jp: '田中さん、夜遅くにすみません。少しだけ、お時間いいですか。', en: 'Ms. Tanaka — sorry to call so late. Could I have a moment?', style: 'Professional, controlled, slightly slower than the day-tone. The apology arrives before the request.', mood: 'professional_after_hours' },
      { speaker: 'yuki_office', jp: 'はい、大丈夫です。どうかされましたか？', en: 'Yes, that\'s fine. Is something the matter?', style: 'Already half-standing. Voice steady, not panicked. The instinct to be useful overrides everything else.', mood: 'attending' },
      { speaker: 'hiroshi_boss', jp: '明日の資料、一点だけ確認させてください。', en: 'About tomorrow\'s materials — let me confirm just one point.', style: 'Drops to pure business. The phrasing 「一点だけ」 narrows the scope kindly.', mood: 'focusing' },
      { speaker: 'yuki_office', jp: 'はい、どの部分でしょうか。', en: 'Yes, which part?', style: 'Already opening the document in the voice.', mood: 'ready' },
      { speaker: 'hiroshi_boss', jp: '十二ページの数字、本当に最新のものですよね。', en: 'The figure on page twelve — that\'s genuinely the latest, correct?', style: 'The 「本当に」 is doing double duty: confirming the fact, and acknowledging that he\'s asking late. Even.', mood: 'verifying' },
      { speaker: 'yuki_office', jp: 'はい、確認しました。間違いないです。', en: 'Yes — I checked. There\'s no mistake.', style: 'Calm certainty. Voice steadies further. The line that ends the worry on both ends.', mood: 'settling_it' },
    ],
  },
  {
    id: 'conv_00022',
    context: 'Late at the izakaya. Two pints in. Daichi is mid-story; Kenji is laughing.',
    purpose: 'narrative + banter — long form storytelling between close friends',
    ambient: 'izakaya_evening',
    target_vocab: ['本当に','人','時間','言う','ない','一番','見る','大丈夫'],
    cast: ['daichi_kansai','kenji_office'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'daichi_kansai', jp: 'で、その人な、本当に、まったく動かんかってん。', en: 'So this guy, right — he literally wouldn\'t budge an inch.', style: 'Mid-story, beer in hand, two-thirds of the way through. The 「な」 is the pin that holds the listener.', mood: 'mid_narration' },
      { speaker: 'kenji_office', jp: 'うそやろ。', en: 'No way.', style: 'Half-laughing already. Borrows the Kansai for one word.', mood: 'amused' },
      { speaker: 'daichi_kansai', jp: '本当やって。十分も二十分も、ずっと立ったまま。', en: 'I\'m telling you. Ten, twenty minutes — just standing there.', style: 'Slaps the table lightly in the voice. The escalation is part of the bit.', mood: 'escalating' },
      { speaker: 'kenji_office', jp: 'なんで誰も、声かけへんかったん？', en: 'Why didn\'t anyone say anything to him?', style: 'Earnest middle of a story. The straight-man line.', mood: 'straight_man' },
      { speaker: 'daichi_kansai', jp: 'それやねん。誰も。一人もな。', en: 'That\'s the thing. No one. Not a single person.', style: 'Voice drops half a step for the punchline run-up. Kansai musicality.', mood: 'punchline_setup' },
      { speaker: 'kenji_office', jp: 'みんな見て見ぬふり、ってこと？', en: 'Everyone pretending not to see him, you mean?', style: 'The straight-man does the work. Smile in the voice.', mood: 'helping_setup' },
      { speaker: 'daichi_kansai', jp: 'まさにそれ。日本一の見て見ぬふり大会。', en: 'Exactly that. Japan\'s number-one look-the-other-way championship.', style: 'Full Kansai grin. Big lift on 「日本一」.', mood: 'punchline' },
      { speaker: 'kenji_office', jp: '(笑) もう無理、それ。', en: '(laughs) Stop — that\'s killing me.', style: 'Genuine laugh, head back. The kind of laugh that\'s been waiting since the start of the story.', mood: 'cracking_up' },
      { speaker: 'daichi_kansai', jp: 'で、結局な、おじいちゃんが一人来て、「大丈夫？」って言ったら、その人やっと動いた。', en: 'And then — finally — one old guy comes up and goes "you okay?" — and only then does the guy move.', style: 'Coda mode. Slows down deliberately. The old guy is the hero of the story.', mood: 'coda' },
      { speaker: 'kenji_office', jp: 'いい話やん、それ。', en: 'That\'s a good one, actually.', style: 'Quieter, more thoughtful. The laugh has settled into something gentler.', mood: 'reflective' },
      { speaker: 'daichi_kansai', jp: 'やろ。…日本、本当におかしいけど、ええ国やわ。', en: 'Right? …Japan\'s really weird, but it\'s a good place.', style: 'Honest contradiction. The kind of sentence two pints in. Affectionate.', mood: 'sentimental_truthful' },
      { speaker: 'kenji_office', jp: 'うん、わかる。もう一杯いく？', en: 'Yeah — I get it. One more?', style: 'Soft closing. Already lifting his empty glass in the voice.', mood: 'closing_warm' },
    ],
  },
  {
    id: 'conv_00023',
    context: 'Sunday afternoon. Riku, fifteen, has been hiding in his room. Yumiko knocks and lets herself in.',
    purpose: 'mother-teen check-in — careful access to a closed room',
    ambient: 'apartment_indoor',
    target_vocab: ['今日','どう','大丈夫','本当に','少し','時間','ない'],
    cast: ['yumiko_mom','riku_teen'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (in-chat batch_001)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'yumiko_mom', jp: 'ちょっと、いい？', en: 'You got a sec?', style: 'Knocks twice in the voice. Comes in two-thirds of a step. Doesn\'t step in fully — waits for permission post hoc.', mood: 'careful_entry' },
      { speaker: 'riku_teen', jp: 'ん。', en: 'Mn.', style: 'Single syllable. Doesn\'t look up. Voice still cracking. Not unfriendly — defended.', mood: 'guarded' },
      { speaker: 'yumiko_mom', jp: '今日、ずっと部屋いるね。大丈夫？', en: 'You\'ve been in here all day. You okay?', style: 'Not accusing — observing. The 「大丈夫？」 is offered like a chair, not a key.', mood: 'observing' },
      { speaker: 'riku_teen', jp: '別に、なんもない。', en: 'It\'s nothing.', style: 'Reflexive teen deflection. But the volume is conversational — he could be drawn out.', mood: 'deflecting' },
      { speaker: 'yumiko_mom', jp: 'うん。…言いたくなかったら、言わなくていいよ。', en: 'Mm. …If you don\'t want to talk, you don\'t have to.', style: 'Sits on the edge of his bed in the voice. The permission is the door.', mood: 'permission' },
      { speaker: 'riku_teen', jp: '…ちょっと、面倒なことあって。', en: '…There\'s just something annoying going on.', style: 'A small concession. The 「ちょっと」 is a half-open door. JP and EN: same small concession.', mood: 'tiny_open' },
      { speaker: 'yumiko_mom', jp: 'そっか。時間あるから、いつでも。本当に。', en: 'Got it. I\'ve got time — whenever. Really.', style: 'No pressure. The 「本当に」 lands like a small genuine offer, not a sales close.', mood: 'closing_open' },
      { speaker: 'riku_teen', jp: 'うん。…ありがと。', en: 'Yeah. …Thanks.', style: 'Eyes still on his lap, but the word landed. Slightly quieter than the other lines.', mood: 'small_thanks' },
    ],
  },
];

// ─── Write all to disk ──────────────────────────────────────────────────────

for (const conv of CONVERSATIONS) {
  const outPath = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(outPath, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log(`wrote ${CONVERSATIONS.length} conversation(s) to ${OUT_DIR}`);
