// scripts/batches/batch_004.mjs
// Batch 4: conv_00064 .. conv_00083.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
fs.mkdirSync(OUT_DIR, { recursive: true });
const NOW = new Date().toISOString();
const META = (row) => ({ generated_by: 'claude-opus-4-7 (batch_004)', generated_at: NOW, source_plan_row: row || '' });

const CONVERSATIONS = [
  {
    id: 'conv_00064',
    context: 'Outside the koban. Hina has been "playing with the fountain pen she found." Officer Takeda is on patrol and is the only adult around.',
    purpose: 'gentle authority + kid logic — officer doing the smallest possible enforcement',
    ambient: 'police_box',
    target_vocab: ['本当に','大丈夫','見る','ない','ありがとう'],
    cast: ['takeda_officer','hina_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'takeda_officer', jp: 'こんにちは。それ、見せてもらえる？', en: 'Hello there. Can you let me see that?', style: 'Crouches down to her level in the voice. Calm, low, friendly.', mood: 'crouching_friendly' },
      { speaker: 'hina_child', jp: 'え、これ？拾った！', en: 'Eh, this? I found it!', style: 'Holds it up proudly. Eight-year-old certainty about finder rights.', mood: 'proud_kid' },
      { speaker: 'takeda_officer', jp: 'そっか。本当に拾ったの？落とした人、いるかも。', en: 'I see. Really, you found it? Someone might have dropped it.', style: 'No accusation. Plants the seed gently.', mood: 'gentle_seed' },
      { speaker: 'hina_child', jp: '…うん。たぶん。', en: '…Yeah. Probably.', style: 'A small reality-check. Voice loses half its certainty.', mood: 'losing_certainty' },
      { speaker: 'takeda_officer', jp: 'じゃあ、一緒に交番に預けようか。', en: 'Then — shall we hand it in at the koban, together?', style: 'Hand offered in the voice. Not taking it from her.', mood: 'hand_offered' },
      { speaker: 'hina_child', jp: 'えー、私のじゃないの？', en: 'Whaaa — it\'s not mine?', style: 'Half-protest, half-already-knowing. Pout in the voice.', mood: 'pouty_resigned' },
      { speaker: 'takeda_officer', jp: '届けたら、もしかして、ありがとうって言ってくれる人いるかも。', en: 'If you turn it in, someone might come thank you, you know.', style: 'Pitches it as a small adventure.', mood: 'reframing_adventure' },
    ],
  },
  {
    id: 'conv_00065',
    context: 'Mei is home with a cold. The knock at the door is Mrs. Mori with a small pot of soup, uninvited and unstoppable.',
    purpose: 'neighborhood care — Kansai warmth steamrollers Tokyo politeness',
    ambient: 'apartment_hallway',
    target_vocab: ['本当に','大丈夫','元気','今','時間','ありがとう'],
    cast: ['mrs_mori_neighbor','mei_romantic'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'メイちゃん、大丈夫？スープ持ってきた。', en: 'Mei-chan — you alright? Brought soup.', style: 'Loud, mid-volume Kansai. Already holding out the pot in the voice.', mood: 'pouncing_warm' },
      { speaker: 'mei_romantic', jp: 'えっ…なんでわかったんですか？', en: 'Wait… how did you know?', style: 'Surprised, half-laughing. Voice slightly hoarse.', mood: 'hoarse_surprise' },
      { speaker: 'mrs_mori_neighbor', jp: '昨日、咳しとった声、聞こえた。', en: 'Heard your coughing voice yesterday.', style: 'Said as if it were obvious. The neighborhood-spy energy.', mood: 'matter_of_fact' },
      { speaker: 'mei_romantic', jp: '本当に、ありがとうございます。お時間…', en: 'Really — thank you so much. Your time…', style: 'A bow inside the voice. Politely worried about the imposition.', mood: 'apologetic_grateful' },
      { speaker: 'mrs_mori_neighbor', jp: 'ええの、ええの。寝なはれ、元気になるまで。', en: 'It\'s fine, fine. Sleep — until you\'re well.', style: 'Brisk dismissal of any guilt. Already turning to leave.', mood: 'dismissive_kind' },
      { speaker: 'mei_romantic', jp: 'はい…本当にすみません。', en: 'Yes… really, I\'m sorry.', style: 'Half-tear in the voice. The unexpected care landing.', mood: 'landing_care' },
      { speaker: 'mrs_mori_neighbor', jp: '謝らんでええって。今、休む時間。', en: 'No need to apologise. It\'s rest-time, now.', style: 'A small finger-wag in the voice. Affectionate.', mood: 'affectionate_scolding' },
      { speaker: 'mei_romantic', jp: 'ありがとうございます…本当に。', en: 'Thank you… truly.', style: 'A small grateful exhale. Voice softer than the first thank-you.', mood: 'softer_thanks' },
      { speaker: 'mrs_mori_neighbor', jp: 'また明日、見にくるわ。', en: 'I\'ll check on you tomorrow.', style: 'A small claim and a small promise. Steps back from the door in the voice.', mood: 'small_claim' },
    ],
  },
  {
    id: 'conv_00066',
    context: 'Dr. Saito\'s daughter (Sakura, here playing the role of Saito\'s teen) has come into her mother\'s clinic after school because she didn\'t know where else to go.',
    purpose: 'mother-daughter doctor-patient hybrid — Saito switches registers mid-scene',
    ambient: 'clinic_waiting_room',
    target_vocab: ['本当に','大丈夫','今','時間','心配','ない'],
    cast: ['saito_doctor','sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'お母さん、ちょっといい？', en: 'Mom — got a sec?', style: 'A whisper in the clinic. Half-Kansai, half-careful at her mother\'s workplace.', mood: 'careful_whisper' },
      { speaker: 'saito_doctor', jp: 'さくら？…どうしたの、こんな時間に。', en: 'Sakura? …What is it — at this hour?', style: 'Doctor voice cracks half a step into mother voice. Stands.', mood: 'mother_breaking_through' },
      { speaker: 'sakura_teen', jp: 'なんもない。本当に。ただ、ちょっと…', en: 'It\'s nothing. Really. Just — a little…', style: 'Reflexive teen deflection. Eyes on the floor.', mood: 'reflexive_deflect' },
      { speaker: 'saito_doctor', jp: '座って。ちゃんと診るから、座って。', en: 'Sit. I\'ll check you properly — sit.', style: 'Practiced doctor-tone covering real worry.', mood: 'practiced_worried' },
      { speaker: 'sakura_teen', jp: 'お母さん、診察ちゃう。話。', en: 'Mom — not an exam. Talk.', style: 'A small honest correction. Voice quieter.', mood: 'small_correction' },
      { speaker: 'saito_doctor', jp: '…そっか。じゃ、コーヒー、淹れる。', en: '…I see. Then — coffee. I\'ll make some.', style: 'A full pivot. Removes the white coat in the voice.', mood: 'full_pivot' },
      { speaker: 'sakura_teen', jp: 'ありがとう。…本当に、心配かけたくなかってん。', en: 'Thanks. …Really — I didn\'t want to worry you.', style: 'Honest, voice small. Kansai ending.', mood: 'honest_small' },
      { speaker: 'saito_doctor', jp: '心配は、私の仕事。母の方の仕事。', en: 'Worrying — that\'s my job. The mom-side job.', style: 'A small line that does a lot. Voice warm.', mood: 'warm_line' },
      { speaker: 'sakura_teen', jp: '…うん。', en: '…Mm.', style: 'A relieved exhale audible. Sits down properly.', mood: 'relieved_sitting' },
      { speaker: 'saito_doctor', jp: '時間ある。今日は、もう仕事ない。', en: 'I\'ve got time. No more work today.', style: 'A small lie of generosity. Closes the laptop in the voice.', mood: 'generous_lie' },
      { speaker: 'sakura_teen', jp: 'ありがとう、お母さん。本当に。', en: 'Thank you, Mom. Really.', style: 'The whole afternoon condensed. Voice steady.', mood: 'condensed_thanks' },
    ],
  },
  {
    id: 'conv_00067',
    context: '9pm. Hiroshi (the boss) has called Kenji back to the office. A client crisis has hit and someone is going to have to fix it overnight.',
    purpose: 'workplace urgency — boss asking subordinate to take a hit, calmly',
    ambient: 'quiet_office',
    target_vocab: ['本当に','時間','今','明日','大変','大丈夫','一緒','仕事'],
    cast: ['hiroshi_boss','kenji_office'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '佐藤くん、夜遅くにすまない。', en: 'Sato-kun — sorry to call you back so late.', style: 'Composed but warmer than his daytime voice. Real apology underneath.', mood: 'composed_apologetic' },
      { speaker: 'kenji_office', jp: 'いえ、大丈夫です。何ですか？', en: 'No — it\'s fine. What is it?', style: 'Bag still on shoulder. Voice neutral, professional.', mood: 'professional_neutral' },
      { speaker: 'hiroshi_boss', jp: 'クライアントの件。明日朝までに、修正が必要だ。', en: 'The client matter. Needs fixing by tomorrow morning.', style: 'Plain, no extra weight. The information first.', mood: 'plain_info' },
      { speaker: 'kenji_office', jp: '…どのくらいの修正ですか？', en: '…How big a fix?', style: 'Sits down in the voice. Calculating.', mood: 'calculating' },
      { speaker: 'hiroshi_boss', jp: '正直、大きい。本当に申し訳ない。', en: 'Honestly — big. I\'m truly sorry.', style: 'The 「本当に」 rare from this man. Sincere.', mood: 'rare_sincere' },
      { speaker: 'kenji_office', jp: 'わかりました。私、やります。', en: 'Understood. I\'ll do it.', style: 'Quiet professional commitment. No theatre.', mood: 'commitment' },
      { speaker: 'hiroshi_boss', jp: '一緒にやる。私も残る。', en: 'Together. I\'m staying too.', style: 'A small statement that changes the conversation entirely.', mood: 'changing_things' },
      { speaker: 'kenji_office', jp: '…部長も？本当にいいんですか。', en: '…You too, sir? Really, is that alright?', style: 'Genuinely surprised. The first real human note from him in the scene.', mood: 'genuinely_surprised' },
      { speaker: 'hiroshi_boss', jp: '私が頼んだ仕事だ。当然だろう。', en: 'It\'s work I asked of you. Of course.', style: 'Plain, firm. Self-evident logic, by his code.', mood: 'firm_code' },
      { speaker: 'kenji_office', jp: 'ありがとうございます。…正直、助かります。', en: 'Thank you. …Honestly — that helps.', style: 'A small unguarded line. Bag finally set down in the voice.', mood: 'small_unguarded' },
      { speaker: 'hiroshi_boss', jp: 'コーヒー淹れた。…時間、節約しよう。', en: 'I\'ve made coffee. …Let\'s save time.', style: 'A small practical kindness covering a larger one.', mood: 'practical_cover' },
      { speaker: 'kenji_office', jp: 'はい。…大変ですけど、なんとかなる。', en: 'Yes. …It\'s a lot, but we\'ll manage.', style: 'Rolling sleeves up in the voice. Quietly determined.', mood: 'rolling_up' },
      { speaker: 'hiroshi_boss', jp: 'なるさ。明日の朝、笑える。', en: 'We will. We\'ll be laughing tomorrow morning.', style: 'A small uncharacteristic promise. Voice slightly warmer.', mood: 'uncharacteristic_warm' },
    ],
  },
  {
    id: 'conv_00068',
    context: 'A small classroom show-and-tell. Sho stands at the front holding a rock he\'s very proud of. Asuka — visiting his class today — is patient and curious.',
    purpose: 'tiny classroom moment — shy kid given an audience by a teacher',
    ambient: 'school_classroom',
    target_vocab: ['本当に','見る','面白い','どこ','大切','ありがとう'],
    cast: ['sho_child','asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'しょうくん、その石、見せて？', en: 'Sho-kun — can I see that rock?', style: 'Crouches to his level. Voice warm, unhurried.', mood: 'warm_crouch' },
      { speaker: 'sho_child', jp: '…うん。', en: '…Mm.', style: 'Holds it out with both hands, careful. Eyes on the rock, not her.', mood: 'careful_holding' },
      { speaker: 'asuka_teacher', jp: 'うわ、本当にきれい。どこで見つけたの？', en: 'Wow — really pretty. Where did you find it?', style: 'A real teacher-delight. Not exaggerated; genuine.', mood: 'genuine_delight' },
      { speaker: 'sho_child', jp: 'ええと…公園の池の近く。', en: 'Um… by the pond at the park.', style: 'A small voice gaining confidence as he speaks.', mood: 'gaining_voice' },
      { speaker: 'asuka_teacher', jp: 'いいところ知ってるね。これ、面白い色してる。', en: 'You know good places. This one\'s got an interesting color.', style: 'Slight emphasis on 「面白い」. Treats his find with respect.', mood: 'respectful_curious' },
      { speaker: 'sho_child', jp: '大切なやつ。家に、たくさんある。', en: 'It\'s an important one. I\'ve got lots at home.', style: 'A proud full sentence — longest one all day.', mood: 'proud_full' },
      { speaker: 'asuka_teacher', jp: 'コレクター、すごいね。次、見せてくれる？', en: 'A collector — that\'s impressive. Show me more next time?', style: 'A small bow inside the voice. Invitation as compliment.', mood: 'invitation_compliment' },
      { speaker: 'sho_child', jp: 'うん…ありがとう、先生。', en: 'Yeah… thanks, sensei.', style: 'A small unguarded line. Pleased.', mood: 'unguarded_pleased' },
    ],
  },
  {
    id: 'conv_00069',
    context: 'Conference room, 11am. Daichi has come in to formally tell Hiroshi he\'s leaving the company. Daichi has known Hiroshi for years; the formality is real but covers warmth.',
    purpose: 'resignation conversation — Kansai casual energy meets formal boss register, mutual respect underneath',
    ambient: 'office_meeting_room',
    target_vocab: ['本当に','時間','今','仕事','大変','ありがとう'],
    cast: ['daichi_kansai','hiroshi_boss'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'お時間いただいて、ありがとうございます。', en: 'Thank you for making the time.', style: 'A small full bow inside the voice. Drops Kansai for the formal opener.', mood: 'formal_opener' },
      { speaker: 'hiroshi_boss', jp: 'いえ、こちらこそ。座って。', en: 'Not at all. Sit.', style: 'Composed, slightly slower than usual. Already half-knows.', mood: 'composed_knowing' },
      { speaker: 'daichi_kansai', jp: '実は、来月で、会社を辞めることに。', en: 'The truth is — I\'m leaving the company at the end of next month.', style: 'A small breath. Sentence said out loud after weeks of rehearsal.', mood: 'rehearsed_release' },
      { speaker: 'hiroshi_boss', jp: '…そうか。覚悟はしていた。', en: '…I see. I had a feeling.', style: 'A small acknowledgment without surprise.', mood: 'unsurprised' },
      { speaker: 'daichi_kansai', jp: '本当に、長い間、お世話になりました。', en: 'Truly — thank you for everything, all this time.', style: 'A real bow audible. Voice drops half a step.', mood: 'real_bow' },
      { speaker: 'hiroshi_boss', jp: '理由、聞いてもいいか。', en: 'May I ask why.', style: 'Plain, not investigative. The right of a boss-friend.', mood: 'plain_friend' },
      { speaker: 'daichi_kansai', jp: '…大阪、帰る。母が、ちょっと体悪くて。', en: '…Going back to Osaka. My mom\'s not doing well.', style: 'A small private answer. The Kansai cadence returns half a step.', mood: 'returning_kansai' },
      { speaker: 'hiroshi_boss', jp: 'それは、大変だな。本当に。', en: 'That — is hard. Truly.', style: 'A line said person-to-person, not boss-to-employee.', mood: 'person_to_person' },
      { speaker: 'daichi_kansai', jp: 'ありがとうございます。…正直、寂しいです。', en: 'Thank you. …Honestly — I\'ll miss this.', style: 'Half-laugh through a small lump. Real.', mood: 'real_lump' },
      { speaker: 'hiroshi_boss', jp: '私もだ。…ま、辞める前に、一度飲もう。', en: 'So will I. …Before you go — let\'s drink, once.', style: 'A small unguarded line from him. Rare.', mood: 'rare_unguarded' },
      { speaker: 'daichi_kansai', jp: 'ぜひ。本当に、ぜひ。', en: 'Absolutely. Truly — absolutely.', style: 'Big Kansai smile audible. The pressure released.', mood: 'kansai_grin' },
      { speaker: 'hiroshi_boss', jp: '時間、私が合わせる。教えて。', en: 'I\'ll match my schedule to yours. Let me know.', style: 'A small command-disguised-as-gift. Warm.', mood: 'command_gift' },
    ],
  },
  {
    id: 'conv_00070',
    context: 'A weekend morning at Aoi\'s café. Ryosuke comes in with his five-year-old son after a long walk; the kid is asleep in the carrier.',
    purpose: 'tiny phatic service moment — kindness from one tired adult to another',
    ambient: 'cafe_morning',
    target_vocab: ['本当に','今日','子供','大丈夫','ありがとう'],
    cast: ['aoi_barista','ryosuke_dad'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'いらっしゃいませ。…うわ、寝てる、寝てる。', en: 'Welcome — oh wow, asleep, asleep.', style: 'A delighted whisper. Voice instantly half a step quieter for the kid.', mood: 'delighted_whisper' },
      { speaker: 'ryosuke_dad', jp: '本当に、ようやく。今日、二時間散歩したから。', en: 'Yeah — finally. Two hours of walking today.', style: 'Quiet, half-laughing through fatigue. Eyes still half-soft.', mood: 'tired_laughing' },
      { speaker: 'aoi_barista', jp: 'お父さん、お疲れさまです。ホット、いつもの？', en: 'Dad, you\'ve earned it. Hot one — the usual?', style: 'A small smile audible. Already moving to the espresso machine.', mood: 'small_smile' },
      { speaker: 'ryosuke_dad', jp: 'はい、ぜひ。本当に、いつもありがとう。', en: 'Yes please. Really, thank you as always.', style: 'A real thank-you. Half-leans on the counter in the voice.', mood: 'real_leaning' },
      { speaker: 'aoi_barista', jp: 'お子さん、おいくつでしたっけ？', en: 'How old is he again?', style: 'A real follow-up question. The relationship-customer dynamic.', mood: 'real_followup' },
      { speaker: 'ryosuke_dad', jp: '五歳。…一日が三十時間あったらと、毎日思う。', en: 'Five. …Every day I wish there were thirty hours.', style: 'A small honest joke. Real fatigue under it.', mood: 'honest_joke' },
      { speaker: 'aoi_barista', jp: '(small laugh)わかります。…大丈夫、これ、私のおごり。', en: '(small laugh) I get that. …It\'s alright — this one\'s on me.', style: 'A small generosity. Slides the cup over without ceremony.', mood: 'small_generosity' },
    ],
  },
  {
    id: 'conv_00071',
    context: 'A small bar. Yuki and Ren have been set up by a mutual friend — first time meeting. Both shy. Both trying.',
    purpose: 'first-date awkward — two reserved people, building it carefully',
    ambient: 'bar_evening',
    target_vocab: ['本当に','今日','時間','大丈夫','どう','好き','少し'],
    cast: ['yuki_office','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'えっと…はじめまして。レンです。', en: 'Um… nice to meet you. I\'m Ren.', style: 'Half-bows in the voice. The 「えっと」 is half a breath.', mood: 'half_bow' },
      { speaker: 'yuki_office', jp: 'こちらこそ、ゆきです。…緊張、しちゃってる。', en: 'Likewise — I\'m Yuki. …I\'m a bit nervous.', style: 'A small honest laugh. Voice slightly higher than usual.', mood: 'honest_nervous' },
      { speaker: 'ren_uni', jp: '私も。本当に、めっちゃ。', en: 'Me too. Like — really.', style: 'A small relieved laugh, mid-Kansai-emphasis. Both relax half a step.', mood: 'relieved_laugh' },
      { speaker: 'yuki_office', jp: '(small laugh) よかった、私だけじゃなくて。', en: '(small laugh) Glad it\'s not just me.', style: 'A real laugh. The room got smaller by half.', mood: 'real_laugh' },
      { speaker: 'ren_uni', jp: 'お仕事、何やってるんでしたっけ？', en: 'What was it you do, again?', style: 'A safe start. Voice carefully even.', mood: 'safe_start' },
      { speaker: 'yuki_office', jp: 'プロジェクト調整、みたいなやつです。地味です。', en: 'Project coordinator, sort of. It\'s pretty plain.', style: 'Self-deprecating but real. A small smile.', mood: 'self_deprecating' },
      { speaker: 'ren_uni', jp: '地味じゃないですよ。私、本当に、苦手なやつだから尊敬。', en: 'Not plain at all. That kind of thing — I\'m terrible at it, so I respect it.', style: 'A genuine compliment. Voice steady.', mood: 'genuine_compliment' },
      { speaker: 'yuki_office', jp: 'ありがとうございます。…レンさんは？', en: 'Thank you. …And you, Ren-san?', style: 'A small blush audible. Turns the question back.', mood: 'small_blush' },
      { speaker: 'ren_uni', jp: '言語学。大学院。論文書いてる、毎日。', en: 'Linguistics. Grad school. Writing my thesis, every day.', style: 'A small wry laugh. Real.', mood: 'wry_real' },
      { speaker: 'yuki_office', jp: 'えー、すごい。難しそう。', en: 'Whaa — that\'s impressive. Sounds hard.', style: 'A real impressed lift. Drops a half-step of formality.', mood: 'real_impressed' },
      { speaker: 'ren_uni', jp: '毎日苦しんでます。本当に。', en: 'Every day I suffer. Really.', style: 'A half-laughing confession. Genuine.', mood: 'laughing_confession' },
      { speaker: 'yuki_office', jp: 'お酒、もう一杯どう？少し気が楽になるかも。', en: 'How about another drink? Might loosen things up.', style: 'A small kind initiative. Voice steadier than the opener.', mood: 'kind_initiative' },
      { speaker: 'ren_uni', jp: 'はい、ぜひ。…今日、来てよかった。', en: 'Yes — please. …Glad I came tonight.', style: 'A small unguarded line. Real.', mood: 'unguarded_real' },
      { speaker: 'yuki_office', jp: '…私も。本当に。', en: '…Me too. Really.', style: 'A small returning gift. Voice quieter, settled.', mood: 'returning_gift' },
    ],
  },
  {
    id: 'conv_00072',
    context: 'A Kyushu coastal road. Ren is lost (visiting from Tokyo); Goro, walking home from the pier, intercepts him.',
    purpose: 'incidental rural help — old man cuts through tourist politeness',
    ambient: 'city_street_day',
    target_vocab: ['本当に','すみません','どこ','見る','時間'],
    cast: ['goro_grandpa','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'すみません、ちょっと道、お聞きしても…', en: 'Excuse me — could I ask for directions…', style: 'Polite city register, slight bow in the voice.', mood: 'polite_city' },
      { speaker: 'goro_grandpa', jp: 'ん？どこ行きたいんね。', en: 'Eh? Where do you wanna go?', style: 'Kyushu cadence, no preamble. Direct.', mood: 'direct_kyushu' },
      { speaker: 'ren_uni', jp: '神社、なんですけど…地図、わかりにくくて。', en: 'A shrine — but the map is hard to read.', style: 'Half-laughs at his own helplessness.', mood: 'helpless_laugh' },
      { speaker: 'goro_grandpa', jp: 'ああ、あれな。本当にわかりにくいわ、あの地図。', en: 'Ah, that one — that map\'s genuinely confusing.', style: 'Half-grins at the kid\'s plight. Sympathetic without ceremony.', mood: 'sympathetic_grin' },
      { speaker: 'ren_uni', jp: '本当に、すみません。', en: 'Really — sorry to bother you.', style: 'Reflexive apology. Half-bow inside the voice.', mood: 'reflexive_apology' },
      { speaker: 'goro_grandpa', jp: 'いいから。あっち。坂の上、見える？', en: 'Don\'t worry. Over there — up the slope, you see it?', style: 'Points with his chin in the voice. Kyushu economy.', mood: 'kyushu_pointing' },
      { speaker: 'ren_uni', jp: 'はい、見えます。本当にありがとうございます。', en: 'Yes — I can see it. Truly, thank you.', style: 'Real bow inside the voice. The 「本当に」 unforced.', mood: 'real_bow' },
      { speaker: 'goro_grandpa', jp: '気ぃつけて。時間、もう夕方やで。', en: 'Be careful. Time — it\'s almost evening.', style: 'A small fatherly afterword. The directions weren\'t the whole point.', mood: 'fatherly_afterword' },
    ],
  },
  {
    id: 'conv_00073',
    context: 'Iwate countryside. The visiting urban doctor Saito is doing weekly rounds at the small clinic; today Tatsuya has come in for the first time in two years.',
    purpose: 'rural patient, city doctor — quiet diagnostic encounter',
    ambient: 'clinic_waiting_room',
    target_vocab: ['本当に','時間','大丈夫','少し','見る','心配'],
    cast: ['saito_doctor','tatsuya_country'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'こんにちは。今日は、どんなことで？', en: 'Hello. What brings you in today?', style: 'Calm even tone. Sits before speaking.', mood: 'calm_sitting' },
      { speaker: 'tatsuya_country', jp: 'いや…ちょっと、息切れな。', en: 'Well… a bit of shortness of breath.', style: 'Slow Tohoku admission. Doesn\'t volunteer more.', mood: 'reluctant_admission' },
      { speaker: 'saito_doctor', jp: 'いつ頃から、気になるようになりました？', en: 'When did you start noticing it?', style: 'Plain professional question. Pen in hand in the voice.', mood: 'plain_professional' },
      { speaker: 'tatsuya_country', jp: '…半年くらい前から。', en: '…About six months back.', style: 'A small admission. The number heavy.', mood: 'small_heavy' },
      { speaker: 'saito_doctor', jp: '半年ね…。本当に、その間、誰にも言わずに？', en: 'Six months… and really — you didn\'t tell anyone in that time?', style: 'No judgment in the voice. Just real diagnostic care.', mood: 'real_care' },
      { speaker: 'tatsuya_country', jp: '畑も、やらにゃならんし。', en: 'There\'s the fields too — gotta keep them up.', style: 'A plain explanation. Not an excuse, a worldview.', mood: 'worldview' },
      { speaker: 'saito_doctor', jp: 'なるほど。…少し、ちゃんと診せていただいて、いいですか？', en: 'I see. …May I take a proper look — properly?', style: 'Real respect. Asks permission like he\'s the elder.', mood: 'real_respect' },
      { speaker: 'tatsuya_country', jp: 'ええよ、どうぞ。', en: 'Yeah, sure.', style: 'Sits up a half-step in the voice. Permission given.', mood: 'permission_given' },
      { speaker: 'saito_doctor', jp: '時間、少し取ります。心配しないで、まず深呼吸。', en: 'I\'ll take a little time. Don\'t worry — first, breathe deep.', style: 'Professional kindness in motion. Voice firm and warm.', mood: 'firm_warm' },
      { speaker: 'tatsuya_country', jp: '…ありがとうな、先生。', en: '…Thanks, doctor.', style: 'A small Tohoku-formal thank-you. Real.', mood: 'tohoku_thanks' },
    ],
  },
  {
    id: 'conv_00074',
    context: 'Naoko\'s ramen shop, after closing on her birthday. Mei has come down from Tokyo to see her. The shop is empty and warm.',
    purpose: 'aunt-style birthday — quiet warmth between two unrelated women who chose each other',
    ambient: 'busy_restaurant',
    target_vocab: ['本当に','今日','時間','一緒','元気','ありがとう'],
    cast: ['naoko_aunt','mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'なおこさん、お誕生日おめでとう。', en: 'Naoko-san — happy birthday.', style: 'Walks in with flowers in the voice. A small careful smile.', mood: 'careful_smile' },
      { speaker: 'naoko_aunt', jp: 'えっ…うっそ、メイちゃん、来てくれたん？', en: 'What — no way, Mei-chan, you came down?', style: 'Genuine surprise. Towel paused mid-wipe in the voice.', mood: 'genuine_surprise' },
      { speaker: 'mei_romantic', jp: 'うん。本当に、来たかった。', en: 'Yeah. Really — wanted to come.', style: 'A small honest line. Voice steady.', mood: 'small_honest' },
      { speaker: 'naoko_aunt', jp: 'もう…泣くやん、あんた…', en: 'Oh come on… you\'re gonna make me cry…', style: 'Half-laughing, half-real. Wipes her eye in the voice.', mood: 'laugh_cry_mix' },
      { speaker: 'mei_romantic', jp: 'いつもありがとう。本当に。', en: 'Thanks for everything. Truly.', style: 'A real bow inside the voice. Eyes wet too.', mood: 'real_bow' },
      { speaker: 'naoko_aunt', jp: '座って座って。今日は、私が、ご飯作るで。', en: 'Sit, sit. Today — I cook for you.', style: 'A full Kansai pivot. Doesn\'t accept the role-reversal.', mood: 'reversed_role' },
      { speaker: 'mei_romantic', jp: 'え、お誕生日なのに？', en: 'But — it\'s your birthday?', style: 'Half-laugh. Tries to protest.', mood: 'protesting' },
      { speaker: 'naoko_aunt', jp: '誕生日やから、私が作りたいねん。', en: 'Because it\'s my birthday — I want to cook.', style: 'A small philosophical line. Kansai logic at full warmth.', mood: 'kansai_warmth' },
      { speaker: 'mei_romantic', jp: '…(small laugh)じゃ、いただきます。', en: '…(small laugh) Then — I\'ll have it.', style: 'A small surrender. Sits down properly.', mood: 'gentle_surrender' },
      { speaker: 'naoko_aunt', jp: '一緒に食べる時間、本当に、いちばんの誕生日プレゼント。', en: 'Eating together — this time, this is the best birthday gift.', style: 'A small unguarded sentence. Real.', mood: 'unguarded_real' },
      { speaker: 'mei_romantic', jp: '…私も、嬉しい。', en: '…I\'m glad too.', style: 'The smallest line of the night. Voice catches half a step.', mood: 'small_catch' },
    ],
  },
  {
    id: 'conv_00075',
    context: 'A week after a bad fight. Riku is at the kitchen table; Yumiko sits down across from him. Both have been carrying it.',
    purpose: 'long-deferred repair — mother and teen, finally talking',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','今','時間','言う','大丈夫','ない','大切','ありがとう'],
    cast: ['yumiko_mom','riku_teen'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'リク。…座って、いい？', en: 'Riku. …Can I sit?', style: 'Pulls the chair out slowly. Voice softer than usual.', mood: 'soft_approach' },
      { speaker: 'riku_teen', jp: '…うん。', en: '…Mm.', style: 'One syllable. Doesn\'t look up from his phone.', mood: 'guarded_one_word' },
      { speaker: 'yumiko_mom', jp: 'この前、本当にごめんなさい。言いすぎた。', en: 'The other day — I\'m really sorry. I said too much.', style: 'The apology first, no excuses. Voice steady.', mood: 'apology_first' },
      { speaker: 'riku_teen', jp: '…別に。', en: '…Whatever.', style: 'Reflexive teen-deflect. Voice slightly higher than the line.', mood: 'reflexive_deflect' },
      { speaker: 'yumiko_mom', jp: '別にじゃない。…私、ちゃんと言わなかった。', en: 'It\'s not whatever. …I didn\'t talk to you properly.', style: 'A small insistent line. Doesn\'t accept the deflection.', mood: 'insistent_quiet' },
      { speaker: 'riku_teen', jp: '…なんで今？', en: '…Why now?', style: 'A small honest question. Looks up briefly.', mood: 'small_honest' },
      { speaker: 'yumiko_mom', jp: 'ずっと、言いたかったの。時間、作れなくて。', en: 'I\'ve been wanting to. Just couldn\'t find the time.', style: 'Voice tired, real. The mom-honesty rare for him to hear.', mood: 'rare_mom_honesty' },
      { speaker: 'riku_teen', jp: '…(silence, then)俺も、悪かった。', en: '…(silence) I was — wrong, too.', style: 'A small honest admission. Quietest line in the scene.', mood: 'quiet_admission' },
      { speaker: 'yumiko_mom', jp: '…ありがとう、それ言ってくれて。', en: '…Thank you — for saying that.', style: 'A real catch in the voice. Means it.', mood: 'real_catch' },
      { speaker: 'riku_teen', jp: 'お母さんも、大変だしさ。', en: 'You\'ve got it hard too, you know.', style: 'A small uncharacteristic empathy. Voice slightly lower.', mood: 'uncharacteristic_empathy' },
      { speaker: 'yumiko_mom', jp: 'ありがとう。でも、リクが優先。本当に、大切。', en: 'Thank you. But you come first. Really — you matter.', style: 'A real direct line. Eye-contact level voice.', mood: 'direct_real' },
      { speaker: 'riku_teen', jp: '…(small breath)わかった。', en: '…(small breath) Got it.', style: 'A real beat. The whole week resettling.', mood: 'resettling' },
      { speaker: 'yumiko_mom', jp: '今度、何か一緒にしよ。ご飯でも、ゲームでも。', en: 'Let\'s do something together sometime. Food, games — whatever.', style: 'A small forward step. Practical kindness.', mood: 'practical_step' },
      { speaker: 'riku_teen', jp: 'ゲーム、お母さん下手じゃん。', en: 'Mom — you suck at games.', style: 'A real small grin in the voice. Affection through teasing.', mood: 'affectionate_tease' },
      { speaker: 'yumiko_mom', jp: '(laughs) 教えてよ、じゃあ。', en: '(laughs) Then teach me.', style: 'A real laugh. The whole repair complete.', mood: 'real_laugh_complete' },
      { speaker: 'riku_teen', jp: '…うん。', en: '…Mm.', style: 'The smallest assent. Phone finally face-down in the voice.', mood: 'small_assent' },
      { speaker: 'yumiko_mom', jp: 'ありがとう、リク。本当に。', en: 'Thank you, Riku. Really.', style: 'Closing line. Voice steady.', mood: 'closing_real' },
      { speaker: 'riku_teen', jp: '…うん。お母さんも。', en: '…Mm. You too, Mom.', style: 'The smallest most-important line of the conversation.', mood: 'smallest_important' },
    ],
  },
  {
    id: 'conv_00076',
    context: 'The community singing group meets every Wednesday. Mrs. Mori has been bringing Sachiko (visiting again) to sit in.',
    purpose: 'community ritual — two elders moving through a small social space',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','一緒','今日','嬉しい','元気'],
    cast: ['mrs_mori_neighbor','sachiko_grandma'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'さちこさん、今日も元気そう。', en: 'Sachiko-san — you look well today too.', style: 'Bright Kansai opener. Helps her with the coat in the voice.', mood: 'bright_helpful' },
      { speaker: 'sachiko_grandma', jp: 'おかげさまで。…本当に、ここ、楽しいわ。', en: 'Thanks to you. …Really, this place is nice.', style: 'Slow soft warmth. Pleased to be there.', mood: 'soft_pleased' },
      { speaker: 'mrs_mori_neighbor', jp: 'やろ？歌うとな、本当に、心が軽くなる。', en: 'Right? When you sing — your heart really gets lighter.', style: 'A small philosophy. Kansai economy.', mood: 'small_philosophy' },
      { speaker: 'sachiko_grandma', jp: 'そう思う。年取ってから、なお。', en: 'I think so too. Even more, as you get older.', style: 'A small honest agreement. Voice quiet.', mood: 'quiet_agreement' },
      { speaker: 'mrs_mori_neighbor', jp: '今日、一緒に歌ってくれる？', en: 'Going to sing with us today?', style: 'A small invitation that\'s really a claim.', mood: 'small_claim' },
      { speaker: 'sachiko_grandma', jp: '声、出るかな…でも、ぜひ。', en: 'I wonder if my voice will come out… but yes, gladly.', style: 'Half-laugh, half-real concern. Steps forward in the voice.', mood: 'half_laugh' },
      { speaker: 'mrs_mori_neighbor', jp: '本当に、嬉しい。みんなも喜ぶ。', en: 'Really — I\'m so happy. Everyone will be pleased.', style: 'Real warmth. Pats her arm in the voice.', mood: 'real_warmth' },
      { speaker: 'sachiko_grandma', jp: 'こちらこそ。…一緒の時間、楽しみ。', en: 'Likewise. …Looking forward to time together.', style: 'A small graceful line. Voice softened.', mood: 'graceful_soft' },
    ],
  },
  {
    id: 'conv_00077',
    context: 'It\'s Hiroshi (elder)\'s 71st birthday. Yumiko (his neighbor for years) has stopped by with a small cake.',
    purpose: 'neighborhood-affection — small birthday between people who have known each other a long time',
    ambient: 'apartment_hallway',
    target_vocab: ['本当に','今日','ありがとう','元気','嬉しい','大丈夫'],
    cast: ['hiroshi_elder','yumiko_mom'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'ひろし先生、ちょっと、いいですか？', en: 'Hiroshi-sensei — got a moment?', style: 'A polite call at the door. Soft.', mood: 'polite_soft' },
      { speaker: 'hiroshi_elder', jp: 'ああ、ゆみこさん。どうしました？', en: 'Ah — Yumiko-san. What is it?', style: 'A small pleased recognition. Opens the door slightly more.', mood: 'pleased_open' },
      { speaker: 'yumiko_mom', jp: 'お誕生日、お祝いです。本当に、ささやかですが。', en: 'Birthday — congratulations. Truly, just a little something.', style: 'A small bow inside the voice. Holds out a small box.', mood: 'small_bow' },
      { speaker: 'hiroshi_elder', jp: '…(quiet beat)よく覚えていてくださって。', en: '…(quiet beat) You remembered.', style: 'A real catch in the voice. The professor-voice cracks half a step.', mood: 'voice_cracks' },
      { speaker: 'yumiko_mom', jp: '当たり前です。…お元気で、何よりです。', en: 'Of course. …I\'m so glad you\'re well, above all.', style: 'Soft, real. The 「何よりです」 carries the whole sentiment.', mood: 'sentiment_carrying' },
      { speaker: 'hiroshi_elder', jp: 'ありがとうございます。本当に、嬉しい。', en: 'Thank you. Truly — I\'m glad.', style: 'A small slow bow. Voice steady but moved.', mood: 'slow_bow' },
      { speaker: 'yumiko_mom', jp: 'お時間ある時、お茶でも、いつでも。', en: 'Whenever you have time — tea, any time.', style: 'A small reciprocal invitation. Closes the loop.', mood: 'closing_loop' },
      { speaker: 'hiroshi_elder', jp: 'ぜひ。…今日は、本当にいい一日になりました。', en: 'Gladly. …Today really has become a fine day.', style: 'Closing line. Steps back from the door slowly in the voice.', mood: 'fine_day' },
      { speaker: 'yumiko_mom', jp: 'よかった。ではまた。', en: 'Glad. Until next time.', style: 'A small smile in the voice. Turns to leave.', mood: 'small_smile' },
    ],
  },
  {
    id: 'conv_00078',
    context: 'A late evening at Naoko\'s ramen shop. Sakura has come in alone, sat at the counter, ordered nothing. Naoko watched her for ten minutes before sliding a bowl over.',
    purpose: 'teen confession to a trusted aunt — a long quiet release',
    ambient: 'busy_restaurant',
    target_vocab: ['本当に','時間','今','大丈夫','言う','大変','ない','心配','一人'],
    cast: ['naoko_aunt','sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Extended (21-30)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'さくら、食べな。何も注文せぇへんやろ、あんた。', en: 'Sakura — eat. You weren\'t gonna order anything, were you.', style: 'Slides the bowl across. No question, just observation.', mood: 'slide_observation' },
      { speaker: 'sakura_teen', jp: '…ごめん、おばちゃん。', en: '…Sorry, oba-chan.', style: 'A small quiet line. Eyes on the counter.', mood: 'small_sorry' },
      { speaker: 'naoko_aunt', jp: '謝らんでええ。話、聞こか？', en: 'Don\'t apologise. Want to talk?', style: 'Sits across from her, towel paused. Real attention.', mood: 'real_attention' },
      { speaker: 'sakura_teen', jp: '…(long silence)', en: '(long silence)', style: 'A real beat. The kitchen sounds fade in the voice.', mood: 'real_beat' },
      { speaker: 'naoko_aunt', jp: '時間あるで、私。', en: 'I\'ve got time.', style: 'A small permission. Voice low.', mood: 'small_permission' },
      { speaker: 'sakura_teen', jp: '…学校、辞めたい。', en: '…I want to leave school.', style: 'The sentence she hasn\'t said out loud yet.', mood: 'releasing' },
      { speaker: 'naoko_aunt', jp: 'うん。', en: 'Mm.', style: 'One syllable. No reaction yet. All listening.', mood: 'all_listening' },
      { speaker: 'sakura_teen', jp: '本当に、もう、無理。', en: 'Really — I just can\'t do it anymore.', style: 'A second sentence after the first one didn\'t get a reaction. Voice cracks half a step.', mood: 'cracking' },
      { speaker: 'naoko_aunt', jp: '何が、いちばん辛い？', en: 'What\'s the worst part?', style: 'A plain real question. No advice yet.', mood: 'plain_real' },
      { speaker: 'sakura_teen', jp: 'クラスに、誰も…友達、ほんま、おらん。', en: 'In my class — no one… really, no friends.', style: 'A small admission, voice almost-tearing.', mood: 'almost_tearing' },
      { speaker: 'naoko_aunt', jp: '…そっか。それは、本当に、辛いやろね。', en: '…Mm. That — really is hard.', style: 'A real recognition. Voice quieter.', mood: 'real_recognition' },
      { speaker: 'sakura_teen', jp: '…(small breath)誰にも言われへんかった。', en: '…(small breath) Couldn\'t tell anyone.', style: 'The whole year condensed. Voice catches.', mood: 'condensed_catch' },
      { speaker: 'naoko_aunt', jp: 'うん。よう、よう来たな。本当に。', en: 'Mm. You did well coming here. Truly.', style: 'A small praise that carries no condescension.', mood: 'small_praise' },
      { speaker: 'sakura_teen', jp: 'お母さんに、心配かけたくなくて。', en: 'Didn\'t want to worry Mom.', style: 'A small honest reason. Voice small.', mood: 'small_reason' },
      { speaker: 'naoko_aunt', jp: 'うん。…でもな、お母さん、もう心配しとるで。', en: 'Mm. …But — she\'s already worrying.', style: 'A small honest correction. Slow.', mood: 'small_correction' },
      { speaker: 'sakura_teen', jp: '…(small nod)', en: '(small nod)', style: 'A real beat. Knew this already.', mood: 'knew_already' },
      { speaker: 'naoko_aunt', jp: '辞める、辞めへん、まだ決めんでええ。今、辛いだけや。', en: 'Quit, don\'t quit — don\'t decide yet. Right now it\'s just hard.', style: 'A small piece of practical wisdom. Voice steady.', mood: 'practical_wisdom' },
      { speaker: 'sakura_teen', jp: '…うん。', en: '…Mm.', style: 'A small relieved exhale audible.', mood: 'relieved_small' },
      { speaker: 'naoko_aunt', jp: '一人で、抱え込まんでええんよ。本当に。', en: 'You don\'t have to carry it alone. Truly.', style: 'A real direct line. Eye-contact level.', mood: 'direct_real' },
      { speaker: 'sakura_teen', jp: 'ありがとう…おばちゃん。本当に。', en: 'Thank you… oba-chan. Really.', style: 'A real catch in the voice. Means it.', mood: 'real_catch' },
      { speaker: 'naoko_aunt', jp: 'ええの、ええの。…ラーメン、冷める前に食べな。', en: 'It\'s fine, fine. …Eat before the ramen gets cold.', style: 'A practical pivot, releasing the weight by lifting it.', mood: 'practical_release' },
      { speaker: 'sakura_teen', jp: '…(small laugh through tears)はい。', en: '…(small laugh through tears) Okay.', style: 'A real small laugh. The kitchen sounds returning.', mood: 'real_small_laugh' },
      { speaker: 'naoko_aunt', jp: '明日また、ここ来てええで。時間、いつでもある。', en: 'Come back tomorrow too — anytime, I\'ve got time.', style: 'A small permanent door opened. Voice steady.', mood: 'door_opened' },
      { speaker: 'sakura_teen', jp: '…うん。来る。', en: '…Yeah. I\'ll come.', style: 'The smallest most-important line. Voice quiet but real.', mood: 'smallest_important' },
    ],
  },
  {
    id: 'conv_00079',
    context: 'Wednesday afternoon, a small coffee shop between hospital and language school. Asuka and Saito have a thirty-minute window.',
    purpose: 'busy-professional friend coffee — fast intimacy in a tight slot',
    ambient: 'cafe_afternoon',
    target_vocab: ['本当に','時間','今','元気','大変','友達'],
    cast: ['asuka_teacher','saito_doctor'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'お疲れさま。三十分しかないって、ほんと？', en: 'Hey there. Only thirty minutes? Really?', style: 'A small protest as greeting. Sits down already.', mood: 'protest_greeting' },
      { speaker: 'saito_doctor', jp: 'ごめん、本当に。後輩、研修中で。', en: 'Sorry — truly. Junior\'s in training.', style: 'A real apology. The doctor-voice tired.', mood: 'real_apology' },
      { speaker: 'asuka_teacher', jp: 'ええよ、それなら。元気？最低限。', en: 'It\'s fine, in that case. You okay — at least?', style: 'A small joking concern.', mood: 'joking_concern' },
      { speaker: 'saito_doctor', jp: '最低限、生きてる。', en: 'At least — alive.', style: 'A small dry laugh. The realest answer she has.', mood: 'dry_laugh' },
      { speaker: 'asuka_teacher', jp: '本当に、大変な仕事よね、医者は。', en: 'Really — being a doctor is rough.', style: 'A small honest acknowledgment.', mood: 'honest_ack' },
      { speaker: 'saito_doctor', jp: '教師もな。気を遣う、毎日。', en: 'So is teaching. Mindful work, every day.', style: 'Returns the recognition. Voice softer.', mood: 'returning_recognition' },
      { speaker: 'asuka_teacher', jp: 'ね。…たまに、こうやって会えるの、本当に救い。', en: 'Right. …Honestly, meeting like this — it\'s a real save.', style: 'A small real line. The 「救い」 carries weight.', mood: 'real_save' },
      { speaker: 'saito_doctor', jp: 'うん。友達、おって、よかった。…時間、もう少し。', en: 'Mm. Glad I\'ve got a friend. …A bit more time left.', style: 'A small unguarded line. Checks her watch in the voice.', mood: 'unguarded_check' },
    ],
  },
  {
    id: 'conv_00080',
    context: 'A small ryokan dining room. Mei is travelling alone after a hard period; the elderly woman across from her (Sachiko, also alone) starts a conversation.',
    purpose: 'incidental healing — stranger-but-not, brief warmth between two solo travellers',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','一人','今','時間','元気','大丈夫','ありがとう'],
    cast: ['sachiko_grandma','mei_romantic'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'お一人で、ご旅行？', en: 'Travelling alone?', style: 'Soft, the wobble of older Tokyo speech. A small smile.', mood: 'soft_smile' },
      { speaker: 'mei_romantic', jp: 'はい…そうです。', en: 'Yes… that\'s right.', style: 'A small startled politeness. Half-bow in the voice.', mood: 'startled_polite' },
      { speaker: 'sachiko_grandma', jp: '私も。…たまには、一人もええもんですよ。', en: 'Me too. …Now and then, alone is nice, you know.', style: 'A small graceful line. Voice quiet.', mood: 'graceful_quiet' },
      { speaker: 'mei_romantic', jp: '本当に、そうですね。', en: 'Really — that\'s true.', style: 'A small honest agreement. Eyes lift half a step.', mood: 'honest_lift' },
      { speaker: 'sachiko_grandma', jp: '何かあって、来られたん？', en: 'Did something happen, that you came here?', style: 'A small careful question. No pressure.', mood: 'careful_question' },
      { speaker: 'mei_romantic', jp: '…ちょっと。色々あって。', en: '…A little. A few things, you know.', style: 'A small honest answer. Doesn\'t volunteer.', mood: 'small_answer' },
      { speaker: 'sachiko_grandma', jp: 'うん。…元気になるまで、ゆっくりね。', en: 'Mm. …Until you\'re well — take your time.', style: 'A small grandmother\'s line. Real.', mood: 'grandmother_real' },
      { speaker: 'mei_romantic', jp: '…ありがとうございます。本当に、優しい。', en: '…Thank you. Truly — that\'s kind.', style: 'A small voice catching half a step.', mood: 'voice_catching' },
      { speaker: 'sachiko_grandma', jp: 'いえいえ。お時間、しっかり休んで。', en: 'No, no. Just rest properly.', style: 'A small bow inside the voice. Closes warmly.', mood: 'small_bow_close' },
    ],
  },
  {
    id: 'conv_00081',
    context: 'Ren has been hired by Sho\'s parents to tutor him for thirty minutes a week. Today is week three. The kid still doesn\'t look up.',
    purpose: 'tutor-pupil — small patience, smaller progress',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','見る','少し','時間','大丈夫','ありがとう'],
    cast: ['ren_uni','sho_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'しょうくん、これ、見て。', en: 'Sho-kun — look at this.', style: 'Calm, slowed down for a kid. Holds out a worksheet.', mood: 'slowed_calm' },
      { speaker: 'sho_child', jp: '…うん。', en: '…Mm.', style: 'One syllable. Eyes still on his hands.', mood: 'eyes_down' },
      { speaker: 'ren_uni', jp: '本当に、少しずつでいいから。', en: 'Truly — little by little is fine.', style: 'A small patient reassurance.', mood: 'small_patient' },
      { speaker: 'sho_child', jp: '…難しい。', en: '…Hard.', style: 'A small honest admission. One word.', mood: 'small_honest' },
      { speaker: 'ren_uni', jp: 'うん、わかる。私も、最初、難しかった。', en: 'Mm — I get it. It was hard for me too, at first.', style: 'A small honest disclosure. Levels the field.', mood: 'levelling_field' },
      { speaker: 'sho_child', jp: '…本当に？', en: '…Really?', style: 'A small surprised lift. First time looking up.', mood: 'first_look_up' },
      { speaker: 'ren_uni', jp: '本当に。…じゃ、一緒に一個だけやろうか。', en: 'Really. …Then let\'s just do one, together.', style: 'A small invitation that lowers the stakes.', mood: 'invitation_lower' },
    ],
  },
  {
    id: 'conv_00082',
    context: 'A long drive home from grandparents\'. Hina is in the passenger seat with her dad, half-eating a snack. The conversation drifts somewhere real.',
    purpose: 'father-daughter drive talk — quiet kid-philosophy meets dad-listening',
    ambient: 'taxi_interior',
    target_vocab: ['本当に','時間','今日','大丈夫','見る','大切','一緒'],
    cast: ['ryosuke_dad','hina_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'お父さん、おじいちゃん、大丈夫？', en: 'Dad — is Grandpa okay?', style: 'A small unprompted question. Eyes on the window.', mood: 'unprompted' },
      { speaker: 'ryosuke_dad', jp: 'うん…大丈夫だよ。なんで？', en: 'Yeah… he\'s fine. Why?', style: 'Voice calm, slightly cautious. Eyes on the road.', mood: 'cautious_calm' },
      { speaker: 'hina_child', jp: 'なんか、今日、ちょっと、見えた。', en: 'Just — today, a bit, it looked like.', style: 'A small honest observation. Eight-year-old radar.', mood: 'small_radar' },
      { speaker: 'ryosuke_dad', jp: 'ふうん…どんなふうに？', en: 'Hmm… how do you mean?', style: 'A small careful follow-up. No correcting.', mood: 'careful_follow' },
      { speaker: 'hina_child', jp: 'なんか…静か。本当に、いつもより。', en: 'Just — quiet. Really, more than usual.', style: 'A small precise child-honest line. Voice low.', mood: 'precise_honest' },
      { speaker: 'ryosuke_dad', jp: 'ちゃんと見てるね、ひな。…うん、お父さんも、ちょっと心配。', en: 'You really watch, Hina. …Yeah — I\'m a bit worried too.', style: 'A real honest answer. Doesn\'t deflect.', mood: 'real_honest' },
      { speaker: 'hina_child', jp: '本当？', en: 'Really?', style: 'A small lift. The honesty surprising her.', mood: 'small_lift' },
      { speaker: 'ryosuke_dad', jp: '本当。でも、大丈夫。今度、もっと一緒に、時間作るから。', en: 'Really. But — it\'s okay. We\'ll spend more time with him, going forward.', style: 'A small calm promise. Voice steady.', mood: 'calm_promise' },
      { speaker: 'hina_child', jp: '…私も？', en: '…Me too?', style: 'A small hopeful question. Eyes on her dad.', mood: 'small_hopeful' },
      { speaker: 'ryosuke_dad', jp: 'もちろん、ひなも。…本当に、大切な家族だから。', en: 'Of course, you too. …Truly — important family.', style: 'A small real line. Both 「本当に」 and 「大切」 land.', mood: 'real_landing' },
      { speaker: 'hina_child', jp: '…(small nod, watching the road)', en: '(small nod, watching the road)', style: 'A real beat. The kid resettling.', mood: 'resettling_kid' },
      { speaker: 'ryosuke_dad', jp: '…ありがとう、ひな。今日、気づいてくれて。', en: '…Thank you, Hina. For noticing today.', style: 'A small unguarded line. Closes the conversation gently.', mood: 'gentle_close' },
    ],
  },
  {
    id: 'conv_00083',
    context: 'Aoi\'s café, 8am. Kenji walks in for coffee — same morning, different season from the last time. They both notice.',
    purpose: 'tiny continuity moment — service warmth across time',
    ambient: 'cafe_morning',
    target_vocab: ['本当に','今日','ありがとう','元気'],
    cast: ['aoi_barista','kenji_office'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'おはようございます。あ、お久しぶり。', en: 'Good morning. Oh — long time.', style: 'A small recognition lift in the voice. Genuinely pleased.', mood: 'recognition_lift' },
      { speaker: 'kenji_office', jp: 'おはよう。本当に。元気だった？', en: 'Morning. Truly — been well?', style: 'A small warm return. Pulls out his wallet in the voice.', mood: 'warm_return' },
      { speaker: 'aoi_barista', jp: 'おかげさまで。今日も、ホット？', en: 'Yes, thank you. Hot one again today?', style: 'A small familiar smile. Already moving to the machine.', mood: 'familiar_smile' },
      { speaker: 'kenji_office', jp: 'はい、ぜひ。…前と変わらず、いいお店ですね。', en: 'Yes, please. …Still the same fine café as before.', style: 'A small genuine compliment. Voice quiet.', mood: 'genuine_compliment' },
      { speaker: 'aoi_barista', jp: '本当にありがとう。…また、来てくださいね。', en: 'Really — thank you. …Please come again.', style: 'A small smile audible. Slides the cup across.', mood: 'small_smile_slide' },
      { speaker: 'kenji_office', jp: 'もちろん。…ありがとう。今日もいい一日に。', en: 'Of course. …Thanks. Have a good day.', style: 'A small warm closer. Voice slightly different on the way out.', mood: 'warm_closer' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log(`wrote ${CONVERSATIONS.length} conversation(s) to ${OUT_DIR}`);
