import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_120)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02381',
    'Sakura and Ren review a political news segment for their column.',
    'Two writers in news-analysis register; civic vocabulary in natural home.',
    'study_room_lamp',
    ['氏', 'による', '大臣', '政策', '指摘', '国家'],
    ['sakura_teen', 'ren_uni'], 'Long (13-20)',
    [
      { speaker: 'sakura_teen', jp: '蓮くん、この記事、田中氏の発言が中心ね。', en: "Ren, this article centers on Mr. Tanaka's remarks.", style: 'composed adult writer voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、大臣の発表による影響、大きいですね。', en: "Yes — the impact of the minister's announcement is large.", style: 'soft young man voice, warm engaged professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '新しい政策、国家の方針が変わるみたい。', en: "It seems the new policy shifts the national direction.", style: 'gentle adult writer voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: '専門家も、問題点を指摘していますね。', en: "Experts are pointing out problems too.", style: 'composed young man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '両方の見方、丁寧に伝えたいね。', en: "I want to present both views carefully.", style: 'soft adult writer voice, warm committed delivery carefully' },
      { speaker: 'ren_uni', jp: '氏の言葉、正確に引用しましょう。', en: "Let's quote his words accurately.", style: 'gentle young man voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、根拠が、はっきりするから。', en: "Yes — it makes the basis clear.", style: 'composed adult writer voice, soft warm clear delivery carefully' },
      { speaker: 'ren_uni', jp: '読者が、自分で考えられる記事に。', en: "An article readers can think through themselves.", style: 'warm young man voice, soft warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'それが、私たちの役目ね。', en: "That's our role.", style: 'tender adult writer voice, soft warm reflective delivery carefully' },
      { speaker: 'ren_uni', jp: '一緒に、仕上げましょう。', en: "Let's finish it together.", style: 'soft young man voice, warm warm collaborative delivery carefully' },
    ]),
  C('conv_02382',
    'Hiroshi-boss leads a business meeting on a product launch decision.',
    'Business register; professional vocabulary in natural home.',
    'office_meeting_low',
    ['ビジネス', '決定', '代表', '公開', '能力', '使用'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '今回のビジネス、慎重に決定したい。', en: "I want to decide this business move carefully.", style: 'measured boss voice, soft warm professional delivery carefully' },
      { speaker: 'yuki_office', jp: '新製品の公開、来月の予定です。', en: "The new product launch is planned for next month.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'チームの能力、十分に活かせるかな?', en: "Can we fully use the team's capabilities?", style: 'professional boss voice, soft warm thoughtful delivery carefully' },
      { speaker: 'yuki_office', jp: 'はい、新しい技術の使用で、効率が上がります。', en: "Yes — using the new technology raises efficiency.", style: 'gentle office woman voice, soft warm clear delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '代表として、責任を持って進める。', en: "As the representative, I'll proceed responsibly.", style: 'warm boss voice, soft warm committed delivery carefully' },
      { speaker: 'yuki_office', jp: '資料、ご確認お願いします。', en: "Please review the materials.", style: 'soft office woman voice, warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '皆で、しっかり考えましょう。', en: "Let's all think it through carefully.", style: 'warm boss voice, soft warm collaborative delivery carefully' },
    ]),
  C('conv_02383',
    'Asuka gives a clear lecture; uses formal connectives naturally.',
    'Teacher lecture register; connectives in natural home.',
    'lecture_hall_quiet',
    ['つまり', 'あるいは', 'しかも', 'そこで', 'さて', '明らか'],
    ['asuka_teacher', 'hina_child'], 'Long (13-20)',
    [
      { speaker: 'asuka_teacher', jp: 'さて、今日のテーマに入りましょう。', en: "Now, let's get into today's topic.", style: 'composed teacher voice, soft warm professional delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、よろしくお願いします。', en: "Yes, thank you.", style: 'soft attentive teen girl voice, warm respectful delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'この実験から、結果は明らかです。', en: "From this experiment, the result is clear.", style: 'gentle teacher voice, soft warm clear delivery carefully' },
      { speaker: 'hina_child', jp: 'つまり、どういうことですか?', en: "So, what does that mean?", style: 'curious teen girl voice, soft warm engaged delivery carefully', jp: 'つまり、どういうことですか?' },
      { speaker: 'asuka_teacher', jp: 'つまり、温度が上がると、変化が起きる。', en: "In short, when temperature rises, change occurs.", style: 'warm teacher voice, soft warm explanatory delivery carefully' },
      { speaker: 'hina_child', jp: '他の方法も、ありますか?', en: "Are there other methods?", style: 'soft teen girl voice, warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '加熱、あるいは、冷却。どちらでも調べられます。', en: "Heating, or cooling — you can investigate either.", style: 'gentle teacher voice, soft warm informative delivery carefully' },
      { speaker: 'hina_child', jp: 'なるほど、面白いです!', en: "I see — that's interesting!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'しかも、応用範囲が、とても広いんですよ。', en: "Moreover, the range of applications is very wide.", style: 'warm teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: 'もっと、知りたくなりました。', en: "I want to learn even more.", style: 'soft teen girl voice, warm warm eager delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'そこで、次回は、実際にやってみましょう。', en: "So then, next time let's actually try it.", style: 'tender teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、楽しみです!', en: "Yes — I'm looking forward to it!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ]),
  C('conv_02384',
    'Saito explains insurance and treatment cost to a worried Mei.',
    'Doctor explanatory register; formal vocabulary in natural home.',
    'clinic_office_quiet',
    ['非常', '程度', '保険', '消費', '相談', '安心'],
    ['saito_doctor', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '先生、治療費が、非常に心配です。', en: "Doctor, I'm extremely worried about the treatment cost.", style: 'soft worried young mother voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '保険で、ある程度、まかなえますよ。', en: "Insurance can cover it to a degree.", style: 'measured doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: '消費する分、抑えられますか?', en: "Can we keep the out-of-pocket spending down?", style: 'gentle young woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ。窓口で、丁寧に相談できます。', en: "Yes — you can consult carefully at the desk.", style: 'gentle doctor voice, soft warm informative delivery carefully' },
      { speaker: 'mei_romantic', jp: '少し、安心しました。', en: "I feel a little relieved.", style: 'soft young woman voice, warm warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: '一人で、抱え込まないでくださいね。', en: "Please don't carry it alone.", style: 'warm doctor voice, soft warm caring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとうございます。', en: "Thank you very much.", style: 'tender young woman voice, soft warm grateful delivery carefully' },
    ]),
  C('conv_02385',
    'Sakura and Hiroshi-elder discuss US-Korea relations on the news.',
    'Two adults discussing world affairs; proper nouns in natural home.',
    'living_room_tv_low',
    ['米国', '韓国', '国際', '代表', '関係', '指摘'],
    ['sakura_teen', 'hiroshi_elder'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'おとうさん、米国と韓国の会談、ありましたね。', en: "Otosan, there was a US-Korea summit.", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、国際の話、ようけ出とるな。', en: "Yeah — lots of international news lately.", style: 'slow elder Kansai voice, warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '両国の代表、笑顔で握手していました。', en: "Both nations' representatives shook hands smiling.", style: 'gentle adult writer voice, soft warm informative delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '専門家は、課題も指摘しとったな。', en: "The experts pointed out challenges, too.", style: 'gentle elder Kansai voice, soft warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: '良い関係が、続くといいですね。', en: "I hope the good relations continue.", style: 'soft adult writer voice, warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、平和がいちばんや。', en: "Truly — peace above all.", style: 'warm elder Kansai voice, soft warm agreeing delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に、丁寧に書きます。', en: "I'll write about it carefully.", style: 'tender adult writer voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02386',
    'Ren interviews a factory manager about production.',
    'Writer interviewing professional; industry vocabulary in natural home.',
    'office_quiet_low',
    ['生産', '購入', '及び', '一部', '行う', '表示'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '生産について、教えていただけますか?', en: "Could you tell me about production?", style: 'soft young man voice, warm professional inquiry delivered carefully' },
      { speaker: 'hiroshi_boss', jp: 'ええ。部品及び完成品を、ここで作ります。', en: "Yes — we make parts and finished goods here.", style: 'measured boss voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: '一部は、海外でも、購入されるんですか?', en: "Is a portion purchased overseas too?", style: 'engaged young man voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'はい。検査も、すべてここで行います。', en: "Yes. We carry out all inspections here too.", style: 'professional boss voice, soft warm clear delivery carefully' },
      { speaker: 'ren_uni', jp: '製品の表示も、丁寧ですね。', en: "The product labeling is meticulous too.", style: 'soft young man voice, warm appreciative delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'お客様のため、当然のことです。', en: "It's only natural — for our customers.", style: 'warm boss voice, soft warm humble delivery carefully' },
      { speaker: 'ren_uni', jp: '記事に、しっかり書きます。', en: "I'll write it up thoroughly.", style: 'humble young man voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02387',
    'Naoko vents about a truck blocking deliveries; Daichi helps.',
    'Aunt venting about everyday nuisance naturally.',
    'ramen_shop_morning',
    ['トラック', 'バック', 'しまっ', '以外', '困る', '相談'],
    ['naoko_aunt', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'naoko_aunt', jp: '大ちゃん、トラックが、店の前で止まってしもた!', en: "Daichi, a truck has stopped right in front of the shop!", style: 'animated Kansai aunt voice, bright warm exasperated delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'えっ、バックして、どけてもらえへんの?', en: "Eh — can't they back up and clear it?", style: 'soft Kansai husband voice, warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'それが、運転手、おらへんねん。困るわ。', en: "Thing is, the driver's not around. It's a hassle.", style: 'frustrated Kansai aunt voice, bright warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '正面以外、入口、ないもんな。', en: "There's no entrance besides the front, after all.", style: 'gentle Kansai husband voice, soft warm sympathetic delivery carefully' },
      { speaker: 'naoko_aunt', jp: '誰かに、相談した方がええかな?', en: "Should I consult someone?", style: 'soft Kansai aunt voice, warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '俺、近所の人に、声かけてくるわ。', en: "I'll go ask the neighbors.", style: 'warm Kansai husband voice, soft warm helpful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おおきに、助かるわ!', en: "Thanks — that's a big help!", style: 'warm Kansai aunt voice, bright warm grateful delivery carefully' },
    ]),
  C('conv_02388',
    'Asuka discusses a labor topic with Yuki over coffee.',
    'Two adults discussing work life naturally.',
    'cafe_afternoon_low',
    ['労働', '委員', '一方', 'における', '能力', '指摘'],
    ['asuka_teacher', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'ゆきさん、職場における労働環境、どう?', en: "Yuki, how's the labor environment at your workplace?", style: 'composed teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: '委員会で、改善案が出ているんです。', en: "There are improvement proposals in committee.", style: 'gentle office woman voice, soft warm informative delivery carefully' },
      { speaker: 'asuka_teacher', jp: '一方で、難しい点も、あるでしょうね。', en: "On the other hand, there must be difficult points.", style: 'soft teacher voice, warm thoughtful delivery carefully' },
      { speaker: 'yuki_office', jp: 'ええ、上司も、課題を指摘しています。', en: "Yes — the boss is pointing out challenges too.", style: 'composed office woman voice, soft warm clear delivery carefully' },
      { speaker: 'asuka_teacher', jp: '皆の能力が、活きるといいわね。', en: "I hope everyone's abilities are put to use.", style: 'warm teacher voice, soft warm hopeful delivery carefully' },
      { speaker: 'yuki_office', jp: '少しずつ、変わると信じています。', en: "I believe it'll change little by little.", style: 'tender office woman voice, soft warm earnest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '応援してるわ。', en: "I'm rooting for you.", style: 'warm teacher voice, soft warm supportive delivery carefully' },
    ]),
  C('conv_02389',
    'Sakura interviews a historian about a documentary on national history.',
    'WIDENED SCENARIO: historian interview; formal/abstract vocabulary in natural home.',
    'study_quiet_warm',
    ['国家', '時代', 'における', '一部', '明らか', '指摘'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '先生、この時代における国家の役割、教えてください。', en: "Professor, please tell me the state's role in this era.", style: 'gentle adult writer voice, soft warm professional inquiry delivered carefully' },
      { speaker: 'hiroshi_boss', jp: '資料から、その役割は明らかになっています。', en: "From the records, that role has become clear.", style: 'measured scholar-mode boss voice, soft warm informative delivery carefully' },
      { speaker: 'sakura_teen', jp: '一部の記録は、失われたんですか?', en: "Were some of the records lost?", style: 'curious adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ええ、その点は、研究者も指摘しています。', en: "Yes — researchers point that out too.", style: 'soft scholar voice, warm warm clear delivery carefully' },
      { speaker: 'sakura_teen', jp: '深い歴史ですね、本当に。', en: "It's deep history, truly.", style: 'tender adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '次の世代に、伝えたい話です。', en: "It's a story I want to pass to the next generation.", style: 'warm scholar voice, soft warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: '心をこめて、書きます。', en: "I'll write it with all my heart.", style: 'humble adult writer voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02390',
    'Kenji explains his decision to publish work online to Ren.',
    'Mentor explaining a choice naturally.',
    'studio_lamp_evening',
    ['決定', '公開', 'つまり', '反応', 'について', '心配'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '蓮、作品をネットで公開すること、決定したわ。', en: "Ren, I've decided to publish my work online.", style: 'soft Kansai man voice, warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '大きな一歩ですね。', en: "That's a big step.", style: 'soft young man voice, warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: 'つまり、皆に見てもらうってことや。', en: "In other words, letting everyone see it.", style: 'gentle Kansai man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'ren_uni', jp: '反応について、心配ですか?', en: "Are you worried about the reactions?", style: 'curious young man voice, soft warm caring delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、正直、ちょっと怖いわ。', en: "Yeah — honestly, a little scared.", style: 'soft Kansai man voice, warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '健司さんの作品、絶対、響きます。', en: "Your work will definitely resonate, Kenji-san.", style: 'warm young man voice, soft warm reassuring delivery carefully' },
      { speaker: 'kenji_office', jp: 'おおきに、心強いわ。', en: "Thanks — that's encouraging.", style: 'tender Kansai man voice, soft warm grateful delivery carefully' },
    ]),
  C('conv_02391',
    'Hina-young asks Hiroshi-elder about how few cars there were long ago.',
    'Grandfather reflecting on social change with formal-tinged words.',
    'porch_evening_breeze',
    ['以前', 'ほとんど', 'その後', 'かなり', 'すべて', '時代'],
    ['hiroshi_elder', 'hina_child'], 'Medium (7-12)',
    [
      { speaker: 'hina_child', jp: 'おじいちゃん、以前は、車、少なかったの?', en: "Grandpa, were cars rare in the old days?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ほとんど無かったで、わしの若い頃。', en: "Yeah, there were almost none in my youth.", style: 'slow elder Kansai voice, warm reminiscent delivery carefully' },
      { speaker: 'hina_child', jp: 'その後、かなり増えたんですね。', en: "Then they increased a lot afterward.", style: 'soft teen girl voice, warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'そや、すべてが、便利になったわ。', en: "That's right — everything got convenient.", style: 'gentle elder Kansai voice, soft warm reflective delivery carefully' },
      { speaker: 'hina_child', jp: '時代の変化、すごいですね。', en: "The change of eras is incredible.", style: 'tender teen girl voice, soft warm appreciative delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前に話せて、嬉しいわ。', en: "I'm glad I can tell you about it.", style: 'warm elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: 'もっと、聞きたい!', en: "I want to hear more!", style: 'bright teen girl voice, soft warm eager delivery carefully' },
    ]),
  C('conv_02392',
    'Yuki briefs Aoi on a new business regulation affecting the cafe.',
    'Two women discussing rules in practical register.',
    'cafe_office_quiet',
    ['法律', '対象', 'について', '全て', '確認', '相談'],
    ['yuki_office', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '蒼さん、新しい法律、お店も対象なんです。', en: "Aoi, the new law applies to the shop too.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'aoi_barista', jp: 'まあ、何について、ですか?', en: "Oh — about what?", style: 'soft worried adult woman voice, warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: '食品の表示について、全て見直しが必要です。', en: "All food labeling needs to be reviewed.", style: 'gentle office woman voice, soft warm informative delivery carefully' },
      { speaker: 'aoi_barista', jp: '一緒に、確認してもらえますか?', en: "Could you check it with me?", style: 'curious adult woman voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: 'もちろん、いつでも相談してね。', en: "Of course — consult me anytime.", style: 'warm office woman voice, soft warm supportive delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、助かる。', en: "Thanks — that helps.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'yuki_office', jp: '一つずつ、進めましょう。', en: "Let's go through it one by one.", style: 'soft office woman voice, warm warm collaborative delivery carefully' },
    ]),
  C('conv_02393',
    'Ren reads a finance article; discusses consumer spending with Sakura.',
    'Writers discussing economics in editorial register.',
    'cafe_afternoon_low',
    ['消費', '億', '一方', '指摘', 'における', '傾向'],
    ['ren_uni', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'さくらさん、消費の傾向、変わってきてますね。', en: "Sakura, consumer trends are shifting.", style: 'soft young man voice, warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '数字、何億円規模なの?', en: "What scale — hundreds of millions of yen?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、都市における消費が、特に大きい。', en: "Yes — urban spending is especially large.", style: 'composed young man voice, soft warm informative delivery carefully' },
      { speaker: 'sakura_teen', jp: '一方で、地方は、どうなの?', en: "On the other hand, what about rural areas?", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '専門家が、その差を指摘しています。', en: "Experts point out that gap.", style: 'gentle young man voice, soft warm clear delivery carefully' },
      { speaker: 'sakura_teen', jp: '面白い記事になりそう。', en: "It'll make an interesting article.", style: 'warm adult writer voice, soft warm content delivery carefully' },
      { speaker: 'ren_uni', jp: '丁寧に、まとめます。', en: "I'll write it up carefully.", style: 'humble young man voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02394',
    'Daichi tells Mei about a company decision; they discuss the impact.',
    'Couple discussing work change naturally.',
    'kitchen_evening_warm',
    ['決定', 'わけ', '思わ', '以外', '相談', '将来'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'メイ、会社の決定で、部署が変わるねん。', en: "Mei, a company decision is moving me to another department.", style: 'soft Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'えっ、どういうわけ?', en: "What — for what reason?", style: 'soft worried young wife voice, warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '思わぬ話やったけど、悪い話やない。', en: "It was unexpected, but it's not bad.", style: 'gentle Kansai husband voice, soft warm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'それ以外に、変わることは?', en: "Anything else that'll change?", style: 'gentle young woman voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おまえと、将来のこと、相談したかってん。', en: "I wanted to talk about our future with you.", style: 'soft Kansai husband voice, warm warm earnest delivery carefully' },
      { speaker: 'mei_romantic', jp: '二人で、考えていこう。', en: "Let's think it through together.", style: 'tender young wife voice, soft warm united delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ありがとう、心強いわ。', en: "Thanks — that's reassuring.", style: 'tender Kansai husband voice, soft warm grateful delivery carefully' },
    ]),
  C('conv_02395',
    'Sho-young asks Asuka about a connective word; gentle grammar help.',
    'Teacher patiently teaching connectives to a child.',
    'classroom_after_quiet',
    ['つまり', 'しかも', 'そこで', '全く', 'それから', '例えば'],
    ['asuka_teacher', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: '先生、「そこで」って、どう使うの?', en: "Sensei, how do you use \"so then\"?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '困った時、次の行動を言う時に使うのよ。', en: "You use it to say the next action when stuck.", style: 'warm teacher voice, soft warm gentle delivery carefully' },
      { speaker: 'sho_child', jp: '「しかも」は?', en: "And \"moreover\"?", style: 'soft child boy voice, warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '何かを付け加える時。それから、こうも言えるわ。', en: "When adding something. And you can also say it like this.", style: 'gentle teacher voice, soft warm explanatory delivery carefully' },
      { speaker: 'sho_child', jp: '全く分からなかったけど、つまり、わかってきた!', en: "I had no clue, but — in short, I'm getting it!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '例えば、お話を作って、練習しようね。', en: "Let's practice by making up a little story.", style: 'tender teacher voice, soft warm patient delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、やってみる!', en: "Yeah — I'll try!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ]),
  C('conv_02396',
    'Hiroshi-boss addresses staff formally; opening remarks.',
    'Boss in formal address register; polite vocabulary in natural home.',
    'office_hall_low',
    ['申し上げ', '皆様', '御', 'について', '目的', '感謝'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '皆様、本日はお集まりいただき、御礼申し上げます。', en: "Everyone, thank you for gathering today.", style: 'measured boss voice, soft warm formal courteous delivery carefully' },
      { speaker: 'yuki_office', jp: '社長、本日の目的は何でしょうか?', en: "Boss, what's the purpose of today?", style: 'composed office woman voice, soft warm respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '新しい事業について、ご説明いたします。', en: "I'll explain about the new venture.", style: 'professional boss voice, soft warm clear delivery carefully' },
      { speaker: 'yuki_office', jp: '皆、関心を持っております。', en: "Everyone is interested.", style: 'gentle office woman voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '御協力に、心から感謝しています。', en: "I'm sincerely grateful for your cooperation.", style: 'warm boss voice, soft warm humble delivery carefully' },
      { speaker: 'yuki_office', jp: '一緒に、頑張りましょう。', en: "Let's work hard together.", style: 'soft office woman voice, warm warm committed delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'よろしくお願いいたします。', en: "I'm counting on all of you.", style: 'warm boss voice, soft warm respectful delivery carefully' },
    ]),
  C('conv_02397',
    'Sakura discusses a TV documentary on China with Ren.',
    'WIDENED SCENARIO: documentary discussion; proper noun in natural home.',
    'living_room_tv_low',
    ['中国', '時代', 'における', '一方', '文化', '指摘'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '蓮くん、中国の古い時代の番組、深いね。', en: "Ren, this program on ancient China is profound.", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: 'その時代における文化、豊かでしたね。', en: "The culture of that era was rich.", style: 'gentle young man voice, soft warm appreciative delivery carefully' },
      { speaker: 'sakura_teen', jp: '一方で、難しい時期もあったみたい。', en: "On the other hand, there were hard times too.", style: 'composed adult writer voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: '研究者が、その点を指摘していました。', en: "Researchers pointed that out.", style: 'soft young man voice, warm clear delivery carefully' },
      { speaker: 'sakura_teen', jp: '学ぶこと、たくさんあるね。', en: "There's so much to learn.", style: 'tender adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'ren_uni', jp: 'また、一緒に観ましょう。', en: "Let's watch again together.", style: 'warm young man voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、ぜひ。', en: "Yes — by all means.", style: 'soft adult writer voice, warm warm affirming delivery carefully' },
    ]),
  C('conv_02398',
    'Naoko discusses health insurance with Mrs. Mori.',
    'Two older women on practical matters naturally.',
    'ramen_shop_afternoon',
    ['保険', '非常', '程度', '相談', '安心', 'について'],
    ['naoko_aunt', 'mrs_mori_neighbor'], 'Medium (7-12)',
    [
      { speaker: 'naoko_aunt', jp: '森さん、保険について、聞きたいことがあって。', en: "Mori-san, I've got a question about insurance.", style: 'soft Kansai aunt voice, warm engaged delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'まあ、何でも聞いてちょうだい。', en: "Oh, ask me anything.", style: 'gentle older neighbor voice, soft warm welcoming delivery carefully' },
      { speaker: 'naoko_aunt', jp: '医療費が、非常に高くてな。', en: "Medical costs are extremely high.", style: 'animated Kansai aunt voice, bright warm honest delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ある程度は、保険でまかなえるわよ。', en: "Insurance covers it to some degree.", style: 'warm older woman voice, soft warm informative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '窓口で、相談してみるわ。', en: "I'll consult at the desk.", style: 'soft Kansai aunt voice, warm warm practical delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'それがいいわ、安心できるから。', en: "That's good — it'll put you at ease.", style: 'tender older neighbor voice, soft warm reassuring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おおきに、助かるわ!', en: "Thanks — that's a help!", style: 'warm Kansai aunt voice, bright warm grateful delivery carefully' },
    ]),
  C('conv_02399',
    'Sakura interviews a researcher about an international study.',
    'WIDENED SCENARIO: research interview; academic vocabulary in natural home.',
    'office_quiet_low',
    ['国際', '調査', 'における', '行わ', '能力', '明らか'],
    ['sakura_teen', 'saito_doctor'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '先生、この国際調査、どこで行われたんですか?', en: "Doctor, where was this international study conducted?", style: 'gentle adult writer voice, soft warm professional inquiry delivered carefully' },
      { speaker: 'saito_doctor', jp: '複数の国における病院で、行われました。', en: "It was carried out at hospitals in several countries.", style: 'measured doctor voice, soft warm informative delivery carefully' },
      { speaker: 'sakura_teen', jp: '結果は、明らかになったんですか?', en: "Did the results become clear?", style: 'curious adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ。治療の能力が、大きく向上しました。', en: "Yes — treatment capability improved greatly.", style: 'gentle doctor voice, soft warm clear delivery carefully' },
      { speaker: 'sakura_teen', jp: '素晴らしい成果ですね。', en: "What a wonderful outcome.", style: 'soft adult writer voice, warm appreciative delivery carefully' },
      { speaker: 'saito_doctor', jp: '多くの研究者の、努力のおかげです。', en: "It's thanks to many researchers' efforts.", style: 'warm doctor voice, soft warm humble delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に、心をこめて書きます。', en: "I'll write it with all my heart.", style: 'humble adult writer voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02400',
    'Whole group has a relaxed dinner; light formal-tinged conversation.',
    'Multi-voice family meal, natural with some formal vocabulary.',
    'dining_room_warm',
    ['つまり', 'すべて', 'ひとつ', 'それから', '皆', '感謝'],
    ['hiroshi_elder', 'naoko_aunt', 'mei_romantic', 'daichi_kansai', 'sho_child', 'hina_child'], 'Long (13-20)',
    [
      { speaker: 'hiroshi_elder', jp: '今夜も、皆、集まれて、ありがたいな。', en: "I'm grateful everyone could gather tonight too.", style: 'slow elder Kansai voice, warm warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ほんま、賑やかでええわ!', en: "Truly, it's lovely and lively!", style: 'brassy Kansai aunt voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'すべてが、いい思い出になるね。', en: "It all becomes a good memory.", style: 'soft young mother voice, warm reflective delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'それから、来年の話も、せなあかんな。', en: "And we'll have to talk about next year too.", style: 'warm Kansai husband voice, soft warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: 'お父さん、ひとつ、いい?', en: "Dad, can I say one thing?", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、なんや?', en: "Sure, what is it?", style: 'soft Kansai husband voice, warm warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: 'つまり、皆が、大好きってこと!', en: "In short — I love everyone!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'ふふ、可愛いこと言うね。', en: "Heh, what a sweet thing to say.", style: 'bright teen girl voice, soft warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: '皆に、感謝の気持ちでいっぱい。', en: "I'm full of gratitude for everyone.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ええ家族や、ほんま!', en: "What a fine family, truly!", style: 'warm Kansai aunt voice, bright warm proud delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'こうやって、ずっと続けような。', en: "Let's keep this going for a long time.", style: 'gentle elder Kansai voice, soft warm enduring delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、約束や。', en: "Yeah — it's a promise.", style: 'warm Kansai husband voice, soft warm committed delivery carefully' },
      { speaker: 'sho_child', jp: 'やった!', en: "Yay!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
    ]),
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_120 wrote', CONVERSATIONS.length, 'files');
