import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_079)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01566',
    context: 'Ren and Saito discuss a research article over coffee.',
    purpose: 'Young creative and doctor exchanging intellectual curiosity.',
    ambient: 'cafe_afternoon_quiet',
    sound_effects: [],
    target_vocab: ['研究', '論文', '専門', '分野'],
    cast: ['ren_uni', 'saito_doctor'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'この論文、興味深いです。', en: "This paper's fascinating.", style: 'soft young man voice, warm intellectual eager delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ、専門の研究ですね。', en: "Yes — specialized research.", style: 'measured doctor voice, soft warm academic interest delivered carefully' },
      { speaker: 'ren_uni', jp: '別分野でも、応用できそう。', en: "Could apply to other fields.", style: 'engaged young man voice, soft warm curious delivery carefully' },
      { speaker: 'saito_doctor', jp: 'いい着眼点ですね。', en: "Good angle.", style: 'warm doctor voice, soft impressed approving delivery carefully' },
      { speaker: 'ren_uni', jp: '今度、深く読んでみます。', en: "I'll read it more deeply next time.", style: 'soft young man voice, warm committed studious delivery carefully' },
      { speaker: 'saito_doctor', jp: '感想、聞かせてください。', en: "Share your thoughts after.", style: 'gentle doctor voice, soft warm friendly delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、必ず。', en: "Yes — without fail.", style: 'humble young man voice, soft warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_01567',
    context: 'Hina-young asks Asuka about studying abroad someday.',
    purpose: 'Teen seeking guidance on future possibilities.',
    ambient: 'classroom_after_quiet',
    sound_effects: [],
    target_vocab: ['留学', '海外', '言語', '夢'],
    cast: ['hina_child', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '先生、留学って、難しい?', en: "Teacher — is studying abroad hard?", style: 'curious teen girl voice, soft warm hopeful inquiry delivered carefully' },
      { speaker: 'asuka_teacher', jp: 'ええ、でも素敵な経験よ。', en: "Yes — but a wonderful experience.", style: 'gentle teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '海外、行ってみたいな。', en: "I'd love to go abroad.", style: 'soft teen girl voice, warm dreamy hopeful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '言語、頑張って勉強してね。', en: "Study the language hard.", style: 'warm teacher voice, soft encouraging guiding delivery carefully' },
      { speaker: 'hina_child', jp: '英語、得意になりたい。', en: "Want to be good at English.", style: 'eager teen girl voice, soft warm determined delivery carefully' },
      { speaker: 'asuka_teacher', jp: '夢、大切にね。', en: "Cherish your dream.", style: 'tender teacher voice, soft warm wise delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、頑張ります!', en: "Yes — I'll work hard!", style: 'bright teen girl voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_01568',
    context: 'Sho-young brings home a science kit; Kenji helps him with an experiment.',
    purpose: 'Father figure helping child with hands-on learning.',
    ambient: 'kitchen_table_low',
    sound_effects: [],
    target_vocab: ['実験', '科学', '道具', '発見'],
    cast: ['kenji_office', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '健司おじちゃん、実験しよ!', en: "Kenji-ojichan — let's experiment!", style: 'eager child boy voice, bright cheerful warm delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、何の科学や?', en: "Yeah — what kind of science?", style: 'warm Kansai man voice, soft cheerful curious delivery carefully' },
      { speaker: 'sho_child', jp: '水と油、混ざるかな?', en: "Will water and oil mix?", style: 'curious child boy voice, soft warm hopeful delivery carefully' },
      { speaker: 'kenji_office', jp: '道具揃えて、やってみよか。', en: "Get the tools — let's try.", style: 'soft Kansai mentor voice, warm patient encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、楽しい!', en: "Yeah — fun!", style: 'thrilled child boy voice, bright warm energetic delivery carefully' },
      { speaker: 'kenji_office', jp: '何か発見、するかもな。', en: "Might discover something.", style: 'gentle Kansai voice, soft warm playful delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、わくわくする!', en: "Yay — exciting!", style: 'energetic child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01569',
    context: 'Sakura interviews a small-town movie director for an article.',
    purpose: 'Author interviewing local filmmaker; warm professional exchange.',
    ambient: 'studio_office_low',
    sound_effects: [],
    target_vocab: ['映画', '監督', '撮影', '演技'],
    cast: ['sakura_teen', 'hiroshi_boss'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '監督、映画の撮影、どうでした?', en: "Director — how was filming?", style: 'soft adult writer voice, warm polite professional inquiry delivered carefully' },
      { speaker: 'hiroshi_boss', jp: '俳優陣の演技、素晴らしかった。', en: "The actors were superb.", style: 'warm boss voice, soft proud professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '時間、大変でしたか?', en: "Was the schedule tough?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ええ、しかし充実してました。', en: "Yes — but fulfilling.", style: 'composed boss voice, soft warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '上映、楽しみにしてます。', en: "Looking forward to the release.", style: 'warm adult writer voice, soft hopeful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble boss voice, soft warm grateful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お話、書かせていただきます。', en: "I'll write up our talk.", style: 'professional adult writer voice, soft warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_01570',
    context: 'Tatsuya-country sends a young employee to learn at a city seminar.',
    purpose: 'Elder farmer encouraging young worker\'s education.',
    ambient: 'farmhouse_porch_morning',
    sound_effects: [],
    target_vocab: ['学ぶ', '都会', '経験', '機会'],
    cast: ['tatsuya_country', 'ren_uni'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '都会の研修、行ってこい。', en: "Go to the city seminar.", style: 'soft Tohoku farmer voice, warm fatherly direct delivery carefully' },
      { speaker: 'ren_uni', jp: 'いいんですか?', en: "Are you sure?", style: 'soft young man voice, warm humble surprised delivery carefully' },
      { speaker: 'tatsuya_country', jp: '学ぶ機会、大事や。', en: "A learning chance — precious.", style: 'gentle Tohoku voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: '経験、生かします。', en: "I'll make use of the experience.", style: 'committed young man voice, soft warm respectful delivery carefully' },
      { speaker: 'tatsuya_country', jp: '楽しんでこい。', en: "Have fun.", style: 'warm Tohoku farmer voice, soft fatherly encouraging delivery carefully' },
    ],
  },
  {
    id: 'conv_01571',
    context: 'Naoko teaches a new young server how to take orders at the ramen shop.',
    purpose: 'Aunt teaching workplace ropes with warmth and bite.',
    ambient: 'ramen_shop_morning_prep',
    sound_effects: [],
    target_vocab: ['注文', '客', '丁寧', '対応'],
    cast: ['naoko_aunt', 'sakura_teen'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '注文取るときは、丁寧にな!', en: "When taking orders — be polite!", style: 'brassy Kansai aunt voice, bright loud firm delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、覚えます。', en: "Yes — I'll remember.", style: 'soft adult writer voice, warm humble attentive delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お客さん、ようけ来るで。', en: "Lots of customers come.", style: 'animated Kansai aunt voice, bright warm informative delivery carefully' },
      { speaker: 'sakura_teen', jp: '対応、気をつけます。', en: "I'll be careful in handling.", style: 'composed adult writer voice, soft warm respectful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うん、ええ子や、頑張り!', en: "Yes — good kid, keep at it!", style: 'warm Kansai aunt voice, bright loud loving delivery carefully' },
    ],
  },
  {
    id: 'conv_01572',
    context: 'Yumiko reads aloud to Hikari (Mei\'s baby substitute → use hina_child as small visitor).',
    purpose: 'Grandmother figure reading aloud to a young child.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['本', '物語', '声', '優しい'],
    cast: ['yumiko_mom', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'ひなちゃん、本読もうか。', en: "Hina — shall we read a book?", style: 'gentle older mother voice, soft warm inviting delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、優しい話がいい。', en: "Yes — a kind story.", style: 'soft teen girl voice, warm gentle preference delivered carefully' },
      { speaker: 'yumiko_mom', jp: 'この物語、心が温まるわよ。', en: "This story warms the heart.", style: 'warm older mother voice, soft fond delivery carefully' },
      { speaker: 'hina_child', jp: 'おばあちゃんの声、好き。', en: "Grandma — I love your voice.", style: 'tender teen girl voice, soft warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、嬉しいわ。', en: "Heh — I'm glad.", style: 'soft older mother voice, warm tender affectionate delivery carefully' },
    ],
  },
  {
    id: 'conv_01573',
    context: 'Daichi and Ren go to the gym together; quick workout chat.',
    purpose: 'Older brother figure and young man bonding through exercise.',
    ambient: 'gym_low_machines',
    sound_effects: [],
    target_vocab: ['筋肉', '体', '運動', '汗'],
    cast: ['daichi_kansai', 'ren_uni'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '蓮、いい運動なってる?', en: "Ren — getting a good workout?", style: 'warm Kansai man voice, soft cheerful brotherly delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、汗びっしょりです。', en: "Yes — totally sweaty.", style: 'breathless young man voice, soft warm cheerful honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '筋肉、ついてきたな。', en: "Muscles are showing up.", style: 'fond Kansai man voice, soft warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: '毎日、続けてます。', en: "Keeping at it daily.", style: 'soft young man voice, warm proud humble delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええ感じや、若いなぁ。', en: "Nice — you're young.", style: 'warm Kansai man voice, soft fond admiring delivery carefully' },
    ],
  },
  {
    id: 'conv_01574',
    context: 'Mei and Aoi browse a fabric shop for kimono fabric for a wedding.',
    purpose: 'Two female friends shopping for fancy garment.',
    ambient: 'shop_quiet_silk',
    sound_effects: [],
    target_vocab: ['着物', '布', '色', '柄'],
    cast: ['mei_romantic', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '蒼さん、この色、似合うかな?', en: "Aoi — does this color suit?", style: 'soft young woman voice, warm fond inquiring delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ええ、肌に映えるね。', en: "Yes — flatters your skin.", style: 'warm adult woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'mei_romantic', jp: '柄、控えめがいいかな。', en: "Subtle pattern's best?", style: 'gentle young woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、上品で美しい。', en: "Yes — elegant and lovely.", style: 'soft adult woman voice, warm appreciative observant delivery carefully' },
      { speaker: 'mei_romantic', jp: '着物選び、楽しいね。', en: "Picking kimono is fun.", style: 'tender young woman voice, soft warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、一緒に来てよかった。', en: "Heh — glad I came along.", style: 'warm adult woman voice, soft fond delight delivered carefully' },
      { speaker: 'mei_romantic', jp: 'うん、心強い。', en: "Yes — reassuring.", style: 'soft young woman voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01575',
    context: 'Hiroshi-elder and Goro-grandpa watch sumo together on TV.',
    purpose: 'Two elders sharing traditional sport viewing.',
    ambient: 'tatami_tv_low',
    sound_effects: [],
    target_vocab: ['相撲', '力士', '勝負', '応援'],
    cast: ['hiroshi_elder', 'goro_grandpa'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'おっ、この力士、強いな。', en: "Oh — this rikishi's strong.", style: 'slow elder Kansai voice, warm engaged delivery carefully' },
      { speaker: 'goro_grandpa', jp: '勝負、見応えあるなぁ。', en: "The match is worth watching.", style: 'gentle elder voice, soft warm appreciative delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '応援、しよか。', en: "Let's cheer.", style: 'soft elder Kansai voice, warm content brotherly delivery carefully' },
      { speaker: 'goro_grandpa', jp: 'うん、頑張れ!', en: "Yeah — go for it!", style: 'warm elder voice, soft cheering delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おっしゃ、勝った!', en: "Yes — won!", style: 'animated elder Kansai voice, bright loud cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01576',
    context: 'Kenji teaches Sho-young the basics of using chopsticks properly.',
    purpose: 'Uncle gently correcting a child\'s table manners.',
    ambient: 'dining_table_low',
    sound_effects: [],
    target_vocab: ['箸', '持ち方', '練習', '丁寧'],
    cast: ['kenji_office', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '箸の持ち方、ちょっと違うで。', en: "Chopstick grip's a bit off.", style: 'soft Kansai mentor voice, warm gentle correcting delivery carefully' },
      { speaker: 'sho_child', jp: '本当?教えて!', en: "Really? Teach me!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: '上の箸だけ動かすんや。', en: "Only move the top one.", style: 'patient Kansai voice, soft warm instructional delivery carefully' },
      { speaker: 'sho_child', jp: 'むずかしいなぁ。', en: "Hard.", style: 'soft child boy voice, warm honest concentrating delivery carefully' },
      { speaker: 'kenji_office', jp: '練習したら、できるで。', en: "With practice, you'll get it.", style: 'warm Kansai voice, soft encouraging patient delivery carefully' },
    ],
  },
  {
    id: 'conv_01577',
    context: 'Asuka and Saito visit a local elderly community center.',
    purpose: 'Two professionals warming up to community service.',
    ambient: 'community_hall_low',
    sound_effects: [],
    target_vocab: ['高齢', '地域', '活動', '参加'],
    cast: ['asuka_teacher', 'saito_doctor'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '今日、参加できて嬉しいです。', en: "Glad to participate today.", style: 'warm teacher voice, soft sincere appreciative delivery carefully' },
      { speaker: 'saito_doctor', jp: '高齢の方、元気そうですね。', en: "Elderly folks look spry.", style: 'gentle doctor voice, soft warm observant delivery carefully' },
      { speaker: 'asuka_teacher', jp: '地域の活動、大切ですね。', en: "Community activities matter.", style: 'soft teacher voice, warm reflective delivery carefully' },
      { speaker: 'saito_doctor', jp: '健康相談、たくさん来ました。', en: "Many health consults today.", style: 'measured doctor voice, soft warm professional delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'みんな、安心したでしょうね。', en: "I'm sure they were relieved.", style: 'tender teacher voice, soft warm caring delivery carefully' },
      { speaker: 'saito_doctor', jp: 'またこの活動、続けたいです。', en: "Want to keep this going.", style: 'warm doctor voice, soft committed delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ぜひ、ご一緒に。', en: "Together — by all means.", style: 'warm teacher voice, soft collaborative friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_01578',
    context: 'Aoi and Hina-young have a deep heart-to-heart about growing up.',
    purpose: 'Adult mentor having gentle reassuring talk with teen.',
    ambient: 'cafe_evening_low',
    sound_effects: [],
    target_vocab: ['大人', '不安', '自分', '将来'],
    cast: ['aoi_barista', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '蒼さん、大人になるの怖い。', en: "Aoi — scared of becoming an adult.", style: 'soft worried teen girl voice, warm honest vulnerable delivery carefully' },
      { speaker: 'aoi_barista', jp: 'みんな、そう感じるよ。', en: "Everyone feels that.", style: 'gentle adult woman voice, soft warm reassuring delivery carefully' },
      { speaker: 'hina_child', jp: '自分が、わからない。', en: "I don't know myself.", style: 'soft teen girl voice, warm raw honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '時間かけて、見つければいい。', en: "Take your time to find out.", style: 'tender adult woman voice, soft warm wise delivery carefully' },
      { speaker: 'hina_child', jp: '将来、不安で仕方ない。', en: "Anxious about the future.", style: 'soft worried teen girl voice, warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '不安、当然のことよ。', en: "Anxiety — natural.", style: 'warm adult woman voice, soft kind validating delivery carefully' },
      { speaker: 'hina_child', jp: '蒼さんも、若い頃そう?', en: "Were you that way when young?", style: 'curious teen girl voice, soft warm honest inquiry delivered carefully' },
      { speaker: 'aoi_barista', jp: 'もちろん、すごく不安だった。', en: "Of course — really anxious.", style: 'soft adult woman voice, warm honest reflective delivery carefully' },
      { speaker: 'hina_child', jp: 'どうやって、乗り越えた?', en: "How did you get through?", style: 'soft teen girl voice, warm hopeful curious delivery carefully' },
      { speaker: 'aoi_barista', jp: '一日一日、丁寧に過ごした。', en: "Lived each day carefully.", style: 'gentle adult woman voice, soft warm wise delivery carefully' },
      { speaker: 'hina_child', jp: 'そっか、頑張ってみる。', en: "I see — I'll try.", style: 'soft teen girl voice, warm gently encouraged delivery carefully' },
      { speaker: 'aoi_barista', jp: 'いつでも、相談してね。', en: "Always — consult me.", style: 'tender adult woman voice, soft warm loyal delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'soft teen girl voice, warm grateful tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01579',
    context: 'Ryosuke-dad helps Mei plan a small surprise birthday for Daichi.',
    purpose: 'Father supporting daughter in spousal-celebration planning.',
    ambient: 'kitchen_planning_low',
    sound_effects: [],
    target_vocab: ['誕生日', 'プレゼント', '計画', '驚く'],
    cast: ['ryosuke_dad', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'お父さん、大ちゃんの誕生日、計画してる。', en: "Dad — planning Daichi's birthday.", style: 'cheerful young woman voice, soft warm conspiratorial delivery carefully' },
      { speaker: 'ryosuke_dad', jp: 'ええなぁ、プレゼントは?', en: "Lovely — what's the gift?", style: 'warm father voice, soft fond interested delivery carefully' },
      { speaker: 'mei_romantic', jp: '手作りのアルバムを。', en: "A handmade album.", style: 'soft young woman voice, warm proud tender delivery carefully' },
      { speaker: 'ryosuke_dad', jp: 'それは、喜ぶで。', en: "He'll be thrilled.", style: 'gentle father voice, soft warm certain delivery carefully' },
      { speaker: 'mei_romantic', jp: '驚かせたいの、絶対に。', en: "Want to surprise — definitely.", style: 'bright young woman voice, soft warm scheming delivery carefully' },
      { speaker: 'ryosuke_dad', jp: '俺も、手伝うで。', en: "I'll help too.", style: 'warm father voice, soft fond supportive delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、お父さん!', en: "Thanks — Dad!", style: 'tender young woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01580',
    context: 'Riku-teen tries out for a school sports team; Hiroshi-boss happens to coach.',
    purpose: 'Authoritative coach giving sharp but warm feedback.',
    ambient: 'gym_practice_low',
    sound_effects: [],
    target_vocab: ['練習', '部活', '挑戦', '努力'],
    cast: ['hiroshi_boss', 'riku_teen'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '今日の練習、良かったぞ。', en: "Today's practice — good.", style: 'authoritative coach voice, soft warm proud delivery carefully' },
      { speaker: 'riku_teen', jp: 'ほんとですか?やった!', en: "Really? Yes!", style: 'thrilled teen boy voice, bright cheerful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '挑戦する姿勢、評価する。', en: "Your willingness to try — admirable.", style: 'firm coach voice, soft warm professional praise delivered carefully' },
      { speaker: 'riku_teen', jp: '努力、続けます!', en: "I'll keep working!", style: 'committed teen boy voice, bright warm determined delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'うん、その意気や。', en: "Yeah — that spirit.", style: 'warm coach voice, soft encouraging delivery carefully' },
    ],
  },
  {
    id: 'conv_01581',
    context: 'Sakura visits a pottery workshop; chats with the potter Tatsuya.',
    purpose: 'Writer interviewing rural craftsman about craft philosophy.',
    ambient: 'workshop_wheel_low',
    sound_effects: [],
    target_vocab: ['陶芸', '土', '形', '完成'],
    cast: ['sakura_teen', 'tatsuya_country'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '陶芸、何年されてますか?', en: "How many years in pottery?", style: 'gentle adult writer voice, soft warm respectful inquiry delivered carefully' },
      { speaker: 'tatsuya_country', jp: '三十年、毎日土触ってる。', en: "Thirty years — clay daily.", style: 'slow Tohoku voice, soft warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: '土、生き物のようですね。', en: "Clay — like a living thing.", style: 'soft adult writer voice, warm awed appreciative delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ほんま、毎回違うんや。', en: "Truly — each time different.", style: 'gentle Tohoku farmer voice, soft warm wise delivery carefully' },
      { speaker: 'sakura_teen', jp: '形、決めるの難しい?', en: "Hard to settle on shape?", style: 'curious adult writer voice, soft warm interested delivery carefully' },
      { speaker: 'tatsuya_country', jp: '土が、形を教えてくれる。', en: "Clay teaches the shape.", style: 'soft Tohoku voice, warm philosophical reverent delivery carefully' },
      { speaker: 'sakura_teen', jp: '完成、いつ感じます?', en: "When do you feel it's finished?", style: 'engaged adult writer voice, soft warm curious delivery carefully' },
    ],
  },
  {
    id: 'conv_01582',
    context: 'Mrs. Mori brings flowers from her garden to Yumiko\'s house.',
    purpose: 'Two older women sharing simple seasonal gift.',
    ambient: 'genkan_morning_quiet',
    sound_effects: [],
    target_vocab: ['花', '咲く', '庭', '春'],
    cast: ['mrs_mori_neighbor', 'yumiko_mom'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: '庭の花、咲いたの。', en: "Garden flowers bloomed.", style: 'warm older neighbor voice, soft cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、綺麗ね!', en: "Oh — beautiful!", style: 'gentle older mother voice, soft warm awed delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '春が来たのよ、本当に。', en: "Spring's here — truly.", style: 'soft older woman voice, warm reflective delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'いただきます、活けます。', en: "I'll receive them — arrange them.", style: 'warm older mother voice, soft grateful delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふふ、楽しんでね。', en: "Heh — enjoy.", style: 'gentle older neighbor voice, soft warm friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_01583',
    context: 'Kenji walks Hina-young to school in a thunderstorm; comforting talk.',
    purpose: 'Uncle figure walking child through fear.',
    ambient: 'street_storm_umbrella',
    sound_effects: [],
    target_vocab: ['雷', '傘', '怖い', '一緒'],
    cast: ['kenji_office', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '健司おじちゃん、雷怖い。', en: "Kenji-ojichan — thunder's scary.", style: 'soft teen girl voice, warm small honest delivery carefully' },
      { speaker: 'kenji_office', jp: '大丈夫、傘一緒に持っとこ。', en: "It's okay — let's share the umbrella.", style: 'warm Kansai man voice, soft tender protective delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、安心する。', en: "Thanks — feels safer.", style: 'soft teen girl voice, warm grateful relieved delivery carefully' },
      { speaker: 'kenji_office', jp: 'おじちゃんおるから、心配いらん。', en: "Ojichan's here — no worries.", style: 'soft Kansai man voice, warm tender brave delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、ありがとうね。', en: "Yeah — thanks.", style: 'soft teen girl voice, warm tender grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01584',
    context: 'Daichi reads Sho-young a bedtime story about a brave farmer.',
    purpose: 'Father reading to child; gentle bedtime ritual.',
    ambient: 'bedroom_lamp_warm',
    sound_effects: [],
    target_vocab: ['物語', '読む', '勇気', '主人公'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、物語読んで。', en: "Dad — read a story.", style: 'soft sleepy child boy voice, warm tender delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'よっしゃ、この本でええか?', en: "Sure — this book okay?", style: 'warm Kansai father voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、勇気の話がいい。', en: "Yeah — a bravery story.", style: 'soft child boy voice, warm hopeful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'これ、農家の主人公や。', en: "This one — a farmer hero.", style: 'gentle Kansai father voice, soft warm delivery carefully' },
      { speaker: 'sho_child', jp: 'わくわくする!', en: "Exciting!", style: 'bright child boy voice, soft cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01585',
    context: 'Aoi and Hiroshi-boss meet briefly about a community cafe sponsorship.',
    purpose: 'Polite professional negotiation in a calm setting.',
    ambient: 'office_quiet_window',
    sound_effects: [],
    target_vocab: ['援助', '地域', '提案', '感謝'],
    cast: ['aoi_barista', 'hiroshi_boss'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '社長、ご援助、感謝しています。', en: "Boss — grateful for your support.", style: 'gracious adult woman voice, soft warm formal sincere delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '地域のため、当然です。', en: "For the community — natural.", style: 'measured boss voice, soft warm professional humble delivery carefully' },
      { speaker: 'aoi_barista', jp: '次のイベント、提案あります。', en: "Have a proposal for the next event.", style: 'composed adult woman voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '伺いますよ、お聞かせを。', en: "I'll hear it — go on.", style: 'professional boss voice, soft warm receptive delivery carefully' },
      { speaker: 'aoi_barista', jp: '地元の音楽家、紹介したい。', en: "Want to introduce local musicians.", style: 'warm adult woman voice, soft engaged earnest delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'いい案ですね、賛成です。', en: "Good idea — I agree.", style: 'warm boss voice, soft approving professional delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとうございます、進めます。', en: "Thank you — I'll proceed.", style: 'gracious adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_079 wrote', CONVERSATIONS.length, 'files');
