import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_113)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02241',
    context: 'Daichi reads a weather report; concerned about a heavy rain.',
    purpose: 'Married couple discussing weather worry.',
    ambient: 'living_room_morning_low',
    sound_effects: [],
    target_vocab: ['大雨', '予期', '準備', '心配', '台風', '注意', 'ふだん', '対策'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、大雨、来そうやで。', en: "Mei — heavy rain, coming.", style: 'soft Kansai husband voice, warm warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、台風、予期しないと。', en: "Oh — typhoon, must anticipate.", style: 'gentle young wife voice, soft warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ふだんから、準備しとくのが大事や。', en: "Usually — prepare, matters.", style: 'warm Kansai husband voice, soft warm practical delivery carefully' },
      { speaker: 'mei_romantic', jp: '心配だけど、対策、しっかりね。', en: "Worried but — measures, properly.", style: 'tender young wife voice, soft warm caring delivery carefully' },
      { speaker: 'daichi_kansai', jp: '注意、ようけ必要や。', en: "Caution — much needed.", style: 'soft Kansai husband voice, warm warm focused delivery carefully' },
      { speaker: 'mei_romantic', jp: '皆、無事でありたいね。', en: "All — want safe.", style: 'soft young wife voice, warm warm hopeful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、二人で、乗り切ろう。', en: "Yeah — two, get through.", style: 'tender Kansai husband voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02242',
    context: 'Sho-young breaks his arm; Saito treats him gently.',
    purpose: 'Doctor caring for injured child.',
    ambient: 'clinic_quiet_low',
    sound_effects: [],
    target_vocab: ['骨折', '処方', '冷却', '優しい', '安心', '回復', '心配', '丁寧'],
    cast: ['saito_doctor', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '翔くん、骨折、心配いりません。', en: "Sho — fracture, no worry.", style: 'measured doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: '先生、痛いよ。', en: "Doctor — hurts.", style: 'tearful child boy voice, soft warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '冷却、しながら、優しい薬、処方します。', en: "Cooling — while, gentle medicine, prescribe.", style: 'tender doctor voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: 'いつ、回復する?', en: "When — recover?", style: 'soft worried child boy voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '丁寧に、休めば、すぐ良くなるよ。', en: "Carefully — rest, soon better.", style: 'warm doctor voice, soft warm gentle delivery carefully' },
      { speaker: 'sho_child', jp: '安心した、ありがとう先生!', en: "Relieved — thanks doctor!", style: 'soft tender child boy voice, warm warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'お母さん、心配しないでね。', en: "Mom — don't worry.", style: 'gentle doctor voice, soft warm reassuring delivery carefully' },
    ],
  },
  {
    id: 'conv_02243',
    context: 'Aoi packs a gift carefully for a friend\'s birthday.',
    purpose: 'Adult woman thoughtfully preparing gift.',
    ambient: 'kitchen_table_lamp',
    sound_effects: [],
    target_vocab: ['包装', '誓い', '愛情', '心', '気持ち', '丁寧', '渡す', '友人'],
    cast: ['aoi_barista', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'ひな、贈り物の包装、手伝ってくれる?', en: "Hina — gift wrap, help?", style: 'soft adult woman voice, warm warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: 'もちろん!愛情、こもってますね。', en: "Of course — love, contained.", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: '誓いを込めて、贈るの。', en: "Vow contained — gift.", style: 'tender adult woman voice, soft warm reverent delivery carefully' },
      { speaker: 'hina_child', jp: '丁寧な気持ち、伝わるね。', en: "Careful feeling — conveys.", style: 'soft teen girl voice, warm warm appreciative delivery carefully' },
      { speaker: 'aoi_barista', jp: 'お友人、心、喜ぶといいな。', en: "Friend — heart, pleased good.", style: 'gentle adult woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'hina_child', jp: 'こうやって、渡すの、素敵!', en: "Like this — hand, lovely!", style: 'tender teen girl voice, soft warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、お前と一緒で、嬉しい。', en: "Heh — with you, happy.", style: 'warm adult woman voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02244',
    context: 'Naoko teaches Hina-young to make a simple homemade pizza.',
    purpose: 'Aunt teaching teen cooking experimentally.',
    ambient: 'kitchen_warm_busy',
    sound_effects: [],
    target_vocab: ['試みる', '生地', '焼い', '凝っ', '熱い', '厚い', '味', '工夫'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、ピザの生地、試みるで!', en: "Hina — pizza dough, attempt!", style: 'animated Kansai aunt voice, bright warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: '厚いの、薄いの、どっちが好き?', en: "Thick, thin — which like?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: '凝った味付け、ようけしたいねん。', en: "Elaborate seasoning — much want.", style: 'soft Kansai aunt voice, warm warm enthusiastic delivery carefully' },
      { speaker: 'hina_child', jp: '熱いオーブン、ちょうどいいかな?', en: "Hot oven — just right?", style: 'engaged teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: '焼いて、ええ味、出るで、絶対!', en: "Baking — fine taste, comes, definitely!", style: 'warm Kansai aunt voice, soft warm confident delivery carefully' },
      { speaker: 'hina_child', jp: '工夫、もっとできるかな?', en: "Ingenuity — more can?", style: 'eager teen girl voice, bright warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ええ感心や、お前!', en: "Fine impressed — you!", style: 'tender Kansai aunt voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02245',
    context: 'Yumiko and Hiroshi-elder talk about plans for their old age.',
    purpose: 'Married elders discussing life arc.',
    ambient: 'tatami_evening_quiet',
    sound_effects: [],
    target_vocab: ['老後', '寛容', '感謝', '長年', '人生', '深く', '尽くし', '生きる'],
    cast: ['yumiko_mom', 'hiroshi_elder'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'おじいちゃん、老後、どう過ごす?', en: "Grandpa — old age, how spend?", style: 'soft older mother voice, warm reflective delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、寛容な心、持って生きたい。', en: "Yeah — generous heart, hold live.", style: 'slow elder Kansai voice, warm warm philosophical delivery carefully' },
      { speaker: 'yumiko_mom', jp: '感謝、ようけ、毎日感じる。', en: "Gratitude — much, daily feel.", style: 'tender older mother voice, soft warm content delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '長年、家族に尽くしてきた人生や。', en: "Long years — family devoted life.", style: 'gentle elder Kansai voice, soft warm reflective delivery carefully' },
      { speaker: 'yumiko_mom', jp: '深く、こうやって過ごせる時間、宝物。', en: "Deeply — like this spend time, treasure.", style: 'soft older mother voice, warm warm grateful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前と、最後まで、楽しく生きよう。', en: "With you — end until, happily live.", style: 'tender elder Kansai voice, soft warm loving delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、約束ね。', en: "Yeah — promise.", style: 'tender older mother voice, soft warm enduring delivery carefully' },
    ],
  },
  {
    id: 'conv_02246',
    context: 'Sakura watches birds in a garden; reflective writer moment.',
    purpose: 'Author observing nature alone with companion.',
    ambient: 'garden_morning_birds',
    sound_effects: [],
    target_vocab: ['漂う', '鳩', '泳い', '木々', '至り', 'まね', '素早く', '皮'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、鳩、群れ、漂ってるね。', en: "Ren — pigeon, flock, drifting.", style: 'soft adult writer voice, warm warm reflective delivery carefully' },
      { speaker: 'ren_uni', jp: '木々の間、泳いでるみたいに飛んでる。', en: "Tree between — swimming-like flying.", style: 'gentle young man voice, soft warm awed delivery carefully' },
      { speaker: 'sakura_teen', jp: '素早く、まねできない動き。', en: "Quickly — can't mimic movement.", style: 'composed adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'ren_uni', jp: '皮、薄い、強い力、感じる。', en: "Skin — thin, strong power, feel.", style: 'soft young man voice, warm warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '至るところ、自然の不思議。', en: "Everywhere — nature mystery.", style: 'tender adult writer voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '記事に、書きませんか?', en: "Article — write?", style: 'engaged young man voice, soft warm collaborative delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、心、こめて。', en: "Yeah — heart, put.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02247',
    context: 'Kenji and Aoi sip morning tea; conversation about life.',
    purpose: 'Couple in quiet morning reflection.',
    ambient: 'kitchen_morning_quiet',
    sound_effects: [],
    target_vocab: ['ふだん', '生きる', '愛情', '寛容', '深く', '時代', '関わり', '尽くし'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '蒼、ふだんの朝、こうやって、ええなぁ。', en: "Aoi — usual morning, like this, fine.", style: 'soft Kansai husband voice, warm warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: '寛容な気持ち、持って、生きていきたい。', en: "Generous feeling — hold, want live.", style: 'tender adult woman voice, soft warm philosophical delivery carefully' },
      { speaker: 'kenji_office', jp: '深く愛情、感じる時間や。', en: "Deeply love — feel time.", style: 'warm Kansai man voice, soft warm tender delivery carefully' },
      { speaker: 'aoi_barista', jp: '時代の中、こうやって、繋がる関わり。', en: "In era — like this, connecting bond.", style: 'gentle adult woman voice, soft warm reverent delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前に、ようけ尽くしてもらった。', en: "You — much devoted got.", style: 'soft Kansai husband voice, warm warm humble delivery carefully' },
      { speaker: 'aoi_barista', jp: 'お互いに、ね。', en: "Each — yeah.", style: 'tender adult woman voice, soft warm united delivery carefully' },
      { speaker: 'kenji_office', jp: 'これからも、ずっと。', en: "Going forward — always.", style: 'tender Kansai husband voice, soft warm enduring delivery carefully' },
    ],
  },
  {
    id: 'conv_02248',
    context: 'Sho-young plays with a small dog; tells Mei about the moment.',
    purpose: 'Child sharing simple joy with mother.',
    ambient: 'park_afternoon_birds',
    sound_effects: [],
    target_vocab: ['犬', 'お出かけ', '愛情', '素早く', 'まね', '楽しい', '尻尾', '皆'],
    cast: ['sho_child', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、犬、見たよ、お出かけで!', en: "Mom — dog, saw, outing!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、可愛い犬?', en: "Oh — cute dog?", style: 'gentle young mother voice, soft warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: '素早く、走って、まねできなかった!', en: "Quickly — ran, couldn't mimic!", style: 'animated child boy voice, bright warm awed delivery carefully' },
      { speaker: 'mei_romantic', jp: '尻尾、ようけ振ってた?', en: "Tail — much waved?", style: 'soft young mother voice, warm warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '愛情、いっぱい、感じた!', en: "Love — full, felt!", style: 'bright child boy voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '皆と楽しく、過ごせて、良かったね。', en: "All happily — spent, good.", style: 'tender young mother voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '本当に、楽しかった!', en: "Truly — fun!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02249',
    context: 'Hina-young finishes a school project; reflects with Ren about it.',
    purpose: 'Teen sharing achievement with mentor.',
    ambient: 'study_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['過ち', '改良', '分かれる', '頑張る', '努力', '理科', '感謝', '将来'],
    cast: ['hina_child', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '蓮くん、理科の宿題、ようやく終わった!', en: "Ren — science homework, finally finished!", style: 'bright teen girl voice, soft warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: '頑張りましたね、努力、伝わる。', en: "Tried — effort, conveys.", style: 'warm young man voice, soft warm appreciative delivery carefully' },
      { speaker: 'hina_child', jp: '過ち、ようけしたけど、改良した。', en: "Mistake — much did, improved.", style: 'soft committed teen girl voice, warm warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '結果と過程、分かれることも、大事。', en: "Result and process — separate, matters.", style: 'gentle young man voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: '将来、研究、続けたいかも。', en: "Future — research, want continue maybe.", style: 'tender teen girl voice, soft warm dreamy delivery carefully' },
      { speaker: 'ren_uni', jp: '感謝、ようけ、伝えてあげて。', en: "Gratitude — much, convey.", style: 'soft young man voice, warm warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、頑張ります!', en: "Yes — try!", style: 'soft determined teen girl voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02250',
    context: 'Tatsuya-country tells Asuka about an old village proverb.',
    purpose: 'Elder sharing traditional wisdom.',
    ambient: 'porch_evening_quiet',
    sound_effects: [],
    target_vocab: ['昔', '言葉', '寛容', '長年', '知識', '理不尽', '生きる', '尊重'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: 'あすか、昔の言葉、ようけある。', en: "Asuka — old words, much exists.", style: 'slow Tohoku farmer voice, warm warm reflective delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'どんな知識、伝えたい?', en: "What knowledge — want convey?", style: 'gentle teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: '寛容に生きる、長年、村の教え。', en: "Generously live — long years, village teaching.", style: 'soft Tohoku voice, warm warm philosophical delivery carefully' },
      { speaker: 'asuka_teacher', jp: '理不尽なこと、ようけある、世の中。', en: "Unreasonable — much exist, world.", style: 'thoughtful teacher voice, soft warm honest delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お互い、尊重して、生きるもんや。', en: "Each — respect, live.", style: 'firm Tohoku farmer voice, soft warm wise delivery carefully' },
      { speaker: 'asuka_teacher', jp: '若い人にも、伝えていきたいね。', en: "Young people too — want convey.", style: 'tender teacher voice, soft warm committed delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、ええ姿勢や、お前。', en: "Yeah — fine stance, you.", style: 'warm Tohoku voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02251',
    context: 'Daichi gets a Christmas surprise gift; tender reaction.',
    purpose: 'Husband receiving thoughtful surprise.',
    ambient: 'living_room_holiday_warm',
    sound_effects: [],
    target_vocab: ['頂戴', '感謝', '愛情', '心', '丁寧', '包装', '誓い', '気持ち'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、これ、頂戴!', en: "Daichi — this, receive!", style: 'soft young wife voice, warm warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'えっ、なんやろう?', en: "Eh — what?", style: 'awed Kansai husband voice, soft warm surprised delivery carefully' },
      { speaker: 'mei_romantic', jp: '愛情、心、こめて、丁寧に包装した。', en: "Love — heart, put, carefully wrapped.", style: 'tender young wife voice, soft warm proud delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ほんま、感謝、ようけや!', en: "Truly — gratitude, much!", style: 'soft Kansai husband voice, warm warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '誓い、ずっとお互い、愛し合おうね。', en: "Vow — always each, love.", style: 'tender young wife voice, soft warm reverent delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前の気持ち、深く伝わる。', en: "Your feeling — deeply conveys.", style: 'tender Kansai husband voice, soft warm loving delivery carefully' },
      { speaker: 'mei_romantic', jp: '一生、一緒よ。', en: "Lifetime — together.", style: 'tender young wife voice, soft warm enduring delivery carefully' },
    ],
  },
  {
    id: 'conv_02252',
    context: 'Saito reflects on retiring; quiet conversation with Asuka.',
    purpose: 'Two old friends discussing career end.',
    ambient: 'porch_evening_lamp',
    sound_effects: [],
    target_vocab: ['老後', '退職', '人生', '寛容', '関わり', '感謝', '尽くし', '生きる'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'あすか、退職後、何をしようか。', en: "Asuka — post-retirement, what?", style: 'measured doctor voice, soft warm reflective delivery carefully' },
      { speaker: 'asuka_teacher', jp: '老後、寛容に、楽しく生きたい。', en: "Old age — generously, fun live.", style: 'gentle teacher voice, soft warm content delivery carefully' },
      { speaker: 'saito_doctor', jp: '長い人生、皆さんに尽くしてきた。', en: "Long life — all devoted.", style: 'soft doctor voice, warm warm humble delivery carefully' },
      { speaker: 'asuka_teacher', jp: '関わり、感謝、いっぱい残ってる。', en: "Bonds — gratitude, full remains.", style: 'tender teacher voice, soft warm appreciative delivery carefully' },
      { speaker: 'saito_doctor', jp: 'これからは、二人で、ようけ過ごそう。', en: "Now — two, much spend.", style: 'warm doctor voice, soft warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: '感謝の毎日、続けていきたいね。', en: "Grateful daily — want continue.", style: 'soft teacher voice, warm warm committed delivery carefully' },
      { speaker: 'saito_doctor', jp: 'うん、約束。', en: "Yeah — promise.", style: 'tender doctor voice, soft warm enduring delivery carefully' },
    ],
  },
  {
    id: 'conv_02253',
    context: 'Naoko explains a regional dish to a new tourist customer.',
    purpose: 'Aunt warmly explaining Kansai food to visitor.',
    ambient: 'ramen_shop_busy',
    sound_effects: [],
    target_vocab: ['定食', '味付け', '濃い', '伝統', '関西', '皮', '地方', '丁寧'],
    cast: ['naoko_aunt', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'おばさん、定食、いただきます。', en: "Auntie — set meal, receive.", style: 'soft polite young man voice, warm warm respectful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、関西の伝統、味わってや!', en: "Yeah — Kansai tradition, taste!", style: 'brassy Kansai aunt voice, bright warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: '味付け、濃い感じ、しますね。', en: "Seasoning — dense feel.", style: 'gentle young man voice, soft warm appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '地方によって、味、違うで、皆。', en: "By region — taste, differ, all.", style: 'warm Kansai aunt voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: '皮、丁寧に作ってますね。', en: "Skin — carefully made.", style: 'soft young man voice, warm warm impressed delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ようけ、毎日、ええもん作っとる!', en: "Much — daily, fine thing making!", style: 'animated Kansai aunt voice, bright warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、本当にうまい!', en: "Thanks — truly tasty!", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02254',
    context: 'Hiroshi-elder watches a sumo championship; explains to Sho-young.',
    purpose: 'Grandfather teaching child tradition.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['闘う', '皮', '伝統', '尊重', '勝負', '長年', '我々', '熱心'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、力士、皮、すごい!', en: "Grandpa — wrestler, skin, amazing!", style: 'awed child boy voice, bright warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、闘うのは、伝統や。', en: "Yeah — fighting, tradition.", style: 'slow elder Kansai voice, warm warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '勝負、長年、続いとるのね。', en: "Match — long years, continues.", style: 'thoughtful child boy voice, soft warm understanding delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '我々、尊重しとる文化や。', en: "We — respect culture.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '熱心に応援する、お父さん!', en: "Passionately cheer — Dad!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前も、いつか、好きになるで。', en: "You too — someday, become like.", style: 'tender elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、面白い!', en: "Yeah — fun!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02255',
    context: 'Mei plans a trip to a hot spring with Yumiko.',
    purpose: 'Two women planning relaxing getaway.',
    ambient: 'living_room_lamp_quiet',
    sound_effects: [],
    target_vocab: ['温泉', '老後', '寛容', '気軽', 'お出かけ', '愛情', '時代', '深く'],
    cast: ['mei_romantic', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'お母さん、温泉、お出かけしましょう。', en: "Mom — hot spring, go out.", style: 'soft young woman voice, warm warm cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、嬉しい、ようけ気軽に。', en: "Oh — happy, much casually.", style: 'tender older mother voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '老後、お母さんと、深く時間過ごしたい。', en: "Old age — Mom with, deeply spend.", style: 'gentle young woman voice, soft warm earnest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '愛情、ようけ感じるわ。', en: "Love — much feel.", style: 'soft older mother voice, warm warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '時代、変わっても、家族、大事ね。', en: "Era — change, family, matters.", style: 'tender young mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'yumiko_mom', jp: '寛容な気持ち、お互い持ちましょう。', en: "Generous feeling — each hold.", style: 'tender older mother voice, soft warm wise delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、必ず、行こうね。', en: "Yeah — surely, go.", style: 'soft committed young woman voice, warm warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02256',
    context: 'Sakura takes notes about old folk tales; consults Hiroshi-elder.',
    purpose: 'Writer gathering oral history from elder.',
    ambient: 'tatami_lamp_evening',
    sound_effects: [],
    target_vocab: ['昔話', '伝説', '寛容', '深い', '尊重', '老人', '長年', '感謝'],
    cast: ['sakura_teen', 'hiroshi_elder'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'おとうさん、昔話、教えてください。', en: "Otosan — folk tale, teach.", style: 'humble adult writer voice, soft warm respectful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '長年、伝わる伝説、ようけある。', en: "Long years — passed legend, much.", style: 'slow elder Kansai voice, warm warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: '寛容な物語、印象的でしたね。', en: "Generous story — impressive.", style: 'soft adult writer voice, warm warm appreciative delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '深い知恵、老人から、若者に伝える。', en: "Deep wisdom — elder from, youth convey.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '尊重して、書かせていただきます。', en: "Respecting — let write.", style: 'reverent adult writer voice, soft warm committed delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '感謝、ようけ伝えとくれ、お前。', en: "Gratitude — much convey, you.", style: 'tender elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、必ず、心をこめて。', en: "Yes — surely, heart put.", style: 'soft adult writer voice, warm warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_02257',
    context: 'Aoi reads about a new cafe opening up in another town.',
    purpose: 'Business owner reading industry news.',
    ambient: 'cafe_morning_low',
    sound_effects: [],
    target_vocab: ['開き', '時代', '尽くし', '経営', '深く', '気軽', '関わり', '皆さん'],
    cast: ['aoi_barista', 'yuki_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'ゆきさん、新しいカフェ、開きを知った?', en: "Yuki — new cafe, opening know?", style: 'soft adult woman voice, warm warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: '記事で読んだ、深く尽くしてる経営。', en: "Article read — deeply devoted management.", style: 'composed office woman voice, soft warm informative delivery carefully' },
      { speaker: 'aoi_barista', jp: '時代の流れ、勉強になる。', en: "Era flow — learning.", style: 'gentle adult woman voice, soft warm reflective delivery carefully' },
      { speaker: 'yuki_office', jp: '気軽に、皆さん、関わって来てるね。', en: "Casually — all, involve come.", style: 'soft office woman voice, warm warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うちも、いい関わり、続けていきたい。', en: "We too — fine bond, want continue.", style: 'tender adult woman voice, soft warm committed delivery carefully' },
      { speaker: 'yuki_office', jp: '頑張ってる蒼ちゃん、応援してる。', en: "Trying Aoi-chan — cheering.", style: 'warm office woman voice, soft warm supportive delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'humble adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02258',
    context: 'Ren and Kenji visit a small museum together; cultural outing.',
    purpose: 'Two artist-friends sharing cultural moment.',
    ambient: 'museum_quiet_floor',
    sound_effects: [],
    target_vocab: ['化石', '簡素', '寛容', '尊重', '巨大', '時代', '我々', '深く'],
    cast: ['ren_uni', 'kenji_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '健司さん、化石、巨大ですね!', en: "Kenji — fossil, huge!", style: 'awed young man voice, bright warm impressed delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、長い時代、生きとった生物や。', en: "Yeah — long era, lived creature.", style: 'soft Kansai man voice, warm warm reverent delivery carefully' },
      { speaker: 'ren_uni', jp: '簡素な展示、寛容に楽しめる。', en: "Simple display — generously enjoy.", style: 'gentle young man voice, soft warm content delivery carefully' },
      { speaker: 'kenji_office', jp: '我々の時代、ようけ深く考えるべきや。', en: "Our era — much deeply should think.", style: 'composed Kansai man voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '尊重したい、過去の生き物。', en: "Want respect — past creatures.", style: 'soft young man voice, warm warm reverent delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前と来れて、ええ時間や。', en: "With you came — fine time.", style: 'tender Kansai man voice, soft warm fond delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、深い体験。', en: "Thank you — deep experience.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02259',
    context: 'Hina-young learns a recipe from Mei step-by-step.',
    purpose: 'Mother carefully teaching cooking technique.',
    ambient: 'kitchen_busy_warm',
    sound_effects: [],
    target_vocab: ['ふだん', '丁寧', '焼い', '熱い', '凝っ', '味', '工夫', '楽しい'],
    cast: ['mei_romantic', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'ひな、ふだん、こうやって作るの。', en: "Hina — usually, like this make.", style: 'gentle young mother voice, soft warm teaching delivery carefully' },
      { speaker: 'hina_child', jp: 'メイさん、丁寧に焼いてますね。', en: "Mei — carefully baking.", style: 'soft attentive teen girl voice, warm warm observant delivery carefully' },
      { speaker: 'mei_romantic', jp: '熱い火、注意しながらね。', en: "Hot fire — careful while.", style: 'warm young mother voice, soft warm cautious delivery carefully' },
      { speaker: 'hina_child', jp: '凝った味、出すの、好き!', en: "Elaborate taste — bring, love!", style: 'bright teen girl voice, soft warm eager delivery carefully' },
      { speaker: 'mei_romantic', jp: '工夫が、料理を楽しくするわよ。', en: "Ingenuity — cooking fun makes.", style: 'tender young mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: '味、ようけ実験したい!', en: "Taste — much experiment want!", style: 'eager teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '楽しいわね、料理。', en: "Fun — cooking.", style: 'warm young mother voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_02260',
    context: 'Whole group gathers around an old photo album; many memories.',
    purpose: 'Multi-voice nostalgic family scene.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['思い出', '愛情', '皆', '深く', '感謝', '長年', '時代', '振り返っ'],
    cast: ['yumiko_mom', 'hiroshi_elder', 'mei_romantic', 'daichi_kansai', 'sho_child', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '皆、この写真、振り返ってみて。', en: "All — this photo, look back.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ふふ、長年の思い出、ようけ詰まっとる。', en: "Heh — long-year memories, much packed.", style: 'slow elder Kansai voice, warm warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '深く愛情、感じるね、皆と。', en: "Deeply love — feel, all with.", style: 'tender young mother voice, soft warm reverent delivery carefully' },
      { speaker: 'daichi_kansai', jp: '時代、ようけ流れたなぁ。', en: "Era — much flowed.", style: 'soft Kansai husband voice, warm warm reflective delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼく、ようけ小さい!', en: "I — much small!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'hina_child', jp: 'おばあちゃん、若いとき、綺麗!', en: "Grandma — young time, pretty!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、感謝の毎日、本当に。', en: "Heh — grateful daily, truly.", style: 'tender older mother voice, soft warm humble delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '皆おって、ええ家族や、ほんま。', en: "All here — fine family, truly.", style: 'warm elder Kansai voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: '振り返ると、感謝、いっぱい。', en: "Looking back — gratitude, full.", style: 'soft young mother voice, warm warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'これからも、皆と、過ごしような。', en: "Going forward — all, spend.", style: 'warm Kansai husband voice, soft warm committed delivery carefully' },
      { speaker: 'sho_child', jp: '皆、大好き!', en: "All — love!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'こうやって、長く、続けてほしい。', en: "Like this — long, want continue.", style: 'tender teen girl voice, soft warm wishful delivery carefully' },
      { speaker: 'yumiko_mom', jp: '家族、宝物、ようけ。', en: "Family — treasure, much.", style: 'tender older mother voice, soft warm enduring delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_113 wrote', CONVERSATIONS.length, 'files');
