import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_150)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // count-2 theater/cafe cluster (劇場 開か かける ティー + おっしゃる 肌) ×3
  C('conv_02981',
    'Mei and Aoi plan an evening at the theater.',
    'WIDENED SCENARIO: leisure chat; vocabulary (劇場/開か/かける/ティー/おっしゃる) in natural home.',
    'cafe_quiet_chatter',
    ['劇場', '開か', 'かける', 'ティー', 'おっしゃる'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '今夜、劇場でお芝居を観るの。', en: "Tonight I'll see a play at the theater.", style: 'soft warm woman voice, gentle excited delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね!何時に開かれるの?', en: "Nice! When does it open?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '七時に、幕が開かれるの。', en: "The curtain rises at seven.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'チケットに、お金かけたんでしょ?', en: "You spent money on the ticket, right?", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、良い席にかけちゃった。', en: "Yeah, I splurged on a good seat.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '前に観た俳優、何ておっしゃってた?', en: "What did the actor you saw before say?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '「また劇場で」と、おっしゃってたわ。', en: "He said 'see you at the theater again.'", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '帰りに、ミルクティー飲もうね!', en: "On the way back, let's have milk tea!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02982',
    'Sakura interviews a theater director.',
    'WIDENED SCENARIO: arts interview; vocabulary (劇場/開か/かける/ティー/おっしゃる) in natural home.',
    'office_quiet_low',
    ['劇場', '開か', 'かける', 'ティー', 'おっしゃる'],
    ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '新しい劇場が、開かれるそうですね。', en: "I hear a new theater is opening.", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、来月、初公演が開かれます。', en: "Yes, the first show opens next month.", style: 'composed director voice, soft warm gentle clarity throughout' },
      { speaker: 'sakura_teen', jp: '準備に、どれくらいかけましたか?', en: "How long did preparation take?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '二年を、かけて作り上げました。', en: "We spent two years building it.", style: 'gentle director voice, soft warm clarity throughout' },
      { speaker: 'sakura_teen', jp: '俳優の皆さんは、何とおっしゃってますか?', en: "What do the actors say?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '良い劇場だと、おっしゃっています。', en: "They say it's a good theater.", style: 'composed director voice, soft warm gentle clarity throughout' },
      { speaker: 'sakura_teen', jp: 'ロビーで、ティーも出るんですか?', en: "Is tea served in the lobby too?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、開演前にティーをどうぞ。', en: "Yes, please enjoy tea before the show.", style: 'warm director voice, soft warm gentle closing clarity throughout' },
    ]),

  C('conv_02983',
    'Ren and Mei recall a play they saw.',
    'Casual register; vocabulary (劇場/開か/かける/ティー/肌) in natural home.',
    'cafe_quiet_chatter',
    ['劇場', '開か', 'かける', 'ティー', '肌'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの劇場のお芝居、感動したね。', en: "That theater's play was moving.", style: 'soft warm woman voice, gentle moved delivery throughout' },
      { speaker: 'ren_uni', jp: '幕が開かれた瞬間、鳥肌が立ったよ。', en: "The moment the curtain opened, I got goosebumps.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '私も、肌で感動を覚えたの。', en: "I felt the emotion in my skin too.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'いい席に、お金をかけて正解だったね。', en: "Spending on good seats was the right call.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '次は、別の劇場にも行きたいな。', en: "Next I want to go to a different theater too.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '帰りに飲んだティー、おいしかったね。', en: "The tea we drank on the way back was good.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '幕が開かれるドキドキ、また味わいたい。', en: "I want to feel that curtain-rising thrill again.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '時間をかけて、また観に行こうよ。', en: "Let's take our time and go see one again.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-4/3 cleanup (目指す 恋 乗る 問わ 層 無く)
  C('conv_02984',
    'Mei and Aoi chat about chasing a dream.',
    'Casual register; vocabulary (目指す/恋/乗る/問わ/無く) in natural home.',
    'cafe_quiet_chatter',
    ['目指す', '恋', '乗る', '問わ', '無く'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '私、いつか自分の店を目指してるの。', en: "I'm aiming to have my own shop someday.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '素敵な夢だね。応援するよ。', en: "What a lovely dream. I'll support you.", style: 'soft warm woman voice, gentle delivery throughout' },
      { speaker: 'aoi_barista', jp: '勢いに乗って、頑張りたいんだ。', en: "I want to ride the momentum and work hard.", style: 'enthusiastic barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '年齢を問わず、夢は持てるよね。', en: "Regardless of age, you can have dreams.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'お金が無くても、工夫すればいいよね。', en: "Even without money, you can be resourceful.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '恋も夢も、大事にしたいな。', en: "I want to cherish both love and dreams.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '迷いが無くなったら、すぐ動くよ。', en: "Once my doubts are gone, I'll act right away.", style: 'determined barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '目指す場所が、見えてきたね。', en: "The place you're aiming for is coming into view.", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-1 cluster A — daily/casual (再び なんだか びっくり 無駄 いきなり)
  C('conv_02985',
    'Riku tells Aoi about a surprising day.',
    'Casual register; vocabulary (再び/なんだか/びっくり/無駄/いきなり) in natural home.',
    'cafe_quiet_chatter',
    ['再び', 'なんだか', 'びっくり', '無駄', 'いきなり'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '今日、いきなり先生に呼ばれたんだ。', en: "Today the teacher suddenly called me.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'えっ、びっくりしたでしょ?', en: "Huh, you must've been surprised.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、なんだか怒られるかと思った。', en: "Yeah, I somehow thought I'd be scolded.", style: 'rueful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '心配は、無駄だったってこと?', en: "So the worry was for nothing?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'そう、無駄に緊張しちゃったよ。', en: "Right, I got nervous for nothing.", style: 'laughing teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '再び呼ばれたら、また驚くね。', en: "If you're called again, you'll be surprised again.", style: 'playful barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'いきなりだと、びっくりするよなー。', en: "When it's sudden, you do get startled.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'なんだか、笑える話だね!', en: "Somehow, it's a funny story!", style: 'giggly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02986',
    'Mei and Ren recount a surprising reunion.',
    'Casual register; vocabulary (再び/なんだか/びっくり/無駄/いきなり) in natural home.',
    'cafe_quiet_chatter',
    ['再び', 'なんだか', 'びっくり', '無駄', 'いきなり'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '昔の友達に、再び会えたの!', en: "I got to meet an old friend again!", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'ren_uni', jp: 'いきなり、街で会ったの?', en: "Did you meet suddenly in town?", style: 'curious young man voice, soft warm engaged delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、いきなりで、びっくりしたの。', en: "Yeah, it was sudden, and I was surprised.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'なんだか、運命みたいだね。', en: "Somehow, it's like fate.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '連絡先を、無くしてたのに会えたの。', en: "I'd lost the contact, yet we met.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '探す手間が、無駄にならなくて良かったね。', en: "Good that the effort to find them wasn't wasted.", style: 'gentle young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '再び、よく集まろうって話したの。', en: "We agreed to gather often again.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'なんだか、嬉しい一日だったね。', en: "Somehow, it was a happy day.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02987',
    'Sho tells Grandma about a surprise at school.',
    'Casual home register; vocabulary (再び/なんだか/びっくり/無駄/いきなり) in natural home.',
    'tatami_room_quiet',
    ['再び', 'なんだか', 'びっくり', '無駄', 'いきなり'],
    ['sho_child', 'sachiko_grandma'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おばあちゃん、いきなり雨が降ったよ!', en: "Grandma, it suddenly rained!", style: 'animated small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'まあ、びっくりしたでしょう。', en: "Oh my, you must've been startled.", style: 'tender grandmother voice, soft warm gentle delivery throughout' },
      { speaker: 'sho_child', jp: 'うん、傘がなんだか役に立たなくて。', en: "Yeah, my umbrella was somehow useless.", style: 'pouty small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '濡れちゃったの?無駄に走ったのね。', en: "Did you get wet? You ran for nothing.", style: 'gentle grandmother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'でも、再び晴れてきたんだ!', en: "But it cleared up again!", style: 'cheerful small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'なんだか、忙しいお天気ねぇ。', en: "Somehow, the weather's busy, isn't it.", style: 'tender grandmother voice, soft warm amused delivery throughout' },
      { speaker: 'sho_child', jp: 'いきなり虹も、出たんだよ!', en: "A rainbow suddenly came out too!", style: 'delighted small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'それは、びっくりするほど綺麗ね。', en: "That's surprisingly beautiful.", style: 'tender grandmother voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02988',
    'Daichi and Mei laugh about a wasted errand.',
    'Casual register; vocabulary (再び/なんだか/びっくり/無駄/いきなり) in natural home.',
    'cafe_quiet_chatter',
    ['再び', 'なんだか', 'びっくり', '無駄', 'いきなり'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '今日な、いきなり店が閉まっとってん。', en: "Today the shop was suddenly closed.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: 'えっ、びっくりしましたね。', en: "Huh, you must've been surprised.", style: 'soft warm woman voice, gentle delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'わざわざ行ったのに、無駄足やったわ。', en: "I went all that way, and it was a wasted trip.", style: 'rueful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'なんだか、ついてない日でしたね。', en: "Somehow, an unlucky day.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '明日、再び行ってみるわ。', en: "I'll try going again tomorrow.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '再び閉まってたら、笑えますね。', en: "If it's closed again, that'd be funny.", style: 'playful woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'いきなり休みやと、困るわー。', en: "A sudden closure is a pain.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '無駄にならないこと、祈ってます。', en: "I hope it won't be in vain.", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-1 cluster B — science/news (化学 石油 統合 合併 配信)
  C('conv_02989',
    'Economic news: Sakura and Ren on a corporate merger.',
    'WIDENED SCENARIO: business news; vocabulary (化学/石油/統合/合併/配信) in natural home.',
    'studio_room_tone',
    ['化学', '石油', '統合', '合併', '配信'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '大きな化学会社が、合併しました。', en: "A major chemical company merged.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '石油部門も、統合されるんですか?', en: "Will the oil division be integrated too?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、石油と化学が統合されます。', en: "Yes, oil and chemicals will be integrated.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '合併の狙いは、何でしょう?', en: "What's the aim of the merger?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '統合で、競争力を高める狙いです。', en: "The aim is to boost competitiveness through integration.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '会見は、配信もされましたか?', en: "Was the briefing streamed too?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、ネットで配信されました。', en: "Yes, it was streamed online.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '化学業界の合併、注目ですね。', en: "The chemical-industry merger is one to watch.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02990',
    'Asuka lectures on chemistry and oil.',
    'WIDENED SCENARIO: science lecture; vocabulary (化学/石油/統合/合併/配信) in natural home.',
    'lecture_hall_quiet',
    ['化学', '石油', '統合', '合併', '配信'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '石油から、多くの化学製品が作られます。', en: "Many chemical products are made from oil.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '化学って、生活に身近なんですね。', en: "Chemistry is close to daily life.", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、石油は様々な物に統合されます。', en: "Yes, oil is integrated into various things.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '会社が合併するのも、関係しますか?', en: "Does company merging relate to this too?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '化学と石油の合併は、よくあります。', en: "Mergers of chemicals and oil are common.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '授業を、配信で見られますか?', en: "Can I watch the lecture via streaming?", style: 'thoughtful teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、配信で復習できますよ。', en: "Yes, you can review via streaming.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '化学の統合、面白いですね!', en: "The integration of chemistry is fascinating!", style: 'delighted teen boy voice, soft warm bright engaged throughout' },
    ]),

  C('conv_02991',
    'Ren reports an integration plan to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (化学/石油/統合/合併/配信) in natural home.',
    'office_quiet_low',
    ['化学', '石油', '統合', '合併', '配信'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '二つの部門を、統合する案です。', en: "It's a plan to integrate two divisions.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '化学と、どの部門を統合するかね?', en: "Which division do we integrate with chemicals?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '化学と石油の部門を、統合します。', en: "We'll integrate the chemical and oil divisions.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '他社との合併も、視野にあるかね?', en: "Is a merger with another firm in view?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '将来的に、合併も検討しています。', en: "We're considering a merger in the future.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '社内には、どう配信するかね?', en: "How do we announce it internally?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '社内に、動画で配信します。', en: "We'll distribute it internally by video.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '統合で、強い会社を目指そう。', en: "Through integration, let's aim for a strong company.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02992',
    'Ren interviews a chemist about oil research.',
    'WIDENED SCENARIO: science interview; vocabulary (化学/石油/統合/合併/配信) in natural home.',
    'office_quiet_low',
    ['化学', '石油', '統合', '合併', '配信'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '化学の研究、どんな内容ですか?', en: "What does your chemistry research involve?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: '石油に代わる素材を、研究しています。', en: "I research materials to replace oil.", style: 'composed chemist voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '複数の研究を、統合するんですか?', en: "Do you integrate multiple studies?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、知見を統合して進めます。', en: "Yes, we integrate findings to proceed.", style: 'patient chemist voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '研究所同士の合併も、ありますか?', en: "Are there mergers between institutes too?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '合併で、化学の力が集まります。', en: "Through mergers, chemical expertise gathers.", style: 'composed chemist voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '成果は、どこで配信されますか?', en: "Where are the results distributed?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '論文を、ネットで配信しています。', en: "We distribute papers online.", style: 'warm chemist voice, soft warm measured closing clarity throughout' },
    ]),

  // count-1 cluster C — academic (博士 研究所 証明 単語 翻訳)
  C('conv_02993',
    'Sakura interviews a researcher with a doctorate.',
    'WIDENED SCENARIO: academic interview; vocabulary (博士/研究所/証明/単語/翻訳) in natural home.',
    'office_quiet_low',
    ['博士', '研究所', '証明', '単語', '翻訳'],
    ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '博士は、どんな研究所で働いていますか?', en: "What kind of institute do you work at, doctor?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'asuka_teacher', jp: '言語を研究する、研究所です。', en: "An institute that studies language.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '言葉の意味は、どう証明するんですか?', en: "How do you prove word meanings?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '多くの例で、意味を証明します。', en: "We prove meaning with many examples.", style: 'patient researcher voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '難しい単語も、扱うんですか?', en: "Do you handle difficult words too?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '珍しい単語を、研究所で集めます。', en: "We collect rare words at the institute.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '翻訳の研究も、されていますか?', en: "Do you research translation too?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、翻訳の精度を証明しています。', en: "Yes, we prove the accuracy of translation.", style: 'warm researcher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02994',
    'Asuka teaches Ren about vocabulary study.',
    'WIDENED SCENARIO: language lesson; vocabulary (博士/研究所/証明/単語/翻訳) in natural home.',
    'lecture_hall_quiet',
    ['博士', '研究所', '証明', '単語', '翻訳'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '新しい単語、なかなか覚えられません。', en: "I struggle to remember new words.", style: 'troubled young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '単語は、例文と一緒に覚えましょう。', en: "Learn words together with example sentences.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '翻訳して、意味を確かめてもいいですか?', en: "Can I translate to confirm the meaning?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、翻訳で意味を証明できます。', en: "Yes, translation helps prove the meaning.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '博士は、どう単語を覚えたんですか?', en: "How did you memorize words, doctor?", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '研究所で、毎日単語に触れました。', en: "At the institute, I touched words daily.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '翻訳の練習も、効果がありますか?', en: "Is translation practice effective too?", style: 'thoughtful young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '効果は、研究でも証明されています。', en: "Its effect is proven in research too.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02995',
    'Ren and Mei discuss a translated book.',
    'Casual register; vocabulary (博士/研究所/証明/単語/翻訳) in natural home.',
    'cafe_quiet_chatter',
    ['博士', '研究所', '証明', '単語', '翻訳'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この本、翻訳がすごく自然だね。', en: "This book's translation is very natural.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'ren_uni', jp: '訳者は、言語学の博士なんだって。', en: "The translator is a linguistics doctor, I hear.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '難しい単語も、分かりやすいね。', en: "Even hard words are easy to understand.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '研究所で、長く翻訳を学んだそうだよ。', en: "They studied translation at an institute for years.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '言葉の力って、証明されてるね。', en: "The power of words really is proven, isn't it.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '一つの単語に、深い意味があるよね。', en: "A single word holds deep meaning.", style: 'thoughtful young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '翻訳って、研究所の仕事みたいね。', en: "Translation is like institute work.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '博士の苦労が、本に表れてるね。', en: "The doctor's effort shows in the book.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02996',
    'Riku asks Asuka about becoming a researcher.',
    'WIDENED SCENARIO: career chat; vocabulary (博士/研究所/証明/単語/翻訳) in natural home.',
    'lecture_hall_quiet',
    ['博士', '研究所', '証明', '単語', '翻訳'],
    ['riku_teen', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '将来、博士になりたいんです。', en: "I want to become a doctor (PhD) someday.", style: 'eager teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '素敵な夢ですね。研究所で働けますよ。', en: "A lovely dream. You could work at an institute.", style: 'composed teacher voice, soft warm encouraging clarity throughout' },
      { speaker: 'riku_teen', jp: '英語の単語、もっと覚えなきゃ。', en: "I have to learn more English words.", style: 'determined teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '単語を増やせば、翻訳も楽になります。', en: "More words make translation easier too.", style: 'patient teacher voice, soft warm measured clarity throughout' },
      { speaker: 'riku_teen', jp: '翻訳の仕事も、面白そうですね。', en: "Translation work sounds interesting too.", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '研究所では、翻訳も大切な仕事です。', en: "At an institute, translation is important work too.", style: 'composed teacher voice, soft warm measured clarity throughout' },
      { speaker: 'riku_teen', jp: '自分の力を、証明したいです。', en: "I want to prove my abilities.", style: 'resolved teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '努力は、いつか必ず証明されますよ。', en: "Effort is always proven in the end.", style: 'warm teacher voice, soft warm encouraging closing clarity throughout' },
    ]),

  // count-1 cluster D — society/abstract (権力 常識 真実 発想 要因)
  C('conv_02997',
    'Asuka lectures on power and truth.',
    'WIDENED SCENARIO: philosophy lecture; vocabulary (権力/常識/真実/発想/要因) in natural home.',
    'lecture_hall_quiet',
    ['権力', '常識', '真実', '発想', '要因'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '権力は、真実を曲げることがあります。', en: "Power can sometimes bend the truth.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '真実は、どう守るんですか?', en: "How do we protect the truth?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '常識を疑う発想が、真実を守ります。', en: "The idea of doubting common sense protects truth.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '常識は、いつも正しいんですか?', en: "Is common sense always right?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '常識が、誤りの要因になることもあります。', en: "Common sense can be a factor in error too.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '新しい発想は、どう生まれますか?', en: "How do new ideas arise?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '権力に流されない姿勢が、要因です。', en: "A stance not swayed by power is a factor.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '真実を求める発想、大事ですね。', en: "The mindset of seeking truth matters.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_02998',
    'Sakura and Ren discuss a documentary on a leader.',
    'WIDENED SCENARIO: documentary discussion; vocabulary (権力/常識/真実/発想/要因) in natural home.',
    'living_room_quiet',
    ['権力', '常識', '真実', '発想', '要因'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'あの指導者、権力を握ってたんだね。', en: "That leader held power.", style: 'thoughtful young man voice, soft warm reflective throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、でも真実を隠したのが要因で倒れたの。', en: "Yes, but hiding the truth was the factor in his fall.", style: 'measured adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '常識を超えた発想も、あったよね。', en: "He also had ideas beyond common sense.", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'sakura_teen', jp: 'その発想が、最初は人を惹きつけたの。', en: "Those ideas first attracted people.", style: 'clear adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '権力に酔うのが、失敗の要因かな。', en: "Getting drunk on power was the factor in failure.", style: 'analytical young man voice, soft warm reflective throughout' },
      { speaker: 'sakura_teen', jp: '真実を、無視できなかったのね。', en: "He couldn't ignore the truth in the end.", style: 'thoughtful adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '常識を疑う発想は、諸刃だね。', en: "Doubting common sense is a double-edged idea.", style: 'understanding young man voice, soft warm reflective throughout' },
      { speaker: 'sakura_teen', jp: '権力と真実、難しい関係ね。', en: "Power and truth — a difficult relationship.", style: 'measured adult anchor voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02999',
    'Hiroshi-boss and Ren brainstorm a fresh idea.',
    'WIDENED SCENARIO: business brainstorming; vocabulary (権力/常識/真実/発想/要因) in natural home.',
    'office_quiet_low',
    ['権力', '常識', '真実', '発想', '要因'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '新しい発想が、必要だと思う。', en: "I think we need a fresh idea.", style: 'composed boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '常識にとらわれず、考えてみます。', en: "I'll think without being bound by common sense.", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '成功の要因は、何だと思うかね?', en: "What do you think is the factor for success?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '顧客の真実の声が、要因だと思います。', en: "I think customers' true voices are the factor.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '社内の権力争いは、無くしたいな。', en: "I want to eliminate internal power struggles.", style: 'firm boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '権力より、発想を大事にしたいです。', en: "Rather than power, I want to value ideas.", style: 'resolved young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '常識を超える発想を、歓迎するよ。', en: "I welcome ideas that surpass common sense.", style: 'warm boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '真実に基づいて、提案します。', en: "I'll propose based on the truth.", style: 'confident young manager voice, soft warm closing throughout' },
    ]),

  C('conv_03000',
    'Ren interviews a scholar on critical thinking.',
    'WIDENED SCENARIO: expert interview; vocabulary (権力/常識/真実/発想/要因) in natural home.',
    'office_quiet_low',
    ['権力', '常識', '真実', '発想', '要因'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '真実を見抜くには、何が大切ですか?', en: "What matters for seeing through to the truth?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: '常識を、一度疑う発想です。', en: "An idea that doubts common sense once.", style: 'composed scholar voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '権力が、判断を歪めることは?', en: "Can power distort judgment?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '権力は、しばしば真実を覆います。', en: "Power often masks the truth.", style: 'patient scholar voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '誤りの主な要因は、何でしょう?', en: "What's the main factor in errors?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '思い込みが、大きな要因です。', en: "Preconceptions are a major factor.", style: 'composed scholar voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '新しい発想を、どう育てますか?', en: "How do you cultivate new ideas?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '常識を問い、真実を探す習慣です。', en: "It's the habit of questioning common sense and seeking truth.", style: 'warm scholar voice, soft warm measured closing clarity throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_150 wrote', CONVERSATIONS.length, 'files');
