import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_107)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02121',
    context: 'Aoi shows Hina-young a new product line at the cafe.',
    purpose: 'Adult and teen reviewing business product.',
    ambient: 'cafe_morning_low',
    sound_effects: [],
    target_vocab: ['製品', '最新', '反応', 'スタッフ', '体制', '気分', '実行', '日々'],
    cast: ['aoi_barista', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'ひな、新しい製品、紹介するね。', en: "Hina — new product, introduce.", style: 'soft adult woman voice, warm warm professional delivery carefully' },
      { speaker: 'hina_child', jp: '最新のメニュー、楽しみ!', en: "Latest menu — looking forward!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: '日々、お客さんの反応、気にしてる。', en: "Daily — customer reaction, care.", style: 'gentle adult woman voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: 'スタッフの皆、頑張ってますね。', en: "Staff all — trying.", style: 'soft teen girl voice, warm appreciative delivery carefully' },
      { speaker: 'aoi_barista', jp: '体制、しっかり整えてる。', en: "System — properly arranged.", style: 'composed adult woman voice, soft warm professional delivery carefully' },
      { speaker: 'hina_child', jp: '気分、すごくいい雰囲気!', en: "Mood — super fine atmosphere!", style: 'thrilled teen girl voice, bright warm delivery carefully' },
      { speaker: 'aoi_barista', jp: '実行に移すの、嬉しい。', en: "Execute to move — happy.", style: 'tender adult woman voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_02122',
    context: 'Daichi takes Sho-young to vote with him for the first time observing.',
    purpose: 'Father showing son civic process.',
    ambient: 'polling_station_low',
    sound_effects: [],
    target_vocab: ['投票', '票', '呼ば', '立っ', '会話', '頂き', '皆さん', 'そんなに'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、投票所、皆さん、ようけ立ってる。', en: "Dad — polling station, everyone, many standing.", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、票を入れる場所や。', en: "Yeah — vote-putting place.", style: 'warm Kansai father voice, soft warm informative delivery carefully' },
      { speaker: 'sho_child', jp: '会話、皆静かやな。', en: "Talk — all quiet.", style: 'soft child boy voice, warm warm observant delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お父さん、呼ばれた、行ってくる。', en: "Dad — called, go.", style: 'soft Kansai husband voice, warm calm delivery carefully' },
      { speaker: 'sho_child', jp: 'そんなに、緊張する場所?', en: "So much — nervous place?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'いや、いつも頂きに来てるみたいなもんや。', en: "No — like always come receiving.", style: 'soft Kansai father voice, warm warm relaxed delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼくも、いつか、来る!', en: "I — someday, come!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02123',
    context: 'Naoko discusses new Japanese language students with Asuka.',
    purpose: 'Aunt and teacher talking about language education.',
    ambient: 'ramen_shop_afternoon',
    sound_effects: [],
    target_vocab: ['言語', '課題', 'どうして', '反映', '進歩', '徐々に', '頂い', '働き'],
    cast: ['naoko_aunt', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'あすか先生、言語の課題、どう?', en: "Asuka — language challenge, how?", style: 'warm Kansai aunt voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '徐々に、進歩してる、生徒さんたち。', en: "Gradually — progressing, students.", style: 'gentle teacher voice, soft warm proud delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'どうして、ようけ来てるんやろ。', en: "Why — many coming?", style: 'curious Kansai aunt voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '頂いた支援、反映されてます。', en: "Received support — reflected.", style: 'soft teacher voice, warm warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '皆の働き、素晴らしいで。', en: "All work — splendid.", style: 'tender Kansai aunt voice, soft warm proud delivery carefully' },
      { speaker: 'asuka_teacher', jp: '生徒さんの努力、嬉しいわ。', en: "Students effort — happy.", style: 'tender teacher voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'こうやって、地域、ええ感じやな。', en: "Like this — area, fine.", style: 'warm Kansai aunt voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_02124',
    context: 'Kenji finishes a long art project; reflects with Ren.',
    purpose: 'Two artists in quiet end-of-project reflection.',
    ambient: 'studio_lamp_evening',
    sound_effects: [],
    target_vocab: ['終え', '反省', '後ろ', '先週', '呼ぶ', '比', '同じく', 'たった'],
    cast: ['kenji_office', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '蓮、ようやく、終えたわ。', en: "Ren — finally, finished.", style: 'tired but content Kansai man voice, soft warm relieved delivery carefully' },
      { speaker: 'ren_uni', jp: 'お疲れさまでした。', en: "Good work.", style: 'humble young man voice, soft warm respectful delivery carefully' },
      { speaker: 'kenji_office', jp: '先週、たった一枚やのに、ようけ時間。', en: "Last week — just one piece, much time.", style: 'reflective Kansai man voice, soft warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '前作と比、どう感じます?', en: "Previous work — how feel?", style: 'gentle young man voice, soft warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: '同じくらいの満足感、ある。', en: "Equal satisfaction — exists.", style: 'soft Kansai man voice, warm warm content delivery carefully' },
      { speaker: 'ren_uni', jp: '後ろ、見ても、誇れる仕事や。', en: "Behind — look, proud work.", style: 'warm young man voice, soft warm respectful delivery carefully' },
      { speaker: 'kenji_office', jp: '反省、ようけあるけど、進む。', en: "Reflection — much but, proceed.", style: 'gentle Kansai man voice, soft warm philosophical delivery carefully' },
    ],
  },
  {
    id: 'conv_02125',
    context: 'Sho-young finds a small bird; Yumiko helps look after it.',
    purpose: 'Grandmother and child gentle wildlife care.',
    ambient: 'garden_morning_birds',
    sound_effects: [],
    target_vocab: ['鳥', '小さく', 'やってき', '居', '飲む', '台風', '降り', '悲しい'],
    cast: ['sho_child', 'yumiko_mom'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おばあちゃん、小さく鳥、やってきた!', en: "Grandma — small bird, came!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、可愛い、台風で降りたかしら。', en: "Oh — cute, typhoon by came down?", style: 'gentle older mother voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: '水、飲ませてあげよう。', en: "Water — give drink.", style: 'soft child boy voice, warm warm caring delivery carefully' },
      { speaker: 'yumiko_mom', jp: '居場所、作ってあげようね。', en: "Place — make.", style: 'tender older mother voice, soft warm helpful delivery carefully' },
      { speaker: 'sho_child', jp: '飛び立てない、悲しいね。', en: "Can't fly off — sad.", style: 'soft empathetic child boy voice, warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '大丈夫、ゆっくり、回復するわよ。', en: "Fine — slowly, recover.", style: 'warm older mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: '毎日、お世話する!', en: "Daily — care!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02126',
    context: 'Ren returns from a trip; small reunion with Sakura at the cafe.',
    purpose: 'Friend recounting recent travel.',
    ambient: 'cafe_afternoon_quiet',
    sound_effects: [],
    target_vocab: ['帰国', 'コンサート', 'リーダー', '定期', 'すると', '都合', '時計', '別れ'],
    cast: ['ren_uni', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、帰国、おめでとう!', en: "Ren — return home, congrats!", style: 'tender adult writer voice, soft warm cheerful delivery carefully' },
      { speaker: 'ren_uni', jp: '定期コンサート、見られたんです。', en: "Regular concert — could see.", style: 'soft young man voice, warm warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、誰のコンサート?', en: "Oh — whose concert?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'ren_uni', jp: '若いリーダーの音楽団。', en: "Young leader music group.", style: 'composed young man voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: 'すると、時計、いっぱい思い出した?', en: "Then — clock, full reminded?", style: 'curious adult writer voice, soft warm probing delivery carefully' },
      { speaker: 'ren_uni', jp: '都合つかず、別れ際、寂しかったです。', en: "Schedule didn't — parting, lonely.", style: 'tender young man voice, soft warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: 'また、行けるよ、ね。', en: "Again — can go, yeah.", style: 'warm adult writer voice, soft warm encouraging delivery carefully' },
    ],
  },
  {
    id: 'conv_02127',
    context: 'Mei explains household philosophy to Hina-young; gentle wisdom.',
    purpose: 'Mother sharing life perspective with teen.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['ゴルフ', '比', '嘘', '演出', '反省', 'まい', '徐々に', '心'],
    cast: ['mei_romantic', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'ひな、嘘、絶対つかないでね。', en: "Hina — lie, definitely don't.", style: 'soft young mother voice, warm warm earnest delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、なんで、急にそう言うの?', en: "Yeah — why, suddenly say?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: '心に、徐々に、何かが残るから。', en: "Heart — gradually, something remains.", style: 'gentle young mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: '演出、しないで、素直に?', en: "Staging — don't, honestly?", style: 'thoughtful teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、人と比、しないで、自分でいて。', en: "Yeah — people compare, don't, self be.", style: 'tender young mother voice, soft warm wise delivery carefully' },
      { speaker: 'hina_child', jp: '反省すること、いっぱい、あるよ。', en: "Reflecting — much, exists.", style: 'soft teen girl voice, warm warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まい、お互い、頑張ろうね。', en: "Each — both, try.", style: 'tender young mother voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02128',
    context: 'Saito and Asuka go to a small museum on a Sunday.',
    purpose: 'Married couple cultural outing.',
    ambient: 'museum_quiet_floor',
    sound_effects: [],
    target_vocab: ['美術館', '見学', '道具', '個性', '哲学', 'なんとなく', '小さく', '置く'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'あすか、美術館、見学、いいね。', en: "Asuka — museum, see, fine.", style: 'warm doctor voice, soft warm content delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'この道具、なんとなく、温かみがある。', en: "This tool — somehow, warmth exists.", style: 'gentle teacher voice, soft warm reflective delivery carefully' },
      { speaker: 'saito_doctor', jp: '小さく置かれた展示、丁寧やな。', en: "Small placed display — careful.", style: 'soft doctor voice, warm warm appreciative delivery carefully' },
      { speaker: 'asuka_teacher', jp: '個性的な作家ね、哲学を感じる。', en: "Individual artist — philosophy feel.", style: 'composed teacher voice, soft warm philosophical delivery carefully' },
      { speaker: 'saito_doctor', jp: '見学、こうやって、ゆっくり、ええなぁ。', en: "See — like this, slowly, lovely.", style: 'tender doctor voice, soft warm content delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'また、来たいね、二人で。', en: "Again — want come, two.", style: 'tender teacher voice, soft warm loving delivery carefully' },
      { speaker: 'saito_doctor', jp: 'うん、定期的に、ね。', en: "Yeah — regularly, yeah.", style: 'warm doctor voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02129',
    context: 'Hina-young helps Hiroshi-elder cross a street; gentle care moment.',
    purpose: 'Teen helping elder with everyday street action.',
    ambient: 'street_corner_low',
    sound_effects: [],
    target_vocab: ['後ろ', '飲む', '読め', 'カフェ', 'たった', '同じく', '居', '降り'],
    cast: ['hina_child', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'ひな、後ろ、ようけ気をつけてな。', en: "Hina — behind, much careful.", style: 'slow elder Kansai voice, warm warm caring delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、おじいちゃん、カフェ、寄ろうか?', en: "Yeah — grandpa, cafe, drop?", style: 'soft teen girl voice, warm warm caring delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、お茶、飲み、ええな。', en: "Yeah — tea, drink, fine.", style: 'gentle elder Kansai voice, soft warm content delivery carefully' },
      { speaker: 'hina_child', jp: 'メニュー、読めるよ、見せて?', en: "Menu — can read, show?", style: 'gentle teen girl voice, soft warm helpful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'たった、二、三品、もろうたら、ええ。', en: "Just — two, three items, receive, fine.", style: 'soft elder Kansai voice, warm warm humble delivery carefully' },
      { speaker: 'hina_child', jp: '同じく、頼みます!', en: "Same — order!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '居心地、ええ場所やな。', en: "Comfort — fine place.", style: 'tender elder Kansai voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_02130',
    context: 'Sakura and Naoko visit a regional craft market for inspiration.',
    purpose: 'Two adults exploring local arts together.',
    ambient: 'market_outdoor_chatter',
    sound_effects: [],
    target_vocab: ['取ら', 'レス', '美術館', '悲しい', '進歩', '徐々に', 'だらけ', '時計'],
    cast: ['sakura_teen', 'naoko_aunt'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'さくらちゃん、ここの市、面白いやろ?', en: "Sakura — this market, fun?", style: 'warm Kansai aunt voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、写真、ようけ取らせていただきます。', en: "Yes — photos, much take.", style: 'soft adult writer voice, warm warm professional delivery carefully' },
      { speaker: 'naoko_aunt', jp: '美術館も、近くにあるで。', en: "Museum — nearby too.", style: 'gentle Kansai aunt voice, soft warm informative delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事、まだ書いてない、悲しい!', en: "Article — not yet, sad!", style: 'soft pouty adult writer voice, warm warm honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: '徐々に、進歩しとるやんか!', en: "Gradually — progressing!", style: 'animated Kansai aunt voice, bright warm encouraging delivery carefully' },
      { speaker: 'sakura_teen', jp: 'メモだらけ、時計見ながら、書きます。', en: "Notes-filled — clock watching, write.", style: 'composed adult writer voice, soft warm committed delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お前なら、絶対できる、レス対応で。', en: "You — definitely can, reply with.", style: 'tender Kansai aunt voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02131',
    context: 'Sho-young and Ren find an injured tree branch; consider how to help.',
    purpose: 'Adult mentor and child solving small nature problem.',
    ambient: 'garden_afternoon_low',
    sound_effects: [],
    target_vocab: ['植物', '症状', '徐々に', '結局', '進歩', '台風', 'なんとなく', '次第'],
    cast: ['ren_uni', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '蓮にいちゃん、この植物、症状、変!', en: "Ren — this plant, symptom, strange!", style: 'worried child boy voice, soft warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '台風のせいかな、徐々に弱ってる。', en: "Typhoon by — gradually weakening.", style: 'gentle young man voice, soft warm observant delivery carefully' },
      { speaker: 'sho_child', jp: '結局、どうやって、助ける?', en: "After all — how, help?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '次第に、回復、するはず。', en: "Gradually — recover, should.", style: 'soft young man voice, warm warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: 'なんとなく、心配やな。', en: "Somehow — worried.", style: 'soft empathetic child boy voice, warm warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '進歩、毎日、見守ろう。', en: "Progress — daily, watch.", style: 'tender young man voice, soft warm patient delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、お水、毎日あげる!', en: "Yeah — water, daily give!", style: 'soft committed child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02132',
    context: 'Asuka and Hiroshi-boss discuss volunteer work coordination.',
    purpose: 'Two professionals coordinating community service.',
    ambient: 'office_low_meeting',
    sound_effects: [],
    target_vocab: ['ますます', 'リーダー', '帰国', '都合', '比', '会場', '会話', '若い'],
    cast: ['asuka_teacher', 'hiroshi_boss'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '社長、ボランティア、ますます活発ですね。', en: "Boss — volunteer, increasingly active.", style: 'composed teacher voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'おう、若いリーダーが、頑張ってる。', en: "Yeah — young leaders, trying.", style: 'measured boss voice, soft warm proud delivery carefully' },
      { speaker: 'asuka_teacher', jp: '帰国した若手、都合は?', en: "Returned youth — schedule?", style: 'engaged teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '比較的、空いてるみたいや。', en: "Relatively — free seems.", style: 'gentle boss voice, soft warm informative delivery carefully' },
      { speaker: 'asuka_teacher', jp: '会場、しっかり準備しましょう。', en: "Venue — properly prep.", style: 'soft teacher voice, warm warm committed delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '会話の機会、増やしたい。', en: "Talk chances — want increase.", style: 'warm boss voice, soft warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: '一緒に、進めましょう。', en: "Together — advance.", style: 'tender teacher voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02133',
    context: 'Yuki-office meets a colleague at a conference; introduction.',
    purpose: 'Brief professional encounter with formal courtesy.',
    ambient: 'conference_lobby_low',
    sound_effects: [],
    target_vocab: ['票', '別れ', '帯', '抜け', '見学', 'カフェ', '飲む', '立つ'],
    cast: ['yuki_office', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: 'お疲れさま、見学、いかがでしたか?', en: "Good work — see, how was?", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '抜けるとこ、ようけありました。', en: "Skipping parts — many.", style: 'soft young man voice, warm honest delivery carefully' },
      { speaker: 'yuki_office', jp: 'カフェで、お話しませんか?', en: "Cafe — talk?", style: 'gentle office woman voice, soft warm inviting delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、コーヒー、飲みたい。', en: "Yes — coffee, want drink.", style: 'warm young man voice, soft warm eager delivery carefully' },
      { speaker: 'yuki_office', jp: '立ちっぱなしで、疲れましたね。', en: "Standing all — tired.", style: 'tender office woman voice, soft warm caring delivery carefully' },
      { speaker: 'ren_uni', jp: '別れ際、いつ?', en: "Parting time — when?", style: 'soft young man voice, warm warm thoughtful delivery carefully' },
      { speaker: 'yuki_office', jp: '一時間、ぐらい、お時間ありますか?', en: "Hour — about, time exist?", style: 'composed office woman voice, soft warm polite delivery carefully' },
    ],
  },
  {
    id: 'conv_02134',
    context: 'Mei and Daichi watch their child fall asleep; quiet midnight.',
    purpose: 'Couple tender late-night parental moment.',
    ambient: 'bedroom_night_quiet',
    sound_effects: [],
    target_vocab: ['居', '小さく', 'すっかり', '読め', '飲む', '上がる', 'すると', '進歩'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、子供、すっかり寝てる。', en: "Daichi — kid, completely sleeping.", style: 'tender young mother voice, soft warm fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: '今夜、本、読めなかった、疲れたか?', en: "Tonight — book, couldn't read, tired?", style: 'soft Kansai husband voice, warm warm caring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、お茶、飲んでから、上がる。', en: "Yeah — tea, after drinking, rise.", style: 'soft young wife voice, warm warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前も、寝室、居る時間、増やせ。', en: "You too — bedroom, stay time, increase.", style: 'warm Kansai husband voice, soft warm caring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'すると、私も、休む時間、増える。', en: "Then — I too, rest time, increase.", style: 'gentle young wife voice, soft warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: '進歩、ええで。', en: "Progress — fine.", style: 'tender Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: '小さく、生活、整えていこう。', en: "Small — life, arrange.", style: 'soft young wife voice, warm warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02135',
    context: 'Tatsuya-country teaches Sho-young how to read a clock face.',
    purpose: 'Elder showing child time-reading skill.',
    ambient: 'tatami_morning_quiet',
    sound_effects: [],
    target_vocab: ['時計', '読む', '進歩', '徐々に', 'なんとなく', '小さく', '同じく', 'やってき'],
    cast: ['tatsuya_country', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '翔、時計、読めるか?', en: "Sho — clock, can read?", style: 'slow Tohoku farmer voice, warm warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: '小さく、針、動いてるね。', en: "Small — hand, moving.", style: 'observant child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: '徐々に、覚えるんや、なんとなく感じて。', en: "Gradually — memorize, somehow feel.", style: 'gentle Tohoku voice, soft warm patient delivery carefully' },
      { speaker: 'sho_child', jp: '同じくらいの位置、何度も見る!', en: "Same position — many times see!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お、進歩したな、お前!', en: "Oh — progressed, you!", style: 'warm Tohoku farmer voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: 'おじいちゃん、教えてくれて、嬉しい!', en: "Grandpa — teaching, happy!", style: 'thrilled child boy voice, bright warm grateful delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'やってきた成果や、頑張ったな。', en: "Came-achieved result — tried.", style: 'tender Tohoku voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02136',
    context: 'Hiroshi-elder reads a newspaper crossword aloud; Sho-young helps.',
    purpose: 'Grandfather and grandson sharing wordplay.',
    ambient: 'porch_morning_quiet',
    sound_effects: [],
    target_vocab: ['みなさん', '考える', '言える', '読み', 'たった', '同じく', '時計', '徐々に'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'みなさん、何やと思う、この問題?', en: "All — what think, this problem?", style: 'gentle elder Kansai voice, soft warm playful delivery carefully' },
      { speaker: 'sho_child', jp: 'うーん、徐々に、考えてみる!', en: "Hmm — gradually, think!", style: 'engaged child boy voice, soft warm thinking delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '読み方、難しいな、たった一行で。', en: "Reading — hard, just one line.", style: 'soft elder Kansai voice, warm warm focused delivery carefully' },
      { speaker: 'sho_child', jp: '同じく、頭使うね。', en: "Same — brain use.", style: 'thoughtful child boy voice, soft warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '時計、見たら、随分時間経った。', en: "Clock — see, quite time passed.", style: 'warm elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '答え、言えるかも!', en: "Answer — can say maybe!", style: 'thrilled child boy voice, bright warm delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、お前、頭ええなぁ!', en: "Yeah — you, smart!", style: 'tender elder Kansai voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02137',
    context: 'Aoi finishes a long shift; small celebration with Yuki.',
    purpose: 'Two women winding down after busy day.',
    ambient: 'cafe_after_close_low',
    sound_effects: [],
    target_vocab: ['終え', '反省', '上げる', '次第', '都合', '帰国', '比', '日々'],
    cast: ['aoi_barista', 'yuki_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'ゆきさん、今日、ようやく終えた!', en: "Yuki — today, finally finished!", style: 'soft tired adult woman voice, warm relieved delivery carefully' },
      { speaker: 'yuki_office', jp: 'お疲れさま、反省、後でね。', en: "Good work — reflect, later.", style: 'gentle office woman voice, soft warm caring delivery carefully' },
      { speaker: 'aoi_barista', jp: '次第に、お客さん、増えてきた。', en: "Gradually — customers, increasing.", style: 'composed adult woman voice, soft warm proud delivery carefully' },
      { speaker: 'yuki_office', jp: '売上、徐々に上がってるね。', en: "Sales — gradually rising.", style: 'warm office woman voice, soft warm engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: '都合つくとき、また打ち合わせを。', en: "Schedule fits — again meeting.", style: 'soft adult woman voice, warm warm professional delivery carefully' },
      { speaker: 'yuki_office', jp: '帰国した友人、紹介しようか?', en: "Returned friend — introduce?", style: 'gentle office woman voice, soft warm friendly delivery carefully' },
      { speaker: 'aoi_barista', jp: '是非!日々、深まる繋がり、嬉しい。', en: "By all means — daily, deepening ties, happy.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02138',
    context: 'Sho-young plays with a dropped soccer ball; chats with Riku-teen.',
    purpose: 'Two friends sharing simple physical play.',
    ambient: 'park_afternoon_low',
    sound_effects: [],
    target_vocab: ['動く', 'ボール', '比', '上がる', '次第', '初心者', '重ね', 'ずいぶん'],
    cast: ['sho_child', 'riku_teen'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '陸くん、ボール、ずいぶん遠く動く!', en: "Riku — ball, far away moves!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'riku_teen', jp: '上手いな、上がってきたで、お前!', en: "Skilled — risen, you!", style: 'warm teen boy voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '初心者と比べたら、進歩した?', en: "Beginner compare — progressed?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'riku_teen', jp: '次第に、力、ついてきたな。', en: "Gradually — strength, gained.", style: 'gentle teen boy voice, soft warm impressed delivery carefully' },
      { speaker: 'sho_child', jp: '練習、重ねて、もっとうまく!', en: "Practice — pile, more well!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
      { speaker: 'riku_teen', jp: 'お前、すごい根性や!', en: "You — amazing grit!", style: 'animated teen boy voice, bright warm proud delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、応援!', en: "Thanks — cheer!", style: 'bright child boy voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02139',
    context: 'Sakura takes a curry meal with Ren on a cold day.',
    purpose: 'Adult writers sharing comforting meal.',
    ambient: 'restaurant_warm_low',
    sound_effects: [],
    target_vocab: ['カレー', 'うまい', '帯', '抜け', '住所', '会う', '飲む', '関わる'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、このカレー、うまいね。', en: "Ren — this curry, tasty.", style: 'soft adult writer voice, warm warm content delivery carefully' },
      { speaker: 'ren_uni', jp: '寒い日、温まる、嬉しい。', en: "Cold day — warming, happy.", style: 'tender young man voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お店、ここの住所、覚えとこう。', en: "Shop — here address, remember.", style: 'composed adult writer voice, soft warm practical delivery carefully' },
      { speaker: 'ren_uni', jp: '若い人とも、会えそう、ここで。', en: "Young people too — can meet, here.", style: 'soft young man voice, warm warm hopeful delivery carefully' },
      { speaker: 'sakura_teen', jp: '町に関わる仕事、楽しい?', en: "Town-related work — fun?", style: 'gentle adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、抜け道、ようけ知る。', en: "Yes — shortcut, much learn.", style: 'warm young man voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '温かいお茶、飲んで、ゆっくりしよう。', en: "Warm tea — drink, slowly.", style: 'tender adult writer voice, soft warm peaceful delivery carefully' },
    ],
  },
  {
    id: 'conv_02140',
    context: 'Whole group hosts a small picnic-concert with friends; many voices.',
    purpose: 'Multi-voice outdoor cultural community moment.',
    ambient: 'park_concert_outdoor',
    sound_effects: [],
    target_vocab: ['コンサート', '広場', '集まる', 'みなさん', '進歩', '徐々に', '心', '関わる'],
    cast: ['kenji_office', 'aoi_barista', 'sakura_teen', 'ren_uni', 'naoko_aunt', 'hiroshi_elder', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '広場、皆、集まったな!', en: "Plaza — all, gathered!", style: 'warm Kansai man voice, soft warm cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'みなさん、ようこそ、ピクニックコンサート!', en: "All — welcome, picnic concert!", style: 'bright adult woman voice, soft warm hosting delivery carefully' },
      { speaker: 'sakura_teen', jp: '心、ようけ、繋がるね、こうやって。', en: "Heart — much, connect, like this.", style: 'tender adult writer voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '関わる皆さんに、感謝の気持ち。', en: "Related all — gratitude feeling.", style: 'humble young man voice, soft warm respectful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'こんな広場、徐々に賑やかになったな!', en: "Such plaza — gradually lively!", style: 'animated Kansai aunt voice, bright warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '昔と比、進歩、感じるな。', en: "Past compare — progress, feel.", style: 'gentle elder Kansai voice, soft warm reflective delivery carefully' },
      { speaker: 'sho_child', jp: '皆と、楽しい、最高!', en: "All — fun, best!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: '音楽、もう少しで始まるで!', en: "Music — soon starts!", style: 'warm Kansai man voice, soft warm anticipating delivery carefully' },
      { speaker: 'aoi_barista', jp: '皆、ありがとう、心、温い。', en: "All — thanks, heart, warm.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に書きたい、こんな日。', en: "Article — want write, day like this.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '皆との出会い、宝物。', en: "All meeting — treasure.", style: 'tender young man voice, soft warm fond delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うちのお店も、こうやって、繋がる!', en: "My shop too — like this, connect!", style: 'warm Kansai aunt voice, soft warm proud delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええ町や、皆おって。', en: "Fine town — all here.", style: 'tender elder Kansai voice, soft warm content delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_107 wrote', CONVERSATIONS.length, 'files');
