import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_088)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01746',
    context: 'Hiroshi-boss and Kenji discuss the small business\'s yearly budget over coffee.',
    purpose: 'Two adults reviewing finances of company.',
    ambient: 'office_evening_quiet',
    sound_effects: [],
    target_vocab: ['経済', '取引', '価格', '判断'],
    cast: ['hiroshi_boss', 'kenji_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '今期の経済、厳しいな。', en: "This term's economy — tough.", style: 'measured boss voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'はい、取引先も慎重です。', en: "Yes — clients cautious too.", style: 'soft Kansai man voice, warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '価格、見直し必要やな。', en: "Pricing — review needed.", style: 'gentle boss voice, soft warm strategic delivery carefully' },
      { speaker: 'kenji_office', jp: '社内で、判断検討しましょう。', en: "Internally — consider judgment.", style: 'composed Kansai man voice, soft warm collaborative delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'うん、急がず、丁寧にな。', en: "Yeah — not rushed, carefully.", style: 'warm boss voice, soft wise delivery carefully' },
      { speaker: 'kenji_office', jp: '了解です、来週準備します。', en: "Understood — prep next week.", style: 'soft Kansai man voice, warm committed delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'お前おって、心強いわ。', en: "With you — reassuring.", style: 'warm boss voice, soft trusting delivery carefully' },
    ],
  },
  {
    id: 'conv_01747',
    context: 'Yuki-office tells Sakura about a new part-time job she\'s considering.',
    purpose: 'Friend discussing career change with another.',
    ambient: 'cafe_lunch_low',
    sound_effects: [],
    target_vocab: ['仕事', '契約', '時給', '迷う'],
    cast: ['yuki_office', 'sakura_teen'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: '新しい仕事、迷ってるの。', en: "New job — wavering.", style: 'soft office woman voice, warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どんな仕事?', en: "What kind?", style: 'gentle adult writer voice, soft warm caring inquiry delivered carefully' },
      { speaker: 'yuki_office', jp: '契約で、時給も悪くないの。', en: "Contract — hourly fair too.", style: 'warm office woman voice, soft thinking delivery carefully' },
      { speaker: 'sakura_teen', jp: '内容、合いそう?', en: "Content — suits?", style: 'curious adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: 'うん、興味ある分野なの。', en: "Yeah — field of interest.", style: 'soft office woman voice, warm cheerful delivery carefully' },
      { speaker: 'sakura_teen', jp: '挑戦、いいと思うよ。', en: "Challenge — I think it's good.", style: 'warm adult writer voice, soft warm encouraging delivery carefully' },
      { speaker: 'yuki_office', jp: '背中、押されたよ、ありがとう。', en: "Pushed by you — thanks.", style: 'tender office woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01748',
    context: 'Ren and Aoi discuss the cost of living rising; quiet concern at the cafe.',
    purpose: 'Two adults sharing economic anxieties together.',
    ambient: 'cafe_quiet_window',
    sound_effects: [],
    target_vocab: ['物価', '生活', '心配', '工夫'],
    cast: ['ren_uni', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '最近、物価、上がってるね。', en: "Lately — prices rising.", style: 'soft adult woman voice, warm concerned delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、生活、大変です。', en: "Yes — life, tough.", style: 'soft young man voice, warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うちも、心配してる。', en: "We worry too.", style: 'gentle adult woman voice, soft warm shared delivery carefully' },
      { speaker: 'ren_uni', jp: '工夫しないと、ですね。', en: "Have to adjust.", style: 'thoughtful young man voice, soft warm practical delivery carefully' },
      { speaker: 'aoi_barista', jp: '節約、ちゃんとしようね。', en: "Save — properly.", style: 'warm adult woman voice, soft determined delivery carefully' },
      { speaker: 'ren_uni', jp: '一緒に、頑張りましょう。', en: "Try together.", style: 'soft young man voice, warm solidarity delivered carefully' },
      { speaker: 'aoi_barista', jp: 'うん、心強いわ。', en: "Yeah — encouraging.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01749',
    context: 'Daichi gets a small promotion at work; tells Mei excitedly at home.',
    purpose: 'Husband sharing career milestone with wife.',
    ambient: 'living_room_evening_warm',
    sound_effects: [],
    target_vocab: ['昇進', '責任', '給料', '頑張る'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、昇進、決まったわ!', en: "Mei — promotion, decided!", style: 'thrilled Kansai husband voice, bright warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'えっ、本当?おめでとう!', en: "Eh — really? Congrats!", style: 'tender young wife voice, soft warm delight delivered carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、責任、増えるけどな。', en: "Yeah — responsibility increases.", style: 'soft Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '大変かもしれないけど、嬉しい!', en: "Might be tough — but happy!", style: 'gentle young wife voice, soft warm proud delivery carefully' },
      { speaker: 'daichi_kansai', jp: '給料も、ちょっと上がる。', en: "Pay — bit higher.", style: 'warm Kansai husband voice, soft fond delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お父さん、誇りに思う。', en: "Dad — I'm proud.", style: 'tender young wife voice, soft warm loving delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おまえのおかげや、ほんま。', en: "Thanks to you — truly.", style: 'soft Kansai husband voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01750',
    context: 'Saito has dinner with old colleagues; small reunion of doctors.',
    purpose: 'Adult doctors warmly reconnecting at restaurant.',
    ambient: 'izakaya_warm_low',
    sound_effects: [],
    target_vocab: ['仲間', '同期', '医師', '懐かしい'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '同期、集まれて嬉しい。', en: "Same-year colleagues gathered — happy.", style: 'soft doctor voice, warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ええ、懐かしい顔ぶれ。', en: "Yes — nostalgic faces.", style: 'warm teacher voice, soft fond delivery carefully' },
      { speaker: 'saito_doctor', jp: '医師の道、長いね。', en: "Doctor's path — long.", style: 'gentle doctor voice, soft warm reflective delivery carefully' },
      { speaker: 'asuka_teacher', jp: '苦労も、思い出も、たくさん。', en: "Hardships, memories — many.", style: 'soft teacher voice, warm tender delivery carefully' },
      { speaker: 'saito_doctor', jp: '皆、変わらず元気で。', en: "All — unchanged, well.", style: 'warm doctor voice, soft fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'こういう時間、宝物ね。', en: "Times like this — treasure.", style: 'tender teacher voice, soft warm appreciative delivery carefully' },
      { speaker: 'saito_doctor', jp: 'また、集まりましょう。', en: "Let's gather again.", style: 'warm doctor voice, soft fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01751',
    context: 'Hina-young helps Yumiko declutter old keepsakes; emotional sorting.',
    purpose: 'Teen and grandmother going through old objects together.',
    ambient: 'storage_room_quiet',
    sound_effects: [],
    target_vocab: ['整理', '思い出', '昔', '手放す'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、これも整理する?', en: "Grandma — sort this too?", style: 'soft teen girl voice, warm gentle inquiring delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'これは、思い出の品よ。', en: "This — keepsake.", style: 'tender older mother voice, soft warm tender delivery carefully' },
      { speaker: 'hina_child', jp: 'どんな思い出?', en: "What memory?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'お父さんと、初めての旅行。', en: "First trip with dad.", style: 'soft older mother voice, warm fond reminiscent delivery carefully' },
      { speaker: 'hina_child', jp: 'すごく大切な物ね。', en: "Truly precious.", style: 'soft teen girl voice, warm reverent delivery carefully' },
      { speaker: 'yumiko_mom', jp: '手放す前に、写真撮ろうかしら。', en: "Before letting go — take photo?", style: 'gentle older mother voice, soft warm thoughtful delivery carefully' },
      { speaker: 'hina_child', jp: 'いい考え!私、撮るね。', en: "Good idea — I'll shoot.", style: 'bright teen girl voice, soft warm helpful delivery carefully' },
    ],
  },
  {
    id: 'conv_01752',
    context: 'Sho-young watches the news with Hiroshi-elder; asks naive but earnest question.',
    purpose: 'Grandfather patiently explaining world events to child.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['ニュース', '世界', '平和', '人々'],
    cast: ['sho_child', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、戦争、何で?', en: "Grandpa — war, why?", style: 'soft curious child boy voice, warm small honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '難しい話やな、子。', en: "Hard topic, kid.", style: 'slow elder Kansai voice, warm tender philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '世界、平和になるかな?', en: "World — become peaceful?", style: 'soft hopeful child boy voice, warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '皆が、願い続けたらな。', en: "If all keep wishing.", style: 'gentle elder Kansai voice, soft warm hopeful delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼくも、祈る!', en: "I'll pray too!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_01753',
    context: 'Naoko hosts a small ramen-shop charity night for local kids.',
    purpose: 'Generous aunt running community kindness event.',
    ambient: 'ramen_shop_charity_warm',
    sound_effects: [],
    target_vocab: ['子供', '寄付', '地域', '心'],
    cast: ['naoko_aunt', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '今夜、子供たち、無料やで!', en: "Tonight — kids free!", style: 'brassy Kansai aunt voice, bright loud generous delivery carefully' },
      { speaker: 'aoi_barista', jp: 'おばさん、優しい。', en: "Auntie — kind.", style: 'tender adult woman voice, soft warm admiring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うちなんかでも、できる寄付や。', en: "Even ours — can donate.", style: 'soft Kansai aunt voice, warm humble delivery carefully' },
      { speaker: 'aoi_barista', jp: '地域に、響くわよ。', en: "Resonates in the area.", style: 'soft adult woman voice, warm proud delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'みんなで、子供を支えなあかん。', en: "All together — support kids.", style: 'firm Kansai aunt voice, soft warm passionate delivery carefully' },
      { speaker: 'aoi_barista', jp: '心、温かいね。', en: "Heart — warm.", style: 'tender adult woman voice, soft warm reverent delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、当たり前や!', en: "Heh — natural!", style: 'animated Kansai aunt voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01754',
    context: 'Mei prepares a long family budget review with Daichi at the kitchen table.',
    purpose: 'Couple seriously reviewing household finances.',
    ambient: 'kitchen_evening_lamp',
    sound_effects: [],
    target_vocab: ['家計', '節約', '計画', '将来'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '家計、見直そうね、今日は。', en: "Household budget — review today.", style: 'soft young wife voice, warm practical delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、ちゃんと話そか。', en: "Yeah — talk properly.", style: 'warm Kansai husband voice, soft committed delivery carefully' },
      { speaker: 'mei_romantic', jp: '節約、もう少し必要かも。', en: "Save — bit more needed.", style: 'gentle young woman voice, soft warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '外食、減らそか?', en: "Eat out — cut?", style: 'soft Kansai husband voice, warm practical delivery carefully' },
      { speaker: 'mei_romantic', jp: '光熱費も、見直したい。', en: "Utilities — review too.", style: 'thoughtful young woman voice, soft warm careful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '将来、子供のためにもな。', en: "Future — for kids too.", style: 'soft Kansai husband voice, warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: '貯金、目標立てる?', en: "Savings — set a goal?", style: 'gentle young woman voice, soft warm planning delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、一年で百万や!', en: "Yeah — one million in a year!", style: 'animated Kansai husband voice, bright warm decisive delivery carefully' },
      { speaker: 'mei_romantic', jp: 'やる気あるね、頑張ろう!', en: "Motivated — let's try!", style: 'bright young woman voice, soft warm encouraging delivery carefully' },
      { speaker: 'daichi_kansai', jp: '一緒なら、できるわ。', en: "Together — we can.", style: 'tender Kansai husband voice, soft warm united delivery carefully' },
      { speaker: 'mei_romantic', jp: '計画的に、無理せず。', en: "Planned — not pushed.", style: 'gentle young woman voice, soft warm balanced delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おまえと一緒で、心強い。', en: "With you — encouraged.", style: 'warm Kansai husband voice, soft tender delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、頼りにしてる。', en: "Thanks — relying on you.", style: 'tender young wife voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01755',
    context: 'Tatsuya-country teaches Sho-young how to plant a small garden seed.',
    purpose: 'Elder farmer patiently teaching child basic agriculture.',
    ambient: 'garden_morning_breeze',
    sound_effects: [],
    target_vocab: ['種', '土', '育てる', '水'],
    cast: ['tatsuya_country', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: 'この種、土に植えるんや。', en: "This seed — plant in soil.", style: 'slow Tohoku farmer voice, warm patient teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'こんな小さいのが育つの?', en: "Such a small thing grows?", style: 'awed child boy voice, soft warm honest delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'うん、水あげて、待つんや。', en: "Yeah — water it, wait.", style: 'gentle Tohoku voice, soft warm wise delivery carefully' },
      { speaker: 'sho_child', jp: '毎日、水あげる!', en: "Water daily!", style: 'eager child boy voice, bright warm committed delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ええ子や、育つで。', en: "Fine kid — will grow.", style: 'warm Tohoku farmer voice, soft fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01756',
    context: 'Sakura discusses publishing rights with Hiroshi-boss for a translation.',
    purpose: 'Author and publisher negotiating international deal.',
    ambient: 'office_quiet_window',
    sound_effects: [],
    target_vocab: ['翻訳', '海外', '権利', '契約'],
    cast: ['sakura_teen', 'hiroshi_boss'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '海外版、翻訳の話、来ました。', en: "Overseas edition — translation talk.", style: 'soft adult writer voice, warm proud professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ええ知らせやな!どこの国?', en: "Fine news! What country?", style: 'warm boss voice, soft excited delivery carefully' },
      { speaker: 'sakura_teen', jp: 'フランスです、最初は。', en: "France — first.", style: 'composed adult writer voice, soft warm informative delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '権利、しっかり管理せなな。', en: "Rights — manage well.", style: 'measured boss voice, soft warm businesslike delivery carefully' },
      { speaker: 'sakura_teen', jp: '契約書、丁寧に確認します。', en: "Contract — check carefully.", style: 'gentle adult writer voice, soft warm careful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'うん、こちらも全面支援する。', en: "Yeah — we'll fully support.", style: 'warm boss voice, soft committed delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01757',
    context: 'Aoi tells Kenji she\'s preparing for maternity leave from the cafe.',
    purpose: 'Pregnant wife planning practical work arrangements with husband.',
    ambient: 'porch_evening_warm',
    sound_effects: [],
    target_vocab: ['仕事', '休む', '準備', '時期'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、仕事、休む準備してる。', en: "Ken-chan — preparing leave.", style: 'soft adult woman voice, warm content practical delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、時期、決まったんか?', en: "Yeah — timing decided?", style: 'gentle Kansai man voice, soft warm caring delivery carefully' },
      { speaker: 'aoi_barista', jp: '来月末から、しばらく。', en: "End of next month — for a while.", style: 'gentle adult woman voice, soft warm informative delivery carefully' },
      { speaker: 'kenji_office', jp: 'ようけ、お疲れさん。', en: "You've worked hard.", style: 'soft Kansai man voice, warm tender delivery carefully' },
      { speaker: 'aoi_barista', jp: 'スタッフにも、伝えなきゃ。', en: "Staff — must tell.", style: 'soft adult woman voice, warm thoughtful delivery carefully' },
      { speaker: 'kenji_office', jp: '俺も、ちゃんと協力するで。', en: "I'll properly help.", style: 'warm Kansai husband voice, soft committed delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、嬉しい。', en: "Thanks — happy.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01758',
    context: 'Mrs. Mori and Hiroshi-elder discuss aging in the community.',
    purpose: 'Two elders reflecting on later life challenges together.',
    ambient: 'porch_afternoon_breeze',
    sound_effects: [],
    target_vocab: ['老い', '健康', '近所', '助け合う'],
    cast: ['mrs_mori_neighbor', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: '老いって、思うようにいかんね。', en: "Old age — doesn't go as wished.", style: 'soft older neighbor voice, warm honest reflective delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、身体、辛い時もある。', en: "Truly — body, sometimes painful.", style: 'gentle elder Kansai voice, soft warm honest delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '健康、ありがたいわね。', en: "Health — grateful.", style: 'soft older woman voice, warm humble delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '近所同士、助け合うのが大事や。', en: "Neighbors — helping is key.", style: 'slow elder Kansai voice, warm wise delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'こうやって話せて、嬉しい。', en: "Glad to talk like this.", style: 'tender older neighbor voice, soft warm grateful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、お互い長生きしような。', en: "Yeah — both live long.", style: 'warm elder Kansai voice, soft tender delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふふ、約束ね。', en: "Heh — promise.", style: 'soft older neighbor voice, warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01759',
    context: 'Riku-teen tells Sho-young his future career dreams excitedly.',
    purpose: 'Teen sharing future ambitions with younger friend.',
    ambient: 'park_bench_afternoon',
    sound_effects: [],
    target_vocab: ['夢', '将来', '職業', '頑張る'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'riku_teen', jp: '俺、将来、警察になりたいんよ。', en: "I want to become police.", style: 'bright teen boy voice, soft warm determined delivery carefully' },
      { speaker: 'sho_child', jp: 'えっ、すごい!', en: "Eh — wow!", style: 'awed child boy voice, bright warm delivery carefully' },
      { speaker: 'riku_teen', jp: '頑張って、勉強せなあかん。', en: "Have to study hard.", style: 'soft committed teen boy voice, warm honest delivery carefully' },
      { speaker: 'sho_child', jp: '陸くん、応援する!', en: "Riku — I'll cheer!", style: 'eager child boy voice, bright warm supportive delivery carefully' },
      { speaker: 'riku_teen', jp: 'ありがとう、嬉しいわ。', en: "Thanks — happy.", style: 'soft teen boy voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01760',
    context: 'Yumiko writes a letter to her late husband; Mei sits quietly with her.',
    purpose: 'Widow tenderly writing memorial letter with companion.',
    ambient: 'tatami_lamp_evening',
    sound_effects: [],
    target_vocab: ['手紙', '心', '思い', '届ける'],
    cast: ['yumiko_mom', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '夫に、手紙を書いてるの。', en: "Writing a letter to husband.", style: 'soft older mother voice, warm tender reverent delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お母さん、心、こもってる。', en: "Mom — heart's in it.", style: 'tender young wife voice, soft warm appreciative delivery carefully' },
      { speaker: 'yumiko_mom', jp: '想い、届けたいだけ。', en: "Just to deliver feelings.", style: 'gentle older mother voice, soft warm wistful delivery carefully' },
      { speaker: 'mei_romantic', jp: '今でも、繋がってるのね。', en: "Even now — connected.", style: 'soft young woman voice, warm reverent delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、心の中にずっと。', en: "Yeah — always in heart.", style: 'tender older mother voice, soft warm enduring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お父さん、喜んでるよ。', en: "Dad — is pleased.", style: 'tender young wife voice, soft warm tender delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ありがとう、隣にいてくれて。', en: "Thanks — for being beside me.", style: 'soft older mother voice, warm grateful tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01761',
    context: 'Kenji and Daichi help Hiroshi-elder set up his vegetable garden.',
    purpose: 'Two friends helping elder with seasonal yard work.',
    ambient: 'garden_spring_breeze',
    sound_effects: [],
    target_vocab: ['畑', '野菜', '土', '春'],
    cast: ['kenji_office', 'daichi_kansai'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: 'この畑、ええ土やな。', en: "This patch — fine soil.", style: 'soft Kansai man voice, warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: '春、ばっちりや。', en: "Spring — perfect.", style: 'warm Kansai husband voice, soft cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: '何の野菜、植えるんかな。', en: "What veggie planting?", style: 'gentle Kansai man voice, soft warm curious delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'トマト、キュウリ、たくさん。', en: "Tomatoes, cukes — lots.", style: 'soft Kansai husband voice, warm fond delivery carefully' },
      { speaker: 'kenji_office', jp: '楽しみやな、収穫。', en: "Looking forward — harvest.", style: 'warm Kansai man voice, soft fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01762',
    context: 'Asuka volunteers to help a teen group; meets Hina-young at a workshop.',
    purpose: 'Teacher offering kind community education.',
    ambient: 'community_hall_low',
    sound_effects: [],
    target_vocab: ['学ぶ', '生徒', '伝える', '楽しい'],
    cast: ['asuka_teacher', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '今日のワークショップ、楽しい?', en: "Today's workshop — fun?", style: 'warm teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、すごく学んでる!', en: "Yeah — learning lots!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '生徒、みんな熱心ね。', en: "Students — all engaged.", style: 'gentle teacher voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: '先生の伝え方、わかりやすい。', en: "Your teaching — clear.", style: 'soft teen girl voice, warm admiring delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ありがとう、嬉しい言葉。', en: "Thanks — happy words.", style: 'tender teacher voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01763',
    context: 'Goro-grandpa and Sho-young visit the local fire station for a kids\' tour.',
    purpose: 'Elder taking child on community education outing.',
    ambient: 'fire_station_busy',
    sound_effects: [],
    target_vocab: ['消防士', '車', '勇気', '守る'],
    cast: ['goro_grandpa', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、消防車、かっこいい!', en: "Grandpa — fire truck, cool!", style: 'thrilled child boy voice, bright cheerful warm delivery carefully' },
      { speaker: 'goro_grandpa', jp: '消防士、勇気あるなぁ。', en: "Firefighters — brave.", style: 'soft elder voice, warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '町、守ってくれてる?', en: "Protecting the town?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'goro_grandpa', jp: 'うん、毎日、訓練してるんや。', en: "Yeah — drilling daily.", style: 'gentle elder voice, soft warm informative delivery carefully' },
      { speaker: 'sho_child', jp: '僕も、守りたい!', en: "I want to protect too!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_01764',
    context: 'Sakura sits with Naoko after Naoko\'s tough day; quiet support.',
    purpose: 'Author offering quiet emotional support to friend.',
    ambient: 'ramen_shop_after_close',
    sound_effects: [],
    target_vocab: ['辛い', '頑張る', '休む', '聴く'],
    cast: ['sakura_teen', 'naoko_aunt'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '今日、めっちゃ辛かったわ。', en: "Today — really hard.", style: 'soft Kansai aunt voice, warm vulnerable honest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'おばさん、お疲れさま。', en: "Auntie — good work.", style: 'gentle adult writer voice, soft warm caring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お客さんと、ちょっと揉めて。', en: "Customer — small scuffle.", style: 'soft Kansai aunt voice, warm honest weary delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お話、聴いていますよ。', en: "I'm listening.", style: 'tender adult writer voice, soft warm patient delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おまえおって、助かるわ。', en: "With you — saved.", style: 'warm Kansai aunt voice, soft grateful delivery carefully' },
      { speaker: 'sakura_teen', jp: '休んで、ゆっくりね。', en: "Rest — slowly.", style: 'gentle adult writer voice, soft warm caring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うん、ありがとう、ほんま。', en: "Yeah — thanks, truly.", style: 'soft Kansai aunt voice, warm tender grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01765',
    context: 'Big group at New Year\'s eve countdown; many warm wishes.',
    purpose: 'Multiple voices joining for year-end family gathering.',
    ambient: 'living_room_new_year_warm',
    sound_effects: [],
    target_vocab: ['新年', '挨拶', '幸せ', '健康', '感謝'],
    cast: ['hiroshi_elder', 'naoko_aunt', 'daichi_kansai', 'mei_romantic', 'sho_child', 'hina_child', 'aoi_barista', 'kenji_office'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'いよいよ、新年やな。', en: "Finally — new year.", style: 'slow elder Kansai voice, warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'カウントダウン、しよか!', en: "Countdown — let's do!", style: 'brassy Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、新年!', en: "Yay — new year!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'みんな、おめでとう!', en: "Everyone — congratulations!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '今年も、ありがとうございました。', en: "This year — thank you.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'みんなで、幸せに過ごせて感謝や。', en: "Together — grateful to spend happily.", style: 'warm Kansai husband voice, soft tender content delivery carefully' },
      { speaker: 'aoi_barista', jp: '来年も、健康でいたい。', en: "Next year — want to be healthy.", style: 'soft adult woman voice, warm hopeful delivery carefully' },
      { speaker: 'kenji_office', jp: 'お互いに、支え合ってな。', en: "Both of us — supporting.", style: 'soft Kansai man voice, warm tender delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '家族の絆、宝物や。', en: "Family bonds — treasure.", style: 'gentle elder Kansai voice, soft warm wise delivery carefully' },
      { speaker: 'naoko_aunt', jp: '乾杯、いくで!', en: "Toast — go!", style: 'animated Kansai aunt voice, bright loud excited delivery carefully' },
      { speaker: 'mei_romantic', jp: '今年も、家族で頑張ろう。', en: "This year too — family, try.", style: 'soft young mother voice, warm united delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええ年にしような。', en: "Make a fine year.", style: 'warm Kansai husband voice, soft proud delivery carefully' },
      { speaker: 'sho_child', jp: '来年も、楽しもうね!', en: "Next year too — let's enjoy!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_088 wrote', CONVERSATIONS.length, 'files');
