import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_097)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01926',
    context: 'Mei buys a new fridge; checks reviews with Daichi at the appliance shop.',
    purpose: 'Married couple making major home purchase together.',
    ambient: 'shop_quiet_low',
    sound_effects: [],
    target_vocab: ['冷蔵庫', '値段', '選ぶ', '相談'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '冷蔵庫、これ、どう思う?', en: "Fridge — this, think?", style: 'gentle young wife voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '値段、ちょっと高いな。', en: "Price — bit high.", style: 'warm Kansai husband voice, soft cautious delivery carefully' },
      { speaker: 'mei_romantic', jp: '大きさ、ちょうどいいかも。', en: "Size — maybe just right.", style: 'soft young woman voice, warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '機能、必要なの揃ってる?', en: "Functions — needed?", style: 'soft Kansai husband voice, warm practical delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、節電タイプ、いいね。', en: "Yeah — energy-save, lovely.", style: 'warm young woman voice, soft warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: '相談して、決めよか。', en: "Discuss — decide.", style: 'gentle Kansai husband voice, soft warm collaborative delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、これにしよう。', en: "Yeah — this.", style: 'soft decisive young woman voice, warm warm delivery carefully' },
    ],
  },
  {
    id: 'conv_01927',
    context: 'Sho-young breaks a glass at home; Mei reassures him.',
    purpose: 'Mother responding kindly to child\'s accident.',
    ambient: 'kitchen_clatter_quiet',
    sound_effects: [],
    target_vocab: ['割る', '気をつける', 'けが', '大丈夫'],
    cast: ['sho_child', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、ごめんなさい!', en: "Mom — sorry!", style: 'soft tearful child boy voice, warm contrite delivery carefully' },
      { speaker: 'mei_romantic', jp: 'けが、ない?', en: "Injury — none?", style: 'urgent young mother voice, soft warm concerned delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、大丈夫。', en: "Yeah — okay.", style: 'soft relieved child boy voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '物より、あなたが大事よ。', en: "More than item — you matter.", style: 'tender young mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: '気をつける、次は。', en: "Be careful — next.", style: 'soft determined child boy voice, warm resolved delivery carefully' },
    ],
  },
  {
    id: 'conv_01928',
    context: 'Naoko shops for new curtains for the ramen shop with Aoi advising.',
    purpose: 'Two women advising on interior choice.',
    ambient: 'shop_low_fabric',
    sound_effects: [],
    target_vocab: ['カーテン', '色', '部屋', '雰囲気'],
    cast: ['naoko_aunt', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'カーテン、何色がええ?', en: "Curtain — what color?", style: 'animated Kansai aunt voice, bright loud engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: '店の雰囲気、明るくしたいね。', en: "Shop mood — want bright.", style: 'gentle adult woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '黄色、どうやろか?', en: "Yellow — how?", style: 'warm Kansai aunt voice, soft cheerful suggesting delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、温かい感じになる!', en: "Yeah — warm feel becomes!", style: 'soft adult woman voice, warm bright approving delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'よっしゃ、これに決めや!', en: "Right — this decide!", style: 'brassy Kansai aunt voice, bright loud decisive delivery carefully' },
    ],
  },
  {
    id: 'conv_01929',
    context: 'Hina-young helps Yumiko reorganize the family living room.',
    purpose: 'Teen and grandmother bonding through household task.',
    ambient: 'living_room_afternoon',
    sound_effects: [],
    target_vocab: ['部屋', '整理', '家具', '配置'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、家具、動かす?', en: "Grandma — furniture, move?", style: 'eager teen girl voice, soft warm helpful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、ソファ、こっちに。', en: "Yeah — sofa, this side.", style: 'gentle older mother voice, soft warm decisive delivery carefully' },
      { speaker: 'hina_child', jp: '重いね、手伝うね。', en: "Heavy — I help.", style: 'soft teen girl voice, warm warm encouraging delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ありがとう、無理しないで。', en: "Thanks — don't push.", style: 'warm older mother voice, soft tender caring delivery carefully' },
      { speaker: 'hina_child', jp: '本棚、ここに置く?', en: "Bookshelf — place here?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'いいね、整理しよう。', en: "Lovely — organize.", style: 'tender older mother voice, soft warm content delivery carefully' },
      { speaker: 'hina_child', jp: 'お部屋、明るくなった!', en: "Room — became bright!", style: 'bright teen girl voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01930',
    context: 'Daichi installs a new ceiling light; Sho-young watches with curiosity.',
    purpose: 'Father teaching son basic home repair.',
    ambient: 'living_room_tool_low',
    sound_effects: [],
    target_vocab: ['電球', '取り付ける', '明るい', '見守る'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、電球、変えるの?', en: "Dad — light bulb, change?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、見ててな、慎重に。', en: "Yeah — watch, carefully.", style: 'soft Kansai father voice, warm cautious teaching delivery carefully' },
      { speaker: 'sho_child', jp: '高い、危なくない?', en: "High — dangerous?", style: 'soft worried child boy voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '大丈夫、コツがある。', en: "Fine — trick exists.", style: 'warm Kansai father voice, soft confident delivery carefully' },
      { speaker: 'sho_child', jp: '明るくなった、すごい!', en: "Bright — wow!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
    ],
  },
  {
    id: 'conv_01931',
    context: 'Yumiko prepares a feast; Aoi and Mei help in the kitchen.',
    purpose: 'Three generations cooking large meal together.',
    ambient: 'kitchen_warm_busy',
    sound_effects: [],
    target_vocab: ['料理', '台所', '皿', '準備'],
    cast: ['yumiko_mom', 'aoi_barista', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '皆で、料理、楽しいわね。', en: "All — cooking, fun.", style: 'warm older mother voice, soft warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: 'おばあちゃん、何手伝う?', en: "Grandma — help what?", style: 'soft adult woman voice, warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '台所、賑やかになる。', en: "Kitchen — gets lively.", style: 'gentle young mother voice, soft warm fond delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まず、皿、揃えましょう。', en: "First — plates, gather.", style: 'tender older mother voice, soft warm teaching delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、こちらに用意します。', en: "Yes — here prepare.", style: 'gentle adult woman voice, soft warm helpful delivery carefully' },
      { speaker: 'mei_romantic', jp: '野菜、私が切るね。', en: "Veggies — I cut.", style: 'soft young mother voice, warm warm contributing delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ありがとう、頼もしいわね。', en: "Thanks — reliable.", style: 'warm older mother voice, soft warm proud delivery carefully' },
      { speaker: 'aoi_barista', jp: '楽しい時間、貴重ね。', en: "Fun time — precious.", style: 'tender adult woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'mei_romantic', jp: '皆で、こうやって過ごせて嬉しい。', en: "All — spending like this, happy.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
      { speaker: 'yumiko_mom', jp: '伝統の味、引き継いでね。', en: "Traditional flavor — pass on.", style: 'warm older mother voice, soft warm wise delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、しっかり覚えます。', en: "Yes — properly remember.", style: 'soft committed adult woman voice, warm earnest delivery carefully' },
      { speaker: 'mei_romantic', jp: '私も、ちゃんと習得したい。', en: "I — properly master.", style: 'gentle young woman voice, soft warm determined delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ええ嫁、ええ娘やわ。', en: "Fine daughters-in-law, daughters.", style: 'tender older mother voice, soft warm loving delivery carefully' },
    ],
  },
  {
    id: 'conv_01932',
    context: 'Kenji helps Hiroshi-elder buy a new umbrella; small autumn outing.',
    purpose: 'Adult helping elder with practical small purchase.',
    ambient: 'shop_low_quiet',
    sound_effects: [],
    target_vocab: ['傘', '雨', '選ぶ', '丈夫'],
    cast: ['kenji_office', 'hiroshi_elder'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '傘、新しい欲しい。', en: "Umbrella — new want.", style: 'slow elder Kansai voice, warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええで、丈夫なん選ぼか。', en: "Sure — sturdy pick.", style: 'warm Kansai man voice, soft warm helpful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'これ、ちょっと小さいな。', en: "This — bit small.", style: 'gentle elder Kansai voice, soft warm thoughtful delivery carefully' },
      { speaker: 'kenji_office', jp: '大きいの、こっちに。', en: "Big — here.", style: 'soft Kansai man voice, warm helpful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、これにしよ。', en: "Yeah — this.", style: 'warm elder Kansai voice, soft fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01933',
    context: 'Sho-young arranges his own room for the first time; proud display to Mei.',
    purpose: 'Child showing independence task to mother.',
    ambient: 'bedroom_evening_warm',
    sound_effects: [],
    target_vocab: ['部屋', '飾る', '本棚', '机'],
    cast: ['sho_child', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、見て、お部屋!', en: "Mom — see, room!", style: 'thrilled child boy voice, bright warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、すごく綺麗!', en: "Oh — super pretty!", style: 'tender young mother voice, soft warm delighted delivery carefully' },
      { speaker: 'sho_child', jp: '机、本棚、整えた!', en: "Desk, bookshelf — arranged!", style: 'proud child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '一人で、頑張ったね。', en: "Alone — tried.", style: 'tender young mother voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、嬉しい!', en: "Yeah — happy!", style: 'bright child boy voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_01934',
    context: 'Ren and Aoi discuss buying a small piano for the cafe.',
    purpose: 'Two adults planning practical artistic upgrade.',
    ambient: 'cafe_morning_low',
    sound_effects: [],
    target_vocab: ['ピアノ', '置く', '音色', '雰囲気'],
    cast: ['ren_uni', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '蓮くん、ピアノ置きたいの。', en: "Ren — piano want place.", style: 'soft adult woman voice, warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: 'ええ案ですね、雰囲気変わる。', en: "Fine idea — mood changes.", style: 'gentle young man voice, soft warm impressed delivery carefully' },
      { speaker: 'aoi_barista', jp: '音色、優しい感じが欲しい。', en: "Tone — gentle feel want.", style: 'tender adult woman voice, soft warm fond delivery carefully' },
      { speaker: 'ren_uni', jp: '中古でも、いいですか?', en: "Used — fine?", style: 'soft young man voice, warm practical delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、状態よければ。', en: "Yeah — if state fine.", style: 'warm adult woman voice, soft flexible delivery carefully' },
      { speaker: 'ren_uni', jp: '一緒に、見に行きましょう。', en: "Together — go see.", style: 'soft young man voice, warm warm collaborative delivery carefully' },
      { speaker: 'aoi_barista', jp: '是非、お願い。', en: "By all means — please.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01935',
    context: 'Hiroshi-elder cleans his glasses while chatting with Sho-young.',
    purpose: 'Elder doing small task, casual chat with child.',
    ambient: 'tatami_quiet_lamp',
    sound_effects: [],
    target_vocab: ['眼鏡', '見える', '視力', '年'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、眼鏡、いつから?', en: "Grandpa — glasses, since when?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'もう、四十年や。', en: "Already — forty years.", style: 'slow elder Kansai voice, warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'よく見える?', en: "Well see?", style: 'soft child boy voice, warm warm curious delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おかげさんでな。', en: "Thankfully.", style: 'gentle elder Kansai voice, soft warm humble delivery carefully' },
      { speaker: 'sho_child', jp: '年、取っても、元気だね。', en: "Aged — still well.", style: 'tender child boy voice, soft warm admiring delivery carefully' },
    ],
  },
  {
    id: 'conv_01936',
    context: 'Naoko buys a small new clock for the ramen shop wall.',
    purpose: 'Aunt making practical small business purchase.',
    ambient: 'shop_morning_low',
    sound_effects: [],
    target_vocab: ['時計', '壁', 'デザイン', '見やすい'],
    cast: ['naoko_aunt', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '時計、壁にええの欲しいわ。', en: "Clock — wall want fine.", style: 'brassy Kansai aunt voice, bright loud engaged delivery carefully' },
      { speaker: 'kenji_office', jp: 'デザイン、これどう?', en: "Design — this how?", style: 'soft Kansai man voice, warm helpful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '見やすそうやな、ええで!', en: "Easy to see — fine!", style: 'animated Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: 'シンプルで、落ち着いてる。', en: "Simple — calm.", style: 'gentle Kansai man voice, soft warm approving delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'これに、決まりや!', en: "This — decided!", style: 'warm Kansai aunt voice, bright cheerful decisive delivery carefully' },
    ],
  },
  {
    id: 'conv_01937',
    context: 'Hina-young buys her first wallet on her own; tells Mei excitedly.',
    purpose: 'Teen showing personal purchase milestone to mentor.',
    ambient: 'living_room_evening_warm',
    sound_effects: [],
    target_vocab: ['財布', '自分', '色', '気に入る'],
    cast: ['hina_child', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、財布、買った!', en: "Mei — wallet, bought!", style: 'bright teen girl voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、見せて、可愛い!', en: "Oh — show, cute!", style: 'tender young woman voice, soft warm delighted delivery carefully' },
      { speaker: 'hina_child', jp: '色、気に入って!', en: "Color — like!", style: 'thrilled teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ええ選び方ね。', en: "Fine choice.", style: 'warm young woman voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: 'お小遣い、貯めて買った!', en: "Allowance — saved bought!", style: 'proud teen girl voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01938',
    context: 'Daichi unpacks new winter coats for the family with Sho-young.',
    purpose: 'Father preparing seasonal clothing with son.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['冬', 'コート', '暖かい', '準備'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '冬、近づいたな、コート用意。', en: "Winter near — coat prep.", style: 'warm Kansai father voice, soft cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'お父さん、これ、僕の?', en: "Dad — this, mine?", style: 'eager child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、暖かいで、しっかり着。', en: "Yeah — warm, wear well.", style: 'soft Kansai father voice, warm caring delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、嬉しい!', en: "Thanks — happy!", style: 'thrilled child boy voice, bright warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '一緒に、雪見ような。', en: "Together — snow see.", style: 'tender Kansai father voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01939',
    context: 'Sakura attempts to set up a new home office space; consults Ren.',
    purpose: 'Author setting up workspace with friend\'s help.',
    ambient: 'study_room_low',
    sound_effects: [],
    target_vocab: ['机', '椅子', '配置', '集中'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、机、ここでいい?', en: "Ren — desk, here okay?", style: 'gentle adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '窓向き、集中できますよ。', en: "Window facing — focus.", style: 'soft young man voice, warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '椅子、座ってみる。', en: "Chair — try sit.", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '高さ、合います?', en: "Height — fits?", style: 'gentle young man voice, soft warm caring delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、ぴったり!', en: "Yeah — perfect!", style: 'cheerful adult writer voice, bright warm delivery carefully' },
      { speaker: 'ren_uni', jp: '配置、ええ感じ。', en: "Layout — fine feel.", style: 'soft young man voice, warm approving delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとう、書きたくなる!', en: "Thanks — want to write!", style: 'tender adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01940',
    context: 'Aoi takes baby for a walk in stroller; runs into Asuka at the park.',
    purpose: 'Two adult women bumping into each other on walks.',
    ambient: 'park_morning_birds',
    sound_effects: [],
    target_vocab: ['散歩', '赤ちゃん', '会う', '元気'],
    cast: ['aoi_barista', 'asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '蒼さん、お散歩!', en: "Aoi — walk!", style: 'warm teacher voice, soft warm friendly delivery carefully' },
      { speaker: 'aoi_barista', jp: 'あ、あすかさん、お久しぶり!', en: "Oh — Asuka, long time!", style: 'soft adult woman voice, warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '赤ちゃん、元気そうね。', en: "Baby — looks well.", style: 'tender teacher voice, soft warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: 'おかげさまで、ぐんぐん成長。', en: "Thankfully — growing fast.", style: 'tender adult woman voice, soft warm proud delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'また、ご飯しましょう。', en: "Let's eat again.", style: 'warm teacher voice, soft warm friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_01941',
    context: 'Tatsuya-country builds a small wooden shelf with Hiroshi-elder.',
    purpose: 'Two elders building together; shared craft labor.',
    ambient: 'workshop_low_tools',
    sound_effects: [],
    target_vocab: ['棚', '木材', '釘', '組み立てる'],
    cast: ['tatsuya_country', 'hiroshi_elder'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: 'この木材、ええ感じやな。', en: "This wood — fine feel.", style: 'soft Tohoku farmer voice, warm focused delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、しっかりしとる。', en: "Yeah — sturdy.", style: 'gentle elder Kansai voice, soft warm approving delivery carefully' },
      { speaker: 'tatsuya_country', jp: '釘、打つで。', en: "Nail — hammer.", style: 'firm Tohoku voice, soft warm focused delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '丁寧に、組み立てよか。', en: "Carefully — assemble.", style: 'soft elder Kansai voice, warm warm patient delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お互い、年取っても、できる。', en: "Both — aged, can still.", style: 'warm Tohoku farmer voice, soft proud delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ふふ、嬉しいで、ほんま。', en: "Heh — happy, truly.", style: 'tender elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'tatsuya_country', jp: '棚、完成や、立派!', en: "Shelf — done, splendid!", style: 'soft Tohoku voice, warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01942',
    context: 'Yumiko gives Hina-young her grandmother\'s hairpin as a heirloom.',
    purpose: 'Elder passing meaningful heirloom across generations.',
    ambient: 'tatami_lamp_quiet',
    sound_effects: [],
    target_vocab: ['髪飾り', '受け取る', '大切', '伝統'],
    cast: ['yumiko_mom', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'ひな、これ、おばあちゃんの。', en: "Hina — this, grandma's.", style: 'tender older mother voice, soft warm reverent delivery carefully' },
      { speaker: 'hina_child', jp: 'まあ、本当にいいの?', en: "Oh — really fine?", style: 'awed teen girl voice, soft warm grateful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、お前に、託したい。', en: "Yeah — to you, entrust.", style: 'gentle older mother voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: '大切に、します。', en: "Cherish.", style: 'soft committed teen girl voice, warm tender delivery carefully' },
      { speaker: 'yumiko_mom', jp: '伝統、守ってね。', en: "Tradition — protect.", style: 'tender older mother voice, soft warm enduring delivery carefully' },
    ],
  },
  {
    id: 'conv_01943',
    context: 'Riku-teen helps Hina-young carry her heavy school books.',
    purpose: 'Older teen offering practical help to younger.',
    ambient: 'school_corridor_low',
    sound_effects: [],
    target_vocab: ['本', '重い', '手伝う', '助かる'],
    cast: ['riku_teen', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '陸くん、本、重い!', en: "Riku — books, heavy!", style: 'soft teen girl voice, warm tired honest delivery carefully' },
      { speaker: 'riku_teen', jp: '手伝うで、貸して!', en: "Help — lend!", style: 'warm teen boy voice, soft cheerful helpful delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、助かる。', en: "Thanks — saved.", style: 'gentle teen girl voice, soft warm grateful delivery carefully' },
      { speaker: 'riku_teen', jp: 'こんな量、毎日?', en: "Such amount — daily?", style: 'amazed teen boy voice, soft warm honest delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、勉強多い。', en: "Yeah — study many.", style: 'tired teen girl voice, soft warm honest delivery carefully' },
    ],
  },
  {
    id: 'conv_01944',
    context: 'Mei reorganizes the family closet with seasonal swap; Sho-young watches.',
    purpose: 'Mother teaching child organizing.',
    ambient: 'bedroom_afternoon_low',
    sound_effects: [],
    target_vocab: ['服', '季節', '整理', '片付け'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、何してるの?', en: "Mom — doing what?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: '服、季節で整理してるの。', en: "Clothes — season organizing.", style: 'gentle young mother voice, soft warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: '夏の服、しまうの?', en: "Summer clothes — put away?", style: 'soft child boy voice, warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、冬の服、出す。', en: "Yeah — winter, out.", style: 'soft young mother voice, warm warm practical delivery carefully' },
      { speaker: 'sho_child', jp: '手伝うね、片付け!', en: "Help — clean!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01945',
    context: 'Whole family helps Hiroshi-elder move to a small new apartment; many voices.',
    purpose: 'Multi-voice gentle family helping with major life change.',
    ambient: 'apartment_moving_warm',
    sound_effects: [],
    target_vocab: ['引っ越し', '荷物', '皆', '手伝う', '新しい'],
    cast: ['hiroshi_elder', 'mei_romantic', 'daichi_kansai', 'sho_child', 'hina_child', 'naoko_aunt', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '新しい家、ドキドキするわ。', en: "New home — heart pounds.", style: 'slow elder Kansai voice, warm cheerful nervous delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おとうさん、皆で手伝うで!', en: "Otosan — all help!", style: 'warm Kansai husband voice, soft warm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: '荷物、これで全部?', en: "Bags — all this?", style: 'gentle young woman voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: 'おじいちゃん、ここ、明るいね!', en: "Grandpa — here, bright!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: '新しい部屋、楽しい!', en: "New room — fun!", style: 'thrilled child boy voice, bright warm delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お祝い、ラーメン、用意したで!', en: "Celebration ramen — prepared!", style: 'brassy Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: 'これからも、いつでも、来るで。', en: "Going forward — anytime, come.", style: 'soft Kansai man voice, warm fond loyal delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '皆の助け、本当にありがたい。', en: "Everyone's help — truly grateful.", style: 'gentle elder Kansai voice, soft warm tender delivery carefully' },
      { speaker: 'daichi_kansai', jp: '家族や、当たり前や!', en: "Family — natural!", style: 'warm Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お父さん、これからもよろしく。', en: "Dad — going forward please.", style: 'tender young woman voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: 'おじいちゃん、毎週来るね!', en: "Grandpa — weekly come!", style: 'bright teen girl voice, soft warm promising delivery carefully' },
      { speaker: 'sho_child', jp: '僕も、たくさん遊びに来る!', en: "I — many visit!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'みんなおって、寂しくないわ。', en: "All here — not lonely.", style: 'tender elder Kansai voice, soft warm content delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_097 wrote', CONVERSATIONS.length, 'files');
