import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_138)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // THEME A — academic (著作 参照 疑問 賞 与える + いただく)
  C('conv_02741',
    'Asuka lectures on copyright and citing sources.',
    'WIDENED SCENARIO: lecture; academic vocabulary (著作/参照/疑問/賞/与える) in natural home.',
    'lecture_hall_quiet',
    ['著作', '参照', '疑問', '賞', '与える'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '論文では、著作の出典を必ず示します。', en: "In papers, always cite the source of works.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '参照した本も、書くんですか?', en: "Do I write the books I referenced too?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、参照した著作を、全て載せます。', en: "Yes, list every work you referenced.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '一つ、疑問があるんですが。', en: "I have one question.", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '疑問は、遠慮なく聞いて下さいね。', en: "Please ask your questions freely.", style: 'warm teacher voice, soft warm measured encouraging clarity throughout' },
      { speaker: 'sakura_teen', jp: '良い論文には、賞が出るんですか?', en: "Do good papers receive awards?", style: 'engaged adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '優れた著作には、賞が与えられます。', en: "Excellent works are given awards.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '参照を大切に、書いてみます。', en: "Valuing citations, I'll try writing.", style: 'resolved adult student voice, soft warm appreciative closing throughout' },
    ]),

  C('conv_02742',
    'Ren consults Asuka about referencing a source.',
    'WIDENED SCENARIO: academic guidance; vocabulary (著作/参照/疑問/賞/与える) in natural home.',
    'lecture_hall_quiet',
    ['著作', '参照', '疑問', '賞', '与える'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この著作を、参照してもいいですか?', en: "May I reference this work?", style: 'earnest young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、参照する時は出典を示しましょう。', en: "Yes, show the source when you reference it.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '内容に、疑問が残るんです。', en: "I still have a question about the content.", style: 'thoughtful young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'その疑問を、論文で扱うといいですよ。', en: "It's good to address that question in your paper.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'この著作は、賞を取ったんですか?', en: "Did this work win an award?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、大きな賞を与えられました。', en: "Yes, it was given a major award.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '私にも、ヒントを与えてくれそうです。', en: "It seems it'll give me hints too.", style: 'engaged young student voice, soft warm throughout' },
      { speaker: 'asuka_teacher', jp: '疑問を、参照で深めていきましょう。', en: "Let's deepen your question through references.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02743',
    'Sakura interviews an award-winning author.',
    'WIDENED SCENARIO: author interview; vocabulary (著作/参照/疑問/賞/与える) in natural home.',
    'office_quiet_low',
    ['著作', '参照', '疑問', '賞', '与える'],
    ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'ご著作が、賞を受けられたそうですね。', en: "I hear your work received an award.", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、思いがけず賞を与えられました。', en: "Yes, I was unexpectedly given an award.", style: 'modest author voice, soft warm gentle clarity throughout' },
      { speaker: 'sakura_teen', jp: '執筆中、疑問は多かったですか?', en: "Were there many questions while writing?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '疑問のたびに、古い著作を参照しました。', en: "With each question, I referenced old works.", style: 'reflective author voice, soft warm gentle clarity throughout' },
      { speaker: 'sakura_teen', jp: '参照した本は、多かったんですか?', en: "Did you reference many books?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '数えきれない著作を、参照しました。', en: "I referenced countless works.", style: 'warm author voice, soft warm gentle clarity throughout' },
      { speaker: 'sakura_teen', jp: '読者に、何を与えたいですか?', en: "What do you want to give readers?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '小さな疑問を、与えたいですね。', en: "I'd like to give them small questions.", style: 'gentle author voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_02744',
    'Asuka gives Ren feedback on a draft.',
    'WIDENED SCENARIO: academic feedback; vocabulary (著作/参照/疑問/賞/与える) in natural home.',
    'lecture_hall_quiet',
    ['著作', '参照', '疑問', '賞', '与える'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '良く書けています。賞を狙えますよ。', en: "Well written. You could aim for an award.", style: 'composed teacher voice, soft warm encouraging clarity throughout' },
      { speaker: 'ren_uni', jp: '本当ですか?疑問もありますが。', en: "Really? Though I have questions.", style: 'surprised young student voice, soft warm earnest throughout' },
      { speaker: 'asuka_teacher', jp: 'その疑問を、結論で与えるといいですね。', en: "It's good to pose that question in your conclusion.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '参照が、足りないでしょうか?', en: "Are the references insufficient?", style: 'thoughtful young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'もう一つ、著作を参照しましょう。', en: "Let's reference one more work.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'どの著作を、参照すべきですか?', en: "Which work should I reference?", style: 'engaged young student voice, soft warm throughout' },
      { speaker: 'asuka_teacher', jp: '古典が、深みを与えてくれますよ。', en: "The classics will give it depth.", style: 'warm teacher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '疑問を大切に、書き直します。', en: "Valuing the question, I'll rewrite it.", style: 'resolved young student voice, soft warm appreciative closing throughout' },
    ]),

  C('conv_02745',
    'Mei and Asuka discuss an award-winning book.',
    'WIDENED SCENARIO: literature chat; vocabulary (著作/参照/疑問/賞/与える) in natural home.',
    'living_room_quiet',
    ['著作', '参照', '疑問', '賞', '与える'],
    ['mei_romantic', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この著作、賞を取ったんですよね?', en: "This work won an award, right?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、世界的な賞を与えられました。', en: "Yes, it was given an international award.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '読んでいて、疑問が浮かびました。', en: "While reading, questions came to me.", style: 'thoughtful woman voice, soft warm curious delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'その疑問が、読書を豊かにします。', en: "Those questions enrich your reading.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '著者は、何を参照したんでしょう?', en: "What did the author reference?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '多くの古い著作を、参照したようです。', en: "It seems they referenced many old works.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: 'この本は、私に勇気を与えてくれました。', en: "This book gave me courage.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '良い著作は、疑問と答えを与えますね。', en: "A good work gives both questions and answers.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  // THEME B — daily objects (ケース モノ セット ビル 倍)
  C('conv_02746',
    'Mei and Aoi shop for a phone case.',
    'Casual register; daily vocabulary (ケース/モノ/セット/ビル/倍) in natural home.',
    'cafe_quiet_chatter',
    ['ケース', 'モノ', 'セット', 'ビル', '倍'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'スマホのケースを、探しているの。', en: "I'm looking for a phone case.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'aoi_barista', jp: 'あのビルのお店、品揃えがいいよ。', en: "The shop in that building has good selection.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ケースとフィルムの、セットがいいな。', en: "A case-and-film set would be nice.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'セットだと、安くなるモノも多いよ。', en: "As a set, many things are cheaper.", style: 'helpful barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '単品だと、倍の値段なんだって。', en: "Bought separately, it's twice the price.", style: 'surprised woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'じゃあ、セットの方がお得なモノだね。', en: "Then the set is the better deal.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'あのビルの上の階に、あるかな?', en: "Is it on the upper floor of that building?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '行ってみよう。いいケース、見つかるよ!', en: "Let's go. You'll find a good case!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02747',
    'Kenji helps Yuki choose an equipment set.',
    'WIDENED SCENARIO: office shopping; vocabulary (ケース/モノ/セット/ビル/倍) in natural home.',
    'office_quiet_low',
    ['ケース', 'モノ', 'セット', 'ビル', '倍'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '会議室の備品を、揃えたいの。', en: "I want to equip the meeting room.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'まとめてセットで買うと、安いですよ。', en: "Buying as a set is cheaper.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'ケースに入った道具も、要りますね。', en: "We need tools in a case too.", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '隣のビルの店に、良いモノがあります。', en: "The shop in the next building has good ones.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '単品だと、倍くらいするんですか?', en: "Separately, is it about double?", style: 'curious office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'ええ、セットなら倍も得します。', en: "Yes, as a set you save twofold.", style: 'reassuring office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '丈夫なモノを、選びたいですね。', en: "I'd like to choose sturdy ones.", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'ビルの店で、ケースごと見ましょう。', en: "At the building's shop, let's look case by case.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02748',
    'Riku and Aoi compare game gear deals.',
    'Casual register; daily vocabulary (ケース/モノ/セット/ビル/倍) in natural home.',
    'cafe_quiet_chatter',
    ['ケース', 'モノ', 'セット', 'ビル', '倍'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '新しいゲーム機、セットで買ったんだ!', en: "I bought the new console as a set!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、ケースも付いてたの?', en: "Nice, did it come with a case?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、ケースとソフトのセットだよ。', en: "Yeah, a case-and-software set.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ばらばらだと、倍したんじゃない?', en: "Bought separately, wasn't it double?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'そう、倍くらいするモノだったよ。', en: "Yeah, it was about twice the price.", style: 'pleased teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'どのビルの店で、買ったの?', en: "Which building's shop did you buy at?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '駅前のビルの、ゲーム屋だよ。', en: "The game shop in the building by the station.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'セットで買うの、賢いモノの選び方だね!', en: "Buying as a set is a smart way to choose!", style: 'bubbly barista voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02749',
    'Daichi sells a gift set to Mei at a shop.',
    'WIDENED SCENARIO: shop chat; vocabulary (ケース/モノ/セット/ビル/倍) in natural home.',
    'street_quiet_distant',
    ['ケース', 'モノ', 'セット', 'ビル', '倍'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '贈り物に、いいモノを探しています。', en: "I'm looking for a nice gift.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'このお茶のセット、人気やで。', en: "This tea set is popular.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '木のケースが、素敵ですね。', en: "The wooden case is lovely.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ケース付きは、見栄えがええモノやな。', en: "With a case, it looks nice.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '単品だと、倍くらいしますか?', en: "Separately, is it about double?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'セットやと、倍お得やで。', en: "As a set, it's twice the value.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'このビルに、お店があって助かりました。', en: "I'm glad there's a shop in this building.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ええモノを選んだなあ。喜ばれるで!', en: "You chose a good one. They'll be pleased!", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_02750',
    'Yumiko and Sho organize a craft set at home.',
    'Casual home register; vocabulary (ケース/モノ/セット/ビル/倍) in natural home.',
    'kitchen_evening_quiet',
    ['ケース', 'モノ', 'セット', 'ビル', '倍'],
    ['yumiko_mom', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'ママ、お絵かきセットを出して!', en: "Mom, get out the drawing set!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'はいはい、ケースから出しましょうね。', en: "Okay okay, let's take it out of the case.", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: 'クレヨンが、前の倍になったよ!', en: "There are twice as many crayons as before!", style: 'delighted small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'セットで買うと、たくさん入っているのよ。', en: "Buying a set gives you lots.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '高いビルの絵を、描きたい!', en: "I want to draw a tall building!", style: 'eager small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'いいわね。好きなモノを描きましょう。', en: "Lovely. Draw whatever you like.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'ケースに、ちゃんと戻すね!', en: "I'll put it back in the case properly!", style: 'proud small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'えらいわ。大事なモノだものね。', en: "Good boy. It's something precious.", style: 'tender mother voice, soft warm closing delivery throughout' },
    ]),

  // THEME C — time/work (先ほど 時刻 とおり 午前 前回)
  C('conv_02751',
    'Yuki and Kenji confirm a meeting schedule.',
    'WIDENED SCENARIO: office scheduling; vocabulary (先ほど/時刻/とおり/午前/前回) in natural home.',
    'office_quiet_low',
    ['先ほど', '時刻', 'とおり', '午前', '前回'],
    ['yuki_office', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '先ほど、会議の連絡が来ました。', en: "A meeting notice came just now.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '開始の時刻は、決まりましたか?', en: "Is the start time decided?", style: 'attentive office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '前回どおり、午前十時です。', en: "As last time, 10 a.m.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '前回の資料も、使いますか?', en: "Do we use last time's materials too?", style: 'curious office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '先ほどの連絡では、そのとおりです。', en: "Per the notice just now, that's right.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '午前中に、準備を終えましょう。', en: "Let's finish prep in the morning.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '時刻に遅れないよう、気をつけます。', en: "I'll be careful not to be late.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '前回どおり、スムーズにいきましょう。', en: "Let's go smoothly, like last time.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02752',
    'Hiroshi-boss reviews a schedule with Ren.',
    'WIDENED SCENARIO: business scheduling; vocabulary (先ほど/時刻/とおり/午前/前回) in natural home.',
    'office_quiet_low',
    ['先ほど', '時刻', 'とおり', '午前', '前回'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '先ほどの件は、どうなったかね?', en: "How did the matter from earlier go?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '前回の予定どおり、進んでいます。', en: "It's going as last time's schedule.", style: 'reliable young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '訪問の時刻は、いつかね?', en: "When is the visit time?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '午前十一時の予定です。', en: "It's scheduled for 11 a.m.", style: 'precise young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '先ほど、先方から連絡はあったかね?', en: "Did the other party contact us earlier?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'はい、予定どおりだと先ほど確認しました。', en: "Yes, I confirmed just now it's as scheduled.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '前回より、早く着くようにな。', en: "Arrive earlier than last time.", style: 'firm boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '午前のうちに、向かいます。', en: "I'll head over in the morning.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_02753',
    'Saito explains a morning appointment to a patient.',
    'WIDENED SCENARIO: clinic scheduling; vocabulary (先ほど/時刻/とおり/午前/前回) in natural home.',
    'clinic_room_quiet',
    ['先ほど', '時刻', 'とおり', '午前', '前回'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '次の予約は、いつでしょうか?', en: "When is my next appointment?", style: 'polite office woman voice, soft warm clarity throughout' },
      { speaker: 'saito_doctor', jp: '前回どおり、午前がよろしいですね。', en: "As last time, morning is good.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: '時刻は、九時で大丈夫ですか?', en: "Is nine o'clock okay?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'saito_doctor', jp: '先ほど確認したとおり、九時で取れます。', en: "As I checked just now, nine is available.", style: 'clear doctor voice, soft warm measured clarity throughout' },
      { speaker: 'yuki_office', jp: '前回の検査の結果も、聞けますか?', en: "Can I hear last time's test results too?", style: 'curious office woman voice, soft warm clarity throughout' },
      { speaker: 'saito_doctor', jp: 'ええ、前回の結果も、その時刻にお伝えします。', en: "Yes, I'll share last time's results at that time.", style: 'gentle doctor voice, soft warm reassuring clarity throughout' },
      { speaker: 'yuki_office', jp: '午前なら、仕事の前に来られます。', en: "If it's morning, I can come before work.", style: 'relieved office woman voice, soft warm clarity throughout' },
      { speaker: 'saito_doctor', jp: 'では、そのとおり予約しておきますね。', en: "Then I'll book it accordingly.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_02754',
    'Asuka confirms a class time with Sakura.',
    'WIDENED SCENARIO: class scheduling; vocabulary (先ほど/時刻/とおり/午前/前回) in natural home.',
    'lecture_hall_quiet',
    ['先ほど', '時刻', 'とおり', '午前', '前回'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '先生、次の授業はいつですか?', en: "Teacher, when's the next class?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '前回どおり、午前の授業です。', en: "As last time, it's a morning class.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '時刻は、変わっていませんか?', en: "Has the time not changed?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '先ほどの連絡のとおり、変わりません。', en: "As the notice just now said, it's unchanged.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '前回の宿題も、提出ですか?', en: "Do we submit last time's homework too?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、前回の分も午前に集めます。', en: "Yes, I'll collect last time's in the morning too.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '時刻に、遅れないようにします。', en: "I'll make sure not to be late.", style: 'resolved adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '先ほど伝えたとおり、楽しみにしていますね。', en: "As I said just now, I look forward to it.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02755',
    'Daichi and Mei plan an early-morning departure.',
    'Casual register; vocabulary (先ほど/時刻/とおり/午前/前回) in natural home.',
    'cafe_quiet_chatter',
    ['先ほど', '時刻', 'とおり', '午前', '前回'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '明日は、午前に出発しよか。', en: "Let's leave in the morning tomorrow.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '時刻は、何時くらいがいいですか?', en: "What time is good?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: '前回どおり、八時でええかな。', en: "Like last time, eight should be fine.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '先ほど、天気を調べたんです。', en: "I checked the weather just now.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'おお、で、予報のとおり晴れる?', en: "Oh, and per the forecast, will it be sunny?", style: 'curious Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ええ、午前は晴れるそうです。', en: "Yes, it'll be sunny in the morning.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ほな、前回より早う着けるな。', en: "Then we'll arrive earlier than last time.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '時刻どおりに、出ましょうね。', en: "Let's leave right on time.", style: 'gentle woman voice, soft warm closing delivery throughout' },
    ]),

  // THEME D — civic/abstract (総合 一体 さまざま 多数 有効)
  C('conv_02756',
    'Asuka lectures on integrating diverse viewpoints.',
    'WIDENED SCENARIO: lecture; abstract vocabulary (総合/一体/さまざま/多数/有効) in natural home.',
    'lecture_hall_quiet',
    ['総合', '一体', 'さまざま', '多数', '有効'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'さまざまな意見を、総合して考えます。', en: "We integrate various opinions and think.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '多数の意見が、正しいんですか?', en: "Is the majority opinion correct?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '多数が、常に正しいとは限りません。', en: "The majority isn't always right.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'では、どう総合するんですか?', en: "Then how do we integrate them?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'さまざまな視点を、一体として見ます。', en: "We view various perspectives as one whole.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'それは、有効な方法ですか?', en: "Is that an effective method?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、最も有効な考え方の一つです。', en: "Yes, one of the most effective ways of thinking.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'さまざまを総合する力、養いたいです。', en: "I want to cultivate the power to integrate the various.", style: 'resolved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_02757',
    'News discussion: Sakura and Ren on a comprehensive plan.',
    'WIDENED SCENARIO: news-analysis; abstract vocabulary (総合/一体/さまざま/多数/有効) in natural home.',
    'studio_room_tone',
    ['総合', '一体', 'さまざま', '多数', '有効'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '市が、総合的な計画を発表しました。', en: "The city announced a comprehensive plan.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'さまざまな分野を、含むんですか?', en: "Does it include various fields?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、さまざまな課題を総合しています。', en: "Yes, it integrates various issues.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '多数の住民が、賛成していますか?', en: "Do many residents support it?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '多数が、有効な計画だと評価しています。', en: "The majority rates it an effective plan.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '市と住民が、一体となれますか?', en: "Can the city and residents become one?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '一体となって、進めることが有効です。', en: "Advancing as one is effective.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'さまざまな声を、総合してほしいですね。', en: "I hope they integrate the various voices.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02758',
    'Hiroshi-boss and Yuki design a company-wide policy.',
    'WIDENED SCENARIO: business strategy; abstract vocabulary (総合/一体/さまざま/多数/有効) in natural home.',
    'office_quiet_low',
    ['総合', '一体', 'さまざま', '多数', '有効'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: 'さまざまな部署を、一体にしたい。', en: "I want to unite the various departments.", style: 'composed boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '総合的な方針が、必要ですね。', en: "A comprehensive policy is needed.", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '多数の社員の声を、集めてくれ。', en: "Gather many employees' voices.", style: 'measured boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: 'さまざまな意見が、集まっています。', en: "Various opinions are gathering.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'それを総合し、有効な策にしよう。', en: "Let's integrate them into an effective measure.", style: 'firm boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '一体感を、生む方針にしたいです。', en: "I want a policy that creates unity.", style: 'earnest office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '多数が納得する、有効な形をな。', en: "An effective form the majority accepts.", style: 'composed boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '総合的に、まとめてみます。', en: "I'll pull it together comprehensively.", style: 'resolved office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02759',
    'Ren reports a survey synthesis to Hiroshi-boss.',
    'WIDENED SCENARIO: research report; abstract vocabulary (総合/一体/さまざま/多数/有効) in natural home.',
    'office_quiet_low',
    ['総合', '一体', 'さまざま', '多数', '有効'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'さまざまなデータを、総合しました。', en: "I integrated various data.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '多数の回答が、集まったのかね?', en: "Did many responses come in?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'はい、多数の回答を総合しました。', en: "Yes, I integrated many responses.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '何か、有効な結論は出たかね?', en: "Did any effective conclusion emerge?", style: 'engaged boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '有効な改善点が、いくつか見えました。', en: "Several effective improvements became visible.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '部署が一体で、取り組めるかね?', en: "Can departments tackle it as one?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'さまざまな部署が、一体で動けます。', en: "Various departments can move as one.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '総合的に、よくまとめてくれた。', en: "You synthesized it well overall.", style: 'satisfied boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02760',
    'Asuka and Riku discuss diverse ecosystems.',
    'WIDENED SCENARIO: science lecture; abstract vocabulary (総合/一体/さまざま/多数/有効) in natural home.',
    'lecture_hall_quiet',
    ['総合', '一体', 'さまざま', '多数', '有効'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '森には、さまざまな生き物がいます。', en: "A forest has various creatures.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '多数の生き物が、関わるんですか?', en: "Do many creatures interrelate?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、多数の命が一体で生きています。', en: "Yes, many lives live as one whole.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'それを、どう調べるんですか?', en: "How do we study that?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'さまざまな情報を、総合して調べます。', en: "We integrate various information to study it.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '森を守るのに、有効な方法は?', en: "What's an effective way to protect the forest?", style: 'thoughtful teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '総合的な保護が、最も有効です。', en: "Comprehensive protection is most effective.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '森が一体だって、よく分かりました。', en: "I understand the forest is one whole.", style: 'moved teen boy voice, soft warm realization throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_138 wrote', CONVERSATIONS.length, 'files');
