import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_125)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02481',
    'Political news: Sakura and Ren on a legal reform.',
    'WIDENED SCENARIO: political news; civic vocabulary (氏/大臣/平成/法律) in natural home.',
    'studio_room_tone',
    ['氏', '大臣', '平成', '法律', '現在'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '現在、法律の改正が進んでいます。', en: "A revision of the law is currently underway.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'この法律は、平成から続く課題ですね。', en: "This law is an issue carried over from Heisei.", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '担当の大臣は、何と説明しましたか?', en: "How did the minister in charge explain it?", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '大臣は、現状の問題点を認めました。', en: "The minister acknowledged the current problems.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '佐藤氏も、賛成しているんですか?', en: "Does Mr. Sato also support it?", style: 'curious adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '氏は、慎重な立場を取っています。', en: "He takes a cautious stance.", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '現在の法律で、十分なのでしょうか。', en: "Is the current law sufficient?", style: 'thoughtful adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '平成の時代とは、状況が違いますからね。', en: "Conditions differ from the Heisei era.", style: 'reflective young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02482',
    'Civic news: Sakura and Ren on a public disclosure.',
    'WIDENED SCENARIO: news-analysis; civic vocabulary (氏/大臣/公開/発生) in natural home.',
    'studio_room_tone',
    ['氏', '大臣', '公開', '発生', 'これら'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '本日、新しい資料が公開されました。', en: "New materials were disclosed today.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'これらの資料で、何が分かりますか?', en: "What do these materials reveal?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '問題が発生した経緯等が、記されています。', en: "The circumstances of the issue and so on are recorded.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '担当の大臣は、公開を認めたんですね。', en: "So the minister in charge approved the disclosure.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: 'はい、山田氏が会見で説明しました。', en: "Yes, Mr. Yamada explained at the briefing.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'これらの情報で、信頼が戻るといいですね。', en: "I hope this information restores trust.", style: 'thoughtful young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '再発生を防ぐ取り組みも、必要です。', en: "Efforts to prevent recurrence are needed too.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '氏の今後の対応に、注目しましょう。', en: "Let's watch his future response.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02483',
    'Economic news: Ren and Yuki on consumer spending.',
    'WIDENED SCENARIO: economic discussion; finance vocabulary (金融/ビジネス/ドル/億/購入) in natural home.',
    'office_quiet_low',
    ['金融', 'ビジネス', 'ドル', '億', '購入'],
    ['ren_uni', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '昨年、高額な購入が増えました。', en: "Last year, expensive purchases increased.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: 'ビジネスにも、追い風ですね。', en: "That's a tailwind for business too.", style: 'engaged office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '購入額は、合計で数億に達しました。', en: "Total purchases reached several hundred million.", style: 'precise young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '金融市場の反応は、どうでしたか?', en: "How did the financial markets react?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '金融機関も、前向きに見ています。', en: "Financial institutions view it positively too.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: 'ドルの動きは、影響しましたか?', en: "Did dollar movements have an effect?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'ドル高で、輸入品の購入は減りました。', en: "With a strong dollar, imported-goods purchases fell.", style: 'analytical young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: 'ビジネスの判断が、難しい時期ですね。', en: "It's a tricky time for business decisions.", style: 'reflective office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02484',
    'Economic news: Ren and Yuki on the manufacturing sector.',
    'WIDENED SCENARIO: economic discussion; industry vocabulary (金融/ビジネス/産業/生産/与え) in natural home.',
    'office_quiet_low',
    ['金融', 'ビジネス', '産業', '生産', '与え'],
    ['ren_uni', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '昨年、産業の生産が回復しました。', en: "Last year, industrial production recovered.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '生産の増加は、雇用に影響しますか?', en: "Does rising production affect employment?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'ええ、雇用に良い影響を与えています。', en: "Yes, it's having a good effect on employment.", style: 'precise young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '金融の支援も、あったんですか?', en: "Was there financial support too?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '金融機関が、産業に資金を与えました。', en: "Financial institutions provided funds to industry.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '新しいビジネスも、生まれそうですね。', en: "New businesses seem likely to emerge too.", style: 'hopeful office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'ビジネスの広がりが、産業を支えます。', en: "The spread of business supports industry.", style: 'analytical young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '生産が安定すると、安心ですね。', en: "When production stabilizes, it's reassuring.", style: 'warm office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02485',
    'Geography documentary: Asuka and Riku on neighboring countries.',
    'WIDENED SCENARIO: geography discussion; place vocabulary (県/ドイツ/韓国/側/アメリカ) in natural home.',
    'living_room_quiet',
    ['県', 'ドイツ', '韓国', '側', 'アメリカ'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '日本の西側には、何があるんですか?', en: "What's to the west of Japan?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '西側には、韓国や中国があります。', en: "To the west are Korea and China.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '韓国は、どの県から近いんですか?', en: "Which prefecture is Korea close to?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '西の県から、海を越えてすぐです。', en: "Right across the sea from the western prefectures.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'ドイツやアメリカは、遠いんですよね。', en: "Germany and America are far, right?", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ドイツは西、アメリカは東の側です。', en: "Germany is to the west, America to the east.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '各県から見ると、世界が広いですね。', en: "Seen from each prefecture, the world is wide.", style: 'reflective teen boy voice, soft warm understanding throughout' },
      { speaker: 'asuka_teacher', jp: 'ドイツも韓国も、いつか訪ねたいですね。', en: "I'd like to visit both Germany and Korea someday.", style: 'warm teacher voice, soft warm encouraging gentle clarity throughout' },
    ]),

  C('conv_02486',
    'History documentary discussion: Asuka and Ren on the postwar world.',
    'WIDENED SCENARIO: history discussion; geopolitics vocabulary (県/ドイツ/米国/軍/平成) in natural home.',
    'living_room_quiet',
    ['ドイツ', '米国', '軍', '平成', '等'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '戦後、ドイツはどう復興したんですか?', en: "How did Germany rebuild after the war?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '米国等の支援を受けて、立て直しました。', en: "It rebuilt with support from the US and others.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '米国の軍も、駐留したんですか?', en: "Did the US military station there too?", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、各地に軍が置かれました。', en: "Yes, forces were placed in various regions.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '日本は、平成に何が変わりましたか?', en: "What changed for Japan in Heisei?", style: 'thoughtful young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '平成は、国際協力が広がった時代です。', en: "Heisei was an age when international cooperation spread.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'ドイツ等の例から、学べそうですね。', en: "We can learn from examples like Germany.", style: 'understanding young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: '歴史は、平成も含めて続いていますよ。', en: "History continues, Heisei included.", style: 'warm teacher voice, soft warm measured clarity throughout' },
    ]),

  C('conv_02487',
    'Kenji helps Yuki set up a dashboard tool.',
    'WIDENED SCENARIO: tech help; UI vocabulary (レベル/ポイント/センター/固定/バック) in natural home.',
    'office_quiet_low',
    ['レベル', 'ポイント', 'センター', '固定', 'バック'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'この画面、設定が難しいの。', en: "This screen's settings are hard.", style: 'mildly stuck office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: '表示のレベルを、下げてみて下さい。', en: "Try lowering the display level.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'レベルを下げたら、見やすくなった。', en: "Lowering the level made it easier to see.", style: 'relieved office woman voice, soft warm engaged delivery throughout' },
      { speaker: 'kenji_office', jp: '大事な項目は、固定しておきましょう。', en: "Let's fix the important items in place.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '間違えたら、バックできますか?', en: "If I make a mistake, can I go back?", style: 'cautious office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: 'ええ、左上のバックで戻れます。', en: "Yes, the back arrow at top-left returns you.", style: 'reassuring office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '注目すべきポイントは、どこですか?', en: "Where's the point to watch?", style: 'focused office woman voice, soft warm engaged delivery throughout' },
      { speaker: 'kenji_office', jp: '困ったら、支援センターに聞いて下さい。', en: "If stuck, ask the support center.", style: 'helpful office man voice, soft warm patient closing throughout' },
    ]),

  C('conv_02488',
    'Kenji and Ren build a presentation for a client.',
    'WIDENED SCENARIO: tech/work; presentation vocabulary (レベル/ポイント/携帯/イメージ/作成) in natural home.',
    'office_quiet_low',
    ['レベル', 'ポイント', '携帯', 'イメージ', '作成'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '資料の作成、手伝ってもらえますか?', en: "Can you help me create the materials?", style: 'earnest young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: 'いいですよ。まず全体のイメージを決めましょう。', en: "Sure. First let's set the overall image.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '伝えたいポイントは、三つあります。', en: "There are three points I want to convey.", style: 'focused young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: '内容のレベルは、相手に合わせましょう。', en: "Let's match the content's level to the audience.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '携帯でも、見やすく作成できますか?', en: "Can we make it readable on a phone too?", style: 'curious young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: 'ええ、携帯用のイメージも作成します。', en: "Yes, I'll create a phone version image too.", style: 'reassuring office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'ポイントが、はっきり伝わりそうです。', en: "The points seem to come across clearly.", style: 'satisfied young colleague voice, soft warm appreciative throughout' },
      { speaker: 'kenji_office', jp: '良いイメージに、仕上がりましたね。', en: "It came together into a good image.", style: 'pleased office man voice, soft warm closing throughout' },
    ]),

  C('conv_02489',
    'Sakura reports on a new product launch event.',
    'WIDENED SCENARIO: news feature; launch vocabulary (作成/登場/これら/等) in natural home.',
    'studio_room_tone',
    ['作成', '登場', 'これら', '等', 'イメージ'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '今日、新しい商品が登場しました。', en: "A new product debuted today.", style: 'bright adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'これらの商品の特徴は、何ですか?', en: "What are the features of these products?", style: 'curious young reporter voice, soft warm engaged throughout' },
      { speaker: 'sakura_teen', jp: '専用のアプリ等で、簡単に使えます。', en: "You can use them easily with a dedicated app and such.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'これらの宣伝は、誰が作成したんですか?', en: "Who created these advertisements?", style: 'engaged young reporter voice, soft warm curious throughout' },
      { speaker: 'sakura_teen', jp: '若いチームが、作成したそうです。', en: "A young team created them, apparently.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '商品のイメージも、新しいですね。', en: "The product's image is fresh too.", style: 'engaged young reporter voice, soft warm throughout' },
      { speaker: 'sakura_teen', jp: '新顔の登場で、市場が動きそうです。', en: "With newcomers debuting, the market may move.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'これらの動きに、注目したいですね。', en: "I'd like to watch these moves.", style: 'warm young reporter voice, soft warm closing throughout' },
    ]),

  C('conv_02490',
    'Asuka lectures on argument and stance.',
    'WIDENED SCENARIO: lecture; stance connectives (に対する/に関して/に関する/つつ/のみ) in natural home.',
    'lecture_hall_quiet',
    ['に対する', 'に関して', 'に関する', 'つつ', 'のみ'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '意見に対する反論も、尊重しましょう。', en: "Let's respect counterarguments to an opinion too.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'その問題に関して、資料はありますか?', en: "Are there materials regarding that issue?", style: 'engaged young student voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: '歴史に関する資料が、役立ちます。', en: "History-related materials are useful.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '事実のみで、説得できるんですか?', en: "Can you persuade with facts alone?", style: 'thoughtful young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '事実のみでなく、感情も大切です。', en: "Not facts alone — emotion matters too.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '相手に対する敬意も、必要ですね。', en: "Respect toward the other party is needed too.", style: 'understanding young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '相手を尊重しつつ、主張を述べます。', en: "We state our claim while respecting the other.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'この件に関して、よく分かりました。', en: "I understand well regarding this matter.", style: 'grateful young student voice, soft warm appreciative throughout' },
    ]),

  C('conv_02491',
    'Asuka lectures on values and priorities.',
    'WIDENED SCENARIO: philosophy lecture; literary forms (に対する/に関して/その他/あろ/最も) in natural home.',
    'lecture_hall_quiet',
    ['に対する', 'に関して', 'その他', 'あろ', '最も'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '人生で、最も大切なものは何であろうか。', en: "What might be the most important thing in life?", style: 'contemplative teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'mei_romantic', jp: '人に対する優しさ、でしょうか。', en: "Kindness toward people, perhaps?", style: 'soft thoughtful woman voice, gentle warm attentive throughout' },
      { speaker: 'asuka_teacher', jp: '優しさは、最も尊い価値の一つです。', en: "Kindness is one of the most precious values.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'mei_romantic', jp: 'お金やその他のものは、どうですか?', en: "What about money and other things?", style: 'gentle woman voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: 'その他の価値も、無意味ではありません。', en: "Other values aren't meaningless either.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'mei_romantic', jp: '幸福に関して、答えはあるんでしょうか。', en: "Is there an answer regarding happiness?", style: 'soft woman voice, gentle warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: '幸福に関して、答えは人それぞれであろう。', en: "Regarding happiness, the answer differs by person.", style: 'reflective teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'mei_romantic', jp: '最も大切なのは、問い続ける心ですね。', en: "What matters most is a heart that keeps questioning.", style: 'moved woman voice, soft warm quiet realization throughout' },
    ]),

  C('conv_02492',
    'Asuka opens a seminar and frames the topics.',
    'WIDENED SCENARIO: lecture opening; formal discourse markers (さて/そこで/および/なし/知識) in natural home.',
    'lecture_hall_quiet',
    ['さて', 'そこで', 'および', 'なし', '知識'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'さて、今日は二つの話題を扱います。', en: "Now, today we'll cover two topics.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '予備の知識は、必要ですか?', en: "Is prior knowledge needed?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '知識なしでも、理解できる内容です。', en: "It's content you can grasp even without knowledge.", style: 'reassuring teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'asuka_teacher', jp: '歴史および文化を、合わせて学びます。', en: "We'll study history and culture together.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '二つは、関係があるんですか?', en: "Are the two related?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'そこで、両者のつながりを考えます。', en: "So, we'll consider the link between them.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '基礎知識なしで、不安だったので安心です。', en: "I was anxious without basic knowledge, so I'm relieved.", style: 'relieved adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'さて、それでは始めましょう。', en: "Now then, let's begin.", style: 'warm teacher voice, soft warm encouraging clarity throughout' },
    ]),

  C('conv_02493',
    'Hiroshi-boss gives Yuki formal year-end remarks.',
    'WIDENED SCENARIO: business keigo; ceremonial vocabulary (申し上げ/につきまして/年度/施設/団体/保険) in natural home.',
    'office_quiet_low',
    ['申し上げ', 'につきまして', '年度', '施設', '保険'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '本年度の御協力に、御礼申し上げます。', en: "I thank you for your cooperation this fiscal year.", style: 'formal boss voice, soft warm composed dignified clarity throughout' },
      { speaker: 'yuki_office', jp: '新年度につきまして、計画はございますか?', en: "Do you have plans regarding the new fiscal year?", style: 'polite office woman voice, soft warm respectful clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '新しい施設を、設ける予定だ。', en: "We plan to establish a new facility.", style: 'measured boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '施設の保険につきましては、確認します。', en: "I'll check on the facility's insurance.", style: 'reliable office woman voice, soft warm professional clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '関係する団体にも、連絡を頼む。', en: "Please contact the related organizations too.", style: 'formal boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '保険の手続きも、年度内に進めます。', en: "I'll advance the insurance procedures within the year.", style: 'diligent office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '団体との連携につきまして、感謝申し上げる。', en: "I'm grateful regarding the ties with the organizations.", style: 'warm boss voice, soft warm dignified clarity throughout' },
      { speaker: 'yuki_office', jp: '来年度も、誠心誠意努めて参ります。', en: "I'll devote myself sincerely next year too.", style: 'earnest office woman voice, soft warm sincere closing throughout' },
    ]),

  C('conv_02494',
    'Ren reports operational steps to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; operations vocabulary (行う/実施/施設/作成/等) in natural home.',
    'office_quiet_low',
    ['行う', '実施', '施設', '作成', '等'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '点検は、来週に実施いたします。', en: "We'll carry out the inspection next week.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'どの施設から、行うのかね?', en: "Which facility do we start with?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '本社の施設から、順に行います。', en: "We'll proceed in order from the headquarters facility.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '報告書等は、誰が作成するのかね?', en: "Who creates the reports and such?", style: 'engaged boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '担当者が、書類等を作成します。', en: "The person in charge creates the documents and so on.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '実施の前に、確認を行ってくれ。', en: "Carry out a check before implementation.", style: 'firm boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '各施設で、事前確認を行います。', en: "We'll do prior checks at each facility.", style: 'confident young presenter voice, soft warm resolved throughout' },
      { speaker: 'hiroshi_boss', jp: '計画通り、実施してくれたまえ。', en: "Carry it out as planned.", style: 'satisfied boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02495',
    'Saito explains a treatment plan to a patient.',
    'WIDENED SCENARIO: medical explanation; clinical vocabulary (男性/精神/障害/行為/固定) in natural home.',
    'clinic_room_quiet',
    ['男性', '精神', '障害', '行為', '固定'],
    ['saito_doctor', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '肩が、上がらなくて困っています。', en: "My shoulder won't lift, and it's troubling.", style: 'troubled office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '運動の障害は、軽い段階です。', en: "The movement impairment is at a mild stage.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: '無理に動かす行為は、避けるべきですか?', en: "Should I avoid forcing it to move?", style: 'concerned office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: 'はい、しばらく軽く固定しましょう。', en: "Yes, let's keep it lightly fixed for a while.", style: 'clear doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: '同年代の男性にも、多い症状ですか?', en: "Is it common in men my age too?", style: 'curious office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '働く男性に、よく見られます。', en: "It's often seen in working men.", style: 'informative doctor voice, soft warm measured clarity throughout' },
      { speaker: 'kenji_office', jp: '精神的にも、少し参っていて。', en: "I'm a bit worn down mentally too.", style: 'vulnerable office man voice, soft warm quiet honesty throughout' },
      { speaker: 'saito_doctor', jp: '精神面の不安も、一緒に支えますよ。', en: "We'll support your mental anxiety together too.", style: 'gentle doctor voice, soft warm compassionate closing clarity throughout' },
    ]),

  C('conv_02496',
    'Media news: Sakura and Ren on a documentary release.',
    'WIDENED SCENARIO: media news; broadcast vocabulary (放送/公開/登場/イメージ/男性) in natural home.',
    'studio_room_tone',
    ['放送', '公開', '登場', 'イメージ', '男性'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '話題の番組が、来週放送されます。', en: "A much-talked-about program airs next week.", style: 'bright adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '一般公開は、いつからですか?', en: "When does the public release begin?", style: 'curious young commentator voice, soft warm engaged throughout' },
      { speaker: 'sakura_teen', jp: '放送と同時に、公開されます。', en: "It's released at the same time as the broadcast.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '新しい司会者も、登場するんですか?', en: "Will a new host appear too?", style: 'engaged young commentator voice, soft warm curious throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、若い男性が登場します。', en: "Yes, a young man will appear.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '番組のイメージも、変わりそうですね。', en: "The program's image seems likely to change.", style: 'analytical young commentator voice, soft warm throughout' },
      { speaker: 'sakura_teen', jp: '公開後の反応が、楽しみですね。', en: "I look forward to the response after release.", style: 'warm adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '放送を、ぜひ見てみたいです。', en: "I really want to watch the broadcast.", style: 'eager young commentator voice, soft warm closing throughout' },
    ]),

  C('conv_02497',
    'Mom and daughter, an everyday slip-up at home.',
    'Casual home register hitting common stragglers (しまい/彼女/無い/使わ/八) naturally.',
    'kitchen_evening_quiet',
    ['しまい', '彼女', '無い', '使わ', '八'],
    ['yumiko_mom', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'お母さん、牛乳を使い切ってしまい。', en: "Mom, I used up all the milk.", style: 'sheepish adult daughter voice, soft warm rueful honest throughout' },
      { speaker: 'yumiko_mom', jp: 'あら、もう無いの?', en: "Oh, there's none left?", style: 'gentle mother voice, soft warm mild surprise affectionate throughout' },
      { speaker: 'sakura_teen', jp: 'うん、全部使わせてもらっちゃった。', en: "Yeah, I used all of it.", style: 'apologetic adult daughter voice, soft warm honest throughout' },
      { speaker: 'yumiko_mom', jp: '八時までに、買ってきてくれる?', en: "Could you buy some by eight o'clock?", style: 'gentle mother voice, soft warm gently asking throughout' },
      { speaker: 'sakura_teen', jp: 'うん、友達の彼女も誘って行くね。', en: "Yeah, I'll invite my friend's girlfriend and go.", style: 'cheerful adult daughter voice, soft warm relaxed throughout' },
      { speaker: 'yumiko_mom', jp: 'その彼女に、よろしく伝えてね。', en: "Say hello to that girlfriend for me.", style: 'warm mother voice, soft warm affectionate throughout' },
      { speaker: 'sakura_teen', jp: '卵も無いから、ついでに買うね。', en: "There are no eggs either, so I'll grab some too.", style: 'helpful adult daughter voice, soft warm relaxed throughout' },
      { speaker: 'yumiko_mom', jp: '助かるわ。八時には戻ってね。', en: "That helps. Be back by eight.", style: 'grateful mother voice, soft warm caring closing throughout' },
    ]),

  C('conv_02498',
    'Daichi chats with a delivery driver about the route.',
    'WIDENED SCENARIO: logistics chat; transport vocabulary (トラック/バック/彼ら/無い) in natural home.',
    'street_quiet_distant',
    ['トラック', 'バック', '彼ら', '無い', '側'],
    ['daichi_kansai', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'お、そのトラック、よう停めたなあ。', en: "Oh, you parked that truck well.", style: 'lively Kansai man voice, warm hearty friendly delivery throughout' },
      { speaker: 'kenji_office', jp: 'ええ、後ろにバックするのが大変で。', en: "Yeah, backing it up is tough.", style: 'modest office man voice, soft warm relatable delivery throughout' },
      { speaker: 'daichi_kansai', jp: '右側に、もう少し寄せたらええよ。', en: "You can pull a bit more to the right.", style: 'lively Kansai man voice, warm helpful friendly delivery throughout' },
      { speaker: 'kenji_office', jp: 'ありがとう。今日は荷物が多くて。', en: "Thanks. There's a lot of cargo today.", style: 'grateful office man voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '他の運転手は、もう来てへんの?', en: "Haven't the other drivers come yet?", style: 'curious Kansai man voice, warm friendly delivery throughout' },
      { speaker: 'kenji_office', jp: '彼らは、別の側から回るそうです。', en: "They're going around from the other side.", style: 'informative office man voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ほな、停める場所も、もう無いなあ。', en: "Then there's no parking spot left, huh.", style: 'lively Kansai man voice, warm wry friendly delivery throughout' },
      { speaker: 'kenji_office', jp: '彼らが来る前に、バックで入れます。', en: "I'll back in before they arrive.", style: 'resolved office man voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02499',
    'Sakura interviews a logistics manager about delivery.',
    'WIDENED SCENARIO: business interview; logistics/industry vocabulary (トラック/産業/男性/ビジネス) in natural home.',
    'office_quiet_low',
    ['トラック', '産業', '男性', 'ビジネス', 'ポイント'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '運送業界は、今どんな状況ですか?', en: "What's the situation in the delivery industry now?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'トラックの数が、足りていません。', en: "There aren't enough trucks.", style: 'measured boss voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: 'この産業の課題は、何ですか?', en: "What's the challenge in this industry?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '働く男性も女性も、不足しています。', en: "Both working men and women are in short supply.", style: 'professional boss voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '改善のポイントは、どこでしょう?', en: "Where's the point for improvement?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '待遇の改善が、重要なポイントです。', en: "Improving conditions is a key point.", style: 'measured boss voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '新しいビジネスの形も、必要ですね。', en: "New forms of business are needed too.", style: 'thoughtful adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'ええ、産業全体で、変わるべき時です。', en: "Yes, it's time for the whole industry to change.", style: 'earnest boss voice, soft warm informative closing throughout' },
    ]),

  C('conv_02500',
    'Asuka leads a discussion comparing two essays.',
    'WIDENED SCENARIO: seminar discussion; analytical connectives (つつ/そこで/その他/なし/最も) in natural home.',
    'lecture_hall_quiet',
    ['つつ', 'そこで', 'その他', 'なし', '最も'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '二つの文章を、比べてみましょう。', en: "Let's compare the two essays.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '最初の文章は、根拠なしに見えます。', en: "The first essay seems to lack grounds.", style: 'analytical young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '根拠なしの主張は、弱くなります。', en: "A claim without grounds becomes weak.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '二つ目は、最も論理的ですね。', en: "The second is the most logical.", style: 'engaged young student voice, soft warm throughout' },
      { speaker: 'asuka_teacher', jp: '事実を示しつつ、感情にも訴えています。', en: "It shows facts while appealing to emotion.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'その他の点では、どうでしょうか?', en: "What about the other points?", style: 'curious young student voice, soft warm throughout' },
      { speaker: 'asuka_teacher', jp: 'そこで、構成の違いに注目しましょう。', en: "So, let's focus on the difference in structure.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '最も大切なのは、流れなんですね。', en: "What matters most is the flow.", style: 'understanding young student voice, soft warm realization throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_125 wrote', CONVERSATIONS.length, 'files');
