import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_099)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01966',
    context: 'Ren and Saito discuss AI in medicine briefly.',
    purpose: 'Mentor and protégé reflecting on technology.',
    ambient: 'cafe_evening_low',
    sound_effects: [],
    target_vocab: ['コンピューター', '技術', '医療', '変化'],
    cast: ['ren_uni', 'saito_doctor'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '先生、医療の技術、変化、速いですね。', en: "Doctor — medicine tech, fast change.", style: 'soft young man voice, warm thoughtful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ、コンピューター、すごく助かる。', en: "Yes — computer, helps lots.", style: 'measured doctor voice, soft warm agreeing delivery carefully' },
      { speaker: 'ren_uni', jp: 'でも、心、忘れない方がいい。', en: "But — heart, don't forget.", style: 'gentle young man voice, soft warm earnest delivery carefully' },
      { speaker: 'saito_doctor', jp: 'おっしゃる通り。', en: "As you say.", style: 'warm doctor voice, soft warm agreeing delivery carefully' },
      { speaker: 'ren_uni', jp: '技術、道具、ですね。', en: "Tech — tool.", style: 'soft young man voice, warm philosophical delivery carefully' },
      { speaker: 'saito_doctor', jp: 'うん、心が、本質。', en: "Yeah — heart essence.", style: 'tender doctor voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: '記事に、書きたい話。', en: "Article — want write.", style: 'engaged young man voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_01967',
    context: 'Sho-young watches a robot show with Daichi; curious questions.',
    purpose: 'Father patiently explaining technology to child.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['ロボット', '動く', '未来', '面白い'],
    cast: ['sho_child', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、ロボット、動いてる!', en: "Dad — robot, moving!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、すごい技術やな。', en: "Yeah — amazing tech.", style: 'warm Kansai father voice, soft impressed delivery carefully' },
      { speaker: 'sho_child', jp: '未来、こんな世界になるの?', en: "Future — world like this?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '人間と、共存やな。', en: "Human — coexist.", style: 'gentle Kansai father voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼくも、作りたい!', en: "I — want make!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_01968',
    context: 'Hina-young tries voice-assistant tech; teaches Yumiko how to use it.',
    purpose: 'Teen teaching grandmother new tech.',
    ambient: 'living_room_evening_warm',
    sound_effects: [],
    target_vocab: ['機械', '便利', '声', '教える'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、これ、声で動くの!', en: "Grandma — this, voice moves!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、便利ね、本当に。', en: "Oh — convenient, truly.", style: 'gentle older mother voice, soft warm amazed delivery carefully' },
      { speaker: 'hina_child', jp: '話しかけて、見て?', en: "Speak — try?", style: 'soft teen girl voice, warm warm helpful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'えーと、天気、教えて。', en: "Erm — weather, tell.", style: 'tender older mother voice, soft warm uncertain delivery carefully' },
      { speaker: 'hina_child', jp: 'すごいでしょ、おばあちゃん!', en: "Wow, right — grandma!", style: 'thrilled teen girl voice, bright warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01969',
    context: 'Kenji uses a new tablet to draw; Aoi watches and chats.',
    purpose: 'Couple adapting to creative tech together.',
    ambient: 'studio_quiet_low',
    sound_effects: [],
    target_vocab: ['機器', '描く', '画面', '便利'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: 'この機器、ええなぁ。', en: "This device — lovely.", style: 'soft Kansai artist voice, warm engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: '画面、すごく綺麗。', en: "Screen — super pretty.", style: 'soft adult woman voice, warm impressed delivery carefully' },
      { speaker: 'kenji_office', jp: '描くの、便利や。', en: "Drawing — convenient.", style: 'gentle Kansai man voice, soft warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: '紙より、楽?', en: "Paper than — easy?", style: 'curious adult woman voice, soft warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: '紙の良さも、ある。', en: "Paper's good too — exists.", style: 'soft Kansai man voice, warm philosophical delivery carefully' },
      { speaker: 'aoi_barista', jp: '両方、使い分けるの?', en: "Both — use separately?", style: 'gentle adult woman voice, soft warm interested delivery carefully' },
      { speaker: 'kenji_office', jp: 'うん、両方、ええ。', en: "Yeah — both, fine.", style: 'warm Kansai artist voice, soft content delivery carefully' },
    ],
  },
  {
    id: 'conv_01970',
    context: 'Sakura interviews a young inventor for an article; questions about creativity.',
    purpose: 'Writer profiling tech innovator deeply.',
    ambient: 'office_quiet_low',
    sound_effects: [],
    target_vocab: ['発明', '創造', '夢', '挑戦'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮さん、発明、どこから?', en: "Ren — invention, from where?", style: 'gentle adult writer voice, soft warm professional inquiry delivered carefully' },
      { speaker: 'ren_uni', jp: '日常の不便、感じてた。', en: "Daily inconvenience — felt.", style: 'soft young man voice, warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '創造、誰でもできる?', en: "Creation — anyone?", style: 'curious adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '見る目、養えば、できる。', en: "Eye — if cultivate, can.", style: 'thoughtful young man voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '夢、どんな?', en: "Dream — what?", style: 'soft adult writer voice, warm warm probing delivery carefully' },
      { speaker: 'ren_uni', jp: '誰かの、役に立ちたい。', en: "Someone — want help.", style: 'soft young man voice, warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: '挑戦、続けた理由?', en: "Challenge — kept reason?", style: 'engaged adult writer voice, soft warm interested delivery carefully' },
      { speaker: 'ren_uni', jp: '諦めない心、です。', en: "Don't-give-up heart — yes.", style: 'firm young man voice, soft warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '素敵な志、伝えます。', en: "Lovely will — convey.", style: 'tender adult writer voice, soft warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: '読者、励ましたい。', en: "Readers — encourage.", style: 'soft young man voice, warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '若い人に、響きそう。', en: "Young — resonates.", style: 'warm adult writer voice, soft warm hopeful delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble young man voice, soft warm grateful delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事、心、こめて書きます。', en: "Article — heart, put.", style: 'soft adult writer voice, warm warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_01971',
    context: 'Mei tries online shopping; quizzes Daichi about a delivery question.',
    purpose: 'Wife consulting husband on tech purchase.',
    ambient: 'kitchen_evening_low',
    sound_effects: [],
    target_vocab: ['ネット', '注文', '配達', '便利'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'ネット注文、便利ね。', en: "Net order — convenient.", style: 'soft young woman voice, warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、配達も早いやろ。', en: "Yeah — delivery fast.", style: 'warm Kansai husband voice, soft content delivery carefully' },
      { speaker: 'mei_romantic', jp: 'これ、必要なものよね?', en: "This — needed thing?", style: 'gentle young woman voice, soft warm confirming delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、買うてええで。', en: "Yeah — buy fine.", style: 'soft Kansai husband voice, warm warm agreeing delivery carefully' },
      { speaker: 'mei_romantic', jp: '楽しみ、明日来る!', en: "Looking forward — tomorrow comes!", style: 'bright young wife voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01972',
    context: 'Naoko complains about app updates; Hina-young helps her sort it out.',
    purpose: 'Teen patiently helping aunt with tech struggle.',
    ambient: 'ramen_shop_evening_low',
    sound_effects: [],
    target_vocab: ['アプリ', '更新', '難しい', '助かる'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、アプリ、また変わった!', en: "Hina — app, changed again!", style: 'frustrated Kansai aunt voice, bright loud honest delivery carefully' },
      { speaker: 'hina_child', jp: 'おばちゃん、見せて。', en: "Auntie — show.", style: 'soft teen girl voice, warm helpful patient delivery carefully' },
      { speaker: 'naoko_aunt', jp: '更新したら、わからんようなった。', en: "Updated — became unsure.", style: 'soft Kansai aunt voice, warm honest delivery carefully' },
      { speaker: 'hina_child', jp: 'こうやって、押すんだよ。', en: "Like this — press.", style: 'gentle teen girl voice, soft warm teaching delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おお、助かったわ、ひな!', en: "Oh — saved, Hina!", style: 'warm Kansai aunt voice, bright loud grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01973',
    context: 'Sho-young learns about space and stars with Hiroshi-elder; asks deep questions.',
    purpose: 'Grandfather sharing scientific wonder with grandchild.',
    ambient: 'porch_night_crickets',
    sound_effects: [],
    target_vocab: ['宇宙', '星', '広い', '不思議'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、宇宙、広いね。', en: "Grandpa — space, wide.", style: 'soft awed child boy voice, warm philosophical delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、不思議や、ほんま。', en: "Yeah — mysterious, truly.", style: 'slow elder Kansai voice, warm reverent delivery carefully' },
      { speaker: 'sho_child', jp: '星、いっぱい、ある!', en: "Stars — many, exist!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '人間、小さいなぁ。', en: "Humans — small.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '宇宙人、いるかな?', en: "Aliens — exist?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おるかもしれん、ロマンや。', en: "May be — romance.", style: 'warm elder Kansai voice, soft fond playful delivery carefully' },
      { speaker: 'sho_child', jp: 'いつか、行きたい!', en: "Someday — want go!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01974',
    context: 'Aoi attends a small business seminar online; quick chat with Yumiko afterward.',
    purpose: 'Adult woman discussing modern business learning.',
    ambient: 'home_office_quiet',
    sound_effects: [],
    target_vocab: ['オンライン', '学習', '便利', '時代'],
    cast: ['aoi_barista', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'お母さん、今日、オンライン勉強。', en: "Mom — today, online study.", style: 'soft adult woman voice, warm cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、便利な時代ね。', en: "Oh — convenient era.", style: 'warm older mother voice, soft warm amazed delivery carefully' },
      { speaker: 'aoi_barista', jp: '家にいながら、学べる。', en: "Home stay — can learn.", style: 'gentle adult woman voice, soft warm content delivery carefully' },
      { speaker: 'yumiko_mom', jp: '昔は、考えられなかった。', en: "Past — couldn't think.", style: 'tender older mother voice, soft warm reflective delivery carefully' },
      { speaker: 'aoi_barista', jp: '時代、本当に変わったね。', en: "Times — truly changed.", style: 'soft adult woman voice, warm philosophical delivery carefully' },
    ],
  },
  {
    id: 'conv_01975',
    context: 'Tatsuya-country reads an old farming journal; reflects on tradition vs new.',
    purpose: 'Elder farmer reflecting alone on profession\'s arc.',
    ambient: 'farmhouse_lamp_quiet',
    sound_effects: [],
    target_vocab: ['農業', '伝統', '近代', '工夫'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '昔の農業、今と全然違う。', en: "Old farming — now wholly differs.", style: 'soft Tohoku farmer voice, warm reflective delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'どう変わったの?', en: "How changed?", style: 'gentle teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: '機械、めっちゃ進んだ。', en: "Machine — much advanced.", style: 'gentle Tohoku voice, soft warm impressed delivery carefully' },
      { speaker: 'asuka_teacher', jp: '伝統も、守りたいでしょ?', en: "Tradition — want keep?", style: 'soft teacher voice, warm warm understanding delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、両立、工夫しとる。', en: "Yeah — balance, devising.", style: 'firm Tohoku voice, soft warm committed delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'あなたの姿勢、素敵。', en: "Your stance — lovely.", style: 'tender teacher voice, soft warm proud delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おまえおって、励みになる。', en: "With you — encouragement.", style: 'soft Tohoku farmer voice, warm tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01976',
    context: 'Kenji starts to publish manga online; Ren helps him set up.',
    purpose: 'Younger man helping mentor with technology.',
    ambient: 'studio_evening_lamp',
    sound_effects: [],
    target_vocab: ['投稿', '読者', '感想', '反応'],
    cast: ['kenji_office', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '蓮、ネット投稿、初めてや。', en: "Ren — net post, first.", style: 'soft Kansai artist voice, warm nervous honest delivery carefully' },
      { speaker: 'ren_uni', jp: '一緒に、設定しましょう。', en: "Together — setup.", style: 'gentle young man voice, soft warm helpful delivery carefully' },
      { speaker: 'kenji_office', jp: '読者の反応、気になるな。', en: "Reader reaction — bothers.", style: 'soft Kansai man voice, warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '感想、必ず来ますよ。', en: "Impressions — surely come.", style: 'warm young man voice, soft warm encouraging delivery carefully' },
      { speaker: 'kenji_office', jp: 'ドキドキするわ、ほんま。', en: "Heart pounds — truly.", style: 'gentle Kansai artist voice, soft warm vulnerable delivery carefully' },
      { speaker: 'ren_uni', jp: '健司さんの作品、絶対、響きます。', en: "Kenji's work — definitely resonates.", style: 'soft young man voice, warm warm confident delivery carefully' },
      { speaker: 'kenji_office', jp: 'おおきに、心強い。', en: "Thanks — encouraging.", style: 'tender Kansai man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01977',
    context: 'Sakura uses voice transcription for the first time; quick test.',
    purpose: 'Adult writer adopting new productivity tool.',
    ambient: 'study_room_lamp_quiet',
    sound_effects: [],
    target_vocab: ['声', '入力', '機械', '便利'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、声、入力、本当にできるの?', en: "Ren — voice input, really can?", style: 'curious adult writer voice, soft warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、話してみて。', en: "Yes — speak try.", style: 'soft young man voice, warm encouraging delivery carefully' },
      { speaker: 'sakura_teen', jp: 'すごい、ちゃんと、変換した!', en: "Wow — properly converted!", style: 'awed adult writer voice, bright warm cheerful delivery carefully' },
      { speaker: 'ren_uni', jp: '便利でしょ?', en: "Convenient, right?", style: 'gentle young man voice, soft warm playful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、書くの、楽になる。', en: "Yeah — writing, easier.", style: 'soft adult writer voice, warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_01978',
    context: 'Hiroshi-elder gets a smart watch from family; learns to use it.',
    purpose: 'Elder embracing modern tech with family help.',
    ambient: 'living_room_warm',
    sound_effects: [],
    target_vocab: ['時計', '健康', '記録', '便利'],
    cast: ['hiroshi_elder', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おじいちゃん、これ、スマートウォッチ。', en: "Grandpa — this, smart watch.", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'まあ、時計より、すごい!', en: "Oh — watch than, amazing!", style: 'awed elder Kansai voice, soft warm impressed delivery carefully' },
      { speaker: 'hina_child', jp: '健康、記録してくれるよ。', en: "Health — records.", style: 'soft teen girl voice, warm warm helpful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '便利な時代やな、ほんま。', en: "Convenient era — truly.", style: 'gentle elder Kansai voice, soft warm reflective delivery carefully' },
      { speaker: 'hina_child', jp: 'ずっと、元気でいてね!', en: "Always — be well!", style: 'soft tender teen girl voice, warm warm wishing delivery carefully' },
    ],
  },
  {
    id: 'conv_01979',
    context: 'Yuki-office presents a new project plan at work to Kenji.',
    purpose: 'Adult colleague pitching idea to boss.',
    ambient: 'office_meeting_low',
    sound_effects: [],
    target_vocab: ['計画', '企画', '提案', '実行'],
    cast: ['yuki_office', 'kenji_office'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: '健司さん、新しい計画、提案します。', en: "Kenji — new plan, propose.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: '聞かせてくれ。', en: "Let me hear.", style: 'measured Kansai man voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: '企画書、こちらです。', en: "Plan document — here.", style: 'soft office woman voice, warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええなぁ、内容ようできてる。', en: "Lovely — content well made.", style: 'warm Kansai man voice, soft warm approving delivery carefully' },
      { speaker: 'yuki_office', jp: '実行、いつから?', en: "Execution — from when?", style: 'engaged office woman voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: '来月から、ええで。', en: "Next month — fine.", style: 'soft Kansai man voice, warm warm decisive delivery carefully' },
      { speaker: 'yuki_office', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble office woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01980',
    context: 'Mei takes baby (use sho_child as small child) to first electronic toy demo.',
    purpose: 'Mother and child exploring new gadget play.',
    ambient: 'living_room_table_warm',
    sound_effects: [],
    target_vocab: ['玩具', '音', '光', '楽しい'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、玩具、光る!', en: "Mom — toy, shines!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'mei_romantic', jp: '音も、出るね。', en: "Sound — out too.", style: 'soft young mother voice, warm warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: '楽しい、もっと触りたい!', en: "Fun — touch more!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '気をつけて、ね。', en: "Be careful — yeah.", style: 'gentle young mother voice, soft warm cautious delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、優しく!', en: "Yeah — gently!", style: 'soft child boy voice, warm responsive delivery carefully' },
    ],
  },
  {
    id: 'conv_01981',
    context: 'Daichi attends a small online cooking class; tells Mei what he learned.',
    purpose: 'Husband sharing new domestic skill with wife.',
    ambient: 'kitchen_evening_warm',
    sound_effects: [],
    target_vocab: ['オンライン', '料理', '学ぶ', '楽しい'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、オンライン料理、ええで。', en: "Mei — online cooking, fine.", style: 'warm Kansai husband voice, soft cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、何を学んだの?', en: "Oh — learned what?", style: 'gentle young wife voice, soft warm curious delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'パン、作り方や。', en: "Bread — making.", style: 'soft Kansai husband voice, warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: '今度、作ってよ!', en: "Next — make!", style: 'tender young wife voice, soft warm encouraging delivery carefully' },
      { speaker: 'daichi_kansai', jp: '楽しみに、しとき!', en: "Look forward — wait!", style: 'animated Kansai husband voice, bright loud playful delivery carefully' },
    ],
  },
  {
    id: 'conv_01982',
    context: 'Hina-young writes a small blog post; shows it to Sakura for feedback.',
    purpose: 'Teen sharing online writing with mentor.',
    ambient: 'study_room_lamp_low',
    sound_effects: [],
    target_vocab: ['ブログ', '文章', '感想', '発信'],
    cast: ['hina_child', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、ブログ、書いてみた。', en: "Sakura — blog, wrote.", style: 'soft teen girl voice, warm cheerful proud delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、見せて!', en: "Oh — show!", style: 'tender adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: '感想、教えてください。', en: "Impressions — tell.", style: 'soft teen girl voice, warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: '文章、すごく素直で素敵。', en: "Prose — honest, lovely.", style: 'gentle adult writer voice, soft warm warm praising delivery carefully' },
      { speaker: 'hina_child', jp: '発信、続けたい。', en: "Posting — keep.", style: 'soft determined teen girl voice, warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '読者、増えていくよ。', en: "Readers — increase.", style: 'warm adult writer voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '本当?嬉しい、ありがとう!', en: "Truly? Happy — thanks!", style: 'thrilled teen girl voice, bright warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01983',
    context: 'Naoko videocalls with a far-away cousin; first time using video.',
    purpose: 'Aunt nervously trying new tech.',
    ambient: 'ramen_shop_after_close',
    sound_effects: [],
    target_vocab: ['電話', '映像', '懐かしい', '元気'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、映像、見えるか?', en: "Hina — video, visible?", style: 'nervous Kansai aunt voice, soft warm uncertain delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、ちゃんと見えてる!', en: "Yeah — properly visible!", style: 'bright teen girl voice, soft warm helpful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、いとこ、元気そうや!', en: "Yeah — cousin, well-looking!", style: 'warm Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'hina_child', jp: '懐かしいでしょ。', en: "Nostalgic, right.", style: 'gentle teen girl voice, soft warm fond delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ほんま、嬉しいわ!', en: "Truly — happy!", style: 'tender Kansai aunt voice, soft warm tearful delivery carefully' },
    ],
  },
  {
    id: 'conv_01984',
    context: 'Saito reads a science article with Asuka in bed; quiet morning.',
    purpose: 'Married couple sharing curious news together.',
    ambient: 'bedroom_morning_quiet',
    sound_effects: [],
    target_vocab: ['記事', '科学', '発見', '驚く'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'あすか、面白い記事、見つけた。', en: "Asuka — interesting article, found.", style: 'soft doctor voice, warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'どんな話?', en: "What story?", style: 'gentle teacher voice, soft warm curious delivery carefully' },
      { speaker: 'saito_doctor', jp: '新しい発見、本当に驚く。', en: "New finding — truly amazes.", style: 'warm doctor voice, soft impressed delivery carefully' },
      { speaker: 'asuka_teacher', jp: '科学、すごいわね。', en: "Science — amazing.", style: 'tender teacher voice, soft warm fond delivery carefully' },
      { speaker: 'saito_doctor', jp: 'うん、まだまだ、わからん世界。', en: "Yeah — still unknown world.", style: 'soft doctor voice, warm philosophical delivery carefully' },
    ],
  },
  {
    id: 'conv_01985',
    context: 'Ren and Sakura submit a final manuscript online together; quiet emotional moment.',
    purpose: 'Collaborators completing major creative milestone.',
    ambient: 'study_room_late_lamp',
    sound_effects: [],
    target_vocab: ['原稿', '送信', '完成', '達成'],
    cast: ['ren_uni', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、原稿、ついに完成。', en: "Ren — manuscript, finally done.", style: 'tearful adult writer voice, soft warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、長い道のりでした。', en: "Yes — long road.", style: 'soft young man voice, warm warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '一緒に、送信しよう。', en: "Together — send.", style: 'tender adult writer voice, soft warm united delivery carefully' },
      { speaker: 'ren_uni', jp: '達成感、すごいですね。', en: "Achievement — amazing.", style: 'soft young man voice, warm warm awed delivery carefully' },
      { speaker: 'sakura_teen', jp: '蓮くん、本当にありがとう。', en: "Ren — truly thanks.", style: 'tender adult writer voice, soft warm grateful delivery carefully' },
      { speaker: 'ren_uni', jp: 'こちらこそ、勉強になりました。', en: "Likewise — learned.", style: 'humble young man voice, soft warm respectful delivery carefully' },
      { speaker: 'sakura_teen', jp: '送信、します!', en: "Send — do!", style: 'animated adult writer voice, bright warm cheerful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_099 wrote', CONVERSATIONS.length, 'files');
