import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_082)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01626',
    context: 'Mei and Yumiko plan the week\'s menu over morning tea.',
    purpose: 'Two women planning meals; gentle household coordination.',
    ambient: 'kitchen_morning_kettle',
    sound_effects: [],
    target_vocab: ['献立', '食材', '野菜', '魚'],
    cast: ['mei_romantic', 'yumiko_mom'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '今週の献立、考えませんか。', en: "Shall we plan this week's menu?", style: 'soft young mother voice, warm gentle inviting delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ええ、お野菜たくさん使いたい。', en: "Yes — want lots of vegetables.", style: 'gentle older mother voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '今、旬の食材は何ですか?', en: "What's in season now?", style: 'curious young woman voice, soft warm inquiring delivery carefully' },
      { speaker: 'yumiko_mom', jp: '大根とほうれん草よ。', en: "Daikon and spinach.", style: 'warm older mother voice, soft informative delivery carefully' },
      { speaker: 'mei_romantic', jp: '魚も、入れたいですね。', en: "Want to add fish too.", style: 'soft young woman voice, warm planning gentle delivery carefully' },
      { speaker: 'yumiko_mom', jp: '鯖、いいんじゃない?', en: "Mackerel — sounds good.", style: 'gentle older mother voice, soft warm suggesting delivery carefully' },
      { speaker: 'mei_romantic', jp: '決まりですね、ありがとうございます。', en: "Decided — thank you.", style: 'tender young woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01627',
    context: 'Daichi takes Sho-young out to a sushi shop for the first time.',
    purpose: 'Father introducing son to a special food experience.',
    ambient: 'sushi_counter_clink',
    sound_effects: [],
    target_vocab: ['寿司', '注文', '魚', '美味しい'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、寿司、初めてや!', en: "Dad — first time at sushi!", style: 'excited child boy voice, bright cheerful warm delivery carefully' },
      { speaker: 'daichi_kansai', jp: '何、注文する?', en: "What'll you order?", style: 'warm Kansai father voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: 'マグロ食べたい!', en: "Want tuna!", style: 'eager child boy voice, bright warm decisive delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええで、新鮮な魚やで。', en: "Sure — fresh fish.", style: 'soft Kansai father voice, warm content delivery carefully' },
      { speaker: 'sho_child', jp: 'うわっ、めっちゃ美味しい!', en: "Whoa — so good!", style: 'thrilled child boy voice, bright warm delighted delivery carefully' },
    ],
  },
  {
    id: 'conv_01628',
    context: 'Naoko gives a friendly cooking lesson at a noodle workshop.',
    purpose: 'Aunt teaching a small group how to make noodles by hand.',
    ambient: 'kitchen_workshop_flour',
    sound_effects: [],
    target_vocab: ['麺', '粉', 'こねる', '茹でる'],
    cast: ['naoko_aunt', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '麺は、ようこねるんやで!', en: "Noodles — knead well!", style: 'brassy Kansai aunt voice, bright loud teaching delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、おばさん、こうですか?', en: "Yes — auntie, like this?", style: 'gentle adult woman voice, soft warm attentive delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ええ感じや、力入れて!', en: "Good — put some muscle!", style: 'animated Kansai aunt voice, bright loud encouraging delivery carefully' },
      { speaker: 'aoi_barista', jp: '粉、ふんわりしてきた。', en: "The flour's getting airy.", style: 'soft adult woman voice, warm observant delivery carefully' },
      { speaker: 'naoko_aunt', jp: '茹でるの、お湯たっぷりや。', en: "When boiling — plenty of water.", style: 'warm Kansai aunt voice, soft firm teaching delivery carefully' },
      { speaker: 'aoi_barista', jp: 'なるほど、覚えました。', en: "I see — got it.", style: 'soft adult woman voice, warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、ええ生徒や!', en: "Heh — fine student!", style: 'brassy Kansai aunt voice, bright proud fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01629',
    context: 'Saito and Ren chat at a small izakaya about life choices.',
    purpose: 'Older mentor and younger man sharing drinks and philosophy.',
    ambient: 'izakaya_warm_low',
    sound_effects: [],
    target_vocab: ['居酒屋', 'お酒', '人生', '選ぶ'],
    cast: ['saito_doctor', 'ren_uni'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '居酒屋、落ち着きますね。', en: "Izakaya — calming.", style: 'soft young man voice, warm content delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ、こういう時間、大切。', en: "Yes — times like this matter.", style: 'measured doctor voice, soft warm reflective delivery carefully' },
      { speaker: 'ren_uni', jp: 'お酒、ゆっくり飲みたい。', en: "Want to drink slowly.", style: 'gentle young man voice, soft warm peaceful delivery carefully' },
      { speaker: 'saito_doctor', jp: '人生も、急がなくていい。', en: "Life — no need to rush either.", style: 'gentle doctor voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '今、選ぶこと多くて。', en: "So many choices now.", style: 'soft young man voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '一つ一つ、丁寧にね。', en: "Each one — carefully.", style: 'warm doctor voice, soft wise delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、勉強になります。', en: "Thank you — I'm learning.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01630',
    context: 'Hina-young helps Sakura prepare a small home dinner party.',
    purpose: 'Teen learning entertainment cooking from adult mentor.',
    ambient: 'kitchen_warm_chopping',
    sound_effects: [],
    target_vocab: ['夕食', '皿', '盛る', '配る'],
    cast: ['hina_child', 'sakura_teen'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、皿、ここでいい?', en: "Sakura — plates here?", style: 'soft teen girl voice, warm attentive helpful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、綺麗に並べてね。', en: "Yes — arrange them nicely.", style: 'gentle adult writer voice, soft warm instructional delivery carefully' },
      { speaker: 'hina_child', jp: '盛り付け、難しいなぁ。', en: "Plating — tricky.", style: 'soft teen girl voice, warm honest concentrating delivery carefully' },
      { speaker: 'sakura_teen', jp: '色とバランス、見ながらね。', en: "Watch color and balance.", style: 'warm adult writer voice, soft patient teaching delivery carefully' },
      { speaker: 'hina_child', jp: '配るの、私やる。', en: "I'll serve them.", style: 'eager teen girl voice, soft warm helpful delivery carefully' },
    ],
  },
  {
    id: 'conv_01631',
    context: 'Tatsuya-country and Hiroshi-elder enjoy slow conversation over miso soup at breakfast.',
    purpose: 'Two old men sharing simple morning meal.',
    ambient: 'kitchen_morning_steam',
    sound_effects: [],
    target_vocab: ['味噌', '汁', '朝食', '故郷'],
    cast: ['tatsuya_country', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: 'この味噌汁、懐かしい味やな。', en: "This miso soup — nostalgic.", style: 'slow Tohoku voice, soft warm reminiscent delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、故郷の味やろ?', en: "Yeah — flavor of home, right?", style: 'gentle elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ほんま、心に染みる。', en: "Truly — soaks into the heart.", style: 'soft Tohoku farmer voice, warm tender delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '朝食はやっぱり、ご飯と味噌や。', en: "Breakfast — rice and miso, always.", style: 'soft elder Kansai voice, warm content delivery carefully' },
      { speaker: 'tatsuya_country', jp: '日本人の朝、これやな。', en: "A Japanese morning — this.", style: 'gentle Tohoku voice, soft warm philosophical delivery carefully' },
    ],
  },
  {
    id: 'conv_01632',
    context: 'Riku-teen and Sho-young go to a curry shop after a basketball match.',
    purpose: 'Two teens hungry and happy after sport.',
    ambient: 'curry_shop_busy',
    sound_effects: [],
    target_vocab: ['カレー', '辛い', '甘い', '盛り'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'riku_teen', jp: 'カレー、大盛りいっとこ!', en: "Curry — large size!", style: 'animated teen boy voice, bright cheerful loud delivery carefully' },
      { speaker: 'sho_child', jp: '俺も、大盛り!', en: "Me too — large!", style: 'energetic teen boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'riku_teen', jp: '辛いの、いける?', en: "Spicy — can handle?", style: 'casual teen boy voice, soft warm playful delivery carefully' },
      { speaker: 'sho_child', jp: '甘口でお願いします!', en: "Mild, please!", style: 'soft teen boy voice, warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: 'ふふ、お子様やな。', en: "Heh — what a kid.", style: 'teasing teen boy voice, bright warm playful delivery carefully' },
    ],
  },
  {
    id: 'conv_01633',
    context: 'Kenji and Aoi enjoy a quiet anniversary dinner at a small restaurant.',
    purpose: 'Couple sharing celebratory dinner; reflective tenderness.',
    ambient: 'restaurant_low_candle',
    sound_effects: [],
    target_vocab: ['記念', '夕食', '幸せ', '一緒'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '今日、結婚記念日やな。', en: "Today — our anniversary.", style: 'soft Kansai husband voice, warm tender delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、信じられないね、もう。', en: "Yes — hard to believe, already.", style: 'tender adult woman voice, soft warm fond delivery carefully' },
      { speaker: 'kenji_office', jp: '一緒に、いられて幸せ。', en: "Happy being with you.", style: 'soft Kansai man voice, warm sincere delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、私もよ。', en: "Heh — same.", style: 'gentle adult woman voice, soft warm teasing delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前との時間、宝物や。', en: "Time with you — treasure.", style: 'tender Kansai man voice, soft warm loving delivery carefully' },
      { speaker: 'aoi_barista', jp: 'これからも、ね。', en: "Going forward too — yeah?", style: 'soft adult woman voice, warm tender hopeful delivery carefully' },
      { speaker: 'kenji_office', jp: 'もちろん、ずっと。', en: "Of course — always.", style: 'soft Kansai husband voice, warm firm loving delivery carefully' },
    ],
  },
  {
    id: 'conv_01634',
    context: 'Mrs. Mori and Sachiko-grandma share pickling tips at a community kitchen.',
    purpose: 'Two older women sharing traditional preservation craft.',
    ambient: 'community_kitchen_low',
    sound_effects: [],
    target_vocab: ['漬物', '塩', '保存', '伝統'],
    cast: ['mrs_mori_neighbor', 'sachiko_grandma'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: '漬物、塩加減が肝心ね。', en: "Pickles — salt balance is key.", style: 'warm older neighbor voice, soft wise delivery carefully' },
      { speaker: 'sachiko_grandma', jp: 'うん、長く保存できるわ。', en: "Yes — keeps long.", style: 'gentle grandmother voice, soft warm agreement delivered carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '伝統の知恵、伝えていきたい。', en: "Want to pass on tradition.", style: 'soft older woman voice, warm reflective delivery carefully' },
      { speaker: 'sachiko_grandma', jp: 'ええ考えね、若い人に。', en: "Good idea — to young ones.", style: 'warm grandmother voice, soft fond delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'また、教室開きましょう。', en: "Let's open a class again.", style: 'gentle older neighbor voice, soft warm planning delivery carefully' },
    ],
  },
  {
    id: 'conv_01635',
    context: 'Yumiko shops at the market with Mei; bargaining and chatting.',
    purpose: 'Elder and younger woman traditional market trip together.',
    ambient: 'market_outdoor_chatter',
    sound_effects: [],
    target_vocab: ['市場', '新鮮', '値段', '選ぶ'],
    cast: ['yumiko_mom', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'この市場、品物がいいわ。', en: "This market — goods are fine.", style: 'gentle older mother voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '本当に、新鮮ですね。', en: "Truly fresh.", style: 'soft young woman voice, warm observant delivery carefully' },
      { speaker: 'yumiko_mom', jp: '値段も、お得よ。', en: "Prices — good value too.", style: 'warm older mother voice, soft practical delivery carefully' },
      { speaker: 'mei_romantic', jp: '今晩は、これにしましょう。', en: "Tonight — let's do this.", style: 'gentle young woman voice, soft warm decisive delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、選ぶの楽しいわね。', en: "Yes — fun choosing.", style: 'warm older mother voice, soft fond delivery carefully' },
      { speaker: 'mei_romantic', jp: '一緒だと、本当に楽しい。', en: "With you — truly fun.", style: 'tender young woman voice, soft warm grateful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、また来ましょうね。', en: "Heh — let's come again.", style: 'soft older mother voice, warm friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_01636',
    context: 'Sho-young is sad at a missed school trip; Daichi comforts him with udon.',
    purpose: 'Father consoling disappointed child through gentle ritual.',
    ambient: 'udon_shop_warm',
    sound_effects: [],
    target_vocab: ['うどん', '元気', '残念', '次回'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、行きたかった。', en: "Dad — I wanted to go.", style: 'soft sad child boy voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '残念やったな、来年あるで。', en: "Tough — next year there's another.", style: 'warm Kansai father voice, soft tender consoling delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、でも悲しい。', en: "Yeah — but sad.", style: 'soft child boy voice, warm honest tearful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うどん食べて、元気出そう。', en: "Eat udon — feel better.", style: 'soft Kansai father voice, warm tender comforting delivery carefully' },
      { speaker: 'sho_child', jp: '熱くて、美味しい。', en: "Hot — delicious.", style: 'soft warmed child boy voice, warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_01637',
    context: 'Asuka and Tatsuya-country host their daughter\'s family for a long dinner.',
    purpose: 'Multi-generational warm rural family meal.',
    ambient: 'tatami_dinner_warm',
    sound_effects: [],
    target_vocab: ['食事', '家族', '故郷', '帰省'],
    cast: ['asuka_teacher', 'tatsuya_country'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '帰省、ありがとう。', en: "Thanks for coming home.", style: 'warm teacher voice, soft tender grateful delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ようきたな、ようきた。', en: "You came, you came.", style: 'soft Tohoku farmer voice, warm tender fatherly delivery carefully' },
      { speaker: 'asuka_teacher', jp: '今日は、たくさん作ったの。', en: "Made lots today.", style: 'gentle teacher voice, soft warm proud delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お母さんの味、最高や。', en: "Mom's flavor — the best.", style: 'fond Tohoku voice, soft warm appreciative delivery carefully' },
      { speaker: 'asuka_teacher', jp: '懐かしいでしょう?', en: "Nostalgic, isn't it?", style: 'warm teacher voice, soft fond inquiring delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'この味、街では出せん。', en: "This flavor — city can't make.", style: 'gentle Tohoku voice, soft warm proud delivery carefully' },
      { speaker: 'asuka_teacher', jp: '故郷、忘れないでね。', en: "Don't forget your home.", style: 'tender teacher voice, soft warm earnest delivery carefully' },
      { speaker: 'tatsuya_country', jp: '心は、いつもここや。', en: "Heart — always here.", style: 'soft Tohoku farmer voice, warm tender delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'また、いつでも帰ってきて。', en: "Come home anytime.", style: 'gentle teacher voice, soft warm loving delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'うん、約束やな。', en: "Yes — promise.", style: 'soft Tohoku voice, warm firm tender delivery carefully' },
      { speaker: 'asuka_teacher', jp: '一緒の食事、嬉しいわ。', en: "Meals together — happy.", style: 'tender teacher voice, soft warm grateful delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お父さんも、嬉しいで。', en: "Dad's happy too.", style: 'gentle Tohoku farmer voice, soft warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: '次の帰省も、待ってるね。', en: "Next return too — we'll wait.", style: 'warm teacher voice, soft tender waiting delivery carefully' },
    ],
  },
  {
    id: 'conv_01638',
    context: 'Sakura interviews a young pastry chef for an article over coffee.',
    purpose: 'Writer interviewing young culinary craftsman warmly.',
    ambient: 'cafe_pastry_low',
    sound_effects: [],
    target_vocab: ['パン', '焼く', 'こだわり', '工夫'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'パン作り、何年されてますか?', en: "Bread-making — how many years?", style: 'gentle adult writer voice, soft warm interviewer delivery carefully' },
      { speaker: 'ren_uni', jp: '七年です、まだ修行中で。', en: "Seven — still apprentice.", style: 'humble young man voice, soft warm modest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こだわり、ありますか?', en: "Any particularities?", style: 'curious adult writer voice, soft warm inquiring delivery carefully' },
      { speaker: 'ren_uni', jp: '酵母、自家製にしています。', en: "Yeast — homemade.", style: 'soft young man voice, warm proud delivery carefully' },
      { speaker: 'sakura_teen', jp: 'すごい工夫ですね。', en: "Impressive effort.", style: 'warm adult writer voice, soft admiring delivery carefully' },
      { speaker: 'ren_uni', jp: '時間かかるけど、味が違う。', en: "Takes time — flavor's different.", style: 'soft young man voice, warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '読者、喜びそうです。', en: "Readers will be pleased.", style: 'soft adult writer voice, warm professional delivery carefully' },
    ],
  },
  {
    id: 'conv_01639',
    context: 'Hina-young and Mei plan a small surprise tea party for Yumiko\'s birthday.',
    purpose: 'Two younger women planning a kind surprise.',
    ambient: 'kitchen_planning_low',
    sound_effects: [],
    target_vocab: ['誕生', '茶', 'お菓子', '驚き'],
    cast: ['hina_child', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、おばあちゃんの誕生!', en: "Mei — Grandma's birthday!", style: 'eager teen girl voice, bright cheerful warm delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お茶会、開きましょうか?', en: "Tea party — shall we hold?", style: 'soft young woman voice, warm planning delivery carefully' },
      { speaker: 'hina_child', jp: 'お菓子、私が作るね。', en: "Sweets — I'll make.", style: 'eager teen girl voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: '驚き、最高にしようね。', en: "Surprise — make it the best.", style: 'gentle young woman voice, soft warm conspiratorial delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、楽しみ!', en: "Yeah — excited!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01640',
    context: 'Goro-grandpa and Hiroshi-elder catch up at a small soba shop.',
    purpose: 'Two elder men sharing simple comfort food.',
    ambient: 'soba_shop_low',
    sound_effects: [],
    target_vocab: ['蕎麦', '汁', '美味しい', '久しぶり'],
    cast: ['goro_grandpa', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'goro_grandpa', jp: '久しぶりに、蕎麦やな。', en: "Soba — long time.", style: 'gentle elder voice, soft warm fond delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ここの汁、ほんま美味しい。', en: "This broth — truly good.", style: 'slow elder Kansai voice, warm appreciative delivery carefully' },
      { speaker: 'goro_grandpa', jp: '年取っても、この味は変わらん。', en: "Even old, this taste's the same.", style: 'soft elder voice, warm philosophical delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ありがたいわ。', en: "Yeah — grateful.", style: 'gentle elder Kansai voice, soft warm humble delivery carefully' },
      { speaker: 'goro_grandpa', jp: 'また、来ような。', en: "Let's come again.", style: 'warm elder voice, soft fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01641',
    context: 'Sakura and Aoi go out for a tofu dinner; deep autumn-evening talk.',
    purpose: 'Two adult women sharing soothing food and reflective talk.',
    ambient: 'tofu_restaurant_low',
    sound_effects: [],
    target_vocab: ['豆腐', '優しい', '体', '心'],
    cast: ['sakura_teen', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'お豆腐、体に優しいね。', en: "Tofu — kind to the body.", style: 'soft adult writer voice, warm appreciative delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、心も和むわ。', en: "Yes — calms the heart too.", style: 'gentle adult woman voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こういう時間、必要ね。', en: "Times like this — needed.", style: 'soft adult writer voice, warm reflective delivery carefully' },
      { speaker: 'aoi_barista', jp: '蒼さんも、忙しい?', en: "Aoi — busy too?", style: 'warm adult woman voice, soft caring delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、でも、こうやって会えると嬉しい。', en: "Yeah — but glad we meet like this.", style: 'tender adult writer voice, soft warm grateful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'また、ご飯しようね。', en: "Let's eat together again.", style: 'soft adult woman voice, warm friendly delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、是非。', en: "Yes — by all means.", style: 'gentle adult writer voice, soft warm affirming delivery carefully' },
    ],
  },
  {
    id: 'conv_01642',
    context: 'Ryosuke-dad takes Mei out for a daddy-daughter lunch nostalgically.',
    purpose: 'Father and grown daughter sharing tender retro outing.',
    ambient: 'restaurant_quiet_window',
    sound_effects: [],
    target_vocab: ['昔', '思い出', '父', '娘'],
    cast: ['ryosuke_dad', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ryosuke_dad', jp: '昔、ここよく来たな。', en: "Used to come here often.", style: 'warm middle-aged father voice, soft fond nostalgic delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お父さん、覚えてる。', en: "Dad — I remember.", style: 'tender young woman voice, soft warm fond delivery carefully' },
      { speaker: 'ryosuke_dad', jp: '小学生やった、お前。', en: "You were in elementary school.", style: 'gentle father voice, soft warm reminiscent delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ふふ、大きくなったね。', en: "Heh — grown up.", style: 'soft young woman voice, warm fond delivery carefully' },
      { speaker: 'ryosuke_dad', jp: 'いつまでも、可愛い娘や。', en: "Always — sweet daughter.", style: 'tender father voice, soft warm loving delivery carefully' },
      { speaker: 'mei_romantic', jp: '本当に、嬉しい言葉。', en: "Truly — happy words.", style: 'tender young woman voice, soft warm grateful delivery carefully' },
      { speaker: 'ryosuke_dad', jp: 'また、来ような。', en: "Let's come again.", style: 'warm father voice, soft fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01643',
    context: 'Kenji takes Sho-young to a small ramen-making class together.',
    purpose: 'Uncle figure and child sharing fun culinary outing.',
    ambient: 'workshop_kitchen_low',
    sound_effects: [],
    target_vocab: ['ラーメン', '麺', 'スープ', '一緒'],
    cast: ['kenji_office', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '健司おじちゃん、楽しい!', en: "Kenji-ojichan — fun!", style: 'eager child boy voice, bright cheerful warm delivery carefully' },
      { speaker: 'kenji_office', jp: '麺、自分で作ったやろ?', en: "Made the noodles yourself, right?", style: 'warm Kansai mentor voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、ぼくが作ったの!', en: "Yeah — I made them!", style: 'thrilled child boy voice, bright warm proud delivery carefully' },
      { speaker: 'kenji_office', jp: 'スープも、ええ味やで。', en: "Soup — fine flavor.", style: 'soft Kansai man voice, warm praising delivery carefully' },
      { speaker: 'sho_child', jp: '一緒だと、もっと美味しい!', en: "Together — even tastier!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01644',
    context: 'Naoko hosts a small ramen-shop birthday for a regular customer.',
    purpose: 'Aunt warmly celebrating a community regular with multiple voices.',
    ambient: 'ramen_shop_party_warm',
    sound_effects: [],
    target_vocab: ['誕生', 'お祝い', '常連', '心'],
    cast: ['naoko_aunt', 'hiroshi_elder', 'goro_grandpa', 'mrs_mori_neighbor'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'みんな、ようきた!', en: "Everyone — welcome!", style: 'brassy Kansai aunt voice, bright loud warm delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おめでとう、今日は祝いや。', en: "Congrats — today's celebration.", style: 'slow elder Kansai voice, warm fond delivery carefully' },
      { speaker: 'goro_grandpa', jp: '常連の誕生、嬉しいなぁ。', en: "Regular's birthday — happy.", style: 'gentle elder voice, soft warm delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'お祝いの席、ありがたいわ。', en: "Celebration seat — grateful.", style: 'warm older neighbor voice, soft appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '特別ラーメン、作ったで!', en: "Special ramen — made!", style: 'animated Kansai aunt voice, bright loud proud delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'いつもの味、ええなぁ。', en: "Usual flavor — lovely.", style: 'soft elder Kansai voice, warm fond delivery carefully' },
      { speaker: 'goro_grandpa', jp: '心こもってるわ、ナオコの料理。', en: "Heart in it — Naoko's cooking.", style: 'gentle elder voice, soft warm appreciative delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'こういう集まり、長く続けたい。', en: "Want this gathering to last.", style: 'soft older woman voice, warm hopeful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '当たり前や、続けたるで!', en: "Of course — I'll keep it going!", style: 'brassy Kansai aunt voice, bright loud committed delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'みんなおると、嬉しいなぁ。', en: "With everyone — happy.", style: 'warm elder Kansai voice, soft tender content delivery carefully' },
      { speaker: 'goro_grandpa', jp: '長生きの秘訣、ここにあるわ。', en: "Longevity secret — here.", style: 'gentle elder voice, soft warm philosophical delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふふ、ありがたいことね。', en: "Heh — blessing.", style: 'soft older neighbor voice, warm humble delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ほな、もう一杯やろか!', en: "Right — another round!", style: 'animated Kansai aunt voice, bright loud cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01645',
    context: 'Sakura ends an exhausting workday at a quiet bar with Yuki-office.',
    purpose: 'Two adult women decompressing over wine.',
    ambient: 'bar_evening_quiet',
    sound_effects: [],
    target_vocab: ['一杯', 'お酒', '今日', '疲れ'],
    cast: ['sakura_teen', 'yuki_office'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '今日、本当に疲れた。', en: "Today — really tired.", style: 'soft adult writer voice, warm honest weary delivery carefully' },
      { speaker: 'yuki_office', jp: 'うん、一杯飲もう。', en: "Yeah — let's drink.", style: 'warm office woman voice, soft tender suggesting delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お酒、染みるわ。', en: "Sake — soaks in.", style: 'gentle adult writer voice, soft warm content delivery carefully' },
      { speaker: 'yuki_office', jp: 'たまには、こんな夜も。', en: "Sometimes — nights like this.", style: 'soft office woman voice, warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとう、来てくれて。', en: "Thanks for coming.", style: 'tender adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_082 wrote', CONVERSATIONS.length, 'files');
