// scripts/batches/batch_005.mjs — conv_00084..00103
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
fs.mkdirSync(OUT_DIR, { recursive: true });
const NOW = new Date().toISOString();
const META = (row) => ({ generated_by: 'claude-opus-4-7 (batch_005)', generated_at: NOW, source_plan_row: row || '' });

const CONVERSATIONS = [
  {
    id: 'conv_00084',
    context: 'Late evening at a small Tokyo intersection. An elderly visitor sits on a bench looking confused. Officer Takeda steps over from his bicycle.',
    purpose: 'tiny help across regions — careful officer, slightly tipsy elder, Tokyo at night',
    ambient: 'city_street_night',
    target_vocab: ['本当に','大丈夫','時間','家','どこ','すみません'],
    cast: ['takeda_officer','tatsuya_country'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'takeda_officer', jp: 'こんばんは。大丈夫ですか？', en: 'Good evening. Are you alright?', style: 'Low, calm, professional. Crouches a half-step at the bench.', mood: 'professional_low' },
      { speaker: 'tatsuya_country', jp: 'ああ…ちょっと、迷ってしもうて。', en: 'Ahh… got a bit lost.', style: 'Slow Tohoku honesty with a small slurred edge.', mood: 'tohoku_honest' },
      { speaker: 'takeda_officer', jp: 'お家、どちらですか？', en: 'Where\'s home for you?', style: 'Plain question, no judgment in the voice.', mood: 'plain_polite' },
      { speaker: 'tatsuya_country', jp: '岩手や。今、息子の家、来とるんやけど。', en: 'Iwate. But — visiting my son\'s place now.', style: 'A small admission. The visiting-elder honesty.', mood: 'visiting_honest' },
      { speaker: 'takeda_officer', jp: 'なるほど。一緒に、お時間少しいただければ。', en: 'I see. If I can have a moment of your time, together.', style: 'A small kind formality. Already pulling out his phone.', mood: 'kind_formal' },
      { speaker: 'tatsuya_country', jp: '本当に、すみません。', en: 'Truly — I\'m sorry.', style: 'A small genuine apology. Voice slightly lower.', mood: 'genuine_apology' },
    ],
  },
  {
    id: 'conv_00085',
    context: 'A koban afternoon. Takeda is showing a new officer (placeholder: Ren, here as the trainee) how to handle a lost-item intake.',
    purpose: 'mentor + trainee — workplace patience, tiny instruction',
    ambient: 'police_box',
    target_vocab: ['本当に','時間','見る','大丈夫','今','少し'],
    cast: ['takeda_officer','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'takeda_officer', jp: 'まず、これ、見て。', en: 'First — look at this.', style: 'Slides a form across the desk. Calm professional pacing.', mood: 'instructional_calm' },
      { speaker: 'ren_uni', jp: '…はい。', en: '…Yes.', style: 'Mumbled focus. Pen already in hand.', mood: 'focused' },
      { speaker: 'takeda_officer', jp: '記入は三カ所だけ。本当に簡単。', en: 'Only three fields to fill. Truly — simple.', style: 'A small reassuring tone. Eye-contact in the voice.', mood: 'reassuring_pro' },
      { speaker: 'ren_uni', jp: '本当に簡単ですか？', en: 'Truly simple?', style: 'Half-laugh of nervous trainee. Doubting himself.', mood: 'nervous_trainee' },
      { speaker: 'takeda_officer', jp: '本当に。最初は、誰でも緊張する。', en: 'Truly. Everyone is nervous at first.', style: 'A normalising kindness. Slow, even.', mood: 'normalising' },
      { speaker: 'ren_uni', jp: '時間、もう少しください、念のため。', en: 'Just to be safe — a little more time, please.', style: 'A small polite request. Voice careful.', mood: 'polite_careful' },
      { speaker: 'takeda_officer', jp: '大丈夫。今日は、お客さん少ないから。', en: 'It\'s fine. Few visitors today.', style: 'A small reassurance with a small joke audible.', mood: 'reassuring_joke' },
      { speaker: 'ren_uni', jp: 'ありがとうございます。', en: 'Thank you very much.', style: 'A small bow inside the voice. Settles into the desk.', mood: 'settling' },
    ],
  },
  {
    id: 'conv_00086',
    context: 'Train-station koban. A child has gotten separated from his mom at rush hour. Takeda has been giving him juice while they wait. Then his mom arrives, half-running.',
    purpose: 'three-speaker — kid, calming officer, panicking parent',
    ambient: 'train_station_day',
    target_vocab: ['本当に','大丈夫','今','すみません','ありがとう','家'],
    cast: ['takeda_officer','sho_child','yumiko_mom'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'takeda_officer', jp: 'もうすぐ、お母さん来るからね。', en: 'Mom\'s coming any moment now.', style: 'Calm crouched voice. Slides a juice across the desk.', mood: 'crouched_calm' },
      { speaker: 'sho_child', jp: '…うん。', en: '…Mm.', style: 'A small one-syllable. Hands holding the juice carefully.', mood: 'careful_small' },
      { speaker: 'yumiko_mom', jp: 'しょう！しょう！…ああ、本当にすみません！', en: 'Sho! Sho! …Oh — truly, I\'m so sorry!', style: 'Half-running breathless. Apology and relief flooding together.', mood: 'breathless_relief' },
      { speaker: 'sho_child', jp: 'お母さん！', en: 'Mom!', style: 'A small bright voice. Stands up too fast in the voice.', mood: 'bright_relief' },
      { speaker: 'yumiko_mom', jp: '迷子になっちゃって、本当に、ご迷惑を…', en: 'He got lost — truly, what an inconvenience for you…', style: 'A real apology directed at Takeda. Half-bow.', mood: 'real_apology' },
      { speaker: 'takeda_officer', jp: '大丈夫ですよ。お子さん、落ち着いて待ってました。', en: 'It\'s fine. He waited calmly.', style: 'Praises the kid before reassuring the mom. Practiced.', mood: 'praising_first' },
      { speaker: 'sho_child', jp: 'おじさん、ジュースくれた。', en: 'The mister gave me juice.', style: 'A small honest report.', mood: 'small_report' },
      { speaker: 'yumiko_mom', jp: '本当に、ありがとうございます。今、お礼…', en: 'Truly — thank you so much. Now, a token…', style: 'Reaching into her bag in the voice. A real fluster.', mood: 'real_fluster' },
      { speaker: 'takeda_officer', jp: 'いえいえ、お気持ちだけで。お気をつけて。', en: 'No, no — your sentiment is enough. Please take care.', style: 'A small polite refusal. Already turning to the next form.', mood: 'polite_refusal' },
      { speaker: 'yumiko_mom', jp: 'はい…本当にありがとうございました。', en: 'Yes… thank you, truly.', style: 'A real bow. Voice steadier now.', mood: 'real_bow' },
      { speaker: 'sho_child', jp: 'バイバイ、おじさん。', en: 'Bye, mister.', style: 'A small bright wave. The whole encounter resolved.', mood: 'bright_resolved' },
    ],
  },
  {
    id: 'conv_00087',
    context: 'A small rural train station. Riku is sitting on a bench at 11am — clearly should be in school. An older country man (Tatsuya) sits down beside him.',
    purpose: 'unexpected mentor — country stillness brushes up against urban teen turmoil',
    ambient: 'train_station_day',
    target_vocab: ['本当に','時間','今','学校','大丈夫','ない'],
    cast: ['tatsuya_country','riku_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '…(sits, silence)いい天気やな。', en: '(sits, silence) Fine weather, eh.', style: 'A whole comfortable silence before this. Tohoku cadence.', mood: 'tohoku_open' },
      { speaker: 'riku_teen', jp: '…そうですね。', en: '…Yes.', style: 'Polite mumbled deflection. Eyes on his phone.', mood: 'mumbled_polite' },
      { speaker: 'tatsuya_country', jp: '学校、休みか。', en: 'School off, then?', style: 'Plain question. No accusation in the voice.', mood: 'plain_open' },
      { speaker: 'riku_teen', jp: '…(silence)', en: '(silence)', style: 'A real beat. The lie too hard to tell.', mood: 'lie_too_hard' },
      { speaker: 'tatsuya_country', jp: 'うん。…時々、そういう日もあるな。', en: 'Mm. …Sometimes there are days like that.', style: 'A small philosophy with no judgment.', mood: 'no_judgment' },
      { speaker: 'riku_teen', jp: '…本当に？', en: '…Really?', style: 'Looks up briefly. Voice cracks half a step.', mood: 'looking_up' },
      { speaker: 'tatsuya_country', jp: '本当に。…大丈夫やで、たまになら。', en: 'Truly. …Now and then is fine.', style: 'A small gift of permission. Real Tohoku warmth.', mood: 'gift_permission' },
      { speaker: 'riku_teen', jp: '…(small breath)', en: '(small breath)', style: 'A real beat. The teen-armor lifting a half-step.', mood: 'armor_lifting' },
      { speaker: 'tatsuya_country', jp: 'でもな。明日は、行きや。今日だけ。', en: 'But — tomorrow, go. Just today.', style: 'A small firm closing line.', mood: 'firm_closing' },
      { speaker: 'riku_teen', jp: '…うん。ありがとう。', en: '…Mm. Thanks.', style: 'A small honest line. Voice quieter than the opener.', mood: 'honest_quiet' },
    ],
  },
  {
    id: 'conv_00088',
    context: 'A hotel bar in central Tokyo, 11pm. Hiroshi (the boss) sits at the counter alone. Aoi has taken a second job here on weekends.',
    purpose: 'unexpected double role — Aoi the barista is also Aoi the late-night bartender',
    ambient: 'bar_late_night',
    target_vocab: ['本当に','今','時間','ありがとう','元気'],
    cast: ['hiroshi_boss','aoi_barista'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'いらっしゃいませ。…ウィスキー、お決まりですか？', en: 'Welcome. …Whiskey, have you decided?', style: 'Calm professional polish. Hands already reaching for the bottle.', mood: 'calm_polish' },
      { speaker: 'hiroshi_boss', jp: 'いつもの、で。…本当に、長い一週間でした。', en: 'The usual. …Truly, a long week.', style: 'Sits heavily. Voice slightly tired for him.', mood: 'tired_for_him' },
      { speaker: 'aoi_barista', jp: 'お疲れさまです。今日も、ストレートで？', en: 'You\'ve earned it. Straight today as well?', style: 'A small remembered detail. Professional but warm.', mood: 'remembered_warm' },
      { speaker: 'hiroshi_boss', jp: 'よく覚えてますね。…ありがとう。', en: 'You remember well. …Thank you.', style: 'A small genuine note. Doesn\'t expect to be remembered.', mood: 'genuine_note' },
      { speaker: 'aoi_barista', jp: 'お客様、皆様の好み、なんとなく。', en: 'Customers — everyone\'s preferences, somehow, I just know.', style: 'A small modest line with a real smile audible.', mood: 'modest_smile' },
      { speaker: 'hiroshi_boss', jp: 'いい仕事ですね、本当に。', en: 'Fine work, truly.', style: 'A small unguarded compliment. Voice quieter.', mood: 'unguarded_compliment' },
    ],
  },
  {
    id: 'conv_00089',
    context: 'Naoko has come to Kyushu for a wholesale ingredient buy. Goro is sitting on a bench by the fish market — the only other customer at the early-morning auction.',
    purpose: 'two old strangers, Kansai meets Kyushu — incidental bench-talk',
    ambient: 'park_morning',
    target_vocab: ['本当に','今','時間','元気','人','ない','見る'],
    cast: ['naoko_aunt','goro_grandpa'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'おはようさん。早いな。', en: 'Mornin\'. You\'re up early.', style: 'Loud Kansai opener. Plops down two metres from him on the bench.', mood: 'loud_open' },
      { speaker: 'goro_grandpa', jp: 'ああ。漁師の癖や。', en: 'Mm. Fisherman\'s habit.', style: 'A slow Kyushu line. Doesn\'t look over.', mood: 'kyushu_slow' },
      { speaker: 'naoko_aunt', jp: 'なるほどなあ。私、大阪。ラーメン屋。', en: 'Ah, makes sense. I\'m from Osaka. Ramen shop.', style: 'Instant intel-sharing. Kansai economy.', mood: 'instant_share' },
      { speaker: 'goro_grandpa', jp: 'ふん。ラーメン、最近食うた覚えがない。', en: 'Hm. Haven\'t eaten ramen in a while, come to think of it.', style: 'A small philosophical observation. Eyes on the water.', mood: 'philosophical' },
      { speaker: 'naoko_aunt', jp: 'なんと！本当に？うちの店、来た方がええで。', en: 'What?! Really? You ought to come to my shop.', style: 'Mock-outraged Kansai. A real invitation behind the bit.', mood: 'mock_outraged' },
      { speaker: 'goro_grandpa', jp: '大阪は、遠いな。', en: 'Osaka — that\'s far.', style: 'A small dry observation. Slight Kyushu humor audible.', mood: 'dry_humor' },
      { speaker: 'naoko_aunt', jp: 'ほな、私が、ここでラーメン作ったろか。', en: 'Then I\'ll make ramen for you right here.', style: 'A wild Kansai joke offer.', mood: 'wild_kansai' },
      { speaker: 'goro_grandpa', jp: '(small laugh)…本当に来そうで、怖いな。', en: '(small laugh) …Sounds like you might actually do it. Scary.', style: 'A real Kyushu laugh, rare. Voice slightly amused.', mood: 'rare_laugh' },
      { speaker: 'naoko_aunt', jp: 'やるで。本当に。お互い、まだ時間あるしな。', en: 'I would. Really. We\'ve still got time, both of us.', style: 'A small unguarded honest line.', mood: 'small_unguarded' },
    ],
  },
  {
    id: 'conv_00090',
    context: 'Tatsuya\'s vegetable patch in Iwate, late summer. Hina is visiting on holiday with her family and has come out alone — Tatsuya is showing her how to pick tomatoes.',
    purpose: 'tiny instructional warmth — country man, city kid',
    ambient: 'park_morning',
    target_vocab: ['本当に','見る','大丈夫','一緒','少し','時間'],
    cast: ['tatsuya_country','hina_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: 'ひな、これ、見てみ。', en: 'Hina — take a look at this.', style: 'Holds up a tomato in the voice. Slow, careful.', mood: 'slow_careful' },
      { speaker: 'hina_child', jp: 'うわ、大きい！', en: 'Whoa — big!', style: 'A bright eight-year-old delight. Voice lifts.', mood: 'bright_delight' },
      { speaker: 'tatsuya_country', jp: 'うん。今日、ちょうどええ時期や。', en: 'Mm. Today — just the right time.', style: 'A small Tohoku-toned line. Slow.', mood: 'tohoku_pleased' },
      { speaker: 'hina_child', jp: '取っていい？', en: 'Can I pick one?', style: 'Hands already hovering. Eager.', mood: 'eager_hovering' },
      { speaker: 'tatsuya_country', jp: 'いい。少し、ねじってな。', en: 'Sure. Twist gently — like that.', style: 'A small careful demonstration. Voice patient.', mood: 'patient_demo' },
      { speaker: 'hina_child', jp: '…取れた！', en: '…Got it!', style: 'A breath of triumph. Holds it up proudly.', mood: 'breath_triumph' },
      { speaker: 'tatsuya_country', jp: 'うまい、うまい。', en: 'Well done.', style: 'A small slow Kyushu-tone praise.', mood: 'slow_praise' },
      { speaker: 'hina_child', jp: 'もう一個、本当に取っていい？', en: 'Another one — can I really pick another?', style: 'A small lobbying. Half-laughs.', mood: 'lobbying' },
      { speaker: 'tatsuya_country', jp: 'たくさんあるで。一緒に取ろう。', en: 'Lots of them. Let\'s pick together.', style: 'A small invitation. Kneels down too in the voice.', mood: 'kneeling_invite' },
      { speaker: 'hina_child', jp: 'うん！おじいちゃん、本当にありがとう！', en: 'Yeah! Grandpa — really, thank you!', style: 'A full kid-volume happiness.', mood: 'full_happy' },
      { speaker: 'tatsuya_country', jp: 'ええよ。…時間あるからな、今日は。', en: 'It\'s fine. …I\'ve got time today.', style: 'A small closing line. The whole afternoon offered.', mood: 'closing_offered' },
    ],
  },
  {
    id: 'conv_00091',
    context: 'Sunday morning in Goro\'s living room. He has been roped into watching Sho for an hour. Both of them look at each other from across the room.',
    purpose: 'tiny intergenerational silence — both unsure what to say',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','大丈夫','見る','ない'],
    cast: ['goro_grandpa','sho_child'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'goro_grandpa', jp: '…(silence)…元気か。', en: '(silence) …You well?', style: 'A whole long beat first. The opening Kyushu cadence slow.', mood: 'opening_slow' },
      { speaker: 'sho_child', jp: '…うん。', en: '…Mm.', style: 'A single careful syllable.', mood: 'careful_single' },
      { speaker: 'goro_grandpa', jp: '…テレビ、見るか。', en: '…Want to watch TV?', style: 'A small pragmatic offer. The neutral ground.', mood: 'pragmatic_offer' },
      { speaker: 'sho_child', jp: 'うん。', en: 'Mm.', style: 'A slightly brighter syllable. Already moving to the couch.', mood: 'slightly_brighter' },
      { speaker: 'goro_grandpa', jp: '何が、いいんかな。', en: 'What\'s a good one, then.', style: 'Reaches for the remote with mild bewilderment in the voice.', mood: 'mild_bewilderment' },
      { speaker: 'sho_child', jp: 'なんでもいい、本当に。', en: 'Anything is fine, really.', style: 'A small kid-honest line. Sits next to him on the couch.', mood: 'kid_honest' },
    ],
  },
  {
    id: 'conv_00092',
    context: 'A weekend morning at the apartment building park. Sho has been trying to ride a scooter; Riku is sitting on a bench with headphones in. He notices and sets the headphones down.',
    purpose: 'older-kid energy directed at a smaller one — accidental big-brother',
    ambient: 'park_morning',
    target_vocab: ['本当に','大丈夫','見る','時間','ない'],
    cast: ['riku_teen','sho_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'riku_teen', jp: 'おい、そこ、止まんなって。', en: 'Hey — stop right there.', style: 'A small Tokyo-teen bark. Half-laugh under it.', mood: 'teen_bark' },
      { speaker: 'sho_child', jp: '…(stops, looks up)', en: '(stops, looks up)', style: 'A real beat. Caught at the top of the path.', mood: 'caught_real' },
      { speaker: 'riku_teen', jp: '足、こう置くんだよ。本当に。', en: 'Feet — like this. Really.', style: 'Crouches down. Demo on his own foot in the voice.', mood: 'demo_crouch' },
      { speaker: 'sho_child', jp: '…こう？', en: '…Like this?', style: 'A small careful attempt.', mood: 'careful_attempt' },
      { speaker: 'riku_teen', jp: 'うん、そう。…見て、楽になる。', en: 'Yeah — like that. Watch — it gets easier.', style: 'A small encouraging line. Voice less guarded than usual.', mood: 'less_guarded' },
      { speaker: 'sho_child', jp: '本当に、楽！', en: 'Really — easy!', style: 'A bright relief. The smallest break-through.', mood: 'bright_breakthrough' },
      { speaker: 'riku_teen', jp: '俺も、お前くらいの時、ヘタやった。', en: 'I was bad at it too, when I was your size.', style: 'A small unexpected vulnerable share.', mood: 'small_share' },
      { speaker: 'sho_child', jp: '本当に？', en: 'Really?', style: 'A small awestruck question.', mood: 'awestruck_small' },
      { speaker: 'riku_teen', jp: '本当に。…じゃ、もう一回、見せて。', en: 'Really. …Now — show me once more.', style: 'A small directive. The big-brother voice activated.', mood: 'big_brother' },
    ],
  },
  {
    id: 'conv_00093',
    context: 'Ren has been hired to help Sakura prep for the qualifying English exam. They\'re at a public library Saturday afternoon. She\'s frustrated.',
    purpose: 'tutor + teen — frustration meets steady patience',
    ambient: 'school_classroom',
    target_vocab: ['本当に','時間','大丈夫','少し','言う','見る','ない'],
    cast: ['ren_uni','sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'もう無理。本当に、無理。', en: 'I can\'t. Really — I can\'t.', style: 'Slams the pencil down softly. Real frustration, half-Kansai.', mood: 'real_frustration' },
      { speaker: 'ren_uni', jp: 'うん。…一回、休もう。', en: 'Mm. …Let\'s take a break.', style: 'Calm, no contradiction. Closes his own book in the voice.', mood: 'calm_yielding' },
      { speaker: 'sakura_teen', jp: 'でも、時間ない。', en: 'But there\'s no time.', style: 'Half-protest, half-honest.', mood: 'half_honest' },
      { speaker: 'ren_uni', jp: '少し休んだ方が、効率いい。本当に。', en: 'A break actually makes it more efficient. Really.', style: 'A small gentle expertise.', mood: 'gentle_expert' },
      { speaker: 'sakura_teen', jp: '…(small exhale)', en: '(small exhale)', style: 'A real beat. Releases the pen.', mood: 'releasing' },
      { speaker: 'ren_uni', jp: 'さっきの問題、見せて。一緒に考えよう。', en: 'Show me that question. Let\'s think it through together.', style: 'Pulls the worksheet over. Voice careful.', mood: 'pulling_together' },
      { speaker: 'sakura_teen', jp: '私、本当にバカやと思ってた。', en: 'I really thought I was an idiot.', style: 'A small confession. Voice quieter.', mood: 'small_confession' },
      { speaker: 'ren_uni', jp: '違うよ。ちゃんと、考え方の問題。', en: 'You\'re not. It\'s a question of approach.', style: 'A small firm reassurance. Doesn\'t over-explain.', mood: 'firm_reassure' },
      { speaker: 'sakura_teen', jp: '…言うてくれる人、初めて。', en: '…First person who\'s said that.', style: 'Voice catches half a step. Real.', mood: 'real_catch' },
      { speaker: 'ren_uni', jp: 'そう？じゃ、私が言い続ける。大丈夫。', en: 'Really? Then I\'ll keep saying it. It\'s fine.', style: 'A small unguarded line. Sits straighter.', mood: 'sitting_straighter' },
      { speaker: 'sakura_teen', jp: 'ありがとう。本当に、ありがとう。', en: 'Thank you. Really — thank you.', style: 'A real doubled thank-you. Voice steady.', mood: 'steady_thanks' },
    ],
  },
  {
    id: 'conv_00094',
    context: 'Daichi\'s family home in Osaka. His mother (Sachiko, playing the part of his elderly mom in this scene) has been waiting all afternoon for him to drop in.',
    purpose: 'adult-son visit home — affectionate maternal interrogation, soft underneath',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','今日','時間','元気','大丈夫','一人','ありがとう','大変'],
    cast: ['daichi_kansai','sachiko_grandma'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'ダイチ、やっと来た！', en: 'Daichi — finally here!', style: 'Loud delighted Kansai-soft-Tokyo blend. Already up from her chair in the voice.', mood: 'delighted_up' },
      { speaker: 'daichi_kansai', jp: 'ごめん、母さん、本当に。仕事、長くて。', en: 'Sorry, Mom — really. Work ran long.', style: 'A small genuine apology. Bag still on shoulder.', mood: 'genuine_apology' },
      { speaker: 'sachiko_grandma', jp: 'ええの、ええの。座って、座って。ご飯あるで。', en: 'It\'s fine, it\'s fine. Sit, sit. There\'s food.', style: 'Three commands disguised as hospitality. Familiar.', mood: 'commanding_warm' },
      { speaker: 'daichi_kansai', jp: '元気にしとった？', en: 'You been well?', style: 'Drops the bag in the voice. Tone genuine.', mood: 'genuine_tone' },
      { speaker: 'sachiko_grandma', jp: '元気、元気。あんたは？最近、本当に痩せた気がする。', en: 'Well, well. And you? Honestly, you\'ve gotten thinner lately.', style: 'A diagnostic mother-look across the room.', mood: 'diagnostic_mother' },
      { speaker: 'daichi_kansai', jp: '痩せてへんよ、別に。', en: 'Haven\'t gotten thinner, really.', style: 'A reflexive deflection. A small smile.', mood: 'reflexive_smile' },
      { speaker: 'sachiko_grandma', jp: 'うそや。お母さんの目、本当に騙されへんで。', en: 'Liar. A mother\'s eyes — really, can\'t fool them.', style: 'Slides a plate across. The diagnostic eye narrowed.', mood: 'diagnostic_eye' },
      { speaker: 'daichi_kansai', jp: '(laughs) はいはい、降参。', en: '(laughs) Alright, alright — I surrender.', style: 'A real Kansai laugh. Half-hands-up in the voice.', mood: 'kansai_surrender' },
      { speaker: 'sachiko_grandma', jp: 'ちゃんと食べんと、大変なことになるで。', en: 'Eat properly, or it\'ll be a real problem.', style: 'A small mother-warning, half-real.', mood: 'half_real_warning' },
      { speaker: 'daichi_kansai', jp: 'はい、はい。…でも、本当に、母さんの料理、いちばん。', en: 'Yes, yes. …But really — your cooking is the best.', style: 'A small unguarded compliment. Real.', mood: 'unguarded_real' },
      { speaker: 'sachiko_grandma', jp: '(small laugh) お世辞、上手なって。', en: '(small laugh) You\'ve gotten good at flattery.', style: 'A small pleased laugh. Pours tea in the voice.', mood: 'pleased_laugh' },
      { speaker: 'daichi_kansai', jp: 'お世辞ちゃう。本当に。', en: 'Not flattery. Really.', style: 'A small firm correction. Mouth full.', mood: 'firm_full' },
      { speaker: 'sachiko_grandma', jp: '一人で、ちゃんと食べてる？', en: 'Are you eating properly — on your own?', style: 'The real question under the previous lines.', mood: 'real_question' },
      { speaker: 'daichi_kansai', jp: '…まあ、ちゃんと、とは言えへんかも。', en: '…Well — properly, maybe I can\'t say.', style: 'A small honest concession. Voice quieter.', mood: 'small_concession' },
      { speaker: 'sachiko_grandma', jp: '本当のこと、ありがとう。ちゃんとしぃや、時間あるから今日は。', en: 'Thanks for the honesty. Take care of yourself — we\'ve got time today.', style: 'A real warmth. The whole afternoon offered.', mood: 'whole_afternoon' },
    ],
  },
  {
    id: 'conv_00095',
    context: 'School pickup. Asuka has been chatting weekly with one of her students\' moms (Yumiko); today they walk to the gate together.',
    purpose: 'parent-teacher friendship — adults becoming friends through proximity',
    ambient: 'school_classroom',
    target_vocab: ['本当に','時間','今日','子供','一緒','大変'],
    cast: ['asuka_teacher','yumiko_mom'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'お疲れさまです。今日も、お迎えですね。', en: 'Good work today. Pickup again, I see.', style: 'A small warm professional greeting. Half-bow in the voice.', mood: 'warm_pro' },
      { speaker: 'yumiko_mom', jp: '本当にお世話になってます。', en: 'Truly — thank you for everything.', style: 'A real bow inside the voice. Polite.', mood: 'polite_real' },
      { speaker: 'asuka_teacher', jp: 'こちらこそ。…たまには、お茶でもしませんか？', en: 'Likewise. …How about tea sometime?', style: 'A small unguarded extension. Voice slightly cautious.', mood: 'cautious_extend' },
      { speaker: 'yumiko_mom', jp: 'えっ、嬉しい。…私で、よかったら、ぜひ。', en: 'Oh — that\'s nice. …If it\'s alright with me — yes, please.', style: 'A small startled pleasure. Half-laugh.', mood: 'startled_pleasure' },
      { speaker: 'asuka_teacher', jp: 'よかった。…子供同士じゃない時間も、大切で。', en: 'I\'m glad. …Time outside of kid-stuff is important too.', style: 'A small honest line. Walks slower with her in the voice.', mood: 'honest_walking' },
      { speaker: 'yumiko_mom', jp: '本当に、そう思います。仕事と子供で、もう毎日…', en: 'I really think so. Between work and kids, every day…', style: 'A small honest exhaustion audible.', mood: 'honest_exhausted' },
      { speaker: 'asuka_teacher', jp: 'わかります。大変ですよね。', en: 'I understand. It\'s a lot.', style: 'A small validating line. Voice steady.', mood: 'validating' },
      { speaker: 'yumiko_mom', jp: '今度、本当に、楽しみにしてます。', en: 'Next time — truly, looking forward to it.', style: 'A real reciprocation. Voice slightly lighter.', mood: 'real_reciprocation' },
      { speaker: 'asuka_teacher', jp: '時間、合わせます。連絡先、交換しましょう。', en: 'I\'ll match your time. Let\'s swap contacts.', style: 'Pulls out her phone in the voice. Friendly initiative.', mood: 'friendly_initiative' },
      { speaker: 'yumiko_mom', jp: 'はい、ぜひ。', en: 'Yes — please.', style: 'A small bright agreement. The friendship beginning.', mood: 'beginning_bright' },
    ],
  },
  {
    id: 'conv_00096',
    context: 'A café between the office and home. Yuki and Mei have been close since university; haven\'t seen each other in three months.',
    purpose: 'long-time friend catch-up — old shorthand, real warmth',
    ambient: 'cafe_afternoon',
    target_vocab: ['本当に','元気','今','時間','一緒','嬉しい'],
    cast: ['yuki_office','mei_romantic'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'ゆきー！久しぶり、本当に！', en: 'Yukii! Long time — really!', style: 'Half-rises in the voice. Real warmth, old friendship.', mood: 'real_warmth' },
      { speaker: 'yuki_office', jp: 'メイ、元気そう。…私、なんか緊張する。', en: 'Mei — you look good. …I feel weirdly nervous.', style: 'Half-laughs at herself. Sits down.', mood: 'self_laughing' },
      { speaker: 'mei_romantic', jp: 'なんでよ。私たち、何年の友達やと思ってんの。', en: 'Why? How many years have we been friends, exactly?', style: 'A small affectionate prod. Voice steady.', mood: 'affectionate_prod' },
      { speaker: 'yuki_office', jp: '十二年、たぶん。…(small laugh)時間って、すごい。', en: 'Twelve years — probably. …(small laugh) Time is something.', style: 'A real small laugh. The whole catch-up\'s warmth.', mood: 'warm_catch_up' },
      { speaker: 'mei_romantic', jp: '本当に。…で、最近どう？', en: 'Truly. …So — how have you been?', style: 'Sits forward. Real attention.', mood: 'real_attention' },
      { speaker: 'yuki_office', jp: '色々ある。仕事…結構、本気で考えてて。', en: 'A lot, actually. Work — I\'ve been seriously thinking.', style: 'A small honest line. Voice slightly steadier than usual.', mood: 'steadier_honest' },
      { speaker: 'mei_romantic', jp: 'そっか。…一緒に、考えよっか、今日。', en: 'I see. …Let\'s think it through together, today.', style: 'A small generous line. The 「一緒に」 carrying the friendship.', mood: 'generous_real' },
      { speaker: 'yuki_office', jp: '…ありがとう。本当に、嬉しい。', en: '…Thank you. Really — I\'m glad.', style: 'A small voice catching. Real.', mood: 'real_catch' },
      { speaker: 'mei_romantic', jp: 'うん。…時間あるよ、たくさん。', en: 'Mm. …I\'ve got time — plenty.', style: 'A small full-hearted commitment. Both lean in.', mood: 'full_commitment' },
    ],
  },
  {
    id: 'conv_00097',
    context: 'Yuki has come to Saito\'s clinic for a routine annual check. The encounter is professional but warm — Saito is also a friend of a friend.',
    purpose: 'small medical encounter — professional with a small human note',
    ambient: 'clinic_waiting_room',
    target_vocab: ['本当に','大丈夫','時間','少し','心配','元気'],
    cast: ['saito_doctor','yuki_office'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '田中さん、こんにちは。お変わりないですか？', en: 'Ms. Tanaka — hello. Anything different?', style: 'Calm professional. Sits across from her.', mood: 'calm_pro' },
      { speaker: 'yuki_office', jp: 'はい…たぶん。少し、最近、疲れやすくて。', en: 'Yes… probably. Just — tired easily lately.', style: 'A small honest report. Voice careful.', mood: 'careful_report' },
      { speaker: 'saito_doctor', jp: 'なるほど。…どのくらい前から？', en: 'I see. …Since how long ago?', style: 'Plain professional follow-up.', mood: 'plain_follow' },
      { speaker: 'yuki_office', jp: '…たぶん、二ヶ月。', en: '…Maybe two months.', style: 'A small honest admission. Voice slightly lower.', mood: 'small_admission' },
      { speaker: 'saito_doctor', jp: '本当に？それは、ちゃんと診ましょう。', en: 'Really? Then — let\'s check properly.', style: 'A small note of real concern professionally framed.', mood: 'real_concern_framed' },
      { speaker: 'yuki_office', jp: '心配かけて、すみません。', en: 'Sorry for the worry.', style: 'A reflexive apology. Half-bow.', mood: 'reflexive_apology' },
      { speaker: 'saito_doctor', jp: '心配は仕事ですから。…体重、少し測りますね。', en: 'Worrying is my job. …Let\'s check your weight.', style: 'A small warm joke that lands.', mood: 'warm_joke' },
      { speaker: 'yuki_office', jp: 'はい。…本当にありがとうございます。', en: 'Yes. …Truly, thank you.', style: 'A small grateful exhale.', mood: 'grateful_exhale' },
      { speaker: 'saito_doctor', jp: '大丈夫ですよ。時間、ゆっくり取りますから。', en: 'It\'ll be fine. I\'ll take my time, properly.', style: 'A small steady kindness. Closes the loop.', mood: 'steady_kind' },
    ],
  },
  {
    id: 'conv_00098',
    context: 'Hiroshi (elder) has been hosting Ren for an evening tutorial in his book-filled living room. They\'ve gotten to the heart of why Ren came.',
    purpose: 'apprentice-style mentorship — old professor and grad student',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','今','大切','言う','考える','一緒','少し'],
    cast: ['hiroshi_elder','ren_uni'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'レンくん、お茶、もう一杯どうかい。', en: 'Ren-kun — another cup of tea?', style: 'Slow polite warmth. The professor cadence.', mood: 'professor_warm' },
      { speaker: 'ren_uni', jp: 'はい、ぜひ。…本当に、お時間、ありがとうございます。', en: 'Yes, please. …Truly — thank you for your time.', style: 'A small bow inside the voice. Pen put down.', mood: 'pen_down' },
      { speaker: 'hiroshi_elder', jp: 'いえいえ。…論文、どこで詰まってる？', en: 'No, no. …Where\'s the thesis stuck?', style: 'A small direct question. Pours slowly.', mood: 'direct_pour' },
      { speaker: 'ren_uni', jp: '第三章で…本当に、書けなくて。', en: 'Chapter three… really — I can\'t write it.', style: 'A small confession. Voice catches half a step.', mood: 'small_catch' },
      { speaker: 'hiroshi_elder', jp: 'うん。…どこが、本当の問題かな。', en: 'Mm. …Where is the real problem, I wonder.', style: 'A small Socratic prompt. Slow.', mood: 'socratic_slow' },
      { speaker: 'ren_uni', jp: '…(thinking)書きたいことが、ありすぎて。', en: '…(thinking) There\'s too much I want to write.', style: 'A real beat. Honest realisation.', mood: 'honest_realise' },
      { speaker: 'hiroshi_elder', jp: 'なるほど。それは、本当によくある。', en: 'I see. That\'s — truly very common.', style: 'A small normalisation. Voice warm.', mood: 'normalising_warm' },
      { speaker: 'ren_uni', jp: 'え、そうなんですか？', en: 'Oh — is that so?', style: 'A small startled lift. Hopeful.', mood: 'startled_hopeful' },
      { speaker: 'hiroshi_elder', jp: '皆、そう。…まず、いちばん大切なこと、一つ、決めなさい。', en: 'Everyone does. …First — decide on one most important thing.', style: 'A small piece of advice. Slow, considered.', mood: 'considered_advice' },
      { speaker: 'ren_uni', jp: '一つだけ…難しい。', en: 'Just one… that\'s hard.', style: 'A small honest reaction.', mood: 'honest_reaction' },
      { speaker: 'hiroshi_elder', jp: '難しい。でも、論文は、一つの問いに、深く答えるもの。', en: 'It is. But a thesis answers one question, deeply.', style: 'A small piece of decades of experience. Even.', mood: 'decades_distilled' },
      { speaker: 'ren_uni', jp: '…(quiet, writing it down)', en: '(quiet, writing it down)', style: 'A real beat. Pen back in hand.', mood: 'writing_down' },
      { speaker: 'hiroshi_elder', jp: '今日でなくていい。少しずつ、絞ろう。', en: 'Doesn\'t have to be today. Narrow it down, gradually.', style: 'A small reassurance. Voice patient.', mood: 'patient_reassure' },
      { speaker: 'ren_uni', jp: '本当に、ありがとうございます。一緒に考えていただいて。', en: 'Truly, thank you — for thinking it through with me.', style: 'A real catch. Bowed.', mood: 'real_bow' },
      { speaker: 'hiroshi_elder', jp: 'こちらこそ、嬉しい。次は、来週で。', en: 'Likewise — I\'m glad. Next time, next week.', style: 'A small closing that opens. Voice warm.', mood: 'closing_open' },
    ],
  },
  {
    id: 'conv_00099',
    context: 'Family dinner. Yumiko, Ryosuke, and Hina are at the table. Hina has been quiet all evening — finally puts her chopsticks down and says something.',
    purpose: 'three-speaker family dinner — kid surprises adults with the real question',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','今','時間','大丈夫','一緒','大切','家族'],
    cast: ['yumiko_mom','ryosuke_dad','hina_child'],
    frequency_tier: 1,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'お母さん、お父さん。…ちょっと、聞きたいことある。', en: 'Mom, Dad. …I want to ask something.', style: 'Sets chopsticks down deliberately. Voice careful for eight years old.', mood: 'careful_eight' },
      { speaker: 'yumiko_mom', jp: 'うん、どうしたの。', en: 'Mm — what is it?', style: 'Drops own chopsticks. Real attention.', mood: 'real_attention' },
      { speaker: 'ryosuke_dad', jp: 'うん、聞くよ。', en: 'Mm — I\'m listening.', style: 'Same beat. Both adults align.', mood: 'aligning' },
      { speaker: 'hina_child', jp: '家族って、本当に、ずっと一緒？', en: 'Family — really — stays together forever?', style: 'A small huge question. Voice quiet.', mood: 'huge_question' },
      { speaker: 'yumiko_mom', jp: '…(beat)どうしてそんなこと、聞くの？', en: '…(beat) Why are you asking that?', style: 'A small careful follow-up. No anger.', mood: 'careful_follow' },
      { speaker: 'hina_child', jp: 'クラスの子の、お父さんとお母さんが…別れたって。', en: 'A kid in my class — their mom and dad split up.', style: 'A small honest report. Voice low.', mood: 'low_report' },
      { speaker: 'ryosuke_dad', jp: 'うん。…そういうこと、あるね、家族にも。', en: 'Mm. …Yes — that happens, even in families.', style: 'A real honest answer. Doesn\'t soften unnecessarily.', mood: 'real_honest' },
      { speaker: 'hina_child', jp: '私たちは…大丈夫？', en: 'Are we… okay?', style: 'A small frightened question. Voice catches.', mood: 'frightened_catch' },
      { speaker: 'yumiko_mom', jp: 'うん。…本当に、大丈夫。', en: 'Yeah. …Truly — we\'re okay.', style: 'A small direct answer. Voice steady.', mood: 'direct_steady' },
      { speaker: 'ryosuke_dad', jp: 'でも、心配してくれて、本当にありがとう。', en: 'But — thank you for worrying. Truly.', style: 'A small honoring of her concern.', mood: 'honoring_concern' },
      { speaker: 'hina_child', jp: '…(small relieved breath)', en: '(small relieved breath)', style: 'A real release. Picks up chopsticks again.', mood: 'real_release' },
      { speaker: 'yumiko_mom', jp: '家族って、ずっと一緒っていうより、ずっと大切に思う。', en: 'Family — it\'s less staying-together than always-caring.', style: 'A small philosophical line offered gently.', mood: 'gentle_philosophy' },
      { speaker: 'hina_child', jp: '…うん。わかった。', en: '…Mm. Got it.', style: 'A small grown-up nod. Real.', mood: 'small_grown' },
      { speaker: 'ryosuke_dad', jp: '今度、何でも、聞いていいからね。', en: 'Anything — anytime — you can ask.', style: 'A small closing line. Real.', mood: 'closing_real' },
    ],
  },
  {
    id: 'conv_00100',
    context: 'A three-way meeting at the office. Hiroshi (boss), Kenji (senior subordinate), and Yuki (junior). The boss is laying out a difficult project; Yuki has been promoted into a leadership role on it.',
    purpose: 'three-way workplace formality — assignment and quiet support',
    ambient: 'office_meeting_room',
    target_vocab: ['本当に','時間','今','大変','大丈夫','一緒','仕事'],
    cast: ['hiroshi_boss','kenji_office','yuki_office'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '佐藤くん、田中さん、お時間ありがとう。', en: 'Sato-kun, Ms. Tanaka — thank you for the time.', style: 'Calm professional opener. Sits at the head of the table.', mood: 'professional_opener' },
      { speaker: 'kenji_office', jp: '(small bow) はい。', en: '(small bow) Yes.', style: 'Reflexive professional bow inside the voice.', mood: 'reflexive_bow' },
      { speaker: 'yuki_office', jp: 'はい、よろしくお願いします。', en: 'Yes — at your service.', style: 'Careful junior politeness.', mood: 'careful_junior' },
      { speaker: 'hiroshi_boss', jp: 'この案件、田中さんに、リードしてもらいたい。', en: 'On this matter — Ms. Tanaka, I\'d like you to lead.', style: 'Direct, no preamble. Hands the file across.', mood: 'direct_hand' },
      { speaker: 'yuki_office', jp: 'えっ…私、ですか？', en: 'Wait — me?', style: 'A small startled lift. Hands instinctively to chest.', mood: 'startled_lift' },
      { speaker: 'hiroshi_boss', jp: 'うん。本当に、君に任せたい。', en: 'Yes. Truly — I want to entrust this to you.', style: 'The 「本当に」 rare from him. Lands genuine.', mood: 'rare_genuine' },
      { speaker: 'kenji_office', jp: 'いい話ですね。私も、後ろから支えます。', en: 'Good news. I\'ll support from behind.', style: 'A small senior-colleague reassurance.', mood: 'senior_reassure' },
      { speaker: 'yuki_office', jp: 'お二人、本当にありがとうございます。', en: 'Both of you — truly, thank you.', style: 'A real bow inside the voice. Voice slightly catches.', mood: 'real_catch' },
      { speaker: 'hiroshi_boss', jp: '一緒に、進めよう。大変だが、できる。', en: 'Let\'s move forward together. It\'s hard — but doable.', style: 'A small firm encouragement.', mood: 'firm_encourage' },
      { speaker: 'kenji_office', jp: '時間、私も合わせます。', en: 'I\'ll match my time too.', style: 'A small parallel commitment.', mood: 'parallel_commit' },
      { speaker: 'yuki_office', jp: '頑張ります。本当に、頑張ります。', en: 'I\'ll do my best. Truly — my best.', style: 'A small doubled commitment. Voice steady.', mood: 'doubled_commit' },
      { speaker: 'hiroshi_boss', jp: '頼みます。', en: 'I\'m counting on you.', style: 'A small closing line. Slight bow.', mood: 'closing_pro' },
    ],
  },
  {
    id: 'conv_00101',
    context: 'Last call at a bar Kenji, Daichi, and Aoi all know. Aoi is doing closing; Kenji and Daichi are the last two customers.',
    purpose: 'three-way bar moment — friends + service-friend, final-cup intimacy',
    ambient: 'bar_late_night',
    target_vocab: ['本当に','今日','時間','大丈夫','ありがとう','元気'],
    cast: ['kenji_office','daichi_kansai','aoi_barista'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'もう少しで、ラストオーダーです。', en: 'Last orders, in a moment.', style: 'Calm professional but warm. Hands moving.', mood: 'calm_warm' },
      { speaker: 'daichi_kansai', jp: 'あおいちゃん、一杯、私らと飲み？', en: 'Aoi-chan — one cup with us, eh?', style: 'A small Kansai invitation. Half-laughing.', mood: 'kansai_invite' },
      { speaker: 'aoi_barista', jp: '(small laugh) 仕事中だから、本当に、無理です。', en: '(small laugh) I\'m working — really, can\'t.', style: 'A real laugh. Polite refusal.', mood: 'polite_refuse' },
      { speaker: 'kenji_office', jp: 'まあな、無理言うな、ダイチ。', en: 'Come on, don\'t put her on the spot, Daichi.', style: 'A small senior-friend correction.', mood: 'senior_correct' },
      { speaker: 'daichi_kansai', jp: 'はいはい、すまんすまん。', en: 'Yeah, yeah — sorry, sorry.', style: 'Kansai self-deprecation. Half-laugh.', mood: 'kansai_apology' },
      { speaker: 'aoi_barista', jp: '本当に、お二人、よく来てくださって。', en: 'You two — really, thank you for coming so often.', style: 'A small genuine line. Slides their drinks.', mood: 'small_genuine' },
      { speaker: 'kenji_office', jp: 'こちらこそ。…今日は、特に助かった。', en: 'Likewise. …Today especially — it helped.', style: 'A small unguarded line. Real.', mood: 'small_unguarded' },
      { speaker: 'aoi_barista', jp: 'いつでも、来てくださいね。', en: 'Come any time — please.', style: 'A small warm closing. Voice quiet.', mood: 'warm_closing' },
      { speaker: 'daichi_kansai', jp: 'あおいちゃん、ほんま、ありがとう。', en: 'Aoi-chan — really, thanks.', style: 'A small full Kansai gratitude.', mood: 'kansai_gratitude' },
      { speaker: 'kenji_office', jp: '時間、引き止めてすみません。お疲れさまです。', en: 'Sorry for keeping you. Good work today.', style: 'A small considerate close.', mood: 'considerate_close' },
      { speaker: 'aoi_barista', jp: '大丈夫です。…お気をつけて、お帰りを。', en: 'It\'s fine. …Get home safely.', style: 'A small warm send-off.', mood: 'warm_send' },
    ],
  },
  {
    id: 'conv_00102',
    context: 'Sachiko, her adult daughter Yumiko, and her five-year-old grandson Sho are at the kitchen table on a quiet Sunday. Sachiko has news. The whole afternoon turns on it.',
    purpose: 'three-generation extended scene — health news, three layers of reaction',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','今','心配','大丈夫','一緒','大切','家族','元気'],
    cast: ['sachiko_grandma','yumiko_mom','sho_child'],
    frequency_tier: 2,
    length_tier: 'Extended (21-30)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'ゆみちゃん、しょうくん、ちょっと、座って。', en: 'Yumi-chan, Sho-kun — sit a moment.', style: 'A soft careful summoning. The kitchen quiets.', mood: 'careful_summon' },
      { speaker: 'yumiko_mom', jp: 'うん…何、お母さん。', en: 'Mm — what is it, Mom?', style: 'A small careful follow-up. Reads the air.', mood: 'reading_air' },
      { speaker: 'sho_child', jp: '…(climbs into chair, quiet)', en: '(climbs into chair, quiet)', style: 'A real beat. Reads the adults\' faces.', mood: 'reading_faces' },
      { speaker: 'sachiko_grandma', jp: 'こないだ、検査受けてね。…ちょっと、見つかったんよ。', en: 'I had a test the other day. …Something — was found.', style: 'A small careful release. Voice steady but soft.', mood: 'careful_release' },
      { speaker: 'yumiko_mom', jp: '…(beat)どんな、検査？', en: '…(beat) What kind of test?', style: 'A small composed response. Adult voice activated.', mood: 'adult_activated' },
      { speaker: 'sachiko_grandma', jp: '本当に、心配しすぎなくて、大丈夫よ。', en: 'Truly — don\'t worry too much. It\'s okay.', style: 'Mother-soothing first, news-delivering second.', mood: 'soothe_first' },
      { speaker: 'sho_child', jp: 'おばあちゃん、痛い？', en: 'Grandma — does it hurt?', style: 'A small honest five-year-old question.', mood: 'kid_honest' },
      { speaker: 'sachiko_grandma', jp: '(small laugh) 痛くないよ、しょうくん。本当に。', en: '(small laugh) Doesn\'t hurt, Sho-kun. Really.', style: 'A real warm laugh. Pats his hand.', mood: 'warm_laugh' },
      { speaker: 'yumiko_mom', jp: 'お母さん、ちゃんと教えて。', en: 'Mom — tell me properly.', style: 'A small firm adult line. Voice steady but tight.', mood: 'firm_tight' },
      { speaker: 'sachiko_grandma', jp: 'うん。…小さいの、見つかったの。今、経過観察。', en: 'Mm. …Something small — was found. Just monitoring now.', style: 'A small clinical-but-soft delivery.', mood: 'clinical_soft' },
      { speaker: 'yumiko_mom', jp: '…一緒に、病院、行く。次は、必ず。', en: '…I\'m going with you. Next time — without fail.', style: 'A small firm commitment. Voice catches half a step.', mood: 'firm_catch' },
      { speaker: 'sachiko_grandma', jp: 'いいの、いいの。あなた、仕事、本当に大変なのに。', en: 'It\'s fine, it\'s fine. You — work\'s really hard for you.', style: 'A small protest. Mother-style.', mood: 'mother_protest' },
      { speaker: 'yumiko_mom', jp: '仕事、関係ない。時間、絶対作る。', en: 'Work doesn\'t matter. I\'ll make time — absolutely.', style: 'A small firm overrule. Voice steady.', mood: 'firm_overrule' },
      { speaker: 'sho_child', jp: '私も、行く。', en: 'I\'ll go too.', style: 'A small unexpected child-voice. Quiet certainty.', mood: 'child_certain' },
      { speaker: 'sachiko_grandma', jp: 'しょうくん…(voice softens)ありがとう。', en: 'Sho-kun… (voice softens) thank you.', style: 'A small real catch in the voice. Real.', mood: 'real_catch' },
      { speaker: 'yumiko_mom', jp: '家族、みんなで、ちゃんとやろ。本当に。', en: 'Family — all of us — let\'s do this properly. Really.', style: 'A small grounding line. Reaches for both their hands.', mood: 'grounding' },
      { speaker: 'sachiko_grandma', jp: '…(small breath)ありがとう、二人とも。', en: '…(small breath) Thank you, both of you.', style: 'A real exhale. Voice steadier than before.', mood: 'real_steady' },
      { speaker: 'sho_child', jp: 'おばあちゃん、私の絵、見る？元気になるから。', en: 'Grandma — want to see my drawing? It\'ll cheer you up.', style: 'A small unexpected pivot. Pure kid-warmth.', mood: 'pure_kid' },
      { speaker: 'sachiko_grandma', jp: '見る、見る。本当に、見たい。', en: 'I do — really. I really want to.', style: 'A small real laugh through the tears.', mood: 'laugh_tears' },
      { speaker: 'yumiko_mom', jp: 'お母さん、一緒に、お茶でも入れる？', en: 'Mom — shall I make some tea, together?', style: 'A small practical kindness. Stands.', mood: 'practical_kindness' },
      { speaker: 'sachiko_grandma', jp: 'うん。…一緒に、ね。', en: 'Mm. …Together — yes.', style: 'A small quiet line. The whole afternoon condensed.', mood: 'whole_condensed' },
      { speaker: 'sho_child', jp: '(running for the drawings)', en: '(running for the drawings)', style: 'A real beat. The energy in the room re-channeled.', mood: 'rechanneled' },
    ],
  },
  {
    id: 'conv_00103',
    context: 'New Year\'s morning. The Saito family living room (mom Yumiko, dad Ryosuke, daughter Hina) plus grandma Sachiko visiting from out of town. The osechi is out; everyone has been awake too long.',
    purpose: 'four-speaker family New Year — overlapping affection across generations',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','今日','明日','元気','大丈夫','一緒','家族','時間','ありがとう'],
    cast: ['sachiko_grandma','yumiko_mom','ryosuke_dad','hina_child'],
    frequency_tier: 1,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'みなさん、明けまして、おめでとう。', en: 'Everyone — happy new year.', style: 'Slow, ceremonial, warm. The opening line of the holiday.', mood: 'ceremonial_warm' },
      { speaker: 'yumiko_mom', jp: 'おめでとうございます、お母さん。', en: 'Happy new year, Mom.', style: 'A small formal-warm return. Half-bow.', mood: 'formal_warm' },
      { speaker: 'ryosuke_dad', jp: '明けましておめでとうございます。本当に、来てくれて、ありがとう。', en: 'Happy new year. Truly — thank you for coming.', style: 'A small genuine welcome. Voice steady.', mood: 'genuine_welcome' },
      { speaker: 'hina_child', jp: 'おばあちゃん、おめでとう！お年玉は？', en: 'Grandma — happy new year! Where\'s my otoshidama?', style: 'A real eight-year-old. The whole holiday compressed into one question.', mood: 'compressed_kid' },
      { speaker: 'sachiko_grandma', jp: '(laughs) はいはい、ちゃんとあるよ、ひなちゃん。', en: '(laughs) Yes, yes — I\'ve got it, Hina-chan.', style: 'A real laugh. Already pulling out an envelope.', mood: 'real_laugh' },
      { speaker: 'yumiko_mom', jp: 'ひな、まずご挨拶。順番。', en: 'Hina — greetings first. Order.', style: 'A small mom-correction. Half-laugh underneath.', mood: 'mom_correct' },
      { speaker: 'hina_child', jp: 'はーい。…おばあちゃん、今年もよろしく。', en: 'Okaaay. …Grandma — let\'s have a good year.', style: 'A small adjusted formality. Voice softer.', mood: 'adjusted_formal' },
      { speaker: 'sachiko_grandma', jp: 'こちらこそ、ひなちゃん。…本当に、大きくなったね。', en: 'Likewise, Hina-chan. …Really, you\'ve grown.', style: 'A small grandmother-line. Voice catches half a step.', mood: 'grandmother_catch' },
      { speaker: 'ryosuke_dad', jp: 'お母さん、お雑煮、いかがですか？', en: 'Mom — how about some ozoni?', style: 'A small dad-host line. Pours.', mood: 'dad_host' },
      { speaker: 'sachiko_grandma', jp: 'いただきます。本当に、家族で食べるご飯は、いちばん。', en: 'Itadakimasu. Truly — eating with family is the best.', style: 'A small philosophical line. Voice slightly quieter.', mood: 'philosophical_quiet' },
      { speaker: 'hina_child', jp: 'お餅、私、三個食べる！', en: 'Mochi — I\'ll eat three!', style: 'A full eight-year-old declaration. Voice bouncing.', mood: 'kid_declaration' },
      { speaker: 'yumiko_mom', jp: '一個ずつ、お母さん。お餅は、本当に詰まるから。', en: 'One at a time, Mom. Mochi really gets stuck.', style: 'A small practical mom-warning.', mood: 'practical_warn' },
      { speaker: 'ryosuke_dad', jp: 'お母さんもね、ゆっくり。今日は、時間ある。', en: 'Mom too — slowly. We\'ve got time today.', style: 'A small inclusive line. Looks at both of them.', mood: 'inclusive' },
      { speaker: 'sachiko_grandma', jp: '本当に、ね。…一緒に過ごせて、嬉しい。', en: 'Truly. …I\'m glad we can spend time together.', style: 'A small unguarded sentence. Voice soft.', mood: 'unguarded_soft' },
      { speaker: 'hina_child', jp: '今年、たくさん遊ぼうね、おばあちゃん。', en: 'Let\'s play lots this year, Grandma.', style: 'A small kid-promise that lands hard.', mood: 'kid_promise' },
      { speaker: 'sachiko_grandma', jp: '…ありがとう、ひなちゃん。本当に。', en: '…Thank you, Hina-chan. Really.', style: 'A real catch. The whole morning condensed.', mood: 'morning_condensed' },
      { speaker: 'yumiko_mom', jp: '来年も、再来年も、一緒に。家族で、いっぱい時間作ろう。', en: 'Next year — the year after too. Together. As a family, lots of time.', style: 'A small closing-but-opening line.', mood: 'closing_opening' },
    ],
  },
];

for (const conv of CONVERSATIONS) fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
console.log(`wrote ${CONVERSATIONS.length} conversation(s) to ${OUT_DIR}`);
