import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_118)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02341',
    'Daichi and Sho-young watch the Olympics on TV together.',
    'Father and son sharing sports excitement naturally.',
    'living_room_tv_low',
    ['オリンピック', '活躍', '応援', '比べる'],
    ['daichi_kansai', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'お父さん、オリンピック、始まったね!', en: "Dad — the Olympics started!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、日本の選手、活躍しとるな。', en: "Yeah — the Japanese athletes are doing great.", style: 'warm Kansai father voice, soft proud engaged delivery carefully' },
      { speaker: 'sho_child', jp: 'この選手、すごく速い!', en: "This athlete is really fast!", style: 'animated child boy voice, bright warm awed delivery carefully' },
      { speaker: 'daichi_kansai', jp: '前の大会と比べても、力が上がってるな。', en: "Compared to the last games, they've gotten stronger.", style: 'soft Kansai father voice, warm thoughtful delivery carefully' },
      { speaker: 'sho_child', jp: '最後まで、応援しよう!', en: "Let's cheer to the very end!", style: 'bright child boy voice, soft warm passionate delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、一緒に見よか。', en: "Yeah, let's watch together.", style: 'tender Kansai father voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02342',
    'Hina-young recommends a TV drama to Mei.',
    'Teen sharing media enthusiasm naturally.',
    'living_room_evening_warm',
    ['ドラマ', '解釈', '再び', '面白い'],
    ['hina_child', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'hina_child', jp: 'メイさん、このドラマ、面白いよ!', en: "Mei, this drama is really good!", style: 'bright teen girl voice, soft warm enthusiastic delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、どんな話なの?', en: "Oh, what's it about?", style: 'gentle young woman voice, soft warm curious delivery carefully' },
      { speaker: 'hina_child', jp: '最後の場面、解釈が分かれるんだって。', en: "Apparently people read the final scene differently.", style: 'soft teen girl voice, warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'それは、もう一回見たくなるね。', en: "That makes you want to watch it again.", style: 'warm young woman voice, soft fond delivery carefully' },
      { speaker: 'hina_child', jp: '再び見たら、また違う気持ちになりそう。', en: "Watching it again, I'd probably feel something different.", style: 'tender teen girl voice, soft warm thoughtful delivery carefully' },
      { speaker: 'mei_romantic', jp: '一緒に、見てみようか。', en: "Want to watch it together?", style: 'soft young woman voice, warm warm inviting delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、ぜひ!', en: "Yeah, definitely!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ]),
  C('conv_02343',
    'Sho-young goes horseback riding for the first time with Tatsuya.',
    'Elder guiding child on first riding experience.',
    'ranch_outdoor_breeze',
    ['馬', 'スタート', '怖い', '優しい'],
    ['tatsuya_country', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おじさん、馬、大きいね!', en: "Mister, the horse is so big!", style: 'awed child boy voice, bright warm honest delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、優しい馬やから、怖がらんでええ。', en: "Yeah, it's a gentle horse, no need to be scared.", style: 'slow Tohoku farmer voice, warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: 'ちょっと、怖いけど、乗ってみる!', en: "I'm a little scared, but I'll try riding!", style: 'soft brave child boy voice, warm determined delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ゆっくり、スタートしような。', en: "Let's start off slowly.", style: 'gentle Tohoku voice, soft warm patient delivery carefully' },
      { speaker: 'sho_child', jp: 'うわ、揺れる、楽しい!', en: "Whoa, it sways — this is fun!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ええ笑顔やな、その調子や。', en: "Nice smile — that's the spirit.", style: 'tender Tohoku farmer voice, soft warm proud delivery carefully' },
    ]),
  C('conv_02344',
    'Aoi shops for clothes; asks a store clerk about sizes.',
    'Customer-clerk natural shopping exchange.',
    'shop_quiet_low',
    ['店員', 'サイズ', '限定', '丁寧'],
    ['aoi_barista', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'すみません、店員さん、このサイズ、ありますか?', en: "Excuse me — do you have this in my size?", style: 'soft polite adult woman voice, warm friendly delivery carefully' },
      { speaker: 'yuki_office', jp: 'はい、少々お待ちください、確認します。', en: "Yes, one moment please, I'll check.", style: 'composed clerk-mode office woman voice, soft warm professional delivery carefully' },
      { speaker: 'aoi_barista', jp: 'これ、限定の商品なんですか?', en: "Is this a limited-edition item?", style: 'curious adult woman voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: 'ええ、今月だけの限定です。', en: "Yes, it's limited to this month only.", style: 'gentle office woman voice, soft warm informative delivery carefully' },
      { speaker: 'aoi_barista', jp: '丁寧に教えてくださって、ありがとう。', en: "Thank you for explaining so kindly.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'yuki_office', jp: 'またお越しくださいね。', en: "Please come again.", style: 'warm office woman voice, soft warm courteous delivery carefully' },
    ]),
  C('conv_02345',
    'Saito explains a mild illness to a worried Mei.',
    'Doctor reassuring patient naturally.',
    'clinic_room_quiet',
    ['病気', '医師', '詳しく', '安心'],
    ['saito_doctor', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '先生、この病気、心配なんです。', en: "Doctor, I'm worried about this illness.", style: 'soft worried young mother voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '大丈夫ですよ、詳しく説明しますね。', en: "It's all right — let me explain in detail.", style: 'measured doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お薬で、よくなりますか?', en: "Will medicine make it better?", style: 'gentle young woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ、ゆっくり休めば、回復します。', en: "Yes — with rest, you'll recover.", style: 'gentle doctor voice, soft warm caring delivery carefully' },
      { speaker: 'mei_romantic', jp: '医師の先生に、聞けて安心しました。', en: "I feel relieved hearing it from you, Doctor.", style: 'tender young woman voice, soft warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'いつでも、相談してくださいね。', en: "Please consult me anytime.", style: 'warm doctor voice, soft warm supportive delivery carefully' },
    ]),
  C('conv_02346',
    'Kenji and Aoi plan a camping trip together.',
    'Couple planning a getaway naturally.',
    'living_room_evening_lamp',
    ['キャンプ', '高める', '意欲', '楽しみ'],
    ['kenji_office', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'けんちゃん、今度、キャンプ行かない?', en: "Ken-chan, want to go camping sometime?", style: 'bright adult woman voice, soft warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええなぁ、ちょっと意欲、湧いてきたわ。', en: "Sounds great — I'm getting motivated.", style: 'warm Kansai husband voice, soft warm engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: '自然の中で、気分を高めたいの。', en: "I want to lift my spirits out in nature.", style: 'soft adult woman voice, warm content delivery carefully' },
      { speaker: 'kenji_office', jp: 'テント、準備せなあかんな。', en: "We'll need to get the tent ready.", style: 'gentle Kansai husband voice, soft warm practical delivery carefully' },
      { speaker: 'aoi_barista', jp: 'すごく楽しみ!', en: "I'm really looking forward to it!", style: 'tender adult woman voice, soft warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほな、計画、立てよか。', en: "All right, let's make a plan.", style: 'warm Kansai husband voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02347',
    'Sho-young asks Hiroshi-elder about life long ago.',
    'Grandfather sharing the past naturally.',
    'porch_afternoon_quiet',
    ['かつて', '少なく', '電気', '昔'],
    ['hiroshi_elder', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おじいちゃん、昔って、電気あったの?', en: "Grandpa, was there electricity in the old days?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、でも、かつては少なかったで。', en: "Yeah, but back then there was less of it.", style: 'slow elder Kansai voice, warm reminiscent delivery carefully' },
      { speaker: 'sho_child', jp: 'えー、夜、暗かった?', en: "Whoa — was it dark at night?", style: 'awed child boy voice, soft warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '電気の灯り、少なくてな、星がよう見えた。', en: "There were few lights, so you could really see the stars.", style: 'gentle elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'いいなぁ、見てみたい!', en: "That sounds nice — I'd love to see that!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'いつか、田舎で見せたるわ。', en: "Someday I'll show you out in the countryside.", style: 'tender elder Kansai voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02348',
    'Hina-young studies for an exam; talks about her goal with Ren.',
    'Teen sharing study goal naturally.',
    'study_lamp_evening',
    ['資格', '困難', '医師', 'ひとり'],
    ['hina_child', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hina_child', jp: '蓮くん、将来、医師になりたいの。', en: "Ren, I want to become a doctor someday.", style: 'soft teen girl voice, warm earnest dreamy delivery carefully' },
      { speaker: 'ren_uni', jp: 'いいですね、資格、難しそうですか?', en: "That's wonderful — are the qualifications hard?", style: 'gentle young man voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、すごく困難な道だと思う。', en: "Yeah, I think it's a really difficult path.", style: 'soft teen girl voice, warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: 'でも、ひとりじゃないですよ。', en: "But you're not alone in it.", style: 'warm young man voice, soft warm reassuring delivery carefully' },
      { speaker: 'hina_child', jp: '応援してくれて、心強い。', en: "Having your support means a lot.", style: 'tender teen girl voice, soft warm grateful delivery carefully' },
      { speaker: 'ren_uni', jp: '一緒に、頑張りましょう。', en: "Let's work hard together.", style: 'soft young man voice, warm warm supportive delivery carefully' },
    ]),
  C('conv_02349',
    'Daichi notices road construction on his commute; mentions it to Mei.',
    'Husband sharing daily observation naturally.',
    'kitchen_evening_warm',
    ['工事', '自動車', '困難', '時間'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'メイ、駅前で、工事、始まったわ。', en: "Mei, they've started construction near the station.", style: 'soft Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、自動車、通りにくくなる?', en: "Oh — will it make driving harder?", style: 'gentle young wife voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、しばらく、困難やろな。', en: "Yeah, it'll probably be tough for a while.", style: 'warm Kansai husband voice, soft warm thoughtful delivery carefully' },
      { speaker: 'mei_romantic', jp: '時間、余裕持って出ないとね。', en: "We'd better leave with time to spare.", style: 'soft young woman voice, warm practical delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'そやな、早めに出るわ。', en: "Right, I'll head out early.", style: 'gentle Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '気をつけてね。', en: "Take care.", style: 'tender young wife voice, soft warm caring delivery carefully' },
    ]),
  C('conv_02350',
    'Naoko and Yumiko discuss a famous athlete retiring.',
    'Two older women discussing news naturally.',
    'ramen_shop_afternoon',
    ['引退', '活躍', '近年', '惜しい'],
    ['naoko_aunt', 'yumiko_mom'], 'Medium (7-12)',
    [
      { speaker: 'naoko_aunt', jp: 'お姉さん、あの選手、引退するんやって!', en: "Sister, that athlete's retiring!", style: 'animated Kansai aunt voice, bright warm surprised delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、近年、ずっと活躍してたのにね。', en: "Oh, and they've been so active these recent years.", style: 'gentle older mother voice, soft warm reflective delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ほんま、惜しいわ。', en: "Truly, what a shame.", style: 'soft Kansai aunt voice, warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'でも、ようけ頑張ったわね。', en: "But they gave it their all.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'naoko_aunt', jp: '次の人生も、応援したいわ。', en: "I want to root for their next chapter too.", style: 'warm Kansai aunt voice, soft warm supportive delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'そうね、お疲れさまって、言いたい。', en: "Yes — I'd like to say 'well done.'", style: 'soft older mother voice, warm warm appreciative delivery carefully' },
    ]),
  C('conv_02351',
    'Ren reads about an art exhibition; discusses interpretation with Sakura.',
    'Two writers discussing art naturally.',
    'cafe_afternoon_low',
    ['解釈', '引用', '正常', '比べる'],
    ['ren_uni', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'さくらさん、この作品の解釈、難しいですね。', en: "Sakura, this piece is hard to interpret.", style: 'soft young man voice, warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '本に引用されてた批評、読んだ?', en: "Did you read the review quoted in the book?", style: 'gentle adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、でも、皆、感じ方が違う。', en: "Yes, but everyone feels it differently.", style: 'composed young man voice, soft warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '他の作品と比べると、面白いね。', en: "It's interesting compared to other works.", style: 'soft adult writer voice, warm appreciative delivery carefully' },
      { speaker: 'ren_uni', jp: '正常な見方なんて、ないのかも。', en: "Maybe there's no 'correct' way to see it.", style: 'tender young man voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: 'それが、芸術の面白さね。', en: "That's the beauty of art.", style: 'warm adult writer voice, soft warm content delivery carefully' },
    ]),
  C('conv_02352',
    'Sho-young excited about a school sports day; tells Mei.',
    'Child sharing school excitement naturally.',
    'living_room_evening_warm',
    ['運動会', 'スタート', '活躍', '応援'],
    ['sho_child', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'お母さん、運動会、もうすぐ!', en: "Mom, sports day is coming up!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、楽しみね。何に出るの?', en: "Oh, how exciting. What are you in?", style: 'gentle young mother voice, soft warm curious delivery carefully' },
      { speaker: 'sho_child', jp: 'かけっこ!スタート、がんばる!', en: "The race! I'll give the start my all!", style: 'animated child boy voice, bright warm determined delivery carefully' },
      { speaker: 'mei_romantic', jp: 'みんなの前で、活躍できるといいね。', en: "I hope you shine in front of everyone.", style: 'soft young mother voice, warm warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'お母さん、応援してくれる?', en: "Mom, will you cheer for me?", style: 'eager child boy voice, bright warm hopeful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'もちろん、いちばん大きな声でね。', en: "Of course — the loudest of all.", style: 'tender young mother voice, soft warm steadfast delivery carefully' },
    ]),
  C('conv_02353',
    'Kenji and Daichi discuss energy and power topics on the news.',
    'Two friends discussing current affairs naturally.',
    'living_room_tv_low',
    ['原子力', '近年', '保障', '議論'],
    ['kenji_office', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: 'ダイチ、原子力の話、また出てるな。', en: "Daichi, the nuclear power topic is up again.", style: 'soft Kansai man voice, warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、近年、ようけ議論になっとるな。', en: "Yeah, it's been debated a lot in recent years.", style: 'warm Kansai husband voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: '安全の保障、大事やな。', en: "Guaranteeing safety is important.", style: 'gentle Kansai man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '我々も、しっかり考えなあかん。', en: "We need to think about it seriously too.", style: 'firm Kansai husband voice, soft warm earnest delivery carefully' },
      { speaker: 'kenji_office', jp: '難しい問題やな、ほんま。', en: "It's a tough issue, really.", style: 'soft Kansai man voice, warm reflective delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'みんなで、向き合っていこう。', en: "Let's face it together.", style: 'warm Kansai husband voice, soft warm united delivery carefully' },
    ]),
  C('conv_02354',
    'Hina-young attends a birthday party; tells Yumiko about it.',
    'Teen recounting social event naturally.',
    'living_room_lamp_warm',
    ['パーティ', '店員', '高める', '楽しい'],
    ['hina_child', 'yumiko_mom'], 'Medium (7-12)',
    [
      { speaker: 'hina_child', jp: 'おばあちゃん、パーティ、楽しかった!', en: "Grandma, the party was so fun!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、よかったわね。どこで?', en: "Oh, how nice. Where was it?", style: 'gentle older mother voice, soft warm curious delivery carefully' },
      { speaker: 'hina_child', jp: 'カフェで、店員さんも優しかった。', en: "At a cafe — the staff were kind too.", style: 'soft teen girl voice, warm content delivery carefully' },
      { speaker: 'yumiko_mom', jp: '皆で、気分を高められたのね。', en: "You all got to lift your spirits together.", style: 'warm older mother voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、友達と、たくさん笑った!', en: "Yeah — I laughed a lot with my friends!", style: 'thrilled teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'いい思い出になったわね。', en: "What a lovely memory.", style: 'tender older mother voice, soft warm content delivery carefully' },
    ]),
  C('conv_02355',
    'Sakura interviews a small business owner about manufacturing.',
    'Writer interviewing professional naturally.',
    'office_quiet_low',
    ['製造', '資産', '高める', '工夫'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '社長、製造の現場、見せていただけますか?', en: "Boss, may I see the manufacturing floor?", style: 'gentle adult writer voice, soft warm respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'もちろんです、こちらへどうぞ。', en: "Of course — this way, please.", style: 'measured boss voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '品質を高める、工夫があるんですね。', en: "You have ways of raising the quality.", style: 'soft adult writer voice, warm appreciative delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ええ、大事な資産は、人ですから。', en: "Yes — our most important asset is people.", style: 'warm boss voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '素敵な考え方ですね。', en: "What a wonderful philosophy.", style: 'tender adult writer voice, soft warm admiring delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '記事、よろしく頼みますね。', en: "I'm counting on the article.", style: 'warm boss voice, soft warm trusting delivery carefully' },
    ]),
  C('conv_02356',
    'Sho-young and Riku-teen play a board game; competitive fun.',
    'Two friends playing a game naturally.',
    'living_room_table_lamp',
    ['上位', 'スタート', '比べる', '勝負'],
    ['riku_teen', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: '陸くん、もう一回、勝負しよ!', en: "Riku, let's play one more round!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'riku_teen', jp: 'ええで、今度はスタートから本気や!', en: "Sure — this time I'm serious from the start!", style: 'animated teen boy voice, bright warm playful delivery carefully' },
      { speaker: 'sho_child', jp: '前と比べて、上手くなった?', en: "Have I gotten better than before?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'riku_teen', jp: 'おう、上位、狙えるで!', en: "Yeah, you can aim for the top spots!", style: 'warm teen boy voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、絶対勝つ!', en: "Yes — I'm definitely winning!", style: 'thrilled child boy voice, bright warm determined delivery carefully' },
      { speaker: 'riku_teen', jp: 'ふふ、負けへんで!', en: "Heh, I won't lose!", style: 'bright teen boy voice, soft warm playful delivery carefully' },
    ]),
  C('conv_02357',
    'Mei watches a documentary about wildlife in India.',
    'Couple watching a documentary naturally.',
    'living_room_tv_low',
    ['インド', '面積', '数多く', '驚く'],
    ['mei_romantic', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '大ちゃん、インドの自然、すごいね。', en: "Daichi, the nature in India is amazing.", style: 'soft young wife voice, warm awed delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、面積、ようけ広いんやな。', en: "Yeah, the land area is really vast.", style: 'warm Kansai husband voice, soft warm impressed delivery carefully' },
      { speaker: 'mei_romantic', jp: '数多くの動物が、暮らしてるのね。', en: "So many animals live there.", style: 'gentle young woman voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'こんな世界、知らんかったわ。', en: "I had no idea such a world existed.", style: 'soft Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'いつか、行ってみたいね。', en: "I'd love to go someday.", style: 'tender young wife voice, soft warm hopeful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええなぁ、夢が広がるわ。', en: "That'd be wonderful — dreams keep growing.", style: 'warm Kansai husband voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02358',
    'Aoi listens to a customer\'s feedback; thanks them sincerely.',
    'Business owner receiving feedback naturally.',
    'cafe_afternoon_low',
    ['聴き', '店員', '名称', '改善'],
    ['aoi_barista', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '蒼さん、新しいメニューの名称、いいですね。', en: "Aoi, the name of the new menu item is nice.", style: 'soft young man voice, warm warm engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、お客様の声、聴きながら決めたの。', en: "Thanks — I decided by listening to customers.", style: 'gentle adult woman voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '店員さんも、丁寧に対応してくれます。', en: "The staff handle things kindly too.", style: 'warm young man voice, soft warm appreciative delivery carefully' },
      { speaker: 'aoi_barista', jp: '改善できるとこ、ようけあるけどね。', en: "There's still a lot we can improve, though.", style: 'soft adult woman voice, warm humble delivery carefully' },
      { speaker: 'ren_uni', jp: 'その姿勢が、素敵です。', en: "That attitude is wonderful.", style: 'tender young man voice, soft warm admiring delivery carefully' },
      { speaker: 'aoi_barista', jp: 'これからも、頑張るね。', en: "I'll keep working at it.", style: 'warm adult woman voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02359',
    'Hiroshi-elder reflects on how few cars there were in his youth.',
    'Elder reflecting on change naturally.',
    'porch_evening_breeze',
    ['自動車', 'かつて', '少なく', '時代'],
    ['hiroshi_elder', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'おとうさん、昔、自動車、少なかったんですか?', en: "Otosan, were there few cars back then?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、かつては、ほとんど無かったわ。', en: "Yeah, once upon a time there were almost none.", style: 'slow elder Kansai voice, warm reminiscent delivery carefully' },
      { speaker: 'sakura_teen', jp: 'みんな、歩いていたんですね。', en: "So everyone walked.", style: 'soft adult writer voice, warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'そや、静かな時代やったで。', en: "That's right — it was a quiet era.", style: 'gentle elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '時代の変化、深く感じます。', en: "I really feel how times have changed.", style: 'tender adult writer voice, soft warm reflective delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前に伝えられて、嬉しいわ。', en: "I'm glad I can pass it on to you.", style: 'warm elder Kansai voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02360',
    'Whole family gathers for a relaxed Sunday lunch.',
    'Multi-voice family meal, natural and warm.',
    'dining_room_warm',
    ['集団', '少なく', '楽しい', '家族'],
    ['naoko_aunt', 'mei_romantic', 'daichi_kansai', 'sho_child', 'hina_child', 'yumiko_mom'], 'Long (13-20)',
    [
      { speaker: 'naoko_aunt', jp: '皆、ようけ集まったなぁ!', en: "Everyone's gathered, nice and big!", style: 'brassy Kansai aunt voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '日曜のお昼、賑やかでいいね。', en: "Sunday lunch is lovely and lively.", style: 'soft young mother voice, warm warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'こういう日は、めったに少なくないな。', en: "Days like this aren't so rare lately.", style: 'warm Kansai husband voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'お料理、いっぱいだ!', en: "There's so much food!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: '皆と食べると、楽しいね。', en: "Eating with everyone is so fun.", style: 'bright teen girl voice, soft warm content delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'たくさん作ったから、召し上がれ。', en: "I made plenty, so dig in.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うちのも、食べてや!', en: "Have some of mine too!", style: 'animated Kansai aunt voice, bright warm generous delivery carefully' },
      { speaker: 'mei_romantic', jp: 'こんな家族、本当にありがたい。', en: "I'm truly grateful for a family like this.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ほんま、ええ家族や。', en: "Truly, a fine family.", style: 'warm Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '皆、大好き!', en: "I love everyone!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'こういう日が、ずっと続けばいいな。', en: "I hope days like this go on forever.", style: 'soft tender teen girl voice, warm warm wishful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'みんな、元気でいてね。', en: "Stay healthy, everyone.", style: 'tender older mother voice, soft warm enduring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ほな、いただきまーす!', en: "All right — let's eat!", style: 'brassy Kansai aunt voice, bright warm cheerful delivery carefully' },
    ]),
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_118 wrote', CONVERSATIONS.length, 'files');
