import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_129)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02561',
    'Political news: Sakura and Ren on a citizens\' petition.',
    'WIDENED SCENARIO: political news; civic vocabulary (市民/要求/首相/記者/憲法) in natural home.',
    'studio_room_tone',
    ['市民', '要求', '首相', '記者', '憲法'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '市民の団体が、署名を提出しました。', en: "A citizens' group submitted a petition.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '市民は、どんな要求をしていますか?', en: "What demands are the citizens making?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '生活費の支援を、要求しています。', en: "They demand support for living costs.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '首相は、応じる構えですか?', en: "Is the prime minister ready to respond?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '首相は、前向きに検討すると述べました。', en: "The prime minister said he'll consider it positively.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '憲法の権利とも、関わりますね。', en: "It relates to constitutional rights too.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '会見には、多くの記者が集まりました。', en: "Many reporters gathered at the briefing.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '市民の要求の行方を、見守りましょう。', en: "Let's watch where the citizens' demands go.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02562',
    'Political news: Sakura and Ren on a budget debate.',
    'WIDENED SCENARIO: political news; civic vocabulary (市民/要求/首相/記者/中央/憲法) in natural home.',
    'studio_room_tone',
    ['市民', '要求', '首相', '記者', '中央'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '中央政府が、新しい予算を示しました。', en: "The central government presented a new budget.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '市民の反応は、どうですか?', en: "What's the citizens' reaction?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '市民は、教育への投資を要求しています。', en: "Citizens demand investment in education.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '首相は、中央で説明しましたか?', en: "Did the prime minister explain it centrally?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '首相は、記者の質問に丁寧に答えました。', en: "The prime minister answered reporters carefully.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '憲法に沿った対応が、求められますね。', en: "A constitutional response is called for.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '記者たちは、続報を待っています。', en: "Reporters are awaiting further news.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '市民の要求が、中央に届くといいですね。', en: "I hope the citizens' demands reach the center.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02563',
    'Political news: Sakura and Ren on a reform bill.',
    'WIDENED SCENARIO: political news; civic vocabulary (市民/要求/首相/憲法/ただし) in natural home.',
    'studio_room_tone',
    ['市民', '要求', '首相', '憲法', 'ただし'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '首相が、改革案を発表しました。', en: "The prime minister announced a reform plan.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '市民は、その案を歓迎していますか?', en: "Do citizens welcome the plan?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '多くの市民が、賛成しています。', en: "Many citizens are in favor.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'ただし、反対の声もあるんですね?', en: "However, there are opposing voices too?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、ただし数は多くありません。', en: "Yes, however the number isn't large.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '憲法との整合性は、保たれますか?', en: "Is consistency with the constitution kept?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '首相は、憲法を尊重すると述べました。', en: "The prime minister said he'll respect the constitution.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '市民の要求と、どう折り合うかですね。', en: "The question is how to reconcile with citizens' demands.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02564',
    'History documentary: Asuka and Ren on modern Europe.',
    'WIDENED SCENARIO: history discussion; geography (イギリス/ヨーロッパ/イタリア/ロシア/アジア) in natural home.',
    'living_room_quiet',
    ['イギリス', 'ヨーロッパ', 'イタリア', 'ロシア', 'アジア'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '近代のヨーロッパは、激しく動きましたね。', en: "Modern Europe moved dramatically.", style: 'thoughtful young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、イギリスは海を越えて広がりました。', en: "Yes, Britain expanded across the seas.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'イタリアは、どんな役割でしたか?', en: "What role did Italy play?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'イタリアは、芸術と政治で影響を残しました。', en: "Italy left influence in art and politics.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'ロシアとアジアの関係は?', en: "What about Russia and Asia's ties?", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ロシアは、アジアにも広く接していました。', en: "Russia bordered Asia widely too.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'ヨーロッパとアジアは、つながっていたんですね。', en: "Europe and Asia were connected.", style: 'understanding young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'イギリスもイタリアも、世界を動かしました。', en: "Both Britain and Italy moved the world.", style: 'warm teacher voice, soft warm measured clarity closing throughout' },
    ]),

  C('conv_02565',
    'Asuka and Mei discuss European art via photos.',
    'WIDENED SCENARIO: art discussion; geography/image vocabulary (イギリス/ヨーロッパ/イタリア/ロシア/画像) in natural home.',
    'living_room_quiet',
    ['イギリス', 'ヨーロッパ', 'イタリア', 'ロシア', '画像'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この画像、ヨーロッパの古い街ですか?', en: "Is this image an old European city?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、イタリアの古都の画像ですよ。', en: "Yes, it's an image of an old Italian capital.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'mei_romantic', jp: 'イギリスの建築とは、違いますね。', en: "It differs from British architecture.", style: 'observant woman voice, gentle warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'イギリスは、石造りが多いですね。', en: "Britain has much stonework.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'mei_romantic', jp: 'ロシアの画像も、見たいです。', en: "I'd like to see images of Russia too.", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ロシアの教会は、色が鮮やかですよ。', en: "Russian churches are vividly colored.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'mei_romantic', jp: 'ヨーロッパは、国ごとに個性がありますね。', en: "Europe has character that differs by country.", style: 'moved woman voice, soft warm appreciative delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'イタリアの画像、もっとお見せしますね。', en: "I'll show you more images of Italy.", style: 'warm teacher voice, soft warm gentle closing clarity throughout' },
    ]),

  C('conv_02566',
    'Ren interviews a traveler about a Europe trip.',
    'WIDENED SCENARIO: travel interview; geography/move vocabulary (イギリス/ヨーロッパ/イタリア/ロシア/移動) in natural home.',
    'cafe_quiet_chatter',
    ['イギリス', 'ヨーロッパ', 'イタリア', 'ロシア', '移動'],
    ['ren_uni', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'ヨーロッパは、どこを回ったんですか?', en: "Where in Europe did you go?", style: 'engaged young interviewer voice, soft warm curious throughout' },
      { speaker: 'daichi_kansai', jp: 'イギリスから、イタリアまで回ったで。', en: "I went from Britain down to Italy.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'ren_uni', jp: '国の間の移動は、大変でしたか?', en: "Was moving between countries hard?", style: 'curious young interviewer voice, soft warm throughout' },
      { speaker: 'daichi_kansai', jp: '列車での移動が、楽やったわ。', en: "Traveling by train was easy.", style: 'cheerful Kansai man voice, warm friendly delivery throughout' },
      { speaker: 'ren_uni', jp: 'ロシアにも、行ったんですか?', en: "Did you go to Russia too?", style: 'engaged young interviewer voice, soft warm curious throughout' },
      { speaker: 'daichi_kansai', jp: 'ロシアは遠くて、移動が長かったなあ。', en: "Russia was far, so the travel was long.", style: 'lively Kansai man voice, warm reflective delivery throughout' },
      { speaker: 'ren_uni', jp: 'イタリアとイギリス、どちらが好きでした?', en: "Italy or Britain — which did you like?", style: 'curious young interviewer voice, soft warm throughout' },
      { speaker: 'daichi_kansai', jp: 'どっちもええわ。ヨーロッパは最高や!', en: "Both are great. Europe is the best!", style: 'cheerful Kansai man voice, warm enthusiastic closing delivery throughout' },
    ]),

  C('conv_02567',
    'Kenji and Ren design an app data model.',
    'WIDENED SCENARIO: tech design; software vocabulary (設計/モデル/画像/ファイル/ユーザー) in natural home.',
    'office_quiet_low',
    ['設計', 'モデル', '画像', 'ファイル', 'ユーザー'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'ユーザー向けの設計を、考えたいです。', en: "I want to plan the user-facing design.", style: 'earnest young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: 'まず、データのモデルを決めましょう。', en: "First, let's decide the data model.", style: 'analytical office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'ユーザーの画像も、扱いますか?', en: "Do we handle user images too?", style: 'curious young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: '画像は、ファイルとして保存します。', en: "Images are saved as files.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'ファイルは、ユーザーごとに分けますか?', en: "Do we separate files per user?", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、モデルに合わせて分けます。', en: "Yes, we separate them per the model.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'ユーザーに、優しい設計ですね。', en: "It's a user-friendly design.", style: 'satisfied young colleague voice, soft warm appreciative throughout' },
      { speaker: 'kenji_office', jp: '良いモデルは、画像の管理も楽にします。', en: "A good model eases image management too.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02568',
    'Kenji and Yuki organize project files.',
    'WIDENED SCENARIO: tech/work; file vocabulary (モデル/ファイル/画像/そのもの/トップ) in natural home.',
    'office_quiet_low',
    ['モデル', 'ファイル', '画像', 'そのもの', 'トップ'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'ファイルが、たくさんで整理できないの。', en: "There are so many files I can't organize them.", style: 'overwhelmed office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: 'トップに、フォルダを作りましょう。', en: "Let's make a folder at the top.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '画像ファイルは、別にしますか?', en: "Do we separate the image files?", style: 'attentive office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'ええ、画像はモデルごとに分けましょう。', en: "Yes, let's separate images by model.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'ファイルそのものに、名前を付けますか?', en: "Do we name the files themselves?", style: 'curious office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'ファイルそのものに、日付を入れましょう。', en: "Let's put dates in the files themselves.", style: 'measured office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'トップから、すぐ探せますね。', en: "I can find them quickly from the top.", style: 'relieved office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'モデルが整えば、管理そのものが楽です。', en: "Once the model's set, management itself is easy.", style: 'reassuring office man voice, soft warm closing throughout' },
    ]),

  C('conv_02569',
    'Kenji helps Yuki who is stuck on a login page.',
    'WIDENED SCENARIO: web help; site vocabulary (トップ/ホームページ/入る/ところが/モデル) in natural home.',
    'office_quiet_low',
    ['トップ', 'ホームページ', '入る', 'ところが', 'モデル'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'ホームページに、入れないんです。', en: "I can't get into the homepage.", style: 'puzzled office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: 'トップは、表示されていますか?', en: "Is the top page showing?", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'トップは出ます。ところが、進めなくて。', en: "The top shows. But I can't proceed.", style: 'frustrated office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: '新しいモデルの端末ですか?', en: "Is it a new-model device?", style: 'analytical office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'はい、新しいモデルに変えたばかりで。', en: "Yes, I just switched to a new model.", style: 'earnest office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'では、設定し直せば、入れますよ。', en: "Then resetting it will let you in.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '直したら、ホームページに入れました!', en: "After fixing it, I got into the homepage!", style: 'relieved office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'トップから、もう何でも使えますよ。', en: "From the top, you can use everything now.", style: 'reassuring office man voice, soft warm closing throughout' },
    ]),

  C('conv_02570',
    'Asuka lectures on regional population.',
    'WIDENED SCENARIO: demography lecture; population vocabulary (人口/中央/平均/区) in natural home.',
    'lecture_hall_quiet',
    ['人口', '中央', '平均', '区', '都市'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '都市の人口は、中央に集まりがちです。', en: "Urban populations tend to gather in the center.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '一つの区に、何人くらいいるんですか?', en: "About how many live in one ward?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '中央の区は、人口が特に多いです。', en: "Central wards have especially large populations.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '平均すると、どのくらいですか?', en: "On average, how many?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '平均で、一つの区に数万人います。', en: "On average, tens of thousands per ward.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '中央以外の区は、少ないんですか?', en: "Are non-central wards less populous?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、平均より少ない区もあります。', en: "Yes, some wards are below average.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '都市の人口の偏りが、よく分かりました。', en: "I understand the urban population imbalance well.", style: 'satisfied adult student voice, soft warm realization throughout' },
    ]),

  C('conv_02571',
    'Asuka and Mei discuss a biography.',
    'WIDENED SCENARIO: literature chat; biography vocabulary (人物/著/求める/ファン/かつ) in natural home.',
    'living_room_quiet',
    ['人物', '著', '求める', 'ファン', 'かつ'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この伝記の人物、本当に魅力的でした。', en: "The figure in this biography was truly fascinating.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: '著者は、人物像を丁寧に描いていますね。', en: "The author depicts the figure carefully.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: 'その人は、優しくかつ強かったんですね。', en: "That person was kind yet strong.", style: 'gentle woman voice, soft warm admiring delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、理想を求め続けた人物です。', en: "Yes, a figure who kept seeking ideals.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '多くのファンが、彼を慕ったんですね。', en: "Many admirers looked up to him.", style: 'warm woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'この著は、彼の手紙を基にしています。', en: "This work is based on his letters.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '私も、すっかりファンになりました。', en: "I've completely become a fan too.", style: 'delighted woman voice, soft warm bright delivery throughout' },
      { speaker: 'asuka_teacher', jp: '真実を求める姿が、心を打ちますね。', en: "His pursuit of truth is moving.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_02572',
    'Hiroshi-boss and Ren plan a spin-off venture.',
    'WIDENED SCENARIO: business strategy; competition vocabulary (コスト/競争/独立/設計/つて) in natural home.',
    'office_quiet_low',
    ['コスト', '競争', '独立', '設計', 'つて'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: 'この部門を、独立させたいと思う。', en: "I'm thinking of spinning off this division.", style: 'decisive boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '独立すれば、競争にも強くなりますね。', en: "Once independent, it'll be stronger in competition.", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'コストの設計は、できているかね?', en: "Is the cost structure designed?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '事業の設計を、見直しているところです。', en: "I'm reviewing the business design now.", style: 'reliable young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '取引先は、つてで広げられるかね?', en: "Can we expand clients through connections?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'つてを活かしつつ、新規も開拓します。', en: "We'll use connections while opening new accounts.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'コストを抑え、競争に勝とう。', en: "Let's cut costs and win the competition.", style: 'firm boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '独立に向けて、設計を固めます。', en: "Toward independence, I'll firm up the design.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_02573',
    'Daichi and Mei discuss reaching a central town.',
    'WIDENED SCENARIO: travel chat; transport vocabulary (移動/道路/整備/中央/平均) in natural home.',
    'cafe_quiet_chatter',
    ['移動', '道路', '整備', '中央', '平均'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '中央の町まで、行ってみたいなあ。', en: "I'd like to go to the central town.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '道路は、整備されているんですか?', en: "Are the roads maintained?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: '最近、道路がきれいに整備されたんよ。', en: "Recently the roads were nicely repaved.", style: 'cheerful Kansai man voice, warm friendly delivery throughout' },
      { speaker: 'mei_romantic', jp: '移動の時間は、平均でどのくらい?', en: "On average, how long is the trip?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '平均で、二時間ほどの移動やね。', en: "On average, about a two-hour trip.", style: 'lively Kansai man voice, warm informative delivery throughout' },
      { speaker: 'mei_romantic', jp: '中央まで、まっすぐ行けますか?', en: "Can we go straight to the center?", style: 'thoughtful woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '整備された道路で、中央まで一本や。', en: "On the paved road, it's straight to the center.", style: 'cheerful Kansai man voice, warm reassuring delivery throughout' },
      { speaker: 'mei_romantic', jp: '移動が楽なら、行きやすいですね。', en: "If travel's easy, it's easy to visit.", style: 'gentle woman voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02574',
    'Saito advises a patient on rest and the body.',
    'WIDENED SCENARIO: medical advice; clinical vocabulary (身体/脳/感覚/いれ/求める) in natural home.',
    'clinic_room_quiet',
    ['身体', '脳', '感覚', 'いれ', '求める'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '身体は元気なのに、頭が重いんです。', en: "My body's fine, but my head feels heavy.", style: 'tired office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '脳が、休みを求めている感覚ですね。', en: "It's the sense that your brain seeks rest.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: '身体と脳は、別なんですか?', en: "Are body and brain separate?", style: 'curious office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: 'ええ、別の感覚として現れます。', en: "Yes, they appear as different sensations.", style: 'clear doctor voice, soft warm measured clarity throughout' },
      { speaker: 'yuki_office', jp: '力を入れすぎていたかもしれません。', en: "I may have been pushing too hard.", style: 'reflective office woman voice, soft warm honest delivery throughout' },
      { speaker: 'saito_doctor', jp: '時には、力を抜く感覚も大切です。', en: "Sometimes the feeling of relaxing matters too.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: '脳に、休みを入れてあげます。', en: "I'll give my brain some rest.", style: 'understanding office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '身体が求める声を、聞いて下さいね。', en: "Please listen to what your body asks for.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_02575',
    'Incident news: Sakura and Ren on a road hazard.',
    'WIDENED SCENARIO: incident news; safety vocabulary (事故/危険/記者/中央/ところが) in natural home.',
    'studio_room_tone',
    ['事故', '危険', '記者', '中央', 'ところが'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '中央通りで、事故が起きました。', en: "An accident occurred on Central Avenue.", style: 'crisp adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '危険な場所だったんですか?', en: "Was it a dangerous spot?", style: 'measured young reporter voice, soft warm serious focus throughout' },
      { speaker: 'sakura_teen', jp: '以前から、危険が指摘されていました。', en: "Danger had been pointed out before.", style: 'clear adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '対策は、取られていたんですか?', en: "Were measures taken?", style: 'serious young reporter voice, soft warm focus throughout' },
      { speaker: 'sakura_teen', jp: 'ところが、改善が遅れていたんです。', en: "However, the improvements were delayed.", style: 'measured adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '記者として、現場を見たいですね。', en: "As a reporter, I'd like to see the scene.", style: 'earnest young reporter voice, soft warm focus throughout' },
      { speaker: 'sakura_teen', jp: '多くの記者が、中央に集まっています。', en: "Many reporters are gathering at the center.", style: 'professional adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '危険を、早く取り除くべきですね。', en: "The danger should be removed quickly.", style: 'firm young reporter voice, soft warm calm closing throughout' },
    ]),

  C('conv_02576',
    'Asuka leads a seminar comparing two arguments.',
    'WIDENED SCENARIO: seminar; analytical connectives (かつ/つて/いれ/ただし/そのもの) in natural home.',
    'lecture_hall_quiet',
    ['かつ', 'つて', 'いれ', 'ただし', 'そのもの'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '良い主張は、明確かつ誠実です。', en: "A good argument is clear and sincere.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '誠実さそのものが、大事なんですね。', en: "Sincerity itself matters.", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ただし、感情を入れすぎてもいけません。', en: "However, you mustn't pour in too much emotion.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '昔は、つてで資料を集めたとか。', en: "In the past, they gathered data through connections.", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '今は、つてに頼らず手に入れられます。', en: "Now you can obtain it without connections.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '論理そのものを、磨くべきですね。', en: "We should polish the logic itself.", style: 'understanding young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '明確かつ丁寧に、力を入れましょう。', en: "Let's put effort into being clear and polite.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'ただし、心も忘れずに、ですね。', en: "However, without forgetting the heart, right.", style: 'warm young student voice, soft warm realization throughout' },
    ]),

  C('conv_02577',
    'Sho tells Grandpa about a walk in the neighborhood.',
    'Casual home register reusing stragglers (入る/道路/ファン/とにかく/どうも) naturally.',
    'tatami_room_quiet',
    ['入る', '道路', 'ファン', 'とにかく', 'どうも'],
    ['sho_child', 'goro_grandpa'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おじいちゃん、公園に入ってきたよ!', en: "Grandpa, I went into the park!", style: 'bright small child voice, warm excited bouncing delivery throughout' },
      { speaker: 'goro_grandpa', jp: 'ほう、道路は気をつけたかね?', en: "Oh, were you careful on the road?", style: 'gravelly old man voice, soft warm gentle caring delivery throughout' },
      { speaker: 'sho_child', jp: 'うん、道路の端を歩いたよ。', en: "Yeah, I walked on the edge of the road.", style: 'proud small child voice, warm cheerful delivery throughout' },
      { speaker: 'goro_grandpa', jp: 'えらいぞ。どうも最近、車が多いからな。', en: "Good boy. Somehow there are many cars lately.", style: 'gravelly old man voice, soft warm approving delivery throughout' },
      { speaker: 'sho_child', jp: '公園で、電車のファンの子に会ったよ!', en: "In the park I met a kid who's a train fan!", style: 'excited small child voice, warm bubbly delivery throughout' },
      { speaker: 'goro_grandpa', jp: 'ほう、君も電車のファンじゃろ?', en: "Oh, you're a train fan too, aren't you?", style: 'gravelly old man voice, soft warm amused delivery throughout' },
      { speaker: 'sho_child', jp: 'とにかく、電車が大好きなんだ!', en: "Anyway, I just love trains!", style: 'enthusiastic small child voice, warm eager delivery throughout' },
      { speaker: 'goro_grandpa', jp: 'とにかく、また道路に気をつけてな。', en: "Anyway, watch the road again next time.", style: 'gravelly old man voice, soft warm caring closing delivery throughout' },
    ]),

  C('conv_02578',
    'Asuka lectures on global geography averages.',
    'WIDENED SCENARIO: geography lecture; place/stat vocabulary (ヨーロッパ/アジア/イギリス/移動/平均) in natural home.',
    'lecture_hall_quiet',
    ['ヨーロッパ', 'アジア', 'イギリス', '移動', '平均'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'ヨーロッパとアジアは、地続きです。', en: "Europe and Asia are connected by land.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'イギリスは、島国なんですよね?', en: "Britain is an island nation, right?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、イギリスは海に囲まれています。', en: "Yes, Britain is surrounded by sea.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '昔の移動は、大変だったんですか?', en: "Was travel hard in the old days?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '移動には、平均で何ヶ月もかかりました。', en: "Travel took months on average.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'アジアからヨーロッパまで、遠いですね。', en: "From Asia to Europe is far.", style: 'thoughtful teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '今は、平均で一日あれば移動できます。', en: "Now, on average, a day's enough to travel.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'ヨーロッパが、急に近く感じます。', en: "Europe suddenly feels close.", style: 'moved teen boy voice, soft warm wonder delivery throughout' },
    ]),

  C('conv_02579',
    'Kenji and Ren sort image files on a shared drive.',
    'WIDENED SCENARIO: tech/work; file vocabulary (ファイル/画像/モデル/ホームページ/トップ) in natural home.',
    'office_quiet_low',
    ['ファイル', '画像', 'モデル', 'ホームページ', 'トップ'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'ホームページ用の画像を、探しています。', en: "I'm looking for images for the homepage.", style: 'engaged young colleague voice, soft warm focused throughout' },
      { speaker: 'kenji_office', jp: '画像ファイルは、ここにまとめてあります。', en: "The image files are gathered here.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: 'トップに使う画像は、どれですか?', en: "Which image is for the top page?", style: 'curious young colleague voice, soft warm focused throughout' },
      { speaker: 'kenji_office', jp: 'この新しいモデルの画像が、トップ用です。', en: "This new-model image is for the top.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: 'ファイルの名前で、探せますか?', en: "Can I find it by file name?", style: 'engaged young colleague voice, soft warm focused throughout' },
      { speaker: 'kenji_office', jp: 'ええ、モデル名でファイルを探せます。', en: "Yes, you can find files by model name.", style: 'measured office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: 'ホームページが、見栄え良くなりそうです。', en: "The homepage should look good.", style: 'satisfied young colleague voice, soft warm appreciative throughout' },
      { speaker: 'kenji_office', jp: 'トップの画像で、印象が決まりますからね。', en: "The top image sets the impression.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02580',
    'Asuka and Mei discuss what a great essay seeks.',
    'WIDENED SCENARIO: writing discussion; connectives/abstract (ただし/いれ/かつ/求める/人物) in natural home.',
    'living_room_quiet',
    ['ただし', 'いれ', 'かつ', '求める', '人物'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '良い文章って、何を求めるんでしょう?', en: "What does good writing seek?", style: 'soft thoughtful woman voice, gentle warm curious delivery throughout' },
      { speaker: 'asuka_teacher', jp: '読者の心に、深く入ることを求めます。', en: "It seeks to enter deep into the reader's heart.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '論理的かつ、温かい文章がいいですね。', en: "Writing that's logical yet warm is nice.", style: 'gentle woman voice, soft warm engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ただし、感情を入れすぎてもいけません。', en: "However, you mustn't put in too much emotion.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '登場する人物に、心を込めたいです。', en: "I want to put heart into the characters.", style: 'warm woman voice, soft warm sincere delivery throughout' },
      { speaker: 'asuka_teacher', jp: '人物に命を入れると、物語が動きます。', en: "Putting life into characters makes the story move.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '読者が求めるのは、その命ですね。', en: "What readers seek is that life.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '明確かつ優しい文章を、目指しましょう。', en: "Let's aim for clear yet kind writing.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_129 wrote', CONVERSATIONS.length, 'files');
