import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_077)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01526',
    context: 'Hina and Sho check the weather forecast worrying about a school sports day.',
    purpose: 'Teen siblings nervously checking weather conditions.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['天気', '晴れ', '雨', '予報'],
    cast: ['hina_child', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '明日の天気、どうかな?', en: "How's tomorrow's weather?", style: 'soft teen girl voice, warm anxious hopeful inquiry delivered carefully' },
      { speaker: 'sho_child', jp: '予報、晴れって言うとった!', en: "Forecast said sunny!", style: 'bright teen boy voice, cheerful relieved warm delivery carefully' },
      { speaker: 'hina_child', jp: 'やった、運動会できる!', en: "Yay — sports day's on!", style: 'thrilled teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: '雨やったら最悪やったな。', en: "Would've been awful in the rain.", style: 'relieved teen boy voice, soft warm honest delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、明日楽しもう!', en: "Yeah — let's enjoy tomorrow!", style: 'bright teen girl voice, soft warm excited delivery carefully' },
    ],
  },
  {
    id: 'conv_01527',
    context: 'Aoi and Kenji watch a meteor shower from the porch on a clear winter night.',
    purpose: 'Adult couple sharing a quiet awe-filled moment under the sky.',
    ambient: 'porch_winter_silence',
    sound_effects: [],
    target_vocab: ['星空', '流星', '光', '宇宙'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '星空、こんなに綺麗。', en: "Such a beautiful starry sky.", style: 'soft adult woman voice, warm reverent awed delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほんま、宇宙の広さ感じるな。', en: "Really — you feel the vastness.", style: 'soft Kansai man voice, warm contemplative tender delivery carefully' },
      { speaker: 'aoi_barista', jp: 'あっ、流星!見た?', en: "Oh — a shooting star! Did you see?", style: 'excited adult woman voice, soft warm wonder delivered carefully' },
      { speaker: 'kenji_office', jp: '見た見た、ええ光やった。', en: "Yeah saw it — lovely light.", style: 'warm Kansai man voice, soft awed shared joy delivered carefully' },
      { speaker: 'aoi_barista', jp: '願い事、間に合わなかった。', en: "Couldn't make a wish in time.", style: 'soft adult woman voice, warm playful disappointment delivered carefully' },
      { speaker: 'kenji_office', jp: 'ほな、次まで考えとこ。', en: "Then — think one up by next time.", style: 'gentle Kansai voice, soft warm playful suggestion delivered carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、いい夜ね。', en: "Heh — lovely night.", style: 'tender adult woman voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_01528',
    context: 'Naoko and Sho take shelter in the ramen shop during a sudden typhoon.',
    purpose: 'Aunt protecting child during a brief storm scare.',
    ambient: 'ramen_shop_storm_rain',
    sound_effects: [],
    target_vocab: ['台風', '風', '雨', '安全'],
    cast: ['naoko_aunt', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'うわ、すごい台風や!', en: "Whoa — what a typhoon!", style: 'animated Kansai aunt voice, bright loud honest delivery carefully' },
      { speaker: 'sho_child', jp: 'おばちゃん、ちょっと怖い。', en: "Auntie — a bit scared.", style: 'soft child boy voice, warm small honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ここは安全やから、安心せえ。', en: "It's safe here — relax.", style: 'brassy Kansai aunt voice, bright firm protective delivery carefully' },
      { speaker: 'sho_child', jp: '風と雨、すごいね。', en: "Wind and rain — wild.", style: 'soft child boy voice, warm awed honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: '温いラーメン作ったるで、待ち!', en: "I'll make hot ramen — wait!", style: 'warm Kansai aunt voice, bright loud loving delivery carefully' },
    ],
  },
  {
    id: 'conv_01529',
    context: 'Yumiko and Mei talk softly about the rainy season starting.',
    purpose: 'Two generations of women on seasonal change.',
    ambient: 'porch_rain_steady',
    sound_effects: [],
    target_vocab: ['梅雨', '湿気', '空気', '季節'],
    cast: ['yumiko_mom', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'もう梅雨入りね。', en: "Already the rainy season.", style: 'soft older mother voice, warm contemplative seasonal delivery carefully' },
      { speaker: 'mei_romantic', jp: '湿気、苦手だなぁ。', en: "I'm not great with humidity.", style: 'soft young woman voice, warm honest gentle complaint delivered carefully' },
      { speaker: 'yumiko_mom', jp: '空気、重く感じるわね。', en: "The air feels heavy.", style: 'gentle older mother voice, soft warm understanding delivery carefully' },
      { speaker: 'mei_romantic', jp: '紫陽花、咲いてきますね。', en: "Hydrangeas are starting to bloom.", style: 'soft young woman voice, warm seasonal appreciation delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'それは、季節の楽しみよ。', en: "That's the joy of the season.", style: 'warm older mother voice, soft wise content delivery carefully' },
    ],
  },
  {
    id: 'conv_01530',
    context: 'Saito and Asuka discuss an earthquake drill at the school.',
    purpose: 'Two professionals coordinating community safety education.',
    ambient: 'school_hall_quiet',
    sound_effects: [],
    target_vocab: ['地震', '避難', '訓練', '安全'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '地震訓練、来週の予定です。', en: "Earthquake drill scheduled next week.", style: 'composed teacher voice, soft professional clear delivery carefully' },
      { speaker: 'saito_doctor', jp: 'いいですね、避難経路の確認も。', en: "Good — check evacuation routes too.", style: 'measured doctor voice, soft professional advice delivered carefully' },
      { speaker: 'asuka_teacher', jp: '保健室の準備、お願いできますか?', en: "Could you ready the nurse's room?", style: 'polite teacher voice, soft professional request delivered carefully' },
      { speaker: 'saito_doctor', jp: 'もちろん、必要な物揃えます。', en: "Of course — I'll gather supplies.", style: 'warm doctor voice, soft committed professional delivery carefully' },
      { speaker: 'asuka_teacher', jp: '生徒の安全が、第一ですね。', en: "Student safety comes first.", style: 'soft teacher voice, warm serious professional delivery carefully' },
      { speaker: 'saito_doctor', jp: 'はい、共に取り組みましょう。', en: "Yes — let's work on it together.", style: 'warm doctor voice, soft collaborative professional delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'よろしくお願いします。', en: "Thank you.", style: 'gracious teacher voice, soft formal sincere delivery carefully' },
    ],
  },
  {
    id: 'conv_01531',
    context: 'Hiroshi-boss attends a local concert with his old friend Goro-grandpa.',
    purpose: 'Two older men admiring music together; nostalgic camaraderie.',
    ambient: 'concert_hall_warm',
    sound_effects: [],
    target_vocab: ['音楽', '演奏', '感動', '拍手'],
    cast: ['hiroshi_boss', 'goro_grandpa'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'goro_grandpa', jp: 'ええ演奏やったなぁ。', en: "Fine performance.", style: 'gentle elder voice, soft warm appreciative delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ええ、本当に感動しました。', en: "Yes — truly moved.", style: 'warm boss voice, soft sincere reverent delivery carefully' },
      { speaker: 'goro_grandpa', jp: '若い人の音楽、新鮮やわ。', en: "Young people's music — fresh.", style: 'soft elder voice, warm fond reflective delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '拍手が、長く続きましたね。', en: "Applause lasted long.", style: 'gentle boss voice, soft warm fond observation delivered carefully' },
      { speaker: 'goro_grandpa', jp: 'お客さんも、満足してた。', en: "Audience seemed satisfied too.", style: 'warm elder voice, soft observant content delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '次回も、一緒に来ましょう。', en: "Let's come again together.", style: 'warm boss voice, soft friendly fond delivery carefully' },
      { speaker: 'goro_grandpa', jp: 'ふふ、ええなぁ。', en: "Heh — sounds good.", style: 'gentle elder voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_01532',
    context: 'Ren and Sakura work on a small play script for a charity event.',
    purpose: 'Two writers collaborating on dramatic structure.',
    ambient: 'studio_evening_papers',
    sound_effects: [],
    target_vocab: ['台本', '役', '舞台', '稽古'],
    cast: ['ren_uni', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '台本の流れ、もう少し練ろう。', en: "Let's refine the script flow.", style: 'thoughtful adult writer voice, soft warm collaborative delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、ここの役、もう少し深く。', en: "Yes — this role, deeper.", style: 'soft young man voice, warm engaged thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '舞台での動き、想像できる?', en: "Can you picture the stage movement?", style: 'curious adult writer voice, soft warm collaborative inquiry delivered carefully' },
      { speaker: 'ren_uni', jp: 'ええ、稽古しながら見えてきます。', en: "Yes — it comes clear through rehearsal.", style: 'soft young man voice, warm thoughtful patient delivery carefully' },
      { speaker: 'sakura_teen', jp: '今回の演出家、若いんでしょ?', en: "The director this time — young?", style: 'engaged adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、情熱がすごいです。', en: "Yes — full of passion.", style: 'soft young man voice, warm admiring delivery carefully' },
      { speaker: 'sakura_teen', jp: 'いい作品になりそうね。', en: "Sounds like a fine work.", style: 'warm adult writer voice, soft hopeful confident delivery carefully' },
    ],
  },
  {
    id: 'conv_01533',
    context: 'Daichi and Mei watch their kids practicing for a school singing event.',
    purpose: 'Parents fondly observing a child rehearsal.',
    ambient: 'school_hall_practice',
    sound_effects: [],
    target_vocab: ['歌う', '合唱', '声', '練習'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'みんな、上手に歌うね。', en: "They all sing well.", style: 'tender young mother voice, soft warm proud delivery carefully' },
      { speaker: 'daichi_kansai', jp: '合唱、ええ響きや。', en: "Choir — lovely resonance.", style: 'warm Kansai father voice, soft proud appreciative delivery carefully' },
      { speaker: 'mei_romantic', jp: '声が揃ってる、素敵。', en: "Voices in unison — lovely.", style: 'soft young woman voice, warm fond observation delivery carefully' },
      { speaker: 'daichi_kansai', jp: '練習、頑張ってきたんやな。', en: "They've been practising hard.", style: 'soft Kansai father voice, warm proud paternal delivery carefully' },
      { speaker: 'mei_romantic', jp: '本番が楽しみね。', en: "Looking forward to the show.", style: 'tender young mother voice, soft warm hopeful delivery carefully' },
    ],
  },
  {
    id: 'conv_01534',
    context: 'Yuki-office and Asuka catch a small art exhibit on a Saturday afternoon.',
    purpose: 'Two female friends enjoying culture together casually.',
    ambient: 'gallery_quiet_floor',
    sound_effects: [],
    target_vocab: ['美術', '展示', '作品', '芸術'],
    cast: ['yuki_office', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'この展示、評判ですよ。', en: "This exhibit's well-rated.", style: 'gentle teacher voice, soft warm informative delivery carefully' },
      { speaker: 'yuki_office', jp: 'うん、作品ごとに個性ある。', en: "Yeah — each work has character.", style: 'soft office woman voice, warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '芸術、心に響くね。', en: "Art moves the heart.", style: 'soft teacher voice, warm reflective delivery carefully' },
      { speaker: 'yuki_office', jp: 'ほんと、来てよかった。', en: "Truly — glad we came.", style: 'gentle office woman voice, soft warm grateful delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'お茶でもしましょうか。', en: "Let's go for tea?", style: 'warm teacher voice, soft friendly suggestion delivered carefully' },
    ],
  },
  {
    id: 'conv_01535',
    context: 'Sakura and Hina watch a rainbow after rain; tender mentor moment.',
    purpose: 'Adult writer sharing simple joy with teen mentee.',
    ambient: 'porch_after_rain',
    sound_effects: [],
    target_vocab: ['虹', '空', '雨', '美しい'],
    cast: ['sakura_teen', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、虹!', en: "Sakura — a rainbow!", style: 'thrilled teen girl voice, bright cheerful warm delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、本当に美しい。', en: "Oh — truly beautiful.", style: 'soft adult writer voice, warm awed delivery carefully' },
      { speaker: 'hina_child', jp: '雨上がりだから、見られた。', en: "Saw it because of the rain.", style: 'soft teen girl voice, warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '空、すっかり晴れたね。', en: "The sky's fully clear.", style: 'gentle adult writer voice, soft warm reflective delivery carefully' },
      { speaker: 'hina_child', jp: '写真、撮ろうかな。', en: "Maybe I'll take a photo.", style: 'soft teen girl voice, warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01536',
    context: 'Kenji and Ren go to the music store; Kenji buys a small guitar.',
    purpose: 'Mentor and protégé shopping for an instrument.',
    ambient: 'music_store_quiet',
    sound_effects: [],
    target_vocab: ['楽器', 'ギター', '音色', '弾く'],
    cast: ['kenji_office', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: 'このギターの音色、ええなぁ。', en: "This guitar sounds lovely.", style: 'soft Kansai man voice, warm appreciative delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、温かい音ですね。', en: "Yes — warm tone.", style: 'soft young man voice, warm agreeing observation delivered carefully' },
      { speaker: 'kenji_office', jp: 'もう一回、弾いてみよか。', en: "Let me try it again.", style: 'gentle Kansai voice, soft warm focused delivery carefully' },
      { speaker: 'ren_uni', jp: '健司さん、上手ですね。', en: "Kenji-san — you're good.", style: 'soft young man voice, warm admiring sincere delivery carefully' },
      { speaker: 'kenji_office', jp: 'ぼちぼちや、趣味やから。', en: "So-so — it's a hobby.", style: 'warm Kansai man voice, soft humble modest delivery carefully' },
      { speaker: 'ren_uni', jp: '楽器、買うんですか?', en: "Buying the instrument?", style: 'curious young man voice, soft warm inquiry delivered carefully' },
      { speaker: 'kenji_office', jp: 'うん、これに決めた。', en: "Yeah — decided on this.", style: 'soft Kansai man voice, warm content decisive delivery carefully' },
    ],
  },
  {
    id: 'conv_01537',
    context: 'Tatsuya-country and Hiroshi-elder talk about good harvest and bad years.',
    purpose: 'Two old men reflecting on farming life and patience.',
    ambient: 'porch_afternoon_breeze',
    sound_effects: [],
    target_vocab: ['収穫', '田んぼ', '実る', '感謝'],
    cast: ['tatsuya_country', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '今年、ようけ実ったわ。', en: "Good harvest this year.", style: 'slow Tohoku voice, soft warm satisfied delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええなぁ、お米はどうや?', en: "Lovely — how's the rice?", style: 'gentle elder Kansai voice, soft warm curious delivery carefully' },
      { speaker: 'tatsuya_country', jp: '艶がええ、味も濃い。', en: "Nice sheen — rich flavor too.", style: 'proud Tohoku farmer voice, soft warm modest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '田んぼ、丹精込めて。', en: "Tended with care.", style: 'soft elder Kansai voice, warm appreciative delivery carefully' },
      { speaker: 'tatsuya_country', jp: '自然に、感謝やな。', en: "Gratitude to nature.", style: 'gentle Tohoku voice, soft warm reverent delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、その通りや。', en: "Truly — exactly so.", style: 'warm elder Kansai voice, soft wise agreement delivered carefully' },
      { speaker: 'tatsuya_country', jp: 'また、来年も頑張る。', en: "Next year too — I'll keep at it.", style: 'soft Tohoku voice, warm resolved gentle delivery carefully' },
    ],
  },
  {
    id: 'conv_01538',
    context: 'Hina-young afraid of thunder during a small storm; Sachiko-grandma comforts her.',
    purpose: 'Elder soothing a frightened child.',
    ambient: 'bedroom_storm_distant',
    sound_effects: [],
    target_vocab: ['雷', '怖い', '布団', '安心'],
    cast: ['sachiko_grandma', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、雷怖い!', en: "Grandma — thunder's scary!", style: 'soft scared teen girl voice, warm small honest delivery carefully' },
      { speaker: 'sachiko_grandma', jp: '大丈夫、ここにおるよ。', en: "It's okay — I'm here.", style: 'warm grandmother voice, soft tender protective delivery carefully' },
      { speaker: 'hina_child', jp: '布団、一緒に入ってもいい?', en: "Can I get under the futon with you?", style: 'soft teen girl voice, warm hopeful small delivery carefully' },
      { speaker: 'sachiko_grandma', jp: 'うん、おいで、安心せえ。', en: "Yes — come, ease your mind.", style: 'gentle grandmother voice, soft warm loving delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがと、おばあちゃん。', en: "Thanks — Grandma.", style: 'soft sleepy teen girl voice, warm grateful peaceful delivery carefully' },
    ],
  },
  {
    id: 'conv_01539',
    context: 'Takeda-officer briefs Daichi on neighborhood safety after a small incident.',
    purpose: 'Officer informing resident professionally about local awareness.',
    ambient: 'street_evening_quiet',
    sound_effects: [],
    target_vocab: ['警察', '注意', '近所', '事件'],
    cast: ['takeda_officer', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'takeda_officer', jp: '最近、近所で小さい事件が。', en: "Recently a small incident nearby.", style: 'measured officer voice, soft professional clear delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'え、何があったんですか?', en: "Oh — what happened?", style: 'concerned Kansai man voice, soft warm honest inquiry delivered carefully' },
      { speaker: 'takeda_officer', jp: '空き巣ですね、注意してください。', en: "A break-in — please be cautious.", style: 'professional officer voice, soft serious clear delivery carefully' },
      { speaker: 'daichi_kansai', jp: '了解しました、戸締まり気をつけます。', en: "Understood — I'll lock up well.", style: 'soft Kansai man voice, warm respectful careful delivery carefully' },
      { speaker: 'takeda_officer', jp: '何かあれば、すぐ連絡を。', en: "If anything happens — call right away.", style: 'firm officer voice, soft professional reassuring delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'はい、ありがとうございます。', en: "Yes — thank you.", style: 'polite Kansai man voice, soft warm grateful delivery carefully' },
      { speaker: 'takeda_officer', jp: '失礼します。', en: "Excuse me.", style: 'composed officer voice, soft formal courteous delivery carefully' },
    ],
  },
  {
    id: 'conv_01540',
    context: 'Sho-young learns to swim; Saito watches from the pool side.',
    purpose: 'Adult mentoring child overcoming fear in water.',
    ambient: 'pool_low_echo',
    sound_effects: [],
    target_vocab: ['泳ぐ', 'プール', '息', '頑張る'],
    cast: ['saito_doctor', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '先生、泳げない!', en: "Doctor — I can't swim!", style: 'panicky child boy voice, soft warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '焦らず、息整えて。', en: "Don't rush — steady your breath.", style: 'calm doctor voice, soft warm patient delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、頑張る!', en: "Yeah — I'll try!", style: 'soft determined child boy voice, warm brave delivery carefully' },
      { speaker: 'saito_doctor', jp: 'いいね、ゆっくり進んで。', en: "Good — go slowly.", style: 'gentle doctor voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'できた、泳げた!', en: "I did it — I swam!", style: 'thrilled child boy voice, bright cheerful proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01541',
    context: 'Mei talks tenderly with Naoko about feeling overwhelmed in motherhood.',
    purpose: 'Younger woman seeking emotional support from older relative.',
    ambient: 'kitchen_evening_low',
    sound_effects: [],
    target_vocab: ['育児', '疲れる', '相談', '応援'],
    cast: ['mei_romantic', 'naoko_aunt'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'おばさん、最近育児で疲れてて。', en: "Auntie — tired from child-rearing lately.", style: 'soft young mother voice, warm honest vulnerable delivery carefully' },
      { speaker: 'naoko_aunt', jp: '当たり前や、ようやってる。', en: "Of course — you're doing well.", style: 'warm Kansai aunt voice, bright firm loving delivery carefully' },
      { speaker: 'mei_romantic', jp: '相談したくて、来たの。', en: "Came to talk it through.", style: 'soft young woman voice, warm honest grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'なんでも言うてみ、聞くで。', en: "Say anything — I'll listen.", style: 'animated Kansai aunt voice, bright loud caring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'たまに、自分が消えそうで。', en: "Sometimes I feel I'll disappear.", style: 'soft young mother voice, warm raw honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お母さんだけが、お前やない。', en: "You're not only a mother.", style: 'tender Kansai aunt voice, soft warm wise loving delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、心が軽くなった。', en: "Thanks — feels lighter.", style: 'soft young woman voice, warm tender grateful relief delivered carefully' },
      { speaker: 'naoko_aunt', jp: 'いつでも、来てええで。', en: "Come anytime.", style: 'warm Kansai aunt voice, bright loud loving delivery carefully' },
    ],
  },
  {
    id: 'conv_01542',
    context: 'Aoi takes Sho-young to a small puppet show at a community center.',
    purpose: 'Adult and child enjoying simple cultural outing.',
    ambient: 'community_hall_warm',
    sound_effects: [],
    target_vocab: ['人形', '舞台', '面白い', '笑う'],
    cast: ['aoi_barista', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '蒼さん、人形動いてる!', en: "Aoi — the puppets move!", style: 'thrilled child boy voice, bright cheerful awed delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、上手に操ってるね。', en: "Yeah — handled skillfully.", style: 'soft adult woman voice, warm fond observation delivered carefully' },
      { speaker: 'sho_child', jp: 'すごく面白い!', en: "Super fun!", style: 'excited child boy voice, bright warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '笑い声、ええね。', en: "Your laugh is lovely.", style: 'tender adult woman voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'また来たい!', en: "Want to come again!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01543',
    context: 'Sakura attends Ren\'s small piano recital at the music school.',
    purpose: 'Author admiring her friend\'s amateur musical achievement.',
    ambient: 'recital_hall_warm',
    sound_effects: [],
    target_vocab: ['ピアノ', '演奏', '指', '緊張'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、緊張してる?', en: "Ren — nervous?", style: 'gentle adult writer voice, soft warm caring inquiry delivered carefully' },
      { speaker: 'ren_uni', jp: 'はい、指、震えてます。', en: "Yes — fingers trembling.", style: 'soft young man voice, warm honest vulnerable delivery carefully' },
      { speaker: 'sakura_teen', jp: '深呼吸、ゆっくりね。', en: "Deep breaths — slow.", style: 'tender adult writer voice, soft warm encouraging delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、頑張ります。', en: "Yes — I'll do my best.", style: 'soft young man voice, warm determined humble delivery carefully' },
      { speaker: 'sakura_teen', jp: '私、ずっと聴いてるから。', en: "I'll be listening throughout.", style: 'warm adult writer voice, soft loyal supportive delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble young man voice, soft warm sincere delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うまくいくよ、信じてる。', en: "It'll go well — I believe.", style: 'tender adult writer voice, soft warm steadfast delivery carefully' },
    ],
  },
  {
    id: 'conv_01544',
    context: 'Kenji and Daichi help Hiroshi-elder move firewood in late autumn.',
    purpose: 'Three men sharing simple physical labor warmly.',
    ambient: 'yard_autumn_breeze',
    sound_effects: [],
    target_vocab: ['秋', '薪', '運ぶ', '寒い'],
    cast: ['kenji_office', 'daichi_kansai', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '今年も寒くなってきたな。', en: "Cold's setting in this year too.", style: 'slow elder Kansai voice, warm weathered reflective delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ほんま、薪助かりますわ。', en: "Truly — firewood's a help.", style: 'warm Kansai man voice, soft humble grateful delivery carefully' },
      { speaker: 'kenji_office', jp: 'これくらい、運ぶで。', en: "I'll carry this much.", style: 'soft Kansai artist voice, warm helpful steady delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おまえらおったら、心強いわ。', en: "With you two — I'm encouraged.", style: 'gentle elder Kansai voice, soft warm fatherly delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'いつでも、頼ってくださいな。', en: "Lean on us anytime.", style: 'warm Kansai husband voice, soft sincere loyal delivery carefully' },
      { speaker: 'kenji_office', jp: '冬の準備、ばっちりや。', en: "Winter prep — perfect.", style: 'soft Kansai man voice, warm content cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ふふ、ありがたいことや。', en: "Heh — what a blessing.", style: 'warm elder Kansai voice, soft humble grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01545',
    context: 'Yumiko and Mrs. Mori at a tea group; reminiscing about old neighborhood.',
    purpose: 'Two older women bonding over shared local history.',
    ambient: 'tea_room_quiet',
    sound_effects: [],
    target_vocab: ['昔', '町', '変わる', '思い出'],
    cast: ['yumiko_mom', 'mrs_mori_neighbor'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'この町、変わったわね。', en: "This town's changed.", style: 'soft older neighbor voice, warm reflective delivery carefully' },
      { speaker: 'yumiko_mom', jp: '本当に、昔と全然違う。', en: "Truly — wholly different from before.", style: 'gentle older mother voice, soft warm fond nostalgic delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'でも、人は変わらないわ。', en: "But people don't change.", style: 'warm older woman voice, soft wise observational delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、それが嬉しい。', en: "Yes — that's the joy.", style: 'tender older mother voice, soft warm content delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '思い出、たくさんあるね。', en: "So many memories.", style: 'soft older neighbor voice, warm fond reflective delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'これからも、増やしていきましょ。', en: "Let's add more going forward.", style: 'warm older mother voice, soft hopeful loving delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ええ、よろしくね。', en: "Yes — looking forward.", style: 'gentle older woman voice, soft warm friendly delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_077 wrote', CONVERSATIONS.length, 'files');
