import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_104)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02061',
    context: 'Hina-young updates her online profile registration; help from Mei.',
    purpose: 'Mother helping teen with profile administration.',
    ambient: 'home_office_quiet',
    sound_effects: [],
    target_vocab: ['登録', '更新', 'サイト', 'メール', '良く', '最終', '確認', '正確'],
    cast: ['mei_romantic', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、登録、更新したいの。', en: "Mei — registration, want update.", style: 'soft teen girl voice, warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'サイトに、メール入力した?', en: "Site to — email input?", style: 'gentle young woman voice, soft warm helpful delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、最終確認、お願いします。', en: "Yes — final check, please.", style: 'composed teen girl voice, soft warm respectful delivery carefully' },
      { speaker: 'mei_romantic', jp: '良く書けてる、正確ね。', en: "Well written — accurate.", style: 'tender young woman voice, soft warm approving delivery carefully' },
      { speaker: 'hina_child', jp: '間違い、ないかな?', en: "Mistake — none?", style: 'soft worried teen girl voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、送信、しよう。', en: "Yeah — send.", style: 'warm young woman voice, soft warm decisive delivery carefully' },
    ],
  },
  {
    id: 'conv_02062',
    context: 'Sho-young and Sakura visit a shrine; small ritual moment.',
    purpose: 'Adult and child sharing spiritual outing.',
    ambient: 'shrine_grounds_quiet',
    sound_effects: [],
    target_vocab: ['神', '神社', '祈り', '千', '万', '願い', '心', 'お参り'],
    cast: ['sakura_teen', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'さくらさん、神社、大きい!', en: "Sakura — shrine, big!", style: 'awed child boy voice, bright warm delivery carefully' },
      { speaker: 'sakura_teen', jp: '神様、祈り、しっかり伝えてね。', en: "God — prayer, properly convey.", style: 'gentle adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'sho_child', jp: '千円、お賽銭、入れていい?', en: "1000 yen — offering, put okay?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '気持ち、大事よ、金額じゃない。', en: "Heart — matters, not amount.", style: 'tender adult writer voice, soft warm wise delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、心、こめて、お参りする!', en: "Yeah — heart, put, visit!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02063',
    context: 'Saito reads a survey result; discusses with Asuka.',
    purpose: 'Two professionals reviewing community data.',
    ambient: 'office_papers_low',
    sound_effects: [],
    target_vocab: ['調査', '事件', '多く', '結果', '環境', '医療', 'とても', '影響'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '今回の調査、ようけの事例があります。', en: "This survey — many cases exist.", style: 'measured doctor voice, soft professional delivery carefully' },
      { speaker: 'asuka_teacher', jp: '結果、多くの人に影響しますね。', en: "Result — many people affect.", style: 'gentle teacher voice, soft warm thoughtful delivery carefully' },
      { speaker: 'saito_doctor', jp: '環境医療、とても重要な分野です。', en: "Environmental medicine — very important field.", style: 'soft doctor voice, warm warm professional delivery carefully' },
      { speaker: 'asuka_teacher', jp: '事件も、いくつか、報告に上がってる。', en: "Incidents — several, in report.", style: 'composed teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'saito_doctor', jp: '対応、社会全体で考えるべき。', en: "Response — society-wide should think.", style: 'firm doctor voice, soft warm committed delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'こうやって、議論を続けるのが大事ね。', en: "Like this — debate continue matters.", style: 'tender teacher voice, soft warm philosophical delivery carefully' },
      { speaker: 'saito_doctor', jp: 'はい、一緒に、取り組みましょう。', en: "Yes — together, tackle.", style: 'warm doctor voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02064',
    context: 'Yuki-office helps Kenji with a financial calculation; office work.',
    purpose: 'Two adults working through numbers professionally.',
    ambient: 'office_calculator_low',
    sound_effects: [],
    target_vocab: ['負担', '逆', 'もらい', 'カード', '実験', '明確', '計算', '正確'],
    cast: ['yuki_office', 'kenji_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: '健司さん、この負担、計算、合いますか?', en: "Kenji — this burden, calc, match?", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: '逆に、もう一度、確認したい。', en: "Reverse — once more, want verify.", style: 'soft Kansai man voice, warm warm focused delivery carefully' },
      { speaker: 'yuki_office', jp: 'カード、領収書からもらいました。', en: "Card — receipt from received.", style: 'gentle office woman voice, soft warm helpful delivery carefully' },
      { speaker: 'kenji_office', jp: '実験的に、新しいシステム、試そうか?', en: "Experimental — new system, try?", style: 'engaged Kansai man voice, soft warm strategic delivery carefully' },
      { speaker: 'yuki_office', jp: '明確な指示、ありがとうございます。', en: "Clear direction — thanks.", style: 'humble office woman voice, soft warm grateful delivery carefully' },
      { speaker: 'kenji_office', jp: '正確な計算、皆、頼ってる。', en: "Accurate calc — all, rely.", style: 'warm Kansai man voice, soft warm reassuring delivery carefully' },
      { speaker: 'yuki_office', jp: '頑張ります、本当に!', en: "Try — truly!", style: 'bright office woman voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02065',
    context: 'Mei observes Hina-young\'s study; talks about study habits.',
    purpose: 'Mother offering teen academic perspective.',
    ambient: 'study_room_evening',
    sound_effects: [],
    target_vocab: ['視点', '効率', '分かっ', '画面', '習慣', '集中', 'なきゃ', '半分'],
    cast: ['mei_romantic', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'ひな、勉強、効率いい?', en: "Hina — study, efficient?", style: 'gentle young mother voice, soft warm caring delivery carefully' },
      { speaker: 'hina_child', jp: '画面ばかりで、集中、難しい。', en: "Screen only — focus, hard.", style: 'soft tired teen girl voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '視点、変えると、いいかも。', en: "Viewpoint — change, maybe good.", style: 'warm young mother voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '半分、紙に書いて、進めるべき?', en: "Half — paper write, proceed should?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、習慣つくと、楽になる。', en: "Yeah — habit forms, easier.", style: 'tender young mother voice, soft warm wise delivery carefully' },
      { speaker: 'hina_child', jp: '分かった、頑張らなきゃ。', en: "Got — must try.", style: 'soft determined teen girl voice, warm gentle resolve delivered carefully' },
      { speaker: 'mei_romantic', jp: 'ゆっくり、ね。', en: "Slowly — yeah.", style: 'soft young mother voice, warm warm caring delivery carefully' },
    ],
  },
  {
    id: 'conv_02066',
    context: 'Naoko gossips with Mrs. Mori about the neighborhood cats.',
    purpose: 'Two older women in light neighborhood chatter.',
    ambient: 'porch_afternoon_birds',
    sound_effects: [],
    target_vocab: ['猫', '住ん', '母親', '可愛い', '世話', 'たまに', '近所', '見れ'],
    cast: ['naoko_aunt', 'mrs_mori_neighbor'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '近所の猫、母親、ようけ子猫世話しとるな。', en: "Neighborhood cat — mom, much kittens care.", style: 'warm Kansai aunt voice, soft warm fond delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '可愛いわね、見れて、嬉しい。', en: "Cute — see, happy.", style: 'gentle older neighbor voice, soft warm delighted delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'たまに、うちの店、住んでるみたいや。', en: "Sometimes — shop, living-like.", style: 'soft Kansai aunt voice, warm fond delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '世話、皆で見守ってるね。', en: "Care — all watching.", style: 'tender older neighbor voice, soft warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、地域の宝物や、本当に。', en: "Heh — community treasure, truly.", style: 'warm Kansai aunt voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02067',
    context: 'Hina-young arrives at port for boat trip; chats about travel arrival.',
    purpose: 'Teen on practical travel logistics.',
    ambient: 'port_terminal_low',
    sound_effects: [],
    target_vocab: ['船', '到着', '出発', '北海道', 'なきゃ', '時間', '安心', '確認'],
    cast: ['hina_child', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、船、北海道行き、確認できた?', en: "Mei — boat, Hokkaido bound, verified?", style: 'composed teen girl voice, soft warm focused delivery carefully' },
      { speaker: 'mei_romantic', jp: '出発、十時、間に合わなきゃ。', en: "Departure — ten, must make.", style: 'soft young woman voice, warm warm careful delivery carefully' },
      { speaker: 'hina_child', jp: '時間、ぎりぎりだね。', en: "Time — tight.", style: 'nervous teen girl voice, soft warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '到着、夕方になるかな。', en: "Arrival — evening become.", style: 'gentle young woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'hina_child', jp: '荷物、ちゃんと持った、安心。', en: "Bags — properly held, relief.", style: 'soft relieved teen girl voice, warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '船、揺れるかしら?', en: "Boat — sway?", style: 'soft young woman voice, warm warm cautious delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、楽しみだけど、ちょっと不安。', en: "Yeah — looking forward but, bit anxious.", style: 'tender teen girl voice, soft warm honest delivery carefully' },
    ],
  },
  {
    id: 'conv_02068',
    context: 'Sho-young learns to play guitar from Ren in the cafe.',
    purpose: 'Adult mentor teaching child music basics.',
    ambient: 'cafe_evening_low',
    sound_effects: [],
    target_vocab: ['ギター', '弾', '練習', '指', '音', '玉', '曲', '繰り返し'],
    cast: ['ren_uni', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '蓮にいちゃん、ギター、教えて!', en: "Ren — guitar, teach!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'ren_uni', jp: 'まず、指、ここに置いて。', en: "First — finger, here place.", style: 'soft young man voice, warm warm patient delivery carefully' },
      { speaker: 'sho_child', jp: '弾、強く、押さえる?', en: "Pluck — strong, hold?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: 'うん、優しく、音、出してみて。', en: "Yeah — gently, sound, try out.", style: 'gentle young man voice, soft warm instructional delivery carefully' },
      { speaker: 'sho_child', jp: '玉みたいな音、出た!', en: "Ball-like sound — came!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'ren_uni', jp: '練習、繰り返しが大事。', en: "Practice — repetition matters.", style: 'soft young man voice, warm warm wise delivery carefully' },
      { speaker: 'sho_child', jp: '毎日、曲、弾けるように頑張る!', en: "Daily — songs, can play try!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02069',
    context: 'Kenji and Aoi order Italian wine at a restaurant; couples evening.',
    purpose: 'Couple sharing intimate dinner moment.',
    ambient: 'restaurant_warm_lamp',
    sound_effects: [],
    target_vocab: ['ワイン', 'ビール', 'メニュー', '注文', '雰囲気', '本格', '味', '満足'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、ワインかビール、どっち?', en: "Ken-chan — wine or beer, which?", style: 'soft adult woman voice, warm warm curious delivery carefully' },
      { speaker: 'kenji_office', jp: 'ワインにしよ、本格的なやつ。', en: "Wine pick — authentic kind.", style: 'warm Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: 'メニュー、見せてもらおうか。', en: "Menu — let's see.", style: 'gentle adult woman voice, soft warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: 'お店の雰囲気、ええなぁ。', en: "Restaurant mood — lovely.", style: 'soft Kansai man voice, warm warm appreciative delivery carefully' },
      { speaker: 'aoi_barista', jp: '注文、これと、これにする?', en: "Order — this, this make?", style: 'soft adult woman voice, warm warm decisive delivery carefully' },
      { speaker: 'kenji_office', jp: '味、楽しみやな。', en: "Flavor — looking forward.", style: 'warm Kansai husband voice, soft warm anticipating delivery carefully' },
      { speaker: 'aoi_barista', jp: '満足、できる夜になりそう。', en: "Satisfaction — possible night.", style: 'tender adult woman voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_02070',
    context: 'Saito explains a surgery to a patient using clear terms.',
    purpose: 'Doctor reassuring patient about medical procedure.',
    ambient: 'clinic_room_quiet',
    sound_effects: [],
    target_vocab: ['手術', '症', '治療', '血液', '確認', '安心', '原稿', '書類'],
    cast: ['saito_doctor', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '先生、手術、不安です。', en: "Doctor — surgery, anxious.", style: 'soft worried adult writer voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '心配いりません、安心して。', en: "No worry — relax.", style: 'measured doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'sakura_teen', jp: '症状、治療で良くなりますか?', en: "Symptoms — treatment improve?", style: 'gentle adult writer voice, soft warm hopeful delivery carefully' },
      { speaker: 'saito_doctor', jp: '血液検査、結果、確認しました。', en: "Blood test — result, verified.", style: 'soft doctor voice, warm warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '書類、これで揃いますか?', en: "Documents — these gather?", style: 'composed adult writer voice, soft warm careful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'はい、原稿、揃ってます。', en: "Yes — manuscript, gathered.", style: 'gentle doctor voice, soft warm clear delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとうございます、本当に。', en: "Thank you — truly.", style: 'humble adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02071',
    context: 'Daichi runs a marathon training session; tells Mei after.',
    purpose: 'Athletic husband reports to supportive wife.',
    ambient: 'home_evening_warm',
    sound_effects: [],
    target_vocab: ['走る', '走っ', '汗', '時間', '半分', '到着', '目指し', '勝負'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、今日、半分、走り切った!', en: "Mei — today, half, finished!", style: 'breathless Kansai husband voice, bright warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、汗、ようけかいたね。', en: "Oh — sweat, much.", style: 'tender young wife voice, soft warm fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: '時間、もう少しで、目指してた到着。', en: "Time — bit more, targeted arrival.", style: 'soft Kansai husband voice, warm warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '勝負、本番、もうすぐね。', en: "Match — real, soon.", style: 'soft young woman voice, warm warm encouraging delivery carefully' },
      { speaker: 'daichi_kansai', jp: '走るの、楽しいわ、最近。', en: "Running — fun, lately.", style: 'warm Kansai husband voice, soft warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '応援、ずっとしてるよ。', en: "Cheering — always.", style: 'tender young wife voice, soft warm steadfast delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ありがとう、頑張れるわ。', en: "Thanks — can try.", style: 'tender Kansai husband voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02072',
    context: 'Hiroshi-elder gardens; Sho-young helps water plants.',
    purpose: 'Grandfather teaching child plant care.',
    ambient: 'garden_morning_birds',
    sound_effects: [],
    target_vocab: ['植物', '水', '草', '土', '油', '弱', '油断', '世話'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '翔、植物、水、ようけあげなあかん。', en: "Sho — plant, water, much give.", style: 'slow elder Kansai voice, warm warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'おじいちゃん、どれくらい?', en: "Grandpa — how much?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '土、ちょっと湿ったら、ええで。', en: "Soil — slightly moist, fine.", style: 'gentle elder Kansai voice, soft warm patient delivery carefully' },
      { speaker: 'sho_child', jp: '草、抜くのは?', en: "Weeds — pull?", style: 'soft child boy voice, warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '弱った株、油断したらすぐ枯れる。', en: "Weakened plant — careless, soon dies.", style: 'firm elder Kansai voice, soft warm advising delivery carefully' },
      { speaker: 'sho_child', jp: '世話、毎日するね!', en: "Care — daily do!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええ子や、頼もしいで。', en: "Fine kid — reliable.", style: 'tender elder Kansai voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02073',
    context: 'Naoko cleans the shop in early morning; teaches Aoi technique.',
    purpose: 'Veteran teaching cleaning technique to younger.',
    ambient: 'ramen_shop_morning_quiet',
    sound_effects: [],
    target_vocab: ['掃除', '洗濯', '油', '汗', '丁寧', '毎回', '習慣', '改善'],
    cast: ['naoko_aunt', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '蒼ちゃん、掃除、丁寧にやで。', en: "Aoi-chan — cleaning, carefully.", style: 'brassy Kansai aunt voice, bright firm teaching delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、油、ようけ落ちました。', en: "Yes — oil, much off.", style: 'soft adult woman voice, warm warm dutiful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '汗かいて、頑張ってるね。', en: "Sweating — trying.", style: 'warm Kansai aunt voice, soft warm approving delivery carefully' },
      { speaker: 'aoi_barista', jp: '洗濯、毎回、決まったやり方で?', en: "Wash — every time, set way?", style: 'curious adult woman voice, soft warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、習慣にしたら、楽や。', en: "Yeah — habit make, easy.", style: 'firm Kansai aunt voice, soft warm philosophical delivery carefully' },
      { speaker: 'aoi_barista', jp: '改善、続けて、頑張ります。', en: "Improvement — continue, try.", style: 'soft committed adult woman voice, warm earnest delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、ええ職人になるで!', en: "Heh — fine artisan become!", style: 'tender Kansai aunt voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02074',
    context: 'Riku-teen helps Sho-young memorize multiplication tables.',
    purpose: 'Older teen tutoring younger child math.',
    ambient: 'living_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['数学', '計算', '繰り返し', '九九', '間違い', '正解', '練習', '確実'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '陸くん、数学、九九、覚えられない!', en: "Riku — math, multiplication, can't memorize!", style: 'frustrated child boy voice, soft warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: '繰り返しが大事、毎日やろ。', en: "Repetition matters — daily.", style: 'soft teen boy voice, warm warm patient delivery carefully' },
      { speaker: 'sho_child', jp: '間違い、ようけしてしまう。', en: "Mistakes — many.", style: 'soft tearful child boy voice, warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: '計算、ゆっくりで、ええで。', en: "Calc — slow, fine.", style: 'gentle teen boy voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '正解、出たら、嬉しい!', en: "Correct — come, happy!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'riku_teen', jp: '練習、確実、覚えられるで。', en: "Practice — certain, memorize.", style: 'warm teen boy voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、頑張る!', en: "Thanks — try!", style: 'soft determined child boy voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02075',
    context: 'Sakura visits Tatsuya-country to interview about poetry.',
    purpose: 'Writer meeting elder about literary tradition.',
    ambient: 'farmhouse_tatami_warm',
    sound_effects: [],
    target_vocab: ['詩', '言葉', '文学', '伝統', '土曜日', '愛し', '心', '時代'],
    cast: ['sakura_teen', 'tatsuya_country'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'おじさん、詩、書いてはるんですね。', en: "Uncle — poetry, write.", style: 'gentle adult writer voice, soft warm respectful delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、土曜日に、ようけ書いとる。', en: "Yeah — Saturday, much write.", style: 'slow Tohoku farmer voice, warm warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '言葉、愛してる感じ、伝わります。', en: "Words — love feel, conveys.", style: 'soft adult writer voice, warm reverent delivery carefully' },
      { speaker: 'tatsuya_country', jp: '文学、若い頃から、好きやった。', en: "Literature — young from, loved.", style: 'gentle Tohoku voice, soft warm reminiscent delivery carefully' },
      { speaker: 'sakura_teen', jp: '伝統的な形、守りたいですか?', en: "Traditional form — protect want?", style: 'engaged adult writer voice, soft warm probing delivery carefully' },
      { speaker: 'tatsuya_country', jp: '心、時代に合わせて、変えていく。', en: "Heart — era match, change.", style: 'soft Tohoku farmer voice, warm warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '貴重なお言葉、ありがとうございます。', en: "Precious words — thanks.", style: 'reverent adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02076',
    context: 'Asuka and Yumiko visit an art exhibit; comment carefully.',
    purpose: 'Two adult women admiring art critically.',
    ambient: 'gallery_quiet_floor',
    sound_effects: [],
    target_vocab: ['視点', '尊重', '解釈', '感想', '本格', '本当は', '見れ', '届い'],
    cast: ['asuka_teacher', 'yumiko_mom'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'この作品、視点、独特ね。', en: "This work — viewpoint, unique.", style: 'composed teacher voice, soft warm thoughtful delivery carefully' },
      { speaker: 'yumiko_mom', jp: '人それぞれの解釈、尊重したいわ。', en: "Each interpretation — respect want.", style: 'tender older mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'asuka_teacher', jp: '本当は、こう感じてほしい、と思った。', en: "Truth — this feel want, thought.", style: 'soft teacher voice, warm warm earnest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '見れて、感想、心に届いたかしら。', en: "See — impression, heart reached?", style: 'gentle older mother voice, soft warm hopeful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '本格的な美術、深いですね。', en: "Authentic art — deep.", style: 'warm teacher voice, soft warm appreciative delivery carefully' },
      { speaker: 'yumiko_mom', jp: '次の作品、楽しみね。', en: "Next work — looking forward.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'こうやって、来れて、よかった。', en: "Like this — come, good.", style: 'soft teacher voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02077',
    context: 'Mei thinks about returning to work after maternity leave.',
    purpose: 'Adult woman wrestling with career-vs-family choice.',
    ambient: 'living_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['就職', '転職', '人材', '働き', '送っ', '迷い', '決心', '考える'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、転職、考えてるの。', en: "Daichi — career change, thinking.", style: 'soft young wife voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'えっ、就職、どこに?', en: "Eh — job, where?", style: 'gentle Kansai husband voice, soft warm caring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まだ、迷いがある。', en: "Still — wavering exists.", style: 'soft young woman voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '働きやすい場所、選ぼうな。', en: "Easy-work place — choose.", style: 'soft Kansai husband voice, warm warm encouraging delivery carefully' },
      { speaker: 'mei_romantic', jp: '送っているメール、返事、待ってる。', en: "Sent email — reply, awaiting.", style: 'composed young woman voice, soft warm professional delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前、人材として、絶対、求められる。', en: "You — talent as, definitely, sought.", style: 'tender Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、決心、ついた。', en: "Thanks — decision, set.", style: 'tender young wife voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02078',
    context: 'Sho-young learns about classroom rules at school via talk with Asuka.',
    purpose: 'Teacher patiently explaining school rules.',
    ambient: 'classroom_after_quiet',
    sound_effects: [],
    target_vocab: ['教室', '先輩', '玉', 'パン', '安い', '一般', '良く', '見れ'],
    cast: ['asuka_teacher', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '翔くん、教室、ちゃんと使ってね。', en: "Sho — classroom, properly use.", style: 'warm teacher voice, soft warm instructional delivery carefully' },
      { speaker: 'sho_child', jp: '先輩から、教わったルール、覚えてる!', en: "Senior from — learned rules, remember!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '皆と、良く協力するのも、大事。', en: "All — well cooperate, matters.", style: 'gentle teacher voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '玉、ボール遊び、する時の?', en: "Ball — ball play, time?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'うん、休み時間、安い物、皆で分けて。', en: "Yeah — break time, cheap things, all divide.", style: 'warm teacher voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'パン、いっぱい食べたい!', en: "Bread — much want eat!", style: 'animated child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '一般的に、お友達と分けてね。', en: "Generally — friends share.", style: 'tender teacher voice, soft warm reminding delivery carefully' },
    ],
  },
  {
    id: 'conv_02079',
    context: 'Aoi runs a budget check on the cafe; talks with Yuki for help.',
    purpose: 'Business owner getting professional check.',
    ambient: 'office_papers_low',
    sound_effects: [],
    target_vocab: ['物価', '押し', '届い', '切っ', 'メモ', '入ら', '範囲', '昭和'],
    cast: ['aoi_barista', 'yuki_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'ゆきさん、物価、押し上げてる。', en: "Yuki — prices, pushing up.", style: 'soft adult woman voice, warm concerned delivery carefully' },
      { speaker: 'yuki_office', jp: '今月のレシート、届いた分、確認しよう。', en: "Month receipts — arrived, verify.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'aoi_barista', jp: 'メモ、切って、整理してます。', en: "Notes — cut, organized.", style: 'gentle adult woman voice, soft warm dutiful delivery carefully' },
      { speaker: 'yuki_office', jp: '予算範囲、入らないかも。', en: "Budget range — won't fit maybe.", style: 'soft office woman voice, warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '昭和の物価とは、全然違うのよね。', en: "Showa prices — wholly different.", style: 'reflective adult woman voice, soft warm honest delivery carefully' },
      { speaker: 'yuki_office', jp: '一緒に、見直そう。', en: "Together — review.", style: 'warm office woman voice, soft warm united delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02080',
    context: 'Group gathers for a casual rooftop evening; many voices casual.',
    purpose: 'Multi-voice low-stakes evening chat.',
    ambient: 'rooftop_evening_breeze',
    sound_effects: [],
    target_vocab: ['だが', '本当は', '愛し', 'たまに', '尊重', '本格', 'すっかり', '届い'],
    cast: ['sakura_teen', 'ren_uni', 'kenji_office', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'こうやって、屋上で過ごす夜、本当に好き。', en: "Like this — rooftop spend night, truly love.", style: 'tender adult woman voice, soft warm content delivery carefully' },
      { speaker: 'kenji_office', jp: 'たまに、こうして、皆で集まると、ええなぁ。', en: "Sometimes — like this, all gather, lovely.", style: 'warm Kansai man voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '本当は、もっと頻繁にしたいよね。', en: "Truth — more often want.", style: 'soft adult writer voice, warm warm wistful delivery carefully' },
      { speaker: 'ren_uni', jp: 'だが、皆、忙しいんですよね。', en: "But — all, busy.", style: 'gentle young man voice, soft warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: 'お互いの時間、尊重しながら、繋がっていきたい。', en: "Each time — respecting, connect.", style: 'soft adult woman voice, warm warm philosophical delivery carefully' },
      { speaker: 'kenji_office', jp: '本格的な料理、用意してきたで!', en: "Authentic cooking — prepared!", style: 'animated Kansai man voice, bright warm cheerful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'すっかり、夕暮れね。', en: "Completely — sunset.", style: 'tender adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'ren_uni', jp: '心、届いてる、温かい空気。', en: "Heart — reaches, warm air.", style: 'soft young man voice, warm warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '皆を、愛してる、本当に。', en: "All — love, truly.", style: 'tender adult woman voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ言葉や、ほんま。', en: "Fine words — truly.", style: 'soft Kansai man voice, warm warm tender delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こういう時間、書き留めたい。', en: "Times like this — want capture.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: 'また、こうやって、集まりましょう。', en: "Again — like this, gather.", style: 'tender young man voice, soft warm united delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、約束ね。', en: "Yeah — promise.", style: 'tender adult woman voice, soft warm enduring delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_104 wrote', CONVERSATIONS.length, 'files');
