import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_116)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02301',
    context: 'Sho-young hurts his hand; Mei tends to it gently.',
    purpose: 'Mother caring for child injury.',
    ambient: 'kitchen_morning_quiet',
    sound_effects: [],
    target_vocab: ['手首', 'ケガ', '優しい', '直ぐに', '小児', '心配', '冷却', '安心'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、手首、痛い!', en: "Mom — wrist, hurts!", style: 'soft tearful child boy voice, warm warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、ケガしたの?見せて。', en: "Oh — injured? Show.", style: 'soft worried young mother voice, warm warm caring delivery carefully' },
      { speaker: 'sho_child', jp: 'ちょっと、しか、ない。', en: "Slightly — only.", style: 'soft child boy voice, warm warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '優しく、冷却しようね。', en: "Gently — cool.", style: 'tender young mother voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: '直ぐに、治る?', en: "Soon — heal?", style: 'soft hopeful child boy voice, warm warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '小児だから、すぐ回復するよ、安心して。', en: "Child — soon recover, relax.", style: 'warm young mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、お母さん。', en: "Thanks — Mom.", style: 'soft tender child boy voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02302',
    context: 'Daichi tries cooking; uses a new gadget at home.',
    purpose: 'Husband adventurously trying new cooking.',
    ambient: 'kitchen_evening_warm',
    sound_effects: [],
    target_vocab: ['スプーン', '和食', 'おかず', '直ぐに', '美味い', 'がんばる', '味', '工夫'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、今夜、和食、作ってみる!', en: "Mei — tonight, Japanese food, try!", style: 'animated Kansai husband voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、頑張ってね、応援する!', en: "Oh — try, cheer!", style: 'soft young wife voice, warm warm encouraging delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'スプーンで、味、見ながら、進めるわ。', en: "Spoon — taste, while, proceed.", style: 'soft Kansai husband voice, warm warm focused delivery carefully' },
      { speaker: 'mei_romantic', jp: '美味いおかず、できるかな?', en: "Tasty side dish — can?", style: 'gentle young woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '工夫しながら、直ぐに、味、整える!', en: "Ingenuity — soon, taste, arrange!", style: 'cheerful Kansai husband voice, bright warm determined delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ふふ、楽しみ。', en: "Heh — looking forward.", style: 'tender young wife voice, soft warm fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前のため、頑張るで!', en: "For you — try!", style: 'warm Kansai husband voice, soft warm loving delivery carefully' },
    ],
  },
  {
    id: 'conv_02303',
    context: 'Saito treats Mrs. Mori for general wellness; quiet medical visit.',
    purpose: 'Doctor caring for elderly community member.',
    ambient: 'clinic_room_quiet',
    sound_effects: [],
    target_vocab: ['受診', '熱心', '丁寧', '回復', '症状', '優しい', '直ぐに', 'ふだん'],
    cast: ['saito_doctor', 'mrs_mori_neighbor'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: '先生、受診、お願いします。', en: "Doctor — visit, please.", style: 'soft polite older neighbor voice, warm warm respectful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'おはようございます、症状、教えてください。', en: "Morning — symptom, tell.", style: 'measured doctor voice, soft warm professional delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふだん、丁寧に過ごしてるんだけど。', en: "Usually — carefully spending.", style: 'gentle older neighbor voice, soft warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '回復、順調そうですね。', en: "Recovery — smooth seems.", style: 'warm doctor voice, soft warm content delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '熱心に治療してくれて、感謝。', en: "Passionately treated — gratitude.", style: 'tender older neighbor voice, soft warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: '優しい言葉、こちらこそ。', en: "Kind words — likewise.", style: 'humble doctor voice, soft warm respectful delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '直ぐに、また、来ますね。', en: "Soon — again, come.", style: 'warm older neighbor voice, soft warm friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_02304',
    context: 'Aoi gets a small ladybug visit at the cafe; tells Sho-young.',
    purpose: 'Adult sharing nature wonder with child.',
    ambient: 'cafe_morning_birds',
    sound_effects: [],
    target_vocab: ['虫', '小さく', '丁寧', '優しく', '飛ぶ', '心', 'まね', '記念'],
    cast: ['aoi_barista', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '翔くん、てんとう虫、見て!', en: "Sho — ladybug, look!", style: 'soft adult woman voice, warm warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'うわ、ようけ小さく、可愛い!', en: "Whoa — much small, cute!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'aoi_barista', jp: '優しく、丁寧に、触ってね。', en: "Gently — carefully, touch.", style: 'gentle adult woman voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: '飛ぶの、まね、できない!', en: "Fly — mimic, can't!", style: 'awed child boy voice, soft warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '心、温まるね、こういう瞬間。', en: "Heart — warming, moment like.", style: 'tender adult woman voice, soft warm content delivery carefully' },
      { speaker: 'sho_child', jp: '記念に、見ておこう!', en: "Memory — see!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、写真、撮ろうか?', en: "Heh — photo, take?", style: 'warm adult woman voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02305',
    context: 'Naoko and Hina-young chat about a famous chef on TV.',
    purpose: 'Aunt and teen casually watching cooking show.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['本場', '巧', '吟味', '料理', '熱心', 'ふだん', '感心', '工夫'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、この料理人、本場で勉強したんやって!', en: "Hina — this chef, real place studied!", style: 'animated Kansai aunt voice, bright warm impressed delivery carefully' },
      { speaker: 'hina_child', jp: 'まあ、巧みな包丁さばき、ようけ綺麗!', en: "Oh — skilled knife handling, much pretty!", style: 'awed teen girl voice, bright warm appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '吟味、ようけしてる、食材選び。', en: "Examining — much doing, ingredient choice.", style: 'soft Kansai aunt voice, warm warm observant delivery carefully' },
      { speaker: 'hina_child', jp: '熱心な姿勢、感心しますね。', en: "Passionate stance — impressed.", style: 'tender teen girl voice, soft warm admiring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふだんから、工夫、ようけしとるんやろ。', en: "Usually — ingenuity, much.", style: 'warm Kansai aunt voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: '私も、料理、頑張ってみたい。', en: "I too — cooking, want try.", style: 'soft committed teen girl voice, warm earnest delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うちで、教えたるで!', en: "My place — teach!", style: 'bright Kansai aunt voice, soft warm welcoming delivery carefully' },
    ],
  },
  {
    id: 'conv_02306',
    context: 'Ren discusses his manga career goals with Kenji.',
    purpose: 'Two artists discussing professional path.',
    ambient: 'studio_lamp_evening',
    sound_effects: [],
    target_vocab: ['仕上がり', '故意', '広まっ', '誤差', '生み出さ', '熱心', '深く', '尊重'],
    cast: ['ren_uni', 'kenji_office'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '健司さん、仕上がり、満足してますか?', en: "Kenji — finish, satisfied?", style: 'soft young man voice, warm warm respectful delivery carefully' },
      { speaker: 'kenji_office', jp: '故意に、深い表現、生み出さなあかんわ。', en: "Intentionally — deep expression, must create.", style: 'measured Kansai mentor voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '誤差、ようけ気にしてしまうんです。', en: "Error — much care.", style: 'thoughtful young man voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: '熱心な姿勢、ええ作品、広まっていくで。', en: "Passionate stance — fine work, spread.", style: 'warm Kansai mentor voice, soft warm encouraging delivery carefully' },
      { speaker: 'ren_uni', jp: '皆の作風、尊重しながら、深く創作したい。', en: "All styles — respecting, deeply want create.", style: 'committed young man voice, soft warm earnest delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前なら、絶対できる、本当に。', en: "You — definitely can, truly.", style: 'tender Kansai man voice, soft warm trusting delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02307',
    context: 'Mei looks at old photos from her own youth; Daichi watches.',
    purpose: 'Couple in tender nostalgic exchange.',
    ambient: 'living_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['昔', '若い', '懐かしい', '同窓会', '深く', '思い出', '心', '長年'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、この写真、見て、若い時の私。', en: "Daichi — this photo, see, young me.", style: 'soft tender young wife voice, warm warm fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'まあ、変わらず、可愛いやんか。', en: "Oh — unchanged, cute.", style: 'tender Kansai husband voice, soft warm loving delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ふふ、長年、過ぎたわね。', en: "Heh — long years, passed.", style: 'gentle young wife voice, soft warm reflective delivery carefully' },
      { speaker: 'daichi_kansai', jp: '同窓会、今度、行く予定やろ?', en: "Reunion — next, going plan?", style: 'soft Kansai husband voice, warm warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、懐かしいわ、本当に。', en: "Yeah — nostalgic, truly.", style: 'tender young wife voice, soft warm fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: '心、深く感じる時間やな、思い出。', en: "Heart — deeply feel time, memory.", style: 'warm Kansai husband voice, soft warm philosophical delivery carefully' },
      { speaker: 'mei_romantic', jp: '皆と再会、楽しみ。', en: "All reunion — looking forward.", style: 'soft young wife voice, warm warm hopeful delivery carefully' },
    ],
  },
  {
    id: 'conv_02308',
    context: 'Hina-young finds a small pond in a park; observes nature.',
    purpose: 'Teen quietly observing wildlife.',
    ambient: 'park_pond_quiet',
    sound_effects: [],
    target_vocab: ['池', '草', '木々', '湧い', '広まっ', '生まれ', '静か', '心'],
    cast: ['hina_child', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '蓮くん、この池、深いね。', en: "Ren — this pond, deep.", style: 'soft teen girl voice, warm warm reverent delivery carefully' },
      { speaker: 'ren_uni', jp: '木々の周りに、草、ようけ生えてる。', en: "Trees around — grass, much grows.", style: 'gentle young man voice, soft warm observant delivery carefully' },
      { speaker: 'hina_child', jp: '水、湧いてる、感じ、するね。', en: "Water — gushing, feel, exists.", style: 'composed teen girl voice, soft warm awed delivery carefully' },
      { speaker: 'ren_uni', jp: '静かな場所、こんなところで生まれた魚も。', en: "Quiet place — fish born here too.", style: 'tender young man voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: '広まっていく、心、洗われる。', en: "Spreading — heart, washed.", style: 'soft teen girl voice, warm warm content delivery carefully' },
      { speaker: 'ren_uni', jp: '時々、こうやって、来たいですね。', en: "Sometimes — like this, want come.", style: 'warm young man voice, soft warm content delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、絶対!', en: "Yeah — definitely!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02309',
    context: 'Tatsuya-country tells Sakura about an old festival in his village.',
    purpose: 'Writer collecting oral history from elder.',
    ambient: 'porch_evening_breeze',
    sound_effects: [],
    target_vocab: ['本場', '長年', '伝統', '熱心', 'がんばる', '巧', '尊重', '振り返っ'],
    cast: ['tatsuya_country', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'おじさん、お祭り、本場で見たこと、ある?', en: "Uncle — festival, real place seen?", style: 'soft adult writer voice, warm warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: '長年、伝統、続いとったわ、若い頃から。', en: "Long years — tradition, continued, young times from.", style: 'slow Tohoku farmer voice, warm warm reminiscent delivery carefully' },
      { speaker: 'sakura_teen', jp: '熱心な皆さん、ようけ、頑張ってきた。', en: "Passionate all — much, tried.", style: 'tender adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'tatsuya_country', jp: '巧みな職人、たくさん、おったわ。', en: "Skilled artisans — many, existed.", style: 'gentle Tohoku voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '尊重したい、皆さんの努力。', en: "Want respect — all effort.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
      { speaker: 'tatsuya_country', jp: '振り返ったら、ようけ感謝や、本当に。', en: "Looked back — much grateful, truly.", style: 'tender Tohoku farmer voice, soft warm humble delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事に、心こめて、書きます。', en: "Article — heart put, write.", style: 'humble adult writer voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02310',
    context: 'Yumiko teaches Mei how to wrap a traditional gift.',
    purpose: 'Elder teaching younger woman cultural craft.',
    ambient: 'tatami_lamp_quiet',
    sound_effects: [],
    target_vocab: ['包装', '丁寧', '熱心', '結ぶ', '心', '愛情', '尽くし', '長年'],
    cast: ['yumiko_mom', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'メイ、包装、丁寧に、しましょうね。', en: "Mei — wrap, carefully.", style: 'gentle older mother voice, soft warm teaching delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お母さん、結ぶの、難しい。', en: "Mom — tie, hard.", style: 'soft young wife voice, warm warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '長年、家族に教えてきた、伝統。', en: "Long years — family taught, tradition.", style: 'tender older mother voice, soft warm reverent delivery carefully' },
      { speaker: 'mei_romantic', jp: '熱心に、覚えたいです。', en: "Passionately — want learn.", style: 'committed young woman voice, soft warm earnest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '心、愛情、ようけ込めるの。', en: "Heart — love, much put.", style: 'warm older mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'mei_romantic', jp: '尽くしてきた人に、ようけ感謝。', en: "Devoted person to — much gratitude.", style: 'soft young wife voice, warm warm grateful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'お前、立派になったわ。', en: "You — splendid become.", style: 'tender older mother voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02311',
    context: 'Sho-young watches his first ever movie at a cinema with Mei.',
    purpose: 'Mother taking child to first big movie experience.',
    ambient: 'cinema_seat_quiet',
    sound_effects: [],
    target_vocab: ['本場', '映像', '熱い', '深く', '恐竜', '冒険', '勇気', '楽しい'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、本場の映画館、すごい!', en: "Mom — real cinema, amazing!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'mei_romantic', jp: '映像、ようけ綺麗、感じるね。', en: "Visual — much pretty, feel.", style: 'tender young mother voice, soft warm content delivery carefully' },
      { speaker: 'sho_child', jp: '恐竜、出てきた、ようけ熱い場面!', en: "Dinosaur — came out, much passionate scene!", style: 'animated child boy voice, bright warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: '冒険、深く感じる物語ね。', en: "Adventure — deeply feel story.", style: 'soft young mother voice, warm warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '主人公、勇気、ようけある!', en: "Hero — courage, much exists!", style: 'thrilled child boy voice, bright warm admiring delivery carefully' },
      { speaker: 'mei_romantic', jp: '楽しい時間ね、お母さんも嬉しい。', en: "Fun time — Mom too happy.", style: 'warm young mother voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、お母さん!', en: "Thanks — Mom!", style: 'soft tender child boy voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02312',
    context: 'Aoi runs the cafe alone briefly; Kenji checks in.',
    purpose: 'Couple in casual workplace check-in.',
    ambient: 'cafe_busy_low',
    sound_effects: [],
    target_vocab: ['スタッフ', '一刻', '直ぐに', '無条件', '気軽', '深く', '愛情', '丁寧'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '蒼、スタッフ、足りとる?', en: "Aoi — staff, enough?", style: 'warm Kansai husband voice, soft warm caring delivery carefully' },
      { speaker: 'aoi_barista', jp: '一刻、待って、応援、ようけありがたい!', en: "Moment — wait, support, much grateful!", style: 'animated adult woman voice, bright warm grateful delivery carefully' },
      { speaker: 'kenji_office', jp: '直ぐに、無条件で、手伝うわ。', en: "Soon — unconditionally, help.", style: 'tender Kansai husband voice, soft warm steadfast delivery carefully' },
      { speaker: 'aoi_barista', jp: '気軽に、いつでも、頼れる夫やね。', en: "Casually — anytime, rely husband.", style: 'soft adult woman voice, warm warm fond delivery carefully' },
      { speaker: 'kenji_office', jp: '深く、愛情、ようけ持っとるで。', en: "Deeply — love, much hold.", style: 'tender Kansai husband voice, soft warm loving delivery carefully' },
      { speaker: 'aoi_barista', jp: '丁寧に、お客さん、対応するね。', en: "Carefully — customers, respond.", style: 'composed adult woman voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前、最高や!', en: "You — best!", style: 'warm Kansai husband voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02313',
    context: 'Hiroshi-elder tells Sho-young about the moon viewing tradition.',
    purpose: 'Grandfather teaching cultural tradition.',
    ambient: 'porch_night_crickets',
    sound_effects: [],
    target_vocab: ['月', '夜空', '伝統', '尊重', '長年', '深く', '心', '穏やか'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '翔、月、見たことあるか?', en: "Sho — moon, seen?", style: 'slow elder Kansai voice, warm warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、夜空、綺麗!', en: "Yeah — night sky, pretty!", style: 'awed child boy voice, bright warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '昔から、伝統やな、月を尊重するの。', en: "Long ago — tradition, moon respect.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '長年、皆、見てきたんやね。', en: "Long years — all, seen.", style: 'soft thoughtful child boy voice, warm warm understanding delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '深く、心、穏やかになる景色や。', en: "Deeply — heart, calm scenery.", style: 'tender elder Kansai voice, soft warm reverent delivery carefully' },
      { speaker: 'sho_child', jp: '心、温かく、感じる!', en: "Heart — warm, feel!", style: 'soft tender child boy voice, warm warm content delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ええ瞬間や、覚えとき。', en: "Yeah — fine moment, remember.", style: 'warm elder Kansai voice, soft warm enduring delivery carefully' },
    ],
  },
  {
    id: 'conv_02314',
    context: 'Sakura watches a planet documentary; chats with Ren.',
    purpose: 'Two writers reflecting on cosmic perspective.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['望遠鏡', '宇宙', '星空', '深く', '惑星', '科学', '尽きる', '感動'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、望遠鏡で見る宇宙、すごいね。', en: "Ren — telescope-see universe, amazing.", style: 'soft adult writer voice, warm warm awed delivery carefully' },
      { speaker: 'ren_uni', jp: '惑星、ようけある、宇宙の広さ。', en: "Planet — much exists, universe vastness.", style: 'tender young man voice, soft warm reverent delivery carefully' },
      { speaker: 'sakura_teen', jp: '深く、星空、見ると、感動する。', en: "Deeply — star sky, see, moved.", style: 'gentle adult writer voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '科学、皆、尽きないテーマですね。', en: "Science — all, inexhaustible theme.", style: 'composed young man voice, soft warm intellectual delivery carefully' },
      { speaker: 'sakura_teen', jp: '宇宙の話、心、温まる。', en: "Universe story — heart, warm.", style: 'soft adult writer voice, warm warm content delivery carefully' },
      { speaker: 'ren_uni', jp: '記事、書きたくなる、こういう瞬間。', en: "Article — want write, moment like.", style: 'tender young man voice, soft warm inspired delivery carefully' },
      { speaker: 'sakura_teen', jp: '一緒に、書きませんか?', en: "Together — write?", style: 'soft adult writer voice, warm warm collaborative delivery carefully' },
    ],
  },
  {
    id: 'conv_02315',
    context: 'Daichi gives Sho-young some tips on running a marathon.',
    purpose: 'Father teaching son endurance.',
    ambient: 'park_morning_breeze',
    sound_effects: [],
    target_vocab: ['ランナー', '走る', 'がんばる', 'よくよく', '直ぐに', '焦っ', '深く', '応援'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '翔、ランナー、よくよく見てみ。', en: "Sho — runner, well-well look.", style: 'soft Kansai father voice, warm warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '走るの、ようけ速いね!', en: "Run — much fast!", style: 'awed child boy voice, bright warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'がんばる姿勢、深く、感じるな。', en: "Trying stance — deeply, feel.", style: 'warm Kansai father voice, soft warm reverent delivery carefully' },
      { speaker: 'sho_child', jp: '直ぐに、止まらず、続けてる!', en: "Soon — without stopping, continuing!", style: 'soft impressed child boy voice, warm warm appreciative delivery carefully' },
      { speaker: 'daichi_kansai', jp: '焦らず、ペース、保つのが大事や。', en: "Without rush — pace, hold matters.", style: 'gentle Kansai father voice, soft warm wise delivery carefully' },
      { speaker: 'sho_child', jp: '応援、ようけ、しよう!', en: "Cheer — much, do!", style: 'thrilled child boy voice, bright warm passionate delivery carefully' },
      { speaker: 'daichi_kansai', jp: '皆、頑張れー!', en: "All — go!", style: 'animated Kansai father voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02316',
    context: 'Naoko hires a new part-timer; orientation chat.',
    purpose: 'Shop owner welcoming new employee.',
    ambient: 'ramen_shop_morning',
    sound_effects: [],
    target_vocab: ['出所', '熱心', '気軽', 'ふだん', '丁寧', '尽くし', '心', '頑張る'],
    cast: ['naoko_aunt', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '蓮、ふだんから、丁寧に、お客さんに接してな。', en: "Ren — usually, carefully, customer face.", style: 'warm Kansai aunt voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、熱心に、頑張ります!', en: "Yes — passionately, try!", style: 'soft committed young man voice, warm earnest delivery carefully' },
      { speaker: 'naoko_aunt', jp: '気軽に、何でも聞いてや。', en: "Casually — anything ask.", style: 'gentle Kansai aunt voice, soft warm welcoming delivery carefully' },
      { speaker: 'ren_uni', jp: '出所、いつでも、教えてください。', en: "Source — anytime, teach.", style: 'humble young man voice, soft warm respectful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '心、尽くしてくれたら、お客さんも喜ぶで。', en: "Heart — devote, customer too pleased.", style: 'tender Kansai aunt voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: 'お互いに、お話していきましょう。', en: "Each — talk.", style: 'soft young man voice, warm warm friendly delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'よろしく頼むで、家族みたいやで!', en: "Please — family-like!", style: 'warm Kansai aunt voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02317',
    context: 'Hina-young reads a book about Greek mythology; tells Sakura.',
    purpose: 'Teen sharing intellectual interest with mentor.',
    ambient: 'study_lamp_quiet',
    sound_effects: [],
    target_vocab: ['ギリシア', '神話', '昔', '伝統', '深く', '感心', '尊重', '丁寧'],
    cast: ['hina_child', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、ギリシアの神話、面白い!', en: "Sakura — Greek myth, fun!", style: 'thrilled teen girl voice, bright warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '昔の伝統、深く感じるね。', en: "Old tradition — deeply feel.", style: 'tender adult writer voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: '皆さんの感心、ようけ集めた話。', en: "All impressed — much gathered tale.", style: 'soft teen girl voice, warm warm impressed delivery carefully' },
      { speaker: 'sakura_teen', jp: '尊重したい、過去の物語。', en: "Want respect — past story.", style: 'composed adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'hina_child', jp: '丁寧に、ようけ、勉強したい。', en: "Carefully — much, want study.", style: 'soft committed teen girl voice, warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お前、ようけ熱心な学習者やね。', en: "You — much passionate learner.", style: 'warm adult writer voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとうございます!', en: "Thank you!", style: 'humble teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02318',
    context: 'Yuki-office and Mei discuss a fashion magazine\'s spring trends.',
    purpose: 'Two women in light lifestyle chat.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['スリム', 'スカイ', 'カスタム', '気軽', '丁寧', 'ふだん', '優しい', '春'],
    cast: ['yuki_office', 'mei_romantic'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: 'メイ、春の流行、スリムなデザイン、多いね。', en: "Mei — spring trend, slim design, many.", style: 'composed office woman voice, soft warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'スカイブルーの色、優しい感じ。', en: "Sky blue color — gentle feel.", style: 'soft young mother voice, warm warm appreciative delivery carefully' },
      { speaker: 'yuki_office', jp: 'カスタムできる服、増えてるみたい。', en: "Customizable clothes — increasing.", style: 'gentle office woman voice, soft warm informative delivery carefully' },
      { speaker: 'mei_romantic', jp: '気軽に、丁寧に、選びたいね。', en: "Casually — carefully, want choose.", style: 'tender young woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'yuki_office', jp: 'ふだん使い、優しい服、欲しい。', en: "Daily use — gentle clothes, want.", style: 'warm office woman voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '春、お互い、楽しもうね。', en: "Spring — each, enjoy.", style: 'soft young woman voice, warm warm cheerful delivery carefully' },
      { speaker: 'yuki_office', jp: 'うん、お買い物、また行こう!', en: "Yeah — shopping, again go!", style: 'bright office woman voice, soft warm delight delivered carefully' },
    ],
  },
  {
    id: 'conv_02319',
    context: 'Saito watches a nature documentary about dolphins with Asuka.',
    purpose: 'Couple sharing TV nature wonder.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['イルカ', '海', '深く', '群れ', '感動', '生態', '尊重', '驚かさ'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'あすか、イルカ、群れで泳いでる!', en: "Asuka — dolphin, school swimming!", style: 'awed doctor voice, soft warm content delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'まあ、深く感動するね、海。', en: "Oh — deeply moved, sea.", style: 'tender teacher voice, soft warm reverent delivery carefully' },
      { speaker: 'saito_doctor', jp: '生態、ようけ複雑、賢い生き物。', en: "Ecology — much complex, wise creature.", style: 'measured doctor voice, soft warm appreciative delivery carefully' },
      { speaker: 'asuka_teacher', jp: '尊重したい、自然の世界。', en: "Want respect — natural world.", style: 'gentle teacher voice, soft warm philosophical delivery carefully' },
      { speaker: 'saito_doctor', jp: '驚かされる、毎回、新しい発見。', en: "Surprised — every time, new discovery.", style: 'soft doctor voice, warm warm fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'こうやって、観るの、心が洗われる。', en: "Like this — watch, heart washed.", style: 'tender teacher voice, soft warm content delivery carefully' },
      { speaker: 'saito_doctor', jp: 'うん、本当に。', en: "Yeah — truly.", style: 'warm doctor voice, soft warm enduring delivery carefully' },
    ],
  },
  {
    id: 'conv_02320',
    context: 'Whole group celebrates Hina-young\'s acceptance to university.',
    purpose: 'Multi-voice family celebration of teen achievement.',
    ambient: 'living_room_celebration_warm',
    sound_effects: [],
    target_vocab: ['合格', '大学', '頑張る', '応援', '深く', '感謝', '誇る', '心'],
    cast: ['hina_child', 'mei_romantic', 'daichi_kansai', 'sho_child', 'yumiko_mom', 'naoko_aunt'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '皆、大学、本当に合格した!', en: "All — university, truly passed!", style: 'tearful thrilled teen girl voice, bright warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、おめでとう、深く感動!', en: "Oh — congrats, deeply moved!", style: 'tender young mother voice, soft warm tearful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前、ようけ頑張ってきた、誇りに思う!', en: "You — much tried, proud!", style: 'animated Kansai husband voice, bright warm proud delivery carefully' },
      { speaker: 'sho_child', jp: 'ねえちゃん、すごい!', en: "Sis — amazing!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'yumiko_mom', jp: '長年応援してきて、嬉しい。', en: "Long years cheered — happy.", style: 'tearful older mother voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '皆の応援、心、温まる!', en: "Everyone's cheer — heart, warm!", style: 'brassy Kansai aunt voice, bright warm delighted delivery carefully' },
      { speaker: 'hina_child', jp: '感謝、ようけ、伝えたい。', en: "Gratitude — much, want convey.", style: 'soft tender teen girl voice, warm warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '大学、ようけ楽しんでね。', en: "University — much enjoy.", style: 'warm young mother voice, soft warm encouraging delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お父さん、いつでも応援するで!', en: "Dad — anytime cheer!", style: 'tender Kansai husband voice, soft warm steadfast delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼくも、ねえちゃんみたいに、頑張る!', en: "I too — sis-like, try!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'おばあちゃん、誇り、ようけ感じる!', en: "Grandma — pride, much feel!", style: 'tender older mother voice, soft warm proud delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ええ姪っ子や、ほんま!', en: "Fine niece — truly!", style: 'warm Kansai aunt voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: '皆、ありがとう、本当に!', en: "All — thanks, truly!", style: 'tearful teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_116 wrote', CONVERSATIONS.length, 'files');
