import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_153)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // count-4/3 cleanup (死ん オープン 含む 思える 乗る + 探す おっしゃる)
  C('conv_03041',
    'Mei and Aoi chat about a newly opened cafe.',
    'Casual register; vocabulary (死ん/オープン/含む/思える/乗る) in natural home.',
    'cafe_quiet_chatter',
    ['死ん', 'オープン', '含む', '思える', '乗る'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '近くに、新しいカフェがオープンしたよ。', en: "A new cafe opened nearby.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'いいね、行ってみたいと思える?', en: "Nice, does it seem worth visiting?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'aoi_barista', jp: 'メニューに、限定の甘味も含むんだって。', en: "The menu reportedly includes limited sweets too.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '人気に乗って、混みそうだね。', en: "Riding the popularity, it'll likely be crowded.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'オープン初日、行列で死ぬほど並ぶかも。', en: "On opening day, there might be a brutal queue.", style: 'animated barista voice, soft warm playful delivery throughout' },
      { speaker: 'mei_romantic', jp: '料金に、ドリンク代も含むのかな?', en: "Does the price include the drink fee too?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '良さそうに思えるから、確かめようよ。', en: "It seems good, so let's check.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '波に乗って、早めに行こうね!', en: "Riding the wave, let's go early!", style: 'bubbly woman voice, soft warm cheerful closing delivery throughout' },
    ]),

  // count-2 robotics cluster (成立 ロボット 測定 出張 済み) ×3
  C('conv_03042',
    'Ren reports a robotics deal to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (成立/ロボット/測定/出張/済み) in natural home.',
    'office_quiet_low',
    ['成立', 'ロボット', '測定', '出張', '済み'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'ロボットの契約が、成立しました。', en: "The robot contract was concluded.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '出張は、無事に済んだかね?', en: "Did the business trip go smoothly?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'はい、出張は問題なく済みました。', en: "Yes, the trip was completed without issue.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'ロボットの精度は、測定したかね?', en: "Did you measure the robot's precision?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '測定済みで、基準を満たしています。', en: "It's measured and meets the standard.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '契約成立で、生産を進められるな。', en: "With the deal concluded, we can advance production.", style: 'satisfied boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '測定の報告書も、提出済みです。', en: "The measurement report is submitted too.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '成立おめでとう。次の出張も頼む。', en: "Congrats on the deal. I count on the next trip too.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_03043',
    'Kenji and Ren test a measurement robot.',
    'WIDENED SCENARIO: tech work; vocabulary (成立/ロボット/測定/出張/済み) in natural home.',
    'office_quiet_low',
    ['成立', 'ロボット', '測定', '出張', '済み'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'このロボット、測定が正確ですね。', en: "This robot measures accurately.", style: 'engaged young colleague voice, soft warm focused throughout' },
      { speaker: 'kenji_office', jp: '調整は、もう済んでいますよ。', en: "The adjustment is already done.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '出張先でも、測定できますか?', en: "Can we measure on business trips too?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '出張用に、小型ロボットを用意しました。', en: "I prepared a compact robot for trips.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '導入の契約は、成立したんですか?', en: "Was the adoption contract concluded?", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、先週、無事に成立しました。', en: "Yes, it was successfully concluded last week.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'テストも、済みですね。', en: "The tests are done too.", style: 'satisfied young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ロボットの測定、本番でも安心です。', en: "The robot's measurement is reliable in real use too.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_03044',
    'Sakura interviews a robotics engineer.',
    'WIDENED SCENARIO: tech interview; vocabulary (成立/ロボット/測定/出張/済み) in natural home.',
    'office_quiet_low',
    ['成立', 'ロボット', '測定', '出張', '済み'],
    ['sakura_teen', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'ロボット開発は、進んでいますか?', en: "Is robot development progressing?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'kenji_office', jp: '基本の設計は、もう済んでいます。', en: "The basic design is already done.", style: 'measured engineer voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '精度の測定は、どうですか?', en: "How is the precision measurement?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '測定の結果は、とても良好です。', en: "The measurement results are very good.", style: 'clear engineer voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '海外との契約も、成立しましたか?', en: "Were overseas contracts concluded too?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '出張して、契約を成立させました。', en: "I traveled and closed the contract.", style: 'measured engineer voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '出張は、大変じゃないですか?', en: "Aren't business trips hard?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '出張も、ロボットのためなら楽しいです。', en: "Trips are fun if they're for the robots.", style: 'warm engineer voice, soft warm informative closing clarity throughout' },
    ]),

  // count-1 cluster A — startup/work (起業 オフィス 応募 枠 配置) + 探す
  C('conv_03045',
    'Ren tells Hiroshi-boss about a startup plan.',
    'WIDENED SCENARIO: business chat; vocabulary (起業/オフィス/応募/枠/配置) in natural home.',
    'office_quiet_low',
    ['起業', 'オフィス', '応募', '枠', '配置'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'いつか、起業したいと思っています。', en: "Someday I want to start a business.", style: 'earnest young manager voice, soft warm engaged throughout' },
      { speaker: 'hiroshi_boss', jp: '立派な志だ。オフィスは考えたかね?', en: "An admirable ambition. Thought about an office?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '小さなオフィスを、探しています。', en: "I'm looking for a small office.", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '人は、どう集めるつもりかね?', en: "How do you plan to gather people?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '応募を募って、数人の枠を埋めます。', en: "I'll take applications and fill a few slots.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '机の配置も、大事だぞ。', en: "Desk arrangement matters too.", style: 'firm boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '働きやすい配置を、考えます。', en: "I'll think of an arrangement that's easy to work in.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '起業の夢、応援しているよ。', en: "I support your dream to start a business.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_03046',
    'Sakura interviews a young entrepreneur.',
    'WIDENED SCENARIO: business interview; vocabulary (起業/オフィス/応募/枠/配置) in natural home.',
    'office_quiet_low',
    ['起業', 'オフィス', '応募', '枠', '配置'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '若くして、起業されたんですね。', en: "You started a business young.", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: 'はい、二年前にオフィスを開きました。', en: "Yes, I opened an office two years ago.", style: 'warm entrepreneur voice, soft warm sincere delivery throughout' },
      { speaker: 'sakura_teen', jp: '社員は、応募で集めたんですか?', en: "Did you gather staff through applications?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'はい、応募の枠を、少しずつ広げました。', en: "Yes, I widened the application slots gradually.", style: 'gentle entrepreneur voice, soft warm delivery throughout' },
      { speaker: 'sakura_teen', jp: 'オフィスの配置は、こだわりましたか?', en: "Were you particular about the office layout?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '話しやすい配置に、こだわりました。', en: "I cared about a layout that's easy to talk in.", style: 'reflective entrepreneur voice, soft warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '起業して、良かったと思いますか?', en: "Do you think starting was a good move?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '応募してくれた仲間に、感謝しています。', en: "I'm grateful to the colleagues who applied.", style: 'warm entrepreneur voice, soft warm sincere closing delivery throughout' },
    ]),

  C('conv_03047',
    'Yuki and Kenji rearrange the office.',
    'WIDENED SCENARIO: office task; vocabulary (起業/オフィス/応募/枠/配置) in natural home.',
    'office_quiet_low',
    ['起業', 'オフィス', '応募', '枠', '配置'],
    ['yuki_office', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'オフィスの配置を、変えたいんです。', en: "I want to change the office layout.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '新しい人の、枠も増えましたしね。', en: "The slots for new people increased too.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '応募が多くて、嬉しい悩みです。', en: "Lots of applications — a happy problem.", style: 'cheerful office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '机の配置は、窓際がいいですか?', en: "Should the desks be by the window?", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '窓際の配置で、明るくしたいです。', en: "I want a bright window-side arrangement.", style: 'engaged office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '社長も、起業の頃を思い出すでしょうね。', en: "The boss must recall the startup days.", style: 'warm office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '応募の枠、来月も募集しますね。', en: "We'll recruit for the slots next month too.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'いいオフィスに、なりそうですね。', en: "It's shaping into a good office.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_03048',
    'Mei and Ren discuss applying for a job.',
    'Casual register; vocabulary (起業/オフィス/応募/枠/配置) in natural home.',
    'cafe_quiet_chatter',
    ['起業', 'オフィス', '応募', '枠', '配置'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '新しい仕事に、応募してみたの。', en: "I applied for a new job.", style: 'soft warm woman voice, gentle excited delivery throughout' },
      { speaker: 'ren_uni', jp: 'いいね、どんなオフィスなの?', en: "Nice, what kind of office?", style: 'warm young man voice, soft warm engaged delivery throughout' },
      { speaker: 'mei_romantic', jp: '起業したばかりの、小さな会社なの。', en: "A small company that just started up.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '応募の枠は、少ないの?', en: "Are the application slots few?", style: 'curious young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '枠は二つで、競争率が高いの。', en: "There are two slots, so it's competitive.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'オフィスの雰囲気、良さそうだね。', en: "The office atmosphere sounds good.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '机の配置も、自由なんだって。', en: "The desk layout is flexible too, they say.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '応募、きっとうまくいくよ!', en: "Your application will surely go well!", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-1 cluster B — performance (ステージ 公演 楽器 ヒット キャラ)
  C('conv_03049',
    'Aoi and Riku talk about a concert performance.',
    'Casual register; vocabulary (ステージ/公演/楽器/ヒット/キャラ) in natural home.',
    'cafe_quiet_chatter',
    ['ステージ', '公演', '楽器', 'ヒット', 'キャラ'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '昨日の公演、ステージが派手だったよ!', en: "Yesterday's show — the stage was flashy!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、どんな楽器を使ってたの?', en: "Nice, what instruments did they use?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '珍しい楽器が、たくさんあったよ。', en: "There were lots of unusual instruments.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ヒット曲も、演奏したの?', en: "Did they play their hit songs too?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、ヒット曲でステージが盛り上がった。', en: "Yeah, the hits got the stage hyped.", style: 'thrilled teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'メンバーの、キャラも立ってた?', en: "Did the members' characters stand out?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'みんなキャラが濃くて、面白かったよ。', en: "Everyone had strong personalities; it was fun.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '次の公演、私も行きたいなー!', en: "I want to go to the next show too!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03050',
    'Sakura interviews a stage performer.',
    'WIDENED SCENARIO: arts interview; vocabulary (ステージ/公演/楽器/ヒット/キャラ) in natural home.',
    'office_quiet_low',
    ['ステージ', '公演', '楽器', 'ヒット', 'キャラ'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '公演の前は、緊張しますか?', en: "Do you get nervous before a show?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: 'ステージに立つと、落ち着くんです。', en: "Once I'm on stage, I calm down.", style: 'warm performer voice, soft warm sincere delivery throughout' },
      { speaker: 'sakura_teen', jp: 'どんな楽器を、演奏しますか?', en: "What instruments do you play?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '弦の楽器を、中心に演奏します。', en: "I mainly play string instruments.", style: 'gentle performer voice, soft warm delivery throughout' },
      { speaker: 'sakura_teen', jp: 'ヒット曲も、生まれましたね。', en: "You've had hit songs too.", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'ヒットは、ステージのおかげです。', en: "The hits are thanks to the stage.", style: 'modest performer voice, soft warm delivery throughout' },
      { speaker: 'sakura_teen', jp: 'ご自身のキャラを、意識しますか?', en: "Are you conscious of your own persona?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '自然なキャラで、公演に臨みます。', en: "I face the show as my natural self.", style: 'warm performer voice, soft warm sincere closing delivery throughout' },
    ]),

  C('conv_03051',
    'Riku and Daichi reminisce about a festival stage.',
    'Casual register; vocabulary (ステージ/公演/楽器/ヒット/キャラ) in natural home.',
    'cafe_quiet_chatter',
    ['ステージ', '公演', '楽器', 'ヒット', 'キャラ'],
    ['riku_teen', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '夏祭りのステージ、覚えてる?', en: "Remember the summer-festival stage?", style: 'cheerful teen boy voice, bright warm nostalgic delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'おう、あの公演は最高やったなあ。', en: "Yeah, that show was the best.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'riku_teen', jp: '地元のバンドが、楽器を持ち寄ったんだ。', en: "Local bands brought their instruments.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'みんな、楽器が上手やったわ。', en: "Everyone was skilled with their instruments.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'riku_teen', jp: '昔のヒット曲で、盛り上がったよね。', en: "We got hyped on old hit songs.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '司会のキャラが、また濃かったなあ。', en: "The MC's character was quite something.", style: 'lively Kansai man voice, warm amused delivery throughout' },
      { speaker: 'riku_teen', jp: 'またあのステージ、見たいなー。', en: "I want to see that stage again.", style: 'wistful teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '今年も、公演あるか調べよか。', en: "Let's check if there's a show this year too.", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_03052',
    'Mei and Asuka discuss a musical performance.',
    'WIDENED SCENARIO: arts discussion; vocabulary (ステージ/公演/楽器/ヒット/キャラ) in natural home.',
    'living_room_quiet',
    ['ステージ', '公演', '楽器', 'ヒット', 'キャラ'],
    ['mei_romantic', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '先日の公演、本当に感動しました。', en: "The other day's show was truly moving.", style: 'soft warm woman voice, gentle moved delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ステージの照明も、美しかったですね。', en: "The stage lighting was beautiful too.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '生の楽器の音、迫力がありました。', en: "The live instruments had real power.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'あの曲は、昔のヒットですね。', en: "That piece is an old hit.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '主役のキャラが、印象的でした。', en: "The lead's character was striking.", style: 'thoughtful woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'キャラが立つと、公演が生きますね。', en: "Strong characters bring a show to life.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: 'また、ステージを観に行きたいです。', en: "I want to go see the stage again.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '次の公演も、楽しみですね。', en: "I look forward to the next show too.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  // count-1 cluster C — news/trade (貿易 統一 承認 検証 提示)
  C('conv_03053',
    'News: Sakura and Ren on a trade agreement.',
    'WIDENED SCENARIO: economic news; vocabulary (貿易/統一/承認/検証/提示) in natural home.',
    'studio_room_tone',
    ['貿易', '統一', '承認', '検証', '提示'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '新しい貿易の協定が、提示されました。', en: "A new trade agreement was presented.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '各国の承認は、得られましたか?', en: "Was each nation's approval obtained?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '主要国の承認が、進んでいます。', en: "Major nations' approval is progressing.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'ルールの統一も、含まれますか?', en: "Does it include unifying rules?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、基準の統一が、提示されました。', en: "Yes, unified standards were presented.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '内容の検証は、済んでいますか?', en: "Has the content been verified?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '専門家が、検証を続けています。', en: "Experts continue the verification.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '貿易の統一が、進むといいですね。', en: "I hope trade unification advances.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_03054',
    'Hiroshi-boss and Ren review a trade proposal.',
    'WIDENED SCENARIO: business strategy; vocabulary (貿易/統一/承認/検証/提示) in natural home.',
    'office_quiet_low',
    ['貿易', '統一', '承認', '検証', '提示'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '貿易の新しい案を、提示します。', en: "I'll present a new trade proposal.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '社内の承認は、取れそうかね?', en: "Can we get internal approval?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '役員に提示し、承認を求めます。', en: "I'll present to the board and seek approval.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '数字の検証は、済んでいるかね?', en: "Are the numbers verified?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '何度も、検証を重ねました。', en: "I verified them many times over.", style: 'reliable young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '取引の条件は、統一できるかね?', en: "Can we unify the trade terms?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '条件の統一を、提案に含めました。', en: "I included term unification in the proposal.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '検証を踏まえ、承認を出そう。', en: "Based on the verification, let's grant approval.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_03055',
    'Asuka lectures on trade history.',
    'WIDENED SCENARIO: economics lecture; vocabulary (貿易/統一/承認/検証/提示) in natural home.',
    'lecture_hall_quiet',
    ['貿易', '統一', '承認', '検証', '提示'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '貿易は、古くから国を結んできました。', en: "Trade has long linked nations.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'ルールの統一は、難しかったんですか?', en: "Was unifying rules difficult?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '統一には、各国の承認が要りました。', en: "Unification required each nation's approval.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '条件は、どう提示されたんですか?', en: "How were the terms presented?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '文書で提示し、検証を重ねました。', en: "They were presented in documents and verified repeatedly.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '検証が、信頼を生んだんですね。', en: "Verification built trust.", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、承認の積み重ねが、貿易を広げました。', en: "Yes, accumulated approvals widened trade.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '貿易の統一、奥が深いですね。', en: "Trade unification is profound.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_03056',
    'Ren interviews a trade analyst.',
    'WIDENED SCENARIO: expert interview; vocabulary (貿易/統一/承認/検証/提示) in natural home.',
    'office_quiet_low',
    ['貿易', '統一', '承認', '検証', '提示'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '今の貿易の課題は、何ですか?', en: "What's the current trade challenge?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: '基準の統一が、最大の課題です。', en: "Unifying standards is the biggest challenge.", style: 'composed analyst voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '承認の手続きは、複雑ですか?', en: "Are approval procedures complex?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '承認には、丁寧な検証が要ります。', en: "Approval requires careful verification.", style: 'patient analyst voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '提案は、どう提示するんですか?', en: "How are proposals presented?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: 'データを提示し、検証してもらいます。', en: "We present data and have it verified.", style: 'composed analyst voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '統一が進めば、貿易は楽になりますか?', en: "If unification advances, does trade get easier?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、統一が、貿易を滑らかにします。', en: "Yes, unification smooths trade.", style: 'warm analyst voice, soft warm measured closing clarity throughout' },
    ]),

  // count-1 cluster D — daily/emotion (うれしい かわいい お気に入り 文句 メリット)
  C('conv_03057',
    'Mei and Aoi gush over a cute new item.',
    'Casual register; vocabulary (うれしい/かわいい/お気に入り/文句/メリット) in natural home.',
    'cafe_quiet_chatter',
    ['うれしい', 'かわいい', 'お気に入り', '文句', 'メリット'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'この新しいカップ、かわいいでしょ?', en: "This new cup is cute, right?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ほんとだ、すごくかわいいね。', en: "It really is, so cute.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'aoi_barista', jp: 'お気に入りになっちゃった!', en: "It's become my favorite!", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '使うのが、うれしくなるね。', en: "Using it makes you happy.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '軽くて、洗いやすいメリットもあるよ。', en: "It's light and easy to wash too — a merit.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '文句なしの、お気に入りだね。', en: "A favorite with no complaints.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'お客さんにも、うれしいと言われたよ。', en: "Customers said they're happy with it too.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'かわいくて、メリットも多いね!', en: "Cute and with lots of merits!", style: 'bubbly woman voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03058',
    'Sho shows Grandma a favorite toy.',
    'Casual home register; vocabulary (うれしい/かわいい/お気に入り/文句/メリット) in natural home.',
    'tatami_room_quiet',
    ['うれしい', 'かわいい', 'お気に入り', '文句', 'メリット'],
    ['sho_child', 'sachiko_grandma'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おばあちゃん、このぬいぐるみかわいいでしょ!', en: "Grandma, this stuffed animal is cute, right!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'まあ、本当にかわいいわね。', en: "Oh my, it really is cute.", style: 'tender grandmother voice, soft warm gentle delivery throughout' },
      { speaker: 'sho_child', jp: '一番のお気に入りなんだ!', en: "It's my number one favorite!", style: 'proud small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'もらった時、うれしかったでしょう。', en: "You must've been happy when you got it.", style: 'gentle grandmother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'うん、すごくうれしかったよ!', en: "Yeah, I was so happy!", style: 'delighted small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '一つも文句がないのね。', en: "Not a single complaint, huh.", style: 'tender grandmother voice, soft warm amused delivery throughout' },
      { speaker: 'sho_child', jp: '柔らかいのが、メリットなんだ!', en: "Being soft is its merit!", style: 'cheerful small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'お気に入りを、大事にしてね。', en: "Take care of your favorite.", style: 'tender grandmother voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_03059',
    'Riku and Aoi compare two gadgets.',
    'Casual register; vocabulary (うれしい/かわいい/お気に入り/文句/メリット) in natural home.',
    'cafe_quiet_chatter',
    ['うれしい', 'かわいい', 'お気に入り', '文句', 'メリット'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '新しいイヤホン、買ったんだ!', en: "I bought new earphones!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、デザインもかわいいね。', en: "Nice, the design's cute too.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '音がいいのが、最大のメリットだよ。', en: "Good sound is the biggest merit.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '値段に、文句はないの?', en: "No complaints about the price?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '安かったから、文句なしだよ。', en: "It was cheap, so no complaints.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'お気に入りに、なりそうだね。', en: "It's set to be a favorite.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、毎日使えてうれしいよ。', en: "Yeah, I'm happy to use it daily.", style: 'happy teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'かわいくて、便利なんて最高だね!', en: "Cute and convenient — the best!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03060',
    'Mei and Ren talk about a favorite cafe.',
    'Casual register; vocabulary (うれしい/かわいい/お気に入り/文句/メリット) in natural home.',
    'cafe_quiet_chatter',
    ['うれしい', 'かわいい', 'お気に入り', '文句', 'メリット'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'このカフェ、私のお気に入りなの。', en: "This cafe is my favorite.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'ren_uni', jp: '内装が、かわいいね。', en: "The interior is cute.", style: 'warm young man voice, soft warm engaged delivery throughout' },
      { speaker: 'mei_romantic', jp: '静かなのが、メリットなの。', en: "Being quiet is its merit.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '確かに、文句のつけようがないね。', en: "Indeed, nothing to complain about.", style: 'agreeable young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ここに来ると、うれしくなるの。', en: "Coming here makes me happy.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '店員さんも、優しくてうれしいね。', en: "The staff are kind, which is nice.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'かわいいケーキも、お気に入りなの。', en: "The cute cakes are my favorite too.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '二人のお気に入りに、しようね。', en: "Let's make it our shared favorite.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_153 wrote', CONVERSATIONS.length, 'files');
