import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_124)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02461',
    'Civic news: Sakura and Ren on a parliamentary session.',
    'WIDENED SCENARIO: political news; civic vocabulary (氏/大臣/議員/述べ) in natural home.',
    'studio_room_tone',
    ['氏', '大臣', '現在', 'これら', '議員'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '本日、国会で重要な議論が行われました。', en: "Today an important debate was held in the Diet.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '中村氏は、何と述べたんですか?', en: "What did Mr. Nakamura state?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '氏は、改革の必要性を述べました。', en: "He stated the need for reform.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '大臣も、同じ考えなんでしょうか?', en: "Does the minister share that view?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '大臣は、現在、検討中だと答えました。', en: "The minister answered it's currently under consideration.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '反対する議員も、いたんですか?', en: "Were there opposing members too?", style: 'probing young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '複数の議員が、これらの案に反対しました。', en: "Several members opposed these proposals.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'これらの議論は、現在も続いています。', en: "These debates continue even now.", style: 'measured young commentator voice, soft warm analytical reflective throughout' },
    ]),

  C('conv_02462',
    'Economic news: Ren and Yuki on corporate earnings.',
    'WIDENED SCENARIO: business-news discussion; finance vocabulary (億/利益/税/株) in natural home.',
    'office_quiet_low',
    ['億', 'ドル', '昨年', '利益', '税'],
    ['ren_uni', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '昨年の決算が、発表されました。', en: "Last year's earnings were announced.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '利益は、どのくらい出たんですか?', en: "How much profit did they make?", style: 'attentive office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: '利益は、五億ほどに伸びました。', en: "Profit grew to about five hundred million.", style: 'precise young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '昨年より、増えたんですね。', en: "So it rose from last year.", style: 'engaged office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'ええ、海外でドル建ての売上が伸びました。', en: "Yes, dollar-denominated overseas sales grew.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '税の負担は、重くないんですか?', en: "Isn't the tax burden heavy?", style: 'thoughtful office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: '税を引いても、利益は十分残ります。', en: "Even after tax, plenty of profit remains.", style: 'confident young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '今年も、ドルの動きが鍵ですね。', en: "Dollar movements are key again this year.", style: 'reflective office woman voice, soft warm engaged closing throughout' },
    ]),

  C('conv_02463',
    'Business planning: Hiroshi-boss and Yuki on a new service.',
    'WIDENED SCENARIO: business meeting; corporate vocabulary (ビジネス/業務/事務/センター) in natural home.',
    'office_quiet_low',
    ['ビジネス', 'レベル', 'センター', '業務', '事務'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '新しいビジネスを、立ち上げたい。', en: "I want to launch a new business.", style: 'decisive boss voice, soft warm composed authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: 'どの業務から、始めますか?', en: "Which operations do we start with?", style: 'attentive office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'まず、事務の体制を整えよう。', en: "First, let's set up the office structure.", style: 'measured boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '専用のセンターも、必要でしょうか?', en: "Will we need a dedicated center too?", style: 'thoughtful office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '相談センターを、設けるつもりだ。', en: "I intend to set up a consultation center.", style: 'decisive boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: 'サービスのレベルは、高く保ちたいですね。', en: "We want to keep the service level high.", style: 'earnest office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'その通り。業務の質が、信用を生む。', en: "Exactly. Quality of work builds trust.", style: 'firm boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '事務とセンター、両方準備します。', en: "I'll prepare both the office and the center.", style: 'reliable office woman voice, soft warm resolved closing throughout' },
    ]),

  C('conv_02464',
    'Geography documentary: Asuka and Riku on regions and neighbors.',
    'WIDENED SCENARIO: geography discussion; regional vocabulary (県/区/都市/側) in natural home.',
    'living_room_quiet',
    ['県', '側', '区', '都市', 'ドイツ'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '大きな都市は、どこにありますか?', en: "Where are the big cities?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '都市は、海の側に多く集まります。', en: "Cities gather mostly near the sea.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '県の中に、区もあるんですか?', en: "Are there wards within prefectures?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '大きな都市は、いくつもの区に分かれます。', en: "Big cities split into many wards.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'ドイツの都市も、そうなんですか?', en: "Are German cities like that too?", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ドイツにも、区に似た仕組みがあります。', en: "Germany too has a system like wards.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '山の側には、都市は少ないんですね。', en: "There are few cities on the mountain side.", style: 'understanding teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '県ごとに、地形が違って面白いですよ。', en: "Terrain differs by prefecture, which is interesting.", style: 'warm teacher voice, soft warm measured encouraging clarity throughout' },
    ]),

  C('conv_02465',
    'History documentary discussion: Asuka and Ren on the last century.',
    'WIDENED SCENARIO: history discussion; era/military vocabulary (平成/軍/世紀/米国) in natural home.',
    'living_room_quiet',
    ['平成', '軍', '米国', '世紀', '等'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '二十世紀は、戦争の時代でしたね。', en: "The twentieth century was an age of war.", style: 'thoughtful young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、各国の軍が、大きく動きました。', en: "Yes, each nation's military moved greatly.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '米国の役割は、大きかったんですか?', en: "Was America's role large?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '米国等の大国が、世界を動かしました。', en: "Great powers such as the US moved the world.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '平成に入って、何が変わりましたか?', en: "What changed entering the Heisei era?", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '平成は、比較的平和な時代でした。', en: "Heisei was a relatively peaceful era.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '軍の役割も、変わったんですね。', en: "The military's role changed too.", style: 'understanding young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: '新しい世紀の課題は、また別ですよ。', en: "The new century's challenges are another matter.", style: 'thoughtful teacher voice, soft warm measured clarity throughout' },
    ]),

  C('conv_02466',
    'Kenji helps Yuki navigate a company website.',
    'WIDENED SCENARIO: web help; internet vocabulary (ホームページ/アクセス/トップ/クリック) in natural home.',
    'office_quiet_low',
    ['ホームページ', 'アクセス', 'トップ', 'クリック', 'リンク'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '会社のホームページが、開けないの。', en: "I can't open the company website.", style: 'puzzled office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: 'まず、ここからアクセスしてみて下さい。', en: "First, try accessing from here.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'アクセスしたら、トップが出ました。', en: "After accessing, the top page appeared.", style: 'relieved office woman voice, soft warm engaged delivery throughout' },
      { speaker: 'kenji_office', jp: 'トップのメニューを、クリックして下さい。', en: "Please click the menu on the top page.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'クリックしたら、リンクが並びました。', en: "When I clicked, links lined up.", style: 'engaged office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: '目的のリンクを、もう一度クリック。', en: "Click the link you want once more.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'ホームページの使い方、分かってきた。', en: "I'm getting the hang of the website.", style: 'satisfied office woman voice, soft warm appreciative delivery throughout' },
    ]),

  C('conv_02467',
    'Asuka lectures on classification, using formal alternatives.',
    'WIDENED SCENARIO: lecture; formal connectives (または/いわゆる/含め/自体) in natural home.',
    'lecture_hall_quiet',
    ['または', 'いわゆる', '含め', '自体', '同様'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '物事は、形または機能で分けられます。', en: "Things can be divided by form or function.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'いわゆる分類、ということですか?', en: "You mean what's called classification?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'そうです。いわゆる基本の考え方です。', en: "Yes — it's the so-called basic idea.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'asuka_teacher', jp: '例外も含めて、考える必要があります。', en: "We must think, including exceptions.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '言葉自体の意味も、関係しますか?', en: "Does the meaning of the word itself matter?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、言葉自体が、分類を左右します。', en: "Yes, the word itself shapes classification.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '色や音も、同様に分けられますね。', en: "Colors and sounds can be divided similarly.", style: 'engaged adult student voice, soft warm understanding throughout' },
      { speaker: 'asuka_teacher', jp: '同様の方法を、例外も含めて応用します。', en: "We apply the same method, including exceptions.", style: 'warm teacher voice, soft warm measured encouraging clarity throughout' },
    ]),

  C('conv_02468',
    'Asuka lectures on standards and measurement.',
    'WIDENED SCENARIO: lecture; abstract vocabulary (基準/最大/相当/新た) in natural home.',
    'lecture_hall_quiet',
    ['基準', '最大', '相当', '新た', 'これら'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '測るには、明確な基準が要ります。', en: "To measure, you need a clear standard.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '基準は、誰が決めるんですか?', en: "Who decides the standard?", style: 'engaged young student voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: '研究者が、新たな基準を提案します。', en: "Researchers propose new standards.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '最大の課題は、何でしょうか?', en: "What's the biggest challenge?", style: 'thoughtful young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '最大の課題は、公平さを保つことです。', en: "The biggest challenge is keeping fairness.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '相当な議論が、必要そうですね。', en: "It seems considerable debate is needed.", style: 'understanding young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、相当な時間をかけて決めます。', en: "Yes, it's decided over considerable time.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'これらの基準が、社会を支えるんですね。', en: "So these standards support society.", style: 'moved young student voice, soft warm realization throughout' },
    ]),

  C('conv_02469',
    'News editorial: Sakura and Ren on a politician\'s statement.',
    'WIDENED SCENARIO: news-analysis; discourse vocabulary (述べ/発言/批判/攻撃) in natural home.',
    'studio_room_tone',
    ['述べ', '発言', '批判', '攻撃', '被害'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'ある議員の発言が、話題です。', en: "A certain member's statement is the talk.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '具体的に、何と述べたんですか?', en: "Specifically, what did they state?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '対策が遅いと、述べました。', en: "They stated the measures are slow.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'その発言に、批判も出ていますね。', en: "Criticism has arisen over that statement.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、個人への攻撃だという声もあります。', en: "Yes, some say it's a personal attack.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '被害を受けた人々への配慮も、必要です。', en: "Consideration for those harmed is needed too.", style: 'thoughtful young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '批判より、対策の議論を進めたいですね。', en: "Rather than criticism, let's advance debate on measures.", style: 'balanced adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '冷静な発言が、求められています。', en: "Calm statements are being called for.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02470',
    'Hiroshi-boss and Yuki review a finance proposal.',
    'WIDENED SCENARIO: finance meeting; banking vocabulary (株/銀行/利益/無料) in natural home.',
    'office_quiet_low',
    ['株', '銀行', '利益', '無料', '億'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '銀行から、融資の返事が来ました。', en: "A reply on the loan came from the bank.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '条件は、悪くないのかね?', en: "Aren't the terms bad?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'はい、利益への影響は小さいです。', en: "Yes, the impact on profit is small.", style: 'reassuring office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '株を、新たに発行する案はどうかね?', en: "What about the plan to issue new shares?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '株の発行で、一億ほど集まります。', en: "Issuing shares would raise about a hundred million.", style: 'precise office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '銀行と、よく相談しておこう。', en: "Let's consult the bank carefully.", style: 'decisive boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '相談は、無料だそうです。', en: "The consultation is free, apparently.", style: 'helpful office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'では、無料のうちに進めよう。', en: "Then let's proceed while it's free.", style: 'satisfied boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02471',
    'Mei and Aoi chat about moving to the city.',
    'WIDENED SCENARIO: urban-life chat; city vocabulary (区/住宅/都市/センター) in natural home.',
    'cafe_quiet_chatter',
    ['区', '住宅', '都市', '側', 'センター'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '来月、都市の方へ引っ越すの。', en: "I'm moving toward the city next month.", style: 'soft warm woman voice, gentle relaxed delivery throughout' },
      { speaker: 'aoi_barista', jp: 'へえ、どの区に住むの?', en: "Oh, which ward will you live in?", style: 'bright barista voice, soft warm curious cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '駅の東側の区を、考えてるの。', en: "I'm thinking of the ward east of the station.", style: 'gentle woman voice, soft warm thoughtful delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そっちは、住宅が多い地域だよね。', en: "That area has a lot of housing, right?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、新しい住宅が増えてるみたい。', en: "Yeah, new housing seems to be increasing.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '近くに、文化センターもあるよ。', en: "There's a cultural center nearby too.", style: 'helpful barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'センターが近いと、便利でいいな。', en: "A nearby center would be convenient.", style: 'pleased woman voice, soft warm delighted delivery throughout' },
      { speaker: 'aoi_barista', jp: '都市の生活、楽しみだね!', en: "City life — exciting!", style: 'cheerful barista voice, soft warm bubbly delivery throughout' },
    ]),

  C('conv_02472',
    'Aoi and Riku talk about a band\'s new release.',
    'WIDENED SCENARIO: music chat; fan vocabulary (ファン/メンバー/演奏/放送) in natural home.',
    'cafe_quiet_chatter',
    ['ファン', 'メンバー', '演奏', '放送', '公開'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'あのバンド、新曲を公開したよ!', en: "That band released a new song!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'わたし、あそこのファンなんだ!', en: "I'm a fan of theirs!", style: 'thrilled barista voice, soft warm bubbly delivery throughout' },
      { speaker: 'riku_teen', jp: 'メンバーが、一人増えたんだって。', en: "They added a new member, I heard.", style: 'engaged teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '新しいメンバーの演奏、聴いた?', en: "Did you hear the new member's playing?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、演奏がすごく上手だった。', en: "Yeah, the performance was really skilled.", style: 'impressed teen boy voice, bright warm admiring delivery throughout' },
      { speaker: 'aoi_barista', jp: '今夜、ラジオで放送されるよ。', en: "It airs on the radio tonight.", style: 'excited barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'ファンとして、絶対聴かなきゃ!', en: "As a fan, I absolutely have to listen!", style: 'eager teen boy voice, bright warm determined delivery throughout' },
      { speaker: 'aoi_barista', jp: '放送の後、感想を言い合おうね!', en: "After the broadcast, let's share thoughts!", style: 'cheerful barista voice, soft warm bubbly delivery throughout' },
    ]),

  C('conv_02473',
    'Yuki and Kenji finalize an event schedule.',
    'WIDENED SCENARIO: event planning; time vocabulary (時刻/開始/終了/同時に) in natural home.',
    'office_quiet_low',
    ['時刻', '開始', '終了', '同時に', '現在'],
    ['yuki_office', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '開始の時刻は、決まりましたか?', en: "Has the start time been decided?", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '現在、午前十時で調整しています。', en: "Currently, we're arranging for 10 a.m.", style: 'clear office man voice, soft warm focused delivery throughout' },
      { speaker: 'yuki_office', jp: '終了の時刻は、何時頃ですか?', en: "Around what time does it end?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '終了は、午後三時の予定です。', en: "It's scheduled to end at 3 p.m.", style: 'precise office man voice, soft warm focused delivery throughout' },
      { speaker: 'yuki_office', jp: '受付は、開始と同時に始めますか?', en: "Does reception start at the same time as the opening?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'いえ、開始の三十分前に始めます。', en: "No, it starts thirty minutes before.", style: 'clear office man voice, soft warm focused delivery throughout' },
      { speaker: 'yuki_office', jp: '二つの会場で、同時に進めるんですね。', en: "So we run two venues simultaneously.", style: 'understanding office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'はい、現在、人員を確認中です。', en: "Yes, we're currently checking staffing.", style: 'reliable office man voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02474',
    'Saito explains a mental-health checkup to a patient.',
    'WIDENED SCENARIO: medical explanation; clinical vocabulary (精神/男性/障害/御) in natural home.',
    'clinic_room_quiet',
    ['精神', '男性', '障害', '御', '自己'],
    ['saito_doctor', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '最近、よく眠れないんです。', en: "Lately I can't sleep well.", style: 'tired office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '精神的な疲れが、出ているようですね。', en: "It seems mental fatigue is showing.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: 'これは、何かの障害でしょうか?', en: "Is this some kind of disorder?", style: 'worried office man voice, soft warm anxious delivery throughout' },
      { speaker: 'saito_doctor', jp: '重い障害ではありません。御安心下さい。', en: "It's not a serious disorder. Please rest assured.", style: 'gentle doctor voice, soft warm reassuring compassionate clarity throughout' },
      { speaker: 'kenji_office', jp: '同年代の男性にも、多いんですか?', en: "Is it common among men my age too?", style: 'curious office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '働く男性に、よく見られます。', en: "It's often seen in working men.", style: 'informative doctor voice, soft warm measured clarity throughout' },
      { speaker: 'kenji_office', jp: '自己流で、休んでも大丈夫ですか?', en: "Is it okay to rest in my own way?", style: 'earnest office man voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '自己判断より、御相談下さいね。', en: "Rather than self-judgment, please consult me.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_02475',
    'Grandpa tells Sho about old days, with archaic register.',
    'WIDENED SCENARIO: elder storytelling; archaic/negation forms (ぬ/無い/全く/八) in natural home.',
    'tatami_room_quiet',
    ['ぬ', '無い', '全く', '八', 'その後'],
    ['goro_grandpa', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おじいちゃん、昔は車あったの?', en: "Grandpa, were there cars long ago?", style: 'curious small child voice, bright warm earnest delivery throughout' },
      { speaker: 'goro_grandpa', jp: '昔は、車など全く無かったのじゃ。', en: "Long ago there were no cars at all.", style: 'gravelly old man voice, soft warm slow nostalgic delivery throughout' },
      { speaker: 'sho_child', jp: 'えっ、じゃあどうやって行ったの?', en: "Huh, then how did you get around?", style: 'surprised small child voice, bright warm wide-eyed delivery throughout' },
      { speaker: 'goro_grandpa', jp: '歩くしか、道は無かったのよ。', en: "There was no way but to walk.", style: 'gravelly old man voice, soft warm slow nostalgic delivery throughout' },
      { speaker: 'sho_child', jp: '遠くても、歩いたの?', en: "Even if it was far, you walked?", style: 'amazed small child voice, bright warm earnest delivery throughout' },
      { speaker: 'goro_grandpa', jp: '八里の道も、歩いて行かねばならぬ。', en: "Even a road of eight ri, we had to walk.", style: 'gravelly old man voice, soft warm slow nostalgic delivery throughout' },
      { speaker: 'sho_child', jp: 'その後、車が来たの?', en: "After that, did cars come?", style: 'engaged small child voice, bright warm curious delivery throughout' },
      { speaker: 'goro_grandpa', jp: 'その後、村にも一台、八台と増えたわ。', en: "After that, the village got one, then eight.", style: 'gravelly old man voice, soft warm fond nostalgic delivery throughout' },
    ]),

  C('conv_02476',
    'Hiroshi-boss gives Yuki year-end formal instructions.',
    'WIDENED SCENARIO: business keigo; ceremonial vocabulary (につきまして/なし/年度/等) in natural home.',
    'office_quiet_low',
    ['につきまして', 'なし', '年度', '等', '御'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '年度末の処理につきまして、確認しよう。', en: "Let's confirm the year-end processing.", style: 'formal boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '書類等は、すでに揃っています。', en: "The documents and so on are already gathered.", style: 'reliable office woman voice, soft warm professional clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '不足は、なしということでいいかね?', en: "So there are no shortfalls, correct?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'はい、問題なしと確認しました。', en: "Yes, I confirmed there are no problems.", style: 'confident office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '新年度につきましても、準備を頼む。', en: "Please prepare for the new fiscal year too.", style: 'formal boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '備品等も、来年度分を手配します。', en: "I'll arrange supplies and such for next year.", style: 'reliable office woman voice, soft warm professional clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '御苦労だが、よろしく頼むよ。', en: "It's a lot, but I count on you.", style: 'warm boss voice, soft warm appreciative closing throughout' },
      { speaker: 'yuki_office', jp: '御任せ下さい。漏れなく進めます。', en: "Leave it to me. I'll proceed without omissions.", style: 'resolved office woman voice, soft warm sincere closing throughout' },
    ]),

  C('conv_02477',
    'Ren interviews a researcher about a survey method.',
    'WIDENED SCENARIO: research interview; method vocabulary (述べ/基準/自己/知識) in natural home.',
    'office_quiet_low',
    ['述べ', '基準', '自己', '行う', '法律'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '調査は、どんな基準で行うんですか?', en: "By what standard do you conduct the survey?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: '公平な基準を、まず定めます。', en: "First we set a fair standard.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '対象者は、自己申告するんですか?', en: "Do participants self-report?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、自己申告を基に分析を行います。', en: "Yes, we analyze based on self-reports.", style: 'patient researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '個人の法律上の権利は、守られますか?', en: "Are individuals' legal rights protected?", style: 'serious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '法律に従い、情報を厳重に守ります。', en: "Following the law, we strictly protect information.", style: 'firm researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '結果は、どこで述べられますか?', en: "Where are the results stated?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '論文で、結論を述べる予定です。', en: "We plan to state the conclusions in a paper.", style: 'composed researcher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02478',
    'Ren and Mei chat casually after a long day.',
    'Casual register reusing common stragglers (彼ら/使わ/すでに/とにかく) naturally.',
    'cafe_quiet_chatter',
    ['彼ら', '使わ', 'すでに', 'とにかく', '全く'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '今日の打ち合わせ、長かったね。', en: "Today's meeting was long.", style: 'tired young man voice, soft warm relaxed delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、彼らの説明、長すぎたよね。', en: "Yeah, their explanation was too long.", style: 'soft warm woman voice, gentle relaxed delivery throughout' },
      { speaker: 'ren_uni', jp: '資料は、すでに読んでたのにね。', en: "We'd already read the materials, though.", style: 'mildly exasperated young man voice, soft warm relaxed delivery throughout' },
      { speaker: 'mei_romantic', jp: '彼ら、同じ言葉を何度も使ってた。', en: "They used the same words over and over.", style: 'gentle woman voice, soft warm amused delivery throughout' },
      { speaker: 'ren_uni', jp: '難しい言葉ばかり使われて、疲れたよ。', en: "So many hard words were used; I'm tired.", style: 'weary young man voice, soft warm relaxed delivery throughout' },
      { speaker: 'mei_romantic', jp: '全く、もっと簡単でいいのにね。', en: "Honestly, it could be much simpler.", style: 'soft woman voice, gentle warm sympathetic delivery throughout' },
      { speaker: 'ren_uni', jp: 'とにかく、今日は早く休もう。', en: "Anyway, let's rest early today.", style: 'gentle young man voice, soft warm caring delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、とにかくお茶でも飲もう。', en: "Yeah, let's at least have some tea.", style: 'warm woman voice, gentle affectionate delivery throughout' },
    ]),

  C('conv_02479',
    'Kenji and Ren discuss a software program at work.',
    'WIDENED SCENARIO: tech chat; software vocabulary (プログラム/通信/開始/終了) in natural home.',
    'office_quiet_low',
    ['プログラム', '通信', '開始', '終了', 'アクセス'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'このプログラム、動きが遅いんです。', en: "This program runs slowly.", style: 'mildly frustrated young colleague voice, soft warm earnest throughout' },
      { speaker: 'kenji_office', jp: '通信に、時間がかかっていますね。', en: "The communication is taking time.", style: 'analytical office man voice, soft warm focused guiding throughout' },
      { speaker: 'ren_uni', jp: '一度、プログラムを終了しましょうか?', en: "Shall we close the program once?", style: 'engaged young colleague voice, soft warm earnest throughout' },
      { speaker: 'kenji_office', jp: 'ええ、終了して、開始し直して下さい。', en: "Yes, close it and start again.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: '開始したら、通信が速くなりました。', en: "After starting, the connection got faster.", style: 'relieved young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: 'サーバーへのアクセスも、安定しましたね。', en: "Access to the server stabilized too.", style: 'satisfied office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '次から、通信を先に確認します。', en: "Next time I'll check the connection first.", style: 'resolved young colleague voice, soft warm appreciative throughout' },
    ]),

  C('conv_02480',
    'Asuka lectures on similarity and difference in art.',
    'WIDENED SCENARIO: art lecture; analytical vocabulary (同様/または/含め/最も) in natural home.',
    'lecture_hall_quiet',
    ['同様', 'または', '含め', '最も', 'いわゆる'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '絵は、色または線で印象が決まります。', en: "A painting's impression is set by color or line.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '音楽も、同様なんですか?', en: "Is music the same?", style: 'attentive adult student voice, soft warm curious engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、音楽も同様に、構成が大切です。', en: "Yes, in music too, structure matters similarly.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'いわゆる名作には、共通点がありますか?', en: "Do so-called masterpieces share traits?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '余白を含め、全体の調和が見事です。', en: "Including the blank space, the whole harmony is superb.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '最も大切なのは、何でしょうか?', en: "What matters most?", style: 'engaged adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '最も大切なのは、作り手の心です。', en: "What matters most is the maker's heart.", style: 'warm teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '技術を含め、心が伝わるんですね。', en: "Including technique, the heart comes through.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_124 wrote', CONVERSATIONS.length, 'files');
