import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_112)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02221',
    context: 'Sho-young watches a soccer match on TV with Daichi.',
    purpose: 'Father and son sharing sport excitement.',
    ambient: 'living_room_tv_loud',
    sound_effects: [],
    target_vocab: ['呼ぶ', '飛ん', '角', '開き', '広がっ', '勝負', '答える', '応援'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、ボール、すごく飛んだ!', en: "Dad — ball, super flew!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、角から、ようけ広がって攻めとる。', en: "Yeah — corner from, much spread attacking.", style: 'animated Kansai father voice, bright warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: '実況、応援、呼ぶ声、聞こえる?', en: "Commentary — cheer, calling voice, hear?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、皆、開きやすい場所、攻めとる!', en: "Yeah — all, open place, attack!", style: 'warm Kansai father voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: '勝負、どっち勝つかな?', en: "Match — which win?", style: 'eager child boy voice, bright warm hopeful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '答えるの、難しい、最後まで応援!', en: "Answer — hard, end-to cheer!", style: 'warm Kansai husband voice, soft warm passionate delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、頑張れー!', en: "Yeah — go!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02222',
    context: 'Aoi explains nutrition basics to Hina-young at the cafe.',
    purpose: 'Adult informally teaching teen about food.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['筋肉', '保健', '健康', '答える', '飲む', '良く', '心配', '丁寧'],
    cast: ['aoi_barista', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '蒼さん、筋肉、ようけ食べたら付く?', en: "Aoi — muscle, much eat, attaches?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: '保健的に、健康な食事、大事ね。', en: "Health-wise — healthy meal, matters.", style: 'gentle adult woman voice, soft warm informative delivery carefully' },
      { speaker: 'hina_child', jp: '答えてもらえて、嬉しい。', en: "Answered — happy.", style: 'soft teen girl voice, warm warm grateful delivery carefully' },
      { speaker: 'aoi_barista', jp: '水も、よく飲んでね、毎日。', en: "Water — well drink, daily.", style: 'warm adult woman voice, soft warm caring delivery carefully' },
      { speaker: 'hina_child', jp: '心配しないで、丁寧にやる!', en: "Don't worry — carefully do!", style: 'soft committed teen girl voice, warm warm earnest delivery carefully' },
      { speaker: 'aoi_barista', jp: '良く考えて、無理せずね。', en: "Well think — without overdoing.", style: 'tender adult woman voice, soft warm advising delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、ありがとう!', en: "Yes — thanks!", style: 'bright teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02223',
    context: 'Mei looks at Sho-young\'s eye irritation; small medical concern.',
    purpose: 'Mother checking child\'s minor health issue.',
    ambient: 'bathroom_morning_quiet',
    sound_effects: [],
    target_vocab: ['眼', '症状', '心配', '低く', '安心', '熱い', '抑える', '優しい'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、眼、ちょっと変。', en: "Mom — eye, slightly strange.", style: 'soft worried child boy voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '見せて、症状、深い?', en: "Show — symptom, deep?", style: 'soft worried young mother voice, warm warm caring delivery carefully' },
      { speaker: 'sho_child', jp: '熱い感じ、する。', en: "Hot feel — exists.", style: 'tearful child boy voice, soft warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '心配いらない、症状、低いから。', en: "No worry — symptom, low.", style: 'tender young mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: '安心、お母さんといると。', en: "Relief — with Mom.", style: 'soft tender child boy voice, warm warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: '優しく、抑える薬、塗ろうね。', en: "Gently — soothing medicine, apply.", style: 'warm young mother voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、ありがとう、お母さん。', en: "Yeah — thanks, Mom.", style: 'soft grateful child boy voice, warm warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_02224',
    context: 'Naoko proudly serves a new cheese-based dish; Yumiko tastes.',
    purpose: 'Two older women in food experiment.',
    ambient: 'ramen_shop_evening',
    sound_effects: [],
    target_vocab: ['チーズ', '味', '濃い', '感心', '料理', '尽くし', '改良', '気軽'],
    cast: ['naoko_aunt', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '姉ちゃん、新しい料理、試して!', en: "Sister — new dish, try!", style: 'animated Kansai aunt voice, bright warm enthusiastic delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、チーズ、入ってるの?', en: "Oh — cheese, contained?", style: 'gentle older mother voice, soft warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: '濃い味、ようけ尽くして作ったで!', en: "Dense taste — much devoted made!", style: 'brassy Kansai aunt voice, bright warm proud delivery carefully' },
      { speaker: 'yumiko_mom', jp: '感心するわ、改良してる。', en: "Impressed — improved.", style: 'warm older mother voice, soft warm appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '気軽に、お客さんに、出せる味や!', en: "Casually — customers, can serve flavor!", style: 'tender Kansai aunt voice, soft warm cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'いいわね、皆、喜ぶ。', en: "Lovely — all, pleased.", style: 'tender older mother voice, soft warm proud delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おおきに、ほめてくれて!', en: "Thanks — praising!", style: 'warm Kansai aunt voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02225',
    context: 'Saito and Asuka watch a political talk show; quiet commentary.',
    purpose: 'Married couple parsing news critically.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['野党', '両者', '主張', '関東', '九州', '対応', '結局', '中学生'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'あすか、両者の主張、面白いな。', en: "Asuka — both arguments, interesting.", style: 'measured doctor voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '野党の意見、深く考えてるね。', en: "Opposition view — deeply thinking.", style: 'composed teacher voice, soft warm thoughtful delivery carefully' },
      { speaker: 'saito_doctor', jp: '関東の方々と、九州の対応、違うね。', en: "Kanto folks and — Kyushu response, differ.", style: 'gentle doctor voice, soft warm observant delivery carefully' },
      { speaker: 'asuka_teacher', jp: '結局、地域、ようけ違う考え方。', en: "After all — region, much different thinking.", style: 'soft teacher voice, warm warm reflective delivery carefully' },
      { speaker: 'saito_doctor', jp: '中学生、こういう議論、関心持ってほしい。', en: "Middle school — such debate, interest want hold.", style: 'warm doctor voice, soft warm philosophical delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'うん、教育、続けていきたいわ。', en: "Yeah — education, want continue.", style: 'tender teacher voice, soft warm committed delivery carefully' },
      { speaker: 'saito_doctor', jp: 'お互い、社会への関わり、大事や。', en: "Each — society involvement, matters.", style: 'soft doctor voice, warm warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02226',
    context: 'Hina-young decorates her bedroom with new posters.',
    purpose: 'Teen decorating personal space.',
    ambient: 'bedroom_afternoon_quiet',
    sound_effects: [],
    target_vocab: ['置き', '飾っ', '看板', '広がり', '感心', '丁寧', '部屋', '雰囲気'],
    cast: ['hina_child', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、ポスター、ここに置きたい!', en: "Mei — poster, here want place!", style: 'eager teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'いいね、飾るの楽しい!', en: "Lovely — decorating fun!", style: 'tender young woman voice, soft warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: '看板みたい、感じになるね!', en: "Sign-like — feel becomes!", style: 'thrilled teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '丁寧に貼ってあるね、感心。', en: "Carefully pasted — impressed.", style: 'warm young woman voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: '広がりがあって、部屋らしい。', en: "Spaciousness exists — room-like.", style: 'soft teen girl voice, warm warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '雰囲気、本当に変わったね。', en: "Mood — truly changed.", style: 'tender young woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、嬉しい、ありがとう!', en: "Yeah — happy, thanks!", style: 'bright teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02227',
    context: 'Daichi takes Mei to a casual jazz club; relaxed adult night.',
    purpose: 'Couple having grown-up night out.',
    ambient: 'jazz_bar_warm_low',
    sound_effects: [],
    target_vocab: ['気軽', '丁寧', 'ブラック', '味わい', '心', '愛情', '雰囲気', '深く'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、ブラック、飲む?', en: "Mei — black, drink?", style: 'soft warm Kansai husband voice, warm warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: 'はい、気軽に、頼むわ。', en: "Yes — casually, ask.", style: 'tender young wife voice, soft warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '丁寧に淹れてるな、ここ。', en: "Carefully brewing — here.", style: 'warm Kansai husband voice, soft warm appreciative delivery carefully' },
      { speaker: 'mei_romantic', jp: '味わい、心に染みるね。', en: "Flavor — heart soaks.", style: 'tender young wife voice, soft warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前との時間、愛情、ようけ感じる。', en: "With you time — love, much feel.", style: 'soft Kansai husband voice, warm warm tender delivery carefully' },
      { speaker: 'mei_romantic', jp: '雰囲気、本当にいい、深くて。', en: "Mood — truly fine, deep.", style: 'tender young wife voice, soft warm fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'こんな夜、もっと、過ごそう。', en: "Night like this — more, spend.", style: 'warm Kansai husband voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02228',
    context: 'Sho-young plays a board game with Naoko; competitive moment.',
    purpose: 'Aunt and child sharing playful game.',
    ambient: 'tatami_quiet_lamp',
    sound_effects: [],
    target_vocab: ['打ち', '勝負', '集める', '夢中', '抑える', '当たる', '止める', '逆転'],
    cast: ['naoko_aunt', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '翔、わし、本気で打ち合うで!', en: "Sho — I, seriously play!", style: 'animated Kansai aunt voice, bright warm playful delivery carefully' },
      { speaker: 'sho_child', jp: 'おばちゃん、勝負、本気!', en: "Auntie — match, serious!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'こっちのコマ、集めるで!', en: "This piece — gather!", style: 'firm Kansai aunt voice, bright warm decisive delivery carefully' },
      { speaker: 'sho_child', jp: '夢中になっちゃう、面白い!', en: "Get absorbed — fun!", style: 'eager child boy voice, soft warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: '抑えるの、難しいで、わしを!', en: "Hold — hard, me!", style: 'animated Kansai aunt voice, bright warm playful delivery carefully' },
      { speaker: 'sho_child', jp: '止めることできない、勝つで!', en: "Stop can't — win!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、当たるか、逆転やな!', en: "Heh — hit, reversal!", style: 'warm Kansai aunt voice, soft warm playful delivery carefully' },
    ],
  },
  {
    id: 'conv_02229',
    context: 'Hiroshi-elder reminisces about a Buddhist temple visit long ago.',
    purpose: 'Elder telling reflective spiritual story.',
    ambient: 'tatami_evening_quiet',
    sound_effects: [],
    target_vocab: ['仏教', '振り返っ', '深く', '昔', '巨大', '輝い', '尊重', '心'],
    cast: ['hiroshi_elder', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'さくら、昔、巨大な仏教のお寺、行った。', en: "Sakura — past, huge Buddhist temple, went.", style: 'slow elder Kansai voice, warm warm reminiscent delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、どんな所?', en: "Oh — what place?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '輝いとった、夕日、心に残ってる。', en: "Shining — sunset, heart remains.", style: 'tender elder Kansai voice, soft warm reverent delivery carefully' },
      { speaker: 'sakura_teen', jp: '深く尊重、感じる場所だったんですね。', en: "Deeply respect — feel place was.", style: 'soft adult writer voice, warm warm appreciative delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '振り返ったら、人生、ようけ学んだ。', en: "Looked back — life, much learned.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '今でも、心、生きてるんですね。', en: "Even now — heart, living.", style: 'tender adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ようけ、生かしてる。', en: "Yeah — much, utilizing.", style: 'tender elder Kansai voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_02230',
    context: 'Ren and Kenji discuss a new manga art technique.',
    purpose: 'Two artists exchanging craft ideas.',
    ambient: 'studio_lamp_quiet',
    sound_effects: [],
    target_vocab: ['動かし', 'こだわり', '創作', '角度', '伸ばし', '構え', '尊重', '結局'],
    cast: ['ren_uni', 'kenji_office'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '健司さん、線、動かし方、難しいです。', en: "Kenji — line, move way, hard.", style: 'soft young man voice, warm warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'こだわり、ようけ持っとるな、お前。', en: "Conviction — much hold, you.", style: 'warm Kansai man voice, soft warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: '創作の角度、もっと伸ばしたい。', en: "Creation angle — more want extend.", style: 'composed young man voice, soft warm earnest delivery carefully' },
      { speaker: 'kenji_office', jp: '構えすぎると、伸ばしの自由が消える。', en: "Over-prepare — extension freedom fades.", style: 'gentle Kansai man voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: 'お互いの作風、尊重したいです。', en: "Each style — want respect.", style: 'tender young man voice, soft warm respectful delivery carefully' },
      { speaker: 'kenji_office', jp: '結局、自分らしさ、見つけることや。', en: "After all — self-likeness, finding.", style: 'warm Kansai man voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、頑張ります。', en: "Yes — try.", style: 'humble young man voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02231',
    context: 'Aoi and Sakura visit a small antique shop; appraising old items.',
    purpose: 'Two friends exploring vintage finds.',
    ambient: 'shop_low_traditional',
    sound_effects: [],
    target_vocab: ['屋根', '薄い', '巨大', '感心', '尊重', '広がり', '隠さ', '透明'],
    cast: ['aoi_barista', 'sakura_teen'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'さくら、この古い屋根瓦、薄いね。', en: "Sakura — this old roof tile, thin.", style: 'soft adult woman voice, warm warm observant delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、巨大な歴史、感じる。', en: "Oh — huge history, feel.", style: 'tender adult writer voice, soft warm awed delivery carefully' },
      { speaker: 'aoi_barista', jp: '職人さんの仕事、感心するわ。', en: "Artisan work — impressed.", style: 'warm adult woman voice, soft warm reverent delivery carefully' },
      { speaker: 'sakura_teen', jp: '尊重したい、長年の文化。', en: "Want respect — long-year culture.", style: 'soft adult writer voice, warm warm reverent delivery carefully' },
      { speaker: 'aoi_barista', jp: '伝統の広がり、今でも残ってる。', en: "Tradition spread — even now remains.", style: 'gentle adult woman voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '隠さない美しさ、透明な感じね。', en: "Not-hiding beauty — transparent feel.", style: 'tender adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'aoi_barista', jp: '記事に、ぜひ書いてね。', en: "Article — please write.", style: 'warm adult woman voice, soft warm encouraging delivery carefully' },
    ],
  },
  {
    id: 'conv_02232',
    context: 'Mei reorganizes the laundry; Daichi helps casually.',
    purpose: 'Couple in light domestic activity.',
    ambient: 'laundry_room_low',
    sound_effects: [],
    target_vocab: ['移し', 'やめる', 'ベルト', '焼い', '片付け', '夢中', 'レジ', '済ん'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、洗濯物、移してくれる?', en: "Daichi — laundry, move?", style: 'soft young wife voice, warm warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、片付けるわ。', en: "Yeah — clean.", style: 'warm Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: 'やめる前に、夢中、なってる!', en: "Quit before — absorbed!", style: 'animated young wife voice, bright warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ベルト、ようけ、片付けたで!', en: "Belt — much, cleaned!", style: 'soft Kansai husband voice, warm warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: '焼いたケーキ、後で食べようね。', en: "Baked cake — later eat.", style: 'gentle young woman voice, soft warm fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'レジ、買い物、後で済ますわ。', en: "Register — shopping, later finish.", style: 'composed Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、頼もしい!', en: "Thanks — reliable!", style: 'tender young wife voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02233',
    context: 'Hina-young helps a Yumiko move boxes in the closet; small chore.',
    purpose: 'Teen helping grandmother with seasonal cleanup.',
    ambient: 'storage_room_lamp_quiet',
    sound_effects: [],
    target_vocab: ['ビン', 'あんなに', '博', '欠か', '移し', '焼い', '済ん', '名刺'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、このビン、ようけある!', en: "Grandma — this bottle, much exists!", style: 'awed teen girl voice, soft warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'あんなに、集めたわよ、長年。', en: "That much — gathered, long years.", style: 'soft older mother voice, warm warm fond delivery carefully' },
      { speaker: 'hina_child', jp: '博物館みたい!', en: "Museum-like!", style: 'thrilled teen girl voice, bright warm awed delivery carefully' },
      { speaker: 'yumiko_mom', jp: '欠かしてない箱、移して片付けようね。', en: "Not-missing box — move clean.", style: 'gentle older mother voice, soft warm helpful delivery carefully' },
      { speaker: 'hina_child', jp: '昔の名刺、見つけた!', en: "Old card — found!", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'yumiko_mom', jp: '懐かしい、焼いて、記念に残そう。', en: "Nostalgic — burn, memory leave.", style: 'tender older mother voice, soft warm reminiscent delivery carefully' },
      { speaker: 'hina_child', jp: '済んだら、お茶しよう!', en: "Done — tea!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02234',
    context: 'Tatsuya-country shows Sho-young how to identify rice quality.',
    purpose: 'Elder farmer teaching child agricultural skill.',
    ambient: 'porch_rice_low',
    sound_effects: [],
    target_vocab: ['農業', '田んぼ', '皮', '濃い', '実', '丁寧', '実際', '深く'],
    cast: ['tatsuya_country', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '翔、お米、皮、見てみ。', en: "Sho — rice, skin, look.", style: 'slow Tohoku farmer voice, warm warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'おじいちゃん、濃い色、いいの?', en: "Grandpa — dense color, good?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: '実、丁寧に育って、できとるな。', en: "Grain — carefully grown, done.", style: 'gentle Tohoku voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '田んぼ、深く、皆さんが育ててる?', en: "Paddy — deep, all raise?", style: 'thoughtful child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: '実際、長年、皆で、頑張ってきた。', en: "Actually — long years, all, tried.", style: 'warm Tohoku farmer voice, soft warm reverent delivery carefully' },
      { speaker: 'sho_child', jp: '農業、すごい仕事やな!', en: "Farming — amazing work!", style: 'awed child boy voice, bright warm admiring delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お前も、いつか、覚えてな。', en: "You too — someday, remember.", style: 'tender Tohoku voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02235',
    context: 'Yuki-office helps Ren find a new apartment listing.',
    purpose: 'Friend helping with practical move logistics.',
    ambient: 'cafe_afternoon_lamp',
    sound_effects: [],
    target_vocab: ['移っ', '住所', '本屋', '安い', '便利', '広場', '丁寧', '日程'],
    cast: ['yuki_office', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: '蓮くん、新しい部屋に移ってみる?', en: "Ren — new room move try?", style: 'composed office woman voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、住所、変わるかもしれません。', en: "Yes — address, may change.", style: 'soft young man voice, warm warm honest delivery carefully' },
      { speaker: 'yuki_office', jp: '本屋にも、近い、便利な場所。', en: "Bookstore too — close, convenient place.", style: 'gentle office woman voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: '広場、ようけあって、安いから良いです。', en: "Plaza — much exists, cheap good.", style: 'tender young man voice, soft warm content delivery carefully' },
      { speaker: 'yuki_office', jp: '丁寧に、契約見ようね。', en: "Carefully — contract see.", style: 'warm office woman voice, soft warm careful delivery carefully' },
      { speaker: 'ren_uni', jp: '日程、お送りします。', en: "Schedule — send.", style: 'composed young man voice, soft warm professional delivery carefully' },
      { speaker: 'yuki_office', jp: '一緒に、行きましょう。', en: "Together — go.", style: 'tender office woman voice, soft warm friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_02236',
    context: 'Daichi joins a community recycling event; tells Mei after.',
    purpose: 'Husband sharing volunteer experience.',
    ambient: 'home_evening_warm',
    sound_effects: [],
    target_vocab: ['寄付', '関わり', '熱心', '集める', '気軽', '皆さん', '尽くし', '深く'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、今日、寄付活動に関わってきた。', en: "Mei — today, donation event involved.", style: 'warm Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、皆さん、熱心だった?', en: "Oh — all, passionate?", style: 'soft young wife voice, warm warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '気軽に、集めた物資、ようけあった。', en: "Casually — gathered goods, much existed.", style: 'gentle Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '深く考えなくても、参加できるのね。', en: "Without deep thought — can participate.", style: 'composed young wife voice, soft warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、皆さんに尽くしてもらった。', en: "Yeah — all devoted got.", style: 'soft Kansai husband voice, warm warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'こういう関わり、続けていきたいね。', en: "Like this involvement — want continue.", style: 'tender young mother voice, soft warm committed delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、一緒にやろ。', en: "Yeah — together do.", style: 'warm Kansai husband voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02237',
    context: 'Sho-young learns about politics from Hiroshi-elder; child-level explanation.',
    purpose: 'Grandfather teaching grandchild civics simply.',
    ambient: 'porch_afternoon_quiet',
    sound_effects: [],
    target_vocab: ['野党', '主張', '関わら', '尽くし', '我々', '皆', '伝統', '時代'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、野党って、何?', en: "Grandpa — opposition, what?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '違う主張、する人たちや。', en: "Different argument — people do.", style: 'slow elder Kansai voice, warm warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: '皆、関わらなあかんの?', en: "All — must involve?", style: 'thoughtful child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '我々の社会、皆で尽くす、伝統や。', en: "Our society — all devote, tradition.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '時代、変わっても、大事なのね。', en: "Era — changing, matters.", style: 'soft thoughtful child boy voice, warm warm understanding delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、お前も、いつか参加するで。', en: "Yeah — you too, someday participate.", style: 'tender elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、ちゃんと、考える!', en: "Yeah — properly, think!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02238',
    context: 'Sakura interviews a young woman about being a tech engineer.',
    purpose: 'Writer profiling industry professional.',
    ambient: 'office_quiet_low',
    sound_effects: [],
    target_vocab: ['企業', '事業', '改善', '創造', '可能', '丁寧', '関連', '幅広く'],
    cast: ['sakura_teen', 'yuki_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'ゆきさん、企業で、どんな事業を?', en: "Yuki — company, what business?", style: 'gentle adult writer voice, soft warm professional inquiry delivered carefully' },
      { speaker: 'yuki_office', jp: '改善、ようけ提案できる仕事です。', en: "Improvement — much propose work.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '創造、毎日、できますか?', en: "Creation — daily, can?", style: 'curious adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: 'はい、可能、丁寧に、進められる。', en: "Yes — possible, carefully, advance.", style: 'soft office woman voice, warm warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '関連分野、幅広く、関わるんですね。', en: "Related field — broadly, involve.", style: 'tender adult writer voice, soft warm impressed delivery carefully' },
      { speaker: 'yuki_office', jp: '皆と協力する、いい仕事です。', en: "All cooperate — fine work.", style: 'warm office woman voice, soft warm proud delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事、心こめて書きます。', en: "Article — heart put write.", style: 'humble adult writer voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02239',
    context: 'Hina-young rehearses a dance for school festival; Mei coaches.',
    purpose: 'Mother coaching teen for school event.',
    ambient: 'living_room_practice_low',
    sound_effects: [],
    target_vocab: ['踊り', '練習', '繰り返し', '気軽', '緊張', '本番', '応援', '熱い'],
    cast: ['mei_romantic', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、踊り、本番、緊張する!', en: "Mei — dance, real, nervous!", style: 'nervous teen girl voice, soft warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '練習、繰り返し、しっかりやったね。', en: "Practice — repetition, properly did.", style: 'warm young mother voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '気軽に、できるかな?', en: "Casually — can?", style: 'soft worried teen girl voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '熱い気持ち、ようけ持って、踊って!', en: "Passionate feeling — much hold, dance!", style: 'tender young mother voice, soft warm passionate delivery carefully' },
      { speaker: 'hina_child', jp: '応援、お母さん、してくれる?', en: "Cheer — Mom, do?", style: 'soft hopeful teen girl voice, warm warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: 'もちろん、ずっと見てる!', en: "Of course — always watch!", style: 'tender young mother voice, soft warm steadfast delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、頑張る!', en: "Thanks — try!", style: 'soft determined teen girl voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02240',
    context: 'Whole group celebrates the cherry blossom season briefly together.',
    purpose: 'Multi-voice spring nature appreciation.',
    ambient: 'park_hanami_breeze',
    sound_effects: [],
    target_vocab: ['桜', '広がっ', '皆', '感謝', '春', '輝い', '心', '深く'],
    cast: ['hiroshi_elder', 'naoko_aunt', 'mei_romantic', 'daichi_kansai', 'sho_child', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '桜、ようけ咲いて、広がっとるな。', en: "Cherry — much bloom, spreading.", style: 'slow elder Kansai voice, warm warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: '輝いた春!皆で、ええ時間や!', en: "Shining spring — all, fine time!", style: 'brassy Kansai aunt voice, bright warm delighted delivery carefully' },
      { speaker: 'mei_romantic', jp: '深く、感謝の気持ち、感じる。', en: "Deeply — gratitude, feel.", style: 'tender young mother voice, soft warm reverent delivery carefully' },
      { speaker: 'daichi_kansai', jp: '心、温かい、皆おって。', en: "Heart — warm, all here.", style: 'warm Kansai husband voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '桜、すごく綺麗!', en: "Cherry — super pretty!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'hina_child', jp: '皆との時間、宝物!', en: "All time — treasure!", style: 'bright teen girl voice, soft warm grateful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'こうやって、長く、皆で過ごしような。', en: "Like this — long, all spend.", style: 'gentle elder Kansai voice, soft warm enduring delivery carefully' },
      { speaker: 'naoko_aunt', jp: '来年も、桜、見に来よう!', en: "Next year — cherry, come see!", style: 'animated Kansai aunt voice, bright warm committed delivery carefully' },
      { speaker: 'mei_romantic', jp: '家族、本当に、ありがたい。', en: "Family — truly, grateful.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええ春やな、ほんま。', en: "Fine spring — truly.", style: 'warm Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'sho_child', jp: '皆、大好き!', en: "All — love!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'こんな日、ずっと、続けばいい。', en: "Day like this — always, continue good.", style: 'tender teen girl voice, soft warm wishful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '家族、宝物や、本当に。', en: "Family — treasure, truly.", style: 'tender elder Kansai voice, soft warm humble delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_112 wrote', CONVERSATIONS.length, 'files');
