import fs from 'node:fs'; import path from 'node:path'; import url from 'node:url';
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_173)', generated_at: NOW, source_plan_row: '' });
const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 3, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // ===== CLUSTER A: travel & geography =====
  C('conv_03441', 'Friends dream up their next trip', 'Brainstorm a trip; teach アフリカ/欧米/香港/神戸/広島/わが国/直前/殆ど', 'cafe_quiet_chatter',
    ['アフリカ','欧米','香港','神戸','広島','わが国','直前','殆ど'], ['mei_romantic', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: '次は遠くに行きたい。アフリカとか。', en: 'Next I want to go far — Africa, maybe.', style: 'adventurous friend floating an idea' },
    { speaker: 'ren_uni', jp: 'いいね、欧米とは全然違う景色だろうね。', en: 'Nice — totally different scenery from Europe/America.', style: 'engaged friend agreeing' },
    { speaker: 'sakura_teen', jp: '私はアジアがいいな。香港の夜景見たい。', en: 'I prefer Asia. I want to see Hong Kong’s night view.', style: 'eager friend pitching' },
    { speaker: 'ren_uni', jp: '国内なら、神戸も魅力的だよ。', en: 'Domestically, Kobe is appealing too.', style: 'friend suggesting' },
    { speaker: 'mei_romantic', jp: '広島の平和記念公園にも行きたい。', en: 'I want to visit Hiroshima’s peace park too.', style: 'thoughtful friend adding' },
    { speaker: 'sakura_teen', jp: 'わが国にも、まだまだ訪れたい場所があるね。', en: 'There are still places in our country I want to visit.', style: 'reflective friend embracing home' },
    { speaker: 'ren_uni', jp: '直前まで予定が決まらないけど。', en: 'Plans aren’t set until just before departure, though.', style: 'wry friend admitting' },
    { speaker: 'mei_romantic', jp: '殆ど決めてないけど、それも楽しい。', en: 'Almost nothing’s decided, but that’s fun too.', style: 'easygoing friend enjoying spontaneity' },
  ]),
  C('conv_03442', 'Returning from a Hong Kong trip', 'Recount the trip; teach 香港/直前/殆ど/欧米/アフリカ/神戸/広島/わが国', 'cafe_quiet_chatter',
    ['香港','直前','殆ど','欧米','アフリカ','神戸','広島','わが国'], ['ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '香港旅行、どうだった？', en: 'How was the Hong Kong trip?', style: 'curious friend welcoming him back' },
    { speaker: 'ren_uni', jp: '出発の直前まで仕事だったから、疲れたよ。', en: 'I worked right up to departure, so I’m tired.', style: 'weary friend admitting' },
    { speaker: 'sakura_teen', jp: 'でも殆どの観光地は回れたんでしょ？', en: 'But you covered almost all the sights, right?', style: 'friend confirming' },
    { speaker: 'ren_uni', jp: 'うん、現地の食文化は欧米とは全然違う。', en: 'Yeah — the food culture is totally unlike Europe/America.', style: 'friend reflecting' },
    { speaker: 'sakura_teen', jp: '次はアフリカも視野に入れてる？', en: 'Are you considering Africa next too?', style: 'friend exploring further' },
    { speaker: 'ren_uni', jp: 'いつかね。国内では神戸と広島が候補。', en: 'Someday. Domestically, Kobe and Hiroshima are candidates.', style: 'friend planning' },
    { speaker: 'sakura_teen', jp: 'わが国の歴史も、もっと知りたいね。', en: 'I want to know our country’s history more too.', style: 'wistful friend closing' },
  ]),
  C('conv_03443', 'Comparing destinations together', 'Compare places; teach 欧米/香港/アフリカ/わが国/神戸/広島/直前/殆ど', 'cafe_quiet_chatter',
    ['欧米','香港','アフリカ','わが国','神戸','広島','直前','殆ど'], ['mei_romantic', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: '欧米と香港、どっちが楽しい？', en: 'Europe/America or Hong Kong — which is more fun?', style: 'friend posing a fun question' },
    { speaker: 'ren_uni', jp: 'それぞれ違う良さがあるよ。', en: 'Each has its own charms.', style: 'friend answering wisely' },
    { speaker: 'mei_romantic', jp: 'アフリカは未知の世界って感じだよね。', en: 'Africa feels like an unknown world.', style: 'curious friend imagining' },
    { speaker: 'ren_uni', jp: 'わが国にも、神戸や広島みたいに国際的な街がある。', en: 'In our country too, there are international cities like Kobe and Hiroshima.', style: 'friend grounding it locally' },
    { speaker: 'mei_romantic', jp: '旅って、直前のワクワクが好き。', en: 'I love the just-before-departure excitement.', style: 'friend savoring the feeling' },
    { speaker: 'ren_uni', jp: 'でも準備殆どできてないと、焦るよ。', en: 'But if you’ve barely prepped, you panic.', style: 'friend laughing wryly' },
    { speaker: 'mei_romantic', jp: 'それも旅の醍醐味だね。', en: 'That’s part of the joy of travel too.', style: 'friend embracing the chaos' },
  ]),
  C('conv_03444', 'A geography class reflection', 'Reflect on a class; teach 香港/欧米/アフリカ/わが国/神戸/広島/直前/殆ど', 'lecture_hall_quiet',
    ['香港','欧米','アフリカ','わが国','神戸','広島','直前','殆ど'], ['mei_romantic', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: '地理の授業で、世界の都市を学んでるんだ。', en: 'In geography, I’m learning world cities.', style: 'friend opening the topic' },
    { speaker: 'sakura_teen', jp: '香港は人口密度が高いんでしょ？', en: 'Hong Kong has high population density, right?', style: 'curious friend asking' },
    { speaker: 'mei_romantic', jp: 'そう。欧米の都市とは構造が違う。', en: 'Right — its structure differs from Europe/America.', style: 'friend explaining' },
    { speaker: 'sakura_teen', jp: 'アフリカの都市も、近代化が進んでるって。', en: 'African cities are modernizing too, they say.', style: 'informed friend adding' },
    { speaker: 'mei_romantic', jp: 'わが国だと、神戸や広島も特色ある街だね。', en: 'In our country, Kobe and Hiroshima have character too.', style: 'friend grounding the lesson' },
    { speaker: 'sakura_teen', jp: '直前のレポートで、殆ど徹夜だったよ。', en: 'Doing the report just before due, I pulled an almost-all-nighter.', style: 'tired friend lamenting' },
    { speaker: 'mei_romantic', jp: 'お疲れさま。世界は広いね。', en: 'Good work. The world is wide.', style: 'sympathetic friend closing warmly' },
  ]),
  C('conv_03445', 'Dreaming of the next big journey', 'Plan the next trip; teach わが国/アフリカ/香港/欧米/神戸/広島/直前/殆ど', 'living_room_quiet',
    ['わが国','アフリカ','香港','欧米','神戸','広島','直前','殆ど'], ['sakura_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '次は、わが国を出て、もっと遠くへ行きたい。', en: 'Next I want to leave our country and go farther.', style: 'restless friend wanting more' },
    { speaker: 'ren_uni', jp: 'アフリカのサファリも憧れるね。', en: 'A safari in Africa is a dream too.', style: 'friend dreaming aloud' },
    { speaker: 'sakura_teen', jp: '香港でショッピングも楽しい。', en: 'Shopping in Hong Kong is fun too.', style: 'friend listing options' },
    { speaker: 'ren_uni', jp: '欧米の文化も、深く知りたい。', en: 'I want to know Western culture deeply too.', style: 'curious friend' },
    { speaker: 'sakura_teen', jp: '国内では神戸の夜景、見たことある？', en: 'Have you seen Kobe’s night view?', style: 'friend asking' },
    { speaker: 'ren_uni', jp: '広島でお好み焼きを食べたい。', en: 'I want to eat okonomiyaki in Hiroshima.', style: 'friend craving food' },
    { speaker: 'sakura_teen', jp: '出発の直前まで、ワクワクするよね。', en: 'You keep buzzing right up to departure, right?', style: 'friend savoring anticipation' },
    { speaker: 'ren_uni', jp: '殆ど決まってないけど、それが旅。', en: 'Almost nothing’s set, but that’s travel.', style: 'easygoing friend closing' },
  ]),

  // ===== CLUSTER B: corporate executive meetings =====
  C('conv_03446', 'A board meeting opens', 'Open a board meeting; teach 取締役/幹部/当社/既存/民営/法的/解析/自立', 'office_quiet_low',
    ['取締役','幹部','当社','既存','民営','法的','解析','自立'], ['hiroshi_boss', 'kenji_office', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'hiroshi_boss', jp: '取締役会で、今後の方針を決める。', en: 'At the board, we decide future direction.', style: 'commanding boss opening' },
    { speaker: 'kenji_office', jp: '幹部のみなさん、準備はよろしいですか。', en: 'Executives, are you all ready?', style: 'organized manager calling order' },
    { speaker: 'yuki_office', jp: '当社の業績は、堅調です。', en: 'Our company’s results are solid.', style: 'assistant reporting cleanly' },
    { speaker: 'hiroshi_boss', jp: '既存の事業を整理する必要もある。', en: 'We must also tidy existing businesses.', style: 'boss raising a tough call' },
    { speaker: 'kenji_office', jp: '一部の部門の民営化も検討案にあります。', en: 'Privatizing some divisions is in the proposals too.', style: 'manager outlining options' },
    { speaker: 'hiroshi_boss', jp: '法的な手続きは、慎重に進めよう。', en: 'Let’s move carefully on the legal procedures.', style: 'boss urging caution' },
    { speaker: 'yuki_office', jp: '数字の解析結果を、共有します。', en: 'I’ll share the numerical analysis.', style: 'assistant presenting data' },
    { speaker: 'kenji_office', jp: '自立した経営体制を目指しましょう。', en: 'Let’s aim for self-sustaining management.', style: 'manager rallying the vision' },
  ]),
  C('conv_03447', 'A strategy session between mid-managers', 'Strategize; teach 取締役/幹部/当社/既存/民営/法的/解析/自立', 'office_quiet_low',
    ['取締役','幹部','当社','既存','民営','法的','解析','自立'], ['kenji_office', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'kenji_office', jp: '取締役会の決定を、現場に伝えよう。', en: 'Let’s convey the board’s decisions to the field.', style: 'manager planning communications' },
    { speaker: 'yuki_office', jp: '幹部のサポートも欠かせません。', en: 'Executive support is essential too.', style: 'assistant noting needs' },
    { speaker: 'kenji_office', jp: '当社の強みは、既存の顧客基盤にある。', en: 'Our strength lies in the existing customer base.', style: 'manager identifying core' },
    { speaker: 'yuki_office', jp: '民営化された業界では、競争が激しいです。', en: 'In privatized industries, competition is fierce.', style: 'assistant noting context' },
    { speaker: 'kenji_office', jp: '法的なリスクは、徹底的に解析しよう。', en: 'Let’s thoroughly analyze legal risks.', style: 'manager urging rigor' },
    { speaker: 'yuki_office', jp: '経営の自立性を、保たなければなりません。', en: 'We must preserve management’s autonomy.', style: 'principled assistant' },
    { speaker: 'kenji_office', jp: 'みんなで力を合わせよう。', en: 'Let’s combine our efforts.', style: 'manager rallying' },
  ]),
  C('conv_03448', 'Onboarding a new hire', 'Onboard a hire; teach 取締役/幹部/当社/既存/民営/法的/解析/自立', 'office_quiet_low',
    ['取締役','幹部','当社','既存','民営','法的','解析','自立'], ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'yuki_office', jp: '新入社員に、会社の仕組みを教えています。', en: 'I’m teaching new hires how the company works.', style: 'patient assistant explaining' },
    { speaker: 'hiroshi_boss', jp: '取締役と幹部の違いを、まず説明するといい。', en: 'Start with the difference between directors and executives.', style: 'boss advising' },
    { speaker: 'yuki_office', jp: '当社の歴史も大事ですね。', en: 'Our company’s history matters too.', style: 'assistant adding' },
    { speaker: 'hiroshi_boss', jp: '既存の部署と新規の挑戦、両方知ってほしい。', en: 'I want them to know both existing units and new challenges.', style: 'boss broadening scope' },
    { speaker: 'yuki_office', jp: '民営の競合との比較も、勉強になります。', en: 'Comparing with private competitors is instructive too.', style: 'assistant noting value' },
    { speaker: 'hiroshi_boss', jp: '法的な知識も、業務に役立つよ。', en: 'Legal knowledge helps the work too.', style: 'boss emphasizing learning' },
    { speaker: 'yuki_office', jp: 'データ解析の基礎も、教えています。', en: 'I teach the basics of data analysis too.', style: 'assistant noting curriculum' },
    { speaker: 'hiroshi_boss', jp: '自立した社員に育ってほしいな。', en: 'I want them to grow into independent staff.', style: 'boss closing warmly' },
  ]),
  C('conv_03449', 'Quarterly review at the board', 'Review the quarter; teach 取締役/幹部/当社/既存/民営/法的/解析/自立', 'office_quiet_low',
    ['取締役','幹部','当社','既存','民営','法的','解析','自立'], ['hiroshi_boss', 'kenji_office', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'hiroshi_boss', jp: '四半期の取締役会、結果を発表する。', en: 'At the quarterly board, we announce results.', style: 'boss opening crisply' },
    { speaker: 'kenji_office', jp: '幹部の判断が、業績を支えました。', en: 'Executive judgment supported the results.', style: 'manager crediting leadership' },
    { speaker: 'yuki_office', jp: '当社の売上は、前年比で改善しています。', en: 'Our company’s sales improved year-on-year.', style: 'assistant citing data' },
    { speaker: 'hiroshi_boss', jp: '既存事業の効率化が、効いたな。', en: 'Streamlining existing business worked.', style: 'boss noting the win' },
    { speaker: 'kenji_office', jp: '民営化への流れも、注視すべきです。', en: 'We should watch the privatization trend too.', style: 'manager raising vigilance' },
    { speaker: 'yuki_office', jp: '法的な対応も、滞りなく進めました。', en: 'Legal responses moved without delays too.', style: 'assistant reassuring' },
    { speaker: 'hiroshi_boss', jp: '細かい解析データ、よくまとめてくれた。', en: 'You compiled the detailed analysis well.', style: 'boss praising' },
    { speaker: 'kenji_office', jp: '自立した組織になりつつあります。', en: 'We’re becoming a self-sustaining organization.', style: 'manager noting growth' },
  ]),
  C('conv_03450', 'Year-end gathering of the leadership', 'Year-end recap; teach 取締役/幹部/当社/既存/民営/法的/解析/自立', 'office_quiet_low',
    ['取締役','幹部','当社','既存','民営','法的','解析','自立'], ['hiroshi_boss', 'kenji_office'], 'Medium (7-12)', [
    { speaker: 'hiroshi_boss', jp: '今年も、取締役会を無事に乗り切ったな。', en: 'We made it through this year’s board too.', style: 'relieved boss reflecting' },
    { speaker: 'kenji_office', jp: '幹部の協力なしには、難しかったです。', en: 'Without executive cooperation, it’d have been hard.', style: 'manager crediting peers' },
    { speaker: 'hiroshi_boss', jp: '当社、社員一同に感謝だ。', en: 'I’m grateful to all our company’s staff.', style: 'warm boss thanking' },
    { speaker: 'kenji_office', jp: '既存の顧客との関係も、深まりました。', en: 'Relationships with existing customers deepened too.', style: 'manager noting progress' },
    { speaker: 'hiroshi_boss', jp: '業界の民営化の動きにも、対応できた。', en: 'We adapted to the industry’s privatization moves too.', style: 'boss appraising' },
    { speaker: 'kenji_office', jp: '法的な観点でも、問題はありません。', en: 'No issues from a legal viewpoint either.', style: 'manager confirming' },
    { speaker: 'hiroshi_boss', jp: '解析チームが、本当に頑張ってくれた。', en: 'The analytics team really pulled through.', style: 'boss praising the team' },
    { speaker: 'kenji_office', jp: '来年も、自立した経営を続けましょう。', en: 'Next year too, let’s continue independent management.', style: 'manager closing forward-looking' },
  ]),

  // ===== CLUSTER C: sports training =====
  C('conv_03451', 'A training session for an upcoming meet', 'Train for a meet; teach 競技/スキル/マシン/エリア/必死/武器/神経/競馬', 'studio_room_tone',
    ['競技','スキル','マシン','エリア','必死','武器','神経','競馬'], ['ren_uni', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '今日も競技のためのトレーニングだ。', en: 'Today too, training for the competition.', style: 'focused athlete preparing' },
    { speaker: 'riku_teen', jp: 'スキルアップ、調子はどう？', en: 'How’s your skill-up going?', style: 'friend asking warmly' },
    { speaker: 'ren_uni', jp: '新しいマシンを使い始めたんだ。', en: 'I started using a new machine.', style: 'athlete sharing news' },
    { speaker: 'riku_teen', jp: '専用のエリアがあるんだね。', en: 'There’s a dedicated area, huh.', style: 'friend noticing' },
    { speaker: 'ren_uni', jp: '必死で取り組んでるよ。', en: 'I’m going at it with all I’ve got.', style: 'determined athlete' },
    { speaker: 'riku_teen', jp: 'スピードが君の武器だもんね。', en: 'Speed is your weapon, after all.', style: 'friend encouraging' },
    { speaker: 'ren_uni', jp: '神経を集中して、フォームを磨く。', en: 'I concentrate my nerves and polish form.', style: 'athlete describing focus' },
    { speaker: 'riku_teen', jp: 'ところで、競馬好きの先輩が応援に来るらしい。', en: 'By the way, a horse-racing-loving senior is coming to cheer.', style: 'friend sharing news' },
  ]),
  C('conv_03452', 'A coach checks in with the athlete', 'Coach the athlete; teach 競技/スキル/マシン/エリア/必死/武器/神経/競馬', 'studio_room_tone',
    ['競技','スキル','マシン','エリア','必死','武器','神経','競馬'], ['daichi_kansai', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'daichi_kansai', jp: '今日の競技、調子ええで。', en: 'Today’s competition form looks good.', style: 'Kansai coach approving warmly' },
    { speaker: 'ren_uni', jp: 'スキルが伸びてる気がします。', en: 'My skills feel like they’re growing.', style: 'athlete reporting' },
    { speaker: 'daichi_kansai', jp: 'あのマシン、もっと使い込んでみ。', en: 'Use that machine more thoroughly.', style: 'coach directing' },
    { speaker: 'ren_uni', jp: '奥のエリア、空いてますか？', en: 'Is the back area free?', style: 'athlete asking' },
    { speaker: 'daichi_kansai', jp: '空いとるで。必死さが伝わってくるわ。', en: 'It’s open. Your fierce drive comes through.', style: 'coach reading him' },
    { speaker: 'ren_uni', jp: '持久力を、自分の武器にしたいです。', en: 'I want endurance as my weapon.', style: 'athlete naming his aim' },
    { speaker: 'daichi_kansai', jp: '神経の使い方も、訓練やで。', en: 'How you use your nerves is training too.', style: 'coach teaching mental side' },
    { speaker: 'ren_uni', jp: '競馬で言うサラブレッドみたいに、磨きたいです。', en: 'Like a thoroughbred in horse racing, I want to polish.', style: 'athlete drawing a vivid parallel' },
  ]),
  C('conv_03453', 'On the day of the competition', 'Race day; teach 競技/スキル/マシン/エリア/必死/武器/神経/競馬', 'studio_room_tone',
    ['競技','スキル','マシン','エリア','必死','武器','神経','競馬'], ['ren_uni', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: '競技、いよいよ本番だね。', en: 'The competition is finally here.', style: 'excited friend pumped up' },
    { speaker: 'ren_uni', jp: '練習で身につけたスキルを、出すだけ。', en: 'I just bring out the skills I trained.', style: 'composed athlete focusing' },
    { speaker: 'riku_teen', jp: 'あのマシン、調子よさそう。', en: 'That machine looks good today.', style: 'friend reading the equipment' },
    { speaker: 'ren_uni', jp: 'ウォームアップエリアで、もう体は温まった。', en: 'In the warm-up area, my body’s already warm.', style: 'athlete ready to go' },
    { speaker: 'riku_teen', jp: '必死さが顔に出てるよ。', en: 'Your fierce focus shows on your face.', style: 'friend observing' },
    { speaker: 'ren_uni', jp: 'スピードが俺の武器だ。', en: 'Speed is my weapon.', style: 'athlete affirming himself' },
    { speaker: 'riku_teen', jp: '神経を切らさず、最後まで！', en: 'Don’t break your nerve to the finish!', style: 'friend cheering hard' },
    { speaker: 'ren_uni', jp: '競馬みたいに、ゴール一直線で行く。', en: 'Like horse racing, I’ll dash straight to the goal.', style: 'athlete with vivid resolve' },
  ]),
  C('conv_03454', 'Post-race debrief with the coach', 'Debrief after a race; teach 競技/スキル/マシン/エリア/必死/武器/神経/競馬', 'studio_room_tone',
    ['競技','スキル','マシン','エリア','必死','武器','神経','競馬'], ['daichi_kansai', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'daichi_kansai', jp: '今日の競技、ようやった。', en: 'You did well in today’s competition.', style: 'proud Kansai coach praising' },
    { speaker: 'ren_uni', jp: '練習のスキル、活かせました。', en: 'I used the skills from practice.', style: 'satisfied athlete reflecting' },
    { speaker: 'daichi_kansai', jp: 'あのマシン、フォーム改善に貢献したな。', en: 'That machine helped improve your form.', style: 'coach noting cause' },
    { speaker: 'ren_uni', jp: 'スタートエリアで、緊張しすぎたかな。', en: 'In the start area, I was maybe too tense.', style: 'athlete self-critiquing' },
    { speaker: 'daichi_kansai', jp: 'ええ、必死すぎるとよくない時もある。', en: 'Yeah, being too desperate isn’t always good.', style: 'coach offering balance' },
    { speaker: 'ren_uni', jp: 'でも武器の脚力は、最後まで保てました。', en: 'But I kept my leg-strength weapon to the end.', style: 'athlete noting the win' },
    { speaker: 'daichi_kansai', jp: '神経の太さは、本物や。', en: 'Your nerve is the real thing.', style: 'coach praising mental strength' },
    { speaker: 'ren_uni', jp: '競馬の名馬も、こんな気持ちなのかな。', en: 'I wonder if famous racehorses feel like this too.', style: 'athlete musing fondly' },
  ]),
  C('conv_03455', 'Looking ahead to the next race', 'Set new goals; teach 競技/スキル/マシン/エリア/必死/武器/神経/競馬', 'studio_room_tone',
    ['競技','スキル','マシン','エリア','必死','武器','神経','競馬'], ['ren_uni', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '次の競技、もう照準を合わせてる。', en: 'I’m already aiming for the next competition.', style: 'driven athlete looking ahead' },
    { speaker: 'riku_teen', jp: 'スキルの幅、広げていきたいね。', en: 'I want to widen my range of skills too.', style: 'friend matching ambition' },
    { speaker: 'ren_uni', jp: '新しいマシンを試したい。', en: 'I want to try a new machine.', style: 'athlete planning' },
    { speaker: 'riku_teen', jp: '練習エリアの予約、取っとくよ。', en: 'I’ll book the practice area.', style: 'helpful friend' },
    { speaker: 'ren_uni', jp: '必死に頑張る姿、応援する側も力をもらえる。', en: 'Watching desperate effort gives the cheering side strength too.', style: 'athlete reflecting on mutual support' },
    { speaker: 'riku_teen', jp: '君の武器、まだまだ伸びるよ。', en: 'Your weapon still has room to grow.', style: 'friend encouraging' },
    { speaker: 'ren_uni', jp: '神経を整えて、また挑戦する。', en: 'I’ll steady my nerves and challenge again.', style: 'athlete vowing' },
    { speaker: 'riku_teen', jp: '競馬みたいに、ペース配分も大事だね。', en: 'Like in horse racing, pacing matters too.', style: 'friend offering a tip' },
  ]),

  // ===== CLUSTER D: international-affairs discussion =====
  C('conv_03456', 'Following an international negotiation', 'Discuss diplomacy; teach 圧力/延長/行なわ/意義/払っ/あえて/そうすると/いわば', 'living_room_quiet',
    ['圧力','延長','行なわ','意義','払っ','あえて','そうすると','いわば'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '国際会議で、各国の圧力が強まっています。', en: 'At the international conference, countries’ pressure is mounting.', style: 'measured teacher framing' },
    { speaker: 'ren_uni', jp: '議論の期限が、再び延長されました。', en: 'The debate’s deadline was extended again.', style: 'student updating' },
    { speaker: 'sakura_teen', jp: '投票は、来週行なわれる予定です。', en: 'The vote will be conducted next week.', style: 'attentive teen reporting' },
    { speaker: 'asuka_teacher', jp: '今回の会議には、意義があると言えます。', en: 'You could say this conference has significance.', style: 'teacher offering analysis' },
    { speaker: 'ren_uni', jp: '各国とも、細部まで注意を払っています。', en: 'Every country is paying attention to details.', style: 'student noting care' },
    { speaker: 'sakura_teen', jp: '先生は、あえて批判的な視点も大事だと？', en: 'You think a deliberately critical view matters too?', style: 'teen pressing the teacher' },
    { speaker: 'asuka_teacher', jp: 'そうすると、議論が深まりますからね。', en: 'Doing so deepens the debate.', style: 'teacher affirming' },
    { speaker: 'ren_uni', jp: 'いわば、自国の利害を超えた対話、ですね。', en: 'So to speak, a dialogue beyond national interest.', style: 'student synthesizing' },
  ]),
  C('conv_03457', 'A student-teacher debate on sanctions', 'Debate sanctions; teach 圧力/延長/行なわ/意義/払っ/あえて/そうすると/いわば', 'lecture_hall_quiet',
    ['圧力','延長','行なわ','意義','払っ','あえて','そうすると','いわば'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '経済制裁は、圧力として有効ですか？', en: 'Are economic sanctions effective as pressure?', style: 'student raising a sharp question' },
    { speaker: 'asuka_teacher', jp: '効果が出るまで、時間の延長が必要なこともあります。', en: 'Time extensions are sometimes needed for effect.', style: 'teacher answering carefully' },
    { speaker: 'ren_uni', jp: '制裁が行なわれている期間、どう過ごすかが課題ですね。', en: 'How to spend the period while sanctions are conducted is the issue.', style: 'student probing further' },
    { speaker: 'asuka_teacher', jp: '制裁自体に意義があるのか、議論があります。', en: 'There’s debate on whether sanctions themselves have significance.', style: 'teacher acknowledging the controversy' },
    { speaker: 'ren_uni', jp: '各国が、慎重に注意を払っています。', en: 'Each country is paying careful attention.', style: 'student observing' },
    { speaker: 'asuka_teacher', jp: 'あえて立場を明確にすることも、大事です。', en: 'Deliberately clarifying one’s stance also matters.', style: 'teacher advising' },
    { speaker: 'ren_uni', jp: 'そうすると、誤解が減りますね。', en: 'Doing that reduces misunderstanding.', style: 'student following the logic' },
    { speaker: 'asuka_teacher', jp: 'いわば、対話の出発点になります。', en: 'So to speak, it becomes a starting point for dialogue.', style: 'teacher closing the thought' },
  ]),
  C('conv_03458', 'Analyzing a new agreement', 'Analyze an agreement; teach 圧力/延長/行なわ/意義/払っ/あえて/そうすると/いわば', 'lecture_hall_quiet',
    ['圧力','延長','行なわ','意義','払っ','あえて','そうすると','いわば'], ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '先生、今回の合意には大きな圧力があったとか。', en: 'Teacher, this agreement reportedly came under big pressure.', style: 'curious teen asking' },
    { speaker: 'asuka_teacher', jp: '各国は譲歩し、期限も延長されました。', en: 'Countries conceded, and the deadline was extended.', style: 'teacher recounting' },
    { speaker: 'sakura_teen', jp: '詳細な調査が行なわれているそうですね。', en: 'A detailed investigation is being conducted, I hear.', style: 'teen confirming' },
    { speaker: 'asuka_teacher', jp: '結果には、大きな意義があります。', en: 'The result has great significance.', style: 'teacher affirming' },
    { speaker: 'sakura_teen', jp: '専門家は、細部に注意を払っています。', en: 'Experts pay attention to detail.', style: 'teen noting expert care' },
    { speaker: 'asuka_teacher', jp: 'あえて反対意見を表明する人もいます。', en: 'Some deliberately voice opposing views.', style: 'teacher noting dissent' },
    { speaker: 'sakura_teen', jp: 'そうすると、議論はまだ続きますね。', en: 'Then the debate goes on, doesn’t it?', style: 'teen following up' },
    { speaker: 'asuka_teacher', jp: 'いわば、これは始まりに過ぎないのです。', en: 'So to speak, this is only the beginning.', style: 'teacher giving perspective' },
  ]),
  C('conv_03459', 'Discussing labor reform', 'Discuss labor reform; teach 圧力/延長/行なわ/意義/払っ/あえて/そうすると/いわば', 'lecture_hall_quiet',
    ['圧力','延長','行なわ','意義','払っ','あえて','そうすると','いわば'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '労働改革、社会的な圧力が背景にありますね。', en: 'Labor reform — social pressure is behind it.', style: 'student framing the context' },
    { speaker: 'asuka_teacher', jp: '制度の見直しは、何度も延長されました。', en: 'The system review was extended repeatedly.', style: 'teacher noting delays' },
    { speaker: 'ren_uni', jp: '専門委員会で議論が行なわれています。', en: 'Discussion is being conducted at the expert committee.', style: 'student updating' },
    { speaker: 'asuka_teacher', jp: '働き方を変える意義は、大きいですね。', en: 'The significance of changing how we work is great.', style: 'teacher affirming the stakes' },
    { speaker: 'ren_uni', jp: '私たちも、関心を払っていきたいです。', en: 'We also want to keep paying attention.', style: 'student committing' },
    { speaker: 'asuka_teacher', jp: 'あえて声を上げる若者も、増えています。', en: 'More young people are deliberately speaking up too.', style: 'teacher noting a trend' },
    { speaker: 'ren_uni', jp: 'そうすると、社会が動き出すんですね。', en: 'Doing that gets society moving.', style: 'student grasping it' },
    { speaker: 'asuka_teacher', jp: 'いわば、市民の力が試される時期です。', en: 'So to speak, it’s a time when citizens’ power is tested.', style: 'teacher offering a unifying line' },
  ]),
  C('conv_03460', 'Reflecting on the international-affairs unit', 'Wrap up the unit; teach 圧力/延長/行なわ/意義/払っ/あえて/そうすると/いわば', 'lecture_hall_quiet',
    ['圧力','延長','行なわ','意義','払っ','あえて','そうすると','いわば'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '国際情勢の単元、いかがでしたか？', en: 'How was the international-affairs unit?', style: 'teacher inviting reflection' },
    { speaker: 'ren_uni', jp: '様々な圧力と外交を、学べました。', en: 'I learned about various pressures and diplomacy.', style: 'satisfied student summarizing' },
    { speaker: 'sakura_teen', jp: '期限の延長を巡るかけひきも、興味深かったです。', en: 'The maneuvering around deadline extensions was fascinating too.', style: 'engaged teen reflecting' },
    { speaker: 'asuka_teacher', jp: '会議が行なわれる背景まで、見えてきましたね。', en: 'You came to see even the background behind conferences.', style: 'teacher affirming depth' },
    { speaker: 'ren_uni', jp: '一つ一つの行動に、意義を感じるようになりました。', en: 'I came to feel significance in each action.', style: 'student noting personal growth' },
    { speaker: 'sakura_teen', jp: '細部に注意を払う大切さも、知りました。', en: 'I learned the importance of paying attention to detail too.', style: 'teen acknowledging' },
    { speaker: 'asuka_teacher', jp: 'あえて難しい問いを、自分に課してください。', en: 'Deliberately ask yourself hard questions.', style: 'teacher offering a charge' },
    { speaker: 'ren_uni', jp: 'そうすると、思考の幅が広がる気がします。', en: 'Doing that, I feel my thinking widens.', style: 'student internalizing' },
    { speaker: 'sakura_teen', jp: 'いわば、これからが本当の学びですね。', en: 'So to speak, real learning begins from now.', style: 'reflective teen closing' },
  ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_173 wrote', CONVERSATIONS.length, 'files');
