// scripts/batches/batch_007.mjs — conv_00124..00143
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
fs.mkdirSync(OUT_DIR, { recursive: true });
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_007)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_00124',
    context: 'A small Saturday class at Asuka\'s language school. Ren has come as a guest student to help test a new lesson plan. The other students are away — just the two of them.',
    purpose: 'small tutoring with a friend — old colleagues in a relaxed mode',
    ambient: 'school_classroom',
    target_vocab: ['本当に','大丈夫','時間','一緒','少し','ありがとう'],
    cast: ['asuka_teacher','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'レン、今日、本当に来てくれてありがとう。', en: 'Ren — truly, thank you for coming today.', style: 'Warm friendly opener. Spreads materials across the desk.', mood: 'warm_open' },
      { speaker: 'ren_uni', jp: 'いえ、楽しみで。お役に立てれば。', en: 'No — I was looking forward. If I can help.', style: 'A small modest reply. Sits across from her.', mood: 'modest_sit' },
      { speaker: 'asuka_teacher', jp: '新しい教材、少し試してみたいの。', en: 'I want to try this new material a bit.', style: 'A small business-like teacher voice activated.', mood: 'business_teacher' },
      { speaker: 'ren_uni', jp: 'はい、もちろん。…難しそう？', en: 'Yes, of course. …Looks hard?', style: 'A small joking concern. Half-laugh audible.', mood: 'joking_concern' },
      { speaker: 'asuka_teacher', jp: '(small laugh) 大丈夫、本当に。…一緒に考えよう。', en: '(small laugh) It\'s fine, really. …Let\'s think through it together.', style: 'A small reassuring laugh. The 「一緒に」 collegial.', mood: 'collegial_warm' },
      { speaker: 'ren_uni', jp: 'お時間、私も大丈夫。', en: 'I\'ve got the time too — no problem.', style: 'A small steady commitment.', mood: 'steady_commit' },
      { speaker: 'asuka_teacher', jp: 'じゃ、最初の問題から、いこう。', en: 'Right — let\'s start with the first item.', style: 'A small kind teacher-direction.', mood: 'kind_direction' },
    ],
  },
  {
    id: 'conv_00125',
    context: 'Hiroshi (the boss) has unexpectedly come to visit Hiroshi (his father, the retired professor) on a weeknight. The father pours tea slowly.',
    purpose: 'father-son evening visit — composed son slowly admitting tiredness',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','今','大丈夫','仕事','少し','大切','一緒'],
    cast: ['hiroshi_boss','hiroshi_elder'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '父さん、夜分にすまない。', en: 'Dad — sorry for the late hour.', style: 'A small composed apology at the door.', mood: 'composed_apologetic' },
      { speaker: 'hiroshi_elder', jp: 'いえ、いつでも。お茶でも飲んでいきなさい。', en: 'No — anytime. Have some tea before you go.', style: 'A slow welcome. Pours without asking.', mood: 'slow_welcome' },
      { speaker: 'hiroshi_boss', jp: '…(sits, exhales)', en: '(sits, exhales)', style: 'A real beat. Loosens his tie in the voice.', mood: 'real_loosen' },
      { speaker: 'hiroshi_elder', jp: '仕事、今日も長かったか。', en: 'Work — long again today?', style: 'A small careful question. Voice low.', mood: 'careful_low' },
      { speaker: 'hiroshi_boss', jp: 'まあな。…本当に、最近、何も考えられない。', en: 'Yeah, kind of. …Honestly — I can\'t think about anything lately.', style: 'A small unguarded admission. Voice tired.', mood: 'unguarded_tired' },
      { speaker: 'hiroshi_elder', jp: 'うん。…そういう時期、誰にもある。', en: 'Mm. …That kind of phase — everyone has it.', style: 'A small grounded normalisation.', mood: 'grounded_normal' },
      { speaker: 'hiroshi_boss', jp: '父さんは、どう乗り越えた？', en: 'Dad — how did you get through it?', style: 'A small honest question. Rare from him.', mood: 'honest_rare' },
      { speaker: 'hiroshi_elder', jp: '…(pause) 少し、立ち止まる。本当に、少しだけ。', en: '…(pause) Stop a little. Really — just a little.', style: 'A small considered answer. Slow.', mood: 'considered_slow' },
      { speaker: 'hiroshi_boss', jp: '止まる、か。', en: 'Stop, huh.', style: 'A small repeat. Tasting the idea.', mood: 'tasting' },
      { speaker: 'hiroshi_elder', jp: '今、一週間でも、お茶飲んで、本読んで。', en: 'Right now — even a week. Drink tea, read books.', style: 'A small piece of practical wisdom.', mood: 'practical_wisdom' },
      { speaker: 'hiroshi_boss', jp: '一週間、本当に取れるかな…', en: 'A whole week — can I really take it…', style: 'A small doubting half-laugh.', mood: 'doubting' },
      { speaker: 'hiroshi_elder', jp: '取りなさい。時間は、本当に、大切。', en: 'Take it. Time — really — matters.', style: 'A small firm-soft directive.', mood: 'firm_soft' },
      { speaker: 'hiroshi_boss', jp: '…(small breath) ありがとう、父さん。', en: '…(small breath) Thank you, Dad.', style: 'A real catch in the voice.', mood: 'real_catch' },
      { speaker: 'hiroshi_elder', jp: 'もう一杯、飲んでいきなさい。', en: 'Have another cup before you go.', style: 'A small closing line. Pours again.', mood: 'closing_pour' },
    ],
  },
  {
    id: 'conv_00126',
    context: 'A quiet office cafeteria, twelve-thirty. Yuki has come down with her bento; Asuka (visiting the building for a separate meeting) recognises her from a friend-of-a-friend introduction last month.',
    purpose: 'small lunch encounter — half-strangers, finding common ground',
    ambient: 'office_open_plan',
    target_vocab: ['本当に','今日','一緒','時間','元気','どう'],
    cast: ['yuki_office','asuka_teacher'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'あれ…田中さん、ですよね？', en: 'Hey — Ms. Tanaka, right?', style: 'A small uncertain recognition. Lunch tray paused.', mood: 'uncertain_recognise' },
      { speaker: 'yuki_office', jp: 'えっ…木村さん。…先月の、お食事の。', en: 'Oh — Ms. Kimura. …From last month\'s dinner.', style: 'A small pleased recovery. Sets her bento down.', mood: 'pleased_recover' },
      { speaker: 'asuka_teacher', jp: '良かった、覚えてもらえてて。一緒に座っても？', en: 'Glad you remember. Mind if I join you?', style: 'A small warm request.', mood: 'warm_request' },
      { speaker: 'yuki_office', jp: 'もちろん。…本当に、奇遇ですね。', en: 'Of course. …Truly, what a coincidence.', style: 'A small pleased coincidence note.', mood: 'pleased_coincidence' },
      { speaker: 'asuka_teacher', jp: '今日、こちらでミーティングで。', en: 'Today — I\'ve got a meeting here.', style: 'A small contextual line.', mood: 'context_line' },
      { speaker: 'yuki_office', jp: 'お忙しい中、いつもありがとうございます。', en: 'Thank you for your hard work, always.', style: 'A polite reflexive line.', mood: 'polite_reflex' },
      { speaker: 'asuka_teacher', jp: '田中さんも、最近お元気？', en: 'And you — doing well lately?', style: 'A small redirect to her.', mood: 'small_redirect' },
      { speaker: 'yuki_office', jp: '元気です。…本当に、少しずつ。', en: 'Yes — well. …Truly, little by little.', style: 'A small honest answer.', mood: 'small_honest' },
    ],
  },
  {
    id: 'conv_00127',
    context: 'Aoi\'s café is short-staffed. Sakura has come in for her first day of weekend work. Aoi is showing her the espresso machine.',
    purpose: 'small first-day tutorial — patient mentor + nervous teen',
    ambient: 'cafe_morning',
    target_vocab: ['本当に','見る','大丈夫','時間','少し','ありがとう'],
    cast: ['aoi_barista','sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'さくらちゃん、まず、見て。', en: 'Sakura-chan — first, watch.', style: 'A small calm instructional voice.', mood: 'calm_instruct' },
      { speaker: 'sakura_teen', jp: '…はい。', en: '…Yes.', style: 'A small focused one-syllable.', mood: 'focused' },
      { speaker: 'aoi_barista', jp: 'コーヒー、本当に、グラム正確に。', en: 'Coffee — really, grams have to be exact.', style: 'A small precise teacher-line.', mood: 'precise' },
      { speaker: 'sakura_teen', jp: 'え、めっちゃ難しそう…', en: 'Whoa — that looks really hard…', style: 'A small honest Kansai-Tokyo blend reaction.', mood: 'honest_react' },
      { speaker: 'aoi_barista', jp: '最初は誰でも、そう。私もよ。', en: 'At first — everyone\'s like that. Me too.', style: 'A small normalising warmth.', mood: 'normalising' },
      { speaker: 'sakura_teen', jp: '本当に？', en: 'Really?', style: 'A small surprised confirmation.', mood: 'surprised' },
      { speaker: 'aoi_barista', jp: '本当に。…時間かけて、ゆっくり覚えよう。', en: 'Really. …Take time — learn slowly.', style: 'A small grounded pace-setting.', mood: 'grounded_pace' },
      { speaker: 'sakura_teen', jp: 'ありがとうございます。頑張る。', en: 'Thank you. I\'ll do my best.', style: 'A small earnest commitment.', mood: 'earnest' },
      { speaker: 'aoi_barista', jp: '大丈夫、一緒にやろう。', en: 'It\'s fine — let\'s do this together.', style: 'A small inclusive closing.', mood: 'inclusive_close' },
      { speaker: 'sakura_teen', jp: 'はい！…少し緊張するけど。', en: 'Yes! …Still — a little nervous.', style: 'A small honest mix.', mood: 'honest_mix' },
      { speaker: 'aoi_barista', jp: '本当に大丈夫だから。私も最初、震えてた。', en: 'You really will be fine. I shook on my first day too.', style: 'A small disarming confession.', mood: 'disarming' },
      { speaker: 'sakura_teen', jp: '(small laugh) ありがとう、本当に。', en: '(small laugh) Thank you — really.', style: 'A small real laugh. The shift starts.', mood: 'shift_starts' },
    ],
  },
  {
    id: 'conv_00128',
    context: 'A koban at Haneda Airport, very early morning. Tatsuya has missed a connection and asks the officer where he can sit until his rebooked flight.',
    purpose: 'tiny travel-help moment — country man + city officer',
    ambient: 'airport_terminal',
    target_vocab: ['すみません','本当に','時間','大丈夫','どこ'],
    cast: ['tatsuya_country','takeda_officer'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: 'すみません、ちょっと尋ねていいか。', en: 'Excuse me — may I ask something?', style: 'A slow polite opener. Tohoku cadence.', mood: 'slow_polite' },
      { speaker: 'takeda_officer', jp: 'はい、どうぞ。', en: 'Yes, please go ahead.', style: 'A small calm professional reply.', mood: 'calm_pro' },
      { speaker: 'tatsuya_country', jp: '便、乗り遅れてな。どこで待てばええ？', en: 'Missed my flight. Where can I wait?', style: 'A small embarrassed admission.', mood: 'embarrassed_admit' },
      { speaker: 'takeda_officer', jp: '本当に、お疲れさまです。あちらに、休憩所が。', en: 'Truly — that\'s rough. Over there — there\'s a lounge.', style: 'A small polite direction. Gestures in the voice.', mood: 'polite_direction' },
      { speaker: 'tatsuya_country', jp: 'ありがとな。お時間取らせて。', en: 'Thanks. Sorry to take your time.', style: 'A small Tohoku-formal gratitude.', mood: 'tohoku_thanks' },
      { speaker: 'takeda_officer', jp: '大丈夫ですよ。ご無事の旅を。', en: 'It\'s fine. Safe travels.', style: 'A small closing warm line.', mood: 'closing_warm' },
    ],
  },
  {
    id: 'conv_00129',
    context: 'Hospital waiting room. Mei is waiting for a friend who just had a small procedure. Mrs Mori is two seats over, equally tense.',
    purpose: 'incidental stranger-bonding — shared anxious wait',
    ambient: 'clinic_waiting_room',
    target_vocab: ['本当に','大丈夫','時間','心配','一人','ありがとう'],
    cast: ['mei_romantic','mrs_mori_neighbor'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'お一人で、待ってはるんですか？', en: 'You\'re waiting alone?', style: 'A small Kansai inquiry. Voice softer than usual.', mood: 'soft_kansai' },
      { speaker: 'mei_romantic', jp: 'はい…友達の手術なんです。', en: 'Yes… my friend\'s in surgery.', style: 'A small careful answer. Voice slightly catching.', mood: 'careful_catch' },
      { speaker: 'mrs_mori_neighbor', jp: 'そうかー。私もな、姉の。本当に、長いな、こういう時。', en: 'Ahh. Me too — my sister. Really, these times feel long.', style: 'A small companion-sharing.', mood: 'companion_share' },
      { speaker: 'mei_romantic', jp: '本当に。…時間、止まってる気がして。', en: 'Truly. …Feels like time has stopped.', style: 'A small honest exhausted line.', mood: 'honest_exhausted' },
      { speaker: 'mrs_mori_neighbor', jp: 'うん。心配は、本当に体に来るよね。', en: 'Mm. Worry — really gets into the body.', style: 'A small wise observation.', mood: 'wise_obs' },
      { speaker: 'mei_romantic', jp: 'ですね…(small breath)', en: 'It does… (small breath)', style: 'A small real exhale.', mood: 'real_exhale' },
      { speaker: 'mrs_mori_neighbor', jp: 'お茶、いる？自販機、あっちにあるで。', en: 'Want tea? Vending machine\'s over there.', style: 'A small practical kindness.', mood: 'practical_kindness' },
      { speaker: 'mei_romantic', jp: 'ありがとうございます。…でも、大丈夫です。', en: 'Thank you. …But — I\'m alright.', style: 'A small polite half-decline.', mood: 'polite_decline' },
      { speaker: 'mrs_mori_neighbor', jp: 'ええの、ええの。一緒に待ちましょね。', en: 'It\'s fine, fine. Let\'s wait together.', style: 'A small Kansai inclusion.', mood: 'kansai_inclusion' },
    ],
  },
  {
    id: 'conv_00130',
    context: 'Sachiko has invited Hiroshi (elder) — an old neighbour from their university days — to her son\'s spare room. She has found a box of letters her late husband wrote during his student years. Hiroshi knew the husband. They sit on the floor with the box.',
    purpose: 'extended quiet nostalgic scene — two seventy-somethings reading old letters',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','大切','一緒','少し','心配','元気','見る'],
    cast: ['sachiko_grandma','hiroshi_elder'],
    frequency_tier: 2,
    length_tier: 'Extended (21-30)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'ひろしさん、来てくれて、本当にありがとう。', en: 'Hiroshi-san — truly, thank you for coming.', style: 'A small careful welcome. Voice slow.', mood: 'careful_welcome' },
      { speaker: 'hiroshi_elder', jp: 'いえ。…箱、これですね。', en: 'No. …The box — this one, yes?', style: 'A small recognition. Sits down carefully.', mood: 'careful_sit' },
      { speaker: 'sachiko_grandma', jp: 'うん。先週、押し入れの奥から。', en: 'Mm. Last week — from deep in the closet.', style: 'A small surprised report. Voice quiet.', mood: 'surprised_quiet' },
      { speaker: 'hiroshi_elder', jp: '…(opens the box)これは、二十二歳の彼の字。', en: '…(opens the box) That\'s his hand, age twenty-two.', style: 'A real beat. Slow recognition.', mood: 'slow_recognition' },
      { speaker: 'sachiko_grandma', jp: 'よく覚えてくれてる。本当に。', en: 'You remember well. Truly.', style: 'A small touched line.', mood: 'small_touched' },
      { speaker: 'hiroshi_elder', jp: 'ずっと、忘れたことない。', en: 'Never forgotten — not once.', style: 'A small honest steady line.', mood: 'honest_steady' },
      { speaker: 'sachiko_grandma', jp: '…(unfolds a letter)読んでみる？', en: '…(unfolds a letter) Want to read it?', style: 'A small careful offer.', mood: 'careful_offer' },
      { speaker: 'hiroshi_elder', jp: 'いいですか。…ありがとう。', en: 'May I? …Thank you.', style: 'A small slow gratitude.', mood: 'slow_gratitude' },
      { speaker: 'sachiko_grandma', jp: 'うん。…私も、初めて読む。', en: 'Mm. …I\'m reading it for the first time too.', style: 'A small honest disclosure.', mood: 'honest_disclose' },
      { speaker: 'hiroshi_elder', jp: 'えっ、本当に？', en: 'Really?', style: 'A small surprised lift.', mood: 'surprised_lift' },
      { speaker: 'sachiko_grandma', jp: '当時、本人の前で読むのが、本当に照れくさくて。', en: 'Back then — reading it in front of him felt really embarrassing.', style: 'A small fond admission.', mood: 'fond_admit' },
      { speaker: 'hiroshi_elder', jp: '(small laugh) 彼らしいですね、それも。', en: '(small laugh) That sounds like him too.', style: 'A real small laugh.', mood: 'real_laugh' },
      { speaker: 'sachiko_grandma', jp: '…(reading) 「秋の空は、君の声を、聞こえる気がする」…', en: '…(reading) "In the autumn sky — I feel I hear your voice"…', style: 'A small careful read. Voice catches half a step.', mood: 'catch_read' },
      { speaker: 'hiroshi_elder', jp: '…(silence)', en: '(silence)', style: 'A real beat. The whole room held.', mood: 'real_held' },
      { speaker: 'sachiko_grandma', jp: '私、知らなかった。こんなこと、書いてくれてたなんて。', en: 'I didn\'t know. That he\'d written something like this.', style: 'A small voice catching.', mood: 'voice_catch' },
      { speaker: 'hiroshi_elder', jp: 'いい人だった、本当に。', en: 'A fine man — truly.', style: 'A small real eulogy.', mood: 'real_eulogy' },
      { speaker: 'sachiko_grandma', jp: '…(small breath) うん。', en: '…(small breath) Mm.', style: 'A real exhale.', mood: 'real_exhale' },
      { speaker: 'hiroshi_elder', jp: '時間、こんなふうに、流れるんですね。', en: 'Time — flows like this, doesn\'t it.', style: 'A small philosophical observation.', mood: 'philo_observe' },
      { speaker: 'sachiko_grandma', jp: '本当に。…でも、こうして、ひろしさんと一緒に、読めて、嬉しい。', en: 'Truly. …But — being able to read this with you — I\'m glad.', style: 'A small unguarded gratitude.', mood: 'unguarded_grateful' },
      { speaker: 'hiroshi_elder', jp: 'こちらこそ。…大切に、また、読みましょう。', en: 'Likewise. …Carefully — let\'s read more again.', style: 'A small steady offering.', mood: 'steady_offer' },
      { speaker: 'sachiko_grandma', jp: 'ええ。少しずつ。', en: 'Yes. Little by little.', style: 'A small closing line.', mood: 'small_close' },
      { speaker: 'hiroshi_elder', jp: '…(carefully refolding) 大切な箱ですね、本当に。', en: '…(carefully refolding) A precious box — truly.', style: 'A small final reverent line.', mood: 'reverent_final' },
    ],
  },
  {
    id: 'conv_00131',
    context: 'A small ramen shop, Saturday evening. The actual date. Both nervous, both trying. Aoi shows up in clothes she hasn\'t worn in a year.',
    purpose: 'first proper date — both ordinary people, both willing to try',
    ambient: 'busy_restaurant',
    target_vocab: ['本当に','今日','時間','大丈夫','一緒','好き','ありがとう'],
    cast: ['kenji_office','aoi_barista'],
    frequency_tier: 1,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: 'あおいさん、来てくれて、本当にありがとう。', en: 'Aoi-san — truly, thank you for coming.', style: 'A small formal nervous opener. Voice slightly higher than usual.', mood: 'formal_nervous' },
      { speaker: 'aoi_barista', jp: 'こちらこそ。…なんか、緊張する。', en: 'Likewise. …I feel — kind of nervous.', style: 'A small honest laugh.', mood: 'honest_laugh' },
      { speaker: 'kenji_office', jp: '私も。本当に、めっちゃ。', en: 'Me too. Really — a lot.', style: 'A real relieved laugh borrowing Kansai emphasis.', mood: 'real_relieved' },
      { speaker: 'aoi_barista', jp: '(small laugh) 良かった。私だけじゃなくて。', en: '(small laugh) Glad — not just me.', style: 'A small real settling-in.', mood: 'real_settling' },
      { speaker: 'kenji_office', jp: '何、食べます？ラーメン、初めての方？', en: 'What\'ll you have? First time here?', style: 'A small safe topic. Menu out.', mood: 'safe_topic' },
      { speaker: 'aoi_barista', jp: 'はい、はじめて。佐藤さんは、いつも、何？', en: 'Yes — first time. And you, Sato-san? Usually what?', style: 'A small returning question.', mood: 'returning' },
      { speaker: 'kenji_office', jp: '醤油。本当に、ここの醤油、好きで。', en: 'Shoyu. Really — I love their shoyu.', style: 'A small honest recommendation.', mood: 'honest_recommend' },
      { speaker: 'aoi_barista', jp: 'じゃあ、私も、同じで。', en: 'Then I\'ll have the same.', style: 'A small easy following.', mood: 'easy_follow' },
      { speaker: 'kenji_office', jp: '…(silence after ordering)あの、聞いてもいい？', en: '…(silence after ordering) Um — may I ask something?', style: 'A small careful new opening.', mood: 'careful_open' },
      { speaker: 'aoi_barista', jp: 'はい、なんでも。', en: 'Yes — anything.', style: 'A small open invitation.', mood: 'open' },
      { speaker: 'kenji_office', jp: 'なんで…私で、いいって思ってくれたんですか。', en: 'Why… did you think — me, would be okay?', style: 'A small honest question. Voice cracks half a step.', mood: 'honest_crack' },
      { speaker: 'aoi_barista', jp: '(small laugh)…本当に、聞く？', en: '(small laugh) …Really — you\'re asking?', style: 'A small affectionate teasing.', mood: 'affectionate_tease' },
      { speaker: 'kenji_office', jp: 'うん。', en: 'Mm.', style: 'A small careful single-syllable.', mood: 'careful_single' },
      { speaker: 'aoi_barista', jp: 'いつも、本当に、優しいから。お店で。', en: 'You\'re always — really, kind. At the café.', style: 'A small honest answer. Eyes on the napkin.', mood: 'honest_eyes' },
      { speaker: 'kenji_office', jp: '…(small breath, half-laugh)それは、ありがたい。', en: '…(small breath, half-laugh) That\'s very kind.', style: 'A small real exhale. Touched.', mood: 'touched' },
      { speaker: 'aoi_barista', jp: '時間、ゆっくり、ね。今日、本当に楽しみで。', en: 'Take time — slow. Today — I was really looking forward.', style: 'A small generous line.', mood: 'small_generous' },
      { speaker: 'kenji_office', jp: '…ありがとう。一緒にいられて、嬉しい。', en: '…Thank you. Being here with you — I\'m happy.', style: 'A small unguarded closing line.', mood: 'unguarded_close' },
    ],
  },
  {
    id: 'conv_00132',
    context: 'Friday evening, the Saito-Hayashi household. Sho\'s school friend has invited him to a sleepover. Sho is hesitant; Hina has opinions; Yumiko mediates.',
    purpose: 'three-speaker family micro-decision — kid uncertainty, sister opinion, mom listening',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','大丈夫','一緒','少し','ありがとう','明日'],
    cast: ['sho_child','hina_child','yumiko_mom'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん…明日、ともだち、お泊まりって。', en: 'Mom… tomorrow — a friend invited me to sleep over.', style: 'A small careful kid-announcement.', mood: 'careful_announce' },
      { speaker: 'yumiko_mom', jp: 'えっ、本当？嬉しいね、しょう。', en: 'Oh — really? That\'s lovely, Sho.', style: 'A small bright mom-response.', mood: 'bright_mom' },
      { speaker: 'hina_child', jp: 'しょうは、行く？行かない？', en: 'Sho — going? Or not?', style: 'A small big-sister probe.', mood: 'big_sister' },
      { speaker: 'sho_child', jp: '…わかんない。ちょっと、こわい。', en: '…Don\'t know. A little — scared.', style: 'A small honest fear.', mood: 'honest_fear' },
      { speaker: 'yumiko_mom', jp: 'そっか。…どんなところが、こわい？', en: 'I see. …What part is scary?', style: 'A small careful open question.', mood: 'careful_open' },
      { speaker: 'sho_child', jp: '夜、お母さん、いない。', en: 'At night — Mom won\'t be there.', style: 'A small honest core-fear.', mood: 'core_fear' },
      { speaker: 'hina_child', jp: 'でも、ともだちのお母さん、優しいよ。私、知ってる。', en: 'But — the friend\'s mom is nice. I know.', style: 'A small big-sister reassurance.', mood: 'sister_reassure' },
      { speaker: 'yumiko_mom', jp: '本当に？お姉ちゃん、お友達、いるの？', en: 'Really? You know them too, big sis?', style: 'A small interested mom-check.', mood: 'interested_check' },
      { speaker: 'hina_child', jp: 'お母さん同士、知り合い。', en: 'Their moms — know each other.', style: 'A small confident kid-line.', mood: 'confident_kid' },
      { speaker: 'sho_child', jp: '…じゃ、ちょっと、行ってみる、かも。', en: '…Then — I might give it a try.', style: 'A small careful step forward.', mood: 'careful_step' },
      { speaker: 'yumiko_mom', jp: '大丈夫だよ。途中で帰りたかったら、電話して。', en: 'It\'ll be okay. If you want to come back partway — call.', style: 'A small grounded permission.', mood: 'grounded_permit' },
    ],
  },
  {
    id: 'conv_00133',
    context: 'Daichi has stayed at Ren\'s place for the weekend. Sunday afternoon. They\'ve been sitting on the floor with old beer for an hour.',
    purpose: 'old-friend hangout — two adult men in low gear',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','今','元気','一緒','大丈夫','少し'],
    cast: ['daichi_kansai','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'レン、お前の家、本当に静かやな。', en: 'Ren — your place is really quiet, man.', style: 'A small Kansai observation. Cross-legged on the floor.', mood: 'kansai_observe' },
      { speaker: 'ren_uni', jp: 'メイ、出かけてるから。普段は、もう少し。', en: 'Mei\'s out. Usually — a little more.', style: 'A small explanation.', mood: 'explain' },
      { speaker: 'daichi_kansai', jp: 'ええ静けさやな。本当に。', en: 'It\'s a good kind of quiet. Really.', style: 'A small unguarded observation.', mood: 'unguarded' },
      { speaker: 'ren_uni', jp: '本、読む？気になるの、ある？', en: 'Want to read something? Anything that catches your eye?', style: 'A small host-offer.', mood: 'host_offer' },
      { speaker: 'daichi_kansai', jp: '俺、本、読まへんねん、最近。', en: 'I haven\'t been reading lately.', style: 'A small honest admission.', mood: 'small_admit' },
      { speaker: 'ren_uni', jp: 'なんで？', en: 'Why?', style: 'A small genuine question.', mood: 'genuine' },
      { speaker: 'daichi_kansai', jp: '時間、ない気がして。…でも、本当は、ある気がする。', en: 'Feels like no time. …But — actually, maybe there is.', style: 'A small honest contradiction.', mood: 'honest_contradiction' },
      { speaker: 'ren_uni', jp: 'それ、よくわかる。', en: 'I really get that.', style: 'A small honest agreement.', mood: 'honest_agree' },
      { speaker: 'daichi_kansai', jp: 'ちょっと、一冊、貸してくれる？', en: 'Hey — could I borrow one?', style: 'A small unexpected pivot.', mood: 'small_pivot' },
      { speaker: 'ren_uni', jp: 'もちろん。…これ、好きかも、ダイチに。', en: 'Of course. …This one — you might like, Daichi.', style: 'A small careful recommendation.', mood: 'careful_recommend' },
      { speaker: 'daichi_kansai', jp: '本当に？ありがとう。…一緒の時間、ええな。', en: 'Really? Thanks. …Time together — that\'s good.', style: 'A small unguarded closing line.', mood: 'unguarded_close' },
    ],
  },
  {
    id: 'conv_00134',
    context: 'A small countryside onsen. Goro and Ren are in the outdoor bath at dawn. Six lines is all they exchange.',
    purpose: 'tiny onsen exchange — silence is the medium',
    ambient: 'shrine_grounds',
    target_vocab: ['本当に','大丈夫','一緒','時間'],
    cast: ['goro_grandpa','ren_uni'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'goro_grandpa', jp: '…(long quiet) 寒いな。', en: '(long quiet) Cold, isn\'t it.', style: 'A real beat first. Slow Kyushu.', mood: 'kyushu_slow' },
      { speaker: 'ren_uni', jp: 'はい、でも、気持ちいいです。', en: 'Yes — but, feels good.', style: 'A small honest exhale.', mood: 'honest_exhale' },
      { speaker: 'goro_grandpa', jp: '本当に。…時間、忘れるな、ここ。', en: 'Truly. …Time — forgotten here.', style: 'A small philosophical line.', mood: 'philosophical' },
      { speaker: 'ren_uni', jp: '…本当ですね。', en: '…Truly.', style: 'A small returning agreement.', mood: 'returning_agree' },
      { speaker: 'goro_grandpa', jp: 'もう少し、おる？一緒に。', en: 'Stay a little longer? Together.', style: 'A small unceremonious invitation.', mood: 'unceremonious' },
      { speaker: 'ren_uni', jp: 'はい、ぜひ。', en: 'Yes — please.', style: 'A small full assent.', mood: 'full_assent' },
    ],
  },
  {
    id: 'conv_00135',
    context: 'Naoko\'s ramen shop, closing thirty minutes early so she can take Sakura to a small concert. Sakura is helping wipe down.',
    purpose: 'aunt-niece outing prep — Kansai brisk-warm in action',
    ambient: 'busy_restaurant',
    target_vocab: ['本当に','今日','時間','一緒','ありがとう','大丈夫'],
    cast: ['naoko_aunt','sakura_teen'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'さくら、もう、上がってええで。', en: 'Sakura — you can clock out.', style: 'A small Kansai dismissal-with-warmth.', mood: 'kansai_dismiss' },
      { speaker: 'sakura_teen', jp: 'え、本当に？まだ、テーブル…', en: 'Wait — really? The tables still…', style: 'A small protest. Towel still in hand.', mood: 'small_protest' },
      { speaker: 'naoko_aunt', jp: 'ええの、ええの。今日、コンサート、忘れた？', en: 'It\'s fine, fine. Forgotten the concert today?', style: 'A small affectionate prod.', mood: 'affectionate_prod' },
      { speaker: 'sakura_teen', jp: '…(grins) 忘れてへん。', en: '…(grins) Haven\'t forgotten.', style: 'A small real grin.', mood: 'real_grin' },
      { speaker: 'naoko_aunt', jp: 'やろ？着替えて、来。', en: 'See? Change clothes — let\'s go.', style: 'A small brisk direction.', mood: 'brisk_direct' },
      { speaker: 'sakura_teen', jp: 'おばちゃん、本当にありがとう。一緒に行ってくれて。', en: 'Oba-chan — really, thanks for coming with me.', style: 'A small honest gratitude.', mood: 'honest_thanks' },
      { speaker: 'naoko_aunt', jp: 'いえいえ。私も、楽しみやで、本当に。', en: 'No, no. I\'m looking forward too, really.', style: 'A small Kansai unguarded.', mood: 'kansai_unguarded' },
      { speaker: 'sakura_teen', jp: '時間、大丈夫？店、また閉めて。', en: 'Time okay? Closing the shop again, I mean.', style: 'A small considerate question.', mood: 'considerate' },
      { speaker: 'naoko_aunt', jp: '大丈夫。…たまには、こういう時間、大事や。', en: 'It\'s fine. …Once in a while — time like this matters.', style: 'A small unguarded philosophy.', mood: 'unguarded_philo' },
      { speaker: 'sakura_teen', jp: '…(small grin)じゃ、急ぐ。', en: '…(small grin) Then — hurrying.', style: 'A small bright move.', mood: 'bright_move' },
    ],
  },
  {
    id: 'conv_00136',
    context: 'After-school art club. Asuka has volunteered to help with the kids; Sho is hunched over a drawing in the back.',
    purpose: 'tiny art-club kindness — teacher noticing a quiet kid',
    ambient: 'school_classroom',
    target_vocab: ['本当に','見る','大切','少し','ありがとう'],
    cast: ['asuka_teacher','sho_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'しょうくん、何、描いてるの？', en: 'Sho-kun — what are you drawing?', style: 'A small kind curiosity. Crouches at his shoulder.', mood: 'kind_curious' },
      { speaker: 'sho_child', jp: '…うちのねこ。', en: '…Our cat.', style: 'A small careful announcement.', mood: 'careful_announce' },
      { speaker: 'asuka_teacher', jp: 'うわ、本当に上手。よく見てる、しょうくん。', en: 'Wow — really good. You\'ve really observed.', style: 'A small real teacher-praise.', mood: 'real_praise' },
      { speaker: 'sho_child', jp: 'ほんとう？', en: 'Really?', style: 'A small startled-pleased lift.', mood: 'startled_pleased' },
      { speaker: 'asuka_teacher', jp: '本当に。耳の形、すごく、よく描けてる。', en: 'Really. The shape of the ears — very well drawn.', style: 'A small specific praise.', mood: 'specific_praise' },
      { speaker: 'sho_child', jp: '…(small smile) 耳、難しいんだ。', en: '…(small smile) Ears are hard.', style: 'A small artist-admission.', mood: 'artist_admit' },
      { speaker: 'asuka_teacher', jp: 'うん。難しいの、ちゃんとやってる。本当に、大切な絵だね、これ。', en: 'Mm. The hard parts — you\'ve done them. Truly, this is a precious drawing.', style: 'A small steady recognition.', mood: 'steady_recognition' },
      { speaker: 'sho_child', jp: '先生、本当にありがとう。', en: 'Sensei — truly, thank you.', style: 'A small honest full keigo.', mood: 'honest_keigo' },
    ],
  },
  {
    id: 'conv_00137',
    context: 'A phone call. Tatsuya is calling Naoko\'s ramen shop because she sent him hometown miso a month ago and he\'s been meaning to say thanks.',
    purpose: 'cross-region adult phone call — Tohoku slowness meets Kansai brightness',
    ambient: 'phone_call_silent',
    target_vocab: ['本当に','時間','元気','一緒','ありがとう','大丈夫'],
    cast: ['tatsuya_country','naoko_aunt'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: 'もしもし、なおこさんかな。', en: 'Hello — is this Naoko-san?', style: 'A slow Tohoku opener.', mood: 'tohoku_open' },
      { speaker: 'naoko_aunt', jp: 'はーい、なおこです。どなたさん？', en: 'Yes — this is Naoko. Who\'s this?', style: 'A small bright Kansai answer.', mood: 'bright_kansai' },
      { speaker: 'tatsuya_country', jp: '岩手の、遠藤やけど。…味噌、本当にありがとうな。', en: 'Endo, from Iwate. …Really, thanks for the miso.', style: 'A small slow gratitude.', mood: 'slow_gratitude' },
      { speaker: 'naoko_aunt', jp: 'えっ、わざわざ電話くれたん？嬉しい！', en: 'Oh — you called specially? I\'m glad!', style: 'A real bright surprise.', mood: 'bright_surprise' },
      { speaker: 'tatsuya_country', jp: '一ヶ月前のことやけど、本当に、お礼を。', en: 'It was a month ago — really, thanks.', style: 'A small Tohoku-formal gratitude.', mood: 'tohoku_formal' },
      { speaker: 'naoko_aunt', jp: 'いえいえ。お元気にしてはった？', en: 'No, no. Have you been well?', style: 'A small Kansai return-question.', mood: 'kansai_return' },
      { speaker: 'tatsuya_country', jp: 'おかげさんで。…一緒に飲んだ夜、本当にええ夜やった。', en: 'By your grace. …That night drinking together — truly a fine night.', style: 'A small slow honest line.', mood: 'slow_honest' },
      { speaker: 'naoko_aunt', jp: 'やんなあ。…次は、いつ？時間、合わせるで。', en: 'Right? …Next one — when? I\'ll match the time.', style: 'A real warm directive.', mood: 'warm_directive' },
      { speaker: 'tatsuya_country', jp: '春、また、行こうかな。', en: 'Spring — maybe again.', style: 'A small considered offering.', mood: 'considered_offer' },
      { speaker: 'naoko_aunt', jp: '春、待ってる。本当に。', en: 'Spring — I\'ll be waiting. Really.', style: 'A small genuine warm closing.', mood: 'genuine_warm' },
    ],
  },
  {
    id: 'conv_00138',
    context: 'Hiroshi (boss) is back in his hometown for the New Year. His sixteen-year-old daughter (Sakura, here playing his daughter) corners him in the kitchen.',
    purpose: 'father-teen daughter long-deferred talk — boss reduced to dad',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','今','大切','言う','大丈夫','一緒','仕事'],
    cast: ['hiroshi_boss','sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'お父さん、ちょっと、いい？', en: 'Dad — got a sec?', style: 'A small Kansai-Tokyo blend opener.', mood: 'small_open' },
      { speaker: 'hiroshi_boss', jp: 'うん、何だ。', en: 'Mm — what is it.', style: 'A composed-but-soft for-her voice.', mood: 'composed_soft' },
      { speaker: 'sakura_teen', jp: '本当に、最近、家、いないやん。', en: 'Truly — you\'re never home lately.', style: 'A small Kansai accusation, warm.', mood: 'warm_accuse' },
      { speaker: 'hiroshi_boss', jp: '…(beat)わかってる。仕事が、本当に長くて。', en: '…(beat) I know. Work — really, runs long.', style: 'A small honest admission.', mood: 'honest_admit' },
      { speaker: 'sakura_teen', jp: '言い訳、要らんわ。本当のこと言って。', en: 'Don\'t want excuses. Tell me the truth.', style: 'A small firm teen line.', mood: 'firm_teen' },
      { speaker: 'hiroshi_boss', jp: '…(real beat) 怖いんだ、家にいるのが。', en: '…(real beat) I\'m — afraid of being home.', style: 'A small huge confession. Voice cracks.', mood: 'huge_crack' },
      { speaker: 'sakura_teen', jp: '…(silence)', en: '(silence)', style: 'A real beat. The teen-armor falling.', mood: 'armor_falling' },
      { speaker: 'hiroshi_boss', jp: '何を話していいか、お前と、わからなくて。', en: 'I don\'t know — what to talk to you about.', style: 'A small honest fatherly confession.', mood: 'honest_father' },
      { speaker: 'sakura_teen', jp: 'なんでも、ええ。本当に、なんでも。', en: 'Anything\'s fine. Truly — anything.', style: 'A small unguarded teen line.', mood: 'unguarded_teen' },
      { speaker: 'hiroshi_boss', jp: '…ありがとう。…時間、もっと、ちゃんと作る。', en: '…Thank you. …Time — I\'ll properly make more.', style: 'A small steady commitment.', mood: 'steady_commit' },
      { speaker: 'sakura_teen', jp: '一緒にご飯、たまには。約束。', en: 'Dinner together — once in a while. Promise.', style: 'A small concrete demand.', mood: 'concrete_demand' },
      { speaker: 'hiroshi_boss', jp: '約束する。本当に。', en: 'I promise. Truly.', style: 'A small firm honest line.', mood: 'firm_honest' },
      { speaker: 'sakura_teen', jp: '…(small breath) 大丈夫、お父さん。', en: '…(small breath) It\'s alright, Dad.', style: 'A small role-reversal moment.', mood: 'role_reverse' },
      { speaker: 'hiroshi_boss', jp: 'ありがとう、さくら。本当に。', en: 'Thank you, Sakura. Really.', style: 'A real exhale. The composed-boss is gone.', mood: 'composed_gone' },
    ],
  },
  {
    id: 'conv_00139',
    context: 'A small post office. Sachiko has come to mail a parcel to her son. Officer Takeda has stopped in on a routine visit and ends up holding the door.',
    purpose: 'tiny micro-courtesy — old woman, kind officer, no fuss',
    ambient: 'post_office',
    target_vocab: ['本当に','すみません','ありがとう','大丈夫'],
    cast: ['sachiko_grandma','takeda_officer'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'あら、ありがとうございます。', en: 'Oh — thank you so much.', style: 'A small soft Tokyo bow inside the voice.', mood: 'soft_bow' },
      { speaker: 'takeda_officer', jp: 'お気をつけて。', en: 'Please take care.', style: 'A small calm professional line.', mood: 'calm_pro' },
      { speaker: 'sachiko_grandma', jp: 'お時間、本当に、すみません。', en: 'Truly — sorry for the time.', style: 'A small polite reflexive apology.', mood: 'reflexive_polite' },
      { speaker: 'takeda_officer', jp: '大丈夫ですよ。お荷物、お持ちしましょうか。', en: 'It\'s fine. Shall I carry the package?', style: 'A small unexpected kind offer.', mood: 'unexpected_kind' },
      { speaker: 'sachiko_grandma', jp: '本当に？ありがとう、嬉しい。', en: 'Truly? Thank you — I\'m glad.', style: 'A small surprised warm gratitude.', mood: 'surprised_warm' },
      { speaker: 'takeda_officer', jp: 'こちらこそ。お元気で。', en: 'My pleasure. Stay well.', style: 'A small warm closing line.', mood: 'warm_closing' },
    ],
  },
  {
    id: 'conv_00140',
    context: 'A small audition room. Riku has been talked into trying out for a community theater play. Asuka, a friend of his mom\'s, is on the panel — purely by coincidence.',
    purpose: 'small-stakes audition — nervous teen, kind familiar judge',
    ambient: 'school_classroom',
    target_vocab: ['本当に','大丈夫','時間','言う','少し','心配'],
    cast: ['riku_teen','asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '…リクくん？', en: '…Riku-kun?', style: 'A small startled-pleased recognition.', mood: 'startled_pleased' },
      { speaker: 'riku_teen', jp: 'うわ…木村さん。', en: 'Whoa… Ms. Kimura.', style: 'A real teen embarrassment.', mood: 'real_embar' },
      { speaker: 'asuka_teacher', jp: '今日、来てくれて、本当にありがとう。', en: 'Truly — thank you for coming today.', style: 'A small professional pivot.', mood: 'pro_pivot' },
      { speaker: 'riku_teen', jp: '…なんで、ここにいんの。', en: '…Why are you here, like.', style: 'A small honest teen line.', mood: 'honest_teen' },
      { speaker: 'asuka_teacher', jp: '(small laugh) 審査員、一人だけ、足りなくて。', en: '(small laugh) They needed one more judge — that\'s all.', style: 'A small explanation.', mood: 'small_explain' },
      { speaker: 'riku_teen', jp: '…マジでやめてほしい。', en: '…Seriously, please don\'t.', style: 'A small Kansai-Tokyo blend protest.', mood: 'mock_protest' },
      { speaker: 'asuka_teacher', jp: '大丈夫。私、ちゃんと先生として、見るから。', en: 'It\'s alright. I\'ll watch you — properly, as a teacher.', style: 'A small steady reassurance.', mood: 'steady_reassure' },
      { speaker: 'riku_teen', jp: '…(beat) 心配かけて、すみません。', en: '…(beat) Sorry to make you worry.', style: 'A small unexpected mature line.', mood: 'unexpected_mature' },
      { speaker: 'asuka_teacher', jp: 'いえいえ。…本当に、ゆっくり、やって。', en: 'Not at all. …Really — take your time, do it.', style: 'A small warm permission.', mood: 'warm_permit' },
      { speaker: 'riku_teen', jp: 'はい…(small breath) 始めます。', en: 'Yes… (small breath) starting.', style: 'A small focused commitment.', mood: 'focused_commit' },
      { speaker: 'asuka_teacher', jp: '時間、ちゃんとあるから。', en: 'There\'s plenty of time.', style: 'A small final permission.', mood: 'final_permit' },
      { speaker: 'riku_teen', jp: '…(begins, voice cracks then steadies)', en: '(begins, voice cracks then steadies)', style: 'A real beat. The audition under way.', mood: 'audition_starts' },
    ],
  },
  {
    id: 'conv_00141',
    context: 'A long lazy Sunday at Goro\'s house. Both Sho and Hina are visiting. Goro decides to tell them a story he hasn\'t told in fifty years.',
    purpose: 'three-speaker oral-history — grandfather, two grandkids, one true story',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','見る','一緒','大切','少し','大丈夫','人'],
    cast: ['goro_grandpa','sho_child','hina_child'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'goro_grandpa', jp: '二人、座って。話、ある。', en: 'You two — sit. There\'s a story.', style: 'A small slow Kyushu summoning.', mood: 'slow_summon' },
      { speaker: 'hina_child', jp: 'うん！どんなはなし？', en: 'Yes! What kind of story?', style: 'A bright eight-year-old anticipation.', mood: 'bright_anticipate' },
      { speaker: 'sho_child', jp: '…うん。', en: '…Mm.', style: 'A small careful single.', mood: 'careful_single' },
      { speaker: 'goro_grandpa', jp: 'おじいちゃんの、お父さんの話な。', en: 'A story about my own father.', style: 'A small slow introduction.', mood: 'slow_intro' },
      { speaker: 'hina_child', jp: 'うわ、本当に古い話！', en: 'Whoa — really old story!', style: 'A bright kid-awe.', mood: 'bright_awe' },
      { speaker: 'goro_grandpa', jp: 'うん。…戦争の、すぐ後やった。', en: 'Mm. …Right after the war.', style: 'A small careful frame. Voice low.', mood: 'careful_frame' },
      { speaker: 'sho_child', jp: '…戦争？', en: '…War?', style: 'A small careful question.', mood: 'careful_question' },
      { speaker: 'goro_grandpa', jp: 'うん。…おじいちゃんも、子供だった、その時。', en: 'Mm. …I was a child then, too.', style: 'A small slow personal frame.', mood: 'slow_personal' },
      { speaker: 'hina_child', jp: '本当に？', en: 'Really?', style: 'A small wide-eyed kid-line.', mood: 'wide_eyed' },
      { speaker: 'goro_grandpa', jp: '本当に。…ある日、本当に、知らん人が、家に来た。', en: 'Truly. …One day — a complete stranger came to the door.', style: 'A small story-beat. Voice drops.', mood: 'story_beat' },
      { speaker: 'sho_child', jp: '怖くなかった？', en: 'Weren\'t you scared?', style: 'A small kid-empathy question.', mood: 'kid_empathy' },
      { speaker: 'goro_grandpa', jp: '怖かった、本当に。…でも、その人、優しい人やった。', en: 'I was — truly. …But that person — was a kind person.', style: 'A small slow turning of the story.', mood: 'slow_turn' },
      { speaker: 'hina_child', jp: '何、くれた？', en: 'What did they give?', style: 'A small kid-curious line.', mood: 'kid_curious' },
      { speaker: 'goro_grandpa', jp: 'おにぎり、一つ。…本当に、その時の味、忘れんかった。', en: 'A single onigiri. …I never forgot the taste.', style: 'A small precious memory.', mood: 'precious_memory' },
      { speaker: 'sho_child', jp: '…(quiet awe)', en: '(quiet awe)', style: 'A real silent beat. The kid taking it in.', mood: 'real_awe' },
      { speaker: 'hina_child', jp: 'その人、また会えた？', en: 'Did you see that person again?', style: 'A small careful follow-up.', mood: 'careful_follow' },
      { speaker: 'goro_grandpa', jp: 'いいや。…でも、大切な人やった。一緒におった時間、短くても。', en: 'No. …But a precious person. Even though the time together was short.', style: 'A small closing wisdom.', mood: 'closing_wisdom' },
    ],
  },
  {
    id: 'conv_00142',
    context: 'A small therapy office. Mei has come back to Dr. Saito (here playing a therapist she sees once a quarter). They\'ve known each other for years.',
    purpose: 'therapy session — long-term patient, careful gentle prompting',
    ambient: 'clinic_waiting_room',
    target_vocab: ['本当に','今','時間','大丈夫','心配','少し','言う'],
    cast: ['saito_doctor','mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'こんにちは、メイさん。お変わり、ありますか。', en: 'Hello, Mei-san. Any changes?', style: 'A small steady professional opener.', mood: 'steady_pro' },
      { speaker: 'mei_romantic', jp: 'はい…少し。…今、本当に、よく眠れて。', en: 'Yes… a little. …Now — I really sleep well.', style: 'A small honest report. Voice slightly lighter than past visits.', mood: 'honest_lighter' },
      { speaker: 'saito_doctor', jp: '本当に？それは、嬉しい変化ですね。', en: 'Really? That\'s a happy change.', style: 'A small genuine warmth.', mood: 'genuine_warm' },
      { speaker: 'mei_romantic', jp: 'はい。…仕事も、少し楽。', en: 'Yes. …Work too — a little easier.', style: 'A small steady positive line.', mood: 'steady_positive' },
      { speaker: 'saito_doctor', jp: 'いいですね。…何が、変わったと思いますか。', en: 'Wonderful. …What do you think changed?', style: 'A small careful Socratic.', mood: 'careful_socratic' },
      { speaker: 'mei_romantic', jp: '…(beat) ちゃんと、自分のために、時間取れてる。', en: '…(beat) I\'m taking time for myself, properly.', style: 'A small honest realisation.', mood: 'honest_realise' },
      { speaker: 'saito_doctor', jp: 'それ、本当に、大事ですよね。', en: 'That — is genuinely important.', style: 'A small grounded validation.', mood: 'grounded_validate' },
      { speaker: 'mei_romantic', jp: '心配は、まだある。でも、前より、少し。', en: 'There\'s still worry. But — less than before.', style: 'A small honest measurement.', mood: 'honest_measure' },
      { speaker: 'saito_doctor', jp: 'うん。…大丈夫ですよ、その「少し」が、本当に大切。', en: 'Mm. …It\'s alright — that "little" really matters.', style: 'A small steady reassurance.', mood: 'steady_reassure' },
      { speaker: 'mei_romantic', jp: '…ありがとうございます。先生に、言えて、楽になる。', en: '…Thank you. Being able to tell you — it makes things lighter.', style: 'A small grateful exhale.', mood: 'grateful_exhale' },
      { speaker: 'saito_doctor', jp: 'こちらこそ。…次は、いつにしましょうか。', en: 'Likewise. …When shall we do next?', style: 'A small closing logistics line.', mood: 'closing_logistics' },
      { speaker: 'mei_romantic', jp: '三ヶ月後で、本当に、大丈夫だと思います。', en: 'Three months — really, I think will be okay.', style: 'A small confident commitment.', mood: 'confident_commit' },
    ],
  },
  {
    id: 'conv_00143',
    context: 'Year-end office, Friday afternoon. Hiroshi (boss) has called in Kenji, Yuki, and Asuka (a consultant from her language school doing seasonal corporate work) for a four-way wrap-up.',
    purpose: 'four-speaker workplace year-end — professional, slightly warmer than usual',
    ambient: 'office_meeting_room',
    target_vocab: ['本当に','時間','今年','大変','一緒','仕事','ありがとう'],
    cast: ['hiroshi_boss','kenji_office','yuki_office','asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '皆さん、今年も、本当にお疲れさまでした。', en: 'Everyone — truly, thank you for this year\'s work.', style: 'A small composed opener with warmth underneath.', mood: 'composed_warm' },
      { speaker: 'kenji_office', jp: 'こちらこそ。本当に、長い一年でした。', en: 'Likewise. Truly — a long year.', style: 'A small honest report.', mood: 'honest_report' },
      { speaker: 'yuki_office', jp: '私、本当に、勉強させていただきました。', en: 'I truly — learned so much.', style: 'A small careful junior line.', mood: 'careful_junior' },
      { speaker: 'asuka_teacher', jp: '皆さんと、一緒に仕事できて、本当に良かったです。', en: 'Working with all of you — truly was a privilege.', style: 'A small warm consultant line.', mood: 'warm_consultant' },
      { speaker: 'hiroshi_boss', jp: '田中さん、本当に、よく頑張ってくれた。', en: 'Ms. Tanaka — truly, you worked so hard.', style: 'A rare direct compliment from him.', mood: 'rare_compliment' },
      { speaker: 'yuki_office', jp: '部長…(small bow)ありがとうございます。', en: 'Sir… (small bow) thank you very much.', style: 'A small voice catching in the bow.', mood: 'voice_catch' },
      { speaker: 'kenji_office', jp: '田中さん、最初の頃から、ずっと真面目で。', en: 'Ms. Tanaka — from the start, always serious about her work.', style: 'A small honest senior-colleague observation.', mood: 'senior_observe' },
      { speaker: 'asuka_teacher', jp: 'はじめてお会いした時、本当に、すぐにわかりました。', en: 'When I first met you — truly, I knew right away.', style: 'A small kind professional note.', mood: 'kind_pro' },
      { speaker: 'yuki_office', jp: 'みなさん、本当に…(eyes wet)', en: 'Everyone, truly… (eyes wet)', style: 'A real small catch. Hands clasped in the voice.', mood: 'real_catch' },
      { speaker: 'hiroshi_boss', jp: '来年も、一緒に。仕事は、まだまだ大変だが。', en: 'Next year too — together. Work — still hard ahead.', style: 'A small firm forward-looking line.', mood: 'firm_forward' },
      { speaker: 'kenji_office', jp: 'はい、頑張ります。本当に。', en: 'Yes — I\'ll do my best. Truly.', style: 'A small steady commitment.', mood: 'steady_commit' },
      { speaker: 'asuka_teacher', jp: '私も、また、関わらせていただければ。', en: 'I too — if I may be involved again.', style: 'A small careful consultant ask.', mood: 'careful_ask' },
      { speaker: 'hiroshi_boss', jp: 'もちろん。木村先生、本当に、ありがたい。', en: 'Of course. Ms. Kimura — truly grateful.', style: 'A small unguarded thank-you.', mood: 'unguarded_thanks' },
      { speaker: 'yuki_office', jp: '時間、皆さん、本当に、いつもありがとうございます。', en: 'Time — everyone, truly, always thank you.', style: 'A small closing real line.', mood: 'closing_real' },
      { speaker: 'kenji_office', jp: '良いお年を。本当に、お疲れさまでした。', en: 'Happy new year. Truly — fine work this year.', style: 'A small formal closing exchange.', mood: 'formal_closing' },
      { speaker: 'asuka_teacher', jp: '良いお年を。皆さん。', en: 'Happy new year — everyone.', style: 'A small warm closing.', mood: 'warm_closing' },
      { speaker: 'hiroshi_boss', jp: '良いお年を。…本当に、来年も、頼みます。', en: 'Happy new year. …Truly — counting on you again next year.', style: 'A small rare warm closer from him.', mood: 'rare_warm' },
      { speaker: 'yuki_office', jp: '…(small bow, real smile)良いお年を。', en: '…(small bow, real smile) Happy new year.', style: 'A real settled-bright closing line.', mood: 'real_settled' },
    ],
  },
];

for (const conv of CONVERSATIONS) fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
console.log(`wrote ${CONVERSATIONS.length} conversation(s) to ${OUT_DIR}`);
