import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_081)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01606',
    context: 'Hina-young confides to Yumiko about feeling lost about a friendship.',
    purpose: 'Teen seeking gentle wisdom from grandmother figure.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['悩み', '迷い', '友達', '気持ち'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、悩みがあるの。', en: "Grandma — I have a worry.", style: 'soft teen girl voice, warm honest vulnerable delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、何があった?', en: "Oh — what happened?", style: 'gentle older mother voice, soft warm caring inquiry delivered carefully' },
      { speaker: 'hina_child', jp: '友達との関係、迷ってる。', en: "Friendship — I'm confused.", style: 'soft teen girl voice, warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '気持ち、整理する時間ね。', en: "Time to sort your feelings.", style: 'warm older mother voice, soft wise delivery carefully' },
      { speaker: 'hina_child', jp: 'どうしたら、いいかな。', en: "What should I do?", style: 'soft teen girl voice, warm hopeful inquiring delivery carefully' },
      { speaker: 'yumiko_mom', jp: '正直に、話してみるのよ。', en: "Try talking honestly.", style: 'gentle older mother voice, soft warm guiding delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、勇気出してみる。', en: "Yeah — I'll find courage.", style: 'soft determined teen girl voice, warm gentle resolve delivered carefully' },
    ],
  },
  {
    id: 'conv_01607',
    context: 'Kenji and Aoi reflect on their reunion years after first meeting.',
    purpose: 'Couple reminiscing about fated reconnection tenderly.',
    ambient: 'porch_evening_breeze',
    sound_effects: [],
    target_vocab: ['縁', '再会', '出会い', '運命'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'あの再会、不思議だったね。', en: "That reunion — strange wasn't it.", style: 'soft adult woman voice, warm tender reflective delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほんま、縁を感じたわ。', en: "Truly — felt fate.", style: 'soft Kansai man voice, warm reverent delivery carefully' },
      { speaker: 'aoi_barista', jp: '十年ぶりの出会いだもの。', en: "Reunion after ten years.", style: 'gentle adult woman voice, soft warm fond delivery carefully' },
      { speaker: 'kenji_office', jp: '運命やったんかもしれん。', en: "Maybe it was fate.", style: 'soft Kansai man voice, warm philosophical delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、ロマンチックね。', en: "Heh — romantic.", style: 'warm adult woman voice, soft teasing tender delivery carefully' },
      { speaker: 'kenji_office', jp: 'たまには、こんなこと言うで。', en: "Sometimes I say things like this.", style: 'gentle Kansai man voice, soft warm shy delivery carefully' },
      { speaker: 'aoi_barista', jp: '嬉しい、本当に。', en: "Happy — truly.", style: 'tender adult woman voice, soft warm sincere delivery carefully' },
    ],
  },
  {
    id: 'conv_01608',
    context: 'Sho-young breaks something accidentally and tries to hide it; Mei finds out.',
    purpose: 'Mother gently teaching child about honesty.',
    ambient: 'kitchen_quiet_late',
    sound_effects: [],
    target_vocab: ['嘘', '本音', '正直', '謝る'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '翔くん、何かあった?', en: "Sho — something happen?", style: 'gentle young mother voice, soft warm careful inquiry delivered carefully' },
      { speaker: 'sho_child', jp: 'え、別に。', en: "Eh — nothing.", style: 'soft nervous child boy voice, warm guilty delivery carefully' },
      { speaker: 'mei_romantic', jp: '嘘、ついてるね?', en: "You're lying, aren't you?", style: 'soft young mother voice, warm gentle firmness delivered carefully' },
      { speaker: 'sho_child', jp: 'ごめんなさい、お皿割っちゃった。', en: "I'm sorry — broke a plate.", style: 'soft contrite child boy voice, warm honest tearful delivery carefully' },
      { speaker: 'mei_romantic', jp: '正直に言ってくれてありがとう。', en: "Thanks for telling the truth.", style: 'tender young mother voice, soft warm appreciative delivery carefully' },
      { speaker: 'sho_child', jp: '怒らないの?', en: "Not angry?", style: 'soft surprised child boy voice, warm hopeful delivery carefully' },
      { speaker: 'mei_romantic', jp: '本音を言える、勇気よ。', en: "Speaking your truth — that's courage.", style: 'warm young mother voice, soft warm teaching delivery carefully' },
    ],
  },
  {
    id: 'conv_01609',
    context: 'Sakura and Naoko spend a slow afternoon together; tea and gentle banter.',
    purpose: 'Quieter writer and gruff aunt unexpectedly close.',
    ambient: 'ramen_shop_quiet_afternoon',
    sound_effects: [],
    target_vocab: ['静か', '時間', '美味しい', '安らぎ'],
    cast: ['sakura_teen', 'naoko_aunt'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '静かな時間、ありがとうございます。', en: "Thank you for the quiet time.", style: 'soft adult writer voice, warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、お茶どうや?', en: "Heh — how's the tea?", style: 'warm Kansai aunt voice, soft fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '美味しい、ほっとします。', en: "Delicious — comforting.", style: 'gentle adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うちで安らいでくれて、嬉しいわ。', en: "Glad you can ease up here.", style: 'soft Kansai aunt voice, warm tender delivery carefully' },
      { speaker: 'sakura_teen', jp: 'おばさん、優しい。', en: "Auntie — you're kind.", style: 'tender adult writer voice, soft warm honest delivery carefully' },
    ],
  },
  {
    id: 'conv_01610',
    context: 'Hiroshi-elder talks to Saito about how to face his own old age.',
    purpose: 'Elder confiding fears about mortality; doctor responding warmly.',
    ambient: 'clinic_room_quiet',
    sound_effects: [],
    target_vocab: ['老い', '人生', '受け入れる', '感謝'],
    cast: ['hiroshi_elder', 'saito_doctor'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '先生、老いって、辛いもんやな。', en: "Doctor — old age is harsh.", style: 'slow elder Kansai voice, warm soft honest delivery carefully' },
      { speaker: 'saito_doctor', jp: 'お気持ち、わかります。', en: "I understand the feeling.", style: 'measured doctor voice, soft warm empathetic delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '体、思うように動かん。', en: "Body — won't move as I'd like.", style: 'gentle elder Kansai voice, soft warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: 'でも、無理なさらず。', en: "But — please don't overdo.", style: 'gentle doctor voice, soft warm caring delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '人生、考えるなぁ。', en: "Life — gives one pause.", style: 'soft elder Kansai voice, warm reflective delivery carefully' },
      { speaker: 'saito_doctor', jp: '受け入れる、難しいですね。', en: "Acceptance — hard.", style: 'tender doctor voice, soft warm understanding delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、感謝もあるんやけどな。', en: "Yeah — gratitude too, though.", style: 'gentle elder Kansai voice, soft warm humble delivery carefully' },
      { speaker: 'saito_doctor', jp: 'その気持ち、大切にしてください。', en: "Cherish that feeling.", style: 'warm doctor voice, soft tender wise delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '家族、大事にせなな。', en: "Family — must cherish.", style: 'soft elder Kansai voice, warm reflective resolved delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ご家族、本当に大切ですね。', en: "Family is truly precious.", style: 'gentle doctor voice, soft warm affirming delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '先生のおかげで、心軽くなった。', en: "Thanks to you — heart lighter.", style: 'warm elder Kansai voice, soft tender grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'いつでも、お話聞きます。', en: "Anytime — I'll listen.", style: 'tender doctor voice, soft warm loyal delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、ありがたいわ。', en: "Truly — grateful.", style: 'soft elder Kansai voice, warm humble delivery carefully' },
    ],
  },
  {
    id: 'conv_01611',
    context: 'Asuka tries pottery for the first time at Tatsuya\'s workshop.',
    purpose: 'Wife joining husband\'s craft tradition warmly.',
    ambient: 'workshop_clay_low',
    sound_effects: [],
    target_vocab: ['初めて', '楽しむ', '形', '工芸'],
    cast: ['asuka_teacher', 'tatsuya_country'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '初めての陶芸、緊張するわ。', en: "First time pottery — nervous.", style: 'warm teacher voice, soft eager honest delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ゆっくり、楽しんでな。', en: "Slowly — enjoy.", style: 'gentle Tohoku voice, soft warm patient delivery carefully' },
      { speaker: 'asuka_teacher', jp: '土、思ったより冷たい。', en: "Clay — colder than I thought.", style: 'soft teacher voice, warm honest sensory delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'すぐ、温うなるよ。', en: "Soon — warms up.", style: 'soft Tohoku farmer voice, warm reassuring delivery carefully' },
      { speaker: 'asuka_teacher', jp: '形、なかなか定まらない。', en: "Shape — won't settle.", style: 'soft teacher voice, warm honest struggling delivery carefully' },
      { speaker: 'tatsuya_country', jp: '工芸は、待つもんや。', en: "Craft — is patience.", style: 'gentle Tohoku voice, soft warm philosophical delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'なるほど、面白いわ。', en: "I see — interesting.", style: 'warm teacher voice, soft curious appreciative delivery carefully' },
    ],
  },
  {
    id: 'conv_01612',
    context: 'Ren and Kenji discuss imposter syndrome over late-night studio work.',
    purpose: 'Two artists honest about self-doubt in their work.',
    ambient: 'studio_late_lamp',
    sound_effects: [],
    target_vocab: ['自信', '不安', '才能', '信じる'],
    cast: ['ren_uni', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '健司さん、自分の才能、信じられません。', en: "Kenji-san — can't believe in my talent.", style: 'soft young man voice, warm raw vulnerable delivery carefully' },
      { speaker: 'kenji_office', jp: '俺も、ようけ感じたで。', en: "I felt that a lot too.", style: 'soft Kansai mentor voice, warm honest empathetic delivery carefully' },
      { speaker: 'ren_uni', jp: '不安、いつ消えるんですか?', en: "Anxiety — when does it go?", style: 'soft young man voice, warm honest searching delivery carefully' },
      { speaker: 'kenji_office', jp: '消えへん、付き合うもんや。', en: "Doesn't — you live with it.", style: 'gentle Kansai man voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: 'そうなんですか…。', en: "I see.", style: 'soft young man voice, warm thoughtful processing delivery carefully' },
      { speaker: 'kenji_office', jp: '不安があるからこそ、磨かれる。', en: "Anxiety — sharpens us.", style: 'soft Kansai mentor voice, warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: '信じてみます、自分を。', en: "I'll try believing in myself.", style: 'soft determined young man voice, warm gentle resolve delivered carefully' },
    ],
  },
  {
    id: 'conv_01613',
    context: 'Mei and Daichi argue gently about household chores; resolve warmly.',
    purpose: 'Marital tension lovingly worked through.',
    ambient: 'kitchen_evening_warm',
    sound_effects: [],
    target_vocab: ['手伝う', '分担', '不満', '謝る'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'ちょっと、手伝ってほしいな。', en: "Hey — want some help.", style: 'soft young wife voice, warm gentle assertive delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'え、なんかあった?', en: "Eh — something up?", style: 'soft Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '家事の分担、気になってて。', en: "Chore split — bothers me.", style: 'gentle young woman voice, soft warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ああ、確かにそうやな。', en: "Ah — true.", style: 'soft Kansai husband voice, warm honest acknowledging delivery carefully' },
      { speaker: 'mei_romantic', jp: '不満を、ためたくないの。', en: "Don't want to bottle frustration.", style: 'soft young wife voice, warm honest tender delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'すまんかった、もっと手伝うわ。', en: "Sorry — I'll help more.", style: 'soft Kansai husband voice, warm apologetic sincere delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、嬉しい。', en: "Thanks — happy.", style: 'tender young wife voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01614',
    context: 'Sho-young watches a meteor shower with Hiroshi-elder; quiet wonder.',
    purpose: 'Grandfather and grandson sharing simple awe.',
    ambient: 'yard_night_crickets',
    sound_effects: [],
    target_vocab: ['星', '夜空', '願い', '思う'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、星きれい!', en: "Grandpa — pretty stars!", style: 'bright child boy voice, soft warm awed delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、夜空澄んどるな。', en: "Truly — clear night.", style: 'soft elder Kansai voice, warm content delivery carefully' },
      { speaker: 'sho_child', jp: '願い、するの?', en: "Do we make a wish?", style: 'curious child boy voice, soft warm hopeful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええで、何思うてる?', en: "Sure — what are you thinking?", style: 'gentle elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'みんな、元気でいますように。', en: "May everyone stay well.", style: 'soft tender child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_01615',
    context: 'Naoko teaches Hina-young how to make takoyaki at the ramen shop.',
    purpose: 'Aunt teaching teen cooking with fond impatience.',
    ambient: 'ramen_shop_grill_sizzle',
    sound_effects: [],
    target_vocab: ['粉', '焼く', '形', '味'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、粉、こねるんやで。', en: "Hina — knead the batter.", style: 'brassy Kansai aunt voice, bright loud instructing delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、おばちゃん!', en: "Yes — auntie!", style: 'eager teen girl voice, bright cheerful warm delivery carefully' },
      { speaker: 'naoko_aunt', jp: '焼くの、回しながらや。', en: "Grilling — keep rotating.", style: 'animated Kansai aunt voice, bright firm teaching delivery carefully' },
      { speaker: 'hina_child', jp: '形、丸くなるかな。', en: "Will the shape come round?", style: 'soft teen girl voice, warm hopeful nervous delivery carefully' },
      { speaker: 'naoko_aunt', jp: '練習や、最初はええかげんでええ。', en: "It's practice — first try, loose.", style: 'warm Kansai aunt voice, soft encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '味、最高!', en: "Flavor — the best!", style: 'thrilled teen girl voice, bright warm cheerful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、当たり前や!', en: "Heh — of course!", style: 'brassy Kansai aunt voice, bright proud playful delivery carefully' },
    ],
  },
  {
    id: 'conv_01616',
    context: 'Sakura visits an old elementary teacher in retirement.',
    purpose: 'Adult thanking former mentor; quiet emotion.',
    ambient: 'tatami_quiet_kettle',
    sound_effects: [],
    target_vocab: ['先生', '恩', '昔', '感謝'],
    cast: ['sakura_teen', 'asuka_teacher'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '先生、お久しぶりです。', en: "Sensei — it's been a while.", style: 'soft adult writer voice, warm respectful tender delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'まあ、さくらちゃん、立派になって。', en: "Oh — Sakura, grown up so fine.", style: 'tender older teacher voice, soft warm proud delivery carefully' },
      { speaker: 'sakura_teen', jp: '昔のご恩、忘れていません。', en: "Haven't forgotten your kindness.", style: 'gracious adult writer voice, soft warm sincere delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ふふ、教師の喜びね。', en: "Heh — a teacher's joy.", style: 'warm older teacher voice, soft humble tender delivery carefully' },
      { speaker: 'sakura_teen', jp: 'おかげさまで、作家になれました。', en: "Thanks to you — became a writer.", style: 'humble adult writer voice, soft warm grateful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '自分の力よ、誇って。', en: "Your own strength — be proud.", style: 'gentle teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとうございます。', en: "Thank you.", style: 'tender adult writer voice, soft warm sincere delivery carefully' },
    ],
  },
  {
    id: 'conv_01617',
    context: 'Daichi and Ren talk about being older brothers; over coffee.',
    purpose: 'Two men sharing brotherly responsibility reflections.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['兄', '弟', '責任', '愛'],
    cast: ['daichi_kansai', 'ren_uni'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '蓮、弟との関係、どうや?', en: "Ren — how's your bond with your brother?", style: 'warm Kansai man voice, soft fond inquiring delivery carefully' },
      { speaker: 'ren_uni', jp: 'まだ、難しいです。', en: "Still — hard.", style: 'soft young man voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '兄として、悩むよな。', en: "As older brother — you worry.", style: 'soft Kansai man voice, warm empathetic delivery carefully' },
      { speaker: 'ren_uni', jp: '責任、感じます、ずっと。', en: "Feel responsibility — always.", style: 'soft young man voice, warm earnest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '愛があるから、悩む。', en: "Because there's love — you worry.", style: 'warm Kansai man voice, soft tender wise delivery carefully' },
      { speaker: 'ren_uni', jp: 'なるほど、心が軽くなりました。', en: "I see — feels lighter.", style: 'soft young man voice, warm grateful relieved delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お互いに、頑張ろうや。', en: "Both of us — keep at it.", style: 'warm Kansai man voice, soft brotherly delivery carefully' },
    ],
  },
  {
    id: 'conv_01618',
    context: 'Yumiko and Mrs. Mori at a craft fair selling small hand-knit items.',
    purpose: 'Two older women running a small charity table together.',
    ambient: 'fair_outdoor_chatter',
    sound_effects: [],
    target_vocab: ['手作り', '販売', 'チャリティー', '楽しい'],
    cast: ['yumiko_mom', 'mrs_mori_neighbor'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'お客さん、たくさん来てるわ。', en: "Many customers coming.", style: 'warm older neighbor voice, soft cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ほんとに、手作り喜ばれて。', en: "Truly — handmade pleases people.", style: 'gentle older mother voice, soft warm proud delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'チャリティーになって、嬉しい。', en: "Charity work — glad.", style: 'soft older woman voice, warm content delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'いい一日ね。', en: "Good day.", style: 'warm older mother voice, soft tender delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'また来年も、しましょうね。', en: "Let's do it next year too.", style: 'gentle older neighbor voice, soft warm friendly delivery carefully' },
    ],
  },
  {
    id: 'conv_01619',
    context: 'Hina-young and Riku-teen practice for a school play together.',
    purpose: 'Two teens helping each other rehearse lines warmly.',
    ambient: 'classroom_after_quiet',
    sound_effects: [],
    target_vocab: ['台本', '役', '練習', '舞台'],
    cast: ['riku_teen', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'この役、難しいなぁ。', en: "This role — tough.", style: 'soft teen girl voice, warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: '台本、もう一回読もか?', en: "Script — let's read once more?", style: 'casual teen boy voice, soft warm helpful delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、お願い。', en: "Yeah — please.", style: 'gentle teen girl voice, soft warm grateful delivery carefully' },
      { speaker: 'riku_teen', jp: '舞台、楽しみやな。', en: "Stage — looking forward.", style: 'bright teen boy voice, soft warm eager delivery carefully' },
      { speaker: 'hina_child', jp: '緊張するけど、頑張る。', en: "Nervous but I'll try.", style: 'soft determined teen girl voice, warm gentle resolve delivered carefully' },
    ],
  },
  {
    id: 'conv_01620',
    context: 'Goro-grandpa and Sachiko-grandma at a small temple for new year visit.',
    purpose: 'Elder couple sharing quiet traditional ritual.',
    ambient: 'temple_bell_distant',
    sound_effects: [],
    target_vocab: ['初詣', 'お参り', '神様', '願い'],
    cast: ['goro_grandpa', 'sachiko_grandma'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'お参り、できたわね。', en: "We've made our visit.", style: 'soft grandmother voice, warm content reverent delivery carefully' },
      { speaker: 'goro_grandpa', jp: 'うん、今年も無事に。', en: "Yeah — safely this year too.", style: 'gentle elder voice, soft warm humble delivery carefully' },
      { speaker: 'sachiko_grandma', jp: '神様に、感謝ね。', en: "Gratitude to the gods.", style: 'tender grandmother voice, soft warm spiritual delivery carefully' },
      { speaker: 'goro_grandpa', jp: '願い、何にした?', en: "What was your wish?", style: 'soft elder voice, warm fond inquiry delivered carefully' },
      { speaker: 'sachiko_grandma', jp: '家族の健康、いつものこと。', en: "Family health — as always.", style: 'warm grandmother voice, soft tender consistent delivery carefully' },
    ],
  },
  {
    id: 'conv_01621',
    context: 'Hiroshi-boss arranges flowers for a memorial; Sakura helps.',
    purpose: 'Boss and writer sharing somber quiet preparation.',
    ambient: 'temple_room_quiet',
    sound_effects: [],
    target_vocab: ['花', '供える', '故人', '心'],
    cast: ['hiroshi_boss', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: 'この花、故人が好きやった。', en: "These flowers — the deceased loved.", style: 'soft boss voice, warm tender reverent delivery carefully' },
      { speaker: 'sakura_teen', jp: '優しい色ですね。', en: "Gentle color.", style: 'gentle adult writer voice, soft warm respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '供える時は、心こめて。', en: "When offering — with full heart.", style: 'measured boss voice, soft warm wise delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、丁寧にいたします。', en: "Yes — I'll do it carefully.", style: 'soft adult writer voice, warm reverent delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '故人、喜んでくれるやろ。', en: "The deceased — will be glad.", style: 'warm boss voice, soft tender delivery carefully' },
      { speaker: 'sakura_teen', jp: 'そう、信じています。', en: "Yes — I believe so.", style: 'tender adult writer voice, soft warm faithful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ありがとう、手伝ってくれて。', en: "Thanks for helping.", style: 'soft boss voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01622',
    context: 'Aoi takes Sho-young and Hina-young apple-picking at a small farm.',
    purpose: 'Adult mentor leading children on simple outing.',
    ambient: 'orchard_breeze_birds',
    sound_effects: [],
    target_vocab: ['りんご', '甘い', '木', '収穫'],
    cast: ['aoi_barista', 'sho_child', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '蒼さん、りんご大きい!', en: "Aoi-san — apples are huge!", style: 'excited child boy voice, bright cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: '甘そうだね、選んでね。', en: "Looks sweet — pick one.", style: 'warm adult woman voice, soft fond delivery carefully' },
      { speaker: 'hina_child', jp: 'この木、低くて取りやすい。', en: "This tree's low — easy.", style: 'bright teen girl voice, soft warm observant delivery carefully' },
      { speaker: 'sho_child', jp: '俺、これにする!', en: "I'll get this one!", style: 'energetic child boy voice, bright warm decisive delivery carefully' },
      { speaker: 'aoi_barista', jp: '収穫、楽しいね。', en: "Picking — fun.", style: 'soft adult woman voice, warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_01623',
    context: 'Tatsuya-country and his daughter Asuka share a long letter exchange.',
    purpose: 'Married couple sharing one daughter\'s letter together tenderly.',
    ambient: 'tatami_lamp_evening',
    sound_effects: [],
    target_vocab: ['手紙', '便り', '元気', '心'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '娘から、手紙来た。', en: "Letter from our daughter came.", style: 'soft Tohoku voice, warm tender fond delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'まあ、嬉しい。読んで。', en: "Oh — happy. Read it.", style: 'warm teacher voice, soft eager fond delivery carefully' },
      { speaker: 'tatsuya_country', jp: '東京で、元気にしてる。', en: "She's well in Tokyo.", style: 'gentle Tohoku voice, soft warm content delivery carefully' },
      { speaker: 'asuka_teacher', jp: '安心するわ、毎度。', en: "Reassuring — every time.", style: 'tender teacher voice, soft warm grateful delivery carefully' },
      { speaker: 'tatsuya_country', jp: '帰省、来月予定や。', en: "Visit home — scheduled next month.", style: 'soft Tohoku farmer voice, warm cheerful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '楽しみね、お料理準備しよう。', en: "Looking forward — let's cook.", style: 'bright teacher voice, soft warm eager delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、好きなもん作ろ。', en: "Yeah — make her favorites.", style: 'soft Tohoku voice, warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01624',
    context: 'Kenji and Hiroshi-elder visit a small graveyard at dusk.',
    purpose: 'Friend supporting elder during quiet memorial visit.',
    ambient: 'graveyard_dusk_quiet',
    sound_effects: [],
    target_vocab: ['墓', '線香', '想い出', '静か'],
    cast: ['kenji_office', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '墓参り、ありがとうな。', en: "Grave visit — thanks.", style: 'slow elder Kansai voice, warm tender grateful delivery carefully' },
      { speaker: 'kenji_office', jp: 'おとうさん、当然です。', en: "Otosan — of course.", style: 'soft Kansai man voice, warm respectful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '線香、立てよか。', en: "Light incense?", style: 'gentle elder Kansai voice, soft warm reverent delivery carefully' },
      { speaker: 'kenji_office', jp: 'はい、お手伝いします。', en: "Yes — I'll help.", style: 'soft Kansai man voice, warm respectful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '静かな夕方、ええなぁ。', en: "Quiet evening — lovely.", style: 'soft elder Kansai voice, warm reflective delivery carefully' },
    ],
  },
  {
    id: 'conv_01625',
    context: 'Sakura wraps up a writing retreat with a personal reflection alone, then chats with Ren.',
    purpose: 'Writer sharing creative breakthrough; mentor encouraging.',
    ambient: 'cabin_evening_lamp',
    sound_effects: [],
    target_vocab: ['書く', '自分', '心', '解放'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、今日、自分が見えた。', en: "Ren — today I saw myself.", style: 'soft adult writer voice, warm tender revelatory delivery carefully' },
      { speaker: 'ren_uni', jp: 'どんな感じでしたか?', en: "What did it feel like?", style: 'gentle young man voice, soft warm curious delivery carefully' },
      { speaker: 'sakura_teen', jp: '心が、解放された感じ。', en: "Heart — felt freed.", style: 'tender adult writer voice, soft warm awed delivery carefully' },
      { speaker: 'ren_uni', jp: 'ええことですね、本当に。', en: "That's truly lovely.", style: 'warm young man voice, soft sincere delivery carefully' },
      { speaker: 'sakura_teen', jp: '書きたいこと、たくさん出てきた。', en: "So much I want to write surfaced.", style: 'soft adult writer voice, warm energized delivery carefully' },
      { speaker: 'ren_uni', jp: '溢れる時、書き留めましょう。', en: "When it overflows — capture it.", style: 'soft young man voice, warm wise delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、ノート手放さない。', en: "Yeah — won't let go of my notebook.", style: 'soft adult writer voice, warm resolved delivery carefully' },
      { speaker: 'ren_uni', jp: 'これからが、楽しみです。', en: "Looking forward from here.", style: 'warm young man voice, soft tender encouraging delivery carefully' },
      { speaker: 'sakura_teen', jp: '一緒に、編集してくれる?', en: "Will you edit with me?", style: 'soft adult writer voice, warm hopeful delivery carefully' },
      { speaker: 'ren_uni', jp: 'もちろん、いつでも。', en: "Of course — anytime.", style: 'gentle young man voice, soft warm loyal delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとう、本当に心強い。', en: "Thanks — truly encouraging.", style: 'tender adult writer voice, soft warm grateful delivery carefully' },
      { speaker: 'ren_uni', jp: 'お互いに、磨き合いましょう。', en: "Let's hone each other.", style: 'soft young man voice, warm collaborative delivery carefully' },
      { speaker: 'sakura_teen', jp: 'これからの作品、楽しみ。', en: "Looking forward to future works.", style: 'warm adult writer voice, soft eager content delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_081 wrote', CONVERSATIONS.length, 'files');
