import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_147)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // count-4/3 cleanup (示す 後半 住む 売れ 左右 落とし 乗る 生き方 備え)
  C('conv_02921',
    'Ren and Mei discuss a documentary on a craftsman.',
    'Casual register; vocabulary (示す/後半/住む/売れ/生き方) in natural home.',
    'cafe_quiet_chatter',
    ['示す', '後半', '住む', '売れ', '生き方'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの職人の生き方、素敵だったね。', en: "That craftsman's way of life was lovely.", style: 'soft warm woman voice, gentle reflective delivery throughout' },
      { speaker: 'ren_uni', jp: '番組の後半が、特に良かったよ。', en: "The latter half was especially good.", style: 'warm young man voice, soft warm reflective delivery throughout' },
      { speaker: 'mei_romantic', jp: '山に住む暮らし、憧れるな。', en: "I admire that life living in the mountains.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '作品は、よく売れているらしいよ。', en: "His works reportedly sell well.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '売れても、生き方は変えないんだね。', en: "Even selling well, he doesn't change his way of life.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '後半で、彼の信念を示していたね。', en: "In the latter half, he showed his conviction.", style: 'thoughtful young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '私も、自分の生き方を考えたいな。', en: "I want to think about my own way of life too.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'どこに住むかも、生き方を示すよね。', en: "Where you live also shows your way of life.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  // CLUSTER A — casual particles (なー ねー よー っていう オレ 逆に)
  C('conv_02922',
    'Riku and Daichi chat super-casually about a game.',
    'Casual register; speech particles (なー/ねー/よー/っていう/オレ) in natural home.',
    'cafe_quiet_chatter',
    ['なー', 'ねー', 'よー', 'っていう', 'オレ'],
    ['riku_teen', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'あのゲーム、めっちゃ面白いんだよなー。', en: "That game is super fun, you know.", style: 'casual teen boy voice, bright warm relaxed delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ほんまかー、オレもやってみたいなー。', en: "Really, I want to try it too.", style: 'lively Kansai man voice, warm hearty relaxed delivery throughout' },
      { speaker: 'riku_teen', jp: 'ラスボスっていう敵が、強いんだよー。', en: "The final boss enemy is so strong.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'へえ、それは燃えるねー。', en: "Oh, that gets you fired up.", style: 'cheerful Kansai man voice, warm relaxed delivery throughout' },
      { speaker: 'riku_teen', jp: 'オレ、まだクリアできてないんだよなー。', en: "I still haven't cleared it.", style: 'rueful teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '逆に、それが楽しいんちゃう?', en: "On the contrary, isn't that the fun part?", style: 'lively Kansai man voice, warm playful delivery throughout' },
      { speaker: 'riku_teen', jp: '攻略っていう動画、見ようかなー。', en: "Maybe I'll watch a walkthrough video.", style: 'thoughtful teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'オレも一緒に見るよー!', en: "I'll watch it with you!", style: 'cheerful Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_02923',
    'Aoi and Riku gossip casually about a show.',
    'Casual register; speech particles (なー/ねー/よー/っていう/逆に) in natural home.',
    'cafe_quiet_chatter',
    ['なー', 'ねー', 'よー', 'っていう', '逆に'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'あのドラマ、最終回が良かったよねー。', en: "That drama's finale was good, wasn't it.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、泣けたっていう感じだったなー。', en: "Yeah, it was kind of a tearjerker.", style: 'casual teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '主役の演技、すごかったよねー。', en: "The lead's acting was amazing, right.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: '逆に、脇役の方が好きだったなー。', en: "On the contrary, I liked the side characters more.", style: 'playful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'えー、そっちかーい!', en: "What, that one!", style: 'giggly barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '裏切るっていう展開、好きなんだよなー。', en: "I love that kind of betrayal twist.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '逆に、私は王道が好きだよー。', en: "Conversely, I like the classic route.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: '次のシリーズも、楽しみだねー!', en: "I'm looking forward to the next series too!", style: 'eager teen boy voice, bright warm cheerful closing delivery throughout' },
    ]),

  C('conv_02924',
    'Daichi and Aoi chat lazily about the weather.',
    'Casual register; speech particles (なー/ねー/よー/オレ/逆に) in natural home.',
    'cafe_quiet_chatter',
    ['なー', 'ねー', 'よー', 'オレ', '逆に'],
    ['daichi_kansai', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '今日は、ええ天気やねー。', en: "Nice weather today, huh.", style: 'lively Kansai man voice, warm hearty relaxed delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ほんと、お散歩日和だよねー。', en: "Really, perfect for a walk.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'オレ、こういう日が好きなんよなー。', en: "I love days like this.", style: 'warm Kansai man voice, warm relaxed delivery throughout' },
      { speaker: 'aoi_barista', jp: '暑すぎないのが、いいよねー。', en: "Not too hot — that's nice.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '逆に、ちょっと風が冷たいかなー。', en: "On the contrary, the wind's a bit cold.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'じゃあ、温かいの淹れるよー。', en: "Then I'll brew something warm.", style: 'warm barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'オレ、コーヒーがええなー。', en: "I'd like coffee.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'はーい、すぐ持ってくるよー!', en: "Sure, I'll bring it right over!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  // CLUSTER B — home (かける 置か 残さ 我が家 以内)
  C('conv_02925',
    'Yumiko and Sho do a quick home tidy.',
    'Casual home register; vocabulary (かける/置か/残さ/我が家/以内) in natural home.',
    'kitchen_evening_quiet',
    ['かける', '置か', '残さ', '我が家', '以内'],
    ['yumiko_mom', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'yumiko_mom', jp: '十分以内に、片付けちゃいましょう。', en: "Let's tidy up within ten minutes.", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: 'はーい!本は棚に置けばいい?', en: "Okay! Do I put the books on the shelf?", style: 'cheerful small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'そうね、上着は椅子にかけてね。', en: "Yes, hang your jacket on the chair.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'おもちゃ、全部置いたよ!', en: "I put away all the toys!", style: 'proud small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'ご飯を、残さず食べたわね。えらいわ。', en: "You ate without leaving any. Good job.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '我が家、ピカピカになったね!', en: "Our house got sparkling clean!", style: 'happy small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '時間以内に、終わったわね。', en: "We finished within the time.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'タオルも、かけておいたよ!', en: "I hung up the towels too!", style: 'cheerful small child voice, bright warm affectionate closing delivery throughout' },
    ]),

  C('conv_02926',
    'Mei and Aoi organize a small home party.',
    'Casual register; vocabulary (かける/置か/残さ/我が家/以内) in natural home.',
    'living_room_quiet',
    ['かける', '置か', '残さ', '我が家', '以内'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '我が家で、小さなパーティーをするの。', en: "I'm having a small party at my place.", style: 'soft warm woman voice, gentle excited delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね!料理は、いつ頃置く?', en: "Nice! When do we set out the food?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '一時間以内に、並べたいな。', en: "I'd like to lay it out within an hour.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '飾りは、壁にかけようか?', en: "Shall we hang decorations on the wall?", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、お皿はここに置いてね。', en: "Yeah, put the plates here.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '料理、残さず食べてもらおうね。', en: "Let's have them eat without leaving anything.", style: 'warm barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '我が家が、にぎやかになりそう。', en: "Our home is going to be lively.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '時間以内に、準備しちゃおう!', en: "Let's get ready within the time!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02927',
    'Kenji helps Ren set up a workspace at home.',
    'WIDENED SCENARIO: home-office setup; vocabulary (かける/置か/残さ/我が家/以内) in natural home.',
    'living_room_quiet',
    ['かける', '置か', '残さ', '我が家', '以内'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '我が家に、作業机を置きたいんです。', en: "I want to put a work desk in my home.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '机は、窓際に置くといいですよ。', en: "It's good to put the desk by the window.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'ケーブルは、壁にかけますか?', en: "Do I hang the cables on the wall?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、かけておくと、すっきりします。', en: "Yes, hanging them keeps it tidy.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '配線を、残さず束ねたいです。', en: "I want to bundle the wiring without leaving any loose.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '一時間以内に、終わりそうですね。', en: "It seems we'll finish within an hour.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '我が家が、仕事場になりますね。', en: "My home becomes a workplace.", style: 'satisfied young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '物を置く場所を、決めておきましょう。', en: "Let's decide where to put things.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // CLUSTER C — sports/game (ゴール スピード プレイ 連続 盤 群)
  C('conv_02928',
    'Riku and Aoi recap a thrilling soccer match.',
    'Casual register; vocabulary (ゴール/スピード/プレイ/連続/群) in natural home.',
    'cafe_quiet_chatter',
    ['ゴール', 'スピード', 'プレイ', '連続', '群'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '昨日の試合、ゴールが決まった瞬間最高だった!', en: "Yesterday's match — the moment the goal went in was the best!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'スピードが、すごかったらしいね!', en: "The speed was apparently amazing!", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、連続でパスをつないだんだ。', en: "Yeah, they linked passes in a row.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'チームの、プレイが見事だったの?', en: "Was the team's play splendid?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '一人の選手が、群を抜いてたよ。', en: "One player stood out from the crowd.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '連続ゴールも、あったの?', en: "Were there consecutive goals too?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '後半に、連続でゴールしたんだ!', en: "In the second half, they scored consecutively!", style: 'thrilled teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そのスピードあるプレイ、見たかったなー!', en: "I wish I'd seen that fast play!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02929',
    'Riku and Daichi discuss a board game tournament.',
    'Casual register; vocabulary (ゴール/スピード/プレイ/連続/盤) in natural home.',
    'cafe_quiet_chatter',
    ['ゴール', 'スピード', 'プレイ', '連続', '盤'],
    ['riku_teen', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '将棋の大会、出てみたいんだ。', en: "I want to enter a shogi tournament.", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ええなあ、盤の前で集中するんやろ?', en: "Nice, you focus in front of the board, right?", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'riku_teen', jp: '盤を見て、スピードよく指すんだ。', en: "You look at the board and move quickly.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '連続で勝てたら、かっこええなー。', en: "Winning consecutively would be cool.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'riku_teen', jp: '相手のプレイを、読むのが大事なんだ。', en: "Reading the opponent's play matters.", style: 'thoughtful teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ゲームにも、ゴールがあるんやな。', en: "Games have a goal too, huh.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、勝ちっていうゴールを目指すんだ。', en: "Yeah, you aim for the goal of winning.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '連続優勝、応援しとるで!', en: "I'm rooting for a winning streak!", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_02930',
    'Kenji and Ren test a new game app.',
    'WIDENED SCENARIO: tech/game; vocabulary (ゴール/スピード/プレイ/連続/盤) in natural home.',
    'office_quiet_low',
    ['ゴール', 'スピード', 'プレイ', '連続', '盤'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この新しいゲーム、プレイしてみました。', en: "I tried playing this new game.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '動きの、スピードはどうでしたか?', en: "How was the movement speed?", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'スピードが速くて、爽快でした。', en: "It was fast and exhilarating.", style: 'enthusiastic young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '盤面の表示は、見やすかったですか?', en: "Was the board display easy to see?", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '盤がきれいで、プレイしやすかったです。', en: "The board was clean and easy to play on.", style: 'satisfied young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '連続でプレイすると、疲れませんか?', en: "Don't you tire from playing continuously?", style: 'curious office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '連続でやっても、楽しいんです。', en: "Even playing in a row, it's fun.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '最終ゴールまで、よく作られていますね。', en: "It's well-made all the way to the final goal.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // CLUSTER D — lecture (含ま 作ら 層 生じ 考えれ 箇所)
  C('conv_02931',
    'Asuka lectures on how layers form in rock.',
    'WIDENED SCENARIO: science lecture; vocabulary (含ま/作ら/層/生じ/箇所) in natural home.',
    'lecture_hall_quiet',
    ['含ま', '作ら', '層', '生じ', '箇所'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '岩には、いくつもの層が含まれます。', en: "Rock contains many layers.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '層は、どうやって作られるんですか?', en: "How are layers formed?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '長い時間をかけて、作られます。', en: "They're formed over a long time.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '隙間が、生じることもありますか?', en: "Do gaps sometimes form too?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、弱い箇所に隙間が生じます。', en: "Yes, gaps form at weak spots.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'その箇所は、どう調べるんですか?', en: "How do you examine those spots?", style: 'thoughtful teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '層に含まれる成分を、調べます。', en: "We examine the components contained in the layers.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '層を見れば、歴史が分かるんですね。', en: "By looking at layers, we learn history.", style: 'moved teen boy voice, soft warm realization throughout' },
    ]),

  C('conv_02932',
    'Asuka guides Ren on revising a draft.',
    'WIDENED SCENARIO: writing guidance; vocabulary (含ま/作ら/層/生じ/考えれ/箇所) in natural home.',
    'lecture_hall_quiet',
    ['含ま', '作ら', '生じ', '考えれ', '箇所'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この文章、直す箇所はありますか?', en: "Are there spots to fix in this essay?", style: 'earnest young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '数箇所、誤解が生じやすいですね。', en: "In a few spots, misunderstanding easily arises.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: 'どう考えれば、直せますか?', en: "How should I think to fix it?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '読者の立場で考えれば、見えてきます。', en: "If you think from the reader's side, it becomes visible.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '結論に、意図が含まれていますか?', en: "Is the intent contained in the conclusion?", style: 'thoughtful young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '意図が、うまく含まれていますよ。', en: "The intent is contained well.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '良い文章は、丁寧に作られるんですね。', en: "Good writing is crafted carefully.", style: 'understanding young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'その箇所を直せば、より良くなります。', en: "Fix those spots and it'll be better.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02933',
    'Ren reports a quality issue to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (含ま/作ら/生じ/考えれ/箇所) in natural home.',
    'office_quiet_low',
    ['含ま', '作ら', '生じ', '考えれ', '箇所'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '製品に、不良の箇所が見つかりました。', en: "A defective spot was found in the product.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'どこで、不良が生じたのかね?', en: "Where did the defect arise?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '作られる工程で、生じたようです。', en: "It seems to have arisen during the production process.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '原因に、何が含まれているかね?', en: "What's contained in the cause?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '温度の管理が、含まれていました。', en: "Temperature control was involved.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'どう考えれば、防げるかね?', en: "How should we think to prevent it?", style: 'engaged boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '工程ごとに考えれば、防げます。', en: "If we think process by process, we can prevent it.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'その箇所を、すぐ直してくれ。', en: "Fix that spot right away.", style: 'decisive boss voice, soft warm closing throughout' },
    ]),

  // CLUSTER E — events (周年 ごろ 辺り 人数 気に入っ 秘密)
  C('conv_02934',
    'Yuki and Hiroshi-boss plan an anniversary event.',
    'WIDENED SCENARIO: business event planning; vocabulary (周年/ごろ/辺り/人数/秘密) in natural home.',
    'office_quiet_low',
    ['周年', 'ごろ', '辺り', '人数', '秘密'],
    ['yuki_office', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '創立十周年の式典を、計画します。', en: "I'll plan the tenth-anniversary ceremony.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'いつ頃、開くのがいいかね?', en: "Around when should we hold it?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '春ごろが、良いと思います。', en: "Around spring would be good.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '会場は、どの辺りにするかね?', en: "Around what area for the venue?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '駅の辺りの、ホールが便利です。', en: "A hall around the station is convenient.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '人数は、どのくらいになるかね?', en: "About how many people?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '人数は、百名ほどの見込みです。', en: "We expect around a hundred.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '余興は、当日まで秘密にしよう。', en: "Let's keep the entertainment secret until the day.", style: 'warm boss voice, soft warm playful closing throughout' },
    ]),

  C('conv_02935',
    'Mei and Aoi plan a surprise anniversary.',
    'Casual register; vocabulary (周年/ごろ/辺り/人数/秘密) in natural home.',
    'cafe_quiet_chatter',
    ['周年', 'ごろ', '辺り', '人数', '秘密'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'お店の五周年を、お祝いしたいの。', en: "I want to celebrate the shop's fifth anniversary.", style: 'soft warm woman voice, gentle excited delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね!何時ごろ集まる?', en: "Nice! Around what time do we gather?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '夕方ごろが、いいかな。', en: "Around evening would be nice.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'この辺りの友達を、呼ぼうよ。', en: "Let's invite friends from around here.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '人数は、十人くらいかな。', en: "About ten people, maybe.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '店長には、秘密にしておこう。', en: "Let's keep it secret from the manager.", style: 'playful barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、周年のサプライズ、楽しみ!', en: "Yeah, the anniversary surprise — exciting!", style: 'delighted woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '人数が増えたら、また相談しようね。', en: "If the headcount grows, let's discuss again.", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02936',
    'Riku and Yumiko plan a family celebration.',
    'Casual home register; vocabulary (周年/ごろ/辺り/人数/気に入っ) in natural home.',
    'kitchen_evening_quiet',
    ['周年', 'ごろ', '辺り', '人数', '気に入っ'],
    ['riku_teen', 'yumiko_mom'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'お母さん、結婚記念は何周年?', en: "Mom, which wedding anniversary is it?", style: 'curious teen boy voice, bright warm engaged delivery throughout' },
      { speaker: 'yumiko_mom', jp: '今年で、二十周年になるのよ。', en: "This year makes it the twentieth.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'お祝い、何時ごろにする?', en: "Around what time for the celebration?", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '夜ごろ、みんなで集まりましょう。', en: "Let's all gather around evening.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: '人数は、おじいちゃんたちも入れて?', en: "Headcount including grandpa and the others?", style: 'engaged teen boy voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'ええ、人数は八人くらいね。', en: "Yes, about eight people.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'この辺りのお店、気に入ってるんだ。', en: "I like the shops around here.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'お父さんが気に入った店に、しましょうね。', en: "Let's go with the shop Dad liked.", style: 'tender mother voice, soft warm affectionate closing delivery throughout' },
    ]),

  // CLUSTER F — Setsubun shop festival (鬼 新しく とら おっしゃる パー 剤)
  C('conv_02937',
    'Daichi preps a Setsubun event at his shop.',
    'WIDENED SCENARIO: festival prep; vocabulary (鬼/新しく/とら/おっしゃる/パー) in natural home.',
    'street_quiet_distant',
    ['鬼', '新しく', 'とら', 'おっしゃる', 'パー'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '節分やから、鬼の役、やるんよ。', en: "It's Setsubun, so I'll play the demon.", style: 'lively Kansai man voice, warm hearty playful delivery throughout' },
      { speaker: 'mei_romantic', jp: '豆は、新しく仕入れたんですか?', en: "Did you newly stock the beans?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'そや、新しく箱で買うたで。', en: "Yeah, I bought a new box.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '豆まきは、パーッと撒くんですか?', en: "Do you scatter the beans with a flourish?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'パーッと撒いて、鬼を追い出すんや。', en: "Scatter them with gusto and drive out the demon.", style: 'lively Kansai man voice, warm playful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'お客さんは、何ておっしゃってました?', en: "What did the customers say?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '「楽しみや」と、おっしゃってたで。', en: "They said they're looking forward to it.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'まだ準備、終わっとらんけどな!', en: "Though I haven't finished prepping yet!", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_02938',
    'Daichi and Sho play during the Setsubun event.',
    'WIDENED SCENARIO: festival; vocabulary (鬼/新しく/とら/おっしゃる/パー) in natural home.',
    'street_quiet_distant',
    ['鬼', '新しく', 'とら', 'おっしゃる', 'パー'],
    ['daichi_kansai', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おじさん、鬼さんになって!', en: "Mister, be the demon!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'よっしゃ、鬼やるで。豆、パーッと投げや!', en: "Alright, I'll be the demon. Throw the beans with gusto!", style: 'lively Kansai man voice, warm playful delivery throughout' },
      { speaker: 'sho_child', jp: '新しい豆、いっぱいあるよ!', en: "There are lots of new beans!", style: 'cheerful small child voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '新しく買うた豆や、たくさん撒きや。', en: "Newly bought beans — scatter plenty.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'sho_child', jp: '鬼さん、こっち見とらんね!今だ!', en: "The demon isn't looking this way! Now!", style: 'gleeful small child voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'うわー、やられたー!', en: "Whoa, you got me!", style: 'lively Kansai man voice, warm theatrical delivery throughout' },
      { speaker: 'sho_child', jp: 'ママが、上手だねっておっしゃってたよ!', en: "Mom said you're good at it!", style: 'happy small child voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'はは、また来年も鬼やるでー!', en: "Haha, I'll be the demon again next year!", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_02939',
    'Daichi cleans up after the festival with Aoi.',
    'WIDENED SCENARIO: cleanup chat; vocabulary (鬼/新しく/とら/おっしゃる/剤) in natural home.',
    'street_quiet_distant',
    ['鬼', '新しく', 'とら', 'おっしゃる', '剤'],
    ['daichi_kansai', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '節分、盛り上がったね!後片付けしよう。', en: "Setsubun was lively! Let's clean up.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'daichi_kansai', jp: '床、まだ拭けとらんわ。洗剤あるか?', en: "I haven't wiped the floor yet. Got detergent?", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'aoi_barista', jp: '新しい洗剤、買っておいたよ。', en: "I bought new detergent.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'おお、新しく買うてくれたんか、助かるわ。', en: "Oh, you bought new ones, that helps.", style: 'warm Kansai man voice, warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '鬼のお面、片付けておくね。', en: "I'll put away the demon mask.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'お客さん、また来たいておっしゃってたで。', en: "The customers said they want to come again.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'この洗剤、よく落ちるね!', en: "This detergent cleans well!", style: 'bright barista voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'まだ豆、拾いきれとらんけどな!', en: "Though I haven't picked up all the beans yet!", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  // count-3 cleanup (備え) + count-2 (連続) + count-1 seeds
  C('conv_02940',
    'Saito advises Yuki on preventive health.',
    'WIDENED SCENARIO: medical advice; vocabulary (備え/連続/剤/パー/新しく) in natural home.',
    'clinic_room_quiet',
    ['備え', '連続', '剤', 'パー', '新しく'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '先生、風邪を引きやすいんです。', en: "Doctor, I catch colds easily.", style: 'concerned office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '日頃の備えが、大切ですよ。', en: "Everyday preparation is important.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: '連続して、体調を崩してしまって。', en: "I keep getting sick one after another.", style: 'tired office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '新しく、ビタミン剤を勧めましょう。', en: "Let me newly recommend a vitamin supplement.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: 'その剤は、効果がありますか?', en: "Does that supplement work?", style: 'curious office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '回復が、数パーセント早まります。', en: "Recovery speeds up by a few percent.", style: 'clear doctor voice, soft warm measured clarity throughout' },
      { speaker: 'yuki_office', jp: '備えあれば、安心ですね。', en: "Being prepared is reassuring.", style: 'understanding office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '連続の無理を、避けて下さいね。', en: "Please avoid pushing yourself repeatedly.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_147 wrote', CONVERSATIONS.length, 'files');
