import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_117)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 5, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02321',
    'Sho-young describes a colorful bug he saw to Mei.',
    'Child sharing nature observation with mother.',
    'living_room_evening_warm',
    ['茶色', '小さく', '乗り物', '機嫌', '優しい', '心', '楽しい', '飛ぶ'],
    ['sho_child', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'お母さん、茶色の虫、見た!', en: "Mom — brown bug, saw!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、小さく可愛い虫?', en: "Oh — small cute bug?", style: 'gentle young mother voice, soft warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: '乗り物みたいに、ようけ速く飛ぶ!', en: "Vehicle-like — much fast flies!", style: 'animated child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '機嫌、良さそうね、あなた。', en: "Mood — good seems, you.", style: 'soft young mother voice, warm warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '優しく、見守ってた、心、温かい!', en: "Gently — watched, heart, warm!", style: 'soft tender child boy voice, warm warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ふふ、楽しい一日ね。', en: "Heh — fun day.", style: 'tender young mother voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、また、見たい!', en: "Yeah — again, want see!", style: 'bright child boy voice, soft warm eager delivery carefully' },
    ]),
  C('conv_02322',
    'Daichi adjusts the home AC; comments on the heat with Mei.',
    'Couple in everyday domestic chat.',
    'living_room_evening_warm',
    ['冷房', 'リモコン', '体温', '熱い', '直ぐに', '機嫌', '気軽', '快適'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'メイ、冷房、リモコンで入れるわ。', en: "Mei — AC, remote with put.", style: 'warm Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '体温、上がってる感じ、暑いね。', en: "Body temp — rising feel, hot.", style: 'soft young wife voice, warm warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '直ぐに、涼しくなるで。', en: "Soon — cool become.", style: 'soft Kansai husband voice, warm warm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: '機嫌、ようけ良くなるわ、これで。', en: "Mood — much better, this.", style: 'gentle young woman voice, soft warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '気軽に、快適に、過ごそうな。', en: "Casually — comfortably, spend.", style: 'warm Kansai husband voice, soft warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、助かる。', en: "Thanks — saved.", style: 'soft young wife voice, warm warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前のためや!', en: "For you!", style: 'tender Kansai husband voice, soft warm loving delivery carefully' },
    ]),
  C('conv_02323',
    'Saito checks Sho-young\'s temperature; mild fever care.',
    'Doctor caring for child fever.',
    'clinic_room_quiet',
    ['体温', '症状', '熱い', '直ぐに', '回復', '優しい', '安心', '休む'],
    ['saito_doctor', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'saito_doctor', jp: '翔くん、体温、測ってみようね。', en: "Sho — temperature, measure.", style: 'measured doctor voice, soft warm gentle delivery carefully' },
      { speaker: 'sho_child', jp: '先生、熱い感じ、する。', en: "Doctor — hot feel, exists.", style: 'soft tearful child boy voice, warm warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '症状、軽いから、安心して。', en: "Symptom — light, relax.", style: 'tender doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: '直ぐに、回復する?', en: "Soon — recover?", style: 'soft hopeful child boy voice, warm warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '優しく、休めば、すぐ良くなるよ。', en: "Gently — rest, soon better.", style: 'gentle doctor voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、先生!', en: "Thanks — doctor!", style: 'soft relieved child boy voice, warm warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'お母さん、心配いりませんよ。', en: "Mom — no worry.", style: 'warm doctor voice, soft warm reassuring delivery carefully' },
    ]),
  C('conv_02324',
    'Aoi joins a community chorus; tells Kenji about it.',
    'Wife sharing new hobby with husband.',
    'living_room_evening_lamp',
    ['コーラス', '唱える', '歌', '気軽', '深く', '心', '楽しい', '熱心'],
    ['aoi_barista', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'けんちゃん、コーラス、始めたの!', en: "Ken-chan — chorus, started!", style: 'bright adult woman voice, soft warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: 'まあ、歌、唱えるんやな、ええなぁ。', en: "Oh — song, sing, lovely.", style: 'warm Kansai husband voice, soft warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '気軽に、皆と、歌えて嬉しい。', en: "Casually — all, sing happy.", style: 'soft adult woman voice, warm warm content delivery carefully' },
      { speaker: 'kenji_office', jp: '深く、心、込めて歌うんやろ?', en: "Deeply — heart, put sing?", style: 'gentle Kansai husband voice, soft warm engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、熱心な皆さん、ようけいる。', en: "Yeah — passionate all, much exists.", style: 'tender adult woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'kenji_office', jp: '今度、聞かせてや。', en: "Next — let hear.", style: 'warm Kansai husband voice, soft warm eager delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、楽しみにしてて!', en: "Heh — look forward!", style: 'bright adult woman voice, soft warm cheerful delivery carefully' },
    ]),
  C('conv_02325',
    'Naoko serves a special set meal; explains its origin to a customer.',
    'Aunt warmly explaining a dish.',
    'ramen_shop_busy',
    ['玄米', 'ご馳走', '本場', '味', '丁寧', '深く', '尽くし', '感心'],
    ['naoko_aunt', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'naoko_aunt', jp: '蓮、今日のご馳走、玄米使ったで!', en: "Ren — today feast, brown rice used!", style: 'animated Kansai aunt voice, bright warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: '本場の味、深く感じます。', en: "Real place taste — deeply feel.", style: 'soft young man voice, warm warm appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '丁寧に、ようけ尽くして作ったわ。', en: "Carefully — much devoted made.", style: 'warm Kansai aunt voice, soft warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: '味、本当に、感心しますね。', en: "Taste — truly, impressed.", style: 'tender young man voice, soft warm admiring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お客さんに、喜んでもらいたい、いつも。', en: "Customer — want pleased, always.", style: 'soft Kansai aunt voice, warm warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '心、ようけ込もってますね。', en: "Heart — much contained.", style: 'soft young man voice, warm warm reverent delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、おおきに!', en: "Heh — thanks!", style: 'warm Kansai aunt voice, soft warm grateful delivery carefully' },
    ]),
  C('conv_02326',
    'Sakura observes the evening light from her window; reflective.',
    'Writer in quiet contemplation with friend.',
    'study_room_evening_lamp',
    ['明かり', '切ない', '夕日', '深く', '心', '静か', '美しい', '時間'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '蓮くん、夕方の明かり、美しいね。', en: "Ren — evening light, beautiful.", style: 'soft adult writer voice, warm warm reverent delivery carefully' },
      { speaker: 'ren_uni', jp: '切ない感じ、深く感じます。', en: "Wistful feel — deeply feel.", style: 'gentle young man voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '静かな時間、心、洗われる。', en: "Quiet time — heart, washed.", style: 'tender adult writer voice, soft warm content delivery carefully' },
      { speaker: 'ren_uni', jp: 'こういう瞬間、書き留めたいですね。', en: "Moment like this — want capture.", style: 'soft young man voice, warm warm inspired delivery carefully' },
      { speaker: 'sakura_teen', jp: '深く、感じたままを、書くの。', en: "Deeply — felt as-is, write.", style: 'gentle adult writer voice, soft warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '一緒に、創りませんか?', en: "Together — create?", style: 'tender young man voice, soft warm collaborative delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、是非。', en: "Yeah — by all means.", style: 'soft adult writer voice, warm warm affirming delivery carefully' },
    ]),
  C('conv_02327',
    'Hina-young joins a judo class; tells Riku about it.',
    'Two teens chatting about martial arts.',
    'classroom_after_quiet',
    ['柔道', '稽古', '心', '熱心', '尊重', '深く', '頑張る', '体'],
    ['hina_child', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'hina_child', jp: '陸くん、柔道、始めたんよ!', en: "Riku — judo, started!", style: 'bright teen girl voice, soft warm proud delivery carefully' },
      { speaker: 'riku_teen', jp: 'えっ、すごい!稽古、厳しい?', en: "Eh — wow! Training, strict?", style: 'animated teen boy voice, bright warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: '心、ようけ鍛えられる、深く。', en: "Heart — much trained, deeply.", style: 'soft teen girl voice, warm warm reflective delivery carefully' },
      { speaker: 'riku_teen', jp: '熱心に、頑張ってるな!', en: "Passionately — trying!", style: 'warm teen boy voice, soft warm admiring delivery carefully' },
      { speaker: 'hina_child', jp: '相手を尊重する、武道の心、好き。', en: "Opponent respect — martial heart, love.", style: 'tender teen girl voice, soft warm philosophical delivery carefully' },
      { speaker: 'riku_teen', jp: '体、強くなりそうやな!', en: "Body — strong become!", style: 'bright teen boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、頑張る!', en: "Yeah — try!", style: 'soft determined teen girl voice, warm earnest delivery carefully' },
    ]),
  C('conv_02328',
    'Tatsuya-country teaches Sho-young about brown rice farming.',
    'Elder farmer teaching child agriculture.',
    'porch_rice_low',
    ['玄米', '田んぼ', '農業', '丁寧', '本場', '実', '深く', '尊重'],
    ['tatsuya_country', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'tatsuya_country', jp: '翔、玄米、ようけ栄養あるで。', en: "Sho — brown rice, much nutrition.", style: 'slow Tohoku farmer voice, warm warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'おじいちゃん、田んぼで、できるの?', en: "Grandpa — paddy, can?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、丁寧に、農業、続けとる。', en: "Yeah — carefully, farming, continue.", style: 'gentle Tohoku voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '本場の味、すごいね!', en: "Real place taste — amazing!", style: 'awed child boy voice, bright warm admiring delivery carefully' },
      { speaker: 'tatsuya_country', jp: '実が、深く、育つんや。', en: "Grain — deeply, grows.", style: 'warm Tohoku farmer voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '農家、尊重したい!', en: "Farmer — want respect!", style: 'soft tender child boy voice, warm warm earnest delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ええ子や、ようけ覚えてな。', en: "Fine kid — much remember.", style: 'tender Tohoku voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02329',
    'Mei recommends a healthy meal to Yumiko.',
    'Younger woman sharing wellness tip with elder.',
    'kitchen_morning_warm',
    ['薦め', '玄米', '日ごろ', '健康', '丁寧', '深く', '心', '感謝'],
    ['mei_romantic', 'yumiko_mom'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'お母さん、玄米、薦めたいの。', en: "Mom — brown rice, want recommend.", style: 'soft young woman voice, warm warm caring delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、日ごろの食事、いいわね。', en: "Oh — daily meal, fine.", style: 'gentle older mother voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '健康、深く考えてみたの。', en: "Health — deeply thought.", style: 'tender young woman voice, soft warm earnest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '丁寧に、教えてくれて、ありがとう。', en: "Carefully — taught, thanks.", style: 'warm older mother voice, soft warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '心、こめて、料理したい。', en: "Heart — put, cook want.", style: 'soft young woman voice, warm warm committed delivery carefully' },
      { speaker: 'yumiko_mom', jp: '感謝、ようけよ、本当に。', en: "Gratitude — much, truly.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: 'これからも、一緒に、頑張ろうね。', en: "Going forward — together, try.", style: 'tender young mother voice, soft warm united delivery carefully' },
    ]),
  C('conv_02330',
    'Kenji and Aoi say goodbye to an old friend moving away.',
    'Couple in emotional farewell.',
    'station_platform_low',
    ['さよなら', '切ない', '深く', '心', '友人', '感謝', '寂しい', '結びつき'],
    ['kenji_office', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'けんちゃん、さよなら、切ないね。', en: "Ken-chan — goodbye, wistful.", style: 'soft tearful adult woman voice, warm warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、深く、寂しい気持ち、するわ。', en: "Yeah — deeply, lonely feeling, exists.", style: 'soft Kansai husband voice, warm warm raw delivery carefully' },
      { speaker: 'aoi_barista', jp: '長年の友人、ようけ感謝してる。', en: "Long-year friend — much grateful.", style: 'tender adult woman voice, soft warm reverent delivery carefully' },
      { speaker: 'kenji_office', jp: '結びつき、ずっと残るで、心に。', en: "Bond — always remains, heart.", style: 'gentle Kansai husband voice, soft warm philosophical delivery carefully' },
      { speaker: 'aoi_barista', jp: 'また、会えるよね、絶対。', en: "Again — can meet, definitely.", style: 'soft adult woman voice, warm warm hopeful delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、心、繋がっとるからな。', en: "Yeah — heart, connected.", style: 'tender Kansai husband voice, soft warm reassuring delivery carefully' },
      { speaker: 'aoi_barista', jp: '元気でね、本当に。', en: "Be well — truly.", style: 'tearful adult woman voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02331',
    'Sho-young describes a left-handed friend to Hiroshi-elder.',
    'Grandfather and child casual chat.',
    'porch_afternoon_quiet',
    ['左利き', '茶色', '機嫌', '優しい', '深く', '心', '楽しい', '友達'],
    ['hiroshi_elder', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おじいちゃん、友達、左利きなんよ!', en: "Grandpa — friend, left-handed!", style: 'bright child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほう、珍しいな、面白い。', en: "Oh — rare, interesting.", style: 'gentle elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '茶色の鉛筆、上手に使うの!', en: "Brown pencil — skillfully use!", style: 'animated child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '機嫌、良さそうな子やな。', en: "Mood — good-seeming kid.", style: 'soft elder Kansai voice, warm warm appreciative delivery carefully' },
      { speaker: 'sho_child', jp: '優しい子で、深く、仲良し!', en: "Kind kid — deeply, friends!", style: 'soft happy child boy voice, warm warm content delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええ友達、大切にな。', en: "Fine friend — cherish.", style: 'tender elder Kansai voice, soft warm wise delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、楽しい毎日!', en: "Yeah — fun daily!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
    ]),
  C('conv_02332',
    'Sakura researches a famous opera; discusses opening night with Ren.',
    'Two writers discussing arts event.',
    'cafe_afternoon_low',
    ['開演', 'コーラス', '深く', '感動', '本場', '尊重', '心', '熱心'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '蓮くん、オペラ、開演、もうすぐね。', en: "Ren — opera, opening, soon.", style: 'soft adult writer voice, warm warm anticipating delivery carefully' },
      { speaker: 'ren_uni', jp: 'コーラス、本場で見られて、嬉しいです。', en: "Chorus — real place see, happy.", style: 'gentle young man voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '深く、感動するでしょうね。', en: "Deeply — moved probably.", style: 'tender adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'ren_uni', jp: '歌い手の心、尊重したいですね。', en: "Singer heart — want respect.", style: 'soft young man voice, warm warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '熱心な舞台、ようけ感じる。', en: "Passionate stage — much feel.", style: 'gentle adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'ren_uni', jp: '記事に、心こめて書きたい。', en: "Article — heart put want write.", style: 'tender young man voice, soft warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '一緒に、行きましょう!', en: "Together — go!", style: 'soft adult writer voice, warm warm cheerful delivery carefully' },
    ]),
  C('conv_02333',
    'Daichi and Sho-young watch a judo match on TV.',
    'Father and son sharing sport viewing.',
    'living_room_tv_low',
    ['柔道', '勝負', '応援', '心', '尊重', '熱心', '深く', '頑張る'],
    ['daichi_kansai', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'お父さん、柔道、すごい技!', en: "Dad — judo, amazing move!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、心、ようけ強いな、選手!', en: "Yeah — heart, much strong, player!", style: 'animated Kansai father voice, bright warm admiring delivery carefully' },
      { speaker: 'sho_child', jp: '勝負、深く、緊張する!', en: "Match — deeply, nervous!", style: 'soft excited child boy voice, warm warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '相手、尊重する、ええ武道や。', en: "Opponent — respect, fine martial.", style: 'warm Kansai father voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '熱心に、応援しよう!', en: "Passionately — cheer!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '皆、頑張れー!', en: "All — go!", style: 'animated Kansai father voice, bright warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、勝った!', en: "Yay — won!", style: 'thrilled child boy voice, bright warm delight delivered carefully' },
    ]),
  C('conv_02334',
    'Yumiko recommends a bus route to Hina-young for a trip.',
    'Grandmother helping teen with travel.',
    'living_room_lamp_quiet',
    ['バス停', '乗り物', '直ぐに', '気軽', '丁寧', '安心', '案内', '心'],
    ['yumiko_mom', 'hina_child'], 'Medium (7-12)',
    [
      { speaker: 'yumiko_mom', jp: 'ひな、バス停、近くにあるわよ。', en: "Hina — bus stop, nearby.", style: 'gentle older mother voice, soft warm helpful delivery carefully' },
      { speaker: 'hina_child', jp: '乗り物、初めて一人で乗るの。', en: "Vehicle — first alone ride.", style: 'soft nervous teen girl voice, warm warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '直ぐに、慣れるから、安心して。', en: "Soon — accustom, relax.", style: 'tender older mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'hina_child', jp: '気軽に、行けるかな?', en: "Casually — can go?", style: 'soft teen girl voice, warm warm hopeful delivery carefully' },
      { speaker: 'yumiko_mom', jp: '丁寧に、案内、書いておくね。', en: "Carefully — guide, write.", style: 'warm older mother voice, soft warm caring delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、心強い!', en: "Thanks — encouraging!", style: 'bright teen girl voice, soft warm grateful delivery carefully' },
      { speaker: 'yumiko_mom', jp: '気をつけて、行ってらっしゃい。', en: "Be careful — go.", style: 'tender older mother voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02335',
    'Kenji and Daichi go to a sale; discuss prices.',
    'Two friends shopping casually.',
    'shop_busy_low',
    ['値下げ', '断然', '気軽', '直ぐに', '深く', '感心', '丁寧', '良い'],
    ['kenji_office', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: 'ダイチ、これ、値下げしとるで!', en: "Daichi — this, price-cut!", style: 'animated Kansai man voice, bright warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、断然、お得やな!', en: "Yeah — by far, good deal!", style: 'warm Kansai husband voice, soft warm delighted delivery carefully' },
      { speaker: 'kenji_office', jp: '気軽に、買えるな、これなら。', en: "Casually — can buy, this.", style: 'soft Kansai man voice, warm warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: '直ぐに、決めよか!', en: "Soon — decide!", style: 'cheerful Kansai husband voice, bright warm decisive delivery carefully' },
      { speaker: 'kenji_office', jp: '深く、考えんでも、ええ品や。', en: "Deeply — without thinking, fine item.", style: 'gentle Kansai man voice, soft warm appreciative delivery carefully' },
      { speaker: 'daichi_kansai', jp: '丁寧に作ってある、感心するわ。', en: "Carefully made — impressed.", style: 'warm Kansai husband voice, soft warm admiring delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ買い物や!', en: "Fine shopping!", style: 'animated Kansai man voice, bright warm cheerful delivery carefully' },
    ]),
  C('conv_02336',
    'Mei comforts Hina-young who feels wistful about leaving home for college.',
    'Mother consoling teen about transition.',
    'bedroom_evening_lamp',
    ['切ない', '深く', '心', '寂しい', '応援', '感謝', '結びつき', '優しい'],
    ['mei_romantic', 'hina_child'], 'Long (13-20)',
    [
      { speaker: 'hina_child', jp: 'メイさん、家、離れるの、切ない。', en: "Mei — home, leave, wistful.", style: 'soft tearful teen girl voice, warm warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '深く、わかるよ、その気持ち。', en: "Deeply — understand, feeling.", style: 'tender young mother voice, soft warm empathetic delivery carefully' },
      { speaker: 'hina_child', jp: '皆と、離れるの、寂しい。', en: "All — separate, lonely.", style: 'soft teen girl voice, warm warm vulnerable delivery carefully' },
      { speaker: 'mei_romantic', jp: '結びつき、ずっと、残るからね。', en: "Bond — always, remains.", style: 'warm young mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'hina_child', jp: '本当に?', en: "Really?", style: 'soft teen girl voice, warm warm hopeful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、心、繋がってる、いつも。', en: "Yeah — heart, connected, always.", style: 'tender young mother voice, soft warm steadfast delivery carefully' },
      { speaker: 'hina_child', jp: '応援、ようけ、感じる。', en: "Cheer — much, feel.", style: 'soft tender teen girl voice, warm warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '優しい気持ち、忘れないでね。', en: "Kind feeling — don't forget.", style: 'tender young mother voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: '感謝、いっぱい、本当に。', en: "Gratitude — full, truly.", style: 'tearful teen girl voice, soft warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'いつでも、帰っておいで。', en: "Anytime — come home.", style: 'warm young mother voice, soft warm enduring delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、頑張ってくる!', en: "Yeah — try!", style: 'soft determined teen girl voice, warm earnest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ずっと、応援してる。', en: "Always — cheering.", style: 'tender young mother voice, soft warm steadfast delivery carefully' },
    ]),
  C('conv_02337',
    'Ren visits a cram school; discusses study with Sakura.',
    'Young man researching education.',
    'cafe_afternoon_low',
    ['予備校', '学習', '熱心', '深く', '頑張る', '心構え', '尊重', '丁寧'],
    ['ren_uni', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'さくらさん、予備校、見学してきました。', en: "Sakura — cram school, visited.", style: 'soft young man voice, warm warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、どんな様子だった?', en: "Oh — what scene?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'ren_uni', jp: '熱心な学習、皆さん、深く取り組んでた。', en: "Passionate study — all, deeply engaged.", style: 'composed young man voice, soft warm impressed delivery carefully' },
      { speaker: 'sakura_teen', jp: '頑張る心構え、立派ね。', en: "Trying mindset — splendid.", style: 'tender adult writer voice, soft warm admiring delivery carefully' },
      { speaker: 'ren_uni', jp: '尊重したい、皆さんの努力。', en: "Want respect — all effort.", style: 'soft young man voice, warm warm reverent delivery carefully' },
      { speaker: 'sakura_teen', jp: '記事、丁寧に書いてね。', en: "Article — carefully write.", style: 'warm adult writer voice, soft warm encouraging delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、心こめて!', en: "Yes — heart put!", style: 'humble young man voice, soft warm committed delivery carefully' },
    ]),
  C('conv_02338',
    'Naoko reflects on her shop and warmly thanks Aoi for help.',
    'Aunt expressing gratitude to younger.',
    'ramen_shop_after_close',
    ['結びつき', '感謝', '深く', '心', '尽くし', '長年', '応援', '愛情'],
    ['naoko_aunt', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'naoko_aunt', jp: '蒼ちゃん、ようけ尽くしてくれて、感謝や。', en: "Aoi-chan — much devoted, gratitude.", style: 'tender Kansai aunt voice, soft warm grateful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'おばさん、こちらこそ。', en: "Auntie — likewise.", style: 'soft adult woman voice, warm warm humble delivery carefully' },
      { speaker: 'naoko_aunt', jp: '長年の結びつき、深く感じるわ。', en: "Long-year bond — deeply feel.", style: 'warm Kansai aunt voice, soft warm philosophical delivery carefully' },
      { speaker: 'aoi_barista', jp: '心、温かい関わり、ありがたい。', en: "Heart — warm bond, grateful.", style: 'tender adult woman voice, soft warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お前の応援、ようけ励みになる。', en: "Your cheer — much encouragement.", style: 'soft Kansai aunt voice, warm warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '愛情、ようけ感じてます、いつも。', en: "Love — much feel, always.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'これからも、よろしくな!', en: "Going forward — please!", style: 'warm Kansai aunt voice, soft warm cheerful delivery carefully' },
    ]),
  C('conv_02339',
    'Hiroshi-elder tells Sho-young a moral fable.',
    'Grandfather teaching life lesson through story.',
    'tatami_lamp_evening',
    ['昔話', '心', '深く', '尊重', '優しい', '寛容', '伝統', '感謝'],
    ['hiroshi_elder', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_elder', jp: '翔、昔話、聞かせたるな。', en: "Sho — folk tale, tell.", style: 'slow elder Kansai voice, warm warm storytelling delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、聞きたい!', en: "Yeah — want hear!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '優しい心、深く持つこと、大事や。', en: "Kind heart — deeply hold, matters.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '寛容な心、ってこと?', en: "Generous heart — meaning?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、人を尊重する、伝統の教えや。', en: "Yeah — person respect, traditional teaching.", style: 'tender elder Kansai voice, soft warm wise delivery carefully' },
      { speaker: 'sho_child', jp: '感謝の気持ち、大事やね!', en: "Gratitude — matters!", style: 'soft tender child boy voice, warm warm understanding delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええ子や、ようけ覚えとき。', en: "Fine kid — much remember.", style: 'warm elder Kansai voice, soft warm fond delivery carefully' },
    ]),
  C('conv_02340',
    'Whole group gathers for a midsummer evening; many warm voices.',
    'Multi-voice summer family gathering.',
    'porch_summer_night',
    ['夏', '夜空', '明かり', '心', '深く', '感謝', '皆', '幸せ'],
    ['hiroshi_elder', 'naoko_aunt', 'mei_romantic', 'daichi_kansai', 'sho_child', 'hina_child'], 'Long (13-20)',
    [
      { speaker: 'hiroshi_elder', jp: '夏の夜、皆おって、ええなぁ。', en: "Summer night — all here, fine.", style: 'slow elder Kansai voice, warm warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: '夜空、明かり、ようけ綺麗や!', en: "Night sky — lights, much pretty!", style: 'brassy Kansai aunt voice, bright warm delighted delivery carefully' },
      { speaker: 'mei_romantic', jp: '深く、心、温まる時間。', en: "Deeply — heart, warming time.", style: 'tender young mother voice, soft warm reverent delivery carefully' },
      { speaker: 'daichi_kansai', jp: '皆と、こうやって、過ごせて感謝や。', en: "All — like this, spend grateful.", style: 'warm Kansai husband voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '花火、まだかな?', en: "Fireworks — yet?", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'こんな夜、幸せ、本当に。', en: "Night like this — happy, truly.", style: 'tender teen girl voice, soft warm content delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '長く、皆で、こうしような。', en: "Long — all, like this.", style: 'gentle elder Kansai voice, soft warm enduring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お弁当、ようけ作ったで!', en: "Bento — much made!", style: 'animated Kansai aunt voice, bright warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: '家族、本当に、宝物。', en: "Family — truly, treasure.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええ夏や、ほんま。', en: "Fine summer — truly.", style: 'warm Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'sho_child', jp: '皆、大好き!', en: "All — love!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'ずっと、こうやって、続けたい。', en: "Always — like this, want continue.", style: 'soft tender teen girl voice, warm warm wishful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '感謝、ようけや、本当に。', en: "Gratitude — much, truly.", style: 'tender elder Kansai voice, soft warm humble delivery carefully' },
    ]),
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_117 wrote', CONVERSATIONS.length, 'files');
