// scripts/batches/batch_002.mjs
//
// Second in-conversation batch: 20 conversations (conv_00024 .. conv_00043).
// Rotates the roster — heavy on hiroshi_elder (was unused in batch 1) and
// other under-used characters; lighter on yuki/kenji/ren.
//
// Run: node scripts/batches/batch_002.mjs

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
fs.mkdirSync(OUT_DIR, { recursive: true });

const NOW = new Date().toISOString();

const CONVERSATIONS = [
  {
    id: 'conv_00024',
    context: 'A quiet community library on a Wednesday afternoon. The retired professor reads a picture book aloud to a small circle of children; one of them keeps interrupting with sincere questions.',
    purpose: 'gentle instructional warmth — building curiosity in a child',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','読む','何','面白い','どう','時間'],
    cast: ['hiroshi_elder','hina_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hiroshi_elder', jp: 'では、続きを読みますよ。', en: 'Alright — I\'ll read on now.', style: 'Low, weathered, warm. The careful pace of someone who has read aloud thousands of times. A small smile in the voice.', mood: 'settled_warm' },
      { speaker: 'hina_child', jp: '先生、その鳥、本当に話せるの？', en: 'Sensei — that bird, can it really talk?', style: 'Bright eight-year-old interruption. Voice lifts on the question. Genuine — not testing him, asking.', mood: 'curious' },
      { speaker: 'hiroshi_elder', jp: 'お話の中ではね。本当のことかは、君が決めていい。', en: 'Inside the story, yes. Whether it\'s really true — you get to decide that.', style: 'Slow, considered. He gives the question the weight of an adult one. Eye-contact level voice.', mood: 'gentle_teaching' },
      { speaker: 'hina_child', jp: 'そっか…じゃあ、話せることにする！', en: 'Oh…then I\'ll decide it can talk!', style: 'A small breath of revelation. Decisive in a way only an eight-year-old can be.', mood: 'decisive_kid' },
      { speaker: 'hiroshi_elder', jp: 'いい判断ですね。続きが楽しみになる。', en: 'A fine decision. Makes the rest of the story more fun.', style: 'Quiet approval. Treats her decision as a real one.', mood: 'approving' },
      { speaker: 'hina_child', jp: 'うん！その次、どうなるの？', en: 'Yeah! What happens next?', style: 'Leans forward in the voice. Already bouncing.', mood: 'eager' },
      { speaker: 'hiroshi_elder', jp: 'それは、読んでからのお楽しみ。', en: 'That — is the fun of reading on.', style: 'A small chuckle hidden in the line. The deliberate withholding of a storyteller.', mood: 'amused_withholding' },
      { speaker: 'hina_child', jp: '早く読んで、おじいちゃん先生！', en: 'Hurry up and read, Grandpa-sensei!', style: 'Affectionate demand. The improvised honorific lands like a compliment. Voice almost laughing.', mood: 'affectionate_demanding' },
    ],
  },
  {
    id: 'conv_00025',
    context: 'Sakura\'s teen bedroom in Osaka. Naoko has barged in unannounced with too much food and unsolicited observations.',
    purpose: 'aunt-niece teasing — affectionate Kansai needling, with a real worry underneath',
    ambient: 'apartment_indoor',
    target_vocab: ['今','本当に','元気','時間','言う','ない','大丈夫'],
    cast: ['naoko_aunt','sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'naoko_aunt', jp: 'さくらー、勉強してる？', en: 'Sakuraaa — you studying?', style: 'Bursts in mid-sentence as if the doorway were a stage. Loud, broad Kansai cadence. Already knows the answer.', mood: 'invasive_warm' },
      { speaker: 'sakura_teen', jp: 'おばちゃん、ノックして…', en: 'Oba-chan — knock first…', style: 'Slumps further into the chair. Half-protest, half-resignation. She is in fact not studying.', mood: 'resigned' },
      { speaker: 'naoko_aunt', jp: 'ええやんか、家族やんか。これ食べな。', en: 'C\'mon, we\'re family. Eat this.', style: 'Already shoving a container at her. The 「家族やんか」 is the all-purpose Kansai justification.', mood: 'shoving_food' },
      { speaker: 'sakura_teen', jp: 'もう食べた、本当に。', en: 'Already ate, really.', style: 'Flat. The 「本当に」 carries no conviction.', mood: 'flat_lie' },
      { speaker: 'naoko_aunt', jp: 'うそや。最近、また痩せたやろ？', en: 'Liar. Lost more weight again, didn\'t you?', style: 'Eyes narrow in the voice. Half-tease, half-real. The diagnostic Kansai aunt.', mood: 'diagnosing' },
      { speaker: 'sakura_teen', jp: '痩せてへんし。', en: 'Have not.', style: 'Reflexive teen-deflect. Looks away from her aunt entirely.', mood: 'deflecting' },
      { speaker: 'naoko_aunt', jp: 'ほんでな、お母さん心配しとったで、最近。', en: 'And — your mom\'s been worried lately.', style: 'Voice drops half a register. The actual reason she came over. Kansai softening.', mood: 'pivot_real' },
      { speaker: 'sakura_teen', jp: '…なんで？別に大丈夫やのに。', en: '…Why? I\'m fine, really.', style: 'A small note of being caught. The 「やのに」 ending is half-honest, half-defensive.', mood: 'caught_defensive' },
      { speaker: 'naoko_aunt', jp: '本当に大丈夫やったら、言うてみ。', en: 'If you\'re really fine, say it once more — for me.', style: 'Quiet, even. Not sharp. Holding the door open.', mood: 'door_open' },
      { speaker: 'sakura_teen', jp: '…またな。今ちょっと無理。', en: '…Another time. Not right now.', style: 'Smallest voice in the scene. Honest. Not a brush-off — a real ask for time.', mood: 'honest_small' },
    ],
  },
  {
    id: 'conv_00026',
    context: 'A neighborhood park bench, after school. Hina has half a bag of cookies; Sho is sitting at the other end of the bench.',
    purpose: 'childhood barter — phatic micro-friendship in six lines',
    ambient: 'park_afternoon',
    target_vocab: ['好き','おいしい','ありがとう','もう','少し'],
    cast: ['sho_child','hina_child'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hina_child', jp: 'お菓子、半分こしよ。', en: 'Let\'s split the snacks.', style: 'Bright, no-preamble. Slides over half a bag without waiting for an answer.', mood: 'generous_kid' },
      { speaker: 'sho_child', jp: 'うん…おねえちゃん、これ好き？', en: 'Yeah… Onee-chan, do you like this kind?', style: 'Quiet, careful. The 「おねえちゃん」 is the polite-younger default — she\'s a year older. Voice low.', mood: 'shy_offering' },
      { speaker: 'hina_child', jp: '好き！おいしい！', en: 'Yes! Tasty!', style: 'Full-volume eight-year-old enthusiasm. Mouth already half full.', mood: 'bright' },
      { speaker: 'sho_child', jp: 'もう少しある。', en: 'There\'s a little more.', style: 'Holds out a second cookie shyly. The 「もう少し」 is a quiet generosity.', mood: 'shy_giving' },
      { speaker: 'hina_child', jp: 'ありがとう！しょうくん、優しい。', en: 'Thank you! Sho-kun, you\'re kind.', style: 'Direct compliment without ceremony. Eats the cookie immediately.', mood: 'direct_praise' },
      { speaker: 'sho_child', jp: '…うん。', en: '…Mm.', style: 'One-syllable acknowledgment. Pleased but doesn\'t know what to do with it. Looks down.', mood: 'pleased_shy' },
    ],
  },
  {
    id: 'conv_00027',
    context: 'A Sunday afternoon phone call. Asuka in Tokyo dials her father at his quiet Iwate farm. He picks up on the third ring, as always.',
    purpose: 'adult-daughter check-in — quiet care across distance',
    ambient: 'phone_call_silent',
    target_vocab: ['今日','本当に','元気','時間','大丈夫','ない','寒い'],
    cast: ['tatsuya_country','asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'tatsuya_country', jp: 'もしもし。', en: 'Hello.', style: 'Slow, weathered, two syllables. The voice of a man who answers a landline.', mood: 'unhurried' },
      { speaker: 'asuka_teacher', jp: 'お父さん、こんにちは。元気？', en: 'Hi Dad — how are you?', style: 'Light, warm, slightly more formal than the words. Already smiling.', mood: 'warm_calling' },
      { speaker: 'tatsuya_country', jp: 'ああ…まあ、変わらず。', en: 'Ah… same as always.', style: 'Two beats between the syllables. Tohoku softening. Doesn\'t volunteer more.', mood: 'reticent' },
      { speaker: 'asuka_teacher', jp: '今日、そっち寒い？', en: 'Cold up there today?', style: 'Easy default question. The conversation is the point, not the information.', mood: 'maintenance' },
      { speaker: 'tatsuya_country', jp: '寒いな。今朝、雪。', en: 'It is. Snow this morning.', style: 'Two clauses, period of silence between. Each one self-sufficient.', mood: 'reporting_calm' },
      { speaker: 'asuka_teacher', jp: 'もう？早いね。', en: 'Already? That\'s early.', style: 'Genuine small surprise. The kind of comment that keeps a call going.', mood: 'gentle_surprise' },
      { speaker: 'tatsuya_country', jp: 'うん。…そっちは。', en: 'Mm. …And you.', style: 'Returns the question with a slight pause. The most affection he uses in a sentence.', mood: 'gentle_return' },
      { speaker: 'asuka_teacher', jp: '私は大丈夫。仕事も、まあまあ。', en: 'I\'m okay. Work\'s alright too.', style: 'Sits down on the bed in the voice. Truth, with the rough edges softened for him.', mood: 'reassuring_filtered' },
      { speaker: 'tatsuya_country', jp: '無理してないか。', en: 'You\'re not overdoing it?', style: 'The whole call is in this line. Three words, slow.', mood: 'father_worry' },
      { speaker: 'asuka_teacher', jp: 'うん、無理してない。本当に。', en: 'No, I\'m not overdoing it. Really.', style: 'A real answer, gently insisted. The 「本当に」 lands genuine.', mood: 'genuine_reassurance' },
      { speaker: 'tatsuya_country', jp: '…そうか。それなら。', en: '…Alright then. If that\'s so.', style: 'Slowest line in the call. The closing of a small worry.', mood: 'settling' },
    ],
  },
  {
    id: 'conv_00028',
    context: 'Saturday morning, a friend\'s kitchen. Riku slept over and is sitting alone at the counter at 7 a.m. His friend\'s dad — Ryosuke — comes in, sees him, and pours coffee for both of them.',
    purpose: 'incidental confessional — adult listens without solving, just makes coffee',
    ambient: 'apartment_indoor',
    target_vocab: ['今','何','ない','言う','時間','大丈夫','本当に'],
    cast: ['ryosuke_dad','riku_teen'],
    frequency_tier: 1,
    length_tier: 'Long (13-20)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'ryosuke_dad', jp: 'お、おはよう。早いな。', en: 'Oh — morning. You\'re up early.', style: 'Warm, unsurprised. The voice of someone who has lived with kids long enough not to read into things.', mood: 'easy_warm' },
      { speaker: 'riku_teen', jp: '…おはようございます。', en: '…Morning.', style: 'Mumbled, fully polite. Surprised to be greeted; doesn\'t look up.', mood: 'mumbled' },
      { speaker: 'ryosuke_dad', jp: 'コーヒー飲む？砂糖いる？', en: 'Want coffee? Sugar?', style: 'Already pouring. Two questions, no pressure on either one.', mood: 'serving' },
      { speaker: 'riku_teen', jp: '…ブラックでいいです。', en: '…Black is fine.', style: 'Small, half-defensive. Wants to seem older than he is.', mood: 'performing_older' },
      { speaker: 'ryosuke_dad', jp: '大人ぶってるな。', en: 'Acting grown-up, huh.', style: 'Said with a smile in the voice, not a barb. Slides the mug over.', mood: 'gentle_tease' },
      { speaker: 'riku_teen', jp: '(half-laugh)', en: '(small laugh)', style: 'A real laugh, surprising himself. A beat of unguarded.', mood: 'unguarded_beat' },
      { speaker: 'ryosuke_dad', jp: '最近、調子はどう？', en: 'How\'ve you been lately?', style: 'Easy and open. The question of someone who genuinely wants the answer but won\'t mind if he doesn\'t get one.', mood: 'open_question' },
      { speaker: 'riku_teen', jp: 'まあ…ふつう。', en: 'Yeah… normal.', style: 'Reflexive teen-armour. Looks at the coffee.', mood: 'armour' },
      { speaker: 'ryosuke_dad', jp: 'ふつうって、本当のふつう？', en: 'Normal — like, really normal?', style: 'No edge. A small follow-up someone could brush off if they wanted.', mood: 'gentle_probe' },
      { speaker: 'riku_teen', jp: '…別に、なんもないけど。', en: '…I mean, nothing really.', style: 'Quieter than the last line. A door inches open.', mood: 'inching_open' },
      { speaker: 'ryosuke_dad', jp: 'うん。なんもなくても、話したかったら話していいよ。', en: 'Mm. Even if there\'s nothing — you can talk if you want.', style: 'Slow, plain. The whole sentence delivered as a small chair pulled out for him.', mood: 'door_offered' },
      { speaker: 'riku_teen', jp: '…ありがとうございます。', en: '…Thank you.', style: 'Smaller than the other lines. The full keigo from a 15-year-old to an adult who has noticed.', mood: 'small_thanks' },
      { speaker: 'ryosuke_dad', jp: 'いいよ。コーヒー、ゆっくり。', en: 'No worries. Take your coffee slow.', style: 'Closing line. Turns to the stove. Quietly leaving the door open.', mood: 'closing_open' },
    ],
  },
  {
    id: 'conv_00029',
    context: 'A quiet Tokyo side-street at 2 a.m. Officer Takeda has stopped to check on a young woman sitting on the curb. She isn\'t drunk, isn\'t hurt — just had one of those nights.',
    purpose: 'professional kindness — late-night police care without paperwork energy',
    ambient: 'city_street_night',
    target_vocab: ['大丈夫','今','家','一人','帰る','本当に','ありがとう'],
    cast: ['takeda_officer','aoi_barista'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'takeda_officer', jp: 'こんばんは。大丈夫ですか？', en: 'Evening. You alright?', style: 'Calm, professional, kind. Stops two metres away — doesn\'t loom.', mood: 'professional_kind' },
      { speaker: 'aoi_barista', jp: 'あ、はい…すみません。', en: 'Oh — yes… sorry.', style: 'Startled out of a long thought. Reflexive politeness; not actually sorry.', mood: 'startled_polite' },
      { speaker: 'takeda_officer', jp: 'ご家族は近くに？', en: 'Family nearby?', style: 'Easy, neutral. The kind of question that\'s really asking a different one.', mood: 'gentle_probe' },
      { speaker: 'aoi_barista', jp: 'いえ、一人で住んでて。', en: 'No — I live alone.', style: 'Honest, soft. The 「一人で」 carries a small weight she doesn\'t hide.', mood: 'honest_soft' },
      { speaker: 'takeda_officer', jp: 'お家まで、お一人で帰れますか？', en: 'Can you make it home okay on your own?', style: 'Slight emphasis on 「お一人で」. The keigo is doing real work — keeping the encounter safe.', mood: 'careful_polite' },
      { speaker: 'aoi_barista', jp: '帰れます…たぶん。', en: 'I can… probably.', style: 'A small wobble inside the certainty. Half-laughs at her own honesty.', mood: 'wobbling_honest' },
      { speaker: 'takeda_officer', jp: 'タクシーお呼びしますね。', en: 'I\'ll call you a taxi, then.', style: 'No question, just an offer in indicative form. Already pulling out the radio in the voice.', mood: 'taking_action' },
      { speaker: 'aoi_barista', jp: '本当に、ありがとうございます…。', en: 'Really — thank you so much…', style: 'Voice catches half a step. The whole night gathered into this one thank-you.', mood: 'gathered_thanks' },
      { speaker: 'takeda_officer', jp: 'お気をつけて。気にしないでください。', en: 'Take care. Don\'t mind it.', style: 'Closing, professional, warm. Walks her toward the taxi in the voice.', mood: 'closing_warm' },
    ],
  },
  {
    id: 'conv_00030',
    context: 'A community centre in Kobe. Sachiko (Tokyo, visiting her sister-in-law for the week) finds herself at the local elder coffee morning, sitting next to Yoshie Mori, who already runs the room.',
    purpose: 'gossip + relationship maintenance — two elders comparing notes across regions',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','元気','今','家族','一人','時間','大変','嬉しい'],
    cast: ['sachiko_grandma','mrs_mori_neighbor'],
    frequency_tier: 1,
    length_tier: 'Long (13-20)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'あら、東京の方やね？', en: 'Oh — Tokyo, are you?', style: 'Loud, immediate, no warm-up. Kansai claim-of-jurisdiction in the form of a question.', mood: 'claiming' },
      { speaker: 'sachiko_grandma', jp: 'はい、はじめまして…さちこと申します。', en: 'Yes — pleased to meet you. I\'m Sachiko.', style: 'Soft, formal, the wobble of older Tokyo speech. Slight bow inside the voice.', mood: 'formal_soft' },
      { speaker: 'mrs_mori_neighbor', jp: 'よしえや。座って座って。お茶飲み。', en: 'Yoshie. Sit, sit. Have tea.', style: 'Three commands disguised as hospitality. Pulls out the chair for her.', mood: 'commanding_warm' },
      { speaker: 'sachiko_grandma', jp: 'ありがとうございます。', en: 'Thank you so much.', style: 'Bows again in the voice. Touched and slightly steamrolled, in a nice way.', mood: 'touched_polite' },
      { speaker: 'mrs_mori_neighbor', jp: 'ご家族で来とるんか？', en: 'Family come with you?', style: 'No preamble. Mid-pour. The intel-gathering begins.', mood: 'casual_probing' },
      { speaker: 'sachiko_grandma', jp: 'いえ、義妹のところに、一人で。', en: 'No — to my sister-in-law\'s, on my own.', style: 'Quiet, dignified. The 「一人で」 carries a small but honest weight.', mood: 'dignified_quiet' },
      { speaker: 'mrs_mori_neighbor', jp: '一人で偉いなあ。元気やん。', en: 'On your own — impressive. You\'ve got it.', style: 'Genuine. Slight upward lift on 「元気やん」. A compliment with no calculation.', mood: 'genuine_praise' },
      { speaker: 'sachiko_grandma', jp: 'あ、ありがとうございます…年取ったら、移動は大変で。', en: 'Oh — thank you… once you get older, travel\'s hard.', style: 'A small, real laugh at the end. Drops a half-step of formality.', mood: 'opening_up' },
      { speaker: 'mrs_mori_neighbor', jp: 'ほんまほんま。膝な、もう。', en: 'Truly truly. The knees — done.', style: 'Taps her own knee in the voice. The instant recognition of two old bodies.', mood: 'recognising' },
      { speaker: 'sachiko_grandma', jp: 'あ、私もです。階段がね…', en: 'Oh, mine too. The stairs, you know…', style: 'Trails into a small commiserating laugh. Door fully open now.', mood: 'commiserating' },
      { speaker: 'mrs_mori_neighbor', jp: 'やろ？でもな、家にこもっとっても、ろくなことないわ。', en: 'Right? But staying shut in the house — nothing good in that.', style: 'A philosophy delivered as gossip. Kansai briskness.', mood: 'philosophical_brisk' },
      { speaker: 'sachiko_grandma', jp: '本当に、その通りで。', en: 'Truly — exactly so.', style: 'Soft genuine agreement. The 「本当に」 unforced.', mood: 'soft_agreement' },
      { speaker: 'mrs_mori_neighbor', jp: '今度、また来た時、寄り。お茶あるで、いつでも。', en: 'Next time you\'re here — drop by. Tea, anytime.', style: 'An invitation that doubles as a small claim. Generous.', mood: 'inviting_warm' },
      { speaker: 'sachiko_grandma', jp: 'ありがとうございます。本当に、嬉しいです。', en: 'Thank you. Really — I\'m glad.', style: 'The 「嬉しい」 cracks the formal register; sincere. A bow inside the voice on the closing word.', mood: 'genuinely_glad' },
    ],
  },
  {
    id: 'conv_00031',
    context: 'A small wine bar after work. Yumiko and Yuki — colleagues at the same firm — discovered recently they\'re both mothers of young kids (Yuki isn\'t one yet, but caught up in the conversation anyway). First time meeting outside the office.',
    purpose: 'colleague friendship gelling — small revelation about shared territory',
    ambient: 'bar_evening',
    target_vocab: ['本当に','大変','時間','今日','大丈夫','一緒','子供'],
    cast: ['yumiko_mom','yuki_office'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'yumiko_mom', jp: '初めての二人飲みやね。', en: 'First time drinking, just us, isn\'t it.', style: 'Warm, easy. The kind of opener that does the work of making it not-awkward.', mood: 'warm_opener' },
      { speaker: 'yuki_office', jp: 'ですね。ちょっと緊張してます。', en: 'It is. I\'m a little nervous.', style: 'Half-laughs at her own honesty. Voice slightly higher than usual.', mood: 'honest_nervous' },
      { speaker: 'yumiko_mom', jp: 'えっ、なんで？', en: 'What — why?', style: 'Amused, leaning in. Already enjoying her.', mood: 'amused' },
      { speaker: 'yuki_office', jp: '先輩なので、いつもオフィスで…', en: 'You\'re my senior — at the office it\'s always…', style: 'Trails. Doesn\'t finish the sentence; both of them know what it means.', mood: 'trailing_polite' },
      { speaker: 'yumiko_mom', jp: '今日は普通に。私もただの飲み仲間。', en: 'Today, just regular. I\'m just a drinking buddy too.', style: 'Sets her glass down on the line. The 「ただの」 carries real intent.', mood: 'levelling' },
      { speaker: 'yuki_office', jp: 'はい。…じゃあ、お子さん、二人でしたよね。', en: 'Right. …Two kids, wasn\'t it?', style: 'A half-beat shift toward real conversation. Memory shown — she\'s been paying attention.', mood: 'careful_pivot' },
      { speaker: 'yumiko_mom', jp: 'うん、十歳と五歳。今日、夫が見てくれてる。', en: 'Mm — ten and five. Husband\'s got them tonight.', style: 'Comfortable. The 「見てくれてる」 carries grateful matter-of-factness.', mood: 'comfortable_sharing' },
      { speaker: 'yuki_office', jp: 'いいですね、そういうの、本当に大事。', en: 'That\'s nice. That kind of thing really matters.', style: 'Sincere. Not performing — she actually thinks so.', mood: 'sincere_admiration' },
      { speaker: 'yumiko_mom', jp: 'ゆきちゃんは、子供は？', en: 'And you, Yuki-chan — kids?', style: 'Drops to the diminutive. Gentle, open.', mood: 'gentle_open' },
      { speaker: 'yuki_office', jp: 'いえ、まだ。…でも、大変そうですね、本当に。', en: 'No — not yet. …But it sounds hard, really.', style: 'Quieter. A real comment, not pity. The 「本当に」 lands honest.', mood: 'honest_quiet' },
    ],
  },
  {
    id: 'conv_00032',
    context: 'A pediatric exam room. Ryosuke\'s son has a fever; Dr. Saito has just finished the exam. Ryosuke is gripping the edge of the chair.',
    purpose: 'medical reassurance — calm authority delivered to a worried parent',
    ambient: 'clinic_waiting_room',
    target_vocab: ['大丈夫','本当に','今','少し','時間','心配','元気'],
    cast: ['saito_doctor','ryosuke_dad'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'saito_doctor', jp: 'お父さん、結果出ました。', en: 'Dad — results are in.', style: 'Sits down before speaking. Even, steady, deliberate.', mood: 'composed' },
      { speaker: 'ryosuke_dad', jp: 'はい、お願いします…。', en: 'Yes — please…', style: 'A breath caught and not quite released. Hands tight in the voice.', mood: 'tense' },
      { speaker: 'saito_doctor', jp: 'ただの風邪ですね。心配いらないです。', en: 'It\'s just a cold. Nothing to worry about.', style: 'Slight emphasis on 「ただの」. Lets the relief land before continuing.', mood: 'delivering_relief' },
      { speaker: 'ryosuke_dad', jp: 'あ…本当に？', en: 'Oh… really?', style: 'A breath finally released. Voice cracks half a step on 「本当に」.', mood: 'releasing' },
      { speaker: 'saito_doctor', jp: '本当に。三日ほど、家でゆっくり。', en: 'Really. Three days at home, take it easy.', style: 'Doubles down warmly. The clinical-warm tone of someone who has delivered this exact news many times.', mood: 'clinical_warm' },
      { speaker: 'ryosuke_dad', jp: 'よかった…ありがとうございます。', en: 'Thank god… thank you.', style: 'Whole shoulders drop in the voice. Genuine, almost embarrassed by his own worry.', mood: 'embarrassed_grateful' },
      { speaker: 'saito_doctor', jp: 'お薬、少しだけ出します。今日と明日、お熱見てあげて。', en: 'I\'ll prescribe a little something. Check his temperature today and tomorrow.', style: 'Back to logistics. Calm, instructional, kind.', mood: 'instructing' },
      { speaker: 'ryosuke_dad', jp: 'はい、必ず。本当に、ご心配おかけして…', en: 'Yes — of course. Sorry to have worried you with this…', style: 'Reflexive Japanese politeness — apologising for having existed in her schedule. Half-bow inside the voice.', mood: 'apologetic' },
      { speaker: 'saito_doctor', jp: 'いえ、いつでも来てください。お大事に。', en: 'Not at all — come in any time. Take care.', style: 'Closing, warm, unhurried. The reassurance is the closing line.', mood: 'closing_kind' },
    ],
  },
  {
    id: 'conv_00033',
    context: 'A weathered fishing pier in Kyushu, early morning. Hina is visiting Grandpa Goro. She has been holding a rod for an hour and caught nothing.',
    purpose: 'cross-generational instruction — patience as a small life lesson, mostly through silence',
    ambient: 'park_morning',
    target_vocab: ['本当に','時間','一緒','少し','見る','ない','何'],
    cast: ['goro_grandpa','hina_child'],
    frequency_tier: 1,
    length_tier: 'Long (13-20)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hina_child', jp: 'おじいちゃん、まだ、なんも来ない…', en: 'Grandpa — nothing\'s come yet…', style: 'Half-whine, half-genuine. Bouncing a little on the pier.', mood: 'restless_kid' },
      { speaker: 'goro_grandpa', jp: 'うん。', en: 'Mm.', style: 'Two letters. Doesn\'t look up. Kyushu drawl.', mood: 'unhurried' },
      { speaker: 'hina_child', jp: 'ねえ、本当に魚いる？', en: 'Hey — are there really fish?', style: 'Tries doubt as a strategy. Lifts the rod doubtfully.', mood: 'doubting_strategy' },
      { speaker: 'goro_grandpa', jp: 'おる。', en: 'They\'re there.', style: 'One word. Total certainty. Doesn\'t elaborate.', mood: 'certain' },
      { speaker: 'hina_child', jp: 'じゃあ、なんで来ないの？', en: 'Then why aren\'t they coming?', style: 'Genuine kid-logic question. Sits down on the pier in the voice.', mood: 'genuinely_asking' },
      { speaker: 'goro_grandpa', jp: '魚の時間や、こっちの時間ちゃう。', en: 'Fish-time and our-time are different.', style: 'Slow, considered. Kyushu inflection. A small offered truth.', mood: 'gentle_teaching' },
      { speaker: 'hina_child', jp: '…(thinking)', en: '(quiet thinking)', style: 'A real beat. The kid is actually considering it. Tilts her head in the voice.', mood: 'thinking' },
      { speaker: 'goro_grandpa', jp: 'ひな。少し、静かに。', en: 'Hina. Quiet a little.', style: 'Even softer than the previous line. An invitation, not a scolding.', mood: 'inviting_quiet' },
      { speaker: 'hina_child', jp: '(holds breath)', en: '(holds her breath)', style: 'A whole-body listening. No words, just attention focused.', mood: 'listening' },
      { speaker: 'goro_grandpa', jp: '見てみ。あそこ、丸い波。', en: 'Look there. The round ripple.', style: 'Points without lifting his arm much. The first new information of the morning.', mood: 'pointing' },
      { speaker: 'hina_child', jp: 'うん…うん！見える！', en: 'Yeah… yeah! I see it!', style: 'A breath of discovery. Voice almost a whisper, then louder on the second 「うん」.', mood: 'discovering' },
      { speaker: 'goro_grandpa', jp: 'あそこに、魚おる。', en: 'A fish, right there.', style: 'Slightly proud — not of the fish, of her seeing. Voice low.', mood: 'quietly_proud' },
      { speaker: 'hina_child', jp: '本当に？', en: 'Really?', style: 'Smaller than her earlier doubt. A whole different word.', mood: 'softened_doubt' },
      { speaker: 'goro_grandpa', jp: 'ほんま。一緒に待とう。', en: 'Really. Let\'s wait — together.', style: 'The most words he\'ll say today. Settles back in the voice.', mood: 'settling_together' },
      { speaker: 'hina_child', jp: 'うん。一緒に。', en: 'Yeah. Together.', style: 'Quietest line in the conversation. She gets it now.', mood: 'quiet_understanding' },
    ],
  },
  {
    id: 'conv_00034',
    context: 'Asuka\'s apartment on a Saturday. Mei has come over to talk through a difficult conversation she needs to have with her family — and is stuck on the words.',
    purpose: 'friend coaches friend — gentle preparation, role-playing the harder voice',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','言う','時間','何','ない','大丈夫','考える'],
    cast: ['asuka_teacher','mei_romantic'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'asuka_teacher', jp: 'で、何を言いたいの、メイちゃんは。', en: 'So — what do you want to say, Mei-chan.', style: 'Sits down across from her. Calm, level, the teacher voice doing real work.', mood: 'inviting_clear' },
      { speaker: 'mei_romantic', jp: '…それが、わかんない。', en: '…That\'s the thing. I don\'t know.', style: 'Eyes on her hands. The honest answer first, almost too honest.', mood: 'honest_lost' },
      { speaker: 'asuka_teacher', jp: 'うん。じゃあ、考えてること、ぜんぶ言ってみて。', en: 'Okay. Then say everything you\'re thinking — all of it.', style: 'No edge. The invitation made spacious.', mood: 'spacious_invite' },
      { speaker: 'mei_romantic', jp: 'ぜんぶは、難しい…', en: 'All of it — that\'s hard…', style: 'Small protest, real. Voice almost tearing.', mood: 'small_protest' },
      { speaker: 'asuka_teacher', jp: 'ちょっとずつでいい。私、時間あるから。', en: 'Bit by bit is fine. I\'ve got time.', style: 'Steady. The 「時間あるから」 carries weight — it\'s the whole offer.', mood: 'patient_offer' },
      { speaker: 'mei_romantic', jp: 'ありがとう…えっと、本当はね…', en: 'Thank you… um, actually…', style: 'A breath in. The 「えっと」 is half a delay, half a gathering.', mood: 'gathering' },
      { speaker: 'asuka_teacher', jp: 'うん。', en: 'Mm.', style: 'One syllable, all listening. Doesn\'t fill the silence.', mood: 'listening' },
      { speaker: 'mei_romantic', jp: '家族に、ちゃんと言いたいことがあって。でも、傷つけたくなくて。', en: 'There\'s something I really want to tell my family. But — I don\'t want to hurt them.', style: 'Two clauses, a beat between. The contradiction is the whole problem.', mood: 'naming_the_knot' },
      { speaker: 'asuka_teacher', jp: 'うん、その気持ちは大事。でも、言わないと、メイちゃんが傷つくよ。', en: 'Mm — that feeling matters. But if you don\'t say it, you\'ll be the one hurt.', style: 'Gentle but firm. Lands the half-step Mei couldn\'t.', mood: 'firm_gentle' },
      { speaker: 'mei_romantic', jp: '…そうかも。', en: '…Maybe so.', style: 'The smallest of agreements. Eyes up, finally.', mood: 'small_agreeing' },
      { speaker: 'asuka_teacher', jp: '大丈夫。練習しよ。私が、お母さんやる。', en: 'It\'s okay. Let\'s practise. I\'ll be your mom.', style: 'Stands up slightly in the voice. A practical kindness — turning the abstract into a scene.', mood: 'practical_kind' },
      { speaker: 'mei_romantic', jp: '(small laugh)…じゃ、お願い。', en: '(small laugh) …Okay then. Please.', style: 'A real laugh, brief. Then a softer ask. The room got lighter by half.', mood: 'half_relieved' },
    ],
  },
  {
    id: 'conv_00035',
    context: 'Sunday lunch at the elder Hiroshi\'s house. Hiroshi Yamada (boss) is the son; Hiroshi Kato (retired professor) is the father. They share a name — and a quiet. Today the son has brought news he\'s been delaying for weeks.',
    purpose: 'long-deferred confessional — adult son to elder father, the conversation he has been rehearsing for two years',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','時間','今','言う','考える','仕事','大丈夫'],
    cast: ['hiroshi_boss','hiroshi_elder'],
    frequency_tier: 2,
    length_tier: 'Extended (21-30)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hiroshi_boss', jp: '父さん、ちょっと話があって。', en: 'Dad — there\'s something I want to talk about.', style: 'Stiff. The opening he has rehearsed in the car. Each word picked carefully.', mood: 'opening_stiff' },
      { speaker: 'hiroshi_elder', jp: 'ああ、座りなさい。お茶、飲むか。', en: 'Mm — sit down. Drink some tea?', style: 'No surprise. Already pouring. The kettle was on for a reason.', mood: 'unsurprised_warm' },
      { speaker: 'hiroshi_boss', jp: 'いえ、すぐで。', en: 'No — I\'ll keep it short.', style: 'Restless. Still standing in the voice.', mood: 'restless' },
      { speaker: 'hiroshi_elder', jp: '忙しいんだろう。座って、まず一杯。', en: 'You\'re busy, I know. Sit — one cup first.', style: 'Slow, deliberate. The chair pulled out is the actual response.', mood: 'making_space' },
      { speaker: 'hiroshi_boss', jp: '…(sits, slow exhale)', en: '(sits down, exhales)', style: 'Lets the chair take him. The exhale audible.', mood: 'sitting_finally' },
      { speaker: 'hiroshi_elder', jp: 'で。', en: 'So.', style: 'Single word. Full attention. The room narrows.', mood: 'fully_attending' },
      { speaker: 'hiroshi_boss', jp: '実は、会社、辞めようかと。', en: 'Truth is — I\'m thinking of leaving the company.', style: 'Quietest he\'s been in years. The sentence he hasn\'t said out loud yet.', mood: 'releasing' },
      { speaker: 'hiroshi_elder', jp: '……。', en: '……', style: 'A long silence — long enough that the listener feels it. No surprise visible.', mood: 'absorbing' },
      { speaker: 'hiroshi_boss', jp: '驚かないの。', en: 'You\'re not surprised.', style: 'Half-relieved, half-asking. A son testing a father.', mood: 'testing_relief' },
      { speaker: 'hiroshi_elder', jp: '驚いた。だが、待った。', en: 'I was. But — I waited.', style: 'Two clauses separated by a small dignified pause. The truth as he has it.', mood: 'dignified_truth' },
      { speaker: 'hiroshi_boss', jp: 'ずっと、考えてた。本当に長く。', en: 'I\'ve been thinking about it. Really, for a long time.', style: 'A long breath. The 「本当に長く」 carries two years of nights.', mood: 'admitting_weight' },
      { speaker: 'hiroshi_elder', jp: 'いつから。', en: 'Since when.', style: 'Plain question. No accusation in it. Just curious.', mood: 'plain_asking' },
      { speaker: 'hiroshi_boss', jp: '正直、二年。', en: 'Honestly — two years.', style: 'The number is the heaviest thing in the sentence.', mood: 'naming_the_weight' },
      { speaker: 'hiroshi_elder', jp: '二年か…。長いな。', en: 'Two years… that\'s long.', style: 'Repeats the number to hold it. The fatherly recognition without judgment.', mood: 'recognising_weight' },
      { speaker: 'hiroshi_boss', jp: '父さんに、最初に言うべきだった。', en: 'I should have told you first.', style: 'The smallest line in the conversation. A confession underneath the confession.', mood: 'sorry_smaller' },
      { speaker: 'hiroshi_elder', jp: 'いや。お前の人生だ。', en: 'No. It\'s your life.', style: 'Firm. The gift of the answer he didn\'t expect.', mood: 'firm_gift' },
      { speaker: 'hiroshi_boss', jp: '…意外だった、その答え。', en: '…That answer surprised me.', style: 'A breath of release. Voice catches half a step.', mood: 'released' },
      { speaker: 'hiroshi_elder', jp: '私だって、お前の年の頃、迷った。', en: 'When I was your age — I was lost too.', style: 'A piece of his own history he never volunteered before. Quiet.', mood: 'sharing' },
      { speaker: 'hiroshi_boss', jp: '父さんが？', en: 'You did?', style: 'Genuine surprise. Looks up in the voice for the first time.', mood: 'looking_up' },
      { speaker: 'hiroshi_elder', jp: 'うん。…で、辞めて、何をするんだ。', en: 'Yes. …So if you leave — what will you do?', style: 'Patient and genuinely curious. The conversation pivoting toward what comes next.', mood: 'pivoting_forward' },
      { speaker: 'hiroshi_boss', jp: 'それも、まだ、決まってなくて。', en: 'That part — I haven\'t decided yet.', style: 'Honest. A faint embarrassed laugh in the voice.', mood: 'honest_embarrassed' },
      { speaker: 'hiroshi_elder', jp: 'いいんだ。時間はある。お茶、もう一杯。', en: 'That\'s fine. There\'s time. Another cup of tea.', style: 'Closing line, in the most fatherly cadence he has. Pours.', mood: 'fatherly_closing' },
    ],
  },
  {
    id: 'conv_00036',
    context: 'Their shared kitchen at 1 a.m. on a Saturday. Mei has been cleaning; Ren has been gaming for three hours and hasn\'t looked up.',
    purpose: 'low-grade partner friction — small domestic friction without becoming a fight',
    ambient: 'apartment_indoor',
    target_vocab: ['今','ちょっと','時間','本当に','大丈夫','ない'],
    cast: ['mei_romantic','ren_uni'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'mei_romantic', jp: 'ちょっと、聞いてる？', en: 'Hey — are you listening?', style: 'Tired, not sharp yet. Pauses with a dish in hand.', mood: 'tired_check' },
      { speaker: 'ren_uni', jp: 'うん、聞いてる…ちょっと待って。', en: 'Yeah — listening… one sec.', style: 'Eyes still on the screen. Half-truth. The 「ちょっと待って」 is reflexive.', mood: 'distracted_yes' },
      { speaker: 'mei_romantic', jp: '待つの三回目だよ。', en: 'That\'s the third time you\'ve said "one sec".', style: 'Sets the dish down. Voice flat — the accusation is in the count, not the tone.', mood: 'flat_accusation' },
      { speaker: 'ren_uni', jp: '…ごめん。今、終わった。何？', en: '…Sorry. Done now. What is it?', style: 'Puts the controller down. Genuinely turning. Voice softer.', mood: 'turning_genuine' },
      { speaker: 'mei_romantic', jp: 'キッチン、明日でいいって言ったの覚えてる？', en: 'You said you\'d do the kitchen tomorrow — remember?', style: 'No edge yet. A real question.', mood: 'real_question' },
      { speaker: 'ren_uni', jp: '…あ。あー、ごめん、忘れてた。', en: '…Oh. Oh — sorry, forgot.', style: 'Caught. Real. Not making excuses or arguing back.', mood: 'caught_honest' },
      { speaker: 'mei_romantic', jp: 'うん。本当に、ちょっとだけ手伝って。', en: 'Yeah. Really — just a little help.', style: 'Tired, not angry. The 「ちょっとだけ」 carries the whole ask.', mood: 'tired_asking' },
    ],
  },
  {
    id: 'conv_00037',
    context: 'Daichi is on solo-babysitting duty for his niece Hina, in his sister\'s apartment. They\'re about an hour in.',
    purpose: 'chaotic uncle-niece play — fond exasperation in both directions',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','今','ない','見る','一緒','ありがとう'],
    cast: ['daichi_kansai','hina_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'daichi_kansai', jp: 'ひな、これ食べてええの？', en: 'Hina — can I eat this?', style: 'Holding a cookie up like evidence. Kansai sing-song.', mood: 'mock_innocent' },
      { speaker: 'hina_child', jp: 'お母さんに聞いて！', en: 'Ask Mom!', style: 'Authority-deferring eight-year-old. Bouncing in the voice.', mood: 'deferring' },
      { speaker: 'daichi_kansai', jp: '電話、出ぇへんねん。', en: 'Phone — she\'s not picking up.', style: 'Mock-tragic. Already eating the cookie in the voice.', mood: 'mock_tragic' },
      { speaker: 'hina_child', jp: '…一個だけならいいよ、たぶん。', en: '…One only — probably okay.', style: 'Cautious permission. The 「たぶん」 is the eight-year-old\'s loophole.', mood: 'cautious_kid' },
      { speaker: 'daichi_kansai', jp: 'ナイス。よし、二人で内緒な。', en: 'Nice. Alright — our secret, the two of us.', style: 'Conspiratorial. Voice drops half a step into mock-whisper.', mood: 'conspiratorial' },
      { speaker: 'hina_child', jp: '内緒、ばれる。', en: 'Secrets — get found out.', style: 'Matter-of-fact wisdom from an eight-year-old. Unflappable.', mood: 'wisdom_kid' },
      { speaker: 'daichi_kansai', jp: '(laugh)本当に、お前、母親みたいに言うな。', en: '(laughs) Really — you sound just like your mom.', style: 'Big Kansai laugh. Affectionate. The 「ほんまに」 in Kansai-Tokyo blend.', mood: 'affectionate_laugh' },
      { speaker: 'hina_child', jp: 'ねえ、おじちゃん、一緒に絵描いて。', en: 'Hey — Oji-chan, let\'s draw together.', style: 'Drops the previous topic instantly. Already pulling out crayons in the voice.', mood: 'topic_shift_kid' },
      { speaker: 'daichi_kansai', jp: '俺、絵、めっちゃ下手やで。', en: 'I\'m super bad at drawing.', style: 'Pre-emptive disclaimer. Half-laughing, already sitting down.', mood: 'self_deprecating' },
      { speaker: 'hina_child', jp: 'いいの、見せて。', en: 'It\'s fine — show me.', style: 'No mercy. Hands him the crayons.', mood: 'no_mercy' },
    ],
  },
  {
    id: 'conv_00038',
    context: 'A village fishing event in Iwate. Goro is visiting from Kyushu; Tatsuya is the local. They\'ve ended up at the same spot by accident. Most of the conversation is silence.',
    purpose: 'incidental old-men camaraderie — companionship punctuated by tiny exchanges',
    ambient: 'park_morning',
    target_vocab: ['本当に','時間','今','大丈夫','見る','一緒'],
    cast: ['goro_grandpa','tatsuya_country'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'goro_grandpa', jp: '…(long silence, then)寒いな。', en: '(long silence) …Cold.', style: 'A whole comfortable silence before this line. Then two syllables.', mood: 'silence_breaking' },
      { speaker: 'tatsuya_country', jp: 'ああ。', en: 'Ah.', style: 'Single syllable acknowledgement. Doesn\'t look over.', mood: 'acknowledging' },
      { speaker: 'goro_grandpa', jp: '九州、もっと暖こうて。', en: 'Kyushu — warmer.', style: 'Three slow clauses. Kyushu inflection. A small geography lesson without lifting his head.', mood: 'geographic_calm' },
      { speaker: 'tatsuya_country', jp: 'だろうな。', en: 'Reckon so.', style: 'Tohoku softness. Spoken like he has thought about Kyushu before.', mood: 'tohoku_acknowledging' },
      { speaker: 'goro_grandpa', jp: '…釣れんけど、ええわ。', en: '…Not biting — but it\'s fine.', style: 'A small philosophical line. Said toward the water.', mood: 'philosophical' },
      { speaker: 'tatsuya_country', jp: 'ええわな。', en: 'Fine indeed.', style: 'The fewest words a man can use to agree. The 「な」 carries everything.', mood: 'minimal_agreement' },
      { speaker: 'goro_grandpa', jp: '(silence, then)息子、東京におるんよ。', en: '(silence) Son\'s in Tokyo.', style: 'Volunteered out of nothing. The shape of a real offering.', mood: 'small_offering' },
      { speaker: 'tatsuya_country', jp: 'うちの娘も、東京。', en: 'My daughter too — Tokyo.', style: 'Returns the offering at the same tempo. Recognition without ceremony.', mood: 'returning_offering' },
      { speaker: 'goro_grandpa', jp: 'ふん。', en: 'Hm.', style: 'Single voiced consonant. Acknowledges the connection.', mood: 'acknowledging_minimal' },
      { speaker: 'tatsuya_country', jp: '会えるか、年に一回。', en: 'See her about once a year.', style: 'Plain fact, no complaint inside the words.', mood: 'plain_fact' },
      { speaker: 'goro_grandpa', jp: '俺は、二回や。今年は。', en: 'Twice for me. This year.', style: 'A small offering of luck — said quietly, not boastfully.', mood: 'quietly_lucky' },
      { speaker: 'tatsuya_country', jp: 'いいな。', en: 'Good.', style: 'No envy, no sarcasm. Genuinely meant agreement.', mood: 'genuine_good' },
      { speaker: 'goro_grandpa', jp: '…うん。', en: '…Mm.', style: 'The smallest sufficient answer. Both men return to the water.', mood: 'sufficient' },
    ],
  },
  {
    id: 'conv_00039',
    context: 'A small café in the afternoon. Aoi and Mei haven\'t seen each other in a few months — both have been quietly drowning. Today is the recover-the-friendship session.',
    purpose: 'friendship maintenance — gentle catch-up after a drift',
    ambient: 'cafe_afternoon',
    target_vocab: ['本当に','元気','今','時間','一緒','嬉しい','見る'],
    cast: ['aoi_barista','mei_romantic'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'aoi_barista', jp: 'メイ、久しぶり！元気？', en: 'Mei — it\'s been so long! How are you?', style: 'Up half an octave on the greeting. Stands when Mei walks in. Real warmth.', mood: 'bright_greeting' },
      { speaker: 'mei_romantic', jp: 'うん、元気。あおいも？', en: 'Yeah — good. You too?', style: 'A little softer than Aoi\'s greeting. Already settling into the chair.', mood: 'softer_returning' },
      { speaker: 'aoi_barista', jp: 'うん、まあまあ。座って座って。', en: 'Mm, alright. Sit, sit.', style: 'Pulls the chair out. Easy, generous.', mood: 'hosting' },
      { speaker: 'mei_romantic', jp: '最後、いつ会ったっけ？', en: 'When did we last see each other?', style: 'Genuinely trying to remember. Slight worried laugh.', mood: 'trying_to_remember' },
      { speaker: 'aoi_barista', jp: '夏、たぶん。', en: 'Summer — probably.', style: 'Half-grimace. The realisation lands in real-time.', mood: 'small_realisation' },
      { speaker: 'mei_romantic', jp: '…うわ、本当に。早いね、時間。', en: '…Wow — really. Time flies.', style: 'Quieter. A small honest commentary on adult life.', mood: 'small_honest' },
      { speaker: 'aoi_barista', jp: 'ね。…で、レンとは、どう？', en: 'Right? …And — how are things with Ren?', style: 'The actual question she has been waiting to ask. Voice soft.', mood: 'asking_real' },
      { speaker: 'mei_romantic', jp: '最近、いい感じ。', en: 'Recently — pretty good.', style: 'A small unguarded smile in the voice.', mood: 'unguarded_smile' },
      { speaker: 'aoi_barista', jp: 'よかった、本当に。なんか、ほっとした。', en: 'I\'m glad — really. Honestly, I feel relieved.', style: 'The 「ほっとした」 is the line that explains why she\'s been worried. Soft.', mood: 'relieved_caring' },
      { speaker: 'mei_romantic', jp: 'あおいは？元気そうで嬉しい。', en: 'And you? You look well — I\'m glad.', style: 'Returns the care, quiet and direct. The 「嬉しい」 is real.', mood: 'direct_caring' },
      { speaker: 'aoi_barista', jp: 'うん、私も今は、ちゃんと。', en: 'Mm — I\'m actually doing okay now.', style: 'A small honest answer. The 「ちゃんと」 carries history.', mood: 'small_honest_answer' },
    ],
  },
  {
    id: 'conv_00040',
    context: 'A train platform on a quiet afternoon. Six-year-old Sho has dropped his train pass; a high school girl picks it up.',
    purpose: 'kindness micro-encounter — older girl gives a kid grace, both walk away brighter',
    ambient: 'train_station_day',
    target_vocab: ['ありがとう','大丈夫','見る','もう'],
    cast: ['sakura_teen','sho_child'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'sakura_teen', jp: 'あ、これ、君の？', en: 'Oh — is this yours?', style: 'Already kneeling in the voice. Kansai cadence softened for a kid.', mood: 'kneeling_kind' },
      { speaker: 'sho_child', jp: '…はい。', en: '…Yes.', style: 'Tiny voice. Surprised to have an older girl talking to him.', mood: 'startled_small' },
      { speaker: 'sakura_teen', jp: '気をつけよ。電車、もうすぐ来るで。', en: 'Be careful. Train\'s coming soon.', style: 'Big-sister tone, Kansai. Warm, brisk, useful.', mood: 'big_sister' },
      { speaker: 'sho_child', jp: 'ありがとうございます。', en: 'Thank you so much.', style: 'Full keigo from a six-year-old. A real little bow in the voice.', mood: 'formal_polite_kid' },
      { speaker: 'sakura_teen', jp: '(grins)真面目やな。じゃあな。', en: '(grins) You\'re a serious one. See ya.', style: 'A real grin in the voice. Standing up. Affectionate.', mood: 'affectionate_grin' },
      { speaker: 'sho_child', jp: '…(small wave)', en: '(small wave)', style: 'No words. The smallest hand-lift in the universe.', mood: 'small_wave' },
    ],
  },
  {
    id: 'conv_00041',
    context: 'The apartment-building entrance, late afternoon. Mrs. Mori catches Riku coming home with a hair colour he very much didn\'t have yesterday.',
    purpose: 'neighbourhood observation — affectionate prying that Riku can\'t escape',
    ambient: 'apartment_hallway',
    target_vocab: ['本当に','今日','見る','ない'],
    cast: ['mrs_mori_neighbor','riku_teen'],
    frequency_tier: 1,
    length_tier: 'Short (5-6)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: 'あら、リクくん、髪、変わった？', en: 'Oh — Riku-kun, did your hair change?', style: 'Voice spikes. Mid-volume Kansai. Has been waiting at the gate.', mood: 'pouncing_warm' },
      { speaker: 'riku_teen', jp: '…あ、はい。', en: '…Oh, yeah.', style: 'Caught in mid-step. Mumbled. Pulls his hood up half-instinctively in the voice.', mood: 'caught_mumbled' },
      { speaker: 'mrs_mori_neighbor', jp: 'お母さん、見たんか、それ？', en: 'Has your mom seen that yet?', style: 'A question that is half a forecast. Eyes narrowed in the voice.', mood: 'forecasting' },
      { speaker: 'riku_teen', jp: '…まだ。', en: '…Not yet.', style: 'One word. A whole near-future visible in it.', mood: 'admitting_doom' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふふ。今日、覚悟しときや。', en: 'Heh. Brace yourself for today.', style: 'A small laugh. Affectionate, mock-warning to the kid.', mood: 'affectionate_warning' },
      { speaker: 'riku_teen', jp: '…(half-laugh)はい。', en: '(half-laugh) Yeah.', style: 'A real laugh, brief. The neighbourhood-aunt energy got him.', mood: 'broken_briefly' },
    ],
  },
  {
    id: 'conv_00042',
    context: 'Hiroshi (elder) is babysitting six-year-old Sho. Out of a drawer he pulls a postcard he hasn\'t looked at in decades — one his own mother wrote to him as a child.',
    purpose: 'oral history micro-moment — an old letter becomes a doorway',
    ambient: 'apartment_indoor',
    target_vocab: ['本当に','見る','時間','今','ない','読む'],
    cast: ['hiroshi_elder','sho_child'],
    frequency_tier: 1,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'hiroshi_elder', jp: 'しょうくん、これ、見たことあるかい。', en: 'Sho-kun — have you seen this before?', style: 'Holds up the postcard carefully. Voice lower, intimate.', mood: 'careful_intimate' },
      { speaker: 'sho_child', jp: '…紙？', en: '…Paper?', style: 'Genuine kid question. Leans in, head tilted.', mood: 'leaning_in' },
      { speaker: 'hiroshi_elder', jp: 'はがき。お母さんからの。私の、お母さん。', en: 'A postcard. From my mother. My mother.', style: 'Slowly. Three short sentences. Lets the word 「母さん」 mean what it means.', mood: 'naming_quietly' },
      { speaker: 'sho_child', jp: 'ええ…おじいちゃんの、お母さん…？', en: 'Wait… Grandpa\'s — mother…?', style: 'Genuine kid astonishment. The math doesn\'t fit at first.', mood: 'kid_astonishment' },
      { speaker: 'hiroshi_elder', jp: '私も、子供だった頃。', en: 'When I was a child too.', style: 'Quiet, slow. A whole life given as five syllables.', mood: 'gentle_truth' },
      { speaker: 'sho_child', jp: '読んでもいい？', en: 'Can I read it?', style: 'A small precious request. Hands not yet touching the postcard.', mood: 'careful_request' },
      { speaker: 'hiroshi_elder', jp: 'もちろん。ゆっくり読みなさい。時間はある。', en: 'Of course. Read it slowly. There\'s time.', style: 'Slides closer in the voice. The 「時間はある」 is the whole afternoon.', mood: 'gentle_offer' },
      { speaker: 'sho_child', jp: 'うん…。', en: 'Mm…', style: 'Settles into the side of the older man in the voice. Reads in silence after.', mood: 'settling_in' },
    ],
  },
  {
    id: 'conv_00043',
    context: 'A small private language school in Shinjuku. Hiroshi (retired professor) has been asked by Asuka to give a one-off Saturday talk to advanced students. He has come early; she\'s showing him around.',
    purpose: 'peer-to-peer professional warmth — two teachers recognising each other',
    ambient: 'school_classroom',
    target_vocab: ['本当に','時間','今日','一緒','元気','ありがとう'],
    cast: ['hiroshi_elder','asuka_teacher'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: { generated_by: 'claude-opus-4-7 (batch_002)', generated_at: NOW, source_plan_row: '' },
    lines: [
      { speaker: 'asuka_teacher', jp: '先生、本日はわざわざ、ありがとうございます。', en: 'Sensei — thank you for taking the time today.', style: 'Polite teacher voice. The double 「ご」 of professional respect.', mood: 'polite_respectful' },
      { speaker: 'hiroshi_elder', jp: 'いえ、こちらこそ。お招きいただいて。', en: 'No — thank you, for the invitation.', style: 'Returns the formality at his slow pace. A small bow inside the voice.', mood: 'returning_formal' },
      { speaker: 'asuka_teacher', jp: 'お元気そうで。', en: 'You look well.', style: 'Honest. The kind of greeting that stops being just a greeting.', mood: 'honest_greeting' },
      { speaker: 'hiroshi_elder', jp: 'うん、なんとか。学生たちは、何人くらい？', en: 'Mm — managing. How many students?', style: 'Pivots toward the work. The 「なんとか」 carries one beat of honest age.', mood: 'pivot_practical' },
      { speaker: 'asuka_teacher', jp: '今日は十二名です。少なめで、すみません。', en: 'Twelve today. Smaller than usual — sorry.', style: 'Half-apologetic. Already worried about disappointing him.', mood: 'half_apologetic' },
      { speaker: 'hiroshi_elder', jp: 'いえいえ。少ないほうが、いい話になる。', en: 'No, no. Fewer makes for better talk.', style: 'A real teacher\'s view. The kind of line that immediately puts her at ease.', mood: 'reassuring_pro' },
      { speaker: 'asuka_teacher', jp: '先生、そうおっしゃると思いました。', en: 'Sensei — I thought you\'d say that.', style: 'A small smile in the voice. The kind of line a junior teacher can\'t resist.', mood: 'smiling_junior' },
      { speaker: 'hiroshi_elder', jp: '(small chuckle)私も、教師、長くやっただけある。', en: '(small chuckle) I\'ve been a teacher a long time, you know.', style: 'Real chuckle. The kind shared between two members of the same craft.', mood: 'craft_recognition' },
      { speaker: 'asuka_teacher', jp: 'お時間、ぴったり一時間で大丈夫ですか？', en: 'Is exactly one hour okay?', style: 'Back to logistics. Practical and warm.', mood: 'practical_warm' },
      { speaker: 'hiroshi_elder', jp: 'うん、ちょうど。…一緒に、お茶でも？前に。', en: 'Yes — perfect. …Tea together first, perhaps?', style: 'A small unexpected offer. Doors opening.', mood: 'opening_doors' },
      { speaker: 'asuka_teacher', jp: 'ぜひ。準備、すぐ。', en: 'Yes please. I\'ll have it ready right away.', style: 'A real smile in the voice. Already turning toward the kitchen.', mood: 'happy_response' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const outPath = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(outPath, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log(`wrote ${CONVERSATIONS.length} conversation(s) to ${OUT_DIR}`);
