import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_115)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02281',
    context: 'Mei does laundry; complains to Daichi about a stubborn stain.',
    purpose: 'Couple in everyday domestic chat.',
    ambient: 'laundry_room_low',
    sound_effects: [],
    target_vocab: ['洗剤', '洗い', '汚れ', '軽量', '残ら', '丁寧', 'がんばる', '気軽'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、新しい洗剤、買ったの。', en: "Daichi — new detergent, bought.", style: 'soft young wife voice, warm warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: '軽量、いいなぁ、持ち運びやすい。', en: "Lightweight — fine, easy carry.", style: 'warm Kansai husband voice, soft warm appreciative delivery carefully' },
      { speaker: 'mei_romantic', jp: '汚れ、残らない感じ、よく洗える。', en: "Stain — not remaining feel, well wash.", style: 'gentle young woman voice, soft warm impressed delivery carefully' },
      { speaker: 'daichi_kansai', jp: '丁寧に、洗えとるな、ええ感じや。', en: "Carefully — washing, fine feel.", style: 'soft Kansai husband voice, warm warm approving delivery carefully' },
      { speaker: 'mei_romantic', jp: '気軽に、毎日、がんばるね。', en: "Casually — daily, try.", style: 'tender young wife voice, soft warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前のおかげで、家、ようけ清潔や。', en: "Thanks to you — home, much clean.", style: 'warm Kansai husband voice, soft warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、嬉しい。', en: "Thanks — happy.", style: 'soft young wife voice, warm warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02282',
    context: 'Sho-young gets sunburn at the beach; Saito treats him.',
    purpose: 'Doctor caring for child summer mishap.',
    ambient: 'clinic_quiet_low',
    sound_effects: [],
    target_vocab: ['日焼け', '小児', '熱い', '皮', '薬', '丁寧', '直ぐに', '注意'],
    cast: ['saito_doctor', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '先生、日焼け、痛い!', en: "Doctor — sunburn, hurts!", style: 'soft tearful child boy voice, warm warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '熱い感じ、ようけある?小児、よく出る症状や。', en: "Hot feel — much exists? Children, often.", style: 'measured doctor voice, soft warm informative delivery carefully' },
      { speaker: 'sho_child', jp: '皮、ようけ赤い!', en: "Skin — much red!", style: 'soft worried child boy voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '直ぐに、優しい薬、塗ってあげるね。', en: "Soon — gentle medicine, apply.", style: 'tender doctor voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: '気をつけないと、また、なるのね。', en: "Be careful — again, become.", style: 'soft thoughtful child boy voice, warm warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '日陰、丁寧に、休んでね。', en: "Shade — carefully, rest.", style: 'gentle doctor voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、先生!', en: "Thanks — doctor!", style: 'soft relieved child boy voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02283',
    context: 'Hina-young helps Naoko fix a broken air conditioner.',
    purpose: 'Teen and aunt solving practical problem.',
    ambient: 'shop_low_repair',
    sound_effects: [],
    target_vocab: ['クーラー', 'しくみ', '故障', '直ぐに', '頑張る', '埋める', '熱い', '冷却'],
    cast: ['hina_child', 'naoko_aunt'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、クーラー、また故障や!', en: "Hina — AC, again broken!", style: 'frustrated Kansai aunt voice, bright warm honest delivery carefully' },
      { speaker: 'hina_child', jp: 'しくみ、見ましょうか?', en: "Mechanism — see?", style: 'soft eager teen girl voice, warm warm helpful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '直ぐに、業者、呼ばなあかんわ。', en: "Soon — repair, call must.", style: 'soft Kansai aunt voice, warm warm pragmatic delivery carefully' },
      { speaker: 'hina_child', jp: '熱い夏なので、冷却、大事ですね。', en: "Hot summer — cooling, matters.", style: 'composed teen girl voice, soft warm informative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '頑張ってもらわなあかん、業者!', en: "Must try — repair!", style: 'animated Kansai aunt voice, bright warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: '隙を埋めながら、直したいですね。', en: "Gap fill — want fix.", style: 'gentle teen girl voice, soft warm encouraging delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お前、頼もしい!', en: "You — reliable!", style: 'tender Kansai aunt voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02284',
    context: 'Kenji and Aoi observe their growing baby; small loving moment.',
    purpose: 'New parents in tender development witnessing.',
    ambient: 'nursery_quiet_warm',
    sound_effects: [],
    target_vocab: ['父母', '視力', '飼い', '着け', '直ぐに', '愛情', '深く', '心'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、視力、ようけ発達してるね、赤ちゃん。', en: "Ken-chan — vision, much developing, baby.", style: 'soft tender adult woman voice, warm warm awed delivery carefully' },
      { speaker: 'kenji_office', jp: '父母として、毎日、感動するわ。', en: "Parents as — daily, moved.", style: 'warm Kansai father voice, soft warm tender delivery carefully' },
      { speaker: 'aoi_barista', jp: '指、直ぐに、ようけ動かす!', en: "Finger — soon, much move!", style: 'thrilled adult woman voice, bright warm delight delivered carefully' },
      { speaker: 'kenji_office', jp: '着けてる靴下、可愛いやな、ちっちゃい。', en: "Wearing sock — cute, tiny.", style: 'tender Kansai father voice, soft warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '愛情、深く、本当に感じる。', en: "Love — deeply, truly feel.", style: 'tearful adult woman voice, soft warm content delivery carefully' },
      { speaker: 'kenji_office', jp: '飼い猫みたい、優しい目しとる!', en: "Pet cat-like — gentle eyes!", style: 'soft amused Kansai father voice, warm warm playful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、家族、本当に幸せ。', en: "Heh — family, truly happy.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02285',
    context: 'Sakura researches a Japanese sushi master\'s story.',
    purpose: 'Writer interviewing craftsman.',
    ambient: 'studio_quiet_warm',
    sound_effects: [],
    target_vocab: ['すし', '旨い', '伝統', '長年', '職人', '誉め', '尊重', '創り'],
    cast: ['sakura_teen', 'hiroshi_boss'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '社長、すしの伝統、深いですね。', en: "Boss — sushi tradition, deep.", style: 'soft adult writer voice, warm warm respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'おう、長年、職人さんが、創り続けてきた。', en: "Yeah — long years, artisans, kept creating.", style: 'measured boss voice, soft warm proud delivery carefully' },
      { speaker: 'sakura_teen', jp: '旨いお店、皆さん、ようけ誉めてはるんですね。', en: "Tasty shop — all, much praising.", style: 'tender adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'お互い、尊重しながら、続けていく。', en: "Each — respecting, continue.", style: 'gentle boss voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '創り続ける、姿勢、すばらしい。', en: "Keep creating — stance, splendid.", style: 'soft adult writer voice, warm warm reverent delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '記事にも、よろしく頼むわ。', en: "Article too — please ask.", style: 'warm boss voice, soft warm trusting delivery carefully' },
      { speaker: 'sakura_teen', jp: '心、こめて書きます。', en: "Heart — put write.", style: 'humble adult writer voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02286',
    context: 'Tatsuya-country tells Sho-young about a crab fishing expedition.',
    purpose: 'Elder sharing rural adventure tale.',
    ambient: 'porch_evening_breeze',
    sound_effects: [],
    target_vocab: ['カニ', '海底', '湧い', '潮', '海', '深い', '昔', '冒険'],
    cast: ['tatsuya_country', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、カニ、釣ったことある?', en: "Grandpa — crab, caught?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、昔、海で冒険したで。', en: "Yeah — past, sea adventure.", style: 'slow Tohoku farmer voice, warm warm reminiscent delivery carefully' },
      { speaker: 'sho_child', jp: '海底、深いの?', en: "Sea bottom — deep?", style: 'awed child boy voice, soft warm curious delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ようけ深い、潮、湧いてくる、面白い場所や。', en: "Much deep — tide, gushing, interesting place.", style: 'gentle Tohoku voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'カニ、おいしい?', en: "Crab — tasty?", style: 'eager child boy voice, bright warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、ようけ食べた、家族で。', en: "Yeah — much ate, family.", style: 'warm Tohoku farmer voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'いつか、釣りに行きたい!', en: "Someday — fishing want go!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02287',
    context: 'Mei reads a magazine about parenting; talks to Aoi.',
    purpose: 'Two mothers discussing childhood development.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['クセ', '年中', '父母', '思いつく', '視力', '気軽', '尊重', '愛情'],
    cast: ['mei_romantic', 'aoi_barista'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '蒼さん、子供のクセ、年中、悩むよね。', en: "Aoi — child habit, year-round, worry.", style: 'soft young mother voice, warm warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '父母として、思いつくこと、ようけ。', en: "Parents as — thinking, much.", style: 'tender adult woman voice, soft warm reflective delivery carefully' },
      { speaker: 'mei_romantic', jp: '視力の発達、ようけ気になる。', en: "Vision development — much care.", style: 'gentle young woman voice, soft warm caring delivery carefully' },
      { speaker: 'aoi_barista', jp: '気軽に、相談できる人、いて嬉しい。', en: "Casually — consult person, happy.", style: 'warm adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '愛情、ようけ、注いでいきたい。', en: "Love — much, pour.", style: 'tender young mother voice, soft warm committed delivery carefully' },
      { speaker: 'aoi_barista', jp: '子供を尊重しながら、育てるのが大事ね。', en: "Child respect — raise matters.", style: 'soft adult woman voice, warm warm philosophical delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、お互い、頑張ろう!', en: "Yeah — each, try!", style: 'soft committed young mother voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02288',
    context: 'Daichi reads news of a sports match\'s draw; tells Sho.',
    purpose: 'Father sharing match result with son.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['引き分け', '勝負', '応援', '残ら', 'がんばる', '熱心', 'よくよく', '焦っ'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '翔、試合、引き分けやって!', en: "Sho — match, draw!", style: 'soft Kansai father voice, warm warm honest delivery carefully' },
      { speaker: 'sho_child', jp: 'ええ、勝負、決まらんかった?', en: "Eh — match, not decided?", style: 'soft disappointed child boy voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '皆、よくよく、頑張ってたな。', en: "All — well-well, tried.", style: 'warm Kansai father voice, soft warm philosophical delivery carefully' },
      { speaker: 'sho_child', jp: '熱心に、応援しとったのに!', en: "Passionately — cheered though!", style: 'frustrated child boy voice, soft warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '焦らず、次の試合、待とうな。', en: "Without rushing — next match, wait.", style: 'tender Kansai father voice, soft warm patient delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、残らないように、また応援する!', en: "Yeah — not remaining, again cheer!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前の応援、ええ気持ち。', en: "Your cheer — fine feeling.", style: 'tender Kansai father voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02289',
    context: 'Yumiko reads about new tea trends; recommends one to Hina-young.',
    purpose: 'Grandmother sharing tea wisdom with teen.',
    ambient: 'tatami_lamp_quiet',
    sound_effects: [],
    target_vocab: ['折角', '本家', '父母', '伝統', '老舗', '深く', '尊重', '飲む'],
    cast: ['yumiko_mom', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'ひな、本家の老舗、お茶屋さん、知ってる?', en: "Hina — main house old shop, tea, know?", style: 'gentle older mother voice, soft warm informative delivery carefully' },
      { speaker: 'hina_child', jp: '父母から、聞いたことあるかも。', en: "Parents from — heard maybe.", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'yumiko_mom', jp: '折角、伝統、深く感じる場所よ。', en: "Specially — tradition, deeply feel place.", style: 'tender older mother voice, soft warm reverent delivery carefully' },
      { speaker: 'hina_child', jp: '尊重したい、お茶の文化。', en: "Want respect — tea culture.", style: 'soft teen girl voice, warm warm philosophical delivery carefully' },
      { speaker: 'yumiko_mom', jp: '皆さん、ようけ尽くしてはるのよ。', en: "All — much devoted.", style: 'warm older mother voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: '今度、一緒に、飲みに行きたい!', en: "Next — together, drink go!", style: 'bright teen girl voice, soft warm eager delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、約束ね。', en: "Yeah — promise.", style: 'tender older mother voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02290',
    context: 'Ren visits Hiroshi-elder; discusses life lessons quietly.',
    purpose: 'Young man seeking wisdom from elder.',
    ambient: 'tatami_evening_quiet',
    sound_effects: [],
    target_vocab: ['ふつう', '寛容', '反撃', '飾ら', '良き', '深い', '誠意', '心'],
    cast: ['ren_uni', 'hiroshi_elder'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'おとうさん、人生のこと、教えてください。', en: "Otosan — life thing, teach.", style: 'humble young man voice, soft warm respectful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ふつうに、寛容に、生きること。', en: "Yeah — normally, generously, living.", style: 'slow elder Kansai voice, warm warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '反撃せず、誠意で、対応するんですね。', en: "Without retaliating — sincerity, respond.", style: 'soft young man voice, warm warm thoughtful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '飾らん心、ようけ大事や。', en: "Unadorned heart — much matters.", style: 'tender elder Kansai voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: '良き友人、ようけ持ちたいです。', en: "Fine friends — much want hold.", style: 'gentle young man voice, soft warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '深い関わり、必ず生まれるで。', en: "Deep bond — surely born.", style: 'warm elder Kansai voice, soft warm reassuring delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、心、温まる。', en: "Thanks — heart, warm.", style: 'soft tender young man voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02291',
    context: 'Hina-young writes a school essay on family; reflects with Mei.',
    purpose: 'Teen exploring identity with mother.',
    ambient: 'study_lamp_evening',
    sound_effects: [],
    target_vocab: ['父母', 'クセ', '飾ら', '誠意', '尊重', '深く', '寛容', '心'],
    cast: ['mei_romantic', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'メイさん、エッセイ、書いてるんだけど。', en: "Mei — essay, writing.", style: 'soft teen girl voice, warm warm focused delivery carefully' },
      { speaker: 'mei_romantic', jp: '何について?', en: "What about?", style: 'gentle young mother voice, soft warm curious delivery carefully' },
      { speaker: 'hina_child', jp: '父母のこと、書きたい。', en: "Parents about — want write.", style: 'tender teen girl voice, soft warm earnest delivery carefully' },
      { speaker: 'mei_romantic', jp: '飾らずに、誠意持って、書くといいわよ。', en: "Without adorning — sincerity hold, write good.", style: 'warm young mother voice, soft warm wise delivery carefully' },
      { speaker: 'hina_child', jp: '皆のクセ、深く、尊重したい気持ち、伝えたい。', en: "All habits — deeply, respect feeling, want convey.", style: 'soft committed teen girl voice, warm earnest delivery carefully' },
      { speaker: 'mei_romantic', jp: '寛容な視点で、書けば、心に届くわよ。', en: "Generous view — write, heart reach.", style: 'tender young mother voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、頑張る!', en: "Thanks — try!", style: 'bright teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02292',
    context: 'Sakura reads a tabloid headline; brief reaction.',
    purpose: 'Writer reacting to news quickly.',
    ambient: 'cafe_morning_low',
    sound_effects: [],
    target_vocab: ['ヤバイ', 'おそれ', '些細', 'よくよく', '深く', 'がんばる', '皆', '心配'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、見出し、ヤバイね、これ。', en: "Ren — headline, bad, this.", style: 'soft adult writer voice, warm warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: 'おそれ、ようけある報道ですね。', en: "Concern — much exists, report.", style: 'composed young man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '些細なことでも、よくよく見ないと。', en: "Trivial too — well-well must look.", style: 'gentle adult writer voice, soft warm careful delivery carefully' },
      { speaker: 'ren_uni', jp: '深く、本質、読み取りたいですね。', en: "Deeply — essence, want read.", style: 'tender young man voice, soft warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'がんばる人たち、ようけいる、心配。', en: "Trying people — much exist, worry.", style: 'soft adult writer voice, warm warm caring delivery carefully' },
      { speaker: 'ren_uni', jp: '皆、安全に過ごせるといい。', en: "All — safely spend good.", style: 'soft young man voice, warm warm wishful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、記事、深く書きたい。', en: "Yeah — article, deeply want write.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02293',
    context: 'Naoko and Yumiko discuss the weather forecast for a heatwave.',
    purpose: 'Two older women preparing for hot weather.',
    ambient: 'ramen_shop_afternoon',
    sound_effects: [],
    target_vocab: ['熱帯', 'クーラー', '汗', '冷却', '直ぐに', '老人', '気軽', 'ふだん'],
    cast: ['naoko_aunt', 'yumiko_mom'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'お姉さん、熱帯みたいや、最近!', en: "Sister — tropical-like, lately!", style: 'animated Kansai aunt voice, bright warm exasperated delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふだん以上に、汗、ようけかくわね。', en: "Usual above — sweat, much.", style: 'soft older mother voice, warm warm honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'クーラー、直ぐに、入れなあかん。', en: "AC — soon, must put.", style: 'firm Kansai aunt voice, soft warm pragmatic delivery carefully' },
      { speaker: 'yumiko_mom', jp: '冷却、本当に、大事ね。', en: "Cooling — truly, matters.", style: 'tender older mother voice, soft warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: '老人、気軽に、休めるようにせなな。', en: "Elder — casually, rest must.", style: 'warm Kansai aunt voice, soft warm caring delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'お互い、健康、第一ね。', en: "Each — health, first.", style: 'gentle older mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、ちゃんと水、飲もう!', en: "Yeah — properly water, drink!", style: 'animated Kansai aunt voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02294',
    context: 'Kenji and Daichi watch a brief news report; politics talk.',
    purpose: 'Two friends discussing current events.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['党員', '議席', '反撃', '主張', '深く', '我々', '尊重', 'ふつう'],
    cast: ['kenji_office', 'daichi_kansai'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: 'ダイチ、党員、議席、揺れとるな。', en: "Daichi — party member, seat, shaking.", style: 'soft Kansai man voice, warm warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '反撃、主張、ようけあるな、皆。', en: "Counter — argument, much exists, all.", style: 'gentle Kansai husband voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: '深く、考えな、いかんわ。', en: "Deeply — think, must.", style: 'composed Kansai man voice, soft warm philosophical delivery carefully' },
      { speaker: 'daichi_kansai', jp: '我々の声、尊重されてほしい。', en: "Our voice — want respected.", style: 'firm Kansai husband voice, soft warm passionate delivery carefully' },
      { speaker: 'kenji_office', jp: 'ふつうに、議論できる時代がええわ。', en: "Normally — debate-able era fine.", style: 'warm Kansai man voice, soft warm reflective delivery carefully' },
      { speaker: 'daichi_kansai', jp: '皆、平和に過ごしたいだけや。', en: "All — peacefully spend want only.", style: 'soft Kansai husband voice, warm warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ社会、皆で作ろうな。', en: "Fine society — all make.", style: 'tender Kansai man voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02295',
    context: 'Mei takes Hikari (using sho_child as small child) for a beach day.',
    purpose: 'Mother and small child enjoying outdoor.',
    ambient: 'beach_waves_breeze',
    sound_effects: [],
    target_vocab: ['日焼け', '海底', 'カニ', '湧い', '冒険', '海', '熱い', '楽しい'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '翔、海、楽しい?', en: "Sho — sea, fun?", style: 'soft young mother voice, warm warm content delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、ようけ、湧いてる、波!', en: "Yeah — much, gushing, waves!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'mei_romantic', jp: 'カニ、見つけられるかな?', en: "Crab — can find?", style: 'gentle young mother voice, soft warm engaged delivery carefully' },
      { speaker: 'sho_child', jp: '海底、深いね、ちょっと怖い!', en: "Sea bottom — deep, slightly scary!", style: 'awed child boy voice, soft warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '熱い太陽、ようけ気をつけてね。', en: "Hot sun — much careful.", style: 'tender young mother voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: '冒険、最高や!', en: "Adventure — best!", style: 'animated child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '日焼け、しないように、帽子、被って!', en: "Sunburn — not, hat, wear!", style: 'soft caring young mother voice, warm warm protective delivery carefully' },
    ],
  },
  {
    id: 'conv_02296',
    context: 'Sho-young loses a game; Riku-teen consoles him.',
    purpose: 'Older teen comforting younger child after loss.',
    ambient: 'living_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['ケンカ', 'がんばる', '焦っ', 'よくよく', '深く', '残ら', '誉め', '気軽'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '陸くん、勝負、負けた!', en: "Riku — match, lost!", style: 'tearful child boy voice, soft warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: '焦らんでええ、よくよく、考えてみ。', en: "Don't rush — well-well, think.", style: 'soft teen boy voice, warm warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'ケンカみたいに、悔しい!', en: "Quarrel-like — frustrating!", style: 'frustrated child boy voice, bright warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: 'がんばってきたやろ、お前、誉めよ。', en: "Tried — you, praise.", style: 'gentle teen boy voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '深く、悔やんでる。', en: "Deeply — regretting.", style: 'soft tender child boy voice, warm warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: '残らないで、次、頑張ろうな。', en: "Not remaining — next, try.", style: 'warm teen boy voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、気軽に、また、挑戦する!', en: "Yeah — casually, again, challenge!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02297',
    context: 'Aoi and Sakura discuss raising children in modern times.',
    purpose: 'Two adult women on parenting in era.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['好ましい', '時代', '寛容', '思い入れ', '深く', '尽くし', '父母', '年中'],
    cast: ['aoi_barista', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'さくら、今の時代、子育て、好ましい方向?', en: "Sakura — current era, childrearing, favorable direction?", style: 'soft adult woman voice, warm warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: '寛容な父母、ようけ増えてる、感じる。', en: "Generous parents — much increase, feel.", style: 'gentle adult writer voice, soft warm philosophical delivery carefully' },
      { speaker: 'aoi_barista', jp: '思い入れ、深く、ようけ持ってる、皆。', en: "Devotion — deeply, much hold, all.", style: 'tender adult woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'sakura_teen', jp: '尽くしてる父母、たくさん見るね。', en: "Devoting parents — many see.", style: 'soft adult writer voice, warm warm proud delivery carefully' },
      { speaker: 'aoi_barista', jp: '年中、こうやって、子供のため。', en: "Year-round — like this, kid for.", style: 'soft adult woman voice, warm warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お互い、応援していきましょうね。', en: "Each — cheer.", style: 'warm adult writer voice, soft warm united delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、心強い!', en: "Yeah — encouraging!", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02298',
    context: 'Hiroshi-elder watches Sho-young\'s school recital online.',
    purpose: 'Grandfather following grandchild event remotely.',
    ambient: 'tatami_screen_low',
    sound_effects: [],
    target_vocab: ['映像', '誉め', '応援', '深く', '感動', '長年', 'ふだん', '昔'],
    cast: ['hiroshi_elder', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'お姉ちゃん、翔の映像、見えるかな?', en: "Sister — Sho's video, visible?", style: 'slow elder Kansai voice, warm warm engaged delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'はい、ようけ立派!', en: "Yes — much splendid!", style: 'tender older mother voice, soft warm proud delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '深く感動するわ、長年、見てきた孫やから。', en: "Deeply moved — long years, seen grandchild.", style: 'tearful elder Kansai voice, soft warm tender delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふだん通りでも、特別な日ね。', en: "Usual but — special day.", style: 'warm older mother voice, soft warm content delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '昔、お前も、こんな日あったやろ。', en: "Past — you too, day like this.", style: 'soft elder Kansai voice, warm warm reminiscent delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、懐かしい、本当に。', en: "Heh — nostalgic, truly.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '応援、心から、送るで。', en: "Cheer — heart, send.", style: 'warm elder Kansai voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02299',
    context: 'Ren and Hina-young walk through a park after school.',
    purpose: 'Young man and teen sharing casual walk.',
    ambient: 'park_evening_birds',
    sound_effects: [],
    target_vocab: ['芝生', '直ぐに', '匹敵', '気軽', '創り', '愛情', '熱帯', '冒険'],
    cast: ['ren_uni', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '蓮くん、芝生、ようけ広い!', en: "Ren — lawn, much wide!", style: 'soft teen girl voice, warm warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '直ぐに、匹敵する公園、無いですね、ここ。', en: "Soon — matching park, none, here.", style: 'gentle young man voice, soft warm appreciative delivery carefully' },
      { speaker: 'hina_child', jp: '気軽に、来れる場所、嬉しい。', en: "Casually — come place, happy.", style: 'tender teen girl voice, soft warm content delivery carefully' },
      { speaker: 'ren_uni', jp: '創り上げた人、感謝ですね。', en: "Created person — gratitude.", style: 'soft young man voice, warm warm reverent delivery carefully' },
      { speaker: 'hina_child', jp: '愛情、ようけ込められてる気がする。', en: "Love — much contained feel.", style: 'tender teen girl voice, soft warm fond delivery carefully' },
      { speaker: 'ren_uni', jp: '熱帯ぽい木々、冒険的やね。', en: "Tropical-like trees — adventurous.", style: 'warm young man voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、また、来たい!', en: "Yeah — again, want come!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02300',
    context: 'Whole group celebrates Kenji and Aoi\'s wedding anniversary.',
    purpose: 'Multi-voice family celebration of milestone.',
    ambient: 'living_room_celebration_warm',
    sound_effects: [],
    target_vocab: ['結婚', '愛情', '深く', '感謝', '皆', '長年', '幸せ', '心'],
    cast: ['kenji_office', 'aoi_barista', 'mei_romantic', 'sho_child', 'hina_child', 'yumiko_mom'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、結婚、何年やね、もう!', en: "Ken-chan — marriage, how many years, already!", style: 'tender adult woman voice, soft warm fond delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほんま、長年、お互い尽くしてきたな。', en: "Truly — long years, each devoted.", style: 'soft Kansai husband voice, warm warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: '深く愛情、感じる夫婦ね。', en: "Deeply love — feel couple.", style: 'tender young mother voice, soft warm admiring delivery carefully' },
      { speaker: 'sho_child', jp: 'おめでとうございます!', en: "Congrats!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: '心、温まる、皆との時間。', en: "Heart — warm, all time.", style: 'tender teen girl voice, soft warm content delivery carefully' },
      { speaker: 'yumiko_mom', jp: '感謝、ようけ、伝えたいわ。', en: "Gratitude — much, want convey.", style: 'tearful older mother voice, soft warm grateful delivery carefully' },
      { speaker: 'aoi_barista', jp: '皆のおかげで、ここまで来れた。', en: "Thanks to all — came this far.", style: 'tender adult woman voice, soft warm humble delivery carefully' },
      { speaker: 'kenji_office', jp: 'これからも、幸せに、過ごそうな!', en: "Going forward — happily, spend!", style: 'warm Kansai husband voice, soft warm committed delivery carefully' },
      { speaker: 'mei_romantic', jp: '私たちも、応援、ずっとよ。', en: "We too — cheer, always.", style: 'soft young mother voice, warm warm steadfast delivery carefully' },
      { speaker: 'sho_child', jp: 'お祝い、最高!', en: "Celebration — best!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'こんな日、宝物!', en: "Day like this — treasure!", style: 'tender teen girl voice, soft warm grateful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'おばあちゃんも、嬉しい!', en: "Grandma too — happy!", style: 'tender older mother voice, soft warm grateful delivery carefully' },
      { speaker: 'kenji_office', jp: '乾杯やで、皆!', en: "Toast — all!", style: 'animated Kansai husband voice, bright warm cheerful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_115 wrote', CONVERSATIONS.length, 'files');
