import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_122)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02421',
    'TV news desk: Sakura and Ren discuss a minister\'s policy announcement.',
    'WIDENED SCENARIO: news-analysis register; civic/institutional vocabulary in its natural home.',
    'studio_room_tone',
    ['氏', '大臣', '委員', '政策', '行政', '発表'],
    ['sakura_teen', 'ren_uni'], 'Long (13-20)',
    [
      { speaker: 'sakura_teen', jp: '今日、大臣が新しい政策を発表しました。', en: "Today the minister announced a new policy.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '田中氏の説明は、とても具体的でしたね。', en: "Mr. Tanaka's explanation was very concrete.", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'この政策は、行政の負担を減らすそうです。', en: "This policy reportedly reduces the administrative burden.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '委員会でも、長く議論されてきた問題です。', en: "It's an issue the committee long debated.", style: 'thoughtful young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '反対する委員も、いたと聞いています。', en: "I hear some committee members opposed it.", style: 'probing adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'ええ、氏の答弁は慎重でした。', en: "Yes — his responses were cautious.", style: 'careful young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '行政の現場は、どう受け止めるでしょう。', en: "How will the administrative front lines react?", style: 'curious adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '実際の効果は、これから見えてきます。', en: "The real effects will become clear from here.", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '大臣は、来月も会見を開くそうです。', en: "The minister will reportedly hold another briefing next month.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'その政策の続報を、待ちたいですね。', en: "We'll await further news on that policy.", style: 'calm young commentator voice, soft warm analytical reflective throughout' },
      { speaker: 'sakura_teen', jp: '視聴者の皆さん、また明日お伝えします。', en: "Viewers, we'll report again tomorrow.", style: 'warm adult anchor voice, soft warm professional closing throughout' },
    ]),

  C('conv_02422',
    'Economic news: Ren and Yuki review last year\'s industry figures.',
    'WIDENED SCENARIO: economic-report discussion; finance/production vocabulary in natural home.',
    'office_quiet_low',
    ['産業', '金融', '消費', '生産', '昨年', '億'],
    ['ren_uni', 'yuki_office'], 'Long (13-20)',
    [
      { speaker: 'ren_uni', jp: '昨年の産業全体の数字が、出ましたよ。', en: "Last year's overall industry figures are out.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '生産は、どのくらい伸びましたか?', en: "How much did production grow?", style: 'attentive office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: '生産額は、前年より三億ほど増えました。', en: "Output rose by about three hundred million over the prior year.", style: 'precise young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '消費の方は、どうだったんでしょう。', en: "And what about consumption?", style: 'curious office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: '消費は、わずかに落ち込んでいます。', en: "Consumption dipped slightly.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '金融の動きが、影響したんですか?', en: "Did finance trends affect it?", style: 'thoughtful office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: 'ええ、金融市場が不安定でしたから。', en: "Yes — the financial markets were unstable.", style: 'calm young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '今年の見通しは、明るいですか?', en: "Is this year's outlook bright?", style: 'hopeful office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'ren_uni', jp: '産業界は、回復を期待しています。', en: "The industry expects a recovery.", style: 'measured young analyst voice, soft warm professional reflective throughout' },
      { speaker: 'yuki_office', jp: '生産が戻れば、消費も上がりますね。', en: "If production returns, consumption will rise too.", style: 'warm office woman voice, soft warm engaged optimistic throughout' },
      { speaker: 'ren_uni', jp: 'その通りです。来月、また確認しましょう。', en: "Exactly. Let's check again next month.", style: 'agreeable young analyst voice, soft warm professional closing throughout' },
    ]),

  C('conv_02423',
    'Asuka lectures on logic, using formal connectives.',
    'WIDENED SCENARIO: university lecture; formal written-register connectives spoken naturally.',
    'lecture_hall_quiet',
    ['あるいは', 'における', 'に対して', 'これら', 'および'],
    ['asuka_teacher', 'ren_uni'], 'Long (13-20)',
    [
      { speaker: 'asuka_teacher', jp: '今日は、議論における基本を学びます。', en: "Today we study the basics of argument.", style: 'composed teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'asuka_teacher', jp: '主張は、根拠及び理由から成り立ちます。', en: "A claim consists of grounds and reasons.", style: 'composed teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'ren_uni', jp: '根拠が弱いと、どうなりますか?', en: "What happens if the grounds are weak?", style: 'engaged young student voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: 'その主張に対して、反論が出ます。', en: "Counterarguments arise against that claim.", style: 'patient teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'asuka_teacher', jp: '事実、あるいは経験で、支える必要があります。', en: "You must support it with facts or experience.", style: 'patient teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'ren_uni', jp: 'これらを、どう組み合わせるんでしょう。', en: "How do we combine these?", style: 'thoughtful young student voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: 'これらの要素を、順序よく並べます。', en: "We arrange these elements in good order.", style: 'composed teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'asuka_teacher', jp: '読者に対して、丁寧に示すことが大切です。', en: "It's important to present them carefully to the reader.", style: 'composed teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'ren_uni', jp: '文章における順序も、関係しますか?', en: "Does order within the text matter too?", style: 'engaged young student voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、論理及び構成は、切り離せません。', en: "Yes — logic and structure are inseparable.", style: 'warm teacher voice, soft warm measured intellectual encouraging throughout' },
      { speaker: 'ren_uni', jp: 'よく分かりました。練習してみます。', en: "I understand well. I'll practice.", style: 'grateful young student voice, soft warm resolved appreciative throughout' },
    ]),

  C('conv_02424',
    'Quarterly planning meeting: Hiroshi-boss and Yuki, formal business speech.',
    'WIDENED SCENARIO: business meeting; keigo and corporate vocabulary in natural home.',
    'office_quiet_low',
    ['申し上げ', '年度', '対象', 'グループ', 'ポイント'],
    ['hiroshi_boss', 'yuki_office'], 'Long (13-20)',
    [
      { speaker: 'hiroshi_boss', jp: '本年度の計画を、ご説明申し上げます。', en: "I will explain this fiscal year's plan.", style: 'formal boss voice, soft warm composed authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: 'よろしくお願い申し上げます。', en: "Thank you in advance.", style: 'polite office woman voice, soft warm respectful attentive throughout' },
      { speaker: 'hiroshi_boss', jp: '今年度の対象は、若い世代です。', en: "This year's target is the younger generation.", style: 'formal boss voice, soft warm composed authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: 'どのグループに、力を入れますか?', en: "Which group will we focus on?", style: 'attentive office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '都市部のグループを、中心に考えています。', en: "We're centering on the urban group.", style: 'measured boss voice, soft warm composed authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '重要なポイントは、何でしょうか?', en: "What's the key point?", style: 'focused office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '三つのポイントに、絞りました。', en: "I've narrowed it to three points.", style: 'decisive boss voice, soft warm composed authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '対象を広げる予定は、ありますか?', en: "Are there plans to widen the target?", style: 'curious office woman voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '来年度に、検討したいと思います。', en: "I'd like to consider that next fiscal year.", style: 'measured boss voice, soft warm composed authoritative clarity throughout' },
      { speaker: 'yuki_office', jp: '承知しました。資料を準備いたします。', en: "Understood. I'll prepare the materials.", style: 'reliable office woman voice, soft warm respectful resolved throughout' },
    ]),

  C('conv_02425',
    'Tech support: Kenji helps Yuki with new software at work.',
    'WIDENED SCENARIO: workplace tech-help; UI/device vocabulary in natural home.',
    'office_quiet_low',
    ['検索', 'リンク', '表示', '使用', '携帯'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'このソフト、使い方が分からなくて。', en: "I can't figure out how to use this software.", style: 'slightly stuck office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: 'まず、上の検索欄に入力してください。', en: "First, type into the search bar at the top.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '検索したら、結果が出ました。', en: "I searched and got results.", style: 'relieved office woman voice, soft warm engaged delivery throughout' },
      { speaker: 'kenji_office', jp: 'そのリンクを、押してみてください。', en: "Try pressing that link.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'リンクを押すと、画面が変わりますね。', en: "Pressing the link changes the screen.", style: 'observant office woman voice, soft warm engaged delivery throughout' },
      { speaker: 'kenji_office', jp: 'はい、そこに情報が表示されます。', en: "Yes, the information is displayed there.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '携帯からも、使用できますか?', en: "Can I use it from my phone too?", style: 'curious office woman voice, soft warm engaged delivery throughout' },
      { speaker: 'kenji_office', jp: 'ええ、携帯でも同じ画面が表示されます。', en: "Yes, the same screen displays on your phone.", style: 'reassuring office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'これで使用できそうです。ありがとう。', en: "I think I can use it now. Thanks.", style: 'grateful office woman voice, soft warm relieved appreciative throughout' },
    ]),

  C('conv_02426',
    'History documentary discussion: Asuka and Riku on the 20th century.',
    'WIDENED SCENARIO: documentary discussion; country names and history vocabulary in natural home.',
    'living_room_quiet',
    ['アメリカ', 'ドイツ', '中国', '軍', '国家'],
    ['asuka_teacher', 'riku_teen'], 'Long (13-20)',
    [
      { speaker: 'riku_teen', jp: '先生、この番組、戦争の話ですか?', en: "Teacher, is this program about the war?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、二十世紀の国家の歴史ですね。', en: "Yes — the history of nations in the twentieth century.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'ドイツは、どうなったんですか?', en: "What happened to Germany?", style: 'engaged teen boy voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: 'ドイツは、戦後に二つに分かれました。', en: "Germany split in two after the war.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: 'アメリカは、関係していましたか?', en: "Was America involved?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'アメリカの軍も、深く関わっていました。', en: "America's military was deeply involved too.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '中国は、どんな立場でしたか?', en: "What position was China in?", style: 'thoughtful teen boy voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: '中国も、大きな変化を経験しました。', en: "China too went through huge changes.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '軍が、国家を動かしたんですね。', en: "So the military moved the nation.", style: 'reflective teen boy voice, soft warm dawning understanding throughout' },
      { speaker: 'asuka_teacher', jp: 'そうした国家の選択が、今に続いています。', en: "Such national choices continue to today.", style: 'thoughtful teacher voice, soft warm measured reflective clarity throughout' },
      { speaker: 'riku_teen', jp: '歴史って、つながっているんですね。', en: "History really is all connected.", style: 'moved teen boy voice, soft warm quiet realization throughout' },
    ]),

  C('conv_02427',
    'Saito explains a recovery plan to a patient.',
    'WIDENED SCENARIO: medical consultation; clinical vocabulary in its natural home.',
    'clinic_room_quiet',
    ['障害', '精神', '非常', '固定', '男性'],
    ['saito_doctor', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '先生、この症状は重いんでしょうか?', en: "Doctor, is this condition serious?", style: 'worried office man voice, soft warm anxious earnest throughout' },
      { speaker: 'saito_doctor', jp: '機能の障害は、軽い段階です。', en: "The functional impairment is at a mild stage.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: '日常生活に、影響しますか?', en: "Will it affect daily life?", style: 'concerned office man voice, soft warm earnest throughout' },
      { speaker: 'saito_doctor', jp: 'しばらく、腕を固定する必要があります。', en: "You'll need to keep the arm fixed for a while.", style: 'clear doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: '精神的にも、つらくて。', en: "It's mentally hard too.", style: 'vulnerable office man voice, soft warm quiet honesty throughout' },
      { speaker: 'saito_doctor', jp: '精神面の不安は、非常に自然なことです。', en: "Mental anxiety is a very natural thing.", style: 'gentle doctor voice, soft warm reassuring compassionate clarity throughout' },
      { speaker: 'kenji_office', jp: '同じ症状の男性は、多いですか?', en: "Are there many men with the same condition?", style: 'curious office man voice, soft warm earnest throughout' },
      { speaker: 'saito_doctor', jp: '同年代の男性に、よく見られます。', en: "It's often seen in men your age.", style: 'informative doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: '安心しました。指示に従います。', en: "I'm relieved. I'll follow your instructions.", style: 'reassured office man voice, soft warm calmer grateful throughout' },
    ]),

  C('conv_02428',
    'Asuka lectures on the mind and knowledge.',
    'WIDENED SCENARIO: psychology lecture; abstract vocabulary spoken naturally.',
    'lecture_hall_quiet',
    ['知識', '自己', '認識', '明らか', '求め'],
    ['asuka_teacher', 'mei_romantic'], 'Long (13-20)',
    [
      { speaker: 'asuka_teacher', jp: '今日は、自己と認識について話します。', en: "Today we talk about the self and perception.", style: 'composed teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'mei_romantic', jp: '認識って、知識とは違うんですか?', en: "Is perception different from knowledge?", style: 'soft thoughtful woman voice, gentle warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: 'はい。知識は、外から得るものです。', en: "Yes. Knowledge is gained from outside.", style: 'patient teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'asuka_teacher', jp: '認識は、自己の内で起こります。', en: "Perception occurs within the self.", style: 'patient teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'mei_romantic', jp: '自己を知るのは、難しそうですね。', en: "Knowing oneself sounds difficult.", style: 'gentle woman voice, soft warm reflective attentive throughout' },
      { speaker: 'asuka_teacher', jp: '多くの人が、それを求め続けています。', en: "Many people keep seeking it.", style: 'composed teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'mei_romantic', jp: '答えは、明らかになりますか?', en: "Will the answer become clear?", style: 'soft woman voice, gentle warm hopeful attentive throughout' },
      { speaker: 'asuka_teacher', jp: '完全に明らかになることは、稀です。', en: "It rarely becomes fully clear.", style: 'thoughtful teacher voice, soft warm measured intellectual clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'しかし、求める過程に意味があります。', en: "But there's meaning in the act of seeking.", style: 'warm teacher voice, soft warm measured encouraging clarity throughout' },
      { speaker: 'mei_romantic', jp: '知識より、その姿勢が大切なんですね。', en: "So that attitude matters more than knowledge.", style: 'moved woman voice, soft warm quiet realization throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ。自己への問いを、続けてください。', en: "Yes. Keep questioning yourself.", style: 'encouraging teacher voice, soft warm measured gentle clarity throughout' },
    ]),

  C('conv_02429',
    'Media-industry news: Sakura and Ren on a broadcast release.',
    'WIDENED SCENARIO: media news-analysis; broadcast vocabulary in natural home.',
    'studio_room_tone',
    ['放送', '公開', '全国', '登場', 'イメージ'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '新しい番組が、全国で放送されます。', en: "A new program will air nationwide.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '初回の放送は、いつ公開されますか?', en: "When will the first broadcast be released?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '来週、全国で同時に公開されます。', en: "It releases nationwide simultaneously next week.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '新しい司会者が、登場するそうですね。', en: "A new host will reportedly appear.", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、番組のイメージも一新されます。', en: "Yes, the program's image will be renewed too.", style: 'engaged adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '若い視聴者の登場を、狙っていますね。', en: "They're aiming to attract young viewers.", style: 'analytical young commentator voice, soft warm calm insight throughout' },
      { speaker: 'sakura_teen', jp: '放送局も、力を入れているようです。', en: "The station seems to be putting in effort.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '公開後の反応が、楽しみですね。', en: "I look forward to the response after release.", style: 'warm young commentator voice, soft warm anticipatory calm throughout' },
    ]),

  C('conv_02430',
    'Grandpa tells Sho an old tale, using archaic speech.',
    'WIDENED SCENARIO: elder storytelling; archaic negation and old register spoken naturally.',
    'tatami_room_quiet',
    ['ぬ', '無い', 'ほか', 'あまり', '以前'],
    ['goro_grandpa', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'おじいちゃん、昔の話して!', en: "Grandpa, tell me an old story!", style: 'eager small child voice, bright warm excited bouncing delivery throughout' },
      { speaker: 'goro_grandpa', jp: '以前、この村には橋が無かった。', en: "Long ago, this village had no bridge.", style: 'gravelly old man voice, soft warm slow nostalgic delivery throughout' },
      { speaker: 'sho_child', jp: 'えっ、川はどう渡ったの?', en: "Huh, how did they cross the river?", style: 'surprised small child voice, bright warm wide-eyed delivery throughout' },
      { speaker: 'goro_grandpa', jp: '誰も渡れぬ日も、あったものよ。', en: "There were days no one could cross.", style: 'gravelly old man voice, soft warm slow nostalgic delivery throughout' },
      { speaker: 'sho_child', jp: 'ほかに、道は無かったの?', en: "Was there no other path?", style: 'curious small child voice, bright warm earnest delivery throughout' },
      { speaker: 'goro_grandpa', jp: 'ほかの道は、あまり無かったのじゃ。', en: "There weren't many other paths.", style: 'gravelly old man voice, soft warm slow nostalgic delivery throughout' },
      { speaker: 'sho_child', jp: '大変だったんだね。', en: "That was tough, huh.", style: 'sympathetic small child voice, bright warm gentle delivery throughout' },
      { speaker: 'goro_grandpa', jp: '皆で力を合わせ、橋を作ったのじゃ。', en: "Everyone joined forces and built a bridge.", style: 'gravelly old man voice, soft warm proud nostalgic delivery throughout' },
      { speaker: 'sho_child', jp: 'すごい!以前の人は強いね。', en: "Amazing! People back then were strong.", style: 'impressed small child voice, bright warm admiring delivery throughout' },
    ]),

  C('conv_02431',
    'Insurance briefing: Yuki explains a plan to Hiroshi-boss.',
    'WIDENED SCENARIO: civic/insurance explanation; institutional vocabulary in natural home.',
    'office_quiet_low',
    ['保険', '団体', '以下', 'につきまして', '以前'],
    ['yuki_office', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '新しい保険につきまして、ご説明します。', en: "I'll explain about the new insurance.", style: 'polite office woman voice, soft warm professional clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '以前のものと、どう違うのかね?', en: "How does it differ from the previous one?", style: 'measured boss voice, soft warm attentive inquiry throughout' },
      { speaker: 'yuki_office', jp: '対象が、団体まで広がりました。', en: "The coverage now extends to groups.", style: 'clear office woman voice, soft warm professional clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '料金は、以前より高いのかね?', en: "Is the fee higher than before?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'いいえ、以下の通り、据え置きです。', en: "No — as below, it stays the same.", style: 'reassuring office woman voice, soft warm professional clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '団体での加入も、可能なのかね?', en: "Is group enrollment possible too?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'はい、団体につきましても、対応します。', en: "Yes, we accommodate groups as well.", style: 'polite office woman voice, soft warm professional clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'よく分かった。資料を残しておいてくれ。', en: "Understood well. Leave the materials with me.", style: 'satisfied boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02432',
    'Research-findings report: Ren presents a survey to Hiroshi-boss.',
    'WIDENED SCENARIO: formal report; survey/research vocabulary in natural home.',
    'office_quiet_low',
    ['行わ', '行う', '明らか', '一部', '認識'],
    ['ren_uni', 'hiroshi_boss'], 'Long (13-20)',
    [
      { speaker: 'ren_uni', jp: '先月、利用者の調査を行いました。', en: "Last month we conducted a user survey.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'どのように、調査を行ったのかね?', en: "How did you conduct the survey?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'アンケートを、全国で行いました。', en: "We ran a questionnaire nationwide.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '何か、明らかになったことは?', en: "Did anything become clear?", style: 'engaged boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '一部の利用者の不満が、明らかになりました。', en: "Some users' dissatisfaction became clear.", style: 'careful young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'その認識は、社内にもあったのかね?', en: "Did that awareness exist internally too?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '一部の社員は、認識していました。', en: "Some employees were aware of it.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '次は、どんな対策を行うのかね?', en: "What measures will we take next?", style: 'decisive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '改善を、段階的に行う予定です。', en: "We plan to make improvements in stages.", style: 'confident young presenter voice, soft warm professional resolved throughout' },
      { speaker: 'hiroshi_boss', jp: '認識を、社内で共有しておこう。', en: "Let's share this awareness across the company.", style: 'measured boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02433',
    'Asuka teaches essay writing, on formal sentence endings.',
    'WIDENED SCENARIO: writing lecture; formal connectives and endings spoken naturally.',
    'lecture_hall_quiet',
    ['わけ', 'のみ', '限り', 'さて', 'そこで'],
    ['asuka_teacher', 'sakura_teen'], 'Long (13-20)',
    [
      { speaker: 'asuka_teacher', jp: 'さて、今日は文章の結びを学びます。', en: "Now, today we learn how to close an essay.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '結びは、どう書けばいいんですか?', en: "How should I write the conclusion?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '主張を繰り返すだけでは、足りません。', en: "Just repeating your claim isn't enough.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'そこで、新しい視点を一つ加えます。', en: "So, you add one fresh perspective.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'それで、説得力が増すわけですね。', en: "So that's how it gains persuasiveness.", style: 'understanding adult student voice, soft warm engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'その通り。事実のみでは、心が動きません。', en: "Exactly. Facts alone don't move the heart.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '感情も、必要というわけですか。', en: "So emotion is necessary too.", style: 'thoughtful adult student voice, soft warm engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'できる限り、両方を込めてください。', en: "As much as possible, include both.", style: 'encouraging teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '今日のみで、書ける気がします。', en: "I feel I can write just from today's lesson.", style: 'motivated adult student voice, soft warm confident delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'できる限り、たくさん練習してくださいね。', en: "Please practice as much as you can.", style: 'warm teacher voice, soft warm encouraging gentle clarity throughout' },
    ]),

  C('conv_02434',
    'Mom and teen daughter, casual evening chat with conjugated verbs.',
    'Casual home register hitting common conjugated stems naturally.',
    'kitchen_evening_quiet',
    ['しまう', '思わ', '使わ', 'あまり', '彼女'],
    ['yumiko_mom', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'yumiko_mom', jp: 'また遅くまで、起きてしまうの?', en: "Are you staying up late again?", style: 'gentle mother voice, soft warm caring slightly chiding throughout' },
      { speaker: 'sakura_teen', jp: 'うん、つい見てしまうんだよね。', en: "Yeah, I just end up watching.", style: 'sheepish adult daughter voice, soft warm relaxed honest throughout' },
      { speaker: 'yumiko_mom', jp: '目が悪くなるとは、思わないの?', en: "Don't you think your eyes will get worse?", style: 'caring mother voice, soft warm gentle concern throughout' },
      { speaker: 'sakura_teen', jp: 'あまり、考えてなかったかも。', en: "Maybe I hadn't thought about it much.", style: 'reflective adult daughter voice, soft warm honest throughout' },
      { speaker: 'yumiko_mom', jp: 'スマホは、寝る前に使わない方がいいわ。', en: "Better not use your phone before bed.", style: 'gentle mother voice, soft warm caring advising throughout' },
      { speaker: 'sakura_teen', jp: '友達の彼女も、同じこと言ってた。', en: "My friend's girlfriend said the same thing.", style: 'casual adult daughter voice, soft warm relaxed throughout' },
      { speaker: 'yumiko_mom', jp: 'その彼女は、賢いわね。', en: "That girlfriend is wise.", style: 'warm mother voice, soft warm gently approving throughout' },
      { speaker: 'sakura_teen', jp: '今日は、早く寝てしまうことにする。', en: "I'll just go to bed early today.", style: 'resolved adult daughter voice, soft warm yielding affectionate throughout' },
    ]),

  C('conv_02435',
    'Geography documentary: Asuka and Riku on regions and directions.',
    'WIDENED SCENARIO: geography discussion; regional vocabulary in natural home.',
    'living_room_quiet',
    ['県', '全国', '方向', '各', '韓国'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '日本には、県がいくつあるんですか?', en: "How many prefectures does Japan have?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '全国で、四十七の県があります。', en: "Nationwide there are forty-seven prefectures.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '各県に、特色があるんですか?', en: "Does each prefecture have its own character?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、各地の食べ物も違います。', en: "Yes — the food differs by region too.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '韓国も、近いんですよね?', en: "Korea's close too, right?", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'はい、西の方向に、韓国があります。', en: "Yes, Korea lies to the west.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '海を渡る方向で、近い国ですね。', en: "Across the sea, it's a near country.", style: 'reflective teen boy voice, soft warm understanding throughout' },
      { speaker: 'asuka_teacher', jp: '全国を旅すれば、よく分かりますよ。', en: "If you travel the whole country, you'll understand well.", style: 'warm teacher voice, soft warm encouraging gentle clarity throughout' },
    ]),

  C('conv_02436',
    'Business-analyst interview: Sakura interviews about the economy.',
    'WIDENED SCENARIO: journalist interview; commerce vocabulary in natural home.',
    'office_quiet_low',
    ['購入', 'ビジネス', 'ドル', '消費', 'レベル'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '最近、消費の傾向はどうですか?', en: "How are consumption trends lately?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '高額な商品の購入が、増えています。', en: "Purchases of expensive goods are rising.", style: 'measured boss voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: 'ビジネスにも、影響しますか?', en: "Does it affect business too?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'ええ、ビジネスの規模が広がっています。', en: "Yes — the scale of business is expanding.", style: 'professional boss voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: 'ドルの動きも、関係しますか?', en: "Do dollar movements matter too?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'ドルが上がると、購入価格も変わります。', en: "When the dollar rises, purchase prices change too.", style: 'measured boss voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '消費のレベルは、戻りそうですか?', en: "Will consumption levels recover?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '以前のレベルに、近づいています。', en: "It's approaching the previous level.", style: 'reassuring boss voice, soft warm informative closing throughout' },
    ]),

  C('conv_02437',
    'Asuka lectures on philosophy, using formal speculation.',
    'WIDENED SCENARIO: philosophy lecture; literary speculative forms spoken naturally.',
    'lecture_hall_quiet',
    ['あろ', 'つまり', 'その他', '最も', '全て'],
    ['asuka_teacher', 'ren_uni'], 'Long (13-20)',
    [
      { speaker: 'asuka_teacher', jp: '人は、なぜ幸福を求めるのであろうか。', en: "Why might people seek happiness?", style: 'contemplative teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: '幸福とは、何を指すんでしょう?', en: "What does happiness refer to?", style: 'thoughtful young student voice, soft warm curious attentive throughout' },
      { speaker: 'asuka_teacher', jp: 'つまり、満たされた心の状態です。', en: "In short, a state of a fulfilled heart.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: '人によって、違うのではないでしょうか。', en: "Wouldn't it differ from person to person?", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'まさに、それが最も難しい問いです。', en: "Indeed, that's the most difficult question.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'お金、名誉、その他、人は様々を求めます。', en: "Money, honor, and others — people seek many things.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: 'その全てが、幸福なんでしょうか。', en: "Are all of those happiness?", style: 'probing young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '全てが、答えとは限りません。', en: "Not all of them are the answer.", style: 'thoughtful teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'つまり、答えは各自の内にあるのであろう。', en: "In short, the answer likely lies within each of us.", style: 'reflective teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: '考え続けることが、最も大切なんですね。', en: "So continuing to think is most important.", style: 'moved young student voice, soft warm quiet realization throughout' },
    ]),

  C('conv_02438',
    'Data discussion: Kenji and Ren review a dashboard.',
    'WIDENED SCENARIO: data-analysis chat; UI/metrics vocabulary in natural home.',
    'office_quiet_low',
    ['ポイント', 'センター', 'グループ', '検索', 'リンク'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この画面の数字、どう読むんですか?', en: "How do I read the numbers on this screen?", style: 'curious young colleague voice, soft warm engaged earnest throughout' },
      { speaker: 'kenji_office', jp: '各グループの数字が、並んでいます。', en: "Each group's figures are lined up.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: 'どこが、注目のポイントですか?', en: "Where's the point to watch?", style: 'focused young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: 'このグループのポイントが、急に伸びています。', en: "This group's points jumped suddenly.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: '原因を、検索で調べられますか?', en: "Can I look up the cause by searching?", style: 'engaged young colleague voice, soft warm earnest throughout' },
      { speaker: 'kenji_office', jp: 'ええ、検索すると、リンクが出ます。', en: "Yes — search and a link appears.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: 'リンク先は、支援センターですか?', en: "Does the link lead to the support center?", style: 'curious young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: 'はい、センターの資料に、つながります。', en: "Yes, it connects to the center's documents.", style: 'reassuring office man voice, soft warm patient closing throughout' },
    ]),

  C('conv_02439',
    'Political news: Sakura and Ren on a national reform.',
    'WIDENED SCENARIO: political news-analysis; civic vocabulary in natural home.',
    'studio_room_tone',
    ['国家', '政策', '平成', '年度', '行政'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '今年度、大きな改革が始まります。', en: "A major reform begins this fiscal year.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '平成の時代から、議論されてきましたね。', en: "It's been debated since the Heisei era.", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'この政策は、国家の方針を変えます。', en: "This policy changes the nation's direction.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '行政の仕組みも、見直されますか?', en: "Will the administrative system be reviewed too?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、行政の効率化が、目的です。', en: "Yes — administrative efficiency is the goal.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '国家全体に、影響が及びますね。', en: "The effect reaches the whole nation.", style: 'thoughtful young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '今年度の動きに、注目が集まります。', en: "Attention focuses on this fiscal year's moves.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '平成からの課題が、解けるといいですね。', en: "I hope the Heisei-era issues get resolved.", style: 'warm young commentator voice, soft warm hopeful calm throughout' },
    ]),

  C('conv_02440',
    'Casual friends planning a trip, hitting common pronouns and loanwords.',
    'Everyday casual register hitting remaining common stragglers naturally.',
    'cafe_quiet_chatter',
    ['わたし', '彼ら', '他', 'バック', '八'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'わたし、今度の休みに旅行したいな。', en: "I want to travel on my next day off.", style: 'soft warm woman voice, gentle dreamy relaxed delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、わたしも行きたい!', en: "Nice, I want to go too!", style: 'bright barista voice, soft warm cheerful upbeat delivery throughout' },
      { speaker: 'mei_romantic', jp: '他の友達も、誘ってみようか?', en: "Shall we invite other friends too?", style: 'gentle woman voice, soft warm thoughtful inviting delivery throughout' },
      { speaker: 'aoi_barista', jp: '彼らも、きっと喜ぶよ。', en: "They'll surely be happy.", style: 'warm barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '荷物は、小さいバックでいいかな。', en: "A small bag should be fine for luggage.", style: 'soft woman voice, gentle warm practical delivery throughout' },
      { speaker: 'aoi_barista', jp: 'うん、八時の電車に乗ろう。', en: "Yeah, let's catch the eight o'clock train.", style: 'bright barista voice, soft warm planning cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '彼らに、八時って伝えておくね。', en: "I'll tell them eight o'clock.", style: 'gentle woman voice, soft warm reliable delivery throughout' },
      { speaker: 'aoi_barista', jp: '楽しみ!わたし、もう待ちきれない。', en: "Can't wait! I'm so excited.", style: 'excited barista voice, soft warm bubbly delivery throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_122 wrote', CONVERSATIONS.length, 'files');
