import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_084)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01666',
    context: 'Sakura and Ren read the morning newspaper together over breakfast.',
    purpose: 'Two writers discussing news thoughtfully.',
    ambient: 'kitchen_morning_paper',
    sound_effects: [],
    target_vocab: ['新聞', '記事', '報道', '話題'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '今朝の新聞、興味深い記事。', en: "Morning paper — interesting article.", style: 'soft adult writer voice, warm thoughtful delivery carefully' },
      { speaker: 'ren_uni', jp: 'どんな話題ですか?', en: "What's the topic?", style: 'curious young man voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '地方の図書館の取り組みです。', en: "Local library's efforts.", style: 'gentle adult writer voice, soft warm informative delivery carefully' },
      { speaker: 'ren_uni', jp: 'いい報道ですね、地域に根ざして。', en: "Good reporting — grounded.", style: 'soft young man voice, warm appreciative delivery carefully' },
      { speaker: 'sakura_teen', jp: '私たちも、書きたい記事ね。', en: "An article we'd want to write.", style: 'thoughtful adult writer voice, soft warm inspired delivery carefully' },
      { speaker: 'ren_uni', jp: 'いつか、取材できたらいいですね。', en: "Someday — if we could cover it.", style: 'gentle young man voice, soft warm hopeful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、メモしておこう。', en: "Yeah — let's note it.", style: 'soft adult writer voice, warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_01667',
    context: 'Hiroshi-boss and Kenji discuss workplace policy changes at lunch.',
    purpose: 'Two adults engaged in professional policy conversation.',
    ambient: 'cafe_lunch_low',
    sound_effects: [],
    target_vocab: ['制度', '改善', '意見', '議論'],
    cast: ['hiroshi_boss', 'kenji_office'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_boss', jp: '今の制度、改善が必要や。', en: "Current system needs improvement.", style: 'measured boss voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'どの点が、気になりますか?', en: "Which points concern you?", style: 'composed Kansai man voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '若手の意見、取り入れたい。', en: "Want to incorporate young voices.", style: 'soft boss voice, warm thoughtful delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ考えやと思います。', en: "I think that's good.", style: 'warm Kansai man voice, soft supportive delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '議論の場、設けようか。', en: "Shall we set a discussion forum?", style: 'professional boss voice, soft warm collaborative delivery carefully' },
      { speaker: 'kenji_office', jp: '是非、お願いします。', en: "By all means — please.", style: 'soft Kansai man voice, warm respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '一緒に、進めような。', en: "Let's proceed together.", style: 'warm boss voice, soft fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01668',
    context: 'Hina-young asks Asuka about voting in upcoming local elections.',
    purpose: 'Teen seeking civic education from teacher.',
    ambient: 'classroom_after_quiet',
    sound_effects: [],
    target_vocab: ['選挙', '投票', '政治', '関心'],
    cast: ['hina_child', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '先生、選挙、難しいですか?', en: "Teacher — elections, hard?", style: 'curious teen girl voice, soft warm hopeful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '関心を持つ、大切なことよ。', en: "Having interest — that matters.", style: 'gentle teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '投票って、どんな感じですか?', en: "What's voting like?", style: 'soft teen girl voice, warm curious delivery carefully' },
      { speaker: 'asuka_teacher', jp: '自分の声、社会に届けるの。', en: "Your voice reaching society.", style: 'warm teacher voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: 'すごく、責任感じます。', en: "Feel huge responsibility.", style: 'soft teen girl voice, warm honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '政治、身近に感じてね。', en: "Politics — feel it close.", style: 'tender teacher voice, soft warm wise delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、勉強します。', en: "Yes — I'll study.", style: 'soft committed teen girl voice, warm gentle resolve delivered carefully' },
    ],
  },
  {
    id: 'conv_01669',
    context: 'Daichi and Mei watch news together and discuss a story.',
    purpose: 'Married couple discussing current events at home.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['事件', '影響', '心配', '対策'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: 'このニュース、心配ね。', en: "This news — worrying.", style: 'soft young wife voice, warm concerned delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、影響、広がってる。', en: "Yeah — effects spreading.", style: 'soft Kansai husband voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '対策、政府が出すかな。', en: "Will the government act?", style: 'gentle young woman voice, soft warm questioning delivery carefully' },
      { speaker: 'daichi_kansai', jp: '我々も、考えなあかんな。', en: "We also have to think.", style: 'warm Kansai husband voice, soft thoughtful delivery carefully' },
      { speaker: 'mei_romantic', jp: '子供たちの将来、不安。', en: "Kids' future — anxious.", style: 'soft young mother voice, warm honest worried delivery carefully' },
      { speaker: 'daichi_kansai', jp: '俺らで、できることせな。', en: "We must do what we can.", style: 'firm Kansai husband voice, soft warm protective delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、一緒に考えよう。', en: "Yeah — think together.", style: 'tender young wife voice, soft warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_01670',
    context: 'Naoko speaks her mind about a community matter at a meeting.',
    purpose: 'Strong-voiced aunt speaking out at neighborhood council.',
    ambient: 'community_hall_low',
    sound_effects: [],
    target_vocab: ['意見', '反対', '主張', '理由'],
    cast: ['naoko_aunt', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '私、その案には反対や!', en: "I oppose that plan!", style: 'brassy Kansai aunt voice, bright loud assertive delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、理由は何や?', en: "Yeah — what's your reason?", style: 'slow elder Kansai voice, warm measured inquiring delivery carefully' },
      { speaker: 'naoko_aunt', jp: '商店街、衰退するで。', en: "Shopping street — will decline.", style: 'animated Kansai aunt voice, bright loud serious delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'なるほど、ええ視点や。', en: "I see — fine perspective.", style: 'gentle elder Kansai voice, soft warm acknowledging delivery carefully' },
      { speaker: 'naoko_aunt', jp: '若い人にも、声届けるねん。', en: "Reach the young ones too.", style: 'firm Kansai aunt voice, bright loud committed delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おまえの主張、筋通ってる。', en: "Your argument — coherent.", style: 'warm elder Kansai voice, soft approving delivery carefully' },
      { speaker: 'naoko_aunt', jp: '感謝や、聞いてくれて。', en: "Thanks — for listening.", style: 'soft Kansai aunt voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01671',
    context: 'Aoi and Yumiko share quiet conversation about parenting concerns.',
    purpose: 'Two women across generations discussing childrearing fears.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['子育て', '不安', '心配', '愛'],
    cast: ['aoi_barista', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '子育て、毎日不安だらけ。', en: "Childrearing — full of anxiety.", style: 'soft adult woman voice, warm honest vulnerable delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、誰でもそうよ。', en: "Oh — everyone is.", style: 'gentle older mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'aoi_barista', jp: '正解、わからないんです。', en: "No right answer.", style: 'soft adult woman voice, warm searching delivery carefully' },
      { speaker: 'yumiko_mom', jp: '愛を持って、向き合えばいい。', en: "Face them with love — that's enough.", style: 'warm older mother voice, soft tender wise delivery carefully' },
      { speaker: 'aoi_barista', jp: '叱るのも、悩む。', en: "Scolding — also a worry.", style: 'gentle adult woman voice, soft warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '心配する気持ち、伝わるわよ。', en: "Concern — comes through.", style: 'soft older mother voice, warm tender delivery carefully' },
      { speaker: 'aoi_barista', jp: '私も、母みたいになれるかな。', en: "Can I be like my mother?", style: 'soft adult woman voice, warm wistful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'あなた、もう立派なお母さん。', en: "You — already a fine mother.", style: 'tender older mother voice, soft warm assuring delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、心が軽くなった。', en: "Thanks — feels lighter.", style: 'soft adult woman voice, warm grateful tender delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'いつでも、頼ってちょうだい。', en: "Lean on me anytime.", style: 'warm older mother voice, soft loyal delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、頼らせてください。', en: "Yes — I will.", style: 'humble adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'yumiko_mom', jp: '子供たち、幸せそうよ。', en: "Children look happy.", style: 'tender older mother voice, soft warm reassuring delivery carefully' },
      { speaker: 'aoi_barista', jp: 'それが、何よりの励み。', en: "That's the greatest encouragement.", style: 'warm adult woman voice, soft tender grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01672',
    context: 'Ren and Sho-young watch a kids\' nature documentary together.',
    purpose: 'Adult mentor and child experiencing science wonder.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['動物', '自然', '環境', '守る'],
    cast: ['ren_uni', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '蓮にいちゃん、すごい動物!', en: "Ren — amazing animals!", style: 'thrilled child boy voice, bright cheerful warm delivery carefully' },
      { speaker: 'ren_uni', jp: '自然って、不思議だね。', en: "Nature — fascinating.", style: 'soft young man voice, warm awed delivery carefully' },
      { speaker: 'sho_child', jp: '環境、大事にしないと!', en: "Environment — must protect!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: 'うん、君もできること、たくさん。', en: "Yeah — you can do lots.", style: 'gentle young man voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '守る、絶対!', en: "Protect — definitely!", style: 'bright child boy voice, soft warm passionate delivery carefully' },
    ],
  },
  {
    id: 'conv_01673',
    context: 'Saito and Sakura discuss a difficult ethical case from his medical work.',
    purpose: 'Doctor seeking outside perspective on ethical dilemma.',
    ambient: 'cafe_evening_quiet',
    sound_effects: [],
    target_vocab: ['倫理', '判断', '迷う', '尊重'],
    cast: ['saito_doctor', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '今、倫理的な判断に迷ってて。', en: "Stuck on an ethical decision.", style: 'soft doctor voice, warm honest weighted delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どんな状況ですか?', en: "What's the situation?", style: 'gentle adult writer voice, soft warm careful inquiry delivered carefully' },
      { speaker: 'saito_doctor', jp: '本人の意思と家族の意思、違う。', en: "Patient and family wishes differ.", style: 'measured doctor voice, soft warm grave delivery carefully' },
      { speaker: 'sakura_teen', jp: '尊重、難しいですね。', en: "Respect — hard.", style: 'soft adult writer voice, warm understanding delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ええ、どちらも大切で。', en: "Yes — both matter.", style: 'gentle doctor voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '本人の声、聞き続けるしか。', en: "Keep listening to the patient.", style: 'thoughtful adult writer voice, soft warm earnest delivery carefully' },
      { speaker: 'saito_doctor', jp: 'そうですね、ありがとうございます。', en: "Right — thank you.", style: 'soft doctor voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01674',
    context: 'Hiroshi-elder talks to Hina-young about old village customs.',
    purpose: 'Elder passing rural cultural memory to teen.',
    ambient: 'porch_evening_breeze',
    sound_effects: [],
    target_vocab: ['村', '習慣', '昔', '伝える'],
    cast: ['hiroshi_elder', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おじいちゃん、村の話、聞きたい。', en: "Grandpa — village stories, want to hear.", style: 'soft teen girl voice, warm eager delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '昔の村は、ようけ習慣あった。', en: "Old village — many customs.", style: 'slow elder Kansai voice, warm reminiscent delivery carefully' },
      { speaker: 'hina_child', jp: 'どんなものですか?', en: "Like what?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '節分、餅つき、田植え。', en: "Setsubun, mochi pounding, rice planting.", style: 'gentle elder Kansai voice, soft warm listing delivery carefully' },
      { speaker: 'hina_child', jp: '今でも、続いてますか?', en: "Still going today?", style: 'soft teen girl voice, warm interested delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '少しはな、でも減ってる。', en: "Some — but fading.", style: 'soft elder Kansai voice, warm gentle regret delivered carefully' },
      { speaker: 'hina_child', jp: '私、伝えたい、若い人に。', en: "I want to pass on — to young people.", style: 'soft determined teen girl voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_01675',
    context: 'Yuki-office and Kenji discuss workplace pressure and self-care.',
    purpose: 'Two coworkers honestly sharing burnout warning signs.',
    ambient: 'office_quiet_late',
    sound_effects: [],
    target_vocab: ['ストレス', '休む', '相談', '無理'],
    cast: ['yuki_office', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: 'ストレス、ためてる気がする。', en: "Feels like I'm accumulating stress.", style: 'soft office woman voice, warm honest weary delivery carefully' },
      { speaker: 'kenji_office', jp: '無理、しすぎたんちゃう?', en: "Pushing yourself too hard?", style: 'gentle Kansai man voice, soft warm caring delivery carefully' },
      { speaker: 'yuki_office', jp: '休む暇、なくて。', en: "No time to rest.", style: 'tired office woman voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'ちゃんと、相談しような。', en: "Let's talk it through properly.", style: 'warm Kansai man voice, soft caring delivery carefully' },
      { speaker: 'yuki_office', jp: 'うん、ありがとう。', en: "Yeah — thanks.", style: 'soft office woman voice, warm grateful delivery carefully' },
      { speaker: 'kenji_office', jp: '自分、大切にせなあかん。', en: "Must take care of yourself.", style: 'gentle Kansai man voice, soft warm wise delivery carefully' },
      { speaker: 'yuki_office', jp: '今日は、早く帰る。', en: "Today — going home early.", style: 'soft determined office woman voice, warm resolve delivered carefully' },
    ],
  },
  {
    id: 'conv_01676',
    context: 'Riku-teen and Sho-young try a new strategy game together; debate tactics.',
    purpose: 'Two teens engaged in strategy discussion gaming.',
    ambient: 'bedroom_game_low',
    sound_effects: [],
    target_vocab: ['戦略', '勝つ', '考える', '工夫'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '陸くん、どうやって勝つ?', en: "Riku — how to win?", style: 'curious teen boy voice, soft warm eager delivery carefully' },
      { speaker: 'riku_teen', jp: '戦略立ててから、進めや。', en: "Set strategy first — then go.", style: 'casual teen boy voice, soft warm confident delivery carefully' },
      { speaker: 'sho_child', jp: '工夫、必要やな。', en: "Tactics — needed.", style: 'soft teen boy voice, warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: '頭使うゲーム、好きやろ?', en: "Brain games — like 'em?", style: 'bright teen boy voice, soft warm playful delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、考えるの楽しい!', en: "Yeah — thinking's fun!", style: 'thrilled teen boy voice, bright cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01677',
    context: 'Aoi takes Kenji to a community discussion about local arts funding.',
    purpose: 'Couple participating in civic engagement together.',
    ambient: 'community_hall_low',
    sound_effects: [],
    target_vocab: ['芸術', '支援', '地域', '貢献'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '芸術の支援、もっと必要ね。', en: "Arts support — more needed.", style: 'soft adult woman voice, warm engaged earnest delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほんま、若手の活躍、欲しい。', en: "Truly — want young talent flourishing.", style: 'warm Kansai man voice, soft committed delivery carefully' },
      { speaker: 'aoi_barista', jp: '地域として、貢献できないかな。', en: "Can the area contribute?", style: 'gentle adult woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'kenji_office', jp: '今夜、提案してみよか。', en: "Tonight — let's propose.", style: 'soft Kansai man voice, warm decisive delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、一緒に発言しよう。', en: "Yeah — speak together.", style: 'tender adult woman voice, soft warm united delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええな、頼もしいわ。', en: "Lovely — you're reliable.", style: 'warm Kansai man voice, soft fond delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ふふ、頼られて嬉しい。', en: "Heh — happy to be relied on.", style: 'soft adult woman voice, warm tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01678',
    context: 'Mei tells Daichi about a problem at the children\'s school PTA.',
    purpose: 'Married couple discussing family-civic involvement.',
    ambient: 'kitchen_evening_warm',
    sound_effects: [],
    target_vocab: ['学校', '保護者', '問題', '解決'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '保護者会で、問題があるの。', en: "PTA — issue there.", style: 'soft young wife voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'どんな問題や?', en: "What kind?", style: 'warm Kansai husband voice, soft engaged inquiry delivered carefully' },
      { speaker: 'mei_romantic', jp: '行事の運営、揉めてて。', en: "Event-running — disputes.", style: 'troubled young woman voice, soft warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前、どう感じてる?', en: "How do you feel?", style: 'soft Kansai husband voice, warm caring delivery carefully' },
      { speaker: 'mei_romantic', jp: 'みんなの意見、聞きたい。', en: "Want to hear everyone's voice.", style: 'gentle young woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええ姿勢や、応援するで。', en: "Good stance — I'll support.", style: 'warm Kansai husband voice, soft proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'tender young wife voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01679',
    context: 'Naoko and Mrs. Mori watch a debate show; cheering loudly for one side.',
    purpose: 'Two older women engaging civically with media.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['討論', '主張', '番組', '面白い'],
    cast: ['naoko_aunt', 'mrs_mori_neighbor'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'うわ、討論、面白いやん!', en: "Whoa — debate's fun!", style: 'brassy Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'うん、主張がはっきりしてるわ。', en: "Yes — claims are clear.", style: 'warm older neighbor voice, soft engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'こっちの人、応援するで!', en: "Cheering this side!", style: 'animated Kansai aunt voice, bright loud passionate delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふふ、熱中するわね。', en: "Heh — really into it.", style: 'gentle older woman voice, soft warm teasing delivery carefully' },
      { speaker: 'naoko_aunt', jp: '当たり前や、関心ある話題!', en: "Of course — topic of interest!", style: 'bright Kansai aunt voice, loud cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01680',
    context: 'Tatsuya-country reflects with Asuka about the village population decline.',
    purpose: 'Older married couple discussing rural community concern.',
    ambient: 'porch_winter_evening',
    sound_effects: [],
    target_vocab: ['人口', '減る', '故郷', '未来'],
    cast: ['tatsuya_country', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '村の人口、また減ったな。', en: "Village population — dropped again.", style: 'soft Tohoku voice, warm honest concerned delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ええ、寂しくなるね。', en: "Yes — gets lonely.", style: 'warm teacher voice, soft tender delivery carefully' },
      { speaker: 'tatsuya_country', jp: '若い人、街へ出ていく。', en: "Young ones — leaving for cities.", style: 'gentle Tohoku farmer voice, soft warm resigned delivery carefully' },
      { speaker: 'asuka_teacher', jp: '故郷、守りたいね。', en: "Want to protect our home.", style: 'soft teacher voice, warm reflective delivery carefully' },
      { speaker: 'tatsuya_country', jp: '未来、どうしたらええか。', en: "Future — what to do.", style: 'soft Tohoku voice, warm worried honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '一緒に、考えていこう。', en: "Let's think together.", style: 'tender teacher voice, soft warm united delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、お前と一緒なら、心強い。', en: "Yeah — with you, encouraged.", style: 'warm Tohoku farmer voice, soft tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01681',
    context: 'Hiroshi-boss invites Sho-young to bring-your-child-to-work day briefly.',
    purpose: 'Authority figure showing child working world warmly.',
    ambient: 'office_quiet_window',
    sound_effects: [],
    target_vocab: ['会社', '仕事', '社長', '見学'],
    cast: ['hiroshi_boss', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '社長、会社、広い!', en: "Boss — company's huge!", style: 'awed child boy voice, bright warm delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'おう、ここで皆、仕事しとる。', en: "Yeah — everyone works here.", style: 'warm boss voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: '何の仕事ですか?', en: "What kind of work?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '人を笑顔にする仕事や。', en: "Work that makes people smile.", style: 'soft boss voice, warm tender delivery carefully' },
      { speaker: 'sho_child', jp: 'いいなぁ、僕もしたい!', en: "Lovely — I want to too!", style: 'thrilled child boy voice, bright warm eager delivery carefully' },
    ],
  },
  {
    id: 'conv_01682',
    context: 'Sakura and Ren collaborate on writing a community newsletter.',
    purpose: 'Two writers volunteering creative skill for community.',
    ambient: 'study_room_lamp',
    sound_effects: [],
    target_vocab: ['記事', '編集', '内容', '発行'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '今号の記事、どの順番にする?', en: "This issue — what article order?", style: 'thoughtful adult writer voice, soft warm collaborative delivery carefully' },
      { speaker: 'ren_uni', jp: '地域の話題、最初がいいかな。', en: "Local topics — first, I'd think.", style: 'soft young man voice, warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '内容、もう一度確認しよう。', en: "Content — let's check again.", style: 'gentle adult writer voice, soft warm careful delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、校正しますね。', en: "Yes — I'll proof.", style: 'composed young man voice, soft warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '発行、今週末ね。', en: "Publication — this weekend.", style: 'soft adult writer voice, warm determined delivery carefully' },
      { speaker: 'ren_uni', jp: '間に合わせます、大丈夫。', en: "I'll make it — no worries.", style: 'soft young man voice, warm reassuring delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとう、本当に助かる。', en: "Thanks — truly helpful.", style: 'tender adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01683',
    context: 'Yumiko gently helps Hiroshi-elder draft a letter to a far-away relative.',
    purpose: 'Wife helping elder husband with personal correspondence.',
    ambient: 'tatami_room_quiet',
    sound_effects: [],
    target_vocab: ['手紙', '宛先', '言葉', '届く'],
    cast: ['yumiko_mom', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '従兄弟に、手紙書きたい。', en: "Want to write to cousin.", style: 'slow elder Kansai voice, warm tender delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、私、手伝うわよ。', en: "Yes — I'll help.", style: 'gentle older mother voice, soft warm delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '宛先、思い出せん。', en: "Address — can't recall.", style: 'soft elder Kansai voice, warm honest delivery carefully' },
      { speaker: 'yumiko_mom', jp: '住所帳、見ましょう。', en: "Let's check the address book.", style: 'warm older mother voice, soft practical delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '言葉、何書いたらええかな。', en: "Words — what should I write?", style: 'soft elder Kansai voice, warm uncertain delivery carefully' },
      { speaker: 'yumiko_mom', jp: '心、そのまま書けば届くわ。', en: "Heart — write as it is, will reach.", style: 'tender older mother voice, soft warm wise delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、おまえの言う通りや。', en: "Yeah — you're right.", style: 'warm elder Kansai voice, soft grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01684',
    context: 'Kenji and Ren visit a small art exhibit; debate over a piece.',
    purpose: 'Two artists discussing aesthetics in gallery.',
    ambient: 'gallery_quiet_floor',
    sound_effects: [],
    target_vocab: ['作品', '評価', '感じる', '意見'],
    cast: ['kenji_office', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: 'この作品、評価分かれそう。', en: "This piece — opinions may split.", style: 'soft young man voice, warm thoughtful delivery carefully' },
      { speaker: 'kenji_office', jp: '俺は、ええと感じる。', en: "I feel it's good.", style: 'soft Kansai artist voice, warm honest delivery carefully' },
      { speaker: 'ren_uni', jp: '僕は、もう一歩欲しい。', en: "I want a step more.", style: 'gentle young man voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ意見の違いや。', en: "Fine difference of opinion.", style: 'warm Kansai man voice, soft fond respectful delivery carefully' },
      { speaker: 'ren_uni', jp: '面白いですね、議論。', en: "Interesting — discussion.", style: 'soft young man voice, warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: '美術は、人それぞれや。', en: "Art — each their own.", style: 'gentle Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: 'なるほど、勉強になります。', en: "I see — I'm learning.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01685',
    context: 'Group at a community meeting deciding on a town festival plan; many voices.',
    purpose: 'Multiple voices brainstorming community event details.',
    ambient: 'community_hall_busy',
    sound_effects: [],
    target_vocab: ['祭り', '計画', '協力', '皆', '実現'],
    cast: ['naoko_aunt', 'hiroshi_elder', 'aoi_barista', 'kenji_office', 'sakura_teen', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '今年の祭り、盛大にやろや!', en: "This year's festival — go big!", style: 'brassy Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '伝統、守りながらな。', en: "While keeping tradition.", style: 'slow elder Kansai voice, warm wise delivery carefully' },
      { speaker: 'aoi_barista', jp: '若い人も、参加しやすいように。', en: "Easy for young people to join.", style: 'soft adult woman voice, warm thoughtful delivery carefully' },
      { speaker: 'kenji_office', jp: '音楽部隊、誘ってみよか。', en: "Invite the music team?", style: 'warm Kansai man voice, soft fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '記録、私が取りますね。', en: "I'll take records.", style: 'composed adult writer voice, soft warm helpful delivery carefully' },
      { speaker: 'mei_romantic', jp: '子供たちの出し物も、考えたい。', en: "Want to plan kids' performances too.", style: 'gentle young mother voice, soft warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: '皆で協力したら、できる!', en: "If we all cooperate — possible!", style: 'animated Kansai aunt voice, bright loud confident delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '実現、楽しみやな。', en: "Realization — looking forward.", style: 'gentle elder Kansai voice, soft warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: '宣伝、SNSで広めるね。', en: "Promote via social media.", style: 'soft adult woman voice, warm practical delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ役割分担や!', en: "Fine division of roles!", style: 'warm Kansai man voice, soft cheerful delivery carefully' },
      { speaker: 'sakura_teen', jp: '一緒に、いいもの作りましょう。', en: "Let's make something fine together.", style: 'gentle adult writer voice, soft warm inspired delivery carefully' },
      { speaker: 'mei_romantic', jp: 'みんなのおかげで、形になる。', en: "Thanks to everyone — taking shape.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'よっしゃ、これで決まりや!', en: "All right — decided!", style: 'animated Kansai aunt voice, bright loud cheerful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_084 wrote', CONVERSATIONS.length, 'files');
