import fs from 'node:fs'; import path from 'node:path'; import url from 'node:url';
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_166)', generated_at: NOW, source_plan_row: '' });
const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 3, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // ===== CLUSTER A: championship sports =====
  C('conv_03301', 'Friends watch a league-deciding match', 'Watch a championship; teach リーグ/女子/統計/勝利/予測/唯一/チャンス/復活', 'living_room_quiet',
    ['リーグ','女子','統計','勝利','予測','唯一','チャンス','復活'], ['riku_teen', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: 'いよいよリーグ優勝がかかった試合だね。', en: 'Finally, a match with the league title on the line.', style: 'hyped fan leaning into the big game' },
    { speaker: 'ren_uni', jp: '今シーズン、女子チームの快進撃がすごい。', en: 'This season the women’s team’s run is incredible.', style: 'impressed fan praising the squad' },
    { speaker: 'riku_teen', jp: '統計を見ると、得点力が一番高いんだ。', en: 'By the statistics, their scoring is the highest.', style: 'data-savvy fan citing the numbers' },
    { speaker: 'sakura_teen', jp: '専門家は、どっちの勝利を予測してるの？', en: 'Which side’s victory do the experts predict?', style: 'curious newcomer asking eagerly' },
    { speaker: 'ren_uni', jp: '接戦になるって予測が多いよ。', en: 'Most predictions say it’ll be close.', style: 'fan summarizing the consensus' },
    { speaker: 'riku_teen', jp: 'あのエースが、唯一の得点源だからね。', en: 'That ace is their sole scoring source.', style: 'fan highlighting the key player' },
    { speaker: 'sakura_teen', jp: '今がチャンス！ 攻めてる！', en: 'Now’s the chance! They’re attacking!', style: 'excited newcomer caught up in the play' },
    { speaker: 'ren_uni', jp: '去年最下位からの復活、感動的だね。', en: 'A comeback from last place last year — moving.', style: 'moved fan appreciating the arc' },
  ]),
  C('conv_03302', 'Breaking down the match afterward', 'Analyze the result; teach 勝利/リーグ/女子/チャンス/統計/予測/復活/唯一', 'living_room_quiet',
    ['勝利','リーグ','女子','チャンス','統計','予測','復活','唯一'], ['ren_uni', 'riku_teen', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '見事な勝利だったね！', en: 'What a splendid victory!', style: 'elated fan savoring the win' },
    { speaker: 'riku_teen', jp: 'リーグ首位に返り咲いた。', en: 'They reclaimed first in the league.', style: 'proud fan noting the standing' },
    { speaker: 'sakura_teen', jp: '女子チームの結束が光ってた。', en: 'The women’s team’s unity shone.', style: 'admiring fan praising teamwork' },
    { speaker: 'ren_uni', jp: '後半のチャンスを確実に決めたのが大きい。', en: 'Converting the second-half chance was huge.', style: 'analytical fan pinpointing the turning point' },
    { speaker: 'riku_teen', jp: '統計でも、決定力が際立ってる。', en: 'In the statistics, their finishing stands out.', style: 'data-minded fan backing it up' },
    { speaker: 'sakura_teen', jp: '解説者の予測、当たったね。', en: 'The commentator’s prediction was right.', style: 'pleased newcomer noting the call' },
    { speaker: 'ren_uni', jp: '怪我から復活した選手が、唯一無二の活躍。', en: 'The player back from injury was peerless.', style: 'fan celebrating a standout comeback' },
  ]),
  C('conv_03303', 'Interviewing the winning player', 'Interview a champion; teach 復活/勝利/女子/リーグ/チャンス/統計/予測/唯一', 'studio_room_tone',
    ['復活','勝利','女子','リーグ','チャンス','統計','予測','唯一'], ['sakura_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '優勝おめでとうございます！ 今の気持ちは？', en: 'Congrats on the title! How do you feel now?', style: 'upbeat interviewer opening warmly' },
    { speaker: 'ren_uni', jp: '最高です。チーム復活の勝利ですから。', en: 'The best. It’s a victory of the team’s revival.', style: 'elated player overflowing with joy' },
    { speaker: 'sakura_teen', jp: '女子リーグでの連覇、狙えますか？', en: 'Can you aim for back-to-back women’s league titles?', style: 'interviewer pressing for ambition' },
    { speaker: 'ren_uni', jp: 'もちろん、チャンスは必ずものにします。', en: 'Of course, I’ll seize every chance.', style: 'confident player vowing determination' },
    { speaker: 'sakura_teen', jp: 'データや統計も活用しているんですか？', en: 'Do you use data and statistics too?', style: 'interviewer probing the method' },
    { speaker: 'ren_uni', jp: 'ええ、相手の動きを予測する材料にしています。', en: 'Yes, as material to predict opponents’ moves.', style: 'thoughtful player explaining his edge' },
    { speaker: 'sakura_teen', jp: 'あなたは、唯一無二の存在ですね。', en: 'You’re truly one of a kind.', style: 'admiring interviewer closing the praise' },
  ]),
  C('conv_03304', 'Discussing the season’s statistics', 'Talk season stats; teach リーグ/統計/勝利/女子/予測/チャンス/唯一/復活', 'living_room_quiet',
    ['リーグ','統計','勝利','女子','予測','チャンス','唯一','復活'], ['riku_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: '今季のリーグ、統計がすごく面白い。', en: 'This season’s league statistics are fascinating.', style: 'data-loving fan diving in' },
    { speaker: 'ren_uni', jp: 'どのチームが勝利数トップ？', en: 'Which team has the most victories?', style: 'curious fan asking the leaderboard' },
    { speaker: 'riku_teen', jp: '女子リーグはうちが一位だよ。', en: 'In the women’s league, we’re first.', style: 'proud fan reporting the standing' },
    { speaker: 'ren_uni', jp: '来季の順位、予測できる？', en: 'Can you predict next season’s ranking?', style: 'fan inviting speculation' },
    { speaker: 'riku_teen', jp: '難しいな。チャンスは全チームにある。', en: 'Hard to say. Every team has a chance.', style: 'measured fan hedging fairly' },
    { speaker: 'ren_uni', jp: '唯一、絶対王者と言える存在はいないね。', en: 'There’s no single undisputed champion.', style: 'fan noting the parity' },
    { speaker: 'riku_teen', jp: '昨季の最下位チームの復活もあり得る。', en: 'Last season’s bottom team could revive too.', style: 'optimistic fan imagining an upset' },
  ]),
  C('conv_03305', 'Fans celebrate the championship', 'Celebrate the title; teach 勝利/リーグ/女子/チャンス/統計/予測/唯一/復活', 'living_room_quiet',
    ['勝利','リーグ','女子','チャンス','統計','予測','唯一','復活'], ['sakura_teen', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: 'ついに優勝！ 最高の勝利だったね。', en: 'Champions at last! The greatest victory.', style: 'jubilant fan bursting with joy' },
    { speaker: 'riku_teen', jp: 'リーグ全体が盛り上がった一年だった。', en: 'The whole league buzzed all year.', style: 'satisfied fan reflecting happily' },
    { speaker: 'sakura_teen', jp: '女子スポーツの人気も上がってるよね。', en: 'Women’s sports popularity is rising too.', style: 'observant fan noting the trend' },
    { speaker: 'riku_teen', jp: 'あのチャンスを決めた瞬間、鳥肌立った。', en: 'When that chance went in, I got chills.', style: 'thrilled fan reliving the moment' },
    { speaker: 'sakura_teen', jp: '統計的にも、歴史的な記録らしいよ。', en: 'Statistically, it’s a historic record too.', style: 'informed fan adding context' },
    { speaker: 'riku_teen', jp: '誰も予測できなかった展開だった。', en: 'Nobody could have predicted this turn.', style: 'awed fan marveling at it' },
    { speaker: 'sakura_teen', jp: 'まさに、唯一無二のシーズン。', en: 'Truly a one-of-a-kind season.', style: 'fan summing it up fondly' },
    { speaker: 'riku_teen', jp: '弱小から強豪への復活、物語みたいだね。', en: 'A revival from weak to strong, like a story.', style: 'fan ending on a wistful note' },
  ]),

  // ===== CLUSTER B: world-geography / nature documentary =====
  C('conv_03306', 'Watching a documentary on the Amazon', 'Discuss a nature film; teach ブラジル/人類/領域/訪れ/周囲/高度/オーストラリア/台湾', 'living_room_quiet',
    ['ブラジル','人類','領域','訪れ','周囲','高度','オーストラリア','台湾'], ['asuka_teacher', 'sakura_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '今日はブラジルのアマゾンを特集します。', en: 'Today we feature Brazil’s Amazon.', style: 'engaging teacher introducing the topic' },
    { speaker: 'sakura_teen', jp: '人類がまだ知らない領域も多いんですよね。', en: 'There are many domains humanity still doesn’t know.', style: 'curious teen marveling at the unknown' },
    { speaker: 'asuka_teacher', jp: 'ええ、未開の地を訪れる探検隊もいます。', en: 'Yes, expeditions visit untouched lands.', style: 'teacher adding a vivid detail' },
    { speaker: 'ren_uni', jp: '周囲を見渡す限り、緑の海ですね。', en: 'As far as the surroundings stretch, a sea of green.', style: 'awed student describing the view' },
    { speaker: 'asuka_teacher', jp: '高度の高い場所から撮影しています。', en: 'They film from high altitude.', style: 'teacher noting the technique' },
    { speaker: 'sakura_teen', jp: 'オーストラリアの砂漠とは全然違いますね。', en: 'Totally different from Australia’s deserts.', style: 'teen drawing a comparison' },
    { speaker: 'ren_uni', jp: '次回は台湾の山岳地帯だそうです。', en: 'Next time is Taiwan’s mountains, apparently.', style: 'student previewing the next episode' },
  ]),
  C('conv_03307', 'Discussing biodiversity and conservation', 'Talk conservation; teach ブラジル/領域/人類/周囲/高度/台湾/オーストラリア/訪れ', 'living_room_quiet',
    ['ブラジル','領域','人類','周囲','高度','台湾','オーストラリア','訪れ'], ['ren_uni', 'asuka_teacher', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: 'ブラジルには、未知の生物がたくさんいるんですね。', en: 'Brazil has so many unknown creatures.', style: 'fascinated student grasping the scale' },
    { speaker: 'asuka_teacher', jp: 'ええ、研究の領域はまだ広大です。', en: 'Yes, the research domain is still vast.', style: 'teacher conveying the open frontier' },
    { speaker: 'sakura_teen', jp: '人類の活動が、周囲の自然を脅かしてます。', en: 'Human activity threatens the surrounding nature.', style: 'concerned teen voicing the issue' },
    { speaker: 'asuka_teacher', jp: '高度な保護技術が求められています。', en: 'Advanced conservation technology is needed.', style: 'teacher prescribing a solution' },
    { speaker: 'ren_uni', jp: '台湾でも似た取り組みがあるとか。', en: 'Taiwan reportedly has similar efforts.', style: 'student adding a parallel' },
    { speaker: 'sakura_teen', jp: 'オーストラリアの森林火災も深刻でしたね。', en: 'Australia’s wildfires were severe too.', style: 'teen recalling a grim example' },
    { speaker: 'asuka_teacher', jp: '多くの研究者が現地を訪れて調査しています。', en: 'Many researchers visit the sites to study them.', style: 'teacher noting the fieldwork' },
  ]),
  C('conv_03308', 'A student interviews a world traveler', 'Interview a traveler; teach ブラジル/人類/領域/訪れ/高度/台湾/オーストラリア/周囲', 'studio_room_tone',
    ['ブラジル','人類','領域','訪れ','高度','台湾','オーストラリア','周囲'], ['sakura_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '世界を旅して、どこが一番印象的でしたか？', en: 'Traveling the world, where impressed you most?', style: 'curious interviewer opening broadly' },
    { speaker: 'ren_uni', jp: 'ブラジルの大自然は、人類の小ささを感じました。', en: 'Brazil’s wild nature made me feel humanity’s smallness.', style: 'reflective traveler sharing awe' },
    { speaker: 'sakura_teen', jp: '危険な領域にも足を運んだんですか？', en: 'Did you venture into dangerous domains too?', style: 'intrigued interviewer probing' },
    { speaker: 'ren_uni', jp: 'ええ、ガイドと一緒に訪れました。', en: 'Yes, I visited with a guide.', style: 'traveler recounting carefully' },
    { speaker: 'sakura_teen', jp: '高度の高い山にも登ったとか。', en: 'You climbed high-altitude mountains too?', style: 'impressed interviewer following up' },
    { speaker: 'ren_uni', jp: '台湾の玉山にも登りましたよ。', en: 'I climbed Taiwan’s Yushan too.', style: 'traveler adding a proud detail' },
    { speaker: 'sakura_teen', jp: 'オーストラリアはどうでしたか？', en: 'How was Australia?', style: 'interviewer steering to the next place' },
    { speaker: 'ren_uni', jp: '周囲に何もない砂漠が、忘れられません。', en: 'The desert with nothing around is unforgettable.', style: 'traveler recalling a vivid memory' },
  ]),
  C('conv_03309', 'A geography lesson on the southern hemisphere', 'Teach geography; teach ブラジル/オーストラリア/領域/台湾/訪れ/人類/周囲/高度', 'lecture_hall_quiet',
    ['ブラジル','オーストラリア','領域','台湾','訪れ','人類','周囲','高度'], ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '今日は南半球の国々を学びます。', en: 'Today we study southern-hemisphere countries.', style: 'organized teacher setting the lesson' },
    { speaker: 'sakura_teen', jp: 'ブラジルとオーストラリア、両方とも広いですね。', en: 'Brazil and Australia are both vast.', style: 'engaged teen noting the scale' },
    { speaker: 'asuka_teacher', jp: 'ええ、それぞれ独自の文化領域を持っています。', en: 'Yes, each has its own cultural domain.', style: 'teacher highlighting distinctiveness' },
    { speaker: 'sakura_teen', jp: '台湾は日本に近いですよね。', en: 'Taiwan is close to Japan, right?', style: 'teen connecting to the familiar' },
    { speaker: 'asuka_teacher', jp: '多くの観光客が毎年訪れます。', en: 'Many tourists visit every year.', style: 'teacher adding a relatable fact' },
    { speaker: 'sakura_teen', jp: '人類の移動の歴史って面白いですね。', en: 'The history of human migration is fascinating.', style: 'thoughtful teen widening the lens' },
    { speaker: 'asuka_teacher', jp: '周囲の海が、文化交流を支えてきました。', en: 'The surrounding seas have supported cultural exchange.', style: 'teacher offering a unifying idea' },
    { speaker: 'sakura_teen', jp: '高度経済成長を遂げた地域も多いんですね。', en: 'Many regions achieved rapid economic growth too.', style: 'teen connecting to economics' },
  ]),
  C('conv_03310', 'Wrapping up the documentary series', 'Reflect on the series; teach ブラジル/台湾/人類/領域/周囲/オーストラリア/訪れ/高度', 'living_room_quiet',
    ['ブラジル','台湾','人類','領域','周囲','オーストラリア','訪れ','高度'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: 'このシリーズ、世界の見方が変わりました。', en: 'This series changed how I see the world.', style: 'moved student reflecting sincerely' },
    { speaker: 'asuka_teacher', jp: 'ブラジルから台湾まで、幅広く扱いましたね。', en: 'We covered widely, from Brazil to Taiwan.', style: 'teacher summarizing the scope' },
    { speaker: 'ren_uni', jp: '人類共通の課題も見えてきました。', en: 'Shared challenges of humanity came into view too.', style: 'student articulating the takeaway' },
    { speaker: 'asuka_teacher', jp: '環境問題は、国の領域を越えています。', en: 'Environmental issues cross national domains.', style: 'teacher stressing the global stakes' },
    { speaker: 'ren_uni', jp: '周囲の人にも、この番組を勧めたいです。', en: 'I want to recommend this show to those around me.', style: 'enthusiastic student spreading the word' },
    { speaker: 'asuka_teacher', jp: 'オーストラリアの回が特に好評でした。', en: 'The Australia episode was especially popular.', style: 'teacher sharing audience feedback' },
    { speaker: 'ren_uni', jp: 'いつか実際に訪れてみたいです。', en: 'Someday I want to actually visit.', style: 'dreaming student looking ahead' },
    { speaker: 'asuka_teacher', jp: '高度な映像技術のおかげで、臨場感がありましたね。', en: 'Thanks to advanced imaging, it felt immersive.', style: 'teacher crediting the production' },
  ]),

  // ===== CLUSTER C: civics & public administration =====
  C('conv_03311', 'A civics lecture on political parties', 'Explain parties; teach 自民党/見解/公務員/把握/連合/趣旨/児童/又は', 'lecture_hall_quiet',
    ['自民党','見解','公務員','把握','連合','趣旨','児童','又は'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '今日は政党の役割を学びます。', en: 'Today we learn the role of political parties.', style: 'organized teacher opening the unit' },
    { speaker: 'ren_uni', jp: '自民党は、長く与党を務めてきましたね。', en: 'The LDP has long been the ruling party.', style: 'informed student stating a fact' },
    { speaker: 'asuka_teacher', jp: 'ええ、政府の見解は政策に反映されます。', en: 'Yes, the government’s views shape policy.', style: 'teacher explaining the linkage' },
    { speaker: 'sakura_teen', jp: '公務員は、その政策を実行するんですね。', en: 'Civil servants carry out that policy.', style: 'teen connecting the roles' },
    { speaker: 'asuka_teacher', jp: 'そうです。現場の状況を把握する力が要ります。', en: 'Right. Grasping the field situation is essential.', style: 'teacher stressing a key skill' },
    { speaker: 'ren_uni', jp: '労働組合の連合も、政治に影響しますか？', en: 'Do labor-union federations affect politics too?', style: 'student probing another actor' },
    { speaker: 'asuka_teacher', jp: 'ええ。法案の趣旨を理解することが大切です。', en: 'Yes. Understanding a bill’s intent matters.', style: 'teacher emphasizing comprehension' },
    { speaker: 'sakura_teen', jp: '児童福祉のような分野も、議論されますよね。', en: 'Fields like child welfare are debated too, right?', style: 'teen widening the scope' },
    { speaker: 'asuka_teacher', jp: '支援の対象は、低所得世帯又は単身家庭などです。', en: 'Recipients are low-income or single-person households, etc.', style: 'teacher giving a precise example' },
  ]),
  C('conv_03312', 'Discussing a new childcare policy', 'Discuss a policy; teach 自民党/児童/見解/連合/公務員/把握/趣旨/又は', 'living_room_quiet',
    ['自民党','児童','見解','連合','公務員','把握','趣旨','又は'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '新しい子育て支援、自民党が推進してるんですよね。', en: 'The LDP is pushing the new childcare support, right?', style: 'informed student raising the topic' },
    { speaker: 'asuka_teacher', jp: 'ええ、児童手当の拡充が柱です。', en: 'Yes, expanding the child allowance is the pillar.', style: 'teacher summarizing the core' },
    { speaker: 'ren_uni', jp: '野党の見解はどうなんですか？', en: 'What’s the opposition’s view?', style: 'student seeking the other side' },
    { speaker: 'asuka_teacher', jp: '連合や各団体も意見を出しています。', en: 'Federations and groups have weighed in too.', style: 'teacher noting the stakeholders' },
    { speaker: 'ren_uni', jp: '公務員の負担も増えそうですね。', en: 'Civil servants’ burden seems set to grow too.', style: 'student anticipating a consequence' },
    { speaker: 'asuka_teacher', jp: '現場が実態を把握しないと、制度は機能しません。', en: 'If the field doesn’t grasp reality, the system fails.', style: 'teacher stressing implementation' },
    { speaker: 'ren_uni', jp: 'この政策の趣旨は、出生率の改善ですか？', en: 'Is the policy’s intent to improve the birth rate?', style: 'student probing the purpose' },
    { speaker: 'asuka_teacher', jp: 'ええ、保育所の増設又は補助金で支えます。', en: 'Yes, supported by more daycare or subsidies.', style: 'teacher detailing the means' },
  ]),
  C('conv_03313', 'A student asks an officer about a civil-service career', 'Discuss a career; teach 公務員/把握/自民党/趣旨/児童/又は/見解/連合', 'office_quiet_low',
    ['公務員','把握','自民党','趣旨','児童','又は','見解','連合'], ['sakura_teen', 'takeda_officer'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '公務員になるには、どうすればいいですか？', en: 'How do I become a civil servant?', style: 'earnest teen seeking guidance' },
    { speaker: 'takeda_officer', jp: '試験に合格し、業務を把握する努力が必要です。', en: 'Pass the exam and work to grasp the duties.', style: 'measured officer giving straight advice' },
    { speaker: 'sakura_teen', jp: '自民党とか、政治と関わるんですか？', en: 'Do you get involved with parties like the LDP?', style: 'curious teen checking a worry' },
    { speaker: 'takeda_officer', jp: '公務員は中立です。政策の趣旨に従って働きます。', en: 'Civil servants are neutral; we serve the policy’s intent.', style: 'officer clarifying the principle' },
    { speaker: 'sakura_teen', jp: '児童福祉の窓口にも配属されますか？', en: 'Could I be assigned to a child-welfare desk?', style: 'teen exploring the roles' },
    { speaker: 'takeda_officer', jp: 'ええ、福祉又は税務など、幅広い部署があります。', en: 'Yes, there are wide departments — welfare or tax, etc.', style: 'officer outlining the breadth' },
    { speaker: 'sakura_teen', jp: '上司の見解と違うときは、どうするんですか？', en: 'What if you differ from a superior’s view?', style: 'thoughtful teen probing a dilemma' },
    { speaker: 'takeda_officer', jp: '組織内の連合的な調整で、合意を目指します。', en: 'We seek consensus through coordinated alignment within.', style: 'officer explaining the resolution' },
  ]),
  C('conv_03314', 'Following news about a contested bill', 'Track a bill; teach 自民党/見解/趣旨/公務員/把握/児童/又は/連合', 'living_room_quiet',
    ['自民党','見解','趣旨','公務員','把握','児童','又は','連合'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: 'あの法案、結局どうなったんですか？', en: 'That bill — what happened in the end?', style: 'curious student following up' },
    { speaker: 'asuka_teacher', jp: '自民党が修正案を出しました。', en: 'The LDP submitted an amendment.', style: 'teacher relaying the development' },
    { speaker: 'ren_uni', jp: '専門家の見解は分かれているようですね。', en: 'Experts’ views seem divided.', style: 'student noting the disagreement' },
    { speaker: 'asuka_teacher', jp: 'ええ、趣旨は良くても、運用が難しい。', en: 'Yes — the intent is good, but operation is hard.', style: 'teacher weighing the nuance' },
    { speaker: 'ren_uni', jp: '現場の公務員が実態を把握できるかが鍵ですね。', en: 'Whether field civil servants grasp reality is key.', style: 'student identifying the crux' },
    { speaker: 'asuka_teacher', jp: '児童や高齢者への影響も考慮されています。', en: 'Effects on children and the elderly are considered too.', style: 'teacher noting the breadth' },
    { speaker: 'ren_uni', jp: '賛成又は反対、世論も割れていますね。', en: 'For or against, public opinion is split too.', style: 'student observing the divide' },
    { speaker: 'asuka_teacher', jp: '各団体の連合が、声明を出しました。', en: 'A federation of groups issued a statement.', style: 'teacher adding the latest move' },
  ]),
  C('conv_03315', 'Wrapping up the politics unit', 'Summarize the unit; teach 自民党/公務員/趣旨/見解/把握/児童/又は/連合', 'lecture_hall_quiet',
    ['自民党','公務員','趣旨','見解','把握','児童','又は','連合'], ['asuka_teacher', 'sakura_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '政治の単元、理解は深まりましたか？', en: 'Did your grasp of the politics unit deepen?', style: 'teacher checking comprehension warmly' },
    { speaker: 'sakura_teen', jp: 'はい。自民党のような政党の役割が分かりました。', en: 'Yes. I understood parties like the LDP.', style: 'satisfied teen summarizing learning' },
    { speaker: 'ren_uni', jp: '公務員の中立性も、大事だと感じました。', en: 'I felt civil-servant neutrality matters too.', style: 'reflective student adding insight' },
    { speaker: 'sakura_teen', jp: '法案の趣旨を読み解く力もつきました。', en: 'I gained the skill to read a bill’s intent too.', style: 'teen noting a concrete gain' },
    { speaker: 'asuka_teacher', jp: '多様な見解を尊重する姿勢が大切です。', en: 'Respecting diverse views is important.', style: 'teacher offering a guiding value' },
    { speaker: 'ren_uni', jp: '状況を把握して判断する習慣をつけたいです。', en: 'I want a habit of grasping the situation before judging.', style: 'maturing student stating a resolve' },
    { speaker: 'sakura_teen', jp: '児童や弱者を守る視点も忘れたくないです。', en: 'I don’t want to forget protecting children and the weak.', style: 'principled teen voicing compassion' },
    { speaker: 'asuka_teacher', jp: '賛成又は反対、議論を続けることが民主主義です。', en: 'For or against, continuing debate is democracy.', style: 'teacher closing on a civic note' },
  ]),

  // ===== CLUSTER D: school study & receiving materials by mail =====
  C('conv_03316', 'Getting ready before class', 'Prep for class; teach 教科書/番目/テキスト/用語/沢山/マガジン/水準/郵便', 'lecture_hall_quiet',
    ['教科書','番目','テキスト','用語','沢山','マガジン','水準','郵便'], ['sakura_teen', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '今日の授業、教科書のどこから？', en: 'Where in the textbook does class start today?', style: 'organized teen checking the plan' },
    { speaker: 'riku_teen', jp: '三番目の章だよ。', en: 'The third chapter.', style: 'helpful classmate answering quickly' },
    { speaker: 'sakura_teen', jp: '英語のテキストも持ってきた？', en: 'Did you bring the English text too?', style: 'teen double-checking materials' },
    { speaker: 'riku_teen', jp: 'うん。専門用語が多くて難しいよね。', en: 'Yeah. Lots of technical terms, it’s tough.', style: 'classmate commiserating' },
    { speaker: 'sakura_teen', jp: '宿題が沢山あって、終わらなかった。', en: 'There was tons of homework; I didn’t finish.', style: 'tired teen confessing' },
    { speaker: 'riku_teen', jp: '学習マガジンの付録、役に立つよ。', en: 'The study magazine’s supplement helps.', style: 'classmate sharing a tip' },
    { speaker: 'sakura_teen', jp: 'クラスの学力水準、高いよね。', en: 'The class’s academic level is high, huh.', style: 'teen noting the pressure' },
    { speaker: 'riku_teen', jp: 'そういえば、通信教材が郵便で届いたよ。', en: 'By the way, the correspondence materials came by mail.', style: 'classmate recalling a delivery' },
  ]),
  C('conv_03317', 'Studying together at home', 'Study together; teach 用語/教科書/番目/テキスト/沢山/水準/マガジン/郵便', 'living_room_quiet',
    ['用語','教科書','番目','テキスト','沢山','水準','マガジン','郵便'], ['riku_teen', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: 'この用語の意味、教科書に載ってる？', en: 'Is this term’s meaning in the textbook?', style: 'puzzled classmate searching' },
    { speaker: 'sakura_teen', jp: '載ってるよ。五番目の項目。', en: 'It is. The fifth item.', style: 'helpful teen pointing it out' },
    { speaker: 'riku_teen', jp: 'テキストの説明のほうが分かりやすいな。', en: 'The text’s explanation is clearer.', style: 'classmate comparing sources' },
    { speaker: 'sakura_teen', jp: '例題が沢山あって、練習になる。', en: 'There are tons of examples; good practice.', style: 'teen appreciating the drills' },
    { speaker: 'riku_teen', jp: 'この問題集の水準、入試レベルだね。', en: 'This workbook’s level is exam-grade.', style: 'classmate gauging the difficulty' },
    { speaker: 'sakura_teen', jp: '解説マガジンも一緒に読むといいよ。', en: 'It helps to read the explainer magazine too.', style: 'teen recommending a resource' },
    { speaker: 'riku_teen', jp: '申し込んだ参考書、まだ郵便で来ない。', en: 'The reference book I ordered hasn’t come by mail yet.', style: 'impatient classmate grumbling' },
  ]),
  C('conv_03318', 'A teacher gives study guidance', 'Advise on studying; teach 教科書/テキスト/用語/沢山/水準/番目/郵便/マガジン', 'lecture_hall_quiet',
    ['教科書','テキスト','用語','沢山','水準','番目','郵便','マガジン'], ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '教科書だけでなく、テキストも併用しましょう。', en: 'Use not just the textbook but the text too.', style: 'guiding teacher offering method' },
    { speaker: 'sakura_teen', jp: '専門用語が覚えられなくて。', en: 'I can’t memorize the technical terms.', style: 'struggling teen seeking help' },
    { speaker: 'asuka_teacher', jp: '沢山書いて、手で覚えるのが効果的です。', en: 'Writing a lot and learning by hand works well.', style: 'teacher prescribing a technique' },
    { speaker: 'sakura_teen', jp: '私の水準だと、どの問題から始めれば？', en: 'At my level, which problems should I start with?', style: 'teen asking for a starting point' },
    { speaker: 'asuka_teacher', jp: '教科書の二番目の例題からどうぞ。', en: 'Start from the textbook’s second example.', style: 'teacher giving a concrete step' },
    { speaker: 'sakura_teen', jp: '補助教材はどうやって入手しますか？', en: 'How do I get the supplementary materials?', style: 'teen inquiring practically' },
    { speaker: 'asuka_teacher', jp: '申し込めば、郵便で送られてきます。', en: 'If you apply, they’re sent by mail.', style: 'teacher explaining the process' },
    { speaker: 'sakura_teen', jp: '先生おすすめの学習マガジンも探してみます。', en: 'I’ll look for the study magazine you recommend too.', style: 'motivated teen taking initiative' },
  ]),
  C('conv_03319', 'Comparing notes during exam prep', 'Prep for exams; teach 教科書/番目/テキスト/用語/沢山/水準/マガジン/郵便', 'living_room_quiet',
    ['教科書','番目','テキスト','用語','沢山','水準','マガジン','郵便'], ['riku_teen', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: '試験範囲、教科書のどこまで？', en: 'How far in the textbook is the exam range?', style: 'anxious classmate confirming scope' },
    { speaker: 'sakura_teen', jp: '四番目の単元までだよ。', en: 'Up to the fourth unit.', style: 'organized teen answering precisely' },
    { speaker: 'riku_teen', jp: 'テキストの重要用語、全部チェックした？', en: 'Did you check all the text’s key terms?', style: 'diligent classmate comparing prep' },
    { speaker: 'sakura_teen', jp: 'うん、沢山あって大変だった。', en: 'Yeah, there were tons; it was rough.', style: 'weary teen sharing the grind' },
    { speaker: 'riku_teen', jp: '過去問の水準は、本番と同じくらい？', en: 'Is the past-paper level like the real thing?', style: 'classmate gauging the difficulty' },
    { speaker: 'sakura_teen', jp: 'そうみたい。対策マガジンにそう書いてた。', en: 'Seems so. The prep magazine said as much.', style: 'teen citing a source' },
    { speaker: 'riku_teen', jp: '合否通知って、郵便で来るんだっけ。', en: 'The results notice comes by mail, right?', style: 'classmate checking a detail' },
  ]),
  C('conv_03320', 'Relaxing after exams', 'Unwind after exams; teach 教科書/テキスト/用語/沢山/水準/マガジン/郵便/番目', 'living_room_quiet',
    ['教科書','テキスト','用語','沢山','水準','マガジン','郵便','番目'], ['sakura_teen', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '試験、やっと終わったね！', en: 'Exams are finally over!', style: 'relieved teen exhaling happily' },
    { speaker: 'riku_teen', jp: '教科書、もう見たくないよ。', en: 'I don’t want to see the textbook anymore.', style: 'exhausted classmate joking' },
    { speaker: 'sakura_teen', jp: 'テキストも用語集も、しばらく封印。', en: 'The text and term list are sealed away a while.', style: 'teen playfully declaring a break' },
    { speaker: 'riku_teen', jp: '沢山勉強したから、自信はある。', en: 'I studied tons, so I’m confident.', style: 'hopeful classmate reassuring himself' },
    { speaker: 'sakura_teen', jp: '自分の水準、少しは上がったかな。', en: 'I wonder if my level rose a bit.', style: 'reflective teen gauging growth' },
    { speaker: 'riku_teen', jp: 'ご褒美に、好きなマガジン買おう。', en: 'As a reward, let’s buy our favorite magazine.', style: 'cheerful classmate suggesting a treat' },
    { speaker: 'sakura_teen', jp: '結果は来週、郵便で届くね。', en: 'Results arrive by mail next week.', style: 'teen noting what’s next' },
    { speaker: 'riku_teen', jp: '番目の順位まで出るのか、ドキドキする。', en: 'It even shows your rank — nerve-wracking.', style: 'jittery classmate anticipating it' },
  ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_166 wrote', CONVERSATIONS.length, 'files');
