import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_091)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01806',
    context: 'Aoi finally has her baby; cradling with Kenji at the hospital.',
    purpose: 'New parents tender first moments with baby.',
    ambient: 'hospital_room_warm_quiet',
    sound_effects: [],
    target_vocab: ['赤ちゃん', '小さい', '可愛い', '幸せ'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '産まれた、本当に小さい。', en: "Born — truly small.", style: 'tender exhausted adult woman voice, soft warm awed delivery carefully' },
      { speaker: 'kenji_office', jp: 'うん、可愛い、ほんま。', en: "Yeah — cute, truly.", style: 'soft Kansai father voice, warm tearful tender delivery carefully' },
      { speaker: 'aoi_barista', jp: '指、ちっちゃい!', en: "Fingers — tiny!", style: 'soft adult woman voice, warm awed delight delivered carefully' },
      { speaker: 'kenji_office', jp: 'お前、よう頑張った。', en: "You — well done.", style: 'tender Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'aoi_barista', jp: '幸せって、こういうこと。', en: "Happiness — this.", style: 'tender adult woman voice, soft warm content delivery carefully' },
      { speaker: 'kenji_office', jp: 'これから、家族でな。', en: "From now — as family.", style: 'warm Kansai father voice, soft tender committed delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、頑張ろうね。', en: "Yeah — let's try.", style: 'soft adult woman voice, warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_01807',
    context: 'Sho-young tries to describe his feelings to Mei about a complex day.',
    purpose: 'Mother helping child name their emotions.',
    ambient: 'kitchen_evening_warm',
    sound_effects: [],
    target_vocab: ['気持ち', '嬉しい', '寂しい', '混ざる'],
    cast: ['sho_child', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、気持ち、変だった。', en: "Mom — feelings, strange.", style: 'soft child boy voice, warm thoughtful honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'どんな感じ?', en: "What feel?", style: 'gentle young mother voice, soft warm caring inquiry delivered carefully' },
      { speaker: 'sho_child', jp: '嬉しいけど、寂しい。', en: "Happy — but sad.", style: 'soft thoughtful child boy voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '混ざってるのね。', en: "Mixed.", style: 'tender young mother voice, soft warm understanding delivery carefully' },
      { speaker: 'sho_child', jp: '変?', en: "Strange?", style: 'soft child boy voice, warm worried delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ううん、人間らしいの。', en: "No — human.", style: 'warm young mother voice, soft tender accepting delivery carefully' },
    ],
  },
  {
    id: 'conv_01808',
    context: 'Naoko praises Hina-young at the ramen shop after her first solo shift.',
    purpose: 'Aunt giving teen earnest workplace praise.',
    ambient: 'ramen_shop_evening',
    sound_effects: [],
    target_vocab: ['素晴らしい', '頑張る', '成長', '誇り'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、今日、素晴らしかった!', en: "Hina — today, splendid!", style: 'brassy Kansai aunt voice, bright loud proud delivery carefully' },
      { speaker: 'hina_child', jp: 'ほんとに?嬉しい!', en: "Really? Happy!", style: 'thrilled teen girl voice, bright warm proud delivery carefully' },
      { speaker: 'naoko_aunt', jp: '成長したな、お前!', en: "Grew up — you!", style: 'tender Kansai aunt voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: 'おばちゃんのおかげ。', en: "Thanks to auntie.", style: 'soft teen girl voice, warm humble grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '誇りに思うで、ほんま!', en: "Proud — truly!", style: 'warm Kansai aunt voice, bright loud loving delivery carefully' },
    ],
  },
  {
    id: 'conv_01809',
    context: 'Daichi tries to comfort Mei after a hard parenting day.',
    purpose: 'Husband supportive of overwhelmed wife.',
    ambient: 'bedroom_lamp_quiet',
    sound_effects: [],
    target_vocab: ['疲れる', '辛い', '抱きしめる', '一緒'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '今日、本当に疲れた。', en: "Today — really tired.", style: 'soft exhausted young mother voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、お疲れさん。', en: "Yeah — good work.", style: 'tender Kansai husband voice, soft warm caring delivery carefully' },
      { speaker: 'mei_romantic', jp: '子供、ぐずって、辛かった。', en: "Kids fussed — hard.", style: 'soft young mother voice, warm tearful honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '一人で、ようやった。', en: "Alone — well done.", style: 'soft Kansai husband voice, warm tender proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'たまには、泣きたい。', en: "Sometimes — want to cry.", style: 'soft vulnerable young mother voice, warm raw delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええで、泣いてええで。', en: "Fine — cry's fine.", style: 'tender Kansai husband voice, soft warm protective delivery carefully' },
      { speaker: 'mei_romantic', jp: '一緒におってくれて、ありがとう。', en: "With me — thanks.", style: 'tender young wife voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01810',
    context: 'Sakura interviews Naoko for a piece about strong women in business.',
    purpose: 'Writer talking with strong-personality business owner.',
    ambient: 'ramen_shop_afternoon_quiet',
    sound_effects: [],
    target_vocab: ['女性', '経営', '強い', '人生'],
    cast: ['sakura_teen', 'naoko_aunt'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'おばさんの経営、長いですね。', en: "Your business — long.", style: 'gentle adult writer voice, soft warm professional inquiry delivered carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、もう三十年や。', en: "Yeah — thirty years.", style: 'warm Kansai aunt voice, soft proud delivery carefully' },
      { speaker: 'sakura_teen', jp: '苦労、ありましたか?', en: "Hardships — were?", style: 'curious adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ようけ、ようけあったわ。', en: "Many — many.", style: 'soft Kansai aunt voice, warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '女性として、特に?', en: "As a woman — especially?", style: 'thoughtful adult writer voice, soft warm probing delivery carefully' },
      { speaker: 'naoko_aunt', jp: '取引、なめられたこと、多い。', en: "Negotiation — looked down on, often.", style: 'firm Kansai aunt voice, soft warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どうやって、乗り越えた?', en: "How — got through?", style: 'engaged adult writer voice, soft warm respectful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '腹くくって、強く出るしかない。', en: "Steeled — go strong.", style: 'animated Kansai aunt voice, bright loud determined delivery carefully' },
      { speaker: 'sakura_teen', jp: '若い女性に、メッセージは?', en: "Message to young women?", style: 'gentle adult writer voice, soft warm professional delivery carefully' },
      { speaker: 'naoko_aunt', jp: '自分、信じて、貫け!', en: "Self — believe, persist!", style: 'brassy Kansai aunt voice, bright loud passionate delivery carefully' },
      { speaker: 'sakura_teen', jp: '心に響く、言葉です。', en: "Resonates — words.", style: 'soft adult writer voice, warm tender appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '人生、後悔せんでええ。', en: "Life — without regret.", style: 'warm Kansai aunt voice, soft tender wise delivery carefully' },
      { speaker: 'sakura_teen', jp: '貴重なお話、ありがとうございます。', en: "Precious words — thanks.", style: 'humble adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01811',
    context: 'Ren gets bad news about a family illness; talks to Saito alone after hours.',
    purpose: 'Young man processing grief with elder mentor.',
    ambient: 'clinic_evening_quiet',
    sound_effects: [],
    target_vocab: ['病気', '心配', '家族', '受け入れる'],
    cast: ['ren_uni', 'saito_doctor'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '先生、母の病気、進行してます。', en: "Doctor — mom's illness, advancing.", style: 'soft tearful young man voice, warm raw honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '辛いね、本当に。', en: "Hard — truly.", style: 'measured doctor voice, soft warm empathetic delivery carefully' },
      { speaker: 'ren_uni', jp: '心配で、眠れません。', en: "Worry — can't sleep.", style: 'soft exhausted young man voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ご家族、何より大事。', en: "Family — above all.", style: 'gentle doctor voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: '受け入れる、難しい。', en: "Acceptance — hard.", style: 'soft young man voice, warm raw struggling delivery carefully' },
      { speaker: 'saito_doctor', jp: '時間かけて、ゆっくり。', en: "Take time — slowly.", style: 'tender doctor voice, soft warm patient delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、聞いてくれて。', en: "Thanks — for listening.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01812',
    context: 'Kenji and Aoi celebrate their baby\'s first month at home quietly.',
    purpose: 'New parents adjusting to family life sweetly.',
    ambient: 'living_room_evening_warm',
    sound_effects: [],
    target_vocab: ['月', '成長', '一緒', '感謝'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'もう、一ヶ月経つの。', en: "Already — one month.", style: 'tender adult woman voice, soft warm awed delivery carefully' },
      { speaker: 'kenji_office', jp: '早いなぁ、ほんま。', en: "Fast — truly.", style: 'soft Kansai father voice, warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '成長、毎日見える。', en: "Growth — daily visible.", style: 'gentle adult woman voice, soft warm proud delivery carefully' },
      { speaker: 'kenji_office', jp: '一緒におる時間、宝物や。', en: "Time together — treasure.", style: 'tender Kansai father voice, soft warm loving delivery carefully' },
      { speaker: 'aoi_barista', jp: '感謝の毎日、本当に。', en: "Grateful daily — truly.", style: 'tender adult woman voice, soft warm humble delivery carefully' },
    ],
  },
  {
    id: 'conv_01813',
    context: 'Hina-young tries her first part-time job at the ramen shop; Naoko coaches.',
    purpose: 'Aunt guiding teen through first workday lessons.',
    ambient: 'ramen_shop_busy',
    sound_effects: [],
    target_vocab: ['仕事', '緊張', '丁寧', '笑顔'],
    cast: ['hina_child', 'naoko_aunt'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばちゃん、緊張する!', en: "Auntie — nervous!", style: 'soft nervous teen girl voice, warm honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'お客さんに、笑顔やで!', en: "Customers — smile!", style: 'brassy Kansai aunt voice, bright firm teaching delivery carefully' },
      { speaker: 'hina_child', jp: '丁寧に、頑張る!', en: "Carefully — try!", style: 'soft determined teen girl voice, warm committed delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ええ調子や、その意気!', en: "Fine pace — that spirit!", style: 'animated Kansai aunt voice, bright loud encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、おばちゃん、ありがと!', en: "Yeah — auntie, thanks!", style: 'bright teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01814',
    context: 'Yumiko receives a phone call about a friend\'s passing; tearful with Mei.',
    purpose: 'Elder grief shared with caring family member.',
    ambient: 'living_room_evening_quiet',
    sound_effects: [],
    target_vocab: ['訃報', '友達', '悲しい', '思い出'],
    cast: ['yumiko_mom', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '友達、亡くなったって。', en: "Friend — passed.", style: 'soft tearful older mother voice, warm raw honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お母さん、辛いでしょう。', en: "Mom — must be hard.", style: 'tender young woman voice, soft warm empathetic delivery carefully' },
      { speaker: 'yumiko_mom', jp: '長い付き合い、だった。', en: "Long bond — was.", style: 'gentle older mother voice, soft warm reflective delivery carefully' },
      { speaker: 'mei_romantic', jp: '思い出、たくさんありますね。', en: "Memories — many.", style: 'soft young woman voice, warm reverent delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'うん、宝物のような。', en: "Yeah — like treasure.", style: 'tearful older mother voice, soft warm tender delivery carefully' },
      { speaker: 'mei_romantic', jp: '今日は、一緒に泣いていいよ。', en: "Today — cry together.", style: 'tender young woman voice, soft warm steadfast delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ありがとう、隣にいてくれて。', en: "Thanks — for being.", style: 'soft older mother voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01815',
    context: 'Hiroshi-elder gives Daichi a small ancestral keepsake before declining health.',
    purpose: 'Elder passing meaningful item to son-in-law.',
    ambient: 'tatami_evening_lamp',
    sound_effects: [],
    target_vocab: ['先祖', '伝える', '大切', '受け取る'],
    cast: ['hiroshi_elder', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '大ちゃん、これ、先祖の品や。', en: "Daichi — this, ancestor's item.", style: 'slow elder Kansai voice, warm tender reverent delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おとうさん、こんな大切なもの。', en: "Otosan — such precious thing.", style: 'soft Kansai man voice, warm awed honoring delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前に、託したい。', en: "To you — entrust.", style: 'gentle elder Kansai voice, soft warm earnest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '受け取ってええんですか?', en: "May I receive?", style: 'humble Kansai husband voice, soft warm careful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、家族の伝統や。', en: "Yeah — family tradition.", style: 'warm elder Kansai voice, soft tender delivery carefully' },
      { speaker: 'daichi_kansai', jp: '大切に、守ります。', en: "Preciously — protect.", style: 'committed Kansai man voice, soft warm reverent delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええ婿に、来てくれたな。', en: "Fine son-in-law — came.", style: 'tender elder Kansai voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01816',
    context: 'Sho-young describes a vivid dream he had to Sakura at breakfast.',
    purpose: 'Child sharing imagination with adult mentor.',
    ambient: 'kitchen_morning_warm',
    sound_effects: [],
    target_vocab: ['夢', '不思議', '空', '飛ぶ'],
    cast: ['sho_child', 'sakura_teen'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'さくらさん、不思議な夢見た!', en: "Sakura — strange dream!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どんな夢?', en: "What dream?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'sho_child', jp: '空、飛んでた!', en: "Sky — flying!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、素敵な夢。', en: "Oh — lovely dream.", style: 'soft adult writer voice, warm tender appreciative delivery carefully' },
      { speaker: 'sho_child', jp: 'また、見たい!', en: "Want to see again!", style: 'bright child boy voice, soft warm hopeful delivery carefully' },
    ],
  },
  {
    id: 'conv_01817',
    context: 'Kenji and Sakura have a long studio talk about creativity in middle age.',
    purpose: 'Two adults reflecting on changing creative life.',
    ambient: 'studio_lamp_evening',
    sound_effects: [],
    target_vocab: ['創作', '年齢', '変化', '深い'],
    cast: ['kenji_office', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '年取って、創作、変わった?', en: "Aging — creation, changed?", style: 'thoughtful adult writer voice, soft warm philosophical delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、深さが、変わった。', en: "Yeah — depth, changed.", style: 'gentle Kansai artist voice, soft warm reflective delivery carefully' },
      { speaker: 'sakura_teen', jp: '私も、感じる。', en: "I too — feel.", style: 'soft adult writer voice, warm agreement delivered carefully' },
      { speaker: 'kenji_office', jp: '若い頃、勢いだけやった。', en: "Young — just momentum.", style: 'soft Kansai man voice, warm honest delivery carefully' },
      { speaker: 'sakura_teen', jp: '今は、丁寧に作る。', en: "Now — make carefully.", style: 'gentle adult writer voice, soft warm content delivery carefully' },
      { speaker: 'kenji_office', jp: '変化、ええことやな。', en: "Change — fine.", style: 'warm Kansai artist voice, soft fond delivery carefully' },
      { speaker: 'sakura_teen', jp: 'これからも、楽しみ。', en: "Going forward — looking forward.", style: 'soft adult writer voice, warm hopeful delivery carefully' },
    ],
  },
  {
    id: 'conv_01818',
    context: 'Hina-young learns to write a calligraphy character; Sachiko-grandma teaches.',
    purpose: 'Grandmother sharing brush-art craft with teen.',
    ambient: 'tatami_room_quiet',
    sound_effects: [],
    target_vocab: ['書道', '筆', '集中', '美しい'],
    cast: ['sachiko_grandma', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sachiko_grandma', jp: 'ひな、筆、ようけ持って。', en: "Hina — hold the brush well.", style: 'gentle grandmother voice, soft warm teaching delivery carefully' },
      { speaker: 'hina_child', jp: 'こうですか?', en: "Like this?", style: 'soft attentive teen girl voice, warm careful delivery carefully' },
      { speaker: 'sachiko_grandma', jp: '集中、息を整えて。', en: "Focus — settle breath.", style: 'warm grandmother voice, soft warm patient delivery carefully' },
      { speaker: 'hina_child', jp: '書道、心、整うね。', en: "Calligraphy — heart orders.", style: 'soft teen girl voice, warm content delivery carefully' },
      { speaker: 'sachiko_grandma', jp: '美しい字、書けたわよ。', en: "Beautiful char — written.", style: 'tender grandmother voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01819',
    context: 'Asuka shares a difficult classroom story with Saito over dinner.',
    purpose: 'Two professionals supporting each other after hard day.',
    ambient: 'kitchen_dinner_warm',
    sound_effects: [],
    target_vocab: ['生徒', '悩む', '聞く', '寄り添う'],
    cast: ['asuka_teacher', 'saito_doctor'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '生徒、深く悩んでて。', en: "Student — deeply troubled.", style: 'soft teacher voice, warm honest concerned delivery carefully' },
      { speaker: 'saito_doctor', jp: 'お話、聞かせて。', en: "Tell me.", style: 'gentle doctor voice, soft warm caring delivery carefully' },
      { speaker: 'asuka_teacher', jp: '家庭、複雑みたい。', en: "Home — complex.", style: 'gentle teacher voice, soft warm careful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'あなた、寄り添うだけで充分。', en: "You — being there's enough.", style: 'soft doctor voice, warm tender wise delivery carefully' },
      { speaker: 'asuka_teacher', jp: '何も、できないのが辛い。', en: "Can't do — hard.", style: 'soft teacher voice, warm raw honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '聞く、その存在、大きい。', en: "Listening — that presence, huge.", style: 'warm doctor voice, soft tender philosophical delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ありがとう、心が軽くなった。', en: "Thanks — feels lighter.", style: 'tender teacher voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01820',
    context: 'Mei takes Sho-young to a small festival; lots of energy and joy.',
    purpose: 'Mother and child experiencing festive happiness.',
    ambient: 'festival_lanterns_drums',
    sound_effects: [],
    target_vocab: ['祭り', '楽しい', '屋台', '盆踊り'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、屋台、たくさん!', en: "Mom — stalls, many!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'うん、祭り、楽しいね。', en: "Yeah — festival, fun.", style: 'warm young mother voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: 'たこ焼き、食べたい!', en: "Takoyaki — want!", style: 'eager child boy voice, bright warm delivery carefully' },
      { speaker: 'mei_romantic', jp: '盆踊り、見ようね、後で。', en: "Bon dance — later watch.", style: 'soft young mother voice, warm warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、ずっと楽しい!', en: "Yay — keeps fun!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01821',
    context: 'Naoko and Hiroshi-elder talk seriously about aging together for the first time.',
    purpose: 'Two elders sharing rare honest aging conversation.',
    ambient: 'tatami_evening_quiet',
    sound_effects: [],
    target_vocab: ['老い', '健康', '互いに', '長生き'],
    cast: ['naoko_aunt', 'hiroshi_elder'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '兄ちゃん、最近、しんどい?', en: "Brother — lately, weary?", style: 'soft Kansai aunt voice, warm tender caring delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、ちょっとな。', en: "Yeah — a bit.", style: 'slow elder Kansai voice, warm honest delivery carefully' },
      { speaker: 'naoko_aunt', jp: '無理せんでええで。', en: "Don't push.", style: 'tender Kansai aunt voice, soft warm caring delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おまえも、ちゃんと休めや。', en: "You too — rest properly.", style: 'gentle elder Kansai voice, soft warm caring delivery carefully' },
      { speaker: 'naoko_aunt', jp: '互いに、長生きせなあかんな。', en: "Both — must live long.", style: 'warm Kansai aunt voice, soft tender delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、約束やで。', en: "Yeah — promise.", style: 'warm elder Kansai voice, soft tender enduring delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、家族の絆やな。', en: "Heh — family bond.", style: 'soft Kansai aunt voice, warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_01822',
    context: 'Ren brings Aoi and baby a homemade meal as a gift.',
    purpose: 'Friend bringing thoughtful gift to new mother.',
    ambient: 'cafe_evening_quiet',
    sound_effects: [],
    target_vocab: ['手作り', '気持ち', '助かる', '友達'],
    cast: ['ren_uni', 'aoi_barista'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '蒼さん、手作り、持ってきました。', en: "Aoi — handmade, brought.", style: 'soft young man voice, warm humble caring delivery carefully' },
      { speaker: 'aoi_barista', jp: 'まあ、ありがとう、嬉しい!', en: "Oh — thanks, happy!", style: 'tender adult woman voice, soft warm grateful delight delivered carefully' },
      { speaker: 'ren_uni', jp: '少しでも、助かれば。', en: "Even a little — if helps.", style: 'gentle young man voice, soft warm humble delivery carefully' },
      { speaker: 'aoi_barista', jp: '気持ちが、本当に温かい。', en: "Feeling — truly warm.", style: 'soft adult woman voice, warm tender appreciative delivery carefully' },
      { speaker: 'ren_uni', jp: '友達、当然のことです。', en: "Friend — natural.", style: 'humble young man voice, soft warm sincere delivery carefully' },
    ],
  },
  {
    id: 'conv_01823',
    context: 'Daichi reads with Sho-young about an old samurai code; values discussion.',
    purpose: 'Father teaching son about traditional virtues.',
    ambient: 'living_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['武士', '正義', '勇気', '忠'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、武士、強い?', en: "Dad — samurai, strong?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、心、強かった。', en: "Yeah — heart strong.", style: 'warm Kansai father voice, soft fond delivery carefully' },
      { speaker: 'sho_child', jp: '正義のため、戦う?', en: "For justice — fight?", style: 'soft child boy voice, warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、勇気と忠誠、大事や。', en: "Yeah — courage, loyalty matter.", style: 'gentle Kansai father voice, soft warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼくも、勇気持ちたい!', en: "Want courage too!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前に、ええ心、ちゃんとある。', en: "You — good heart, properly.", style: 'tender Kansai father voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: 'ありがとう、お父さん。', en: "Thanks — Dad.", style: 'soft child boy voice, warm tender grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01824',
    context: 'Sakura reads her latest chapter aloud to Hiroshi-elder for feedback.',
    purpose: 'Writer seeking quiet elder reader response.',
    ambient: 'tatami_lamp_evening',
    sound_effects: [],
    target_vocab: ['文章', '感想', '心', '伝える'],
    cast: ['sakura_teen', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'おとうさん、感想、聞かせてください。', en: "Otosan — impressions, please.", style: 'soft adult writer voice, warm humble respectful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ええ文章やった、心にしみた。', en: "Fine prose — soaked in heart.", style: 'slow elder Kansai voice, warm tender appreciative delivery carefully' },
      { speaker: 'sakura_teen', jp: '本当に?嬉しいです。', en: "Truly? Happy.", style: 'gentle adult writer voice, soft warm grateful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '伝える力、強いな、お前。', en: "Conveying power — strong, you.", style: 'warm elder Kansai voice, soft proud delivery carefully' },
      { speaker: 'sakura_teen', jp: '長く、書いてきた甲斐があった。', en: "Long writing — worth it.", style: 'tender adult writer voice, soft warm content delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'これからも、続けてな。', en: "Going forward — keep.", style: 'tender elder Kansai voice, soft warm enduring delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、必ず。', en: "Yes — without fail.", style: 'committed adult writer voice, soft warm resolved delivery carefully' },
    ],
  },
  {
    id: 'conv_01825',
    context: 'Whole family gathers for spring cherry blossom viewing; many voices.',
    purpose: 'Big intergenerational hanami appreciation.',
    ambient: 'park_hanami_breeze',
    sound_effects: [],
    target_vocab: ['桜', '春', '満開', '一緒', '美しい'],
    cast: ['hiroshi_elder', 'naoko_aunt', 'mei_romantic', 'daichi_kansai', 'sho_child', 'hina_child', 'aoi_barista', 'kenji_office'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '桜、満開やな、見事や。', en: "Cherry — full bloom, splendid.", style: 'slow elder Kansai voice, warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ほんま、美しいわ!', en: "Truly — beautiful!", style: 'brassy Kansai aunt voice, bright loud delighted delivery carefully' },
      { speaker: 'sho_child', jp: 'うわー、いっぱい!', en: "Whoa — lots!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'hina_child', jp: '春、本当に、いい季節。', en: "Spring — truly fine season.", style: 'soft teen girl voice, warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お弁当、広げましょうか。', en: "Bento — open?", style: 'gentle young mother voice, soft warm caring delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お酒、用意したで!', en: "Sake — prepared!", style: 'warm Kansai husband voice, soft cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: '赤ちゃんも、桜デビュー。', en: "Baby — cherry debut.", style: 'tender adult woman voice, soft warm fond delivery carefully' },
      { speaker: 'kenji_office', jp: '一緒に、ええ時間や。', en: "Together — fine time.", style: 'soft Kansai father voice, warm tender delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '毎年、こうやって集まりたい。', en: "Yearly — like this gather.", style: 'gentle elder Kansai voice, soft warm enduring delivery carefully' },
      { speaker: 'naoko_aunt', jp: '当たり前や、家族の伝統!', en: "Of course — family tradition!", style: 'animated Kansai aunt voice, bright loud committed delivery carefully' },
      { speaker: 'sho_child', jp: '桜、来年も、見たい!', en: "Cherry — next year see!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: '思い出、また増えるね。', en: "Memories — increase.", style: 'tender teen girl voice, soft warm fond delivery carefully' },
      { speaker: 'mei_romantic', jp: '家族、宝物。', en: "Family — treasure.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_091 wrote', CONVERSATIONS.length, 'files');
