import fs from 'node:fs'; import path from 'node:path'; import url from 'node:url';
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_170)', generated_at: NOW, source_plan_row: '' });
const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 3, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // ===== CLUSTER A: software / gadget setup =====
  C('conv_03381', 'Two friends compare a newly installed app', 'Discuss an app; teach インストール/バージョン/プラス/マイナス/カラー/回転/穴/録音', 'office_quiet_low',
    ['インストール','バージョン','プラス','マイナス','カラー','回転','穴','録音'], ['ren_uni', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '新しいアプリ、インストールした？', en: 'Did you install the new app?', style: 'curious techie checking in' },
    { speaker: 'riku_teen', jp: 'うん、最新バージョンを入れたよ。', en: 'Yeah, I put in the latest version.', style: 'up-to-date friend reporting' },
    { speaker: 'ren_uni', jp: '動作が速くなって、プラスだね。', en: 'It got faster — a plus.', style: 'pleased techie noting the upside' },
    { speaker: 'riku_teen', jp: 'でもバッテリーの消費はマイナスかも。', en: 'But battery drain might be a minus.', style: 'critical friend weighing the downside' },
    { speaker: 'ren_uni', jp: 'カラー設定もカスタマイズできるよ。', en: 'You can customize the color settings too.', style: 'enthusiastic techie sharing a feature' },
    { speaker: 'riku_teen', jp: '画面の回転にも対応してる？', en: 'Does it support screen rotation too?', style: 'practical friend probing details' },
    { speaker: 'ren_uni', jp: 'してる。ただ、セキュリティに穴がないか心配。', en: 'It does. But I worry about security holes.', style: 'cautious techie raising a concern' },
    { speaker: 'riku_teen', jp: '通話を録音する機能もあるみたいだね。', en: 'It seems to have a call-recording feature too.', style: 'observant friend noting a feature' },
  ]),
  C('conv_03382', 'Troubleshooting an app that won’t launch', 'Fix a glitch; teach インストール/バージョン/プラス/マイナス/カラー/回転/穴/録音', 'office_quiet_low',
    ['インストール','バージョン','プラス','マイナス','カラー','回転','穴','録音'], ['riku_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: 'インストールしたのに、起動しないんだ。', en: 'I installed it, but it won’t launch.', style: 'frustrated friend reporting a bug' },
    { speaker: 'ren_uni', jp: 'バージョンが古いんじゃない？', en: 'Isn’t the version outdated?', style: 'diagnosing techie offering a guess' },
    { speaker: 'riku_teen', jp: '更新したら、プラスの変化があった。', en: 'After updating, there was a positive change.', style: 'relieved friend confirming' },
    { speaker: 'ren_uni', jp: '逆に、容量がマイナスになった気がする。', en: 'Conversely, storage feels like a minus now.', style: 'techie noting a tradeoff' },
    { speaker: 'riku_teen', jp: 'アイコンのカラーも変わったね。', en: 'The icon color changed too.', style: 'observant friend noticing' },
    { speaker: 'ren_uni', jp: '設定で画面の回転をロックできるよ。', en: 'You can lock screen rotation in settings.', style: 'helpful techie advising' },
    { speaker: 'riku_teen', jp: 'バグっていう穴を、開発者が埋めたのかな。', en: 'Maybe the devs patched the bug holes.', style: 'speculating friend musing' },
    { speaker: 'ren_uni', jp: '操作画面を録音して、報告するといいよ。', en: 'Record the screen and report it — that helps.', style: 'practical techie suggesting' },
  ]),
  C('conv_03383', 'Reviewing a new device', 'Review a gadget; teach インストール/バージョン/プラス/マイナス/カラー/回転/穴/録音', 'office_quiet_low',
    ['インストール','バージョン','プラス','マイナス','カラー','回転','穴','録音'], ['ren_uni', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: 'この新しいデバイス、どう？', en: 'How’s this new device?', style: 'curious reviewer opening' },
    { speaker: 'riku_teen', jp: 'アプリのインストールが簡単だった。', en: 'Installing apps was easy.', style: 'pleased reviewer noting ease' },
    { speaker: 'ren_uni', jp: 'バージョンアップも自動なんだ。', en: 'Version upgrades are automatic too.', style: 'reviewer adding a plus' },
    { speaker: 'riku_teen', jp: '軽さはプラス評価だね。', en: 'The lightness is a plus point.', style: 'reviewer scoring it positively' },
    { speaker: 'ren_uni', jp: '値段が高いのはマイナスだけど。', en: 'The high price is a minus, though.', style: 'fair reviewer noting the con' },
    { speaker: 'riku_teen', jp: '画面のカラーが鮮やかでいい。', en: 'The screen color is vivid and nice.', style: 'appreciative reviewer praising it' },
    { speaker: 'ren_uni', jp: '縦横の回転もスムーズ。', en: 'Vertical-horizontal rotation is smooth too.', style: 'reviewer noting responsiveness' },
    { speaker: 'riku_teen', jp: '唯一、スピーカーに穴が少なくて音が小さい。', en: 'The one issue: few speaker holes, so it’s quiet.', style: 'reviewer flagging a flaw' },
    { speaker: 'ren_uni', jp: '動画の録音性能は高いみたいだよ。', en: 'Its video-recording performance seems high.', style: 'reviewer ending on a positive' },
  ]),
  C('conv_03384', 'Helping a parent set up a phone', 'Set up a phone; teach インストール/バージョン/プラス/マイナス/カラー/回転/穴/録音', 'living_room_quiet',
    ['インストール','バージョン','プラス','マイナス','カラー','回転','穴','録音'], ['riku_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: '親のスマホ、設定手伝ってよ。', en: 'Help me set up my parent’s phone.', style: 'friend asking for a hand' },
    { speaker: 'ren_uni', jp: 'まず必要なアプリをインストールしよう。', en: 'First, let’s install the needed apps.', style: 'methodical techie leading' },
    { speaker: 'riku_teen', jp: 'バージョンは最新でいい？', en: 'Should the version be the latest?', style: 'friend checking a step' },
    { speaker: 'ren_uni', jp: 'うん。文字を大きくすると、プラスに使いやすい。', en: 'Yes. Bigger text makes it a plus to use.', style: 'thoughtful techie advising' },
    { speaker: 'riku_teen', jp: '通知が多いのはマイナスだから、減らそう。', en: 'Lots of notifications is a minus, so let’s cut them.', style: 'friend tidying up' },
    { speaker: 'ren_uni', jp: '背景のカラーも見やすいものに。', en: 'Make the background color easy to read too.', style: 'techie refining the setup' },
    { speaker: 'riku_teen', jp: '画面の回転は固定したほうがいいね。', en: 'Better to lock screen rotation.', style: 'friend deciding practically' },
    { speaker: 'ren_uni', jp: '操作に穴があると困るから、丁寧に確認しよう。', en: 'Gaps in usability are trouble, so let’s check carefully.', style: 'careful techie urging diligence' },
    { speaker: 'riku_teen', jp: '説明を録音しておけば、後で見返せるよ。', en: 'If we record the instructions, we can review later.', style: 'practical friend planning ahead' },
  ]),
  C('conv_03385', 'Wrapping up the setup', 'Finish the setup; teach インストール/バージョン/プラス/マイナス/カラー/回転/穴/録音', 'living_room_quiet',
    ['インストール','バージョン','プラス','マイナス','カラー','回転','穴','録音'], ['ren_uni', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '今日のセットアップ、終わったね。', en: 'Today’s setup is done.', style: 'satisfied techie wrapping up' },
    { speaker: 'riku_teen', jp: '全部インストールできて、すっきり。', en: 'Everything’s installed — feels clean.', style: 'relieved friend exhaling' },
    { speaker: 'ren_uni', jp: 'バージョンも揃えたしね。', en: 'We aligned the versions too.', style: 'techie noting completeness' },
    { speaker: 'riku_teen', jp: '使い勝手は、断然プラスになった。', en: 'Usability became a clear plus.', style: 'pleased friend appraising' },
    { speaker: 'ren_uni', jp: '心配だったマイナス点も、解消できた。', en: 'We resolved the minus points we worried about.', style: 'techie confirming the fix' },
    { speaker: 'riku_teen', jp: 'カラーテーマも気に入ってもらえた。', en: 'They liked the color theme too.', style: 'happy friend reporting success' },
    { speaker: 'ren_uni', jp: '回転設定も完璧。', en: 'The rotation setting is perfect too.', style: 'techie ticking the last box' },
    { speaker: 'riku_teen', jp: 'もう操作に穴はないね。', en: 'There are no usability holes now.', style: 'confident friend concluding' },
    { speaker: 'ren_uni', jp: '念のため、手順を録音して残しておこう。', en: 'Just in case, let’s record the steps and keep them.', style: 'prudent techie finishing thoroughly' },
  ]),

  // ===== CLUSTER B: crime & legal news =====
  C('conv_03386', 'A class discusses a criminal trial in the news', 'Discuss a trial; teach 殺人/暴力/原告/代理/執行/恐怖/公表/怒り', 'lecture_hall_quiet',
    ['殺人','暴力','原告','代理','執行','恐怖','公表','怒り'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '今日は、ある裁判のニュースを取り上げます。', en: 'Today we take up the news of a certain trial.', style: 'serious teacher opening the topic' },
    { speaker: 'ren_uni', jp: '殺人事件の裁判ですよね。', en: 'It’s a murder trial, right?', style: 'informed student identifying it' },
    { speaker: 'sakura_teen', jp: '暴力的な犯行で、衝撃的でした。', en: 'A violent crime — it was shocking.', style: 'disturbed teen reacting' },
    { speaker: 'asuka_teacher', jp: '原告側は、厳しい処罰を求めています。', en: 'The plaintiff’s side seeks harsh punishment.', style: 'teacher relaying the stance' },
    { speaker: 'ren_uni', jp: '被告には、弁護士が代理で立っています。', en: 'A lawyer represents the defendant.', style: 'student noting the procedure' },
    { speaker: 'asuka_teacher', jp: '判決が出れば、刑の執行に進みます。', en: 'Once the verdict comes, it proceeds to sentencing.', style: 'teacher explaining the next step' },
    { speaker: 'sakura_teen', jp: '被害者の家族の恐怖は、計り知れません。', en: 'The victims’ family’s fear is immeasurable.', style: 'empathetic teen voicing compassion' },
    { speaker: 'asuka_teacher', jp: '裁判所は、判決を公表しました。', en: 'The court announced the verdict.', style: 'teacher stating the development' },
    { speaker: 'ren_uni', jp: '社会には、大きな怒りが広がっています。', en: 'Great anger spread through society.', style: 'student noting public reaction' },
  ]),
  C('conv_03387', 'Explaining how a trial proceeds', 'Explain procedure; teach 原告/殺人/暴力/代理/執行/恐怖/公表/怒り', 'lecture_hall_quiet',
    ['原告','殺人','暴力','代理','執行','恐怖','公表','怒り'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '裁判って、どう進むんですか？', en: 'How does a trial proceed?', style: 'curious student asking plainly' },
    { speaker: 'asuka_teacher', jp: 'まず原告が訴えを起こします。', en: 'First the plaintiff files suit.', style: 'teacher explaining step by step' },
    { speaker: 'ren_uni', jp: '殺人のような重い罪だと、慎重になりますね。', en: 'For grave crimes like murder, it’s cautious.', style: 'student grasping the gravity' },
    { speaker: 'asuka_teacher', jp: 'ええ、暴力事件は証拠が重要です。', en: 'Yes, in violent cases evidence is crucial.', style: 'teacher stressing a key point' },
    { speaker: 'ren_uni', jp: '弁護士が代理で主張するんですよね。', en: 'The lawyer argues on the client’s behalf, right?', style: 'student confirming' },
    { speaker: 'asuka_teacher', jp: 'そうです。判決後、執行までに時間がかかることも。', en: 'Right. After the verdict, enforcement can take time.', style: 'teacher adding nuance' },
    { speaker: 'ren_uni', jp: '被告が恐怖から自白する場合もあるとか。', en: 'Defendants sometimes confess out of fear.', style: 'student noting a human angle' },
    { speaker: 'asuka_teacher', jp: '判決は、原則として公表されます。', en: 'Verdicts are, in principle, made public.', style: 'teacher stating the rule' },
    { speaker: 'ren_uni', jp: '世間の怒りが、量刑に影響することは？', en: 'Does public anger affect sentencing?', style: 'student probing further' },
  ]),
  C('conv_03388', 'Students react to the case', 'React to a crime; teach 殺人/暴力/怒り/恐怖/原告/代理/執行/公表', 'living_room_quiet',
    ['殺人','暴力','怒り','恐怖','原告','代理','執行','公表'], ['sakura_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: 'あの殺人事件、こわすぎる。', en: 'That murder case is too scary.', style: 'shaken teen voicing unease' },
    { speaker: 'ren_uni', jp: '暴力には、本当に怒りを感じるよ。', en: 'Violence really makes me feel anger.', style: 'indignant friend reacting' },
    { speaker: 'sakura_teen', jp: '被害者を思うと、恐怖でいっぱい。', en: 'Thinking of the victim fills me with fear.', style: 'distressed teen empathizing' },
    { speaker: 'ren_uni', jp: '原告側の主張、もっともだと思う。', en: 'The plaintiff’s argument seems reasonable.', style: 'thoughtful friend taking a view' },
    { speaker: 'sakura_teen', jp: '加害者の代理人は、何を言うんだろう。', en: 'What will the perpetrator’s counsel say?', style: 'curious teen wondering' },
    { speaker: 'ren_uni', jp: '刑が執行されるまで、長いんだって。', en: 'It’s a long time until the sentence is carried out.', style: 'friend sharing a fact' },
    { speaker: 'sakura_teen', jp: '裁判所が情報を公表してくれて、少し安心した。', en: 'The court releasing info eased me a little.', style: 'relieved teen reflecting' },
  ]),
  C('conv_03389', 'Interviewing a legal expert', 'Interview an expert; teach 暴力/殺人/恐怖/原告/代理/執行/公表/怒り', 'studio_room_tone',
    ['暴力','殺人','恐怖','原告','代理','執行','公表','怒り'], ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '先生、暴力犯罪は減っているんですか？', en: 'Professor, are violent crimes decreasing?', style: 'prepared interviewer asking' },
    { speaker: 'asuka_teacher', jp: '統計上は減っていますが、殺人は依然深刻です。', en: 'Statistically yes, but murder remains grave.', style: 'expert giving a balanced answer' },
    { speaker: 'sakura_teen', jp: '被害者の恐怖を、社会はどう支えますか？', en: 'How does society support victims’ fear?', style: 'interviewer probing compassion' },
    { speaker: 'asuka_teacher', jp: '原告を支援する制度が整いつつあります。', en: 'Systems to support plaintiffs are taking shape.', style: 'expert noting progress' },
    { speaker: 'sakura_teen', jp: '代理人の役割も大きいですね。', en: 'The role of counsel is big too.', style: 'interviewer acknowledging' },
    { speaker: 'asuka_teacher', jp: 'ええ、刑の執行の透明性も求められています。', en: 'Yes, transparency in enforcement is demanded too.', style: 'expert raising another issue' },
    { speaker: 'sakura_teen', jp: '判決の公表は、抑止につながりますか？', en: 'Does publishing verdicts deter crime?', style: 'interviewer pursuing the point' },
    { speaker: 'asuka_teacher', jp: '人々の怒りを、再発防止に向けることが大切です。', en: 'Channeling people’s anger toward prevention matters.', style: 'expert offering a constructive close' },
  ]),
  C('conv_03390', 'Reflecting on the justice unit', 'Reflect on justice; teach 殺人/暴力/原告/代理/執行/恐怖/公表/怒り', 'lecture_hall_quiet',
    ['殺人','暴力','原告','代理','執行','恐怖','公表','怒り'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '司法の単元、考えさせられましたね。', en: 'The justice unit was thought-provoking.', style: 'reflective teacher closing' },
    { speaker: 'ren_uni', jp: '殺人のような罪に、社会はどう向き合うか。', en: 'How society faces crimes like murder.', style: 'pensive student framing it' },
    { speaker: 'sakura_teen', jp: '暴力のない社会を、願わずにいられません。', en: 'I can’t help wishing for a violence-free society.', style: 'earnest teen voicing hope' },
    { speaker: 'asuka_teacher', jp: '原告も被告も、公正に扱われるべきです。', en: 'Both plaintiff and defendant deserve fairness.', style: 'teacher stating a principle' },
    { speaker: 'ren_uni', jp: '代理人の存在が、権利を守るんですね。', en: 'Counsel protects people’s rights.', style: 'student appreciating the role' },
    { speaker: 'sakura_teen', jp: '刑の執行には、慎重さが要りますね。', en: 'Carrying out sentences needs care.', style: 'thoughtful teen noting' },
    { speaker: 'asuka_teacher', jp: '恐怖で人を支配してはいけません。', en: 'We mustn’t rule people through fear.', style: 'teacher offering a moral' },
    { speaker: 'ren_uni', jp: '真実の公表が、信頼を生むと思います。', en: 'Publishing the truth builds trust, I think.', style: 'student articulating a view' },
    { speaker: 'sakura_teen', jp: '怒りを、より良い社会への力に変えたいです。', en: 'I want to turn anger into power for a better society.', style: 'hopeful teen closing strongly' },
  ]),

  // ===== CLUSTER C: school life & manga club =====
  C('conv_03391', 'New school year and club choices', 'Start the school year; teach 入学/所属/ともかく/連載/日曜日/翌日/割合/育成', 'living_room_quiet',
    ['入学','所属','ともかく','連載','日曜日','翌日','割合','育成'], ['sakura_teen', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: 'もうすぐ入学式だね。', en: 'The entrance ceremony is soon.', style: 'excited teen anticipating' },
    { speaker: 'riku_teen', jp: 'どの部活に所属する？', en: 'Which club will you join?', style: 'friend mulling options' },
    { speaker: 'sakura_teen', jp: '迷ってる。ともかく見学に行ってみる。', en: 'I’m unsure. Anyway, I’ll go observe.', style: 'undecided teen keeping it open' },
    { speaker: 'riku_teen', jp: '僕は漫画研究会。連載作品を読むのが好きで。', en: 'I’m for the manga club. I love reading serials.', style: 'enthusiastic friend sharing his hobby' },
    { speaker: 'sakura_teen', jp: '日曜日に、新刊が出るやつ？', en: 'The ones that release new volumes on Sunday?', style: 'curious teen connecting' },
    { speaker: 'riku_teen', jp: 'そう。発売の翌日には、感想を語り合うんだ。', en: 'Yes. The day after release, we discuss impressions.', style: 'friend describing the routine' },
    { speaker: 'sakura_teen', jp: '新入生の割合、今年は多いみたいだよ。', en: 'The proportion of new students seems high this year.', style: 'teen sharing a tidbit' },
    { speaker: 'riku_teen', jp: '先輩として、後輩の育成もしなきゃね。', en: 'As a senior, I’ve got to nurture juniors too.', style: 'responsible friend resolving' },
  ]),
  C('conv_03392', 'Joining a literature club', 'Talk club life; teach 入学/所属/連載/日曜日/翌日/割合/ともかく/育成', 'living_room_quiet',
    ['入学','所属','連載','日曜日','翌日','割合','ともかく','育成'], ['riku_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: '入学してすぐ、何の部に入った？', en: 'Right after enrolling, which club did you join?', style: 'friend asking casually' },
    { speaker: 'ren_uni', jp: '文芸部に所属したよ。', en: 'I joined the literature club.', style: 'friend answering plainly' },
    { speaker: 'riku_teen', jp: '連載小説を書いてるって本当？', en: 'Is it true you write a serialized novel?', style: 'impressed friend probing' },
    { speaker: 'ren_uni', jp: 'うん。毎週日曜日に更新してる。', en: 'Yeah. I update every Sunday.', style: 'committed friend explaining' },
    { speaker: 'riku_teen', jp: 'すごい継続力だね。', en: 'That’s impressive persistence.', style: 'admiring friend praising' },
    { speaker: 'ren_uni', jp: '投稿した翌日に、感想が来るのが励みなんだ。', en: 'Getting feedback the day after posting motivates me.', style: 'friend sharing what drives him' },
    { speaker: 'riku_teen', jp: '読者の割合、増えてる？', en: 'Is the share of readers growing?', style: 'friend asking about reach' },
    { speaker: 'ren_uni', jp: '少しずつね。ともかく、書き続けるよ。', en: 'Bit by bit. Anyway, I’ll keep writing.', style: 'determined friend resolving' },
    { speaker: 'riku_teen', jp: '後輩の育成も、そろそろ考えたら？', en: 'Maybe start thinking about nurturing juniors too?', style: 'friend suggesting thoughtfully' },
  ]),
  C('conv_03393', 'Making weekend plans', 'Plan a weekend; teach 日曜日/ともかく/連載/翌日/所属/割合/入学/育成', 'cafe_quiet_chatter',
    ['日曜日','ともかく','連載','翌日','所属','割合','入学','育成'], ['sakura_teen', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '日曜日、暇？', en: 'Free on Sunday?', style: 'casual teen reaching out' },
    { speaker: 'riku_teen', jp: 'ともかく、宿題を終わらせてからだな。', en: 'Anyway, after I finish homework.', style: 'practical friend hedging' },
    { speaker: 'sakura_teen', jp: '例の連載漫画、最新話読んだ？', en: 'Did you read the latest of that serial manga?', style: 'eager teen changing topic' },
    { speaker: 'riku_teen', jp: '読んだ！ 翌日まで余韻が残ったよ。', en: 'I did! The aftertaste lingered into the next day.', style: 'enthusiastic friend gushing' },
    { speaker: 'sakura_teen', jp: '部活、どっちに所属するか決めた？', en: 'Did you decide which club to join?', style: 'teen following up' },
    { speaker: 'riku_teen', jp: 'まだ。新入生の割合を見てから。', en: 'Not yet. After seeing the new-student ratio.', style: 'cautious friend deferring' },
    { speaker: 'sakura_teen', jp: '入学したばかりだもんね、焦らなくていいよ。', en: 'You just enrolled, no need to rush.', style: 'reassuring teen' },
    { speaker: 'riku_teen', jp: '上手な先輩に、育成してもらいたいな。', en: 'I’d like a skilled senior to nurture me.', style: 'hopeful friend wishing' },
  ]),
  C('conv_03394', 'A year in the soccer club', 'Reflect on a sport; teach 所属/入学/育成/日曜日/翌日/割合/ともかく/連載', 'living_room_quiet',
    ['所属','入学','育成','日曜日','翌日','割合','ともかく','連載'], ['ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: 'サッカー部に所属して、もう一年か。', en: 'A year already in the soccer club, huh.', style: 'reflective friend marking time' },
    { speaker: 'sakura_teen', jp: '入学のときは、初心者だったよね。', en: 'You were a beginner when you enrolled.', style: 'friend reminiscing' },
    { speaker: 'ren_uni', jp: 'コーチの育成のおかげで、上達したよ。', en: 'Thanks to the coach’s nurturing, I improved.', style: 'grateful friend crediting' },
    { speaker: 'sakura_teen', jp: '試合は日曜日が多いの？', en: 'Are matches mostly on Sunday?', style: 'curious friend asking' },
    { speaker: 'ren_uni', jp: 'うん。勝った翌日は、気分がいいね。', en: 'Yeah. The day after a win feels great.', style: 'happy friend recalling' },
    { speaker: 'sakura_teen', jp: 'レギュラーの割合、どれくらい？', en: 'What’s the ratio of regulars?', style: 'friend probing competition' },
    { speaker: 'ren_uni', jp: '半分くらいかな。ともかく、練習あるのみ。', en: 'About half. Anyway, it’s all practice.', style: 'determined friend resolving' },
    { speaker: 'sakura_teen', jp: '部の活動、漫画雑誌の連載みたいに毎週だね。', en: 'Club activity is weekly, like a magazine serial.', style: 'playful friend drawing a comparison' },
  ]),
  C('conv_03395', 'End-of-term reflection among friends', 'Reflect on the year; teach 入学/所属/連載/日曜日/翌日/割合/ともかく/育成', 'cafe_quiet_chatter',
    ['入学','所属','連載','日曜日','翌日','割合','ともかく','育成'], ['sakura_teen', 'riku_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '入学してから、あっという間だったね。', en: 'It flew by since we enrolled.', style: 'wistful teen reflecting' },
    { speaker: 'riku_teen', jp: '部活に所属して、世界が広がった。', en: 'Joining a club widened my world.', style: 'grateful friend sharing' },
    { speaker: 'ren_uni', jp: '連載を最後まで書き切ったのが、自信になった。', en: 'Finishing my serial became confidence.', style: 'proud friend recalling an achievement' },
    { speaker: 'sakura_teen', jp: '日曜日ごとの活動が、いい思い出。', en: 'The Sunday activities are good memories.', style: 'fond teen reminiscing' },
    { speaker: 'riku_teen', jp: '大会の翌日に、みんなで打ち上げしたね。', en: 'The day after the tournament, we all celebrated.', style: 'happy friend recalling' },
    { speaker: 'ren_uni', jp: '出場できた割合は低かったけど、満足だ。', en: 'My play time ratio was low, but I’m satisfied.', style: 'content friend accepting' },
    { speaker: 'sakura_teen', jp: 'ともかく、来年も頑張ろう。', en: 'Anyway, let’s do our best next year too.', style: 'upbeat teen rallying' },
    { speaker: 'riku_teen', jp: '後輩の育成も、引き継いでいこう。', en: 'Let’s carry on nurturing the juniors too.', style: 'responsible friend committing' },
  ]),

  // ===== CLUSTER D: religion & culture documentary =====
  C('conv_03396', 'A documentary on the history of Christianity', 'Discuss religious history; teach キリスト教/聖書/魂/犠牲/移行/いったい/もはや/ふと', 'living_room_quiet',
    ['キリスト教','聖書','魂','犠牲','移行','いったい','もはや','ふと'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '今日はキリスト教の歴史を学びます。', en: 'Today we study the history of Christianity.', style: 'measured teacher opening' },
    { speaker: 'ren_uni', jp: '聖書は、世界で最も読まれた本ですよね。', en: 'The Bible is the most-read book in the world, right?', style: 'engaged student noting a fact' },
    { speaker: 'sakura_teen', jp: '人は、魂の救いを求めてきたんですね。', en: 'People have sought salvation of the soul.', style: 'reflective teen musing' },
    { speaker: 'asuka_teacher', jp: 'ええ、信仰のために犠牲を払う人もいました。', en: 'Yes, some made sacrifices for their faith.', style: 'teacher conveying gravity' },
    { speaker: 'ren_uni', jp: '時代と共に、信仰の形態も移行してきました。', en: 'With the times, forms of faith shifted too.', style: 'student noting change' },
    { speaker: 'sakura_teen', jp: 'いったい、何が人々を支えたんでしょう。', en: 'What on earth sustained people?', style: 'wondering teen asking earnestly' },
    { speaker: 'asuka_teacher', jp: '苦難の中でも、希望はもはや失われませんでした。', en: 'Even in hardship, hope was no longer lost.', style: 'teacher offering a moving thought' },
    { speaker: 'ren_uni', jp: 'ふと、自分の生き方を考えさせられます。', en: 'It suddenly makes me reflect on my own life.', style: 'pensive student turning inward' },
  ]),
  C('conv_03397', 'Discussing faith in modern society', 'Discuss faith today; teach 移行/キリスト教/聖書/魂/もはや/犠牲/いったい/ふと', 'living_room_quiet',
    ['移行','キリスト教','聖書','魂','もはや','犠牲','いったい','ふと'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '現代では、宗教の役割は変わりましたか？', en: 'Has religion’s role changed in modern times?', style: 'curious student opening' },
    { speaker: 'asuka_teacher', jp: 'ええ、社会の価値観が移行しています。', en: 'Yes, society’s values are shifting.', style: 'teacher answering thoughtfully' },
    { speaker: 'ren_uni', jp: 'キリスト教の信者も、昔とは違うんですね。', en: 'Christians too differ from the past.', style: 'student observing' },
    { speaker: 'asuka_teacher', jp: '聖書の解釈も、多様になりました。', en: 'Interpretations of the Bible diversified too.', style: 'teacher adding nuance' },
    { speaker: 'ren_uni', jp: '魂という概念は、今も大切にされていますか？', en: 'Is the concept of the soul still valued?', style: 'student probing deeper' },
    { speaker: 'asuka_teacher', jp: 'ええ、もはや一部の人だけのものではありません。', en: 'Yes, it’s no longer only for a few.', style: 'teacher widening the view' },
    { speaker: 'ren_uni', jp: '信仰のために犠牲を払う意味とは、いったい何でしょう。', en: 'What on earth is the meaning of sacrifice for faith?', style: 'student asking searchingly' },
    { speaker: 'asuka_teacher', jp: 'ふと立ち止まって、考える価値がありますね。', en: 'It’s worth pausing suddenly to think.', style: 'teacher offering a reflective close' },
  ]),
  C('conv_03398', 'A student reflects on religion', 'Reflect on belief; teach 聖書/キリスト教/魂/犠牲/移行/いったい/もはや/ふと', 'lecture_hall_quiet',
    ['聖書','キリスト教','魂','犠牲','移行','いったい','もはや','ふと'], ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '先生、宗教って難しいです。', en: 'Teacher, religion is hard.', style: 'honest teen confessing' },
    { speaker: 'asuka_teacher', jp: 'そうですね。聖書を一度読んでみるといい。', en: 'Indeed. It’s good to read the Bible once.', style: 'gentle teacher advising' },
    { speaker: 'sakura_teen', jp: 'キリスト教だけでなく、いろんな宗教がありますよね。', en: 'Not just Christianity — there are many religions.', style: 'curious teen broadening' },
    { speaker: 'asuka_teacher', jp: 'ええ、どれも魂の問題に向き合っています。', en: 'Yes, all face the question of the soul.', style: 'teacher unifying the idea' },
    { speaker: 'sakura_teen', jp: '信者は、何を犠牲にしてきたんですか？', en: 'What have believers sacrificed?', style: 'teen probing earnestly' },
    { speaker: 'asuka_teacher', jp: '時には命を。価値観が移行する中でもね。', en: 'Sometimes their lives — even as values shifted.', style: 'teacher conveying solemnity' },
    { speaker: 'sakura_teen', jp: 'いったい、信じるとはどういうことなんでしょう。', en: 'What on earth does it mean to believe?', style: 'searching teen wondering' },
    { speaker: 'asuka_teacher', jp: 'もはや答えは一つではありません。ふと感じる心が大事です。', en: 'There’s no longer a single answer. The heart that suddenly feels matters.', style: 'teacher offering wisdom' },
  ]),
  C('conv_03399', 'Looking at religious art', 'Discuss art and faith; teach キリスト教/聖書/魂/犠牲/移行/いったい/もはや/ふと', 'museum_hall_quiet',
    ['キリスト教','聖書','魂','犠牲','移行','いったい','もはや','ふと'], ['ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: 'この絵画、キリスト教がテーマなんだって。', en: 'This painting’s theme is Christianity, they say.', style: 'informed friend at a gallery' },
    { speaker: 'sakura_teen', jp: '聖書の場面を描いてるんだね。', en: 'It depicts a Bible scene.', style: 'observant friend recognizing it' },
    { speaker: 'ren_uni', jp: '人物の表情に、魂が宿ってるみたい。', en: 'The figures’ faces seem to hold a soul.', style: 'moved friend admiring' },
    { speaker: 'sakura_teen', jp: '殉教者の犠牲が、テーマなのかな。', en: 'Maybe the theme is the martyrs’ sacrifice.', style: 'thoughtful friend interpreting' },
    { speaker: 'ren_uni', jp: '様式は、時代とともに移行していったらしい。', en: 'The style apparently shifted with the eras.', style: 'friend adding context' },
    { speaker: 'sakura_teen', jp: 'いったい、画家は何を伝えたかったんだろう。', en: 'What on earth did the painter want to convey?', style: 'wondering friend musing' },
    { speaker: 'ren_uni', jp: 'もはや言葉では説明できない感動があるね。', en: 'There’s emotion words can no longer explain.', style: 'awed friend reflecting' },
    { speaker: 'sakura_teen', jp: 'ふと、心が静かになる気がする。', en: 'Suddenly my heart feels calm.', style: 'serene friend savoring it' },
  ]),
  C('conv_03400', 'Wrapping up the religion-and-culture unit', 'Summarize the unit; teach キリスト教/聖書/魂/犠牲/移行/いったい/もはや/ふと', 'lecture_hall_quiet',
    ['キリスト教','聖書','魂','犠牲','移行','いったい','もはや','ふと'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '宗教と文化の単元、いかがでしたか？', en: 'How was the religion-and-culture unit?', style: 'teacher inviting reflection' },
    { speaker: 'ren_uni', jp: 'キリスト教の影響の大きさに驚きました。', en: 'I was struck by Christianity’s vast influence.', style: 'impressed student sharing' },
    { speaker: 'sakura_teen', jp: '聖書の物語が、芸術に生きているんですね。', en: 'Bible stories live on in art.', style: 'appreciative teen noting' },
    { speaker: 'asuka_teacher', jp: '人の魂への問いは、普遍的です。', en: 'The question of the soul is universal.', style: 'teacher offering a unifying idea' },
    { speaker: 'ren_uni', jp: '犠牲の意味を、深く考えました。', en: 'I thought deeply about the meaning of sacrifice.', style: 'reflective student' },
    { speaker: 'sakura_teen', jp: '価値観の移行も、歴史の一部なんですね。', en: 'Shifting values are part of history too.', style: 'teen synthesizing' },
    { speaker: 'asuka_teacher', jp: 'いったい何を信じるかは、各自の自由です。', en: 'What on earth one believes is each person’s freedom.', style: 'teacher affirming autonomy' },
    { speaker: 'ren_uni', jp: 'もはや他人事とは思えません。', en: 'I can no longer see it as someone else’s matter.', style: 'moved student internalizing' },
    { speaker: 'sakura_teen', jp: 'ふと、自分の信念を見つめ直したくなりました。', en: 'I suddenly want to re-examine my own beliefs.', style: 'introspective teen closing' },
  ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_170 wrote', CONVERSATIONS.length, 'files');
