import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_133)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // N4 media finishers
  C('conv_02641',
    'Aoi and Riku talk about a new game release.',
    'WIDENED SCENARIO: entertainment chat; media vocabulary (シリーズ/タイトル/発売/ネタ/ランキング) in natural home.',
    'cafe_quiet_chatter',
    ['シリーズ', 'タイトル', '発売', 'ネタ', 'ランキング'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '新しいゲームが、ついに発売されたよ!', en: "The new game finally released!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'あの人気シリーズの、続きなの?', en: "Is it the sequel to that popular series?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、シリーズの最新作なんだ。', en: "Yeah, the latest in the series.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'タイトルは、何ていうの?', en: "What's the title?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'タイトルは、英語でかっこいいんだ。', en: "The title's in English and it's cool.", style: 'proud teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '発売初日の、ランキングは?', en: "What about the day-one rankings?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'ランキング一位で、話のネタになってるよ。', en: "It's number one and a hot topic.", style: 'thrilled teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '面白いネタ、もっと聞かせて!', en: "Tell me more fun bits!", style: 'cheerful barista voice, soft warm bubbly closing delivery throughout' },
    ]),

  C('conv_02642',
    'Media news: Sakura and Ren on a film\'s release.',
    'WIDENED SCENARIO: media news; media vocabulary (メディア/ビデオ/シーン/裏/発売) in natural home.',
    'studio_room_tone',
    ['メディア', 'ビデオ', 'シーン', '裏', '発売'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '話題の映画が、来週発売されます。', en: "The talked-about film releases next week.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'メディアでも、注目されていますね。', en: "The media is paying attention too.", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '特典のビデオも、付くそうです。', en: "A bonus video reportedly comes with it.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'そのビデオには、何が入っていますか?', en: "What's in that video?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '撮影の裏側のシーンが、入っています。', en: "It includes behind-the-scenes footage.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '裏のシーンは、ファンに嬉しいですね。', en: "Behind-the-scenes shots delight fans.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '発売後、メディアの評価が楽しみです。', en: "After release, I look forward to media reviews.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '名シーンが、また話題になりそうですね。', en: "The famous scenes will be talked about again.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02643',
    'Aoi and Mei discuss a video series.',
    'WIDENED SCENARIO: entertainment chat; media vocabulary (ビデオ/シーン/裏/ネタ/シリーズ) in natural home.',
    'cafe_quiet_chatter',
    ['ビデオ', 'シーン', '裏', 'ネタ', 'シリーズ'],
    ['aoi_barista', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'あのビデオシリーズ、見終わった?', en: "Did you finish that video series?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、最後のシーンで泣いちゃった。', en: "Yeah, I cried at the final scene.", style: 'soft emotional woman voice, gentle warm tender delivery throughout' },
      { speaker: 'aoi_barista', jp: '裏話のビデオも、あるんだよ。', en: "There's a behind-the-scenes video too.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '裏の話は、面白いネタが多いよね。', en: "The behind-the-scenes has lots of fun bits.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'あのシーンの裏側、知りたいな。', en: "I want to know the backstory of that scene.", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'シリーズの最初から、見直したいな。', en: "I want to rewatch the series from the start.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '次のシリーズの、ネタも気になるね。', en: "I'm curious about the next series' material too.", style: 'cheerful barista voice, soft warm bubbly closing delivery throughout' },
    ]),

  // N4 civic finishers + N3 会見
  C('conv_02644',
    'Political news: Sakura and Ren on a president\'s press conference.',
    'WIDENED SCENARIO: political news; civic vocabulary (大統領/審議/設置/会見/メディア) in natural home.',
    'studio_room_tone',
    ['大統領', '審議', '設置', '会見', 'メディア'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '大統領が、記者会見を開きました。', en: "The president held a press conference.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '会見で、何を発表したんですか?', en: "What did he announce at the conference?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '新しい委員会の設置を、発表しました。', en: "He announced the establishment of a new committee.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'その委員会は、何を審議しますか?', en: "What will that committee deliberate?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '環境の政策を、審議する予定です。', en: "It's set to deliberate environmental policy.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'メディアの反応は、どうでしたか?', en: "How did the media react?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '会見の様子を、各メディアが伝えました。', en: "Each media outlet covered the conference.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '設置後の審議に、注目したいですね。', en: "I'd like to watch the deliberation after it's set up.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02645',
    'Documentary discussion: Asuka and Ren on a leader\'s legacy.',
    'WIDENED SCENARIO: documentary discussion; civic vocabulary (大統領/設置/審議/会見/財産) in natural home.',
    'living_room_quiet',
    ['大統領', '設置', '審議', '会見', '財産'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この大統領は、何を残したんですか?', en: "What did this president leave behind?", style: 'thoughtful young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: '多くの機関を、設置しました。', en: "He established many institutions.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '長い審議の末に、決めたんですか?', en: "Did he decide after long deliberation?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、慎重な審議を重ねました。', en: "Yes, he repeated careful deliberation.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '会見では、どう語ったんですか?', en: "How did he speak at his conferences?", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '会見で、国民の財産を守ると述べました。', en: "At conferences, he vowed to protect citizens' assets.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '国の財産を、大切にしたんですね。', en: "So he valued the nation's assets.", style: 'understanding young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'その大統領の決断が、今も生きています。', en: "That president's decisions live on today.", style: 'warm teacher voice, soft warm measured clarity closing throughout' },
    ]),

  // N4 adverb finishers + N3 ところで, ガ(メガネ)
  C('conv_02646',
    'Mei and Aoi chat over coffee.',
    'Casual register; adverbs/daily (どうも/いれ/ところで/メガネ/おいしい) in natural home.',
    'cafe_quiet_chatter',
    ['どうも', 'いれ', 'ところで', 'メガネ', 'おいしい'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'このケーキ、すごくおいしいね。', en: "This cake is really delicious.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'aoi_barista', jp: '砂糖を少し入れすぎたかも。', en: "I might have put in a bit too much sugar.", style: 'bright barista voice, soft warm sheepish delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ううん、どうも甘さがちょうどいいよ。', en: "No, the sweetness is somehow just right.", style: 'gentle woman voice, soft warm reassuring delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ところで、新しいメガネにしたの?', en: "By the way, did you get new glasses?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、メガネを変えてみたの。', en: "Yeah, I changed my glasses.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'どうも、その方が似合ってるよ。', en: "Somehow, those suit you better.", style: 'warm barista voice, soft warm complimentary delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ありがとう。コーヒー、もう一杯入れてくれる?', en: "Thanks. Could you pour me another coffee?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'もちろん!おいしいの、入れるね。', en: "Of course! I'll make a tasty one.", style: 'cheerful barista voice, soft warm bubbly closing delivery throughout' },
    ]),

  // N3 count-4: writing/lit
  C('conv_02647',
    'Asuka and Mei discuss an author\'s essay.',
    'WIDENED SCENARIO: literature chat; writing vocabulary (引用/解釈/著者/本質/配慮) in natural home.',
    'living_room_quiet',
    ['引用', '解釈', '著者', '本質', '配慮'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この著者の文章、深いですね。', en: "This author's writing is deep.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: '著者は、古い詩を引用していますね。', en: "The author quotes an old poem.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: 'その引用の解釈が、難しいです。', en: "The interpretation of that quote is hard.", style: 'thoughtful woman voice, soft warm curious delivery throughout' },
      { speaker: 'asuka_teacher', jp: '解釈は、人によって変わるものです。', en: "Interpretation varies by person.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '本質は、どこにあるんでしょう?', en: "Where does the essence lie?", style: 'gentle woman voice, soft warm engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: '本質は、読者への配慮にあります。', en: "The essence is in the consideration for the reader.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '配慮のある文章は、優しいですね。', en: "Writing with consideration is gentle.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '引用も、配慮の一つの形ですよ。', en: "Quotation is one form of consideration too.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_02648',
    'Asuka guides Ren on formatting a report.',
    'WIDENED SCENARIO: academic guidance; writing vocabulary (項目/欄/載せ/引用/著者) in natural home.',
    'lecture_hall_quiet',
    ['項目', '欄', '載せ', '引用', '著者'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'レポートの書き方を、教えて下さい。', en: "Please teach me how to write the report.", style: 'earnest young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'まず、項目ごとに分けましょう。', en: "First, let's divide it by item.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '参考にした著者は、どこに載せますか?', en: "Where do I list the authors I referenced?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '最後の欄に、著者名を載せます。', en: "You list author names in the final field.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '引用は、どう書けばいいですか?', en: "How should I write quotations?", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '引用は、はっきり区別して載せます。', en: "List quotations clearly distinguished.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '各項目に、欄を作るんですね。', en: "So I make a field for each item.", style: 'understanding young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '著者への敬意を、引用で示しましょう。', en: "Show respect to authors through quotation.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  // N3 count-4: business
  C('conv_02649',
    'Hiroshi-boss and Yuki review sales procedures.',
    'WIDENED SCENARIO: business ops; sales vocabulary (売上/手続き/設け/専用/複数) in natural home.',
    'office_quiet_low',
    ['売上', '手続き', '設け', '専用', '複数'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '今月の売上は、どうだったかね?', en: "How were this month's sales?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '複数の店舗で、売上が伸びました。', en: "Sales rose at multiple stores.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '注文の手続きは、簡単になったかね?', en: "Did the order procedure get simpler?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'はい、専用の窓口を設けました。', en: "Yes, we set up a dedicated counter.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '専用の窓口で、手続きは速くなったね。', en: "With the dedicated counter, the procedure got faster.", style: 'satisfied boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '複数の支払い方法も、設けました。', en: "We also set up multiple payment methods.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '売上の管理は、しっかり頼むよ。', en: "Please manage sales carefully.", style: 'firm boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '手続きを、もっと簡単にしていきます。', en: "I'll keep simplifying the procedures.", style: 'resolved office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02650',
    'Hiroshi-boss and Ren plan multiple new outlets.',
    'WIDENED SCENARIO: business strategy; vocabulary (手続/財産/複数/売上/設け) in natural home.',
    'office_quiet_low',
    ['手続', '財産', '複数', '売上', '設け'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '複数の地域に、店を設けたい。', en: "I want to open stores in multiple regions.", style: 'decisive boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '開店の手続は、進んでいますか?', en: "Are the opening procedures progressing?", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '手続は、順調に進んでいる。', en: "The procedures are progressing well.", style: 'measured boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '会社の財産は、十分ですか?', en: "Are the company's assets sufficient?", style: 'thoughtful young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '財産を慎重に使い、複数を設ける。', en: "We'll use assets carefully and open several.", style: 'firm boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '売上の見込みは、明るいですか?', en: "Is the sales outlook bright?", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '複数の店で、売上が増えるはずだ。', en: "With several stores, sales should grow.", style: 'confident boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '手続を、確実に進めます。', en: "I'll carry out the procedures reliably.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  // N3 count-4: medical
  C('conv_02651',
    'Saito explains a treatment to a patient.',
    'WIDENED SCENARIO: medical explanation; clinical vocabulary (医師/配慮/下げ/上げる/終わる) in natural home.',
    'clinic_room_quiet',
    ['医師', '配慮', '下げ', '上げる', '終わる'],
    ['saito_doctor', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '先生、血圧が高いんです。', en: "Doctor, my blood pressure is high.", style: 'worried office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '医師として、少し下げたいですね。', en: "As your doctor, I'd like to lower it a bit.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: '薬で、下げるんですか?', en: "Do you lower it with medicine?", style: 'curious office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: 'まず、運動で下げてみましょう。', en: "First, let's try lowering it with exercise.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'kenji_office', jp: '効果が上がるまで、どのくらい?', en: "How long until the effect rises?", style: 'attentive office man voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '効果が上がるには、数週間かかります。', en: "It takes a few weeks for the effect to rise.", style: 'clear doctor voice, soft warm measured clarity throughout' },
      { speaker: 'kenji_office', jp: '治療は、いつ終わるんですか?', en: "When does the treatment end?", style: 'concerned office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '医師として、丁寧に配慮しながら進めます。', en: "As your doctor, I'll proceed with careful consideration.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),

  // N3 count-4: food/home
  C('conv_02652',
    'Yumiko and Sho cook dinner together.',
    'Casual home register; food/daily vocabulary (おいしい/カレー/鍵/送る/出かけ) in natural home.',
    'kitchen_evening_quiet',
    ['おいしい', 'カレー', '鍵', '送る', '出かけ'],
    ['yumiko_mom', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'yumiko_mom', jp: '今日は、おいしいカレーを作るわよ。', en: "Today I'll make delicious curry.", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: 'やった!カレー大好き!', en: "Yay! I love curry!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'お父さんを、駅まで迎えに行くわ。', en: "I'll go pick up Dad at the station.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '鍵、忘れないでね!', en: "Don't forget the keys!", style: 'earnest small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'ありがとう。鍵は、ちゃんと持ったわ。', en: "Thanks. I've got the keys.", style: 'warm mother voice, soft warm affectionate delivery throughout' },
      { speaker: 'sho_child', jp: '出かける前に、味見させて!', en: "Let me taste it before you leave!", style: 'eager small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '出かけたら、すぐ戻るからね。', en: "Once I leave, I'll be right back.", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: 'カレーできたら、写真送ってね!', en: "Send a photo when the curry's done!", style: 'playful small child voice, bright warm cheerful closing delivery throughout' },
    ]),

  C('conv_02653',
    'Grandma and Sho tidy the entrance.',
    'Casual home register; daily vocabulary (板/石/鍵/出かけ/終わる) in natural home.',
    'tatami_room_quiet',
    ['板', '石', '鍵', '出かけ', '終わる'],
    ['sachiko_grandma', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sachiko_grandma', jp: '玄関の板を、拭いておきましょうね。', en: "Let's wipe the entrance floorboard.", style: 'tender grandmother voice, soft warm gentle patient delivery throughout' },
      { speaker: 'sho_child', jp: 'この石、外に置くの?', en: "Do we put this stone outside?", style: 'curious small child voice, bright warm earnest delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'そうね、石は庭に戻しましょう。', en: "Yes, let's return the stone to the garden.", style: 'tender grandmother voice, soft warm gentle delivery throughout' },
      { speaker: 'sho_child', jp: '鍵は、どこに置けばいい?', en: "Where should I put the keys?", style: 'helpful small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '鍵は、板の上の箱に入れてね。', en: "Put the keys in the box on the board.", style: 'gentle grandmother voice, soft warm patient delivery throughout' },
      { speaker: 'sho_child', jp: '掃除が終わったら、出かけてもいい?', en: "When we're done cleaning, can I go out?", style: 'eager small child voice, bright warm delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '終わったら、一緒に出かけましょうね。', en: "When it's done, let's go out together.", style: 'tender grandmother voice, soft warm affectionate delivery throughout' },
      { speaker: 'sho_child', jp: 'やった!早く終わらせよう!', en: "Yay! Let's finish quickly!", style: 'enthusiastic small child voice, bright warm bouncing closing delivery throughout' },
    ]),

  // N3 count-4: nature/science
  C('conv_02654',
    'Asuka and Riku watch a nature documentary.',
    'WIDENED SCENARIO: nature discussion; vocabulary (太陽/巨大/見事/低/石) in natural home.',
    'living_room_quiet',
    ['太陽', '巨大', '見事', '低', '石'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '先生、この山、すごく巨大ですね!', en: "Teacher, this mountain is huge!", style: 'amazed teen boy voice, soft warm wonder engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、巨大な岩が積み重なっています。', en: "Yes, massive rocks are piled up.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '太陽の光が、石を照らして見事ですね。', en: "The sunlight on the stones is splendid.", style: 'impressed teen boy voice, soft warm admiring throughout' },
      { speaker: 'asuka_teacher', jp: '見事な眺めですね。太陽の角度が低いです。', en: "A splendid view. The sun's angle is low.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '低い太陽だと、影が長いですね。', en: "With a low sun, the shadows are long.", style: 'observant teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'その石は、長い年月で削られました。', en: "Those stones were carved over long ages.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '自然の力って、見事ですね。', en: "Nature's power is magnificent.", style: 'moved teen boy voice, soft warm wonder throughout' },
      { speaker: 'asuka_teacher', jp: '巨大な自然の前では、人は小さいですね。', en: "Before vast nature, humans are small.", style: 'warm teacher voice, soft warm measured reflective closing clarity throughout' },
    ]),

  // N3 count-4: sports/music
  C('conv_02655',
    'Aoi and Riku talk about a sports star and a band.',
    'WIDENED SCENARIO: hobby chat; vocabulary (ゴルフ/バンド/活躍/見事/送る) in natural home.',
    'cafe_quiet_chatter',
    ['ゴルフ', 'バンド', '活躍', '見事', '送る'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'あのゴルフ選手、優勝したよ!', en: "That golfer won the championship!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: '若いのに、すごい活躍だね!', en: "Such great success for someone so young!", style: 'impressed barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '最後のショットが、見事だったんだ。', en: "The final shot was magnificent.", style: 'enthusiastic teen boy voice, bright warm admiring delivery throughout' },
      { speaker: 'aoi_barista', jp: '私は、あのバンドの活躍が気になるな。', en: "I'm more into that band's success.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'バンドも、見事な演奏だったよね。', en: "The band's performance was splendid too.", style: 'agreeable teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '応援のメッセージ、送ろうかな。', en: "Maybe I'll send a message of support.", style: 'warm barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'いいね、僕もゴルフ選手に送るよ。', en: "Nice, I'll send one to the golfer too.", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '二人の活躍、これからも楽しみだね!', en: "I look forward to both their successes!", style: 'cheerful barista voice, soft warm bubbly closing delivery throughout' },
    ]),

  // N3 count-4: tech online + 勧め, オン
  C('conv_02656',
    'Kenji recommends an online tool to Ren.',
    'WIDENED SCENARIO: tech chat; vocabulary (オンライン/専用/項目/載せ/勧め) in natural home.',
    'office_quiet_low',
    ['オンライン', '専用', '項目', '載せ', '勧め'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: 'このオンラインの道具、お勧めですよ。', en: "I recommend this online tool.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'オンラインで、何ができるんですか?', en: "What can it do online?", style: 'curious young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: '専用の画面で、項目を管理できます。', en: "On a dedicated screen, you can manage items.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '項目は、自由に載せられますか?', en: "Can I freely add items?", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、好きな項目を載せられます。', en: "Yes, you can add any items you like.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '専用のアプリも、あるんですか?', en: "Is there a dedicated app too?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、オンラインでもアプリでも使えます。', en: "Yes, you can use it online or via the app.", style: 'reassuring office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'お勧め通り、使ってみます。', en: "I'll try it as you recommend.", style: 'satisfied young colleague voice, soft warm appreciative closing throughout' },
    ]),

  // N3 count-3 doublers + 無かっ, ちゃい
  C('conv_02657',
    'Ren and Mei recall a trip where things went wrong.',
    'Casual register; vocabulary (無かっ/ちゃい/何とか/余裕/遠く) in natural home.',
    'cafe_quiet_chatter',
    ['何とか', '余裕', '遠く', '驚き', '真剣'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの旅行、電車が無かったよね。', en: "On that trip, there were no trains.", style: 'soft warm woman voice, gentle amused delivery throughout' },
      { speaker: 'ren_uni', jp: 'うん、最終に乗り遅れちゃった。', en: "Yeah, we missed the last one.", style: 'rueful young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '遠くまで、歩く羽目になったね。', en: "We ended up walking far.", style: 'gentle woman voice, soft warm reminiscing delivery throughout' },
      { speaker: 'ren_uni', jp: '何とか、宿には着いたよね。', en: "We somehow made it to the inn.", style: 'relieved young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '時間に余裕が、全然無かったの。', en: "We had no time to spare at all.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '君が真剣に地図を見てて、驚いたよ。', en: "I was surprised how seriously you read the map.", style: 'warm young man voice, soft warm fond delivery throughout' },
      { speaker: 'mei_romantic', jp: 'あの驚きの旅、また話そうね。', en: "Let's talk about that surprising trip again.", style: 'gentle woman voice, soft warm affectionate delivery throughout' },
      { speaker: 'ren_uni', jp: '今思えば、余裕を持つべきだったね。', en: "Looking back, we should've left more room.", style: 'reflective young man voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02658',
    'Ren interviews a researcher about preventing problems.',
    'WIDENED SCENARIO: research interview; vocabulary (証拠/防止/分類/品質/成果) in natural home.',
    'office_quiet_low',
    ['証拠', '防止', '分類', '品質', '成果'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '研究の成果は、出ましたか?', en: "Have the research results come in?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、はっきりした証拠が得られました。', en: "Yes, we obtained clear evidence.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: 'その証拠は、何を防止しますか?', en: "What does that evidence help prevent?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '事故の防止に、役立ちます。', en: "It helps prevent accidents.", style: 'patient researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: 'データは、どう分類したんですか?', en: "How did you classify the data?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '品質ごとに、丁寧に分類しました。', en: "We carefully classified it by quality.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '品質の高さが、成果を支えたんですね。', en: "High quality supported the results.", style: 'understanding young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '防止の成果を、社会に役立てたいです。', en: "I want the prevention results to serve society.", style: 'warm researcher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02659',
    'Asuka discusses creative writing methods with Sakura.',
    'WIDENED SCENARIO: writing lecture; vocabulary (やり方/創造/見方/新規/信用) in natural home.',
    'lecture_hall_quiet',
    ['やり方', '創造', '見方', '新規', '信用'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '物語の作り方が、分からなくて。', en: "I can't figure out how to make a story.", style: 'troubled adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'やり方は、一つではありませんよ。', en: "There's more than one way.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '創造には、何が必要ですか?', en: "What does creation require?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '新しい見方を、持つことが創造の鍵です。', en: "Holding a new perspective is the key to creation.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '新規の発想は、どう生まれますか?', en: "How do novel ideas arise?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '日常を、別の見方で見るんです。', en: "You see the everyday from a different view.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '自分のやり方を、信用していいですか?', en: "Can I trust my own way?", style: 'earnest adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、自分を信用して、創造を続けて。', en: "Yes, trust yourself and keep creating.", style: 'warm teacher voice, soft warm measured encouraging closing clarity throughout' },
    ]),

  C('conv_02660',
    'Asuka and Ren discuss a postwar history documentary.',
    'WIDENED SCENARIO: history discussion; vocabulary (戦後/かつて/思想/背景/過程) in natural home.',
    'living_room_quiet',
    ['戦後', 'かつて', '思想', '背景', '過程'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '戦後の日本は、大きく変わったんですね。', en: "Postwar Japan changed greatly.", style: 'thoughtful young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、かつての価値観が揺らぎました。', en: "Yes, former values were shaken.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '新しい思想も、広がったんですか?', en: "Did new ideologies spread too?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '戦後、様々な思想が生まれました。', en: "After the war, various ideologies emerged.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'その背景には、何があったんですか?', en: "What was behind that?", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '復興の過程が、背景にあります。', en: "The process of recovery is the background.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'かつての日本を、過程から学べますね。', en: "We can learn about former Japan from the process.", style: 'understanding young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: '背景を知ると、戦後がよく見えますよ。', en: "Knowing the background, the postwar era becomes clear.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_133 wrote', CONVERSATIONS.length, 'files');
