import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_136)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // ADVERB cluster (3 convs, each dense)
  C('conv_02701',
    'Mei and Aoi chat after a hectic shift.',
    'Casual register; adverbs (ちなみに/こうした/既に/さすが/あまりに/そうした/それでも) in natural home.',
    'cafe_quiet_chatter',
    ['ちなみに', 'こうした', '既に', 'さすが', 'あまりに'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '今日は、あまりに忙しかったね。', en: "Today was far too busy.", style: 'bright tired barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'お昼には、既に満席だったもんね。', en: "It was already full by noon.", style: 'soft warm woman voice, gentle delivery throughout' },
      { speaker: 'aoi_barista', jp: 'こうした日は、本当に疲れるね。', en: "Days like this are really tiring.", style: 'warm barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'それでも、あなたは笑顔だったね。', en: "Even so, you kept smiling.", style: 'gentle woman voice, soft warm admiring delivery throughout' },
      { speaker: 'aoi_barista', jp: 'さすが、あなたも落ち着いてたよ。', en: "As expected, you stayed calm too.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ちなみに、明日も予約が多いの。', en: "By the way, tomorrow has many reservations too.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そうした日は、早めに準備しよう。', en: "On such days, let's prep early.", style: 'engaged barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '既に、ある程度は仕込んであるよ。', en: "I've already prepped to some extent.", style: 'gentle woman voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02702',
    'Asuka opens a lecture and frames examples.',
    'WIDENED SCENARIO: lecture; adverbs (ちなみに/こうした/既に/さすが/あまりに/そうした/といった/おそらく) in natural home.',
    'lecture_hall_quiet',
    ['ちなみに', 'こうした', '既に', 'といった', 'おそらく'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'こうした問いには、答えが多くあります。', en: "Such questions have many answers.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '既に、習った内容もありますか?', en: "Is some content already covered?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ちなみに、前回の続きから入ります。', en: "By the way, we pick up from last time.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '歴史といった例も、出ますか?', en: "Will examples like history come up?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'おそらく、芸術といった分野も触れます。', en: "We'll probably touch fields like art too.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'さすが、幅広い授業ですね。', en: "As expected, a broad lesson.", style: 'admiring adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'あまりに広げすぎないよう、注意します。', en: "I'll be careful not to spread too thin.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'そうした配慮が、ありがたいです。', en: "Such consideration is appreciated.", style: 'grateful adult student voice, soft warm closing throughout' },
    ]),

  C('conv_02703',
    'Kenji and Ren weigh a cautious release step.',
    'WIDENED SCENARIO: work chat; adverbs (少なくとも/おそらく/一応/それでも/といった) in natural home.',
    'office_quiet_low',
    ['少なくとも', 'おそらく', '一応', 'それでも', 'あまりに'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この機能、今日入れて大丈夫ですか?', en: "Is it okay to add this feature today?", style: 'cautious young colleague voice, soft warm earnest throughout' },
      { speaker: 'kenji_office', jp: '一応、テストしてからにしましょう。', en: "Let's test it first, just in case.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'それでも、急いだ方がいいですか?', en: "Even so, should we hurry?", style: 'concerned young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'おそらく、明日でも間に合いますよ。', en: "We'll probably still make it tomorrow.", style: 'calm office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '少なくとも、半日は要りますね。', en: "It needs at least half a day.", style: 'thoughtful young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '急ぎすぎると、あまりに危ないです。', en: "Rushing too much is far too risky.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'それでも、計画通りに進めたいです。', en: "Even so, I want to proceed as planned.", style: 'resolved young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '一応、上司にも一報を入れましょう。', en: "Just in case, let's notify the boss.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // SOCIETY cluster (3 convs)
  C('conv_02704',
    'Documentary discussion: Asuka and Ren on a society\'s growth.',
    'WIDENED SCENARIO: documentary discussion; vocabulary (われわれ/北朝鮮/宗教/自ら/発展) in natural home.',
    'living_room_quiet',
    ['われわれ', '北朝鮮', '宗教', '自ら', '発展'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この地域は、どう発展したんですか?', en: "How did this region develop?", style: 'curious young man voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '人々が、自ら道を開きました。', en: "People opened the path themselves.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '宗教も、発展に関わったんですか?', en: "Did religion play a part in the growth?", style: 'engaged young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、宗教が人々を支えました。', en: "Yes, religion supported the people.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: '北朝鮮は、別の道でしたか?', en: "Did North Korea take a different path?", style: 'thoughtful young man voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '北朝鮮は、独自の発展をしました。', en: "North Korea developed in its own way.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'われわれは、何を学べますか?', en: "What can we learn?", style: 'engaged young man voice, soft warm reflective throughout' },
      { speaker: 'asuka_teacher', jp: 'われわれも、自ら考え続けるべきですね。', en: "We too should keep thinking for ourselves.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02705',
    'News discussion: Sakura and Ren on a society feature.',
    'WIDENED SCENARIO: news-analysis; vocabulary (われわれ/北朝鮮/宗教/自ら/様々) in natural home.',
    'studio_room_tone',
    ['われわれ', '北朝鮮', '宗教', '自ら', '様々'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '今日は、様々な社会を特集します。', en: "Today we feature various societies.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '北朝鮮の状況も、扱うんですか?', en: "Will you cover North Korea's situation too?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、北朝鮮を含め、様々に触れます。', en: "Yes, we'll touch on various places, including North Korea.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '宗教の役割も、国で違いますね。', en: "Religion's role differs by country too.", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '宗教は、様々な形で根付いています。', en: "Religion takes root in various forms.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: 'われわれは、偏見なく見たいですね。', en: "We want to look without prejudice.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '人々が自ら選んだ道を、尊重しましょう。', en: "Let's respect the paths people chose themselves.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'われわれの視点も、問い直したいですね。', en: "We want to re-examine our own perspective too.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02706',
    'Documentary discussion: Asuka and Sakura on national identity.',
    'WIDENED SCENARIO: documentary discussion; vocabulary (われわれ/北朝鮮/自ら/発展/様々) in natural home.',
    'living_room_quiet',
    ['われわれ', '北朝鮮', '自ら', '発展', '様々'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '国の発展には、何が要るんでしょう?', en: "What does a nation's development require?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '様々な力が、発展を支えます。', en: "Various forces support development.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '北朝鮮も、発展を目指したんですか?', en: "Did North Korea aim for development too?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '北朝鮮も、自らの形を選びました。', en: "North Korea too chose its own form.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'われわれの国は、どうでしょう?', en: "What about our nation?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'われわれも、様々な選択をしてきました。', en: "We too have made various choices.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '自ら学ぶことが、大切なんですね。', en: "Learning for ourselves is important.", style: 'understanding adult student voice, soft warm realization throughout' },
      { speaker: 'asuka_teacher', jp: '様々な歴史から、自ら考えましょう。', en: "From various histories, let's think for ourselves.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  // LABOR/CIVIC cluster (3 convs)
  C('conv_02707',
    'Yuki and Hiroshi-boss discuss joining an association.',
    'WIDENED SCENARIO: business briefing; vocabulary (会員/組合/協会/官/いれ) in natural home.',
    'office_quiet_low',
    ['会員', '組合', '協会', '官', 'いれ'],
    ['yuki_office', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '業界の協会に、力を入れたいです。', en: "I'd like to invest in the industry association.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '会員になると、利点はあるのかね?', en: "Are there benefits to becoming members?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '会員は、情報を手に入れやすいです。', en: "Members get information easily.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '組合とは、役割が違うのかね?', en: "Does it differ in role from a union?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'ええ、組合とは目的が違います。', en: "Yes, its purpose differs from a union's.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '官との窓口も、あるのかね?', en: "Is there a channel to officials too?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '協会が、官との橋渡しを入れてくれます。', en: "The association bridges us to officials.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'では、会員として力を入れよう。', en: "Then let's commit as members.", style: 'decisive boss voice, soft warm closing clarity throughout' },
    ]),

  C('conv_02708',
    'Civic news: Sakura and Ren on a labor bill.',
    'WIDENED SCENARIO: civic news; vocabulary (会員/組合/協会/国会/指定) in natural home.',
    'studio_room_tone',
    ['会員', '組合', '協会', '国会', '指定'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '国会で、労働の法案が議論されました。', en: "A labor bill was debated in the Diet.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '労働組合は、賛成していますか?', en: "Does the labor union support it?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '組合は、慎重な立場です。', en: "The union takes a cautious stance.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '業界の協会は、どう見ていますか?', en: "How does the industry association view it?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '協会の会員は、賛否が分かれています。', en: "Association members are split.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '指定の業種にも、影響しますか?', en: "Does it affect designated industries too?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、指定の業種が対象です。', en: "Yes, designated industries are covered.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '国会での審議を、見守りましょう。', en: "Let's watch the Diet deliberation.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02709',
    'Sakura interviews an official about a membership service.',
    'WIDENED SCENARIO: civic interview; vocabulary (会員/官/いれ/国会/指定) in natural home.',
    'office_quiet_low',
    ['会員', '官', 'いれ', '国会', '指定'],
    ['sakura_teen', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '新しい会員サービスについて、伺います。', en: "I'll ask about the new membership service.", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '会員の声を、丁寧に取り入れました。', en: "We carefully incorporated members' voices.", style: 'measured official voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '担当の官は、何名ですか?', en: "How many officials are in charge?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '官が数名、運営に力を入れています。', en: "A few officials are putting effort into running it.", style: 'professional official voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '指定の地域から、始めるんですか?', en: "Do you start from designated areas?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '指定地域で試し、会員を増やします。', en: "We test in designated areas and grow membership.", style: 'measured official voice, soft warm informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '国会でも、報告されるんですか?', en: "Is it reported to the Diet too?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'ええ、国会に進み具合を入れて報告します。', en: "Yes, we report progress to the Diet.", style: 'professional official voice, soft warm informative closing throughout' },
    ]),

  // N3 count-4 sweep (11 convs)
  C('conv_02710',
    'Asuka and Mei discuss a beloved author.',
    'WIDENED SCENARIO: culture chat; vocabulary (アルバム/読書/作者/本物/ショップ) in natural home.',
    'living_room_quiet',
    ['アルバム', '読書', '作者', '本物', 'ショップ'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '最近、読書が楽しくて仕方ないんです。', en: "Lately reading is so much fun.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'どの作者の本を、読むんですか?', en: "Which author's books do you read?", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '本物の文章を書く、作者が好きです。', en: "I like authors who write genuine prose.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'その作者の写真アルバムも、出ていますよ。', en: "That author's photo album is out too.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: 'アルバムは、どのショップにありますか?', en: "Which shop has the album?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '駅前のショップに、置いてありますよ。', en: "It's stocked at the shop by the station.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '本物の読書って、心が豊かになりますね。', en: "Genuine reading enriches the heart.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'アルバムを見て、読書がもっと深まりますよ。', en: "Seeing the album deepens the reading.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_02711',
    'Mei and Aoi react to a frustrating delay.',
    'Casual register; vocabulary (とっても/お知らせ/けっこう/不満/困る) in natural home.',
    'cafe_quiet_chatter',
    ['とっても', 'お知らせ', 'けっこう', '不満', '困る'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '配達が遅れて、けっこう困ってるの。', en: "The delivery's late, and it's quite a problem.", style: 'troubled barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'お知らせは、来てないの?', en: "Hasn't a notice come?", style: 'soft warm woman voice, gentle concerned delivery throughout' },
      { speaker: 'aoi_barista', jp: 'お知らせが、とっても遅いの。', en: "The notice is super late.", style: 'frustrated barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'それは、不満が残るね。', en: "That leaves you dissatisfied.", style: 'gentle woman voice, soft warm sympathetic delivery throughout' },
      { speaker: 'aoi_barista', jp: 'うん、けっこう不満なんだ。', en: "Yeah, I'm pretty dissatisfied.", style: 'grumbling barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '困った時は、電話してみよう。', en: "When troubled, let's try calling.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'とっても助かる。ありがとう。', en: "That helps a lot. Thank you.", style: 'grateful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'お知らせが来たら、教えてね。', en: "Let me know when the notice comes.", style: 'gentle woman voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02712',
    'Yumiko and Sho tidy a drawer and take photos.',
    'Casual home register; vocabulary (切れ/鏡/ノート/撮っ/開く) in natural home.',
    'kitchen_evening_quiet',
    ['切れ', '鏡', 'ノート', '撮っ', '開く'],
    ['yumiko_mom', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'yumiko_mom', jp: 'この引き出しを、開いてみましょう。', en: "Let's open this drawer.", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: '古いノートが、いっぱい出てきた!', en: "Lots of old notebooks came out!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'あら、ペンのインクが切れてるわね。', en: "Oh, the pen's ink has run out.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'このノート、写真に撮ってもいい?', en: "Can I take a photo of this notebook?", style: 'eager small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'いいわよ。鏡の前で撮りましょう。', en: "Sure. Let's photograph it by the mirror.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '鏡に、ノートが映ってる!', en: "The notebook's reflected in the mirror!", style: 'delighted small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'インクが切れたペンは、捨てましょうね。', en: "Let's toss the pen that ran out of ink.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'ノートを開くの、楽しいね!', en: "Opening notebooks is fun!", style: 'happy small child voice, bright warm cheerful closing delivery throughout' },
    ]),

  C('conv_02713',
    'Daichi and Mei enjoy a coastal view.',
    'WIDENED SCENARIO: travel chat; vocabulary (波/辺/眺め/各地/通っ) in natural home.',
    'street_quiet_distant',
    ['波', '辺', '眺め', '各地', '通っ'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'この辺の眺め、ほんまにええなあ。', en: "The view around here is really nice.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '波の音が、心地よいですね。', en: "The sound of the waves is soothing.", style: 'soft warm woman voice, gentle dreamy delivery throughout' },
      { speaker: 'daichi_kansai', jp: '各地を回ったけど、ここが一番や。', en: "I've toured many places, but here's the best.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'この道、前に通ったことあります?', en: "Have you passed this road before?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '昔、よくこの辺を通ったわ。', en: "I used to pass around here often.", style: 'nostalgic Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '波の眺めは、各地で違いますね。', en: "Wave views differ from place to place.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'この辺の波は、穏やかで好きや。', en: "I love how gentle the waves are here.", style: 'warm Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'また、この眺めを見に通いたいです。', en: "I'd like to keep coming for this view.", style: 'soft woman voice, gentle warm closing delivery throughout' },
    ]),

  C('conv_02714',
    'Riku tells Aoi about a surprising school day.',
    'Casual register; vocabulary (驚い/中学/それに/食べ物/ちゃい) in natural home.',
    'cafe_quiet_chatter',
    ['驚い', '中学', 'それに', '食べ物', '困る'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '中学の給食、急に変わって驚いたよ。', en: "The middle-school lunch suddenly changed; I was surprised.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'へえ、どんな食べ物になったの?', en: "Oh, what kind of food did it become?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '世界の食べ物が、出るようになったんだ。', en: "World foods started being served.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'それに、味はどうだったの?', en: "And how did it taste?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'それに、すごくおいしくて驚いたよ。', en: "And it was so good it surprised me.", style: 'delighted teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '苦手な食べ物は、困らなかった?', en: "Didn't disliked foods give you trouble?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '辛いのは、ちょっと困ったけどね。', en: "The spicy stuff was a bit of a problem.", style: 'rueful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '中学の給食、進化してるね!', en: "Middle-school lunches are evolving!", style: 'bubbly barista voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02715',
    'Ren and Kenji discuss a tech that connects people.',
    'WIDENED SCENARIO: tech chat; vocabulary (発達/つながり/細かい/開く/倫理) in natural home.',
    'office_quiet_low',
    ['発達', 'つながり', '細かい', '開く', '倫理'],
    ['ren_uni', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '技術の発達で、何が変わりますか?', en: "What changes with technological development?", style: 'engaged young colleague voice, soft warm curious throughout' },
      { speaker: 'kenji_office', jp: '人と人の、つながりが広がります。', en: "Connections between people widen.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '細かい設定も、必要ですか?', en: "Are fine settings needed too?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '細かい配慮が、信頼を開きます。', en: "Fine consideration opens trust.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '発達には、倫理も問われますね。', en: "Development raises ethical questions too.", style: 'thoughtful young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '倫理を守れば、つながりは健全です。', en: "If we uphold ethics, connections stay healthy.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '未来を開く、いい技術にしたいです。', en: "I want to make it a good tech that opens the future.", style: 'hopeful young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '細かい倫理まで、考えていきましょう。', en: "Let's think through to the fine ethics.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02716',
    'Hiroshi-boss and Ren prepare for interviews.',
    'WIDENED SCENARIO: business HR; vocabulary (面接/会う/社内/歓迎/つながり) in natural home.',
    'office_quiet_low',
    ['面接', '会う', '社内', '歓迎', 'つながり'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '来週、面接で候補者と会う。', en: "Next week we'll meet candidates in interviews.", style: 'composed boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '何名と、会うんですか?', en: "How many will we meet?", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '五名と会う。社内で行う予定だ。', en: "We'll meet five. We'll hold it in-house.", style: 'measured boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '社内の雰囲気も、伝えたいですね。', en: "I'd like to convey the in-house atmosphere too.", style: 'thoughtful young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'ああ、温かく歓迎しよう。', en: "Yes, let's welcome them warmly.", style: 'warm boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '面接で、人とのつながりを見たいです。', en: "In the interview, I want to see how they connect with people.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '社内のつながりも、紹介しよう。', en: "Let's introduce our in-house connections too.", style: 'composed boss voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '歓迎の準備を、進めます。', en: "I'll get the welcome ready.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_02717',
    'Aoi and Riku talk about music practice.',
    'Casual register; vocabulary (リズム/歌っ/暇/たっぷり/選択肢) in natural home.',
    'cafe_quiet_chatter',
    ['リズム', '歌っ', '暇', 'たっぷり', '選択肢'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '昨日、家でずっと歌ってたんだ。', en: "Yesterday I sang at home the whole time.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、暇があると音楽だね。', en: "Nice, free time means music for you.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'リズムを取るのが、楽しいんだ。', en: "Keeping the rhythm is fun.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '曲の選択肢が、たっぷりあるね。', en: "You've got plenty of song choices.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、選択肢が多すぎて迷うよ。', en: "Yeah, so many choices I can't decide.", style: 'playful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '暇な時に、一緒に歌おうよ。', en: "Let's sing together when we're free.", style: 'warm barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'リズムに乗って、たっぷり歌おう!', en: "Let's ride the rhythm and sing plenty!", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '暇を見つけて、練習しようね!', en: "Let's find free time and practice!", style: 'bubbly barista voice, soft warm closing delivery throughout' },
    ]),

  C('conv_02718',
    'Asuka and Riku tour a uniquely built old house.',
    'WIDENED SCENARIO: architecture visit; vocabulary (独自/組み合わせ/少々/建て/肩) in natural home.',
    'museum_hall_quiet',
    ['独自', '組み合わせ', '少々', '建て', '肩'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'この家、独自の形ですね。', en: "This house has a unique shape.", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、独自の方法で建てられました。', en: "Yes, it was built with a unique method.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '木と石の組み合わせが、面白いです。', en: "The combination of wood and stone is interesting.", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'その組み合わせが、独自の魅力です。', en: "That combination is its unique charm.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '天井が、少々低いですね。', en: "The ceiling is a little low.", style: 'observant teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '少々かがむと、肩がぶつかりますよ。', en: "If you stoop a little, your shoulder bumps it.", style: 'gentle teacher voice, soft warm measured clarity throughout' },
      { speaker: 'riku_teen', jp: '昔の人は、独自に工夫したんですね。', en: "People long ago devised things uniquely.", style: 'reflective teen boy voice, soft warm wonder throughout' },
      { speaker: 'asuka_teacher', jp: '木と土の組み合わせで、建てたんですよ。', en: "They built it combining wood and earth.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_02719',
    'Mei tells Ren about a place that changed.',
    'Casual register; vocabulary (激しい/まわり/戻り/底/なくなっ) in natural home.',
    'cafe_quiet_chatter',
    ['激しい', 'まわり', '戻り', '底', 'なくなっ'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '久しぶりに、故郷に戻ったの。', en: "I returned to my hometown after a long time.", style: 'soft warm woman voice, gentle nostalgic delivery throughout' },
      { speaker: 'ren_uni', jp: 'まわりは、変わっていた?', en: "Had the surroundings changed?", style: 'gentle young man voice, soft warm engaged delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、変化が激しくて驚いたの。', en: "Yeah, the change was so drastic it surprised me.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '昔の店は、まだあった?', en: "Were the old shops still there?", style: 'curious young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '好きだった店は、なくなっていたの。', en: "The shop I loved was gone.", style: 'wistful woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '川の底まで、見えるくらい澄んでた?', en: "Was it so clear you could see the riverbed?", style: 'gentle young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '川は、昔のまま底まで澄んでたよ。', en: "The river was clear to the bottom, just like before.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'また、まわりを一緒に歩いて戻りたいね。', en: "I'd like to walk the surroundings and return together again.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02720',
    'Asuka and Mei discuss a story\'s characters.',
    'WIDENED SCENARIO: literature chat; vocabulary (中村/木村/生まれる/らしく/祈り) in natural home.',
    'living_room_quiet',
    ['中村', '木村', '生まれる', 'らしく', '祈り'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この物語、中村という人物が魅力的です。', en: "In this story, a character named Nakamura is fascinating.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: '中村は、いかにも人間らしく描かれていますね。', en: "Nakamura is drawn so very human.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '友人の木村も、いい味を出していますね。', en: "His friend Kimura adds nice flavor too.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '木村は、優しさから生まれた人物です。', en: "Kimura is a character born from kindness.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '物語の終わりの祈りに、泣きました。', en: "I cried at the prayer at the story's end.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '中村の祈りは、静かで美しいですね。', en: "Nakamura's prayer is quiet and beautiful.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '人物が、生き生きと生まれていますね。', en: "The characters come vividly to life.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '木村らしく、最後まで優しかったですね。', en: "True to Kimura, he was kind to the end.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_136 wrote', CONVERSATIONS.length, 'files');
