import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_156)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // sensory cluster finish (腕 床 模様 詳しい 香り) ×2 + 楽しむ 胸 おっしゃる
  C('conv_03101',
    'Asuka and Mei admire a traditional craft.',
    'WIDENED SCENARIO: craft discussion; vocabulary (腕/床/模様/詳しい/香り) in natural home.',
    'living_room_quiet',
    ['腕', '床', '模様', '詳しい', '香り'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この織物、模様が細かくて素敵ですね。', en: "This textile's pattern is fine and lovely.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: '職人の腕が、よく表れていますね。', en: "The artisan's skill really shows.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '床に飾ると、部屋が華やぎますね。', en: "Placed on the floor, it brightens the room.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '先生は、模様の意味に詳しいですね。', en: "You're knowledgeable about the patterns' meanings.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: 'ほのかな香りも、しますね。', en: "It has a faint scent too.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '草木の香りが、染み込んでいますね。', en: "The scent of plants is steeped in it.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '見ていると、胸が温かくなります。', en: "Looking at it warms my heart.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '腕のいい職人が、おっしゃっていましたよ。', en: "A skilled artisan was saying so too.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_03102',
    'Aoi and Riku visit a craft fair.',
    'Casual register; vocabulary (腕/床/模様/詳しい/香り) in natural home.',
    'museum_hall_quiet',
    ['腕', '床', '模様', '詳しい', '香り'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'この器、模様がかっこいいね!', en: "This bowl's pattern is cool!", style: 'excited teen boy voice, bright warm engaged delivery throughout' },
      { speaker: 'aoi_barista', jp: '作った人、腕がいいんだね。', en: "The maker is skilled.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'お店の人、すごく詳しいよ。', en: "The shop person is really knowledgeable.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '木の床に、よく合いそうだね。', en: "It'd go well on a wooden floor.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'お香の香りも、いいね。', en: "The incense scent is nice too.", style: 'engaged teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '香りに包まれて、胸が落ち着くね。', en: "Wrapped in the scent, my heart settles.", style: 'soft barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'この模様、家でも楽しみたいな。', en: "I want to enjoy this pattern at home too.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '腕のいい作家さん、応援したいね!', en: "I want to support skilled artists!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  // count-2 tech cluster (補助 かける 動作 させる 送ら) ×3
  C('conv_03103',
    'Kenji helps Ren run an automation tool.',
    'WIDENED SCENARIO: tech help; vocabulary (補助/かける/動作/させる/送ら) in natural home.',
    'office_quiet_low',
    ['補助', 'かける', '動作', 'させる', '送ら'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この自動化、どう動かすんですか?', en: "How do I run this automation?", style: 'engaged young colleague voice, soft warm focused throughout' },
      { speaker: 'kenji_office', jp: '補助ツールを使えば、簡単に動作します。', en: "With the helper tool, it runs easily.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: '一気に、全部動作させられますか?', en: "Can I run it all at once?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、順に動作させましょう。', en: "Yes, let's run it in sequence.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: '結果は、メールで送らせますか?', en: "Shall I have it send results by email?", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '自動で送らせれば、手間が省けます。', en: "Having it auto-send saves effort.", style: 'measured office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: 'チェックに、時間をかけたいです。', en: "I want to spend time on the check.", style: 'reliable young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '補助があれば、安心して動作させられます。', en: "With the helper, you can run it with confidence.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_03104',
    'Saito guides Yuki through a rehab movement.',
    'WIDENED SCENARIO: medical/rehab; vocabulary (補助/かける/動作/させる/送ら) in natural home.',
    'clinic_room_quiet',
    ['補助', 'かける', '動作', 'させる', '送ら'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '先生、腕の動作が、ぎこちないんです。', en: "Doctor, my arm's movement is awkward.", style: 'concerned office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '補助の器具で、ゆっくり動作させましょう。', en: "Let's move it slowly with a support device.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: '力をかけても、大丈夫ですか?', en: "Is it okay to apply force?", style: 'curious office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '少しずつ、力をかけて動かして下さい。', en: "Please apply force gradually as you move.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: '記録は、後で送らせてもらえますか?', en: "May I have the record sent later?", style: 'attentive office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: 'ええ、データを送らせていただきます。', en: "Yes, I'll have the data sent to you.", style: 'clear doctor voice, soft warm measured clarity throughout' },
      { speaker: 'yuki_office', jp: '補助があると、安心して動かせます。', en: "With support, I can move it at ease.", style: 'relieved office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '焦らず、丁寧に動作させましょうね。', en: "Without rushing, let's move it carefully.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_03105',
    'Kenji and Yuki set up an auto-report system.',
    'WIDENED SCENARIO: office tech; vocabulary (補助/かける/動作/させる/送ら) in natural home.',
    'office_quiet_low',
    ['補助', 'かける', '動作', 'させる', '送ら'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '毎日の報告を、自動にできますか?', en: "Can daily reports be automated?", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'システムに、自動で送らせましょう。', en: "Let's have the system send them automatically.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '設定に、時間をかけますか?', en: "Will the setup take time?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '少し時間をかければ、すぐ動作します。', en: "With a little time, it'll run right away.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '補助の機能も、ありますか?', en: "Are there helper functions too?", style: 'curious office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'ええ、補助機能が動作を助けます。', en: "Yes, helper functions assist the operation.", style: 'measured office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '自動で送らせると、楽になりますね。', en: "Auto-sending makes it easy.", style: 'satisfied office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '正しく動作させれば、もう安心です。', en: "If it runs correctly, you're all set.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // count-1 cluster A — secondhand/travel (中古 高級 修理 列車 出会っ)
  C('conv_03106',
    'Daichi and Mei shop for a secondhand item.',
    'WIDENED SCENARIO: shopping chat; vocabulary (中古/高級/修理/列車/出会っ) in natural home.',
    'cafe_quiet_chatter',
    ['中古', '高級', '修理', '列車', '出会っ'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '中古のカメラ、ええの見つけたで。', en: "I found a nice secondhand camera.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '高級なやつは、高いですもんね。', en: "The high-end ones are expensive.", style: 'soft warm woman voice, gentle delivery throughout' },
      { speaker: 'daichi_kansai', jp: '中古でも、修理すれば長く使えるで。', en: "Even secondhand, repaired it lasts long.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'お店は、どこで出会ったんですか?', en: "Where did you come across the shop?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '列車で行った先の、古道具屋でな。', en: "At an antique shop where the train took me.", style: 'nostalgic Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '素敵な品に、出会えたんですね。', en: "You came across a lovely item.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '修理に出したら、新品みたいやで。', en: "After repair, it's like new.", style: 'enthusiastic Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '列車の旅で、宝物に出会えますね。', en: "On a train trip, you can find treasures.", style: 'soft woman voice, gentle warm cheerful closing delivery throughout' },
    ]),

  C('conv_03107',
    'Riku tells Aoi about a train trip find.',
    'Casual register; vocabulary (中古/高級/修理/列車/出会っ) in natural home.',
    'cafe_quiet_chatter',
    ['中古', '高級', '修理', '列車', '出会っ'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '古い列車に、乗ってきたよ!', en: "I rode an old train!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、どんな列車だったの?', en: "Nice, what kind of train?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '高級な内装で、びっくりしたよ。', en: "Luxurious interior — I was surprised.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '古い車両でも、きれいだったの?', en: "Even an old car, was it clean?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '丁寧に修理されてて、ピカピカだった。', en: "Carefully repaired, it was sparkling.", style: 'impressed teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '中古の車両も、大事にされてるんだね。', en: "Even old cars are treasured, huh.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '車内で、面白い人に出会ったんだ。', en: "I met an interesting person on board.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '列車の出会い、ロマンがあるね!', en: "Train encounters are romantic!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03108',
    'Sakura interviews a train restorer.',
    'WIDENED SCENARIO: hobby interview; vocabulary (中古/高級/修理/列車/出会っ) in natural home.',
    'office_quiet_low',
    ['中古', '高級', '修理', '列車', '出会っ'],
    ['sakura_teen', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '古い列車を、修理されているんですね。', en: "You repair old trains.", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'daichi_kansai', jp: 'そや、中古の車両を直しとるんよ。', en: "Yeah, I fix secondhand cars.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'sakura_teen', jp: 'この仕事に、どう出会ったんですか?', en: "How did you come across this work?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '子供の頃、列車に出会って夢中になってな。', en: "As a kid, I encountered trains and got hooked.", style: 'nostalgic Kansai man voice, warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '高級な車両も、扱うんですか?', en: "Do you handle luxury cars too?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '高級な列車も、中古から蘇らせるで。', en: "Even luxury trains, I revive from secondhand.", style: 'enthusiastic Kansai man voice, warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '修理で、大変なことは?', en: "What's hard about the repairs?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '部品との出会いが、一番難しいわ。', en: "Finding the right parts is the hardest.", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_03109',
    'Mei and Ren reminisce about a train journey.',
    'Casual register; vocabulary (中古/高級/修理/列車/出会っ) in natural home.',
    'cafe_quiet_chatter',
    ['中古', '高級', '修理', '列車', '出会っ'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '去年の列車旅、楽しかったね。', en: "Last year's train trip was fun.", style: 'soft warm woman voice, gentle nostalgic delivery throughout' },
      { speaker: 'ren_uni', jp: 'うん、古い列車に乗れて良かったね。', en: "Yeah, glad we rode the old train.", style: 'warm young man voice, soft warm reflective delivery throughout' },
      { speaker: 'mei_romantic', jp: '車内で、地元の方に出会ったよね。', en: "We met a local on board.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '高級な弁当も、おいしかったな。', en: "The premium bento was delicious too.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '中古の駅舎も、味があったね。', en: "The old station building had character too.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '修理されながら、残ってるのが素敵だね。', en: "It's lovely that it remains, repaired over time.", style: 'thoughtful young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'また、列車で旅したいな。', en: "I want to travel by train again.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '新しい出会いも、あるだろうね。', en: "There'll be new encounters too.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-1 cluster B — news/treaty (協定 同意 保有 全面 変動)
  C('conv_03110',
    'News: Sakura and Ren on an international agreement.',
    'WIDENED SCENARIO: world-news analysis; vocabulary (協定/同意/保有/全面/変動) in natural home.',
    'studio_room_tone',
    ['協定', '同意', '保有', '全面', '変動'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '新しい協定が、結ばれました。', en: "A new agreement was concluded.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '各国の同意は、得られたんですか?', en: "Was each nation's consent obtained?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '主要国が、全面的に同意しました。', en: "Major nations fully consented.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '資源の保有量も、議題でしたか?', en: "Were resource holdings on the agenda too?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、保有量を巡って、議論されました。', en: "Yes, holdings were debated.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '価格の変動は、収まりますか?', en: "Will price fluctuations settle?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '協定で、変動が抑えられる見込みです。', en: "The agreement is expected to curb fluctuations.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '全面的な合意が、続くといいですね。', en: "I hope the full agreement holds.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_03111',
    'Asuka lectures on treaties and resources.',
    'WIDENED SCENARIO: economics lecture; vocabulary (協定/同意/保有/全面/変動) in natural home.',
    'lecture_hall_quiet',
    ['協定', '同意', '保有', '全面', '変動'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '協定は、国同士の同意で成り立ちます。', en: "Agreements rest on consent between nations.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '全面的な同意は、難しいんですか?', en: "Is full consent difficult?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '全面の同意には、長い交渉が要ります。', en: "Full consent requires long negotiation.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '資源の保有が、関係しますか?', en: "Do resource holdings relate to it?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '保有量の差が、交渉を難しくします。', en: "Differences in holdings complicate negotiation.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '価格の変動も、影響しますか?', en: "Do price fluctuations affect it too?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '変動が大きいと、協定が揺らぎます。', en: "Large fluctuations shake agreements.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '協定の難しさ、よく分かりました。', en: "I understand the difficulty of agreements.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_03112',
    'Hiroshi-boss and Ren weigh a partnership pact.',
    'WIDENED SCENARIO: business strategy; vocabulary (協定/同意/保有/全面/変動) in natural home.',
    'office_quiet_low',
    ['協定', '同意', '保有', '全面', '変動'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '提携の協定を、結びたいと思う。', en: "I want to form a partnership agreement.", style: 'composed boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '相手の同意は、得られそうですか?', en: "Can we get the partner's consent?", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '全面的に、同意してくれそうだ。', en: "They seem likely to fully consent.", style: 'measured boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '株式の保有は、どうしますか?', en: "What about share holdings?", style: 'thoughtful young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '互いに、株を保有し合おう。', en: "Let's hold each other's shares.", style: 'firm boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '相場の変動が、リスクですね。', en: "Market fluctuations are a risk.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '変動に備えた協定に、しよう。', en: "Let's make an agreement that prepares for fluctuations.", style: 'composed boss voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '全面の合意を、目指します。', en: "I'll aim for full agreement.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_03113',
    'Ren interviews a trade negotiator.',
    'WIDENED SCENARIO: expert interview; vocabulary (協定/同意/保有/全面/変動) in natural home.',
    'office_quiet_low',
    ['協定', '同意', '保有', '全面', '変動'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '協定をまとめるコツは、何ですか?', en: "What's the knack for forming agreements?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: '小さな同意を、積み重ねることです。', en: "It's accumulating small consents.", style: 'composed negotiator voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '全面の同意は、いつ得られますか?', en: "When is full consent obtained?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '信頼が育てば、全面の同意に至ります。', en: "When trust grows, full consent is reached.", style: 'patient negotiator voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '資源の保有も、論点ですか?', en: "Are resource holdings a point too?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '保有の公平さが、鍵になります。', en: "Fairness of holdings becomes the key.", style: 'composed negotiator voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '情勢の変動には、どう備えますか?', en: "How do you prepare for shifting conditions?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '変動を見越して、協定を結びます。', en: "We form agreements anticipating fluctuations.", style: 'warm negotiator voice, soft warm measured closing clarity throughout' },
    ]),

  // count-1 cluster C — abstract/system (体系 性能 至る 伴う 充分)
  C('conv_03114',
    'Asuka lectures on knowledge as a system.',
    'WIDENED SCENARIO: lecture; vocabulary (体系/性能/至る/伴う/充分) in natural home.',
    'lecture_hall_quiet',
    ['体系', '性能', '至る', '伴う', '充分'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '知識は、体系として学ぶと身につきます。', en: "Knowledge sticks when learned as a system.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '体系を作るのは、難しいですか?', en: "Is building a system difficult?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '体系には、努力が伴います。', en: "A system is accompanied by effort.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '理解に至るまで、時間がかかりますね。', en: "It takes time to reach understanding.", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '充分に時間をかければ、理解に至ります。', en: "With enough time, you reach understanding.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '道具の性能も、関係しますか?', en: "Does tool performance relate too?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '性能の良い辞書は、学びを助けます。', en: "A high-performance dictionary aids learning.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '体系的に、充分学びたいです。', en: "I want to learn systematically and fully.", style: 'resolved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_03115',
    'Ren interviews an engineer about performance.',
    'WIDENED SCENARIO: tech interview; vocabulary (体系/性能/至る/伴う/充分) in natural home.',
    'office_quiet_low',
    ['体系', '性能', '至る', '伴う', '充分'],
    ['ren_uni', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この機械の性能は、どうですか?', en: "How is this machine's performance?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'kenji_office', jp: '性能は、十分に高いですよ。', en: "The performance is sufficiently high.", style: 'measured engineer voice, soft warm informative clarity throughout' },
      { speaker: 'ren_uni', jp: '開発には、苦労が伴いましたか?', en: "Did development involve struggles?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'kenji_office', jp: '多くの試行錯誤が、伴いました。', en: "It was accompanied by much trial and error.", style: 'clear engineer voice, soft warm informative clarity throughout' },
      { speaker: 'ren_uni', jp: '完成に至るまで、長かったですか?', en: "Was it long to reach completion?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'kenji_office', jp: '完成に至るまで、三年かかりました。', en: "It took three years to reach completion.", style: 'measured engineer voice, soft warm informative clarity throughout' },
      { speaker: 'ren_uni', jp: '設計は、体系的なんですね。', en: "The design is systematic.", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'kenji_office', jp: '体系を整えれば、性能も安定します。', en: "Order the system and performance stabilizes.", style: 'warm engineer voice, soft warm informative closing clarity throughout' },
    ]),

  C('conv_03116',
    'Hiroshi-boss and Ren assess a product\'s readiness.',
    'WIDENED SCENARIO: business review; vocabulary (体系/性能/至る/伴う/充分) in natural home.',
    'office_quiet_low',
    ['体系', '性能', '至る', '伴う', '充分'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '製品の性能は、十分かね?', en: "Is the product's performance sufficient?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '性能は、充分に達しています。', en: "Performance has sufficiently reached the mark.", style: 'reliable young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '発売に至るまで、課題はあるかね?', en: "Are there issues before reaching launch?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '宣伝の手間が、伴います。', en: "Promotion effort is involved.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '管理の体系は、整っているかね?', en: "Is the management system in order?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '体系を整え、充分に備えました。', en: "I ordered the system and prepared fully.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'リスクも、伴うのを忘れずにな。', en: "Don't forget risk is involved too.", style: 'firm boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '成功に至るよう、全力を尽くします。', en: "I'll do my utmost to reach success.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_03117',
    'Ren and Asuka discuss a study method.',
    'WIDENED SCENARIO: academic chat; vocabulary (体系/性能/至る/伴う/充分) in natural home.',
    'lecture_hall_quiet',
    ['体系', '性能', '至る', '伴う', '充分'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '勉強を、体系的にしたいんです。', en: "I want to study systematically.", style: 'earnest young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '体系を作るには、計画が伴います。', en: "Building a system involves planning.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '充分な時間が、取れるか心配です。', en: "I'm worried whether I can take sufficient time.", style: 'troubled young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '短くても、充分に集中すれば十分です。', en: "Even short, if you focus fully, it's enough.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '辞書の性能も、大事ですか?', en: "Does the dictionary's quality matter too?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '良い辞書は、理解に至る助けになります。', en: "A good dictionary helps you reach understanding.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '努力が伴えば、必ず伸びますね。', en: "If effort accompanies it, I'll surely grow.", style: 'motivated young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '体系を信じて、続けましょう。', en: "Trust the system and keep going.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  // count-1 cluster D (partial, 3 convs) — names/casual (太郎 加藤 あたし 辞書 そういえば)
  C('conv_03118',
    'Mei and Aoi chat about a mutual friend.',
    'Casual register; vocabulary (太郎/加藤/あたし/辞書/そういえば) in natural home.',
    'cafe_quiet_chatter',
    ['太郎', '加藤', 'あたし', '辞書', 'そういえば'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'そういえば、太郎くん、元気にしてる?', en: "Come to think of it, how's Taro doing?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、太郎くん、最近よく会うの。', en: "Yeah, I see Taro a lot lately.", style: 'soft warm woman voice, gentle delivery throughout' },
      { speaker: 'aoi_barista', jp: '加藤さんとは、まだ仲いいの?', en: "Are you still close with Kato?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '加藤さんとも、よく勉強してるよ。', en: "I study with Kato a lot too.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'あたしも、また混ぜてよ。', en: "Let me join in again too.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'もちろん!あたし、辞書持ってくね。', en: "Of course! I'll bring a dictionary.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そういえば、いい辞書、探してたよね。', en: "Come to think of it, you were looking for a good dictionary.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '太郎くんが、おすすめを教えてくれたの。', en: "Taro told me a recommendation.", style: 'gentle woman voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03119',
    'Riku and Aoi study together with friends.',
    'Casual register; vocabulary (太郎/加藤/あたし/辞書/そういえば) in natural home.',
    'cafe_quiet_chatter',
    ['太郎', '加藤', 'あたし', '辞書', 'そういえば'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '今日、太郎と勉強会したよ。', en: "Today I had a study session with Taro.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、加藤くんも来たの?', en: "Nice, did Kato come too?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、加藤も辞書を持ってきたよ。', en: "Yeah, Kato brought a dictionary too.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'あたしの辞書、古いんだよね。', en: "My dictionary is old, you know.", style: 'sheepish barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'そういえば、太郎が新しいの勧めてたよ。', en: "Come to think of it, Taro recommended a new one.", style: 'engaged teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'へえ、あたしも見てみようかな。', en: "Oh, maybe I'll check it out too.", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '加藤が、辞書の使い方も詳しいんだ。', en: "Kato's also knowledgeable about using dictionaries.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そういえば、次はあたしも行く!', en: "Come to think of it, I'll come next time too!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03120',
    'Yumiko and Sho talk about a school friend.',
    'Casual home register; vocabulary (太郎/加藤/あたし/辞書/そういえば) in natural home.',
    'kitchen_evening_quiet',
    ['太郎', '加藤', 'あたし', '辞書', 'そういえば'],
    ['sho_child', 'yumiko_mom'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'ママ、今日、太郎くんと遊んだよ!', en: "Mom, I played with Taro today!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'あら、太郎くんと仲良しなのね。', en: "Oh, you're good friends with Taro.", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: '加藤先生が、絵本を読んでくれたよ。', en: "Mr. Kato read us a picture book.", style: 'cheerful small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '加藤先生、優しいわよね。', en: "Mr. Kato is kind, isn't he.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'そういえば、難しい言葉があったんだ。', en: "Come to think of it, there was a hard word.", style: 'thoughtful small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'じゃあ、辞書で調べてみましょうか。', en: "Then shall we look it up in a dictionary?", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'うん!太郎くんにも教えてあげる!', en: "Yeah! I'll teach Taro too!", style: 'happy small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '辞書を引くのが、上手になったわね。', en: "You've gotten good at using a dictionary.", style: 'tender mother voice, soft warm affectionate closing delivery throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_156 wrote', CONVERSATIONS.length, 'files');
