import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_095)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01886',
    context: 'Sho-young tells Daichi about a kid being unfair at school.',
    purpose: 'Father teaching son about justice and fairness.',
    ambient: 'porch_evening_low',
    sound_effects: [],
    target_vocab: ['不公平', '友達', '正義', '勇気'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、不公平、嫌い!', en: "Dad — unfair, hate!", style: 'soft frustrated child boy voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、何があったん?', en: "Yeah — what happened?", style: 'gentle Kansai father voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: '友達、誰かに、いじめられた。', en: "Friend — by someone, bullied.", style: 'soft sad child boy voice, warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前、どうした?', en: "You — what did?", style: 'soft Kansai father voice, warm engaged inquiry delivered carefully' },
      { speaker: 'sho_child', jp: '何も、できなかった。', en: "Nothing — couldn't.", style: 'tearful child boy voice, soft warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '勇気要るな、でも大事や。', en: "Courage needed — but important.", style: 'gentle Kansai father voice, soft warm wise delivery carefully' },
      { speaker: 'sho_child', jp: '次は、頑張ってみる。', en: "Next — I'll try.", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_01887',
    context: 'Aoi confides in Kenji about feelings of jealousy toward a colleague.',
    purpose: 'Wife sharing complicated feelings with husband.',
    ambient: 'bedroom_lamp_quiet',
    sound_effects: [],
    target_vocab: ['嫉妬', '気持ち', '正直', '受け入れる'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、恥ずかしいけど、嫉妬してる。', en: "Ken-chan — embarrassed, but jealous.", style: 'soft adult woman voice, warm raw honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'え、誰に?', en: "Eh — to whom?", style: 'soft Kansai husband voice, warm caring engaged delivery carefully' },
      { speaker: 'aoi_barista', jp: '同僚の成功、羨ましくて。', en: "Colleague success — envious.", style: 'tender adult woman voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: '正直な気持ち、ええんやで。', en: "Honest feelings — fine.", style: 'warm Kansai husband voice, soft warm reassuring delivery carefully' },
      { speaker: 'aoi_barista', jp: '自分、嫌になる。', en: "Self — hate.", style: 'soft adult woman voice, warm vulnerable delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前のペース、あるんや。', en: "Your pace — exists.", style: 'tender Kansai husband voice, soft warm wise delivery carefully' },
      { speaker: 'aoi_barista', jp: 'ありがとう、受け入れてくれて。', en: "Thanks — accepting.", style: 'soft adult woman voice, warm tender grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01888',
    context: 'Hina-young talks to Sakura about her admiration for a famous author.',
    purpose: 'Teen sharing role-model love with adult mentor.',
    ambient: 'living_room_evening_low',
    sound_effects: [],
    target_vocab: ['憧れ', '尊敬', '作家', '夢'],
    cast: ['hina_child', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、憧れの作家、いる。', en: "Sakura — admired author, exists.", style: 'soft teen girl voice, warm dreamy delivery carefully' },
      { speaker: 'sakura_teen', jp: 'まあ、誰?', en: "Oh — who?", style: 'gentle adult writer voice, soft warm curious delivery carefully' },
      { speaker: 'hina_child', jp: '尊敬してる作家、有名な人。', en: "Respected author — famous.", style: 'soft teen girl voice, warm earnest delivery carefully' },
      { speaker: 'sakura_teen', jp: '夢、近づけるかもね。', en: "Dream — can near.", style: 'warm adult writer voice, soft fond encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、頑張る!', en: "Yeah — try!", style: 'bright teen girl voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_01889',
    context: 'Ren has a quiet breakdown over a hard week; Saito offers tender mentor support.',
    purpose: 'Young man processing burnout with elder mentor.',
    ambient: 'cafe_evening_quiet',
    sound_effects: [],
    target_vocab: ['辛い', '休む', '受け入れる', '心'],
    cast: ['ren_uni', 'saito_doctor'],
    frequency_tier: 2,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '先生、心、限界です。', en: "Doctor — heart, limit.", style: 'soft exhausted young man voice, warm raw honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '辛いね、本当に。', en: "Hard — truly.", style: 'measured doctor voice, soft warm empathetic delivery carefully' },
      { speaker: 'ren_uni', jp: '頑張りすぎて、息できない。', en: "Tried too — can't breathe.", style: 'soft young man voice, warm raw delivery carefully' },
      { speaker: 'saito_doctor', jp: '受け入れて、自分を。', en: "Accept — yourself.", style: 'tender doctor voice, soft warm wise delivery carefully' },
      { speaker: 'ren_uni', jp: '休む、罪悪感がある。', en: "Rest — guilt.", style: 'soft young man voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '休むことは、必要なんです。', en: "Resting — necessary.", style: 'firm doctor voice, soft warm caring delivery carefully' },
      { speaker: 'ren_uni', jp: 'そう、ですよね。', en: "Right — isn't it.", style: 'soft young man voice, warm thoughtful delivery carefully' },
      { speaker: 'saito_doctor', jp: '自分を、許してください。', en: "Yourself — forgive.", style: 'tender doctor voice, soft warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '難しいけど、やってみます。', en: "Hard — but try.", style: 'soft young man voice, warm committed delivery carefully' },
      { speaker: 'saito_doctor', jp: '一人じゃない、ですからね。', en: "Not alone — you know.", style: 'warm doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、本当に。', en: "Thank you — truly.", style: 'soft tearful young man voice, warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: 'いつでも、来てください。', en: "Anytime — come.", style: 'tender doctor voice, soft warm enduring delivery carefully' },
      { speaker: 'ren_uni', jp: 'はい、ゆっくり、休みます。', en: "Yes — slowly rest.", style: 'soft determined young man voice, warm gentle resolve delivered carefully' },
    ],
  },
  {
    id: 'conv_01890',
    context: 'Naoko tells Hina about a moment in her past when she was stubborn but right.',
    purpose: 'Aunt sharing personal lesson story with teen.',
    ambient: 'ramen_shop_evening_quiet',
    sound_effects: [],
    target_vocab: ['頑固', '信じる', '結果', '誇る'],
    cast: ['naoko_aunt', 'hina_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'ひな、頑固って、悪くないで。', en: "Hina — stubborn, not bad.", style: 'warm Kansai aunt voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: 'えっ、本当?', en: "Eh — really?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'naoko_aunt', jp: '若い時、皆に反対された。', en: "Young — all opposed.", style: 'soft Kansai aunt voice, warm reminiscent delivery carefully' },
      { speaker: 'hina_child', jp: 'どうしたの?', en: "What did?", style: 'engaged teen girl voice, soft warm interested delivery carefully' },
      { speaker: 'naoko_aunt', jp: '自分、信じて、続けた。', en: "Self — believed, continued.", style: 'firm Kansai aunt voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: '結果、よかった?', en: "Result — good?", style: 'curious teen girl voice, soft warm hopeful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、今、誇りに思う。', en: "Yeah — now, proud.", style: 'tender Kansai aunt voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_01891',
    context: 'Mei tells Aoi about a moment she lost patience with her child.',
    purpose: 'Two mothers sharing honest parenting struggles.',
    ambient: 'cafe_afternoon_quiet',
    sound_effects: [],
    target_vocab: ['母親', '怒り', '反省', '愛'],
    cast: ['mei_romantic', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '蒼さん、今日、怒っちゃった。', en: "Aoi — today, got angry.", style: 'soft contrite young mother voice, warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: '誰でも、あるよ。', en: "Everyone — happens.", style: 'gentle adult woman voice, soft warm empathetic delivery carefully' },
      { speaker: 'mei_romantic', jp: '反省、しまくり。', en: "Reflecting — heavily.", style: 'soft young woman voice, warm vulnerable delivery carefully' },
      { speaker: 'aoi_barista', jp: '愛、伝わってるから、大丈夫。', en: "Love — reaches, fine.", style: 'tender adult woman voice, soft warm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: '謝ろうかな、ちゃんと。', en: "Apologize — properly.", style: 'soft young mother voice, warm honest delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、それが大切。', en: "Yeah — that matters.", style: 'warm adult woman voice, soft wise delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、聞いてくれて。', en: "Thanks — for listening.", style: 'tender young woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01892',
    context: 'Hiroshi-elder tells Sakura about a friend he wronged in youth, asking forgiveness.',
    purpose: 'Elder sharing deep moral regret with writer.',
    ambient: 'tatami_evening_lamp',
    sound_effects: [],
    target_vocab: ['後悔', '若い', '許す', '反省'],
    cast: ['hiroshi_elder', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'さくら、若い頃の後悔、ある。', en: "Sakura — young regrets, exist.", style: 'slow elder Kansai voice, warm raw honest delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どんなこと?', en: "What thing?", style: 'soft adult writer voice, warm gentle caring delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '友達、傷つけてしもた。', en: "Friend — hurt.", style: 'soft elder Kansai voice, warm regretful delivery carefully' },
      { speaker: 'sakura_teen', jp: '謝れましたか?', en: "Apologized?", style: 'gentle adult writer voice, soft warm probing delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、長い後で。', en: "Yeah — long after.", style: 'gentle elder Kansai voice, soft warm tender delivery carefully' },
      { speaker: 'sakura_teen', jp: '許してくれましたか?', en: "Forgave?", style: 'soft adult writer voice, warm tender curious delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ありがたかった。', en: "Yeah — grateful.", style: 'warm elder Kansai voice, soft tender humble delivery carefully' },
    ],
  },
  {
    id: 'conv_01893',
    context: 'Daichi takes a brave step at work; tells Mei about it.',
    purpose: 'Husband sharing courageous workplace decision with wife.',
    ambient: 'bedroom_evening_warm',
    sound_effects: [],
    target_vocab: ['勇気', '決断', '挑戦', '誇り'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、今日、上司に意見、言ったわ。', en: "Mei — today, boss, opinion said.", style: 'bright Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: 'まあ、勇気あるね。', en: "Oh — brave.", style: 'tender young wife voice, soft warm admiring delivery carefully' },
      { speaker: 'daichi_kansai', jp: '心臓、ドキドキした。', en: "Heart — pounded.", style: 'soft Kansai man voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '決断、よかったね。', en: "Decision — good.", style: 'warm young wife voice, soft warm proud delivery carefully' },
      { speaker: 'daichi_kansai', jp: '挑戦、できた。', en: "Challenge — done.", style: 'soft Kansai husband voice, warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: '誇り、感じてる、私。', en: "Pride — feel, me.", style: 'tender young wife voice, soft warm fond delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前のおかげや。', en: "Thanks to you.", style: 'tender Kansai husband voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01894',
    context: 'Asuka and Tatsuya-country reflect on aging together; quiet acceptance.',
    purpose: 'Elder couple sharing tender mortality acceptance.',
    ambient: 'porch_evening_winter',
    sound_effects: [],
    target_vocab: ['老い', '受け入れる', '感謝', '人生'],
    cast: ['asuka_teacher', 'tatsuya_country'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: 'お互い、年取ったね。', en: "Both — aged.", style: 'soft teacher voice, warm fond reflective delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、信じられんわ。', en: "Yeah — unbelievable.", style: 'gentle Tohoku farmer voice, soft warm honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '受け入れるしかない、それも。', en: "Accept only — that too.", style: 'warm teacher voice, soft warm wise delivery carefully' },
      { speaker: 'tatsuya_country', jp: '感謝の人生、やったな。', en: "Grateful life — was.", style: 'soft Tohoku voice, warm tender delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'これからも、丁寧に生きたい。', en: "Going forward — live carefully.", style: 'gentle teacher voice, soft warm earnest delivery carefully' },
      { speaker: 'tatsuya_country', jp: '一緒におって、ありがたい。', en: "Together — grateful.", style: 'soft Tohoku farmer voice, warm tender enduring delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ふふ、ずっと、隣にね。', en: "Heh — always, beside.", style: 'tender teacher voice, soft warm loving delivery carefully' },
    ],
  },
  {
    id: 'conv_01895',
    context: 'Yumiko reflects with Mei about the loss of her late husband, gentle.',
    purpose: 'Widow sharing grief journey with caring daughter-in-law.',
    ambient: 'tatami_lamp_quiet',
    sound_effects: [],
    target_vocab: ['亡くす', '悲しみ', '思い出', '感謝'],
    cast: ['yumiko_mom', 'mei_romantic'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: '今でも、寂しいわ。', en: "Even now — lonely.", style: 'soft older mother voice, warm tearful honest delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お母さん、当然です。', en: "Mom — natural.", style: 'tender young woman voice, soft warm empathetic delivery carefully' },
      { speaker: 'yumiko_mom', jp: '思い出、たくさん残してくれた。', en: "Memories — many left.", style: 'gentle older mother voice, soft warm reverent delivery carefully' },
      { speaker: 'mei_romantic', jp: '感謝の毎日、ですね。', en: "Grateful daily — yes.", style: 'soft young woman voice, warm tender delivery carefully' },
      { speaker: 'yumiko_mom', jp: '悲しみと、共に生きる。', en: "Sadness — live with.", style: 'tender older mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お母さん、強いね。', en: "Mom — strong.", style: 'tender young woman voice, soft warm admiring delivery carefully' },
      { speaker: 'yumiko_mom', jp: '皆のおかげよ、本当に。', en: "Thanks to all — truly.", style: 'soft older mother voice, warm humble grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01896',
    context: 'Sho-young learns about humility from Hiroshi-elder during tea.',
    purpose: 'Grandfather teaching young child wisdom.',
    ambient: 'tatami_afternoon_lamp',
    sound_effects: [],
    target_vocab: ['謙虚', '偉い', '心', '人'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '翔、謙虚って、知ってるか?', en: "Sho — humility, know?", style: 'slow elder Kansai voice, warm warm teaching delivery carefully' },
      { speaker: 'sho_child', jp: 'ううん、わからん。', en: "No — don't get.", style: 'soft child boy voice, warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '偉そうにせんことや。', en: "Not act proud.", style: 'gentle elder Kansai voice, soft warm wise delivery carefully' },
      { speaker: 'sho_child', jp: '心、優しいってこと?', en: "Heart — kind, that?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うん、そういう人、強いんや。', en: "Yeah — that person, strong.", style: 'warm elder Kansai voice, soft warm philosophical delivery carefully' },
    ],
  },
  {
    id: 'conv_01897',
    context: 'Sakura and Ren debate justice in their writing project.',
    purpose: 'Two writers wrestling with ethical themes in work.',
    ambient: 'study_room_lamp_low',
    sound_effects: [],
    target_vocab: ['正義', '悪', '物語', '描く'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'この物語、正義、難しいね。', en: "This story — justice, hard.", style: 'thoughtful adult writer voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '善悪、はっきり分けられない。', en: "Good-evil — can't sharply divide.", style: 'gentle young man voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '読者、考えさせたい。', en: "Readers — want to think.", style: 'soft adult writer voice, warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '描き方、丁寧に。', en: "Depiction — carefully.", style: 'soft young man voice, warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '結末、決めかねる。', en: "Ending — can't decide.", style: 'gentle adult writer voice, soft warm uncertain delivery carefully' },
      { speaker: 'ren_uni', jp: '読者に、委ねる手も。', en: "Readers — entrust hand too.", style: 'thoughtful young man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、それもいいね。', en: "Yeah — that too.", style: 'warm adult writer voice, soft appreciative delivery carefully' },
    ],
  },
  {
    id: 'conv_01898',
    context: 'Kenji apologizes to Aoi for being impatient earlier; tender moment.',
    purpose: 'Husband sincere apology to wife.',
    ambient: 'living_room_lamp_warm',
    sound_effects: [],
    target_vocab: ['謝る', '反省', '気持ち', '愛'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '蒼、さっき、すまんかった。', en: "Aoi — earlier, sorry.", style: 'soft Kansai husband voice, warm contrite honest delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、気にしないで。', en: "Yeah — don't mind.", style: 'tender adult woman voice, soft warm gentle delivery carefully' },
      { speaker: 'kenji_office', jp: '反省してる、ほんま。', en: "Reflecting — truly.", style: 'soft Kansai husband voice, warm earnest delivery carefully' },
      { speaker: 'aoi_barista', jp: '気持ち、伝わってる。', en: "Feelings — convey.", style: 'soft adult woman voice, warm tender delivery carefully' },
      { speaker: 'kenji_office', jp: '愛してる、お前を。', en: "Love — you.", style: 'tender Kansai husband voice, soft warm honest delivery carefully' },
    ],
  },
  {
    id: 'conv_01899',
    context: 'Hina-young and Riku-teen apologize to each other after a small disagreement.',
    purpose: 'Two teens working through misunderstanding maturely.',
    ambient: 'park_bench_afternoon',
    sound_effects: [],
    target_vocab: ['ごめん', '反省', '気持ち', '友達'],
    cast: ['hina_child', 'riku_teen'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '陸くん、ごめんね、昨日。', en: "Riku — sorry, yesterday.", style: 'soft contrite teen girl voice, warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: 'こっちも、ごめん。', en: "Mine too — sorry.", style: 'soft teen boy voice, warm honest delivery carefully' },
      { speaker: 'hina_child', jp: '気持ち、わからなかった。', en: "Feelings — couldn't.", style: 'soft teen girl voice, warm honest reflective delivery carefully' },
      { speaker: 'riku_teen', jp: '友達、大事やもんな。', en: "Friend — matters.", style: 'warm teen boy voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: 'うん、これからも、よろしく!', en: "Yeah — going forward, please!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01900',
    context: 'Naoko reaches a major milestone in business; whole crew gathers.',
    purpose: 'Multi-voice celebration of personal achievement.',
    ambient: 'ramen_shop_celebration_warm',
    sound_effects: [],
    target_vocab: ['節目', '感謝', '応援', '皆', '幸せ'],
    cast: ['naoko_aunt', 'hiroshi_elder', 'aoi_barista', 'mei_romantic', 'hina_child', 'kenji_office'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '皆、よう集まってくれたな!', en: "All — gathered!", style: 'brassy Kansai aunt voice, bright loud delighted delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '三十年、節目や!', en: "Thirty years — milestone!", style: 'slow elder Kansai voice, warm proud delivery carefully' },
      { speaker: 'aoi_barista', jp: 'おばさん、本当におめでとう!', en: "Auntie — truly congrats!", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お疲れさまでした、長い道のり。', en: "Good work — long road.", style: 'soft young woman voice, warm warm reverent delivery carefully' },
      { speaker: 'hina_child', jp: 'おばちゃん、すごい!', en: "Auntie — amazing!", style: 'thrilled teen girl voice, bright warm awed delivery carefully' },
      { speaker: 'kenji_office', jp: '感謝しかない、ほんま。', en: "Only gratitude — truly.", style: 'soft Kansai man voice, warm humble delivery carefully' },
      { speaker: 'naoko_aunt', jp: '皆の応援、おかげで、できた。', en: "Everyone's cheer — thanks, could.", style: 'tender Kansai aunt voice, soft warm grateful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前、ようやった!', en: "You — well done!", style: 'gentle elder Kansai voice, soft warm proud delivery carefully' },
      { speaker: 'aoi_barista', jp: 'これからも、応援するね。', en: "Going forward — cheer.", style: 'warm adult woman voice, soft warm steadfast delivery carefully' },
      { speaker: 'mei_romantic', jp: '幸せ、伝わる夜。', en: "Happiness — conveying night.", style: 'tender young woman voice, soft warm content delivery carefully' },
      { speaker: 'hina_child', jp: 'おばちゃん、大好き!', en: "Auntie — love!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うちも、皆大好きや!', en: "I too — all love!", style: 'animated Kansai aunt voice, bright loud delighted delivery carefully' },
      { speaker: 'kenji_office', jp: '乾杯、しよか!', en: "Toast — do!", style: 'warm Kansai man voice, soft cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01901',
    context: 'Saito reflects with his daughter Hina on choosing kindness in medicine.',
    purpose: 'Father teaching child about compassion as profession.',
    ambient: 'porch_evening_quiet',
    sound_effects: [],
    target_vocab: ['親切', '医療', '心', '大切'],
    cast: ['saito_doctor', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'ひな、医療、親切が一番。', en: "Hina — medicine, kindness first.", style: 'measured doctor voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: 'お父さん、なんで?', en: "Dad — why?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'saito_doctor', jp: '患者、心、安らぐから。', en: "Patient — heart, calms.", style: 'gentle doctor voice, soft warm tender delivery carefully' },
      { speaker: 'hina_child', jp: 'なるほど、深いね。', en: "I see — deep.", style: 'soft teen girl voice, warm thoughtful delivery carefully' },
      { speaker: 'saito_doctor', jp: '技術より、心が伝わる。', en: "Heart conveys — more than tech.", style: 'soft doctor voice, warm warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: '私も、優しくなりたい。', en: "I — want kind too.", style: 'soft determined teen girl voice, warm earnest delivery carefully' },
      { speaker: 'saito_doctor', jp: 'もう、十分優しいよ。', en: "Already — enough kind.", style: 'tender doctor voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01902',
    context: 'Asuka pep-talks her struggling student gently after school.',
    purpose: 'Teacher offering kind support to faltering student.',
    ambient: 'classroom_after_quiet',
    sound_effects: [],
    target_vocab: ['頑張る', '応援', '自信', '夢'],
    cast: ['asuka_teacher', 'riku_teen'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'asuka_teacher', jp: '陸くん、最近、元気ない?', en: "Riku — lately, no energy?", style: 'gentle teacher voice, soft warm caring inquiry delivered carefully' },
      { speaker: 'riku_teen', jp: '自信、なくしてて。', en: "Confidence — losing.", style: 'soft teen boy voice, warm vulnerable delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'みんな、そんな時期ある。', en: "Everyone — has such time.", style: 'warm teacher voice, soft warm philosophical delivery carefully' },
      { speaker: 'riku_teen', jp: '夢、追えるかな。', en: "Dream — can chase?", style: 'soft worried teen boy voice, warm honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'あなたなら、できる。', en: "You — can.", style: 'firm teacher voice, soft warm proud delivery carefully' },
      { speaker: 'riku_teen', jp: 'ありがとうございます、先生。', en: "Thanks — teacher.", style: 'soft teen boy voice, warm grateful delivery carefully' },
      { speaker: 'asuka_teacher', jp: '応援してる、ずっと。', en: "Cheering — always.", style: 'tender teacher voice, soft warm steadfast delivery carefully' },
    ],
  },
  {
    id: 'conv_01903',
    context: 'Mrs. Mori reflects on a recent good deed she did and feels content.',
    purpose: 'Elder woman quietly content after kindness.',
    ambient: 'tatami_quiet_kettle',
    sound_effects: [],
    target_vocab: ['親切', '気持ち', '良い', '満足'],
    cast: ['mrs_mori_neighbor', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: '今日、ちょっと親切したわ。', en: "Today — small kind did.", style: 'warm older neighbor voice, soft content delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、何があった?', en: "Oh — what happened?", style: 'gentle older mother voice, soft warm engaged delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '迷子、案内してあげた。', en: "Lost child — guided.", style: 'soft older woman voice, warm humble delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'えらいわね、お疲れさま。', en: "Splendid — good work.", style: 'warm older mother voice, soft warm appreciative delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '気持ち、満足してる。', en: "Feel — content.", style: 'tender older neighbor voice, soft warm content delivery carefully' },
    ],
  },
  {
    id: 'conv_01904',
    context: 'Tatsuya-country and Hiroshi-boss talk about honesty in business across decades.',
    purpose: 'Two older men comparing professional ethics across eras.',
    ambient: 'restaurant_quiet_evening',
    sound_effects: [],
    target_vocab: ['正直', '取引', '信頼', '時代'],
    cast: ['tatsuya_country', 'hiroshi_boss'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '昔の商売、正直が肝心や。', en: "Old business — honesty key.", style: 'slow Tohoku farmer voice, warm wise delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ええ、今も変わりません。', en: "Yes — now too unchanged.", style: 'measured boss voice, soft warm agreeing delivery carefully' },
      { speaker: 'tatsuya_country', jp: '信頼、築くの、時間かかる。', en: "Trust — building takes time.", style: 'gentle Tohoku voice, soft warm philosophical delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '時代、変わっても、本質同じ。', en: "Times change — essence same.", style: 'warm boss voice, soft warm reflective delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お前、ようけ大事にしてる。', en: "You — much cherish.", style: 'soft Tohoku voice, warm fond delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'ありがとうございます、お父さん。', en: "Thanks — Otosan.", style: 'humble boss voice, soft warm respectful delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'お互い、誠実に生きような。', en: "Both — sincerely live.", style: 'gentle Tohoku farmer voice, soft warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_01905',
    context: 'Sho-young is jealous of Riku-teen\'s success; Mei helps him process it.',
    purpose: 'Mother teaching child to handle envy.',
    ambient: 'bedroom_evening_warm',
    sound_effects: [],
    target_vocab: ['羨ましい', '気持ち', '頑張る', '比べる'],
    cast: ['mei_romantic', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お母さん、陸くん、羨ましい。', en: "Mom — Riku, envious.", style: 'soft vulnerable child boy voice, warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '気持ち、わかるよ。', en: "Feel — understand.", style: 'tender young mother voice, soft warm empathetic delivery carefully' },
      { speaker: 'sho_child', jp: '比べちゃう、ダメだよね。', en: "Compare — not okay, right.", style: 'soft child boy voice, warm self-aware delivery carefully' },
      { speaker: 'mei_romantic', jp: '人それぞれ、いいところある。', en: "Each one — good points.", style: 'warm young mother voice, soft warm wise delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、頑張る、自分のペースで。', en: "Yeah — try, own pace.", style: 'soft determined child boy voice, warm resolved delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_095 wrote', CONVERSATIONS.length, 'files');
