import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_080)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01586',
    context: 'Sho-young helps Hiroshi-elder set up a new smartphone.',
    purpose: 'Tech-savvy youth patiently teaching grandparent.',
    ambient: 'living_room_evening_quiet',
    sound_effects: [],
    target_vocab: ['携帯', '画面', '操作', '設定'],
    cast: ['sho_child', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: 'この携帯、難しいわ。', en: "This phone — hard.", style: 'slow elder Kansai voice, warm puzzled honest delivery carefully' },
      { speaker: 'sho_child', jp: 'おじいちゃん、画面押すだけ。', en: "Grandpa — just press the screen.", style: 'patient teen boy voice, soft warm teaching delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、ここか?', en: "Oh — here?", style: 'gentle elder Kansai voice, soft warm uncertain delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、操作、慣れたら簡単やで。', en: "Yeah — easy once used to it.", style: 'warm teen boy voice, soft encouraging delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '設定、お前に任せるわ。', en: "Setup — I'll leave to you.", style: 'soft elder Kansai voice, warm trusting delivery carefully' },
      { speaker: 'sho_child', jp: '俺がやっとくから、安心して。', en: "I'll handle it — relax.", style: 'cheerful teen boy voice, soft warm helpful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おおきに、頼もしいなぁ。', en: "Thanks — reliable kid.", style: 'warm elder Kansai voice, soft fond proud delivery carefully' },
    ],
  },
  {
    id: 'conv_01587',
    context: 'Ren and Aoi discuss social media trends over coffee.',
    purpose: 'Two adults reflecting on modern attention culture.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['流行', '話題', '影響', '傾向'],
    cast: ['ren_uni', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '最近の流行、追いつけないよ。', en: "Can't keep up with trends lately.", style: 'soft adult woman voice, warm self-deprecating honest delivery carefully' },
      { speaker: 'ren_uni', jp: '変化、速いですね。', en: "Changes are fast.", style: 'soft young man voice, warm reflective delivery carefully' },
      { speaker: 'aoi_barista', jp: '話題、毎週変わる感じ。', en: "Topics shift weekly, it feels.", style: 'gentle adult woman voice, soft warm observant delivery carefully' },
      { speaker: 'ren_uni', jp: 'SNSの影響、強いです。', en: "Social media has strong influence.", style: 'thoughtful young man voice, soft warm intellectual delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、傾向、読みにくいね。', en: "Yes — hard to read the trends.", style: 'warm adult woman voice, soft reflective delivery carefully' },
      { speaker: 'ren_uni', jp: '深く付き合わない方が、楽。', en: "Easier not to engage deeply.", style: 'soft young man voice, warm wise delivery carefully' },
      { speaker: 'aoi_barista', jp: 'そうね、賢明な判断。', en: "Right — wise call.", style: 'gentle adult woman voice, soft warm approving delivery carefully' },
    ],
  },
  {
    id: 'conv_01588',
    context: 'Daichi tries to fix a broken washing machine; Kenji stops by to help.',
    purpose: 'Two men troubleshooting an appliance together.',
    ambient: 'laundry_room_low',
    sound_effects: [],
    target_vocab: ['故障', '修理', '電源', '部品'],
    cast: ['daichi_kansai', 'kenji_office'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '洗濯機、故障してもうた。', en: "Washing machine — broke.", style: 'troubled Kansai man voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: '電源、入らんの?', en: "Power won't turn on?", style: 'soft Kansai mentor voice, warm focused diagnostic delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'うん、うんともすんとも。', en: "Yeah — completely dead.", style: 'frustrated Kansai man voice, soft warm honest delivery carefully' },
      { speaker: 'kenji_office', jp: 'コード、確認しよか。', en: "Let's check the cord.", style: 'gentle Kansai artist voice, soft warm practical delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'こっち、見て見て。', en: "Here — look look.", style: 'soft Kansai husband voice, warm focused delivery carefully' },
      { speaker: 'kenji_office', jp: 'ああ、部品交換要るな。', en: "Ah — needs a part swap.", style: 'composed Kansai voice, soft warm professional diagnosis delivered carefully' },
      { speaker: 'daichi_kansai', jp: '頼むわ、店行ってくる。', en: "Please — I'll head to the shop.", style: 'warm Kansai husband voice, soft grateful determined delivery carefully' },
    ],
  },
  {
    id: 'conv_01589',
    context: 'Sakura discusses publishing goals with Hiroshi-boss; quiet ambition talk.',
    purpose: 'Author and publisher discussing long-term creative goals.',
    ambient: 'office_quiet_window',
    sound_effects: [],
    target_vocab: ['目標', '挑戦', '達成', '実現'],
    cast: ['sakura_teen', 'hiroshi_boss'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '次の目標、考えています。', en: "Thinking about the next goal.", style: 'soft adult writer voice, warm reflective committed delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'どんな挑戦ですか?', en: "What kind of challenge?", style: 'measured boss voice, soft warm curious delivery carefully' },
      { speaker: 'sakura_teen', jp: '長編に挑戦、したいです。', en: "Want to take on a novel.", style: 'committed adult writer voice, soft warm ambitious delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'いい挑戦ですね、応援します。', en: "Fine challenge — I'll support you.", style: 'warm boss voice, soft proud encouraging delivery carefully' },
      { speaker: 'sakura_teen', jp: '達成するには、時間が要ります。', en: "To achieve it — need time.", style: 'soft adult writer voice, warm honest realistic delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '焦らず、実現してください。', en: "Don't rush — realize it.", style: 'gentle boss voice, soft warm wise delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble adult writer voice, soft warm sincere delivery carefully' },
    ],
  },
  {
    id: 'conv_01590',
    context: 'Hina-young takes Yumiko to use a new pharmacy app; gentle teaching.',
    purpose: 'Teen helping grandparent navigate digital tools.',
    ambient: 'living_room_quiet',
    sound_effects: [],
    target_vocab: ['アプリ', '便利', '登録', '通知'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、このアプリ便利だよ。', en: "Grandma — this app's handy.", style: 'bright teen girl voice, soft warm helpful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'まあ、どうやって使うの?', en: "Oh — how to use it?", style: 'gentle older mother voice, soft warm curious delivery carefully' },
      { speaker: 'hina_child', jp: 'まず登録、私やるね。', en: "First — register. I'll do it.", style: 'cheerful teen girl voice, soft warm capable delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ありがとう、頼もしいわ。', en: "Thanks — reliable.", style: 'warm older mother voice, soft fond grateful delivery carefully' },
      { speaker: 'hina_child', jp: '通知、薬の時間に来るよ。', en: "Notifications come at medicine time.", style: 'soft teen girl voice, warm helpful clear delivery carefully' },
    ],
  },
  {
    id: 'conv_01591',
    context: 'Naoko and Mei discuss a new young business owner opening shop nearby.',
    purpose: 'Two women discussing community business with warm interest.',
    ambient: 'ramen_shop_morning',
    sound_effects: [],
    target_vocab: ['起業', '経営', '若い', '応援'],
    cast: ['naoko_aunt', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '若い人が、起業したんですね。', en: "A young person started a business.", style: 'soft young woman voice, warm impressed observant delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、勇気あるなぁ。', en: "Yeah — brave one.", style: 'brassy Kansai aunt voice, bright warm admiring delivery carefully' },
      { speaker: 'mei_romantic', jp: '経営、上手くいくといいですね。', en: "Hope the business goes well.", style: 'gentle young woman voice, soft warm hopeful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'うちも、応援するで。', en: "We'll cheer them on.", style: 'warm Kansai aunt voice, soft loyal supportive delivery carefully' },
      { speaker: 'mei_romantic', jp: '一緒に行きましょうか。', en: "Shall we go together?", style: 'soft young woman voice, warm friendly inviting delivery carefully' },
    ],
  },
  {
    id: 'conv_01592',
    context: 'Saito and Asuka talk about a difficult medical case; supportive professional exchange.',
    purpose: 'Two professionals leaning on each other after a hard day.',
    ambient: 'office_late_quiet',
    sound_effects: [],
    target_vocab: ['患者', '対応', '困難', '尽くす'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '今日の患者、難しかったです。', en: "Today's patient — tough.", style: 'tired doctor voice, soft warm honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'お疲れさまでした、大変でしたね。', en: "Good work — it must've been hard.", style: 'gentle teacher voice, soft warm caring delivery carefully' },
      { speaker: 'saito_doctor', jp: '対応、全力を尽くしました。', en: "Gave it my all.", style: 'soft doctor voice, warm honest worn delivery carefully' },
      { speaker: 'asuka_teacher', jp: '先生の真摯さ、伝わります。', en: "Your sincerity shows.", style: 'tender teacher voice, soft warm admiring delivery carefully' },
      { speaker: 'saito_doctor', jp: '困難な時こそ、丁寧に。', en: "In hard times — go carefully.", style: 'measured doctor voice, soft warm wise delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ご自身も、休んでくださいね。', en: "Please rest yourself too.", style: 'caring teacher voice, soft warm concerned delivery carefully' },
      { speaker: 'saito_doctor', jp: 'ありがとう、そうします。', en: "Thanks — I will.", style: 'soft doctor voice, warm grateful tender delivery carefully' },
    ],
  },
  {
    id: 'conv_01593',
    context: 'Riku-teen and Hina-teen do homework together at the library.',
    purpose: 'Teen peers studying with quiet companionship.',
    ambient: 'library_pages_quiet',
    sound_effects: [],
    target_vocab: ['宿題', '集中', '頭', '休憩'],
    cast: ['riku_teen', 'hina_child'],
    frequency_tier: 2,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'riku_teen', jp: '宿題、進む?', en: "Homework going?", style: 'soft teen boy voice, warm friendly inquiry delivered carefully' },
      { speaker: 'hina_child', jp: 'うーん、集中できない。', en: "Mm — can't focus.", style: 'soft teen girl voice, warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: '頭、疲れてんねん。', en: "Brain's tired.", style: 'casual teen boy voice, soft warm relatable delivery carefully' },
      { speaker: 'hina_child', jp: '休憩、しようか。', en: "Let's take a break.", style: 'gentle teen girl voice, soft warm suggestion delivered carefully' },
      { speaker: 'riku_teen', jp: 'うん、お菓子買ってくる。', en: "Yeah — I'll grab snacks.", style: 'bright teen boy voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_01594',
    context: 'Ren and Sakura collaborate on writing a literary essay over many hours.',
    purpose: 'Two writers in close creative collaboration.',
    ambient: 'study_room_late',
    sound_effects: [],
    target_vocab: ['文章', '表現', '推敲', '完成'],
    cast: ['ren_uni', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: 'この文章、もう一度推敲したい。', en: "Want to refine this sentence again.", style: 'thoughtful adult writer voice, soft warm focused delivery carefully' },
      { speaker: 'ren_uni', jp: 'どこの表現が気になります?', en: "Which expression bothers you?", style: 'soft young man voice, warm engaged careful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ここの繰り返し、削ろう。', en: "This repetition — cut it.", style: 'composed adult writer voice, soft warm decisive delivery carefully' },
      { speaker: 'ren_uni', jp: '同感、無くした方が締まる。', en: "Agreed — tighter without it.", style: 'soft young man voice, warm engaged collaborative delivery carefully' },
      { speaker: 'sakura_teen', jp: '結びの言葉、迷うね。', en: "The closing words — uncertain.", style: 'soft adult writer voice, warm reflective delivery carefully' },
      { speaker: 'ren_uni', jp: '静かに終えるのが、いい。', en: "Quiet ending is best.", style: 'gentle young man voice, soft warm thoughtful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、そう感じる。', en: "Yes — that's what I feel.", style: 'warm adult writer voice, soft agreement delivered carefully' },
      { speaker: 'ren_uni', jp: 'ここを少し、変えませんか?', en: "Shall we tweak this bit?", style: 'soft young man voice, warm gentle suggesting delivery carefully' },
      { speaker: 'sakura_teen', jp: 'どう変える?', en: "How?", style: 'curious adult writer voice, soft warm open delivery carefully' },
      { speaker: 'ren_uni', jp: '受け身を、能動にする。', en: "Passive — to active.", style: 'composed young man voice, soft warm precise delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ああ、ぐっと締まるね。', en: "Ah — much tighter.", style: 'pleased adult writer voice, soft warm impressed delivery carefully' },
      { speaker: 'ren_uni', jp: '完成、近いです。', en: "Completion — near.", style: 'soft young man voice, warm hopeful delivery carefully' },
      { speaker: 'sakura_teen', jp: '今夜、終えられそう。', en: "Might finish tonight.", style: 'gentle adult writer voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_01595',
    context: 'Aoi and Kenji compare childhood photos and reminisce gently.',
    purpose: 'Couple sharing intimate memory exploration.',
    ambient: 'living_room_evening_lamp',
    sound_effects: [],
    target_vocab: ['写真', '思い出', '子供', '懐かしい'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 2,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'この写真、子供の頃の私。', en: "This photo — me as a child.", style: 'soft adult woman voice, warm fond nostalgic delivery carefully' },
      { speaker: 'kenji_office', jp: 'ほんま?可愛いやんか。', en: "Really? So cute.", style: 'warm Kansai man voice, soft fond admiring delivery carefully' },
      { speaker: 'aoi_barista', jp: 'お母さん、よく着せてくれてた。', en: "Mom would dress me up.", style: 'tender adult woman voice, soft warm reminiscing delivery carefully' },
      { speaker: 'kenji_office', jp: '懐かしいなぁ、見せて。', en: "Nostalgic — show me.", style: 'soft Kansai man voice, warm interested fond delivery carefully' },
      { speaker: 'aoi_barista', jp: 'これ、家族旅行の写真。', en: "This — family trip photo.", style: 'soft adult woman voice, warm fond delivery carefully' },
      { speaker: 'kenji_office', jp: '思い出、大切やな。', en: "Memories — precious.", style: 'gentle Kansai voice, soft warm reflective delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、宝物。', en: "Yeah — treasure.", style: 'tender adult woman voice, soft warm delivery carefully' },
    ],
  },
  {
    id: 'conv_01596',
    context: 'Sho-young learns how to ride a unicycle from Riku-teen at the park.',
    purpose: 'Older teen patiently teaching child a tricky physical skill.',
    ambient: 'park_afternoon_breeze',
    sound_effects: [],
    target_vocab: ['挑戦', '転ぶ', '頑張る', 'バランス'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '一輪車、挑戦したい!', en: "Unicycle — I want to try!", style: 'eager child boy voice, bright cheerful determined delivery carefully' },
      { speaker: 'riku_teen', jp: 'よっしゃ、最初は転ぶで。', en: "Sure — you'll fall first.", style: 'casual teen boy voice, soft warm honest delivery carefully' },
      { speaker: 'sho_child', jp: '怖いけど、頑張る!', en: "Scary but I'll try!", style: 'soft determined child boy voice, warm brave delivery carefully' },
      { speaker: 'riku_teen', jp: 'バランス、感じて乗ってみ。', en: "Feel the balance — try riding.", style: 'gentle teen boy voice, soft warm guiding delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、やってみる!', en: "Yeah — I'll try!", style: 'bright child boy voice, soft warm energized delivery carefully' },
    ],
  },
  {
    id: 'conv_01597',
    context: 'Mei tells Daichi about her mom\'s anniversary memorial preparations.',
    purpose: 'Spouses planning family memorial event tenderly.',
    ambient: 'tatami_evening_quiet',
    sound_effects: [],
    target_vocab: ['法事', '準備', '親族', '心'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '法事の準備、進めるね。', en: "I'll handle the memorial prep.", style: 'soft young wife voice, warm tender delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お母さんの法事やな。', en: "Mom's memorial.", style: 'soft Kansai husband voice, warm reverent delivery carefully' },
      { speaker: 'mei_romantic', jp: '親族、何人来てくれるかな。', en: "Wonder how many relatives.", style: 'gentle young woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '昨年と、同じくらいやろな。', en: "About like last year.", style: 'soft Kansai husband voice, warm calm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: '心、こめて迎えたい。', en: "Want to receive them with full heart.", style: 'tender young wife voice, soft warm reverent delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前なら、ちゃんとできる。', en: "You'll do it properly.", style: 'warm Kansai husband voice, soft tender trusting delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとう、心強い。', en: "Thanks — encouraging.", style: 'soft young wife voice, warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01598',
    context: 'Hiroshi-elder rambles fondly to Tatsuya about his late wife.',
    purpose: 'Two old men sharing tender bereavement memories.',
    ambient: 'porch_winter_evening',
    sound_effects: [],
    target_vocab: ['妻', '想い', '優しい', '幸せ'],
    cast: ['hiroshi_elder', 'tatsuya_country'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '亡くなった妻、優しい人やった。', en: "My late wife — gentle person.", style: 'slow elder Kansai voice, warm tender grief-laden delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'ええ奥さんやったんですね。', en: "A fine wife, she was.", style: 'soft Tohoku voice, warm respectful reverent delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '毎朝、味噌汁作ってくれた。', en: "Made me miso soup every morning.", style: 'gentle elder Kansai voice, soft warm fond delivery carefully' },
      { speaker: 'tatsuya_country', jp: '思い出、ようけ残ってますね。', en: "Many memories left.", style: 'gentle Tohoku voice, soft warm understanding delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '想い、忘れたことないわ。', en: "Never forgot the feeling.", style: 'soft elder Kansai voice, warm tender grieving delivery carefully' },
      { speaker: 'tatsuya_country', jp: '幸せな結婚、やったんですね。', en: "A happy marriage, then.", style: 'warm Tohoku farmer voice, soft tender delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'ほんま、感謝しかない。', en: "Truly — only gratitude.", style: 'gentle elder Kansai voice, soft warm humble delivery carefully' },
    ],
  },
  {
    id: 'conv_01599',
    context: 'Asuka helps Hina-young rehearse for a speech contest.',
    purpose: 'Teacher patiently coaching student on public speaking.',
    ambient: 'classroom_after_quiet',
    sound_effects: [],
    target_vocab: ['発表', '練習', '声', '自信'],
    cast: ['asuka_teacher', 'hina_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: '先生、発表、緊張する。', en: "Teacher — speech makes me nervous.", style: 'soft teen girl voice, warm honest anxious delivery carefully' },
      { speaker: 'asuka_teacher', jp: '練習、ちゃんとしてきたわよ。', en: "You've practiced well.", style: 'gentle teacher voice, soft warm reassuring delivery carefully' },
      { speaker: 'hina_child', jp: '声、震えそう。', en: "Voice might shake.", style: 'soft worried teen girl voice, warm honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '深呼吸して、ゆっくり話してね。', en: "Deep breath — speak slowly.", style: 'warm teacher voice, soft tender guiding delivery carefully' },
      { speaker: 'hina_child', jp: '自信、まだないんです。', en: "Still no confidence.", style: 'soft teen girl voice, warm vulnerable delivery carefully' },
      { speaker: 'asuka_teacher', jp: '自分を信じて、いいの。', en: "Trust yourself — it's fine.", style: 'tender teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、頑張ります。', en: "Yes — I'll try.", style: 'soft determined teen girl voice, warm gentle resolve delivered carefully' },
    ],
  },
  {
    id: 'conv_01600',
    context: 'Kenji and Daichi take Hiroshi-elder fishing on a quiet morning lake.',
    purpose: 'Three men sharing rare slow outdoor moment.',
    ambient: 'lake_morning_water',
    sound_effects: [],
    target_vocab: ['釣り', '湖', '静か', '時間'],
    cast: ['kenji_office', 'daichi_kansai', 'hiroshi_elder'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '湖、静かでええなぁ。', en: "Lake — quiet, lovely.", style: 'slow elder Kansai voice, warm content delivery carefully' },
      { speaker: 'daichi_kansai', jp: '釣り、久しぶりですね。', en: "Fishing — first time in a while.", style: 'warm Kansai man voice, soft fond delivery carefully' },
      { speaker: 'kenji_office', jp: '時間、ゆっくり流れるな。', en: "Time — flowing slowly.", style: 'soft Kansai artist voice, warm reflective delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おまえらと、嬉しいわ。', en: "With you two — happy.", style: 'gentle elder Kansai voice, soft warm fatherly delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'たまには、こういう日も。', en: "Sometimes — days like this.", style: 'warm Kansai husband voice, soft content delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ仲間や、ほんま。', en: "Fine company — truly.", style: 'soft Kansai man voice, warm tender brotherly delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'これがな、人生の宝や。', en: "This — life's treasure.", style: 'tender elder Kansai voice, soft warm wise delivery carefully' },
    ],
  },
  {
    id: 'conv_01601',
    context: 'Yumiko and Naoko bake mochi together for new year preparations.',
    purpose: 'Two older women cooking traditionally with banter.',
    ambient: 'kitchen_steam_warm',
    sound_effects: [],
    target_vocab: ['餅', '正月', '伝統', '準備'],
    cast: ['yumiko_mom', 'naoko_aunt'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'もうすぐ正月やな、姉ちゃん。', en: "New Year's coming, sister.", style: 'brassy Kansai aunt voice, bright cheerful delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ええ、餅の準備しないと。', en: "Yes — must prep mochi.", style: 'gentle older mother voice, soft warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: '伝統やね、毎年。', en: "Tradition — every year.", style: 'warm Kansai aunt voice, soft fond delivery carefully' },
      { speaker: 'yumiko_mom', jp: '一緒だと、楽しいわ。', en: "Together — fun.", style: 'soft older mother voice, warm tender delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、一杯やって作ろか!', en: "Heh — drink and make 'em!", style: 'animated Kansai aunt voice, bright loud playful delivery carefully' },
    ],
  },
  {
    id: 'conv_01602',
    context: 'Ren visits Aoi at the cafe with a small gift; quiet sweet moment.',
    purpose: 'Adult mentee bringing thoughtful surprise to mentor.',
    ambient: 'cafe_quiet_pour',
    sound_effects: [],
    target_vocab: ['贈り物', '気持ち', '感謝', '小さい'],
    cast: ['ren_uni', 'aoi_barista'],
    frequency_tier: 3,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '蒼さん、これ、小さい贈り物。', en: "Aoi-san — a small gift.", style: 'soft young man voice, warm shy sincere delivery carefully' },
      { speaker: 'aoi_barista', jp: 'まあ、何かしら?', en: "Oh — what is it?", style: 'gentle adult woman voice, soft warm surprised delivery carefully' },
      { speaker: 'ren_uni', jp: '日頃の感謝の気持ちです。', en: "My daily gratitude.", style: 'humble young man voice, soft warm sincere delivery carefully' },
      { speaker: 'aoi_barista', jp: '嬉しい、ありがとうね。', en: "Happy — thank you.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'ren_uni', jp: 'いつも、お世話になっています。', en: "Always indebted to you.", style: 'humble young man voice, soft warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_01603',
    context: 'Mrs. Mori shares her late husband\'s favorite poem with Sakura.',
    purpose: 'Widow opening up to young writer tenderly.',
    ambient: 'tatami_quiet_kettle',
    sound_effects: [],
    target_vocab: ['詩', '言葉', '亡くなる', '想う'],
    cast: ['mrs_mori_neighbor', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'mrs_mori_neighbor', jp: '夫が好きやった詩、聞く?', en: "Want to hear my husband's favorite poem?", style: 'soft older neighbor voice, warm tender vulnerable delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、ぜひ。', en: "Yes — please.", style: 'soft adult writer voice, warm respectful delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: 'ふふ、短いけど深い言葉やの。', en: "Heh — short but deep words.", style: 'gentle older woman voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お聞かせください。', en: "Please share.", style: 'tender adult writer voice, soft warm reverent delivery carefully' },
      { speaker: 'mrs_mori_neighbor', jp: '想い出すたびに、温かいわ。', en: "Each time I recall — warm.", style: 'soft older neighbor voice, warm tender reminiscing delivery carefully' },
    ],
  },
  {
    id: 'conv_01604',
    context: 'Yuki-office and Sakura have lunch and talk about creative blocks.',
    purpose: 'Two adult women supporting each other through artistic struggle.',
    ambient: 'cafe_lunch_low',
    sound_effects: [],
    target_vocab: ['行き詰まる', '休む', '頭', '言葉'],
    cast: ['yuki_office', 'sakura_teen'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '最近、書けなくて行き詰まってる。', en: "Lately I can't write — stuck.", style: 'soft adult writer voice, warm honest tired delivery carefully' },
      { speaker: 'yuki_office', jp: 'まあ、無理しないで。', en: "Oh — don't push yourself.", style: 'gentle office woman voice, soft warm caring delivery carefully' },
      { speaker: 'sakura_teen', jp: '頭、言葉が浮かばない。', en: "Mind — no words come.", style: 'gentle adult writer voice, soft warm frustrated delivery carefully' },
      { speaker: 'yuki_office', jp: 'たまには、休んでみたら?', en: "Why not rest for a while?", style: 'warm office woman voice, soft caring suggesting delivery carefully' },
      { speaker: 'sakura_teen', jp: 'そうね、焦りすぎてる。', en: "Right — rushing too much.", style: 'soft adult writer voice, warm honest reflection delivered carefully' },
      { speaker: 'yuki_office', jp: '体と心、大切に。', en: "Body and heart — take care.", style: 'tender office woman voice, soft warm wise delivery carefully' },
      { speaker: 'sakura_teen', jp: 'ありがとう、心が軽くなった。', en: "Thanks — feels lighter.", style: 'warm adult writer voice, soft tender grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_01605',
    context: 'Big extended group hosts a community open day at the cafe.',
    purpose: 'Multiple voices welcoming neighbors warmly.',
    ambient: 'cafe_open_day_buzz',
    sound_effects: [],
    target_vocab: ['集まる', '地域', '交流', '楽しむ', '感謝'],
    cast: ['aoi_barista', 'kenji_office', 'mei_romantic', 'sakura_teen', 'naoko_aunt', 'hina_child', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '皆さん、ようこそ!', en: "Everyone — welcome!", style: 'bright adult woman voice, soft warm cheerful hostess delivery carefully' },
      { speaker: 'kenji_office', jp: '地域の交流、ええもんやな。', en: "Community gatherings — lovely.", style: 'soft Kansai man voice, warm fond delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'みんなで楽しもか!', en: "Let's all enjoy!", style: 'brassy Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'こうやって集まれて、嬉しい。', en: "Glad we can gather like this.", style: 'tender young woman voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: 'みんなの笑顔、いいね。', en: "Everyone's smiles — lovely.", style: 'soft adult writer voice, warm fond observation delivered carefully' },
      { speaker: 'hina_child', jp: '楽しい、ずっと続けたい!', en: "Fun — want this to last!", style: 'bright teen girl voice, soft warm energetic delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼくもまた来る!', en: "I'll come back too!", style: 'energetic child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'みんなのおかげで、できてる。', en: "Thanks to everyone — this happens.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'kenji_office', jp: '来年も、続けような。', en: "Next year too — let's continue.", style: 'warm Kansai man voice, soft committed delivery carefully' },
      { speaker: 'naoko_aunt', jp: '当たり前や、毎年やで!', en: "Of course — every year!", style: 'animated Kansai aunt voice, bright loud confident delivery carefully' },
      { speaker: 'mei_romantic', jp: '感謝の気持ち、いっぱい。', en: "Full of gratitude.", style: 'soft young woman voice, warm tender grateful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こういう日、書きたくなる。', en: "Days like this — make me want to write.", style: 'tender adult writer voice, soft warm inspired delivery carefully' },
      { speaker: 'hina_child', jp: 'みんな、ありがとう!', en: "Everyone — thanks!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_080 wrote', CONVERSATIONS.length, 'files');
