import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_126)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  C('conv_02501',
    'Kenji helps Yuki install a work program.',
    'WIDENED SCENARIO: tech help; software vocabulary (プログラム/入力/アクセス/アップ/バー) in natural home.',
    'office_quiet_low',
    ['プログラム', '入力', 'アクセス', 'アップ', 'バー'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'この新しいプログラム、入れ方が分からなくて。', en: "I don't know how to install this new program.", style: 'slightly stuck office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'kenji_office', jp: 'まず、上のバーから設定を開いて下さい。', en: "First, open settings from the top bar.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'バーを押したら、画面が出ました。', en: "I pressed the bar and a screen appeared.", style: 'engaged office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'そこに、社員番号を入力して下さい。', en: "Enter your employee number there.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '入力したら、アクセスできました。', en: "After entering it, I got access.", style: 'relieved office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'プログラムを、最新版にアップして下さい。', en: "Please update the program to the latest version.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'アップしたら、通信も速くなりました。', en: "After updating, the connection got faster too.", style: 'satisfied office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: '通信が安定すれば、もう大丈夫です。', en: "Once the connection is stable, you're fine.", style: 'reassuring office man voice, soft warm patient closing throughout' },
    ]),

  C('conv_02502',
    'Kenji and Ren troubleshoot a slow web app.',
    'WIDENED SCENARIO: tech troubleshooting; web vocabulary (クリック/通信/入力/アクセス/アップ) in natural home.',
    'office_quiet_low',
    ['クリック', '通信', '入力', 'アクセス', 'アップ'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'クリックしても、反応が遅いんです。', en: "Even when I click, it responds slowly.", style: 'mildly frustrated young colleague voice, soft warm earnest throughout' },
      { speaker: 'kenji_office', jp: '通信の状態を、確認してみましょう。', en: "Let's check the connection status.", style: 'analytical office man voice, soft warm focused guiding throughout' },
      { speaker: 'ren_uni', jp: 'もう一度、アクセスし直しますか?', en: "Shall I access it again?", style: 'engaged young colleague voice, soft warm earnest throughout' },
      { speaker: 'kenji_office', jp: 'ええ、IDを入力して、入り直して下さい。', en: "Yes, enter your ID and re-enter.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: '入力したら、アクセスが速くなりました。', en: "After entering it, access got faster.", style: 'relieved young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: 'アプリを、最新にアップしておきましょう。', en: "Let's update the app to the latest.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'ren_uni', jp: 'アップしたら、クリックも軽くなった。', en: "After updating, clicking got snappier too.", style: 'satisfied young colleague voice, soft warm appreciative throughout' },
      { speaker: 'kenji_office', jp: '通信さえ良ければ、快適に使えますよ。', en: "As long as the connection's good, it runs smoothly.", style: 'reassuring office man voice, soft warm closing throughout' },
    ]),

  C('conv_02503',
    'Political news: Sakura and Ren on a city-policy debate.',
    'WIDENED SCENARIO: political news; civic vocabulary (述べ/発言/議員/批判/都市) in natural home.',
    'studio_room_tone',
    ['述べ', '発言', '議員', '批判', '都市'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '都市の開発を巡り、議論が続いています。', en: "Debate continues over the city's development.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '議員は、どんな発言をしたんですか?', en: "What statement did the member make?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ある議員が、計画の見直しを述べました。', en: "One member stated the plan should be revised.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: 'その発言に、批判は出ましたか?', en: "Did criticism arise over that statement?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '住民からは、強い批判もありました。', en: "There was strong criticism from residents too.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '都市の声を、どう反映するかですね。', en: "The question is how to reflect the city's voice.", style: 'thoughtful young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '他の議員も、意見を述べる予定です。', en: "Other members plan to state their views too.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '冷静な発言が、求められていますね。', en: "Calm statements are being called for.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02504',
    'News report: Sakura and Ren on a police investigation.',
    'WIDENED SCENARIO: incident news; safety vocabulary (警察/被害/議員/発言/述べ) in natural home.',
    'studio_room_tone',
    ['警察', '被害', '議員', '発言', '述べ'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '昨夜、市内で事故が起きました。', en: "An accident occurred in the city last night.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '被害の状況は、どうですか?', en: "What's the extent of the damage?", style: 'measured young reporter voice, soft warm serious focus throughout' },
      { speaker: 'sakura_teen', jp: '大きな被害は、出ていないそうです。', en: "Reportedly there's no major damage.", style: 'clear adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '警察は、原因を述べましたか?', en: "Did the police state the cause?", style: 'serious young reporter voice, soft warm focus throughout' },
      { speaker: 'sakura_teen', jp: '警察は、調査中だと述べました。', en: "The police stated it's under investigation.", style: 'professional adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '地元の議員も、発言していますか?', en: "Are local members commenting too?", style: 'curious young reporter voice, soft warm focus throughout' },
      { speaker: 'sakura_teen', jp: '議員が、安全対策の強化を発言しました。', en: "A member called for stronger safety measures.", style: 'clear adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '警察の発表を、待ちたいですね。', en: "We'll await the police announcement.", style: 'earnest young reporter voice, soft warm calm closing throughout' },
    ]),

  C('conv_02505',
    'Finance meeting: Hiroshi-boss and Yuki on a bank loan.',
    'WIDENED SCENARIO: finance meeting; banking vocabulary (銀行/株/税/利益/無料) in natural home.',
    'office_quiet_low',
    ['銀行', '株', '税', '利益', '無料'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '銀行との話は、進んでいるかね?', en: "Are talks with the bank progressing?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'はい、銀行から良い返事が来ました。', en: "Yes, we got a good reply from the bank.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '株の発行は、どうするかね?', en: "What about issuing shares?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '株を出せば、利益が安定します。', en: "Issuing shares would stabilize profit.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '税の負担は、増えないのかね?', en: "Won't the tax burden increase?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '税を引いても、利益は十分残ります。', en: "Even after tax, plenty of profit remains.", style: 'reassuring office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '銀行の相談は、費用がかかるのかね?', en: "Does the bank consultation cost money?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'いいえ、相談は無料だそうです。', en: "No, the consultation is free.", style: 'helpful office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02506',
    'Ren explains a funding plan to Yuki.',
    'WIDENED SCENARIO: finance discussion; capital vocabulary (資金/発行/株/銀行/利益) in natural home.',
    'office_quiet_low',
    ['資金', '発行', '株', '銀行', '利益'],
    ['ren_uni', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '新しい事業に、資金が必要です。', en: "We need funds for the new venture.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '資金は、どこから集めますか?', en: "Where do we raise the funds?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '株を発行して、資金を集めます。', en: "We'll issue shares to raise funds.", style: 'precise young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '銀行からも、借りるんですか?', en: "Do we also borrow from the bank?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '銀行の融資と、株の発行を組み合わせます。', en: "We combine a bank loan with a share issue.", style: 'measured young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '利益が出るまで、時間はかかりますか?', en: "Will it take time until we see profit?", style: 'curious office woman voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '二年ほどで、利益が見込めます。', en: "We can expect profit in about two years.", style: 'confident young analyst voice, soft warm professional focus throughout' },
      { speaker: 'yuki_office', jp: '資金の計画、よく分かりました。', en: "I understand the funding plan well.", style: 'satisfied office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02507',
    'Mei and Aoi chat about a canceled plan.',
    'Casual register hitting everyday stragglers (だって/つもり/残念/もらう/おく) naturally.',
    'cafe_quiet_chatter',
    ['だって', 'つもり', '残念', 'もらう', 'おく'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '明日の映画、行くつもりだったの。', en: "I was planning to go to the movie tomorrow.", style: 'soft warm woman voice, gentle slightly disappointed delivery throughout' },
      { speaker: 'aoi_barista', jp: 'えっ、行けなくなったの?残念!', en: "Huh, you can't go anymore? That's a shame!", style: 'bright barista voice, soft warm sympathetic delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、だって急に仕事が入って。', en: "Yeah, because work suddenly came up.", style: 'gentle woman voice, soft warm rueful delivery throughout' },
      { speaker: 'aoi_barista', jp: 'チケット、誰かにもらってもらう?', en: "Should you have someone take the ticket?", style: 'helpful barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '友達にもらってもらうつもりなの。', en: "I plan to have a friend take it.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '次は、早めに予約しておこうね。', en: "Next time, let's reserve early.", style: 'warm barista voice, soft warm encouraging delivery throughout' },
      { speaker: 'mei_romantic', jp: 'そうね、今度はおくびに出さず計画するわ。', en: "Right, next time I'll plan quietly.", style: 'gentle woman voice, soft warm resolved delivery throughout' },
      { speaker: 'aoi_barista', jp: '残念だけど、また誘ってね!', en: "It's a shame, but invite me again!", style: 'cheerful barista voice, soft warm bubbly delivery throughout' },
    ]),

  C('conv_02508',
    'Grandma teaches Sho table manners.',
    'Casual home register hitting body/object vocabulary (耳/箸/右/知る/だって) naturally.',
    'tatami_room_quiet',
    ['耳', '箸', '右', '知る', 'だって'],
    ['sachiko_grandma', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sachiko_grandma', jp: '正坊、お箸は右手で持つのよ。', en: "Sho dear, hold your chopsticks in your right hand.", style: 'tender grandmother voice, soft warm gentle patient delivery throughout' },
      { speaker: 'sho_child', jp: 'だって、左の方が持ちやすいよ。', en: "But the left is easier to hold!", style: 'pouty small child voice, bright warm insistent delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'お箸の持ち方も、覚えると良いわ。', en: "It's good to learn how to hold chopsticks too.", style: 'tender grandmother voice, soft warm gentle patient delivery throughout' },
      { speaker: 'sho_child', jp: '右で持つと、変な感じ。', en: "Holding with my right feels weird.", style: 'uncertain small child voice, bright warm earnest delivery throughout' },
      { speaker: 'sachiko_grandma', jp: '練習すれば、すぐ慣れると知るわよ。', en: "If you practice, you'll soon find you get used to it.", style: 'encouraging grandmother voice, soft warm gentle delivery throughout' },
      { speaker: 'sho_child', jp: '耳まで、ご飯ついちゃった!', en: "I got rice up to my ear!", style: 'giggly small child voice, bright warm playful delivery throughout' },
      { speaker: 'sachiko_grandma', jp: 'あらあら、耳を拭きましょうね。', en: "Oh my, let's wipe your ear.", style: 'tender grandmother voice, soft warm amused affectionate delivery throughout' },
      { speaker: 'sho_child', jp: '右手で持てたよ、見て!', en: "I held it with my right hand, look!", style: 'proud small child voice, bright warm triumphant delivery throughout' },
    ]),

  C('conv_02509',
    'Asuka lectures on the Earth and space.',
    'WIDENED SCENARIO: science lecture; cosmology vocabulary (宇宙/地球/得る/含め/同様) in natural home.',
    'lecture_hall_quiet',
    ['宇宙', '地球', '得る', '含め', '同様'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '地球は、広い宇宙の一部です。', en: "Earth is a part of the vast universe.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '宇宙には、地球以外の星もありますか?', en: "Are there stars besides Earth in space?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '無数の星を含めて、宇宙は広がっています。', en: "Including countless stars, the universe expands.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '地球と同様の星は、あるんですか?', en: "Are there stars similar to Earth?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '地球と同様の環境は、稀だと考えられます。', en: "Earth-like environments are thought to be rare.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '宇宙のことは、どうやって知るんですか?', en: "How do we learn about space?", style: 'thoughtful teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '観測から、多くの情報を得ます。', en: "We gain much information from observation.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '宇宙を含めて、自然は不思議ですね。', en: "Including space, nature is mysterious.", style: 'moved teen boy voice, soft warm wonder delivery throughout' },
    ]),

  C('conv_02510',
    'Asuka lectures on categories and criteria.',
    'WIDENED SCENARIO: lecture; formal connectives (基準/いわゆる/または/要素/含め) in natural home.',
    'lecture_hall_quiet',
    ['基準', 'いわゆる', 'または', '要素', '含め'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '分類には、明確な基準が必要です。', en: "Classification needs clear criteria.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '基準は、形または色で決めますか?', en: "Do we set criteria by form or color?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '形または機能、両方の要素を見ます。', en: "We look at both form or function, both elements.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'いわゆる例外も、含めるんですか?', en: "Do we include the so-called exceptions too?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '例外を含めて、基準を考えます。', en: "We consider criteria, including exceptions.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '大事な要素は、何でしょうか?', en: "What's the important element?", style: 'engaged adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'いわゆる共通点が、最も重要な要素です。', en: "The so-called common point is the most important element.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '基準を含めて、よく整理できました。', en: "Including the criteria, I organized it well.", style: 'satisfied adult student voice, soft warm appreciative throughout' },
    ]),

  C('conv_02511',
    'Hiroshi-boss and Ren review on-site operations.',
    'WIDENED SCENARIO: business ops; field vocabulary (現場/業者/現状/強化/開始) in natural home.',
    'office_quiet_low',
    ['現場', '業者', '現状', '強化', '開始'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '現場の状況は、どうなっているかね?', en: "How are things at the site?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '現状では、人手が足りていません。', en: "As it stands, we're short on staff.", style: 'honest young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '外部の業者に、頼めるかね?', en: "Can we ask an outside contractor?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '信頼できる業者に、声をかけています。', en: "I'm reaching out to a reliable contractor.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '安全の体制も、強化したい。', en: "I also want to strengthen safety measures.", style: 'firm boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '来週から、点検を強化して開始します。', en: "From next week, we'll start stronger inspections.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '現場の声も、よく聞いてくれ。', en: "Listen well to the voices on the ground.", style: 'caring boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '現状を、こまめに報告いたします。', en: "I'll report the situation frequently.", style: 'reliable young manager voice, soft warm resolved closing throughout' },
    ]),

  C('conv_02512',
    'Hiroshi-boss and Yuki discuss new hires for a factory.',
    'WIDENED SCENARIO: business HR; employment vocabulary (採用/雇用/工場/確保/終了) in natural home.',
    'office_quiet_low',
    ['採用', '雇用', '工場', '確保', '終了'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '工場の人員を、増やしたい。', en: "I want to increase factory staff.", style: 'decisive boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '今期の採用は、何名でしょうか?', en: "How many hires this term?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '十名ほど、新たに採用したい。', en: "I'd like to newly hire about ten.", style: 'measured boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '雇用の条件は、見直しますか?', en: "Will we revise the employment terms?", style: 'thoughtful office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '良い人材を確保するため、改善しよう。', en: "Let's improve them to secure good people.", style: 'firm boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '工場の安全も、確保が大切ですね。', en: "Securing factory safety is important too.", style: 'earnest office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '募集は、来月末で終了する予定だ。', en: "Recruitment ends at the end of next month.", style: 'measured boss voice, soft warm composed clarity throughout' },
      { speaker: 'yuki_office', jp: '採用が終了したら、ご報告します。', en: "I'll report once hiring ends.", style: 'reliable office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02513',
    'Aoi and Riku talk about a live concert.',
    'WIDENED SCENARIO: music chat; performance vocabulary (演奏/ライブ/クラブ/魅力/年代) in natural home.',
    'cafe_quiet_chatter',
    ['演奏', 'ライブ', 'クラブ', '魅力', '年代'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '昨日のライブ、すごかったよ!', en: "Yesterday's live show was amazing!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: '演奏は、どんな感じだった?', en: "What was the performance like?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '演奏が、耳に心地よくてさ。', en: "The performance was pleasing to the ear.", style: 'enthusiastic teen boy voice, bright warm admiring delivery throughout' },
      { speaker: 'aoi_barista', jp: 'あのバンドの魅力は、声だよね。', en: "That band's charm is the vocals.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '小さなクラブだったけど、最高だった。', en: "It was a small club, but it was the best.", style: 'happy teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'チケットは、高くなかった?', en: "Wasn't the ticket expensive?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'ちょっと高くても、魅力で十分元が取れた。', en: "Even a bit pricey, the charm made it worth it.", style: 'satisfied teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '私の年代も、ああいう演奏が好きだな。', en: "My generation likes that kind of playing too.", style: 'warm barista voice, soft warm fond delivery throughout' },
    ]),

  C('conv_02514',
    'Asuka discusses a novel and its commentary with Mei.',
    'WIDENED SCENARIO: literature chat; book vocabulary (小説/コラム/解説/示し/求める) in natural home.',
    'living_room_quiet',
    ['小説', 'コラム', '解説', '示し', '求める'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの小説、最後が切なかったです。', en: "That novel's ending was bittersweet.", style: 'soft emotional woman voice, gentle warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '作者は、何を求めて書いたのでしょうね。', en: "I wonder what the author sought in writing it.", style: 'thoughtful teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '新聞のコラムに、解説がありましたよ。', en: "There was commentary in a newspaper column.", style: 'gentle woman voice, soft warm engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'その解説は、何を示していましたか?', en: "What did that commentary indicate?", style: 'curious teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '孤独の意味を、示していました。', en: "It pointed to the meaning of loneliness.", style: 'soft woman voice, gentle warm thoughtful delivery throughout' },
      { speaker: 'asuka_teacher', jp: '読者は、答えを求めて読むものですね。', en: "Readers read seeking answers.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: 'コラムを読んで、小説がより深まりました。', en: "Reading the column deepened the novel for me.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '良い解説は、新たな視点を示します。', en: "Good commentary shows a new perspective.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_02515',
    'Daichi and Mei plan a trip to an island.',
    'WIDENED SCENARIO: travel planning; transport vocabulary (交通/料金/増加/直接/島) in natural home.',
    'cafe_quiet_chatter',
    ['交通', '料金', '増加', '直接', '島'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '今度、南の島に行かへん?', en: "Want to go to a southern island sometime?", style: 'lively Kansai man voice, warm hearty inviting delivery throughout' },
      { speaker: 'mei_romantic', jp: 'いいですね。交通は、どうしましょう?', en: "Sounds nice. How about transportation?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: '船やと、料金が安いんよ。', en: "By ship, the fare is cheap.", style: 'cheerful Kansai man voice, warm friendly delivery throughout' },
      { speaker: 'mei_romantic', jp: '島まで、直接行けるんですか?', en: "Can we go directly to the island?", style: 'curious woman voice, gentle warm engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'うん、直接行ける便があるで。', en: "Yeah, there's a direct service.", style: 'lively Kansai man voice, warm reassuring delivery throughout' },
      { speaker: 'mei_romantic', jp: '夏は、観光客が増加しますよね。', en: "In summer, tourists increase, right?", style: 'thoughtful woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'そやな、増加する前に行こか。', en: "Right, let's go before they increase.", style: 'cheerful Kansai man voice, warm friendly delivery throughout' },
      { speaker: 'mei_romantic', jp: '交通の予約、早めにしておきますね。', en: "I'll book the transport early.", style: 'gentle woman voice, soft warm reliable closing delivery throughout' },
    ]),

  C('conv_02516',
    'Yuki and Kenji coordinate a team message.',
    'WIDENED SCENARIO: workplace coordination; communication vocabulary (メッセージ/全員/正しい/思え/まさに) in natural home.',
    'office_quiet_low',
    ['メッセージ', '全員', '正しい', '思え', 'まさに'],
    ['yuki_office', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '全員に、お知らせを送りたいんです。', en: "I want to send a notice to everyone.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'メッセージは、もう作りましたか?', en: "Have you made the message yet?", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'はい、この文で正しいでしょうか?', en: "Yes, is this wording correct?", style: 'careful office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'まさに、これで完璧だと思えます。', en: "Indeed, this seems perfect to me.", style: 'reassuring office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '全員に、同時に届きますか?', en: "Will it reach everyone at once?", style: 'attentive office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'ええ、一度で全員に送れます。', en: "Yes, you can send to everyone at once.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '内容が正しいか、もう一度確認します。', en: "I'll check once more if the content is correct.", style: 'diligent office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'まさに、その慎重さが大事ですよ。', en: "Indeed, that carefulness matters.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02517',
    'Asuka and Riku tour a historic building.',
    'WIDENED SCENARIO: architecture visit; structure vocabulary (建物/壁/入る/そのまま/もと) in natural home.',
    'museum_hall_quiet',
    ['建物', '壁', '入る', 'そのまま', 'もと'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'この建物、すごく古いですね。', en: "This building is really old.", style: 'impressed teen boy voice, soft warm curious engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'もとは、お城だった建物ですよ。', en: "It was originally a castle.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '中に、入ってもいいんですか?', en: "Can we go inside?", style: 'eager teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、静かに入りましょう。', en: "Yes, let's enter quietly.", style: 'gentle teacher voice, soft warm guiding clarity throughout' },
      { speaker: 'riku_teen', jp: '壁が、もとの色のままですね。', en: "The walls are still their original color.", style: 'observant teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、壁はそのまま残されています。', en: "Yes, the walls are preserved as they were.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '昔の人が、ここに入ったんですね。', en: "People long ago entered here.", style: 'reflective teen boy voice, soft warm wonder throughout' },
      { speaker: 'asuka_teacher', jp: 'もとの姿を、そのまま感じられますね。', en: "You can feel its original form just as it was.", style: 'warm teacher voice, soft warm measured clarity closing throughout' },
    ]),

  C('conv_02518',
    'Ren reports research findings to Hiroshi-boss.',
    'WIDENED SCENARIO: research report; analysis vocabulary (レポート/示し/得る/現状/強化) in natural home.',
    'office_quiet_low',
    ['レポート', '示し', '得る', '現状', '強化'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '調査のレポートが、まとまりました。', en: "The research report is finished.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '何か、新しい発見はあったかね?', en: "Were there any new findings?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'データは、利用者の不満を示しています。', en: "The data indicates user dissatisfaction.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '現状の弱点が、見えたわけだね。', en: "So the current weaknesses became visible.", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'はい、改善のヒントも得られました。', en: "Yes, we also gained hints for improvement.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'では、対応を強化しよう。', en: "Then let's strengthen our response.", style: 'decisive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'レポートを基に、体制を強化します。', en: "Based on the report, we'll strengthen the system.", style: 'reliable young presenter voice, soft warm resolved throughout' },
      { speaker: 'hiroshi_boss', jp: 'この現状から、得るものは多いな。', en: "There's much to gain from this situation.", style: 'satisfied boss voice, soft warm closing throughout' },
    ]),

  C('conv_02519',
    'Geography documentary: Asuka and Riku on regions and islands.',
    'WIDENED SCENARIO: geography discussion; place vocabulary (県/州/島/都市/増加) in natural home.',
    'living_room_quiet',
    ['県', '州', '島', '都市', '増加'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '日本は、たくさんの島でできているんですか?', en: "Is Japan made of many islands?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、大小の島が連なっています。', en: "Yes, large and small islands stretch in a line.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '外国では、県の代わりに州ですか?', en: "Abroad, do they use states instead of prefectures?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'そうです。国によって、県や州に分かれます。', en: "Right. Depending on the country, it's prefectures or states.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '大きな都市は、島に集まりますか?', en: "Do big cities gather on the islands?", style: 'curious teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '主要な都市の人口は、増加しています。', en: "The population of major cities is increasing.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '県や州ごとに、特色があるんですね。', en: "Each prefecture or state has its character.", style: 'understanding teen boy voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '都市の増加は、世界中で進んでいますよ。', en: "Urban growth is advancing worldwide.", style: 'warm teacher voice, soft warm measured clarity closing throughout' },
    ]),

  C('conv_02520',
    'Ren and Mei chat after a planetarium visit.',
    'Casual reflective register reusing stragglers (宇宙/演奏/つもり/残念/知る) naturally.',
    'cafe_quiet_chatter',
    ['宇宙', '演奏', 'つもり', '残念', '知る'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'プラネタリウム、宇宙が綺麗だったね。', en: "The planetarium — the universe was beautiful.", style: 'soft warm woman voice, gentle dreamy delivery throughout' },
      { speaker: 'ren_uni', jp: 'うん、背景の演奏も良かったね。', en: "Yeah, the background music was good too.", style: 'warm young man voice, soft warm reflective delivery throughout' },
      { speaker: 'mei_romantic', jp: '宇宙のことを、もっと知りたくなった。', en: "I got curious to know more about space.", style: 'gentle woman voice, soft warm engaged delivery throughout' },
      { speaker: 'ren_uni', jp: '次は、別の回も見るつもりだよ。', en: "I plan to see another showing next time.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '今日で終わりなのが、残念だな。', en: "It's a shame today's the last one.", style: 'soft woman voice, gentle warm wistful delivery throughout' },
      { speaker: 'ren_uni', jp: '演奏付きの回は、また来るらしいよ。', en: "The showings with music are coming back, apparently.", style: 'reassuring young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '知れて良かった。絶対行くつもり!', en: "Glad to know. I'm definitely planning to go!", style: 'bright woman voice, soft warm delighted delivery throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_126 wrote', CONVERSATIONS.length, 'files');
