import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_145)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // count-4 cleanup (示す 取る 理想 サーバー 深刻 乗る)
  C('conv_02881',
    'Kenji and Ren handle a serious server load.',
    'WIDENED SCENARIO: tech troubleshooting; vocabulary (示す/取る/理想/サーバー/深刻) in natural home.',
    'office_quiet_low',
    ['示す', '取る', '理想', 'サーバー', '深刻'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'サーバーの数字が、深刻な値を示しています。', en: "The server numbers show serious values.", style: 'concerned young colleague voice, soft warm earnest throughout' },
      { speaker: 'kenji_office', jp: 'ログを取って、原因を調べましょう。', en: "Let's take the logs and find the cause.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '理想は、止めずに直すことですよね?', en: "Ideally, we fix it without stopping it, right?", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、理想はそうですが、慎重に。', en: "Yes, ideally, but carefully.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'グラフが、急な上昇を示していますね。', en: "The graph shows a sharp rise.", style: 'observant young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '深刻になる前に、対策を取ります。', en: "We'll take measures before it gets serious.", style: 'reassuring office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'サーバーが波に乗り切れるといいですね。', en: "I hope the server can ride the wave.", style: 'hopeful young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '理想に近づくよう、記録を取り続けます。', en: "I'll keep taking records to approach the ideal.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // CLUSTER A — home/health (ゴミ 袋 育児 体重 階段)
  C('conv_02882',
    'Saito advises Yuki on health after childbirth.',
    'WIDENED SCENARIO: medical advice; vocabulary (ゴミ/袋/育児/体重/階段) in natural home.',
    'clinic_room_quiet',
    ['ゴミ', '袋', '育児', '体重', '階段'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '育児が忙しくて、運動できません。', en: "Childcare keeps me busy; I can't exercise.", style: 'tired office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '階段の上り下りも、良い運動ですよ。', en: "Going up and down stairs is good exercise.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: '体重が、少し増えてしまって。', en: "My weight has gone up a little.", style: 'concerned office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '育児の合間に、軽く動きましょう。', en: "Move lightly between childcare tasks.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: 'ゴミ出しも、いい運動ですか?', en: "Is taking out the trash good exercise too?", style: 'curious office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: 'ええ、ゴミ袋を運ぶのも運動です。', en: "Yes, carrying the trash bag is exercise too.", style: 'clear doctor voice, soft warm measured clarity throughout' },
      { speaker: 'yuki_office', jp: '階段を使って、体重を戻します。', en: "I'll use the stairs to get my weight back.", style: 'resolved office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '育児も体も、無理なく続けて下さいね。', en: "Keep up both childcare and your body without strain.", style: 'warm doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_02883',
    'Yumiko and Sho do morning chores.',
    'Casual home register; vocabulary (ゴミ/袋/育児/体重/階段) in natural home.',
    'kitchen_evening_quiet',
    ['ゴミ', '袋', '育児', '体重', '階段'],
    ['yumiko_mom', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'yumiko_mom', jp: '正坊、ゴミを袋にまとめてくれる?', en: "Sho, can you gather the trash in the bag?", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: 'うん!この袋、いっぱいだね。', en: "Yeah! This bag is full.", style: 'cheerful small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: '階段の下まで、運んでくれる?', en: "Can you carry it to the bottom of the stairs?", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '重いけど、できるよ!', en: "It's heavy, but I can do it!", style: 'determined small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'ありがとう。体重、増えてきたね。', en: "Thanks. You're gaining weight, huh.", style: 'warm mother voice, soft warm affectionate delivery throughout' },
      { speaker: 'sho_child', jp: '大きくなった証拠だよ!', en: "It's proof I've grown!", style: 'proud small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '育児って、毎日が運動みたいね。', en: "Childcare is like exercise every day.", style: 'gentle mother voice, soft warm amused delivery throughout' },
      { speaker: 'sho_child', jp: '階段、駆け上がって戻るね!', en: "I'll race up the stairs and back!", style: 'energetic small child voice, bright warm cheerful closing delivery throughout' },
    ]),

  C('conv_02884',
    'Mei and Aoi chat about a friend\'s new baby.',
    'Casual register; vocabulary (ゴミ/袋/育児/体重/階段) in natural home.',
    'cafe_quiet_chatter',
    ['ゴミ', '袋', '育児', '体重', '階段'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '友達が、育児で大変そうなの。', en: "My friend seems swamped with childcare.", style: 'bright barista voice, soft warm caring delivery throughout' },
      { speaker: 'mei_romantic', jp: '赤ちゃんの体重は、順調なの?', en: "Is the baby's weight on track?", style: 'soft warm woman voice, gentle delivery throughout' },
      { speaker: 'aoi_barista', jp: 'うん、すくすく体重が増えてるって。', en: "Yeah, gaining weight steadily, they say.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '階段のある家だと、大変そうね。', en: "With stairs in the house, it must be tough.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ゴミ出しも、ひと苦労みたい。', en: "Even taking out trash seems like a chore.", style: 'sympathetic barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '私も、ゴミ袋を運んであげようかな。', en: "Maybe I'll carry the trash bags for her.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '育児の合間に、手伝えたらいいね。', en: "It'd be nice to help between childcare.", style: 'warm barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '階段の上り下り、私も手伝うね。', en: "I'll help with the stairs too.", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  // CLUSTER B — abstract/emotion (運命 幸福 正義 才能 誤解)
  C('conv_02885',
    'Asuka lectures on happiness and fate.',
    'WIDENED SCENARIO: philosophy lecture; vocabulary (運命/幸福/正義/才能/誤解) in natural home.',
    'lecture_hall_quiet',
    ['運命', '幸福', '正義', '才能', '誤解'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '幸福とは、何だと思いますか?', en: "What do you think happiness is?", style: 'contemplative teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '運命に、左右されるんですか?', en: "Is it swayed by fate?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '運命だけでは、幸福は決まりません。', en: "Fate alone doesn't decide happiness.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '才能が、幸福を生むんでしょうか?', en: "Does talent produce happiness?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '才能だけ、というのは誤解です。', en: "That it's only talent is a misunderstanding.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '正義と幸福は、関係しますか?', en: "Are justice and happiness related?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '正義を貫く人に、幸福が宿ります。', en: "Happiness dwells in those who uphold justice.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'sakura_teen', jp: '誤解を解くのも、大事なんですね。', en: "Clearing up misunderstanding matters too.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_02886',
    'Asuka and Mei discuss a novel\'s themes.',
    'WIDENED SCENARIO: literature chat; vocabulary (運命/幸福/正義/才能/誤解) in natural home.',
    'living_room_quiet',
    ['運命', '幸福', '正義', '才能', '誤解'],
    ['asuka_teacher', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この小説、運命の物語ですね。', en: "This novel is a story of fate.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: '主人公は、才能に恵まれていますね。', en: "The protagonist is blessed with talent.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: 'でも、幸福ではなかったですね。', en: "But he wasn't happy.", style: 'thoughtful woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '才能と幸福は、別のものです。', en: "Talent and happiness are different things.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '彼は、誤解されて孤独でしたね。', en: "He was misunderstood and lonely.", style: 'gentle woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '誤解の中でも、正義を信じました。', en: "Even amid misunderstanding, he believed in justice.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '最後に、運命を受け入れましたね。', en: "In the end, he accepted his fate.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'asuka_teacher', jp: '正義を貫く姿に、幸福を感じました。', en: "I felt happiness in his upholding justice.", style: 'warm teacher voice, soft warm reflective closing clarity throughout' },
    ]),

  C('conv_02887',
    'Ren and Mei reflect on a documentary subject.',
    'Casual register; vocabulary (運命/幸福/正義/才能/誤解) in natural home.',
    'cafe_quiet_chatter',
    ['運命', '幸福', '正義', '才能', '誤解'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの人の人生、運命的だったね。', en: "That person's life was fateful.", style: 'soft warm woman voice, gentle reflective delivery throughout' },
      { speaker: 'ren_uni', jp: 'うん、すごい才能の持ち主だった。', en: "Yeah, a person of great talent.", style: 'warm young man voice, soft warm reflective delivery throughout' },
      { speaker: 'mei_romantic', jp: '才能ゆえに、誤解もされたよね。', en: "Because of the talent, he was misunderstood too.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '誤解されても、正義を曲げなかった。', en: "Even misunderstood, he didn't bend his sense of justice.", style: 'admiring young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '本当の幸福を、見つけたのかな。', en: "I wonder if he found true happiness.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '運命を、自分で選んだ気がするよ。', en: "I feel he chose his own fate.", style: 'thoughtful young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '正義と幸福、両方を生きたんだね。', en: "He lived both justice and happiness.", style: 'moved woman voice, soft warm tender delivery throughout' },
      { speaker: 'ren_uni', jp: '誤解を越えた生き方、見習いたいな。', en: "I want to emulate his life beyond misunderstanding.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  // CLUSTER C — business (融資 商売 クライアント 受付 進行)
  C('conv_02888',
    'Hiroshi-boss and Yuki discuss a financing deal.',
    'WIDENED SCENARIO: business meeting; vocabulary (融資/商売/クライアント/受付/進行) in natural home.',
    'office_quiet_low',
    ['融資', '商売', 'クライアント', '受付', '進行'],
    ['hiroshi_boss', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '銀行の融資は、進んでいるかね?', en: "Is the bank financing progressing?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'はい、順調に進行しています。', en: "Yes, it's progressing smoothly.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '商売の拡大に、使うんだったね。', en: "We're using it to expand the business, right?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'ええ、商売の幅を広げます。', en: "Yes, we'll widen the scope of business.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'クライアントの反応は、どうかね?', en: "How is the clients' response?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: 'クライアントは、前向きです。', en: "The clients are positive.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '受付の体制も、整えてくれ。', en: "Set up the reception system too.", style: 'firm boss voice, soft warm clarity throughout' },
      { speaker: 'yuki_office', jp: '受付を整え、進行を早めます。', en: "I'll ready reception and speed up the progress.", style: 'resolved office woman voice, soft warm clarity closing throughout' },
    ]),

  C('conv_02889',
    'Ren reports a client project to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (融資/商売/クライアント/受付/進行) in natural home.',
    'office_quiet_low',
    ['融資', '商売', 'クライアント', '受付', '進行'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'クライアントとの商売が、まとまりました。', en: "The deal with the client came together.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '融資の話も、出たのかね?', en: "Did financing come up too?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'はい、融資の相談を受けました。', en: "Yes, we received a financing inquiry.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '進行は、予定どおりかね?', en: "Is progress on schedule?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '進行は、計画どおりに進んでいます。', en: "Progress is going as planned.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: 'クライアントの受付は、誰が?', en: "Who handles client reception?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '専任の社員が、受付を担当します。', en: "A dedicated staffer handles reception.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '商売を、着実に進めてくれ。', en: "Advance the business steadily.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02890',
    'Sakura interviews a small-business owner.',
    'WIDENED SCENARIO: business interview; vocabulary (融資/商売/クライアント/受付/進行) in natural home.',
    'office_quiet_low',
    ['融資', '商売', 'クライアント', '受付', '進行'],
    ['sakura_teen', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: 'ご商売は、順調ですか?', en: "Is business going well?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'daichi_kansai', jp: 'おかげさんで、商売は順調やで。', en: "Thankfully, business is going well.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'sakura_teen', jp: '融資は、受けられたんですか?', en: "Were you able to get financing?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '銀行の融資で、店を広げたんや。', en: "I expanded the shop with bank financing.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'sakura_teen', jp: 'クライアントは、増えましたか?', en: "Did clients increase?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '新しいクライアントが、どんどん来るで。', en: "New clients keep coming.", style: 'enthusiastic Kansai man voice, warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '受付も、忙しいんですね。', en: "Reception is busy too.", style: 'thoughtful adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '受付を増やして、進行を早めとるわ。', en: "I added reception staff to speed things up.", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  // CLUSTER D — cafe/food (甘い カップ 素材 快適 過ぎる)
  C('conv_02891',
    'Aoi and Mei develop a new cafe drink.',
    'Casual register; vocabulary (甘い/カップ/素材/快適/過ぎる) in natural home.',
    'cafe_quiet_chatter',
    ['甘い', 'カップ', '素材', '快適', '過ぎる'],
    ['aoi_barista', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '新しい甘いドリンク、考えたの!', en: "I came up with a new sweet drink!", style: 'excited barista voice, soft warm bubbly delivery throughout' },
      { speaker: 'mei_romantic', jp: 'いいね、どんな素材を使うの?', en: "Nice, what ingredients do you use?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'aoi_barista', jp: '自然な素材で、優しい甘さなの。', en: "Natural ingredients, with a gentle sweetness.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'この大きいカップ、いいね。', en: "This big cup is nice.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'カップも、手に快適なものを選んだの。', en: "I chose a cup that's comfortable in the hand.", style: 'engaged barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '甘過ぎると、飽きちゃうかな?', en: "If it's too sweet, will people tire of it?", style: 'thoughtful woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '甘過ぎないよう、素材を調整したよ。', en: "I adjusted the ingredients so it's not too sweet.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '快適なカップで、ゆっくり飲めるね。', en: "With a comfortable cup, you can sip slowly.", style: 'gentle woman voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02892',
    'Daichi and Aoi taste-test a dessert.',
    'Casual register; vocabulary (甘い/カップ/素材/快適/過ぎる) in natural home.',
    'cafe_quiet_chatter',
    ['甘い', 'カップ', '素材', '快適', '過ぎる'],
    ['daichi_kansai', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'このケーキ、ちょっと甘いなあ。', en: "This cake is a bit sweet.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'aoi_barista', jp: '甘過ぎた?素材を変えてみようか。', en: "Too sweet? Shall I change the ingredients?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'daichi_kansai', jp: '素材はええで。砂糖が過ぎただけや。', en: "The ingredients are fine. Just too much sugar.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'このカップに、盛り付けると可愛いよ。', en: "Plated in this cup, it looks cute.", style: 'engaged barista voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ええカップやな。座り心地も快適や。', en: "Nice cup. The seating's comfortable too.", style: 'warm Kansai man voice, warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '快適な店にしたくて、頑張ってるの。', en: "I'm working to make it a comfortable shop.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '甘さを抑えたら、もっと売れるで。', en: "Cut the sweetness and it'll sell more.", style: 'lively Kansai man voice, warm friendly delivery throughout' },
      { speaker: 'aoi_barista', jp: '良い素材で、甘過ぎない味にするね。', en: "With good ingredients, I'll make it not too sweet.", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02893',
    'Mei and Ren relax at a cozy cafe.',
    'Casual register; vocabulary (甘い/カップ/素材/快適/過ぎる) in natural home.',
    'cafe_quiet_chatter',
    ['甘い', 'カップ', '素材', '快適', '過ぎる'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'このカフェ、すごく快適だね。', en: "This cafe is really comfortable.", style: 'soft warm woman voice, gentle relaxed delivery throughout' },
      { speaker: 'ren_uni', jp: 'うん、椅子もカップも、いい感じだね。', en: "Yeah, the chairs and cups feel nice.", style: 'warm young man voice, soft warm relaxed delivery throughout' },
      { speaker: 'mei_romantic', jp: 'このケーキ、甘さがちょうどいいの。', en: "This cake's sweetness is just right.", style: 'gentle woman voice, soft warm delighted delivery throughout' },
      { speaker: 'ren_uni', jp: '甘過ぎなくて、食べやすいね。', en: "Not too sweet, easy to eat.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '素材に、こだわってるんだろうね。', en: "They must be particular about ingredients.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '良い素材だと、味が違うよね。', en: "With good ingredients, the taste is different.", style: 'thoughtful young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'カップが温かくて、手が快適だな。', en: "The cup is warm and comfortable in my hands.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '時間が過ぎるのも、忘れちゃうね。', en: "We even forget time passing.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  // CLUSTER E — society/news (会談 信号 通知 視聴 路線)
  C('conv_02894',
    'News: Sakura and Ren on a leaders\' summit.',
    'WIDENED SCENARIO: news-analysis; vocabulary (会談/信号/通知/視聴/路線) in natural home.',
    'studio_room_tone',
    ['会談', '信号', '通知', '視聴', '路線'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '両国の会談が、行われました。', en: "A summit between the two nations was held.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '会談は、良い信号になりましたか?', en: "Did the summit become a good signal?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: 'ええ、前向きな信号と受け止められています。', en: "Yes, it's seen as a positive signal.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '結果は、いつ通知されますか?', en: "When will the results be announced?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '正式な通知は、明日の予定です。', en: "The official notice is set for tomorrow.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '視聴者の関心も、高いですね。', en: "Viewers' interest is high too.", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '会談は、多くの人が視聴しました。', en: "Many people watched the summit.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '対話の路線が、続くといいですね。', en: "I hope the path of dialogue continues.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_02895',
    'Kenji shows Yuki a transit-info app.',
    'WIDENED SCENARIO: tech help; vocabulary (会談/信号/通知/視聴/路線) in natural home.',
    'office_quiet_low',
    ['信号', '通知', '視聴', '路線', '会談'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'この乗り換えアプリ、便利ですか?', en: "Is this transfer app handy?", style: 'curious office woman voice, soft warm engaged delivery throughout' },
      { speaker: 'kenji_office', jp: 'ええ、路線を一目で示してくれます。', en: "Yes, it shows the routes at a glance.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '遅れの通知も、来るんですか?', en: "Do delay notifications come too?", style: 'attentive office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'はい、通知が、すぐに届きます。', en: "Yes, notifications arrive right away.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '路線図は、信号待ちでも見られますか?', en: "Can I view the route map while waiting at a light?", style: 'curious office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: '信号待ちの間に、さっと確認できますよ。', en: "You can check quickly while at a signal.", style: 'reassuring office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'ニュースの会談も、視聴できますか?', en: "Can I watch the news summit too?", style: 'engaged office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: '会談の中継も、視聴できますよ。', en: "You can watch the summit broadcast too.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_02896',
    'Daichi and Mei plan a route to an event.',
    'Casual register; vocabulary (信号/通知/視聴/路線/会談) in natural home.',
    'cafe_quiet_chatter',
    ['信号', '通知', '視聴', '路線', '会談'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '会場まで、どの路線で行く?', en: "Which line do we take to the venue?", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '東の路線が、早いみたいですよ。', en: "The eastern line seems faster.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: '遅れの通知、来てへんか?', en: "Has a delay notice come?", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '今のところ、通知はないですね。', en: "So far, no notifications.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '信号が多い道は、避けよか。', en: "Let's avoid roads with lots of signals.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'イベントは、会談みたいに大事ですね。', en: "The event matters like an important summit.", style: 'playful woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '家で、配信を視聴してもええけどな。', en: "We could watch the stream at home too.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '路線を調べて、早めに出ましょう。', en: "Let's check the route and leave early.", style: 'gentle woman voice, soft warm closing delivery throughout' },
    ]),

  // CLUSTER F — entertainment (ジャズ サイン 原作 シート 見かけ)
  C('conv_02897',
    'Aoi and Riku talk about a jazz concert.',
    'Casual register; vocabulary (ジャズ/サイン/原作/シート/見かけ) in natural home.',
    'cafe_quiet_chatter',
    ['ジャズ', 'サイン', '原作', 'シート', '見かけ'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '昨日、ジャズのライブに行ったよ!', en: "Yesterday I went to a jazz live show!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、いいシートで聴けた?', en: "Nice, did you get a good seat?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '前のシートで、迫力満点だったよ。', en: "From a front seat, it was powerful.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'サインは、もらえたの?', en: "Did you get an autograph?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、CDにサインをもらったんだ!', en: "Yeah, I got an autograph on a CD!", style: 'thrilled teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そのジャズ、映画の原作にもなったよね。', en: "That jazz became a film's original work too, right?", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '原作の本も、読んでみたいな。', en: "I want to read the original book too.", style: 'eager teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '駅で、その演奏家を見かけたよ!', en: "I spotted that musician at the station!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_02898',
    'Mei and Asuka discuss a film and its source.',
    'WIDENED SCENARIO: film discussion; vocabulary (ジャズ/サイン/原作/シート/見かけ) in natural home.',
    'living_room_quiet',
    ['ジャズ', 'サイン', '原作', 'シート', '見かけ'],
    ['mei_romantic', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの映画、原作が小説なんですね。', en: "That film's source is a novel.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、原作も素晴らしいですよ。', en: "Yes, the original is wonderful too.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '音楽は、ジャズが多かったですね。', en: "The music had a lot of jazz.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'ジャズが、物語の雰囲気を作りますね。', en: "Jazz creates the story's atmosphere.", style: 'patient teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '映画館のシート、快適でしたか?', en: "Were the cinema seats comfortable?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: '後ろのシートが、見やすかったです。', en: "The back seats were easy to view from.", style: 'composed teacher voice, soft warm reflective clarity throughout' },
      { speaker: 'mei_romantic', jp: '原作者を、街で見かけたんですよ。', en: "I spotted the original author in town.", style: 'delighted woman voice, soft warm delivery throughout' },
      { speaker: 'asuka_teacher', jp: 'まあ、サインをもらえばよかったですね。', en: "Oh, you should have gotten an autograph.", style: 'warm teacher voice, soft warm gentle closing clarity throughout' },
    ]),

  C('conv_02899',
    'Riku tells Mei about meeting a musician.',
    'Casual register; vocabulary (ジャズ/サイン/原作/シート/見かけ) in natural home.',
    'cafe_quiet_chatter',
    ['ジャズ', 'サイン', '原作', 'シート', '見かけ'],
    ['riku_teen', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '昨日、有名なジャズの人を見かけたよ!', en: "Yesterday I spotted a famous jazz person!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'mei_romantic', jp: 'すごい!話しかけられたの?', en: "Amazing! Did you talk to them?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、ノートにサインをもらったんだ。', en: "Yeah, I got an autograph in my notebook.", style: 'thrilled teen boy voice, bright warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'その人、映画の原作も書いたんだよね。', en: "That person wrote a film's original too, right?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'そう!原作の話も、少し聞けたよ。', en: "Yeah! I got to hear a bit about the original too.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ライブの席は、いいシートだった?', en: "Was your live-show seat good?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'riku_teen', jp: '一番前のシートで、最高だったよ!', en: "Front-row seat, it was the best!", style: 'happy teen boy voice, bright warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'サイン、大事にしてね!', en: "Treasure that autograph!", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-3 cleanup (を通じて 通じ 並ん + 後半 含ま)
  C('conv_02900',
    'Asuka lectures on learning through experience.',
    'WIDENED SCENARIO: lecture; connectives (を通じて/通じ/並ん/後半/含ま) in natural home.',
    'lecture_hall_quiet',
    ['を通じて', '並ん', '後半', '含ま', '通じ'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '人は、経験を通じて成長します。', en: "People grow through experience.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '本を通じても、学べますか?', en: "Can we learn through books too?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、読書を通じて、視野が広がります。', en: "Yes, through reading, your horizons widen.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '授業の後半は、何を学びますか?', en: "What do we study in the second half of class?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '後半は、実例を含めて考えます。', en: "In the second half, we think, including examples.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '本が、棚に並んでいますね。', en: "Books are lined up on the shelf.", style: 'observant adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '並んだ本を通じて、世界とつながります。', en: "Through the lined-up books, we connect to the world.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '経験を通じて、学び続けたいです。', en: "I want to keep learning through experience.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_145 wrote', CONVERSATIONS.length, 'files');
