import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_159)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // abstract cluster finish (極めて ゆえ 果たし 意志 ないし) ×2
  C('conv_03161',
    'Asuka lectures on perseverance and will.',
    'WIDENED SCENARIO: philosophy lecture; vocabulary (極めて/ゆえ/果たし/意志/ないし) in natural home.',
    'lecture_hall_quiet',
    ['極めて', 'ゆえ', '果たし', '意志', 'ないし'],
    ['asuka_teacher', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '目標を果たすには、強い意志が要ります。', en: "To achieve a goal, strong will is needed.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: '意志ゆえに、人は粘れるんですね。', en: "Because of will, people can persevere.", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '極めて困難でも、諦めずに進みます。', en: "Even extremely difficult, we go on without giving up.", style: 'patient teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: '一人、ないし数人で、支え合うんですか?', en: "Do one or a few people support each other?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '仲間がいるゆえに、極めて強くなれます。', en: "Because we have companions, we grow extremely strong.", style: 'composed teacher voice, soft warm measured philosophical clarity throughout' },
      { speaker: 'ren_uni', jp: '役割を、果たしたいです。', en: "I want to fulfill my role.", style: 'resolved young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '意志あるゆえに、君は果たせます。', en: "Because you have will, you can fulfill it.", style: 'warm teacher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '極めて大切な、学びでした。', en: "It was an extremely important lesson.", style: 'moved young student voice, soft warm realization closing throughout' },
    ]),

  C('conv_03162',
    'Ren interviews an athlete on willpower.',
    'WIDENED SCENARIO: sports interview; vocabulary (極めて/ゆえ/果たし/意志/ないし) in natural home.',
    'office_quiet_low',
    ['極めて', 'ゆえ', '果たし', '意志', 'ないし'],
    ['ren_uni', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '目標を果たす、秘訣は何ですか?', en: "What's the secret to achieving a goal?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'daichi_kansai', jp: '強い意志や。それに尽きるわ。', en: "Strong will. That's all there is to it.", style: 'lively Kansai athlete voice, warm hearty delivery throughout' },
      { speaker: 'ren_uni', jp: '練習は、極めて厳しいんですか?', en: "Is training extremely tough?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'daichi_kansai', jp: '極めて厳しいけど、意志で乗り越えるんや。', en: "It's extremely tough, but I overcome it by will.", style: 'cheerful Kansai athlete voice, warm delivery throughout' },
      { speaker: 'ren_uni', jp: '一人、ないしチームで挑むんですね。', en: "You face it alone or as a team.", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'daichi_kansai', jp: '仲間がおるゆえに、頑張れるんや。', en: "Because I have teammates, I can push on.", style: 'warm Kansai athlete voice, warm delivery throughout' },
      { speaker: 'ren_uni', jp: '夢を、果たせそうですか?', en: "Does it seem you can achieve your dream?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'daichi_kansai', jp: '意志があるゆえに、必ず果たすで!', en: "Because I have will, I'll surely fulfill it!", style: 'lively Kansai athlete voice, warm hearty closing delivery throughout' },
    ]),

  // count-4/3 cleanup (向かう 話し合い させる おっしゃる ライト) ×2
  C('conv_03163',
    'Hiroshi-boss and Ren discuss a difficult decision.',
    'WIDENED SCENARIO: business chat; vocabulary (向かう/話し合い/させる/おっしゃる/ライト) in natural home.',
    'office_quiet_low',
    ['向かう', '話し合い', 'させる', 'おっしゃる', 'ライト'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '解決に向かうため、話し合いを開こう。', en: "To head toward a resolution, let's hold a discussion.", style: 'composed boss voice, soft warm authoritative clarity throughout' },
      { speaker: 'ren_uni', jp: '皆を、納得させたいですね。', en: "I want to get everyone on board.", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '担当者は、何とおっしゃっていた?', en: "What did the person in charge say?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '前向きに進めたいと、おっしゃっていました。', en: "They said they want to proceed positively.", style: 'reliable young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '会議室のライトを、つけておいてくれ。', en: "Turn on the meeting room lights.", style: 'firm boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'ライトをつけて、準備させます。', en: "I'll turn on the lights and have it prepared.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '話し合いで、未来へ向かおう。', en: "Through discussion, let's head to the future.", style: 'composed boss voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '良い方向に向かうよう、努めます。', en: "I'll strive to head in a good direction.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_03164',
    'Mei and Aoi plan to fix a problem together.',
    'Casual register; vocabulary (向かう/話し合い/させる/おっしゃる/ライト) in natural home.',
    'cafe_quiet_chatter',
    ['向かう', '話し合い', 'させる', 'おっしゃる', 'ライト'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '店の問題、話し合いで解決したいね。', en: "Let's solve the shop's problem through discussion.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'うん、前向きに向かおうね。', en: "Yeah, let's head forward positively.", style: 'soft warm woman voice, gentle delivery throughout' },
      { speaker: 'aoi_barista', jp: '店長は、改善したいとおっしゃってたよ。', en: "The manager said they want to improve it.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'みんなを、安心させたいね。', en: "I want to reassure everyone.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '暗いから、ライトを足そうって話したの。', en: "Since it's dark, we talked about adding lights.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ライトを増やせば、明るくなるね。', en: "More lights will brighten it up.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '話し合いを、続けようね。', en: "Let's keep up the discussion.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '良い方向に、向かいそうだね!', en: "It looks like it's heading in a good direction!", style: 'bright woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-1 cluster A — casual/shopping (旧 売っ 売る きっかけ そろそろ) + かける
  C('conv_03165',
    'Daichi and Mei talk about selling old goods.',
    'Casual register; vocabulary (旧/売っ/売る/きっかけ/そろそろ) in natural home.',
    'street_quiet_distant',
    ['旧', '売っ', '売る', 'きっかけ', 'そろそろ'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'そろそろ、旧式の道具を売ろうと思てな。', en: "I'm thinking of selling the old-style tools soon.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '売るきっかけは、何だったんですか?', en: "What prompted you to sell?", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'daichi_kansai', jp: '引っ越しが、きっかけやねん。', en: "The move was the trigger.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '旧式でも、売れますか?', en: "Even old-style, will they sell?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '欲しい人がおるから、売れるで。', en: "There are people who want them, so they'll sell.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '時間をかけて、探したんですね。', en: "You spent time finding buyers.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'そろそろ、ネットでも売ろか。', en: "Maybe I'll sell online soon too.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '旧い道具に、新しい持ち主ですね。', en: "Old tools getting new owners.", style: 'soft woman voice, gentle warm cheerful closing delivery throughout' },
    ]),

  C('conv_03166',
    'Riku and Aoi chat about a garage sale.',
    'Casual register; vocabulary (旧/売っ/売る/きっかけ/そろそろ) in natural home.',
    'cafe_quiet_chatter',
    ['旧', '売っ', '売る', 'きっかけ', 'そろそろ'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '旧いゲームを、売ろうと思うんだ。', en: "I'm thinking of selling my old games.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、何がきっかけなの?', en: "Nice, what's the trigger?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '部屋が狭くなったのが、きっかけだよ。', en: "My room getting cramped was the trigger.", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '旧いソフトでも、売れるの?', en: "Even old software, will it sell?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'レアなのは、高く売れるんだ。', en: "Rare ones sell for a high price.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そろそろ、私も片付けようかな。', en: "Maybe I'll tidy up soon too.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '昨日、一個売ったら、嬉しかったよ。', en: "I sold one yesterday and was happy.", style: 'happy teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そろそろ、一緒にフリマ出そうよ!', en: "Let's do a flea market together soon!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03167',
    'Sakura interviews a shop owner about a comeback.',
    'WIDENED SCENARIO: business interview; vocabulary (旧/売っ/売る/きっかけ/かける) in natural home.',
    'office_quiet_low',
    ['旧', '売っ', '売る', 'きっかけ', 'かける'],
    ['sakura_teen', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '旧い商品が、また売れているそうですね。', en: "I hear old products are selling again.", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'daichi_kansai', jp: 'そや、旧式が人気を取り戻したんや。', en: "Yeah, the old style regained popularity.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'sakura_teen', jp: '人気の、きっかけは何ですか?', en: "What was the trigger for the popularity?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: 'テレビで紹介されたのが、きっかけや。', en: "Being featured on TV was the trigger.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '宣伝に、力をかけたんですか?', en: "Did you put effort into promotion?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '宣伝に時間をかけて、よう売ったわ。', en: "I spent time on promotion and sold a lot.", style: 'enthusiastic Kansai man voice, warm delivery throughout' },
      { speaker: 'sakura_teen', jp: '一日で、たくさん売ったんですか?', en: "Did you sell a lot in a day?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'daichi_kansai', jp: '飛ぶように売れたで。きっかけに感謝や。', en: "They flew off the shelves. I'm grateful for the trigger.", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_03168',
    'Mei and Ren browse a secondhand bookshop.',
    'Casual register; vocabulary (旧/売っ/売る/きっかけ/かける) in natural home.',
    'cafe_quiet_chatter',
    ['旧', '売っ', '売る', 'きっかけ', 'かける'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'この旧い本屋、味があるね。', en: "This old bookshop has character.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'ren_uni', jp: '旧版の本も、売ってるんだね。', en: "They sell old editions too.", style: 'warm young man voice, soft warm engaged delivery throughout' },
      { speaker: 'mei_romantic', jp: '読書を始めたきっかけ、覚えてる?', en: "Remember what got you into reading?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'この店が、きっかけだったんだ。', en: "This shop was the trigger.", style: 'nostalgic young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '店主が、時間をかけて選ぶんだって。', en: "The owner spends time selecting, they say.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '丁寧に売ってるのが、伝わるね。', en: "You can tell they sell with care.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '旧い本に、出会えて嬉しいな。', en: "I'm glad to come across old books.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'また、ここに来るきっかけにしようね。', en: "Let's make this a reason to come again.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-1 cluster B — lecture/business (一定 形式 内部 諸 一覧)
  C('conv_03169',
    'Asuka lectures on document formats.',
    'WIDENED SCENARIO: writing lecture; vocabulary (一定/形式/内部/諸/一覧) in natural home.',
    'lecture_hall_quiet',
    ['一定', '形式', '内部', '諸', '一覧'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '報告書は、一定の形式で書きます。', en: "Reports are written in a fixed format.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '形式は、なぜ決まっているんですか?', en: "Why is the format fixed?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '一定の形式だと、読みやすいからです。', en: "A fixed format makes it easy to read.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '内部の構成も、決まっていますか?', en: "Is the internal structure fixed too?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '内部は、序論や結論に分かれます。', en: "Internally, it's divided into intro and conclusion.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '参考にした諸資料は、どう示しますか?', en: "How do we show the various references?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '諸資料を、一覧にして載せます。', en: "We list the various references in a table.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '一覧があると、分かりやすいですね。', en: "A list makes it easy to understand.", style: 'satisfied adult student voice, soft warm realization throughout' },
    ]),

  C('conv_03170',
    'Yuki and Hiroshi-boss standardize internal forms.',
    'WIDENED SCENARIO: business ops; vocabulary (一定/形式/内部/諸/一覧) in natural home.',
    'office_quiet_low',
    ['一定', '形式', '内部', '諸', '一覧'],
    ['yuki_office', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '社内の書類を、統一したいんです。', en: "I want to standardize internal documents.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '一定の形式に、まとめてくれ。', en: "Compile them into a fixed format.", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '内部の部署ごとに、違っていたんです。', en: "They differed by internal department.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '諸部署の意見も、聞いたかね?', en: "Did you hear the various departments' views?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '諸部署から、意見を集めました。', en: "I gathered views from the various departments.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '書類の一覧は、作ったかね?', en: "Did you make a list of the documents?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '一覧にして、内部で共有します。', en: "I'll list them and share internally.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '一定の形式で、効率が上がるな。', en: "A fixed format raises efficiency.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_03171',
    'Kenji helps Ren organize a data list.',
    'WIDENED SCENARIO: tech/office; vocabulary (一定/形式/内部/諸/一覧) in natural home.',
    'office_quiet_low',
    ['一定', '形式', '内部', '諸', '一覧'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'データを、一覧にまとめたいんです。', en: "I want to compile the data into a list.", style: 'engaged young colleague voice, soft warm focused throughout' },
      { speaker: 'kenji_office', jp: '一定の形式に、そろえましょう。', en: "Let's align it to a fixed format.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '内部のデータも、含めますか?', en: "Do we include internal data too?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '内部のデータは、別の一覧にしましょう。', en: "Let's put internal data in a separate list.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '諸条件も、書き込みますか?', en: "Do we write in the various conditions too?", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '諸条件を、形式に沿って入れましょう。', en: "Let's enter the various conditions per the format.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '一覧になると、見やすいですね。', en: "As a list, it's easy to view.", style: 'satisfied young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '一定の形式が、内部の混乱を防ぎます。', en: "A fixed format prevents internal confusion.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_03172',
    'Ren reports a standardization plan to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (一定/形式/内部/諸/一覧) in natural home.',
    'office_quiet_low',
    ['一定', '形式', '内部', '諸', '一覧'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '形式を、一定に統一する案です。', en: "It's a plan to standardize the format.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '内部の反応は、どうかね?', en: "How's the internal reaction?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '内部からは、好意的です。', en: "Internally, it's favorable.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '諸問題は、整理できたかね?', en: "Were the various issues sorted out?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '諸問題を、一覧にまとめました。', en: "I compiled the various issues into a list.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '一定の基準で、進めてくれ。', en: "Proceed by a fixed standard.", style: 'firm boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '一覧をもとに、形式を整えます。', en: "Based on the list, I'll order the format.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '内部の効率が、上がりそうだな。', en: "Internal efficiency looks set to rise.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  // count-1 cluster C — emotion/casual (ひどい 逃げ ほんとう 聴く ブルー)
  C('conv_03173',
    'Mei comforts Aoi after a rough day.',
    'Casual register; vocabulary (ひどい/逃げ/ほんとう/聴く/ブルー) in natural home.',
    'cafe_quiet_chatter',
    ['ひどい', '逃げ', 'ほんとう', '聴く', 'ブルー'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '今日、ほんとうにひどい一日だったの。', en: "Today was really a terrible day.", style: 'tired barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '大丈夫?話、聴くよ。', en: "Are you okay? I'll listen.", style: 'soft warm woman voice, gentle caring delivery throughout' },
      { speaker: 'aoi_barista', jp: 'お客さんに、ひどく怒られちゃって。', en: "A customer scolded me badly.", style: 'downcast barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'それは、気分がブルーになるね。', en: "That would put you in a blue mood.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '逃げ出したい気分だったよ。', en: "I felt like running away.", style: 'honest barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '逃げてもいいの。無理しないで。', en: "It's okay to step away. Don't push yourself.", style: 'gentle woman voice, soft warm caring delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ほんとう、聴いてくれてありがとう。', en: "Really, thank you for listening.", style: 'grateful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ブルーな日も、明日は晴れるよ。', en: "Even on blue days, tomorrow will clear up.", style: 'soft woman voice, gentle warm affectionate closing delivery throughout' },
    ]),

  C('conv_03174',
    'Ren and Mei talk through a hard week.',
    'Casual register; vocabulary (ひどい/逃げ/ほんとう/聴く/ブルー) in natural home.',
    'living_room_quiet',
    ['ひどい', '逃げ', 'ほんとう', '聴く', 'ブルー'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '今週、ほんとうに大変だったよ。', en: "This week was really tough.", style: 'tired young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ひどく疲れた顔してるね。', en: "You look terribly tired.", style: 'soft warm woman voice, gentle caring delivery throughout' },
      { speaker: 'ren_uni', jp: '正直、逃げ出したくなったよ。', en: "Honestly, I wanted to run away.", style: 'honest young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '逃げずに頑張ったの、えらいよ。', en: "Not running and pushing through — that's admirable.", style: 'gentle woman voice, soft warm caring delivery throughout' },
      { speaker: 'ren_uni', jp: '気分が、ずっとブルーだったんだ。', en: "I'd been feeling blue the whole time.", style: 'downcast young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '好きな音楽でも、聴こうよ。', en: "Let's listen to some music you like.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '音楽を聴くと、ほんとう落ち着くよ。', en: "Listening to music really calms me.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ブルーな気分、一緒に晴らそうね。', en: "Let's clear away that blue mood together.", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_03175',
    'Saito reassures a stressed patient.',
    'WIDENED SCENARIO: medical advice; vocabulary (ひどい/逃げ/ほんとう/聴く/ブルー) in natural home.',
    'clinic_room_quiet',
    ['ひどい', '逃げ', 'ほんとう', '聴く', 'ブルー'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '先生、ひどく落ち込むんです。', en: "Doctor, I get terribly down.", style: 'vulnerable office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: 'まず、ゆっくりお話を聴きますね。', en: "First, let me listen to you slowly.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: '全部から、逃げたくなるんです。', en: "I want to run from everything.", style: 'honest office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '逃げたい気持ちは、自然なことです。', en: "The urge to flee is natural.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: 'ブルーな日が、続いていて。', en: "Blue days have been continuing.", style: 'soft office woman voice, gentle warm delivery throughout' },
      { speaker: 'saito_doctor', jp: 'ほんとうに、よく頑張っていますよ。', en: "You're really doing your best.", style: 'warm doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: '聴いてもらえて、安心しました。', en: "Being listened to, I feel reassured.", style: 'relieved office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: 'ブルーな時は、無理に逃げず、休みましょう。', en: "When blue, rather than fleeing, let's rest.", style: 'gentle doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_03176',
    'Riku and Aoi talk about a sad movie.',
    'Casual register; vocabulary (ひどい/逃げ/ほんとう/聴く/ブルー) in natural home.',
    'cafe_quiet_chatter',
    ['ひどい', '逃げ', 'ほんとう', '聴く', 'ブルー'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: 'あの映画、ほんとう泣けたよ。', en: "That movie really made me cry.", style: 'moved teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '主人公、ひどい目に遭ってたよね。', en: "The hero went through a terrible time.", style: 'soft barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: '逃げずに、立ち向かったのが良かった。', en: "He faced it without fleeing — that was good.", style: 'admiring teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '音楽も、ブルーで切なかったね。', en: "The music was blue and bittersweet too.", style: 'gentle barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'サントラ、もう一回聴きたいな。', en: "I want to listen to the soundtrack again.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '聴くと、また泣いちゃいそう。', en: "Listening to it, I might cry again.", style: 'soft barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'ほんとう、いい映画だったね。', en: "It really was a good movie.", style: 'warm teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ブルーだけど、心に残る作品だね。', en: "Blue, but a work that stays with you.", style: 'gentle barista voice, soft warm affectionate closing delivery throughout' },
    ]),

  // count-1 cluster D — tech/misc (発明 ハード モード フル 札幌)
  C('conv_03177',
    'Kenji and Ren discuss a new gadget.',
    'WIDENED SCENARIO: tech chat; vocabulary (発明/ハード/モード/フル/札幌) in natural home.',
    'office_quiet_low',
    ['発明', 'ハード', 'モード', 'フル', '札幌'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この装置、すごい発明ですね。', en: "This device is an amazing invention.", style: 'impressed young colleague voice, soft warm engaged throughout' },
      { speaker: 'kenji_office', jp: '札幌の研究チームが、発明したんですよ。', en: "A Sapporo research team invented it.", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'ハードの性能は、高いですか?', en: "Is the hardware performance high?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ハードが、極めて優秀です。', en: "The hardware is extremely excellent.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '省エネのモードも、あるんですか?', en: "Is there an energy-saving mode too?", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'ええ、モードを切り替えられます。', en: "Yes, you can switch modes.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'フルで動かすと、速いですか?', en: "When running at full, is it fast?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'フルパワーだと、抜群に速いですよ。', en: "At full power, it's outstandingly fast.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_03178',
    'Ren interviews an inventor in Sapporo.',
    'WIDENED SCENARIO: tech interview; vocabulary (発明/ハード/モード/フル/札幌) in natural home.',
    'office_quiet_low',
    ['発明', 'ハード', 'モード', 'フル', '札幌'],
    ['ren_uni', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '札幌で、発明をされているんですね。', en: "You invent things in Sapporo.", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'kenji_office', jp: 'はい、札幌の工房で作っています。', en: "Yes, I make them in a Sapporo workshop.", style: 'warm inventor voice, soft warm sincere clarity throughout' },
      { speaker: 'ren_uni', jp: 'ハードの設計は、大変ですか?', en: "Is hardware design hard?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'kenji_office', jp: 'ハードの調整に、時間をかけます。', en: "I spend time tuning the hardware.", style: 'measured inventor voice, soft warm informative clarity throughout' },
      { speaker: 'ren_uni', jp: '複数のモードが、あるんですか?', en: "Are there multiple modes?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'kenji_office', jp: 'ええ、用途でモードを変えます。', en: "Yes, modes change by use.", style: 'clear inventor voice, soft warm informative clarity throughout' },
      { speaker: 'ren_uni', jp: 'フルに性能を、引き出せますか?', en: "Can you draw out full performance?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'kenji_office', jp: 'フルに使える発明を、目指しています。', en: "I aim for an invention you can use to the fullest.", style: 'warm inventor voice, soft warm sincere closing clarity throughout' },
    ]),

  C('conv_03179',
    'Riku and Daichi talk about a Sapporo trip.',
    'Casual register; vocabulary (発明/ハード/モード/フル/札幌) in natural home.',
    'cafe_quiet_chatter',
    ['発明', 'ハード', 'モード', 'フル', '札幌'],
    ['riku_teen', 'daichi_kansai'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '冬休み、札幌に行ってきたよ!', en: "I went to Sapporo over winter break!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ええなあ、札幌は雪がすごいやろ?', en: "Nice, Sapporo's got tons of snow, right?", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'riku_teen', jp: 'うん、雪まつりをフルで楽しんだよ。', en: "Yeah, I enjoyed the snow festival to the fullest.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '寒さは、ハードやったやろ?', en: "The cold must've been hard, huh?", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'ハードだったけど、最高だった!', en: "It was hard, but the best!", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'カメラの撮影モード、活躍したか?', en: "Did the camera's shooting modes shine?", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'riku_teen', jp: '夜景モードで、フルに撮ったよ。', en: "I shot fully with night mode.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '雪像って、まさに発明みたいやな!', en: "Snow sculptures are like inventions!", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_03180',
    'Asuka lectures on a famous invention.',
    'WIDENED SCENARIO: science lecture; vocabulary (発明/ハード/モード/フル/札幌) in natural home.',
    'lecture_hall_quiet',
    ['発明', 'ハード', 'モード', 'フル', '札幌'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: 'この発明は、暮らしを大きく変えました。', en: "This invention greatly changed life.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'sakura_teen', jp: 'どこで、発明されたんですか?', en: "Where was it invented?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '札幌の大学で、発明されました。', en: "It was invented at a Sapporo university.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '当時のハードは、大きかったんですか?', en: "Was the hardware large back then?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ハードは大きく、性能は限られました。', en: "The hardware was large and performance limited.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '今は、いろんなモードがありますね。', en: "Now there are various modes.", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: 'フルに活用すれば、可能性は無限です。', en: "Used to the fullest, the possibilities are endless.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'sakura_teen', jp: '発明の歴史、面白いですね。', en: "The history of inventions is fascinating.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_159 wrote', CONVERSATIONS.length, 'files');
