import fs from 'node:fs'; import path from 'node:path'; import url from 'node:url';
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_162)', generated_at: NOW, source_plan_row: '' });
const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 3, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // ===== CLUSTER A: welfare-policy debate =====
  C('conv_03221', 'A teacher introduces a new social-welfare policy in class', 'Explain a welfare policy; teach 福祉/世帯/原則/所得/制限/適用/財源/協議/当事者/支持', 'lecture_hall_quiet',
    ['福祉','世帯','原則','所得','制限','適用','財源','協議','当事者','支持'], ['asuka_teacher', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '今日は新しい社会福祉の制度を取り上げます。', en: 'Today we’ll examine a new social-welfare system.', style: 'composed teacher opening a serious topic clearly' },
    { speaker: 'ren_uni', jp: 'どんな世帯が対象になるんですか？', en: 'What kind of households are eligible?', style: 'engaged student probing for the specifics' },
    { speaker: 'asuka_teacher', jp: '原則として、低所得の世帯が対象です。', en: 'In principle, low-income households are the target.', style: 'precise teacher laying out the rule plainly' },
    { speaker: 'ren_uni', jp: '所得制限はあるんですか？', en: 'Is there an income cap?', style: 'sharp student pressing on the threshold' },
    { speaker: 'asuka_teacher', jp: 'ええ、一定の所得を超えると適用されません。', en: 'Yes, above a set income it doesn’t apply.', style: 'measured teacher clarifying the boundary' },
    { speaker: 'ren_uni', jp: '財源はどこから出るんでしょう。', en: 'Where does the funding come from?', style: 'curious student following the money' },
    { speaker: 'asuka_teacher', jp: 'そこは国と自治体が協議して決めます。', en: 'That’s decided through state-municipal consultation.', style: 'informed teacher explaining the process' },
    { speaker: 'ren_uni', jp: '当事者の声は反映されるんですか？', en: 'Are the voices of those affected reflected?', style: 'principled student advocating for stakeholders' },
    { speaker: 'asuka_teacher', jp: '当事者団体の支持を得ることが前提です。', en: 'Gaining the support of stakeholder groups is a prerequisite.', style: 'thoughtful teacher stressing legitimacy' },
  ]),
  C('conv_03222', 'Two students debate who qualifies for the benefit', 'Debate eligibility; teach 世帯/適用/原則/所得/制限/財源/当事者/協議/支持/福祉', 'lecture_hall_quiet',
    ['世帯','適用','原則','所得','制限','財源','当事者','協議','支持','福祉'], ['ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: 'この制度、全世帯に適用されるの？', en: 'Does this apply to all households?', style: 'curious teen seeking the broad picture' },
    { speaker: 'ren_uni', jp: 'いや、原則は低所得層だけだよ。', en: 'No, in principle only low-income groups.', style: 'knowledgeable peer correcting gently' },
    { speaker: 'sakura_teen', jp: '所得の制限がけっこう厳しいね。', en: 'The income limit is pretty strict.', style: 'reacting teen weighing the harshness' },
    { speaker: 'ren_uni', jp: '財源が限られてるから仕方ないみたい。', en: 'Funding’s limited, so it seems unavoidable.', style: 'pragmatic peer explaining the constraint' },
    { speaker: 'sakura_teen', jp: '当事者からは不満も出てるって。', en: 'Apparently those affected have complaints.', style: 'informed teen relaying the friction' },
    { speaker: 'ren_uni', jp: 'だから国会でも何度も協議されてる。', en: 'That’s why it’s debated repeatedly in the Diet.', style: 'analytical peer noting the political churn' },
    { speaker: 'sakura_teen', jp: '世論の支持がないと通らないよね。', en: 'It won’t pass without public support, right?', style: 'shrewd teen grasping the politics' },
    { speaker: 'ren_uni', jp: '福祉の充実は誰もが願うことだけどね。', en: 'Though everyone wishes for richer welfare.', style: 'reflective peer acknowledging the ideal' },
  ]),
  C('conv_03223', 'A ward officer explains the benefit to a resident', 'Advise a citizen; teach 世帯/所得/適用/原則/制限/福祉/財源/協議/当事者/支持', 'office_quiet_low',
    ['世帯','所得','適用','原則','制限','福祉','財源','協議','当事者','支持'], ['takeda_officer', 'ryosuke_dad'], 'Medium (7-12)', [
    { speaker: 'ryosuke_dad', jp: 'うちの世帯も対象になりますか？', en: 'Is my household eligible too?', style: 'hopeful resident asking a practical question' },
    { speaker: 'takeda_officer', jp: 'ご家庭の所得によって変わります。', en: 'It depends on your household income.', style: 'measured official giving a careful answer' },
    { speaker: 'ryosuke_dad', jp: '所得が多いと適用外なんですね。', en: 'So with higher income it doesn’t apply.', style: 'understanding resident confirming the rule' },
    { speaker: 'takeda_officer', jp: 'はい、原則そういう制限があります。', en: 'Yes, in principle there’s such a limit.', style: 'polite official stating policy plainly' },
    { speaker: 'ryosuke_dad', jp: '福祉のお金って、財源は税金ですか？', en: 'Is the welfare money funded by taxes?', style: 'curious resident asking where money comes from' },
    { speaker: 'takeda_officer', jp: 'ええ、使い道は議会で協議されています。', en: 'Yes, its use is deliberated in the assembly.', style: 'informative official explaining oversight' },
    { speaker: 'ryosuke_dad', jp: '当事者として、ちゃんと支持したいです。', en: 'As one affected, I want to support it properly.', style: 'earnest resident expressing civic intent' },
    { speaker: 'takeda_officer', jp: 'ご理解ありがとうございます。', en: 'Thank you for understanding.', style: 'courteous official closing the exchange warmly' },
  ]),
  C('conv_03224', 'A student interviews an official about the policy’s aims', 'Interview on policy; teach 福祉/世帯/適用/所得/原則/制限/財源/協議/当事者/支持', 'office_quiet_low',
    ['福祉','世帯','適用','所得','原則','制限','財源','協議','当事者','支持'], ['sakura_teen', 'takeda_officer'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: 'この福祉政策の狙いは何ですか？', en: 'What’s the aim of this welfare policy?', style: 'poised teen interviewer leading clearly' },
    { speaker: 'takeda_officer', jp: '困っている世帯を直接支える点です。', en: 'To directly support struggling households.', style: 'official answering with quiet conviction' },
    { speaker: 'sakura_teen', jp: '適用の基準はどう決めるんですか？', en: 'How are the eligibility criteria set?', style: 'methodical teen pursuing the mechanics' },
    { speaker: 'takeda_officer', jp: '所得を基準に、原則を定めています。', en: 'We set principles based on income.', style: 'official explaining the framework precisely' },
    { speaker: 'sakura_teen', jp: '制限を設ける理由は？', en: 'Why impose limits?', style: 'probing teen challenging the restriction' },
    { speaker: 'takeda_officer', jp: '財源に限りがあるからです。', en: 'Because funding is finite.', style: 'official giving the blunt fiscal reason' },
    { speaker: 'sakura_teen', jp: '関係者との協議は進んでいますか？', en: 'Is consultation with stakeholders progressing?', style: 'diligent teen checking the process' },
    { speaker: 'takeda_officer', jp: '当事者の意見も聞き、広く支持を求めています。', en: 'We hear those affected and seek broad support.', style: 'official affirming an inclusive approach' },
  ]),
  C('conv_03225', 'The class wraps up the welfare discussion', 'Summarize the debate; teach 原則/所得/適用/世帯/制限/財源/当事者/協議/支持/福祉', 'lecture_hall_quiet',
    ['原則','所得','適用','世帯','制限','財源','当事者','協議','支持','福祉'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: 'この制度、原則はシンプルですね。', en: 'This system’s principle is simple.', style: 'summarizing teacher distilling the core' },
    { speaker: 'ren_uni', jp: '所得に応じて適用されるのが基本です。', en: 'The basics: it applies according to income.', style: 'concise student restating the rule' },
    { speaker: 'sakura_teen', jp: 'でも世帯ごとの事情は複雑です。', en: 'But each household’s situation is complex.', style: 'thoughtful teen adding nuance' },
    { speaker: 'asuka_teacher', jp: 'だから制限の線引きが難しいんです。', en: 'That’s why drawing the limit is hard.', style: 'teacher acknowledging the real difficulty' },
    { speaker: 'ren_uni', jp: '財源を増やせれば、もっと広げられるのに。', en: 'If funding grew, it could expand further.', style: 'wishful student naming the constraint' },
    { speaker: 'sakura_teen', jp: '当事者の声を協議に活かしてほしい。', en: 'I hope stakeholder voices feed the consultation.', style: 'earnest teen voicing a final hope' },
    { speaker: 'asuka_teacher', jp: '国民の支持があってこそ続く福祉です。', en: 'Welfare lasts only with public support.', style: 'teacher closing with a guiding principle' },
  ]),

  // ===== CLUSTER B: governance & history documentary =====
  C('conv_03226', 'Watching a documentary on the history of democracy', 'Discuss governance history; teach 民主/集団/支配/民族/司法/態度/長官', 'living_room_quiet',
    ['民主','集団','支配','民族','司法','態度','長官'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: 'この番組は民主主義の歴史を扱っています。', en: 'This program covers the history of democracy.', style: 'introducing teacher framing the documentary' },
    { speaker: 'ren_uni', jp: '昔は一部の集団が国を支配していたんですね。', en: 'Long ago a small group ruled the country.', style: 'reflective student grasping the past' },
    { speaker: 'asuka_teacher', jp: 'ええ、王や貴族が権力を握っていました。', en: 'Yes, kings and nobles held power.', style: 'teacher filling in the historical detail' },
    { speaker: 'sakura_teen', jp: 'いろんな民族が一つの国に暮らしていたんだ。', en: 'Many peoples lived in one country.', style: 'intrigued teen noticing the diversity' },
    { speaker: 'asuka_teacher', jp: '司法の独立も、長い闘いの末に生まれました。', en: 'Judicial independence was born of long struggle.', style: 'teacher conveying hard-won progress' },
    { speaker: 'ren_uni', jp: '当時の人々の態度は、今とは大きく違いますね。', en: 'People’s attitudes then differ greatly from now.', style: 'observant student comparing the eras' },
    { speaker: 'asuka_teacher', jp: '長官のような役職も、時代で意味が変わりました。', en: 'Roles like director shifted meaning over time.', style: 'teacher noting institutional change' },
    { speaker: 'sakura_teen', jp: '民主の仕組みって、当たり前じゃないんですね。', en: 'Democracy’s machinery isn’t a given, huh.', style: 'awed teen appreciating its fragility' },
  ]),
  C('conv_03227', 'Discussing how multi-ethnic states stay together', 'Discuss pluralism; teach 民族/集団/支配/民主/司法/態度/長官', 'living_room_quiet',
    ['民族','集団','支配','民主','司法','態度','長官'], ['ren_uni', 'asuka_teacher', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '多民族の国家って、まとめるの大変そう。', en: 'Multi-ethnic states seem hard to hold together.', style: 'thoughtful student raising a real tension' },
    { speaker: 'asuka_teacher', jp: 'ええ、特定の集団が支配すると対立が起きます。', en: 'Yes, when one group dominates, conflict arises.', style: 'teacher explaining the underlying risk' },
    { speaker: 'sakura_teen', jp: 'だから民主的な話し合いが必要なんですね。', en: 'So democratic dialogue is necessary.', style: 'connecting teen reaching the insight' },
    { speaker: 'asuka_teacher', jp: '司法が公平でないと、人々の信頼も崩れます。', en: 'If courts aren’t fair, public trust collapses.', style: 'teacher stressing the rule of law' },
    { speaker: 'ren_uni', jp: '指導者の態度ひとつで国が変わることも。', en: 'A leader’s attitude alone can change a nation.', style: 'student reflecting on leadership’s weight' },
    { speaker: 'asuka_teacher', jp: '警察庁の長官の判断が注目された例もあります。', en: 'A police agency director’s call once drew attention.', style: 'teacher citing a concrete example' },
    { speaker: 'sakura_teen', jp: '歴史を見ると、民主の大切さがよく分かる。', en: 'Looking at history, democracy’s value is clear.', style: 'moved teen drawing the lesson' },
  ]),
  C('conv_03228', 'Clarifying the difference between rule and governance', 'Define key terms; teach 支配/民主/集団/司法/民族/態度/長官', 'lecture_hall_quiet',
    ['支配','民主','集団','司法','民族','態度','長官'], ['sakura_teen', 'asuka_teacher', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '先生、支配と統治って違うんですか？', en: 'Teacher, are domination and governance different?', style: 'curious teen asking a precise question' },
    { speaker: 'asuka_teacher', jp: 'いい質問です。力で抑えるのが支配に近い。', en: 'Good question. Suppressing by force is closer to domination.', style: 'teacher praising and explaining carefully' },
    { speaker: 'ren_uni', jp: '民主では、集団の合意が土台になりますね。', en: 'In democracy, group consensus is the base.', style: 'student building on the definition' },
    { speaker: 'asuka_teacher', jp: 'そう、そして司法がそれを守ります。', en: 'Right, and the judiciary protects it.', style: 'teacher affirming and extending the point' },
    { speaker: 'sakura_teen', jp: '少数民族の権利はどう守られるんですか？', en: 'How are minority peoples’ rights protected?', style: 'conscientious teen pressing on fairness' },
    { speaker: 'asuka_teacher', jp: '法の下では、誰もが平等という態度が原則です。', en: 'Under law, the principle is an attitude of equality.', style: 'teacher articulating a foundational value' },
    { speaker: 'ren_uni', jp: '行政の長官にも、説明責任がありますね。', en: 'Administrative directors bear accountability too.', style: 'student noting institutional duty' },
  ]),
  C('conv_03229', 'A documentary episode on an independence movement', 'Discuss an independence story; teach 民族/集団/支配/民主/司法/態度/長官', 'living_room_quiet',
    ['民族','集団','支配','民主','司法','態度','長官'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: 'この回は、ある民族の独立運動が題材です。', en: 'This episode is about one people’s independence movement.', style: 'teacher setting up the episode’s theme' },
    { speaker: 'ren_uni', jp: '大きな集団が立ち上がったんですね。', en: 'A large group rose up.', style: 'engaged student picturing the scale' },
    { speaker: 'sakura_teen', jp: '長く支配されていた人たちですよね。', en: 'They’d been ruled for a long time, right?', style: 'sympathetic teen recalling their plight' },
    { speaker: 'asuka_teacher', jp: 'ええ、民主的な選挙を勝ち取りました。', en: 'Yes, they won democratic elections.', style: 'teacher narrating the triumph' },
    { speaker: 'ren_uni', jp: '新しい司法制度も整えたとか。', en: 'They also built a new judicial system.', style: 'student adding a notable detail' },
    { speaker: 'sakura_teen', jp: '指導者の冷静な態度が印象的でした。', en: 'The leader’s calm attitude was striking.', style: 'impressed teen highlighting character' },
    { speaker: 'asuka_teacher', jp: '初代の長官が改革を主導したそうです。', en: 'The first director apparently led the reforms.', style: 'teacher crediting the key figure' },
  ]),
  C('conv_03230', 'Reflecting on what keeps democracy alive', 'Draw closing lessons; teach 民主/集団/支配/司法/民族/態度/長官', 'living_room_quiet',
    ['民主','集団','支配','司法','民族','態度','長官'], ['ren_uni', 'asuka_teacher', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '民主って、維持するのも大変なんですね。', en: 'Democracy is hard to maintain too.', style: 'sobered student reaching a mature point' },
    { speaker: 'asuka_teacher', jp: '一つの集団が暴走すれば、また支配が生まれます。', en: 'If one group runs amok, domination returns.', style: 'teacher delivering a cautionary truth' },
    { speaker: 'sakura_teen', jp: 'だから司法のチェックが大事なんだ。', en: 'So judicial checks matter.', style: 'teen consolidating the lesson firmly' },
    { speaker: 'asuka_teacher', jp: '多様な民族が共に生きる知恵も問われます。', en: 'The wisdom for diverse peoples to coexist is tested too.', style: 'teacher widening the moral scope' },
    { speaker: 'ren_uni', jp: '市民の態度が、社会の質を決めますね。', en: 'Citizens’ attitudes decide a society’s quality.', style: 'student articulating civic responsibility' },
    { speaker: 'asuka_teacher', jp: '長官や大臣も、市民の目で選ばれる時代です。', en: 'Even directors and ministers are now chosen under citizens’ eyes.', style: 'teacher closing on accountability' },
  ]),

  // ===== CLUSTER C: tech & community software =====
  C('conv_03231', 'Building an online community platform', 'Design a forum app; teach ソフトウェア/掲示板/コミュニケーション/方式/微妙/標準', 'office_quiet_low',
    ['ソフトウェア','掲示板','コミュニケーション','方式','微妙','標準'], ['ren_uni', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '新しいソフトウェアの開発、進んでる？', en: 'Is the new software development moving along?', style: 'checking-in tech lead keeping things on track' },
    { speaker: 'riku_teen', jp: 'うん、掲示板の機能を作ってるところ。', en: 'Yeah, I’m building the message-board feature.', style: 'focused junior dev reporting progress' },
    { speaker: 'ren_uni', jp: 'ユーザー同士のコミュニケーションが鍵だね。', en: 'Communication between users is the key.', style: 'product-minded lead naming the priority' },
    { speaker: 'riku_teen', jp: '投稿の表示方式、どっちがいいか微妙でさ。', en: 'The post-display method, it’s hard to call.', style: 'uncertain dev mulling a design tradeoff' },
    { speaker: 'ren_uni', jp: '業界の標準に合わせるのが無難だよ。', en: 'Matching the industry standard is safest.', style: 'pragmatic lead advising the safe path' },
    { speaker: 'riku_teen', jp: '標準仕様だと、後から拡張しやすいしね。', en: 'A standard spec is easier to extend later.', style: 'agreeing dev seeing the long-term benefit' },
    { speaker: 'ren_uni', jp: '掲示板って、運営のコミュニケーションも大事。', en: 'For a board, moderator communication matters too.', style: 'experienced lead flagging an overlooked angle' },
  ]),
  C('conv_03232', 'Pitching the software for internal company use', 'Pitch to a manager; teach ソフトウェア/コミュニケーション/掲示板/方式/標準/微妙', 'office_quiet_low',
    ['ソフトウェア','コミュニケーション','掲示板','方式','標準','微妙'], ['kenji_office', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'kenji_office', jp: 'このソフトウェア、社内でも使えそう？', en: 'Could this software work internally too?', style: 'evaluating manager probing the fit' },
    { speaker: 'ren_uni', jp: 'はい、コミュニケーションの効率が上がります。', en: 'Yes, it boosts communication efficiency.', style: 'confident presenter selling the benefit' },
    { speaker: 'kenji_office', jp: '掲示板みたいに情報を共有できるんだね。', en: 'So you can share info like a message board.', style: 'manager grasping the concept' },
    { speaker: 'ren_uni', jp: 'ええ、入力方式も直感的にしました。', en: 'Yes, the input method is intuitive too.', style: 'presenter highlighting a design win' },
    { speaker: 'kenji_office', jp: 'セキュリティの標準は満たしてる？', en: 'Does it meet the security standard?', style: 'cautious manager checking compliance' },
    { speaker: 'ren_uni', jp: '標準規格に準拠しています。', en: 'It complies with the standard specs.', style: 'presenter reassuring on the requirement' },
    { speaker: 'kenji_office', jp: '操作感が少し微妙な画面があるね。', en: 'Some screens feel a bit off.', style: 'frank manager flagging a rough edge' },
    { speaker: 'ren_uni', jp: 'そこは改善します。', en: 'We’ll improve that part.', style: 'responsive developer accepting the feedback' },
  ]),
  C('conv_03233', 'The board takes off as users post', 'Review engagement; teach 掲示板/コミュニケーション/方式/標準/ソフトウェア', 'office_quiet_low',
    ['掲示板','コミュニケーション','方式','標準','ソフトウェア'], ['riku_teen', 'ren_uni'], 'Short (5-6)', [
    { speaker: 'riku_teen', jp: '掲示板の書き込み、増えてきたね。', en: 'Posts on the board are increasing.', style: 'pleased dev watching the activity grow' },
    { speaker: 'ren_uni', jp: 'コミュニケーションが活発な証拠だよ。', en: 'It’s proof communication is lively.', style: 'satisfied lead reading the signal' },
    { speaker: 'riku_teen', jp: '通知の方式、メールとアプリどっちにする？', en: 'For notifications, email or app?', style: 'practical dev raising a choice' },
    { speaker: 'ren_uni', jp: '両方を標準で用意しよう。', en: 'Let’s offer both as standard.', style: 'decisive lead settling the question' },
    { speaker: 'riku_teen', jp: 'このソフトウェア、軽くて使いやすい。', en: 'This software is light and easy to use.', style: 'proud dev appreciating the result' },
    { speaker: 'ren_uni', jp: '掲示板を中心に、機能を足していこう。', en: 'Let’s add features around the board.', style: 'forward-looking lead planning ahead' },
  ]),
  C('conv_03234', 'A pre-release review of the platform', 'Polish before launch; teach コミュニケーション/方式/掲示板/標準/ソフトウェア/微妙', 'office_quiet_low',
    ['コミュニケーション','方式','掲示板','標準','ソフトウェア','微妙'], ['ren_uni', 'kenji_office'], 'Short (5-6)', [
    { speaker: 'ren_uni', jp: 'リリース前に、コミュニケーション方式を見直そう。', en: 'Before release, let’s review the communication method.', style: 'diligent lead pushing a final check' },
    { speaker: 'kenji_office', jp: '掲示板の通報機能は標準で入れてある？', en: 'Is the board’s report function in by standard?', style: 'careful manager verifying safeguards' },
    { speaker: 'ren_uni', jp: 'はい、業界標準に沿っています。', en: 'Yes, it follows the industry standard.', style: 'assured developer confirming compliance' },
    { speaker: 'kenji_office', jp: 'このソフトウェア、競合と比べてどう？', en: 'How does this software compare to rivals?', style: 'strategic manager sizing up the market' },
    { speaker: 'ren_uni', jp: '操作は優れていますが、デザインが微妙かも。', en: 'The controls are great, but the design’s iffy.', style: 'honest developer admitting a weakness' },
    { speaker: 'kenji_office', jp: 'そこはユーザーのコミュニケーションを見て調整しよう。', en: 'Let’s tune that by watching user communication.', style: 'data-minded manager proposing a fix' },
  ]),
  C('conv_03235', 'Celebrating the platform’s launch', 'Mark the launch; teach ソフトウェア/掲示板/コミュニケーション/方式/標準/微妙', 'office_quiet_low',
    ['ソフトウェア','掲示板','コミュニケーション','方式','標準','微妙'], ['riku_teen', 'ren_uni'], 'Short (5-6)', [
    { speaker: 'riku_teen', jp: 'ついにソフトウェアが完成したね！', en: 'The software is finally done!', style: 'elated dev celebrating the milestone' },
    { speaker: 'ren_uni', jp: '掲示板も、もう安定して動いてる。', en: 'The board is running stably now too.', style: 'relieved lead confirming reliability' },
    { speaker: 'riku_teen', jp: 'ユーザーのコミュニケーションが盛り上がってる。', en: 'User communication is buzzing.', style: 'thrilled dev watching the community grow' },
    { speaker: 'ren_uni', jp: '表示方式の評判もいいよ。', en: 'The display method is well received.', style: 'pleased lead sharing positive feedback' },
    { speaker: 'riku_teen', jp: '標準的な操作で、誰でも使えるしね。', en: 'With standard controls, anyone can use it.', style: 'proud dev valuing the accessibility' },
    { speaker: 'ren_uni', jp: '細かいところは微妙な点も残ってるけど、上出来。', en: 'Some small bits are still iffy, but well done.', style: 'balanced lead ending on honest praise' },
  ]),

  // ===== CLUSTER D: brand-sale shopping outing =====
  C('conv_03236', 'Friends plan to meet for a brand sale', 'Plan a shopping trip; teach 集合/ブランド/キャンペーン/勝手/スタイル/妙/だり', 'cafe_quiet_chatter',
    ['集合','ブランド','キャンペーン','勝手','スタイル','妙','だり'], ['mei_romantic', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: '今日、何時に集合する？', en: 'What time shall we meet today?', style: 'easygoing friend coordinating plans' },
    { speaker: 'sakura_teen', jp: '駅前に十時でどう？ あのブランドのセール見たい。', en: 'Ten at the station? I want to see that brand’s sale.', style: 'eager friend keen on the shopping' },
    { speaker: 'mei_romantic', jp: 'いいね、今キャンペーン中だもんね。', en: 'Nice, there’s a promotion on right now.', style: 'enthusiastic friend confirming the deal' },
    { speaker: 'sakura_teen', jp: '勝手に決めちゃ悪いけど、先に行ってもいい？', en: 'Bad to decide on my own, but can I go ahead?', style: 'slightly apologetic friend asking politely' },
    { speaker: 'mei_romantic', jp: 'どうぞどうぞ。あのお店、スタイルがいい服多いよね。', en: 'Go ahead. That shop has lots of flattering styles.', style: 'easygoing friend praising the store' },
    { speaker: 'sakura_teen', jp: 'うん、でもたまに妙なデザインもあるよね。', en: 'Yeah, but sometimes there are odd designs.', style: 'candid friend adding a wry caveat' },
    { speaker: 'mei_romantic', jp: '悩んだり相談したりして選ぼう。', en: 'Let’s pick by mulling and consulting.', style: 'easygoing friend suggesting a relaxed approach' },
  ]),
  C('conv_03237', 'Browsing the brand store during the sale', 'Shop the sale; teach ブランド/キャンペーン/スタイル/妙/勝手/集合', 'cafe_quiet_chatter',
    ['ブランド','キャンペーン','スタイル','妙','勝手','集合'], ['aoi_barista', 'sakura_teen', 'mei_romantic'], 'Medium (7-12)', [
    { speaker: 'aoi_barista', jp: 'いらっしゃいませ。今、ブランド全品キャンペーン中です。', en: 'Welcome. All brand items are on promotion now.', style: 'bright shop clerk greeting cheerfully' },
    { speaker: 'sakura_teen', jp: 'わあ、お得！ このコート、スタイルよく見える。', en: 'Wow, a steal! This coat makes the figure look good.', style: 'delighted shopper admiring herself' },
    { speaker: 'mei_romantic', jp: '色が妙に派手かな…でも素敵。', en: 'The color’s oddly bold… but lovely.', style: 'considering friend weighing it aloud' },
    { speaker: 'sakura_teen', jp: '勝手に似合うって決めつけないでよ。', en: 'Don’t just decide it suits me on your own.', style: 'playfully protesting friend teasing back' },
    { speaker: 'aoi_barista', jp: '集合のお時間まで、ごゆっくりどうぞ。', en: 'Take your time until your meet-up.', style: 'gracious clerk inviting them to linger' },
    { speaker: 'mei_romantic', jp: 'ありがとう。じっくり選ぶね。', en: 'Thanks. We’ll choose carefully.', style: 'appreciative friend settling in to browse' },
  ]),
  C('conv_03238', 'Losing track of time while shopping', 'Get absorbed in shopping; teach ブランド/スタイル/キャンペーン/集合/勝手/だり', 'cafe_quiet_chatter',
    ['ブランド','スタイル','キャンペーン','集合','勝手','だり'], ['mei_romantic', 'sakura_teen'], 'Short (5-6)', [
    { speaker: 'mei_romantic', jp: 'このブランド、最近スタイルが洗練されたよね。', en: 'This brand’s style got refined lately.', style: 'observant friend noting the trend' },
    { speaker: 'sakura_teen', jp: 'キャンペーンのおかげで手が届く値段。', en: 'The promotion makes it affordable.', style: 'pleased friend grateful for the price' },
    { speaker: 'mei_romantic', jp: '集合してから、もう二時間も見てる。', en: 'We’ve browsed two hours since meeting.', style: 'amused friend noticing the time' },
    { speaker: 'sakura_teen', jp: '勝手に時間が過ぎちゃう、楽しくて。', en: 'Time just slips away, it’s so fun.', style: 'carried-away friend enjoying herself' },
    { speaker: 'mei_romantic', jp: '試着したり悩んだりして、決められない。', en: 'Trying things on and fretting, I can’t decide.', style: 'indecisive friend laughing at herself' },
  ]),
  C('conv_03239', 'Deciding on a final purchase', 'Make the call; teach 妙/スタイル/ブランド/キャンペーン/勝手/集合', 'cafe_quiet_chatter',
    ['妙','スタイル','ブランド','キャンペーン','勝手','集合'], ['sakura_teen', 'mei_romantic'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '妙にこのバッグが気になるんだよね。', en: 'I’m oddly drawn to this bag.', style: 'fixated friend admitting an impulse' },
    { speaker: 'mei_romantic', jp: 'わかる、スタイルに合うもんね。', en: 'I get it, it suits your look.', style: 'supportive friend validating the choice' },
    { speaker: 'sakura_teen', jp: 'ブランド物だけど、キャンペーンで安い。', en: 'It’s a brand item, but cheap with the promotion.', style: 'rationalizing friend justifying the buy' },
    { speaker: 'mei_romantic', jp: '勝手に背中押しちゃうけど、買いなよ。', en: 'I’ll nudge you on my own — buy it.', style: 'encouraging friend cheerfully pushing' },
    { speaker: 'sakura_teen', jp: 'じゃあ決めた！ 次どこ集合する？', en: 'Decided then! Where do we meet next?', style: 'satisfied friend moving on briskly' },
    { speaker: 'mei_romantic', jp: 'あっちのカフェで。妙な小物屋も近いよ。', en: 'At that café. A quirky trinket shop’s nearby too.', style: 'planning friend suggesting the next stop' },
  ]),
  C('conv_03240', 'Wrapping up a satisfying shopping day', 'Close the outing; teach ブランド/キャンペーン/スタイル/妙/勝手/集合/だり', 'cafe_quiet_chatter',
    ['ブランド','キャンペーン','スタイル','妙','勝手','集合','だり'], ['mei_romantic', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: '今日はいい買い物できたね。', en: 'We shopped well today.', style: 'content friend reflecting happily' },
    { speaker: 'sakura_teen', jp: 'うん、ブランドのセール、最高だった。', en: 'Yeah, the brand sale was the best.', style: 'satisfied friend savoring the win' },
    { speaker: 'mei_romantic', jp: 'キャンペーンは今月末までだって。', en: 'The promotion runs till month’s end.', style: 'informative friend sharing a useful note' },
    { speaker: 'sakura_teen', jp: 'スタイルアップした気分！', en: 'I feel like my style leveled up!', style: 'buoyant friend riding the good mood' },
    { speaker: 'mei_romantic', jp: '妙なテンションで散財しちゃったかも。', en: 'I may have splurged in an odd high.', style: 'sheepish friend half-regretting the spend' },
    { speaker: 'sakura_teen', jp: '勝手に反省しないの、楽しかったでしょ。', en: 'No regretting on your own — it was fun, right?', style: 'reassuring friend brushing it off warmly' },
    { speaker: 'mei_romantic', jp: 'また集合して、選んだり試したりしようね。', en: 'Let’s meet again and pick and try things.', style: 'warm friend planning the next outing' },
  ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_162 wrote', CONVERSATIONS.length, 'files');
