import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_108)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02141',
    context: 'Yuki-office leads a small business team meeting; new staff onboarding.',
    purpose: 'Manager guiding fresh team coordination.',
    ambient: 'office_meeting_low',
    sound_effects: [],
    target_vocab: ['気分', '実行', 'スタッフ', '体制', '比較', '位置', '日程', '気軽'],
    cast: ['yuki_office', 'kenji_office'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: '健司さん、新スタッフ、気分、いいですね。', en: "Kenji — new staff, mood, fine.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'kenji_office', jp: '体制、ちゃんとできてる、見えるな。', en: "System — properly, visible.", style: 'warm Kansai man voice, soft warm approving delivery carefully' },
      { speaker: 'yuki_office', jp: '日程、もう少し、比較しないと。', en: "Schedule — bit more, must compare.", style: 'gentle office woman voice, soft warm thoughtful delivery carefully' },
      { speaker: 'kenji_office', jp: '位置、ちょっと変えて、実行しよか。', en: "Position — slightly change, execute?", style: 'soft Kansai man voice, warm warm strategic delivery carefully' },
      { speaker: 'yuki_office', jp: '気軽に、相談できる体制、目指したい。', en: "Casually — consult system, aim.", style: 'soft committed office woman voice, warm earnest delivery carefully' },
      { speaker: 'kenji_office', jp: 'ええ目標や、頑張ろ。', en: "Fine goal — try.", style: 'warm Kansai man voice, soft warm encouraging delivery carefully' },
      { speaker: 'yuki_office', jp: 'はい、よろしくお願いします。', en: "Yes — thank you.", style: 'humble office woman voice, soft warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_02142',
    context: 'Saito reviews a patient\'s recovery progress with Asuka.',
    purpose: 'Two professionals discussing health outcome.',
    ambient: 'clinic_office_low',
    sound_effects: [],
    target_vocab: ['回復', '日中', '熱い', '軽い', '下がっ', '不安定', '当たっ', '進み'],
    cast: ['saito_doctor', 'asuka_teacher'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: 'あすか、患者の回復、順調。', en: "Asuka — patient recovery, smooth.", style: 'measured doctor voice, soft warm professional delivery carefully' },
      { speaker: 'asuka_teacher', jp: '日中、熱、下がってる?', en: "Day — fever, dropped?", style: 'gentle teacher voice, soft warm engaged delivery carefully' },
      { speaker: 'saito_doctor', jp: 'はい、軽い熱、まだあるけれど。', en: "Yes — light fever, still but.", style: 'soft doctor voice, warm warm honest delivery carefully' },
      { speaker: 'asuka_teacher', jp: '体調、不安定、心配ね。', en: "Condition — unstable, worry.", style: 'soft teacher voice, warm warm caring delivery carefully' },
      { speaker: 'saito_doctor', jp: '治療、ちょうど当たっている、進みは良い。', en: "Treatment — exactly hitting, progress good.", style: 'professional doctor voice, soft warm content delivery carefully' },
      { speaker: 'asuka_teacher', jp: 'ご家族にも、伝えてあげてね。', en: "Family too — tell.", style: 'tender teacher voice, soft warm caring delivery carefully' },
      { speaker: 'saito_doctor', jp: 'うん、明日には、報告できるはず。', en: "Yeah — tomorrow, can report.", style: 'warm doctor voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02143',
    context: 'Naoko teaches a young man ramen shop work; he is a beginner.',
    purpose: 'Aunt-figure training new employee patiently.',
    ambient: 'ramen_shop_busy',
    sound_effects: [],
    target_vocab: ['初心者', '重ね', 'うまい', '練習', '動く', '居る', '呼び', '広場'],
    cast: ['naoko_aunt', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: '蓮、初心者やけど、覚え早いな!', en: "Ren — beginner but, learn fast!", style: 'brassy Kansai aunt voice, bright warm proud delivery carefully' },
      { speaker: 'ren_uni', jp: 'おばさんの教え方、本当にうまい。', en: "Auntie's teaching — truly skilled.", style: 'humble young man voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '練習、重ねたらええで、徐々に。', en: "Practice — pile, gradually.", style: 'warm Kansai aunt voice, soft warm patient delivery carefully' },
      { speaker: 'ren_uni', jp: '動く時、お客さん、呼びますね。', en: "Move time — customer, call.", style: 'soft young man voice, warm warm focused delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'おう、お前みたいな子、居てくれて嬉しい。', en: "Yeah — kid like you, here happy.", style: 'tender Kansai aunt voice, soft warm fond delivery carefully' },
      { speaker: 'ren_uni', jp: '広場のお祭りも、手伝います。', en: "Plaza festival too — help.", style: 'soft committed young man voice, warm warm earnest delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、頼りになるなぁ!', en: "Heh — reliable!", style: 'warm Kansai aunt voice, soft warm proud delivery carefully' },
    ],
  },
  {
    id: 'conv_02144',
    context: 'Daichi commutes to work; tells Mei about a long crowded train ride.',
    purpose: 'Married couple discussing daily commute.',
    ambient: 'kitchen_evening_warm',
    sound_effects: [],
    target_vocab: ['通勤', '帯', '置く', '流れる', '家具', '役立つ', '黒い', '光景'],
    cast: ['daichi_kansai', 'mei_romantic'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: 'メイ、通勤、ずいぶん混んでた。', en: "Mei — commute, quite crowded.", style: 'tired Kansai husband voice, soft warm honest delivery carefully' },
      { speaker: 'mei_romantic', jp: '混雑の時間帯、辛いね。', en: "Crowded time zone — hard.", style: 'gentle young wife voice, soft warm empathetic delivery carefully' },
      { speaker: 'daichi_kansai', jp: '黒いビル街、光景、ずっと続く。', en: "Black building street — view, keeps.", style: 'soft Kansai husband voice, warm warm observant delivery carefully' },
      { speaker: 'mei_romantic', jp: '家、新しい家具、置く場所考えてる。', en: "Home — new furniture, place thinking.", style: 'soft young woman voice, warm warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前のセンス、ようけ役立つ。', en: "Your sense — much useful.", style: 'warm Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: '時間、流れるの早いね、最近。', en: "Time — flowing fast, lately.", style: 'tender young wife voice, soft warm philosophical delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ほんま、お互い、健康にな。', en: "Truly — both, healthy.", style: 'tender Kansai husband voice, soft warm caring delivery carefully' },
    ],
  },
  {
    id: 'conv_02145',
    context: 'Sho-young watches a school play; Asuka explains acting.',
    purpose: 'Teacher explaining theatrical art to child.',
    ambient: 'school_auditorium_low',
    sound_effects: [],
    target_vocab: ['演技', '俳優', '舞台', '男の子', '熱い', '尋ね', '迎える', '稽古'],
    cast: ['asuka_teacher', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '先生、男の子の演技、すごい!', en: "Teacher — boy's acting, amazing!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'asuka_teacher', jp: '熱い気持ち、よく演じてる。', en: "Passionate feeling — well acts.", style: 'warm teacher voice, soft warm appreciative delivery carefully' },
      { speaker: 'sho_child', jp: '俳優って、どうしてあんなにできるの?', en: "Actor — how, that way can?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'asuka_teacher', jp: '稽古を、何回も、重ねるのよ。', en: "Practice — many times, pile.", style: 'gentle teacher voice, soft warm informative delivery carefully' },
      { speaker: 'sho_child', jp: '舞台、ぼくも、立ちたい!', en: "Stage — I, want stand!", style: 'eager child boy voice, bright warm dreamy delivery carefully' },
      { speaker: 'asuka_teacher', jp: '尋ねたら、先生紹介できるよ。', en: "Ask — teacher introduce.", style: 'tender teacher voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '今度、迎えに来てね!', en: "Next — come fetch!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02146',
    context: 'Hina-young helps Yumiko sort old family photos by year.',
    purpose: 'Teen and grandmother working through memories.',
    ambient: 'tatami_lamp_quiet',
    sound_effects: [],
    target_vocab: ['ふたり', '日中', '黒い', '熱い', '匂い', '清', '背', '迎える'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'ひな、おじいちゃん、ふたりで写ってる。', en: "Hina — grandpa, two photographed.", style: 'tender older mother voice, soft warm reminiscent delivery carefully' },
      { speaker: 'hina_child', jp: 'まあ、おじいちゃん、背、高いね!', en: "Oh — grandpa, back, tall!", style: 'awed teen girl voice, bright warm fond delivery carefully' },
      { speaker: 'yumiko_mom', jp: '日中、熱い夏、撮ったの。', en: "Daytime — hot summer, took.", style: 'soft older mother voice, warm warm reminiscent delivery carefully' },
      { speaker: 'hina_child', jp: '黒い髪、清々しい感じ。', en: "Black hair — refreshing feel.", style: 'gentle teen girl voice, soft warm appreciative delivery carefully' },
      { speaker: 'yumiko_mom', jp: '匂い、覚えてる、夏の匂い。', en: "Smell — remember, summer smell.", style: 'tender older mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'hina_child', jp: '昔を、迎えるみたいだね。', en: "Past — welcoming-like.", style: 'soft teen girl voice, warm warm reverent delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ほんと、宝物の時間ね。', en: "Truly — treasure time.", style: 'tender older mother voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02147',
    context: 'Sakura interviews a famous local actor.',
    purpose: 'Writer in professional artist interview.',
    ambient: 'studio_quiet_warm',
    sound_effects: [],
    target_vocab: ['俳優', '演技', '稽古', '創作', '本格', '光景', '記入', '共感'],
    cast: ['sakura_teen', 'hiroshi_boss'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '俳優として、どんな稽古を?', en: "Actor as — what training?", style: 'gentle adult writer voice, soft warm respectful inquiry delivered carefully' },
      { speaker: 'hiroshi_boss', jp: '毎朝、本格的に、稽古しています。', en: "Every morning — authentically, training.", style: 'measured boss voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '演技、共感、どうやって?', en: "Acting — empathy, how?", style: 'soft adult writer voice, warm warm probing delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '光景、想像する、ようけ。', en: "Scene — imagine, much.", style: 'soft boss voice, warm warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: '記入する、メモ、いいですか?', en: "Record — note, okay?", style: 'composed adult writer voice, soft warm polite delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'もちろん、創作の参考に。', en: "Of course — creation reference.", style: 'warm boss voice, soft warm helpful delivery carefully' },
      { speaker: 'sakura_teen', jp: '貴重なお話、ありがとうございます。', en: "Precious words — thanks.", style: 'humble adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02148',
    context: 'Aoi visits a small flower festival with Kenji; sensory description.',
    purpose: 'Couple sharing aesthetic outing.',
    ambient: 'festival_outdoor_breeze',
    sound_effects: [],
    target_vocab: ['踊り', '匂い', '皮', '草', '池', '池', '広がり', '広場'],
    cast: ['aoi_barista', 'kenji_office'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、踊り、見える!', en: "Ken-chan — dance, visible!", style: 'bright adult woman voice, soft warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: '花の匂い、ええなぁ、広がりやな。', en: "Flower smell — lovely, spreading.", style: 'warm Kansai husband voice, soft warm appreciative delivery carefully' },
      { speaker: 'aoi_barista', jp: '池の方、草、緑が深い。', en: "Pond side — grass, green deep.", style: 'tender adult woman voice, soft warm awed delivery carefully' },
      { speaker: 'kenji_office', jp: '皮の感じ、しっとり、いいわ。', en: "Skin feel — moist, fine.", style: 'soft Kansai man voice, warm warm sensory delivery carefully' },
      { speaker: 'aoi_barista', jp: '広場、皆さん、楽しんでる!', en: "Plaza — all, enjoying!", style: 'cheerful adult woman voice, soft warm observant delivery carefully' },
      { speaker: 'kenji_office', jp: 'こうやって、過ごせる時間、ええなぁ。', en: "Like this — spend time, fine.", style: 'tender Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、宝物の時間、本当に。', en: "Yeah — treasure time, truly.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02149',
    context: 'Tatsuya-country and Hiroshi-elder discuss Buddhist tradition.',
    purpose: 'Two elders sharing spiritual reflection.',
    ambient: 'tatami_temple_low',
    sound_effects: [],
    target_vocab: ['仏教', '文献', '稽古', '信じる', '許し', '愛情', '共感', '清'],
    cast: ['tatsuya_country', 'hiroshi_elder'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '仏教の文献、ようけ読んだな、昔。', en: "Buddhist documents — much read, past.", style: 'slow Tohoku farmer voice, warm warm reflective delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、信じる、深いもんや。', en: "Yeah — believe, deep thing.", style: 'gentle elder Kansai voice, soft warm philosophical delivery carefully' },
      { speaker: 'tatsuya_country', jp: '人を許し、愛情持つ、難しい。', en: "Person forgive, love hold — hard.", style: 'soft Tohoku voice, warm warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '共感、心、清らかになる。', en: "Empathy — heart, becomes clean.", style: 'warm elder Kansai voice, soft warm reverent delivery carefully' },
      { speaker: 'tatsuya_country', jp: '稽古みたいに、毎日、向き合うもんや。', en: "Practice-like — daily, face.", style: 'firm Tohoku farmer voice, soft warm wise delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お互い、長生きで、ようけ学ぼう。', en: "Both — long life, much learn.", style: 'tender elder Kansai voice, soft warm enduring delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おおきに、心強いわ。', en: "Thanks — encouraging.", style: 'soft Tohoku voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02150',
    context: 'Ren visits a publisher\'s editing office; meets with the editor.',
    purpose: 'Young writer in professional editorial visit.',
    ambient: 'editorial_office_low',
    sound_effects: [],
    target_vocab: ['執筆', '改良', '毎月', '進み', '比較', '位置', '共感', '創作'],
    cast: ['ren_uni', 'hiroshi_boss'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '社長、執筆の進み、ご報告します。', en: "Boss — writing progress, report.", style: 'composed young man voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'うん、毎月、見直してるんやな。', en: "Yeah — monthly, reviewing.", style: 'measured boss voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '改良点、いくつも、見つかりました。', en: "Improvement points — several, found.", style: 'soft young man voice, warm warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '前作と比較、位置づけ、はっきり。', en: "Previous compare — placement, clear.", style: 'professional boss voice, soft warm strategic delivery carefully' },
      { speaker: 'ren_uni', jp: '共感の場面、創作で、強化したい。', en: "Empathy scene — creation, strengthen.", style: 'committed young man voice, soft warm earnest delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'お前の力、信じてる。', en: "Your power — believe.", style: 'tender boss voice, soft warm trusting delivery carefully' },
      { speaker: 'ren_uni', jp: 'ありがとうございます、励みになります。', en: "Thanks — encouragement.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02151',
    context: 'Sho-young learns about traditional sushi from Hiroshi-elder.',
    purpose: 'Grandfather teaching child food tradition.',
    ambient: 'sushi_counter_low',
    sound_effects: [],
    target_vocab: ['寿司', '本屋', '図書', '本格', 'うまい', '初心者', '熱い', '冒険'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hiroshi_elder', jp: '翔、本格の寿司、食べてみるか。', en: "Sho — authentic sushi, try?", style: 'slow elder Kansai voice, warm warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、初心者やけど、冒険する!', en: "Yeah — beginner but, adventure!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'うまい、本格的な味やで。', en: "Tasty — authentic flavor.", style: 'tender elder Kansai voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '熱いお茶も、いただこう。', en: "Hot tea too — receive.", style: 'eager child boy voice, bright warm engaged delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '昔、本屋で寿司の図書、読んだ。', en: "Past — bookstore sushi book, read.", style: 'soft elder Kansai voice, warm warm reminiscent delivery carefully' },
      { speaker: 'sho_child', jp: '今度、読みたい、その本!', en: "Next — want read, that book!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、貸したるで。', en: "Yeah — lend.", style: 'warm elder Kansai voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02152',
    context: 'Naoko hosts a birthday party at the shop; many small touches.',
    purpose: 'Aunt warmly orchestrating celebration.',
    ambient: 'ramen_shop_party_warm',
    sound_effects: [],
    target_vocab: ['ベル', '稽古', '広がり', '止まっ', '関数', '記入', '好評', '拝見'],
    cast: ['naoko_aunt', 'sakura_teen'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'さくらちゃん、ベル、ピーン!', en: "Sakura — bell, ding!", style: 'animated Kansai aunt voice, bright loud cheerful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お祝い、楽しい雰囲気ね。', en: "Celebration — fun mood.", style: 'soft adult writer voice, warm warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: '稽古、ようけしてた、料理もな。', en: "Practice — much done, food too.", style: 'warm Kansai aunt voice, soft warm proud delivery carefully' },
      { speaker: 'sakura_teen', jp: 'お料理の広がり、好評ですね。', en: "Food spread — well-received.", style: 'tender adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'naoko_aunt', jp: '止まったら、こっち、よろしくな!', en: "Stopped — here, please!", style: 'cheerful Kansai aunt voice, bright warm hosting delivery carefully' },
      { speaker: 'sakura_teen', jp: '拝見させていただきます、本当に。', en: "See — truly.", style: 'soft adult writer voice, warm warm reverent delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'こんなふうに、関わってくれて感謝。', en: "Like this — related, gratitude.", style: 'tender Kansai aunt voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02153',
    context: 'Mei runs an errand at the bank; small administrative chat.',
    purpose: 'Adult woman handling bank business briefly.',
    ambient: 'bank_lobby_low',
    sound_effects: [],
    target_vocab: ['銀行', '記入', '住所', '渡し', '関わる', '進み', 'スタッフ', '気軽'],
    cast: ['mei_romantic', 'takeda_officer'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '銀行員さん、書類、記入しましたか?', en: "Banker — documents, filled?", style: 'soft young woman voice, warm warm polite delivery carefully' },
      { speaker: 'takeda_officer', jp: 'はい、住所、こちらでよろしいですか?', en: "Yes — address, this okay?", style: 'composed officer voice, soft warm professional delivery carefully' },
      { speaker: 'mei_romantic', jp: 'はい、合ってます、渡してください。', en: "Yes — matches, hand please.", style: 'gentle young woman voice, soft warm clear delivery carefully' },
      { speaker: 'takeda_officer', jp: '進み、すぐ、ご確認いただけます。', en: "Progress — soon, verify.", style: 'professional officer voice, soft warm efficient delivery carefully' },
      { speaker: 'mei_romantic', jp: 'スタッフの方、皆、丁寧ですね。', en: "Staff folks — all, careful.", style: 'tender young woman voice, soft warm grateful delivery carefully' },
      { speaker: 'takeda_officer', jp: '気軽に、ご質問、どうぞ。', en: "Casually — question, please.", style: 'gentle officer voice, soft warm welcoming delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ありがとうございます。', en: "Thank you.", style: 'humble young woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02154',
    context: 'Hina-young visits a small library; researches with Sakura.',
    purpose: 'Teen learning research with adult mentor.',
    ambient: 'library_quiet_pages',
    sound_effects: [],
    target_vocab: ['本屋', '図書', '文献', '記入', '永遠', '見つける', '答える', '長年'],
    cast: ['hina_child', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'さくらさん、図書、ようけありますね。', en: "Sakura — books, many.", style: 'awed teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '本屋とは違って、長年の文献ある。', en: "Bookstore differ — long-years documents exist.", style: 'gentle adult writer voice, soft warm informative delivery carefully' },
      { speaker: 'hina_child', jp: 'どうやって、答え、見つける?', en: "How — answer, find?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '記入するメモ、必ず持ってね。', en: "Recording note — surely hold.", style: 'composed adult writer voice, soft warm professional delivery carefully' },
      { speaker: 'hina_child', jp: '永遠に、こんな場所、残ったらいい。', en: "Eternally — place like this, remain good.", style: 'tender teen girl voice, soft warm reverent delivery carefully' },
      { speaker: 'sakura_teen', jp: '皆で、守っていきたいね。', en: "All — want protect.", style: 'soft adult writer voice, warm warm committed delivery carefully' },
      { speaker: 'hina_child', jp: 'はい、答え、ちゃんと見つけます!', en: "Yes — answer, properly find!", style: 'soft determined teen girl voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02155',
    context: 'Kenji and Aoi prepare baby supplies; tender domestic scene.',
    purpose: 'Couple in practical parenting prep.',
    ambient: 'nursery_quiet_warm',
    sound_effects: [],
    target_vocab: ['出産', '愛情', '居る', '熱い', '不安定', '安心', '恵まれ', '気付い'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'けんちゃん、出産前、準備、ばっちり?', en: "Ken-chan — pre-birth, prep, ready?", style: 'soft adult woman voice, warm warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: 'うん、お前のおかげで、安心や。', en: "Yeah — thanks to you, relief.", style: 'tender Kansai husband voice, soft warm grateful delivery carefully' },
      { speaker: 'aoi_barista', jp: '気付いたら、赤ちゃん、すぐ居る!', en: "Realize — baby, soon here!", style: 'thrilled adult woman voice, bright warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: '気持ち、不安定やけど、愛情、強い。', en: "Feeling — unstable but, love, strong.", style: 'soft Kansai husband voice, warm warm vulnerable delivery carefully' },
      { speaker: 'aoi_barista', jp: '熱い気持ち、ようけ感じる。', en: "Passionate feeling — much feel.", style: 'tender adult woman voice, soft warm loving delivery carefully' },
      { speaker: 'kenji_office', jp: '恵まれた家庭や、お互いに。', en: "Blessed family — both.", style: 'tender Kansai husband voice, soft warm reverent delivery carefully' },
      { speaker: 'aoi_barista', jp: 'これからも、二人で、ね。', en: "Going forward — two, yeah.", style: 'soft adult woman voice, warm warm united delivery carefully' },
    ],
  },
  {
    id: 'conv_02156',
    context: 'Daichi takes Sho-young to a kid sports event; spectator role.',
    purpose: 'Father and son experiencing sport together.',
    ambient: 'gym_practice_low',
    sound_effects: [],
    target_vocab: ['ふたり', '走っ', '黒い', '冒険', '応援', '当たる', '関わる', '熱心'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '翔、ふたりで、応援しよか!', en: "Sho — two, cheer!", style: 'warm Kansai father voice, soft warm cheerful delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、黒いユニフォーム、応援する!', en: "Yeah — black uniform, cheer!", style: 'thrilled child boy voice, bright warm passionate delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'あの子、ようけ走っとるな、熱心や!', en: "That kid — much running, passionate!", style: 'animated Kansai father voice, bright warm admiring delivery carefully' },
      { speaker: 'sho_child', jp: 'ぼくも、ああいう冒険、してみたい!', en: "I — like that adventure, want try!", style: 'soft eager child boy voice, warm earnest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '関わっていけば、できるで、何でも。', en: "Get involved — can do, anything.", style: 'soft Kansai father voice, warm warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '勝負、いつ当たる?', en: "Match — when meet?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'もうすぐや、楽しみやな!', en: "Soon — looking forward!", style: 'tender Kansai father voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02157',
    context: 'Yuki-office runs through a corporate ranking system with Sakura.',
    purpose: 'Two adults reviewing organizational system.',
    ambient: 'office_lamp_evening',
    sound_effects: [],
    target_vocab: ['順位', '体制', '実行', '改良', '比較', '当て', '位置', '進歩'],
    cast: ['yuki_office', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: 'さくらさん、順位、見直したい。', en: "Sakura — ranking, want review.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '体制、当て直す必要、ありますね。', en: "System — re-fit need, exist.", style: 'gentle adult writer voice, soft warm thoughtful delivery carefully' },
      { speaker: 'yuki_office', jp: '改良を、実行に移しましょう。', en: "Improvement — execute move.", style: 'firm office woman voice, soft warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '前と比較、進歩、はっきり見える。', en: "Before compare — progress, clearly visible.", style: 'soft adult writer voice, warm warm impressed delivery carefully' },
      { speaker: 'yuki_office', jp: '位置、明確になって、嬉しい。', en: "Position — clear, happy.", style: 'tender office woman voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こうやって、共に進められて、感謝。', en: "Like this — together advance, grateful.", style: 'warm adult writer voice, soft warm grateful delivery carefully' },
      { speaker: 'yuki_office', jp: 'こちらこそ、頼もしいわ。', en: "Likewise — reliable.", style: 'gentle office woman voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02158',
    context: 'Ren reads research literature; quotes interesting findings to Saito.',
    purpose: 'Young man sharing reading with mentor.',
    ambient: 'study_lamp_quiet',
    sound_effects: [],
    target_vocab: ['文献', '執筆', '改良', '感心', '関わら', '物事', '同時', '当たる'],
    cast: ['ren_uni', 'saito_doctor'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '先生、新しい文献、読みました。', en: "Doctor — new literature, read.", style: 'soft young man voice, warm warm engaged delivery carefully' },
      { speaker: 'saito_doctor', jp: 'どんな改良、書かれてた?', en: "What improvement — written?", style: 'measured doctor voice, soft warm curious delivery carefully' },
      { speaker: 'ren_uni', jp: '関わらず、進める方向。', en: "Regardless — proceed direction.", style: 'composed young man voice, soft warm professional delivery carefully' },
      { speaker: 'saito_doctor', jp: '物事、同時に、当たる必要あるね。', en: "Things — simultaneously, address need.", style: 'gentle doctor voice, soft warm philosophical delivery carefully' },
      { speaker: 'ren_uni', jp: '感心しました、本当に。', en: "Impressed — truly.", style: 'tender young man voice, soft warm appreciative delivery carefully' },
      { speaker: 'saito_doctor', jp: 'お前の執筆にも、生かせるな。', en: "Your writing too — utilize.", style: 'warm doctor voice, soft warm encouraging delivery carefully' },
      { speaker: 'ren_uni', jp: '必ず、活かします。', en: "Surely — utilize.", style: 'humble young man voice, soft warm committed delivery carefully' },
    ],
  },
  {
    id: 'conv_02159',
    context: 'Hiroshi-elder watches an opening ceremony on TV with Sho-young.',
    purpose: 'Grandfather and grandson sharing TV cultural event.',
    ambient: 'living_room_tv_low',
    sound_effects: [],
    target_vocab: ['花火', '迎える', '飛行', '飛ぶ', '光景', '同時', '永遠', '見つける'],
    cast: ['hiroshi_elder', 'sho_child'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'おじいちゃん、花火、すごい!', en: "Grandpa — fireworks, amazing!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '迎える光景、ようけ綺麗や。', en: "Welcoming view — much pretty.", style: 'gentle elder Kansai voice, soft warm appreciative delivery carefully' },
      { speaker: 'sho_child', jp: '飛行機、空に飛ぶ、見える!', en: "Plane — sky fly, visible!", style: 'awed child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '同時に、たくさん上がるな。', en: "Simultaneously — many rise.", style: 'soft elder Kansai voice, warm warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '永遠に、残るような景色!', en: "Eternally — like remaining scenery!", style: 'tender child boy voice, soft warm reverent delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前、いい言葉、見つけたな。', en: "You — fine words, found.", style: 'warm elder Kansai voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '見守ってくれて、ありがとう!', en: "Watching — thanks!", style: 'soft tender child boy voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02160',
    context: 'Whole group celebrates Aoi\'s book club hosting milestone.',
    purpose: 'Multi-voice cheerful book-related celebration.',
    ambient: 'cafe_celebration_warm',
    sound_effects: [],
    target_vocab: ['本屋', '図書', '答える', '会う', '渡し', '皆さん', '上手く', '関わる'],
    cast: ['aoi_barista', 'sakura_teen', 'ren_uni', 'mei_romantic', 'kenji_office'],
    frequency_tier: 4,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: '皆さん、ようこそ、本屋のように、本がいっぱい!', en: "All — welcome, bookstore-like, books full!", style: 'bright adult woman voice, soft warm hosting delivery carefully' },
      { speaker: 'sakura_teen', jp: '蒼さん、本格的、図書室みたい!', en: "Aoi — authentic, library-like!", style: 'tender adult writer voice, soft warm appreciative delivery carefully' },
      { speaker: 'ren_uni', jp: '皆さんと会えて、嬉しい。', en: "All meet — happy.", style: 'humble young man voice, soft warm respectful delivery carefully' },
      { speaker: 'mei_romantic', jp: '本、渡し合うの、楽しい。', en: "Book — exchange, fun.", style: 'gentle young woman voice, soft warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: '蒼の関わる場所、ようけ広がってるな!', en: "Aoi-related place — much spreading!", style: 'warm Kansai husband voice, soft warm proud delivery carefully' },
      { speaker: 'aoi_barista', jp: '皆の応援、心から感謝。', en: "Everyone's cheer — heart gratitude.", style: 'tender adult woman voice, soft warm grateful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こうやって、繋がる時間、宝物。', en: "Like this — connecting time, treasure.", style: 'soft adult writer voice, warm warm fond delivery carefully' },
      { speaker: 'ren_uni', jp: '上手く、皆さんと過ごせて感激。', en: "Well — everyone spend, moved.", style: 'soft young man voice, warm warm emotional delivery carefully' },
      { speaker: 'mei_romantic', jp: 'お互いの想いに、答えあう関係。', en: "Each thought — answer-answer relation.", style: 'tender young mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'kenji_office', jp: 'こんな夜、また、開きたいな!', en: "Night like this — again, want open!", style: 'warm Kansai man voice, soft warm cheerful delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、定期的に、続けようね。', en: "Yeah — regularly, continue.", style: 'tender adult woman voice, soft warm committed delivery carefully' },
      { speaker: 'sakura_teen', jp: '次回も、楽しみ。', en: "Next — looking forward.", style: 'gentle adult writer voice, soft warm anticipating delivery carefully' },
      { speaker: 'ren_uni', jp: '心、温まる時間でした。', en: "Heart — warming time.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_108 wrote', CONVERSATIONS.length, 'files');
