import fs from 'node:fs'; import path from 'node:path'; import url from 'node:url';
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_172)', generated_at: NOW, source_plan_row: '' });
const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 3, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // ===== CLUSTER A: national museum annual program (Chiba) =====
  C('conv_03421', 'Drafting an annual program for a national museum', 'Plan the program; teach 国立/千葉/２月/８月/１０月/１２月/男女/３つ', 'office_quiet_low',
    ['国立','千葉','２月','８月','１０月','１２月','男女','３つ'], ['yuki_office', 'kenji_office'], 'Medium (7-12)', [
    { speaker: 'yuki_office', jp: '国立美術館で、年間プログラムを組みました。', en: 'I drew up the annual program for the national museum.', style: 'organized planner presenting the lineup' },
    { speaker: 'kenji_office', jp: '千葉の本館で開催ですよね。', en: 'Held at the Chiba main building, right?', style: 'manager confirming the venue' },
    { speaker: 'yuki_office', jp: 'ええ、２月は新春展、８月は夏の企画展です。', en: 'Yes — a New Year show in February, summer feature in August.', style: 'planner detailing the seasons' },
    { speaker: 'kenji_office', jp: '１０月と１２月にも特別展がありますね。', en: 'There are special shows in October and December too.', style: 'manager noting the full year' },
    { speaker: 'yuki_office', jp: '男女問わず、幅広い世代に楽しんでもらえます。', en: 'Both men and women, all generations can enjoy it.', style: 'planner stressing accessibility' },
    { speaker: 'kenji_office', jp: 'テーマは３つの柱で構成されてるんですよね。', en: 'The theme rests on three pillars, right?', style: 'manager checking the structure' },
    { speaker: 'yuki_office', jp: 'ファミリー層も意識して、解説も丁寧に。', en: 'Mindful of families too, with careful explanations.', style: 'thoughtful planner adding nuance' },
    { speaker: 'kenji_office', jp: '３つのテーマが、それぞれ際立つように。', en: 'So the three themes each stand out.', style: 'manager affirming the design' },
  ]),
  C('conv_03422', 'Promoting the program to a visitor', 'Promote the program; teach 国立/千葉/２月/８月/１０月/１２月/男女/３つ', 'office_quiet_low',
    ['国立','千葉','２月','８月','１０月','１２月','男女','３つ'], ['aoi_barista', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'aoi_barista', jp: '国立美術館の年間予定、知りたいです。', en: 'I want to know the national museum’s yearly schedule.', style: 'curious visitor asking warmly' },
    { speaker: 'yuki_office', jp: '千葉の本館で、四つの大きな展覧会があります。', en: 'At the Chiba main building, there are four major shows.', style: 'staffer explaining clearly' },
    { speaker: 'aoi_barista', jp: '２月の展示は何ですか？', en: 'What’s the February show?', style: 'visitor probing details' },
    { speaker: 'yuki_office', jp: '新春展です。８月の夏休み企画も人気ですよ。', en: 'A New Year show. The August summer plan is popular too.', style: 'staffer naming the highlights' },
    { speaker: 'aoi_barista', jp: '１０月、１２月にも何かありますか？', en: 'Are there things in October and December too?', style: 'visitor following up' },
    { speaker: 'yuki_office', jp: '秋と冬の特別展ですね。男女問わず楽しめます。', en: 'Autumn and winter special exhibitions. All genders can enjoy them.', style: 'staffer welcoming all' },
    { speaker: 'aoi_barista', jp: '３つのジャンルで楽しめるのは魅力的。', en: 'Enjoying three genres is appealing.', style: 'pleased visitor responding' },
  ]),
  C('conv_03423', 'A visitor recounts their trip to the museum', 'Recount a visit; teach 国立/千葉/２月/８月/１０月/１２月/男女/３つ', 'cafe_quiet_chatter',
    ['国立','千葉','２月','８月','１０月','１２月','男女','３つ'], ['aoi_barista', 'kenji_office'], 'Medium (7-12)', [
    { speaker: 'aoi_barista', jp: '国立美術館、行ってきました。', en: 'I went to the national museum.', style: 'happy visitor reporting back' },
    { speaker: 'kenji_office', jp: '千葉の館ですね。どうでしたか？', en: 'The Chiba branch, yes? How was it?', style: 'curious manager asking' },
    { speaker: 'aoi_barista', jp: '２月の新春展、書道が見事でした。', en: 'February’s New Year show — the calligraphy was superb.', style: 'visitor savoring the memory' },
    { speaker: 'kenji_office', jp: '８月の現代美術展も話題でしたよ。', en: 'August’s contemporary show was talked about too.', style: 'manager adding context' },
    { speaker: 'aoi_barista', jp: '１０月の特別展も気になります。', en: 'I’m curious about October’s special show too.', style: 'visitor planning ahead' },
    { speaker: 'kenji_office', jp: '１２月は子ども向けプログラムもあるんです。', en: 'In December there’s a kids’ program too.', style: 'manager highlighting it' },
    { speaker: 'aoi_barista', jp: '男女・年齢を問わず楽しめる工夫がいいですね。', en: 'It’s great that men and women of any age can enjoy it.', style: 'visitor appreciating the care' },
    { speaker: 'kenji_office', jp: '３つのテーマ展示、見比べるのが面白いんです。', en: 'Comparing the three themed displays is the fun part.', style: 'manager explaining the appeal' },
  ]),
  C('conv_03424', 'Planning a school field trip to the museum', 'Plan a school trip; teach 国立/千葉/２月/８月/１０月/１２月/男女/３つ', 'office_quiet_low',
    ['国立','千葉','２月','８月','１０月','１２月','男女','３つ'], ['yuki_office', 'kenji_office'], 'Medium (7-12)', [
    { speaker: 'yuki_office', jp: '学校の社会見学先に、国立美術館はどうでしょう。', en: 'For the school field trip, how about the national museum?', style: 'planner proposing politely' },
    { speaker: 'kenji_office', jp: '千葉の本館、設備も整っていますね。', en: 'The Chiba main building is well equipped too.', style: 'manager endorsing' },
    { speaker: 'yuki_office', jp: '２月か８月、どちらの展示が学習向きですか？', en: 'February or August — which show suits learning?', style: 'planner weighing options' },
    { speaker: 'kenji_office', jp: '１０月の歴史展も、教科書と関連します。', en: 'October’s history show ties to the textbook too.', style: 'manager offering an alternative' },
    { speaker: 'yuki_office', jp: '１２月は混むので、避けたいですね。', en: 'December gets crowded, so I’d avoid it.', style: 'cautious planner ruling out' },
    { speaker: 'kenji_office', jp: '男女別の班分けで、効率よく回れます。', en: 'Splitting by gender keeps the tour efficient.', style: 'manager suggesting logistics' },
    { speaker: 'yuki_office', jp: '３つの展示室を、半日で巡れますよ。', en: 'You can cover three rooms in half a day.', style: 'planner confirming feasibility' },
  ]),
  C('conv_03425', 'Year-end recap of the museum’s program', 'Recap the year; teach 国立/千葉/２月/１２月/８月/１０月/男女/３つ', 'office_quiet_low',
    ['国立','千葉','２月','１２月','８月','１０月','男女','３つ'], ['yuki_office', 'aoi_barista'], 'Medium (7-12)', [
    { speaker: 'yuki_office', jp: '国立美術館の年間プログラム、終わりました。', en: 'The national museum’s yearly program wrapped up.', style: 'satisfied planner reflecting' },
    { speaker: 'aoi_barista', jp: '千葉まで何度も足を運びました。', en: 'I went to Chiba many times.', style: 'devoted visitor sharing' },
    { speaker: 'yuki_office', jp: '２月から１２月まで、無事に開催できました。', en: 'From February through December, we held it without incident.', style: 'planner relieved and proud' },
    { speaker: 'aoi_barista', jp: '８月の夏祭りコラボも素敵でした。', en: 'August’s summer-festival collab was lovely too.', style: 'visitor recalling fondly' },
    { speaker: 'yuki_office', jp: '１０月の市民参加型企画も大盛況でした。', en: 'October’s citizen-participation event was a big hit.', style: 'planner crediting success' },
    { speaker: 'aoi_barista', jp: '男女・世代を超えて集まる場でしたね。', en: 'It was a place where genders and generations met.', style: 'visitor appreciating' },
    { speaker: 'yuki_office', jp: '３つのテーマで、来年も継続します。', en: 'We’ll continue with the three themes next year too.', style: 'planner committing forward' },
  ]),

  // ===== CLUSTER B: power-plant incident news =====
  C('conv_03426', 'A breaking-news segment on a power-plant explosion', 'Report a disaster; teach 発電/爆発/電力/損害/デモ/受信/知事/表明', 'living_room_quiet',
    ['発電','爆発','電力','損害','デモ','受信','知事','表明'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '速報です。発電所で爆発がありました。', en: 'Breaking — there was an explosion at a power plant.', style: 'grave teacher delivering urgent news' },
    { speaker: 'ren_uni', jp: '電力供給に影響は出てるんですか？', en: 'Is the power supply affected?', style: 'concerned student asking practically' },
    { speaker: 'sakura_teen', jp: '周辺で大きな損害が出ているそうです。', en: 'Major damage is reported in the surroundings.', style: 'somber teen relaying info' },
    { speaker: 'asuka_teacher', jp: '住民は抗議デモを準備しているようです。', en: 'Residents seem to be preparing protests.', style: 'teacher noting public response' },
    { speaker: 'ren_uni', jp: '速報を受信して、すぐに動かないと。', en: 'We have to receive updates and move quickly.', style: 'student urging action' },
    { speaker: 'sakura_teen', jp: '知事はもう声明を表明しました。', en: 'The governor has already issued a statement.', style: 'teen noting the official response' },
    { speaker: 'asuka_teacher', jp: '政府も対応を急ぐべきです。', en: 'The government should hurry to respond too.', style: 'teacher calling for action' },
  ]),
  C('conv_03427', 'Following the political response', 'Track the response; teach 知事/表明/発電/爆発/電力/損害/デモ/受信', 'living_room_quiet',
    ['知事','表明','発電','爆発','電力','損害','デモ','受信'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '知事が現地視察に向かったそうです。', en: 'The governor reportedly headed to inspect the site.', style: 'informed student reporting' },
    { speaker: 'asuka_teacher', jp: '立場を明確に表明していましたね。', en: 'Their stance was clearly stated.', style: 'teacher noting clarity' },
    { speaker: 'ren_uni', jp: '発電所の爆発の規模、相当大きいです。', en: 'The plant explosion’s scale is considerable.', style: 'student conveying magnitude' },
    { speaker: 'asuka_teacher', jp: '電力会社は損害賠償の準備を始めました。', en: 'The power company began preparing compensation.', style: 'teacher updating' },
    { speaker: 'ren_uni', jp: '市民の抗議デモも続いています。', en: 'Citizen protests continue too.', style: 'student noting ongoing reaction' },
    { speaker: 'asuka_teacher', jp: '公式アカウントで情報を受信できますよ。', en: 'You can receive info from the official account.', style: 'teacher suggesting a source' },
    { speaker: 'ren_uni', jp: '信頼回復には、時間がかかりそうです。', en: 'Rebuilding trust will likely take time.', style: 'student offering a sober view' },
  ]),
  C('conv_03428', 'A student asks the teacher about the cause', 'Explain the cause; teach 発電/爆発/電力/損害/知事/表明/デモ/受信', 'lecture_hall_quiet',
    ['発電','爆発','電力','損害','知事','表明','デモ','受信'], ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '発電所の爆発、原因は何だったんですか？', en: 'The power-plant explosion — what was the cause?', style: 'curious teen asking earnestly' },
    { speaker: 'asuka_teacher', jp: '老朽化と整備不足です。電力会社が認めました。', en: 'Aging and inadequate maintenance. The utility admitted it.', style: 'teacher explaining clearly' },
    { speaker: 'sakura_teen', jp: '周辺住民への損害は補償されるんですか？', en: 'Will residents’ damages be compensated?', style: 'concerned teen pressing' },
    { speaker: 'asuka_teacher', jp: 'ええ、知事が責任を表明しました。', en: 'Yes, the governor announced responsibility.', style: 'teacher confirming' },
    { speaker: 'sakura_teen', jp: 'でも、抗議デモは収まらないですね。', en: 'But the protests haven’t calmed.', style: 'teen observing tension' },
    { speaker: 'asuka_teacher', jp: '続報を受信するため、注視しています。', en: 'I keep receiving updates and watching closely.', style: 'teacher staying engaged' },
    { speaker: 'sakura_teen', jp: '安全対策を、徹底してほしいですね。', en: 'I want safety measures done thoroughly.', style: 'earnest teen wishing' },
  ]),
  C('conv_03429', 'Days later, following up on the recovery', 'Track recovery; teach 発電/爆発/電力/損害/デモ/受信/知事/表明', 'living_room_quiet',
    ['発電','爆発','電力','損害','デモ','受信','知事','表明'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: 'あの事故、その後の状況です。', en: 'That accident — the situation since.', style: 'teacher opening the update' },
    { speaker: 'ren_uni', jp: '発電所の再開は、まだ見通しが立ちません。', en: 'No timeline yet for the plant’s restart.', style: 'student delivering the news' },
    { speaker: 'sakura_teen', jp: '爆発の調査は進んでいますか？', en: 'Is the explosion investigation advancing?', style: 'teen probing progress' },
    { speaker: 'asuka_teacher', jp: '電力不足で、節電要請が出ています。', en: 'With a power shortage, conservation is requested.', style: 'teacher conveying the impact' },
    { speaker: 'ren_uni', jp: '損害の総額も、徐々に明らかに。', en: 'The total damages are gradually surfacing too.', style: 'student noting unfolding facts' },
    { speaker: 'sakura_teen', jp: 'デモの参加者は減少傾向だそうです。', en: 'Protest attendance reportedly is trending down.', style: 'teen citing a shift' },
    { speaker: 'asuka_teacher', jp: '公式の続報を、こまめに受信しましょう。', en: 'Let’s receive official updates frequently.', style: 'teacher advising vigilance' },
    { speaker: 'ren_uni', jp: '知事も対策を、再度表明しました。', en: 'The governor announced measures again.', style: 'student adding a development' },
  ]),
  C('conv_03430', 'Reflecting on lessons from the disaster', 'Draw lessons; teach 発電/爆発/電力/損害/デモ/受信/知事/表明', 'living_room_quiet',
    ['発電','爆発','電力','損害','デモ','受信','知事','表明'], ['ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '一連の事故、社会に多くを問いかけたね。', en: 'The whole accident asked society a lot.', style: 'reflective friend pondering' },
    { speaker: 'sakura_teen', jp: '発電のあり方、見直す時期だと思う。', en: 'It’s time to rethink how we generate power.', style: 'thoughtful friend proposing' },
    { speaker: 'ren_uni', jp: '爆発のような事故を、二度と起こしたくない。', en: 'I never want another explosion like that.', style: 'resolved friend' },
    { speaker: 'sakura_teen', jp: '電力に頼り切る生活も、考え直さなきゃ。', en: 'A life relying on power must be rethought.', style: 'friend offering a wider view' },
    { speaker: 'ren_uni', jp: '被害者の損害が、早く補償されるといい。', en: 'I hope victims’ damages are compensated soon.', style: 'compassionate friend hoping' },
    { speaker: 'sakura_teen', jp: '平和的なデモが、社会を動かすんだね。', en: 'Peaceful protest moves society.', style: 'friend recognizing the power of voice' },
    { speaker: 'ren_uni', jp: '速報を受信する習慣も、身についた。', en: 'I’ve gained the habit of receiving alerts.', style: 'friend noting a personal change' },
    { speaker: 'sakura_teen', jp: '知事や国の表明を、これからも見ていきたい。', en: 'I want to keep watching the governor’s and the country’s announcements.', style: 'engaged friend committing' },
  ]),

  // ===== CLUSTER C: office IT / database migration =====
  C('conv_03431', 'Proposing a database upgrade', 'Pitch an upgrade; teach 現行/データベース/自主/下記/確率/カット/個々/活性', 'office_quiet_low',
    ['現行','データベース','自主','下記','確率','カット','個々','活性'], ['kenji_office', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'kenji_office', jp: '現行のデータベース、限界に近いね。', en: 'The current database is near its limit.', style: 'manager confronting the reality' },
    { speaker: 'ren_uni', jp: '自主的に検討した移行案、見てください。', en: 'Please review my self-initiated migration proposal.', style: 'proactive engineer presenting' },
    { speaker: 'kenji_office', jp: '下記の比較表が分かりやすいな。', en: 'The comparison table below is easy to read.', style: 'manager appreciating clarity' },
    { speaker: 'ren_uni', jp: '成功の確率は、九割と試算しました。', en: 'I estimate a 90% success probability.', style: 'engineer offering hard numbers' },
    { speaker: 'kenji_office', jp: 'コストは、どこをカットできる？', en: 'Where can we cut costs?', style: 'manager probing for savings' },
    { speaker: 'ren_uni', jp: '個々のサーバーを統合すれば、節約できます。', en: 'Consolidating individual servers saves money.', style: 'engineer suggesting' },
    { speaker: 'kenji_office', jp: 'チームの活性化にもつながるね。', en: 'It’ll boost team activity too.', style: 'manager seeing the upside' },
  ]),
  C('conv_03432', 'Discussing the migration plan with a colleague', 'Plan the migration; teach データベース/現行/下記/確率/カット/個々/自主/活性', 'office_quiet_low',
    ['データベース','現行','下記','確率','カット','個々','自主','活性'], ['ren_uni', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '新しいデータベースへの移行、進めています。', en: 'I’m advancing the migration to the new database.', style: 'engineer updating progress' },
    { speaker: 'yuki_office', jp: '現行システムとの並行運用は？', en: 'What about running in parallel with the current system?', style: 'assistant checking the strategy' },
    { speaker: 'ren_uni', jp: '下記のスケジュール通りに進めます。', en: 'I’ll proceed per the schedule below.', style: 'organized engineer confirming' },
    { speaker: 'yuki_office', jp: 'ダウンタイムの確率はどれくらい？', en: 'What’s the probability of downtime?', style: 'cautious assistant probing risk' },
    { speaker: 'ren_uni', jp: '不要な処理をカットして、最小化します。', en: 'By cutting unneeded processes, we minimize it.', style: 'engineer explaining the mitigation' },
    { speaker: 'yuki_office', jp: '個々のチームに、周知も徹底してください。', en: 'Please thoroughly inform each team.', style: 'assistant emphasizing coordination' },
    { speaker: 'ren_uni', jp: '各部署が自主的に確認できる手順書を配ります。', en: 'I’ll distribute a self-check manual for each dept.', style: 'engineer offering tools' },
    { speaker: 'yuki_office', jp: '移行後、業務の活性化が期待できますね。', en: 'Post-migration, expect more lively operations.', style: 'optimistic assistant projecting' },
  ]),
  C('conv_03433', 'Kicking off the migration project', 'Launch the project; teach データベース/現行/下記/個々/確率/カット/自主/活性', 'office_quiet_low',
    ['データベース','現行','下記','個々','確率','カット','自主','活性'], ['kenji_office', 'ren_uni', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'kenji_office', jp: '今日からデータベース更新プロジェクトを始める。', en: 'We start the DB update project today.', style: 'commanding manager opening' },
    { speaker: 'ren_uni', jp: '現行の運用は維持しつつ、進めます。', en: 'We’ll proceed while maintaining current ops.', style: 'engineer reassuring' },
    { speaker: 'yuki_office', jp: '下記の役割分担で動きましょう。', en: 'Let’s work per the roles below.', style: 'organized assistant directing' },
    { speaker: 'kenji_office', jp: '個々の責任を、明確にしてくれ。', en: 'Make each person’s responsibility clear.', style: 'manager demanding clarity' },
    { speaker: 'ren_uni', jp: '障害発生の確率も計算しています。', en: 'I’m calculating fault probabilities too.', style: 'engineer noting rigor' },
    { speaker: 'yuki_office', jp: '無駄な工程はカットしますね。', en: 'I’ll cut wasteful steps.', style: 'assistant committing to streamline' },
    { speaker: 'kenji_office', jp: '自主性を持って、取り組んでほしい。', en: 'Take initiative as you work.', style: 'manager calling for ownership' },
    { speaker: 'ren_uni', jp: 'チームの活性化にも、つながると信じています。', en: 'I trust it will also energize the team.', style: 'engineer voicing belief' },
  ]),
  C('conv_03434', 'Mid-project status check', 'Status check; teach データベース/現行/下記/確率/カット/個々/自主/活性', 'office_quiet_low',
    ['データベース','現行','下記','確率','カット','個々','自主','活性'], ['yuki_office', 'kenji_office'], 'Medium (7-12)', [
    { speaker: 'yuki_office', jp: '進捗報告です。データベース移行、順調です。', en: 'Progress report — DB migration is on track.', style: 'assistant reporting cleanly' },
    { speaker: 'kenji_office', jp: '現行との切替は？', en: 'What about the switchover from current?', style: 'manager probing the key step' },
    { speaker: 'yuki_office', jp: '下記の通り、来月実施予定です。', en: 'As below, scheduled for next month.', style: 'assistant pointing to the doc' },
    { speaker: 'kenji_office', jp: '成功確率はどうだ？', en: 'How’s the success probability?', style: 'manager pressing for numbers' },
    { speaker: 'yuki_office', jp: '九十五パーセントの確率と試算しています。', en: 'We estimate a 95% probability.', style: 'confident assistant answering' },
    { speaker: 'kenji_office', jp: '余分な機能は、勇気を持ってカットしよう。', en: 'Boldly cut extra features.', style: 'manager urging discipline' },
    { speaker: 'yuki_office', jp: '個々のメンバーが、自主的に動いています。', en: 'Each member is taking initiative.', style: 'pleased assistant noting culture' },
    { speaker: 'kenji_office', jp: 'チームの活性が、目に見えるね。', en: 'The team’s energy is visible.', style: 'manager praising' },
  ]),
  C('conv_03435', 'Post-launch review', 'Post-launch review; teach データベース/現行/下記/確率/カット/個々/自主/活性', 'office_quiet_low',
    ['データベース','現行','下記','確率','カット','個々','自主','活性'], ['kenji_office', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'kenji_office', jp: '新データベース、無事に稼働してるね。', en: 'The new DB is running smoothly.', style: 'pleased manager reflecting' },
    { speaker: 'ren_uni', jp: '現行通り、業務に支障はありません。', en: 'Operations continue as before, no issues.', style: 'engineer confirming stability' },
    { speaker: 'kenji_office', jp: '下記の報告書、よくまとまってる。', en: 'The report below is well organized.', style: 'manager praising the writeup' },
    { speaker: 'ren_uni', jp: '障害の確率も、ほぼゼロでした。', en: 'Fault probability was nearly zero.', style: 'engineer reporting numbers' },
    { speaker: 'kenji_office', jp: '無駄なコストもカットできた。', en: 'We cut wasteful costs too.', style: 'manager noting savings' },
    { speaker: 'ren_uni', jp: '個々のメンバーの努力のおかげです。', en: 'Thanks to each member’s effort.', style: 'humble engineer sharing credit' },
    { speaker: 'kenji_office', jp: 'みんなの自主性が光ったプロジェクトだったな。', en: 'A project where everyone’s initiative shone.', style: 'manager closing warmly' },
    { speaker: 'ren_uni', jp: '部署全体の活性化にも、貢献できました。', en: 'We contributed to the whole dept’s energy too.', style: 'engineer ending happily' },
  ]),

  // ===== CLUSTER D: manga magazine casual chat =====
  C('conv_03436', 'Talking about the week’s manga magazine', 'Discuss a magazine; teach 週刊/マンガ/たまたま/おもしろい/本書/性質/大いに/あんまり', 'cafe_quiet_chatter',
    ['週刊','マンガ','たまたま','おもしろい','本書','性質','大いに','あんまり'], ['sakura_teen', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '今週の週刊マンガ雑誌、買った？', en: 'Did you buy this week’s weekly manga magazine?', style: 'eager fan opening the chat' },
    { speaker: 'riku_teen', jp: 'たまたま本屋で見つけて、すぐ買ったよ。', en: 'I happened to find it at the bookstore and bought it.', style: 'casual friend sharing his luck' },
    { speaker: 'sakura_teen', jp: '巻頭カラー、おもしろい新連載だったね。', en: 'The opening-color new serial was fun.', style: 'animated fan praising' },
    { speaker: 'riku_teen', jp: 'あの作品、本書のテーマが深いんだ。', en: 'That work — the book’s theme is deep.', style: 'thoughtful friend reflecting' },
    { speaker: 'sakura_teen', jp: '主人公の性質が、複雑で気になる。', en: 'The hero’s nature is complex and intriguing.', style: 'fan analyzing' },
    { speaker: 'riku_teen', jp: '続きは大いに楽しみだよ。', en: 'I’m greatly looking forward to the rest.', style: 'excited friend gushing' },
    { speaker: 'sakura_teen', jp: '私はあんまり恋愛要素は得意じゃないけど、これは別。', en: 'I’m not that into romance, but this one’s different.', style: 'fan admitting an exception' },
  ]),
  C('conv_03437', 'Discussing the lead character’s growth', 'Analyze a character; teach マンガ/週刊/性質/たまたま/あんまり/おもしろい/本書/大いに', 'cafe_quiet_chatter',
    ['マンガ','週刊','性質','たまたま','あんまり','おもしろい','本書','大いに'], ['mei_romantic', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: 'あの少女マンガ、読んでる？', en: 'Are you reading that shoujo manga?', style: 'friend opening lightly' },
    { speaker: 'sakura_teen', jp: '週刊で追ってるよ。', en: 'I’m following it weekly.', style: 'devoted fan confirming' },
    { speaker: 'mei_romantic', jp: '主人公の性質が、最近変わってきたよね。', en: 'The hero’s nature has been changing lately.', style: 'observant friend analyzing' },
    { speaker: 'sakura_teen', jp: 'たまたま昨日、過去の巻を読み返した。', en: 'I happened to reread an old volume yesterday.', style: 'fan recalling a coincidence' },
    { speaker: 'mei_romantic', jp: 'あんまり期待してなかったけど、おもしろい。', en: 'I didn’t expect much, but it’s fun.', style: 'pleasantly surprised friend' },
    { speaker: 'sakura_teen', jp: '本書のメッセージは、大いに考えさせられる。', en: 'The book’s message really makes you think.', style: 'fan reflecting deeply' },
    { speaker: 'mei_romantic', jp: '来月の展開、楽しみだね。', en: 'I’m looking forward to next month’s arc.', style: 'fan anticipating warmly' },
  ]),
  C('conv_03438', 'Recommending a series to a friend', 'Recommend a series; teach マンガ/週刊/本書/あんまり/性質/おもしろい/たまたま/大いに', 'cafe_quiet_chatter',
    ['マンガ','週刊','本書','あんまり','性質','おもしろい','たまたま','大いに'], ['riku_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: 'このマンガ、読んでみない？', en: 'Want to try this manga?', style: 'enthusiastic friend offering' },
    { speaker: 'ren_uni', jp: '週刊で連載してるやつ？', en: 'The one serialized weekly?', style: 'curious friend confirming' },
    { speaker: 'riku_teen', jp: 'そう。本書のあらすじを話すよ。', en: 'Yes. I’ll summarize the book’s plot.', style: 'eager friend pitching' },
    { speaker: 'ren_uni', jp: 'あんまり時間ないんだけど、要点を。', en: 'I don’t have much time, but the gist.', style: 'busy friend asking briefly' },
    { speaker: 'riku_teen', jp: '主人公が独特の性質を持ってて、おもしろいんだ。', en: 'The hero has a unique nature — it’s fun.', style: 'fan selling the appeal' },
    { speaker: 'ren_uni', jp: 'たまたま電車で見かけて、気になってた。', en: 'I happened to see it on the train — was curious.', style: 'friend admitting interest' },
    { speaker: 'riku_teen', jp: 'ハマったら、大いに楽しめるよ。', en: 'If you get hooked, you’ll greatly enjoy it.', style: 'fan promising payoff' },
  ]),
  C('conv_03439', 'Analyzing the author', 'Analyze an author; teach マンガ/週刊/本書/性質/たまたま/あんまり/大いに/おもしろい', 'cafe_quiet_chatter',
    ['マンガ','週刊','本書','性質','たまたま','あんまり','大いに','おもしろい'], ['sakura_teen', 'mei_romantic'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: 'あのマンガ家、新作も話題だね。', en: 'That manga artist — the new work’s trending too.', style: 'fan noting buzz' },
    { speaker: 'mei_romantic', jp: '週刊と月刊、両方で連載してるの。', en: 'They’re serialized in both weekly and monthly.', style: 'informed friend explaining' },
    { speaker: 'sakura_teen', jp: '本書の中で、自身の経験を語ってた。', en: 'In the book, the author spoke of their experience.', style: 'fan recalling content' },
    { speaker: 'mei_romantic', jp: '描く女性キャラの性質が、すごく繊細。', en: 'The nature of the female characters is so delicate.', style: 'admiring friend praising craft' },
    { speaker: 'sakura_teen', jp: 'たまたまサイン会に行けたんだ。', en: 'I happened to make it to a signing.', style: 'fan sharing a lucky tale' },
    { speaker: 'mei_romantic', jp: 'いいなあ。あんまり一般には公開されない人なのに。', en: 'Lucky you. They’re not often public.', style: 'envious friend lamenting' },
    { speaker: 'sakura_teen', jp: '大いに感動して、ファンになった。', en: 'I was greatly moved and became a fan.', style: 'fan reliving the feeling' },
    { speaker: 'mei_romantic', jp: 'ストーリーがおもしろいから、長く続くだろうね。', en: 'The story’s fun, so it’ll run long.', style: 'friend predicting longevity' },
  ]),
  C('conv_03440', 'Planning a manga-club essay', 'Plan a club essay; teach マンガ/週刊/本書/性質/たまたま/あんまり/大いに/おもしろい', 'living_room_quiet',
    ['マンガ','週刊','本書','性質','たまたま','あんまり','大いに','おもしろい'], ['sakura_teen', 'riku_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '部誌に、マンガ評論を書いてみない？', en: 'Want to write a manga critique for the club zine?', style: 'inviting friend pitching' },
    { speaker: 'riku_teen', jp: '週刊誌の批評記事みたいに？', en: 'Like a weekly magazine’s review piece?', style: 'curious friend asking' },
    { speaker: 'sakura_teen', jp: 'そう。本書のレビューをまとめる感じで。', en: 'Yeah. Summing up the book in a review.', style: 'friend explaining the format' },
    { speaker: 'riku_teen', jp: '作品の性質を分析するの、楽しそう。', en: 'Analyzing the work’s nature sounds fun.', style: 'enthusiastic friend warming up' },
    { speaker: 'sakura_teen', jp: 'たまたま読んだ作品でも、深く語れるよ。', en: 'You can speak deeply about even a stumbled-on work.', style: 'friend reassuring' },
    { speaker: 'riku_teen', jp: '普段はあんまり書かないけど、挑戦してみる。', en: 'I don’t write much usually, but I’ll try.', style: 'friend stepping out of comfort' },
    { speaker: 'sakura_teen', jp: '大いに刺激し合おう。', en: 'Let’s greatly inspire each other.', style: 'energized friend rallying' },
    { speaker: 'riku_teen', jp: '完成したら、おもしろい部誌になりそう。', en: 'Once done, it’ll be a fun club zine.', style: 'optimistic friend closing' },
  ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_172 wrote', CONVERSATIONS.length, 'files');
