import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_146)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // count-4 cleanup (を通じて 示す 取る 並ん 通じ 乗る 過ぎる 甘い)
  C('conv_02901',
    'Mei and Ren reflect on a book that changed them.',
    'Casual register; vocabulary (を通じて/示す/取る/並ん/通じ) in natural home.',
    'cafe_quiet_chatter',
    ['を通じて', '示す', '取る', '並ん', '通じ'],
    ['mei_romantic', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの本を通じて、考え方が変わったの。', en: "Through that book, my way of thinking changed.", style: 'soft warm woman voice, gentle reflective delivery throughout' },
      { speaker: 'ren_uni', jp: '本は、新しい道を示してくれるよね。', en: "Books show us new paths.", style: 'warm young man voice, soft warm reflective delivery throughout' },
      { speaker: 'mei_romantic', jp: '棚に並んだ本を、つい手に取るの。', en: "I can't help picking up the books lined up on the shelf.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '読書を通じて、心が通じる気がするね。', en: "Through reading, I feel hearts connect.", style: 'engaged young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '甘いお茶を飲みながら、読むのが好き。', en: "I love reading while sipping sweet tea.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: '時間が過ぎるのを、忘れちゃうよね。', en: "We forget time passing, don't we.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '電車に乗って、本屋まで行こうか。', en: "Shall we ride the train to the bookstore?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '並んだ本を通じて、世界が広がるね。', en: "Through the lined-up books, the world widens.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  // CLUSTER A — daily/casual (給料 迷惑 具合 落とし 身近)
  C('conv_02902',
    'Mei and Aoi chat about an awkward payday.',
    'Casual register; vocabulary (給料/迷惑/具合/落とし/身近) in natural home.',
    'cafe_quiet_chatter',
    ['給料', '迷惑', '具合', '落とし', '身近'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '今日、給料が入ったんだ!', en: "My salary came in today!", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'いいね、おめでとう。具合はどう?', en: "Nice, congrats. How are you feeling?", style: 'soft warm woman voice, gentle caring delivery throughout' },
      { speaker: 'aoi_barista', jp: '実は、財布を落としちゃって。', en: "Actually, I dropped my wallet.", style: 'sheepish barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'えっ、それは迷惑な話だね。', en: "Huh, that's a troublesome thing.", style: 'concerned woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '落とした場所が、身近な公園でね。', en: "I dropped it at a familiar park.", style: 'relieved barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '身近な人が、届けてくれたの?', en: "Did someone close return it?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'うん、迷惑かけたけど、戻ってきたよ。', en: "Yeah, I caused trouble, but it came back.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '良かった!給料、大事に使ってね。', en: "Good! Spend that salary wisely.", style: 'warm woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02903',
    'Saito checks on Kenji feeling unwell after work.',
    'WIDENED SCENARIO: medical chat; vocabulary (給料/迷惑/具合/落とし/身近) in natural home.',
    'clinic_room_quiet',
    ['給料', '迷惑', '具合', '落とし', '身近'],
    ['saito_doctor', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'kenji_office', jp: '先生、最近、具合が良くないんです。', en: "Doctor, lately I'm not feeling well.", style: 'tired office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '身近な疲れが、出ているようですね。', en: "Everyday fatigue seems to be showing.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'kenji_office', jp: '仕事のことが、頭から落とせなくて。', en: "I can't get work off my mind.", style: 'troubled office man voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: '人に頼るのは、迷惑ではありませんよ。', en: "Relying on others isn't a nuisance.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'kenji_office', jp: '給料のために、無理してました。', en: "I was pushing myself for the salary.", style: 'honest office man voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '身近な人に、相談してみて下さい。', en: "Please consult someone close to you.", style: 'warm doctor voice, soft warm caring clarity throughout' },
      { speaker: 'kenji_office', jp: '迷惑かなと、ためらってました。', en: "I hesitated, thinking I'd be a bother.", style: 'reflective office man voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '具合が悪い時は、休むのが一番です。', en: "When you feel unwell, resting is best.", style: 'gentle doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_02904',
    'Yumiko and Sho talk about a lost item.',
    'Casual home register; vocabulary (給料/迷惑/具合/落とし/身近) in natural home.',
    'kitchen_evening_quiet',
    ['給料', '迷惑', '具合', '落とし', '身近'],
    ['yumiko_mom', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'ママ、消しゴムを落としちゃった。', en: "Mom, I dropped my eraser.", style: 'pouty small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'あら、どこで落としたの?', en: "Oh, where did you drop it?", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: '身近な、机の下だと思う。', en: "I think it's nearby, under the desk.", style: 'thoughtful small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '友達に、迷惑かけなかった?', en: "Didn't you trouble your friends?", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'ううん、でもお腹の具合が変なの。', en: "No, but my tummy feels weird.", style: 'uneasy small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '具合が悪いなら、早く休みましょう。', en: "If you feel unwell, let's rest early.", style: 'caring mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'パパの給料日、明日だよね?', en: "Dad's payday is tomorrow, right?", style: 'curious small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'そうよ。身近な幸せを、大事にしましょうね。', en: "Yes. Let's cherish the small joys close to us.", style: 'tender mother voice, soft warm affectionate closing delivery throughout' },
    ]),

  // CLUSTER B — abstract/lecture (意思 転換 初期 試み 勝ち)
  C('conv_02905',
    'Asuka lectures on turning points in history.',
    'WIDENED SCENARIO: history lecture; vocabulary (意思/転換/初期/試み/勝ち) in natural home.',
    'lecture_hall_quiet',
    ['意思', '転換', '初期', '試み', '勝ち'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '歴史には、大きな転換点があります。', en: "History has major turning points.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '転換は、誰かの意思で起きるんですか?', en: "Do turns happen by someone's will?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、強い意思が、転換を生みます。', en: "Yes, strong will produces a turn.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '初期の試みは、失敗も多いですか?', en: "Do early attempts often fail?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '初期の試みは、失敗の連続でした。', en: "Early attempts were a string of failures.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: 'それでも、勝ちを得たんですね。', en: "Even so, they gained victory.", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '諦めない意思が、勝ちにつながりました。', en: "An unyielding will led to victory.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '初期の試みが、転換を支えたんですね。', en: "Early attempts supported the turn.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_02906',
    'Hiroshi-boss and Ren plan a strategic shift.',
    'WIDENED SCENARIO: business strategy; vocabulary (意思/転換/初期/試み/勝ち) in natural home.',
    'office_quiet_low',
    ['意思', '転換', '初期', '試み', '勝ち'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '会社の方針を、転換したいと思う。', en: "I want to shift the company's direction.", style: 'decisive boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '転換には、強い意思が要りますね。', en: "A shift requires strong will.", style: 'engaged young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '初期の段階で、小さく試みよう。', en: "Let's try it small in the early stage.", style: 'measured boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '初期の試みで、反応を見るんですね。', en: "We gauge reactions with early attempts.", style: 'thoughtful young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '競争に勝つには、転換が必要だ。', en: "To win the competition, a shift is needed.", style: 'firm boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '勝ちを目指して、意思を固めます。', en: "Aiming for victory, I'll firm up my resolve.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '初期の試みが、鍵になるな。', en: "The early attempt will be key.", style: 'measured boss voice, soft warm composed clarity throughout' },
      { speaker: 'ren_uni', jp: '転換を、着実に進めます。', en: "I'll steadily advance the shift.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_02907',
    'Ren and Asuka discuss a startup\'s pivot.',
    'WIDENED SCENARIO: research discussion; vocabulary (意思/転換/初期/試み/勝ち) in natural home.',
    'lecture_hall_quiet',
    ['意思', '転換', '初期', '試み', '勝ち'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'あの会社、方向を転換したんですね。', en: "That company pivoted its direction.", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '創業者の強い意思が、あったんでしょう。', en: "The founder must have had strong will.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '初期は、苦しかったみたいです。', en: "The early days seem to have been hard.", style: 'thoughtful young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '初期の試みは、たいてい難しいものです。', en: "Early attempts are usually difficult.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '何度も試みて、勝ちを掴んだんですね。', en: "They tried many times and grasped victory.", style: 'admiring young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '意思の強さが、勝ちを呼びます。', en: "Strength of will calls forth victory.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '転換の決断、見習いたいです。', en: "I want to emulate that decision to pivot.", style: 'resolved young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '初期の試みを、恐れないことですね。', en: "It's about not fearing early attempts.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  // CLUSTER C — society/news (地震 出来事 発信 引き続き 方面)
  C('conv_02908',
    'News: Sakura and Ren report on an earthquake.',
    'WIDENED SCENARIO: disaster news; vocabulary (地震/出来事/発信/引き続き/方面) in natural home.',
    'studio_room_tone',
    ['地震', '出来事', '発信', '引き続き', '方面'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '先ほど、強い地震がありました。', en: "A strong earthquake just occurred.", style: 'crisp adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: 'どの方面で、揺れたんですか?', en: "In which direction did it shake?", style: 'measured young reporter voice, soft warm serious focus throughout' },
      { speaker: 'sakura_teen', jp: '東の方面で、大きく揺れました。', en: "It shook strongly in the eastern area.", style: 'clear adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '情報は、どこから発信されますか?', en: "Where is the information sent from?", style: 'serious young reporter voice, soft warm focus throughout' },
      { speaker: 'sakura_teen', jp: '気象台が、発信を続けています。', en: "The weather agency keeps transmitting.", style: 'professional adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: 'こうした出来事には、備えが要りますね。', en: "Such events require preparation.", style: 'thoughtful young reporter voice, soft warm focus throughout' },
      { speaker: 'sakura_teen', jp: '引き続き、最新の情報を発信します。', en: "We'll continue to transmit the latest info.", style: 'measured adult anchor voice, soft warm serious clarity throughout' },
      { speaker: 'ren_uni', jp: '各方面の状況を、引き続き伝えます。', en: "We'll keep reporting conditions in each area.", style: 'earnest young reporter voice, soft warm calm closing throughout' },
    ]),

  C('conv_02909',
    'Asuka lectures on disaster preparedness.',
    'WIDENED SCENARIO: civics lecture; vocabulary (地震/出来事/発信/引き続き/方面) in natural home.',
    'lecture_hall_quiet',
    ['地震', '出来事', '発信', '引き続き', '方面'],
    ['asuka_teacher', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '地震は、いつ起きるか分かりません。', en: "We never know when an earthquake will strike.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '過去の出来事から、学べますか?', en: "Can we learn from past events?", style: 'curious teen boy voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、出来事の記録が、備えを支えます。', en: "Yes, records of events support preparedness.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '情報は、どう発信されますか?', en: "How is information transmitted?", style: 'engaged teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '各方面に、すぐ発信されます。', en: "It's sent to all areas at once.", style: 'composed teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '研究は、引き続き行われますか?', en: "Will research continue?", style: 'thoughtful teen boy voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '引き続き、各方面で研究が進みます。', en: "Research continues in all fields.", style: 'patient teacher voice, soft warm measured informative clarity throughout' },
      { speaker: 'riku_teen', jp: '地震に備えること、大事ですね。', en: "Preparing for earthquakes is important.", style: 'moved teen boy voice, soft warm realization throughout' },
    ]),

  C('conv_02910',
    'Kenji and Yuki set up a disaster alert app.',
    'WIDENED SCENARIO: tech help; vocabulary (地震/出来事/発信/引き続き/方面) in natural home.',
    'office_quiet_low',
    ['地震', '出来事', '発信', '引き続き', '方面'],
    ['kenji_office', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: 'このアプリ、地震の通知が来るの?', en: "Does this app send earthquake alerts?", style: 'curious office woman voice, soft warm engaged delivery throughout' },
      { speaker: 'kenji_office', jp: 'ええ、すぐに発信されますよ。', en: "Yes, they're transmitted instantly.", style: 'helpful office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: 'どの方面の情報も、来ますか?', en: "Does it bring info for every area?", style: 'attentive office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: '住んでいる方面を、登録できます。', en: "You can register your area.", style: 'clear office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '大きな出来事も、知らせてくれる?', en: "Will it notify me of major events too?", style: 'engaged office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: 'ええ、出来事を引き続き発信します。', en: "Yes, it keeps transmitting events.", style: 'reassuring office man voice, soft warm patient guiding throughout' },
      { speaker: 'yuki_office', jp: '引き続き、更新されるんですね。', en: "It keeps updating, then.", style: 'understanding office woman voice, soft warm delivery throughout' },
      { speaker: 'kenji_office', jp: '地震の時、きっと役立ちますよ。', en: "It'll surely help during an earthquake.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // CLUSTER D — work/office (職業 許可 問い合わせ 加入 申し訳)
  C('conv_02911',
    'Yuki handles a membership inquiry with Hiroshi-boss.',
    'WIDENED SCENARIO: business ops; vocabulary (職業/許可/問い合わせ/加入/申し訳) in natural home.',
    'office_quiet_low',
    ['職業', '許可', '問い合わせ', '加入', '申し訳'],
    ['yuki_office', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '加入の問い合わせが、増えています。', en: "Enrollment inquiries are increasing.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: 'どんな職業の人が、多いのかね?', en: "What occupations are most common?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '様々な職業の方が、加入されます。', en: "People of various occupations enroll.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '加入には、許可が要るのかね?', en: "Does enrollment require permission?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '一部は、本部の許可が必要です。', en: "Some require headquarters' permission.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '問い合わせの返信は、早いかね?', en: "Are inquiry replies prompt?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'yuki_office', jp: '遅れた時は、申し訳なくお詫びします。', en: "When delayed, we apologize sincerely.", style: 'earnest office woman voice, soft warm clarity throughout' },
      { speaker: 'hiroshi_boss', jp: '丁寧な問い合わせ対応を、頼むよ。', en: "I count on courteous inquiry handling.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_02912',
    'Sakura interviews a career counselor.',
    'WIDENED SCENARIO: career interview; vocabulary (職業/許可/問い合わせ/加入/申し訳) in natural home.',
    'office_quiet_low',
    ['職業', '許可', '問い合わせ', '加入', '申し訳'],
    ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '若者の職業選びを、支援していますか?', en: "Do you support youths' career choices?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、職業の相談を受けています。', en: "Yes, I take career consultations.", style: 'composed counselor voice, soft warm gentle clarity throughout' },
      { speaker: 'sakura_teen', jp: '問い合わせは、多いんですか?', en: "Are there many inquiries?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '毎日、たくさんの問い合わせが来ます。', en: "Many inquiries come every day.", style: 'gentle counselor voice, soft warm clarity throughout' },
      { speaker: 'sakura_teen', jp: '団体への加入も、勧めますか?', en: "Do you recommend joining organizations?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '加入には、本人の許可を尊重します。', en: "For enrollment, we respect the person's consent.", style: 'composed counselor voice, soft warm gentle clarity throughout' },
      { speaker: 'sakura_teen', jp: '対応しきれない時も、ありますか?', en: "Are there times you can't keep up?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '申し訳ないですが、お待たせもします。', en: "I'm sorry to say, sometimes people wait.", style: 'gentle counselor voice, soft warm sincere closing clarity throughout' },
    ]),

  C('conv_02913',
    'Kenji and Ren troubleshoot a membership form.',
    'WIDENED SCENARIO: tech help; vocabulary (職業/許可/問い合わせ/加入/申し訳) in natural home.',
    'office_quiet_low',
    ['職業', '許可', '問い合わせ', '加入', '申し訳'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '加入の手続きで、エラーが出ます。', en: "An error shows in the enrollment process.", style: 'troubled young colleague voice, soft warm earnest throughout' },
      { speaker: 'kenji_office', jp: '職業の欄が、空いていませんか?', en: "Is the occupation field empty?", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'あ、職業を入れ忘れていました。', en: "Oh, I forgot to enter the occupation.", style: 'sheepish young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '許可の項目も、確認しましょう。', en: "Let's check the permission field too.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '許可にチェックを入れたら、進みました。', en: "When I checked permission, it proceeded.", style: 'relieved young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '困ったら、問い合わせ窓口へどうぞ。', en: "If stuck, head to the inquiry desk.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '時間を取らせて、申し訳ないです。', en: "I'm sorry for taking your time.", style: 'apologetic young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '無事に加入できて、良かったですね。', en: "Glad the enrollment went through.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // CLUSTER E — home/daily (借り 置か 住む 流し 我が)
  C('conv_02914',
    'Daichi and Mei chat about moving into a new home.',
    'Casual register; vocabulary (借り/置か/住む/流し/我が) in natural home.',
    'cafe_quiet_chatter',
    ['借り', '置か', '住む', '流し', '我が'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '新しい部屋を、借りることにしたの。', en: "I decided to rent a new room.", style: 'soft warm woman voice, gentle excited delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'ええなあ、どの辺に住むんや?', en: "Nice, where will you live?", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: '駅の近くに、住む予定なの。', en: "I plan to live near the station.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '台所の流しは、広いんか?', en: "Is the kitchen sink spacious?", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '流しが大きくて、料理しやすいの。', en: "The sink is big and easy to cook at.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '荷物は、どこに置くんや?', en: "Where will you put your stuff?", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '本は、棚に置こうと思ってるの。', en: "I'm thinking of putting books on a shelf.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '我が家にも、遊びに来てや!', en: "Come visit our home too!", style: 'warm Kansai man voice, warm hearty closing delivery throughout' },
    ]),

  C('conv_02915',
    'Yumiko and Sho tidy the kitchen.',
    'Casual home register; vocabulary (借り/置か/住む/流し/我が) in natural home.',
    'kitchen_evening_quiet',
    ['借り', '置か', '住む', '流し', '我が'],
    ['yumiko_mom', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'yumiko_mom', jp: 'お皿を、流しに置いてくれる?', en: "Can you put the dishes in the sink?", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: 'うん!流しがいっぱいだね。', en: "Yeah! The sink is full.", style: 'cheerful small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'コップは、棚に置いておいてね。', en: "Put the cups on the shelf.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '隣に住む子に、本を借りたんだ。', en: "I borrowed a book from the kid living next door.", style: 'happy small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '借りた本は、大事にしてね。', en: "Take care of the borrowed book.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '我が家、きれいになったね!', en: "Our house got clean!", style: 'proud small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '流しを拭いたら、おしまいよ。', en: "Wipe the sink and we're done.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '本を、ちゃんと棚に置いたよ!', en: "I put the book on the shelf properly!", style: 'cheerful small child voice, bright warm affectionate closing delivery throughout' },
    ]),

  C('conv_02916',
    'Ren and Kenji talk about renting a workspace.',
    'WIDENED SCENARIO: work chat; vocabulary (借り/置か/住む/流し/我が) in natural home.',
    'office_quiet_low',
    ['借り', '置か', '住む', '流し', '我が'],
    ['ren_uni', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '作業部屋を、借りようと思うんです。', en: "I'm thinking of renting a workroom.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: 'どの辺に、借りるんですか?', en: "Where will you rent?", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '今住んでいる、近くがいいです。', en: "Near where I live now would be good.", style: 'thoughtful young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '機材は、どこに置くんですか?', en: "Where will you put the equipment?", style: 'curious office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '壁際に、棚を置く予定です。', en: "I plan to put a shelf by the wall.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '小さな流しも、あると便利ですよ。', en: "A small sink is handy to have too.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '流し付きの部屋を、探します。', en: "I'll look for a room with a sink.", style: 'resolved young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '我が社の近くだと、通いやすいですね。', en: "Near our company, it'd be easy to commute.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // CLUSTER F — emotion/casual (一瞬 幸い 気味 そうそう 寄せ)
  C('conv_02917',
    'Mei and Aoi recount a lucky near-miss.',
    'Casual register; vocabulary (一瞬/幸い/気味/そうそう/寄せ) in natural home.',
    'cafe_quiet_chatter',
    ['一瞬', '幸い', '気味', 'そうそう', '寄せ'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: 'さっき、一瞬ヒヤッとしたの。', en: "Earlier, I had a split-second scare.", style: 'animated barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'えっ、何があったの?', en: "Huh, what happened?", style: 'soft warm woman voice, gentle concerned delivery throughout' },
      { speaker: 'aoi_barista', jp: '棚が倒れ気味で、一瞬焦ったの。', en: "A shelf was about to tip, and I panicked for a second.", style: 'lively barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '幸い、けがはなかったのね?', en: "Fortunately, no injuries?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'うん、幸い無事だったよ。', en: "Yeah, fortunately I was fine.", style: 'relieved barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'そうそう、棚は壁に寄せた方がいいよ。', en: "Oh right, you should push the shelf against the wall.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'そうそう、壁に寄せておくね。', en: "Right, I'll push it to the wall.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '一瞬の油断が、危ないもんね。', en: "A moment's carelessness is dangerous.", style: 'gentle woman voice, soft warm caring closing delivery throughout' },
    ]),

  C('conv_02918',
    'Ren and Mei reminisce about a close call on a trip.',
    'Casual register; vocabulary (一瞬/幸い/気味/そうそう/寄せ) in natural home.',
    'cafe_quiet_chatter',
    ['一瞬', '幸い', '気味', 'そうそう', '寄せ'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: 'あの旅で、一瞬迷子になったよね。', en: "On that trip, we got lost for a moment.", style: 'soft warm woman voice, gentle amused delivery throughout' },
      { speaker: 'ren_uni', jp: 'そうそう、地図を逆に見てたんだ。', en: "Oh right, I was reading the map backwards.", style: 'rueful young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '幸い、親切な人に道を聞けたね。', en: "Fortunately, we could ask a kind person.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '少し疲れ気味だったから、焦ったよ。', en: "I was a bit tired, so I got flustered.", style: 'honest young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '車を、道の端に寄せて休んだね。', en: "We pulled the car to the roadside and rested.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'ren_uni', jp: 'そうそう、あの休憩で助かった。', en: "Right, that break saved us.", style: 'warm young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '一瞬の判断が、大事だったね。', en: "That split-second decision mattered.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'ren_uni', jp: '幸い、いい思い出になったよ。', en: "Fortunately, it became a good memory.", style: 'warm young man voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_02919',
    'Aoi and Riku laugh about a clumsy moment.',
    'Casual register; vocabulary (一瞬/幸い/気味/そうそう/寄せ) in natural home.',
    'cafe_quiet_chatter',
    ['一瞬', '幸い', '気味', 'そうそう', '寄せ'],
    ['aoi_barista', 'riku_teen'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '今日、一瞬転びそうになったよ!', en: "Today I almost tripped for a second!", style: 'animated teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'えっ、大丈夫だった?', en: "Huh, were you okay?", style: 'bright barista voice, soft warm concerned delivery throughout' },
      { speaker: 'riku_teen', jp: '幸い、すぐ立て直したよ。', en: "Fortunately, I steadied myself.", style: 'cheerful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '最近、疲れ気味じゃない?', en: "Aren't you a bit tired lately?", style: 'caring barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'そうそう、寝不足気味なんだ。', en: "Right, I'm a bit short on sleep.", style: 'sheepish teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '荷物を、体に寄せて持つといいよ。', en: "Carry your bag close to your body.", style: 'helpful barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: 'そうそう、その方が安定するね。', en: "Right, that's more stable.", style: 'agreeable teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '一瞬の油断、気をつけてね!', en: "Watch out for a moment's lapse!", style: 'bubbly barista voice, soft warm caring closing delivery throughout' },
    ]),

  // count-3 cleanup (後半 売れ 左右 生き方 含ま 作ら)
  C('conv_02920',
    'Ren interviews an author about a bestseller.',
    'WIDENED SCENARIO: author interview; vocabulary (後半/売れ/左右/生き方/含ま) in natural home.',
    'office_quiet_low',
    ['後半', '売れ', '左右', '生き方', '含ま'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'この本、すごく売れているそうですね。', en: "I hear this book sells very well.", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: 'おかげさまで、よく売れています。', en: "Thankfully, it sells well.", style: 'modest author voice, soft warm gentle clarity throughout' },
      { speaker: 'ren_uni', jp: '物語の後半が、特に良かったです。', en: "The latter half was especially good.", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '後半に、私の思いを多く含めました。', en: "I included many of my feelings in the latter half.", style: 'reflective author voice, soft warm gentle clarity throughout' },
      { speaker: 'ren_uni', jp: '主人公の生き方に、心を打たれました。', en: "The protagonist's way of life moved me.", style: 'moved young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '生き方は、選択に左右されますね。', en: "A way of life is shaped by choices.", style: 'composed author voice, soft warm gentle clarity throughout' },
      { speaker: 'ren_uni', jp: '結末は、何に左右されたんですか?', en: "What shaped the ending?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '彼の意思が、後半の結末を左右しました。', en: "His will shaped the latter half's ending.", style: 'warm author voice, soft warm gentle closing clarity throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_146 wrote', CONVERSATIONS.length, 'files');
