import fs from 'node:fs'; import path from 'node:path'; import url from 'node:url';
const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_169)', generated_at: NOW, source_plan_row: '' });
const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 3, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // ===== CLUSTER A: World Cup / racing sports =====
  C('conv_03361', 'Friends watch the World Cup final', 'Watch a final; teach ワールドカップ/前半/プレー/速度/抵抗/発揮/タイム/レース', 'living_room_quiet',
    ['ワールドカップ','前半','プレー','速度','抵抗','発揮','タイム','レース'], ['riku_teen', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: 'ついにワールドカップの決勝だ！', en: 'At last, the World Cup final!', style: 'hyped fan barely containing excitement' },
    { speaker: 'ren_uni', jp: '前半から動きが激しいね。', en: 'The action’s intense from the first half.', style: 'engaged fan reading the pace' },
    { speaker: 'sakura_teen', jp: '今のプレー、すごかった！', en: 'That play just now was amazing!', style: 'thrilled newcomer reacting on impulse' },
    { speaker: 'riku_teen', jp: '選手の走る速度が尋常じゃない。', en: 'The players’ running speed is unreal.', style: 'awed fan marveling at the athletes' },
    { speaker: 'ren_uni', jp: '相手の守備の抵抗も強いね。', en: 'The opponent’s defensive resistance is strong too.', style: 'analytical fan noting the matchup' },
    { speaker: 'sakura_teen', jp: 'エースが実力を発揮してるね。', en: 'The ace is showing his full ability.', style: 'admiring newcomer praising the star' },
    { speaker: 'riku_teen', jp: 'スプリントのタイム、世界記録級だよ。', en: 'His sprint time is world-record level.', style: 'data-savvy fan citing numbers' },
    { speaker: 'ren_uni', jp: 'これはまるで陸上のレースみたいだ。', en: 'This is like a track race.', style: 'fan drawing a vivid comparison' },
  ]),
  C('conv_03362', 'Analyzing the match at half-time', 'Half-time analysis; teach 前半/プレー/速度/抵抗/発揮/ワールドカップ/タイム/レース', 'living_room_quiet',
    ['前半','プレー','速度','抵抗','発揮','ワールドカップ','タイム','レース'], ['ren_uni', 'riku_teen', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '前半は0対0だったね。', en: 'The first half was nil-nil.', style: 'measured fan recapping calmly' },
    { speaker: 'riku_teen', jp: 'でも惜しいプレーが何度もあった。', en: 'But there were close plays again and again.', style: 'animated fan recalling near-misses' },
    { speaker: 'sakura_teen', jp: 'パスの速度がどんどん上がってる。', en: 'The pace of the passes keeps rising.', style: 'observant newcomer noticing the tempo' },
    { speaker: 'ren_uni', jp: '相手の抵抗をどう崩すかが鍵だ。', en: 'Breaking the opponent’s resistance is the key.', style: 'tactical fan framing the challenge' },
    { speaker: 'riku_teen', jp: '後半、エースが本領を発揮するはず。', en: 'In the second half, the ace should shine.', style: 'hopeful fan predicting confidently' },
    { speaker: 'sakura_teen', jp: 'ワールドカップの舞台、緊張するだろうね。', en: 'The World Cup stage must be nerve-wracking.', style: 'empathetic newcomer imagining the pressure' },
    { speaker: 'ren_uni', jp: '終盤はタイムとの戦いになる。', en: 'The endgame becomes a battle against time.', style: 'fan anticipating the clutch moments' },
    { speaker: 'riku_teen', jp: 'まるで長距離レースの駆け引きだ。', en: 'It’s like the tactics of a long-distance race.', style: 'fan extending the analogy' },
  ]),
  C('conv_03363', 'Interviewing an athlete before the tournament', 'Interview an athlete; teach ワールドカップ/前半/プレー/発揮/速度/レース/抵抗/タイム', 'studio_room_tone',
    ['ワールドカップ','前半','プレー','発揮','速度','レース','抵抗','タイム'], ['sakura_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: 'ワールドカップ出場、おめでとうございます！', en: 'Congrats on making the World Cup!', style: 'bright interviewer opening warmly' },
    { speaker: 'ren_uni', jp: 'ありがとう。前半で流れを作りたいです。', en: 'Thanks. I want to set the tempo in the first half.', style: 'focused athlete stating his aim' },
    { speaker: 'sakura_teen', jp: '自分のプレーに自信はありますか？', en: 'Are you confident in your play?', style: 'interviewer probing his mindset' },
    { speaker: 'ren_uni', jp: 'はい、練習の成果を発揮します。', en: 'Yes, I’ll show the results of my training.', style: 'determined athlete vowing readiness' },
    { speaker: 'sakura_teen', jp: '走る速度には自信が？', en: 'Confident in your running speed?', style: 'interviewer pressing on a strength' },
    { speaker: 'ren_uni', jp: 'ええ、レースでも鍛えてきました。', en: 'Yes, I trained through races too.', style: 'athlete grounding it in experience' },
    { speaker: 'sakura_teen', jp: '相手の抵抗にはどう対応を？', en: 'How will you handle opponents’ resistance?', style: 'interviewer asking tactically' },
    { speaker: 'ren_uni', jp: '冷静に、タイムを意識して戦います。', en: 'Calmly, mindful of the clock, I’ll compete.', style: 'composed athlete projecting poise' },
  ]),
  C('conv_03364', 'Reacting right after the team wins', 'Post-match jubilation; teach ワールドカップ/プレー/前半/速度/抵抗/発揮/タイム/レース', 'living_room_quiet',
    ['ワールドカップ','プレー','前半','速度','抵抗','発揮','タイム','レース'], ['riku_teen', 'sakura_teen', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'riku_teen', jp: '勝った！ ワールドカップ初優勝だ！', en: 'We won! First World Cup title!', style: 'ecstatic fan erupting in joy' },
    { speaker: 'sakura_teen', jp: '後半のあのプレーが決め手だったね。', en: 'That second-half play was the decider.', style: 'thrilled fan reliving the moment' },
    { speaker: 'ren_uni', jp: '前半の我慢が、最後に活きた。', en: 'The first-half patience paid off in the end.', style: 'analytical fan crediting the strategy' },
    { speaker: 'riku_teen', jp: '加速の速度が、相手を上回ってた。', en: 'Their acceleration speed beat the opponents.', style: 'fan praising the physical edge' },
    { speaker: 'sakura_teen', jp: '強い抵抗を、よく乗り越えたよね。', en: 'They overcame strong resistance well.', style: 'admiring fan appreciating the grit' },
    { speaker: 'ren_uni', jp: 'チーム全員が力を発揮した結果だ。', en: 'It’s the result of the whole team performing.', style: 'fan honoring the collective effort' },
    { speaker: 'riku_teen', jp: 'ラストスパートのタイム、見事だった。', en: 'The final-spurt time was superb.', style: 'fan marveling at the finish' },
    { speaker: 'sakura_teen', jp: 'まるで筋書きのないレースを見てるようだった。', en: 'It was like watching an unscripted race.', style: 'moved fan capturing the drama' },
  ]),
  C('conv_03365', 'Recapping the whole tournament', 'Recap the event; teach ワールドカップ/前半/プレー/速度/抵抗/発揮/タイム/レース', 'living_room_quiet',
    ['ワールドカップ','前半','プレー','速度','抵抗','発揮','タイム','レース'], ['ren_uni', 'riku_teen', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '今大会のワールドカップ、最高だったね。', en: 'This World Cup was the best.', style: 'satisfied fan reflecting fondly' },
    { speaker: 'riku_teen', jp: 'どの試合も、前半から目が離せなかった。', en: 'Every match gripped me from the first half.', style: 'enthusiastic fan recalling it all' },
    { speaker: 'sakura_teen', jp: '名プレーがたくさん生まれたね。', en: 'So many great plays were born.', style: 'happy fan celebrating highlights' },
    { speaker: 'ren_uni', jp: '選手たちの速度、年々上がってる。', en: 'The players’ speed rises year by year.', style: 'observant fan noting a trend' },
    { speaker: 'riku_teen', jp: '最後まで抵抗したチームも立派だった。', en: 'The teams that resisted to the end were admirable too.', style: 'fan praising the losing side' },
    { speaker: 'sakura_teen', jp: 'それぞれが個性を発揮してた。', en: 'Each showed their individuality.', style: 'fan appreciating the variety' },
    { speaker: 'ren_uni', jp: '記録的なタイムも出たしね。', en: 'Record times were set too.', style: 'fan adding a statistical note' },
    { speaker: 'riku_teen', jp: '次は自転車レースの観戦もしたいな。', en: 'Next I want to watch a cycling race too.', style: 'eager fan looking ahead' },
  ]),

  // ===== CLUSTER B: corporate shareholders' meeting =====
  C('conv_03366', 'Preparing for the shareholders’ meeting', 'Prep the meeting; teach 株主/各種/廃止/合理/要請/流通/中間/命令', 'office_quiet_low',
    ['株主','各種','廃止','合理','要請','流通','中間','命令'], ['hiroshi_boss', 'yuki_office', 'kenji_office'], 'Medium (7-12)', [
    { speaker: 'hiroshi_boss', jp: '株主総会が近い。準備を進めよう。', en: 'The shareholders’ meeting is near. Let’s prep.', style: 'commanding boss setting the agenda' },
    { speaker: 'yuki_office', jp: '各種の資料をまとめています。', en: 'I’m compiling all kinds of materials.', style: 'diligent assistant reporting progress' },
    { speaker: 'kenji_office', jp: '古い制度の廃止も提案しますか？', en: 'Shall we propose abolishing the old system too?', style: 'strategic manager raising an idea' },
    { speaker: 'hiroshi_boss', jp: 'ああ、合理的に判断したい。', en: 'Yes, I want to judge it rationally.', style: 'decisive boss demanding logic' },
    { speaker: 'yuki_office', jp: '取引先からの要請も増えています。', en: 'Requests from clients are increasing too.', style: 'assistant flagging external pressure' },
    { speaker: 'kenji_office', jp: '商品の流通網も見直すべきですね。', en: 'We should review the distribution network too.', style: 'manager proposing a fix' },
    { speaker: 'hiroshi_boss', jp: '中間管理職の負担も考慮しよう。', en: 'Let’s consider middle managers’ burden too.', style: 'thoughtful boss weighing people' },
    { speaker: 'yuki_office', jp: '上からの命令を、現場にどう伝えるかも課題です。', en: 'How to convey top-down orders to the field is a challenge too.', style: 'assistant raising a real concern' },
  ]),
  C('conv_03367', 'Discussing a restructuring plan', 'Plan restructuring; teach 流通/合理/廃止/株主/各種/要請/中間/命令', 'office_quiet_low',
    ['流通','合理','廃止','株主','各種','要請','中間','命令'], ['kenji_office', 'hiroshi_boss', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'kenji_office', jp: '流通コストが、利益を圧迫しています。', en: 'Distribution costs are squeezing profits.', style: 'analytical manager presenting the issue' },
    { speaker: 'hiroshi_boss', jp: '合理化が避けられないな。', en: 'Streamlining is unavoidable.', style: 'grim boss facing reality' },
    { speaker: 'yuki_office', jp: '不採算事業の廃止を、検討すべきでしょうか。', en: 'Should we consider abolishing the unprofitable business?', style: 'cautious assistant raising the option' },
    { speaker: 'hiroshi_boss', jp: '株主への説明が必要になる。', en: 'We’ll need to explain to shareholders.', style: 'boss anticipating accountability' },
    { speaker: 'kenji_office', jp: '各種のデータを揃えておきます。', en: 'I’ll gather all kinds of data.', style: 'manager committing to prep' },
    { speaker: 'yuki_office', jp: '労働組合からの要請も無視できません。', en: 'We can’t ignore the union’s requests either.', style: 'assistant noting another stakeholder' },
    { speaker: 'hiroshi_boss', jp: '中間決算の数字を見てから決めよう。', en: 'Let’s decide after seeing the mid-term figures.', style: 'prudent boss delaying judgment' },
    { speaker: 'kenji_office', jp: 'トップの命令を待つ、ということですね。', en: 'So we await the top’s order, then.', style: 'manager confirming the chain' },
  ]),
  C('conv_03368', 'Rehearsing answers for shareholders', 'Rehearse the Q&A; teach 株主/廃止/流通/各種/合理/要請/中間/命令', 'office_quiet_low',
    ['株主','廃止','流通','各種','合理','要請','中間','命令'], ['yuki_office', 'hiroshi_boss', 'kenji_office'], 'Medium (7-12)', [
    { speaker: 'yuki_office', jp: '株主からの質問に備えましょう。', en: 'Let’s prepare for shareholders’ questions.', style: 'proactive assistant organizing the rehearsal' },
    { speaker: 'hiroshi_boss', jp: '廃止する事業について、説明を尽くす。', en: 'I’ll fully explain the business we’re abolishing.', style: 'resolved boss committing to transparency' },
    { speaker: 'kenji_office', jp: '流通改革の成果も、数字で示します。', en: 'I’ll show distribution-reform results with figures.', style: 'prepared manager backing it with data' },
    { speaker: 'yuki_office', jp: '各種のグラフを用意しました。', en: 'I prepared all kinds of graphs.', style: 'thorough assistant noting her work' },
    { speaker: 'hiroshi_boss', jp: '合理性を強調すれば、理解は得られる。', en: 'Emphasizing the rationale will earn understanding.', style: 'confident boss outlining the pitch' },
    { speaker: 'kenji_office', jp: '行政からの要請にも触れますか？', en: 'Shall we mention the government’s requests too?', style: 'manager checking scope' },
    { speaker: 'yuki_office', jp: '中間目標の達成度も報告します。', en: 'I’ll report progress on mid-term goals too.', style: 'assistant adding to the plan' },
    { speaker: 'hiroshi_boss', jp: 'では、私の命令として、全員で臨もう。', en: 'Then, as my order, let’s all face it together.', style: 'rallying boss issuing the directive' },
  ]),
  C('conv_03369', 'Debriefing after the meeting succeeds', 'Debrief the meeting; teach 株主/廃止/合理/流通/各種/要請/中間/命令', 'office_quiet_low',
    ['株主','廃止','合理','流通','各種','要請','中間','命令'], ['hiroshi_boss', 'yuki_office', 'kenji_office'], 'Medium (7-12)', [
    { speaker: 'hiroshi_boss', jp: '株主総会、無事に終わったな。', en: 'The shareholders’ meeting went smoothly.', style: 'relieved boss exhaling' },
    { speaker: 'yuki_office', jp: '廃止の件も、理解を得られました。', en: 'We got understanding on the abolition too.', style: 'satisfied assistant reporting the win' },
    { speaker: 'kenji_office', jp: '合理化への賛同も多かったです。', en: 'There was much support for streamlining.', style: 'pleased manager noting approval' },
    { speaker: 'hiroshi_boss', jp: '流通の改善が、評価された。', en: 'The distribution improvements were praised.', style: 'proud boss crediting the work' },
    { speaker: 'yuki_office', jp: '各種の質問にも、的確に答えられました。', en: 'We answered all kinds of questions accurately.', style: 'confident assistant recapping' },
    { speaker: 'kenji_office', jp: '株主からの要請を、今後に活かしましょう。', en: 'Let’s use shareholders’ requests going forward.', style: 'forward-looking manager suggesting' },
    { speaker: 'hiroshi_boss', jp: '中間期に向けて、また動き出そう。', en: 'Let’s get moving toward the mid-term again.', style: 'motivating boss looking ahead' },
    { speaker: 'yuki_office', jp: '次の命令を、お待ちしています。', en: 'I await your next orders.', style: 'ready assistant standing by' },
  ]),
  C('conv_03370', 'A senior mentors a junior on the business', 'Mentor on business; teach 株主/合理/各種/流通/廃止/命令/要請/中間', 'office_quiet_low',
    ['株主','合理','各種','流通','廃止','命令','要請','中間'], ['kenji_office', 'yuki_office'], 'Medium (7-12)', [
    { speaker: 'kenji_office', jp: '会社の仕組み、少しずつ分かってきた？', en: 'Are you grasping the company’s workings?', style: 'mentoring manager checking in' },
    { speaker: 'yuki_office', jp: 'はい。株主の存在の大きさを実感しました。', en: 'Yes. I felt how big the shareholders’ presence is.', style: 'learning junior reflecting' },
    { speaker: 'kenji_office', jp: '合理的に動くのが、ビジネスの基本だよ。', en: 'Acting rationally is the basics of business.', style: 'mentor sharing a principle' },
    { speaker: 'yuki_office', jp: '各種の調整が、こんなに大変だとは。', en: 'I didn’t expect all the coordination to be so hard.', style: 'humbled junior admitting it' },
    { speaker: 'kenji_office', jp: '流通や在庫の管理も、奥が深い。', en: 'Distribution and inventory management run deep too.', style: 'mentor widening her view' },
    { speaker: 'yuki_office', jp: '古い慣習の廃止も、勇気が要りますね。', en: 'Abolishing old customs takes courage too.', style: 'junior reflecting thoughtfully' },
    { speaker: 'kenji_office', jp: '上の命令を、ただ待つだけじゃだめだ。', en: 'Just waiting for top orders isn’t enough.', style: 'mentor pushing initiative' },
    { speaker: 'yuki_office', jp: '自分から要請する姿勢も大事ですね。', en: 'Proactively making requests matters too.', style: 'junior internalizing the lesson' },
    { speaker: 'kenji_office', jp: 'そう。中間にいる僕らが、橋渡しをするんだ。', en: 'Right. We in the middle do the bridging.', style: 'mentor framing their role' },
  ]),

  // ===== CLUSTER C: travel destinations =====
  C('conv_03371', 'Friends dream up their next trip', 'Brainstorm a trip; teach ニューヨーク/カナダ/欧州/イスラエル/福岡/名古屋/鉄道/滞在', 'cafe_quiet_chatter',
    ['ニューヨーク','カナダ','欧州','イスラエル','福岡','名古屋','鉄道','滞在'], ['mei_romantic', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: '次の旅行、どこ行きたい？', en: 'Where do you want to go next trip?', style: 'cheerful friend opening the dream' },
    { speaker: 'ren_uni', jp: '僕はニューヨークに行ってみたい。', en: 'I want to try New York.', style: 'aspirational friend naming a city' },
    { speaker: 'sakura_teen', jp: '私はカナダの大自然がいいな。', en: 'I’d love Canada’s great outdoors.', style: 'nature-loving friend chiming in' },
    { speaker: 'mei_romantic', jp: '欧州の街並みも捨てがたいよね。', en: 'Europe’s townscapes are tempting too.', style: 'romantic friend weighing options' },
    { speaker: 'ren_uni', jp: 'イスラエルみたいな歴史的な場所も興味ある。', en: 'I’m curious about historic places like Israel too.', style: 'curious friend broadening it' },
    { speaker: 'sakura_teen', jp: 'でも、まずは国内で福岡とか。', en: 'But first, somewhere domestic like Fukuoka.', style: 'practical friend grounding it' },
    { speaker: 'mei_romantic', jp: '名古屋にも美味しいものが多いよね。', en: 'Nagoya has lots of good food too.', style: 'foodie friend adding a draw' },
    { speaker: 'ren_uni', jp: '鉄道で巡る旅も、風情があっていい。', en: 'A rail journey has its own charm too.', style: 'wistful friend savoring the idea' },
    { speaker: 'sakura_teen', jp: '長く滞在して、ゆっくりしたいな。', en: 'I want to stay long and relax.', style: 'dreamy friend imagining the pace' },
  ]),
  C('conv_03372', 'Planning a domestic rail trip', 'Plan a rail trip; teach 鉄道/名古屋/福岡/滞在/欧州/ニューヨーク/カナダ/イスラエル', 'cafe_quiet_chatter',
    ['鉄道','名古屋','福岡','滞在','欧州','ニューヨーク','カナダ','イスラエル'], ['mei_romantic', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: '今回は鉄道で西へ行こう。', en: 'This time let’s go west by rail.', style: 'planning friend proposing a route' },
    { speaker: 'sakura_teen', jp: '名古屋で一泊して、福岡まで？', en: 'Stay a night in Nagoya, then to Fukuoka?', style: 'engaged friend mapping the legs' },
    { speaker: 'mei_romantic', jp: 'いいね。福岡には何日滞在する？', en: 'Nice. How many days do we stay in Fukuoka?', style: 'organizing friend checking duration' },
    { speaker: 'sakura_teen', jp: '三日くらいゆっくりしたい。', en: 'I want about three relaxed days.', style: 'friend setting the pace' },
    { speaker: 'mei_romantic', jp: '海外だと、欧州は遠いもんね。', en: 'For abroad, Europe is far, after all.', style: 'friend comparing with overseas' },
    { speaker: 'sakura_teen', jp: 'ニューヨークも憧れるけど、予算が…。', en: 'I long for New York too, but the budget…', style: 'friend tempering with reality' },
    { speaker: 'mei_romantic', jp: 'カナダやイスラエルは、また今度ね。', en: 'Canada and Israel are for another time.', style: 'friend deferring the big trips' },
  ]),
  C('conv_03373', 'A friend returns from abroad', 'Hear about a trip; teach ニューヨーク/滞在/カナダ/欧州/イスラエル/福岡/名古屋/鉄道', 'cafe_quiet_chatter',
    ['ニューヨーク','滞在','カナダ','欧州','イスラエル','福岡','名古屋','鉄道'], ['ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: '海外旅行、どうだった？', en: 'How was the overseas trip?', style: 'curious friend welcoming him back' },
    { speaker: 'ren_uni', jp: 'ニューヨークは刺激的だったよ。', en: 'New York was stimulating.', style: 'energized friend recounting' },
    { speaker: 'sakura_teen', jp: 'どれくらい滞在したの？', en: 'How long did you stay?', style: 'friend asking details' },
    { speaker: 'ren_uni', jp: '一週間。そのあとカナダにも寄った。', en: 'A week. Then I stopped in Canada too.', style: 'friend sharing the itinerary' },
    { speaker: 'sakura_teen', jp: '欧州には行かなかったの？', en: 'Didn’t you go to Europe?', style: 'friend probing further' },
    { speaker: 'ren_uni', jp: '今回はね。次はイスラエルを巡りたい。', en: 'Not this time. Next I want to tour Israel.', style: 'friend looking ahead' },
    { speaker: 'sakura_teen', jp: '帰国後は、福岡の実家に？', en: 'After returning, to your Fukuoka home?', style: 'friend connecting to home' },
    { speaker: 'ren_uni', jp: 'うん、名古屋経由で鉄道で帰ったよ。', en: 'Yeah, I went home by rail via Nagoya.', style: 'friend wrapping up the journey' },
  ]),
  C('conv_03374', 'Comparing favorite destinations', 'Compare places; teach 鉄道/名古屋/福岡/ニューヨーク/欧州/カナダ/イスラエル/滞在', 'cafe_quiet_chatter',
    ['鉄道','名古屋','福岡','ニューヨーク','欧州','カナダ','イスラエル','滞在'], ['mei_romantic', 'ren_uni'], 'Medium (7-12)', [
    { speaker: 'mei_romantic', jp: '海外と国内、どっちが好き？', en: 'Which do you prefer, abroad or domestic?', style: 'friend posing a fun question' },
    { speaker: 'ren_uni', jp: '国内なら、鉄道の旅が好きだな。', en: 'Domestically, I love rail trips.', style: 'friend stating a preference' },
    { speaker: 'mei_romantic', jp: '名古屋も福岡も、料理が最高だよね。', en: 'Both Nagoya and Fukuoka have great food.', style: 'foodie friend agreeing warmly' },
    { speaker: 'ren_uni', jp: '海外はニューヨークの活気が忘れられない。', en: 'Abroad, New York’s energy is unforgettable.', style: 'friend reminiscing' },
    { speaker: 'mei_romantic', jp: '私は欧州の歴史ある街が好き。', en: 'I love Europe’s historic towns.', style: 'friend sharing her taste' },
    { speaker: 'ren_uni', jp: 'カナダの自然も雄大だったな。', en: 'Canada’s nature was majestic too.', style: 'friend recalling fondly' },
    { speaker: 'mei_romantic', jp: 'イスラエルは、いつか長く滞在してみたい。', en: 'Israel — someday I want a long stay.', style: 'friend voicing a wish' },
  ]),
  C('conv_03375', 'Looking through travel photos', 'Review photos; teach ニューヨーク/滞在/カナダ/欧州/イスラエル/福岡/名古屋/鉄道', 'living_room_quiet',
    ['ニューヨーク','滞在','カナダ','欧州','イスラエル','福岡','名古屋','鉄道'], ['sakura_teen', 'mei_romantic'], 'Medium (7-12)', [
    { speaker: 'sakura_teen', jp: 'この写真、ニューヨークの夜景？', en: 'Is this photo New York’s night view?', style: 'curious friend flipping through' },
    { speaker: 'mei_romantic', jp: 'そう。すごく長く滞在したんだ。', en: 'Yes. I stayed a really long time.', style: 'fond friend recalling' },
    { speaker: 'sakura_teen', jp: 'こっちはカナダの湖だね。', en: 'This one’s a lake in Canada, right?', style: 'friend recognizing the scene' },
    { speaker: 'mei_romantic', jp: '欧州の教会の写真もあるよ。', en: 'There are photos of European churches too.', style: 'friend sharing more' },
    { speaker: 'sakura_teen', jp: 'イスラエルの遺跡、神秘的だね。', en: 'Israel’s ruins look mystical.', style: 'awed friend admiring' },
    { speaker: 'mei_romantic', jp: '国内では、福岡の屋台が楽しかった。', en: 'Domestically, Fukuoka’s food stalls were fun.', style: 'friend reminiscing happily' },
    { speaker: 'sakura_teen', jp: '名古屋城も立派だったでしょ。', en: 'Nagoya Castle was grand too, right?', style: 'friend prompting a memory' },
    { speaker: 'mei_romantic', jp: 'うん、鉄道の車窓から見た景色も最高だった。', en: 'Yeah, the views from the train window were the best too.', style: 'friend closing on a warm note' },
  ]),

  // ===== CLUSTER D: society & current affairs =====
  C('conv_03376', 'A class discusses social issues', 'Discuss society; teach 自殺/重大/一致/容易/何らかの/原理/民主党/天皇', 'lecture_hall_quiet',
    ['自殺','重大','一致','容易','何らかの','原理','民主党','天皇'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '今日は社会問題を取り上げます。', en: 'Today we take up social issues.', style: 'serious teacher opening the topic' },
    { speaker: 'ren_uni', jp: '自殺者数の減少が、ニュースになっていました。', en: 'A drop in suicides was in the news.', style: 'informed student citing data' },
    { speaker: 'sakura_teen', jp: '重大な課題ですよね。', en: 'It’s a grave issue.', style: 'earnest teen acknowledging gravity' },
    { speaker: 'asuka_teacher', jp: 'ええ、対策には専門家の意見の一致が必要です。', en: 'Yes — measures need consensus among experts.', style: 'teacher stressing agreement' },
    { speaker: 'ren_uni', jp: '解決は容易ではないですね。', en: 'A solution isn’t easy.', style: 'realistic student noting difficulty' },
    { speaker: 'sakura_teen', jp: '何らかの支援制度が求められています。', en: 'Some kind of support system is needed.', style: 'compassionate teen calling for action' },
    { speaker: 'asuka_teacher', jp: '民主主義の原理に基づいて、議論すべきです。', en: 'We should debate it on democratic principles.', style: 'teacher framing the approach' },
    { speaker: 'ren_uni', jp: '政治では、民主党も対策を掲げていました。', en: 'Politically, the Democratic Party raised measures too.', style: 'student adding the political angle' },
    { speaker: 'sakura_teen', jp: '天皇陛下も、福祉への関心を示されました。', en: 'The Emperor also showed concern for welfare.', style: 'teen noting a public gesture' },
  ]),
  C('conv_03377', 'Debating a contested policy', 'Debate policy; teach 容易/重大/一致/民主党/何らかの/原理/自殺/天皇', 'lecture_hall_quiet',
    ['容易','重大','一致','民主党','何らかの','原理','自殺','天皇'], ['ren_uni', 'asuka_teacher'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: 'この問題、解決は容易じゃないですよね。', en: 'This problem isn’t easy to solve, right?', style: 'thoughtful student opening' },
    { speaker: 'asuka_teacher', jp: 'ええ、重大な決断が求められます。', en: 'Yes, a grave decision is required.', style: 'teacher underscoring the stakes' },
    { speaker: 'ren_uni', jp: '各党の意見は一致しているんですか？', en: 'Do the parties agree?', style: 'student probing consensus' },
    { speaker: 'asuka_teacher', jp: 'いいえ、民主党と与党で対立しています。', en: 'No, the Democratic Party and ruling party clash.', style: 'teacher describing the split' },
    { speaker: 'ren_uni', jp: '何らかの妥協点が必要ですね。', en: 'Some kind of compromise is needed.', style: 'student proposing a path' },
    { speaker: 'asuka_teacher', jp: '民主主義の原理を尊重しつつ、ですね。', en: 'While respecting democratic principles, yes.', style: 'teacher adding a condition' },
    { speaker: 'ren_uni', jp: '自殺対策のような福祉も、争点です。', en: 'Welfare like suicide prevention is a point of contention too.', style: 'student widening the scope' },
    { speaker: 'asuka_teacher', jp: '天皇制についても、議論されることがあります。', en: 'The imperial system is sometimes debated too.', style: 'teacher noting another theme' },
  ]),
  C('conv_03378', 'A history lecture on modernization', 'Teach modern history; teach 天皇/重大/原理/一致/容易/何らかの/民主党/自殺', 'lecture_hall_quiet',
    ['天皇','重大','原理','一致','容易','何らかの','民主党','自殺'], ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '近代史では、天皇の役割が大きく変わりました。', en: 'In modern history, the Emperor’s role changed greatly.', style: 'teacher narrating history' },
    { speaker: 'sakura_teen', jp: '重大な転換点だったんですね。', en: 'It was a major turning point.', style: 'engaged teen grasping it' },
    { speaker: 'asuka_teacher', jp: 'ええ、新しい統治の原理が導入されました。', en: 'Yes, new governing principles were introduced.', style: 'teacher explaining the shift' },
    { speaker: 'sakura_teen', jp: '国民の意見は一致していたんですか？', en: 'Did the people agree?', style: 'curious teen asking' },
    { speaker: 'asuka_teacher', jp: 'いいえ、変革は容易ではありませんでした。', en: 'No, the transformation wasn’t easy.', style: 'teacher conveying the struggle' },
    { speaker: 'sakura_teen', jp: '何らかの混乱もあったでしょうね。', en: 'There must have been some chaos.', style: 'teen imagining the era' },
    { speaker: 'asuka_teacher', jp: 'ええ、当時は政党、今で言う民主党のような組織も生まれました。', en: 'Yes — parties, like today’s Democratic Party, emerged then.', style: 'teacher drawing a parallel' },
    { speaker: 'sakura_teen', jp: '社会の歪みで、自殺が増えた時期もあったとか。', en: 'In times of social strain, suicides reportedly rose too.', style: 'teen noting a sobering fact' },
  ]),
  C('conv_03379', 'A current-events roundup', 'Round up the news; teach 重大/民主党/一致/容易/何らかの/原理/天皇/自殺', 'living_room_quiet',
    ['重大','民主党','一致','容易','何らかの','原理','天皇','自殺'], ['ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'ren_uni', jp: '今週も重大なニュースが多かったね。', en: 'This week had a lot of major news too.', style: 'weary friend opening the roundup' },
    { speaker: 'sakura_teen', jp: '民主党の新しい代表が決まったよ。', en: 'The Democratic Party picked a new leader.', style: 'informed friend sharing news' },
    { speaker: 'ren_uni', jp: '党内の意見は一致してるのかな。', en: 'Is the party internally in agreement?', style: 'skeptical friend wondering' },
    { speaker: 'sakura_teen', jp: 'まとめるのは容易じゃなさそう。', en: 'Unifying them won’t be easy.', style: 'friend doubting' },
    { speaker: 'ren_uni', jp: '何らかのスキャンダルもあったらしい。', en: 'There was some scandal too, apparently.', style: 'friend adding gossip' },
    { speaker: 'sakura_teen', jp: '政治の原理原則が問われてるね。', en: 'Political principles are being questioned.', style: 'thoughtful friend reflecting' },
    { speaker: 'ren_uni', jp: '天皇の即位関連のニュースも続いてた。', en: 'News about the Emperor’s accession continued too.', style: 'friend noting another story' },
    { speaker: 'sakura_teen', jp: '自殺対策の予算も、話題になってたよ。', en: 'The suicide-prevention budget was a topic too.', style: 'friend rounding it out' },
  ]),
  C('conv_03380', 'Wrapping up the society unit', 'Summarize the unit; teach 重大/容易/一致/民主党/何らかの/原理/天皇/自殺', 'lecture_hall_quiet',
    ['重大','容易','一致','民主党','何らかの','原理','天皇','自殺'], ['asuka_teacher', 'ren_uni', 'sakura_teen'], 'Medium (7-12)', [
    { speaker: 'asuka_teacher', jp: '社会の単元、いかがでしたか？', en: 'How was the society unit?', style: 'teacher inviting reflection' },
    { speaker: 'ren_uni', jp: '重大な問題が、身近にあると感じました。', en: 'I felt grave issues are close to us.', style: 'reflective student sharing' },
    { speaker: 'sakura_teen', jp: '解決が容易でないことも分かりました。', en: 'I learned solutions aren’t easy.', style: 'maturing teen acknowledging' },
    { speaker: 'asuka_teacher', jp: '意見の一致を目指す過程が、民主主義です。', en: 'The process of seeking agreement is democracy.', style: 'teacher offering a definition' },
    { speaker: 'ren_uni', jp: '民主党のような政党の役割も学べました。', en: 'I learned the role of parties like the Democratic Party too.', style: 'student noting a takeaway' },
    { speaker: 'sakura_teen', jp: '何らかの形で、社会に貢献したいです。', en: 'I want to contribute to society in some way.', style: 'idealistic teen voicing a wish' },
    { speaker: 'asuka_teacher', jp: '原理を理解し、行動することが大切です。', en: 'Understanding principles and acting matters.', style: 'teacher giving a guiding charge' },
    { speaker: 'ren_uni', jp: '天皇という存在の意味も、考えさせられました。', en: 'The meaning of the Emperor made me think too.', style: 'student reflecting deeply' },
    { speaker: 'sakura_teen', jp: '自殺のような悲しい問題を、減らしたいです。', en: 'I want to reduce sad problems like suicide.', style: 'compassionate teen closing earnestly' },
  ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_169 wrote', CONVERSATIONS.length, 'files');
