import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_152)', generated_at: NOW, source_plan_row: '' });

const C = (id, context, purpose, ambient, target_vocab, cast, length_tier, lines) => ({
  id, context, purpose, ambient, sound_effects: [], target_vocab, cast,
  frequency_tier: 4, length_tier, meta: META(), lines,
});

const CONVERSATIONS = [
  // CLUSTER A — shopping/casual (死ん 限定 サイズ 詳しく オープン) + cleanup 探す
  C('conv_03021',
    'Riku and Aoi check out a new shop opening.',
    'Casual register; vocabulary (死ん/限定/サイズ/詳しく/オープン) in natural home.',
    'cafe_quiet_chatter',
    ['死ん', '限定', 'サイズ', '詳しく', 'オープン'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '駅前に、新しい店がオープンしたよ!', en: "A new shop opened by the station!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね、何のお店?詳しく教えて。', en: "Nice, what kind? Tell me in detail.", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '限定のスニーカーが、売ってるんだ。', en: "They sell limited-edition sneakers.", style: 'enthusiastic teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'サイズは、いろいろあるの?', en: "Are there various sizes?", style: 'curious barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '僕のサイズも、あったよ!探してたんだ。', en: "My size was there too! I'd been searching.", style: 'delighted teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '限定だと、すぐ売り切れそうだね。', en: "Limited ones sell out fast, huh.", style: 'engaged barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'スマホの電池が死んで、写真撮れなかった。', en: "My phone battery died, so I couldn't take photos.", style: 'rueful teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'オープン記念、詳しく調べてみようよ!', en: "Let's look into the opening event in detail!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03022',
    'Mei and Aoi shop for a limited-edition item.',
    'Casual register; vocabulary (死ん/限定/サイズ/詳しく/探す) in natural home.',
    'cafe_quiet_chatter',
    ['死ん', '限定', 'サイズ', '詳しく', '探す'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'mei_romantic', jp: '限定のバッグを、探しているの。', en: "I'm searching for a limited-edition bag.", style: 'soft warm woman voice, gentle engaged delivery throughout' },
      { speaker: 'aoi_barista', jp: 'どんなサイズが、いいの?', en: "What size are you after?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: '小さめのサイズを、探してるの。', en: "I'm looking for a smallish size.", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'ネットで、詳しく調べてみようか。', en: "Shall we look it up in detail online?", style: 'helpful barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'mei_romantic', jp: 'あ、スマホが死んじゃった。', en: "Oh, my phone died.", style: 'rueful woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '私のスマホで、詳しく見ようよ。', en: "Let's look at it in detail on mine.", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '限定だから、急いで探さなきゃ。', en: "It's limited, so I have to search fast.", style: 'soft woman voice, gentle warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'サイズが合うの、見つかるといいね!', en: "I hope you find one in your size!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03023',
    'Daichi tells Mei about his shop opening.',
    'WIDENED SCENARIO: shop chat; vocabulary (死ん/限定/サイズ/詳しく/オープン) in natural home.',
    'street_quiet_distant',
    ['死ん', '限定', 'サイズ', '詳しく', 'オープン'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: '来週、新しい店をオープンするんよ!', en: "I'm opening a new shop next week!", style: 'lively Kansai man voice, warm hearty eager delivery throughout' },
      { speaker: 'mei_romantic', jp: 'おめでとうございます!詳しく聞きたいです。', en: "Congratulations! I want to hear the details.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'オープン記念で、限定の品を出すんや。', en: "For the opening, I'll offer limited items.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'サイズは、選べるんですか?', en: "Can we choose sizes?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: 'いろんなサイズを、用意しとるで。', en: "I've prepared various sizes.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '準備で、忙しくて死にそうですか?', en: "Are you swamped with prep?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '忙しくて死にそうやけど、楽しいで!', en: "I'm swamped to death, but it's fun!", style: 'enthusiastic Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'オープン日、詳しく教えて下さいね。', en: "Please tell me the opening day in detail.", style: 'gentle woman voice, soft warm cheerful closing delivery throughout' },
    ]),

  C('conv_03024',
    'Sho tells Yumiko about a limited toy.',
    'Casual home register; vocabulary (死ん/限定/サイズ/詳しく/オープン) in natural home.',
    'kitchen_evening_quiet',
    ['死ん', '限定', 'サイズ', '詳しく', 'オープン'],
    ['sho_child', 'yumiko_mom'], 'Medium (7-12)',
    [
      { speaker: 'sho_child', jp: 'ママ、限定のおもちゃがあるんだ!', en: "Mom, there's a limited-edition toy!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'あら、どんなおもちゃ?詳しく教えて。', en: "Oh, what kind? Tell me in detail.", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: '大きいサイズのロボットなんだ!', en: "It's a big-size robot!", style: 'enthusiastic small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '新しいお店が、オープンしたのね。', en: "A new shop opened, then.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'うん!でも、電池が死んでて動かなかった。', en: "Yeah! But the battery was dead, so it didn't move.", style: 'pouty small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '電池を入れれば、動くわよ。', en: "If you put in batteries, it'll move.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '限定だから、欲しくなっちゃった。', en: "It's limited, so I really want it.", style: 'longing small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: 'オープン日に、見に行きましょうね。', en: "Let's go look on the opening day.", style: 'tender mother voice, soft warm affectionate closing delivery throughout' },
    ]),

  // CLUSTER B — lecture/abstract (含む 単位 基づい 主体 想定) + cleanup 超える
  C('conv_03025',
    'Asuka lectures on the basics of measurement.',
    'WIDENED SCENARIO: science lecture; vocabulary (含む/単位/基づい/主体/想定) in natural home.',
    'lecture_hall_quiet',
    ['含む', '単位', '基づい', '主体', '想定'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '測定は、正しい単位に基づいて行います。', en: "Measurement is done based on correct units.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '単位には、何が含まれますか?', en: "What's included in a unit?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: '長さや重さを、含む基準です。', en: "It's a standard that includes length and weight.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '実験では、何が主体になりますか?', en: "What becomes the main focus in experiments?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '観察を主体に、進めます。', en: "We proceed with observation as the main focus.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '結果は、想定どおりになりますか?', en: "Do results come out as expected?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '想定を超えることも、よくあります。', en: "Going beyond expectations is common too.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '単位に基づく考え方、分かりました。', en: "I understand the unit-based way of thinking.", style: 'satisfied adult student voice, soft warm realization throughout' },
    ]),

  C('conv_03026',
    'Ren and Asuka discuss research design.',
    'WIDENED SCENARIO: research discussion; vocabulary (含む/単位/基づい/主体/想定) in natural home.',
    'lecture_hall_quiet',
    ['含む', '単位', '基づい', '主体', '想定'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '調査は、何に基づいて設計しますか?', en: "What do we base the survey design on?", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '過去のデータに基づいて、設計します。', en: "We design based on past data.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '対象には、誰を含むんですか?', en: "Whom do we include as subjects?", style: 'curious young student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '若者を主体に、幅広く含みます。', en: "We include broadly, with youth as the main focus.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '人数の単位は、どう決めますか?', en: "How do we decide the unit of participants?", style: 'engaged young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '百人を一単位として、想定します。', en: "We assume a hundred as one unit.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'ren_uni', jp: '想定外のことも、起きますか?', en: "Do unexpected things happen too?", style: 'thoughtful young student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '想定を超える発見が、研究の醍醐味です。', en: "Findings beyond expectation are research's joy.", style: 'warm teacher voice, soft warm measured closing clarity throughout' },
    ]),

  C('conv_03027',
    'Hiroshi-boss and Ren plan based on data.',
    'WIDENED SCENARIO: business planning; vocabulary (含む/単位/基づい/主体/想定) in natural home.',
    'office_quiet_low',
    ['含む', '単位', '基づい', '主体', '想定'],
    ['hiroshi_boss', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'hiroshi_boss', jp: '計画は、何に基づいているかね?', en: "What is the plan based on?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '市場のデータに基づいています。', en: "It's based on market data.", style: 'reliable young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '若い顧客を、主体に考えているかね?', en: "Are you centering on young customers?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'はい、若者を主体に想定しています。', en: "Yes, I assume youth as the main focus.", style: 'measured young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '予算には、広告費も含むかね?', en: "Does the budget include ad costs?", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: 'ええ、広告費も含んでいます。', en: "Yes, it includes ad costs.", style: 'confident young manager voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '想定より、需要が増えたらどうかね?', en: "What if demand exceeds expectations?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '想定を超えても、対応できる計画です。', en: "It's a plan that can handle exceeding expectations.", style: 'resolved young manager voice, soft warm closing throughout' },
    ]),

  C('conv_03028',
    'Ren interviews a researcher on study methods.',
    'WIDENED SCENARIO: academic interview; vocabulary (含む/単位/基づい/主体/想定) in natural home.',
    'office_quiet_low',
    ['含む', '単位', '基づい', '主体', '想定'],
    ['ren_uni', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '研究は、何を主体に進めますか?', en: "What do you center your research on?", style: 'engaged young interviewer voice, soft warm curious focus throughout' },
      { speaker: 'asuka_teacher', jp: '事実を主体に、進めます。', en: "I proceed centered on facts.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '結論は、何に基づきますか?', en: "What are conclusions based on?", style: 'curious young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '十分なデータに基づいて、出します。', en: "I draw them based on sufficient data.", style: 'patient researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: '想定と違う結果は、扱いますか?', en: "Do you treat results that differ from expectations?", style: 'engaged young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '想定外も、論文に含みます。', en: "I include the unexpected in the paper too.", style: 'composed researcher voice, soft warm measured clarity throughout' },
      { speaker: 'ren_uni', jp: 'データの単位は、統一するんですか?', en: "Do you unify the data units?", style: 'thoughtful young interviewer voice, soft warm focus throughout' },
      { speaker: 'asuka_teacher', jp: '単位を統一して、想定を検証します。', en: "I unify units and verify the assumptions.", style: 'warm researcher voice, soft warm measured closing clarity throughout' },
    ]),

  // CLUSTER C — society/news (条約 混乱 主要 景気 相場)
  C('conv_03029',
    'Economic news: Sakura and Ren on market turmoil.',
    'WIDENED SCENARIO: economic news; vocabulary (条約/混乱/主要/景気/相場) in natural home.',
    'studio_room_tone',
    ['条約', '混乱', '主要', '景気', '相場'],
    ['sakura_teen', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '今日、相場が大きく動きました。', en: "The market moved sharply today.", style: 'crisp adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '相場の混乱は、何が原因ですか?', en: "What caused the market turmoil?", style: 'measured young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '条約の交渉が、混乱を招きました。', en: "Treaty negotiations caused the confusion.", style: 'clear adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '景気への影響は、大きいですか?', en: "Is the impact on the economy large?", style: 'curious young commentator voice, soft warm analytical calm throughout' },
      { speaker: 'sakura_teen', jp: '主要な産業が、景気に左右されます。', en: "Major industries are swayed by the economy.", style: 'professional adult anchor voice, soft warm clarity throughout' },
      { speaker: 'ren_uni', jp: '主要国の対応は、どうですか?', en: "How are the major nations responding?", style: 'analytical young commentator voice, soft warm calm throughout' },
      { speaker: 'sakura_teen', jp: '条約の見直しで、相場が落ち着くかもしれません。', en: "Revising the treaty may calm the market.", style: 'measured adult anchor voice, soft warm professional clarity throughout' },
      { speaker: 'ren_uni', jp: '景気の回復を、願いたいですね。', en: "I hope for an economic recovery.", style: 'earnest young commentator voice, soft warm calm closing throughout' },
    ]),

  C('conv_03030',
    'Asuka lectures on treaties and the economy.',
    'WIDENED SCENARIO: economics lecture; vocabulary (条約/混乱/主要/景気/相場) in natural home.',
    'lecture_hall_quiet',
    ['条約', '混乱', '主要', '景気', '相場'],
    ['asuka_teacher', 'sakura_teen'], 'Medium (7-12)',
    [
      { speaker: 'asuka_teacher', jp: '条約は、国家間の約束です。', en: "A treaty is a promise between nations.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '条約が、景気にも影響しますか?', en: "Do treaties affect the economy too?", style: 'attentive adult student voice, soft warm earnest engaged throughout' },
      { speaker: 'asuka_teacher', jp: 'ええ、貿易の条約は景気を左右します。', en: "Yes, trade treaties sway the economy.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '相場も、それで動くんですか?', en: "Does the market move because of that too?", style: 'curious adult student voice, soft warm engaged throughout' },
      { speaker: 'asuka_teacher', jp: '相場は、主要な条約に敏感です。', en: "The market is sensitive to major treaties.", style: 'composed teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '混乱を、防ぐ方法はありますか?', en: "Is there a way to prevent turmoil?", style: 'thoughtful adult student voice, soft warm curious throughout' },
      { speaker: 'asuka_teacher', jp: '丁寧な交渉が、混乱を防ぎます。', en: "Careful negotiation prevents turmoil.", style: 'patient teacher voice, soft warm measured instructive clarity throughout' },
      { speaker: 'sakura_teen', jp: '条約と景気、深く関わるんですね。', en: "Treaties and the economy are deeply linked.", style: 'moved adult student voice, soft warm realization throughout' },
    ]),

  C('conv_03031',
    'Ren reports market conditions to Hiroshi-boss.',
    'WIDENED SCENARIO: business report; vocabulary (条約/混乱/主要/景気/相場) in natural home.',
    'office_quiet_low',
    ['条約', '混乱', '主要', '景気', '相場'],
    ['ren_uni', 'hiroshi_boss'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '相場が、不安定になっています。', en: "The market has become unstable.", style: 'measured young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '混乱の原因は、何かね?', en: "What's the cause of the turmoil?", style: 'attentive boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '主要国の条約交渉が、原因です。', en: "Major nations' treaty talks are the cause.", style: 'precise young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '我が社の景気は、大丈夫かね?', en: "Is our company's business okay?", style: 'thoughtful boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '景気の波に、備えています。', en: "We're prepared for the economic waves.", style: 'confident young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '相場を、注意深く見てくれ。', en: "Watch the market carefully.", style: 'measured boss voice, soft warm inquiry throughout' },
      { speaker: 'ren_uni', jp: '主要な取引先とも、相談します。', en: "I'll consult our main clients too.", style: 'reliable young presenter voice, soft warm professional focus throughout' },
      { speaker: 'hiroshi_boss', jp: '混乱の中こそ、冷静に行こう。', en: "Especially amid turmoil, let's stay calm.", style: 'warm boss voice, soft warm decisive closing throughout' },
    ]),

  C('conv_03032',
    'Sakura interviews an economist on treaties.',
    'WIDENED SCENARIO: expert interview; vocabulary (条約/混乱/主要/景気/相場) in natural home.',
    'office_quiet_low',
    ['条約', '混乱', '主要', '景気', '相場'],
    ['sakura_teen', 'asuka_teacher'], 'Medium (7-12)',
    [
      { speaker: 'sakura_teen', jp: '今の景気を、どう見ていますか?', en: "How do you view the current economy?", style: 'professional adult interviewer voice, soft warm engaged clarity throughout' },
      { speaker: 'asuka_teacher', jp: '主要国の動きで、景気は揺れます。', en: "The economy sways with major nations' moves.", style: 'composed economist voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '条約は、相場に影響しますか?', en: "Do treaties affect the market?", style: 'engaged adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '新しい条約で、相場が動きます。', en: "New treaties move the market.", style: 'patient economist voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '混乱は、いつ収まりますか?', en: "When will the turmoil settle?", style: 'curious adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '条約が成立すれば、混乱は収まります。', en: "Once the treaty is concluded, the turmoil settles.", style: 'composed economist voice, soft warm measured clarity throughout' },
      { speaker: 'sakura_teen', jp: '主要な対策は、何ですか?', en: "What's the main measure?", style: 'probing adult interviewer voice, soft warm clarity throughout' },
      { speaker: 'asuka_teacher', jp: '景気を支える、安定した政策です。', en: "Stable policy that supports the economy.", style: 'warm economist voice, soft warm measured closing clarity throughout' },
    ]),

  // CLUSTER D — home/utility (設備 風呂 支払い 印刷 合計)
  C('conv_03033',
    'Yuki sets up utilities for a new apartment with Kenji.',
    'WIDENED SCENARIO: home setup; vocabulary (設備/風呂/支払い/印刷/合計) in natural home.',
    'office_quiet_low',
    ['設備', '風呂', '支払い', '印刷', '合計'],
    ['yuki_office', 'kenji_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '新しい部屋の設備、整えたいの。', en: "I want to set up the new room's facilities.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: 'お風呂の設備は、新しいですか?', en: "Is the bath equipment new?", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: 'はい、お風呂は最新の設備なんです。', en: "Yes, the bath has the latest equipment.", style: 'clear office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '支払いの手続きは、済みましたか?', en: "Have the payment procedures been done?", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '支払いは、来月からです。', en: "Payment starts next month.", style: 'professional office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '契約書を、印刷しておきましょう。', en: "Let's print out the contract.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'yuki_office', jp: '印刷したら、合計の金額を確認します。', en: "After printing, I'll check the total amount.", style: 'reliable office woman voice, soft warm clarity throughout' },
      { speaker: 'kenji_office', jp: '合計が、予算内なら安心ですね。', en: "If the total's within budget, you're set.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  C('conv_03034',
    'Daichi and Mei tour a rental apartment.',
    'WIDENED SCENARIO: housing chat; vocabulary (設備/風呂/支払い/印刷/合計) in natural home.',
    'living_room_quiet',
    ['設備', '風呂', '支払い', '印刷', '合計'],
    ['daichi_kansai', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'daichi_kansai', jp: 'この部屋、設備がええなあ。', en: "This room has nice facilities.", style: 'lively Kansai man voice, warm hearty delivery throughout' },
      { speaker: 'mei_romantic', jp: 'お風呂が、広くて素敵ですね。', en: "The bath is spacious and lovely.", style: 'soft warm woman voice, gentle delighted delivery throughout' },
      { speaker: 'daichi_kansai', jp: '風呂の設備、最新やで。', en: "The bath equipment is the latest.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '毎月の支払いは、いくらですか?', en: "How much is the monthly payment?", style: 'curious woman voice, gentle warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '支払いの明細、印刷してもらお。', en: "Let's have the payment details printed.", style: 'lively Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '合計で、いくらになりますか?', en: "What's the total?", style: 'gentle woman voice, soft warm delivery throughout' },
      { speaker: 'daichi_kansai', jp: '合計を見て、決めたらええよ。', en: "Look at the total and then decide.", style: 'cheerful Kansai man voice, warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '設備が良くて、気に入りました。', en: "The facilities are good; I like it.", style: 'soft woman voice, gentle warm cheerful closing delivery throughout' },
    ]),

  C('conv_03035',
    'Yumiko and Sho prepare a home bath night.',
    'Casual home register; vocabulary (設備/風呂/支払い/印刷/合計) in natural home.',
    'kitchen_evening_quiet',
    ['設備', '風呂', '支払い', '印刷', '合計'],
    ['yumiko_mom', 'sho_child'], 'Medium (7-12)',
    [
      { speaker: 'yumiko_mom', jp: '正坊、お風呂が沸いたわよ。', en: "Sho, the bath is ready.", style: 'gentle mother voice, soft warm caring delivery throughout' },
      { speaker: 'sho_child', jp: 'やった!新しいお風呂、気持ちいい!', en: "Yay! The new bath feels great!", style: 'excited small child voice, bright warm bouncing delivery throughout' },
      { speaker: 'yumiko_mom', jp: '新しい設備にして、良かったわね。', en: "Glad we got the new equipment.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'お金、たくさんかかったの?', en: "Did it cost a lot of money?", style: 'curious small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '支払いは、少しずつしているのよ。', en: "We're paying it off little by little.", style: 'gentle mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: '合計、いくらだったの?', en: "What was the total?", style: 'curious small child voice, bright warm delivery throughout' },
      { speaker: 'yumiko_mom', jp: '合計は、紙に印刷してあるわ。', en: "The total is printed on paper.", style: 'warm mother voice, soft warm delivery throughout' },
      { speaker: 'sho_child', jp: 'お風呂の設備、大好きだよ!', en: "I love the bath equipment!", style: 'happy small child voice, bright warm affectionate closing delivery throughout' },
    ]),

  C('conv_03036',
    'Kenji helps Ren print and total an expense report.',
    'WIDENED SCENARIO: office task; vocabulary (設備/風呂/支払い/印刷/合計) in natural home.',
    'office_quiet_low',
    ['設備', '風呂', '支払い', '印刷', '合計'],
    ['kenji_office', 'ren_uni'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: '経費の報告を、印刷したいんです。', en: "I want to print the expense report.", style: 'engaged young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '合計は、もう計算しましたか?', en: "Have you calculated the total?", style: 'helpful office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: 'はい、合計を出しました。', en: "Yes, I worked out the total.", style: 'reliable young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '支払いの記録も、含めましょう。', en: "Let's include the payment records too.", style: 'clear office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '出張先の風呂代も、支払いに入れますか?', en: "Do I include the trip's bath fees in payments?", style: 'curious young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '宿の設備代として、入れて下さい。', en: "Include it as lodging-facility cost.", style: 'measured office man voice, soft warm guiding throughout' },
      { speaker: 'ren_uni', jp: '印刷して、提出しますね。', en: "I'll print it and submit it.", style: 'satisfied young colleague voice, soft warm throughout' },
      { speaker: 'kenji_office', jp: '合計が合えば、すぐ通りますよ。', en: "If the total matches, it'll pass right away.", style: 'warm office man voice, soft warm closing throughout' },
    ]),

  // CLUSTER E — casual/emotion (ストレス 思える 恐れ すばらしい 早速)
  C('conv_03037',
    'Saito advises Yuki on managing stress.',
    'WIDENED SCENARIO: medical advice; vocabulary (ストレス/思える/恐れ/すばらしい/早速) in natural home.',
    'clinic_room_quiet',
    ['ストレス', '思える', '恐れ', 'すばらしい', '早速'],
    ['saito_doctor', 'yuki_office'], 'Medium (7-12)',
    [
      { speaker: 'yuki_office', jp: '最近、ストレスが溜まっているんです。', en: "Lately I've built up stress.", style: 'tired office woman voice, soft warm earnest delivery throughout' },
      { speaker: 'saito_doctor', jp: 'ストレスは、誰にでもあるものです。', en: "Stress is something everyone has.", style: 'calm doctor voice, soft warm reassuring measured clarity throughout' },
      { speaker: 'yuki_office', jp: '休むのが、怖いように思えるんです。', en: "Resting feels frightening to me.", style: 'vulnerable office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '恐れず、少しずつ休みましょう。', en: "Without fear, let's rest little by little.", style: 'gentle doctor voice, soft warm caring clarity throughout' },
      { speaker: 'yuki_office', jp: '散歩は、ストレスに効きますか?', en: "Is walking effective against stress?", style: 'curious office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '散歩は、すばらしい効果がありますよ。', en: "Walking has a wonderful effect.", style: 'warm doctor voice, soft warm measured clarity throughout' },
      { speaker: 'yuki_office', jp: 'では、早速、始めてみます。', en: "Then I'll start right away.", style: 'resolved office woman voice, soft warm delivery throughout' },
      { speaker: 'saito_doctor', jp: '休む勇気も、すばらしいと思えますよ。', en: "The courage to rest seems wonderful too.", style: 'gentle doctor voice, soft warm caring closing clarity throughout' },
    ]),

  C('conv_03038',
    'Mei and Aoi cheer each other up.',
    'Casual register; vocabulary (ストレス/思える/恐れ/すばらしい/早速) in natural home.',
    'cafe_quiet_chatter',
    ['ストレス', '思える', '恐れ', 'すばらしい', '早速'],
    ['mei_romantic', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'aoi_barista', jp: '最近、なんだかストレスが多くて。', en: "Lately I've somehow had a lot of stress.", style: 'tired barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '頑張りすぎてるように思えるよ。', en: "It seems like you're overdoing it.", style: 'soft warm woman voice, gentle caring delivery throughout' },
      { speaker: 'aoi_barista', jp: '失敗を、恐れちゃうんだよね。', en: "I end up fearing failure.", style: 'honest barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '恐れずに、挑戦していいんだよ。', en: "You can challenge yourself without fear.", style: 'gentle woman voice, soft warm encouraging delivery throughout' },
      { speaker: 'aoi_barista', jp: 'あなたの言葉、すばらしいね。', en: "Your words are wonderful.", style: 'moved barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'すばらしいあなたを、応援してるよ。', en: "I'm cheering for wonderful you.", style: 'warm woman voice, soft warm tender delivery throughout' },
      { speaker: 'aoi_barista', jp: '早速、気持ちが軽くなった!', en: "Right away, my heart feels lighter!", style: 'brightening barista voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'ストレスを、ためずにいこうね。', en: "Let's keep from bottling up stress.", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_03039',
    'Ren tells Mei about a wonderful new opportunity.',
    'Casual register; vocabulary (ストレス/思える/恐れ/すばらしい/早速) in natural home.',
    'cafe_quiet_chatter',
    ['ストレス', '思える', '恐れ', 'すばらしい', '早速'],
    ['ren_uni', 'mei_romantic'], 'Medium (7-12)',
    [
      { speaker: 'ren_uni', jp: 'すばらしい仕事の話が、来たんだ。', en: "A wonderful job offer came up.", style: 'excited young man voice, soft warm eager delivery throughout' },
      { speaker: 'mei_romantic', jp: 'すごい!でも、不安そうに思えるよ。', en: "Amazing! But you seem a bit anxious.", style: 'soft warm woman voice, gentle perceptive delivery throughout' },
      { speaker: 'ren_uni', jp: '新しい環境が、恐れもあるんだ。', en: "A new environment brings some fear too.", style: 'honest young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '恐れは、自然なことだよ。', en: "Fear is a natural thing.", style: 'gentle woman voice, soft warm caring delivery throughout' },
      { speaker: 'ren_uni', jp: 'ストレスも、少しあるけどね。', en: "There's a little stress too.", style: 'reflective young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: 'あなたなら、すばらしくやれると思えるよ。', en: "I feel you can do wonderfully.", style: 'warm woman voice, soft warm encouraging delivery throughout' },
      { speaker: 'ren_uni', jp: 'よし、早速、返事をするよ。', en: "Alright, I'll reply right away.", style: 'resolved young man voice, soft warm delivery throughout' },
      { speaker: 'mei_romantic', jp: '恐れず、進んでいこうね。', en: "Without fear, let's move forward.", style: 'gentle woman voice, soft warm affectionate closing delivery throughout' },
    ]),

  C('conv_03040',
    'Riku tells Aoi about a wonderful match.',
    'Casual register; vocabulary (ストレス/思える/恐れ/すばらしい/早速) in natural home.',
    'cafe_quiet_chatter',
    ['ストレス', '思える', '恐れ', 'すばらしい', '早速'],
    ['riku_teen', 'aoi_barista'], 'Medium (7-12)',
    [
      { speaker: 'riku_teen', jp: '昨日の試合、すばらしかったんだ!', en: "Yesterday's match was wonderful!", style: 'excited teen boy voice, bright warm eager delivery throughout' },
      { speaker: 'aoi_barista', jp: 'いいね!緊張は、しなかったの?', en: "Nice! Weren't you nervous?", style: 'bright barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: '最初は、負ける恐れもあったよ。', en: "At first, there was a fear of losing.", style: 'honest teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'プレッシャーで、ストレスだったでしょ?', en: "The pressure must've been stressful.", style: 'sympathetic barista voice, soft warm cheerful delivery throughout' },
      { speaker: 'riku_teen', jp: 'でも、やれると思えたんだ。', en: "But I felt I could do it.", style: 'confident teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: 'その自信、すばらしいね!', en: "That confidence is wonderful!", style: 'cheerful barista voice, soft warm delivery throughout' },
      { speaker: 'riku_teen', jp: '勝った後、早速みんなで喜んだよ。', en: "After winning, we celebrated right away.", style: 'happy teen boy voice, bright warm delivery throughout' },
      { speaker: 'aoi_barista', jp: '恐れを越えた君、かっこいいよ!', en: "You who overcame fear are cool!", style: 'bubbly barista voice, soft warm cheerful closing delivery throughout' },
    ]),
];

for (const conv of CONVERSATIONS) {
  fs.writeFileSync(path.join(OUT_DIR, `${conv.id}.json`), JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_152 wrote', CONVERSATIONS.length, 'files');
