import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_111)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_02201',
    context: 'Daichi takes Sho-young to an Italian restaurant for first time.',
    purpose: 'Father introducing child to foreign cuisine.',
    ambient: 'restaurant_warm_low',
    sound_effects: [],
    target_vocab: ['パスタ', '初めて', '注文', '味', '油', '皮', '濃い', '美味しい'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '翔、パスタ、初めてやな!', en: "Sho — pasta, first time!", style: 'warm Kansai father voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'うわ、長い麺、面白い!', en: "Whoa — long noodle, fun!", style: 'thrilled child boy voice, bright warm awed delivery carefully' },
      { speaker: 'daichi_kansai', jp: '油、ようけついてる、濃い味や。', en: "Oil — much on, dense flavor.", style: 'soft Kansai father voice, warm warm informative delivery carefully' },
      { speaker: 'sho_child', jp: '皮みたいなチーズ、おいしい!', en: "Skin-like cheese — tasty!", style: 'eager child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'こうやって、いろんな味、覚えるんやな。', en: "Like this — various taste, learn.", style: 'tender Kansai father voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'お母さんにも、教える!', en: "Mom too — teach!", style: 'soft proud child boy voice, warm warm cheerful delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'ええ子や、また来ような。', en: "Fine kid — come again.", style: 'tender Kansai father voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02202',
    context: 'Aoi serves a customer who orders soba; brief shop talk.',
    purpose: 'Cafe owner serving customer professionally.',
    ambient: 'cafe_lunch_low',
    sound_effects: [],
    target_vocab: ['蕎麦', '注文', '料理', '味', '配り', '丁寧', '渡し', '感謝'],
    cast: ['aoi_barista', 'ren_uni'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'ren_uni', jp: '蒼さん、蕎麦、ありますか?', en: "Aoi — soba, exists?", style: 'soft young man voice, warm warm polite delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、注文受け付けます。', en: "Yes — order accept.", style: 'composed adult woman voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '料理、味、いつもうまい。', en: "Food — taste, always tasty.", style: 'warm young man voice, soft warm appreciative delivery carefully' },
      { speaker: 'aoi_barista', jp: '丁寧に、配ってお出ししますね。', en: "Carefully — distribute serve.", style: 'tender adult woman voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '渡してください、お皿に。', en: "Hand — plate to.", style: 'soft young man voice, warm warm polite delivery carefully' },
      { speaker: 'aoi_barista', jp: 'はい、お待たせしました。', en: "Yes — kept waiting.", style: 'warm adult woman voice, soft warm courteous delivery carefully' },
      { speaker: 'ren_uni', jp: '感謝します、ありがとうございます。', en: "Grateful — thanks.", style: 'humble young man voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02203',
    context: 'Hina-young helps Hiroshi-elder with online registration.',
    purpose: 'Teen helping grandfather with tech form.',
    ambient: 'living_room_lamp_low',
    sound_effects: [],
    target_vocab: ['登録', '名前', '住所', '入力', '欠か', '画面', '丁寧', '焼い'],
    cast: ['hina_child', 'hiroshi_elder'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おじいちゃん、登録の名前、ここね。', en: "Grandpa — registration name, here.", style: 'gentle teen girl voice, soft warm helpful delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'おう、住所、いるの?', en: "Yeah — address, need?", style: 'slow elder Kansai voice, warm warm engaged delivery carefully' },
      { speaker: 'hina_child', jp: '欠かしてしまった、書き直そう。', en: "Skipped — rewrite.", style: 'soft attentive teen girl voice, warm warm honest delivery carefully' },
      { speaker: 'hiroshi_elder', jp: '画面、ようけ細かいなぁ。', en: "Screen — much detailed.", style: 'gentle elder Kansai voice, soft warm puzzled delivery carefully' },
      { speaker: 'hina_child', jp: '丁寧に、入力できたよ。', en: "Carefully — could input.", style: 'soft helpful teen girl voice, warm warm proud delivery carefully' },
      { speaker: 'hiroshi_elder', jp: 'お前、頼もしい、ほんま。', en: "You — reliable, truly.", style: 'tender elder Kansai voice, soft warm proud delivery carefully' },
      { speaker: 'hina_child', jp: '今度、ケーキ、焼いたら、お祝い!', en: "Next — cake, baking, celebrate!", style: 'bright teen girl voice, soft warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02204',
    context: 'Sakura researches Japanese political parties; reads articles.',
    purpose: 'Writer studying civic structure.',
    ambient: 'study_lamp_evening',
    sound_effects: [],
    target_vocab: ['野党', '政府', '主張', '対応', '議論', '関連', '報道', '取材'],
    cast: ['sakura_teen', 'ren_uni'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '蓮くん、野党の主張、複雑ね。', en: "Ren — opposition argument, complex.", style: 'thoughtful adult writer voice, soft warm engaged delivery carefully' },
      { speaker: 'ren_uni', jp: '政府の対応、どうなるんでしょうか。', en: "Government response — how become?", style: 'soft young man voice, warm warm curious delivery carefully' },
      { speaker: 'sakura_teen', jp: '関連の議論、報道、追わないと。', en: "Related debate — report, must follow.", style: 'composed adult writer voice, soft warm professional delivery carefully' },
      { speaker: 'ren_uni', jp: '取材、深く、進められるといいですね。', en: "Coverage — deeply, advance hope.", style: 'gentle young man voice, soft warm hopeful delivery carefully' },
      { speaker: 'sakura_teen', jp: 'うん、若い世代の声、ようけ届けたい。', en: "Yeah — young gen voice, much want convey.", style: 'soft committed adult writer voice, warm earnest delivery carefully' },
      { speaker: 'ren_uni', jp: '一緒に、追っていきましょう。', en: "Together — follow.", style: 'warm young man voice, soft warm united delivery carefully' },
      { speaker: 'sakura_teen', jp: 'はい、よろしくお願いします。', en: "Yes — thank you.", style: 'humble adult writer voice, soft warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_02205',
    context: 'Mei looks for kitchen supplies; asks Daichi about a missing item.',
    purpose: 'Married couple in domestic search.',
    ambient: 'kitchen_morning_low',
    sound_effects: [],
    target_vocab: ['移し', '片付け', 'やめる', 'ベルト', '見つける', '置き', '回し', '達する'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、棚、移したよね、先週?', en: "Daichi — shelf, moved, last week?", style: 'soft young wife voice, warm warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'おう、片付けたわ、整理して。', en: "Yeah — cleaned, organized.", style: 'warm Kansai husband voice, soft warm content delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ベルト、どこに置いた?', en: "Belt — where placed?", style: 'curious young wife voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'やめる前に、新しいのを買おう。', en: "Quit before — new buy.", style: 'gentle Kansai husband voice, soft warm practical delivery carefully' },
      { speaker: 'mei_romantic', jp: '回して見たら、見つけるかも。', en: "Turn look — find maybe.", style: 'soft young woman voice, warm warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お互い、達するまで、頑張ろう!', en: "Each — until reach, try!", style: 'animated Kansai husband voice, bright warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: 'ふふ、絶対、見つけるから!', en: "Heh — definitely, find!", style: 'bright young wife voice, soft warm decisive delivery carefully' },
    ],
  },
  {
    id: 'conv_02206',
    context: 'Naoko discusses how a bride to be plans her wedding dress.',
    purpose: 'Aunt helping younger woman plan special event.',
    ambient: 'ramen_shop_afternoon',
    sound_effects: [],
    target_vocab: ['嫁', '洋服', 'ドレス', '名刺', '丁寧', '隠さ', '挨拶', '心'],
    cast: ['naoko_aunt', 'mei_romantic'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'naoko_aunt', jp: 'メイ、嫁入り前、ドレス選び?', en: "Mei — pre-marriage, dress choose?", style: 'animated Kansai aunt voice, bright warm engaged delivery carefully' },
      { speaker: 'mei_romantic', jp: 'はい、洋服も、考えています。', en: "Yes — Western clothes too, thinking.", style: 'soft young woman voice, warm warm content delivery carefully' },
      { speaker: 'naoko_aunt', jp: '名刺渡しの挨拶、隠さん方がええ。', en: "Card-hand greeting — don't hide.", style: 'firm Kansai aunt voice, soft warm wise delivery carefully' },
      { speaker: 'mei_romantic', jp: '丁寧に、皆さん挨拶したいです。', en: "Carefully — all greet want.", style: 'tender young woman voice, soft warm respectful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '心、ようけ伝えるんやで!', en: "Heart — much convey!", style: 'warm Kansai aunt voice, soft warm passionate delivery carefully' },
      { speaker: 'mei_romantic', jp: 'おばさん、励みになります。', en: "Auntie — encouragement.", style: 'humble young woman voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'ふふ、家族や、いつでも。', en: "Heh — family, anytime.", style: 'tender Kansai aunt voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02207',
    context: 'Saito treats a child for an ear infection; quiet exam.',
    purpose: 'Doctor caring for sick child gently.',
    ambient: 'clinic_room_quiet',
    sound_effects: [],
    target_vocab: ['治療', '症状', '耳', '熱い', '休む', '心配', '安心', '優しい'],
    cast: ['saito_doctor', 'sho_child'],
    frequency_tier: 3,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'saito_doctor', jp: '翔くん、耳の症状、見せてね。', en: "Sho — ear symptom, show.", style: 'soft doctor voice, warm warm gentle delivery carefully' },
      { speaker: 'sho_child', jp: '先生、熱い感じ、する。', en: "Doctor — hot feel, exists.", style: 'tearful child boy voice, soft warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '心配いりません、優しい薬、出します。', en: "No worry — gentle medicine, give.", style: 'tender doctor voice, soft warm reassuring delivery carefully' },
      { speaker: 'sho_child', jp: '治療、いつまで?', en: "Treatment — until when?", style: 'soft worried child boy voice, warm honest delivery carefully' },
      { speaker: 'saito_doctor', jp: '一週間、ようけ休んでね。', en: "One week — well rest.", style: 'gentle doctor voice, soft warm caring delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、安心した、ありがとう!', en: "Yeah — relieved, thanks!", style: 'soft tender child boy voice, warm warm grateful delivery carefully' },
      { speaker: 'saito_doctor', jp: '元気になって、また会おうな。', en: "Get well — meet again.", style: 'warm doctor voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02208',
    context: 'Kenji explores a Buddhist temple festival with Aoi.',
    purpose: 'Couple exploring traditional event.',
    ambient: 'temple_festival_warm',
    sound_effects: [],
    target_vocab: ['仏教', '畳', '尽くし', '気軽', '夢中', '輝い', '雰囲気', '深い'],
    cast: ['kenji_office', 'aoi_barista'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '蒼、仏教のお寺、雰囲気深いなぁ。', en: "Aoi — Buddhist temple, deep mood.", style: 'soft Kansai husband voice, warm warm reverent delivery carefully' },
      { speaker: 'aoi_barista', jp: '畳の上、皆、尽くしてお参り。', en: "Tatami on — all, devote pray.", style: 'tender adult woman voice, soft warm reverent delivery carefully' },
      { speaker: 'kenji_office', jp: '気軽に、入ってええんかな?', en: "Casually — enter fine?", style: 'gentle Kansai husband voice, soft warm cautious delivery carefully' },
      { speaker: 'aoi_barista', jp: 'うん、皆、夢中になってる。', en: "Yeah — all, absorbed.", style: 'composed adult woman voice, soft warm observant delivery carefully' },
      { speaker: 'kenji_office', jp: '提灯、輝いとるな、綺麗。', en: "Lantern — shining, pretty.", style: 'warm Kansai man voice, soft warm awed delivery carefully' },
      { speaker: 'aoi_barista', jp: 'こうやって、伝統、感じる時間。', en: "Like this — tradition, feel time.", style: 'tender adult woman voice, soft warm philosophical delivery carefully' },
      { speaker: 'kenji_office', jp: 'お前と来れて、ええわ。', en: "With you came — fine.", style: 'soft Kansai husband voice, warm warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02209',
    context: 'Yuki-office attends a community workshop; chats with Sakura.',
    purpose: 'Two adults learning about new skills.',
    ambient: 'workshop_classroom_low',
    sound_effects: [],
    target_vocab: ['ワークショップ', '熱心', '構え', '気楽', '関わり', '結局', '取り組み', '本格'],
    cast: ['yuki_office', 'sakura_teen'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yuki_office', jp: 'さくらさん、ワークショップ、面白いですね。', en: "Sakura — workshop, fun.", style: 'composed office woman voice, soft warm engaged delivery carefully' },
      { speaker: 'sakura_teen', jp: '熱心な参加者、ようけいますね。', en: "Passionate participants — much exist.", style: 'soft adult writer voice, warm warm appreciative delivery carefully' },
      { speaker: 'yuki_office', jp: '気楽に、構えず、参加できる。', en: "Casually — without guard, participate.", style: 'warm office woman voice, soft warm content delivery carefully' },
      { speaker: 'sakura_teen', jp: '本格的な取り組み、皆さん、ようけ持ってますね。', en: "Authentic effort — all, much hold.", style: 'tender adult writer voice, soft warm impressed delivery carefully' },
      { speaker: 'yuki_office', jp: '結局、こういう関わり、大事。', en: "After all — like this involvement, matters.", style: 'gentle office woman voice, soft warm philosophical delivery carefully' },
      { speaker: 'sakura_teen', jp: 'こうやって、新しい繋がり、生まれるね。', en: "Like this — new bond, born.", style: 'soft adult writer voice, warm warm content delivery carefully' },
      { speaker: 'yuki_office', jp: 'ありがとう、心強い時間。', en: "Thanks — encouraging time.", style: 'tender office woman voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02210',
    context: 'Tatsuya-country recommends an old-school folk song to Sho-young.',
    purpose: 'Elder sharing musical tradition with child.',
    ambient: 'porch_evening_breeze',
    sound_effects: [],
    target_vocab: ['歌', '昔', '農薬', '生え', '草', '田んぼ', '懐かしい', '心'],
    cast: ['tatsuya_country', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'tatsuya_country', jp: '翔、昔の歌、教えたるな。', en: "Sho — old song, teach.", style: 'slow Tohoku farmer voice, warm warm fond delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、おじいちゃん、どんな歌?', en: "Yeah — grandpa, what song?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: '田んぼで草、生えてる頃、歌っとった。', en: "Paddy grass — grew time, sang.", style: 'gentle Tohoku voice, soft warm reminiscent delivery carefully' },
      { speaker: 'sho_child', jp: '農薬、ない頃、自然がいっぱい?', en: "No agrichemicals — nature full?", style: 'thoughtful child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'tatsuya_country', jp: 'おう、心、こめて歌うた。', en: "Yeah — heart, put sang.", style: 'tender Tohoku farmer voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '懐かしい時代やな、おじいちゃんの。', en: "Nostalgic era — grandpa's.", style: 'soft tender child boy voice, warm warm reverent delivery carefully' },
      { speaker: 'tatsuya_country', jp: '一緒に、歌ってみよか。', en: "Together — sing?", style: 'warm Tohoku voice, soft warm inviting delivery carefully' },
    ],
  },
  {
    id: 'conv_02211',
    context: 'Riku-teen helps Sho-young assemble a model airplane.',
    purpose: 'Older teen patiently helping younger child craft.',
    ambient: 'living_room_table_lamp',
    sound_effects: [],
    target_vocab: ['組み立て', '丁寧', '完成', '飛行', '指', '位置', '足元', '丁度'],
    cast: ['riku_teen', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: '陸くん、組み立て、難しい!', en: "Riku — assemble, hard!", style: 'frustrated child boy voice, soft warm honest delivery carefully' },
      { speaker: 'riku_teen', jp: '丁寧に、指、置いてな。', en: "Carefully — finger, place.", style: 'soft teen boy voice, warm warm patient delivery carefully' },
      { speaker: 'sho_child', jp: '丁度、この位置で合うかな?', en: "Just — this position fit?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'riku_teen', jp: 'うん、足元、しっかり持って。', en: "Yeah — feet, firmly hold.", style: 'gentle teen boy voice, soft warm helpful delivery carefully' },
      { speaker: 'sho_child', jp: '完成したら、飛行できる?', en: "Done — fly can?", style: 'eager child boy voice, bright warm hopeful delivery carefully' },
      { speaker: 'riku_teen', jp: 'ええ模型や、ちゃんと飛ぶで!', en: "Fine model — properly fly!", style: 'bright teen boy voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: 'やった、頑張ってよかった!', en: "Yay — tried good!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
    ],
  },
  {
    id: 'conv_02212',
    context: 'Hina-young tries on her grandmother\'s old kimono; emotional.',
    purpose: 'Teen wearing meaningful heirloom.',
    ambient: 'tatami_lamp_quiet',
    sound_effects: [],
    target_vocab: ['着物', '帯', '輝い', '夢中', '丁寧', '時計', '巨大', '昔'],
    cast: ['hina_child', 'yumiko_mom'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'おばあちゃん、着物、ようけ綺麗!', en: "Grandma — kimono, much pretty!", style: 'awed teen girl voice, bright warm reverent delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'ふふ、帯、丁寧に結ぼうね。', en: "Heh — sash, carefully tie.", style: 'tender older mother voice, soft warm fond delivery carefully' },
      { speaker: 'hina_child', jp: '輝いてる、模様、すごい!', en: "Shining — pattern, amazing!", style: 'thrilled teen girl voice, bright warm awed delivery carefully' },
      { speaker: 'yumiko_mom', jp: '昔、時計みたいに、永遠に思えた。', en: "Past — clock-like, eternal thought.", style: 'soft older mother voice, warm warm reflective delivery carefully' },
      { speaker: 'hina_child', jp: '夢中、なってる、私!', en: "Absorbed — becoming, me!", style: 'soft teen girl voice, warm warm content delivery carefully' },
      { speaker: 'yumiko_mom', jp: '巨大な思い出、お前に渡す。', en: "Huge memory — to you give.", style: 'tender older mother voice, soft warm enduring delivery carefully' },
      { speaker: 'hina_child', jp: 'ありがとう、大切に、します。', en: "Thanks — cherish, do.", style: 'soft committed teen girl voice, warm warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02213',
    context: 'Aoi visits a small mochi store; chats with the elderly shopkeeper.',
    purpose: 'Customer-shopkeeper warm exchange.',
    ambient: 'shop_low_traditional',
    sound_effects: [],
    target_vocab: ['粉', '撮り', '達する', '飾っ', '通い', '効い', '差し', '済ん'],
    cast: ['aoi_barista', 'sachiko_grandma'],
    frequency_tier: 6,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'aoi_barista', jp: 'おばあちゃん、お元気ですか?', en: "Grandma — well?", style: 'soft adult woman voice, warm warm polite delivery carefully' },
      { speaker: 'sachiko_grandma', jp: 'おう、いつも通いに来てくれて。', en: "Yeah — always coming.", style: 'gentle grandmother voice, soft warm fond delivery carefully' },
      { speaker: 'aoi_barista', jp: '粉、丁寧に、ようけ用意されてますね。', en: "Flour — carefully, much prepared.", style: 'warm adult woman voice, soft warm appreciative delivery carefully' },
      { speaker: 'sachiko_grandma', jp: '効いてくれて、嬉しいわ。', en: "Effective — happy.", style: 'tender grandmother voice, soft warm grateful delivery carefully' },
      { speaker: 'aoi_barista', jp: '写真、ちょっと撮ってもいいですか?', en: "Photo — slightly take okay?", style: 'composed adult woman voice, soft warm polite delivery carefully' },
      { speaker: 'sachiko_grandma', jp: 'もちろん、店、達するまで飾ってる。', en: "Of course — shop, reach until decorating.", style: 'soft grandmother voice, warm warm proud delivery carefully' },
      { speaker: 'aoi_barista', jp: '済んだら、お送りしますね。', en: "Done — send.", style: 'gentle adult woman voice, soft warm respectful delivery carefully' },
    ],
  },
  {
    id: 'conv_02214',
    context: 'Sho-young learns about his father\'s old marathon experience.',
    purpose: 'Father telling son about athletic achievement.',
    ambient: 'porch_evening_quiet',
    sound_effects: [],
    target_vocab: ['マラソン', '達する', '効い', '一行', '抑える', '熱い', '長年', '訓練'],
    cast: ['daichi_kansai', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sho_child', jp: 'お父さん、マラソン、いつしたん?', en: "Dad — marathon, when did?", style: 'curious child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '長年訓練して、ゴール達した時、嬉しかった。', en: "Long-year trained — goal reached, happy.", style: 'soft Kansai father voice, warm warm reminiscent delivery carefully' },
      { speaker: 'sho_child', jp: '熱い気持ち、抑えるの大変?', en: "Passionate feeling — hold hard?", style: 'thoughtful child boy voice, soft warm engaged delivery carefully' },
      { speaker: 'daichi_kansai', jp: '効いた、毎日の練習。', en: "Effective — daily practice.", style: 'gentle Kansai father voice, soft warm proud delivery carefully' },
      { speaker: 'sho_child', jp: '一行で説明できる、すごい!', en: "One line explain — amazing!", style: 'awed child boy voice, bright warm admiring delivery carefully' },
      { speaker: 'daichi_kansai', jp: 'お前も、いつか挑戦してみ。', en: "You too — someday try.", style: 'tender Kansai father voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: 'うん、必ず!', en: "Yeah — surely!", style: 'soft determined child boy voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02215',
    context: 'Sakura interviews a former politician about reform efforts.',
    purpose: 'Writer formal interview with public figure.',
    ambient: 'office_quiet_warm',
    sound_effects: [],
    target_vocab: ['野党', '改革', '対応', '主張', '時代', '関わり', '尽くし', '深い'],
    cast: ['sakura_teen', 'hiroshi_boss'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'sakura_teen', jp: '社長、野党時代の改革、伺います。', en: "Boss — opposition era reform, ask.", style: 'composed adult writer voice, soft warm professional delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '主張、深く、社会に訴えました。', en: "Argument — deeply, society appealed.", style: 'measured boss voice, soft warm professional delivery carefully' },
      { speaker: 'sakura_teen', jp: '対応、どんな関わり方を?', en: "Response — what involvement?", style: 'soft adult writer voice, warm warm probing delivery carefully' },
      { speaker: 'hiroshi_boss', jp: '尽くして、皆と話し合った時代やった。', en: "Devoted — all talked era.", style: 'soft boss voice, warm warm reverent delivery carefully' },
      { speaker: 'sakura_teen', jp: '今でも、思い深いですか?', en: "Even now — deep thought?", style: 'gentle adult writer voice, soft warm respectful delivery carefully' },
      { speaker: 'hiroshi_boss', jp: 'おう、心に残る経験や。', en: "Yeah — heart-remaining experience.", style: 'tender boss voice, soft warm fond delivery carefully' },
      { speaker: 'sakura_teen', jp: '貴重なお話、感謝します。', en: "Precious words — gratitude.", style: 'humble adult writer voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02216',
    context: 'Mei prepares for an interview; nervously practices with Daichi.',
    purpose: 'Wife rehearsing professional interview at home.',
    ambient: 'living_room_lamp_quiet',
    sound_effects: [],
    target_vocab: ['面接', 'プレッシャー', '気楽', '名刺', '構え', 'ふつう', '応援', '助ける'],
    cast: ['mei_romantic', 'daichi_kansai'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'mei_romantic', jp: '大ちゃん、面接、プレッシャー!', en: "Daichi — interview, pressure!", style: 'nervous young wife voice, soft warm honest delivery carefully' },
      { speaker: 'daichi_kansai', jp: '気楽に、ふつうの感じで行こうな。', en: "Casually — normal feel go.", style: 'warm Kansai husband voice, soft warm reassuring delivery carefully' },
      { speaker: 'mei_romantic', jp: '名刺、忘れずに、持っていく。', en: "Card — without forgetting, take.", style: 'composed young woman voice, soft warm focused delivery carefully' },
      { speaker: 'daichi_kansai', jp: '構えすぎたら、損や、お前らしく。', en: "Over-prepare — loss, you-like.", style: 'gentle Kansai husband voice, soft warm wise delivery carefully' },
      { speaker: 'mei_romantic', jp: '応援、ようけ感じる、ありがとう。', en: "Cheer — much feel, thanks.", style: 'tender young wife voice, soft warm grateful delivery carefully' },
      { speaker: 'daichi_kansai', jp: '心、助けるで、いつでも。', en: "Heart — help, anytime.", style: 'tender Kansai husband voice, soft warm steadfast delivery carefully' },
      { speaker: 'mei_romantic', jp: '頑張ってくる!', en: "Try!", style: 'soft determined young wife voice, warm earnest delivery carefully' },
    ],
  },
  {
    id: 'conv_02217',
    context: 'Kenji takes Sho-young to an old-school arcade; observation.',
    purpose: 'Mentor and child sharing nostalgic outing.',
    ambient: 'arcade_low_beep',
    sound_effects: [],
    target_vocab: ['この間', '気楽', '夢中', '尽くし', '熱心', '盛り上がり', '楽しい', '同級生'],
    cast: ['kenji_office', 'sho_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'kenji_office', jp: '翔、この間来た時、楽しかったやろ?', en: "Sho — last came, fun?", style: 'warm Kansai man voice, soft warm fond delivery carefully' },
      { speaker: 'sho_child', jp: '夢中になっちゃう、楽しい!', en: "Get absorbed — fun!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'kenji_office', jp: '気楽に、ようけ遊んでいきや。', en: "Casually — much play.", style: 'gentle Kansai man voice, soft warm encouraging delivery carefully' },
      { speaker: 'sho_child', jp: '熱心、皆さん、ようけやってますね!', en: "Passionately — all, much doing!", style: 'observant child boy voice, soft warm impressed delivery carefully' },
      { speaker: 'kenji_office', jp: '盛り上がり、ええ場所やな。', en: "Excitement — fine place.", style: 'tender Kansai man voice, soft warm content delivery carefully' },
      { speaker: 'sho_child', jp: '同級生、誘ってもいい?', en: "Classmate — invite okay?", style: 'eager child boy voice, bright warm engaged delivery carefully' },
      { speaker: 'kenji_office', jp: 'おう、尽くしてくれる、ええ友達連れて来や!', en: "Yeah — devoting, fine friends bring!", style: 'warm Kansai mentor voice, soft warm fond delivery carefully' },
    ],
  },
  {
    id: 'conv_02218',
    context: 'Yumiko helps prepare for a wedding; teaches Mei traditional etiquette.',
    purpose: 'Elder woman teaching young wife formal customs.',
    ambient: 'tatami_morning_quiet',
    sound_effects: [],
    target_vocab: ['結婚式', '挨拶', '振舞', '丁寧', '伝統', '振り返っ', '感謝', '尽くし'],
    cast: ['yumiko_mom', 'mei_romantic'],
    frequency_tier: 4,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'yumiko_mom', jp: 'メイ、結婚式の挨拶、覚えてね。', en: "Mei — wedding greeting, remember.", style: 'gentle older mother voice, soft warm teaching delivery carefully' },
      { speaker: 'mei_romantic', jp: 'はい、丁寧に、伝統、守りたいです。', en: "Yes — carefully, tradition, want protect.", style: 'humble young woman voice, soft warm respectful delivery carefully' },
      { speaker: 'yumiko_mom', jp: '振舞、皆さんに、感謝の気持ち、伝えるの。', en: "Manner — all, gratitude, convey.", style: 'tender older mother voice, soft warm philosophical delivery carefully' },
      { speaker: 'mei_romantic', jp: '昔の私を、振り返っても、未熟でした。', en: "Past me — looking back, immature.", style: 'soft young woman voice, warm warm reflective delivery carefully' },
      { speaker: 'yumiko_mom', jp: '今は、立派になったわ。', en: "Now — splendid become.", style: 'warm older mother voice, soft warm proud delivery carefully' },
      { speaker: 'mei_romantic', jp: '皆さんに、尽くしたい、心から。', en: "All — want devote, heart.", style: 'tender young woman voice, soft warm earnest delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'お前なら、絶対、できるわよ。', en: "You — definitely, can.", style: 'tender older mother voice, soft warm encouraging delivery carefully' },
    ],
  },
  {
    id: 'conv_02219',
    context: 'Hina-young learns about basic finance from Yuki-office casually.',
    purpose: 'Adult mentoring teen on practical money.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['投資', '貯金', '小遣い', '計算', '今後', '将来', '管理', '預金'],
    cast: ['yuki_office', 'hina_child'],
    frequency_tier: 5,
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'hina_child', jp: 'ゆきさん、小遣い、貯金、できるかな?', en: "Yuki — allowance, save, can?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: '計算しながら、管理する習慣、大事。', en: "Calculating — manage habit, matters.", style: 'composed office woman voice, soft warm professional delivery carefully' },
      { speaker: 'hina_child', jp: '将来のため、預金、はじめたい。', en: "Future for — savings, want start.", style: 'soft committed teen girl voice, warm earnest delivery carefully' },
      { speaker: 'yuki_office', jp: '少しずつ、今後も、続けてね。', en: "Bit by bit — going forward, continue.", style: 'gentle office woman voice, soft warm encouraging delivery carefully' },
      { speaker: 'hina_child', jp: '投資って、どんなもの?', en: "Investment — what?", style: 'curious teen girl voice, soft warm engaged delivery carefully' },
      { speaker: 'yuki_office', jp: 'ちょっと難しいけど、慎重に、勉強しよう。', en: "Slightly hard — carefully, study.", style: 'warm office woman voice, soft warm cautious delivery carefully' },
      { speaker: 'hina_child', jp: '頑張る、ありがとう!', en: "Try — thanks!", style: 'bright teen girl voice, soft warm grateful delivery carefully' },
    ],
  },
  {
    id: 'conv_02220',
    context: 'Whole group hosts a small picnic; reflecting on the year past.',
    purpose: 'Multi-voice end-of-year nature gathering.',
    ambient: 'park_picnic_breeze',
    sound_effects: [],
    target_vocab: ['楽しい', '夢中', '気楽', '感謝', '皆', '心', '繋がる', '愛情'],
    cast: ['daichi_kansai', 'mei_romantic', 'sho_child', 'hina_child', 'yumiko_mom', 'naoko_aunt'],
    frequency_tier: 3,
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'daichi_kansai', jp: '皆、ようけピクニックに来てくれた!', en: "All — much picnic came!", style: 'warm Kansai husband voice, soft warm cheerful delivery carefully' },
      { speaker: 'mei_romantic', jp: '気楽に、過ごせて、楽しい時間。', en: "Casually — spend, fun time.", style: 'tender young mother voice, soft warm content delivery carefully' },
      { speaker: 'sho_child', jp: 'お弁当、夢中になって食べた!', en: "Bento — absorbed eaten!", style: 'thrilled child boy voice, bright warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: '皆と、こんな日、毎月したい!', en: "All — day like this, monthly want!", style: 'bright teen girl voice, soft warm eager delivery carefully' },
      { speaker: 'yumiko_mom', jp: '感謝の気持ち、ようけあります。', en: "Gratitude — much exists.", style: 'tender older mother voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: '心、繋がる時間、これや!', en: "Heart — connecting time, this!", style: 'animated Kansai aunt voice, bright warm delighted delivery carefully' },
      { speaker: 'daichi_kansai', jp: '愛情、ようけ感じる、本当に。', en: "Love — much feel, truly.", style: 'warm Kansai husband voice, soft warm tender delivery carefully' },
      { speaker: 'mei_romantic', jp: '家族で、こうやって、過ごせるの、宝物。', en: "Family — like this, spending, treasure.", style: 'tender young mother voice, soft warm grateful delivery carefully' },
      { speaker: 'sho_child', jp: '皆、大好き!', en: "All — love!", style: 'bright child boy voice, soft warm cheerful delivery carefully' },
      { speaker: 'hina_child', jp: 'こういう日、ずっと、続けてほしい。', en: "Day like this — always, want continue.", style: 'tender teen girl voice, soft warm fond delivery carefully' },
      { speaker: 'yumiko_mom', jp: 'おばあちゃんも、嬉しい!', en: "Grandma too — happy!", style: 'tearful older mother voice, soft warm grateful delivery carefully' },
      { speaker: 'naoko_aunt', jp: 'これからも、皆で、繋がろう!', en: "Going forward — all, connect!", style: 'brassy Kansai aunt voice, bright warm committed delivery carefully' },
      { speaker: 'daichi_kansai', jp: '乾杯やな!', en: "Toast!", style: 'cheerful Kansai husband voice, bright warm cheerful delivery carefully' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_111 wrote', CONVERSATIONS.length, 'files');
