import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'data', 'conversations');
const NOW = new Date().toISOString();
const META = () => ({ generated_by: 'claude-opus-4-7 (batch_073)', generated_at: NOW, source_plan_row: '' });

const CONVERSATIONS = [
  {
    id: 'conv_01446',
    context: 'A weekend cooking class. Sakura tries grilling fish for the first time while Hina watches the technique.',
    purpose: 'Casual learning, encouragement around acquiring a new domestic skill.',
    ambient: 'kitchen_sizzle_low',
    sound_effects: [],
    target_vocab: ['焼き', '好み', '確か', '味'],
    cast: ['Sakura', 'Hina'],
    frequency_tier: 'High',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Sakura', jp: '魚の焼き方、確かに難しいね。', en: "Grilling fish is definitely tricky.", style: 'thoughtful adult woman, soft sigh of concentration' },
      { speaker: 'Hina', jp: 'うん、皮がきれいに焼けると嬉しい。', en: "Yeah, it's a joy when the skin grills up nicely.", style: 'bright teen girl, encouraging warm tone' },
      { speaker: 'Sakura', jp: 'ひなちゃんの好みは塩?それとも醤油?', en: "What's your preference, Hina — salt or soy?", style: 'curious gentle adult voice, soft questioning lilt' },
      { speaker: 'Hina', jp: '私は塩派。素材の味が分かるから。', en: "I'm team salt — you can taste the fish itself.", style: 'cheerful teen, confident food opinion' },
      { speaker: 'Sakura', jp: 'なるほど、確かにそうだね。', en: "Ah, that makes sense.", style: 'agreeable adult woman, gentle realization' },
      { speaker: 'Hina', jp: '焼き加減は中火がいいよ。', en: "Medium heat works best.", style: 'helpful teen, instructional and warm' },
      { speaker: 'Sakura', jp: 'うん、覚えとくね。ありがとう。', en: "Got it — I'll remember. Thanks.", style: 'grateful adult woman, soft smile in voice' },
    ],
  },
  {
    id: 'conv_01447',
    context: 'Daichi takes Sho to a small neighborhood baseball tournament Sho is competing in.',
    purpose: 'Father-son sport encouragement; pre-game nerves and reassurance.',
    ambient: 'park_distant_chatter',
    sound_effects: [],
    target_vocab: ['大会', '選手', 'ボール', '緊張'],
    cast: ['Daichi', 'Sho'],
    frequency_tier: 'High',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Sho', jp: '大会、ちょっと緊張するな。', en: "I'm a bit nervous about the tournament.", style: 'young teen boy, honest tremor under bravado' },
      { speaker: 'Daichi', jp: '当然や。選手なら誰でもそうやで。', en: "Of course. Every player feels that way.", style: 'Kansai dad voice, grounding and warm' },
      { speaker: 'Sho', jp: 'ボールがちゃんと見えるかな。', en: "I hope I can see the ball okay.", style: 'anxious teen boy, slight uncertainty' },
      { speaker: 'Daichi', jp: '深呼吸して、肩の力抜きや。', en: "Take a deep breath, drop your shoulders.", style: 'calm Kansai father, steady and kind' },
      { speaker: 'Sho', jp: 'うん、やってみる。', en: "Okay, I'll try.", style: 'softer teen voice, gathering himself' },
      { speaker: 'Daichi', jp: '勝っても負けても、楽しんでこい。', en: "Win or lose, just enjoy yourself.", style: 'warm Kansai dad, supportive grin in voice' },
      { speaker: 'Sho', jp: 'ありがとう、行ってくる!', en: "Thanks — here I go!", style: 'energetic teen boy, courage rising' },
    ],
  },
  {
    id: 'conv_01448',
    context: 'Mei and her little daughter Hikari leaving for school early on a cool morning.',
    purpose: 'Quiet morning departure; tying shoelaces and saying goodbye.',
    ambient: 'genkan_quiet_morning',
    sound_effects: [],
    target_vocab: ['早め', '自転車', '靴'],
    cast: ['Mei', 'Hikari'],
    frequency_tier: 'High',
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'Mei', jp: '今日は早めに出ようね。', en: "Let's head out a bit early today.", style: 'gentle young mother, soft morning voice' },
      { speaker: 'Hikari', jp: 'うん、自転車で行く?', en: "Okay — are we going by bike?", style: 'small child voice, sleepy curious' },
      { speaker: 'Mei', jp: 'そうしようか。靴ちゃんと履いてね。', en: "Let's do that. Put your shoes on properly.", style: 'warm mother voice, patient guidance' },
      { speaker: 'Hikari', jp: 'はい!', en: "Yes!", style: 'bright child, energetic compliance' },
      { speaker: 'Mei', jp: '行ってきます。気をつけて。', en: "Off we go. Be careful.", style: 'tender adult woman, careful affection' },
    ],
  },
  {
    id: 'conv_01449',
    context: 'Kenji and Ren in the small art studio working through revisions on a long manga chapter.',
    purpose: 'Creative editing dialogue; structural choices in storytelling.',
    ambient: 'studio_pen_scratch',
    sound_effects: [],
    target_vocab: ['編', '展開', '完成', '修正', '構成'],
    cast: ['Kenji', 'Ren'],
    frequency_tier: 'Medium',
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'Ren', jp: 'この編、展開が早すぎる気がする。', en: "I feel this arc moves too fast.", style: 'soft male artist voice, thoughtful critique' },
      { speaker: 'Kenji', jp: 'ほな、どこを伸ばすべきや思う?', en: "So where do you reckon we extend it?", style: 'Kansai senior artist, deliberate questioning' },
      { speaker: 'Ren', jp: '中盤の感情の部分かな。', en: "The emotional middle, I think.", style: 'analytical young man, gentle certainty' },
      { speaker: 'Kenji', jp: 'なるほど、確かにそこ薄いな。', en: "Right — yeah, that part is thin.", style: 'agreeable Kansai mentor, slow nod tone' },
      { speaker: 'Ren', jp: '修正は明日までに終わらせます。', en: "I'll finish the revisions by tomorrow.", style: 'committed adult male, professional steady' },
      { speaker: 'Kenji', jp: '無理すなや。完成度の方が大事や。', en: "Don't push too hard. Quality matters more.", style: 'caring Kansai elder voice, gentle firmness' },
      { speaker: 'Ren', jp: 'はい、構成から見直します。', en: "Yes, I'll review the structure from scratch.", style: 'respectful young artist, determined' },
      { speaker: 'Kenji', jp: 'ええ判断や。線も丁寧にな。', en: "Good call. Keep the linework careful too.", style: 'approving Kansai mentor, warm guidance' },
      { speaker: 'Ren', jp: '線の太さ、もう少し変化つけます。', en: "I'll vary the line weight a bit more.", style: 'focused young male, refining tone' },
      { speaker: 'Kenji', jp: 'うん、それで物語に深みが出るで。', en: "Yeah, that'll deepen the story.", style: 'wise Kansai voice, patient teaching' },
      { speaker: 'Ren', jp: 'ありがとうございます、頑張ります。', en: "Thank you, I'll give it my all.", style: 'humble young artist, sincere gratitude' },
      { speaker: 'Kenji', jp: 'ええ仕事しよな、ふたりで。', en: "Let's do good work, the two of us.", style: 'tender Kansai mentor, brotherly closeness' },
    ],
  },
  {
    id: 'conv_01450',
    context: 'Dr. Saito briefs nurse Yumiko on an incoming emergency patient at the hospital.',
    purpose: 'Medical professionals coordinating under pressure with calm clarity.',
    ambient: 'hospital_corridor_quiet',
    sound_effects: [],
    target_vocab: ['患者', '緊急', '血', '痛い', '対応', '注意'],
    cast: ['Saito', 'Yumiko'],
    frequency_tier: 'Medium',
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'Saito', jp: '緊急の患者さん、五分後に着きます。', en: "Emergency patient arriving in five minutes.", style: 'measured doctor voice, calm urgency' },
      { speaker: 'Yumiko', jp: '了解です。状態は?', en: "Understood. What's the condition?", style: 'composed nurse, professional alert' },
      { speaker: 'Saito', jp: '出血が多い。痛みも強いそうです。', en: "Heavy bleeding. Strong pain reported too.", style: 'clinical male voice, careful informing' },
      { speaker: 'Yumiko', jp: '輸血の準備、進めておきます。', en: "I'll prepare for transfusion right away.", style: 'efficient nurse, clipped and steady' },
      { speaker: 'Saito', jp: '助かります。血液型の確認も。', en: "That helps. Confirm blood type as well.", style: 'grateful doctor voice, focused' },
      { speaker: 'Yumiko', jp: 'はい、家族にも連絡しましょうか?', en: "Yes — should I contact the family?", style: 'thoughtful nurse, considerate prompt' },
      { speaker: 'Saito', jp: 'お願いします。落ち着いた口調で。', en: "Please. Use a calm tone.", style: 'experienced doctor, gentle reminder' },
      { speaker: 'Yumiko', jp: 'もちろんです。注意して伝えます。', en: "Of course. I'll be careful in how I tell them.", style: 'compassionate nurse, measured promise' },
      { speaker: 'Saito', jp: 'チーム全員、対応に集中してください。', en: "Whole team — focus on the response.", style: 'leading physician, authority with care' },
      { speaker: 'Yumiko', jp: '了解しました。先生、頼みます。', en: "Understood. Doctor, we're with you.", style: 'steady nurse, professional trust' },
      { speaker: 'Saito', jp: 'こちらこそ。一緒に乗り切りましょう。', en: "Likewise. Let's get through this together.", style: 'warm doctor, quiet camaraderie' },
      { speaker: 'Yumiko', jp: 'はい、必ず。', en: "Yes — without fail.", style: 'firm nurse, resolved softness' },
    ],
  },
  {
    id: 'conv_01451',
    context: 'Hiroshi and his middle-aged daughter Aoi sit on the porch looking at an old family photo album.',
    purpose: 'Quiet inter-generational reminiscence; tender memory across age.',
    ambient: 'porch_evening_cicada',
    sound_effects: [],
    target_vocab: ['古い', '古', '思い出'],
    cast: ['Hiroshi', 'Aoi'],
    frequency_tier: 'High',
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'Aoi', jp: 'この写真、ずいぶん古いね。', en: "This photo's quite old.", style: 'middle-aged daughter voice, fond wistful' },
      { speaker: 'Hiroshi', jp: 'ああ、四十年は前やな。', en: "Mm, forty years back, that.", style: 'elder Kansai grandfather, slow warm rasp' },
      { speaker: 'Aoi', jp: 'お母さん、若くて可愛い。', en: "Mom looks so young and cute.", style: 'tender adult woman, soft awe' },
      { speaker: 'Hiroshi', jp: '古い思い出やけど、昨日のようや。', en: "Old memory, but feels like yesterday.", style: 'gentle elder Kansai, soft melancholy' },
      { speaker: 'Aoi', jp: 'お父さん、よく覚えてるね。', en: "You remember it so well, Dad.", style: 'loving adult daughter, soft smile in voice' },
    ],
  },
  {
    id: 'conv_01452',
    context: 'Sho asks Hina for help with English homework at the kitchen table.',
    purpose: 'Peer study help between teens; gentle teaching dynamic.',
    ambient: 'kitchen_evening_clock',
    sound_effects: [],
    target_vocab: ['英語', '学習', '難しく', '意味'],
    cast: ['Sho', 'Hina'],
    frequency_tier: 'High',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Sho', jp: 'この英語の文、意味わからん。', en: "I don't get the meaning of this English sentence.", style: 'frustrated teen boy, honest grumble' },
      { speaker: 'Hina', jp: 'どこの部分?見せて。', en: "Which part? Show me.", style: 'helpful teen girl, calm focus' },
      { speaker: 'Sho', jp: 'ここ、急に難しくなった。', en: "This bit — it got hard out of nowhere.", style: 'puzzled teen boy, slight whine' },
      { speaker: 'Hina', jp: 'ああ、関係代名詞ね。', en: "Ah, relative pronouns.", style: 'composed teen girl, recognition' },
      { speaker: 'Sho', jp: '学習、ペース上がってきつい。', en: "The pace of study is getting brutal.", style: 'tired teen boy, weary humor' },
      { speaker: 'Hina', jp: '一個ずつ覚えれば大丈夫だよ。', en: "If you learn one at a time, you'll be okay.", style: 'encouraging teen girl, patient kindness' },
      { speaker: 'Sho', jp: 'ありがとう、もう一回説明して。', en: "Thanks — explain it once more?", style: 'humble teen boy, genuine ask' },
      { speaker: 'Hina', jp: 'うん、いいよ。一緒にやろう。', en: "Yeah, sure. Let's do it together.", style: 'warm teen girl, supportive grin' },
    ],
  },
  {
    id: 'conv_01453',
    context: 'Daichi and his wife Mei talk quietly on the porch after the children are asleep.',
    purpose: 'Married couple reflecting on family life; gratitude across years.',
    ambient: 'porch_night_distant_train',
    sound_effects: [],
    target_vocab: ['妻', '家庭', '深く', '感謝'],
    cast: ['Daichi', 'Mei'],
    frequency_tier: 'High',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Daichi', jp: 'うちの家庭、なんかええ感じやな。', en: "Our family — it feels good somehow.", style: 'reflective Kansai husband, soft smile' },
      { speaker: 'Mei', jp: 'うん、子供たちも穏やかで。', en: "Yeah, the kids are calm too.", style: 'warm young mother, content tone' },
      { speaker: 'Daichi', jp: 'お前を妻にして、ほんま良かった。', en: "I'm truly glad I made you my wife.", style: 'tender Kansai man, deep sincerity' },
      { speaker: 'Mei', jp: 'ふふ、急にどうしたの?', en: "Heh, what's gotten into you?", style: 'gentle teasing wife, soft laugh' },
      { speaker: 'Daichi', jp: '深く考えてただけや。', en: "Just thinking deeply, that's all.", style: 'soft Kansai husband, unguarded' },
      { speaker: 'Mei', jp: '私も感謝してるよ、いつも。', en: "I'm grateful too — always.", style: 'tender wife voice, quiet warmth' },
      { speaker: 'Daichi', jp: 'これからも、ようろしくな。', en: "Going forward too — let's keep going.", style: 'soft Kansai voice, gentle commitment' },
    ],
  },
  {
    id: 'conv_01454',
    context: 'Sakura discusses publication details with Ren about her new short-story collection.',
    purpose: 'Author-editor talk about release plan and audience.',
    ambient: 'cafe_afternoon_low',
    sound_effects: [],
    target_vocab: ['編', '発表', '販売', '是非', '感想'],
    cast: ['Sakura', 'Ren'],
    frequency_tier: 'Medium',
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'Sakura', jp: '新しい短編集、発表はいつ?', en: "When's the announcement for the new collection?", style: 'curious adult writer, soft anticipation' },
      { speaker: 'Ren', jp: '来月の中旬を予定しています。', en: "Mid next month is the plan.", style: 'professional young editor, measured' },
      { speaker: 'Sakura', jp: 'もう編集は終わったかな。', en: "Has the editing wrapped up?", style: 'thoughtful writer, soft worry' },
      { speaker: 'Ren', jp: '最終確認だけ、残ってます。', en: "Just the final check is left.", style: 'reassuring young man, calm clear' },
      { speaker: 'Sakura', jp: '販売は書店だけ?', en: "Will sales be in bookstores only?", style: 'practical adult woman, gentle question' },
      { speaker: 'Ren', jp: 'いえ、電子書籍も同時です。', en: "No — e-book the same day.", style: 'informative editor, polite' },
      { speaker: 'Sakura', jp: 'なるほど、それは嬉しい。', en: "Ah, that's lovely.", style: 'soft pleased writer voice, gentle smile' },
      { speaker: 'Ren', jp: '是非、サイン会もどうですか?', en: "By all means — a signing event too?", style: 'enthusiastic young editor, polite warmth' },
      { speaker: 'Sakura', jp: 'うん、是非やってみたい。', en: "Yes, I'd love to try one.", style: 'warm writer voice, gracious' },
      { speaker: 'Ren', jp: '読者の感想も集めましょう。', en: "Let's gather reader impressions too.", style: 'engaged editor, forward-leaning' },
      { speaker: 'Sakura', jp: 'それは本当に楽しみ。', en: "That I'm truly looking forward to.", style: 'genuine writer voice, hopeful glow' },
      { speaker: 'Ren', jp: '良い編集、ご一緒できて光栄です。', en: "It's been an honor editing with you.", style: 'humble young editor, warm sincerity' },
    ],
  },
  {
    id: 'conv_01455',
    context: 'Kenji and Aoi attend a small drama performance and discuss it during intermission.',
    purpose: 'Friends-turned-couple sharing arts impressions thoughtfully.',
    ambient: 'theater_foyer_murmur',
    sound_effects: [],
    target_vocab: ['監督', '劇', '意識', '演出'],
    cast: ['Kenji', 'Aoi'],
    frequency_tier: 'Medium',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Aoi', jp: 'この劇の監督、若いみたいね。', en: "The director of this play seems young.", style: 'thoughtful middle-aged woman, cultured tone' },
      { speaker: 'Kenji', jp: 'ああ、演出に意識が見える。', en: "Yeah, you can see thought in the staging.", style: 'observant Kansai artist, soft admiration' },
      { speaker: 'Aoi', jp: '光の使い方が美しいわ。', en: "The use of light is beautiful.", style: 'cultured woman voice, soft awe' },
      { speaker: 'Kenji', jp: '俺もそこ、感心したわ。', en: "I was impressed by that too.", style: 'gentle Kansai male, warm agreement' },
      { speaker: 'Aoi', jp: '休憩終わるね、戻ろう。', en: "Intermission's ending — let's go back.", style: 'soft adult woman, careful timing' },
      { speaker: 'Kenji', jp: 'うん、後半も楽しみや。', en: "Yeah, looking forward to the second half.", style: 'eager Kansai voice, warm anticipation' },
      { speaker: 'Aoi', jp: '一緒に観られて、嬉しい。', en: "Glad I can watch it with you.", style: 'tender middle-aged woman, quiet love' },
    ],
  },
  {
    id: 'conv_01456',
    context: 'Hina and Sho play catch in the small park, warming up loose limbs.',
    purpose: 'Sibling-energy playful exercise and friendly banter.',
    ambient: 'park_morning_birds',
    sound_effects: [],
    target_vocab: ['動い', '軽く', 'ボール'],
    cast: ['Hina', 'Sho'],
    frequency_tier: 'High',
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'Sho', jp: 'ボール、軽く投げるな。', en: "Toss the ball gently, alright?", style: 'casual teen boy, easy confidence' },
      { speaker: 'Hina', jp: 'うん、まず体動いてから。', en: "Yeah, after I move my body a bit.", style: 'cheerful teen girl, light energy' },
      { speaker: 'Sho', jp: '寒いから、軽く準備運動して。', en: "It's cold — do a light warm-up.", style: 'caring teen brother voice, practical' },
      { speaker: 'Hina', jp: 'はーい、お兄ちゃん優しいね。', en: "Okay, big bro — you're being sweet.", style: 'teasing teen girl, warm grin in voice' },
      { speaker: 'Sho', jp: 'うるさい、投げるぞ。', en: "Hush — I'm throwing.", style: 'embarrassed teen boy, flustered laugh' },
    ],
  },
  {
    id: 'conv_01457',
    context: 'Dr. Saito visits Sakura over tea; they discuss her former teaching work.',
    purpose: 'Two reflective adults discussing vocations across professions.',
    ambient: 'cafe_quiet_clink',
    sound_effects: [],
    target_vocab: ['教師', '仕方', '課題', '経験'],
    cast: ['Saito', 'Sakura'],
    frequency_tier: 'Medium',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Saito', jp: '教師の経験、執筆に生きてますか?', en: "Does your teaching experience help your writing?", style: 'curious doctor voice, gentle academic' },
      { speaker: 'Sakura', jp: 'うん、すごく生きてる。', en: "Yes — enormously so.", style: 'reflective writer, warm certainty' },
      { speaker: 'Saito', jp: '子供たちから学んだ仕方も?', en: "Even the ways you learned from children?", style: 'thoughtful male voice, soft inquiry' },
      { speaker: 'Sakura', jp: 'もちろん。教える仕方が大事だった。', en: "Of course — how to teach mattered most.", style: 'gentle writer, confident memory' },
      { speaker: 'Saito', jp: '医療にも似た課題があります。', en: "Medicine has similar challenges.", style: 'measured doctor voice, peer respect' },
      { speaker: 'Sakura', jp: 'どちらも、人と向き合う仕事ね。', en: "Both are work of facing people.", style: 'warm writer voice, shared understanding' },
      { speaker: 'Saito', jp: 'ええ、その通りです。', en: "Yes — exactly so.", style: 'soft doctor voice, quiet camaraderie' },
    ],
  },
  {
    id: 'conv_01458',
    context: 'Mei and Hina take the train north for a short trip; chatting about the view.',
    purpose: 'Aunt-and-niece travel chatter; light geography talk.',
    ambient: 'train_window_low_hum',
    sound_effects: [],
    target_vocab: ['北', '京都', '景色'],
    cast: ['Mei', 'Hina'],
    frequency_tier: 'High',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Hina', jp: '北の景色、空気が違うね。', en: "The northern scenery — the air feels different.", style: 'wide-eyed teen girl, traveling delight' },
      { speaker: 'Mei', jp: '澄んでるよね、ほんとに。', en: "It's so clear, really.", style: 'gentle young aunt, soft awe' },
      { speaker: 'Hina', jp: '京都とはまた違う雰囲気。', en: "A whole different mood from Kyoto.", style: 'curious teen voice, comparing thoughtfully' },
      { speaker: 'Mei', jp: '京都は古い街、北は静か。', en: "Kyoto is an old city; the north is quiet.", style: 'warm young woman, gentle teaching' },
      { speaker: 'Hina', jp: 'どっちも好きだなぁ。', en: "I love both.", style: 'dreamy teen voice, content sigh' },
      { speaker: 'Mei', jp: '次は北海道も行きたいね。', en: "Next time let's go to Hokkaido.", style: 'warm aunt voice, planning fondly' },
      { speaker: 'Hina', jp: 'いいね、絶対行こう!', en: "Yes — let's definitely go!", style: 'excited teen girl, bright commitment' },
    ],
  },
  {
    id: 'conv_01459',
    context: 'Ren and Sho talk about creative discipline late at night in the kitchen.',
    purpose: 'Older mentor figure and teen exchange about craft and self.',
    ambient: 'kitchen_night_fridge_hum',
    sound_effects: [],
    target_vocab: ['機能', '自身', '戦略', '日々'],
    cast: ['Ren', 'Sho'],
    frequency_tier: 'Medium',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Sho', jp: '蓮さん、絵の戦略って必要?', en: "Ren, do you need a strategy for drawing?", style: 'earnest teen boy, curious tone' },
      { speaker: 'Ren', jp: '戦略というより、日々の習慣やね。', en: "Less strategy than daily habit, really.", style: 'soft adult male artist, gentle teaching' },
      { speaker: 'Sho', jp: '自分自身を信じるって難しい。', en: "Believing in yourself is hard.", style: 'reflective teen boy, soft honesty' },
      { speaker: 'Ren', jp: 'うん、誰でもそう。', en: "Yeah — everyone feels that.", style: 'understanding adult, gentle nod tone' },
      { speaker: 'Sho', jp: '機能する練習って、どうやるの?', en: "How do you do practice that actually works?", style: 'curious teen voice, focused' },
      { speaker: 'Ren', jp: '飽きずに、少しずつ毎日。', en: "Without getting bored — a little, daily.", style: 'calm young artist, quiet authority' },
      { speaker: 'Sho', jp: 'なるほど、やってみる。', en: "Got it — I'll try.", style: 'resolved teen boy, soft commitment' },
    ],
  },
  {
    id: 'conv_01460',
    context: 'Aoi and her Kansai friend Saori chat about regional speech patterns.',
    purpose: 'Friends comparing dialects; cultural curiosity in everyday conversation.',
    ambient: 'cafe_window_seat',
    sound_effects: [],
    target_vocab: ['反対', '意味', '振り', '方言'],
    cast: ['Aoi', 'Saori'],
    frequency_tier: 'Medium',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Aoi', jp: '関西弁、意味が反対のこともあるの?', en: "Does Kansai dialect sometimes mean the opposite?", style: 'curious middle-aged woman, gentle questioning' },
      { speaker: 'Saori', jp: 'あるある!皮肉も多いねん。', en: "Yes! There's lots of sarcasm too.", style: 'bright Kansai woman, lively grin in voice' },
      { speaker: 'Aoi', jp: '面白いね、振りで分かるの?', en: "Fascinating — can you tell from the gesture?", style: 'thoughtful adult woman, soft interest' },
      { speaker: 'Saori', jp: 'うん、声の振りが大事やで。', en: "Yep — the inflection of the voice matters.", style: 'animated Kansai friend, teaching playfully' },
      { speaker: 'Aoi', jp: 'なるほど、勉強になる。', en: "Ah, I'm learning.", style: 'gentle adult woman, warm appreciation' },
      { speaker: 'Saori', jp: 'ええやろ、関西弁。覚えてみ?', en: "Kansai's great, right? Try learning it.", style: 'cheery Kansai woman, encouraging tease' },
      { speaker: 'Aoi', jp: 'ふふ、難しそうだけど挑戦する。', en: "Heh, sounds hard but I'll try.", style: 'soft adult woman, playful determination' },
    ],
  },
  {
    id: 'conv_01461',
    context: 'Daichi works on a small woodcraft piece while Hiroshi watches and comments.',
    purpose: 'Father-in-law and son-in-law bonding over craft.',
    ambient: 'workshop_low_evening',
    sound_effects: [],
    target_vocab: ['線', '振り', '道具'],
    cast: ['Daichi', 'Hiroshi'],
    frequency_tier: 'High',
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'Hiroshi', jp: 'その線、まっすぐええで。', en: "That line — nicely straight.", style: 'elder Kansai grandfather, low warm rasp' },
      { speaker: 'Daichi', jp: 'おかげさまで、道具がいい。', en: "Thanks to good tools, sure.", style: 'humble Kansai man, soft modesty' },
      { speaker: 'Hiroshi', jp: 'のこぎりの振り、上達したな。', en: "Your saw stroke has improved.", style: 'proud elder Kansai, gentle praise' },
      { speaker: 'Daichi', jp: 'ほんま?嬉しいわ。', en: "Really? That makes me glad.", style: 'pleased Kansai man, warm smile in voice' },
      { speaker: 'Hiroshi', jp: 'これで子供の机、作れるな。', en: "Now you can build a desk for the kid.", style: 'wise elder voice, fond projection' },
    ],
  },
  {
    id: 'conv_01462',
    context: 'Yumiko and Mei share a quiet moment as Mei rocks her sleeping baby Hikari.',
    purpose: 'Two mothers, generations apart, sharing tender domestic peace.',
    ambient: 'nursery_dim_lullaby',
    sound_effects: [],
    target_vocab: ['喜び', '母親', '静か'],
    cast: ['Yumiko', 'Mei'],
    frequency_tier: 'High',
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'Yumiko', jp: '寝顔、本当に静かね。', en: "Her sleeping face is so peaceful.", style: 'gentle older mother, hushed warmth' },
      { speaker: 'Mei', jp: 'うん、毎晩がちいさな喜び。', en: "Yeah — every night is a small joy.", style: 'tender young mother, soft love' },
      { speaker: 'Yumiko', jp: '母親って、こういう瞬間ね。', en: "Motherhood — it's in moments like this.", style: 'reflective older woman, soft realization' },
      { speaker: 'Mei', jp: '本当にそう、ゆみこさん。', en: "Truly so, Yumiko-san.", style: 'soft young mother, gracious agreement' },
      { speaker: 'Yumiko', jp: 'ゆっくり寝かせてあげましょ。', en: "Let her sleep on quietly.", style: 'wise older mother voice, soft suggestion' },
    ],
  },
  {
    id: 'conv_01463',
    context: 'Sho talks to Kenji about thoughts of his future work life.',
    purpose: 'Teen seeking adult perspective on vocation and direction.',
    ambient: 'studio_dusk_quiet',
    sound_effects: [],
    target_vocab: ['就職', '希望', '強く', '将来'],
    cast: ['Sho', 'Kenji'],
    frequency_tier: 'Medium',
    length_tier: 'Medium (7-12)',
    meta: META(),
    lines: [
      { speaker: 'Sho', jp: '将来、就職どうするか悩む。', en: "I'm worried about future employment.", style: 'serious teen boy, honest unease' },
      { speaker: 'Kenji', jp: '誰でもそうやで、最初は。', en: "Everyone is at first.", style: 'calm Kansai mentor, grounding warmth' },
      { speaker: 'Sho', jp: '希望はあるけど、自信がない。', en: "I have hope, but no confidence.", style: 'soft teen boy, quiet vulnerability' },
      { speaker: 'Kenji', jp: '希望があるだけで、強いで。', en: "Just having hope is already strong.", style: 'warm Kansai elder voice, gentle conviction' },
      { speaker: 'Sho', jp: 'そうかな…ありがとう。', en: "Maybe so... thanks.", style: 'softer teen voice, gathering hope' },
      { speaker: 'Kenji', jp: '強く願えば、道は開けるわ。', en: "If you wish strongly, the path opens.", style: 'sage Kansai voice, fatherly faith' },
      { speaker: 'Sho', jp: 'うん、頑張ってみる。', en: "Yeah — I'll give it a go.", style: 'resolved teen boy, soft determination' },
    ],
  },
  {
    id: 'conv_01464',
    context: 'Hina and Sakura sit in the library; Hina is choosing a novel for the weekend.',
    purpose: 'Quiet intergenerational book recommendation.',
    ambient: 'library_quiet_pages',
    sound_effects: [],
    target_vocab: ['部分', '小説', '読み'],
    cast: ['Hina', 'Sakura'],
    frequency_tier: 'High',
    length_tier: 'Short (5-6)',
    meta: META(),
    lines: [
      { speaker: 'Hina', jp: 'この小説、どの部分がいい?', en: "Which part of this novel is the best?", style: 'soft teen girl, library hush' },
      { speaker: 'Sakura', jp: '中盤の感情の描き方、好き。', en: "I love the emotional middle.", style: 'gentle writer voice, fond appraisal' },
      { speaker: 'Hina', jp: 'なるほど、楽しみだなぁ。', en: "Got it — I'm excited.", style: 'eager teen voice, anticipation' },
      { speaker: 'Sakura', jp: 'ゆっくり読み進めてね。', en: "Read it slowly.", style: 'tender adult woman, soft advice' },
      { speaker: 'Hina', jp: 'うん、週末に読むね。', en: "Yeah — I'll read it this weekend.", style: 'warm teen girl, soft promise' },
    ],
  },
  {
    id: 'conv_01465',
    context: 'A small family year-end gathering: Hiroshi, Aoi, Kenji, Daichi, Mei sharing a long meal.',
    purpose: 'Cross-generational gratitude dinner; many small threads of warmth.',
    ambient: 'living_room_dinner_low',
    sound_effects: [],
    target_vocab: ['豊か', '種類', '期間', '一緒', '感謝'],
    cast: ['Hiroshi', 'Aoi', 'Kenji', 'Daichi', 'Mei'],
    frequency_tier: 'Medium',
    length_tier: 'Long (13-20)',
    meta: META(),
    lines: [
      { speaker: 'Hiroshi', jp: '今年もええ期間やったな。', en: "It's been a good year.", style: 'elder Kansai voice, low warm rasp' },
      { speaker: 'Aoi', jp: 'うん、家族と過ごせて豊か。', en: "Yes — rich, spending it with family.", style: 'reflective middle-aged daughter, content' },
      { speaker: 'Kenji', jp: 'いろんな種類の出来事あったな。', en: "All kinds of things happened, didn't they.", style: 'thoughtful Kansai man, soft retrospect' },
      { speaker: 'Daichi', jp: '子供も増えて、賑やかになった。', en: "Kids grew, things got lively.", style: 'warm Kansai father voice, fond' },
      { speaker: 'Mei', jp: '感謝の気持ちでいっぱいです。', en: "I'm full of gratitude.", style: 'soft young mother, sincere warmth' },
      { speaker: 'Hiroshi', jp: 'みんな一緒に、ありがたいことや。', en: "Everyone together — what a blessing.", style: 'elder Kansai patriarch, tender pride' },
      { speaker: 'Aoi', jp: 'お父さん、長生きしてね。', en: "Dad — live a long life, please.", style: 'tender adult daughter, soft love' },
      { speaker: 'Hiroshi', jp: 'ほな、もうちょい頑張るわ。', en: "Well then, I'll keep at it a bit longer.", style: 'warm elder Kansai, gentle humor' },
      { speaker: 'Kenji', jp: '来年も豊かな一年にしような。', en: "Let's make next year a rich one too.", style: 'soft Kansai artist, hopeful' },
      { speaker: 'Daichi', jp: '家族、ほんま宝や。', en: "Family — truly a treasure.", style: 'tender Kansai husband voice, full heart' },
      { speaker: 'Mei', jp: '一緒に、また春を迎えましょう。', en: "Let's meet spring again, together.", style: 'gentle young mother, soft hope' },
      { speaker: 'Aoi', jp: 'うん、約束ね。', en: "Yes — a promise.", style: 'tender adult woman, quiet certainty' },
      { speaker: 'Hiroshi', jp: 'ほな、いただこか。', en: "Well then — let's eat.", style: 'warm elder Kansai patriarch, settling' },
    ],
  },
];

for (const conv of CONVERSATIONS) {
  const out = path.join(OUT_DIR, `${conv.id}.json`);
  fs.writeFileSync(out, JSON.stringify(conv, null, 2), 'utf-8');
}
console.log('batch_073 wrote', CONVERSATIONS.length, 'files');
