#!/usr/bin/env node
// Regenerates assets/starter/starter.ts (convId → require(zip)) from the
// starter zips on disk. Run after refreshing the starter pack.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const STARTER = path.join(ROOT, 'assets', 'starter')

const zips = fs.readdirSync(STARTER).filter(f => f.endsWith('.zip')).sort()
const entries = zips.map(f => {
  const convId = f.split('-')[0]
  return `  ${convId}: require('./${f}'),`
})

const out = `// GENERATED by scripts/app_pipeline/gen_starter_module.mjs — do not edit.
// Starter pack: first conversations bundled into the app binary so the very
// first session works offline with zero setup.

export const STARTER_BUNDLES: Record<string, number> = {
${entries.join('\n')}
}
`
fs.writeFileSync(path.join(STARTER, 'starter.ts'), out)
console.log(`starter.ts: ${zips.length} bundles`)
