import fs from 'node:fs'
import path from 'node:path'

const ROOT = path.resolve('d:/Program/Japanese Learning App/nagomi')
const OUT_DIR = path.join(ROOT, 'data/conversations')
const VOCAB_PATH = path.join(ROOT, 'data/vocab/words.json')
const vocabSet = new Set(JSON.parse(fs.readFileSync(VOCAB_PATH, 'utf8')).map(w => w.jp))
function lengthLabel(n) { return n <= 6 ? 'Short (5-6)' : n <= 12 ? 'Medium (7-12)' : 'Long (13-20)' }
const META = { generated_by: 'claude-opus-4-7 (batch_264 manual hand-authored)', generated_at: '2026-06-02T00:00:00.000Z', source_plan_row: '' }

const data = [
  {
    id: 'conv_05241', cluster: 'A', ambient: 'cafe_quiet_chatter',
    scenario: 'Two cafe friends gossip about a karaoke night and message drama',
    cast: ['aoi_barista','mei_romantic'],
    targets: ['いまさら','それどころか','またもや','しゃべる','親しみ','スルー','巻い','歌声'],
    lines: [
      { speaker:'mei_romantic', jp:'昨日のカラオケ、すごい盛り上がったよね。タカシくんの歌声、心に染みた。', en:"Yesterday's karaoke was so much fun. Takashi's singing really got to me.", style:'Soft dreamy reminiscing, leaning forward with a quiet smile.' },
      { speaker:'aoi_barista', jp:'本当に。あの人、普段シャイなのに、歌うとあんなにしゃべるみたいに表情豊かなんだね。', en:"Right? He's usually shy, but when he sings he's expressive as if he's talking.", style:'Warm barista observation, slightly impressed and curious.' },
      { speaker:'mei_romantic', jp:'そうそう、いつもよりずっと親しみやすく感じた。マフラー巻いたままシャウトしてたとこ、最高だったわ。', en:"Yeah, he felt way more approachable than usual. The shouting with his scarf still wrapped on, the best.", style:'Giggling memory, hands acting it out playfully.' },
      { speaker:'aoi_barista', jp:'でもね、その後のLINE、私またもやスルーしちゃったの。我ながら情けない。', en:"But after that, I once again left his LINE message unread. I'm hopeless.", style:'Sheepish confession, voice dropping into self-reproach.' },
      { speaker:'mei_romantic', jp:'それはまずいよ。いまさら長文で謝るのも変だけど、一言だけでも送ってあげなよ。', en:"That's bad. Apologizing with a long message now would be weird, but at least send him one line.", style:'Gentle but firm friend-advice, leaning in earnest.' },
      { speaker:'aoi_barista', jp:'それどころか、もう三日も既読つけてないんだ。怖くて開けない。', en:"Worse than that — I haven't even marked it read for three days. Too scared to open.", style:'Whisper-low admission, eyes on the latte cup.' },
      { speaker:'mei_romantic', jp:'わたしが横にいるから、深呼吸して開いてみよ。あの歌声を信じて、ちゃんと返事してあげなよ。', en:"I'm right here, so take a breath and open it. Trust that singing voice and reply properly.", style:'Encouraging, hand on her arm with quiet steadiness.' },
      { speaker:'aoi_barista', jp:'うん…ありがと。よし、今ここで返事打つ。', en:"Yeah… thanks. Okay, I'll reply right here, right now.", style:'Determined small voice, finally lifting her phone.' },
    ],
  },
  {
    id: 'conv_05242', cluster: 'A', ambient: 'street_quiet_distant',
    scenario: 'Two teens debrief a chaotic school chorus practice',
    cast: ['sakura_teen','riku_teen'],
    targets: ['いまさら','それどころか','またもや','しゃべる','親しみ','スルー','巻い','歌声'],
    lines: [
      { speaker:'sakura_teen', jp:'今日の合唱練、めっちゃキツくなかった?', en:"Today's chorus practice was brutal, wasn't it?", style:'Tired teen sigh, walking home pace.' },
      { speaker:'riku_teen', jp:'マジで。声出しすぎて喉に絆創膏巻きたいレベル。', en:"Seriously. I'm so blown out I want to wrap a bandage on my throat.", style:'Casual exhausted teen-boy joke.' },
      { speaker:'sakura_teen', jp:'しかも先生、同じ箇所をまたもや指摘してきてさ。', en:"And the teacher pointed out the same spot, yet again.", style:'Mock-exasperated, rolling her eyes.' },
      { speaker:'riku_teen', jp:'先輩たちの歌声、近くで聞くと別格だな。親しみある優しい音で。', en:"Hearing the seniors up close, their voices are in a different league. Warm, approachable sound.", style:'Quietly impressed teen admiration.' },
      { speaker:'sakura_teen', jp:'わかる。いまさら焦って自主練しても間に合わなくない?', en:"I know. Cramming solo practice this late won't really help, right?", style:'Resigned teen girl venting.' },
      { speaker:'riku_teen', jp:'それどころか、明日の数学のテストも全然手つかずだぜ。', en:"More than that, I haven't even touched tomorrow's math test prep.", style:'Half-laughing teen-boy panic.' },
      { speaker:'sakura_teen', jp:'ふぁ、しゃべるエネルギーすら残ってない。今日はLINEもスルーで早く寝る。', en:"Ugh, I don't even have energy to talk. Tonight I'm ignoring LINE and going straight to bed.", style:'Yawning teen girl, voice trailing off.' },
      { speaker:'riku_teen', jp:'了解。明日朝、駅で集合な。お互いゾンビでも来いよ。', en:"Got it. Tomorrow morning, meet at the station. Show up even as zombies.", style:'Casual teen-boy sign-off, raising a fist weakly.' },
    ],
  },
  {
    id: 'conv_05243', cluster: 'A', ambient: 'living_room_quiet',
    scenario: 'A mom helps her young son rehearse a school recital line',
    cast: ['yumiko_mom','sho_child'],
    targets: ['いまさら','それどころか','またもや','しゃべる','親しみ','スルー','巻い','歌声'],
    lines: [
      { speaker:'sho_child', jp:'ママ、リハで、またもやセリフ間違えちゃったよ…。', en:"Mom, at rehearsal I messed up my line yet again…", style:'Small downcast voice, fiddling with his shirt.' },
      { speaker:'yumiko_mom', jp:'大丈夫よ。いまさら焦らないで、ゆっくり一緒に練習しよ。', en:"It's okay. Don't panic at this point, let's practice slowly together.", style:'Warm motherly tone, brushing his hair.' },
      { speaker:'sho_child', jp:'でもね、僕の歌声、後ろの席まで届いてないってお友達に言われた。', en:"But my friend said my singing doesn't reach the back rows.", style:'Hurt little voice, eyes pleading.' },
      { speaker:'yumiko_mom', jp:'親しみのある声で歌えば、絶対みんなの心に届くよ。', en:"If you sing with a warm, friendly voice, it'll definitely reach everyone's hearts.", style:'Gentle reassurance, kneeling at his level.' },
      { speaker:'sho_child', jp:'先生のお手本動画、つい途中でスルーしちゃうんだ…。', en:"I keep skipping through the teacher's example video halfway.", style:'Guilty mumble, eyes on his feet.' },
      { speaker:'yumiko_mom', jp:'それどころか、お腹の冷えで声も出にくくなるから、まずマフラー巻いて温めよ。', en:"On top of that, a cold belly makes singing harder, so let's wrap a scarf and warm up first.", style:'Practical maternal warmth, helping him bundle up.' },
      { speaker:'sho_child', jp:'うん。ママと一緒なら、本番の前ちゃんとしゃべる練習もできるかも。', en:"Yeah. With you here, I might even practice talking clearly before the show too.", style:'Brightening child voice, hopeful.' },
      { speaker:'yumiko_mom', jp:'いいね、その調子。さあ、最初から通してみよう。', en:"That's the spirit. Let's run it from the top.", style:'Encouraging mother, clapping softly.' },
    ],
  },
  {
    id: 'conv_05244', cluster: 'A', ambient: 'living_room_quiet',
    scenario: 'An elderly couple recalls a community sing-along',
    cast: ['hiroshi_elder','sachiko_grandma'],
    targets: ['いまさら','それどころか','またもや','しゃべる','親しみ','スルー','巻い','歌声'],
    lines: [
      { speaker:'hiroshi_elder', jp:'昨日の老人会の集まり、本当に楽しかったね。', en:"Yesterday's senior club gathering was really enjoyable.", style:'Soft contented elderly tone, sipping tea.' },
      { speaker:'sachiko_grandma', jp:'ええ、田中さんの歌声、若い頃と少しも変わらず素敵だったわ。', en:"Yes, Tanaka-san's voice hasn't changed a bit since the old days.", style:'Warm wistful smile, hands cradling her cup.' },
      { speaker:'hiroshi_elder', jp:'スカーフを首に巻いて踊ってる姿、なんとも親しみがあったよ。', en:"With her scarf wrapped around her neck, dancing — there was something so warm about it.", style:'Fond chuckle, eyes crinkling.' },
      { speaker:'sachiko_grandma', jp:'集合写真の連絡、私またもやLINEで返事をスルーしちゃってたの。', en:"The group photo message — once again I let the LINE reply slip.", style:'Apologetic small laugh, slightly embarrassed.' },
      { speaker:'hiroshi_elder', jp:'いまさら返しても遅くないさ。電話で一言伝えればいい。', en:"It's not too late to reply. Just call and say a quick word.", style:'Gentle elder-husband reassurance, calm pace.' },
      { speaker:'sachiko_grandma', jp:'そうね。それどころか、お礼に手作りの和菓子も持っていきたいわ。', en:"You're right. More than that, I want to bring some homemade sweets as thanks.", style:'Brightening grandmother voice, energetic now.' },
      { speaker:'hiroshi_elder', jp:'いいね。私もたまには口下手だが、ちゃんとしゃべるよう心がけるよ。', en:"Good idea. I'm awkward at small talk, but I'll make sure to actually speak up sometimes.", style:'Self-deprecating elder humor, soft warmth.' },
      { speaker:'sachiko_grandma', jp:'ふふ、その気持ちが何より嬉しいの。', en:"Hehe, that intention itself is what makes me happiest.", style:'Tender quiet laugh, reaching for his hand.' },
    ],
  },
  {
    id: 'conv_05245', cluster: 'A', ambient: 'cafe_quiet_chatter',
    scenario: 'A uni student helps a teen friend rehearse a stage solo',
    cast: ['ren_uni','sakura_teen'],
    targets: ['いまさら','それどころか','またもや','しゃべる','親しみ','スルー','巻い','歌声'],
    lines: [
      { speaker:'sakura_teen', jp:'先輩、明日のソロ発表、本当に緊張するんですけど…。', en:"Senpai, I'm so nervous about tomorrow's solo performance…", style:'Tightly wound teen voice, gripping her cup.' },
      { speaker:'ren_uni', jp:'大丈夫、サクラの歌声、ちゃんと届いてるって俺は思うよ。', en:"You'll be fine. I really think your singing voice carries well.", style:'Calm older-brother reassurance.' },
      { speaker:'sakura_teen', jp:'でも、先生に指摘されたとこ、またもやミスしちゃってて…。', en:"But the part the teacher flagged — I keep botching it again.", style:'Small dejected admission, eyes lowered.' },
      { speaker:'ren_uni', jp:'いまさら一夜漬けで完璧にしようとしなくていい。今日はリラックス優先。', en:"You don't have to cram for perfection at the last minute. Prioritize relaxing today.", style:'Measured mentor delivery, casual sip of coffee.' },
      { speaker:'sakura_teen', jp:'それどころか、夜中まで練習して逆に疲れちゃいそうで怖いです。', en:"Worse, I'm scared I'll over-practice through the night and end up exhausted.", style:'Anxious teen with a slight tremor.' },
      { speaker:'ren_uni', jp:'親しみのある表現が、サクラの強みだよ。マイクのコード、ちゃんと巻いて整理しとくね。', en:"Your warm, relatable delivery is your strength. I'll coil the mic cable for you neatly.", style:'Practical kindness, hands miming the coil.' },
      { speaker:'sakura_teen', jp:'ありがとうございます。先輩が来てくれると、緊張がスルーされて落ち着く。', en:"Thank you. With you there, the nerves just slide past somehow.", style:'Softening teen voice, faint smile.' },
      { speaker:'ren_uni', jp:'明日はしゃべるより歌で勝負しよう。応援に行くから。', en:"Tomorrow, beat them with your voice instead of words. I'll be cheering.", style:'Warm closing, easy confident grin.' },
    ],
  },
  {
    id: 'conv_05246', cluster: 'B', ambient: 'office_quiet_low',
    scenario: 'A boss reviews a regulatory-strategy proposal with his manager',
    cast: ['hiroshi_boss','kenji_office'],
    targets: ['多用','却下','零細','撤廃','利権','啓蒙','弾力','類型'],
    lines: [
      { speaker:'hiroshi_boss', jp:'ケンジくん、新しい規制改革の提案、概要を聞かせてくれ。', en:"Kenji, run me through the gist of the new regulatory reform proposal.", style:'Crisp boss opener, leafing through a binder.' },
      { speaker:'kenji_office', jp:'はい。零細企業向けの優遇税制を撤廃するか、弾力運用に切り替えるかが争点です。', en:"Yes. The fight is over whether to abolish the tax break for small firms, or shift to flexible application.", style:'Polished manager briefing, structured cadence.' },
      { speaker:'hiroshi_boss', jp:'撤廃案、過去にも検討されたが利権絡みで却下されてきた。', en:"The abolition plan was reviewed before but kept getting shot down over vested interests.", style:'Veteran boss recalling history, measured tone.' },
      { speaker:'kenji_office', jp:'今回は過去の類型を整理して、啓蒙資料として現場に配布する予定です。', en:"This time we're sorting the past patterns and distributing them as educational materials to the field.", style:'Confident proposal pitch.' },
      { speaker:'hiroshi_boss', jp:'専門用語を多用しすぎると、現場が読まないぞ。', en:"If you overuse jargon, the field just won't read it.", style:'Stern boss correction, leaning back.' },
      { speaker:'kenji_office', jp:'承知しました。図解中心にして、弾力的な表現に書き直します。', en:"Understood. We'll make it figure-centric and rewrite with more flexible phrasing.", style:'Receptive nod, jotting notes.' },
      { speaker:'hiroshi_boss', jp:'それでいい。零細事業者の声を直接拾う場も併設しよう。', en:"Good. Let's also set up a forum to gather small-business voices directly.", style:'Decisive closing direction, taps the table.' },
      { speaker:'kenji_office', jp:'承知しました。来週上旬までに修正版をお持ちします。', en:"Got it. I'll bring the revised version by early next week.", style:'Crisp respectful sign-off.' },
    ],
  },
  {
    id: 'conv_05247', cluster: 'B', ambient: 'office_quiet_low',
    scenario: 'Two managers prep a small-business outreach plan',
    cast: ['yuki_office','kenji_office'],
    targets: ['多用','却下','零細','撤廃','利権','啓蒙','弾力','類型'],
    lines: [
      { speaker:'yuki_office', jp:'来週の零細事業者向け説明会の資料、最終確認しよう。', en:"Let's do the final check on materials for next week's small-business briefing.", style:'Brisk co-manager opener.' },
      { speaker:'kenji_office', jp:'スライドの専門用語、極力多用を避ける構成にしてあります。', en:"I've structured the slides to avoid heavy jargon use as much as possible.", style:'Methodical reporting, pointing at the screen.' },
      { speaker:'yuki_office', jp:'いいね。質疑応答の弾力性も上げておきたい。', en:"Good. I also want more flexibility built into the Q&A.", style:'Approving nod, scribbling on the agenda.' },
      { speaker:'kenji_office', jp:'過去の却下事例、類型化して付録に入れました。', en:"I categorized past rejection cases and put them in the appendix.", style:'Detail-oriented, slightly proud.' },
      { speaker:'yuki_office', jp:'啓蒙という言葉、人によって硬く響くから、別の表現に置き換えよう。', en:"The word 'enlightenment' lands too stiff for some, let's swap to a softer phrase.", style:'Constructive co-edit, thoughtful.' },
      { speaker:'kenji_office', jp:'「お役立ち情報」あたりが無難ですかね。', en:"Something like 'useful information' would be safe, I think.", style:'Cooperative suggestion.' },
      { speaker:'yuki_office', jp:'それで。利権の話には深入りせず、規制の撤廃案だけ淡々と伝えよう。', en:"Go with that. Don't dive into vested-interest talk; just convey the deregulation proposal plainly.", style:'Pragmatic team-lead direction.' },
      { speaker:'kenji_office', jp:'了解です。配布資料、印刷上がり次第お持ちします。', en:"Understood. I'll bring the handouts as soon as they're printed.", style:'Crisp closer.' },
    ],
  },
  {
    id: 'conv_05248', cluster: 'B', ambient: 'office_quiet_low',
    scenario: 'A uni intern interviews a manager about lobby dynamics',
    cast: ['ren_uni','yuki_office'],
    targets: ['多用','却下','零細','撤廃','利権','啓蒙','弾力','類型'],
    lines: [
      { speaker:'ren_uni', jp:'取材で恐縮ですが、業界内の利権構造、ここ十年でどう変わってきましたか。', en:"Apologies for the imposition — how has the industry's vested-interest structure shifted in the past decade?", style:'Polite student-journalist opening.' },
      { speaker:'yuki_office', jp:'類型的な囲い込みは、弾力的な業界連携に少しずつ変わってきています。', en:"The textbook-pattern lock-ins have gradually shifted toward more flexible industry cooperation.", style:'Measured insider observation.' },
      { speaker:'ren_uni', jp:'一部の規制撤廃が後押しになった、ということですか。', en:"So some regulatory abolitions pushed that along?", style:'Probing follow-up, leaning in.' },
      { speaker:'yuki_office', jp:'その通り。ただ零細事業者からは、まだ啓蒙が足りないという声もあります。', en:"Exactly. Though small operators still say there isn't enough public education.", style:'Honest qualification, even tone.' },
      { speaker:'ren_uni', jp:'業界提案が却下される場面も、多用に経験されてきたんでしょうか。', en:"You must have seen plenty of industry proposals get rejected as well?", style:'Curious follow-up.' },
      { speaker:'yuki_office', jp:'多用というか、ほぼ毎月のように一度は却下案件が出ますね。', en:"Not just 'plenty' — almost monthly some rejection comes through.", style:'Slight chuckle, candid.' },
      { speaker:'ren_uni', jp:'なるほど。記事ではその辺りも踏まえて書きたいと思います。', en:"I see. I'd like to weave that into the article too.", style:'Earnest student nodding.' },
      { speaker:'yuki_office', jp:'助かります。事実関係、確認したい箇所は事前に共有してください。', en:"That would help. Share any factual points you need to verify in advance.", style:'Helpful corporate closer.' },
    ],
  },
  {
    id: 'conv_05249', cluster: 'B', ambient: 'cafe_quiet_chatter',
    scenario: 'A retired exec mentors a younger boss on policy comms',
    cast: ['hiroshi_elder','hiroshi_boss'],
    targets: ['多用','却下','零細','撤廃','利権','啓蒙','弾力','類型'],
    lines: [
      { speaker:'hiroshi_elder', jp:'君の業界の課題、相変わらず零細業者を守る話か。', en:"The challenges in your industry — still about protecting small operators, eh?", style:'Reflective elder, gravelly warmth.' },
      { speaker:'hiroshi_boss', jp:'ええ。今期は規制撤廃の旗を掲げるか、弾力運用に留めるかで意見が割れています。', en:"Yes. This term, the camp is split between waving the deregulation flag and sticking with flexible operation.", style:'Earnest younger executive consulting his mentor.' },
      { speaker:'hiroshi_elder', jp:'弾力という言葉、多用しすぎると逃げ口上に聞こえる。気をつけろ。', en:"Overuse the word 'flexible' and it starts to sound like ducking the issue. Be careful.", style:'Mentor warning, eyebrow raised.' },
      { speaker:'hiroshi_boss', jp:'ご指摘の通りです。社内でも反対派からの却下圧力が強くて。', en:"As you point out. Inside the company, the rejection pressure from opponents is strong.", style:'Candid frustration shared with mentor.' },
      { speaker:'hiroshi_elder', jp:'利権を切り崩すには、まず啓蒙だ。地道にやれ。', en:"To dismantle vested interests, start with public education. Stay patient.", style:'Sage advice, steady gaze.' },
      { speaker:'hiroshi_boss', jp:'はい。類型化した成功事例集を作って、現場に届けます。', en:"Yes. I'll compile a categorized casebook of successes and put it in the field's hands.", style:'Resolved younger voice, taking notes.' },
      { speaker:'hiroshi_elder', jp:'それでいい。古い人間の口出しはこの辺で。', en:"That'll do. An old man's meddling can stop here.", style:'Quiet humility, lifting his cup.' },
      { speaker:'hiroshi_boss', jp:'先輩のお言葉、いつも背中を押してくださいます。', en:"Your words always give me the push I need, mentor.", style:'Grateful close, slight bow.' },
    ],
  },
  {
    id: 'conv_05250', cluster: 'B', ambient: 'office_quiet_low',
    scenario: 'A police officer briefs a uni reporter about a public-affairs case',
    cast: ['takeda_officer','ren_uni'],
    targets: ['多用','却下','零細','撤廃','利権','啓蒙','弾力','類型'],
    lines: [
      { speaker:'takeda_officer', jp:'取材内容、確認しておきます。市の予算案の件ですね。', en:"Let me confirm the topic — the city budget proposal, correct?", style:'Calm, measured officer voice.' },
      { speaker:'ren_uni', jp:'はい。零細事業者向けの補助金が却下された経緯、教えていただけますか。', en:"Yes. Could you walk me through how the small-business subsidies were rejected?", style:'Polite student-journalist opener.' },
      { speaker:'takeda_officer', jp:'議会の弾力的な対応が間に合わず、撤廃案の方が先に通ってしまった。', en:"The council's flexible response didn't keep up, and the abolition plan passed first.", style:'Factual recounting, hands folded.' },
      { speaker:'ren_uni', jp:'利権構造に絡む話だと、住民への啓蒙はどう進めているんですか。', en:"For matters tangled with vested interests, how are you educating residents?", style:'Probing student curiosity.' },
      { speaker:'takeda_officer', jp:'広報資料を多用するより、地域の会合で類型化した事例を直接話すようにしています。', en:"Rather than overusing PR materials, we share categorized cases at local meetings.", style:'Pragmatic officer explanation.' },
      { speaker:'ren_uni', jp:'大変参考になります。資料、後ほどメールでお送りください。', en:"Very helpful. Please email the materials later.", style:'Grateful student nod.' },
      { speaker:'takeda_officer', jp:'了解。匿名処理が必要な箇所、こちらでマークしてお渡しします。', en:"Understood. I'll flag the parts that need anonymization and pass them on.", style:'Procedural closer, slight nod.' },
      { speaker:'ren_uni', jp:'お手数おかけします。ありがとうございます。', en:"Sorry for the trouble. Thank you very much.", style:'Polite student sign-off.' },
    ],
  },
  {
    id: 'conv_05251', cluster: 'C', ambient: 'lecture_hall_quiet',
    scenario: 'A teacher walks a uni student through an oceanography paper',
    cast: ['asuka_teacher','ren_uni'],
    targets: ['海水','ウラン','洞窟','引き上げる','余儀なく','転じ','ストライキ','初級'],
    lines: [
      { speaker:'asuka_teacher', jp:'レンくん、論文の章立て、海水中のウラン抽出の話に絞ったんですね。', en:"Ren, you narrowed your chapter to uranium extraction from seawater.", style:'Calm seminar opener, professorial cadence.' },
      { speaker:'ren_uni', jp:'はい。コスト面で実用化を断念せざるを得ない研究が多く、本筋は撤退を余儀なくされてきました。', en:"Yes. Many studies had to withdraw because the cost made commercialization unfeasible.", style:'Earnest student briefing.' },
      { speaker:'asuka_teacher', jp:'最近、研究の流れが転じて、海底洞窟付近の濃度差を利用する案が出ています。', en:"Recently the field has turned, and proposals are using concentration gradients near undersea caves.", style:'Engaged teacher tone, sliding a figure across the desk.' },
      { speaker:'ren_uni', jp:'その手法だと、抽出効率を大きく引き上げることが可能だそうです。', en:"With that method, extraction efficiency can apparently be raised substantially.", style:'Animated student insight.' },
      { speaker:'asuka_teacher', jp:'初級の教科書では触れられない領域ですが、政策面では重要です。', en:"It's not covered in beginner textbooks, but it matters at the policy level.", style:'Patient teacher explanation.' },
      { speaker:'ren_uni', jp:'港湾労働者のストライキが起きた地域では、研究施設の運営にも影響が出ていますね。', en:"In regions where port-worker strikes happened, research facility operations are also affected.", style:'Thoughtful student observation.' },
      { speaker:'asuka_teacher', jp:'そうした文脈も入れると、論文の説得力が増しますよ。', en:"Bringing in that context will strengthen your paper's persuasiveness.", style:'Encouraging mentor close.' },
      { speaker:'ren_uni', jp:'ありがとうございます。第三章でその点、丁寧に書きます。', en:"Thank you. I'll handle that point carefully in chapter three.", style:'Respectful student close.' },
    ],
  },
  {
    id: 'conv_05252', cluster: 'C', ambient: 'office_quiet_low',
    scenario: 'A boss and his manager dissect a long-form energy article',
    cast: ['hiroshi_boss','kenji_office'],
    targets: ['海水','ウラン','洞窟','引き上げる','余儀なく','転じ','ストライキ','初級'],
    lines: [
      { speaker:'hiroshi_boss', jp:'この記事、ウラン資源の海水抽出技術を取り上げているな。', en:"This article takes up uranium extraction from seawater.", style:'Boss leafing through a magazine, low concentration tone.' },
      { speaker:'kenji_office', jp:'はい。コスト構造の見直しが転じて、産業的に成立する可能性が出てきました。', en:"Yes. The cost picture turned, and industrial viability is starting to look possible.", style:'Manager summarizing crisply.' },
      { speaker:'hiroshi_boss', jp:'引き上げるべきはコストではなく、現場の安全基準だろう。', en:"What needs raising isn't costs but on-site safety standards.", style:'Sharp critique, leaning back.' },
      { speaker:'kenji_office', jp:'関連する港湾組合のストライキ後、人員配置も初級職から再構築されています。', en:"After the related port-union strike, staffing is being rebuilt from junior-level positions.", style:'Reporting detail, tablet in hand.' },
      { speaker:'hiroshi_boss', jp:'海底洞窟調査の権利、政府はどう動いている。', en:"How is the government moving on rights for undersea cave surveys?", style:'Probing boss question.' },
      { speaker:'kenji_office', jp:'一部地域で許可申請が却下され、計画変更を余儀なくされた事業者もいます。', en:"In some regions permit applications were rejected, forcing operators to revise plans.", style:'Steady manager voice.' },
      { speaker:'hiroshi_boss', jp:'なるほど。次の経営会議でも、エネルギー戦略の議題に入れておこう。', en:"I see. We'll put energy strategy on the next executive meeting agenda.", style:'Decisive boss direction.' },
      { speaker:'kenji_office', jp:'承知しました。資料、明日朝までに整えます。', en:"Understood. I'll have the materials ready by tomorrow morning.", style:'Crisp closer.' },
    ],
  },
  {
    id: 'conv_05253', cluster: 'C', ambient: 'office_quiet_low',
    scenario: 'A police officer briefs a uni reporter about a labor dispute story',
    cast: ['takeda_officer','ren_uni'],
    targets: ['海水','ウラン','洞窟','引き上げる','余儀なく','転じ','ストライキ','初級'],
    lines: [
      { speaker:'takeda_officer', jp:'ストライキの件、どこまで取材されました?', en:"The strike — how far has your reporting gotten?", style:'Calm officer opener.' },
      { speaker:'ren_uni', jp:'港湾労働者が賃金を引き上げるよう求めて、二週間目に入っています。', en:"Port workers are demanding wage hikes; we're in the second week.", style:'Concise student-reporter brief.' },
      { speaker:'takeda_officer', jp:'港の倉庫には、ウラン関連の資材が一部置かれていたんです。', en:"Some uranium-related materials were stored in the port warehouses.", style:'Lowered confidential tone.' },
      { speaker:'ren_uni', jp:'その情報は初めて聞きました。それで操業中断は余儀なくされたんですね。', en:"That's new to me. So the operational halt was unavoidable.", style:'Surprised student, scribbling notes.' },
      { speaker:'takeda_officer', jp:'ええ。地下の洞窟調査も同時に止まっていて、研究者からも不満の声が出ています。', en:"Yes. Underground cave surveys halted at the same time, drawing complaints from researchers.", style:'Even officer delivery.' },
      { speaker:'ren_uni', jp:'風向きが転じたのは、政府の介入が入った時点でしょうか。', en:"Did the wind shift when the government intervened?", style:'Probing question.' },
      { speaker:'takeda_officer', jp:'その通り。今は対話の初級段階に戻って、丁寧に進めています。', en:"Exactly. Now we're back to the initial dialogue stage, proceeding carefully.", style:'Composed officer summary.' },
      { speaker:'ren_uni', jp:'海水のサンプル採取も、調査再開待ちですね。ありがとうございます。', en:"Seawater sampling is on hold too, then. Thank you for explaining.", style:'Grateful student close.' },
    ],
  },
  {
    id: 'conv_05254', cluster: 'C', ambient: 'living_room_quiet',
    scenario: 'A uni student interviews a retired explorer about deep-sea work',
    cast: ['hiroshi_elder','ren_uni'],
    targets: ['海水','ウラン','洞窟','引き上げる','余儀なく','転じ','ストライキ','初級'],
    lines: [
      { speaker:'ren_uni', jp:'若い頃の海底洞窟探検の話、伺ってもいいですか。', en:"May I hear about your undersea cave explorations from your younger days?", style:'Polite earnest student opener.' },
      { speaker:'hiroshi_elder', jp:'ああ、私は初級ダイバーから始めて、調査船で二十年勤めたよ。', en:"Sure. I started as a beginner diver and spent twenty years on survey vessels.", style:'Warm elder reminiscing, tea in hand.' },
      { speaker:'ren_uni', jp:'海水温の変動と、当時の調査の関係はありましたか。', en:"Was there a link between seawater temperature changes and your surveys back then?", style:'Curious follow-up.' },
      { speaker:'hiroshi_elder', jp:'大きく転じた時期があってね、計画変更を余儀なくされたこともあった。', en:"There was a time when it shifted dramatically, and we were forced to change plans.", style:'Reflective recall, slow pace.' },
      { speaker:'ren_uni', jp:'ウラン濃度の測定なども行ったんでしょうか。', en:"Did you also measure things like uranium concentration?", style:'Specific probe.' },
      { speaker:'hiroshi_elder', jp:'周辺海域では試料を引き上げる作業を何度もやった。骨が折れたよ。', en:"In nearby waters we hauled samples up many times. Backbreaking work.", style:'Chuckled veteran toughness.' },
      { speaker:'ren_uni', jp:'港湾労働者のストライキで作業が止まった経験は。', en:"Did you ever have work halted by port worker strikes?", style:'Sympathetic probe.' },
      { speaker:'hiroshi_elder', jp:'一度ある。あの時は本当に困った。互いの立場が分かり合えるよう、対話を続けたよ。', en:"Once. We were really stuck. We kept talking so both sides could understand each other's position.", style:'Quiet wisdom, gentle close.' },
    ],
  },
  {
    id: 'conv_05255', cluster: 'C', ambient: 'clinic_quiet',
    scenario: 'A doctor explains a marine-science health study to a teen',
    cast: ['saito_doctor','sakura_teen'],
    targets: ['海水','ウラン','洞窟','引き上げる','余儀なく','転じ','ストライキ','初級'],
    lines: [
      { speaker:'saito_doctor', jp:'桜さん、海水中の微量元素と健康に関する研究、興味深いでしょう。', en:"Sakura, the research on trace elements in seawater and health is intriguing, isn't it?", style:'Doctor friendly explainer tone.' },
      { speaker:'sakura_teen', jp:'はい！ウランも極微量に含まれてるってどういう仕組みなんですか。', en:"Yes! How does seawater end up holding even trace uranium?", style:'Curious teen voice, leaning forward.' },
      { speaker:'saito_doctor', jp:'地下洞窟を通って湧き出る水脈に少量含まれて、そこから海に流れ込むんです。', en:"Small amounts come through veins flowing from underground caves, then enter the sea.", style:'Patient educator pace.' },
      { speaker:'sakura_teen', jp:'それを生物が体内に引き上げると、どんな影響があるんでしょう。', en:"If organisms take it up into their bodies, what kind of impact does it have?", style:'Sharp follow-up.' },
      { speaker:'saito_doctor', jp:'通常は問題になりませんが、特定の条件下では別の物質に転じる可能性があります。', en:"Normally it's no issue, but under certain conditions it can shift into different compounds.", style:'Measured medical caution.' },
      { speaker:'sakura_teen', jp:'研究が止まった時期もあったって聞きました。', en:"I heard there were periods when the research stopped.", style:'Engaged teen prompt.' },
      { speaker:'saito_doctor', jp:'ストライキや予算の事情で、調査中断を余儀なくされた年もありました。', en:"Strikes and budget issues forced investigation pauses in some years.", style:'Steady factual delivery.' },
      { speaker:'sakura_teen', jp:'初級の本では絶対に出てこない話ですね、すごく勉強になりました。', en:"Definitely not the kind of stuff in beginner books. I learned a lot.", style:'Bright grateful close.' },
    ],
  },
  {
    id: 'conv_05256', cluster: 'D', ambient: 'street_quiet_distant',
    scenario: 'Two teens swap weekend resort ideas in the Kanto–Kansai mix',
    cast: ['sakura_teen','riku_teen'],
    targets: ['ネーミング','サプリメント','ハーフ','エンターテイメント','ロープ','枕','山梨','近畿'],
    lines: [
      { speaker:'sakura_teen', jp:'春休みどこ行く?私、山梨の温泉行きたいなって。', en:"Where are we going for spring break? I want to hit the Yamanashi hot springs.", style:'Bouncy teen pitch, walking pace.' },
      { speaker:'riku_teen', jp:'俺は近畿方面で考えてた。USJのエンターテイメントゾーン、すごいらしいぞ。', en:"I was thinking the Kinki area. USJ's entertainment zone is supposed to be wild.", style:'Casual teen counter-proposal.' },
      { speaker:'sakura_teen', jp:'ハーフタイムのアトラクション、絶対乗りたい！ロープウェイも気になる。', en:"I'd absolutely ride the halftime attraction! Ropeway too.", style:'Excited teen energy.' },
      { speaker:'riku_teen', jp:'山梨の宿、ネーミングが「夢の枕」だっけ。マジで枕の質にこだわるらしい。', en:"That Yamanashi inn — wasn't its name 'Dream Pillow'? They obsess over pillow quality.", style:'Half-laughing teen recall.' },
      { speaker:'sakura_teen', jp:'いいね。寝つきが悪いから、サプリメントも持ってこ。', en:"Nice. I sleep badly, so I'll bring supplements too.", style:'Practical teen planning.' },
      { speaker:'riku_teen', jp:'山梨だと、富士山が近くて、朝日見るのが定番だな。', en:"From Yamanashi, Fuji's close — sunrise viewing is a must.", style:'Knowing teen-boy tone.' },
      { speaker:'sakura_teen', jp:'じゃあ近畿は次回にして、今回は山梨にしよ。', en:"Then save Kinki for next time and lock in Yamanashi.", style:'Decisive teen close.' },
      { speaker:'riku_teen', jp:'了解。週末に詳細詰めようぜ。', en:"Got it. Let's nail down details this weekend.", style:'Easy teen sign-off.' },
    ],
  },
  {
    id: 'conv_05257', cluster: 'D', ambient: 'cafe_quiet_chatter',
    scenario: 'Two cafe friends compare a wellness-trip itinerary',
    cast: ['aoi_barista','mei_romantic'],
    targets: ['ネーミング','サプリメント','ハーフ','エンターテイメント','ロープ','枕','山梨','近畿'],
    lines: [
      { speaker:'aoi_barista', jp:'今度の旅行、山梨と近畿、どっちにする?', en:"For our next trip, Yamanashi or the Kinki region?", style:'Friendly barista opener.' },
      { speaker:'mei_romantic', jp:'私、山梨のぶどう園で癒されたい。ロープウェイで富士山も見たい。', en:"I want to unwind at a Yamanashi vineyard. And see Fuji from the ropeway.", style:'Soft dreamy preference.' },
      { speaker:'aoi_barista', jp:'いいね。宿、「眠りの枕」ってネーミングのとこ、口コミめっちゃいいよ。', en:"Good pick. The inn named 'Sleeping Pillow' has great reviews.", style:'Cheerful suggestion.' },
      { speaker:'mei_romantic', jp:'枕のオーダーメイドもあるらしい。サプリメントの試供品もくれるんだって。', en:"Apparently they offer custom pillows. And free supplement samples too.", style:'Excited girlfriend chat.' },
      { speaker:'aoi_barista', jp:'まずハーフコースの体験プランから始めようか。', en:"Let's start with the half-course experience plan.", style:'Practical suggestion.' },
      { speaker:'mei_romantic', jp:'賛成。近畿のエンターテイメントは派手すぎて、今は疲れちゃう。', en:"Agreed. Kinki entertainment is too flashy right now, it'd wear me out.", style:'Wistful preference.' },
      { speaker:'aoi_barista', jp:'じゃあ次は静かな山梨で確定ね。', en:"Okay, so quiet Yamanashi it is.", style:'Warm closer.' },
      { speaker:'mei_romantic', jp:'楽しみ。来週カレンダー合わせよ。', en:"Can't wait. Let's sync calendars next week.", style:'Soft happy sign-off.' },
    ],
  },
  {
    id: 'conv_05258', cluster: 'D', ambient: 'cafe_quiet_chatter',
    scenario: 'A uni student helps a teen friend plan a winter trip',
    cast: ['ren_uni','sakura_teen'],
    targets: ['ネーミング','サプリメント','ハーフ','エンターテイメント','ロープ','枕','山梨','近畿'],
    lines: [
      { speaker:'sakura_teen', jp:'先輩、卒業旅行、どこ行こうかなって悩んでます。', en:"Senpai, I'm stuck on where to go for the graduation trip.", style:'Hesitant teen seeking advice.' },
      { speaker:'ren_uni', jp:'山梨と近畿、両方候補に入れてみたら?', en:"How about both Yamanashi and Kinki on the shortlist?", style:'Calm older-brother suggestion.' },
      { speaker:'sakura_teen', jp:'山梨はロープウェイから富士山見たい！サプリメント持参で体調管理万全に。', en:"In Yamanashi I want Fuji from the ropeway! And I'll pack supplements to stay sharp.", style:'Bright excited teen.' },
      { speaker:'ren_uni', jp:'近畿は寺巡りと夜のエンターテイメント、両方楽しめる。', en:"Kinki gives you both temple-hopping and nighttime entertainment.", style:'Knowledgeable senpai voice.' },
      { speaker:'sakura_teen', jp:'宿のネーミング、最近凝ってるとこ多いですよね。', en:"Hotel names get really creative lately, don't they.", style:'Curious teen observation.' },
      { speaker:'ren_uni', jp:'「眠る前の十分間」とか、枕に特化したホテルが増えてる。', en:"Places like 'Ten Minutes Before Sleep' — pillow-focused hotels are on the rise.", style:'Amused mentor comment.' },
      { speaker:'sakura_teen', jp:'それすごい！ハーフ&ハーフで両方行くのは予算的に厳しいかな。', en:"That's wild! Doing half-and-half on both might be tight on budget though.", style:'Practical teen pause.' },
      { speaker:'ren_uni', jp:'じゃあ山梨を本命にして、近畿は日帰りで一回行こう。', en:"Then make Yamanashi the main, and do a day trip to Kinki once.", style:'Decisive friendly close.' },
    ],
  },
  {
    id: 'conv_05259', cluster: 'D', ambient: 'living_room_quiet',
    scenario: 'A married couple plans a wellness-and-fun weekend',
    cast: ['ryosuke_dad','yumiko_mom'],
    targets: ['ネーミング','サプリメント','ハーフ','エンターテイメント','ロープ','枕','山梨','近畿'],
    lines: [
      { speaker:'yumiko_mom', jp:'ねえ、来月の三連休、どこか行きたいな。', en:"Hey, for next month's three-day weekend, I want to go somewhere.", style:'Warm wife opener.' },
      { speaker:'ryosuke_dad', jp:'山梨の温泉宿はどうだ。最近、枕にこだわった宿が増えてるらしい。', en:"How about a Yamanashi hot-spring inn? Pillow-obsessed places are on the rise.", style:'Casual husband suggestion.' },
      { speaker:'yumiko_mom', jp:'いいね。サプリメント付きの宿泊プランもあるみたいだよ。', en:"Sounds good. Apparently some plans even include supplements.", style:'Brightening agreement.' },
      { speaker:'ryosuke_dad', jp:'ロープウェイで紅葉を見ながら、のんびり過ごそう。', en:"Let's relax with autumn leaves from the ropeway.", style:'Easy paternal warmth.' },
      { speaker:'yumiko_mom', jp:'近畿エリアも捨てがたいけど、エンターテイメントが多くて疲れちゃう。', en:"Kinki's tempting too, but it's so packed with entertainment it'd wear me out.", style:'Wistful wife voice.' },
      { speaker:'ryosuke_dad', jp:'山梨にして正解。宿のネーミング、なんだっけ。', en:"Yamanashi it is. What was that inn called again?", style:'Warm dad recall, scratching head.' },
      { speaker:'yumiko_mom', jp:'「月夜のハーフタイム」だったかな。子供たちは置いてって、二人で。', en:"I think 'Moonlit Halftime.' Let's leave the kids behind, just us.", style:'Conspiratorial wife giggle.' },
      { speaker:'ryosuke_dad', jp:'賛成。じゃあ来週予約入れとくよ。', en:"Agreed. I'll book it next week.", style:'Decisive husband close.' },
    ],
  },
  {
    id: 'conv_05260', cluster: 'D', ambient: 'cafe_quiet_chatter',
    scenario: 'A Kansai chef and a barista swap regional travel highlights',
    cast: ['daichi_kansai','aoi_barista'],
    targets: ['ネーミング','サプリメント','ハーフ','エンターテイメント','ロープ','枕','山梨','近畿'],
    lines: [
      { speaker:'daichi_kansai', jp:'アオイさん、関西の旅行、どこがおすすめなん?', en:"Aoi-san, what's the pick for a Kansai trip, eh?", style:'Friendly Kansai-dialect opener.' },
      { speaker:'aoi_barista', jp:'近畿エリアなら、奈良の鹿公園と、京都の寺院巡りがやっぱり定番です。', en:"For Kinki, Nara's deer park and Kyoto temple tours are still the classics.", style:'Warm barista answer.' },
      { speaker:'daichi_kansai', jp:'山梨にも行ったことある？富士山近くて、別格やで。', en:"Ever been to Yamanashi? Fuji's close, it's another level.", style:'Enthusiastic Kansai recommend.' },
      { speaker:'aoi_barista', jp:'ロープウェイから見る景色、本当に絶景でした。', en:"The view from the ropeway was truly stunning.", style:'Soft impressed recall.' },
      { speaker:'daichi_kansai', jp:'宿のネーミング、最近どんなんがウケてんの?', en:"What kind of hotel names are popular these days?", style:'Curious chef tone.' },
      { speaker:'aoi_barista', jp:'「枕の科学」みたいに、寝心地特化型が増えてます。サプリメント付きのプランも人気。', en:"Sleep-focused names like 'The Science of Pillows' are growing. Supplement plans are popular too.", style:'Knowledgeable cheerful info.' },
      { speaker:'daichi_kansai', jp:'ハーフサイズの夕食コースがある宿、忙しい人向けに流行ってるらしいわ。', en:"Inns with half-size dinner courses are trending for busy folks.", style:'Industry-insider Kansai update.' },
      { speaker:'aoi_barista', jp:'エンターテイメント重視より、静かに過ごす旅、最近ハマってます。', en:"I'm more into quiet trips lately than entertainment-heavy ones.", style:'Reflective barista close.' },
    ],
  },
]

let written = 0, stillMissing = []
for (const r of data) {
  const lines = r.lines
  const jpAll = lines.map(l => l.jp).join('\n')
  const missing = r.targets.filter(t => !jpAll.includes(t))
  if (missing.length > 0) stillMissing.push({ id: r.id, missing })
  const targetVocab = r.targets.filter(t => vocabSet.has(t))
  const conv = {
    id: r.id,
    context: r.scenario,
    purpose: 'Teach: ' + r.targets.join('/'),
    ambient: r.ambient,
    sound_effects: [],
    target_vocab: targetVocab,
    cast: r.cast,
    frequency_tier: 4,
    length_tier: lengthLabel(lines.length),
    meta: META,
    lines,
  }
  fs.writeFileSync(path.join(OUT_DIR, `${r.id}.json`), JSON.stringify(conv, null, 2) + '\n')
  written++
}
console.log('wrote', written)
if (stillMissing.length) console.log('STILL_MISSING', JSON.stringify(stillMissing, null, 2))
