// GENERATED by scripts/app_pipeline/gen_starter_module.mjs — do not edit.
// Starter pack: first conversations bundled into the app binary so the very
// first session works offline with zero setup.

export const STARTER_BUNDLES: Record<string, number> = {
  conv_00001: require('./conv_00001-bd0d7fbd.zip'),
  conv_00002: require('./conv_00002-b5c0a892.zip'),
  conv_00003: require('./conv_00003-928732c6.zip'),
  conv_00004: require('./conv_00004-bc543f10.zip'),
  conv_00005: require('./conv_00005-a34709ef.zip'),
  conv_00006: require('./conv_00006-33d59640.zip'),
  conv_00007: require('./conv_00007-563af3fe.zip'),
  conv_00008: require('./conv_00008-72e25564.zip'),
  conv_00009: require('./conv_00009-bcf53e1e.zip'),
  conv_00010: require('./conv_00010-fd4922d7.zip'),
  conv_00011: require('./conv_00011-ca3055d1.zip'),
  conv_00012: require('./conv_00012-14cf8670.zip'),
  conv_00013: require('./conv_00013-67390d9a.zip'),
  conv_00014: require('./conv_00014-25fd3267.zip'),
  conv_00015: require('./conv_00015-eb857d68.zip'),
  conv_00016: require('./conv_00016-06222837.zip'),
  conv_00017: require('./conv_00017-cdc78b59.zip'),
  conv_00018: require('./conv_00018-9a8ce3db.zip'),
  conv_00019: require('./conv_00019-90f6109d.zip'),
  conv_00020: require('./conv_00020-78babfe4.zip'),
}
